{
  "abstract": [
    {
      "text": "The paragraph or ruler attributes for an attributed string.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSParagraphStyle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSParagraphStyle"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSParagraphStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSParagraphStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSParagraphStyle"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object stores formatting information for a paragraph of text. The formatting information includes the amount of space between lines, indentations for lines of text, line heights, tab-stop positions, and more. Apply paragraph styles to the text of an attributed string by adding the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/1527910-paragraphstyle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " attribute and setting its value to an instance of this class. The text-rendering system uses the paragraph style information in an attributed string to lay out and render the text.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class manages an immutable set of style information, but you can create an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " when you want to modify the style information before applying it to your text.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode": {
      "abstract": [
        {
          "text": "Constants that specify what happens when a line is too long for a container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLineBreakMode"
        }
      ],
      "role": "symbol",
      "title": "NSLineBreakMode",
      "type": "topic",
      "url": "/documentation/appkit/nslinebreakmode"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle": {
      "abstract": [
        {
          "text": "An object for changing the values of the subattributes in a paragraph style attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMutableParagraphStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMutableParagraphStyle"
        }
      ],
      "role": "symbol",
      "title": "NSMutableParagraphStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsmutableparagraphstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle": {
      "abstract": [
        {
          "text": "The paragraph or ruler attributes for an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSParagraphStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSParagraphStyle"
        }
      ],
      "role": "symbol",
      "title": "NSParagraphStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/LineBreakStrategy-swift.struct": {
      "abstract": [
        {
          "text": "Constants that specify how the text system breaks lines while laying out paragraphs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LineBreakStrategy"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/LineBreakStrategy-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LineBreakStrategy"
        }
      ],
      "role": "symbol",
      "title": "NSParagraphStyle.LineBreakStrategy",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/linebreakstrategy-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType": {
      "abstract": [
        {
          "text": "Constants that specify the type of tab stop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TextTabType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TextTabType"
        }
      ],
      "role": "symbol",
      "title": "NSParagraphStyle.TextTabType",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/texttabtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/alignment": {
      "abstract": [
        {
          "text": "The text alignment of the paragraph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextAlignment",
          "text": "NSTextAlignment"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/alignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "alignment"
        }
      ],
      "role": "symbol",
      "title": "alignment",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/alignment"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/allowsDefaultTighteningForTruncation": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the system tightens character spacing before truncating text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsDefaultTighteningForTruncation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/allowsDefaultTighteningForTruncation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsDefaultTighteningForTruncation"
        }
      ],
      "role": "symbol",
      "title": "allowsDefaultTighteningForTruncation",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/allowsdefaulttighteningfortruncation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/baseWritingDirection": {
      "abstract": [
        {
          "text": "The base writing direction for the paragraph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "baseWritingDirection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWritingDirection",
          "text": "NSWritingDirection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/baseWritingDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "baseWritingDirection"
        }
      ],
      "role": "symbol",
      "title": "baseWritingDirection",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/basewritingdirection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/default": {
      "abstract": [
        {
          "text": "The default paragraph style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSParagraphStyle",
          "text": "NSParagraphStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultParagraphStyle"
        }
      ],
      "role": "symbol",
      "title": "default",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/default"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/defaultTabInterval": {
      "abstract": [
        {
          "text": "The documentwide default tab interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultTabInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/defaultTabInterval",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultTabInterval"
        }
      ],
      "role": "symbol",
      "title": "defaultTabInterval",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/defaulttabinterval"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/defaultWritingDirection(forLanguage:)": {
      "abstract": [
        {
          "text": "Returns the default writing direction for the specified language.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultWritingDirection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forLanguage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWritingDirection",
          "text": "NSWritingDirection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/defaultWritingDirection(forLanguage:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultWritingDirectionForLanguage:"
        }
      ],
      "role": "symbol",
      "title": "defaultWritingDirection(forLanguage:)",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/defaultwritingdirection(forlanguage:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/firstLineHeadIndent": {
      "abstract": [
        {
          "text": "The indentation of the first line of the paragraph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "firstLineHeadIndent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/firstLineHeadIndent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "firstLineHeadIndent"
        }
      ],
      "role": "symbol",
      "title": "firstLineHeadIndent",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/firstlineheadindent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/headIndent": {
      "abstract": [
        {
          "text": "The indentation of the paragraph’s lines other than the first.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headIndent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/headIndent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "headIndent"
        }
      ],
      "role": "symbol",
      "title": "headIndent",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/headindent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/headerLevel": {
      "abstract": [
        {
          "text": "The paragraph’s header level for HTML generation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headerLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/headerLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "headerLevel"
        }
      ],
      "role": "symbol",
      "title": "headerLevel",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/headerlevel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/hyphenationFactor": {
      "abstract": [
        {
          "text": "The paragraph’s threshold for hyphenation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hyphenationFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/hyphenationFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hyphenationFactor"
        }
      ],
      "role": "symbol",
      "title": "hyphenationFactor",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/hyphenationfactor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/lineBreakMode": {
      "abstract": [
        {
          "text": "The mode for breaking lines in the paragraph that don’t fit within a container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineBreakMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLineBreakMode",
          "text": "NSLineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/lineBreakMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineBreakMode"
        }
      ],
      "role": "symbol",
      "title": "lineBreakMode",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/linebreakmode"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/lineBreakStrategy-swift.property": {
      "abstract": [
        {
          "text": "The strategy for breaking lines while laying out paragraphs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineBreakStrategy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSParagraphStyle",
          "text": "NSParagraphStyle"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLineBreakStrategy",
          "text": "LineBreakStrategy"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/lineBreakStrategy-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineBreakStrategy"
        }
      ],
      "role": "symbol",
      "title": "lineBreakStrategy",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/linebreakstrategy-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/lineHeightMultiple": {
      "abstract": [
        {
          "text": "The line height multiple.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineHeightMultiple"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/lineHeightMultiple",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineHeightMultiple"
        }
      ],
      "role": "symbol",
      "title": "lineHeightMultiple",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/lineheightmultiple"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/lineSpacing": {
      "abstract": [
        {
          "text": "The distance in points between the bottom of one line fragment and the top of the next.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineSpacing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/lineSpacing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineSpacing"
        }
      ],
      "role": "symbol",
      "title": "lineSpacing",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/linespacing"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/maximumLineHeight": {
      "abstract": [
        {
          "text": "The paragraph’s maximum line height.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumLineHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/maximumLineHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumLineHeight"
        }
      ],
      "role": "symbol",
      "title": "maximumLineHeight",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/maximumlineheight"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/minimumLineHeight": {
      "abstract": [
        {
          "text": "The paragraph’s minimum line height.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumLineHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/minimumLineHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minimumLineHeight"
        }
      ],
      "role": "symbol",
      "title": "minimumLineHeight",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/minimumlineheight"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/paragraphSpacing": {
      "abstract": [
        {
          "text": "Distance between the bottom of this paragraph and top of next.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paragraphSpacing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/paragraphSpacing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paragraphSpacing"
        }
      ],
      "role": "symbol",
      "title": "paragraphSpacing",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/paragraphspacing"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/paragraphSpacingBefore": {
      "abstract": [
        {
          "text": "The distance between the paragraph’s top and the beginning of its text content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paragraphSpacingBefore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/paragraphSpacingBefore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paragraphSpacingBefore"
        }
      ],
      "role": "symbol",
      "title": "paragraphSpacingBefore",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/paragraphspacingbefore"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/tabStops": {
      "abstract": [
        {
          "text": "The text tab objects that represent the paragraph’s tab stops.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabStops"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextTab",
          "text": "NSTextTab"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/tabStops",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabStops"
        }
      ],
      "role": "symbol",
      "title": "tabStops",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/tabstops"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/tailIndent": {
      "abstract": [
        {
          "text": "The trailing indentation of the paragraph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tailIndent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/tailIndent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tailIndent"
        }
      ],
      "role": "symbol",
      "title": "tailIndent",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/tailindent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/textBlocks": {
      "abstract": [
        {
          "text": "The text blocks that contain the paragraph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textBlocks"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextBlock",
          "text": "NSTextBlock"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/textBlocks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textBlocks"
        }
      ],
      "role": "symbol",
      "title": "textBlocks",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/textblocks"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/textLists": {
      "abstract": [
        {
          "text": "The text lists that contain the paragraph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textLists"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextList",
          "text": "NSTextList"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/textLists",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textLists"
        }
      ],
      "role": "symbol",
      "title": "textLists",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/textlists"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/tighteningFactorForTruncation": {
      "abstract": [
        {
          "text": "The threshold for using tightening as an alternative to truncation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tighteningFactorForTruncation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/tighteningFactorForTruncation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tighteningFactorForTruncation"
        }
      ],
      "role": "symbol",
      "title": "tighteningFactorForTruncation",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/tighteningfactorfortruncation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/usesDefaultHyphenation": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the paragraph style uses the system hyphenation settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usesDefaultHyphenation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/usesDefaultHyphenation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "usesDefaultHyphenation"
        }
      ],
      "role": "symbol",
      "title": "usesDefaultHyphenation",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyle/usesdefaulthyphenation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment": {
      "abstract": [
        {
          "text": "Constants that specify text alignment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextAlignment"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextAlignment"
        }
      ],
      "role": "symbol",
      "title": "NSTextAlignment",
      "type": "topic",
      "url": "/documentation/appkit/nstextalignment"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextBlock": {
      "abstract": [
        {
          "text": "A block of text laid out in a subregion of the text container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextBlock"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextBlock"
        }
      ],
      "role": "symbol",
      "title": "NSTextBlock",
      "type": "topic",
      "url": "/documentation/appkit/nstextblock"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextList": {
      "abstract": [
        {
          "text": "A section of text that forms a single list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextList"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextList"
        }
      ],
      "role": "symbol",
      "title": "NSTextList",
      "type": "topic",
      "url": "/documentation/appkit/nstextlist"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextTab": {
      "abstract": [
        {
          "text": "A tab in a paragraph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextTab"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextTab",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextTab"
        }
      ],
      "role": "symbol",
      "title": "NSTextTab",
      "type": "topic",
      "url": "/documentation/appkit/nstexttab"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextTable": {
      "abstract": [
        {
          "text": "An object that represents a text table as a whole.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextTable"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextTable"
        }
      ],
      "role": "symbol",
      "title": "NSTextTable",
      "type": "topic",
      "url": "/documentation/appkit/nstexttable"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextTableBlock": {
      "abstract": [
        {
          "text": "A text block that appears as a cell in a text table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextTableBlock"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextTableBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextTableBlock"
        }
      ],
      "role": "symbol",
      "title": "NSTextTableBlock",
      "type": "topic",
      "url": "/documentation/appkit/nstexttableblock"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection": {
      "abstract": [
        {
          "text": "Constants that specify the writing direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWritingDirection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingDirection"
        }
      ],
      "role": "symbol",
      "title": "NSWritingDirection",
      "type": "topic",
      "url": "/documentation/appkit/nswritingdirection"
    },
    "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/1527910-paragraphstyle": {
      "abstract": [
        {
          "text": "The paragraph style of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "paragraphStyle"
        },
        {
          "kind": "text",
          "text": ": NSAttributedString.Key"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/1527910-paragraphstyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "paragraphStyle",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/key/1527910-paragraphstyle"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSMutableCopying": {
      "abstract": [
        {
          "text": "A protocol that mutable objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSMutableCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSMutableCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMutableCopying",
      "type": "topic",
      "url": "/documentation/foundation/nsmutablecopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSMutableCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Formatting-and-attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSTextTab",
        "doc://com.apple.appkit/documentation/AppKit/NSTextList",
        "doc://com.apple.appkit/documentation/AppKit/NSTextTable",
        "doc://com.apple.appkit/documentation/AppKit/NSTextTableBlock",
        "doc://com.apple.appkit/documentation/AppKit/NSTextBlock"
      ],
      "title": "Formatting and attributes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-paragraph-style",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/default"
      ],
      "title": "Creating a paragraph style"
    },
    {
      "anchor": "Accessing-style-information",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/alignment",
        "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/firstLineHeadIndent",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/headIndent",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/tailIndent",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/lineHeightMultiple",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/maximumLineHeight",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/minimumLineHeight",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/lineSpacing",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/paragraphSpacing",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/paragraphSpacingBefore"
      ],
      "title": "Accessing style information"
    },
    {
      "anchor": "Accessing-tab-information",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/tabStops",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/defaultTabInterval"
      ],
      "title": "Accessing tab information"
    },
    {
      "anchor": "Getting-text-block-and-list-information",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/textBlocks",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/textLists"
      ],
      "title": "Getting text block and list information"
    },
    {
      "anchor": "Getting-line-break-information",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/lineBreakMode",
        "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/lineBreakStrategy-swift.property",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/LineBreakStrategy-swift.struct",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/hyphenationFactor",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/usesDefaultHyphenation",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/tighteningFactorForTruncation",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/allowsDefaultTighteningForTruncation"
      ],
      "title": "Getting line-break information"
    },
    {
      "anchor": "Getting-the-html-header-level",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/headerLevel"
      ],
      "title": "Getting the html header level"
    },
    {
      "anchor": "Determining-writing-direction",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/defaultWritingDirection(forLanguage:)",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/baseWritingDirection",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection"
      ],
      "title": "Determining writing direction"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSParagraphStyle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSParagraphStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSParagraphStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-paragraph-style",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/default"
              ],
              "title": "Creating a paragraph style"
            },
            {
              "anchor": "Accessing-style-information",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/alignment",
                "doc://com.apple.appkit/documentation/AppKit/NSTextAlignment",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/firstLineHeadIndent",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/headIndent",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/tailIndent",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/lineHeightMultiple",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/maximumLineHeight",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/minimumLineHeight",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/lineSpacing",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/paragraphSpacing",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/paragraphSpacingBefore"
              ],
              "title": "Accessing style information"
            },
            {
              "anchor": "Accessing-tab-information",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/tabStops",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/TextTabType",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/defaultTabInterval"
              ],
              "title": "Accessing tab information"
            },
            {
              "anchor": "Getting-text-block-and-list-information",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/textBlocks",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/textLists"
              ],
              "title": "Getting text block and list information"
            },
            {
              "anchor": "Getting-line-break-information",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/lineBreakMode",
                "doc://com.apple.appkit/documentation/AppKit/NSLineBreakMode",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/lineBreakStrategy-swift.property",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/LineBreakStrategy-swift.struct",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/hyphenationFactor",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/usesDefaultHyphenation",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/tighteningFactorForTruncation",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/allowsDefaultTighteningForTruncation"
              ],
              "title": "Getting line-break information"
            },
            {
              "anchor": "Getting-the-html-header-level",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/headerLevel"
              ],
              "title": "Getting the html header level"
            },
            {
              "anchor": "Determining-writing-direction",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/defaultWritingDirection(forLanguage:)",
                "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyle/baseWritingDirection",
                "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection"
              ],
              "title": "Determining writing direction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSMutableCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Formatting-and-attributes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSMutableParagraphStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSTextTab",
                "doc://com.apple.appkit/documentation/AppKit/NSTextList",
                "doc://com.apple.appkit/documentation/AppKit/NSTextTable",
                "doc://com.apple.appkit/documentation/AppKit/NSTextTableBlock",
                "doc://com.apple.appkit/documentation/AppKit/NSTextBlock"
              ],
              "title": "Formatting and attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSParagraphStyle"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTableBlock/title",
          "value": "NSTextTableBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTableBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextTableBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTableBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextTableBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1defaultWritingDirection(forLanguage:)/title",
          "value": "defaultWritingDirectionForLanguage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1defaultWritingDirection(forLanguage:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "defaultWritingDirectionForLanguage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1allowsDefaultTighteningForTruncation/title",
          "value": "allowsDefaultTighteningForTruncation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1allowsDefaultTighteningForTruncation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsDefaultTighteningForTruncation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTable/title",
          "value": "NSTextTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1headerLevel/title",
          "value": "headerLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1headerLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "headerLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1headIndent/title",
          "value": "headIndent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1headIndent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "headIndent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1tighteningFactorForTruncation/title",
          "value": "tighteningFactorForTruncation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1tighteningFactorForTruncation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tighteningFactorForTruncation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextBlock/title",
          "value": "NSTextBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1minimumLineHeight/title",
          "value": "minimumLineHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1minimumLineHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minimumLineHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1paragraphSpacingBefore/title",
          "value": "paragraphSpacingBefore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1paragraphSpacingBefore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "paragraphSpacingBefore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirection/title",
          "value": "NSWritingDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1textLists/title",
          "value": "textLists"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1textLists/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "textLists"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1tabStops/title",
          "value": "tabStops"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1tabStops/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tabStops"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLineBreakMode/title",
          "value": "NSLineBreakMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLineBreakMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineBreakMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLineBreakMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineBreakMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1baseWritingDirection/title",
          "value": "baseWritingDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1baseWritingDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "baseWritingDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1firstLineHeadIndent/title",
          "value": "firstLineHeadIndent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1firstLineHeadIndent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "firstLineHeadIndent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1lineSpacing/title",
          "value": "lineSpacing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1lineSpacing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineSpacing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTab/title",
          "value": "NSTextTab"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTab/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextTab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextTab/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextTab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1hyphenationFactor/title",
          "value": "hyphenationFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1hyphenationFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hyphenationFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1tailIndent/title",
          "value": "tailIndent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1tailIndent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tailIndent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1lineHeightMultiple/title",
          "value": "lineHeightMultiple"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1lineHeightMultiple/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineHeightMultiple"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1usesDefaultHyphenation/title",
          "value": "usesDefaultHyphenation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1usesDefaultHyphenation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "usesDefaultHyphenation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlignment/title",
          "value": "NSTextAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlignment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle/title",
          "value": "NSParagraphStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSParagraphStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSParagraphStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1maximumLineHeight/title",
          "value": "maximumLineHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1maximumLineHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumLineHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1lineBreakMode/title",
          "value": "lineBreakMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1lineBreakMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineBreakMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1lineBreakStrategy-swift.property/title",
          "value": "lineBreakStrategy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1lineBreakStrategy-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineBreakStrategy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle/title",
          "value": "NSMutableParagraphStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMutableParagraphStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMutableParagraphStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMutableParagraphStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1textBlocks/title",
          "value": "textBlocks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1textBlocks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "textBlocks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1alignment/title",
          "value": "alignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1alignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "alignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1TextTabType/title",
          "value": "NSTextTabType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1TextTabType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextTabType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1TextTabType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextTabType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextList/title",
          "value": "NSTextList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextList/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1defaultTabInterval/title",
          "value": "defaultTabInterval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1defaultTabInterval/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultTabInterval"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1paragraphSpacing/title",
          "value": "paragraphSpacing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1paragraphSpacing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "paragraphSpacing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1LineBreakStrategy-swift.struct/title",
          "value": "NSLineBreakStrategy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1LineBreakStrategy-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineBreakStrategy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1LineBreakStrategy-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineBreakStrategy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1default/title",
          "value": "defaultParagraphStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSParagraphStyle~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultParagraphStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsparagraphstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsparagraphstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
