{
  "abstract": [
    {
      "text": "A panel that queries the user for information such as paper type and orientation.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSPageLayout",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSPageLayout"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSPageLayout"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSPageLayout"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSPageLayout"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A page layout panel is typically displayed in response to the user selecting the Page Setup menu item. You obtain an instance with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/pageLayout",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class method. The pane can then be run as a sheet using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/beginSheet(with:modalFor:delegate:didEnd:contextInfo:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or modally using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/runModal()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/runModal(with:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For design guidance, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/design/human-interface-guidelines/macos/system-capabilities/printing#page-setup-dialogs",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageLayout": {
      "abstract": [
        {
          "text": "A panel that queries the user for information such as paper type and orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPageLayout"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPageLayout"
        }
      ],
      "role": "symbol",
      "title": "NSPageLayout",
      "type": "topic",
      "url": "/documentation/appkit/nspagelayout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/Result": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Result"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/Result",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Result"
        }
      ],
      "role": "symbol",
      "title": "NSPageLayout.Result",
      "type": "topic",
      "url": "/documentation/appkit/nspagelayout/result"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/accessoryControllers": {
      "abstract": [
        {
          "text": "An array of accessory view controllers belonging to the page layout panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessoryControllers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSViewController",
          "text": "NSViewController"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/accessoryControllers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessoryControllers"
        }
      ],
      "role": "symbol",
      "title": "accessoryControllers",
      "type": "topic",
      "url": "/documentation/appkit/nspagelayout/accessorycontrollers"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/accessoryView": {
      "abstract": [
        {
          "text": "Returns the page layout panel’s accessory view.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "accessoryView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/accessoryView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessoryView"
        }
      ],
      "role": "symbol",
      "title": "accessoryView",
      "type": "topic",
      "url": "/documentation/appkit/nspagelayout/accessoryview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/addAccessoryController(_:)": {
      "abstract": [
        {
          "text": "Adds the specified controller of an accessory view to be presented in the page setup panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addAccessoryController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSViewController",
          "text": "NSViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/addAccessoryController(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addAccessoryController:"
        }
      ],
      "role": "symbol",
      "title": "addAccessoryController(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nspagelayout/addaccessorycontroller(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/beginSheet(using:on:completionHandler:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginSheet"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "on"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPageLayout",
          "text": "NSPageLayout"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPageLayoutResult",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/beginSheet(using:on:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginSheetUsingPrintInfo:onWindow:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "beginSheet(using:on:completionHandler:)",
      "type": "topic",
      "url": "/documentation/appkit/nspagelayout/beginsheet(using:on:completionhandler:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/beginSheet(with:modalFor:delegate:didEnd:contextInfo:)": {
      "abstract": [
        {
          "text": "Presents a page setup sheet for the specified print info object, document-modal relative to the specified window.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginSheet"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "modalFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "didEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "contextInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/beginSheet(with:modalFor:delegate:didEnd:contextInfo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginSheetWithPrintInfo:modalForWindow:delegate:didEndSelector:contextInfo:"
        }
      ],
      "role": "symbol",
      "title": "beginSheet(with:modalFor:delegate:didEnd:contextInfo:)",
      "type": "topic",
      "url": "/documentation/appkit/nspagelayout/beginsheet(with:modalfor:delegate:didend:contextinfo:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/pageLayout": {
      "abstract": [
        {
          "text": "Returns a newly created page layout object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "pageLayout"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/pageLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pageLayout"
        }
      ],
      "role": "symbol",
      "title": "pageLayout",
      "type": "topic",
      "url": "/documentation/appkit/nspagelayout/pagelayout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/printInfo": {
      "abstract": [
        {
          "text": "The printing information object used when the page layout panel is run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/printInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printInfo"
        }
      ],
      "role": "symbol",
      "title": "printInfo",
      "type": "topic",
      "url": "/documentation/appkit/nspagelayout/printinfo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/readPrintInfo": {
      "abstract": [
        {
          "text": "Sets the page layout’s values to those stored in the print info object used when the page layout panel is run.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "readPrintInfo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/readPrintInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readPrintInfo"
        }
      ],
      "role": "symbol",
      "title": "readPrintInfo",
      "type": "topic",
      "url": "/documentation/appkit/nspagelayout/readprintinfo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/removeAccessoryController(_:)": {
      "abstract": [
        {
          "text": "Removes the specified controller of an accessory view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAccessoryController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSViewController",
          "text": "NSViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/removeAccessoryController(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAccessoryController:"
        }
      ],
      "role": "symbol",
      "title": "removeAccessoryController(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nspagelayout/removeaccessorycontroller(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/runModal()": {
      "abstract": [
        {
          "text": "Displays the page layout panel and begins the modal loop using the shared print info object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "runModal"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/runModal()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runModal"
        }
      ],
      "role": "symbol",
      "title": "runModal()",
      "type": "topic",
      "url": "/documentation/appkit/nspagelayout/runmodal()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/runModal(with:)": {
      "abstract": [
        {
          "text": "Displays the page layout panel and begins the modal loop using the specified print info object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "runModal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/runModal(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runModalWithPrintInfo:"
        }
      ],
      "role": "symbol",
      "title": "runModal(with:)",
      "type": "topic",
      "url": "/documentation/appkit/nspagelayout/runmodal(with:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/setAccessoryView:": {
      "abstract": [
        {
          "text": "Adds a view object to the page layout panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setAccessoryView:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/setAccessoryView:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setAccessoryView:"
        }
      ],
      "role": "symbol",
      "title": "setAccessoryView:",
      "type": "topic",
      "url": "/documentation/appkit/nspagelayout/setaccessoryview:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/writePrintInfo": {
      "abstract": [
        {
          "text": "Writes the page layout’s values to the print info object used when the page layout panel is run.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "writePrintInfo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/writePrintInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writePrintInfo"
        }
      ],
      "role": "symbol",
      "title": "writePrintInfo",
      "type": "topic",
      "url": "/documentation/appkit/nspagelayout/writeprintinfo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo": {
      "abstract": [
        {
          "text": "An object that stores information that’s used to generate printed output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrintInfo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintInfo"
        }
      ],
      "role": "symbol",
      "title": "NSPrintInfo",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel": {
      "abstract": [
        {
          "text": "The Print panel that queries the user for information about a print job.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrintPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPanel"
        }
      ],
      "role": "symbol",
      "title": "NSPrintPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "https://developer.apple.com/design/human-interface-guidelines/macos/system-capabilities/printing#page-setup-dialogs": {
      "identifier": "https://developer.apple.com/design/human-interface-guidelines/macos/system-capabilities/printing#page-setup-dialogs",
      "title": "Human Interface Guidelines",
      "titleInlineContent": [
        {
          "text": "Human Interface Guidelines",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/design/human-interface-guidelines/macos/system-capabilities/printing#page-setup-dialogs"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Print-Panels",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel"
      ],
      "title": "Print Panels"
    }
  ],
  "topicSections": [
    {
      "anchor": "Running-the-page-setup-dialog",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/beginSheet(using:on:completionHandler:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/beginSheet(with:modalFor:delegate:didEnd:contextInfo:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/runModal()",
        "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/runModal(with:)"
      ],
      "title": "Running the page setup dialog"
    },
    {
      "anchor": "Customizing-the-page-setup-dialog",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/addAccessoryController(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/removeAccessoryController(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/accessoryControllers"
      ],
      "title": "Customizing the page setup dialog"
    },
    {
      "anchor": "Accessing-the-printing-information",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/printInfo",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo",
        "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/Result"
      ],
      "title": "Accessing the printing information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPageLayout"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPageLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPageLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-the-page-layout-object",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/pageLayout"
              ],
              "title": "Creating the page layout object"
            },
            {
              "anchor": "Running-the-page-setup-dialog",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/beginSheet(using:on:completionHandler:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/beginSheet(with:modalFor:delegate:didEnd:contextInfo:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/runModal()",
                "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/runModal(with:)"
              ],
              "title": "Running the page setup dialog"
            },
            {
              "anchor": "Customizing-the-page-setup-dialog",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/addAccessoryController(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/removeAccessoryController(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/accessoryControllers"
              ],
              "title": "Customizing the page setup dialog"
            },
            {
              "anchor": "Accessing-the-printing-information",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/printInfo",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo",
                "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/Result"
              ],
              "title": "Accessing the printing information"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/accessoryView",
                "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/setAccessoryView:",
                "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/readPrintInfo",
                "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/writePrintInfo"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Print-Panels",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel"
              ],
              "title": "Print Panels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSPageLayout"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo/title",
          "value": "NSPrintInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout~1accessoryControllers/title",
          "value": "accessoryControllers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout~1accessoryControllers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "accessoryControllers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout~1beginSheet(with:modalFor:delegate:didEnd:contextInfo:)/title",
          "value": "beginSheetWithPrintInfo:modalForWindow:delegate:didEndSelector:contextInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout~1beginSheet(with:modalFor:delegate:didEnd:contextInfo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginSheetWithPrintInfo:modalForWindow:delegate:didEndSelector:contextInfo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout~1printInfo/title",
          "value": "printInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout~1printInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "printInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel/title",
          "value": "NSPrintPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout/title",
          "value": "NSPageLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPageLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPageLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout~1removeAccessoryController(_:)/title",
          "value": "removeAccessoryController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout~1removeAccessoryController(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeAccessoryController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout~1runModal(with:)/title",
          "value": "runModalWithPrintInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout~1runModal(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runModalWithPrintInfo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout~1Result/title",
          "value": "NSPageLayoutResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout~1Result/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPageLayoutResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout~1Result/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPageLayoutResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout~1addAccessoryController(_:)/title",
          "value": "addAccessoryController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout~1addAccessoryController(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addAccessoryController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout~1runModal()/title",
          "value": "runModal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout~1runModal()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runModal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout~1beginSheet(using:on:completionHandler:)/title",
          "value": "beginSheetUsingPrintInfo:onWindow:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout~1beginSheet(using:on:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginSheetUsingPrintInfo:onWindow:completionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nspagelayout"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nspagelayout"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
