{
  "abstract": [
    {
      "text": "The ",
      "type": "text"
    },
    {
      "code": "NSPageControllerDelegate",
      "type": "codeVoice"
    },
    {
      "text": " protocol allows you to customize the behavior of instances of the NSPageController class.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSPageControllerDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSPageControllerDelegate"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSPageControllerDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NSPageControllerDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSPageControllerDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If your page controller is going to completely manage the page snapshots, then you should not implement the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageController(_:viewControllerForIdentifier:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageController(_:prepare:with:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " methods.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "However, if you manually set the ",
                  "type": "text"
                },
                {
                  "code": "NSPageController",
                  "type": "codeVoice"
                },
                {
                  "text": " instance’s ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageController/arrangedObjects",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property, you are required to implement the following those methods so that navigation can properly occur.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageController": {
      "abstract": [
        {
          "text": "An object that controls swipe navigation and animations between views or view content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPageController"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPageController"
        }
      ],
      "role": "symbol",
      "title": "NSPageController",
      "type": "topic",
      "url": "/documentation/appkit/nspagecontroller"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageController/ObjectIdentifier": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ObjectIdentifier"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageController/ObjectIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ObjectIdentifier"
        }
      ],
      "role": "symbol",
      "title": "NSPageController.ObjectIdentifier",
      "type": "topic",
      "url": "/documentation/appkit/nspagecontroller/objectidentifier"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageController/arrangedObjects": {
      "abstract": [
        {
          "text": "An array containing the objects displayed in the page controller’s view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arrangedObjects"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageController/arrangedObjects",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "arrangedObjects"
        }
      ],
      "role": "symbol",
      "title": "arrangedObjects",
      "type": "topic",
      "url": "/documentation/appkit/nspagecontroller/arrangedobjects"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageController/delegate": {
      "abstract": [
        {
          "text": "The page controller’s delegate object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSPageControllerDelegate",
          "text": "NSPageControllerDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageController/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/appkit/nspagecontroller/delegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "NSPageControllerDelegate",
          "type": "codeVoice"
        },
        {
          "text": " protocol allows you to customize the behavior of instances of the NSPageController class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPageControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPageControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSPageControllerDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nspagecontrollerdelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageController(_:didTransitionTo:)": {
      "abstract": [
        {
          "text": "This message is sent when any page transition is completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPageController",
          "text": "NSPageController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didTransitionTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageController(_:didTransitionTo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pageController:didTransitionToObject:"
        }
      ],
      "role": "symbol",
      "title": "pageController(_:didTransitionTo:)",
      "type": "topic",
      "url": "/documentation/appkit/nspagecontrollerdelegate/pagecontroller(_:didtransitionto:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageController(_:frameFor:)": {
      "abstract": [
        {
          "text": "Returns the frame appropriate for displaying the specified object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPageController",
          "text": "NSPageController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "frameFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageController(_:frameFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pageController:frameForObject:"
        }
      ],
      "role": "symbol",
      "title": "pageController(_:frameFor:)",
      "type": "topic",
      "url": "/documentation/appkit/nspagecontrollerdelegate/pagecontroller(_:framefor:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageController(_:identifierFor:)": {
      "abstract": [
        {
          "text": "Return the identifier of the view controller that owns a view to display the object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPageController",
          "text": "NSPageController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "identifierFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPageController",
          "text": "NSPageController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPageControllerObjectIdentifier",
          "text": "ObjectIdentifier"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageController(_:identifierFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pageController:identifierForObject:"
        }
      ],
      "role": "symbol",
      "title": "pageController(_:identifierFor:)",
      "type": "topic",
      "url": "/documentation/appkit/nspagecontrollerdelegate/pagecontroller(_:identifierfor:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageController(_:prepare:with:)": {
      "abstract": [
        {
          "text": "Prepare the view controller and it’s view for drawing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPageController",
          "text": "NSPageController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "prepare"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSViewController",
          "text": "NSViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageController(_:prepare:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pageController:prepareViewController:withObject:"
        }
      ],
      "role": "symbol",
      "title": "pageController(_:prepare:with:)",
      "type": "topic",
      "url": "/documentation/appkit/nspagecontrollerdelegate/pagecontroller(_:prepare:with:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageController(_:viewControllerForIdentifier:)": {
      "abstract": [
        {
          "text": "Returns a view controller the page controller uses for managing the specified identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPageController",
          "text": "NSPageController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "viewControllerForIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPageController",
          "text": "NSPageController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPageControllerObjectIdentifier",
          "text": "ObjectIdentifier"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSViewController",
          "text": "NSViewController"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageController(_:viewControllerForIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pageController:viewControllerForIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "pageController(_:viewControllerForIdentifier:)",
      "type": "topic",
      "url": "/documentation/appkit/nspagecontrollerdelegate/pagecontroller(_:viewcontrollerforidentifier:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageControllerDidEndLiveTransition(_:)": {
      "abstract": [
        {
          "text": "This message is sent when a transition animation completes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageControllerDidEndLiveTransition"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPageController",
          "text": "NSPageController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageControllerDidEndLiveTransition(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pageControllerDidEndLiveTransition:"
        }
      ],
      "role": "symbol",
      "title": "pageControllerDidEndLiveTransition(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nspagecontrollerdelegate/pagecontrollerdidendlivetransition(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageControllerWillStartLiveTransition(_:)": {
      "abstract": [
        {
          "text": "This message is sent when the user begins a transition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageControllerWillStartLiveTransition"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPageController",
          "text": "NSPageController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageControllerWillStartLiveTransition(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pageControllerWillStartLiveTransition:"
        }
      ],
      "role": "symbol",
      "title": "pageControllerWillStartLiveTransition(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nspagecontrollerdelegate/pagecontrollerwillstartlivetransition(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Customizing-the-Paged-Interface-Behavior",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPageController/delegate"
      ],
      "title": "Customizing the Paged Interface Behavior"
    }
  ],
  "topicSections": [
    {
      "anchor": "Transition-Notification",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageControllerWillStartLiveTransition(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageControllerDidEndLiveTransition(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageController(_:didTransitionTo:)"
      ],
      "title": "Transition Notification"
    },
    {
      "anchor": "Managing-View-Controllers",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageController(_:identifierFor:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageController(_:viewControllerForIdentifier:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageController(_:prepare:with:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageController(_:frameFor:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPageController/ObjectIdentifier"
      ],
      "title": "Managing View Controllers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPageControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPageControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPageControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Transition-Notification",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageControllerWillStartLiveTransition(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageControllerDidEndLiveTransition(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageController(_:didTransitionTo:)"
              ],
              "title": "Transition Notification"
            },
            {
              "anchor": "Managing-View-Controllers",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageController(_:identifierFor:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageController(_:viewControllerForIdentifier:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageController(_:prepare:with:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPageControllerDelegate/pageController(_:frameFor:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPageController/ObjectIdentifier"
              ],
              "title": "Managing View Controllers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Customizing-the-Paged-Interface-Behavior",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPageController/delegate"
              ],
              "title": "Customizing the Paged Interface Behavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSPageControllerDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageControllerDelegate/title",
          "value": "NSPageControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPageControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPageControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageController~1ObjectIdentifier/title",
          "value": "NSPageControllerObjectIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageController~1ObjectIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPageControllerObjectIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageController~1ObjectIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPageControllerObjectIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageControllerDelegate~1pageController(_:frameFor:)/title",
          "value": "pageController:frameForObject:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageControllerDelegate~1pageController(_:frameFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pageController:frameForObject:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageController~1arrangedObjects/title",
          "value": "arrangedObjects"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageController~1arrangedObjects/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "arrangedObjects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageControllerDelegate~1pageController(_:identifierFor:)/title",
          "value": "pageController:identifierForObject:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageControllerDelegate~1pageController(_:identifierFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pageController:identifierForObject:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageControllerDelegate~1pageController(_:didTransitionTo:)/title",
          "value": "pageController:didTransitionToObject:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageControllerDelegate~1pageController(_:didTransitionTo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pageController:didTransitionToObject:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageControllerDelegate~1pageController(_:prepare:with:)/title",
          "value": "pageController:prepareViewController:withObject:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageControllerDelegate~1pageController(_:prepare:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pageController:prepareViewController:withObject:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageControllerDelegate~1pageController(_:viewControllerForIdentifier:)/title",
          "value": "pageController:viewControllerForIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageControllerDelegate~1pageController(_:viewControllerForIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pageController:viewControllerForIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageController~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageController~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageControllerDelegate~1pageControllerWillStartLiveTransition(_:)/title",
          "value": "pageControllerWillStartLiveTransition:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageControllerDelegate~1pageControllerWillStartLiveTransition(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pageControllerWillStartLiveTransition:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageControllerDelegate~1pageControllerDidEndLiveTransition(_:)/title",
          "value": "pageControllerDidEndLiveTransition:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageControllerDelegate~1pageControllerDidEndLiveTransition(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pageControllerDidEndLiveTransition:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageController/title",
          "value": "NSPageController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPageController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPageController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nspagecontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nspagecontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
