{
  "abstract": [
    {
      "text": "PDF data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSPDFPboardType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSPDFPboardType",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSPDFPboardType"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSPDFPboardType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSPDFPboardType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSPasteboardType",
              "text": "NSPasteboardType"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSPDFPboardType"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In macOS 10.6 and later, use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/pdf",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorPboardType": {
      "abstract": [
        {
          "code": "NSColor",
          "type": "codeVoice"
        },
        {
          "text": " data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSColorPboardType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorPboardType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSColorPboardType",
      "type": "topic",
      "url": "/documentation/appkit/nscolorpboardtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFilenamesPboardType": {
      "abstract": [
        {
          "text": "An array of ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": " objects designating one or more filenames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFilenamesPboardType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFilenamesPboardType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFilenamesPboardType",
      "type": "topic",
      "url": "/documentation/appkit/nsfilenamespboardtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontPboardType": {
      "abstract": [
        {
          "text": "Font and character information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFontPboardType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPboardType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFontPboardType",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpboardtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHTMLPboardType": {
      "abstract": [
        {
          "text": "HTML (which an ",
          "type": "text"
        },
        {
          "code": "NSTextView",
          "type": "codeVoice"
        },
        {
          "text": " object can read from, but not write to).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSHTMLPboardType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHTMLPboardType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSHTMLPboardType",
      "type": "topic",
      "url": "/documentation/appkit/nshtmlpboardtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMultipleTextSelectionPboardType": {
      "abstract": [
        {
          "text": "Multiple text selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMultipleTextSelectionPboardType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMultipleTextSelectionPboardType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMultipleTextSelectionPboardType",
      "type": "topic",
      "url": "/documentation/appkit/nsmultipletextselectionpboardtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPDFPboardType": {
      "abstract": [
        {
          "text": "PDF data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPDFPboardType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPDFPboardType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPDFPboardType",
      "type": "topic",
      "url": "/documentation/appkit/nspdfpboardtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPICTPboardType": {
      "abstract": [
        {
          "text": "QuickDraw picture data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPICTPboardType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPICTPboardType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPICTPboardType",
      "type": "topic",
      "url": "/documentation/appkit/nspictpboardtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType": {
      "abstract": [
        {
          "text": "The supported pasteboard types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PasteboardType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PasteboardType"
        }
      ],
      "role": "symbol",
      "title": "NSPasteboard.PasteboardType",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/pasteboardtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/fileContentsType(forPathExtension:)": {
      "abstract": [
        {
          "text": "Returns a pasteboard type based on the passed file type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileContentsType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forPathExtension"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardType",
          "text": "PasteboardType"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/fileContentsType(forPathExtension:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCreateFileContentsPboardType"
        }
      ],
      "role": "symbol",
      "title": "fileContentsType(forPathExtension:)",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/pasteboardtype/filecontentstype(forpathextension:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/fileNameType(forPathExtension:)": {
      "abstract": [
        {
          "text": "Returns a pasteboard type based on the passed file type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileNameType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forPathExtension"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardType",
          "text": "PasteboardType"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/fileNameType(forPathExtension:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCreateFilenamePboardType"
        }
      ],
      "role": "symbol",
      "title": "fileNameType(forPathExtension:)",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/pasteboardtype/filenametype(forpathextension:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/filePromise": {
      "abstract": [
        {
          "text": "Promised files.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "filePromise"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardType",
          "text": "PasteboardType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/filePromise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFilesPromisePboardType"
        }
      ],
      "role": "symbol",
      "title": "filePromise",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/pasteboardtype/filepromise"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/inkText": {
      "abstract": [
        {
          "text": "Ink text data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inkText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardType",
          "text": "PasteboardType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/inkText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSInkTextPboardType"
        }
      ],
      "role": "symbol",
      "title": "inkText",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/pasteboardtype/inktext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/pdf": {
      "abstract": [
        {
          "text": "PDF data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pdf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardType",
          "text": "PasteboardType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/pdf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPasteboardTypePDF"
        }
      ],
      "role": "symbol",
      "title": "pdf",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/pasteboardtype/pdf"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/postScript": {
      "abstract": [
        {
          "text": "Encapsulated PostScript (EPS) code.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postScript"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardType",
          "text": "PasteboardType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/postScript",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPostScriptPboardType"
        }
      ],
      "role": "symbol",
      "title": "postScript",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/pasteboardtype/postscript"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/representedPathExtension": {
      "abstract": [
        {
          "text": "A file type based on the passed pasteboard type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "representedPathExtension"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/representedPathExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGetFileType"
        }
      ],
      "role": "symbol",
      "title": "representedPathExtension",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/pasteboardtype/representedpathextension"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/representedPathExtensions(from:)": {
      "abstract": [
        {
          "text": "Returns an array of file types based on the passed pasteboard types.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "representedPathExtensions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardType",
          "text": "PasteboardType"
        },
        {
          "kind": "text",
          "text": "]) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/representedPathExtensions(from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGetFileTypes"
        }
      ],
      "role": "symbol",
      "title": "representedPathExtensions(from:)",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/pasteboardtype/representedpathextensions(from:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/vCard": {
      "abstract": [
        {
          "text": "VCard data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vCard"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardType",
          "text": "PasteboardType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/vCard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVCardPboardType"
        }
      ],
      "role": "symbol",
      "title": "vCard",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/pasteboardtype/vcard"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRTFDPboardType": {
      "abstract": [
        {
          "text": "RTFD formatted file contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRTFDPboardType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRTFDPboardType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRTFDPboardType",
      "type": "topic",
      "url": "/documentation/appkit/nsrtfdpboardtype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/filePromise",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/inkText",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/postScript",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/vCard",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/representedPathExtension",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/fileContentsType(forPathExtension:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/fileNameType(forPathExtension:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType/representedPathExtensions(from:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColorPboardType",
        "doc://com.apple.appkit/documentation/AppKit/NSFilenamesPboardType",
        "doc://com.apple.appkit/documentation/AppKit/NSFontPboardType",
        "doc://com.apple.appkit/documentation/AppKit/NSHTMLPboardType",
        "doc://com.apple.appkit/documentation/AppKit/NSMultipleTextSelectionPboardType",
        "doc://com.apple.appkit/documentation/AppKit/NSPICTPboardType",
        "doc://com.apple.appkit/documentation/AppKit/NSRTFDPboardType"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType/title",
          "value": "NSPasteboardType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1filePromise/title",
          "value": "NSFilesPromisePboardType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1filePromise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFilesPromisePboardType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1pdf/title",
          "value": "NSPasteboardTypePDF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1pdf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardTypePDF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1representedPathExtension/title",
          "value": "NSGetFileType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1representedPathExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGetFileType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1fileContentsType(forPathExtension:)/title",
          "value": "NSCreateFileContentsPboardType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1fileContentsType(forPathExtension:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCreateFileContentsPboardType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1fileNameType(forPathExtension:)/title",
          "value": "NSCreateFilenamePboardType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1fileNameType(forPathExtension:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCreateFilenamePboardType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1representedPathExtensions(from:)/title",
          "value": "NSGetFileTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1representedPathExtensions(from:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGetFileTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1postScript/title",
          "value": "NSPostScriptPboardType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1postScript/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPostScriptPboardType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1inkText/title",
          "value": "NSInkTextPboardType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1inkText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInkTextPboardType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1vCard/title",
          "value": "NSVCardPboardType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType~1vCard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVCardPboardType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nspdfpboardtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
