{
  "abstract": [
    {
      "text": "The pen tip is activated.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSPenTipMask"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSPenTipMask",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSPenTipMask"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSPenTipMask"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.12",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSPenTipMask"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/ButtonMask-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSEventButtonMask",
              "text": "NSEventButtonMask"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSPenTipMask"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/ButtonMask-swift.struct": {
      "abstract": [
        {
          "text": "Constants you use to identify the activated tablet buttons in an event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ButtonMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/ButtonMask-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ButtonMask"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.ButtonMask",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/buttonmask-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPenLowerSideMask": {
      "abstract": [
        {
          "text": "The button on the lower side of the device is activated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPenLowerSideMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPenLowerSideMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPenLowerSideMask",
      "type": "topic",
      "url": "/documentation/appkit/nspenlowersidemask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPenTipMask": {
      "abstract": [
        {
          "text": "The pen tip is activated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPenTipMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPenTipMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPenTipMask",
      "type": "topic",
      "url": "/documentation/appkit/nspentipmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPenUpperSideMask": {
      "abstract": [
        {
          "text": "The button on the upper side of the device is activated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPenUpperSideMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPenUpperSideMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPenUpperSideMask",
      "type": "topic",
      "url": "/documentation/appkit/nspenuppersidemask"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPenLowerSideMask",
        "doc://com.apple.appkit/documentation/AppKit/NSPenUpperSideMask"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1ButtonMask-swift.struct/title",
          "value": "NSEventButtonMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1ButtonMask-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventButtonMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1ButtonMask-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventButtonMask"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nspentipmask"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
