{
  "abstract": [
    {
      "text": "A set of methods that an object can implement to register default placeholders to be displayed for a binding, when no other placeholder is specified.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/cocoa-bindings"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/nsplaceholders"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "title": "NSPlaceholders"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Individual placeholder values can be specified for each of the marker objects (described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/selection-markers",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "), as well as when the property is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Placeholders are used when a property of an instance of the receiving class is accessed through a key value coding compliant method, and returns ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " or a specialized marker.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBindingSelectionMarker": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBindingSelectionMarker"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBindingSelectionMarker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBindingSelectionMarker"
        }
      ],
      "role": "symbol",
      "title": "NSBindingSelectionMarker",
      "type": "topic",
      "url": "/documentation/appkit/nsbindingselectionmarker"
    },
    "doc://com.apple.appkit/documentation/AppKit/cocoa-bindings": {
      "abstract": [
        {
          "text": "Automatically synchronize your data model with your app’s interface using Cocoa Bindings.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/cocoa-bindings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cocoa Bindings",
      "type": "topic",
      "url": "/documentation/appkit/cocoa-bindings"
    },
    "doc://com.apple.appkit/documentation/AppKit/selection-markers": {
      "abstract": [
        {
          "text": "The following constants are used to describe special cases for a controller’s selection.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/selection-markers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Selection Markers",
      "type": "topic",
      "url": "/documentation/appkit/selection-markers"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1458194-setdefaultplaceholder": {
      "abstract": [
        {
          "text": "Sets `placeholder` as the default placeholder for the `binding`, when a key value coding compliant property of an instance of the receiving class returns the value specified by `marker`, and no other placeholder has been specified.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "class func "
        },
        {
          "kind": "identifier",
          "text": "setDefaultPlaceholder"
        },
        {
          "kind": "text",
          "text": "(Any?, "
        },
        {
          "kind": "identifier",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": Any?, "
        },
        {
          "kind": "identifier",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": NSBindingName)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1458194-setdefaultplaceholder",
      "kind": "symbol",
      "role": "symbol",
      "title": "setDefaultPlaceholder(_:for:with:)",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1458194-setdefaultplaceholder"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1458203-defaultplaceholder": {
      "abstract": [
        {
          "text": "Returns an object that will be used as the placeholder for the `binding`, when a key value coding compliant property of an instance of the receiving class returns the value specified by `marker`, and no other placeholder has been specified. ",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "class func "
        },
        {
          "kind": "identifier",
          "text": "defaultPlaceholder"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": Any?, "
        },
        {
          "kind": "identifier",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": NSBindingName) -> Any?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1458203-defaultplaceholder",
      "kind": "symbol",
      "role": "symbol",
      "title": "defaultPlaceholder(for:with:)",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1458203-defaultplaceholder"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Placeholders",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBindingSelectionMarker"
      ],
      "title": "Data Placeholders"
    }
  ],
  "topicSections": [
    {
      "anchor": "Managing-default-placeholders",
      "identifiers": [
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1458194-setdefaultplaceholder",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1458203-defaultplaceholder"
      ],
      "title": "Managing default placeholders"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/selection-markers"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Managing-default-placeholders",
              "identifiers": [
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1458194-setdefaultplaceholder",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1458203-defaultplaceholder"
              ],
              "title": "Managing default placeholders"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/selection-markers"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Placeholders",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSBindingSelectionMarker"
              ],
              "title": "Data Placeholders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobject~11458194-setdefaultplaceholder/title",
          "value": "setDefaultPlaceholder:forMarker:withBinding:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobject~11458203-defaultplaceholder/title",
          "value": "defaultPlaceholderForMarker:withBinding:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingSelectionMarker/title",
          "value": "NSBindingSelectionMarker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingSelectionMarker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBindingSelectionMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBindingSelectionMarker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBindingSelectionMarker"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsplaceholders"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsplaceholders"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
