{
  "abstract": [
    {
      "text": "A set of optional methods that a popover delegate can implement to provide additional or custom functionality.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSPopoverDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSPopoverDelegate"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSPopoverDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NSPopoverDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSPopoverDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPopover",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more information on popovers in general.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPopover": {
      "abstract": [
        {
          "text": "A means to display additional content related to existing content on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPopover"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPopover",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPopover"
        }
      ],
      "role": "symbol",
      "title": "NSPopover",
      "type": "topic",
      "url": "/documentation/appkit/nspopover"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate": {
      "abstract": [
        {
          "text": "A set of optional methods that a popover delegate can implement to provide additional or custom functionality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPopoverDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPopoverDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSPopoverDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nspopoverdelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/detachableWindow(for:)": {
      "abstract": [
        {
          "text": "Detaches the popover creating a window containing the content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "detachableWindow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPopover",
          "text": "NSPopover"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/detachableWindow(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "detachableWindowForPopover:"
        }
      ],
      "role": "symbol",
      "title": "detachableWindow(for:)",
      "type": "topic",
      "url": "/documentation/appkit/nspopoverdelegate/detachablewindow(for:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/popoverDidClose(_:)": {
      "abstract": [
        {
          "text": "Invoked when the popover did close.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popoverDidClose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/popoverDidClose(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "popoverDidClose:"
        }
      ],
      "role": "symbol",
      "title": "popoverDidClose(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nspopoverdelegate/popoverdidclose(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/popoverDidDetach(_:)": {
      "abstract": [
        {
          "text": "Indicates that a popover has been released while it’s in an implicitly detached state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popoverDidDetach"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPopover",
          "text": "NSPopover"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/popoverDidDetach(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "popoverDidDetach:"
        }
      ],
      "role": "symbol",
      "title": "popoverDidDetach(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nspopoverdelegate/popoverdiddetach(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/popoverDidShow(_:)": {
      "abstract": [
        {
          "text": "Invoked when the popover has been shown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popoverDidShow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/popoverDidShow(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "popoverDidShow:"
        }
      ],
      "role": "symbol",
      "title": "popoverDidShow(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nspopoverdelegate/popoverdidshow(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/popoverShouldClose(_:)": {
      "abstract": [
        {
          "text": "Allows a delegate to override a close request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popoverShouldClose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPopover",
          "text": "NSPopover"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/popoverShouldClose(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "popoverShouldClose:"
        }
      ],
      "role": "symbol",
      "title": "popoverShouldClose(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nspopoverdelegate/popovershouldclose(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/popoverShouldDetach(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a popover should detach from its positioning view and become a separate window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popoverShouldDetach"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPopover",
          "text": "NSPopover"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/popoverShouldDetach(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "popoverShouldDetach:"
        }
      ],
      "role": "symbol",
      "title": "popoverShouldDetach(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nspopoverdelegate/popovershoulddetach(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/popoverWillClose(_:)": {
      "abstract": [
        {
          "text": "Invoked when the popover is about to close.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popoverWillClose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/popoverWillClose(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "popoverWillClose:"
        }
      ],
      "role": "symbol",
      "title": "popoverWillClose(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nspopoverdelegate/popoverwillclose(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/popoverWillShow(_:)": {
      "abstract": [
        {
          "text": "Invoked when the popover will show.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popoverWillShow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/popoverWillShow(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "popoverWillShow:"
        }
      ],
      "role": "symbol",
      "title": "popoverWillShow(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nspopoverdelegate/popoverwillshow(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Popovers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPopover"
      ],
      "title": "Popovers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Popover-Window",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/detachableWindow(for:)"
      ],
      "title": "Popover Window"
    },
    {
      "anchor": "Popover-Visibility",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/popoverShouldClose(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/popoverWillShow(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/popoverDidShow(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/popoverWillClose(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/popoverDidClose(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/popoverDidDetach(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/popoverShouldDetach(_:)"
      ],
      "title": "Popover Visibility"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPopoverDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPopoverDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPopoverDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Popover-Window",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/detachableWindow(for:)"
              ],
              "title": "Popover Window"
            },
            {
              "anchor": "Popover-Visibility",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/popoverShouldClose(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/popoverWillShow(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/popoverDidShow(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/popoverWillClose(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/popoverDidClose(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/popoverDidDetach(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPopoverDelegate/popoverShouldDetach(_:)"
              ],
              "title": "Popover Visibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Popovers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPopover"
              ],
              "title": "Popovers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSPopoverDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopoverDelegate~1popoverWillClose(_:)/title",
          "value": "popoverWillClose:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopoverDelegate~1popoverWillClose(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "popoverWillClose:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopoverDelegate~1detachableWindow(for:)/title",
          "value": "detachableWindowForPopover:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopoverDelegate~1detachableWindow(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "detachableWindowForPopover:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopoverDelegate~1popoverDidDetach(_:)/title",
          "value": "popoverDidDetach:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopoverDelegate~1popoverDidDetach(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "popoverDidDetach:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopoverDelegate~1popoverDidClose(_:)/title",
          "value": "popoverDidClose:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopoverDelegate~1popoverDidClose(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "popoverDidClose:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopover/title",
          "value": "NSPopover"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopover/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPopover"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopover/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPopover"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopoverDelegate~1popoverWillShow(_:)/title",
          "value": "popoverWillShow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopoverDelegate~1popoverWillShow(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "popoverWillShow:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopoverDelegate~1popoverDidShow(_:)/title",
          "value": "popoverDidShow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopoverDelegate~1popoverDidShow(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "popoverDidShow:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopoverDelegate~1popoverShouldClose(_:)/title",
          "value": "popoverShouldClose:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopoverDelegate~1popoverShouldClose(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "popoverShouldClose:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopoverDelegate~1popoverShouldDetach(_:)/title",
          "value": "popoverShouldDetach:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopoverDelegate~1popoverShouldDetach(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "popoverShouldDetach:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopoverDelegate/title",
          "value": "NSPopoverDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopoverDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPopoverDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopoverDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPopoverDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nspopoverdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nspopoverdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
