{
  "abstract": [
    {
      "text": "A small circular indicator that can be determinate or indeterminate.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicator/Style-swift.enum/spinning",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicatorSpinningStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSProgressIndicatorSpinningStyle",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSProgressIndicatorSpinningStyle"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSProgressIndicatorSpinningStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSProgressIndicatorSpinningStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicator/Style-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSProgressIndicatorStyle",
              "text": "NSProgressIndicatorStyle"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSProgressIndicatorSpinningStyle"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The appearance of a determinate spinning style indicator is similar to an animated pie chart.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicator/Style-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify the progress indicator’s style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Style"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicator/Style-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Style"
        }
      ],
      "role": "symbol",
      "title": "NSProgressIndicator.Style",
      "type": "topic",
      "url": "/documentation/appkit/nsprogressindicator/style-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicator/Style-swift.enum/spinning": {
      "abstract": [
        {
          "text": "A small circular indicator that can be determinate or indeterminate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spinning"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicator/Style-swift.enum/spinning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSProgressIndicatorStyleSpinning"
        }
      ],
      "role": "symbol",
      "title": "NSProgressIndicator.Style.spinning",
      "type": "topic",
      "url": "/documentation/appkit/nsprogressindicator/style-swift.enum/spinning"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicatorBarStyle": {
      "abstract": [
        {
          "text": "A rectangular indicator that can be determinate or indeterminate.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSProgressIndicatorBarStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicatorBarStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSProgressIndicatorBarStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsprogressindicatorbarstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicatorSpinningStyle": {
      "abstract": [
        {
          "text": "A small circular indicator that can be determinate or indeterminate.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSProgressIndicatorSpinningStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicatorSpinningStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSProgressIndicatorSpinningStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsprogressindicatorspinningstyle"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicatorBarStyle"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSProgressIndicator~1Style-swift.enum/title",
          "value": "NSProgressIndicatorStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSProgressIndicator~1Style-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSProgressIndicatorStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSProgressIndicator~1Style-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSProgressIndicatorStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSProgressIndicator~1Style-swift.enum~1spinning/title",
          "value": "NSProgressIndicatorStyleSpinning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSProgressIndicator~1Style-swift.enum~1spinning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSProgressIndicatorStyleSpinning"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsprogressindicatorspinningstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
