{
  "abstract": [
    {
      "text": "Deprecated. Do not use.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/printing",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo",
        "doc://com.apple.appkit/documentation/AppKit/deprecated-printing-keys"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/printing",
        "doc://com.apple.appkit/documentation/AppKit/NSPageLayout",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo",
        "doc://com.apple.appkit/documentation/AppKit/deprecated-printing-keys"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/printing",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo",
        "doc://com.apple.appkit/documentation/AppKit/deprecated-printing-keys"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/printing",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo",
        "doc://com.apple.appkit/documentation/AppKit/deprecated-printing-keys"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/nsprintfaxjob"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "NSPrintFaxJob"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageLayout": {
      "abstract": [
        {
          "text": "A panel that queries the user for information such as paper type and orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPageLayout"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPageLayout"
        }
      ],
      "role": "symbol",
      "title": "NSPageLayout",
      "type": "topic",
      "url": "/documentation/appkit/nspagelayout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintFormName": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPrintFormName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintFormName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPrintFormName",
      "type": "topic",
      "url": "/documentation/appkit/nsprintformname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo": {
      "abstract": [
        {
          "text": "An object that stores information that’s used to generate printed output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrintInfo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintInfo"
        }
      ],
      "role": "symbol",
      "title": "NSPrintInfo",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintJobFeatures": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPrintJobFeatures"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintJobFeatures",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPrintJobFeatures",
      "type": "topic",
      "url": "/documentation/appkit/nsprintjobfeatures"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintManualFeed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPrintManualFeed"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintManualFeed",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPrintManualFeed",
      "type": "topic",
      "url": "/documentation/appkit/nsprintmanualfeed"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation": {
      "abstract": [
        {
          "text": "An object that controls operations that generate Encapsulated PostScript (EPS) code, Portable Document Format (PDF) code, or print jobs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrintOperation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintOperation"
        }
      ],
      "role": "symbol",
      "title": "NSPrintOperation",
      "type": "topic",
      "url": "/documentation/appkit/nsprintoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPagesPerSheet": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPrintPagesPerSheet"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPagesPerSheet",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPrintPagesPerSheet",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpagespersheet"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel": {
      "abstract": [
        {
          "text": "The Print panel that queries the user for information about a print job.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrintPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPanel"
        }
      ],
      "role": "symbol",
      "title": "NSPrintPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPaperFeed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPrintPaperFeed"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPaperFeed",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPrintPaperFeed",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpaperfeed"
    },
    "doc://com.apple.appkit/documentation/AppKit/deprecated-printing-keys": {
      "abstract": [
        {
          "text": "These keys refer to older printing properties that are no longer used.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/deprecated-printing-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Printing Keys",
      "type": "topic",
      "url": "/documentation/appkit/deprecated-printing-keys"
    },
    "doc://com.apple.appkit/documentation/AppKit/nsprintfaxcoversheetname": {
      "abstract": [
        {
          "text": "Deprecated. Do not use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nsprintfaxcoversheetname",
      "kind": "article",
      "role": "article",
      "title": "NSPrintFaxCoverSheetName",
      "type": "topic",
      "url": "/documentation/appkit/nsprintfaxcoversheetname"
    },
    "doc://com.apple.appkit/documentation/AppKit/nsprintfaxhighresolution": {
      "abstract": [
        {
          "text": "Deprecated. Do not use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nsprintfaxhighresolution",
      "kind": "article",
      "role": "article",
      "title": "NSPrintFaxHighResolution",
      "type": "topic",
      "url": "/documentation/appkit/nsprintfaxhighresolution"
    },
    "doc://com.apple.appkit/documentation/AppKit/nsprintfaxmodem": {
      "abstract": [
        {
          "text": "Deprecated. Do not use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nsprintfaxmodem",
      "kind": "article",
      "role": "article",
      "title": "NSPrintFaxModem",
      "type": "topic",
      "url": "/documentation/appkit/nsprintfaxmodem"
    },
    "doc://com.apple.appkit/documentation/AppKit/nsprintfaxreceivernames": {
      "abstract": [
        {
          "text": "Deprecated. Do not use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nsprintfaxreceivernames",
      "kind": "article",
      "role": "article",
      "title": "NSPrintFaxReceiverNames",
      "type": "topic",
      "url": "/documentation/appkit/nsprintfaxreceivernames"
    },
    "doc://com.apple.appkit/documentation/AppKit/nsprintfaxreceivernumbers": {
      "abstract": [
        {
          "text": "Deprecated. Do not use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nsprintfaxreceivernumbers",
      "kind": "article",
      "role": "article",
      "title": "NSPrintFaxReceiverNumbers",
      "type": "topic",
      "url": "/documentation/appkit/nsprintfaxreceivernumbers"
    },
    "doc://com.apple.appkit/documentation/AppKit/nsprintfaxreturnreceipt": {
      "abstract": [
        {
          "text": "Deprecated. Do not use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nsprintfaxreturnreceipt",
      "kind": "article",
      "role": "article",
      "title": "NSPrintFaxReturnReceipt",
      "type": "topic",
      "url": "/documentation/appkit/nsprintfaxreturnreceipt"
    },
    "doc://com.apple.appkit/documentation/AppKit/nsprintfaxsendtime": {
      "abstract": [
        {
          "text": "Deprecated. Do not use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nsprintfaxsendtime",
      "kind": "article",
      "role": "article",
      "title": "NSPrintFaxSendTime",
      "type": "topic",
      "url": "/documentation/appkit/nsprintfaxsendtime"
    },
    "doc://com.apple.appkit/documentation/AppKit/nsprintfaxtrimpageends": {
      "abstract": [
        {
          "text": "Deprecated. Do not use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nsprintfaxtrimpageends",
      "kind": "article",
      "role": "article",
      "title": "NSPrintFaxTrimPageEnds",
      "type": "topic",
      "url": "/documentation/appkit/nsprintfaxtrimpageends"
    },
    "doc://com.apple.appkit/documentation/AppKit/nsprintfaxusecoversheet": {
      "abstract": [
        {
          "text": "Deprecated. Do not use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nsprintfaxusecoversheet",
      "kind": "article",
      "role": "article",
      "title": "NSPrintFaxUseCoverSheet",
      "type": "topic",
      "url": "/documentation/appkit/nsprintfaxusecoversheet"
    },
    "doc://com.apple.appkit/documentation/AppKit/printing": {
      "abstract": [
        {
          "text": "Display the system print panels and manage the printing process.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/printing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Printing",
      "type": "topic",
      "url": "/documentation/appkit/printing"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/nsprintfaxreceivernames",
        "doc://com.apple.appkit/documentation/AppKit/nsprintfaxreceivernumbers",
        "doc://com.apple.appkit/documentation/AppKit/nsprintfaxsendtime",
        "doc://com.apple.appkit/documentation/AppKit/nsprintfaxusecoversheet",
        "doc://com.apple.appkit/documentation/AppKit/nsprintfaxcoversheetname",
        "doc://com.apple.appkit/documentation/AppKit/nsprintfaxreturnreceipt",
        "doc://com.apple.appkit/documentation/AppKit/nsprintfaxhighresolution",
        "doc://com.apple.appkit/documentation/AppKit/nsprintfaxtrimpageends",
        "doc://com.apple.appkit/documentation/AppKit/nsprintfaxmodem"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPrintFormName",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintJobFeatures",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintManualFeed",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPagesPerSheet",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPaperFeed",
                "doc://com.apple.appkit/documentation/AppKit/nsprintfaxreceivernames",
                "doc://com.apple.appkit/documentation/AppKit/nsprintfaxreceivernumbers",
                "doc://com.apple.appkit/documentation/AppKit/nsprintfaxsendtime",
                "doc://com.apple.appkit/documentation/AppKit/nsprintfaxusecoversheet",
                "doc://com.apple.appkit/documentation/AppKit/nsprintfaxcoversheetname",
                "doc://com.apple.appkit/documentation/AppKit/nsprintfaxreturnreceipt",
                "doc://com.apple.appkit/documentation/AppKit/nsprintfaxhighresolution",
                "doc://com.apple.appkit/documentation/AppKit/nsprintfaxtrimpageends",
                "doc://com.apple.appkit/documentation/AppKit/nsprintfaxmodem"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintOperation/title",
          "value": "NSPrintOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel/title",
          "value": "NSPrintPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo/title",
          "value": "NSPrintInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout/title",
          "value": "NSPageLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPageLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPageLayout"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsprintfaxjob"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsprintfaxjob"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
