{
  "abstract": [
    {
      "text": "An object that describes a printer’s capabilities.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSPrinter"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSPrinter",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSPrinter"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSPrinter"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSPrinter"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSPrinter"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " provides information about a printer; it does not modify printer attributes or control a printing job. A printer object can be constructed by specifying either the printer name or the make and model of an available printer. Typically, Cocoa apps don’t create ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects; instead, the printing system uses these objects to support the printing jobs and when it shows users a list of printers.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo": {
      "abstract": [
        {
          "text": "An object that stores information that’s used to generate printed output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrintInfo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintInfo"
        }
      ],
      "role": "symbol",
      "title": "NSPrintInfo",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation": {
      "abstract": [
        {
          "text": "An object that controls operations that generate Encapsulated PostScript (EPS) code, Portable Document Format (PDF) code, or print jobs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrintOperation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintOperation"
        }
      ],
      "role": "symbol",
      "title": "NSPrintOperation",
      "type": "topic",
      "url": "/documentation/appkit/nsprintoperation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter": {
      "abstract": [
        {
          "text": "An object that describes a printer’s capabilities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrinter"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrinter"
        }
      ],
      "role": "symbol",
      "title": "NSPrinter",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/PaperName": {
      "abstract": [
        {
          "text": "The type you use to specify the name of a type of paper.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PaperName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/PaperName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PaperName"
        }
      ],
      "role": "symbol",
      "title": "NSPrinter.PaperName",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/papername"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TableStatus": {
      "abstract": [
        {
          "text": "Constants that describe the state of a printer information table stored by a printer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TableStatus"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TableStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TableStatus"
        }
      ],
      "role": "symbol",
      "title": "NSPrinter.TableStatus",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/tablestatus"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TypeName": {
      "abstract": [
        {
          "text": "The type you use to describe a printer’s make and model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TypeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TypeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TypeName"
        }
      ],
      "role": "symbol",
      "title": "NSPrinter.TypeName",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/typename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/acceptsBinary": {
      "abstract": [
        {
          "text": "Deprecated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "acceptsBinary"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/acceptsBinary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "acceptsBinary"
        }
      ],
      "role": "symbol",
      "title": "acceptsBinary",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/acceptsbinary"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/booleanForKey:inTable:": {
      "abstract": [
        {
          "text": "Returns the Boolean value associated with the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "booleanForKey:inTable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/booleanForKey:inTable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "booleanForKey:inTable:"
        }
      ],
      "role": "symbol",
      "title": "booleanForKey:inTable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/booleanforkey:intable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/deviceDescription": {
      "abstract": [
        {
          "text": "A dictionary of keys and values that describe the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceDescription"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSDeviceDescriptionKey",
          "text": "NSDeviceDescriptionKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/deviceDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceDescription"
        }
      ],
      "role": "symbol",
      "title": "deviceDescription",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/devicedescription"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/domain": {
      "abstract": [
        {
          "text": "Deprecated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "domain"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/domain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "domain"
        }
      ],
      "role": "symbol",
      "title": "domain",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/domain"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/floatForKey:inTable:": {
      "abstract": [
        {
          "text": "Returns the floating-point value associated with the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "floatForKey:inTable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/floatForKey:inTable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "floatForKey:inTable:"
        }
      ],
      "role": "symbol",
      "title": "floatForKey:inTable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/floatforkey:intable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/host": {
      "abstract": [
        {
          "text": "Deprecated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "host"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/host",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "host"
        }
      ],
      "role": "symbol",
      "title": "host",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/host"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/imageRectForPaper:": {
      "abstract": [
        {
          "text": "Deprecated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "imageRectForPaper:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/imageRectForPaper:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageRectForPaper:"
        }
      ],
      "role": "symbol",
      "title": "imageRectForPaper:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/imagerectforpaper:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/init(name:)": {
      "abstract": [
        {
          "text": "Creates and returns a printer object initialized with the specified printer name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/init(name:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printerWithName:"
        }
      ],
      "role": "symbol",
      "title": "init(name:)",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/init(name:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/init(type:)": {
      "abstract": [
        {
          "text": "Creates and returns a printer object initialized to the first available printer with the specified make and model information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrinter",
          "text": "NSPrinter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrinterTypeName",
          "text": "TypeName"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/init(type:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printerWithType:"
        }
      ],
      "role": "symbol",
      "title": "init(type:)",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/init(type:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/intForKey:inTable:": {
      "abstract": [
        {
          "text": "Returns the integer value associated with the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "intForKey:inTable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/intForKey:inTable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "intForKey:inTable:"
        }
      ],
      "role": "symbol",
      "title": "intForKey:inTable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/intforkey:intable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/isColor": {
      "abstract": [
        {
          "text": "Deprecated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "isColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/isColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isColor"
        }
      ],
      "role": "symbol",
      "title": "isColor",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/iscolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/isFontAvailable:": {
      "abstract": [
        {
          "text": "Deprecated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "isFontAvailable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/isFontAvailable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isFontAvailable:"
        }
      ],
      "role": "symbol",
      "title": "isFontAvailable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/isfontavailable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/isKey:inTable:": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the specified key is in the specified table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "isKey:inTable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/isKey:inTable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isKey:inTable:"
        }
      ],
      "role": "symbol",
      "title": "isKey:inTable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/iskey:intable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/isOutputStackInReverseOrder": {
      "abstract": [
        {
          "text": "Deprecated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "isOutputStackInReverseOrder"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/isOutputStackInReverseOrder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isOutputStackInReverseOrder"
        }
      ],
      "role": "symbol",
      "title": "isOutputStackInReverseOrder",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/isoutputstackinreverseorder"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/languageLevel": {
      "abstract": [
        {
          "text": "The PostScript language level recognized by the printer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "languageLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/languageLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "languageLevel"
        }
      ],
      "role": "symbol",
      "title": "languageLevel",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/languagelevel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/name": {
      "abstract": [
        {
          "text": "The printer’s name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/name"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/note": {
      "abstract": [
        {
          "text": "Deprecated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "note"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/note",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "note"
        }
      ],
      "role": "symbol",
      "title": "note",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/note"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/pageSize(forPaper:)": {
      "abstract": [
        {
          "text": "Returns the size of the page for the specified paper type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forPaper"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrinter",
          "text": "NSPrinter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrinterPaperName",
          "text": "PaperName"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/pageSize(forPaper:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pageSizeForPaper:"
        }
      ],
      "role": "symbol",
      "title": "pageSize(forPaper:)",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/pagesize(forpaper:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/printerNames": {
      "abstract": [
        {
          "text": "Returns the names of all available printers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printerNames"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/printerNames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printerNames"
        }
      ],
      "role": "symbol",
      "title": "printerNames",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/printernames"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/printerTypes": {
      "abstract": [
        {
          "text": "Returns descriptions of the makes and models of all available printers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printerTypes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrinter",
          "text": "NSPrinter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrinterTypeName",
          "text": "TypeName"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/printerTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printerTypes"
        }
      ],
      "role": "symbol",
      "title": "printerTypes",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/printertypes"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/printerWithName:domain:includeUnavailable:": {
      "abstract": [
        {
          "text": "Deprecated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "printerWithName:domain:includeUnavailable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/printerWithName:domain:includeUnavailable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printerWithName:domain:includeUnavailable:"
        }
      ],
      "role": "symbol",
      "title": "printerWithName:domain:includeUnavailable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/printerwithname:domain:includeunavailable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/rectForKey:inTable:": {
      "abstract": [
        {
          "text": "Returns the rectangle associated with the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "rectForKey:inTable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/rectForKey:inTable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rectForKey:inTable:"
        }
      ],
      "role": "symbol",
      "title": "rectForKey:inTable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/rectforkey:intable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/sizeForKey:inTable:": {
      "abstract": [
        {
          "text": "Returns the size data type associated with the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "sizeForKey:inTable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/sizeForKey:inTable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sizeForKey:inTable:"
        }
      ],
      "role": "symbol",
      "title": "sizeForKey:inTable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/sizeforkey:intable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/statusForTable:": {
      "abstract": [
        {
          "text": "Returns the status of the specified table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "statusForTable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/statusForTable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "statusForTable:"
        }
      ],
      "role": "symbol",
      "title": "statusForTable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/statusfortable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/stringForKey:inTable:": {
      "abstract": [
        {
          "text": "Returns the first occurrence of a value associated with specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "stringForKey:inTable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/stringForKey:inTable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stringForKey:inTable:"
        }
      ],
      "role": "symbol",
      "title": "stringForKey:inTable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/stringforkey:intable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/stringListForKey:inTable:": {
      "abstract": [
        {
          "text": "Returns an array of strings, one for each occurrence, associated with specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "stringListForKey:inTable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/stringListForKey:inTable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stringListForKey:inTable:"
        }
      ],
      "role": "symbol",
      "title": "stringListForKey:inTable:",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/stringlistforkey:intable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrinter/type": {
      "abstract": [
        {
          "text": "A description of the printer’s make and model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrinter",
          "text": "NSPrinter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrinterTypeName",
          "text": "TypeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrinter/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/appkit/nsprinter/type"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Print-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation"
      ],
      "title": "Print Information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-the-Printer-Object",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/init(name:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/init(type:)"
      ],
      "title": "Creating the Printer Object"
    },
    {
      "anchor": "Getting-General-Printer-Information",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/printerNames",
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/printerTypes",
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TypeName"
      ],
      "title": "Getting General Printer Information"
    },
    {
      "anchor": "Getting-Attributes",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/name",
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/type"
      ],
      "title": "Getting Attributes"
    },
    {
      "anchor": "Getting-Page-and-Printer-Information",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/pageSize(forPaper:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/PaperName",
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/languageLevel"
      ],
      "title": "Getting Page and Printer Information"
    },
    {
      "anchor": "Querying-Tables",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/deviceDescription"
      ],
      "title": "Querying Tables"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TableStatus"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPrinter"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrinter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrinter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-the-Printer-Object",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/init(name:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/init(type:)"
              ],
              "title": "Creating the Printer Object"
            },
            {
              "anchor": "Getting-General-Printer-Information",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/printerNames",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/printerTypes",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TypeName"
              ],
              "title": "Getting General Printer Information"
            },
            {
              "anchor": "Getting-Attributes",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/name",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/type"
              ],
              "title": "Getting Attributes"
            },
            {
              "anchor": "Getting-Page-and-Printer-Information",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/pageSize(forPaper:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/PaperName",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/languageLevel"
              ],
              "title": "Getting Page and Printer Information"
            },
            {
              "anchor": "Querying-Tables",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/deviceDescription"
              ],
              "title": "Querying Tables"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/isKey:inTable:",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/stringForKey:inTable:",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/stringListForKey:inTable:",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/booleanForKey:inTable:",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/floatForKey:inTable:",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/intForKey:inTable:",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/rectForKey:inTable:",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/sizeForKey:inTable:",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/statusForTable:",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/TableStatus",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/printerWithName:domain:includeUnavailable:",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/acceptsBinary",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/domain",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/host",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/imageRectForPaper:",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/isColor",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/isFontAvailable:",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/isOutputStackInReverseOrder",
                "doc://com.apple.appkit/documentation/AppKit/NSPrinter/note"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Print-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintOperation"
              ],
              "title": "Print Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSPrinter"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1init(type:)/title",
          "value": "printerWithType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1init(type:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "printerWithType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1printerTypes/title",
          "value": "printerTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1printerTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "printerTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1TableStatus/title",
          "value": "NSPrinterTableStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1TableStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrinterTableStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1TableStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrinterTableStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1pageSize(forPaper:)/title",
          "value": "pageSizeForPaper:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1pageSize(forPaper:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pageSizeForPaper:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1deviceDescription/title",
          "value": "deviceDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1deviceDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deviceDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo/title",
          "value": "NSPrintInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter/title",
          "value": "NSPrinter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrinter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrinter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1printerNames/title",
          "value": "printerNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1printerNames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "printerNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1TypeName/title",
          "value": "NSPrinterTypeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1TypeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrinterTypeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1TypeName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrinterTypeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1languageLevel/title",
          "value": "languageLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1languageLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "languageLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintOperation/title",
          "value": "NSPrintOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1init(name:)/title",
          "value": "printerWithName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1init(name:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "printerWithName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1PaperName/title",
          "value": "NSPrinterPaperName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1PaperName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrinterPaperName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrinter~1PaperName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrinterPaperName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsprinter"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsprinter"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
