{
  "abstract": [
    {
      "text": "Specify the height of a progress indicator.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicatorThickness"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSProgressIndicatorThickness",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSProgressIndicatorThickness"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSProgressIndicatorThickness"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSProgressIndicatorThickness"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSProgressIndicatorThickness"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicator/Style-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify the progress indicator’s style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Style"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicator/Style-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Style"
        }
      ],
      "role": "symbol",
      "title": "NSProgressIndicator.Style",
      "type": "topic",
      "url": "/documentation/appkit/nsprogressindicator/style-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicatorThickness": {
      "abstract": [
        {
          "text": "Specify the height of a progress indicator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSProgressIndicatorThickness"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicatorThickness",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSProgressIndicatorThickness",
      "type": "topic",
      "url": "/documentation/appkit/nsprogressindicatorthickness"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicatorThickness/NSProgressIndicatorPreferredAquaThickness": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSProgressIndicatorPreferredAquaThickness"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicatorThickness/NSProgressIndicatorPreferredAquaThickness",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSProgressIndicatorPreferredAquaThickness",
      "type": "topic",
      "url": "/documentation/appkit/nsprogressindicatorthickness/nsprogressindicatorpreferredaquathickness"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicatorThickness/NSProgressIndicatorPreferredLargeThickness": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSProgressIndicatorPreferredLargeThickness"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicatorThickness/NSProgressIndicatorPreferredLargeThickness",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSProgressIndicatorPreferredLargeThickness",
      "type": "topic",
      "url": "/documentation/appkit/nsprogressindicatorthickness/nsprogressindicatorpreferredlargethickness"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicatorThickness/NSProgressIndicatorPreferredSmallThickness": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSProgressIndicatorPreferredSmallThickness"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicatorThickness/NSProgressIndicatorPreferredSmallThickness",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSProgressIndicatorPreferredSmallThickness",
      "type": "topic",
      "url": "/documentation/appkit/nsprogressindicatorthickness/nsprogressindicatorpreferredsmallthickness"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicatorThickness/NSProgressIndicatorPreferredThickness": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSProgressIndicatorPreferredThickness"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicatorThickness/NSProgressIndicatorPreferredThickness",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSProgressIndicatorPreferredThickness",
      "type": "topic",
      "url": "/documentation/appkit/nsprogressindicatorthickness/nsprogressindicatorpreferredthickness"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicator/Style-swift.enum"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicatorThickness/NSProgressIndicatorPreferredThickness",
        "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicatorThickness/NSProgressIndicatorPreferredSmallThickness",
        "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicatorThickness/NSProgressIndicatorPreferredLargeThickness",
        "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicatorThickness/NSProgressIndicatorPreferredAquaThickness"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSProgressIndicator~1Style-swift.enum/title",
          "value": "NSProgressIndicatorStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSProgressIndicator~1Style-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSProgressIndicatorStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSProgressIndicator~1Style-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSProgressIndicatorStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsprogressindicatorthickness"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
