{
  "abstract": [
    {
      "text": "A set of methods that a Print panel object can use to get information from a printing accessory controller.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanelAccessorizing"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSPrintPanelAccessorizing",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSPrintPanelAccessorizing"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSPrintPanelAccessorizing"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NSPrintPanelAccessorizing"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSPrintPanelAccessorizing"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A printing accessory controller manages a custom print panel accessory view and is used to coordinate print settings. If you are implementing a custom printing accessory view, your controller must support this protocol. Implementation of only one method in the protocol is actually required. The other method is considered optional and is used to support the print panel’s built-in preview facilities.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPDFPanel": {
      "abstract": [
        {
          "text": "A Save or Export as PDF panel that’s consistent with the macOS user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPDFPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPDFPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPDFPanel"
        }
      ],
      "role": "symbol",
      "title": "NSPDFPanel",
      "type": "topic",
      "url": "/documentation/appkit/nspdfpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/AccessorySummaryKey": {
      "abstract": [
        {
          "text": "Constants that specify the accessory panel keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AccessorySummaryKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/AccessorySummaryKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AccessorySummaryKey"
        }
      ],
      "role": "symbol",
      "title": "NSPrintPanel.AccessorySummaryKey",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/accessorysummarykey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanelAccessorizing": {
      "abstract": [
        {
          "text": "A set of methods that a Print panel object can use to get information from a printing accessory controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrintPanelAccessorizing"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanelAccessorizing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPanelAccessorizing"
        }
      ],
      "role": "symbol",
      "title": "NSPrintPanelAccessorizing",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanelaccessorizing"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanelAccessorizing/keyPathsForValuesAffectingPreview()": {
      "abstract": [
        {
          "text": "Returns a set of strings identifying the key paths for any properties that might affect the built-in print preview.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyPathsForValuesAffectingPreview"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanelAccessorizing/keyPathsForValuesAffectingPreview()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keyPathsForValuesAffectingPreview"
        }
      ],
      "role": "symbol",
      "title": "keyPathsForValuesAffectingPreview()",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanelaccessorizing/keypathsforvaluesaffectingpreview()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanelAccessorizing/localizedSummaryItems()": {
      "abstract": [
        {
          "text": "Returns an array of dictionaries containing the localized user setting summary strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedSummaryItems"
        },
        {
          "kind": "text",
          "text": "() -> [["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintPanel",
          "text": "NSPrintPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintPanelAccessorySummaryKey",
          "text": "AccessorySummaryKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanelAccessorizing/localizedSummaryItems()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedSummaryItems"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "localizedSummaryItems()",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanelaccessorizing/localizedsummaryitems()"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Print-and-PDF-Panels",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPDFPanel"
      ],
      "title": "Print and PDF Panels"
    }
  ],
  "topicSections": [
    {
      "anchor": "Responding-to-Being-Loaded-from-a-Nib-File",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanelAccessorizing/localizedSummaryItems()",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanelAccessorizing/keyPathsForValuesAffectingPreview()",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/AccessorySummaryKey"
      ],
      "title": "Responding to Being Loaded from a Nib File"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPrintPanelAccessorizing"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelAccessorizing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelAccessorizing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Responding-to-Being-Loaded-from-a-Nib-File",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanelAccessorizing/localizedSummaryItems()",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanelAccessorizing/keyPathsForValuesAffectingPreview()",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/AccessorySummaryKey"
              ],
              "title": "Responding to Being Loaded from a Nib File"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Print-and-PDF-Panels",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPDFPanel"
              ],
              "title": "Print and PDF Panels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSPrintPanelAccessorizing"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanelAccessorizing/title",
          "value": "NSPrintPanelAccessorizing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanelAccessorizing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelAccessorizing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanelAccessorizing/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelAccessorizing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanelAccessorizing~1localizedSummaryItems()/title",
          "value": "localizedSummaryItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanelAccessorizing~1localizedSummaryItems()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "localizedSummaryItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPDFPanel/title",
          "value": "NSPDFPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPDFPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPDFPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPDFPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPDFPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1AccessorySummaryKey/title",
          "value": "NSPrintPanelAccessorySummaryKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1AccessorySummaryKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelAccessorySummaryKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1AccessorySummaryKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelAccessorySummaryKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanelAccessorizing~1keyPathsForValuesAffectingPreview()/title",
          "value": "keyPathsForValuesAffectingPreview"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanelAccessorizing~1keyPathsForValuesAffectingPreview()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "keyPathsForValuesAffectingPreview"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsprintpanelaccessorizing"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsprintpanelaccessorizing"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
