{
  "abstract": [
    {
      "text": "The Print panel that queries the user for information about a print job.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSPrintPanel",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSPrintPanel"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSPrintPanel"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSPrintPanel"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSPrintPanel"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A Print panel may let the user select the range of pages to print and the number of copies before executing the Print command. Print panels can display a simplified interface when printing certain types of data. For example, the panel can display a list of print-setting presets, which lets the user enable print settings in groups as opposed to individually. Assigning an appropriate string to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/jobStyleHint-swift.property",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property activates the simplified interface and identifies which presets to display.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For design guidance, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/design/human-interface-guidelines/macos/system-capabilities/printing/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageLayout": {
      "abstract": [
        {
          "text": "A panel that queries the user for information such as paper type and orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPageLayout"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPageLayout"
        }
      ],
      "role": "symbol",
      "title": "NSPageLayout",
      "type": "topic",
      "url": "/documentation/appkit/nspagelayout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo": {
      "abstract": [
        {
          "text": "An object that stores information that’s used to generate printed output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrintInfo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintInfo"
        }
      ],
      "role": "symbol",
      "title": "NSPrintInfo",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel": {
      "abstract": [
        {
          "text": "The Print panel that queries the user for information about a print job.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrintPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPanel"
        }
      ],
      "role": "symbol",
      "title": "NSPrintPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/JobStyleHint-swift.struct": {
      "abstract": [
        {
          "text": "Constants that specify job style hints for activating the simplified Print panel interface and setting the options to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JobStyleHint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/JobStyleHint-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JobStyleHint"
        }
      ],
      "role": "symbol",
      "title": "NSPrintPanel.JobStyleHint",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/jobstylehint-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct": {
      "abstract": [
        {
          "text": "Constants that specify options for configuring the contents of the main Print panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "role": "symbol",
      "title": "NSPrintPanel.Options",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/options-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Result": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Result"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Result",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Result"
        }
      ],
      "role": "symbol",
      "title": "NSPrintPanel.Result",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/result"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/accessoryControllers": {
      "abstract": [
        {
          "text": "The array of controller objects that manage the Print panel’s accessory views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessoryControllers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSViewController",
          "text": "NSViewController"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/accessoryControllers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessoryControllers"
        }
      ],
      "role": "symbol",
      "title": "accessoryControllers",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/accessorycontrollers"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/accessoryView": {
      "abstract": [
        {
          "text": "Returns the accessory view of the Print panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "accessoryView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/accessoryView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessoryView"
        }
      ],
      "role": "symbol",
      "title": "accessoryView",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/accessoryview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/addAccessoryController(_:)": {
      "abstract": [
        {
          "text": "Adds a custom controller to the Print panel to manage an accessory view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addAccessoryController"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSViewController",
          "text": "NSViewController"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSPrintPanelAccessorizing",
          "text": "NSPrintPanelAccessorizing"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/addAccessoryController(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addAccessoryController:"
        }
      ],
      "role": "symbol",
      "title": "addAccessoryController(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/addaccessorycontroller(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/beginSheet(using:on:completionHandler:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginSheet"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "on"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintPanel",
          "text": "NSPrintPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPrintPanelResult",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/beginSheet(using:on:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginSheetUsingPrintInfo:onWindow:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "beginSheet(using:on:completionHandler:)",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/beginsheet(using:on:completionhandler:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/beginSheet(with:modalFor:delegate:didEnd:contextInfo:)": {
      "abstract": [
        {
          "text": "Displays a Print panel sheet and runs it modally for the specified window.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginSheet"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "modalFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "didEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "contextInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/beginSheet(with:modalFor:delegate:didEnd:contextInfo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginSheetWithPrintInfo:modalForWindow:delegate:didEndSelector:contextInfo:"
        }
      ],
      "role": "symbol",
      "title": "beginSheet(with:modalFor:delegate:didEnd:contextInfo:)",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/beginsheet(with:modalfor:delegate:didend:contextinfo:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/defaultButtonTitle()": {
      "abstract": [
        {
          "text": "Returns the title of the Print panel’s default button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultButtonTitle"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/defaultButtonTitle()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultButtonTitle"
        }
      ],
      "role": "symbol",
      "title": "defaultButtonTitle()",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/defaultbuttontitle()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/finalWritePrintInfo": {
      "abstract": [
        {
          "text": "Writes the Print panel’s printing attributes to the current print operation object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "finalWritePrintInfo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/finalWritePrintInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "finalWritePrintInfo"
        }
      ],
      "role": "symbol",
      "title": "finalWritePrintInfo",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/finalwriteprintinfo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/helpAnchor": {
      "abstract": [
        {
          "text": "The HTML help anchor associated with the Print panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "helpAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSHelpManager",
          "text": "NSHelpManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSHelpAnchorName",
          "text": "AnchorName"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/helpAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "helpAnchor"
        }
      ],
      "role": "symbol",
      "title": "helpAnchor",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/helpanchor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/jobStyleHint-swift.property": {
      "abstract": [
        {
          "text": "The type of settings that the print panel displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "jobStyleHint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintPanel",
          "text": "NSPrintPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintPanelJobStyleHint",
          "text": "JobStyleHint"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/jobStyleHint-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "jobStyleHint"
        }
      ],
      "role": "symbol",
      "title": "jobStyleHint",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/jobstylehint-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/options-swift.property": {
      "abstract": [
        {
          "text": "The current configuration options for the Print panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintPanel",
          "text": "NSPrintPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPrintPanelOptions",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/options-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "options"
        }
      ],
      "role": "symbol",
      "title": "options",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/options-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/printInfo": {
      "abstract": [
        {
          "text": "The information associated with the running Print panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/printInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printInfo"
        }
      ],
      "role": "symbol",
      "title": "printInfo",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/printinfo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/printPanel": {
      "abstract": [
        {
          "text": "Returns a new print panel object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "printPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/printPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printPanel"
        }
      ],
      "role": "symbol",
      "title": "printPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/printpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/removeAccessoryController(_:)": {
      "abstract": [
        {
          "text": "Removes the specified controller and accessory view from the Print panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAccessoryController"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSViewController",
          "text": "NSViewController"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSPrintPanelAccessorizing",
          "text": "NSPrintPanelAccessorizing"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/removeAccessoryController(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAccessoryController:"
        }
      ],
      "role": "symbol",
      "title": "removeAccessoryController(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/removeaccessorycontroller(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/runModal()": {
      "abstract": [
        {
          "text": "Displays the Print panel and begins the modal loop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "runModal"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/runModal()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runModal"
        }
      ],
      "role": "symbol",
      "title": "runModal()",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/runmodal()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/runModal(with:)": {
      "abstract": [
        {
          "text": "Displays the Print panel and runs the modal loop using the specified printing information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "runModal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/runModal(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runModalWithPrintInfo:"
        }
      ],
      "role": "symbol",
      "title": "runModal(with:)",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/runmodal(with:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/setAccessoryView:": {
      "abstract": [
        {
          "text": "Sets the accessory view for the Print panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setAccessoryView:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/setAccessoryView:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setAccessoryView:"
        }
      ],
      "role": "symbol",
      "title": "setAccessoryView:",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/setaccessoryview:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/setDefaultButtonTitle(_:)": {
      "abstract": [
        {
          "text": "Sets the title of the Print panel’s default button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDefaultButtonTitle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/setDefaultButtonTitle(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDefaultButtonTitle:"
        }
      ],
      "role": "symbol",
      "title": "setDefaultButtonTitle(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/setdefaultbuttontitle(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/updateFromPrintInfo": {
      "abstract": [
        {
          "text": "Updates the Print panel with information from the current print operation object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "updateFromPrintInfo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/updateFromPrintInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateFromPrintInfo"
        }
      ],
      "role": "symbol",
      "title": "updateFromPrintInfo",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanel/updatefromprintinfo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintPanelAccessorizing": {
      "abstract": [
        {
          "text": "A set of methods that a Print panel object can use to get information from a printing accessory controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrintPanelAccessorizing"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintPanelAccessorizing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintPanelAccessorizing"
        }
      ],
      "role": "symbol",
      "title": "NSPrintPanelAccessorizing",
      "type": "topic",
      "url": "/documentation/appkit/nsprintpanelaccessorizing"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "https://developer.apple.com/design/human-interface-guidelines/macos/system-capabilities/printing/": {
      "identifier": "https://developer.apple.com/design/human-interface-guidelines/macos/system-capabilities/printing/",
      "title": "Human Interface Guidelines",
      "titleInlineContent": [
        {
          "text": "Human Interface Guidelines",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/design/human-interface-guidelines/macos/system-capabilities/printing/"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Print-Panels",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPageLayout"
      ],
      "title": "Print Panels"
    }
  ],
  "topicSections": [
    {
      "anchor": "Customizing-the-Panel",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/jobStyleHint-swift.property",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/JobStyleHint-swift.struct",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/options-swift.property",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/defaultButtonTitle()",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/setDefaultButtonTitle(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/helpAnchor"
      ],
      "title": "Customizing the Panel"
    },
    {
      "anchor": "Managing-Accessory-Views",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/addAccessoryController(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/removeAccessoryController(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanelAccessorizing",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/accessoryControllers"
      ],
      "title": "Managing Accessory Views"
    },
    {
      "anchor": "Running-the-Panel",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/beginSheet(using:on:completionHandler:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/beginSheet(with:modalFor:delegate:didEnd:contextInfo:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/runModal()",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/runModal(with:)"
      ],
      "title": "Running the Panel"
    },
    {
      "anchor": "Accessing-the-Printing-Information",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/printInfo",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Result"
      ],
      "title": "Accessing the Printing Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPrintPanel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-the-Printing-Panel",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/printPanel"
              ],
              "title": "Creating the Printing Panel"
            },
            {
              "anchor": "Customizing-the-Panel",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/jobStyleHint-swift.property",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/JobStyleHint-swift.struct",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/options-swift.property",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Options-swift.struct",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/defaultButtonTitle()",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/setDefaultButtonTitle(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/helpAnchor"
              ],
              "title": "Customizing the Panel"
            },
            {
              "anchor": "Managing-Accessory-Views",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/addAccessoryController(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/removeAccessoryController(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanelAccessorizing",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/accessoryControllers"
              ],
              "title": "Managing Accessory Views"
            },
            {
              "anchor": "Running-the-Panel",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/beginSheet(using:on:completionHandler:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/beginSheet(with:modalFor:delegate:didEnd:contextInfo:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/runModal()",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/runModal(with:)"
              ],
              "title": "Running the Panel"
            },
            {
              "anchor": "Accessing-the-Printing-Information",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/printInfo",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/Result"
              ],
              "title": "Accessing the Printing Information"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/accessoryView",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/setAccessoryView:",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/updateFromPrintInfo",
                "doc://com.apple.appkit/documentation/AppKit/NSPrintPanel/finalWritePrintInfo"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Print-Panels",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPageLayout"
              ],
              "title": "Print Panels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSPrintPanel"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1addAccessoryController(_:)/title",
          "value": "addAccessoryController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1addAccessoryController(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addAccessoryController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanelAccessorizing/title",
          "value": "NSPrintPanelAccessorizing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanelAccessorizing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelAccessorizing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanelAccessorizing/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelAccessorizing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1printInfo/title",
          "value": "printInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1printInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "printInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1JobStyleHint-swift.struct/title",
          "value": "NSPrintPanelJobStyleHint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1JobStyleHint-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelJobStyleHint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1JobStyleHint-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelJobStyleHint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel/title",
          "value": "NSPrintPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct/title",
          "value": "NSPrintPanelOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Options-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1runModal(with:)/title",
          "value": "runModalWithPrintInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1runModal(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runModalWithPrintInfo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1helpAnchor/title",
          "value": "helpAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1helpAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "helpAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1accessoryControllers/title",
          "value": "accessoryControllers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1accessoryControllers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "accessoryControllers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1removeAccessoryController(_:)/title",
          "value": "removeAccessoryController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1removeAccessoryController(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeAccessoryController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1defaultButtonTitle()/title",
          "value": "defaultButtonTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1defaultButtonTitle()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "defaultButtonTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout/title",
          "value": "NSPageLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPageLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPageLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo/title",
          "value": "NSPrintInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1setDefaultButtonTitle(_:)/title",
          "value": "setDefaultButtonTitle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1setDefaultButtonTitle(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setDefaultButtonTitle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Result/title",
          "value": "NSPrintPanelResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Result/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1Result/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintPanelResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1options-swift.property/title",
          "value": "options"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1options-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1runModal()/title",
          "value": "runModal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1runModal()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runModal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1beginSheet(using:on:completionHandler:)/title",
          "value": "beginSheetUsingPrintInfo:onWindow:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1beginSheet(using:on:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginSheetUsingPrintInfo:onWindow:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1jobStyleHint-swift.property/title",
          "value": "jobStyleHint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1jobStyleHint-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "jobStyleHint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1beginSheet(with:modalFor:delegate:didEnd:contextInfo:)/title",
          "value": "beginSheetWithPrintInfo:modalForWindow:delegate:didEndSelector:contextInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintPanel~1beginSheet(with:modalFor:delegate:didEnd:contextInfo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginSheetWithPrintInfo:modalForWindow:delegate:didEndSelector:contextInfo:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsprintpanel"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsprintpanel"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
