{
  "abstract": [
    {
      "text": "Style best used for address type tokens.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSRoundedTokenStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSRoundedTokenStyle",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSRoundedTokenStyle"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSRoundedTokenStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSRoundedTokenStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenField/TokenStyle-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSTokenStyle",
              "text": "NSTokenStyle"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSRoundedTokenStyle"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDefaultTokenStyle": {
      "abstract": [
        {
          "text": "Style best used for keyword type tokens.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSDefaultTokenStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDefaultTokenStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDefaultTokenStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsdefaulttokenstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPlainTextTokenStyle": {
      "abstract": [
        {
          "text": "Style to use for data you want represented as plain-text and without any token background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPlainTextTokenStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPlainTextTokenStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPlainTextTokenStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsplaintexttokenstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRoundedTokenStyle": {
      "abstract": [
        {
          "text": "Style best used for address type tokens.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRoundedTokenStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRoundedTokenStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRoundedTokenStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsroundedtokenstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTokenField/TokenStyle-swift.enum": {
      "abstract": [
        {
          "text": "The NSTokenStyle constants define how tokens are displayed and editable in the ",
          "type": "text"
        },
        {
          "code": "NSTokenFieldCell",
          "type": "codeVoice"
        },
        {
          "text": ". These values are used by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCell/tokenStyle",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and the delegate method ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:styleForRepresentedObject:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TokenStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenField/TokenStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TokenStyle"
        }
      ],
      "role": "symbol",
      "title": "NSTokenField.TokenStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstokenfield/tokenstyle-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCell/tokenStyle": {
      "abstract": [
        {
          "text": "The token style of the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tokenStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTokenField",
          "text": "NSTokenField"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTokenStyle",
          "text": "TokenStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCell/tokenStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tokenStyle"
        }
      ],
      "role": "symbol",
      "title": "tokenStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstokenfieldcell/tokenstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:styleForRepresentedObject:)": {
      "abstract": [
        {
          "text": "Allows the delegate to return the token style for editing the specified represented object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tokenFieldCell"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTokenFieldCell",
          "text": "NSTokenFieldCell"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "styleForRepresentedObject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTokenField",
          "text": "NSTokenField"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTokenStyle",
          "text": "TokenStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:styleForRepresentedObject:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tokenFieldCell:styleForRepresentedObject:"
        }
      ],
      "role": "symbol",
      "title": "tokenFieldCell(_:styleForRepresentedObject:)",
      "type": "topic",
      "url": "/documentation/appkit/nstokenfieldcelldelegate/tokenfieldcell(_:styleforrepresentedobject:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDefaultTokenStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSPlainTextTokenStyle"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField~1TokenStyle-swift.enum/title",
          "value": "NSTokenStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField~1TokenStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTokenStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField~1TokenStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTokenStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCell~1tokenStyle/title",
          "value": "tokenStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCell~1tokenStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tokenStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCellDelegate~1tokenFieldCell(_:styleForRepresentedObject:)/title",
          "value": "tokenFieldCell:styleForRepresentedObject:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCellDelegate~1tokenFieldCell(_:styleForRepresentedObject:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tokenFieldCell:styleForRepresentedObject:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsroundedtokenstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
