{
  "abstract": [
    {
      "text": "Creates an alert panel.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAlert",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSRunAlertPanel"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@NSRunAlertPanel",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSRunAlertPanel"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSRunAlertPanel"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.10",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "NSRunAlertPanel"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSRunAlertPanel"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "title"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "msgFormat"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "defaultButton"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "alternateButton"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "otherButton"
            },
            {
              "kind": "text",
              "text": ", ...);"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Creates and runs an alert panel (or dialog) with the title of ",
              "type": "text"
            },
            {
              "code": "title",
              "type": "codeVoice"
            },
            {
              "text": " and buttons with titles of ",
              "type": "text"
            },
            {
              "code": "defaultButton",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "alternateButton",
              "type": "codeVoice"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "code": "otherButton",
              "type": "codeVoice"
            },
            {
              "text": ". The optional alert message specified by ",
              "type": "text"
            },
            {
              "code": "msgFormat",
              "type": "codeVoice"
            },
            {
              "text": " should be a static value that can consist of variable values using a format string (list any necessary arguments for this formatted string at the end of the function’s argument list), an unformatted string, or an empty string (",
              "type": "text"
            },
            {
              "code": "@\"\"",
              "type": "codeVoice"
            },
            {
              "text": "), but not ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ". Note that passing an untrusted string in ",
              "type": "text"
            },
            {
              "code": "msgFormat",
              "type": "codeVoice"
            },
            {
              "text": " can lead to security issues. See the description of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBeginAlertSheet",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for information on layout of buttons, default parameters, and possible return values. ",
              "type": "text"
            },
            {
              "code": "NSRunAlertPanel",
              "type": "codeVoice"
            },
            {
              "text": " runs the panel in a modal event loop.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A Command-D key equivalent for the “Don’t Save” button is provided, if one is found. The button titles are searched for the localized value for “Don’t Save.” If a match is found, that button is assigned a Command-D key equivalent, provided it is not the default button.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you create a modal panel using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/runModal(for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/beginSheet(_:modalFor:modalDelegate:didEnd:contextInfo:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", you can assign the key equivalent yourself, using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/keyEquivalent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/keyEquivalentModifierMask",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This function not only creates the panel; it also puts the panel onscreen and runs it using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/runModal(for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method defined in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class. This method sets up a modal event loop that causes the panel to remain onscreen until the user clicks one of its buttons. This function then removes the panel from the screen list and returns a value that indicates which of the three buttons the user clicked. For efficiency, this function creates the panel the first time it’s called and reuses it on subsequent calls, reconfiguring it if necessary.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/raiseBadArgumentException(_:_:_:)": {
      "abstract": [
        {
          "text": "Raises an error if the parameter is the wrong type or has an illegal value",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "raiseBadArgumentException"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/raiseBadArgumentException(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityRaiseBadArgumentException"
        }
      ],
      "role": "symbol",
      "title": "raiseBadArgumentException(_:_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/raisebadargumentexception(_:_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAlert": {
      "abstract": [
        {
          "text": "A modal dialog or sheet attached to a document window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAlert"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAlert",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAlert"
        }
      ],
      "role": "symbol",
      "title": "NSAlert",
      "type": "topic",
      "url": "/documentation/appkit/nsalert"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication": {
      "abstract": [
        {
          "text": "An object that manages an app’s main event loop and resources used by all of that app’s objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSApplication"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplication"
        }
      ],
      "role": "symbol",
      "title": "NSApplication",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/beginSheet(_:modalFor:modalDelegate:didEnd:contextInfo:)": {
      "abstract": [
        {
          "text": "Starts a document modal session.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginSheet"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "modalFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "modalDelegate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "didEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "contextInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/beginSheet(_:modalFor:modalDelegate:didEnd:contextInfo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginSheet:modalForWindow:modalDelegate:didEndSelector:contextInfo:"
        }
      ],
      "role": "symbol",
      "title": "beginSheet(_:modalFor:modalDelegate:didEnd:contextInfo:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/beginsheet(_:modalfor:modaldelegate:didend:contextinfo:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/runModal(for:)": {
      "abstract": [
        {
          "text": "Starts a modal event loop for the specified window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "runModal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSModalResponse",
          "text": "ModalResponse"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/runModal(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runModalForWindow:"
        }
      ],
      "role": "symbol",
      "title": "runModal(for:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/runmodal(for:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBeginAlertSheet": {
      "abstract": [
        {
          "text": "Creates and runs an alert sheet.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBeginAlertSheet"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBeginAlertSheet",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBeginAlertSheet",
      "type": "topic",
      "url": "/documentation/appkit/nsbeginalertsheet"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBeginCriticalAlertSheet": {
      "abstract": [
        {
          "text": "Creates and runs a critical alert sheet.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBeginCriticalAlertSheet"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBeginCriticalAlertSheet",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBeginCriticalAlertSheet",
      "type": "topic",
      "url": "/documentation/appkit/nsbegincriticalalertsheet"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBeginInformationalAlertSheet": {
      "abstract": [
        {
          "text": "Creates and runs an informational alert sheet.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBeginInformationalAlertSheet"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBeginInformationalAlertSheet",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBeginInformationalAlertSheet",
      "type": "topic",
      "url": "/documentation/appkit/nsbegininformationalalertsheet"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/keyEquivalent": {
      "abstract": [
        {
          "text": "The key-equivalent character of the button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyEquivalent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/keyEquivalent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keyEquivalent"
        }
      ],
      "role": "symbol",
      "title": "keyEquivalent",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/keyequivalent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/keyEquivalentModifierMask": {
      "abstract": [
        {
          "text": "The mask specifying the modifier keys for the button’s key equivalent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyEquivalentModifierMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSEventModifierFlags",
          "text": "ModifierFlags"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/keyEquivalentModifierMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keyEquivalentModifierMask"
        }
      ],
      "role": "symbol",
      "title": "keyEquivalentModifierMask",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/keyequivalentmodifiermask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSConvertGlyphsToPackedGlyphs(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Prepares a set of glyphs for processing by character-based routines.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSConvertGlyphsToPackedGlyphs"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSGlyph",
          "text": "NSGlyph"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSMultibyteGlyphPacking",
          "text": "NSMultibyteGlyphPacking"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSConvertGlyphsToPackedGlyphs(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSConvertGlyphsToPackedGlyphs"
        }
      ],
      "role": "symbol",
      "title": "NSConvertGlyphsToPackedGlyphs(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsconvertglyphstopackedglyphs(_:_:_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGetAlertPanel": {
      "abstract": [
        {
          "text": "Returns an alert panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSGetAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGetAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSGetAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsgetalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGetCriticalAlertPanel": {
      "abstract": [
        {
          "text": "Returns an alert panel to display a critical message.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSGetCriticalAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGetCriticalAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSGetCriticalAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsgetcriticalalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGetInformationalAlertPanel": {
      "abstract": [
        {
          "text": "Returns an alert panel to display an informational message.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSGetInformationalAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGetInformationalAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSGetInformationalAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsgetinformationalalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetOption": {
      "abstract": [
        {
          "text": "Returns global OpenGL options.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOpenGLGetOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetOption",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOpenGLGetOption",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglgetoption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetVersion": {
      "abstract": [
        {
          "text": "Returns the NSOpenGL version numbers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOpenGLGetVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetVersion",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOpenGLGetVersion",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglgetversion"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLSetOption": {
      "abstract": [
        {
          "text": "Sets global OpenGL options.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOpenGLSetOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLSetOption",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOpenGLSetOption",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglsetoption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSReleaseAlertPanel(_:)": {
      "abstract": [
        {
          "text": "Disposes of an alert panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSReleaseAlertPanel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSReleaseAlertPanel(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSReleaseAlertPanel"
        }
      ],
      "role": "symbol",
      "title": "NSReleaseAlertPanel(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsreleasealertpanel(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRunAlertPanel": {
      "abstract": [
        {
          "text": "Creates an alert panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRunAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRunAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRunAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsrunalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRunAlertPanelRelativeToWindow": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRunAlertPanelRelativeToWindow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRunAlertPanelRelativeToWindow",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRunAlertPanelRelativeToWindow",
      "type": "topic",
      "url": "/documentation/appkit/nsrunalertpanelrelativetowindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRunCriticalAlertPanel": {
      "abstract": [
        {
          "text": "Creates and runs a critical alert panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRunCriticalAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRunCriticalAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRunCriticalAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsruncriticalalertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRunInformationalAlertPanel": {
      "abstract": [
        {
          "text": "Creates and runs an informational alert panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRunInformationalAlertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRunInformationalAlertPanel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRunInformationalAlertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsruninformationalalertpanel"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSConvertGlyphsToPackedGlyphs(_:_:_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetOption",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGetVersion",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLSetOption",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/raiseBadArgumentException(_:_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSBeginAlertSheet",
        "doc://com.apple.appkit/documentation/AppKit/NSBeginCriticalAlertSheet",
        "doc://com.apple.appkit/documentation/AppKit/NSBeginInformationalAlertSheet",
        "doc://com.apple.appkit/documentation/AppKit/NSGetAlertPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSGetCriticalAlertPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSGetInformationalAlertPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSReleaseAlertPanel(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSRunCriticalAlertPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSRunInformationalAlertPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSRunAlertPanelRelativeToWindow"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1keyEquivalent/title",
          "value": "keyEquivalent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1keyEquivalent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "keyEquivalent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAlert/title",
          "value": "NSAlert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAlert/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAlert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAlert/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAlert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSReleaseAlertPanel(_:)/title",
          "value": "NSReleaseAlertPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSReleaseAlertPanel(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSReleaseAlertPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1keyEquivalentModifierMask/title",
          "value": "keyEquivalentModifierMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1keyEquivalentModifierMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "keyEquivalentModifierMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1runModal(for:)/title",
          "value": "runModalForWindow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1runModal(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runModalForWindow:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1beginSheet(_:modalFor:modalDelegate:didEnd:contextInfo:)/title",
          "value": "beginSheet:modalForWindow:modalDelegate:didEndSelector:contextInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1beginSheet(_:modalFor:modalDelegate:didEnd:contextInfo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginSheet:modalForWindow:modalDelegate:didEndSelector:contextInfo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1raiseBadArgumentException(_:_:_:)/title",
          "value": "NSAccessibilityRaiseBadArgumentException"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1raiseBadArgumentException(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRaiseBadArgumentException"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/title",
          "value": "NSApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSConvertGlyphsToPackedGlyphs(_:_:_:_:)/title",
          "value": "NSConvertGlyphsToPackedGlyphs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSConvertGlyphsToPackedGlyphs(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSConvertGlyphsToPackedGlyphs"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsrunalertpanel"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
