{
  "abstract": [
    {
      "text": "A mask for scroll-wheel events.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSScrollWheelMask"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSScrollWheelMask",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSScrollWheelMask"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSScrollWheelMask"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.12",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSScrollWheelMask"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventTypeMask",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSEventMask",
              "text": "NSEventMask"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSScrollWheelMask"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursorUpdateMask": {
      "abstract": [
        {
          "text": "A mask for cursor-update events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCursorUpdateMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursorUpdateMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCursorUpdateMask",
      "type": "topic",
      "url": "/documentation/appkit/nscursorupdatemask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventTypeMask": {
      "abstract": [
        {
          "text": "Constants that you use to filter out specific event types from the stream of incoming events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EventTypeMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventTypeMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EventTypeMask"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventTypeMask",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventtypemask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSKeyDownMask": {
      "abstract": [
        {
          "text": "A mask for key-down events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSKeyDownMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSKeyDownMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSKeyDownMask",
      "type": "topic",
      "url": "/documentation/appkit/nskeydownmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSKeyUpMask": {
      "abstract": [
        {
          "text": "A mask for key-up events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSKeyUpMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSKeyUpMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSKeyUpMask",
      "type": "topic",
      "url": "/documentation/appkit/nskeyupmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLeftMouseDownMask": {
      "abstract": [
        {
          "text": "A mask for left mouse-down events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLeftMouseDownMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLeftMouseDownMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLeftMouseDownMask",
      "type": "topic",
      "url": "/documentation/appkit/nsleftmousedownmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLeftMouseDraggedMask": {
      "abstract": [
        {
          "text": "A mask for left mouse-dragged events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLeftMouseDraggedMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLeftMouseDraggedMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLeftMouseDraggedMask",
      "type": "topic",
      "url": "/documentation/appkit/nsleftmousedraggedmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLeftMouseUpMask": {
      "abstract": [
        {
          "text": "A mask for left mouse-up events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLeftMouseUpMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLeftMouseUpMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLeftMouseUpMask",
      "type": "topic",
      "url": "/documentation/appkit/nsleftmouseupmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMouseEnteredMask": {
      "abstract": [
        {
          "text": "A mask for mouse-entered events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMouseEnteredMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMouseEnteredMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMouseEnteredMask",
      "type": "topic",
      "url": "/documentation/appkit/nsmouseenteredmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMouseExitedMask": {
      "abstract": [
        {
          "text": "A mask for mouse-exited events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMouseExitedMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMouseExitedMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMouseExitedMask",
      "type": "topic",
      "url": "/documentation/appkit/nsmouseexitedmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMouseMovedMask": {
      "abstract": [
        {
          "text": "A mask for mouse-moved events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMouseMovedMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMouseMovedMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMouseMovedMask",
      "type": "topic",
      "url": "/documentation/appkit/nsmousemovedmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOtherMouseDownMask": {
      "abstract": [
        {
          "text": "A mask for other mouse-down events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOtherMouseDownMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOtherMouseDownMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOtherMouseDownMask",
      "type": "topic",
      "url": "/documentation/appkit/nsothermousedownmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOtherMouseDraggedMask": {
      "abstract": [
        {
          "text": "A mask for other mouse-dragged events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOtherMouseDraggedMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOtherMouseDraggedMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOtherMouseDraggedMask",
      "type": "topic",
      "url": "/documentation/appkit/nsothermousedraggedmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOtherMouseUpMask": {
      "abstract": [
        {
          "text": "A mask for other mouse-up events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOtherMouseUpMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOtherMouseUpMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOtherMouseUpMask",
      "type": "topic",
      "url": "/documentation/appkit/nsothermouseupmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRightMouseDownMask": {
      "abstract": [
        {
          "text": "A mask for right mouse-down events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRightMouseDownMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRightMouseDownMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRightMouseDownMask",
      "type": "topic",
      "url": "/documentation/appkit/nsrightmousedownmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRightMouseDraggedMask": {
      "abstract": [
        {
          "text": "A mask for right mouse-dragged events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRightMouseDraggedMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRightMouseDraggedMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRightMouseDraggedMask",
      "type": "topic",
      "url": "/documentation/appkit/nsrightmousedraggedmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRightMouseUpMask": {
      "abstract": [
        {
          "text": "A mask for right mouse-up events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRightMouseUpMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRightMouseUpMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRightMouseUpMask",
      "type": "topic",
      "url": "/documentation/appkit/nsrightmouseupmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrollWheelMask": {
      "abstract": [
        {
          "text": "A mask for scroll-wheel events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSScrollWheelMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrollWheelMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSScrollWheelMask",
      "type": "topic",
      "url": "/documentation/appkit/nsscrollwheelmask"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSLeftMouseDownMask",
        "doc://com.apple.appkit/documentation/AppKit/NSLeftMouseUpMask",
        "doc://com.apple.appkit/documentation/AppKit/NSRightMouseDownMask",
        "doc://com.apple.appkit/documentation/AppKit/NSRightMouseUpMask",
        "doc://com.apple.appkit/documentation/AppKit/NSOtherMouseDownMask",
        "doc://com.apple.appkit/documentation/AppKit/NSOtherMouseUpMask",
        "doc://com.apple.appkit/documentation/AppKit/NSMouseMovedMask",
        "doc://com.apple.appkit/documentation/AppKit/NSLeftMouseDraggedMask",
        "doc://com.apple.appkit/documentation/AppKit/NSRightMouseDraggedMask",
        "doc://com.apple.appkit/documentation/AppKit/NSOtherMouseDraggedMask",
        "doc://com.apple.appkit/documentation/AppKit/NSMouseEnteredMask",
        "doc://com.apple.appkit/documentation/AppKit/NSMouseExitedMask",
        "doc://com.apple.appkit/documentation/AppKit/NSCursorUpdateMask",
        "doc://com.apple.appkit/documentation/AppKit/NSKeyDownMask",
        "doc://com.apple.appkit/documentation/AppKit/NSKeyUpMask"
      ],
      "title": "Deprecated Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventTypeMask/title",
          "value": "NSEventMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventTypeMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventTypeMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventMask"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsscrollwheelmask"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
