{
  "abstract": [
    {
      "text": "An object that describes the attributes of a computer’s monitor or screen.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSScreen"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSScreen",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSScreen"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSScreen"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSScreen"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSScreen"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An app may use an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to retrieve information about a screen and use this information to decide what to display on that screen. For example, an app may use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/deepest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to find out which of the available screens can best represent color and then might choose to display all of its windows on that screen.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Create the application object before you use the methods in this class, so that the application object can make the necessary connection to the window system. You can make sure the application object exists by invoking the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/shared",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". If you created your app with Xcode, the application object is automatically created for you during initialization.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " class is only for getting information about the available displays. If you need additional information or want to change the attributes relating to a display, you must use Quartz Services. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/coregraphics/quartz_display_services",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication": {
      "abstract": [
        {
          "text": "An object that manages an app’s main event loop and resources used by all of that app’s objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSApplication"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplication"
        }
      ],
      "role": "symbol",
      "title": "NSApplication",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/shared": {
      "abstract": [
        {
          "text": "Returns the application instance, creating it if it doesn’t exist yet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shared"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/shared",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sharedApplication"
        }
      ],
      "role": "symbol",
      "title": "shared",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/shared"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey": {
      "abstract": [
        {
          "text": "These constants are the keys for device description dictionaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDeviceDescriptionKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDeviceDescriptionKey"
        }
      ],
      "role": "symbol",
      "title": "NSDeviceDescriptionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsdevicedescriptionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDisplayGamut": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDisplayGamut"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDisplayGamut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDisplayGamut"
        }
      ],
      "role": "symbol",
      "title": "NSDisplayGamut",
      "type": "topic",
      "url": "/documentation/appkit/nsdisplaygamut"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen": {
      "abstract": [
        {
          "text": "An object that describes the attributes of a computer’s monitor or screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScreen"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScreen"
        }
      ],
      "role": "symbol",
      "title": "NSScreen",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/auxiliaryTopLeftArea-4ow3p": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "auxiliaryTopLeftArea"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/auxiliaryTopLeftArea-4ow3p",
      "kind": "symbol",
      "role": "symbol",
      "title": "auxiliaryTopLeftArea",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/auxiliarytopleftarea-4ow3p"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/auxiliaryTopLeftArea-uglc": {
      "abstract": [
        {
          "text": "The unobscured portion of the top-left corner of the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "auxiliaryTopLeftArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/auxiliaryTopLeftArea-uglc",
      "kind": "symbol",
      "role": "symbol",
      "title": "auxiliaryTopLeftArea",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/auxiliarytopleftarea-uglc"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/auxiliaryTopRightArea-6gb2v": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "auxiliaryTopRightArea"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/auxiliaryTopRightArea-6gb2v",
      "kind": "symbol",
      "role": "symbol",
      "title": "auxiliaryTopRightArea",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/auxiliarytoprightarea-6gb2v"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/auxiliaryTopRightArea-gr2n": {
      "abstract": [
        {
          "text": "The unobscured portion of the top-right corner of the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "auxiliaryTopRightArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/auxiliaryTopRightArea-gr2n",
      "kind": "symbol",
      "role": "symbol",
      "title": "auxiliaryTopRightArea",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/auxiliarytoprightarea-gr2n"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/backingAlignedRect(_:options:)": {
      "abstract": [
        {
          "text": "Converts a rectangle in global screen coordinates to a pixel aligned rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backingAlignedRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSAlignmentOptions",
          "text": "AlignmentOptions"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/backingAlignedRect(_:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backingAlignedRect:options:"
        }
      ],
      "role": "symbol",
      "title": "backingAlignedRect(_:options:)",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/backingalignedrect(_:options:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/backingScaleFactor": {
      "abstract": [
        {
          "text": "The backing store pixel scale factor for the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backingScaleFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/backingScaleFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backingScaleFactor"
        }
      ],
      "role": "symbol",
      "title": "backingScaleFactor",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/backingscalefactor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/canRepresent(_:)": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the color space of the screen is capable of representing the specified display gamut.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canRepresent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDisplayGamut",
          "text": "NSDisplayGamut"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/canRepresent(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canRepresentDisplayGamut:"
        }
      ],
      "role": "symbol",
      "title": "canRepresent(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/canrepresent(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/colorSpace": {
      "abstract": [
        {
          "text": "The color space of the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/colorSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorSpace"
        }
      ],
      "role": "symbol",
      "title": "colorSpace",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/colorspace"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/colorSpaceDidChangeNotification": {
      "abstract": [
        {
          "text": "Posted when the color space of the screen has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorSpaceDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/colorSpaceDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScreenColorSpaceDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "colorSpaceDidChangeNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/colorspacedidchangenotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/convertRectFromBacking(_:)": {
      "abstract": [
        {
          "text": "Converts the rectangle from the device pixel aligned coordinates system of a screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convertRectFromBacking"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/convertRectFromBacking(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertRectFromBacking:"
        }
      ],
      "role": "symbol",
      "title": "convertRectFromBacking(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/convertrectfrombacking(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/convertRectToBacking(_:)": {
      "abstract": [
        {
          "text": "Converts the rectangle to the device pixel aligned coordinates system of a screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convertRectToBacking"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/convertRectToBacking(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertRectToBacking:"
        }
      ],
      "role": "symbol",
      "title": "convertRectToBacking(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/convertrecttobacking(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/deepest": {
      "abstract": [
        {
          "text": "Returns a screen object representing the screen that can best represent color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deepest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSScreen",
          "text": "NSScreen"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/deepest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deepestScreen"
        }
      ],
      "role": "symbol",
      "title": "deepest",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/deepest"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/depth": {
      "abstract": [
        {
          "text": "The current bit depth and colorspace information of the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "depth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowDepth",
          "text": "Depth"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/depth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "depth"
        }
      ],
      "role": "symbol",
      "title": "depth",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/depth"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/deviceDescription": {
      "abstract": [
        {
          "text": "The device dictionary for the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceDescription"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSDeviceDescriptionKey",
          "text": "NSDeviceDescriptionKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/deviceDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceDescription"
        }
      ],
      "role": "symbol",
      "title": "deviceDescription",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/devicedescription"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/displayLink(target:selector:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayLink"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "target"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "selector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CADisplayLink",
          "text": "CADisplayLink"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/displayLink(target:selector:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayLinkWithTarget:selector:"
        }
      ],
      "role": "symbol",
      "title": "displayLink(target:selector:)",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/displaylink(target:selector:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/displayUpdateGranularity": {
      "abstract": [
        {
          "text": "The number of seconds between the screen’s supported update rates, for screens that support fixed update rates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayUpdateGranularity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/displayUpdateGranularity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayUpdateGranularity"
        }
      ],
      "role": "symbol",
      "title": "displayUpdateGranularity",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/displayupdategranularity"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/frame": {
      "abstract": [
        {
          "text": "The dimensions and location of the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/frame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "frame"
        }
      ],
      "role": "symbol",
      "title": "frame",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/frame"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/lastDisplayUpdateTimestamp": {
      "abstract": [
        {
          "text": "The time of the last framebuffer update, expressed as the number of seconds since system startup.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lastDisplayUpdateTimestamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/lastDisplayUpdateTimestamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lastDisplayUpdateTimestamp"
        }
      ],
      "role": "symbol",
      "title": "lastDisplayUpdateTimestamp",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/lastdisplayupdatetimestamp"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/localizedName": {
      "abstract": [
        {
          "text": "The localized name of the display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/localizedName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedName"
        }
      ],
      "role": "symbol",
      "title": "localizedName",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/localizedname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/main": {
      "abstract": [
        {
          "text": "Returns the screen object containing the window with the keyboard focus.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "main"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSScreen",
          "text": "NSScreen"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/main",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mainScreen"
        }
      ],
      "role": "symbol",
      "title": "main",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/main"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/maximumExtendedDynamicRangeColorComponentValue": {
      "abstract": [
        {
          "text": "The current maximum color component value for the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumExtendedDynamicRangeColorComponentValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/maximumExtendedDynamicRangeColorComponentValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumExtendedDynamicRangeColorComponentValue"
        }
      ],
      "role": "symbol",
      "title": "maximumExtendedDynamicRangeColorComponentValue",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/maximumextendeddynamicrangecolorcomponentvalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/maximumFramesPerSecond": {
      "abstract": [
        {
          "text": "The maximum number of frames per second that the screen supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumFramesPerSecond"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/maximumFramesPerSecond",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumFramesPerSecond"
        }
      ],
      "role": "symbol",
      "title": "maximumFramesPerSecond",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/maximumframespersecond"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/maximumPotentialExtendedDynamicRangeColorComponentValue": {
      "abstract": [
        {
          "text": "The maximum possible color component value for the screen when it’s in extended dynamic range (EDR) mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumPotentialExtendedDynamicRangeColorComponentValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/maximumPotentialExtendedDynamicRangeColorComponentValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumPotentialExtendedDynamicRangeColorComponentValue"
        }
      ],
      "role": "symbol",
      "title": "maximumPotentialExtendedDynamicRangeColorComponentValue",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/maximumpotentialextendeddynamicrangecolorcomponentvalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/maximumReferenceExtendedDynamicRangeColorComponentValue": {
      "abstract": [
        {
          "text": "The current maximum color component value for reference rendering to the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumReferenceExtendedDynamicRangeColorComponentValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/maximumReferenceExtendedDynamicRangeColorComponentValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumReferenceExtendedDynamicRangeColorComponentValue"
        }
      ],
      "role": "symbol",
      "title": "maximumReferenceExtendedDynamicRangeColorComponentValue",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/maximumreferenceextendeddynamicrangecolorcomponentvalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/maximumRefreshInterval": {
      "abstract": [
        {
          "text": "The largest refresh interval that the screen supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumRefreshInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/maximumRefreshInterval",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumRefreshInterval"
        }
      ],
      "role": "symbol",
      "title": "maximumRefreshInterval",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/maximumrefreshinterval"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/minimumRefreshInterval": {
      "abstract": [
        {
          "text": "The shortest refresh interval that the screen supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumRefreshInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/minimumRefreshInterval",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minimumRefreshInterval"
        }
      ],
      "role": "symbol",
      "title": "minimumRefreshInterval",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/minimumrefreshinterval"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/safeAreaInsets": {
      "abstract": [
        {
          "text": "The distances from the screen’s edges at which content isn’t obscured.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "safeAreaInsets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSEdgeInsets",
          "text": "NSEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/safeAreaInsets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "safeAreaInsets"
        }
      ],
      "role": "symbol",
      "title": "safeAreaInsets",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/safeareainsets"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/screens": {
      "abstract": [
        {
          "text": "Returns an array of screen objects representing all of the screens available on the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screens"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSScreen",
          "text": "NSScreen"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/screens",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "screens"
        }
      ],
      "role": "symbol",
      "title": "screens",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/screens"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/screensHaveSeparateSpaces": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether each screen can have its own set of spaces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screensHaveSeparateSpaces"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/screensHaveSeparateSpaces",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "screensHaveSeparateSpaces"
        }
      ],
      "role": "symbol",
      "title": "screensHaveSeparateSpaces",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/screenshaveseparatespaces"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/supportedWindowDepths": {
      "abstract": [
        {
          "text": "A zero-terminated array of the window depths supported by the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedWindowDepths"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowDepth",
          "text": "Depth"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/supportedWindowDepths",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedWindowDepths"
        }
      ],
      "role": "symbol",
      "title": "supportedWindowDepths",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/supportedwindowdepths"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/userSpaceScaleFactor": {
      "abstract": [
        {
          "text": "Returns the scaling factor from user space to device space on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "userSpaceScaleFactor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/userSpaceScaleFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userSpaceScaleFactor"
        }
      ],
      "role": "symbol",
      "title": "userSpaceScaleFactor",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/userspacescalefactor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/visibleFrame": {
      "abstract": [
        {
          "text": "The current location and dimensions of the visible screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visibleFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/visibleFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "visibleFrame"
        }
      ],
      "role": "symbol",
      "title": "visibleFrame",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/visibleframe"
    },
    "doc://com.apple.documentation/documentation/coregraphics/quartz_display_services": {
      "abstract": [
        {
          "text": "Provides direct access to features in the macOS window server for configuring and controlling display hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coregraphics/quartz_display_services",
      "kind": "article",
      "role": "article",
      "title": "Quartz Display Services",
      "type": "topic",
      "url": "/documentation/coregraphics/quartz_display_services"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Getting-Screen-Objects",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/main",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/deepest",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/screens"
      ],
      "title": "Getting Screen Objects"
    },
    {
      "anchor": "Getting-Screen-Information",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/depth",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/frame",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/supportedWindowDepths",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/deviceDescription",
        "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/colorSpace",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/localizedName",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/canRepresent(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDisplayGamut",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/screensHaveSeparateSpaces"
      ],
      "title": "Getting Screen Information"
    },
    {
      "anchor": "Converting-Between-Screen-and-Backing-Coordinates",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/backingAlignedRect(_:options:)",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/backingScaleFactor",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/convertRectFromBacking(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/convertRectToBacking(_:)"
      ],
      "title": "Converting Between Screen and Backing Coordinates"
    },
    {
      "anchor": "Getting-the-Visible-Portion-of-the-Screen",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/visibleFrame",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/safeAreaInsets",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/auxiliaryTopLeftArea-uglc",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/auxiliaryTopRightArea-gr2n"
      ],
      "title": "Getting the Visible Portion of the Screen"
    },
    {
      "anchor": "Getting-Extended-Dynamic-Range-Details",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/maximumPotentialExtendedDynamicRangeColorComponentValue",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/maximumExtendedDynamicRangeColorComponentValue",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/maximumReferenceExtendedDynamicRangeColorComponentValue"
      ],
      "title": "Getting Extended Dynamic Range Details"
    },
    {
      "anchor": "Getting-Variable-Refresh-Rate-Details",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/maximumFramesPerSecond",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/minimumRefreshInterval",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/maximumRefreshInterval",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/displayUpdateGranularity",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/lastDisplayUpdateTimestamp"
      ],
      "title": "Getting Variable Refresh Rate Details"
    },
    {
      "anchor": "Receiving-Screen-Related-Notifications",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/colorSpaceDidChangeNotification"
      ],
      "title": "Receiving Screen-Related Notifications"
    },
    {
      "anchor": "Synchronizing-with-the-displays-refresh-rate",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/displayLink(target:selector:)"
      ],
      "title": "Synchronizing with the display’s refresh rate"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSScreen"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-Screen-Objects",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/main",
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/deepest",
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/screens"
              ],
              "title": "Getting Screen Objects"
            },
            {
              "anchor": "Getting-Screen-Information",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/depth",
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/frame",
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/supportedWindowDepths",
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/deviceDescription",
                "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/userSpaceScaleFactor",
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/colorSpace",
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/localizedName",
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/canRepresent(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDisplayGamut",
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/screensHaveSeparateSpaces"
              ],
              "title": "Getting Screen Information"
            },
            {
              "anchor": "Converting-Between-Screen-and-Backing-Coordinates",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/backingAlignedRect(_:options:)",
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/backingScaleFactor",
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/convertRectFromBacking(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/convertRectToBacking(_:)"
              ],
              "title": "Converting Between Screen and Backing Coordinates"
            },
            {
              "anchor": "Getting-the-Visible-Portion-of-the-Screen",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/visibleFrame",
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/safeAreaInsets"
              ],
              "title": "Getting the Visible Portion of the Screen"
            },
            {
              "anchor": "Getting-Extended-Dynamic-Range-Details",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/maximumPotentialExtendedDynamicRangeColorComponentValue",
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/maximumExtendedDynamicRangeColorComponentValue",
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/maximumReferenceExtendedDynamicRangeColorComponentValue"
              ],
              "title": "Getting Extended Dynamic Range Details"
            },
            {
              "anchor": "Getting-Variable-Refresh-Rate-Details",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/maximumFramesPerSecond",
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/minimumRefreshInterval",
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/maximumRefreshInterval",
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/displayUpdateGranularity",
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/lastDisplayUpdateTimestamp"
              ],
              "title": "Getting Variable Refresh Rate Details"
            },
            {
              "anchor": "Receiving-Screen-Related-Notifications",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/colorSpaceDidChangeNotification"
              ],
              "title": "Receiving Screen-Related Notifications"
            },
            {
              "anchor": "Synchronizing-with-the-displays-refresh-rate",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/displayLink(target:selector:)"
              ],
              "title": "Synchronizing with the display’s refresh rate"
            },
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/auxiliaryTopLeftArea-4ow3p",
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/auxiliaryTopRightArea-6gb2v"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSScreen"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1frame/title",
          "value": "frame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1frame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "frame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1displayUpdateGranularity/title",
          "value": "displayUpdateGranularity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1displayUpdateGranularity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayUpdateGranularity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1visibleFrame/title",
          "value": "visibleFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1visibleFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "visibleFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1displayLink(target:selector:)/title",
          "value": "displayLinkWithTarget:selector:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1displayLink(target:selector:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "displayLinkWithTarget:selector:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1convertRectFromBacking(_:)/title",
          "value": "convertRectFromBacking:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1convertRectFromBacking(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertRectFromBacking:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1maximumFramesPerSecond/title",
          "value": "maximumFramesPerSecond"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1maximumFramesPerSecond/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumFramesPerSecond"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1minimumRefreshInterval/title",
          "value": "minimumRefreshInterval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1minimumRefreshInterval/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minimumRefreshInterval"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1convertRectToBacking(_:)/title",
          "value": "convertRectToBacking:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1convertRectToBacking(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertRectToBacking:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1main/title",
          "value": "mainScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1main/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mainScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1colorSpace/title",
          "value": "colorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1colorSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "colorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1canRepresent(_:)/title",
          "value": "canRepresentDisplayGamut:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1canRepresent(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "canRepresentDisplayGamut:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1maximumRefreshInterval/title",
          "value": "maximumRefreshInterval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1maximumRefreshInterval/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumRefreshInterval"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1colorSpaceDidChangeNotification/title",
          "value": "NSScreenColorSpaceDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1colorSpaceDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScreenColorSpaceDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1maximumPotentialExtendedDynamicRangeColorComponentValue/title",
          "value": "maximumPotentialExtendedDynamicRangeColorComponentValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1maximumPotentialExtendedDynamicRangeColorComponentValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumPotentialExtendedDynamicRangeColorComponentValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1screens/title",
          "value": "screens"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1screens/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "screens"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1depth/title",
          "value": "depth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1depth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "depth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1localizedName/title",
          "value": "localizedName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1localizedName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1lastDisplayUpdateTimestamp/title",
          "value": "lastDisplayUpdateTimestamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1lastDisplayUpdateTimestamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lastDisplayUpdateTimestamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1supportedWindowDepths/title",
          "value": "supportedWindowDepths"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1supportedWindowDepths/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportedWindowDepths"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1screensHaveSeparateSpaces/title",
          "value": "screensHaveSeparateSpaces"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1screensHaveSeparateSpaces/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "screensHaveSeparateSpaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1maximumExtendedDynamicRangeColorComponentValue/title",
          "value": "maximumExtendedDynamicRangeColorComponentValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1maximumExtendedDynamicRangeColorComponentValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumExtendedDynamicRangeColorComponentValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeviceDescriptionKey/title",
          "value": "NSDeviceDescriptionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeviceDescriptionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeviceDescriptionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeviceDescriptionKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeviceDescriptionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1safeAreaInsets/title",
          "value": "safeAreaInsets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1safeAreaInsets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "safeAreaInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1deviceDescription/title",
          "value": "deviceDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1deviceDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deviceDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/title",
          "value": "NSApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1shared/title",
          "value": "sharedApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1shared/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sharedApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1backingScaleFactor/title",
          "value": "backingScaleFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1backingScaleFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backingScaleFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDisplayGamut/title",
          "value": "NSDisplayGamut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDisplayGamut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDisplayGamut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDisplayGamut/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDisplayGamut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen/title",
          "value": "NSScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1backingAlignedRect(_:options:)/title",
          "value": "backingAlignedRect:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1backingAlignedRect(_:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "backingAlignedRect:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1deepest/title",
          "value": "deepestScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1deepest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deepestScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1maximumReferenceExtendedDynamicRangeColorComponentValue/title",
          "value": "maximumReferenceExtendedDynamicRangeColorComponentValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1maximumReferenceExtendedDynamicRangeColorComponentValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumReferenceExtendedDynamicRangeColorComponentValue"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsscreen"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsscreen"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
