{
  "abstract": [
    {
      "text": "An abstract class that describes the layout of items within a scrubber control.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSScrubberLayout",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSScrubberLayout"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSScrubberLayout"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSScrubberLayout"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSScrubberLayout"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To determine the layout of items in a scrubber, use one of the built-in subclasses (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberProportionalLayout",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberFlowLayout",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "), or create a custom subclass to implement your own layout.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberFlowLayout": {
      "abstract": [
        {
          "text": "A concrete layout object that arranges items end-to-end in a linear strip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScrubberFlowLayout"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberFlowLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrubberFlowLayout"
        }
      ],
      "role": "symbol",
      "title": "NSScrubberFlowLayout",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberflowlayout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberFlowLayoutDelegate": {
      "abstract": [
        {
          "text": "A protocol that a scrubber delegate can adopt to provide the size of an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScrubberFlowLayoutDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberFlowLayoutDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrubberFlowLayoutDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSScrubberFlowLayoutDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberflowlayoutdelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout": {
      "abstract": [
        {
          "text": "An abstract class that describes the layout of items within a scrubber control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScrubberLayout"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrubberLayout"
        }
      ],
      "role": "symbol",
      "title": "NSScrubberLayout",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberlayout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/automaticallyMirrorsInRightToLeftLayout": {
      "abstract": [
        {
          "text": "Determines whether the scrubber mirrors its layout for right-to-left layouts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automaticallyMirrorsInRightToLeftLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/automaticallyMirrorsInRightToLeftLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticallyMirrorsInRightToLeftLayout"
        }
      ],
      "role": "symbol",
      "title": "automaticallyMirrorsInRightToLeftLayout",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberlayout/automaticallymirrorsinrighttoleftlayout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/init()": {
      "abstract": [
        {
          "text": "Initializes and returns a newly allocated scrubber layout object from code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberlayout/init()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/init(coder:)": {
      "abstract": [
        {
          "text": "Initializes and returns a newly allocated scrubber layout object from a storyboard or nib file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/init(coder:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCoder:"
        }
      ],
      "role": "symbol",
      "title": "init(coder:)",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberlayout/init(coder:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/invalidateLayout()": {
      "abstract": [
        {
          "text": "Signals that the layout has been invalidated, and that the scrubber control should perform a new layout pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidateLayout"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/invalidateLayout()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "invalidateLayout"
        }
      ],
      "role": "symbol",
      "title": "invalidateLayout()",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberlayout/invalidatelayout()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/layoutAttributesClass": {
      "abstract": [
        {
          "text": "A property containing a class that describes layout attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutAttributesClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8AnyClassa",
          "text": "AnyClass"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/layoutAttributesClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layoutAttributesClass"
        }
      ],
      "role": "symbol",
      "title": "layoutAttributesClass",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberlayout/layoutattributesclass"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/layoutAttributesForItem(at:)": {
      "abstract": [
        {
          "text": "The layout attributes for the item with the specified index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutAttributesForItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSScrubberLayoutAttributes",
          "text": "NSScrubberLayoutAttributes"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/layoutAttributesForItem(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layoutAttributesForItemAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "layoutAttributesForItem(at:)",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberlayout/layoutattributesforitem(at:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/layoutAttributesForItems(in:)": {
      "abstract": [
        {
          "text": "The set of layout attributes for all items within the provided rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutAttributesForItems"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSScrubberLayoutAttributes",
          "text": "NSScrubberLayoutAttributes"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/layoutAttributesForItems(in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layoutAttributesForItemsInRect:"
        }
      ],
      "role": "symbol",
      "title": "layoutAttributesForItems(in:)",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberlayout/layoutattributesforitems(in:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/prepare()": {
      "abstract": [
        {
          "text": "Gives you an opportunity to perform layout calculations when the scrubber’s layout is invalidated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prepare"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/prepare()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prepareLayout"
        }
      ],
      "role": "symbol",
      "title": "prepare()",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberlayout/prepare()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/scrubber": {
      "abstract": [
        {
          "text": "The scrubber control that this layout is assigned to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrubber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSScrubber",
          "text": "NSScrubber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/scrubber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrubber"
        }
      ],
      "role": "symbol",
      "title": "scrubber",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberlayout/scrubber"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/scrubberContentSize": {
      "abstract": [
        {
          "text": "The size required to contain all elements within the scrubber.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrubberContentSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/scrubberContentSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrubberContentSize"
        }
      ],
      "role": "symbol",
      "title": "scrubberContentSize",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberlayout/scrubbercontentsize"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/shouldInvalidateLayoutForChange(fromVisibleRect:toVisibleRect:)": {
      "abstract": [
        {
          "text": "Determines whether the scrubber should refresh its layout in response to a change of its visible region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldInvalidateLayoutForChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "fromVisibleRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toVisibleRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/shouldInvalidateLayoutForChange(fromVisibleRect:toVisibleRect:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldInvalidateLayoutForChangeFromVisibleRect:toVisibleRect:"
        }
      ],
      "role": "symbol",
      "title": "shouldInvalidateLayoutForChange(fromVisibleRect:toVisibleRect:)",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberlayout/shouldinvalidatelayoutforchange(fromvisiblerect:tovisiblerect:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/shouldInvalidateLayoutForHighlightChange": {
      "abstract": [
        {
          "text": "Determines whether the scrubber should refresh its layout when an item is highlighted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldInvalidateLayoutForHighlightChange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/shouldInvalidateLayoutForHighlightChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldInvalidateLayoutForHighlightChange"
        }
      ],
      "role": "symbol",
      "title": "shouldInvalidateLayoutForHighlightChange",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberlayout/shouldinvalidatelayoutforhighlightchange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/shouldInvalidateLayoutForSelectionChange": {
      "abstract": [
        {
          "text": "Determines whether the scrubber should refresh its layout when the selection changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldInvalidateLayoutForSelectionChange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/shouldInvalidateLayoutForSelectionChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldInvalidateLayoutForSelectionChange"
        }
      ],
      "role": "symbol",
      "title": "shouldInvalidateLayoutForSelectionChange",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberlayout/shouldinvalidatelayoutforselectionchange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/visibleRect": {
      "abstract": [
        {
          "text": "The currently visible rectangle, in the coordinate space of the scrubber content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visibleRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/visibleRect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "visibleRect"
        }
      ],
      "role": "symbol",
      "title": "visibleRect",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberlayout/visiblerect"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayoutAttributes": {
      "abstract": [
        {
          "text": "The layout of a scrubber item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScrubberLayoutAttributes"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayoutAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrubberLayoutAttributes"
        }
      ],
      "role": "symbol",
      "title": "NSScrubberLayoutAttributes",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberlayoutattributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberProportionalLayout": {
      "abstract": [
        {
          "text": "A concrete layout object that sizes each item to some fraction of the scrubber’s visible size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScrubberProportionalLayout"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberProportionalLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrubberProportionalLayout"
        }
      ],
      "role": "symbol",
      "title": "NSScrubberProportionalLayout",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberproportionallayout"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberFlowLayout",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberProportionalLayout"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Scrubber-layouts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberFlowLayout",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberFlowLayoutDelegate",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberProportionalLayout",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayoutAttributes"
      ],
      "title": "Scrubber layouts"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-scrubber-layout",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/init()",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/init(coder:)"
      ],
      "title": "Creating a scrubber layout"
    },
    {
      "anchor": "Configuring-a-scrubber-layout",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/layoutAttributesClass",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/scrubber",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/visibleRect",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/invalidateLayout()"
      ],
      "title": "Configuring a scrubber layout"
    },
    {
      "anchor": "Subclassing-a-scrubber-layout",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/prepare()",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/scrubberContentSize",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/layoutAttributesForItem(at:)",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/layoutAttributesForItems(in:)",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/shouldInvalidateLayoutForSelectionChange",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/shouldInvalidateLayoutForHighlightChange",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/shouldInvalidateLayoutForChange(fromVisibleRect:toVisibleRect:)",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/automaticallyMirrorsInRightToLeftLayout"
      ],
      "title": "Subclassing a scrubber layout"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12.2",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSScrubberLayout"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-scrubber-layout",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/init()",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/init(coder:)"
              ],
              "title": "Creating a scrubber layout"
            },
            {
              "anchor": "Configuring-a-scrubber-layout",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/layoutAttributesClass",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/scrubber",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/visibleRect",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/invalidateLayout()"
              ],
              "title": "Configuring a scrubber layout"
            },
            {
              "anchor": "Subclassing-a-scrubber-layout",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/prepare()",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/scrubberContentSize",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/layoutAttributesForItem(at:)",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/layoutAttributesForItems(in:)",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/shouldInvalidateLayoutForSelectionChange",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/shouldInvalidateLayoutForHighlightChange",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/shouldInvalidateLayoutForChange(fromVisibleRect:toVisibleRect:)",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/automaticallyMirrorsInRightToLeftLayout"
              ],
              "title": "Subclassing a scrubber layout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberFlowLayout",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberProportionalLayout"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Scrubber-layouts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberFlowLayout",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberFlowLayoutDelegate",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberProportionalLayout",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayoutAttributes"
              ],
              "title": "Scrubber layouts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSScrubberLayout"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1shouldInvalidateLayoutForHighlightChange/title",
          "value": "shouldInvalidateLayoutForHighlightChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1shouldInvalidateLayoutForHighlightChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shouldInvalidateLayoutForHighlightChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1scrubberContentSize/title",
          "value": "scrubberContentSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1scrubberContentSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scrubberContentSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1init(coder:)/title",
          "value": "initWithCoder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1init(coder:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCoder:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1automaticallyMirrorsInRightToLeftLayout/title",
          "value": "automaticallyMirrorsInRightToLeftLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1automaticallyMirrorsInRightToLeftLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticallyMirrorsInRightToLeftLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1prepare()/title",
          "value": "prepareLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1prepare()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "prepareLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout/title",
          "value": "NSScrubberLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberFlowLayout/title",
          "value": "NSScrubberFlowLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberFlowLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberFlowLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberFlowLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberFlowLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1visibleRect/title",
          "value": "visibleRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1visibleRect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "visibleRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberProportionalLayout/title",
          "value": "NSScrubberProportionalLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberProportionalLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberProportionalLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberProportionalLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberProportionalLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberFlowLayoutDelegate/title",
          "value": "NSScrubberFlowLayoutDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberFlowLayoutDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberFlowLayoutDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberFlowLayoutDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberFlowLayoutDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1layoutAttributesClass/title",
          "value": "layoutAttributesClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1layoutAttributesClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "layoutAttributesClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1layoutAttributesForItems(in:)/title",
          "value": "layoutAttributesForItemsInRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1layoutAttributesForItems(in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "layoutAttributesForItemsInRect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1invalidateLayout()/title",
          "value": "invalidateLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1invalidateLayout()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "invalidateLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1layoutAttributesForItem(at:)/title",
          "value": "layoutAttributesForItemAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1layoutAttributesForItem(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "layoutAttributesForItemAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1shouldInvalidateLayoutForSelectionChange/title",
          "value": "shouldInvalidateLayoutForSelectionChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1shouldInvalidateLayoutForSelectionChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shouldInvalidateLayoutForSelectionChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1scrubber/title",
          "value": "scrubber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1scrubber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scrubber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayoutAttributes/title",
          "value": "NSScrubberLayoutAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayoutAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayoutAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1shouldInvalidateLayoutForChange(fromVisibleRect:toVisibleRect:)/title",
          "value": "shouldInvalidateLayoutForChangeFromVisibleRect:toVisibleRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1shouldInvalidateLayoutForChange(fromVisibleRect:toVisibleRect:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "shouldInvalidateLayoutForChangeFromVisibleRect:toVisibleRect:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsscrubberlayout"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsscrubberlayout"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
