{
  "abstract": [
    {
      "text": "The layout of a scrubber item.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayoutAttributes"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSScrubberLayoutAttributes",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSScrubberLayoutAttributes"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSScrubberLayoutAttributes"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSScrubberLayoutAttributes"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSScrubberLayoutAttributes"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A layout attributes object is the model for the layout of a single item in a scrubber control.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you require model attributes in addition to those provided by this class, create a subclass and add appropriate attributes. Subclasses must implement ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobjectprotocol/1418795-isequal",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobjectprotocol/1418859-hash",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nscopying",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberFlowLayout": {
      "abstract": [
        {
          "text": "A concrete layout object that arranges items end-to-end in a linear strip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScrubberFlowLayout"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberFlowLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrubberFlowLayout"
        }
      ],
      "role": "symbol",
      "title": "NSScrubberFlowLayout",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberflowlayout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberFlowLayoutDelegate": {
      "abstract": [
        {
          "text": "A protocol that a scrubber delegate can adopt to provide the size of an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScrubberFlowLayoutDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberFlowLayoutDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrubberFlowLayoutDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSScrubberFlowLayoutDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberflowlayoutdelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout": {
      "abstract": [
        {
          "text": "An abstract class that describes the layout of items within a scrubber control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScrubberLayout"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrubberLayout"
        }
      ],
      "role": "symbol",
      "title": "NSScrubberLayout",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberlayout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayoutAttributes": {
      "abstract": [
        {
          "text": "The layout of a scrubber item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScrubberLayoutAttributes"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayoutAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrubberLayoutAttributes"
        }
      ],
      "role": "symbol",
      "title": "NSScrubberLayoutAttributes",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberlayoutattributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayoutAttributes/alpha": {
      "abstract": [
        {
          "text": "The item’s alpha value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayoutAttributes/alpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "alpha"
        }
      ],
      "role": "symbol",
      "title": "alpha",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberlayoutattributes/alpha"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayoutAttributes/frame": {
      "abstract": [
        {
          "text": "The frame of the scrubber item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayoutAttributes/frame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "frame"
        }
      ],
      "role": "symbol",
      "title": "frame",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberlayoutattributes/frame"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayoutAttributes/init(forItemAt:)": {
      "abstract": [
        {
          "text": "Creates a new layout attributes object for the specified scrubber item index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forItemAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayoutAttributes/init(forItemAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layoutAttributesForItemAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "init(forItemAt:)",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberlayoutattributes/init(foritemat:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayoutAttributes/itemIndex": {
      "abstract": [
        {
          "text": "The index of the scrubber item that is represented by the item’s layout attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "itemIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayoutAttributes/itemIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "itemIndex"
        }
      ],
      "role": "symbol",
      "title": "itemIndex",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberlayoutattributes/itemindex"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberProportionalLayout": {
      "abstract": [
        {
          "text": "A concrete layout object that sizes each item to some fraction of the scrubber’s visible size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScrubberProportionalLayout"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberProportionalLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrubberProportionalLayout"
        }
      ],
      "role": "symbol",
      "title": "NSScrubberProportionalLayout",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberproportionallayout"
    },
    "doc://com.apple.documentation/documentation/foundation/nscopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nscopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobjectprotocol/1418795-isequal": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the receiver and a given object are equal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "isEqual"
        },
        {
          "kind": "text",
          "text": "(Any?) -> Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobjectprotocol/1418795-isequal",
      "kind": "symbol",
      "role": "symbol",
      "title": "isEqual(_:)",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol/1418795-isequal"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobjectprotocol/1418859-hash": {
      "abstract": [
        {
          "text": "Returns an integer that can be used as a table address in a hash table structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "hash"
        },
        {
          "kind": "text",
          "text": ": Int"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobjectprotocol/1418859-hash",
      "kind": "symbol",
      "role": "symbol",
      "title": "hash",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol/1418859-hash"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Scrubber-layouts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberFlowLayout",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberFlowLayoutDelegate",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberProportionalLayout",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout"
      ],
      "title": "Scrubber layouts"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-layout-attributes",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayoutAttributes/init(forItemAt:)"
      ],
      "title": "Creating layout attributes"
    },
    {
      "anchor": "Controlling-the-layout",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayoutAttributes/alpha",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayoutAttributes/frame",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayoutAttributes/itemIndex"
      ],
      "title": "Controlling the layout"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12.2",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSScrubberLayoutAttributes"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-layout-attributes",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayoutAttributes/init(forItemAt:)"
              ],
              "title": "Creating layout attributes"
            },
            {
              "anchor": "Controlling-the-layout",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayoutAttributes/alpha",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayoutAttributes/frame",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayoutAttributes/itemIndex"
              ],
              "title": "Controlling the layout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Scrubber-layouts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberFlowLayout",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberFlowLayoutDelegate",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberProportionalLayout",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout"
              ],
              "title": "Scrubber layouts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSScrubberLayoutAttributes"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout/title",
          "value": "NSScrubberLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberProportionalLayout/title",
          "value": "NSScrubberProportionalLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberProportionalLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberProportionalLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberProportionalLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberProportionalLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayoutAttributes~1frame/title",
          "value": "frame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayoutAttributes~1frame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "frame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobjectprotocol~11418795-isequal/title",
          "value": "isEqual:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayoutAttributes~1alpha/title",
          "value": "alpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayoutAttributes~1alpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "alpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberFlowLayout/title",
          "value": "NSScrubberFlowLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberFlowLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberFlowLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberFlowLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberFlowLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberFlowLayoutDelegate/title",
          "value": "NSScrubberFlowLayoutDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberFlowLayoutDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberFlowLayoutDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberFlowLayoutDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberFlowLayoutDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayoutAttributes~1init(forItemAt:)/title",
          "value": "layoutAttributesForItemAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayoutAttributes~1init(forItemAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "layoutAttributesForItemAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayoutAttributes/title",
          "value": "NSScrubberLayoutAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayoutAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayoutAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayoutAttributes~1itemIndex/title",
          "value": "itemIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayoutAttributes~1itemIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "itemIndex"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsscrubberlayoutattributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsscrubberlayoutattributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
