{
  "abstract": [
    {
      "text": "A set of methods that a scrubber data source object implements to provide items to the scrubber from an associated data collection in your app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSScrubberDataSource"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSScrubberDataSource",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSScrubberDataSource"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSScrubberDataSource"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NSScrubberDataSource"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSScrubberDataSource"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubber": {
      "abstract": [
        {
          "text": "A customizable item picker control for the Touch Bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScrubber"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrubber"
        }
      ],
      "role": "symbol",
      "title": "NSScrubber",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubber"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberDataSource": {
      "abstract": [
        {
          "text": "A set of methods that a scrubber data source object implements to provide items to the scrubber from an associated data collection in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScrubberDataSource"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberDataSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrubberDataSource"
        }
      ],
      "role": "symbol",
      "title": "NSScrubberDataSource",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberdatasource"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberDataSource/numberOfItems(for:)": {
      "abstract": [
        {
          "text": "Asks the data source for the number of items in the scrubber.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfItems"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSScrubber",
          "text": "NSScrubber"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberDataSource/numberOfItems(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfItemsForScrubber:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "numberOfItems(for:)",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberdatasource/numberofitems(for:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberDataSource/scrubber(_:viewForItemAt:)": {
      "abstract": [
        {
          "text": "Asks the data source object for the view the corresponds to the specified item in the scrubber.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrubber"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSScrubber",
          "text": "NSScrubber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "viewForItemAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSScrubberItemView",
          "text": "NSScrubberItemView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberDataSource/scrubber(_:viewForItemAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrubber:viewForItemAtIndex:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "scrubber(_:viewForItemAt:)",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberdatasource/scrubber(_:viewforitemat:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberDelegate": {
      "abstract": [
        {
          "text": "A set of methods that a scrubber delegate implements to respond to user interactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScrubberDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrubberDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSScrubberDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberdelegate"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Scrubbers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScrubber",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberDelegate"
      ],
      "title": "Scrubbers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-scrubber-metrics",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberDataSource/numberOfItems(for:)"
      ],
      "title": "Getting the scrubber metrics"
    },
    {
      "anchor": "Getting-views-for-items",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberDataSource/scrubber(_:viewForItemAt:)"
      ],
      "title": "Getting views for items"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSScrubberDataSource"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-scrubber-metrics",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberDataSource/numberOfItems(for:)"
              ],
              "title": "Getting the scrubber metrics"
            },
            {
              "anchor": "Getting-views-for-items",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberDataSource/scrubber(_:viewForItemAt:)"
              ],
              "title": "Getting views for items"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Scrubbers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScrubber",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberDelegate"
              ],
              "title": "Scrubbers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSScrubberDataSource"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubber/title",
          "value": "NSScrubber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubber/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberDelegate/title",
          "value": "NSScrubberDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberDataSource/title",
          "value": "NSScrubberDataSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberDataSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberDataSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberDataSource~1numberOfItems(for:)/title",
          "value": "numberOfItemsForScrubber:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberDataSource~1numberOfItems(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "numberOfItemsForScrubber:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberDataSource~1scrubber(_:viewForItemAt:)/title",
          "value": "scrubber:viewForItemAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberDataSource~1scrubber(_:viewForItemAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scrubber:viewForItemAtIndex:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsscrubberdatasource"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsscrubberdatasource"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
