{
  "abstract": [
    {
      "text": "A text field optimized for performing text-based searches.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSSearchField"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSSearchField",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSSearchField"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSSearchField"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSSearchField"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSSearchField"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " provides a customized text field for entering search data. The class also provides a search button, a cancel button, and a pop-up icon menu for listing recent search strings and custom search categories.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object wraps an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchFieldCell",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. The cell provides access to most search field attributes and a comprehensive programmatic interface for manipulating the search field. You can use an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to manipulate some aspects of the search field.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For additional information about search fields and how to implement them, see the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchFieldCell",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol": {
      "abstract": [
        {
          "text": "A role-based protocol that declares the minimum interface necessary to interact with an assistive app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityElementProtocol"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityElementProtocol"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityElementProtocol",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityelementprotocol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText": {
      "abstract": [
        {
          "text": "A role-based protocol that declares the minimum interface necessary for an accessibility element to act as navigable static text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityNavigableStaticText"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityNavigableStaticText"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityNavigableStaticText",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitynavigablestatictext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol": {
      "abstract": [
        {
          "text": "The complete list of properties and methods for accessible elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityProtocol",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText": {
      "abstract": [
        {
          "text": "A role-based protocol that declares the minimum interface necessary for an accessibility element to act as static text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityStaticText"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityStaticText"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityStaticText",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitystatictext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAnimatablePropertyContainer": {
      "abstract": [
        {
          "text": "A set of methods that defines a way to add animation to an existing class with a minimum of API impact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAnimatablePropertyContainer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAnimatablePropertyContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAnimatablePropertyContainer"
        }
      ],
      "role": "symbol",
      "title": "NSAnimatablePropertyContainer",
      "type": "topic",
      "url": "/documentation/appkit/nsanimatablepropertycontainer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppearanceCustomization": {
      "abstract": [
        {
          "text": "A set of methods for getting and setting the appearance attributes of a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAppearanceCustomization"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppearanceCustomization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppearanceCustomization"
        }
      ],
      "role": "symbol",
      "title": "NSAppearanceCustomization",
      "type": "topic",
      "url": "/documentation/appkit/nsappearancecustomization"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination": {
      "abstract": [
        {
          "text": "A set of methods that the destination object (or recipient) of a dragged image must implement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDraggingDestination"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDraggingDestination"
        }
      ],
      "role": "symbol",
      "title": "NSDraggingDestination",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingdestination"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchField": {
      "abstract": [
        {
          "text": "A text field optimized for performing text-based searches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSearchField"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSearchField"
        }
      ],
      "role": "symbol",
      "title": "NSSearchField",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfield"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchField/RecentsAutosaveName-swift.typealias": {
      "abstract": [
        {
          "text": "The string that stores the name under which a search field automatically archives a list of recent search strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RecentsAutosaveName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField/RecentsAutosaveName-swift.typealias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RecentsAutosaveName"
        }
      ],
      "role": "symbol",
      "title": "NSSearchField.RecentsAutosaveName",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfield/recentsautosavename-swift.typealias"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchField/cancelButtonBounds": {
      "abstract": [
        {
          "text": "The rectangle for the cancel button within the bounds of the search field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelButtonBounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField/cancelButtonBounds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancelButtonBounds"
        }
      ],
      "role": "symbol",
      "title": "cancelButtonBounds",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfield/cancelbuttonbounds"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchField/centersPlaceholder": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the search field’s components are centered within the control.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centersPlaceholder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField/centersPlaceholder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "centersPlaceholder"
        }
      ],
      "role": "symbol",
      "title": "centersPlaceholder",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfield/centersplaceholder"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchField/clearRecentsMenuItemTag": {
      "abstract": [
        {
          "text": "The menu item for clearing the current set of recent string searches in the menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clearRecentsMenuItemTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField/clearRecentsMenuItemTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSearchFieldClearRecentsMenuItemTag"
        }
      ],
      "role": "symbol",
      "title": "clearRecentsMenuItemTag",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfield/clearrecentsmenuitemtag"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchField/delegate": {
      "abstract": [
        {
          "text": "The delegate for the search field, or ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": " if the search field doesn’t have a delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSSearchFieldDelegate",
          "text": "NSSearchFieldDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfield/delegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchField/maximumRecents": {
      "abstract": [
        {
          "text": "The maximum number of search strings that can appear in the search menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumRecents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField/maximumRecents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumRecents"
        }
      ],
      "role": "symbol",
      "title": "maximumRecents",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfield/maximumrecents"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchField/noRecentsMenuItemTag": {
      "abstract": [
        {
          "text": "The menu item that describes a lack of recent search strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noRecentsMenuItemTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField/noRecentsMenuItemTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSearchFieldNoRecentsMenuItemTag"
        }
      ],
      "role": "symbol",
      "title": "noRecentsMenuItemTag",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfield/norecentsmenuitemtag"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchField/recentSearches": {
      "abstract": [
        {
          "text": "The list of recent search strings for the control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recentSearches"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField/recentSearches",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recentSearches"
        }
      ],
      "role": "symbol",
      "title": "recentSearches",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfield/recentsearches"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchField/recentsAutosaveName-swift.property": {
      "abstract": [
        {
          "text": "The name under which the search field automatically archives the list of recent search strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recentsAutosaveName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSearchField",
          "text": "NSSearchField"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSearchFieldRecentsAutosaveName",
          "text": "RecentsAutosaveName"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField/recentsAutosaveName-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recentsAutosaveName"
        }
      ],
      "role": "symbol",
      "title": "recentsAutosaveName",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfield/recentsautosavename-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchField/recentsMenuItemTag": {
      "abstract": [
        {
          "text": "The location of recent search strings in the “recents” menu group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recentsMenuItemTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField/recentsMenuItemTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSearchFieldRecentsMenuItemTag"
        }
      ],
      "role": "symbol",
      "title": "recentsMenuItemTag",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfield/recentsmenuitemtag"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchField/recentsTitleMenuItemTag": {
      "abstract": [
        {
          "text": "The menu item that provides the title of the menu group for recent search strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recentsTitleMenuItemTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField/recentsTitleMenuItemTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSearchFieldRecentsTitleMenuItemTag"
        }
      ],
      "role": "symbol",
      "title": "recentsTitleMenuItemTag",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfield/recentstitlemenuitemtag"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchField/rectForCancelButton(whenCentered:)": {
      "abstract": [
        {
          "text": "The rectangle for the cancel button within the bounds of the search field.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rectForCancelButton"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "whenCentered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField/rectForCancelButton(whenCentered:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rectForCancelButtonWhenCentered:"
        }
      ],
      "role": "symbol",
      "title": "rectForCancelButton(whenCentered:)",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfield/rectforcancelbutton(whencentered:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchField/rectForSearchButton(whenCentered:)": {
      "abstract": [
        {
          "text": "The rectangle for the search button within the bounds of the search field.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rectForSearchButton"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "whenCentered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField/rectForSearchButton(whenCentered:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rectForSearchButtonWhenCentered:"
        }
      ],
      "role": "symbol",
      "title": "rectForSearchButton(whenCentered:)",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfield/rectforsearchbutton(whencentered:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchField/rectForSearchText(whenCentered:)": {
      "abstract": [
        {
          "text": "The rectangle for the search text within the bounds of the field.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rectForSearchText"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "whenCentered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField/rectForSearchText(whenCentered:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rectForSearchTextWhenCentered:"
        }
      ],
      "role": "symbol",
      "title": "rectForSearchText(whenCentered:)",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfield/rectforsearchtext(whencentered:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchField/searchButtonBounds": {
      "abstract": [
        {
          "text": "The rectangle for the search button within the bounds of the search field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchButtonBounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField/searchButtonBounds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchButtonBounds"
        }
      ],
      "role": "symbol",
      "title": "searchButtonBounds",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfield/searchbuttonbounds"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchField/searchMenuTemplate": {
      "abstract": [
        {
          "text": "The menu object used to dynamically construct the search field’s pop-up icon menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchMenuTemplate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMenu",
          "text": "NSMenu"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField/searchMenuTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchMenuTemplate"
        }
      ],
      "role": "symbol",
      "title": "searchMenuTemplate",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfield/searchmenutemplate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchField/searchTextBounds": {
      "abstract": [
        {
          "text": "The rectangle for the search text within the bounds of the search field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchTextBounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField/searchTextBounds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchTextBounds"
        }
      ],
      "role": "symbol",
      "title": "searchTextBounds",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfield/searchtextbounds"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchField/sendsSearchStringImmediately": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the cell calls its action method immediately when an appropriate action occurs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendsSearchStringImmediately"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField/sendsSearchStringImmediately",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sendsSearchStringImmediately"
        }
      ],
      "role": "symbol",
      "title": "sendsSearchStringImmediately",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfield/sendssearchstringimmediately"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchField/sendsWholeSearchString": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the cell calls its search action method when the user clicks the search button or presses Return, or after each keystroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendsWholeSearchString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField/sendsWholeSearchString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sendsWholeSearchString"
        }
      ],
      "role": "symbol",
      "title": "sendsWholeSearchString",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfield/sendswholesearchstring"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchFieldCell": {
      "abstract": [
        {
          "text": "The programmatic interface for text fields that are used for text-based searches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSearchFieldCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchFieldCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSearchFieldCell"
        }
      ],
      "role": "symbol",
      "title": "NSSearchFieldCell",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfieldcell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchFieldDelegate": {
      "abstract": [
        {
          "text": "A protocol that a search field delegate can use to determine when a search started or ended.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSearchFieldDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchFieldDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSearchFieldDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSSearchFieldDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfielddelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding": {
      "abstract": [
        {
          "text": "Methods that responder subclasses implement to support key binding commands, such as inserting tabs and newlines, or moving the insertion point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStandardKeyBindingResponding"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStandardKeyBindingResponding"
        }
      ],
      "role": "symbol",
      "title": "NSStandardKeyBindingResponding",
      "type": "topic",
      "url": "/documentation/appkit/nsstandardkeybindingresponding"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContent": {
      "abstract": [
        {
          "text": "A protocol that describes specific kinds of input content types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextContent"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContent"
        }
      ],
      "role": "symbol",
      "title": "NSTextContent",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextField": {
      "abstract": [
        {
          "text": "Text the user can select or edit to send an action message to a target when the user presses the Return key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextField"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextField"
        }
      ],
      "role": "symbol",
      "title": "NSTextField",
      "type": "topic",
      "url": "/documentation/appkit/nstextfield"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTouchBarProvider": {
      "abstract": [
        {
          "text": "A protocol that an object adopts to create a bar object in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTouchBarProvider"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouchBarProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTouchBarProvider"
        }
      ],
      "role": "symbol",
      "title": "NSTouchBarProvider",
      "type": "topic",
      "url": "/documentation/appkit/nstouchbarprovider"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserActivityRestoring": {
      "abstract": [
        {
          "text": "A protocol that marks classes to restore the state of your app to continue a user activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserActivityRestoring"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserActivityRestoring",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUserActivityRestoring"
        }
      ],
      "role": "symbol",
      "title": "NSUserActivityRestoring",
      "type": "topic",
      "url": "/documentation/appkit/nsuseractivityrestoring"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification": {
      "abstract": [
        {
          "text": "A set of methods used to associate a unique identifier with objects in your user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserInterfaceItemIdentification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUserInterfaceItemIdentification"
        }
      ],
      "role": "symbol",
      "title": "NSUserInterfaceItemIdentification",
      "type": "topic",
      "url": "/documentation/appkit/nsuserinterfaceitemidentification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceValidations": {
      "abstract": [
        {
          "text": "A protocol that a custom class can adopt to manage the enabled state of a UI element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserInterfaceValidations"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceValidations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUserInterfaceValidations"
        }
      ],
      "role": "symbol",
      "title": "NSUserInterfaceValidations",
      "type": "topic",
      "url": "/documentation/appkit/nsuserinterfacevalidations"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextField"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText",
        "doc://com.apple.appkit/documentation/AppKit/NSAnimatablePropertyContainer",
        "doc://com.apple.appkit/documentation/AppKit/NSAppearanceCustomization",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContent",
        "doc://com.apple.appkit/documentation/AppKit/NSTouchBarProvider",
        "doc://com.apple.appkit/documentation/AppKit/NSUserActivityRestoring",
        "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification",
        "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceValidations",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Managing-Search",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSearchField/delegate",
        "doc://com.apple.appkit/documentation/AppKit/NSSearchFieldDelegate"
      ],
      "title": "Managing Search"
    },
    {
      "anchor": "Managing-Menu-Templates",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSearchField/searchMenuTemplate",
        "doc://com.apple.appkit/documentation/AppKit/NSSearchField/clearRecentsMenuItemTag",
        "doc://com.apple.appkit/documentation/AppKit/NSSearchField/noRecentsMenuItemTag",
        "doc://com.apple.appkit/documentation/AppKit/NSSearchField/recentsMenuItemTag",
        "doc://com.apple.appkit/documentation/AppKit/NSSearchField/recentsTitleMenuItemTag"
      ],
      "title": "Managing Menu Templates"
    },
    {
      "anchor": "Managing-Search-Modes",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSearchField/sendsSearchStringImmediately",
        "doc://com.apple.appkit/documentation/AppKit/NSSearchField/sendsWholeSearchString"
      ],
      "title": "Managing Search Modes"
    },
    {
      "anchor": "Managing-Recent-Searches",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSearchField/recentSearches",
        "doc://com.apple.appkit/documentation/AppKit/NSSearchField/maximumRecents",
        "doc://com.apple.appkit/documentation/AppKit/NSSearchField/recentsAutosaveName-swift.property",
        "doc://com.apple.appkit/documentation/AppKit/NSSearchField/RecentsAutosaveName-swift.typealias"
      ],
      "title": "Managing Recent Searches"
    },
    {
      "anchor": "Getting-Search-Field-Metrics",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSearchField/cancelButtonBounds",
        "doc://com.apple.appkit/documentation/AppKit/NSSearchField/searchButtonBounds",
        "doc://com.apple.appkit/documentation/AppKit/NSSearchField/searchTextBounds"
      ],
      "title": "Getting Search Field Metrics"
    },
    {
      "anchor": "Deprecated-Symbols",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSearchField/centersPlaceholder",
        "doc://com.apple.appkit/documentation/AppKit/NSSearchField/rectForCancelButton(whenCentered:)",
        "doc://com.apple.appkit/documentation/AppKit/NSSearchField/rectForSearchButton(whenCentered:)",
        "doc://com.apple.appkit/documentation/AppKit/NSSearchField/rectForSearchText(whenCentered:)"
      ],
      "title": "Deprecated Symbols"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSSearchField"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Managing-Search",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSearchField/delegate",
                "doc://com.apple.appkit/documentation/AppKit/NSSearchFieldDelegate"
              ],
              "title": "Managing Search"
            },
            {
              "anchor": "Managing-Menu-Templates",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSearchField/searchMenuTemplate",
                "doc://com.apple.appkit/documentation/AppKit/NSSearchField/clearRecentsMenuItemTag",
                "doc://com.apple.appkit/documentation/AppKit/NSSearchField/noRecentsMenuItemTag",
                "doc://com.apple.appkit/documentation/AppKit/NSSearchField/recentsMenuItemTag",
                "doc://com.apple.appkit/documentation/AppKit/NSSearchField/recentsTitleMenuItemTag"
              ],
              "title": "Managing Menu Templates"
            },
            {
              "anchor": "Managing-Search-Modes",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSearchField/sendsSearchStringImmediately",
                "doc://com.apple.appkit/documentation/AppKit/NSSearchField/sendsWholeSearchString"
              ],
              "title": "Managing Search Modes"
            },
            {
              "anchor": "Managing-Recent-Searches",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSearchField/recentSearches",
                "doc://com.apple.appkit/documentation/AppKit/NSSearchField/maximumRecents",
                "doc://com.apple.appkit/documentation/AppKit/NSSearchField/recentsAutosaveName-swift.property",
                "doc://com.apple.appkit/documentation/AppKit/NSSearchField/RecentsAutosaveName-swift.typealias"
              ],
              "title": "Managing Recent Searches"
            },
            {
              "anchor": "Getting-Search-Field-Metrics",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSearchField/cancelButtonBounds",
                "doc://com.apple.appkit/documentation/AppKit/NSSearchField/searchButtonBounds",
                "doc://com.apple.appkit/documentation/AppKit/NSSearchField/searchTextBounds"
              ],
              "title": "Getting Search Field Metrics"
            },
            {
              "anchor": "Deprecated-Symbols",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSearchField/centersPlaceholder",
                "doc://com.apple.appkit/documentation/AppKit/NSSearchField/rectForCancelButton(whenCentered:)",
                "doc://com.apple.appkit/documentation/AppKit/NSSearchField/rectForSearchButton(whenCentered:)",
                "doc://com.apple.appkit/documentation/AppKit/NSSearchField/rectForSearchText(whenCentered:)"
              ],
              "title": "Deprecated Symbols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextField"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSSearchField"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextField",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSTextField",
                    "text": "NSTextField"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/title",
          "value": "NSUserInterfaceItemIdentification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceItemIdentification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceItemIdentification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/title",
          "value": "NSAccessibilityElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchFieldCell/title",
          "value": "NSSearchFieldCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchFieldCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchFieldCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchFieldCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchFieldCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField/title",
          "value": "NSSearchField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserActivityRestoring/title",
          "value": "NSUserActivityRestoring"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserActivityRestoring/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserActivityRestoring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserActivityRestoring/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserActivityRestoring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1recentsAutosaveName-swift.property/title",
          "value": "recentsAutosaveName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1recentsAutosaveName-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recentsAutosaveName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText/title",
          "value": "NSAccessibilityStaticText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityStaticText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityStaticText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1cancelButtonBounds/title",
          "value": "cancelButtonBounds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1cancelButtonBounds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cancelButtonBounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/title",
          "value": "NSAccessibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/title",
          "value": "NSTextField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1recentsTitleMenuItemTag/title",
          "value": "NSSearchFieldRecentsTitleMenuItemTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1recentsTitleMenuItemTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchFieldRecentsTitleMenuItemTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/title",
          "value": "NSStandardKeyBindingResponding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStandardKeyBindingResponding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStandardKeyBindingResponding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1clearRecentsMenuItemTag/title",
          "value": "NSSearchFieldClearRecentsMenuItemTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1clearRecentsMenuItemTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchFieldClearRecentsMenuItemTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1rectForSearchButton(whenCentered:)/title",
          "value": "rectForSearchButtonWhenCentered:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1rectForSearchButton(whenCentered:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rectForSearchButtonWhenCentered:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimatablePropertyContainer/title",
          "value": "NSAnimatablePropertyContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimatablePropertyContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAnimatablePropertyContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimatablePropertyContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAnimatablePropertyContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1maximumRecents/title",
          "value": "maximumRecents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1maximumRecents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumRecents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1searchButtonBounds/title",
          "value": "searchButtonBounds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1searchButtonBounds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "searchButtonBounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1rectForSearchText(whenCentered:)/title",
          "value": "rectForSearchTextWhenCentered:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1rectForSearchText(whenCentered:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rectForSearchTextWhenCentered:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1rectForCancelButton(whenCentered:)/title",
          "value": "rectForCancelButtonWhenCentered:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1rectForCancelButton(whenCentered:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rectForCancelButtonWhenCentered:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchFieldDelegate/title",
          "value": "NSSearchFieldDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchFieldDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchFieldDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchFieldDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchFieldDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1noRecentsMenuItemTag/title",
          "value": "NSSearchFieldNoRecentsMenuItemTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1noRecentsMenuItemTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchFieldNoRecentsMenuItemTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1sendsSearchStringImmediately/title",
          "value": "sendsSearchStringImmediately"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1sendsSearchStringImmediately/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sendsSearchStringImmediately"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1RecentsAutosaveName-swift.typealias/title",
          "value": "NSSearchFieldRecentsAutosaveName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1RecentsAutosaveName-swift.typealias/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchFieldRecentsAutosaveName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1RecentsAutosaveName-swift.typealias/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchFieldRecentsAutosaveName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppearanceCustomization/title",
          "value": "NSAppearanceCustomization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppearanceCustomization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppearanceCustomization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppearanceCustomization/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppearanceCustomization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1searchTextBounds/title",
          "value": "searchTextBounds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1searchTextBounds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "searchTextBounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1sendsWholeSearchString/title",
          "value": "sendsWholeSearchString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1sendsWholeSearchString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sendsWholeSearchString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1searchMenuTemplate/title",
          "value": "searchMenuTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1searchMenuTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "searchMenuTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1recentSearches/title",
          "value": "recentSearches"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1recentSearches/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recentSearches"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarProvider/title",
          "value": "NSTouchBarProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchBarProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchBarProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1recentsMenuItemTag/title",
          "value": "NSSearchFieldRecentsMenuItemTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1recentsMenuItemTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchFieldRecentsMenuItemTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination/title",
          "value": "NSDraggingDestination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContent/title",
          "value": "NSTextContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1centersPlaceholder/title",
          "value": "centersPlaceholder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1centersPlaceholder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "centersPlaceholder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityNavigableStaticText/title",
          "value": "NSAccessibilityNavigableStaticText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityNavigableStaticText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityNavigableStaticText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityNavigableStaticText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityNavigableStaticText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceValidations/title",
          "value": "NSUserInterfaceValidations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceValidations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceValidations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceValidations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceValidations"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nssearchfield"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nssearchfield"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
