{"metadata":{"modules":[{"name":"AppKit"}],"title":"NSSecureTextFieldCell","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSSecureTextFieldCell","kind":"identifier"}],"platforms":[{"beta":false,"name":"macOS","unavailable":false,"deprecated":false}],"navigatorTitle":[{"text":"NSSecureTextFieldCell","kind":"identifier"}],"symbolKind":"class","externalID":"c:objc(cs)NSSecureTextFieldCell","role":"symbol","roleHeading":"Class"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","seeAlsoSections":[{"anchor":"Cell","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell"],"title":"Cell"}],"sections":[],"abstract":[{"text":"A text field whose value is hidden from the user.","type":"text"}],"variants":[{"paths":["/documentation/appkit/nssecuretextfieldcell"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nssecuretextfieldcell"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSSecureTextFieldCell","kind":"identifier"}]}]},{"content":[{"type":"heading","text":"Overview","level":2,"anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSecureTextFieldCell","isActive":true},{"type":"text","text":" works with "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSecureTextField","isActive":true},{"type":"text","text":" and overrides the general cell use of the field editor to provide its own field editor, which doesn’t display text or allow the user to cut or copy its value."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell"],"type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol","doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification","doc://com.externally.resolved.symbol/s:s8SendableP"],"title":"Conforms To","kind":"relationships"}],"topicSections":[{"title":"Working with character echo","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSecureTextFieldCell/echosBullets"],"anchor":"Working-with-character-echo"}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSSecureTextFieldCell","interfaceLanguage":"swift"},"references":{"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"abstract":[{"type":"text","text":"A type with a customized textual representation suitable for debugging purposes."}],"url":"/documentation/Swift/CustomDebugStringConvertible","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomDebugStringConvertible","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","role":"symbol","type":"topic","title":"CustomDebugStringConvertible"},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"kind":"symbol","url":"/documentation/Swift/CustomStringConvertible","role":"symbol","abstract":[{"text":"A type with a customized textual representation.","type":"text"}],"title":"CustomStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}],"identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSSecureTextFieldCell/echosBullets":{"url":"/documentation/appkit/nssecuretextfieldcell/echosbullets","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSecureTextFieldCell/echosBullets","title":"echosBullets","abstract":[{"text":"A Boolean that indicates whether the receiver echoes a bullet character rather than each character typed.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"echosBullets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"echosBullets","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:s8SendableP":{"identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","role":"symbol","type":"topic","url":"/documentation/Swift/Sendable","abstract":[{"text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"title":"Sendable","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.externally.resolved.symbol/s:SH":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SQ","text":"Equatable"}],"url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"title":"Hashable"},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"url":"/documentation/Swift/CVarArg","title":"CVarArg","kind":"symbol","abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVarArg","kind":"identifier"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSUserInterfaceItemIdentification","kind":"identifier"}],"type":"topic","abstract":[{"text":"A set of methods used to associate a unique identifier with objects in your user interface.","type":"text"}],"url":"/documentation/appkit/nsuserinterfaceitemidentification","title":"NSUserInterfaceItemIdentification","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"NSUserInterfaceItemIdentification","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"type":"topic","title":"Equatable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SQ","role":"symbol","url":"/documentation/Swift/Equatable"},"doc://com.apple.appkit/documentation/AppKit/NSSecureTextField":{"abstract":[{"type":"text","text":"A text field that hides the typed text."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSSecureTextField","kind":"identifier"}],"url":"/documentation/appkit/nssecuretextfield","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSecureTextField","role":"symbol","navigatorTitle":[{"text":"NSSecureTextField","kind":"identifier"}],"type":"topic","kind":"symbol","title":"NSSecureTextField"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSAccessibilityProtocol","kind":"identifier"}],"url":"/documentation/appkit/nsaccessibilityprotocol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol","role":"symbol","title":"NSAccessibilityProtocol","kind":"symbol","abstract":[{"text":"The complete list of properties and methods for accessible elements.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityProtocol"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"type":"topic","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"url":"/documentation/objectivec/nsobjectprotocol","title":"NSObjectProtocol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying":{"role":"symbol","type":"topic","title":"NSCopying","url":"/documentation/foundation/nscopying","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","kind":"symbol","fragments":[{"text":"protocol ","kind":"text"},{"kind":"identifier","text":"NSCopying"}],"abstract":[{"type":"text","text":"A protocol that objects adopt to provide functional copies of themselves."}]},"doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NSTextFieldCell"}],"url":"/documentation/appkit/nstextfieldcell","title":"NSTextFieldCell","abstract":[{"text":"An object that enhances the text display capabilities of a cell.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NSTextFieldCell"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSecureTextFieldCell":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSSecureTextFieldCell","kind":"identifier"}],"kind":"symbol","type":"topic","title":"NSSecureTextFieldCell","navigatorTitle":[{"text":"NSSecureTextFieldCell","kind":"identifier"}],"url":"/documentation/appkit/nssecuretextfieldcell","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSecureTextFieldCell","abstract":[{"text":"A text field whose value is hidden from the user.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol":{"title":"NSAccessibilityElementProtocol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAccessibilityElementProtocol","kind":"identifier"}],"abstract":[{"text":"A role-based protocol that declares the minimum interface necessary to interact with an assistive app.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"NSAccessibilityElementProtocol","kind":"identifier"}],"url":"/documentation/appkit/nsaccessibilityelementprotocol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding":{"fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSCoding"}],"title":"NSCoding","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","abstract":[{"type":"text","text":"A protocol that enables an object to be encoded and decoded for archiving and distribution."}],"role":"symbol","url":"/documentation/foundation/nscoding","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"name":"macOS","deprecated":false,"unavailable":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Class"},{"op":"replace","path":"/metadata/title","value":"NSSecureTextFieldCell"},{"value":"class","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"NSSecureTextFieldCell","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":[{"text":"NSSecureTextFieldCell","kind":"identifier"}],"op":"replace","path":"/metadata/navigatorTitle"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"op":"replace","path":"/hierarchy"},{"value":[{"title":"Working with character echo","anchor":"Working-with-character-echo","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSecureTextFieldCell/echosBullets"]}],"op":"replace","path":"/topicSections"},{"value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell"]}],"op":"replace","path":"/relationshipsSections"},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Cell","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell"],"generated":true,"anchor":"Cell"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSSecureTextFieldCell","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSTextFieldCell","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell","text":"NSTextFieldCell","kind":"typeIdentifier"}],"platforms":["Mac Catalyst","macOS"]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSecureTextFieldCell~1echosBullets/title","value":"echosBullets"},{"op":"replace","value":[{"kind":"identifier","text":"echosBullets"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSecureTextFieldCell~1echosBullets/fragments"},{"op":"replace","value":"NSUserInterfaceItemIdentification","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/title"},{"op":"replace","value":[{"text":"NSUserInterfaceItemIdentification","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/fragments"},{"op":"replace","value":[{"text":"NSUserInterfaceItemIdentification","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/navigatorTitle"},{"op":"replace","value":"NSSecureTextField","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSecureTextField/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSSecureTextField"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSecureTextField/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSSecureTextField"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSecureTextField/navigatorTitle"},{"op":"replace","value":"NSAccessibility","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/title"},{"op":"replace","value":[{"text":"NSAccessibility","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/fragments"},{"op":"replace","value":[{"text":"NSAccessibility","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/navigatorTitle"},{"op":"replace","value":"NSObject","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title"},{"op":"replace","value":"NSTextFieldCell","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell/title"},{"op":"replace","value":[{"text":"NSTextFieldCell","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSTextFieldCell"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell/navigatorTitle"},{"op":"replace","value":"NSSecureTextFieldCell","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSecureTextFieldCell/title"},{"op":"replace","value":[{"text":"NSSecureTextFieldCell","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSecureTextFieldCell/fragments"},{"op":"replace","value":[{"text":"NSSecureTextFieldCell","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSecureTextFieldCell/navigatorTitle"},{"op":"replace","value":"NSAccessibilityElement","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSAccessibilityElement"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSAccessibilityElement"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}