{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTextField"],"title":"Inherits From"},{"kind":"relationships","type":"conformsTo","identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText","doc://com.apple.appkit/documentation/AppKit/NSAnimatablePropertyContainer","doc://com.apple.appkit/documentation/AppKit/NSAppearanceCustomization","doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination","doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding","doc://com.apple.appkit/documentation/AppKit/NSTextContent","doc://com.apple.appkit/documentation/AppKit/NSTouchBarProvider","doc://com.apple.appkit/documentation/AppKit/NSUserActivityRestoring","doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification","doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceValidations","doc://com.externally.resolved.symbol/s:s8SendableP"],"title":"Conforms To"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"variants":[{"paths":["/documentation/appkit/nssecuretextfield"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nssecuretextfield"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSSecureTextField","kind":"identifier"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"overview","text":"Overview"},{"inlineContent":[{"text":"A secure text field is suitable for use as a password-entry object or for any item in which the text value must be kept secret. ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSecureTextField","type":"reference"},{"text":" uses ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSecureTextFieldCell","type":"reference"},{"text":" to implement its user interface.","type":"text"}],"type":"paragraph"}]}],"abstract":[{"text":"A text field that hides the typed text.","type":"text"}],"metadata":{"symbolKind":"class","modules":[{"name":"AppKit"}],"externalID":"c:objc(cs)NSSecureTextField","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSSecureTextField","kind":"identifier"}],"role":"symbol","roleHeading":"Class","navigatorTitle":[{"text":"NSSecureTextField","kind":"identifier"}],"platforms":[{"unavailable":false,"name":"macOS","beta":false,"deprecated":false}],"title":"NSSecureTextField"},"seeAlsoSections":[{"anchor":"Views","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTextField"],"generated":true,"title":"Views"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSSecureTextField"},"references":{"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"abstract":[{"type":"text","text":"A type with a customized textual representation suitable for debugging purposes."}],"url":"/documentation/Swift/CustomDebugStringConvertible","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomDebugStringConvertible","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","role":"symbol","type":"topic","title":"CustomDebugStringConvertible"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"url":"/documentation/Swift/CVarArg","title":"CVarArg","kind":"symbol","abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CVarArg","kind":"identifier"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSecureTextField":{"abstract":[{"type":"text","text":"A text field that hides the typed text."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSSecureTextField","kind":"identifier"}],"url":"/documentation/appkit/nssecuretextfield","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSecureTextField","role":"symbol","navigatorTitle":[{"text":"NSSecureTextField","kind":"identifier"}],"type":"topic","kind":"symbol","title":"NSSecureTextField"},"doc://com.externally.resolved.symbol/s:SH":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SQ","text":"Equatable"}],"url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"title":"Hashable"},"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination":{"abstract":[{"type":"text","text":"A set of methods that the destination object (or recipient) of a dragged image must implement."}],"url":"/documentation/appkit/nsdraggingdestination","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSDraggingDestination"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDraggingDestination","title":"NSDraggingDestination","navigatorTitle":[{"kind":"identifier","text":"NSDraggingDestination"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSAnimatablePropertyContainer":{"title":"NSAnimatablePropertyContainer","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAnimatablePropertyContainer","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSAnimatablePropertyContainer"}],"abstract":[{"type":"text","text":"A set of methods that defines a way to add animation to an existing class with a minimum of API impact."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSAnimatablePropertyContainer"}],"url":"/documentation/appkit/nsanimatablepropertycontainer"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStaticText","navigatorTitle":[{"text":"NSAccessibilityStaticText","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAccessibilityStaticText","kind":"identifier"}],"title":"NSAccessibilityStaticText","role":"symbol","abstract":[{"type":"text","text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as static text."}],"kind":"symbol","type":"topic","url":"/documentation/appkit/nsaccessibilitystatictext"},"doc://com.apple.appkit/documentation/AppKit/NSSecureTextFieldCell":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSSecureTextFieldCell","kind":"identifier"}],"kind":"symbol","type":"topic","title":"NSSecureTextFieldCell","navigatorTitle":[{"text":"NSSecureTextFieldCell","kind":"identifier"}],"url":"/documentation/appkit/nssecuretextfieldcell","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSecureTextFieldCell","abstract":[{"text":"A text field whose value is hidden from the user.","type":"text"}]},"doc://com.externally.resolved.symbol/s:s8SendableP":{"identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","role":"symbol","type":"topic","url":"/documentation/Swift/Sendable","abstract":[{"text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"title":"Sendable","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"type":"topic","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"url":"/documentation/objectivec/nsobjectprotocol","title":"NSObjectProtocol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSUserInterfaceItemIdentification","kind":"identifier"}],"type":"topic","abstract":[{"text":"A set of methods used to associate a unique identifier with objects in your user interface.","type":"text"}],"url":"/documentation/appkit/nsuserinterfaceitemidentification","title":"NSUserInterfaceItemIdentification","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"NSUserInterfaceItemIdentification","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceValidations":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSUserInterfaceValidations"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceValidations","abstract":[{"type":"text","text":"A protocol that a custom class can adopt to manage the enabled state of a UI element."}],"type":"topic","title":"NSUserInterfaceValidations","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSUserInterfaceValidations"}],"url":"/documentation/appkit/nsuserinterfacevalidations","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSUserActivityRestoring":{"url":"/documentation/appkit/nsuseractivityrestoring","title":"NSUserActivityRestoring","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSUserActivityRestoring","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"NSUserActivityRestoring","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserActivityRestoring","abstract":[{"text":"A protocol that marks classes to restore the state of your app to continue a user activity.","type":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSTouchBarProvider":{"abstract":[{"text":"A protocol that an object adopts to create a bar object in your app.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSTouchBarProvider","kind":"identifier"}],"url":"/documentation/appkit/nstouchbarprovider","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTouchBarProvider","role":"symbol","navigatorTitle":[{"text":"NSTouchBarProvider","kind":"identifier"}],"type":"topic","kind":"symbol","title":"NSTouchBarProvider"},"doc://com.apple.appkit/documentation/AppKit/NSTextContent":{"url":"/documentation/appkit/nstextcontent","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextContent","type":"topic","title":"NSTextContent","kind":"symbol","abstract":[{"type":"text","text":"A protocol that describes specific kinds of input content types."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSTextContent"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSTextContent"}]},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"kind":"symbol","url":"/documentation/Swift/CustomStringConvertible","role":"symbol","abstract":[{"text":"A type with a customized textual representation.","type":"text"}],"title":"CustomStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}],"identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol":{"title":"NSAccessibilityElementProtocol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSAccessibilityElementProtocol","kind":"identifier"}],"abstract":[{"text":"A role-based protocol that declares the minimum interface necessary to interact with an assistive app.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"NSAccessibilityElementProtocol","kind":"identifier"}],"url":"/documentation/appkit/nsaccessibilityelementprotocol"},"doc://com.apple.appkit/documentation/AppKit/NSAppearanceCustomization":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAppearanceCustomization","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSAppearanceCustomization"}],"type":"topic","abstract":[{"type":"text","text":"A set of methods for getting and setting the appearance attributes of a view."}],"url":"/documentation/appkit/nsappearancecustomization","title":"NSAppearanceCustomization","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSAppearanceCustomization"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSAccessibilityProtocol","kind":"identifier"}],"url":"/documentation/appkit/nsaccessibilityprotocol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol","role":"symbol","title":"NSAccessibilityProtocol","kind":"symbol","abstract":[{"text":"The complete list of properties and methods for accessible elements.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityProtocol"}]},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"type":"topic","title":"Equatable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SQ","role":"symbol","url":"/documentation/Swift/Equatable"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText":{"url":"/documentation/appkit/nsaccessibilitynavigablestatictext","title":"NSAccessibilityNavigableStaticText","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSAccessibilityNavigableStaticText"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityNavigableStaticText"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityNavigableStaticText","abstract":[{"type":"text","text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as navigable static text."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSTextField":{"title":"NSTextField","navigatorTitle":[{"text":"NSTextField","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextField","role":"symbol","url":"/documentation/appkit/nstextfield","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSTextField","kind":"identifier"}],"abstract":[{"text":"Text the user can select or edit to send an action message to a target when the user presses the Return key.","type":"text"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding":{"fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSCoding"}],"title":"NSCoding","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","abstract":[{"type":"text","text":"A protocol that enables an object to be encoded and decoded for archiving and distribution."}],"role":"symbol","url":"/documentation/foundation/nscoding","type":"topic","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding","abstract":[{"text":"Methods that responder subclasses implement to support key binding commands, such as inserting tabs and newlines, or moving the insertion point.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"title":"NSStandardKeyBindingResponding","kind":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"beta":false,"name":"macOS","deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Class","op":"replace","path":"/metadata/roleHeading"},{"value":"NSSecureTextField","op":"replace","path":"/metadata/title"},{"value":"class","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"NSSecureTextField"}],"op":"replace","path":"/metadata/fragments"},{"value":[{"text":"NSSecureTextField","kind":"identifier"}],"op":"replace","path":"/metadata/navigatorTitle"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTextField"],"kind":"relationships"}],"op":"replace","path":"/relationshipsSections"},{"value":[{"generated":true,"anchor":"Views","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTextField"],"title":"Views"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSSecureTextField","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSTextField","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTextField","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextField"}],"languages":["occ"]}]},"op":"replace","path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSecureTextField/title","value":"NSSecureTextField","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSecureTextField/fragments","value":[{"text":"NSSecureTextField","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSecureTextField/navigatorTitle","value":[{"text":"NSSecureTextField","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination/title","value":"NSDraggingDestination","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination/fragments","value":[{"text":"NSDraggingDestination","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingDestination/navigatorTitle","value":[{"text":"NSDraggingDestination","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimatablePropertyContainer/title","value":"NSAnimatablePropertyContainer","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimatablePropertyContainer/fragments","value":[{"text":"NSAnimatablePropertyContainer","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAnimatablePropertyContainer/navigatorTitle","value":[{"text":"NSAnimatablePropertyContainer","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText/title","value":"NSAccessibilityStaticText","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText/fragments","value":[{"kind":"identifier","text":"NSAccessibilityStaticText"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityStaticText/navigatorTitle","value":[{"text":"NSAccessibilityStaticText","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSecureTextFieldCell/title","value":"NSSecureTextFieldCell","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSecureTextFieldCell/fragments","value":[{"kind":"identifier","text":"NSSecureTextFieldCell"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSecureTextFieldCell/navigatorTitle","value":[{"text":"NSSecureTextFieldCell","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","value":"NSObject","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/title","value":"NSUserInterfaceItemIdentification","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/fragments","value":[{"kind":"identifier","text":"NSUserInterfaceItemIdentification"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/navigatorTitle","value":[{"text":"NSUserInterfaceItemIdentification","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceValidations/title","value":"NSUserInterfaceValidations","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceValidations/fragments","value":[{"kind":"identifier","text":"NSUserInterfaceValidations"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceValidations/navigatorTitle","value":[{"text":"NSUserInterfaceValidations","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserActivityRestoring/title","value":"NSUserActivityRestoring","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserActivityRestoring/fragments","value":[{"kind":"identifier","text":"NSUserActivityRestoring"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserActivityRestoring/navigatorTitle","value":[{"kind":"identifier","text":"NSUserActivityRestoring"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarProvider/title","value":"NSTouchBarProvider","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarProvider/fragments","value":[{"kind":"identifier","text":"NSTouchBarProvider"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarProvider/navigatorTitle","value":[{"kind":"identifier","text":"NSTouchBarProvider"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContent/title","value":"NSTextContent","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContent/fragments","value":[{"kind":"identifier","text":"NSTextContent"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContent/navigatorTitle","value":[{"text":"NSTextContent","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/title","value":"NSAccessibilityElement","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/fragments","value":[{"text":"NSAccessibilityElement","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/navigatorTitle","value":[{"text":"NSAccessibilityElement","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppearanceCustomization/title","value":"NSAppearanceCustomization","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppearanceCustomization/fragments","value":[{"text":"NSAppearanceCustomization","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppearanceCustomization/navigatorTitle","value":[{"text":"NSAppearanceCustomization","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/title","value":"NSAccessibility","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/fragments","value":[{"text":"NSAccessibility","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/navigatorTitle","value":[{"kind":"identifier","text":"NSAccessibility"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityNavigableStaticText/title","value":"NSAccessibilityNavigableStaticText","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityNavigableStaticText/fragments","value":[{"text":"NSAccessibilityNavigableStaticText","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityNavigableStaticText/navigatorTitle","value":[{"text":"NSAccessibilityNavigableStaticText","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/title","value":"NSTextField","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/fragments","value":[{"kind":"identifier","text":"NSTextField"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/navigatorTitle","value":[{"text":"NSTextField","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/title","value":"NSStandardKeyBindingResponding","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/fragments","value":[{"kind":"identifier","text":"NSStandardKeyBindingResponding"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/navigatorTitle","value":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}