{
  "abstract": [
    {
      "text": "A protocol that a search field delegate can use to determine when a search started or ended.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSSearchFieldDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSSearchFieldDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSSearchFieldDelegate"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSSearchFieldDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NSSearchFieldDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSSearchFieldDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFieldDelegate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSTextFieldDelegate",
              "text": "NSTextFieldDelegate"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSControl": {
      "abstract": [
        {
          "text": "A specialized view, such as a button or text field, that notifies your app of relevant events using the target-action design pattern.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSControl"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSControl"
        }
      ],
      "role": "symbol",
      "title": "NSControl",
      "type": "topic",
      "url": "/documentation/appkit/nscontrol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate": {
      "abstract": [
        {
          "text": "A set of optional methods implemented by delegates of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControl",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " subclasses to respond to editing actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSControlTextEditingDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSControlTextEditingDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSControlTextEditingDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nscontroltexteditingdelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchField/delegate": {
      "abstract": [
        {
          "text": "The delegate for the search field, or ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": " if the search field doesn’t have a delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSSearchFieldDelegate",
          "text": "NSSearchFieldDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfield/delegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchFieldDelegate": {
      "abstract": [
        {
          "text": "A protocol that a search field delegate can use to determine when a search started or ended.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSearchFieldDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchFieldDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSearchFieldDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSSearchFieldDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfielddelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchFieldDelegate/searchFieldDidEndSearching(_:)": {
      "abstract": [
        {
          "text": "The method that is called when the search field has ended its search for content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchFieldDidEndSearching"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSearchField",
          "text": "NSSearchField"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchFieldDelegate/searchFieldDidEndSearching(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchFieldDidEndSearching:"
        }
      ],
      "role": "symbol",
      "title": "searchFieldDidEndSearching(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfielddelegate/searchfielddidendsearching(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchFieldDelegate/searchFieldDidStartSearching(_:)": {
      "abstract": [
        {
          "text": "The method that is called when the search field begins searching for content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchFieldDidStartSearching"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSearchField",
          "text": "NSSearchField"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchFieldDelegate/searchFieldDidStartSearching(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchFieldDidStartSearching:"
        }
      ],
      "role": "symbol",
      "title": "searchFieldDidStartSearching(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfielddelegate/searchfielddidstartsearching(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFieldDelegate": {
      "abstract": [
        {
          "text": "A protocol that a text field delegate can use to control its field editor action menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextFieldDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFieldDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextFieldDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSTextFieldDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nstextfielddelegate"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFieldDelegate"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Search",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSearchField/delegate"
      ],
      "title": "Managing Search"
    }
  ],
  "topicSections": [
    {
      "anchor": "Detecting-the-Start-and-End-of-a-Search",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSearchFieldDelegate/searchFieldDidStartSearching(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSSearchFieldDelegate/searchFieldDidEndSearching(_:)"
      ],
      "title": "Detecting the Start and End of a Search"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSSearchFieldDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchFieldDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchFieldDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Detecting-the-Start-and-End-of-a-Search",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSearchFieldDelegate/searchFieldDidStartSearching(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSSearchFieldDelegate/searchFieldDidEndSearching(_:)"
              ],
              "title": "Detecting the Start and End of a Search"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextFieldDelegate"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Search",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSearchField/delegate"
              ],
              "title": "Managing Search"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSSearchFieldDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFieldDelegate",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSTextFieldDelegate",
                    "text": "NSTextFieldDelegate"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchFieldDelegate~1searchFieldDidEndSearching(_:)/title",
          "value": "searchFieldDidEndSearching:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchFieldDelegate~1searchFieldDidEndSearching(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "searchFieldDidEndSearching:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchFieldDelegate/title",
          "value": "NSSearchFieldDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchFieldDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchFieldDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchFieldDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchFieldDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl/title",
          "value": "NSControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldDelegate/title",
          "value": "NSTextFieldDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFieldDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFieldDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate/title",
          "value": "NSControlTextEditingDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlTextEditingDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlTextEditingDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchFieldDelegate~1searchFieldDidStartSearching(_:)/title",
          "value": "searchFieldDidStartSearching:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchFieldDelegate~1searchFieldDidStartSearching(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "searchFieldDidStartSearching:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nssearchfielddelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nssearchfielddelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
