{"abstract":[{"text":"A protocol that a sharing service picker item delegate uses to provide a list of items eligible for sharing.","type":"text"}],"topicSections":[{"anchor":"Providing-items-to-share","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerTouchBarItemDelegate/items(for:)"],"title":"Providing items to share"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate"],"type":"inheritsFrom","title":"Inherits From"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSSharingServicePickerTouchBarItemDelegate"},{"kind":"text","text":" : "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate","preciseIdentifier":"c:objc(pl)NSSharingServicePickerDelegate","kind":"typeIdentifier","text":"NSSharingServicePickerDelegate"}],"platforms":["macOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nssharingservicepickertouchbaritemdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nssharingservicepickertouchbaritemdelegate"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerTouchBarItemDelegate"},"sections":[],"kind":"symbol","seeAlsoSections":[{"anchor":"Setting-the-delegate","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerTouchBarItem/delegate"],"generated":true,"title":"Setting the delegate"}],"metadata":{"modules":[{"name":"AppKit"}],"navigatorTitle":[{"kind":"identifier","text":"NSSharingServicePickerTouchBarItemDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSSharingServicePickerTouchBarItemDelegate"}],"externalID":"c:objc(pl)NSSharingServicePickerTouchBarItemDelegate","symbolKind":"protocol","role":"symbol","title":"NSSharingServicePickerTouchBarItemDelegate","roleHeading":"Protocol","platforms":[{"unavailable":false,"name":"macOS","beta":false,"deprecated":false}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate":{"abstract":[{"type":"text","text":"An interface for managing content for the macOS share sheet."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"NSSharingServicePickerDelegate","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"NSSharingServicePickerDelegate","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate","kind":"symbol","url":"/documentation/appkit/nssharingservicepickerdelegate","role":"symbol","title":"NSSharingServicePickerDelegate"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"type":"topic","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"url":"/documentation/objectivec/nsobjectprotocol","title":"NSObjectProtocol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerTouchBarItemDelegate":{"abstract":[{"type":"text","text":"A protocol that a sharing service picker item delegate uses to provide a list of items eligible for sharing."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSSharingServicePickerTouchBarItemDelegate"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSSharingServicePickerTouchBarItemDelegate"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerTouchBarItemDelegate","kind":"symbol","url":"/documentation/appkit/nssharingservicepickertouchbaritemdelegate","role":"symbol","title":"NSSharingServicePickerTouchBarItemDelegate"},"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerTouchBarItem/delegate":{"abstract":[{"type":"text","text":"The object that acts as the delegate of the sharing service picker bar item."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"text":"NSSharingServicePickerTouchBarItemDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSSharingServicePickerTouchBarItemDelegate"},{"text":")?","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerTouchBarItem/delegate","kind":"symbol","url":"/documentation/appkit/nssharingservicepickertouchbaritem/delegate","role":"symbol","title":"delegate"},"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerTouchBarItemDelegate/items(for:)":{"abstract":[{"type":"text","text":"Asks the delegate for items that represent the objects to be shared."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"items","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSSharingServicePickerTouchBarItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSSharingServicePickerTouchBarItem"},{"text":") -> [","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"itemsForSharingServicePickerTouchBarItem:"}],"required":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerTouchBarItemDelegate/items(for:)","kind":"symbol","url":"/documentation/appkit/nssharingservicepickertouchbaritemdelegate/items(for:)","role":"symbol","title":"items(for:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"beta":false,"name":"macOS","deprecated":false}],"path":"/metadata/platforms"},{"path":"/metadata/roleHeading","op":"replace","value":"Protocol"},{"path":"/metadata/title","op":"replace","value":"NSSharingServicePickerTouchBarItemDelegate"},{"path":"/metadata/symbolKind","op":"replace","value":"protocol"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"NSSharingServicePickerTouchBarItemDelegate"}]},{"path":"/metadata/navigatorTitle","op":"replace","value":[{"text":"NSSharingServicePickerTouchBarItemDelegate","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]}},{"path":"/topicSections","op":"replace","value":[{"title":"Providing items to share","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerTouchBarItemDelegate/items(for:)"],"anchor":"Providing-items-to-share"}]},{"path":"/relationshipsSections","op":"replace","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate"],"type":"inheritsFrom"}]},{"value":[{"generated":true,"anchor":"Setting-the-delegate","title":"Setting the delegate","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerTouchBarItem/delegate"]}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSSharingServicePickerTouchBarItemDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate","text":"NSSharingServicePickerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSSharingServicePickerDelegate"},{"text":">","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerDelegate/title","value":"NSSharingServicePickerDelegate"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerDelegate/fragments","value":[{"text":"NSSharingServicePickerDelegate","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerDelegate/navigatorTitle","value":[{"text":"NSSharingServicePickerDelegate","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","value":"NSObject"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerTouchBarItemDelegate/title","value":"NSSharingServicePickerTouchBarItemDelegate"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerTouchBarItemDelegate/fragments","value":[{"text":"NSSharingServicePickerTouchBarItemDelegate","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerTouchBarItemDelegate/navigatorTitle","value":[{"text":"NSSharingServicePickerTouchBarItemDelegate","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerTouchBarItem~1delegate/title","value":"delegate"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerTouchBarItem~1delegate/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerTouchBarItemDelegate~1items(for:)/title","value":"itemsForSharingServicePickerTouchBarItem:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerTouchBarItemDelegate~1items(for:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"itemsForSharingServicePickerTouchBarItem:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}