{
  "abstract": [
    {
      "text": "The shadow of the text.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSShadowAttributeName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSShadowAttributeName",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSShadowAttributeName"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSShadowAttributeName"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSShadowAttributeName"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSAttributedStringKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSAttributedStringKey",
              "text": "NSAttributedStringKey"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSShadowAttributeName"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value of this attribute is an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSShadow",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. The default value of this property is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursorAttributeName": {
      "abstract": [
        {
          "text": "The cursor object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCursorAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursorAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCursorAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nscursorattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLinkAttributeName": {
      "abstract": [
        {
          "text": "The link for the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLinkAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLinkAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLinkAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nslinkattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMarkedClauseSegmentAttributeName": {
      "abstract": [
        {
          "text": "The index of the marked clause segment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMarkedClauseSegmentAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMarkedClauseSegmentAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMarkedClauseSegmentAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsmarkedclausesegmentattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSShadow": {
      "abstract": [
        {
          "text": "An object you use to specify attributes to create and style a drop shadow during drawing operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSShadow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSShadow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSShadow"
        }
      ],
      "role": "symbol",
      "title": "NSShadow",
      "type": "topic",
      "url": "/documentation/appkit/nsshadow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSShadowAttributeName": {
      "abstract": [
        {
          "text": "The shadow of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSShadowAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSShadowAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSShadowAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsshadowattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpellingStateAttributeName": {
      "abstract": [
        {
          "text": "The spelling state of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSSpellingStateAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpellingStateAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSpellingStateAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsspellingstateattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextAlternativesAttributeName": {
      "abstract": [
        {
          "text": "The alternatives for the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextAlternativesAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextAlternativesAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextAlternativesAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nstextalternativesattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextEffectAttributeName": {
      "abstract": [
        {
          "text": "An attribute that applies a text effect to the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextEffectAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextEffectAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextEffectAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nstexteffectattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorSchemeAttributeName": {
      "abstract": [
        {
          "text": "The custom highlight color to apply to the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextHighlightColorSchemeAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorSchemeAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextHighlightColorSchemeAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nstexthighlightcolorschemeattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightStyleAttributeName": {
      "abstract": [
        {
          "text": "An attribute that adds a highlight color to the text to emphasize it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextHighlightStyleAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightStyleAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextHighlightStyleAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nstexthighlightstyleattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSToolTipAttributeName": {
      "abstract": [
        {
          "text": "The tooltip text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSToolTipAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolTipAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSToolTipAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nstooltipattributename"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSAttributedStringKey": {
      "abstract": [
        {
          "text": "The attributes you apply to ranges of characters in an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "NSAttributedString.Key"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSAttributedStringKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedString.Key",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/key"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-text-attribute-keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCursorAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSLinkAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSMarkedClauseSegmentAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSSpellingStateAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSTextAlternativesAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSTextEffectAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorSchemeAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightStyleAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSToolTipAttributeName"
      ],
      "title": "Getting text attribute keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSShadow/title",
          "value": "NSShadow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSShadow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSShadow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSShadow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSShadow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSAttributedStringKey/title",
          "value": "NSAttributedStringKey"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsshadowattributename"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
