{
  "abstract": [
    {
      "text": "Represents the types of sharing (collaborating on an item vs. sending a copy of the item)",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "The share picker supports up to two modes, each of which corresponds to one of these types",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSSharingCollaborationMode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSSharingCollaborationMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSSharingCollaborationMode"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSSharingCollaborationMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSSharingCollaborationMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSSharingCollaborationMode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition": {
      "abstract": [
        {
          "text": "The position along the perimeter of a rectangular frame (its edges and corners) from which it’s resized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FrameResizePosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FrameResizePosition"
        }
      ],
      "role": "symbol",
      "title": "NSCursor.FrameResizePosition",
      "type": "topic",
      "url": "/documentation/appkit/nscursor/frameresizeposition"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursorFrameResizeDirections": {
      "abstract": [
        {
          "text": "The directions in which a rectangular frame can be resized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCursorFrameResizeDirections"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursorFrameResizeDirections",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCursorFrameResizeDirections",
      "type": "topic",
      "url": "/documentation/appkit/nscursorframeresizedirections"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHorizontalDirection": {
      "abstract": [
        {
          "text": "An absolute direction on the horizontal axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSHorizontalDirection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHorizontalDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHorizontalDirection"
        }
      ],
      "role": "symbol",
      "title": "NSHorizontalDirection",
      "type": "topic",
      "url": "/documentation/appkit/nshorizontaldirection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHorizontalDirections": {
      "abstract": [
        {
          "text": "The absolute directions on the horizontal axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSHorizontalDirections"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHorizontalDirections",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSHorizontalDirections",
      "type": "topic",
      "url": "/documentation/appkit/nshorizontaldirections"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange": {
      "abstract": [
        {
          "text": "Describes how High Dynamic Range (HDR) image content displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DynamicRange"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DynamicRange"
        }
      ],
      "role": "symbol",
      "title": "NSImage.DynamicRange",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/dynamicrange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingCollaborationMode": {
      "abstract": [
        {
          "text": "Represents the types of sharing (collaborating on an item vs. sending a copy of the item)",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "The share picker supports up to two modes, each of which corresponds to one of these types",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSharingCollaborationMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingCollaborationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingCollaborationMode"
        }
      ],
      "role": "symbol",
      "title": "NSSharingCollaborationMode",
      "type": "topic",
      "url": "/documentation/appkit/nssharingcollaborationmode"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingCollaborationMode/collaborate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collaborate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingCollaborationMode/collaborate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingCollaborationModeCollaborate"
        }
      ],
      "role": "symbol",
      "title": "NSSharingCollaborationMode.collaborate",
      "type": "topic",
      "url": "/documentation/appkit/nssharingcollaborationmode/collaborate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingCollaborationMode/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingCollaborationMode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nssharingcollaborationmode/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingCollaborationMode/sendCopy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendCopy"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingCollaborationMode/sendCopy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingCollaborationModeSendCopy"
        }
      ],
      "role": "symbol",
      "title": "NSSharingCollaborationMode.sendCopy",
      "type": "topic",
      "url": "/documentation/appkit/nssharingcollaborationmode/sendcopy"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextCursorAccessoryPlacement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextCursorAccessoryPlacement"
        }
      ],
      "role": "symbol",
      "title": "NSTextCursorAccessoryPlacement",
      "type": "topic",
      "url": "/documentation/appkit/nstextcursoraccessoryplacement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVerticalDirection": {
      "abstract": [
        {
          "text": "A direction on the vertical axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSVerticalDirection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVerticalDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVerticalDirection"
        }
      ],
      "role": "symbol",
      "title": "NSVerticalDirection",
      "type": "topic",
      "url": "/documentation/appkit/nsverticaldirection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVerticalDirections": {
      "abstract": [
        {
          "text": "The directions on the vertical axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSVerticalDirections"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVerticalDirections",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSVerticalDirections",
      "type": "topic",
      "url": "/documentation/appkit/nsverticaldirections"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior": {
      "abstract": [
        {
          "text": "Constants that specify the Writing Tools experience for the underlying view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWritingToolsBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsBehavior"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsBehavior",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolsbehavior"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsResultOptions": {
      "abstract": [
        {
          "text": "Constants to specify what type of content to allow in Writing Tools",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "suggestions or rewrites.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWritingToolsResultOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsResultOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsResultOptions"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsResultOptions",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolsresultoptions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition",
        "doc://com.apple.appkit/documentation/AppKit/NSHorizontalDirection",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange",
        "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement",
        "doc://com.apple.appkit/documentation/AppKit/NSVerticalDirection",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsResultOptions"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSharingCollaborationMode/collaborate",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingCollaborationMode/sendCopy"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSharingCollaborationMode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSSharingCollaborationMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingCollaborationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingCollaborationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSharingCollaborationMode/collaborate",
                "doc://com.apple.appkit/documentation/AppKit/NSSharingCollaborationMode/sendCopy"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition",
                "doc://com.apple.appkit/documentation/AppKit/NSCursorFrameResizeDirections",
                "doc://com.apple.appkit/documentation/AppKit/NSHorizontalDirections",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange",
                "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement",
                "doc://com.apple.appkit/documentation/AppKit/NSVerticalDirections",
                "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior",
                "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsResultOptions"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSSharingCollaborationMode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingCollaborationMode~1sendCopy/title",
          "value": "NSSharingCollaborationModeSendCopy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingCollaborationMode~1sendCopy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingCollaborationModeSendCopy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingCollaborationMode/title",
          "value": "NSSharingCollaborationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingCollaborationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingCollaborationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingCollaborationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingCollaborationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement/title",
          "value": "NSTextCursorAccessoryPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextCursorAccessoryPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextCursorAccessoryPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1FrameResizePosition/title",
          "value": "NSCursorFrameResizePosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1FrameResizePosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCursorFrameResizePosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1FrameResizePosition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCursorFrameResizePosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsBehavior/title",
          "value": "NSWritingToolsBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsResultOptions/title",
          "value": "NSWritingToolsResultOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsResultOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsResultOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsResultOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsResultOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingCollaborationMode~1collaborate/title",
          "value": "NSSharingCollaborationModeCollaborate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingCollaborationMode~1collaborate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingCollaborationModeCollaborate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1DynamicRange/title",
          "value": "NSImageDynamicRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1DynamicRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageDynamicRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1DynamicRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageDynamicRange"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nssharingcollaborationmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nssharingcollaborationmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
