{"sections":[],"topicSections":[{"anchor":"Providing-the-Items-to-Share","title":"Providing the Items to Share","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerToolbarItemDelegate/items(for:)"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate"]}],"seeAlsoSections":[{"anchor":"Getting-the-Toolbar-Items","title":"Getting the Toolbar Items","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerToolbarItem/delegate","doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerToolbarItem/activityItemsConfiguration"]}],"abstract":[{"text":"An interface that provides the content to share from the macOS share sheet.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerToolbarItemDelegate","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["/documentation/appkit/nssharingservicepickertoolbaritemdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nssharingservicepickertoolbaritemdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Protocol","role":"symbol","navigatorTitle":[{"text":"NSSharingServicePickerToolbarItemDelegate","kind":"identifier"}],"externalID":"c:objc(pl)NSSharingServicePickerToolbarItemDelegate","symbolKind":"protocol","platforms":[{"unavailable":false,"beta":false,"deprecated":false,"name":"macOS"}],"title":"NSSharingServicePickerToolbarItemDelegate","modules":[{"name":"AppKit"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSSharingServicePickerToolbarItemDelegate","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSSharingServicePickerToolbarItemDelegate"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(pl)NSSharingServicePickerDelegate","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate","kind":"typeIdentifier","text":"NSSharingServicePickerDelegate"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"},{"content":[{"text":"Overview","level":2,"anchor":"overview","type":"heading"},{"inlineContent":[{"text":"Adopt the ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerToolbarItemDelegate","isActive":true,"type":"reference"},{"text":" protocol in one of your app’s custom types and use it to provide shareable content. Assign your delegate object to an ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerToolbarItem","isActive":true,"type":"reference"},{"text":" object you add to your window’s toolbar.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerToolbarItemDelegate":{"navigatorTitle":[{"text":"NSSharingServicePickerToolbarItemDelegate","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerToolbarItemDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"NSSharingServicePickerToolbarItemDelegate","kind":"identifier"}],"type":"topic","title":"NSSharingServicePickerToolbarItemDelegate","kind":"symbol","abstract":[{"type":"text","text":"An interface that provides the content to share from the macOS share sheet."}],"role":"symbol","url":"/documentation/appkit/nssharingservicepickertoolbaritemdelegate"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"type":"topic","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"url":"/documentation/objectivec/nsobjectprotocol","title":"NSObjectProtocol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerToolbarItem/delegate":{"kind":"symbol","url":"/documentation/appkit/nssharingservicepickertoolbaritem/delegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"NSSharingServicePickerToolbarItemDelegate","preciseIdentifier":"c:objc(pl)NSSharingServicePickerToolbarItemDelegate"},{"kind":"text","text":")?"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerToolbarItem/delegate","abstract":[{"type":"text","text":"The custom object from your app that provides the items to share."}],"title":"delegate","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerToolbarItem":{"navigatorTitle":[{"text":"NSSharingServicePickerToolbarItem","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerToolbarItem","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSSharingServicePickerToolbarItem","kind":"identifier"}],"type":"topic","title":"NSSharingServicePickerToolbarItem","kind":"symbol","abstract":[{"type":"text","text":"A toolbar item that displays the macOS share sheet."}],"role":"symbol","url":"/documentation/appkit/nssharingservicepickertoolbaritem"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerToolbarItemDelegate/items(for:)":{"type":"topic","abstract":[{"type":"text","text":"Asks the delegate for the items to share."}],"required":true,"title":"items(for:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"items","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSSharingServicePickerToolbarItem","preciseIdentifier":"c:objc(cs)NSSharingServicePickerToolbarItem","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerToolbarItemDelegate/items(for:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"itemsForSharingServicePickerToolbarItem:"}],"url":"/documentation/appkit/nssharingservicepickertoolbaritemdelegate/items(for:)"},"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate":{"abstract":[{"type":"text","text":"An interface for managing content for the macOS share sheet."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"NSSharingServicePickerDelegate","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"NSSharingServicePickerDelegate","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate","kind":"symbol","url":"/documentation/appkit/nssharingservicepickerdelegate","role":"symbol","title":"NSSharingServicePickerDelegate"},"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerToolbarItem/activityItemsConfiguration":{"kind":"symbol","url":"/documentation/appkit/nssharingservicepickertoolbaritem/activityitemsconfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"activityItemsConfiguration"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"activityItemsConfiguration"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"UIActivityItemsConfigurationReading","preciseIdentifier":"c:objc(pl)UIActivityItemsConfigurationReading"},{"kind":"text","text":")?"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerToolbarItem/activityItemsConfiguration","abstract":[{"type":"text","text":"The custom object from an app built with Mac Catalyst that provides the items to share."}],"title":"activityItemsConfiguration","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"beta":false,"deprecated":false,"name":"macOS"}],"op":"replace","path":"/metadata/platforms"},{"value":"Protocol","op":"replace","path":"/metadata/roleHeading"},{"value":"NSSharingServicePickerToolbarItemDelegate","op":"replace","path":"/metadata/title"},{"value":"protocol","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"NSSharingServicePickerToolbarItemDelegate","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":[{"kind":"identifier","text":"NSSharingServicePickerToolbarItemDelegate"}],"op":"replace","path":"/metadata/navigatorTitle"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"op":"replace","path":"/hierarchy"},{"value":[{"anchor":"Providing-the-Items-to-Share","title":"Providing the Items to Share","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerToolbarItemDelegate/items(for:)"]}],"op":"replace","path":"/topicSections"},{"value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate"]}],"op":"replace","path":"/relationshipsSections"},{"value":[{"anchor":"Getting-the-Toolbar-Items","title":"Getting the Toolbar Items","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerToolbarItem/delegate","doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerToolbarItem/activityItemsConfiguration"],"generated":true}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSSharingServicePickerToolbarItemDelegate"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSSharingServicePickerDelegate","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate","kind":"typeIdentifier","text":"NSSharingServicePickerDelegate"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["macOS"]}]},"op":"replace","path":"/primaryContentSections/0"},{"value":"NSSharingServicePickerToolbarItemDelegate","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerToolbarItemDelegate/title"},{"value":[{"text":"NSSharingServicePickerToolbarItemDelegate","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerToolbarItemDelegate/fragments"},{"value":[{"kind":"identifier","text":"NSSharingServicePickerToolbarItemDelegate"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerToolbarItemDelegate/navigatorTitle"},{"value":"NSObject","op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title"},{"value":"delegate","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerToolbarItem~1delegate/title"},{"value":[{"kind":"identifier","text":"delegate"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerToolbarItem~1delegate/fragments"},{"value":"NSSharingServicePickerToolbarItem","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerToolbarItem/title"},{"value":[{"kind":"identifier","text":"NSSharingServicePickerToolbarItem"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerToolbarItem/fragments"},{"value":[{"text":"NSSharingServicePickerToolbarItem","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerToolbarItem/navigatorTitle"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerToolbarItemDelegate~1items(for:)/title","value":"itemsForSharingServicePickerToolbarItem:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerToolbarItemDelegate~1items(for:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"itemsForSharingServicePickerToolbarItem:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerDelegate/title","value":"NSSharingServicePickerDelegate","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerDelegate/fragments","value":[{"text":"NSSharingServicePickerDelegate","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerDelegate/navigatorTitle","value":[{"kind":"identifier","text":"NSSharingServicePickerDelegate"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerToolbarItem~1activityItemsConfiguration/title","value":"activityItemsConfiguration","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerToolbarItem~1activityItemsConfiguration/fragments","value":[{"kind":"identifier","text":"activityItemsConfiguration"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}