{
  "abstract": [
    {
      "text": "The appearance and behavior of an ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSSliderCell",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSSliderCell"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSSliderCell"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSSliderCell"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSSliderCell"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can customize an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to a certain degree, using its properties. If this doesn’t give you sufficient flexibility, you can create a subclass. In that subclass, you can override any of the following methods: ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/knobRect(flipped:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/drawBar(inside:flipped:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/drawKnob(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/prefersTrackingUntilMouseUp",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol": {
      "abstract": [
        {
          "text": "A role-based protocol that declares the minimum interface necessary to interact with an assistive app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityElementProtocol"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityElementProtocol"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityElementProtocol",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityelementprotocol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol": {
      "abstract": [
        {
          "text": "The complete list of properties and methods for accessible elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityProtocol",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSActionCell": {
      "abstract": [
        {
          "text": "An active area inside a control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSActionCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSActionCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSActionCell"
        }
      ],
      "role": "symbol",
      "title": "NSActionCell",
      "type": "topic",
      "url": "/documentation/appkit/nsactioncell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider": {
      "abstract": [
        {
          "text": "A display of a bar representing a continuous range of numerical values and a knob representing the currently selected value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSlider"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSlider"
        }
      ],
      "role": "symbol",
      "title": "NSSlider",
      "type": "topic",
      "url": "/documentation/appkit/nsslider"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/SliderType-swift.enum": {
      "abstract": [
        {
          "text": "The types of sliders, used by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/sliderType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SliderType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/SliderType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SliderType"
        }
      ],
      "role": "symbol",
      "title": "NSSlider.SliderType",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/slidertype-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum": {
      "abstract": [
        {
          "text": "The position where a linear slider’s tick marks appear (above, below, leading, or trailing).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TickMarkPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TickMarkPosition"
        }
      ],
      "role": "symbol",
      "title": "NSSlider.TickMarkPosition",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/tickmarkposition-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell": {
      "abstract": [
        {
          "text": "The appearance and behavior of an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSliderCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSliderCell"
        }
      ],
      "role": "symbol",
      "title": "NSSliderCell",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/allowsTickMarkValuesOnly": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the receiver fixes its values to those values represented by its tick marks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsTickMarkValuesOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/allowsTickMarkValuesOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsTickMarkValuesOnly"
        }
      ],
      "role": "symbol",
      "title": "allowsTickMarkValuesOnly",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/allowstickmarkvaluesonly"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/altIncrementValue": {
      "abstract": [
        {
          "text": "The amount by which the slider changes its value when the user Option-drags the knob.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "altIncrementValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/altIncrementValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "altIncrementValue"
        }
      ],
      "role": "symbol",
      "title": "altIncrementValue",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/altincrementvalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/barRect(flipped:)": {
      "abstract": [
        {
          "text": "Returns the rectangle in which the bar is drawn.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "barRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "flipped"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/barRect(flipped:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "barRectFlipped:"
        }
      ],
      "role": "symbol",
      "title": "barRect(flipped:)",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/barrect(flipped:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/closestTickMarkValue(toValue:)": {
      "abstract": [
        {
          "text": "Returns the value of the tick mark closest to the specified value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "closestTickMarkValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "toValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/closestTickMarkValue(toValue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "closestTickMarkValueToValue:"
        }
      ],
      "role": "symbol",
      "title": "closestTickMarkValue(toValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/closesttickmarkvalue(tovalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/drawBar(inside:flipped:)": {
      "abstract": [
        {
          "text": "Draws the slider’s bar—but not its bezel or knob—inside the specified rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawBar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "inside"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "flipped"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/drawBar(inside:flipped:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawBarInside:flipped:"
        }
      ],
      "role": "symbol",
      "title": "drawBar(inside:flipped:)",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/drawbar(inside:flipped:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/drawKnob()": {
      "abstract": [
        {
          "text": "Calculates the rectangle in which the knob should be drawn, then calls ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/drawKnob(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to actually draw the knob.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawKnob"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/drawKnob()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawKnob"
        }
      ],
      "role": "symbol",
      "title": "drawKnob()",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/drawknob()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/drawKnob(_:)": {
      "abstract": [
        {
          "text": "Draws the slider knob in the given rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawKnob"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/drawKnob(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawKnob:"
        }
      ],
      "role": "symbol",
      "title": "drawKnob(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/drawknob(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/drawTickMarks()": {
      "abstract": [
        {
          "text": "Draws the slider’s tick marks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawTickMarks"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/drawTickMarks()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawTickMarks"
        }
      ],
      "role": "symbol",
      "title": "drawTickMarks()",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/drawtickmarks()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/image": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "image"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/image",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "image"
        }
      ],
      "role": "symbol",
      "title": "image",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/image"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/indexOfTickMark(at:)": {
      "abstract": [
        {
          "text": "Returns the index of the tick mark closest to the location of the slider represented by the specified point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indexOfTickMark"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/indexOfTickMark(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indexOfTickMarkAtPoint:"
        }
      ],
      "role": "symbol",
      "title": "indexOfTickMark(at:)",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/indexoftickmark(at:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/isVertical": {
      "abstract": [
        {
          "text": "An integer indicating the orientation (vertical or horizontal) of the slider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isVertical"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/isVertical",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vertical"
        }
      ],
      "role": "symbol",
      "title": "isVertical",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/isvertical"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/knobRect(flipped:)": {
      "abstract": [
        {
          "text": "Returns the rectangle in which the slider knob is drawn.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "knobRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "flipped"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/knobRect(flipped:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "knobRectFlipped:"
        }
      ],
      "role": "symbol",
      "title": "knobRect(flipped:)",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/knobrect(flipped:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/knobThickness": {
      "abstract": [
        {
          "text": "The thickness of the slider knob, in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "knobThickness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/knobThickness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "knobThickness"
        }
      ],
      "role": "symbol",
      "title": "knobThickness",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/knobthickness"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/maxValue": {
      "abstract": [
        {
          "text": "The maximum value the slider can send to its target.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/maxValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxValue"
        }
      ],
      "role": "symbol",
      "title": "maxValue",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/maxvalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/minValue": {
      "abstract": [
        {
          "text": "The minimum value the slider can send to its target.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/minValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minValue"
        }
      ],
      "role": "symbol",
      "title": "minValue",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/minvalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/numberOfTickMarks": {
      "abstract": [
        {
          "text": "The number of tick marks associated with the slider, including the tick marks assigned to the minimum and maximum values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfTickMarks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/numberOfTickMarks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfTickMarks"
        }
      ],
      "role": "symbol",
      "title": "numberOfTickMarks",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/numberoftickmarks"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/prefersTrackingUntilMouseUp": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether the ",
          "type": "text"
        },
        {
          "code": "NSSliderCell",
          "type": "codeVoice"
        },
        {
          "text": " continues to track the pointer until the next mouse up.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prefersTrackingUntilMouseUp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/prefersTrackingUntilMouseUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prefersTrackingUntilMouseUp"
        }
      ],
      "role": "symbol",
      "title": "prefersTrackingUntilMouseUp",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/preferstrackinguntilmouseup"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/rectOfTickMark(at:)": {
      "abstract": [
        {
          "text": "Returns the bounding rectangle of the tick mark at the specified index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rectOfTickMark"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/rectOfTickMark(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rectOfTickMarkAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "rectOfTickMark(at:)",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/rectoftickmark(at:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/setImage:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setImage:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/setImage:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setImage:"
        }
      ],
      "role": "symbol",
      "title": "setImage:",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/setimage:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/setKnobThickness:": {
      "abstract": [
        {
          "text": "The thickness of the slider knob, in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setKnobThickness:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/setKnobThickness:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setKnobThickness:"
        }
      ],
      "role": "symbol",
      "title": "setKnobThickness:",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/setknobthickness:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/setTitle:": {
      "abstract": [
        {
          "text": "Sets the title in the bar behind the slider’s knob.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setTitle:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/setTitle:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTitle:"
        }
      ],
      "role": "symbol",
      "title": "setTitle:",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/settitle:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/setTitleCell:": {
      "abstract": [
        {
          "text": "Sets the cell used to draw the slider’s title.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setTitleCell:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/setTitleCell:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTitleCell:"
        }
      ],
      "role": "symbol",
      "title": "setTitleCell:",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/settitlecell:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/setTitleColor:": {
      "abstract": [
        {
          "text": "Sets the color used to draw the slider’s title.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setTitleColor:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/setTitleColor:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTitleColor:"
        }
      ],
      "role": "symbol",
      "title": "setTitleColor:",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/settitlecolor:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/setTitleFont:": {
      "abstract": [
        {
          "text": "Sets the font used to draw the slider’s title.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setTitleFont:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/setTitleFont:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTitleFont:"
        }
      ],
      "role": "symbol",
      "title": "setTitleFont:",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/settitlefont:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/sliderType": {
      "abstract": [
        {
          "text": "The slider type, either linear or circular.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sliderType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSlider",
          "text": "NSSlider"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSSliderType",
          "text": "SliderType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/sliderType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sliderType"
        }
      ],
      "role": "symbol",
      "title": "sliderType",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/slidertype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/tickMarkPosition": {
      "abstract": [
        {
          "text": "The position of the tick marks relative to the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tickMarkPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSlider",
          "text": "NSSlider"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTickMarkPosition",
          "text": "TickMarkPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/tickMarkPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tickMarkPosition"
        }
      ],
      "role": "symbol",
      "title": "tickMarkPosition",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/tickmarkposition"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/tickMarkValue(at:)": {
      "abstract": [
        {
          "text": "Returns the receiver’s value represented by the tick mark at the specified index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tickMarkValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/tickMarkValue(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tickMarkValueAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "tickMarkValue(at:)",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/tickmarkvalue(at:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/title": {
      "abstract": [
        {
          "text": "Returns the slider’s title.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/title"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/titleCell": {
      "abstract": [
        {
          "text": "Returns ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "titleCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/titleCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "titleCell"
        }
      ],
      "role": "symbol",
      "title": "titleCell",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/titlecell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/titleColor": {
      "abstract": [
        {
          "text": "Returns ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "titleColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/titleColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "titleColor"
        }
      ],
      "role": "symbol",
      "title": "titleColor",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/titlecolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/titleFont": {
      "abstract": [
        {
          "text": "Returns ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "titleFont"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/titleFont",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "titleFont"
        }
      ],
      "role": "symbol",
      "title": "titleFont",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/titlefont"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/trackRect": {
      "abstract": [
        {
          "text": "The rectangle within which the cell tracks the pointer while the mouse button is down.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trackRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/trackRect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trackRect"
        }
      ],
      "role": "symbol",
      "title": "trackRect",
      "type": "topic",
      "url": "/documentation/appkit/nsslidercell/trackrect"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification": {
      "abstract": [
        {
          "text": "A set of methods used to associate a unique identifier with objects in your user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserInterfaceItemIdentification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUserInterfaceItemIdentification"
        }
      ],
      "role": "symbol",
      "title": "NSUserInterfaceItemIdentification",
      "type": "topic",
      "url": "/documentation/appkit/nsuserinterfaceitemidentification"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSActionCell"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Managing-Cell-Behavior",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/altIncrementValue",
        "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/prefersTrackingUntilMouseUp",
        "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/trackRect"
      ],
      "title": "Managing Cell Behavior"
    },
    {
      "anchor": "Managing-the-Slider-Type",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/sliderType"
      ],
      "title": "Managing the Slider Type"
    },
    {
      "anchor": "Displaying-the-Cell",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/barRect(flipped:)",
        "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/drawTickMarks()",
        "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/knobRect(flipped:)",
        "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/drawBar(inside:flipped:)",
        "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/drawKnob()",
        "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/drawKnob(_:)"
      ],
      "title": "Displaying the Cell"
    },
    {
      "anchor": "Managing-Cell-Appearance",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/knobThickness",
        "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/isVertical"
      ],
      "title": "Managing Cell Appearance"
    },
    {
      "anchor": "Managing-Value-Limits",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/maxValue",
        "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/minValue"
      ],
      "title": "Managing Value Limits"
    },
    {
      "anchor": "Managing-Tick-Marks",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/allowsTickMarkValuesOnly",
        "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/closestTickMarkValue(toValue:)",
        "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/indexOfTickMark(at:)",
        "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/numberOfTickMarks",
        "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/rectOfTickMark(at:)",
        "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/tickMarkPosition",
        "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/tickMarkValue(at:)"
      ],
      "title": "Managing Tick Marks"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum",
        "doc://com.apple.appkit/documentation/AppKit/NSSlider/SliderType-swift.enum"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSSliderCell"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSliderCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSliderCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Managing-Cell-Behavior",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/altIncrementValue",
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/prefersTrackingUntilMouseUp",
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/trackRect"
              ],
              "title": "Managing Cell Behavior"
            },
            {
              "anchor": "Managing-the-Slider-Type",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/sliderType"
              ],
              "title": "Managing the Slider Type"
            },
            {
              "anchor": "Displaying-the-Cell",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/barRect(flipped:)",
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/drawTickMarks()",
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/knobRect(flipped:)",
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/drawBar(inside:flipped:)",
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/drawKnob()",
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/drawKnob(_:)"
              ],
              "title": "Displaying the Cell"
            },
            {
              "anchor": "Managing-Cell-Appearance",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/knobThickness",
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/isVertical",
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/title",
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/setTitle:",
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/titleCell",
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/setTitleCell:",
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/titleFont",
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/titleColor",
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/setTitleFont:",
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/setTitleColor:"
              ],
              "title": "Managing Cell Appearance"
            },
            {
              "anchor": "Managing-Value-Limits",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/maxValue",
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/minValue"
              ],
              "title": "Managing Value Limits"
            },
            {
              "anchor": "Managing-Tick-Marks",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/allowsTickMarkValuesOnly",
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/closestTickMarkValue(toValue:)",
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/indexOfTickMark(at:)",
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/numberOfTickMarks",
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/rectOfTickMark(at:)",
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/tickMarkPosition",
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/tickMarkValue(at:)"
              ],
              "title": "Managing Tick Marks"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum",
                "doc://com.apple.appkit/documentation/AppKit/NSSlider/SliderType-swift.enum"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Instance-Methods",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/image",
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/setImage:",
                "doc://com.apple.appkit/documentation/AppKit/NSSliderCell/setKnobThickness:"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSActionCell"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSSliderCell"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSActionCell",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSActionCell",
                    "text": "NSActionCell"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1closestTickMarkValue(toValue:)/title",
          "value": "closestTickMarkValueToValue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1closestTickMarkValue(toValue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "closestTickMarkValueToValue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1isVertical/title",
          "value": "vertical"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1isVertical/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vertical"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1drawBar(inside:flipped:)/title",
          "value": "drawBarInside:flipped:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1drawBar(inside:flipped:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawBarInside:flipped:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/title",
          "value": "NSAccessibilityElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1SliderType-swift.enum/title",
          "value": "NSSliderType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1SliderType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSliderType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1SliderType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSliderType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1drawKnob()/title",
          "value": "drawKnob"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1drawKnob()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawKnob"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1trackRect/title",
          "value": "trackRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1trackRect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trackRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1drawKnob(_:)/title",
          "value": "drawKnob:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1drawKnob(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawKnob:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1sliderType/title",
          "value": "sliderType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1sliderType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sliderType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1indexOfTickMark(at:)/title",
          "value": "indexOfTickMarkAtPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1indexOfTickMark(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "indexOfTickMarkAtPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1barRect(flipped:)/title",
          "value": "barRectFlipped:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1barRect(flipped:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "barRectFlipped:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum/title",
          "value": "NSTickMarkPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTickMarkPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTickMarkPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1maxValue/title",
          "value": "maxValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1maxValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/title",
          "value": "NSSlider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSlider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSlider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1knobRect(flipped:)/title",
          "value": "knobRectFlipped:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1knobRect(flipped:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "knobRectFlipped:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1prefersTrackingUntilMouseUp/title",
          "value": "prefersTrackingUntilMouseUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1prefersTrackingUntilMouseUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "prefersTrackingUntilMouseUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell/title",
          "value": "NSSliderCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSliderCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSliderCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSActionCell/title",
          "value": "NSActionCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSActionCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSActionCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSActionCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSActionCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1drawTickMarks()/title",
          "value": "drawTickMarks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1drawTickMarks()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawTickMarks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1rectOfTickMark(at:)/title",
          "value": "rectOfTickMarkAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1rectOfTickMark(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rectOfTickMarkAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1allowsTickMarkValuesOnly/title",
          "value": "allowsTickMarkValuesOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1allowsTickMarkValuesOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsTickMarkValuesOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/title",
          "value": "NSAccessibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1altIncrementValue/title",
          "value": "altIncrementValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1altIncrementValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "altIncrementValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1numberOfTickMarks/title",
          "value": "numberOfTickMarks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1numberOfTickMarks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfTickMarks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1tickMarkValue(at:)/title",
          "value": "tickMarkValueAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1tickMarkValue(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tickMarkValueAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1knobThickness/title",
          "value": "knobThickness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1knobThickness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "knobThickness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/title",
          "value": "NSUserInterfaceItemIdentification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceItemIdentification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceItemIdentification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1tickMarkPosition/title",
          "value": "tickMarkPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1tickMarkPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tickMarkPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1minValue/title",
          "value": "minValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderCell~1minValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minValue"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsslidercell"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsslidercell"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
