{
  "abstract": [
    {
      "text": "A simple square bezel style. Buttons using this style can be scaled to any size.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSSmallSquareBezelStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSSmallSquareBezelStyle",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSSmallSquareBezelStyle"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSSmallSquareBezelStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSSmallSquareBezelStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSBezelStyle",
              "text": "NSBezelStyle"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSSmallSquareBezelStyle"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum": {
      "abstract": [
        {
          "text": "The set of bezel styles to style buttons in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BezelStyle"
        }
      ],
      "role": "symbol",
      "title": "NSButton.BezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/shadowlessSquare": {
      "abstract": [
        {
          "text": "A rectangular button with no shadow, so it can abut the cells without overlapping shadows.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shadowlessSquare"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/shadowlessSquare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStyleShadowlessSquare"
        }
      ],
      "role": "symbol",
      "title": "NSButton.BezelStyle.shadowlessSquare",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/shadowlesssquare"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/texturedSquare": {
      "abstract": [
        {
          "text": "A bezel style appropriate for use with textured (metal) windows.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "texturedSquare"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/texturedSquare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStyleTexturedSquare"
        }
      ],
      "role": "symbol",
      "title": "NSButton.BezelStyle.texturedSquare",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/texturedsquare"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCircularBezelStyle": {
      "abstract": [
        {
          "text": "A round button with room for a small icon or a single character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCircularBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCircularBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCircularBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nscircularbezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDisclosureBezelStyle": {
      "abstract": [
        {
          "text": "A bezel style for use with a disclosure triangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSDisclosureBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDisclosureBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDisclosureBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsdisclosurebezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHelpButtonBezelStyle": {
      "abstract": [
        {
          "text": "A round button with a question mark providing the standard help button look.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSHelpButtonBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHelpButtonBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSHelpButtonBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nshelpbuttonbezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInlineBezelStyle": {
      "abstract": [
        {
          "text": "The inline bezel style contains a solid round-rect border background. It can be used to create an “unread” indicator in an outline view, or another inline button in a tableview, such as a stop progress button in a download panel. Use text for an unread indicator, and a template image for other buttons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSInlineBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInlineBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInlineBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsinlinebezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRecessedBezelStyle": {
      "abstract": [
        {
          "text": "A bezel style that matches the recessed buttons in Mail, Finder and Safari.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRecessedBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRecessedBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRecessedBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsrecessedbezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRegularSquareBezelStyle": {
      "abstract": [
        {
          "text": "A rectangular button with a two-point border, designed for icons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRegularSquareBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRegularSquareBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRegularSquareBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsregularsquarebezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRoundRectBezelStyle": {
      "abstract": [
        {
          "text": "A bezel style that matches the search buttons in Finder and Mail.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRoundRectBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRoundRectBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRoundRectBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsroundrectbezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRoundedBezelStyle": {
      "abstract": [
        {
          "text": "A rounded rectangle button, designed for text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRoundedBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRoundedBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRoundedBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsroundedbezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRoundedDisclosureBezelStyle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRoundedDisclosureBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRoundedDisclosureBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRoundedDisclosureBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsroundeddisclosurebezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSShadowlessSquareBezelStyle": {
      "abstract": [
        {
          "text": "Similar to ",
          "type": "text"
        },
        {
          "code": "NSRegularSquareBezelStyle",
          "type": "codeVoice"
        },
        {
          "text": ", but has no shadow, so you can abut the cells without overlapping shadows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSShadowlessSquareBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSShadowlessSquareBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSShadowlessSquareBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsshadowlesssquarebezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSmallIconButtonBezelStyle": {
      "abstract": [
        {
          "text": "This bezel style is obsolete and should not be used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSSmallIconButtonBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSmallIconButtonBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSmallIconButtonBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nssmalliconbuttonbezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSmallSquareBezelStyle": {
      "abstract": [
        {
          "text": "A simple square bezel style. Buttons using this style can be scaled to any size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSSmallSquareBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSmallSquareBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSmallSquareBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nssmallsquarebezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSThickSquareBezelStyle": {
      "abstract": [
        {
          "text": "A rectangular button with a three-point border, designed for icons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSThickSquareBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSThickSquareBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSThickSquareBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsthicksquarebezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSThickerSquareBezelStyle": {
      "abstract": [
        {
          "text": "A rectangular button with a four-point border, designed for icons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSThickerSquareBezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSThickerSquareBezelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSThickerSquareBezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsthickersquarebezelstyle"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/shadowlessSquare",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/texturedSquare",
        "doc://com.apple.appkit/documentation/AppKit/NSCircularBezelStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSDisclosureBezelStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSHelpButtonBezelStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSInlineBezelStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSRecessedBezelStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSRegularSquareBezelStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSRoundedBezelStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSRoundedDisclosureBezelStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSRoundRectBezelStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSShadowlessSquareBezelStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSSmallIconButtonBezelStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSThickerSquareBezelStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSThickSquareBezelStyle"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1shadowlessSquare/title",
          "value": "NSBezelStyleShadowlessSquare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1shadowlessSquare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleShadowlessSquare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1texturedSquare/title",
          "value": "NSBezelStyleTexturedSquare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1texturedSquare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleTexturedSquare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum/title",
          "value": "NSBezelStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nssmallsquarebezelstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
