{
  "abstract": [
    {
      "text": "The text-scaling mode you used when creating the text.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSSourceTextScalingDocumentAttribute"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSSourceTextScalingDocumentAttribute",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSSourceTextScalingDocumentAttribute"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSSourceTextScalingDocumentAttribute"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSSourceTextScalingDocumentAttribute"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentAttributeKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
              "text": "NSAttributedStringDocumentAttributeKey"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSSourceTextScalingDocumentAttribute"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value of this property is one of the options of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextScalingType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " type. Some platforms scale fonts to improve their appearance. Include this attribute to specify the original text-scaling mode you used to create the text.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentAttributeKey": {
      "abstract": [
        {
          "text": "The attributes you apply to an entire document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAttributedStringDocumentAttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentAttributeKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedStringDocumentAttributeKey",
      "type": "topic",
      "url": "/documentation/appkit/nsattributedstringdocumentattributekey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSourceTextScalingDocumentAttribute": {
      "abstract": [
        {
          "text": "The text-scaling mode you used when creating the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSSourceTextScalingDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSourceTextScalingDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSourceTextScalingDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nssourcetextscalingdocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextScalingDocumentAttribute": {
      "abstract": [
        {
          "text": "The text-scaling mode to use when displaying the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextScalingDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextScalingDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextScalingDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nstextscalingdocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextScalingType": {
      "abstract": [
        {
          "text": "Constants that specify the text scaling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextScalingType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextScalingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextScalingType"
        }
      ],
      "role": "symbol",
      "title": "NSTextScalingType",
      "type": "topic",
      "url": "/documentation/appkit/nstextscalingtype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-font-scaling-options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextScalingDocumentAttribute"
      ],
      "title": "Getting the font-scaling options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextScalingType/title",
          "value": "NSTextScalingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextScalingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextScalingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextScalingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextScalingType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nssourcetextscalingdocumentattribute"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
