{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSSpellCheckerDidChangeAutomaticInlinePredictionNotification"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSSpellCheckerDidChangeAutomaticInlinePredictionNotification",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSSpellCheckerDidChangeAutomaticInlinePredictionNotification"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSSpellCheckerDidChangeAutomaticInlinePredictionNotification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSSpellCheckerDidChangeAutomaticInlinePredictionNotification"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSNotificationName",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSNotificationName",
              "text": "NSNotificationName"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSSpellCheckerDidChangeAutomaticInlinePredictionNotification"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/didChangeAutomaticSpellingCorrectionNotification": {
      "abstract": [
        {
          "text": "This notification is posted when the spell checker did change text using automatic spell checking correction. The are posted to the application’s default notification center.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didChangeAutomaticSpellingCorrectionNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/didChangeAutomaticSpellingCorrectionNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSpellCheckerDidChangeAutomaticSpellingCorrectionNotification"
        }
      ],
      "role": "symbol",
      "title": "didChangeAutomaticSpellingCorrectionNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsspellchecker/didchangeautomaticspellingcorrectionnotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/didChangeAutomaticTextReplacementNotification": {
      "abstract": [
        {
          "text": "Posted when the spell checker changed text using automatic text replacement.  This notification is posted to the app’s default notification center.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didChangeAutomaticTextReplacementNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/didChangeAutomaticTextReplacementNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSpellCheckerDidChangeAutomaticTextReplacementNotification"
        }
      ],
      "role": "symbol",
      "title": "didChangeAutomaticTextReplacementNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsspellchecker/didchangeautomatictextreplacementnotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpellCheckerDidChangeAutomaticInlinePredictionNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSSpellCheckerDidChangeAutomaticInlinePredictionNotification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpellCheckerDidChangeAutomaticInlinePredictionNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSpellCheckerDidChangeAutomaticInlinePredictionNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsspellcheckerdidchangeautomaticinlinepredictionnotification"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSNotificationName": {
      "abstract": [
        {
          "text": "A structure that defines the name of a notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "NSNotification.Name"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSNotificationName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNotification.Name",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Notifications",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/didChangeAutomaticSpellingCorrectionNotification",
        "doc://com.apple.appkit/documentation/AppKit/NSSpellChecker/didChangeAutomaticTextReplacementNotification"
      ],
      "title": "Notifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1didChangeAutomaticTextReplacementNotification/title",
          "value": "NSSpellCheckerDidChangeAutomaticTextReplacementNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1didChangeAutomaticTextReplacementNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSpellCheckerDidChangeAutomaticTextReplacementNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSNotificationName/title",
          "value": "NSNotificationName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1didChangeAutomaticSpellingCorrectionNotification/title",
          "value": "NSSpellCheckerDidChangeAutomaticSpellingCorrectionNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSpellChecker~1didChangeAutomaticSpellingCorrectionNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSpellCheckerDidChangeAutomaticSpellingCorrectionNotification"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsspellcheckerdidchangeautomaticinlinepredictionnotification"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
