{
  "abstract": [
    {
      "text": "Constants for the spelling state attribute key.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSSpellingState"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSSpellingState",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSSpellingState"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSSpellingState"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSSpellingState"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSSpellingState"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these constants as the values for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpellingStateAttributeName",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpellingState": {
      "abstract": [
        {
          "text": "Constants for the spelling state attribute key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSSpellingState"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpellingState",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSpellingState",
      "type": "topic",
      "url": "/documentation/appkit/nsspellingstate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpellingState/NSSpellingStateGrammarFlag": {
      "abstract": [
        {
          "text": "Flag for grammar issues.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSSpellingStateGrammarFlag"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpellingState/NSSpellingStateGrammarFlag",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSpellingStateGrammarFlag",
      "type": "topic",
      "url": "/documentation/appkit/nsspellingstate/nsspellingstategrammarflag"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpellingState/NSSpellingStateSpellingFlag": {
      "abstract": [
        {
          "text": "Flag for spelling issues.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSSpellingStateSpellingFlag"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpellingState/NSSpellingStateSpellingFlag",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSpellingStateSpellingFlag",
      "type": "topic",
      "url": "/documentation/appkit/nsspellingstate/nsspellingstatespellingflag"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpellingStateAttributeName": {
      "abstract": [
        {
          "text": "The spelling state of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSSpellingStateAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpellingStateAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSpellingStateAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsspellingstateattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextEffectStyle": {
      "abstract": [
        {
          "text": "Constants for the type of effect to apply to the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextEffectStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextEffectStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextEffectStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstexteffectstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorScheme": {
      "abstract": [
        {
          "text": "Constants that specify the highlight color to use with the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextHighlightColorScheme"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorScheme",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextHighlightColorScheme",
      "type": "topic",
      "url": "/documentation/appkit/nstexthighlightcolorscheme"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightStyle": {
      "abstract": [
        {
          "text": "Constants that specify the type of highlight to apply to text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextHighlightStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextHighlightStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstexthighlightstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle": {
      "abstract": [
        {
          "text": "Constants for the underline style and strikethrough style attribute keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStyle"
        }
      ],
      "role": "symbol",
      "title": "NSUnderlineStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsunderlinestyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingDirectionFormatType": {
      "abstract": [
        {
          "text": "Constants for the writing direction attribute key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWritingDirectionFormatType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingDirectionFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingDirectionFormatType"
        }
      ],
      "role": "symbol",
      "title": "NSWritingDirectionFormatType",
      "type": "topic",
      "url": "/documentation/appkit/nswritingdirectionformattype"
    },
    "doc://com.apple.appkit/documentation/AppKit/textkit-string-attribute-keys": {
      "abstract": [
        {
          "text": "AppKit-specific keys you use to apply attributes to ranges of characters in an attributed string.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/textkit-string-attribute-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TextKit string attribute keys",
      "type": "topic",
      "url": "/documentation/appkit/textkit-string-attribute-keys"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-text-content-attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/textkit-string-attribute-keys",
        "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorScheme",
        "doc://com.apple.appkit/documentation/AppKit/NSTextEffectStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingDirectionFormatType"
      ],
      "title": "Getting text content attributes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-spelling-states",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSpellingState/NSSpellingStateGrammarFlag",
        "doc://com.apple.appkit/documentation/AppKit/NSSpellingState/NSSpellingStateSpellingFlag"
      ],
      "title": "Getting the spelling states"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirectionFormatType/title",
          "value": "NSWritingDirectionFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirectionFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingDirectionFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirectionFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingDirectionFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle/title",
          "value": "NSUnderlineStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsspellingstate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
