{
  "abstract": [
    {
      "text": "Specifies a square line cap style for endpoints for an open path when stroked.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/square",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSSquareLineCapStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSSquareLineCapStyle",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSSquareLineCapStyle"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSSquareLineCapStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSSquareLineCapStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSLineCapStyle",
              "text": "NSLineCapStyle"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSSquareLineCapStyle"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Here is an example of the appearance of this style:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2934722",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify the shape of endpoints for an open path when it is stroked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LineCapStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LineCapStyle"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.LineCapStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/linecapstyle-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/square": {
      "abstract": [
        {
          "text": "Specifies a square line cap style for endpoints for an open path when stroked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "square"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/LineCapStyle-swift.enum/square",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLineCapStyleSquare"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.LineCapStyle.square",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/linecapstyle-swift.enum/square"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButtLineCapStyle": {
      "abstract": [
        {
          "text": "Specifies a butt line cap style for endpoints for an open path when stroked.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSButtLineCapStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButtLineCapStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSButtLineCapStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsbuttlinecapstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRoundLineCapStyle": {
      "abstract": [
        {
          "text": "Specifies a round line cap style for endpoints for an open path when stroked.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRoundLineCapStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRoundLineCapStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRoundLineCapStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsroundlinecapstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSquareLineCapStyle": {
      "abstract": [
        {
          "text": "Specifies a square line cap style for endpoints for an open path when stroked.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSSquareLineCapStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSquareLineCapStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSquareLineCapStyle",
      "type": "topic",
      "url": "/documentation/appkit/nssquarelinecapstyle"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "media-2934722": {
      "alt": "Diagram that shows the square line cap style.",
      "identifier": "media-2934722",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/a3cd231f2dc0cf94a29bb49fc6fece5d/media-2934722@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSButtLineCapStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSRoundLineCapStyle"
      ],
      "title": "Deprecated Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum~1square/title",
          "value": "NSLineCapStyleSquare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum~1square/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineCapStyleSquare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum/title",
          "value": "NSLineCapStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineCapStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1LineCapStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineCapStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nssquarelinecapstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
