{
  "abstract": [
    {
      "text": "Constants that specify the rendering options for drawing a string.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingOptions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSStringDrawingOptions",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSStringDrawingOptions"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSStringDrawingOptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSStringDrawingOptions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSStringDrawingOptions"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingContext": {
      "abstract": [
        {
          "text": "An object that manages metrics for drawing attributed strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStringDrawingContext"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStringDrawingContext"
        }
      ],
      "role": "symbol",
      "title": "NSStringDrawingContext",
      "type": "topic",
      "url": "/documentation/appkit/nsstringdrawingcontext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingOptions": {
      "abstract": [
        {
          "text": "Constants that specify the rendering options for drawing a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStringDrawingOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingOptions",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStringDrawingOptions",
      "type": "topic",
      "url": "/documentation/appkit/nsstringdrawingoptions"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingOptions/NSStringDrawingDisableScreenFontSubstitution": {
      "abstract": [
        {
          "text": "An option that disables screen font substitution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStringDrawingDisableScreenFontSubstitution"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingOptions/NSStringDrawingDisableScreenFontSubstitution",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStringDrawingDisableScreenFontSubstitution",
      "type": "topic",
      "url": "/documentation/appkit/nsstringdrawingoptions/nsstringdrawingdisablescreenfontsubstitution"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingOptions/NSStringDrawingOneShot": {
      "abstract": [
        {
          "text": "Suppresses caching layout information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStringDrawingOneShot"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingOptions/NSStringDrawingOneShot",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStringDrawingOneShot",
      "type": "topic",
      "url": "/documentation/appkit/nsstringdrawingoptions/nsstringdrawingoneshot"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingOptions/NSStringDrawingTruncatesLastVisibleLine": {
      "abstract": [
        {
          "text": "Truncates and adds the ellipsis character to the last visible line if the text doesn’t fit into the specified bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStringDrawingTruncatesLastVisibleLine"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingOptions/NSStringDrawingTruncatesLastVisibleLine",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStringDrawingTruncatesLastVisibleLine",
      "type": "topic",
      "url": "/documentation/appkit/nsstringdrawingoptions/nsstringdrawingtruncateslastvisibleline"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingOptions/NSStringDrawingUsesDeviceMetrics": {
      "abstract": [
        {
          "text": "Uses image glyph bounds instead of typographic bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStringDrawingUsesDeviceMetrics"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingOptions/NSStringDrawingUsesDeviceMetrics",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStringDrawingUsesDeviceMetrics",
      "type": "topic",
      "url": "/documentation/appkit/nsstringdrawingoptions/nsstringdrawingusesdevicemetrics"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingOptions/NSStringDrawingUsesFontLeading": {
      "abstract": [
        {
          "text": "Uses the font leading for calculating line heights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStringDrawingUsesFontLeading"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingOptions/NSStringDrawingUsesFontLeading",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStringDrawingUsesFontLeading",
      "type": "topic",
      "url": "/documentation/appkit/nsstringdrawingoptions/nsstringdrawingusesfontleading"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingOptions/NSStringDrawingUsesLineFragmentOrigin": {
      "abstract": [
        {
          "text": "Uses the line fragment origin instead of the baseline origin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStringDrawingUsesLineFragmentOrigin"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingOptions/NSStringDrawingUsesLineFragmentOrigin",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStringDrawingUsesLineFragmentOrigin",
      "type": "topic",
      "url": "/documentation/appkit/nsstringdrawingoptions/nsstringdrawinguseslinefragmentorigin"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Strings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingContext"
      ],
      "title": "Strings"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingOptions/NSStringDrawingUsesLineFragmentOrigin",
        "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingOptions/NSStringDrawingUsesFontLeading",
        "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingOptions/NSStringDrawingUsesDeviceMetrics",
        "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingOptions/NSStringDrawingTruncatesLastVisibleLine",
        "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingOptions/NSStringDrawingDisableScreenFontSubstitution",
        "doc://com.apple.appkit/documentation/AppKit/NSStringDrawingOptions/NSStringDrawingOneShot"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStringDrawingContext/title",
          "value": "NSStringDrawingContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStringDrawingContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringDrawingContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStringDrawingContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringDrawingContext"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsstringdrawingoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
