{
  "abstract": [
    {
      "text": "A single action to present when the user swipes horizontally on a table row.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSTableViewRowAction",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSTableViewRowAction"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTableViewRowAction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSTableViewRowAction"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTableViewRowAction"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In an editable table, performing a horizontal swipe on a row reveals a button to delete the row by default. This class lets you define one or more custom actions to display for a given row in your table. Each instance of this class represents a single action to perform and includes the text, formatting information, and behavior for the corresponding button.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To add custom actions to your table view’s rows, implement the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:rowActionsForRow:edge:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method in your table view’s delegate object. In that method, create and return an array of actions for the specified row. The table handles the remaining work of displaying the action buttons and executing the appropriate handler block when the user clicks the button.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableColumn": {
      "abstract": [
        {
          "text": "The display characteristics and identifier for a column in a table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableColumn"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableColumn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableColumn"
        }
      ],
      "role": "symbol",
      "title": "NSTableColumn",
      "type": "topic",
      "url": "/documentation/appkit/nstablecolumn"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/ResizingOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ResizingOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/ResizingOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ResizingOptions"
        }
      ],
      "role": "symbol",
      "title": "NSTableColumn.ResizingOptions",
      "type": "topic",
      "url": "/documentation/appkit/nstablecolumn/resizingoptions"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableHeaderCell": {
      "abstract": [
        {
          "text": "An object that a table header view uses to draw the content of the column headers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableHeaderCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableHeaderCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableHeaderCell"
        }
      ],
      "role": "symbol",
      "title": "NSTableHeaderCell",
      "type": "topic",
      "url": "/documentation/appkit/nstableheadercell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableHeaderView": {
      "abstract": [
        {
          "text": "An object that draws headers over a table view’s columns and handles mouse events in those headers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableHeaderView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableHeaderView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableHeaderView"
        }
      ],
      "role": "symbol",
      "title": "NSTableHeaderView",
      "type": "topic",
      "url": "/documentation/appkit/nstableheaderview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableRowView": {
      "abstract": [
        {
          "text": "The view shown for a row in a table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableRowView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableRowView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableRowView"
        }
      ],
      "role": "symbol",
      "title": "NSTableRowView",
      "type": "topic",
      "url": "/documentation/appkit/nstablerowview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:rowActionsForRow:edge:)": {
      "abstract": [
        {
          "text": "Asks the delegate to provide an array of row actions to be attached to the specified edge of a table row and displayed when the user swipes horizontally across the row.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tableView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableView",
          "text": "NSTableView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rowActionsForRow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "edge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableView",
          "text": "NSTableView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTableRowActionEdge",
          "text": "RowActionEdge"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableViewRowAction",
          "text": "NSTableViewRowAction"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:rowActionsForRow:edge:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tableView:rowActionsForRow:edge:"
        }
      ],
      "role": "symbol",
      "title": "tableView(_:rowActionsForRow:edge:)",
      "type": "topic",
      "url": "/documentation/appkit/nstableviewdelegate/tableview(_:rowactionsforrow:edge:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction": {
      "abstract": [
        {
          "text": "A single action to present when the user swipes horizontally on a table row.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableViewRowAction"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewRowAction"
        }
      ],
      "role": "symbol",
      "title": "NSTableViewRowAction",
      "type": "topic",
      "url": "/documentation/appkit/nstableviewrowaction"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction/Style-swift.enum": {
      "abstract": [
        {
          "text": "Constants that help define the appearance and behavior of action buttons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Style"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction/Style-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Style"
        }
      ],
      "role": "symbol",
      "title": "NSTableViewRowAction.Style",
      "type": "topic",
      "url": "/documentation/appkit/nstableviewrowaction/style-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction/backgroundColor": {
      "abstract": [
        {
          "text": "The background color of the action button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction/backgroundColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backgroundColor"
        }
      ],
      "role": "symbol",
      "title": "backgroundColor",
      "type": "topic",
      "url": "/documentation/appkit/nstableviewrowaction/backgroundcolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction/image": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction/image",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "image"
        }
      ],
      "role": "symbol",
      "title": "image",
      "type": "topic",
      "url": "/documentation/appkit/nstableviewrowaction/image"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction/init(style:title:handler:)": {
      "abstract": [
        {
          "text": "Creates and returns a new table view row action object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "style"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableViewRowAction",
          "text": "NSTableViewRowAction"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTableViewRowActionStyle",
          "text": "Style"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableViewRowAction",
          "text": "NSTableViewRowAction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction/init(style:title:handler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rowActionWithStyle:title:handler:"
        }
      ],
      "role": "symbol",
      "title": "init(style:title:handler:)",
      "type": "topic",
      "url": "/documentation/appkit/nstableviewrowaction/init(style:title:handler:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction/style-swift.property": {
      "abstract": [
        {
          "text": "The style applied to the action button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "style"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableViewRowAction",
          "text": "NSTableViewRowAction"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTableViewRowActionStyle",
          "text": "Style"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction/style-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "style"
        }
      ],
      "role": "symbol",
      "title": "style",
      "type": "topic",
      "url": "/documentation/appkit/nstableviewrowaction/style-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction/title": {
      "abstract": [
        {
          "text": "The title of the action button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/appkit/nstableviewrowaction/title"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Rows-and-Columns",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableHeaderView",
        "doc://com.apple.appkit/documentation/AppKit/NSTableHeaderCell",
        "doc://com.apple.appkit/documentation/AppKit/NSTableRowView",
        "doc://com.apple.appkit/documentation/AppKit/NSTableColumn",
        "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/ResizingOptions"
      ],
      "title": "Rows and Columns"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Table-Row-Action",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction/init(style:title:handler:)"
      ],
      "title": "Creating a Table Row Action"
    },
    {
      "anchor": "Configuring-the-Actions-Appearance",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction/style-swift.property",
        "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction/title",
        "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction/backgroundColor"
      ],
      "title": "Configuring the Action’s Appearance"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction/Style-swift.enum"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction/image"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTableViewRowAction"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewRowAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewRowAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Table-Row-Action",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction/init(style:title:handler:)"
              ],
              "title": "Creating a Table Row Action"
            },
            {
              "anchor": "Configuring-the-Actions-Appearance",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction/style-swift.property",
                "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction/title",
                "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction/backgroundColor"
              ],
              "title": "Configuring the Action’s Appearance"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction/Style-swift.enum"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction/image"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Rows-and-Columns",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTableHeaderView",
                "doc://com.apple.appkit/documentation/AppKit/NSTableHeaderCell",
                "doc://com.apple.appkit/documentation/AppKit/NSTableRowView",
                "doc://com.apple.appkit/documentation/AppKit/NSTableColumn",
                "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/ResizingOptions"
              ],
              "title": "Rows and Columns"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSTableViewRowAction"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewRowAction/title",
          "value": "NSTableViewRowAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewRowAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewRowAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewRowAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewRowAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:rowActionsForRow:edge:)/title",
          "value": "tableView:rowActionsForRow:edge:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:rowActionsForRow:edge:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tableView:rowActionsForRow:edge:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn/title",
          "value": "NSTableColumn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableColumn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableColumn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableRowView/title",
          "value": "NSTableRowView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableRowView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableRowView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableRowView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableRowView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableHeaderView/title",
          "value": "NSTableHeaderView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableHeaderView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableHeaderView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableHeaderView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableHeaderView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewRowAction~1title/title",
          "value": "title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewRowAction~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewRowAction~1style-swift.property/title",
          "value": "style"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewRowAction~1style-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "style"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableHeaderCell/title",
          "value": "NSTableHeaderCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableHeaderCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableHeaderCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableHeaderCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableHeaderCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewRowAction~1backgroundColor/title",
          "value": "backgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewRowAction~1backgroundColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backgroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewRowAction~1image/title",
          "value": "image"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewRowAction~1image/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "image"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewRowAction~1Style-swift.enum/title",
          "value": "NSTableViewRowActionStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewRowAction~1Style-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewRowActionStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewRowAction~1Style-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewRowActionStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewRowAction~1init(style:title:handler:)/title",
          "value": "rowActionWithStyle:title:handler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewRowAction~1init(style:title:handler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "rowActionWithStyle:title:handler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1ResizingOptions/title",
          "value": "NSTableColumnResizingOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1ResizingOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableColumnResizingOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1ResizingOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableColumnResizingOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstableviewrowaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstableviewrowaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
