{"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate","doc://com.externally.resolved.symbol/c:objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"abstract":[{"type":"text","text":"A set of optional methods you implement in a table view delegate to customize the behavior of the table view."}],"seeAlsoSections":[{"anchor":"Management","generated":true,"title":"Management","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource","doc://com.apple.appkit/documentation/AppKit/NSTableViewDiffableDataSource-c5gl"]}],"topicSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:viewFor:row:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:rowViewForRow:)"],"anchor":"Providing-views-for-rows-and-columns","title":"Providing views for rows and columns"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:didAdd:forRow:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:didRemove:forRow:)"],"anchor":"Notification-of-row-views-being-added-or-removed","title":"Notification of row views being added or removed"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:isGroupRow:)"],"anchor":"Grouping-rows","title":"Grouping rows"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:willDisplayCell:for:row:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:dataCellFor:row:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:shouldShowCellExpansionFor:row:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:toolTipFor:rect:tableColumn:row:mouseLocation:)"],"anchor":"Providing-cells-for-rows-and-columns","title":"Providing cells for rows and columns"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:shouldEdit:row:)"],"anchor":"Editing-cells","title":"Editing cells"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:heightOfRow:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:sizeToFitWidthOfColumn:)"],"anchor":"Setting-row-and-column-size","title":"Setting row and column size"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/selectionShouldChange(in:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:shouldSelectRow:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:selectionIndexesForProposedSelection:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:shouldSelect:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableViewSelectionIsChanging(_:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableViewSelectionDidChange(_:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:shouldTypeSelectFor:withCurrentSearch:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:typeSelectStringFor:row:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:nextTypeSelectMatchFromRow:toRow:for:)"],"anchor":"Selecting-rows","title":"Selecting rows"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:shouldReorderColumn:toColumn:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:didDrag:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableViewColumnDidMove(_:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableViewColumnDidResize(_:)"],"anchor":"Moving-and-resizing-columns","title":"Moving and resizing columns"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:didClick:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:mouseDownInHeaderOf:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:shouldTrackCell:for:row:)"],"anchor":"Responding-to-mouse-events","title":"Responding to mouse events"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:rowActionsForRow:edge:)"],"anchor":"Enabling-table-row-actions","title":"Enabling table row actions"},{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:userCanChangeVisibilityOf:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:userDidChangeVisibilityOf:)"],"anchor":"Showing-and-hiding-columns","title":"Showing and hiding columns"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate"},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSTableViewDelegate"},{"kind":"text","text":" : "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSControlTextEditingDelegate","text":"NSControlTextEditingDelegate"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"Using a table view delegate allows you to customize a table view’s behavior without creating a table view subclass. A table view delegate provides views for table rows and columns, and supports functionality such as column reordering and resizing and row selection. To learn more about table views, see ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableView","type":"reference","isActive":true},{"text":".","type":"text"}]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSTableViewDelegate"}],"role":"symbol","symbolKind":"protocol","modules":[{"name":"AppKit"}],"title":"NSTableViewDelegate","navigatorTitle":[{"kind":"identifier","text":"NSTableViewDelegate"}],"platforms":[{"name":"macOS","unavailable":false,"beta":false,"deprecated":false}],"roleHeading":"Protocol","externalID":"c:objc(pl)NSTableViewDelegate"},"variants":[{"paths":["/documentation/appkit/nstableviewdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nstableviewdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:rowViewForRow:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:rowViewForRow:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTableView","preciseIdentifier":"c:objc(cs)NSTableView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rowViewForRow","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)NSTableRowView","text":"NSTableRowView","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","abstract":[{"type":"text","text":"Asks the delegate for a view to display the specified row."}],"url":"/documentation/appkit/nstableviewdelegate/tableview(_:rowviewforrow:)","title":"tableView(_:rowViewForRow:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"tableView:rowViewForRow:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:shouldSelect:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableView","text":"NSTableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldSelect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableColumn","text":"NSTableColumn"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"tableView(_:shouldSelect:)","url":"/documentation/appkit/nstableviewdelegate/tableview(_:shouldselect:)","abstract":[{"text":"Asks the delegate whether the specified table column can be selected.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:shouldSelect:)","navigatorTitle":[{"kind":"identifier","text":"tableView:shouldSelectTableColumn:"}],"kind":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:userDidChangeVisibilityOf:)":{"url":"/documentation/appkit/nstableviewdelegate/tableview(_:userdidchangevisibilityof:)","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSTableView","kind":"typeIdentifier","text":"NSTableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userDidChangeVisibilityOf"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)NSTableColumn","kind":"typeIdentifier","text":"NSTableColumn"},{"kind":"text","text":"])"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:userDidChangeVisibilityOf:)","navigatorTitle":[{"kind":"identifier","text":"tableView:userDidChangeVisibilityOfTableColumns:"}],"abstract":[{"type":"text","text":"Tells the delegate that the user changed the visibility of one or more table columns."}],"title":"tableView(_:userDidChangeVisibilityOf:)"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:mouseDownInHeaderOf:)":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:mouseDownInHeaderOf:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableView"},{"text":", ","kind":"text"},{"text":"mouseDownInHeaderOf","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSTableColumn","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableColumn"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that the mouse button was clicked in the specified table column’s header."}],"type":"topic","url":"/documentation/appkit/nstableviewdelegate/tableview(_:mousedowninheaderof:)","title":"tableView(_:mouseDownInHeaderOf:)","navigatorTitle":[{"kind":"identifier","text":"tableView:mouseDownInHeaderOfTableColumn:"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:shouldTrackCell:for:row:)":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:shouldTrackCell:for:row:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableView"},{"text":", ","kind":"text"},{"text":"shouldTrackCell","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCell","text":"NSCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableColumn","text":"NSTableColumn"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"row"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Asks the delegate whether the specified cell should be tracked."}],"type":"topic","url":"/documentation/appkit/nstableviewdelegate/tableview(_:shouldtrackcell:for:row:)","title":"tableView(_:shouldTrackCell:for:row:)","navigatorTitle":[{"text":"tableView:shouldTrackCell:forTableColumn:row:","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:rowActionsForRow:edge:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:rowActionsForRow:edge:)","type":"topic","url":"/documentation/appkit/nstableviewdelegate/tableview(_:rowactionsforrow:edge:)","role":"symbol","kind":"symbol","abstract":[{"text":"Asks the delegate to provide an array of row actions to be attached to the specified edge of a table row and displayed when the user swipes horizontally across the row.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSTableView","preciseIdentifier":"c:objc(cs)NSTableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rowActionsForRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"edge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSTableView","preciseIdentifier":"c:objc(cs)NSTableView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"RowActionEdge","preciseIdentifier":"c:@E@NSTableRowActionEdge"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableViewRowAction","text":"NSTableViewRowAction"},{"kind":"text","text":"]"}],"title":"tableView(_:rowActionsForRow:edge:)","navigatorTitle":[{"kind":"identifier","text":"tableView:rowActionsForRow:edge:"}]},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:isGroupRow:)":{"url":"/documentation/appkit/nstableviewdelegate/tableview(_:isgrouprow:)","type":"topic","title":"tableView(_:isGroupRow:)","kind":"symbol","navigatorTitle":[{"text":"tableView:isGroupRow:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:isGroupRow:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableView","text":"NSTableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isGroupRow"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Returns whether the specified row is a group row."}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:userCanChangeVisibilityOf:)":{"title":"tableView(_:userCanChangeVisibilityOf:)","abstract":[{"type":"text","text":"Asks the delegate to verify that the user can change the given column’s visibility."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"tableView:userCanChangeVisibilityOfTableColumn:"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:userCanChangeVisibilityOf:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSTableView","preciseIdentifier":"c:objc(cs)NSTableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userCanChangeVisibilityOf"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSTableColumn","preciseIdentifier":"c:objc(cs)NSTableColumn"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"/documentation/appkit/nstableviewdelegate/tableview(_:usercanchangevisibilityof:)"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:shouldEdit:row:)":{"title":"tableView(_:shouldEdit:row:)","abstract":[{"text":"Asks the delegate if the cell at the specified row and column can be edited.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableView","text":"NSTableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldEdit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableColumn","text":"NSTableColumn"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"row"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","url":"/documentation/appkit/nstableviewdelegate/tableview(_:shouldedit:row:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:shouldEdit:row:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"tableView:shouldEditTableColumn:row:"}]},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:shouldShowCellExpansionFor:row:)":{"title":"tableView(_:shouldShowCellExpansionFor:row:)","navigatorTitle":[{"text":"tableView:shouldShowCellExpansionForTableColumn:row:","kind":"identifier"}],"url":"/documentation/appkit/nstableviewdelegate/tableview(_:shouldshowcellexpansionfor:row:)","abstract":[{"type":"text","text":"Asks the delegate if an expansion tooltip should be displayed for a specific row and column."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:shouldShowCellExpansionFor:row:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTableView","preciseIdentifier":"c:objc(cs)NSTableView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldShowCellExpansionFor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSTableColumn","kind":"typeIdentifier","text":"NSTableColumn"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"row"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:sizeToFitWidthOfColumn:)":{"title":"tableView(_:sizeToFitWidthOfColumn:)","abstract":[{"type":"text","text":"Asks the delegate to provide custom sizing behavior when a column’s resize divider is double clicked."}],"url":"/documentation/appkit/nstableviewdelegate/tableview(_:sizetofitwidthofcolumn:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableView","text":"NSTableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sizeToFitWidthOfColumn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:sizeToFitWidthOfColumn:)","navigatorTitle":[{"kind":"identifier","text":"tableView:sizeToFitWidthOfColumn:"}]},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:didRemove:forRow:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:didRemove:forRow:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableView","text":"NSTableView"},{"kind":"text","text":", "},{"text":"didRemove","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSTableRowView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableRowView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"title":"tableView(_:didRemove:forRow:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"tableView:didRemoveRowView:forRow:"}],"url":"/documentation/appkit/nstableviewdelegate/tableview(_:didremove:forrow:)","abstract":[{"type":"text","text":"Tells the delegate that a row view was removed from the table at the specified row."}],"type":"topic","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableViewColumnDidMove(_:)":{"title":"tableViewColumnDidMove(_:)","url":"/documentation/appkit/nstableviewdelegate/tableviewcolumndidmove(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"tableViewColumnDidMove:"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableViewColumnDidMove"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableViewColumnDidMove(_:)","role":"symbol","abstract":[{"type":"text","text":"Tells the delegate that a table column was moved by user action."}]},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:nextTypeSelectMatchFromRow:toRow:for:)":{"title":"tableView(_:nextTypeSelectMatchFromRow:toRow:for:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"tableView:nextTypeSelectMatchFromRow:toRow:forString:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:nextTypeSelectMatchFromRow:toRow:for:)","kind":"symbol","type":"topic","url":"/documentation/appkit/nstableviewdelegate/tableview(_:nexttypeselectmatchfromrow:torow:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableView","text":"NSTableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nextTypeSelectMatchFromRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"toRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Asks the delegate for the row within the specified search range that matches the specified string."}]},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:dataCellFor:row:)":{"type":"topic","abstract":[{"type":"text","text":"Asks the delegate for a custom data cell for the specified row and column."}],"url":"/documentation/appkit/nstableviewdelegate/tableview(_:datacellfor:row:)","title":"tableView(_:dataCellFor:row:)","navigatorTitle":[{"kind":"identifier","text":"tableView:dataCellForTableColumn:row:"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"text":"NSTableView","preciseIdentifier":"c:objc(cs)NSTableView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dataCellFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSTableColumn","preciseIdentifier":"c:objc(cs)NSTableColumn","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"row","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSCell","preciseIdentifier":"c:objc(cs)NSCell","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:dataCellFor:row:)"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate":{"kind":"symbol","url":"/documentation/appkit/nstableviewdelegate","title":"NSTableViewDelegate","navigatorTitle":[{"text":"NSTableViewDelegate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"NSTableViewDelegate","kind":"identifier"}],"type":"topic","abstract":[{"text":"A set of optional methods you implement in a table view delegate to customize the behavior of the table view.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableViewSelectionDidChange(_:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableViewSelectionDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV","text":"Notification"},{"kind":"text","text":")"}],"title":"tableViewSelectionDidChange(_:)","url":"/documentation/appkit/nstableviewdelegate/tableviewselectiondidchange(_:)","abstract":[{"text":"Tells the delegate that the table view’s selection has changed.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableViewSelectionDidChange(_:)","navigatorTitle":[{"kind":"identifier","text":"tableViewSelectionDidChange:"}],"kind":"symbol","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource":{"abstract":[{"type":"text","text":"A set of methods that a table view uses to provide data to a table view and to allow the editing of the table view’s data source object."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSTableViewDataSource","kind":"identifier"}],"url":"/documentation/appkit/nstableviewdatasource","navigatorTitle":[{"kind":"identifier","text":"NSTableViewDataSource"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource","kind":"symbol","role":"symbol","type":"topic","title":"NSTableViewDataSource"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/selectionShouldChange(in:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectionShouldChange","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableView","text":"NSTableView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"selectionShouldChange(in:)","url":"/documentation/appkit/nstableviewdelegate/selectionshouldchange(in:)","abstract":[{"text":"Asks the delegate if the user is allowed to change the selection.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/selectionShouldChange(in:)","navigatorTitle":[{"kind":"identifier","text":"selectionShouldChangeInTableView:"}],"kind":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableViewColumnDidResize(_:)":{"kind":"symbol","title":"tableViewColumnDidResize(_:)","abstract":[{"text":"Tells the delegate that a table column was resized.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableViewColumnDidResize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableViewColumnDidResize(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"tableViewColumnDidResize:"}],"url":"/documentation/appkit/nstableviewdelegate/tableviewcolumndidresize(_:)","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:shouldSelectRow:)":{"title":"tableView(_:shouldSelectRow:)","role":"symbol","navigatorTitle":[{"text":"tableView:shouldSelectRow:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:shouldSelectRow:)","kind":"symbol","type":"topic","url":"/documentation/appkit/nstableviewdelegate/tableview(_:shouldselectrow:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableView","text":"NSTableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldSelectRow"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Asks the delegate if the table view should allow selection of the specified row."}]},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:didDrag:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:didDrag:)","navigatorTitle":[{"kind":"identifier","text":"tableView:didDragTableColumn:"}],"kind":"symbol","url":"/documentation/appkit/nstableviewdelegate/tableview(_:diddrag:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSTableView","kind":"typeIdentifier","text":"NSTableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDrag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSTableColumn","preciseIdentifier":"c:objc(cs)NSTableColumn"},{"kind":"text","text":")"}],"abstract":[{"text":"Tells the delegate that the specified table column was dragged.","type":"text"}],"title":"tableView(_:didDrag:)"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:selectionIndexesForProposedSelection:)":{"title":"tableView(_:selectionIndexesForProposedSelection:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"tableView:selectionIndexesForProposedSelection:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:selectionIndexesForProposedSelection:)","kind":"symbol","type":"topic","url":"/documentation/appkit/nstableviewdelegate/tableview(_:selectionindexesforproposedselection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableView","text":"NSTableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"selectionIndexesForProposedSelection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation8IndexSetV","text":"IndexSet"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation8IndexSetV","text":"IndexSet"}],"abstract":[{"type":"text","text":"Asks the delegate to accept or reject the proposed selection."}]},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:didClick:)":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:didClick:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableView"},{"text":", ","kind":"text"},{"text":"didClick","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSTableColumn","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableColumn"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Tells the delegate that the mouse button was clicked in the specified table column, but the column was not dragged."}],"type":"topic","url":"/documentation/appkit/nstableviewdelegate/tableview(_:didclick:)","title":"tableView(_:didClick:)","navigatorTitle":[{"text":"tableView:didClickTableColumn:","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableViewSelectionIsChanging(_:)":{"title":"tableViewSelectionIsChanging(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"tableViewSelectionIsChanging:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableViewSelectionIsChanging(_:)","kind":"symbol","type":"topic","url":"/documentation/appkit/nstableviewdelegate/tableviewselectionischanging(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableViewSelectionIsChanging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV","text":"Notification"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that the table view’s selection is in the process of changing."}]},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:shouldTypeSelectFor:withCurrentSearch:)":{"title":"tableView(_:shouldTypeSelectFor:withCurrentSearch:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"tableView:shouldTypeSelectForEvent:withCurrentSearchString:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:shouldTypeSelectFor:withCurrentSearch:)","kind":"symbol","type":"topic","url":"/documentation/appkit/nstableviewdelegate/tableview(_:shouldtypeselectfor:withcurrentsearch:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSTableView","text":"NSTableView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldTypeSelectFor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withCurrentSearch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Asks the delegate to allow or deny type select for the specified event and current search string."}]},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:toolTipFor:rect:tableColumn:row:mouseLocation:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTableView","preciseIdentifier":"c:objc(cs)NSTableView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"toolTipFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSCell","preciseIdentifier":"c:objc(cs)NSCell","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rect","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRectPointer","preciseIdentifier":"c:@T@NSRectPointer","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tableColumn"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSTableColumn","kind":"typeIdentifier","text":"NSTableColumn"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"row"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"mouseLocation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPoint","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPoint"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:toolTipFor:rect:tableColumn:row:mouseLocation:)","role":"symbol","title":"tableView(_:toolTipFor:rect:tableColumn:row:mouseLocation:)","url":"/documentation/appkit/nstableviewdelegate/tableview(_:tooltipfor:rect:tablecolumn:row:mouselocation:)","navigatorTitle":[{"text":"tableView:toolTipForCell:rect:tableColumn:row:mouseLocation:","kind":"identifier"}],"abstract":[{"type":"text","text":"Asks the delegate for a string to display in a tooltip for the specified cell in the column and row."}]},"doc://com.apple.appkit/documentation/AppKit/NSTableView":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"NSTableView","kind":"identifier"}],"abstract":[{"type":"text","text":"A set of related records, displayed in rows that represent individual records and columns that represent the attributes of those records."}],"url":"/documentation/appkit/nstableview","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSTableView","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableView","title":"NSTableView"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDiffableDataSource-c5gl":{"url":"/documentation/appkit/nstableviewdiffabledatasource-c5gl","abstract":[{"type":"text","text":"The object you use to manage data and provide items for a table view."}],"role":"symbol","title":"NSTableViewDiffableDataSource","navigatorTitle":[{"kind":"identifier","text":"NSTableViewDiffableDataSource"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDiffableDataSource-c5gl","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSTableViewDiffableDataSource"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate":{"kind":"symbol","url":"/documentation/appkit/nscontroltexteditingdelegate","type":"topic","role":"symbol","navigatorTitle":[{"text":"NSControlTextEditingDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"A set of optional methods implemented by delegates of "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl","isActive":true,"type":"reference"},{"text":" subclasses to respond to editing actions.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSControlTextEditingDelegate","kind":"identifier"}],"title":"NSControlTextEditingDelegate","identifier":"doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate"},"doc://com.apple.appkit/documentation/AppKit/NSControl":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl","navigatorTitle":[{"kind":"identifier","text":"NSControl"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSControl"}],"title":"NSControl","role":"symbol","abstract":[{"text":"A specialized view, such as a button or text field, that notifies your app of relevant events using the target-action design pattern.","type":"text"}],"kind":"symbol","type":"topic","url":"/documentation/appkit/nscontrol"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:heightOfRow:)":{"url":"/documentation/appkit/nstableviewdelegate/tableview(_:heightofrow:)","kind":"symbol","abstract":[{"type":"text","text":"Asks the delegate for the height of the specified row."}],"title":"tableView(_:heightOfRow:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSTableView","kind":"typeIdentifier","text":"NSTableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"heightOfRow"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"tableView:heightOfRow:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:heightOfRow:)","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:shouldReorderColumn:toColumn:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSTableView","kind":"typeIdentifier","text":"NSTableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldReorderColumn"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"toColumn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"tableView:shouldReorderColumn:toColumn:"}],"title":"tableView(_:shouldReorderColumn:toColumn:)","type":"topic","url":"/documentation/appkit/nstableviewdelegate/tableview(_:shouldreordercolumn:tocolumn:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:shouldReorderColumn:toColumn:)","kind":"symbol","role":"symbol","abstract":[{"text":"Asks the delegate to allow or prohibit the specified column to be dragged to a new location.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:typeSelectStringFor:row:)":{"navigatorTitle":[{"kind":"identifier","text":"tableView:typeSelectStringForTableColumn:row:"}],"role":"symbol","type":"topic","url":"/documentation/appkit/nstableviewdelegate/tableview(_:typeselectstringfor:row:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSTableView","kind":"typeIdentifier","text":"NSTableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"typeSelectStringFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableColumn","text":"NSTableColumn"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"row"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:typeSelectStringFor:row:)","abstract":[{"type":"text","text":"Asks the delegate to provide an alternative text value used for type selection for the specified row and column."}],"title":"tableView(_:typeSelectStringFor:row:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:willDisplayCell:for:row:)":{"kind":"symbol","navigatorTitle":[{"text":"tableView:willDisplayCell:forTableColumn:row:","kind":"identifier"}],"abstract":[{"text":"Tells the delegate that the table view will display the specified cell at the specified row and column.","type":"text"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTableView","preciseIdentifier":"c:objc(cs)NSTableView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"willDisplayCell","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"text":"NSTableColumn","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTableColumn"},{"text":"?, ","kind":"text"},{"text":"row","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","url":"/documentation/appkit/nstableviewdelegate/tableview(_:willdisplaycell:for:row:)","title":"tableView(_:willDisplayCell:for:row:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:willDisplayCell:for:row:)"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:didAdd:forRow:)":{"url":"/documentation/appkit/nstableviewdelegate/tableview(_:didadd:forrow:)","role":"symbol","kind":"symbol","title":"tableView(_:didAdd:forRow:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:didAddRowView:forRow:"}],"abstract":[{"text":"Tells the delegate that a row view was added at the specified row.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSTableView","preciseIdentifier":"c:objc(cs)NSTableView"},{"kind":"text","text":", "},{"text":"didAdd","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSTableRowView","preciseIdentifier":"c:objc(cs)NSTableRowView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"forRow"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:didAdd:forRow:)"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"type":"topic","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"url":"/documentation/objectivec/nsobjectprotocol","title":"NSObjectProtocol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDiffableDataSourceReference":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The object you use to manage data and provide items for a table view."}],"kind":"symbol","url":"/documentation/appkit/nstableviewdiffabledatasourcereference","title":"NSTableViewDiffableDataSourceReference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDiffableDataSourceReference","navigatorTitle":[{"text":"NSTableViewDiffableDataSourceReference","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSTableViewDiffableDataSourceReference","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:viewFor:row:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSTableView","kind":"typeIdentifier","text":"NSTableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewFor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSTableColumn","kind":"typeIdentifier","text":"NSTableColumn"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"row"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)NSView","kind":"typeIdentifier","text":"NSView"},{"kind":"text","text":"?"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:viewFor:row:)","abstract":[{"text":"Asks the delegate for a view to display the specified row and column.","type":"text"}],"type":"topic","title":"tableView(_:viewFor:row:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"tableView:viewForTableColumn:row:"}],"url":"/documentation/appkit/nstableviewdelegate/tableview(_:viewfor:row:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"name":"macOS","beta":false,"deprecated":false,"unavailable":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Protocol"},{"op":"replace","path":"/metadata/title","value":"NSTableViewDelegate"},{"op":"replace","path":"/metadata/symbolKind","value":"protocol"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"NSTableViewDelegate"}]},{"op":"replace","path":"/metadata/navigatorTitle","value":[{"kind":"identifier","text":"NSTableViewDelegate"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]}},{"op":"replace","path":"/topicSections","value":[{"title":"Providing views for rows and columns","anchor":"Providing-views-for-rows-and-columns","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:viewFor:row:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:rowViewForRow:)"]},{"title":"Notification of row views being added or removed","anchor":"Notification-of-row-views-being-added-or-removed","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:didAdd:forRow:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:didRemove:forRow:)"]},{"title":"Grouping rows","anchor":"Grouping-rows","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:isGroupRow:)"]},{"title":"Providing cells for rows and columns","anchor":"Providing-cells-for-rows-and-columns","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:willDisplayCell:for:row:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:dataCellFor:row:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:shouldShowCellExpansionFor:row:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:toolTipFor:rect:tableColumn:row:mouseLocation:)"]},{"title":"Editing cells","anchor":"Editing-cells","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:shouldEdit:row:)"]},{"title":"Setting row and column size","anchor":"Setting-row-and-column-size","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:heightOfRow:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:sizeToFitWidthOfColumn:)"]},{"title":"Selecting rows","anchor":"Selecting-rows","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/selectionShouldChange(in:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:shouldSelectRow:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:selectionIndexesForProposedSelection:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:shouldSelect:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableViewSelectionIsChanging(_:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableViewSelectionDidChange(_:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:shouldTypeSelectFor:withCurrentSearch:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:typeSelectStringFor:row:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:nextTypeSelectMatchFromRow:toRow:for:)"]},{"title":"Moving and resizing columns","anchor":"Moving-and-resizing-columns","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:shouldReorderColumn:toColumn:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:didDrag:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableViewColumnDidMove(_:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableViewColumnDidResize(_:)"]},{"anchor":"Responding-to-mouse-events","title":"Responding to mouse events","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:didClick:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:mouseDownInHeaderOf:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:shouldTrackCell:for:row:)"]},{"anchor":"Enabling-table-row-actions","title":"Enabling table row actions","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:rowActionsForRow:edge:)"]},{"anchor":"Showing-and-hiding-columns","title":"Showing and hiding columns","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:userCanChangeVisibilityOf:)","doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate/tableView(_:userDidChangeVisibilityOf:)"]}]},{"op":"replace","path":"/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate"],"type":"inheritsFrom","kind":"relationships"}]},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Management","generated":true,"anchor":"Management","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource","doc://com.apple.appkit/documentation/AppKit/NSTableViewDiffableDataSourceReference"]}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSTableViewDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSControlTextEditingDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSControlTextEditingDelegate","identifier":"doc://com.apple.appkit/documentation/AppKit/NSControlTextEditingDelegate"},{"text":">","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"tableView:rowViewForRow:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:rowViewForRow:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:rowViewForRow:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:rowViewForRow:)/fragments"},{"op":"replace","value":"tableView:shouldSelectTableColumn:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:shouldSelect:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:shouldSelectTableColumn:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:shouldSelect:)/fragments"},{"op":"replace","value":"tableView:userDidChangeVisibilityOfTableColumns:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:userDidChangeVisibilityOf:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:userDidChangeVisibilityOfTableColumns:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:userDidChangeVisibilityOf:)/fragments"},{"op":"replace","value":"tableView:mouseDownInHeaderOfTableColumn:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:mouseDownInHeaderOf:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:mouseDownInHeaderOfTableColumn:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:mouseDownInHeaderOf:)/fragments"},{"op":"replace","value":"tableView:shouldTrackCell:forTableColumn:row:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:shouldTrackCell:for:row:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:shouldTrackCell:forTableColumn:row:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:shouldTrackCell:for:row:)/fragments"},{"op":"replace","value":"tableView:rowActionsForRow:edge:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:rowActionsForRow:edge:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:rowActionsForRow:edge:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:rowActionsForRow:edge:)/fragments"},{"op":"replace","value":"tableView:isGroupRow:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:isGroupRow:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:isGroupRow:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:isGroupRow:)/fragments"},{"op":"replace","value":"tableView:userCanChangeVisibilityOfTableColumn:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:userCanChangeVisibilityOf:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:userCanChangeVisibilityOfTableColumn:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:userCanChangeVisibilityOf:)/fragments"},{"op":"replace","value":"tableView:shouldEditTableColumn:row:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:shouldEdit:row:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:shouldEditTableColumn:row:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:shouldEdit:row:)/fragments"},{"op":"replace","value":"tableView:shouldShowCellExpansionForTableColumn:row:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:shouldShowCellExpansionFor:row:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:shouldShowCellExpansionForTableColumn:row:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:shouldShowCellExpansionFor:row:)/fragments"},{"op":"replace","value":"tableView:sizeToFitWidthOfColumn:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:sizeToFitWidthOfColumn:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:sizeToFitWidthOfColumn:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:sizeToFitWidthOfColumn:)/fragments"},{"op":"replace","value":"tableView:didRemoveRowView:forRow:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:didRemove:forRow:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:didRemoveRowView:forRow:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:didRemove:forRow:)/fragments"},{"op":"replace","value":"tableViewColumnDidMove:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableViewColumnDidMove(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableViewColumnDidMove:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableViewColumnDidMove(_:)/fragments"},{"op":"replace","value":"tableView:nextTypeSelectMatchFromRow:toRow:forString:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:nextTypeSelectMatchFromRow:toRow:for:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:nextTypeSelectMatchFromRow:toRow:forString:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:nextTypeSelectMatchFromRow:toRow:for:)/fragments"},{"op":"replace","value":"tableView:dataCellForTableColumn:row:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:dataCellFor:row:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:dataCellForTableColumn:row:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:dataCellFor:row:)/fragments"},{"op":"replace","value":"NSTableViewDelegate","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSTableViewDelegate"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSTableViewDelegate"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate/navigatorTitle"},{"op":"replace","value":"tableViewSelectionDidChange:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableViewSelectionDidChange(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableViewSelectionDidChange:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableViewSelectionDidChange(_:)/fragments"},{"op":"replace","value":"NSTableViewDataSource","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource/title"},{"op":"replace","value":[{"text":"NSTableViewDataSource","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSTableViewDataSource"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource/navigatorTitle"},{"op":"replace","value":"selectionShouldChangeInTableView:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1selectionShouldChange(in:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"selectionShouldChangeInTableView:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1selectionShouldChange(in:)/fragments"},{"op":"replace","value":"tableViewColumnDidResize:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableViewColumnDidResize(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableViewColumnDidResize:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableViewColumnDidResize(_:)/fragments"},{"op":"replace","value":"tableView:shouldSelectRow:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:shouldSelectRow:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:shouldSelectRow:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:shouldSelectRow:)/fragments"},{"op":"replace","value":"tableView:didDragTableColumn:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:didDrag:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:didDragTableColumn:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:didDrag:)/fragments"},{"op":"replace","value":"tableView:selectionIndexesForProposedSelection:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:selectionIndexesForProposedSelection:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:selectionIndexesForProposedSelection:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:selectionIndexesForProposedSelection:)/fragments"},{"op":"replace","value":"tableView:didClickTableColumn:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:didClick:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:didClickTableColumn:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:didClick:)/fragments"},{"op":"replace","value":"tableViewSelectionIsChanging:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableViewSelectionIsChanging(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableViewSelectionIsChanging:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableViewSelectionIsChanging(_:)/fragments"},{"op":"replace","value":"tableView:shouldTypeSelectForEvent:withCurrentSearchString:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:shouldTypeSelectFor:withCurrentSearch:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:shouldTypeSelectForEvent:withCurrentSearchString:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:shouldTypeSelectFor:withCurrentSearch:)/fragments"},{"op":"replace","value":"tableView:toolTipForCell:rect:tableColumn:row:mouseLocation:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:toolTipFor:rect:tableColumn:row:mouseLocation:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:toolTipForCell:rect:tableColumn:row:mouseLocation:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:toolTipFor:rect:tableColumn:row:mouseLocation:)/fragments"},{"op":"replace","value":"NSTableView","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/title"},{"op":"replace","value":[{"text":"NSTableView","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSTableView"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/navigatorTitle"},{"op":"replace","value":"NSControlTextEditingDelegate","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSControlTextEditingDelegate"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate/fragments"},{"op":"replace","value":[{"text":"NSControlTextEditingDelegate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTextEditingDelegate/navigatorTitle"},{"op":"replace","value":"NSControl","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl/title"},{"op":"replace","value":[{"text":"NSControl","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl/fragments"},{"op":"replace","value":[{"text":"NSControl","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl/navigatorTitle"},{"op":"replace","value":"tableView:heightOfRow:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:heightOfRow:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:heightOfRow:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:heightOfRow:)/fragments"},{"op":"replace","value":"tableView:shouldReorderColumn:toColumn:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:shouldReorderColumn:toColumn:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:shouldReorderColumn:toColumn:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:shouldReorderColumn:toColumn:)/fragments"},{"op":"replace","value":"tableView:typeSelectStringForTableColumn:row:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:typeSelectStringFor:row:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:typeSelectStringForTableColumn:row:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:typeSelectStringFor:row:)/fragments"},{"op":"replace","value":"tableView:willDisplayCell:forTableColumn:row:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:willDisplayCell:for:row:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:willDisplayCell:forTableColumn:row:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:willDisplayCell:for:row:)/fragments"},{"op":"replace","value":"tableView:didAddRowView:forRow:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:didAdd:forRow:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:didAddRowView:forRow:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:didAdd:forRow:)/fragments"},{"op":"replace","value":"NSObject","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title"},{"op":"replace","value":"NSTableViewDiffableDataSource","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDiffableDataSourceReference/title"},{"op":"replace","value":[{"text":"NSTableViewDiffableDataSource","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDiffableDataSourceReference/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSTableViewDiffableDataSource"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDiffableDataSourceReference/navigatorTitle"},{"op":"replace","value":"tableView:viewForTableColumn:row:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:viewFor:row:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:viewForTableColumn:row:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate~1tableView(_:viewFor:row:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}