{
  "abstract": [
    {
      "text": "The display characteristics and identifier for a column in a table view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTableColumn"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSTableColumn",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSTableColumn"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTableColumn"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSTableColumn"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTableColumn"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A table column object determines the width (including the maximum and minimum widths) of its column in the table view and specifies the column’s  resizing and editing behavior. A table column stores two cell objects: the header cell, which is used to draw the column header, and the data cell, which is used to draw the values for each row. In a cell-based table, you can control the display of the column by specifying subclasses of ",
              "type": "text"
            },
            {
              "code": "NSCell",
              "type": "codeVoice"
            },
            {
              "text": " to use and by setting the font and other display characteristics for these cells. For example, you can use an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to display string values or substitute an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageCell",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to display pictures.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage": {
      "abstract": [
        {
          "text": "A high-level interface for manipulating image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImage"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImage"
        }
      ],
      "role": "symbol",
      "title": "NSImage",
      "type": "topic",
      "url": "/documentation/appkit/nsimage"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageCell": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSImageCell",
          "type": "codeVoice"
        },
        {
          "text": " object displays a single image (encapsulated in an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object) in a frame. This class provides methods for choosing the frame and for aligning and scaling the image to fit the frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImageCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageCell"
        }
      ],
      "role": "symbol",
      "title": "NSImageCell",
      "type": "topic",
      "url": "/documentation/appkit/nsimagecell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableColumn": {
      "abstract": [
        {
          "text": "The display characteristics and identifier for a column in a table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableColumn"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableColumn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableColumn"
        }
      ],
      "role": "symbol",
      "title": "NSTableColumn",
      "type": "topic",
      "url": "/documentation/appkit/nstablecolumn"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/ResizingOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ResizingOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/ResizingOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ResizingOptions"
        }
      ],
      "role": "symbol",
      "title": "NSTableColumn.ResizingOptions",
      "type": "topic",
      "url": "/documentation/appkit/nstablecolumn/resizingoptions"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/dataCell": {
      "abstract": [
        {
          "text": "The cell prototype used by the table column to draw individual cells.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataCell"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/dataCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dataCell"
        }
      ],
      "role": "symbol",
      "title": "dataCell",
      "type": "topic",
      "url": "/documentation/appkit/nstablecolumn/datacell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/dataCell(forRow:)": {
      "abstract": [
        {
          "text": "Returns the cell object used to display values in the specified row of the table column.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataCell"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forRow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/dataCell(forRow:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dataCellForRow:"
        }
      ],
      "role": "symbol",
      "title": "dataCell(forRow:)",
      "type": "topic",
      "url": "/documentation/appkit/nstablecolumn/datacell(forrow:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/headerCell": {
      "abstract": [
        {
          "text": "The cell used to draw the table column’s header.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headerCell"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableHeaderCell",
          "text": "NSTableHeaderCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/headerCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "headerCell"
        }
      ],
      "role": "symbol",
      "title": "headerCell",
      "type": "topic",
      "url": "/documentation/appkit/nstablecolumn/headercell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/headerToolTip": {
      "abstract": [
        {
          "text": "The string that’s displayed in a help tag over the table column header.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headerToolTip"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/headerToolTip",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "headerToolTip"
        }
      ],
      "role": "symbol",
      "title": "headerToolTip",
      "type": "topic",
      "url": "/documentation/appkit/nstablecolumn/headertooltip"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/identifier": {
      "abstract": [
        {
          "text": "The identifier string for the table column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSUserInterfaceItemIdentifier",
          "text": "NSUserInterfaceItemIdentifier"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/appkit/nstablecolumn/identifier"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/init(coder:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/init(coder:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCoder:"
        }
      ],
      "role": "symbol",
      "title": "init(coder:)",
      "type": "topic",
      "url": "/documentation/appkit/nstablecolumn/init(coder:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/init(identifier:)": {
      "abstract": [
        {
          "text": "Initializes a newly created table column with a string identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSUserInterfaceItemIdentifier",
          "text": "NSUserInterfaceItemIdentifier"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/init(identifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "init(identifier:)",
      "type": "topic",
      "url": "/documentation/appkit/nstablecolumn/init(identifier:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/isEditable": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether a cell-based table’s column cells are user editable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEditable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/isEditable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "editable"
        }
      ],
      "role": "symbol",
      "title": "isEditable",
      "type": "topic",
      "url": "/documentation/appkit/nstablecolumn/iseditable"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/isHidden": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether the table column is hidden.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isHidden"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/isHidden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hidden"
        }
      ],
      "role": "symbol",
      "title": "isHidden",
      "type": "topic",
      "url": "/documentation/appkit/nstablecolumn/ishidden"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/isResizable": {
      "abstract": [
        {
          "text": "Returns whether the column is resizable.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "isResizable"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/isResizable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isResizable"
        }
      ],
      "role": "symbol",
      "title": "isResizable",
      "type": "topic",
      "url": "/documentation/appkit/nstablecolumn/isresizable"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/maxWidth": {
      "abstract": [
        {
          "text": "The table column’s maximum width, in points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/maxWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxWidth"
        }
      ],
      "role": "symbol",
      "title": "maxWidth",
      "type": "topic",
      "url": "/documentation/appkit/nstablecolumn/maxwidth"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/minWidth": {
      "abstract": [
        {
          "text": "The table column’s minimum width, in points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/minWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minWidth"
        }
      ],
      "role": "symbol",
      "title": "minWidth",
      "type": "topic",
      "url": "/documentation/appkit/nstablecolumn/minwidth"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/resizingMask": {
      "abstract": [
        {
          "text": "The table column’s resizing mask.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resizingMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableColumn",
          "text": "NSTableColumn"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTableColumnResizingOptions",
          "text": "ResizingOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/resizingMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resizingMask"
        }
      ],
      "role": "symbol",
      "title": "resizingMask",
      "type": "topic",
      "url": "/documentation/appkit/nstablecolumn/resizingmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/setResizable:": {
      "abstract": [
        {
          "text": "Sets whether the user can resize the receiver in its NSTableView.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setResizable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/setResizable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setResizable:"
        }
      ],
      "role": "symbol",
      "title": "setResizable:",
      "type": "topic",
      "url": "/documentation/appkit/nstablecolumn/setresizable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/sizeToFit()": {
      "abstract": [
        {
          "text": "Resizes the table column to fit the width of its header cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sizeToFit"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/sizeToFit()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sizeToFit"
        }
      ],
      "role": "symbol",
      "title": "sizeToFit()",
      "type": "topic",
      "url": "/documentation/appkit/nstablecolumn/sizetofit()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/sortDescriptorPrototype": {
      "abstract": [
        {
          "text": "The table column’s sort descriptor prototype.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sortDescriptorPrototype"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSortDescriptor",
          "text": "NSSortDescriptor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/sortDescriptorPrototype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sortDescriptorPrototype"
        }
      ],
      "role": "symbol",
      "title": "sortDescriptorPrototype",
      "type": "topic",
      "url": "/documentation/appkit/nstablecolumn/sortdescriptorprototype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/tableView": {
      "abstract": [
        {
          "text": "The table view that contains the table column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tableView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableView",
          "text": "NSTableView"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/tableView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tableView"
        }
      ],
      "role": "symbol",
      "title": "tableView",
      "type": "topic",
      "url": "/documentation/appkit/nstablecolumn/tableview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/title": {
      "abstract": [
        {
          "text": "The title of the table column’s header.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/appkit/nstablecolumn/title"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/width": {
      "abstract": [
        {
          "text": "The table column’s width, in points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "width"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/width",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "width"
        }
      ],
      "role": "symbol",
      "title": "width",
      "type": "topic",
      "url": "/documentation/appkit/nstablecolumn/width"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableHeaderCell": {
      "abstract": [
        {
          "text": "An object that a table header view uses to draw the content of the column headers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableHeaderCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableHeaderCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableHeaderCell"
        }
      ],
      "role": "symbol",
      "title": "NSTableHeaderCell",
      "type": "topic",
      "url": "/documentation/appkit/nstableheadercell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableHeaderView": {
      "abstract": [
        {
          "text": "An object that draws headers over a table view’s columns and handles mouse events in those headers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableHeaderView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableHeaderView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableHeaderView"
        }
      ],
      "role": "symbol",
      "title": "NSTableHeaderView",
      "type": "topic",
      "url": "/documentation/appkit/nstableheaderview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableRowView": {
      "abstract": [
        {
          "text": "The view shown for a row in a table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableRowView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableRowView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableRowView"
        }
      ],
      "role": "symbol",
      "title": "NSTableRowView",
      "type": "topic",
      "url": "/documentation/appkit/nstablerowview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction": {
      "abstract": [
        {
          "text": "A single action to present when the user swipes horizontally on a table row.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableViewRowAction"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewRowAction"
        }
      ],
      "role": "symbol",
      "title": "NSTableViewRowAction",
      "type": "topic",
      "url": "/documentation/appkit/nstableviewrowaction"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell": {
      "abstract": [
        {
          "text": "An object that enhances the text display capabilities of a cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextFieldCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextFieldCell"
        }
      ],
      "role": "symbol",
      "title": "NSTextFieldCell",
      "type": "topic",
      "url": "/documentation/appkit/nstextfieldcell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification": {
      "abstract": [
        {
          "text": "A set of methods used to associate a unique identifier with objects in your user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserInterfaceItemIdentification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUserInterfaceItemIdentification"
        }
      ],
      "role": "symbol",
      "title": "NSUserInterfaceItemIdentification",
      "type": "topic",
      "url": "/documentation/appkit/nsuserinterfaceitemidentification"
    },
    "doc://com.apple.appkit/documentation/AppKit/resizing-modes": {
      "abstract": [
        {
          "text": "These constants specify the resizing modes for a table column. The values are used to set the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/resizingMask",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/resizing-modes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Resizing Modes",
      "type": "topic",
      "url": "/documentation/appkit/resizing-modes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Rows-and-Columns",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableHeaderView",
        "doc://com.apple.appkit/documentation/AppKit/NSTableHeaderCell",
        "doc://com.apple.appkit/documentation/AppKit/NSTableRowView",
        "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction",
        "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/ResizingOptions"
      ],
      "title": "Rows and Columns"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Table-Column",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/init(identifier:)"
      ],
      "title": "Creating a Table Column"
    },
    {
      "anchor": "Setting-the-Table-View",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/tableView"
      ],
      "title": "Setting the Table View"
    },
    {
      "anchor": "Controlling-Size",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/width",
        "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/minWidth",
        "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/maxWidth",
        "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/resizingMask",
        "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/sizeToFit()"
      ],
      "title": "Controlling Size"
    },
    {
      "anchor": "Setting-the-Header",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/title",
        "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/headerCell"
      ],
      "title": "Setting the Header"
    },
    {
      "anchor": "Setting-the-Identifier",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/identifier"
      ],
      "title": "Setting the Identifier"
    },
    {
      "anchor": "Controlling-Editability-in-a-Cell-Based-Table",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/isEditable"
      ],
      "title": "Controlling Editability in a Cell-Based Table"
    },
    {
      "anchor": "Sorting",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/sortDescriptorPrototype"
      ],
      "title": "Sorting"
    },
    {
      "anchor": "Setting-Column-Visibility",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/isHidden"
      ],
      "title": "Setting Column Visibility"
    },
    {
      "anchor": "Setting-Tooltips",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/headerToolTip"
      ],
      "title": "Setting Tooltips"
    },
    {
      "anchor": "Deprecated-Methods",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/dataCell",
        "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/dataCell(forRow:)"
      ],
      "title": "Deprecated Methods"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/resizing-modes"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/init(coder:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Structures",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/ResizingOptions"
      ],
      "title": "Structures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTableColumn"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableColumn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableColumn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Table-Column",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/init(identifier:)"
              ],
              "title": "Creating a Table Column"
            },
            {
              "anchor": "Setting-the-Table-View",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/tableView"
              ],
              "title": "Setting the Table View"
            },
            {
              "anchor": "Controlling-Size",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/width",
                "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/minWidth",
                "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/maxWidth",
                "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/resizingMask",
                "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/sizeToFit()"
              ],
              "title": "Controlling Size"
            },
            {
              "anchor": "Setting-the-Header",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/title",
                "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/headerCell"
              ],
              "title": "Setting the Header"
            },
            {
              "anchor": "Setting-the-Identifier",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/identifier"
              ],
              "title": "Setting the Identifier"
            },
            {
              "anchor": "Controlling-Editability-in-a-Cell-Based-Table",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/isEditable"
              ],
              "title": "Controlling Editability in a Cell-Based Table"
            },
            {
              "anchor": "Sorting",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/sortDescriptorPrototype"
              ],
              "title": "Sorting"
            },
            {
              "anchor": "Setting-Column-Visibility",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/isHidden"
              ],
              "title": "Setting Column Visibility"
            },
            {
              "anchor": "Setting-Tooltips",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/headerToolTip"
              ],
              "title": "Setting Tooltips"
            },
            {
              "anchor": "Deprecated-Methods",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/isResizable",
                "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/setResizable:",
                "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/dataCell",
                "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/dataCell(forRow:)"
              ],
              "title": "Deprecated Methods"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/resizing-modes"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Initializers",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/init(coder:)"
              ],
              "title": "Initializers"
            },
            {
              "anchor": "Structures",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/ResizingOptions"
              ],
              "title": "Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
                "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Rows-and-Columns",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTableHeaderView",
                "doc://com.apple.appkit/documentation/AppKit/NSTableHeaderCell",
                "doc://com.apple.appkit/documentation/AppKit/NSTableRowView",
                "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction",
                "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/ResizingOptions"
              ],
              "title": "Rows and Columns"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSTableColumn"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1init(identifier:)/title",
          "value": "initWithIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1init(identifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1minWidth/title",
          "value": "minWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1minWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1init(coder:)/title",
          "value": "initWithCoder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1init(coder:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCoder:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell/title",
          "value": "NSTextFieldCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFieldCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFieldCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1isEditable/title",
          "value": "editable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1isEditable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "editable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1sortDescriptorPrototype/title",
          "value": "sortDescriptorPrototype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1sortDescriptorPrototype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sortDescriptorPrototype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewRowAction/title",
          "value": "NSTableViewRowAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewRowAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewRowAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewRowAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewRowAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1title/title",
          "value": "title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/title",
          "value": "NSImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/title",
          "value": "NSUserInterfaceItemIdentification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceItemIdentification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceItemIdentification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableHeaderCell/title",
          "value": "NSTableHeaderCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableHeaderCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableHeaderCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableHeaderCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableHeaderCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1width/title",
          "value": "width"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1width/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "width"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1dataCell/title",
          "value": "dataCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1dataCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dataCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn/title",
          "value": "NSTableColumn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableColumn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableColumn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1isHidden/title",
          "value": "hidden"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1isHidden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hidden"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1tableView/title",
          "value": "tableView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1tableView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1sizeToFit()/title",
          "value": "sizeToFit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1sizeToFit()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sizeToFit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageCell/title",
          "value": "NSImageCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1headerToolTip/title",
          "value": "headerToolTip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1headerToolTip/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "headerToolTip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1headerCell/title",
          "value": "headerCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1headerCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "headerCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1dataCell(forRow:)/title",
          "value": "dataCellForRow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1dataCell(forRow:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dataCellForRow:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1resizingMask/title",
          "value": "resizingMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1resizingMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resizingMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableHeaderView/title",
          "value": "NSTableHeaderView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableHeaderView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableHeaderView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableHeaderView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableHeaderView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableRowView/title",
          "value": "NSTableRowView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableRowView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableRowView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableRowView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableRowView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1maxWidth/title",
          "value": "maxWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1maxWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1ResizingOptions/title",
          "value": "NSTableColumnResizingOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1ResizingOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableColumnResizingOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1ResizingOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableColumnResizingOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstablecolumn"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstablecolumn"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
