{
  "abstract": [
    {
      "text": "A set of methods implemented by objects that support searching using the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinder",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " class and the in-window text find bar.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSTextFinderClient",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSTextFinderClient"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextFinderClient"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NSTextFinderClient"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTextFinderClient"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinder",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for details.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinder": {
      "abstract": [
        {
          "text": "An optional search-and-replace find interface inside a view, usually a scroll view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextFinder"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextFinder"
        }
      ],
      "role": "symbol",
      "title": "NSTextFinder",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinder"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinderBarContainer": {
      "abstract": [
        {
          "text": "A protocol that provides a container in which the find bar is displayed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextFinderBarContainer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinderBarContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextFinderBarContainer"
        }
      ],
      "role": "symbol",
      "title": "NSTextFinderBarContainer",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinderbarcontainer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient": {
      "abstract": [
        {
          "text": "A set of methods implemented by objects that support searching using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinder",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class and the in-window text find bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextFinderClient"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextFinderClient"
        }
      ],
      "role": "symbol",
      "title": "NSTextFinderClient",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinderclient"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/allowsMultipleSelection": {
      "abstract": [
        {
          "text": "Returns whether multiple items can be selected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsMultipleSelection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/allowsMultipleSelection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsMultipleSelection"
        }
      ],
      "role": "symbol",
      "title": "allowsMultipleSelection",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinderclient/allowsmultipleselection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/contentView(at:effectiveCharacterRange:)": {
      "abstract": [
        {
          "text": "Returns the view the context is displayed in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "effectiveCharacterRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRangePointer",
          "text": "NSRangePointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/contentView(at:effectiveCharacterRange:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentViewAtIndex:effectiveCharacterRange:"
        }
      ],
      "role": "symbol",
      "title": "contentView(at:effectiveCharacterRange:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinderclient/contentview(at:effectivecharacterrange:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/didReplaceCharacters()": {
      "abstract": [
        {
          "text": "Specifies whether text characters were replaced.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didReplaceCharacters"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/didReplaceCharacters()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "didReplaceCharacters"
        }
      ],
      "role": "symbol",
      "title": "didReplaceCharacters()",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinderclient/didreplacecharacters()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/drawCharacters(in:forContentView:)": {
      "abstract": [
        {
          "text": "Draw the glyphs for the requested character range as they are drawn in the given content view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawCharacters"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "forContentView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/drawCharacters(in:forContentView:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawCharactersInRange:forContentView:"
        }
      ],
      "role": "symbol",
      "title": "drawCharacters(in:forContentView:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinderclient/drawcharacters(in:forcontentview:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/firstSelectedRange": {
      "abstract": [
        {
          "text": "Returns the currently selected range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "firstSelectedRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/firstSelectedRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "firstSelectedRange"
        }
      ],
      "role": "symbol",
      "title": "firstSelectedRange",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinderclient/firstselectedrange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/isEditable": {
      "abstract": [
        {
          "text": "Returns whether the text is editable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEditable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/isEditable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "editable"
        }
      ],
      "role": "symbol",
      "title": "isEditable",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinderclient/iseditable"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/isSelectable": {
      "abstract": [
        {
          "text": "Returns whether the text is selectable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSelectable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/isSelectable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectable"
        }
      ],
      "role": "symbol",
      "title": "isSelectable",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinderclient/isselectable"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/rects(forCharacterRange:)": {
      "abstract": [
        {
          "text": "An array containing the located text in the content view’s coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rects"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forCharacterRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSValue",
          "text": "NSValue"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/rects(forCharacterRange:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rectsForCharacterRange:"
        }
      ],
      "role": "symbol",
      "title": "rects(forCharacterRange:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinderclient/rects(forcharacterrange:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/replaceCharacters(in:with:)": {
      "abstract": [
        {
          "text": "Replaces the text in the specified range with the new string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "replaceCharacters"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/replaceCharacters(in:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "replaceCharactersInRange:withString:"
        }
      ],
      "role": "symbol",
      "title": "replaceCharacters(in:with:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinderclient/replacecharacters(in:with:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/scrollRangeToVisible(_:)": {
      "abstract": [
        {
          "text": "Scrolls the specified range such that it is visible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollRangeToVisible"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/scrollRangeToVisible(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollRangeToVisible:"
        }
      ],
      "role": "symbol",
      "title": "scrollRangeToVisible(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinderclient/scrollrangetovisible(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/selectedRanges": {
      "abstract": [
        {
          "text": "Returns an array of selected ranges.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectedRanges"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSValue",
          "text": "NSValue"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/selectedRanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectedRanges"
        }
      ],
      "role": "symbol",
      "title": "selectedRanges",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinderclient/selectedranges"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/shouldReplaceCharacters(inRanges:with:)": {
      "abstract": [
        {
          "text": "Returns whether the specified strings should be replaced.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldReplaceCharacters"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "inRanges"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSValue",
          "text": "NSValue"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/shouldReplaceCharacters(inRanges:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldReplaceCharactersInRanges:withStrings:"
        }
      ],
      "role": "symbol",
      "title": "shouldReplaceCharacters(inRanges:with:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinderclient/shouldreplacecharacters(inranges:with:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/string": {
      "abstract": [
        {
          "text": "Allows the client to specify a single string for searching.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "string"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/string",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "string"
        }
      ],
      "role": "symbol",
      "title": "string",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinderclient/string"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/string(at:effectiveRange:endsWithSearchBoundary:)": {
      "abstract": [
        {
          "text": "Returns the found string that is created by conceptually mapping its content to a single string, which is composed of a concatenation of all its substrings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "string"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "effectiveRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRangePointer",
          "text": "NSRangePointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endsWithSearchBoundary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8ObjCBoolV",
          "text": "ObjCBool"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/string(at:effectiveRange:endsWithSearchBoundary:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stringAtIndex:effectiveRange:endsWithSearchBoundary:"
        }
      ],
      "role": "symbol",
      "title": "string(at:effectiveRange:endsWithSearchBoundary:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinderclient/string(at:effectiverange:endswithsearchboundary:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/stringLength()": {
      "abstract": [
        {
          "text": "Returns the full length of the conceptually concatenated string return by the ",
          "type": "text"
        },
        {
          "code": "stringAtIndex:effectiveRange:endsWithSearchBoundary:",
          "type": "codeVoice"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stringLength"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/stringLength()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stringLength"
        }
      ],
      "role": "symbol",
      "title": "stringLength()",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinderclient/stringlength()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/visibleCharacterRanges": {
      "abstract": [
        {
          "text": "An array of visible character ranges.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visibleCharacterRanges"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSValue",
          "text": "NSValue"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/visibleCharacterRanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "visibleCharacterRanges"
        }
      ],
      "role": "symbol",
      "title": "visibleCharacterRanges",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinderclient/visiblecharacterranges"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Search-and-Replace",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinder",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinderBarContainer"
      ],
      "title": "Search and Replace"
    }
  ],
  "topicSections": [
    {
      "anchor": "String-Searching",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/string",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/string(at:effectiveRange:endsWithSearchBoundary:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/stringLength()"
      ],
      "title": "String Searching"
    },
    {
      "anchor": "Replacing-Text",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/shouldReplaceCharacters(inRanges:with:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/replaceCharacters(in:with:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/didReplaceCharacters()"
      ],
      "title": "Replacing Text"
    },
    {
      "anchor": "Selection-Information",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/isSelectable",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/allowsMultipleSelection",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/firstSelectedRange",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/selectedRanges"
      ],
      "title": "Selection Information"
    },
    {
      "anchor": "Text-Edibility",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/isEditable"
      ],
      "title": "Text Edibility"
    },
    {
      "anchor": "Determining-and-Displaying-Text-Locations",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/contentView(at:effectiveCharacterRange:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/rects(forCharacterRange:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/scrollRangeToVisible(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/visibleCharacterRanges"
      ],
      "title": "Determining and Displaying Text Locations"
    },
    {
      "anchor": "Drawing-Glyphs",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/drawCharacters(in:forContentView:)"
      ],
      "title": "Drawing Glyphs"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTextFinderClient"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFinderClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFinderClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "String-Searching",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/string",
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/string(at:effectiveRange:endsWithSearchBoundary:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/stringLength()"
              ],
              "title": "String Searching"
            },
            {
              "anchor": "Replacing-Text",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/shouldReplaceCharacters(inRanges:with:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/replaceCharacters(in:with:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/didReplaceCharacters()"
              ],
              "title": "Replacing Text"
            },
            {
              "anchor": "Selection-Information",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/isSelectable",
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/allowsMultipleSelection",
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/firstSelectedRange",
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/selectedRanges"
              ],
              "title": "Selection Information"
            },
            {
              "anchor": "Text-Edibility",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/isEditable"
              ],
              "title": "Text Edibility"
            },
            {
              "anchor": "Determining-and-Displaying-Text-Locations",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/contentView(at:effectiveCharacterRange:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/rects(forCharacterRange:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/scrollRangeToVisible(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/visibleCharacterRanges"
              ],
              "title": "Determining and Displaying Text Locations"
            },
            {
              "anchor": "Drawing-Glyphs",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinderClient/drawCharacters(in:forContentView:)"
              ],
              "title": "Drawing Glyphs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Search-and-Replace",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinder",
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinderBarContainer"
              ],
              "title": "Search and Replace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSTextFinderClient"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1allowsMultipleSelection/title",
          "value": "allowsMultipleSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1allowsMultipleSelection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsMultipleSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1replaceCharacters(in:with:)/title",
          "value": "replaceCharactersInRange:withString:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1replaceCharacters(in:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "replaceCharactersInRange:withString:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1contentView(at:effectiveCharacterRange:)/title",
          "value": "contentViewAtIndex:effectiveCharacterRange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1contentView(at:effectiveCharacterRange:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "contentViewAtIndex:effectiveCharacterRange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1firstSelectedRange/title",
          "value": "firstSelectedRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1firstSelectedRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "firstSelectedRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient/title",
          "value": "NSTextFinderClient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFinderClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFinderClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1visibleCharacterRanges/title",
          "value": "visibleCharacterRanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1visibleCharacterRanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "visibleCharacterRanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1rects(forCharacterRange:)/title",
          "value": "rectsForCharacterRange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1rects(forCharacterRange:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rectsForCharacterRange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1shouldReplaceCharacters(inRanges:with:)/title",
          "value": "shouldReplaceCharactersInRanges:withStrings:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1shouldReplaceCharacters(inRanges:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "shouldReplaceCharactersInRanges:withStrings:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1didReplaceCharacters()/title",
          "value": "didReplaceCharacters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1didReplaceCharacters()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "didReplaceCharacters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder/title",
          "value": "NSTextFinder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFinder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFinder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1drawCharacters(in:forContentView:)/title",
          "value": "drawCharactersInRange:forContentView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1drawCharacters(in:forContentView:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawCharactersInRange:forContentView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderBarContainer/title",
          "value": "NSTextFinderBarContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderBarContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFinderBarContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderBarContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFinderBarContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1string(at:effectiveRange:endsWithSearchBoundary:)/title",
          "value": "stringAtIndex:effectiveRange:endsWithSearchBoundary:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1string(at:effectiveRange:endsWithSearchBoundary:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stringAtIndex:effectiveRange:endsWithSearchBoundary:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1isSelectable/title",
          "value": "selectable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1isSelectable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1stringLength()/title",
          "value": "stringLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1stringLength()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stringLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1isEditable/title",
          "value": "editable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1isEditable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "editable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1string/title",
          "value": "string"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1string/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "string"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1scrollRangeToVisible(_:)/title",
          "value": "scrollRangeToVisible:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1scrollRangeToVisible(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scrollRangeToVisible:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1selectedRanges/title",
          "value": "selectedRanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinderClient~1selectedRanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectedRanges"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstextfinderclient"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstextfinderclient"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
