{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextFieldDatePickerStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSTextFieldDatePickerStyle",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSTextFieldDatePickerStyle"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextFieldDatePickerStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSTextFieldDatePickerStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/Style",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSDatePickerStyle",
              "text": "NSDatePickerStyle"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTextFieldDatePickerStyle"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Provide a text field interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSClockAndCalendarDatePickerStyle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSClockAndCalendarDatePickerStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSClockAndCalendarDatePickerStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSClockAndCalendarDatePickerStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsclockandcalendardatepickerstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/Style": {
      "abstract": [
        {
          "text": "Constants that define the visual appearance of the date picker cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Style"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/Style",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Style"
        }
      ],
      "role": "symbol",
      "title": "NSDatePicker.Style",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker/style"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFieldAndStepperDatePickerStyle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextFieldAndStepperDatePickerStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFieldAndStepperDatePickerStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextFieldAndStepperDatePickerStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstextfieldandstepperdatepickerstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFieldDatePickerStyle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextFieldDatePickerStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFieldDatePickerStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextFieldDatePickerStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstextfielddatepickerstyle"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextFieldAndStepperDatePickerStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSClockAndCalendarDatePickerStyle"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1Style/title",
          "value": "NSDatePickerStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1Style/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePickerStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1Style/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePickerStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstextfielddatepickerstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
