{
  "abstract": [
    {
      "text": "An object that enhances the text display capabilities of a cell.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSTextFieldCell",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSTextFieldCell"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextFieldCell"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSTextFieldCell"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTextFieldCell"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class adds to the text display capabilities of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class by allowing you to set the color of both the text and its background. You can also specify whether the cell draws its background at all.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "All of the methods declared by this class are also declared by the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextField",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class, which uses ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects to draw and edit text. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextField",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " cover methods call the corresponding ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " methods.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Placeholder strings, set using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/placeholderString",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/placeholderAttributedString",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property, appear in the text field cell if the actual string is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " or an empty string. They’re drawn in gray on the cell and aren’t archived in the “pre-10.2” nib format.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Designated-Initializers",
          "level": 3,
          "text": "Designated Initializers",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When subclassing ",
              "type": "text"
            },
            {
              "code": "NSTextFieldCell",
              "type": "codeVoice"
            },
            {
              "text": " you must implement the designated initializers ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/OSLog/OSLogEntry/init(coder:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/init(textCell:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol": {
      "abstract": [
        {
          "text": "A role-based protocol that declares the minimum interface necessary to interact with an assistive app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityElementProtocol"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityElementProtocol"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityElementProtocol",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityelementprotocol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol": {
      "abstract": [
        {
          "text": "The complete list of properties and methods for accessible elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityProtocol",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityprotocol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSActionCell": {
      "abstract": [
        {
          "text": "An active area inside a control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSActionCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSActionCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSActionCell"
        }
      ],
      "role": "symbol",
      "title": "NSActionCell",
      "type": "topic",
      "url": "/documentation/appkit/nsactioncell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell": {
      "abstract": [
        {
          "text": "A mechanism for displaying text or images in a view object without the overhead of a full ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " subclass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCell"
        }
      ],
      "role": "symbol",
      "title": "NSCell",
      "type": "topic",
      "url": "/documentation/appkit/nscell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell/init(textCell:)": {
      "abstract": [
        {
          "text": "Returns an NSCell object initialized with the specified string and set to have the cell’s default menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "textCell"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/init(textCell:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initTextCell:"
        }
      ],
      "role": "symbol",
      "title": "init(textCell:)",
      "type": "topic",
      "url": "/documentation/appkit/nscell/init(textcell:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSComboBoxCell": {
      "abstract": [
        {
          "text": "The user interface of a combo box.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSComboBoxCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSComboBoxCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSComboBoxCell"
        }
      ],
      "role": "symbol",
      "title": "NSComboBoxCell",
      "type": "topic",
      "url": "/documentation/appkit/nscomboboxcell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPathComponentCell": {
      "abstract": [
        {
          "text": "A component of a path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPathComponentCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPathComponentCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPathComponentCell"
        }
      ],
      "role": "symbol",
      "title": "NSPathComponentCell",
      "type": "topic",
      "url": "/documentation/appkit/nspathcomponentcell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchFieldCell": {
      "abstract": [
        {
          "text": "The programmatic interface for text fields that are used for text-based searches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSearchFieldCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchFieldCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSearchFieldCell"
        }
      ],
      "role": "symbol",
      "title": "NSSearchFieldCell",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfieldcell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSecureTextFieldCell": {
      "abstract": [
        {
          "text": "A text field whose value is hidden from the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSecureTextFieldCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSecureTextFieldCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSecureTextFieldCell"
        }
      ],
      "role": "symbol",
      "title": "NSSecureTextFieldCell",
      "type": "topic",
      "url": "/documentation/appkit/nssecuretextfieldcell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableHeaderCell": {
      "abstract": [
        {
          "text": "An object that a table header view uses to draw the content of the column headers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableHeaderCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableHeaderCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableHeaderCell"
        }
      ],
      "role": "symbol",
      "title": "NSTableHeaderCell",
      "type": "topic",
      "url": "/documentation/appkit/nstableheadercell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextField": {
      "abstract": [
        {
          "text": "Text the user can select or edit to send an action message to a target when the user presses the Return key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextField"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextField"
        }
      ],
      "role": "symbol",
      "title": "NSTextField",
      "type": "topic",
      "url": "/documentation/appkit/nstextfield"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextField/BezelStyle-swift.enum": {
      "abstract": [
        {
          "text": "The style of bezel the text field displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextField/BezelStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BezelStyle"
        }
      ],
      "role": "symbol",
      "title": "NSTextField.BezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstextfield/bezelstyle-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell": {
      "abstract": [
        {
          "text": "An object that enhances the text display capabilities of a cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextFieldCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextFieldCell"
        }
      ],
      "role": "symbol",
      "title": "NSTextFieldCell",
      "type": "topic",
      "url": "/documentation/appkit/nstextfieldcell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/allowedInputSourceLocales": {
      "abstract": [
        {
          "text": "An array of locale identifiers that represent the allowed input sources when the text field has the keyboard focus.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowedInputSourceLocales"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/allowedInputSourceLocales",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowedInputSourceLocales"
        }
      ],
      "role": "symbol",
      "title": "allowedInputSourceLocales",
      "type": "topic",
      "url": "/documentation/appkit/nstextfieldcell/allowedinputsourcelocales"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/backgroundColor": {
      "abstract": [
        {
          "text": "The color of the cell’s background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/backgroundColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backgroundColor"
        }
      ],
      "role": "symbol",
      "title": "backgroundColor",
      "type": "topic",
      "url": "/documentation/appkit/nstextfieldcell/backgroundcolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/bezelStyle": {
      "abstract": [
        {
          "text": "The bezel style to use when drawing the text field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bezelStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextField",
          "text": "NSTextField"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextFieldBezelStyle",
          "text": "BezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/bezelStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bezelStyle"
        }
      ],
      "role": "symbol",
      "title": "bezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstextfieldcell/bezelstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/drawsBackground": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the cell draws its background color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawsBackground"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/drawsBackground",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawsBackground"
        }
      ],
      "role": "symbol",
      "title": "drawsBackground",
      "type": "topic",
      "url": "/documentation/appkit/nstextfieldcell/drawsbackground"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/init(coder:)": {
      "abstract": [
        {
          "text": "Initializes a text field cell from data in the provided unarchiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/init(coder:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCoder:"
        }
      ],
      "role": "symbol",
      "title": "init(coder:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextfieldcell/init(coder:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/init(textCell:)": {
      "abstract": [
        {
          "text": "Initializes a text field cell that displays the specified string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "textCell"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/init(textCell:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initTextCell:"
        }
      ],
      "role": "symbol",
      "title": "init(textCell:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextfieldcell/init(textcell:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/placeholderAttributedString": {
      "abstract": [
        {
          "text": "The placeholder text for the cell, specified as an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "placeholderAttributedString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/placeholderAttributedString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "placeholderAttributedString"
        }
      ],
      "role": "symbol",
      "title": "placeholderAttributedString",
      "type": "topic",
      "url": "/documentation/appkit/nstextfieldcell/placeholderattributedstring"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/placeholderString": {
      "abstract": [
        {
          "text": "The placeholder text for the cell, specified as a plain text string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "placeholderString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/placeholderString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "placeholderString"
        }
      ],
      "role": "symbol",
      "title": "placeholderString",
      "type": "topic",
      "url": "/documentation/appkit/nstextfieldcell/placeholderstring"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/setUpFieldEditorAttributes(_:)": {
      "abstract": [
        {
          "text": "Allows the cell to set up the field editor’s attributes before editing begins.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setUpFieldEditorAttributes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSText",
          "text": "NSText"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSText",
          "text": "NSText"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/setUpFieldEditorAttributes(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setUpFieldEditorAttributes:"
        }
      ],
      "role": "symbol",
      "title": "setUpFieldEditorAttributes(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextfieldcell/setupfieldeditorattributes(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/setWantsNotificationForMarkedText(_:)": {
      "abstract": [
        {
          "text": "Directs the cell’s associated field editor to post text change notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setWantsNotificationForMarkedText"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/setWantsNotificationForMarkedText(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setWantsNotificationForMarkedText:"
        }
      ],
      "role": "symbol",
      "title": "setWantsNotificationForMarkedText(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextfieldcell/setwantsnotificationformarkedtext(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/textColor": {
      "abstract": [
        {
          "text": "The color to use to draw the cell’s text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/textColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textColor"
        }
      ],
      "role": "symbol",
      "title": "textColor",
      "type": "topic",
      "url": "/documentation/appkit/nstextfieldcell/textcolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCell": {
      "abstract": [
        {
          "text": "A text field cell subclass that enables tokenized editing of an array of objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTokenFieldCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTokenFieldCell"
        }
      ],
      "role": "symbol",
      "title": "NSTokenFieldCell",
      "type": "topic",
      "url": "/documentation/appkit/nstokenfieldcell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification": {
      "abstract": [
        {
          "text": "A set of methods used to associate a unique identifier with objects in your user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserInterfaceItemIdentification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUserInterfaceItemIdentification"
        }
      ],
      "role": "symbol",
      "title": "NSUserInterfaceItemIdentification",
      "type": "topic",
      "url": "/documentation/appkit/nsuserinterfaceitemidentification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/appkit/nsview"
    },
    "doc://com.apple.documentation/documentation/OSLog/OSLogEntry/init(coder:)": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/OSLog/OSLogEntry/init(coder:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(coder:)",
      "type": "topic",
      "url": "/documentation/OSLog/OSLogEntry/init(coder:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSActionCell"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSComboBoxCell",
        "doc://com.apple.appkit/documentation/AppKit/NSPathComponentCell",
        "doc://com.apple.appkit/documentation/AppKit/NSSearchFieldCell",
        "doc://com.apple.appkit/documentation/AppKit/NSSecureTextFieldCell",
        "doc://com.apple.appkit/documentation/AppKit/NSTableHeaderCell",
        "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCell"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityElementProtocol",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemIdentification",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Cell",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSecureTextFieldCell"
      ],
      "title": "Cell"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Text-Field-Cell",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/init(textCell:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/init(coder:)"
      ],
      "title": "Creating a Text Field Cell"
    },
    {
      "anchor": "Setting-the-Text-Color",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/textColor"
      ],
      "title": "Setting the Text Color"
    },
    {
      "anchor": "Setting-the-Bezel-Style",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/bezelStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSTextField/BezelStyle-swift.enum"
      ],
      "title": "Setting the Bezel Style"
    },
    {
      "anchor": "Controlling-the-Background",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/backgroundColor",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/drawsBackground"
      ],
      "title": "Controlling the Background"
    },
    {
      "anchor": "Managing-the-Field-Editor",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/setUpFieldEditorAttributes(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/setWantsNotificationForMarkedText(_:)"
      ],
      "title": "Managing the Field Editor"
    },
    {
      "anchor": "Managing-Placeholder-Strings",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/placeholderString",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/placeholderAttributedString"
      ],
      "title": "Managing Placeholder Strings"
    },
    {
      "anchor": "Accessing-Input-Source-Locales",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/allowedInputSourceLocales"
      ],
      "title": "Accessing Input Source Locales"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTextFieldCell"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFieldCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFieldCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Text-Field-Cell",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/init(textCell:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/init(coder:)"
              ],
              "title": "Creating a Text Field Cell"
            },
            {
              "anchor": "Setting-the-Text-Color",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/textColor"
              ],
              "title": "Setting the Text Color"
            },
            {
              "anchor": "Setting-the-Bezel-Style",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/bezelStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSTextField/BezelStyle-swift.enum"
              ],
              "title": "Setting the Bezel Style"
            },
            {
              "anchor": "Controlling-the-Background",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/backgroundColor",
                "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/drawsBackground"
              ],
              "title": "Controlling the Background"
            },
            {
              "anchor": "Managing-the-Field-Editor",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/setUpFieldEditorAttributes(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/setWantsNotificationForMarkedText(_:)"
              ],
              "title": "Managing the Field Editor"
            },
            {
              "anchor": "Managing-Placeholder-Strings",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/placeholderString",
                "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/placeholderAttributedString"
              ],
              "title": "Managing Placeholder Strings"
            },
            {
              "anchor": "Accessing-Input-Source-Locales",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextFieldCell/allowedInputSourceLocales"
              ],
              "title": "Accessing Input Source Locales"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSActionCell"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSComboBoxCell",
                "doc://com.apple.appkit/documentation/AppKit/NSPathComponentCell",
                "doc://com.apple.appkit/documentation/AppKit/NSSearchFieldCell",
                "doc://com.apple.appkit/documentation/AppKit/NSSecureTextFieldCell",
                "doc://com.apple.appkit/documentation/AppKit/NSTableHeaderCell",
                "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCell"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Cell",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSecureTextFieldCell"
              ],
              "title": "Cell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSTextFieldCell"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSActionCell",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSActionCell",
                    "text": "NSActionCell"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/title",
          "value": "NSCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell~1placeholderString/title",
          "value": "placeholderString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell~1placeholderString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "placeholderString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell~1bezelStyle/title",
          "value": "bezelStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell~1bezelStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bezelStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField~1BezelStyle-swift.enum/title",
          "value": "NSTextFieldBezelStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField~1BezelStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFieldBezelStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField~1BezelStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFieldBezelStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSecureTextFieldCell/title",
          "value": "NSSecureTextFieldCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSecureTextFieldCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSecureTextFieldCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSecureTextFieldCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSecureTextFieldCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell~1drawsBackground/title",
          "value": "drawsBackground"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell~1drawsBackground/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "drawsBackground"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell/title",
          "value": "NSTextFieldCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFieldCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFieldCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/title",
          "value": "NSAccessibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell~1allowedInputSourceLocales/title",
          "value": "allowedInputSourceLocales"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell~1allowedInputSourceLocales/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowedInputSourceLocales"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSActionCell/title",
          "value": "NSActionCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSActionCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSActionCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSActionCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSActionCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell~1textColor/title",
          "value": "textColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell~1textColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "textColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCell/title",
          "value": "NSTokenFieldCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTokenFieldCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTokenFieldCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell~1init(coder:)/title",
          "value": "initWithCoder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell~1init(coder:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCoder:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathComponentCell/title",
          "value": "NSPathComponentCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathComponentCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPathComponentCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathComponentCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPathComponentCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title",
          "value": "NSView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell~1backgroundColor/title",
          "value": "backgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell~1backgroundColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backgroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchFieldCell/title",
          "value": "NSSearchFieldCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchFieldCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchFieldCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchFieldCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchFieldCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/title",
          "value": "NSUserInterfaceItemIdentification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceItemIdentification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemIdentification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceItemIdentification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell~1setUpFieldEditorAttributes(_:)/title",
          "value": "setUpFieldEditorAttributes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell~1setUpFieldEditorAttributes(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setUpFieldEditorAttributes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/title",
          "value": "NSTextField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell~1placeholderAttributedString/title",
          "value": "placeholderAttributedString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell~1placeholderAttributedString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "placeholderAttributedString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell~1init(textCell:)/title",
          "value": "initTextCell:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell~1init(textCell:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initTextCell:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboBoxCell/title",
          "value": "NSComboBoxCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboBoxCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSComboBoxCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboBoxCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSComboBoxCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/title",
          "value": "NSAccessibilityElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityElementProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableHeaderCell/title",
          "value": "NSTableHeaderCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableHeaderCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableHeaderCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableHeaderCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableHeaderCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell~1setWantsNotificationForMarkedText(_:)/title",
          "value": "setWantsNotificationForMarkedText:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldCell~1setWantsNotificationForMarkedText(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setWantsNotificationForMarkedText:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1init(textCell:)/title",
          "value": "initTextCell:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1init(textCell:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initTextCell:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstextfieldcell"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstextfieldcell"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
