{
  "abstract": [
    {
      "text": "Constants for the text layout sections document attribute key.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@NSTextLayoutSectionKey",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSTextLayoutSectionKey"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextLayoutSectionKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "NSTextLayoutSectionKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "NSTextLayoutSectionKey"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these constants as values for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionsAttribute",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key in the document attributes dictionary.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentAttributeKey": {
      "abstract": [
        {
          "text": "The attributes you apply to an entire document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAttributedStringDocumentAttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentAttributeKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedStringDocumentAttributeKey",
      "type": "topic",
      "url": "/documentation/appkit/nsattributedstringdocumentattributekey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentType": {
      "abstract": [
        {
          "text": "Constants for the document type document attribute key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAttributedStringDocumentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedStringDocumentType",
      "type": "topic",
      "url": "/documentation/appkit/nsattributedstringdocumenttype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionKey": {
      "abstract": [
        {
          "text": "Constants for the text layout sections document attribute key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutSectionKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextLayoutSectionKey",
      "type": "topic",
      "url": "/documentation/appkit/nstextlayoutsectionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionOrientation": {
      "abstract": [
        {
          "text": "The orientation of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutSectionOrientation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionOrientation",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextLayoutSectionOrientation",
      "type": "topic",
      "url": "/documentation/appkit/nstextlayoutsectionorientation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionRange": {
      "abstract": [
        {
          "text": "The character range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutSectionRange"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextLayoutSectionRange",
      "type": "topic",
      "url": "/documentation/appkit/nstextlayoutsectionrange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionsAttribute": {
      "abstract": [
        {
          "text": "The layout orientations for each section.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutSectionsAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionsAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextLayoutSectionsAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nstextlayoutsectionsattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextScalingType": {
      "abstract": [
        {
          "text": "Constants that specify the text scaling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextScalingType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextScalingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextScalingType"
        }
      ],
      "role": "symbol",
      "title": "NSTextScalingType",
      "type": "topic",
      "url": "/documentation/appkit/nstextscalingtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/document-reading-option-keys": {
      "abstract": [
        {
          "text": "Keys for constructing an attributed string from data on disk.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/document-reading-option-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Document reading option keys",
      "type": "topic",
      "url": "/documentation/appkit/document-reading-option-keys"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-document-wide-attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentAttributeKey",
        "doc://com.apple.appkit/documentation/AppKit/document-reading-option-keys",
        "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentType",
        "doc://com.apple.appkit/documentation/AppKit/NSTextScalingType"
      ],
      "title": "Getting document-wide attributes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-keys-for-text-layouts",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionOrientation",
        "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionRange"
      ],
      "title": "Getting keys for text layouts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextScalingType/title",
          "value": "NSTextScalingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextScalingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextScalingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextScalingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextScalingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstextlayoutsectionkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
