{
  "abstract": [
    {
      "text": "Constants that specify the highlight color to use with the text.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorScheme"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@NSTextHighlightColorScheme",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSTextHighlightColorScheme"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextHighlightColorScheme"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "NSTextHighlightColorScheme"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "NSTextHighlightColorScheme"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorScheme",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " structure as the value of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorSchemeAttributeName",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " attribute. That attribute specifies which color to use when drawing the highlight on the text. This attribute specifies only the color option. To display the highlight itself, add the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightStyleAttributeName",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " attribute to the text.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpellingState": {
      "abstract": [
        {
          "text": "Constants for the spelling state attribute key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSSpellingState"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpellingState",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSpellingState",
      "type": "topic",
      "url": "/documentation/appkit/nsspellingstate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextEffectStyle": {
      "abstract": [
        {
          "text": "Constants for the type of effect to apply to the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextEffectStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextEffectStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextEffectStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstexteffectstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorScheme": {
      "abstract": [
        {
          "text": "Constants that specify the highlight color to use with the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextHighlightColorScheme"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorScheme",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextHighlightColorScheme",
      "type": "topic",
      "url": "/documentation/appkit/nstexthighlightcolorscheme"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorSchemeAttributeName": {
      "abstract": [
        {
          "text": "The custom highlight color to apply to the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextHighlightColorSchemeAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorSchemeAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextHighlightColorSchemeAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nstexthighlightcolorschemeattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorSchemeBlue": {
      "abstract": [
        {
          "text": "A blue highlight color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextHighlightColorSchemeBlue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorSchemeBlue",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextHighlightColorSchemeBlue",
      "type": "topic",
      "url": "/documentation/appkit/nstexthighlightcolorschemeblue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorSchemeDefault": {
      "abstract": [
        {
          "text": "The default system highlight color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextHighlightColorSchemeDefault"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorSchemeDefault",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextHighlightColorSchemeDefault",
      "type": "topic",
      "url": "/documentation/appkit/nstexthighlightcolorschemedefault"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorSchemeMint": {
      "abstract": [
        {
          "text": "A mint green highlight color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextHighlightColorSchemeMint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorSchemeMint",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextHighlightColorSchemeMint",
      "type": "topic",
      "url": "/documentation/appkit/nstexthighlightcolorschememint"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorSchemeOrange": {
      "abstract": [
        {
          "text": "An orange highlight color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextHighlightColorSchemeOrange"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorSchemeOrange",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextHighlightColorSchemeOrange",
      "type": "topic",
      "url": "/documentation/appkit/nstexthighlightcolorschemeorange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorSchemePink": {
      "abstract": [
        {
          "text": "A pink highlight color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextHighlightColorSchemePink"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorSchemePink",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextHighlightColorSchemePink",
      "type": "topic",
      "url": "/documentation/appkit/nstexthighlightcolorschemepink"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorSchemePurple": {
      "abstract": [
        {
          "text": "A purple highlight color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextHighlightColorSchemePurple"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorSchemePurple",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextHighlightColorSchemePurple",
      "type": "topic",
      "url": "/documentation/appkit/nstexthighlightcolorschemepurple"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightStyle": {
      "abstract": [
        {
          "text": "Constants that specify the type of highlight to apply to text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextHighlightStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextHighlightStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstexthighlightstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightStyleAttributeName": {
      "abstract": [
        {
          "text": "An attribute that adds a highlight color to the text to emphasize it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextHighlightStyleAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightStyleAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextHighlightStyleAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nstexthighlightstyleattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle": {
      "abstract": [
        {
          "text": "Constants for the underline style and strikethrough style attribute keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStyle"
        }
      ],
      "role": "symbol",
      "title": "NSUnderlineStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsunderlinestyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingDirectionFormatType": {
      "abstract": [
        {
          "text": "Constants for the writing direction attribute key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWritingDirectionFormatType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingDirectionFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingDirectionFormatType"
        }
      ],
      "role": "symbol",
      "title": "NSWritingDirectionFormatType",
      "type": "topic",
      "url": "/documentation/appkit/nswritingdirectionformattype"
    },
    "doc://com.apple.appkit/documentation/AppKit/textkit-string-attribute-keys": {
      "abstract": [
        {
          "text": "AppKit-specific keys you use to apply attributes to ranges of characters in an attributed string.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/textkit-string-attribute-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TextKit string attribute keys",
      "type": "topic",
      "url": "/documentation/appkit/textkit-string-attribute-keys"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-text-content-attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/textkit-string-attribute-keys",
        "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSTextEffectStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSSpellingState",
        "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingDirectionFormatType"
      ],
      "title": "Getting text content attributes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-color-schemes",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorSchemeDefault",
        "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorSchemeBlue",
        "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorSchemeMint",
        "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorSchemeOrange",
        "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorSchemePink",
        "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorSchemePurple"
      ],
      "title": "Getting the color schemes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirectionFormatType/title",
          "value": "NSWritingDirectionFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirectionFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingDirectionFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirectionFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingDirectionFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle/title",
          "value": "NSUnderlineStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstexthighlightcolorscheme"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
