{
  "abstract": [
    {
      "text": "A set of optional methods implemented by the delegate of an ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSText",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " object to edit text and change text formats.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSTextDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSTextDelegate"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NSTextDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTextDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOutlineView": {
      "abstract": [
        {
          "text": "A view that uses a row-and-column format to display hierarchical data like directories and files that can be expanded and collapsed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOutlineView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOutlineView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOutlineView"
        }
      ],
      "role": "symbol",
      "title": "NSOutlineView",
      "type": "topic",
      "url": "/documentation/appkit/nsoutlineview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSResponder/resignFirstResponder()": {
      "abstract": [
        {
          "text": "Notifies the receiver that it’s been asked to relinquish its status as first responder in its window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resignFirstResponder"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSResponder/resignFirstResponder()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resignFirstResponder"
        }
      ],
      "role": "symbol",
      "title": "resignFirstResponder()",
      "type": "topic",
      "url": "/documentation/appkit/nsresponder/resignfirstresponder()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView": {
      "abstract": [
        {
          "text": "A set of related records, displayed in rows that represent individual records and columns that represent the attributes of those records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableView"
        }
      ],
      "role": "symbol",
      "title": "NSTableView",
      "type": "topic",
      "url": "/documentation/appkit/nstableview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSText": {
      "abstract": [
        {
          "text": "The most general programmatic interface for objects that manage text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSText"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSText"
        }
      ],
      "role": "symbol",
      "title": "NSText",
      "type": "topic",
      "url": "/documentation/appkit/nstext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextDelegate": {
      "abstract": [
        {
          "text": "A set of optional methods implemented by the delegate of an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSText",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object to edit text and change text formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSTextDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nstextdelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextDelegate/textDidBeginEditing(_:)": {
      "abstract": [
        {
          "text": "Informs the delegate that the text object has begun editing (that the user has begun changing it).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textDidBeginEditing"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextDelegate/textDidBeginEditing(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textDidBeginEditing:"
        }
      ],
      "role": "symbol",
      "title": "textDidBeginEditing(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextdelegate/textdidbeginediting(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextDelegate/textDidChange(_:)": {
      "abstract": [
        {
          "text": "Informs the delegate that the text object has changed its characters or formatting attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textDidChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextDelegate/textDidChange(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textDidChange:"
        }
      ],
      "role": "symbol",
      "title": "textDidChange(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextdelegate/textdidchange(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextDelegate/textDidEndEditing(_:)": {
      "abstract": [
        {
          "text": "Informs the delegate that the text object has finished editing (that it has resigned first responder status).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textDidEndEditing"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextDelegate/textDidEndEditing(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textDidEndEditing:"
        }
      ],
      "role": "symbol",
      "title": "textDidEndEditing(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextdelegate/textdidendediting(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextDelegate/textShouldBeginEditing(_:)": {
      "abstract": [
        {
          "text": "Invoked when a text object begins to change its text, this method requests permission for ",
          "type": "text"
        },
        {
          "code": "aTextObject",
          "type": "codeVoice"
        },
        {
          "text": " to begin editing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textShouldBeginEditing"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSText",
          "text": "NSText"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextDelegate/textShouldBeginEditing(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textShouldBeginEditing:"
        }
      ],
      "role": "symbol",
      "title": "textShouldBeginEditing(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextdelegate/textshouldbeginediting(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextDelegate/textShouldEndEditing(_:)": {
      "abstract": [
        {
          "text": "Invoked from a text object’s implementation of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSResponder/resignFirstResponder()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", this method requests permission for ",
          "type": "text"
        },
        {
          "code": "aTextObject",
          "type": "codeVoice"
        },
        {
          "text": " to end editing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textShouldEndEditing"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSText",
          "text": "NSText"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextDelegate/textShouldEndEditing(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textShouldEndEditing:"
        }
      ],
      "role": "symbol",
      "title": "textShouldEndEditing(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextdelegate/textshouldendediting(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextField": {
      "abstract": [
        {
          "text": "Text the user can select or edit to send an action message to a target when the user presses the Return key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextField"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextField"
        }
      ],
      "role": "symbol",
      "title": "NSTextField",
      "type": "topic",
      "url": "/documentation/appkit/nstextfield"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFieldDelegate": {
      "abstract": [
        {
          "text": "A protocol that a text field delegate can use to control its field editor action menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextFieldDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFieldDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextFieldDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSTextFieldDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nstextfielddelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView": {
      "abstract": [
        {
          "text": "A view that draws text and handles user interactions with that text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "role": "symbol",
      "title": "NSTextView",
      "type": "topic",
      "url": "/documentation/appkit/nstextview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextViewDelegate": {
      "abstract": [
        {
          "text": "A set of optional methods that text view delegates can use to manage selection, set text attributes, work with the spell checker, and more.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSTextViewDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nstextviewdelegate"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextViewDelegate"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSOutlineView",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Text-views",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextField",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFieldDelegate",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView",
        "doc://com.apple.appkit/documentation/AppKit/NSTextViewDelegate",
        "doc://com.apple.appkit/documentation/AppKit/NSText"
      ],
      "title": "Text views"
    }
  ],
  "topicSections": [
    {
      "anchor": "Changing-text-formatting",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextDelegate/textDidChange(_:)"
      ],
      "title": "Changing text formatting"
    },
    {
      "anchor": "Editing-text",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextDelegate/textShouldBeginEditing(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextDelegate/textDidBeginEditing(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextDelegate/textShouldEndEditing(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextDelegate/textDidEndEditing(_:)"
      ],
      "title": "Editing text"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTextDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Changing-text-formatting",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextDelegate/textDidChange(_:)"
              ],
              "title": "Changing text formatting"
            },
            {
              "anchor": "Editing-text",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextDelegate/textShouldBeginEditing(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextDelegate/textDidBeginEditing(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextDelegate/textShouldEndEditing(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextDelegate/textDidEndEditing(_:)"
              ],
              "title": "Editing text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextViewDelegate"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Text-views",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextField",
                "doc://com.apple.appkit/documentation/AppKit/NSTextFieldDelegate",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView",
                "doc://com.apple.appkit/documentation/AppKit/NSTextViewDelegate",
                "doc://com.apple.appkit/documentation/AppKit/NSText"
              ],
              "title": "Text views"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSTextDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/title",
          "value": "NSTextField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextDelegate~1textShouldBeginEditing(_:)/title",
          "value": "textShouldBeginEditing:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextDelegate~1textShouldBeginEditing(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textShouldBeginEditing:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextViewDelegate/title",
          "value": "NSTextViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1resignFirstResponder()/title",
          "value": "resignFirstResponder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1resignFirstResponder()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resignFirstResponder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldDelegate/title",
          "value": "NSTextFieldDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFieldDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFieldDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFieldDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/title",
          "value": "NSTableView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextDelegate~1textDidEndEditing(_:)/title",
          "value": "textDidEndEditing:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextDelegate~1textDidEndEditing(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textDidEndEditing:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/title",
          "value": "NSTextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOutlineView/title",
          "value": "NSOutlineView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOutlineView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOutlineView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOutlineView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOutlineView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextDelegate/title",
          "value": "NSTextDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextDelegate~1textDidBeginEditing(_:)/title",
          "value": "textDidBeginEditing:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextDelegate~1textDidBeginEditing(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textDidBeginEditing:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextDelegate~1textDidChange(_:)/title",
          "value": "textDidChange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextDelegate~1textDidChange(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textDidChange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextDelegate~1textShouldEndEditing(_:)/title",
          "value": "textShouldEndEditing:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextDelegate~1textShouldEndEditing(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textShouldEndEditing:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSText/title",
          "value": "NSText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSText"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstextdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstextdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
