{
  "abstract": [
    {
      "text": "The layout orientations for each section.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionsAttribute"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSTextLayoutSectionsAttribute",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSTextLayoutSectionsAttribute"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextLayoutSectionsAttribute"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSTextLayoutSectionsAttribute"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentAttributeKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
              "text": "NSAttributedStringDocumentAttributeKey"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTextLayoutSectionsAttribute"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsarray",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " containing ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsdictionary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects, each dictionary describing a layout orientation section. The dictionary can have two attributes: ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionOrientation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionRange",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". When there is a gap between sections, it’s assumed to have ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TextLayoutOrientation/horizontal",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppearanceDocumentAttribute": {
      "abstract": [
        {
          "text": "The appearance of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAppearanceDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppearanceDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAppearanceDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsappearancedocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentAttributeKey": {
      "abstract": [
        {
          "text": "The attributes you apply to an entire document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAttributedStringDocumentAttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAttributedStringDocumentAttributeKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedStringDocumentAttributeKey",
      "type": "topic",
      "url": "/documentation/appkit/nsattributedstringdocumentattributekey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBackgroundColorDocumentAttribute": {
      "abstract": [
        {
          "text": "The background color of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBackgroundColorDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBackgroundColorDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBackgroundColorDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsbackgroundcolordocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBottomMarginDocumentAttribute": {
      "abstract": [
        {
          "text": "The bottom margin of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBottomMarginDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBottomMarginDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBottomMarginDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsbottommargindocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDefaultFontExcludedDocumentAttribute": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSDefaultFontExcludedDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDefaultFontExcludedDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDefaultFontExcludedDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsdefaultfontexcludeddocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDefaultTabIntervalDocumentAttribute": {
      "abstract": [
        {
          "text": "The default tab stop interval for the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSDefaultTabIntervalDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDefaultTabIntervalDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDefaultTabIntervalDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsdefaulttabintervaldocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSExcludedElementsDocumentAttribute": {
      "abstract": [
        {
          "text": "The HTML elements to exclude in generated HTML.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSExcludedElementsDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSExcludedElementsDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExcludedElementsDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsexcludedelementsdocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHyphenationFactorDocumentAttribute": {
      "abstract": [
        {
          "text": "The hyphenation factor of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSHyphenationFactorDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHyphenationFactorDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSHyphenationFactorDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nshyphenationfactordocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TextLayoutOrientation/horizontal": {
      "abstract": [
        {
          "text": "Lines render horizontally, each line following the previous from top to bottom.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "horizontal"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutManager/TextLayoutOrientation/horizontal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutOrientationHorizontal"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutManager.TextLayoutOrientation.horizontal",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutmanager/textlayoutorientation/horizontal"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLeftMarginDocumentAttribute": {
      "abstract": [
        {
          "text": "The left margin of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLeftMarginDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLeftMarginDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLeftMarginDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsleftmargindocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPaperSizeDocumentAttribute": {
      "abstract": [
        {
          "text": "The paper size for the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPaperSizeDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPaperSizeDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPaperSizeDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nspapersizedocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrefixSpacesDocumentAttribute": {
      "abstract": [
        {
          "text": "The number of spaces for indenting nested HTML elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPrefixSpacesDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrefixSpacesDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPrefixSpacesDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsprefixspacesdocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRightMarginDocumentAttribute": {
      "abstract": [
        {
          "text": "The right margin of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRightMarginDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRightMarginDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRightMarginDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsrightmargindocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionOrientation": {
      "abstract": [
        {
          "text": "The orientation of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutSectionOrientation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionOrientation",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextLayoutSectionOrientation",
      "type": "topic",
      "url": "/documentation/appkit/nstextlayoutsectionorientation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionRange": {
      "abstract": [
        {
          "text": "The character range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutSectionRange"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextLayoutSectionRange",
      "type": "topic",
      "url": "/documentation/appkit/nstextlayoutsectionrange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionsAttribute": {
      "abstract": [
        {
          "text": "The layout orientations for each section.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutSectionsAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutSectionsAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextLayoutSectionsAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nstextlayoutsectionsattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTopMarginDocumentAttribute": {
      "abstract": [
        {
          "text": "The top margin of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTopMarginDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTopMarginDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTopMarginDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nstopmargindocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSViewModeDocumentAttribute": {
      "abstract": [
        {
          "text": "The view mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSViewModeDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSViewModeDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSViewModeDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsviewmodedocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSViewSizeDocumentAttribute": {
      "abstract": [
        {
          "text": "The view size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSViewSizeDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSViewSizeDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSViewSizeDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsviewsizedocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSViewZoomDocumentAttribute": {
      "abstract": [
        {
          "text": "The view zoom.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSViewZoomDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSViewZoomDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSViewZoomDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsviewzoomdocumentattribute"
    },
    "doc://com.apple.documentation/documentation/foundation/nsarray": {
      "abstract": [
        {
          "text": "An object representing a static ordered collection, for use instead of an  constant in cases that require reference semantics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSArray"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsarray",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSArray",
      "type": "topic",
      "url": "/documentation/foundation/nsarray"
    },
    "doc://com.apple.documentation/documentation/foundation/nsdictionary": {
      "abstract": [
        {
          "text": "An object representing a static collection of key-value pairs, for use instead of a  constant in cases that require reference semantics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSDictionary"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsdictionary",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDictionary",
      "type": "topic",
      "url": "/documentation/foundation/nsdictionary"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-document-appearance-keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAppearanceDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSBackgroundColorDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSBottomMarginDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSDefaultFontExcludedDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSDefaultTabIntervalDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSExcludedElementsDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSHyphenationFactorDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSLeftMarginDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSPaperSizeDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSPrefixSpacesDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSRightMarginDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSTopMarginDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSViewModeDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSViewSizeDocumentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSViewZoomDocumentAttribute"
      ],
      "title": "Getting document appearance keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1TextLayoutOrientation~1horizontal/title",
          "value": "NSTextLayoutOrientationHorizontal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutManager~1TextLayoutOrientation~1horizontal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutOrientationHorizontal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsdictionary/abstract",
          "value": [
            {
              "text": "A static collection of objects associated with unique keys.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsarray/abstract",
          "value": [
            {
              "text": "A static ordered collection of objects.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstextlayoutsectionsattribute"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
