{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextMovement"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSTextMovement",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSTextMovement"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextMovement"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSTextMovement"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTextMovement"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSText/didBeginEditingNotification": {
      "abstract": [
        {
          "text": "Posted when an ",
          "type": "text"
        },
        {
          "code": "NSText",
          "type": "codeVoice"
        },
        {
          "text": " object begins any operation that changes characters or formatting attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didBeginEditingNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSText/didBeginEditingNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextDidBeginEditingNotification"
        }
      ],
      "role": "symbol",
      "title": "didBeginEditingNotification",
      "type": "topic",
      "url": "/documentation/appkit/nstext/didbegineditingnotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSText/didChangeNotification": {
      "abstract": [
        {
          "text": "Posted after an ",
          "type": "text"
        },
        {
          "code": "NSText",
          "type": "codeVoice"
        },
        {
          "text": " object performs any operation that changes characters or formatting attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSText/didChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "didChangeNotification",
      "type": "topic",
      "url": "/documentation/appkit/nstext/didchangenotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSText/didEndEditingNotification": {
      "abstract": [
        {
          "text": "Posted when focus leaves an ",
          "type": "text"
        },
        {
          "code": "NSText",
          "type": "codeVoice"
        },
        {
          "text": " object, whether or not any operation has changed characters or formatting attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didEndEditingNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSText/didEndEditingNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextDidEndEditingNotification"
        }
      ],
      "role": "symbol",
      "title": "didEndEditingNotification",
      "type": "topic",
      "url": "/documentation/appkit/nstext/didendeditingnotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSText/movementUserInfoKey": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "userInfo",
          "type": "codeVoice"
        },
        {
          "text": " dictionary key for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSText/didEndEditingNotification",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "movementUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSText/movementUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextMovementUserInfoKey"
        }
      ],
      "role": "symbol",
      "title": "movementUserInfoKey",
      "type": "topic",
      "url": "/documentation/appkit/nstext/movementuserinfokey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextMovement": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextMovement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextMovement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextMovement"
        }
      ],
      "role": "symbol",
      "title": "NSTextMovement",
      "type": "topic",
      "url": "/documentation/appkit/nstextmovement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/backtab": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backtab"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/backtab",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextMovementBacktab"
        }
      ],
      "role": "symbol",
      "title": "NSTextMovement.backtab",
      "type": "topic",
      "url": "/documentation/appkit/nstextmovement/backtab"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/cancel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/cancel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextMovementCancel"
        }
      ],
      "role": "symbol",
      "title": "NSTextMovement.cancel",
      "type": "topic",
      "url": "/documentation/appkit/nstextmovement/cancel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/down": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "down"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/down",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextMovementDown"
        }
      ],
      "role": "symbol",
      "title": "NSTextMovement.down",
      "type": "topic",
      "url": "/documentation/appkit/nstextmovement/down"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextmovement/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/left": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextMovementLeft"
        }
      ],
      "role": "symbol",
      "title": "NSTextMovement.left",
      "type": "topic",
      "url": "/documentation/appkit/nstextmovement/left"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/other": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "other"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/other",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextMovementOther"
        }
      ],
      "role": "symbol",
      "title": "NSTextMovement.other",
      "type": "topic",
      "url": "/documentation/appkit/nstextmovement/other"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/return": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`return`"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/return",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextMovementReturn"
        }
      ],
      "role": "symbol",
      "title": "NSTextMovement.return",
      "type": "topic",
      "url": "/documentation/appkit/nstextmovement/return"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/right": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextMovementRight"
        }
      ],
      "role": "symbol",
      "title": "NSTextMovement.right",
      "type": "topic",
      "url": "/documentation/appkit/nstextmovement/right"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/tab": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tab"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/tab",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextMovementTab"
        }
      ],
      "role": "symbol",
      "title": "NSTextMovement.tab",
      "type": "topic",
      "url": "/documentation/appkit/nstextmovement/tab"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/up": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "up"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/up",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextMovementUp"
        }
      ],
      "role": "symbol",
      "title": "NSTextMovement.up",
      "type": "topic",
      "url": "/documentation/appkit/nstextmovement/up"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Notifications",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSText/didBeginEditingNotification",
        "doc://com.apple.appkit/documentation/AppKit/NSText/didChangeNotification",
        "doc://com.apple.appkit/documentation/AppKit/NSText/didEndEditingNotification",
        "doc://com.apple.appkit/documentation/AppKit/NSText/movementUserInfoKey"
      ],
      "title": "Notifications"
    }
  ],
  "topicSections": [
    {
      "anchor": "Movement-Options",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/return",
        "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/tab",
        "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/backtab",
        "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/left",
        "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/right",
        "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/up",
        "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/down",
        "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/cancel",
        "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/other"
      ],
      "title": "Movement Options"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTextMovement"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextMovement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextMovement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Movement-Options",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/return",
                "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/tab",
                "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/backtab",
                "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/left",
                "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/right",
                "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/up",
                "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/down",
                "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/cancel",
                "doc://com.apple.appkit/documentation/AppKit/NSTextMovement/other"
              ],
              "title": "Movement Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Notifications",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSText/didBeginEditingNotification",
                "doc://com.apple.appkit/documentation/AppKit/NSText/didChangeNotification",
                "doc://com.apple.appkit/documentation/AppKit/NSText/didEndEditingNotification",
                "doc://com.apple.appkit/documentation/AppKit/NSText/movementUserInfoKey"
              ],
              "title": "Notifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSTextMovement"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1backtab/title",
          "value": "NSTextMovementBacktab"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1backtab/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextMovementBacktab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1up/title",
          "value": "NSTextMovementUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1up/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextMovementUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1tab/title",
          "value": "NSTextMovementTab"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1tab/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextMovementTab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1return/title",
          "value": "NSTextMovementReturn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1return/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextMovementReturn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1left/title",
          "value": "NSTextMovementLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextMovementLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1right/title",
          "value": "NSTextMovementRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextMovementRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1other/title",
          "value": "NSTextMovementOther"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1other/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextMovementOther"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSText~1didBeginEditingNotification/title",
          "value": "NSTextDidBeginEditingNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSText~1didBeginEditingNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextDidBeginEditingNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1cancel/title",
          "value": "NSTextMovementCancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1cancel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextMovementCancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement/title",
          "value": "NSTextMovement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextMovement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextMovement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1down/title",
          "value": "NSTextMovementDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextMovement~1down/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextMovementDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSText~1didEndEditingNotification/title",
          "value": "NSTextDidEndEditingNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSText~1didEndEditingNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextDidEndEditingNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSText~1movementUserInfoKey/title",
          "value": "NSTextMovementUserInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSText~1movementUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextMovementUserInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSText~1didChangeNotification/title",
          "value": "NSTextDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSText~1didChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextDidChangeNotification"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstextmovement"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstextmovement"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
