{
  "abstract": [
    {
      "text": "An object that represents the Cocoa text input system.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSTextInputContext",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSTextInputContext"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextInputContext"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSTextInputContext"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTextInputContext"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The text input system communicates primarily with the client of the activated input context via the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputClient",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextAlternatives": {
      "abstract": [
        {
          "text": "A list of alternative strings for a piece of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextAlternatives"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextAlternatives",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextAlternatives"
        }
      ],
      "role": "symbol",
      "title": "NSTextAlternatives",
      "type": "topic",
      "url": "/documentation/appkit/nstextalternatives"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContent": {
      "abstract": [
        {
          "text": "A protocol that describes specific kinds of input content types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextContent"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContent"
        }
      ],
      "role": "symbol",
      "title": "NSTextContent",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputClient": {
      "abstract": [
        {
          "text": "A set of methods that text views need to implement to interact properly with the text input management system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextInputClient"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputClient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextInputClient"
        }
      ],
      "role": "symbol",
      "title": "NSTextInputClient",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputclient"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext": {
      "abstract": [
        {
          "text": "An object that represents the Cocoa text input system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextInputContext"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextInputContext"
        }
      ],
      "role": "symbol",
      "title": "NSTextInputContext",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputcontext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/acceptsGlyphInfo": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the client handles ",
          "type": "text"
        },
        {
          "code": "NSGlyphInfoAttributeName",
          "type": "codeVoice"
        },
        {
          "text": " or not.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "acceptsGlyphInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/acceptsGlyphInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "acceptsGlyphInfo"
        }
      ],
      "role": "symbol",
      "title": "acceptsGlyphInfo",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputcontext/acceptsglyphinfo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/activate()": {
      "abstract": [
        {
          "text": "Activates the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activate"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/activate()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activate"
        }
      ],
      "role": "symbol",
      "title": "activate()",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputcontext/activate()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/allowedInputSourceLocales": {
      "abstract": [
        {
          "text": "The set of keyboard input source locales allowed when this input context is active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowedInputSourceLocales"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/allowedInputSourceLocales",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowedInputSourceLocales"
        }
      ],
      "role": "symbol",
      "title": "allowedInputSourceLocales",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputcontext/allowedinputsourcelocales"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/client": {
      "abstract": [
        {
          "text": "The owner of this input context. (read-only)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "client"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextInputClient",
          "text": "NSTextInputClient"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/client",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "client"
        }
      ],
      "role": "symbol",
      "title": "client",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputcontext/client"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/current": {
      "abstract": [
        {
          "text": "Returns the current, activated, text input context object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "current"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextInputContext",
          "text": "NSTextInputContext"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/current",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentInputContext"
        }
      ],
      "role": "symbol",
      "title": "current",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputcontext/current"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/deactivate()": {
      "abstract": [
        {
          "text": "Deactivates the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deactivate"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/deactivate()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deactivate"
        }
      ],
      "role": "symbol",
      "title": "deactivate()",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputcontext/deactivate()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/discardMarkedText()": {
      "abstract": [
        {
          "text": "Tells the Cocoa text input system to discard the current conversion session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "discardMarkedText"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/discardMarkedText()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "discardMarkedText"
        }
      ],
      "role": "symbol",
      "title": "discardMarkedText()",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputcontext/discardmarkedtext()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/handleEvent(_:)": {
      "abstract": [
        {
          "text": "Tells the Cocoa text input system to handle mouse or key events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handleEvent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/handleEvent(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleEvent:"
        }
      ],
      "role": "symbol",
      "title": "handleEvent(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputcontext/handleevent(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/init(client:)": {
      "abstract": [
        {
          "text": "The designated initializer",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "client"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextInputClient",
          "text": "NSTextInputClient"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/init(client:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithClient:"
        }
      ],
      "role": "symbol",
      "title": "init(client:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputcontext/init(client:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/invalidateCharacterCoordinates()": {
      "abstract": [
        {
          "text": "Notifies the Cocoa text input system that the position information previously queried via methods like ",
          "type": "text"
        },
        {
          "code": "firstRectForCharacterRange:actualRange:",
          "type": "codeVoice"
        },
        {
          "text": " needs to be updated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidateCharacterCoordinates"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/invalidateCharacterCoordinates()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "invalidateCharacterCoordinates"
        }
      ],
      "role": "symbol",
      "title": "invalidateCharacterCoordinates()",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputcontext/invalidatecharactercoordinates()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/keyboardInputSources": {
      "abstract": [
        {
          "text": "The array of keyboard text input source identifier strings available to the receiver. (read-only)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardInputSources"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextInputSourceIdentifier",
          "text": "NSTextInputSourceIdentifier"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/keyboardInputSources",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keyboardInputSources"
        }
      ],
      "role": "symbol",
      "title": "keyboardInputSources",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputcontext/keyboardinputsources"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/keyboardSelectionDidChangeNotification": {
      "abstract": [
        {
          "text": "Posted after the selected text input source changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardSelectionDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/keyboardSelectionDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextInputContextKeyboardSelectionDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "keyboardSelectionDidChangeNotification",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputcontext/keyboardselectiondidchangenotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/localizedName(forInputSource:)": {
      "abstract": [
        {
          "text": "Returns the display name for the given text input source identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forInputSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextInputSourceIdentifier",
          "text": "NSTextInputSourceIdentifier"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/localizedName(forInputSource:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedNameForInputSource:"
        }
      ],
      "role": "symbol",
      "title": "localizedName(forInputSource:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputcontext/localizedname(forinputsource:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/selectedKeyboardInputSource": {
      "abstract": [
        {
          "text": "The identifier string for the selected keyboard text input source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectedKeyboardInputSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextInputSourceIdentifier",
          "text": "NSTextInputSourceIdentifier"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/selectedKeyboardInputSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectedKeyboardInputSource"
        }
      ],
      "role": "symbol",
      "title": "selectedKeyboardInputSource",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputcontext/selectedkeyboardinputsource"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/textInputClientDidEndScrollingOrZooming()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textInputClientDidEndScrollingOrZooming"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/textInputClientDidEndScrollingOrZooming()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textInputClientDidEndScrollingOrZooming"
        }
      ],
      "role": "symbol",
      "title": "textInputClientDidEndScrollingOrZooming()",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputcontext/textinputclientdidendscrollingorzooming()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/textInputClientDidScroll()": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textInputClientDidScroll"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/textInputClientDidScroll()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textInputClientDidScroll"
        }
      ],
      "role": "symbol",
      "title": "textInputClientDidScroll()",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputcontext/textinputclientdidscroll()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/textInputClientDidUpdateSelection()": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textInputClientDidUpdateSelection"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/textInputClientDidUpdateSelection()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textInputClientDidUpdateSelection"
        }
      ],
      "role": "symbol",
      "title": "textInputClientDidUpdateSelection()",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputcontext/textinputclientdidupdateselection()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/textInputClientWillStartScrollingOrZooming()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textInputClientWillStartScrollingOrZooming"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/textInputClientWillStartScrollingOrZooming()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textInputClientWillStartScrollingOrZooming"
        }
      ],
      "role": "symbol",
      "title": "textInputClientWillStartScrollingOrZooming()",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputcontext/textinputclientwillstartscrollingorzooming()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputSourceIdentifier": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextInputSourceIdentifier"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputSourceIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextInputSourceIdentifier"
        }
      ],
      "role": "symbol",
      "title": "NSTextInputSourceIdentifier",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputsourceidentifier"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator": {
      "abstract": [
        {
          "text": "A view that represents the insertion indicator in text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextInsertionIndicator"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextInsertionIndicator"
        }
      ],
      "role": "symbol",
      "title": "NSTextInsertionIndicator",
      "type": "topic",
      "url": "/documentation/appkit/nstextinsertionindicator"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/AutomaticModeOptions-swift.struct": {
      "abstract": [
        {
          "text": "Options that affect the automatic display mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AutomaticModeOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/AutomaticModeOptions-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AutomaticModeOptions"
        }
      ],
      "role": "symbol",
      "title": "NSTextInsertionIndicator.AutomaticModeOptions",
      "type": "topic",
      "url": "/documentation/appkit/nstextinsertionindicator/automaticmodeoptions-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum": {
      "abstract": [
        {
          "text": "Constants that determine how to display the system text cursor in a custom text UI.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DisplayMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DisplayMode"
        }
      ],
      "role": "symbol",
      "title": "NSTextInsertionIndicator.DisplayMode",
      "type": "topic",
      "url": "/documentation/appkit/nstextinsertionindicator/displaymode-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/adopting-the-system-text-cursor-in-custom-text-views": {
      "abstract": [
        {
          "text": "Incorporate the system text cursor into your custom text UI in AppKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/adopting-the-system-text-cursor-in-custom-text-views",
      "kind": "article",
      "role": "article",
      "title": "Adopting the system text cursor in custom text views",
      "type": "topic",
      "url": "/documentation/appkit/adopting-the-system-text-cursor-in-custom-text-views"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Text-input",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/adopting-the-system-text-cursor-in-custom-text-views",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputClient",
        "doc://com.apple.appkit/documentation/AppKit/NSTextAlternatives",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContent",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/AutomaticModeOptions-swift.struct"
      ],
      "title": "Text input"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-an-Input-Context",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/init(client:)"
      ],
      "title": "Creating an Input Context"
    },
    {
      "anchor": "Getting-the-Input-Context-and-Client",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/current",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/client"
      ],
      "title": "Getting the Input Context and Client"
    },
    {
      "anchor": "Configuring-the-Input-Context",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/acceptsGlyphInfo",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/allowedInputSourceLocales"
      ],
      "title": "Configuring the Input Context"
    },
    {
      "anchor": "Activating-the-Input-Context",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/activate()",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/deactivate()"
      ],
      "title": "Activating the Input Context"
    },
    {
      "anchor": "Handling-Input-Sources",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/handleEvent(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/discardMarkedText()",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/invalidateCharacterCoordinates()",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/keyboardInputSources",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/selectedKeyboardInputSource",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/localizedName(forInputSource:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputSourceIdentifier"
      ],
      "title": "Handling Input Sources"
    },
    {
      "anchor": "Notifications",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/keyboardSelectionDidChangeNotification"
      ],
      "title": "Notifications"
    },
    {
      "anchor": "Instance-Methods",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/textInputClientDidEndScrollingOrZooming()",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/textInputClientWillStartScrollingOrZooming()",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/textInputClientDidScroll()",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/textInputClientDidUpdateSelection()"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTextInputContext"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInputContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInputContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-an-Input-Context",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/init(client:)"
              ],
              "title": "Creating an Input Context"
            },
            {
              "anchor": "Getting-the-Input-Context-and-Client",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/current",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/client"
              ],
              "title": "Getting the Input Context and Client"
            },
            {
              "anchor": "Configuring-the-Input-Context",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/acceptsGlyphInfo",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/allowedInputSourceLocales"
              ],
              "title": "Configuring the Input Context"
            },
            {
              "anchor": "Activating-the-Input-Context",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/activate()",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/deactivate()"
              ],
              "title": "Activating the Input Context"
            },
            {
              "anchor": "Handling-Input-Sources",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/handleEvent(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/discardMarkedText()",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/invalidateCharacterCoordinates()",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/keyboardInputSources",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/selectedKeyboardInputSource",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/localizedName(forInputSource:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputSourceIdentifier"
              ],
              "title": "Handling Input Sources"
            },
            {
              "anchor": "Notifications",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/keyboardSelectionDidChangeNotification"
              ],
              "title": "Notifications"
            },
            {
              "anchor": "Instance-Methods",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/textInputClientDidEndScrollingOrZooming()",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/textInputClientWillStartScrollingOrZooming()",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/textInputClientDidScroll()",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext/textInputClientDidUpdateSelection()"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Text-input",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/adopting-the-system-text-cursor-in-custom-text-views",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputClient",
                "doc://com.apple.appkit/documentation/AppKit/NSTextAlternatives",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContent",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/AutomaticModeOptions-swift.struct"
              ],
              "title": "Text input"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSTextInputContext"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1textInputClientDidEndScrollingOrZooming()/title",
          "value": "textInputClientDidEndScrollingOrZooming"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1textInputClientDidEndScrollingOrZooming()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textInputClientDidEndScrollingOrZooming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1textInputClientDidUpdateSelection()/title",
          "value": "textInputClientDidUpdateSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1textInputClientDidUpdateSelection()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textInputClientDidUpdateSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1textInputClientWillStartScrollingOrZooming()/title",
          "value": "textInputClientWillStartScrollingOrZooming"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1textInputClientWillStartScrollingOrZooming()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textInputClientWillStartScrollingOrZooming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext/title",
          "value": "NSTextInputContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInputContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInputContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient/title",
          "value": "NSTextInputClient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInputClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInputClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1activate()/title",
          "value": "activate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1activate()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "activate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContent/title",
          "value": "NSTextContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1keyboardSelectionDidChangeNotification/title",
          "value": "NSTextInputContextKeyboardSelectionDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1keyboardSelectionDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInputContextKeyboardSelectionDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputSourceIdentifier/title",
          "value": "NSTextInputSourceIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputSourceIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInputSourceIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputSourceIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInputSourceIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlternatives/title",
          "value": "NSTextAlternatives"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlternatives/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextAlternatives"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlternatives/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextAlternatives"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1localizedName(forInputSource:)/title",
          "value": "localizedNameForInputSource:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1localizedName(forInputSource:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "localizedNameForInputSource:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1keyboardInputSources/title",
          "value": "keyboardInputSources"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1keyboardInputSources/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "keyboardInputSources"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1deactivate()/title",
          "value": "deactivate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1deactivate()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deactivate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1textInputClientDidScroll()/title",
          "value": "textInputClientDidScroll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1textInputClientDidScroll()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textInputClientDidScroll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1allowedInputSourceLocales/title",
          "value": "allowedInputSourceLocales"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1allowedInputSourceLocales/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowedInputSourceLocales"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1DisplayMode-swift.enum/title",
          "value": "NSTextInsertionIndicatorDisplayMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1DisplayMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicatorDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1DisplayMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicatorDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1client/title",
          "value": "client"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1client/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "client"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1discardMarkedText()/title",
          "value": "discardMarkedText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1discardMarkedText()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "discardMarkedText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1AutomaticModeOptions-swift.struct/title",
          "value": "NSTextInsertionIndicatorAutomaticModeOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1AutomaticModeOptions-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicatorAutomaticModeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1AutomaticModeOptions-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicatorAutomaticModeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1invalidateCharacterCoordinates()/title",
          "value": "invalidateCharacterCoordinates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1invalidateCharacterCoordinates()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "invalidateCharacterCoordinates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1selectedKeyboardInputSource/title",
          "value": "selectedKeyboardInputSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1selectedKeyboardInputSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectedKeyboardInputSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1acceptsGlyphInfo/title",
          "value": "acceptsGlyphInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1acceptsGlyphInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "acceptsGlyphInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1current/title",
          "value": "currentInputContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1current/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentInputContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator/title",
          "value": "NSTextInsertionIndicator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1init(client:)/title",
          "value": "initWithClient:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1init(client:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithClient:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1handleEvent(_:)/title",
          "value": "handleEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext~1handleEvent(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleEvent:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstextinputcontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstextinputcontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
