{
  "abstract": [
    {
      "text": "A set of methods that text views need to implement to interact properly with the text input management system.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextInput"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSTextInput",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSTextInput"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextInput"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NSTextInput"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTextInput"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInput",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " protocol is slated for deprecation. Please use the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputClient",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " protocol instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "code": "NSTextView",
              "type": "codeVoice"
            },
            {
              "text": " and its abstract superclass ",
              "type": "text"
            },
            {
              "code": "NSText",
              "type": "codeVoice"
            },
            {
              "text": " are the only classes included in Cocoa that implement ",
              "type": "text"
            },
            {
              "code": "NSTextInput",
              "type": "codeVoice"
            },
            {
              "text": ". To create another text view class, you can either subclass ",
              "type": "text"
            },
            {
              "code": "NSTextView",
              "type": "codeVoice"
            },
            {
              "text": " (and not ",
              "type": "text"
            },
            {
              "code": "NSText",
              "type": "codeVoice"
            },
            {
              "text": ", for historical reasons), or subclass ",
              "type": "text"
            },
            {
              "code": "NSView",
              "type": "codeVoice"
            },
            {
              "text": " and implement the ",
              "type": "text"
            },
            {
              "code": "NSTextInput",
              "type": "codeVoice"
            },
            {
              "text": " protocol.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Methods specific to the ",
                  "type": "text"
                },
                {
                  "code": "NSTextInput",
                  "type": "codeVoice"
                },
                {
                  "text": " protocol are intended for dealing with text input and generally are not suitable for other purposes.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInputManager": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSInputManager"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInputManager",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInputManager",
      "type": "topic",
      "url": "/documentation/appkit/nsinputmanager"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInput": {
      "abstract": [
        {
          "text": "A set of methods that text views need to implement to interact properly with the text input management system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextInput"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextInput"
        }
      ],
      "role": "symbol",
      "title": "NSTextInput",
      "type": "topic",
      "url": "/documentation/appkit/nstextinput"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInput/attributedSubstringFromRange:": {
      "abstract": [
        {
          "text": "Returns an attributed string derived from the given range in the receiver’s text storage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "attributedSubstringFromRange:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInput/attributedSubstringFromRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attributedSubstringFromRange:"
        }
      ],
      "role": "symbol",
      "title": "attributedSubstringFromRange:",
      "type": "topic",
      "url": "/documentation/appkit/nstextinput/attributedsubstringfromrange:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInput/characterIndexForPoint:": {
      "abstract": [
        {
          "text": "Returns the index of the character whose frame rectangle includes the given point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "characterIndexForPoint:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInput/characterIndexForPoint:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "characterIndexForPoint:"
        }
      ],
      "role": "symbol",
      "title": "characterIndexForPoint:",
      "type": "topic",
      "url": "/documentation/appkit/nstextinput/characterindexforpoint:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInput/conversationIdentifier": {
      "abstract": [
        {
          "text": "Returns a number used to identify the receiver’s context to the input server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "conversationIdentifier"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInput/conversationIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "conversationIdentifier"
        }
      ],
      "role": "symbol",
      "title": "conversationIdentifier",
      "type": "topic",
      "url": "/documentation/appkit/nstextinput/conversationidentifier"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInput/doCommandBySelector:": {
      "abstract": [
        {
          "text": "Invokes the given selector if possible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "doCommandBySelector:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInput/doCommandBySelector:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "doCommandBySelector:"
        }
      ],
      "role": "symbol",
      "title": "doCommandBySelector:",
      "type": "topic",
      "url": "/documentation/appkit/nstextinput/docommandbyselector:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInput/firstRectForCharacterRange:": {
      "abstract": [
        {
          "text": "Returns the first frame rectangle for characters in the given range, in screen coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "firstRectForCharacterRange:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInput/firstRectForCharacterRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "firstRectForCharacterRange:"
        }
      ],
      "role": "symbol",
      "title": "firstRectForCharacterRange:",
      "type": "topic",
      "url": "/documentation/appkit/nstextinput/firstrectforcharacterrange:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInput/hasMarkedText": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether or not the receiver has marked text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "hasMarkedText"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInput/hasMarkedText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasMarkedText"
        }
      ],
      "role": "symbol",
      "title": "hasMarkedText",
      "type": "topic",
      "url": "/documentation/appkit/nstextinput/hasmarkedtext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInput/insertText:": {
      "abstract": [
        {
          "text": "Inserts the given string into the receiver’s text storage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "insertText:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInput/insertText:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "insertText:"
        }
      ],
      "role": "symbol",
      "title": "insertText:",
      "type": "topic",
      "url": "/documentation/appkit/nstextinput/inserttext:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInput/markedRange": {
      "abstract": [
        {
          "text": "Returns the range of the marked text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "markedRange"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInput/markedRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "markedRange"
        }
      ],
      "role": "symbol",
      "title": "markedRange",
      "type": "topic",
      "url": "/documentation/appkit/nstextinput/markedrange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInput/selectedRange": {
      "abstract": [
        {
          "text": "Returns the range of selected text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "selectedRange"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInput/selectedRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectedRange"
        }
      ],
      "role": "symbol",
      "title": "selectedRange",
      "type": "topic",
      "url": "/documentation/appkit/nstextinput/selectedrange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInput/setMarkedText:selectedRange:": {
      "abstract": [
        {
          "text": "Replaces currently marked text in the receiver’s text storage with the given string and sets the selection to the given range, computed from the beginning of the marked text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setMarkedText:selectedRange:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInput/setMarkedText:selectedRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setMarkedText:selectedRange:"
        }
      ],
      "role": "symbol",
      "title": "setMarkedText:selectedRange:",
      "type": "topic",
      "url": "/documentation/appkit/nstextinput/setmarkedtext:selectedrange:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInput/unmarkText": {
      "abstract": [
        {
          "text": "Removes any marking from pending input text and disposes of the marked text as it wishes. The text view should accept the marked text as if it had been inserted normally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "unmarkText"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInput/unmarkText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unmarkText"
        }
      ],
      "role": "symbol",
      "title": "unmarkText",
      "type": "topic",
      "url": "/documentation/appkit/nstextinput/unmarktext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInput/validAttributesForMarkedText": {
      "abstract": [
        {
          "text": "Returns an array of names for the attributes supported by the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "validAttributesForMarkedText"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInput/validAttributesForMarkedText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "validAttributesForMarkedText"
        }
      ],
      "role": "symbol",
      "title": "validAttributesForMarkedText",
      "type": "topic",
      "url": "/documentation/appkit/nstextinput/validattributesformarkedtext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputClient": {
      "abstract": [
        {
          "text": "A set of methods that text views need to implement to interact properly with the text input management system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextInputClient"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputClient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextInputClient"
        }
      ],
      "role": "symbol",
      "title": "NSTextInputClient",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputclient"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView": {
      "abstract": [
        {
          "text": "A view that draws text and handles user interactions with that text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "role": "symbol",
      "title": "NSTextView",
      "type": "topic",
      "url": "/documentation/appkit/nstextview"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextView"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTextInput"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Marked-text",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextInput/hasMarkedText",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInput/markedRange",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInput/selectedRange",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInput/setMarkedText:selectedRange:",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInput/unmarkText",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInput/validAttributesForMarkedText"
              ],
              "title": "Marked text"
            },
            {
              "anchor": "Text-storage",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextInput/attributedSubstringFromRange:",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInput/insertText:"
              ],
              "title": "Text storage"
            },
            {
              "anchor": "Character-coordinates",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextInput/characterIndexForPoint:",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInput/firstRectForCharacterRange:"
              ],
              "title": "Character coordinates"
            },
            {
              "anchor": "Key-bindings",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextInput/doCommandBySelector:"
              ],
              "title": "Key bindings"
            },
            {
              "anchor": "Other",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextInput/conversationIdentifier"
              ],
              "title": "Other"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSInputManager",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSTextInput"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/title",
          "value": "NSTextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient/title",
          "value": "NSTextInputClient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInputClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInputClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInput/title",
          "value": "NSTextInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInput"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstextinput"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstextinput"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
