{
  "abstract": [
    {
      "text": "A protocol that describes specific kinds of input content types.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextContent"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSTextContent",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSTextContent"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextContent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NSTextContent"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTextContent"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSComboBox": {
      "abstract": [
        {
          "text": "A view that displays a list of values in a pop-up menu where the user selects a value or types in a custom value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSComboBox"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSComboBox",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSComboBox"
        }
      ],
      "role": "symbol",
      "title": "NSComboBox",
      "type": "topic",
      "url": "/documentation/appkit/nscombobox"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchField": {
      "abstract": [
        {
          "text": "A text field optimized for performing text-based searches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSearchField"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSearchField"
        }
      ],
      "role": "symbol",
      "title": "NSSearchField",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfield"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSecureTextField": {
      "abstract": [
        {
          "text": "A text field that hides the typed text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSecureTextField"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSecureTextField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSecureTextField"
        }
      ],
      "role": "symbol",
      "title": "NSSecureTextField",
      "type": "topic",
      "url": "/documentation/appkit/nssecuretextfield"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextAlternatives": {
      "abstract": [
        {
          "text": "A list of alternative strings for a piece of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextAlternatives"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextAlternatives",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextAlternatives"
        }
      ],
      "role": "symbol",
      "title": "NSTextAlternatives",
      "type": "topic",
      "url": "/documentation/appkit/nstextalternatives"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContent": {
      "abstract": [
        {
          "text": "A protocol that describes specific kinds of input content types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextContent"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContent"
        }
      ],
      "role": "symbol",
      "title": "NSTextContent",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContent/contentType": {
      "abstract": [
        {
          "text": "The semantic meaning for a text input area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContent/contentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentType"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "contentType",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontent/contenttype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType": {
      "abstract": [
        {
          "text": "Constants that identify the semantic meaning for a text-entry area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentType"
        }
      ],
      "role": "symbol",
      "title": "NSTextContentType",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextField": {
      "abstract": [
        {
          "text": "Text the user can select or edit to send an action message to a target when the user presses the Return key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextField"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextField"
        }
      ],
      "role": "symbol",
      "title": "NSTextField",
      "type": "topic",
      "url": "/documentation/appkit/nstextfield"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputClient": {
      "abstract": [
        {
          "text": "A set of methods that text views need to implement to interact properly with the text input management system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextInputClient"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputClient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextInputClient"
        }
      ],
      "role": "symbol",
      "title": "NSTextInputClient",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputclient"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext": {
      "abstract": [
        {
          "text": "An object that represents the Cocoa text input system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextInputContext"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextInputContext"
        }
      ],
      "role": "symbol",
      "title": "NSTextInputContext",
      "type": "topic",
      "url": "/documentation/appkit/nstextinputcontext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator": {
      "abstract": [
        {
          "text": "A view that represents the insertion indicator in text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextInsertionIndicator"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextInsertionIndicator"
        }
      ],
      "role": "symbol",
      "title": "NSTextInsertionIndicator",
      "type": "topic",
      "url": "/documentation/appkit/nstextinsertionindicator"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/AutomaticModeOptions-swift.struct": {
      "abstract": [
        {
          "text": "Options that affect the automatic display mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AutomaticModeOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/AutomaticModeOptions-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AutomaticModeOptions"
        }
      ],
      "role": "symbol",
      "title": "NSTextInsertionIndicator.AutomaticModeOptions",
      "type": "topic",
      "url": "/documentation/appkit/nstextinsertionindicator/automaticmodeoptions-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum": {
      "abstract": [
        {
          "text": "Constants that determine how to display the system text cursor in a custom text UI.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DisplayMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DisplayMode"
        }
      ],
      "role": "symbol",
      "title": "NSTextInsertionIndicator.DisplayMode",
      "type": "topic",
      "url": "/documentation/appkit/nstextinsertionindicator/displaymode-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView": {
      "abstract": [
        {
          "text": "A view that draws text and handles user interactions with that text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "role": "symbol",
      "title": "NSTextView",
      "type": "topic",
      "url": "/documentation/appkit/nstextview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTokenField": {
      "abstract": [
        {
          "text": "A text field that converts text into visually distinct tokens.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTokenField"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTokenField"
        }
      ],
      "role": "symbol",
      "title": "NSTokenField",
      "type": "topic",
      "url": "/documentation/appkit/nstokenfield"
    },
    "doc://com.apple.appkit/documentation/AppKit/adopting-the-system-text-cursor-in-custom-text-views": {
      "abstract": [
        {
          "text": "Incorporate the system text cursor into your custom text UI in AppKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/adopting-the-system-text-cursor-in-custom-text-views",
      "kind": "article",
      "role": "article",
      "title": "Adopting the system text cursor in custom text views",
      "type": "topic",
      "url": "/documentation/appkit/adopting-the-system-text-cursor-in-custom-text-views"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSComboBox",
        "doc://com.apple.appkit/documentation/AppKit/NSSearchField",
        "doc://com.apple.appkit/documentation/AppKit/NSSecureTextField",
        "doc://com.apple.appkit/documentation/AppKit/NSTextField",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView",
        "doc://com.apple.appkit/documentation/AppKit/NSTokenField"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Text-input",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/adopting-the-system-text-cursor-in-custom-text-views",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInputClient",
        "doc://com.apple.appkit/documentation/AppKit/NSTextAlternatives",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum",
        "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/AutomaticModeOptions-swift.struct"
      ],
      "title": "Text input"
    }
  ],
  "topicSections": [
    {
      "anchor": "Specifying-content-type",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextContent/contentType",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType"
      ],
      "title": "Specifying content type"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTextContent"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Specifying-content-type",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextContent/contentType",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType"
              ],
              "title": "Specifying content type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextField",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Text-input",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/adopting-the-system-text-cursor-in-custom-text-views",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputContext",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInputClient",
                "doc://com.apple.appkit/documentation/AppKit/NSTextAlternatives",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/DisplayMode-swift.enum",
                "doc://com.apple.appkit/documentation/AppKit/NSTextInsertionIndicator/AutomaticModeOptions-swift.struct"
              ],
              "title": "Text input"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSTextContent"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContent/title",
          "value": "NSTextContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSecureTextField/title",
          "value": "NSSecureTextField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSecureTextField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSecureTextField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSecureTextField/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSecureTextField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient/title",
          "value": "NSTextInputClient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInputClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputClient/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInputClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator/title",
          "value": "NSTextInsertionIndicator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/title",
          "value": "NSTextField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType/title",
          "value": "NSTextContentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlternatives/title",
          "value": "NSTextAlternatives"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlternatives/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextAlternatives"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextAlternatives/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextAlternatives"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/title",
          "value": "NSTextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1AutomaticModeOptions-swift.struct/title",
          "value": "NSTextInsertionIndicatorAutomaticModeOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1AutomaticModeOptions-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicatorAutomaticModeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1AutomaticModeOptions-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicatorAutomaticModeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboBox/title",
          "value": "NSComboBox"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboBox/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSComboBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboBox/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSComboBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContent~1contentType/title",
          "value": "contentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContent~1contentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField/title",
          "value": "NSSearchField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1DisplayMode-swift.enum/title",
          "value": "NSTextInsertionIndicatorDisplayMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1DisplayMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicatorDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInsertionIndicator~1DisplayMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInsertionIndicatorDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext/title",
          "value": "NSTextInputContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInputContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextInputContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextInputContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField/title",
          "value": "NSTokenField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTokenField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTokenField"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstextcontent"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstextcontent"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
