{
  "abstract": [
    {
      "text": "A class that represents a line fragment as a single textual layout and rendering unit inside a text layout fragment.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSTextLineFragment",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSTextLineFragment"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextLineFragment"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSTextLineFragment"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTextLineFragment"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContainer": {
      "abstract": [
        {
          "text": "A region where text layout occurs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextContainer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContainer"
        }
      ],
      "role": "symbol",
      "title": "NSTextContainer",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontainer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutFragment": {
      "abstract": [
        {
          "text": "A class that represents the layout fragment typically corresponding to a rendering surface, such as a layer or view subclass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextLayoutFragment"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutFragment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutFragment"
        }
      ],
      "role": "symbol",
      "title": "NSTextLayoutFragment",
      "type": "topic",
      "url": "/documentation/appkit/nstextlayoutfragment"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutManager": {
      "abstract": [
        {
          "text": "The primary class that you use to manage text layout and presentation for custom text displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextLayoutManager"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutManager"
        }
      ],
      "role": "symbol",
      "title": "NSTextLayoutManager",
      "type": "topic",
      "url": "/documentation/appkit/nstextlayoutmanager"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutOrientationProvider": {
      "abstract": [
        {
          "text": "A set of methods that define the orientation of text for an object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextLayoutOrientationProvider"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutOrientationProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutOrientationProvider"
        }
      ],
      "role": "symbol",
      "title": "NSTextLayoutOrientationProvider",
      "type": "topic",
      "url": "/documentation/appkit/nstextlayoutorientationprovider"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment": {
      "abstract": [
        {
          "text": "A class that represents a line fragment as a single textual layout and rendering unit inside a text layout fragment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextLineFragment"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLineFragment"
        }
      ],
      "role": "symbol",
      "title": "NSTextLineFragment",
      "type": "topic",
      "url": "/documentation/appkit/nstextlinefragment"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/attributedString": {
      "abstract": [
        {
          "text": "The source attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributedString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/attributedString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attributedString"
        }
      ],
      "role": "symbol",
      "title": "attributedString",
      "type": "topic",
      "url": "/documentation/appkit/nstextlinefragment/attributedstring"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/characterIndex(for:)": {
      "abstract": [
        {
          "text": "Returns character index for a point inside the line fragment coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "characterIndex"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/characterIndex(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "characterIndexForPoint:"
        }
      ],
      "role": "symbol",
      "title": "characterIndex(for:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextlinefragment/characterindex(for:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/characterRange": {
      "abstract": [
        {
          "text": "The string range for the source attributed string that corresponds to this line fragment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "characterRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/characterRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "characterRange"
        }
      ],
      "role": "symbol",
      "title": "characterRange",
      "type": "topic",
      "url": "/documentation/appkit/nstextlinefragment/characterrange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/draw(at:in:)": {
      "abstract": [
        {
          "text": "Renders the line fragment contents at the rendering origin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draw"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGContextRef",
          "text": "CGContext"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/draw(at:in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawAtPoint:inContext:"
        }
      ],
      "role": "symbol",
      "title": "draw(at:in:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextlinefragment/draw(at:in:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/fractionOfDistanceThroughGlyph(for:)": {
      "abstract": [
        {
          "text": "Returns character index for a point inside the line fragment coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fractionOfDistanceThroughGlyph"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/fractionOfDistanceThroughGlyph(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fractionOfDistanceThroughGlyphForPoint:"
        }
      ],
      "role": "symbol",
      "title": "fractionOfDistanceThroughGlyph(for:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextlinefragment/fractionofdistancethroughglyph(for:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/glyphOrigin": {
      "abstract": [
        {
          "text": "Rendering origin for the left-most glyph in the line fragment coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "glyphOrigin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/glyphOrigin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "glyphOrigin"
        }
      ],
      "role": "symbol",
      "title": "glyphOrigin",
      "type": "topic",
      "url": "/documentation/appkit/nstextlinefragment/glyphorigin"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/init(attributedString:range:)": {
      "abstract": [
        {
          "text": "Creates a new line fragment from the attributed string for the range of characters you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "attributedString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "range"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/init(attributedString:range:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithAttributedString:range:"
        }
      ],
      "role": "symbol",
      "title": "init(attributedString:range:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextlinefragment/init(attributedstring:range:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/init(coder:)": {
      "abstract": [
        {
          "text": "Creates a new line fragment with from data in an unarchiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/init(coder:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCoder:"
        }
      ],
      "role": "symbol",
      "title": "init(coder:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextlinefragment/init(coder:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/init(string:attributes:range:)": {
      "abstract": [
        {
          "text": "Creates a new line fragment using the string, attributes, and range you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "string"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "attributes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringKey",
          "text": "Key"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "range"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/init(string:attributes:range:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithString:attributes:range:"
        }
      ],
      "role": "symbol",
      "title": "init(string:attributes:range:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextlinefragment/init(string:attributes:range:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/locationForCharacter(at:)": {
      "abstract": [
        {
          "text": "Returns the location of the character at the specified index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locationForCharacter"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/locationForCharacter(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "locationForCharacterAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "locationForCharacter(at:)",
      "type": "topic",
      "url": "/documentation/appkit/nstextlinefragment/locationforcharacter(at:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/typographicBounds": {
      "abstract": [
        {
          "text": "The typographic bounds that specifies the dimensions of the line fragment for laying out line fragments to each other.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typographicBounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/typographicBounds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "typographicBounds"
        }
      ],
      "role": "symbol",
      "title": "typographicBounds",
      "type": "topic",
      "url": "/documentation/appkit/nstextlinefragment/typographicbounds"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextViewportLayoutController": {
      "abstract": [
        {
          "text": "Manages the layout process inside the viewport interacting with its delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextViewportLayoutController"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextViewportLayoutController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextViewportLayoutController"
        }
      ],
      "role": "symbol",
      "title": "NSTextViewportLayoutController",
      "type": "topic",
      "url": "/documentation/appkit/nstextviewportlayoutcontroller"
    },
    "doc://com.apple.documentation/documentation/UIKit/using-textkit-2-to-interact-with-text": {
      "abstract": [
        {
          "text": "Interact with text by managing text selection and inserting custom text elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/using-textkit-2-to-interact-with-text",
      "kind": "article",
      "role": "sampleCode",
      "title": "Using TextKit 2 to interact with text",
      "type": "topic",
      "url": "/documentation/UIKit/using-textkit-2-to-interact-with-text"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Layout",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/UIKit/using-textkit-2-to-interact-with-text",
        "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutManager",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContainer",
        "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutFragment",
        "doc://com.apple.appkit/documentation/AppKit/NSTextViewportLayoutController",
        "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutOrientationProvider"
      ],
      "title": "Layout"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-line-fragments",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/init(attributedString:range:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/init(coder:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/init(string:attributes:range:)"
      ],
      "title": "Creating line fragments"
    },
    {
      "anchor": "Line-fragment-characteristics",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/attributedString",
        "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/characterRange",
        "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/glyphOrigin",
        "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/typographicBounds"
      ],
      "title": "Line fragment characteristics"
    },
    {
      "anchor": "Finding-specific-text",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/characterIndex(for:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/fractionOfDistanceThroughGlyph(for:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/locationForCharacter(at:)"
      ],
      "title": "Finding specific text"
    },
    {
      "anchor": "Drawing",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/draw(at:in:)"
      ],
      "title": "Drawing"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTextLineFragment"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLineFragment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLineFragment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-line-fragments",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/init(attributedString:range:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/init(coder:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/init(string:attributes:range:)"
              ],
              "title": "Creating line fragments"
            },
            {
              "anchor": "Line-fragment-characteristics",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/attributedString",
                "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/characterRange",
                "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/glyphOrigin",
                "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/typographicBounds"
              ],
              "title": "Line fragment characteristics"
            },
            {
              "anchor": "Finding-specific-text",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/characterIndex(for:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/fractionOfDistanceThroughGlyph(for:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/locationForCharacter(at:)"
              ],
              "title": "Finding specific text"
            },
            {
              "anchor": "Drawing",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextLineFragment/draw(at:in:)"
              ],
              "title": "Drawing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Layout",
              "generated": true,
              "identifiers": [
                "doc://com.apple.documentation/documentation/UIKit/using-textkit-2-to-interact-with-text",
                "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutManager",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContainer",
                "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutFragment",
                "doc://com.apple.appkit/documentation/AppKit/NSTextViewportLayoutController",
                "doc://com.apple.appkit/documentation/AppKit/NSTextLayoutOrientationProvider"
              ],
              "title": "Layout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSTextLineFragment"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLineFragment~1attributedString/title",
          "value": "attributedString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLineFragment~1attributedString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attributedString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLineFragment~1init(attributedString:range:)/title",
          "value": "initWithAttributedString:range:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLineFragment~1init(attributedString:range:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithAttributedString:range:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContainer/title",
          "value": "NSTextContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLayoutOrientationProvider/title",
          "value": "NSTextLayoutOrientationProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLayoutOrientationProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutOrientationProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLayoutOrientationProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutOrientationProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLayoutManager/title",
          "value": "NSTextLayoutManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLayoutManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLayoutManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLineFragment~1characterRange/title",
          "value": "characterRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLineFragment~1characterRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "characterRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLineFragment~1locationForCharacter(at:)/title",
          "value": "locationForCharacterAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLineFragment~1locationForCharacter(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "locationForCharacterAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLineFragment~1typographicBounds/title",
          "value": "typographicBounds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLineFragment~1typographicBounds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "typographicBounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLineFragment~1draw(at:in:)/title",
          "value": "drawAtPoint:inContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLineFragment~1draw(at:in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawAtPoint:inContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLineFragment~1glyphOrigin/title",
          "value": "glyphOrigin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLineFragment~1glyphOrigin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "glyphOrigin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLineFragment~1init(string:attributes:range:)/title",
          "value": "initWithString:attributes:range:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLineFragment~1init(string:attributes:range:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithString:attributes:range:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLineFragment~1characterIndex(for:)/title",
          "value": "characterIndexForPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLineFragment~1characterIndex(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "characterIndexForPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLineFragment~1fractionOfDistanceThroughGlyph(for:)/title",
          "value": "fractionOfDistanceThroughGlyphForPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLineFragment~1fractionOfDistanceThroughGlyph(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "fractionOfDistanceThroughGlyphForPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLineFragment/title",
          "value": "NSTextLineFragment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLineFragment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLineFragment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLineFragment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLineFragment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLineFragment~1init(coder:)/title",
          "value": "initWithCoder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLineFragment~1init(coder:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCoder:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLayoutFragment/title",
          "value": "NSTextLayoutFragment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLayoutFragment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutFragment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextLayoutFragment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutFragment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextViewportLayoutController/title",
          "value": "NSTextViewportLayoutController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextViewportLayoutController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextViewportLayoutController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextViewportLayoutController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextViewportLayoutController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstextlinefragment"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstextlinefragment"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
