{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum/leading",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTickMarkLeft"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSTickMarkLeft",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSTickMarkLeft"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTickMarkLeft"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.12",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSTickMarkLeft"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSTickMarkPosition",
              "text": "NSTickMarkPosition"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTickMarkLeft"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Tick marks to the left (for vertical sliders).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum": {
      "abstract": [
        {
          "text": "The position where a linear slider’s tick marks appear (above, below, leading, or trailing).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TickMarkPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TickMarkPosition"
        }
      ],
      "role": "symbol",
      "title": "NSSlider.TickMarkPosition",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/tickmarkposition-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum/leading": {
      "abstract": [
        {
          "text": "A constant indicating that tick marks are displayed on the leading side of the slider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leading"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSlider",
          "text": "NSSlider"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTickMarkPosition",
          "text": "TickMarkPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSlider/TickMarkPosition-swift.enum/leading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTickMarkPositionLeading"
        }
      ],
      "role": "symbol",
      "title": "leading",
      "type": "topic",
      "url": "/documentation/appkit/nsslider/tickmarkposition-swift.enum/leading"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTickMarkAbove": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTickMarkAbove"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTickMarkAbove",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTickMarkAbove",
      "type": "topic",
      "url": "/documentation/appkit/nstickmarkabove"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTickMarkBelow": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTickMarkBelow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTickMarkBelow",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTickMarkBelow",
      "type": "topic",
      "url": "/documentation/appkit/nstickmarkbelow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTickMarkLeft": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTickMarkLeft"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTickMarkLeft",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTickMarkLeft",
      "type": "topic",
      "url": "/documentation/appkit/nstickmarkleft"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTickMarkRight": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTickMarkRight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTickMarkRight",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTickMarkRight",
      "type": "topic",
      "url": "/documentation/appkit/nstickmarkright"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTickMarkBelow",
        "doc://com.apple.appkit/documentation/AppKit/NSTickMarkAbove",
        "doc://com.apple.appkit/documentation/AppKit/NSTickMarkRight"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum/title",
          "value": "NSTickMarkPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTickMarkPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTickMarkPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum~1leading/title",
          "value": "NSTickMarkPositionLeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSlider~1TickMarkPosition-swift.enum~1leading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTickMarkPositionLeading"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstickmarkleft"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
