{
  "abstract": [
    {
      "text": "A protocol that allows you to provide the items for a bar dynamically.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTouchBarDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSTouchBarDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSTouchBarDelegate"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTouchBarDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NSTouchBarDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTouchBarDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use a bar delegate, according to the needs of your app, to dynamically create items (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouchBarItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instances). For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouchBar#Item-objects",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView": {
      "abstract": [
        {
          "text": "A view that draws text and handles user interactions with that text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "role": "symbol",
      "title": "NSTextView",
      "type": "topic",
      "url": "/documentation/appkit/nstextview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTouchBar": {
      "abstract": [
        {
          "text": "An object that provides dynamic contextual controls in the Touch Bar of supported models of MacBook Pro.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTouchBar"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouchBar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTouchBar"
        }
      ],
      "role": "symbol",
      "title": "NSTouchBar",
      "type": "topic",
      "url": "/documentation/appkit/nstouchbar"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTouchBar#Item-objects": {
      "abstract": [],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouchBar#Item-objects",
      "kind": "section",
      "title": "Item objects",
      "type": "topic",
      "url": "/documentation/appkit/nstouchbar#Item-objects"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTouchBarDelegate": {
      "abstract": [
        {
          "text": "A protocol that allows you to provide the items for a bar dynamically.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTouchBarDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouchBarDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTouchBarDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSTouchBarDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nstouchbardelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTouchBarDelegate/touchBar(_:makeItemForIdentifier:)": {
      "abstract": [
        {
          "text": "Asks the delegate object for the bar item for the specified bar and item identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchBar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTouchBar",
          "text": "NSTouchBar"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "makeItemForIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTouchBarItem",
          "text": "NSTouchBarItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTouchBarItemIdentifier",
          "text": "Identifier"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTouchBarItem",
          "text": "NSTouchBarItem"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouchBarDelegate/touchBar(_:makeItemForIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "touchBar:makeItemForIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "touchBar(_:makeItemForIdentifier:)",
      "type": "topic",
      "url": "/documentation/appkit/nstouchbardelegate/touchbar(_:makeitemforidentifier:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTouchBarItem": {
      "abstract": [
        {
          "text": "A UI control shown in the Touch Bar on supported models of MacBook Pro.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTouchBarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouchBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSTouchBarItem",
      "type": "topic",
      "url": "/documentation/appkit/nstouchbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTouchBarProvider": {
      "abstract": [
        {
          "text": "A protocol that an object adopts to create a bar object in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTouchBarProvider"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouchBarProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTouchBarProvider"
        }
      ],
      "role": "symbol",
      "title": "NSTouchBarProvider",
      "type": "topic",
      "url": "/documentation/appkit/nstouchbarprovider"
    },
    "doc://com.apple.appkit/documentation/AppKit/creating-and-customizing-the-touch-bar": {
      "abstract": [
        {
          "text": "Adopt Touch Bar support by displaying interactive content and controls for your macOS apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/creating-and-customizing-the-touch-bar",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating and Customizing the Touch Bar",
      "type": "topic",
      "url": "/documentation/appkit/creating-and-customizing-the-touch-bar"
    },
    "doc://com.apple.appkit/documentation/AppKit/integrating-a-toolbar-and-touch-bar-into-your-app": {
      "abstract": [
        {
          "text": "Provide users quick access to your app’s features from a toolbar and corresponding Touch Bar.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/integrating-a-toolbar-and-touch-bar-into-your-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Integrating a Toolbar and Touch Bar into Your App",
      "type": "topic",
      "url": "/documentation/appkit/integrating-a-toolbar-and-touch-bar-into-your-app"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextView"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/integrating-a-toolbar-and-touch-bar-into-your-app",
        "doc://com.apple.appkit/documentation/AppKit/creating-and-customizing-the-touch-bar",
        "doc://com.apple.appkit/documentation/AppKit/NSTouchBar",
        "doc://com.apple.appkit/documentation/AppKit/NSTouchBarProvider"
      ],
      "title": "Essentials"
    }
  ],
  "topicSections": [
    {
      "anchor": "Providing-bar-items",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTouchBarDelegate/touchBar(_:makeItemForIdentifier:)"
      ],
      "title": "Providing bar items"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTouchBarDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchBarDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchBarDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Providing-bar-items",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTouchBarDelegate/touchBar(_:makeItemForIdentifier:)"
              ],
              "title": "Providing bar items"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextView"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/integrating-a-toolbar-and-touch-bar-into-your-app",
                "doc://com.apple.appkit/documentation/AppKit/creating-and-customizing-the-touch-bar",
                "doc://com.apple.appkit/documentation/AppKit/NSTouchBar",
                "doc://com.apple.appkit/documentation/AppKit/NSTouchBarProvider"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSTouchBarDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarDelegate/title",
          "value": "NSTouchBarDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchBarDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchBarDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarDelegate~1touchBar(_:makeItemForIdentifier:)/title",
          "value": "touchBar:makeItemForIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarDelegate~1touchBar(_:makeItemForIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "touchBar:makeItemForIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/title",
          "value": "NSTextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarProvider/title",
          "value": "NSTouchBarProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchBarProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchBarProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarItem/title",
          "value": "NSTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBar/title",
          "value": "NSTouchBar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBar/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchBar"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstouchbardelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstouchbardelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
