{
  "abstract": [
    {
      "text": "A set of optional methods implemented by delegates of ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCell",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " objects to work with tokenized strings.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSTokenFieldCellDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSTokenFieldCellDelegate"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTokenFieldCellDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NSTokenFieldCellDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTokenFieldCellDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCell": {
      "abstract": [
        {
          "text": "A text field cell subclass that enables tokenized editing of an array of objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTokenFieldCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTokenFieldCell"
        }
      ],
      "role": "symbol",
      "title": "NSTokenFieldCell",
      "type": "topic",
      "url": "/documentation/appkit/nstokenfieldcell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate": {
      "abstract": [
        {
          "text": "A set of optional methods implemented by delegates of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCell",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects to work with tokenized strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTokenFieldCellDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTokenFieldCellDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSTokenFieldCellDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nstokenfieldcelldelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:completionsForSubstring:indexOfToken:indexOfSelectedItem:)": {
      "abstract": [
        {
          "text": "Allows the delegate to provide an array of appropriate completions for the contents of the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tokenFieldCell"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTokenFieldCell",
          "text": "NSTokenFieldCell"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionsForSubstring"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "indexOfToken"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "indexOfSelectedItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">) -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:completionsForSubstring:indexOfToken:indexOfSelectedItem:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tokenFieldCell:completionsForSubstring:indexOfToken:indexOfSelectedItem:"
        }
      ],
      "role": "symbol",
      "title": "tokenFieldCell(_:completionsForSubstring:indexOfToken:indexOfSelectedItem:)",
      "type": "topic",
      "url": "/documentation/appkit/nstokenfieldcelldelegate/tokenfieldcell(_:completionsforsubstring:indexoftoken:indexofselecteditem:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:displayStringForRepresentedObject:)": {
      "abstract": [
        {
          "text": "Allows the delegate to provide a string to be displayed as a proxy for the represented object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tokenFieldCell"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTokenFieldCell",
          "text": "NSTokenFieldCell"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "displayStringForRepresentedObject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:displayStringForRepresentedObject:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tokenFieldCell:displayStringForRepresentedObject:"
        }
      ],
      "role": "symbol",
      "title": "tokenFieldCell(_:displayStringForRepresentedObject:)",
      "type": "topic",
      "url": "/documentation/appkit/nstokenfieldcelldelegate/tokenfieldcell(_:displaystringforrepresentedobject:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:editingStringForRepresentedObject:)": {
      "abstract": [
        {
          "text": "Allows the delegate to provide a string to be edited as a proxy for the represented object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tokenFieldCell"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTokenFieldCell",
          "text": "NSTokenFieldCell"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "editingStringForRepresentedObject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:editingStringForRepresentedObject:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tokenFieldCell:editingStringForRepresentedObject:"
        }
      ],
      "role": "symbol",
      "title": "tokenFieldCell(_:editingStringForRepresentedObject:)",
      "type": "topic",
      "url": "/documentation/appkit/nstokenfieldcelldelegate/tokenfieldcell(_:editingstringforrepresentedobject:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:hasMenuForRepresentedObject:)": {
      "abstract": [
        {
          "text": "Allows the delegate to specify whether the represented object provides a menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tokenFieldCell"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTokenFieldCell",
          "text": "NSTokenFieldCell"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "hasMenuForRepresentedObject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:hasMenuForRepresentedObject:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tokenFieldCell:hasMenuForRepresentedObject:"
        }
      ],
      "role": "symbol",
      "title": "tokenFieldCell(_:hasMenuForRepresentedObject:)",
      "type": "topic",
      "url": "/documentation/appkit/nstokenfieldcelldelegate/tokenfieldcell(_:hasmenuforrepresentedobject:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:menuForRepresentedObject:)": {
      "abstract": [
        {
          "text": "Allows the delegate to provide a menu for the specified represented object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tokenFieldCell"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTokenFieldCell",
          "text": "NSTokenFieldCell"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "menuForRepresentedObject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMenu",
          "text": "NSMenu"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:menuForRepresentedObject:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tokenFieldCell:menuForRepresentedObject:"
        }
      ],
      "role": "symbol",
      "title": "tokenFieldCell(_:menuForRepresentedObject:)",
      "type": "topic",
      "url": "/documentation/appkit/nstokenfieldcelldelegate/tokenfieldcell(_:menuforrepresentedobject:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:readFrom:)": {
      "abstract": [
        {
          "text": "Allows the delegate to return an array of objects representing the data read from ",
          "type": "text"
        },
        {
          "code": "pboard",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tokenFieldCell"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTokenFieldCell",
          "text": "NSTokenFieldCell"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "readFrom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:readFrom:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tokenFieldCell:readFromPasteboard:"
        }
      ],
      "role": "symbol",
      "title": "tokenFieldCell(_:readFrom:)",
      "type": "topic",
      "url": "/documentation/appkit/nstokenfieldcelldelegate/tokenfieldcell(_:readfrom:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:representedObjectForEditing:)": {
      "abstract": [
        {
          "text": "Allows the delegate to provide a represented object for the string being edited.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tokenFieldCell"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTokenFieldCell",
          "text": "NSTokenFieldCell"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "representedObjectForEditing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:representedObjectForEditing:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tokenFieldCell:representedObjectForEditingString:"
        }
      ],
      "role": "symbol",
      "title": "tokenFieldCell(_:representedObjectForEditing:)",
      "type": "topic",
      "url": "/documentation/appkit/nstokenfieldcelldelegate/tokenfieldcell(_:representedobjectforediting:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:shouldAdd:at:)": {
      "abstract": [
        {
          "text": "Allows the delegate to validate the tokens to be added to the receiver at a given index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tokenFieldCell"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTokenFieldCell",
          "text": "NSTokenFieldCell"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldAdd"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:shouldAdd:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tokenFieldCell:shouldAddObjects:atIndex:"
        }
      ],
      "role": "symbol",
      "title": "tokenFieldCell(_:shouldAdd:at:)",
      "type": "topic",
      "url": "/documentation/appkit/nstokenfieldcelldelegate/tokenfieldcell(_:shouldadd:at:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:styleForRepresentedObject:)": {
      "abstract": [
        {
          "text": "Allows the delegate to return the token style for editing the specified represented object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tokenFieldCell"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTokenFieldCell",
          "text": "NSTokenFieldCell"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "styleForRepresentedObject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTokenField",
          "text": "NSTokenField"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTokenStyle",
          "text": "TokenStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:styleForRepresentedObject:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tokenFieldCell:styleForRepresentedObject:"
        }
      ],
      "role": "symbol",
      "title": "tokenFieldCell(_:styleForRepresentedObject:)",
      "type": "topic",
      "url": "/documentation/appkit/nstokenfieldcelldelegate/tokenfieldcell(_:styleforrepresentedobject:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:writeRepresentedObjects:to:)": {
      "abstract": [
        {
          "text": "Allows the delegate the opportunity to write custom pasteboard types to the pasteboard for the represented objects in ",
          "type": "text"
        },
        {
          "code": "objects",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tokenFieldCell"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTokenFieldCell",
          "text": "NSTokenFieldCell"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "writeRepresentedObjects"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:writeRepresentedObjects:to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tokenFieldCell:writeRepresentedObjects:toPasteboard:"
        }
      ],
      "role": "symbol",
      "title": "tokenFieldCell(_:writeRepresentedObjects:to:)",
      "type": "topic",
      "url": "/documentation/appkit/nstokenfieldcelldelegate/tokenfieldcell(_:writerepresentedobjects:to:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Cell",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCell"
      ],
      "title": "Cell"
    }
  ],
  "topicSections": [
    {
      "anchor": "Displaying-Tokenized-Strings",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:displayStringForRepresentedObject:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:styleForRepresentedObject:)"
      ],
      "title": "Displaying Tokenized Strings"
    },
    {
      "anchor": "Editing-a-Tokenized-Strings",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:completionsForSubstring:indexOfToken:indexOfSelectedItem:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:editingStringForRepresentedObject:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:representedObjectForEditing:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:shouldAdd:at:)"
      ],
      "title": "Editing a Tokenized Strings"
    },
    {
      "anchor": "Reading-To-and-Writing-From-the-Pasteboard",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:readFrom:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:writeRepresentedObjects:to:)"
      ],
      "title": "Reading To and Writing From the Pasteboard"
    },
    {
      "anchor": "Managing-Menus-for-Represented-Objects",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:hasMenuForRepresentedObject:)",
        "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:menuForRepresentedObject:)"
      ],
      "title": "Managing Menus for Represented Objects"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTokenFieldCellDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTokenFieldCellDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTokenFieldCellDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Displaying-Tokenized-Strings",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:displayStringForRepresentedObject:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:styleForRepresentedObject:)"
              ],
              "title": "Displaying Tokenized Strings"
            },
            {
              "anchor": "Editing-a-Tokenized-Strings",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:completionsForSubstring:indexOfToken:indexOfSelectedItem:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:editingStringForRepresentedObject:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:representedObjectForEditing:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:shouldAdd:at:)"
              ],
              "title": "Editing a Tokenized Strings"
            },
            {
              "anchor": "Reading-To-and-Writing-From-the-Pasteboard",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:readFrom:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:writeRepresentedObjects:to:)"
              ],
              "title": "Reading To and Writing From the Pasteboard"
            },
            {
              "anchor": "Managing-Menus-for-Represented-Objects",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:hasMenuForRepresentedObject:)",
                "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:menuForRepresentedObject:)"
              ],
              "title": "Managing Menus for Represented Objects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Cell",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCell"
              ],
              "title": "Cell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSTokenFieldCellDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCellDelegate~1tokenFieldCell(_:editingStringForRepresentedObject:)/title",
          "value": "tokenFieldCell:editingStringForRepresentedObject:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCellDelegate~1tokenFieldCell(_:editingStringForRepresentedObject:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tokenFieldCell:editingStringForRepresentedObject:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCellDelegate~1tokenFieldCell(_:readFrom:)/title",
          "value": "tokenFieldCell:readFromPasteboard:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCellDelegate~1tokenFieldCell(_:readFrom:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tokenFieldCell:readFromPasteboard:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCellDelegate/title",
          "value": "NSTokenFieldCellDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCellDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTokenFieldCellDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCellDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTokenFieldCellDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCellDelegate~1tokenFieldCell(_:displayStringForRepresentedObject:)/title",
          "value": "tokenFieldCell:displayStringForRepresentedObject:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCellDelegate~1tokenFieldCell(_:displayStringForRepresentedObject:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tokenFieldCell:displayStringForRepresentedObject:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCellDelegate~1tokenFieldCell(_:menuForRepresentedObject:)/title",
          "value": "tokenFieldCell:menuForRepresentedObject:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCellDelegate~1tokenFieldCell(_:menuForRepresentedObject:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tokenFieldCell:menuForRepresentedObject:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCellDelegate~1tokenFieldCell(_:hasMenuForRepresentedObject:)/title",
          "value": "tokenFieldCell:hasMenuForRepresentedObject:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCellDelegate~1tokenFieldCell(_:hasMenuForRepresentedObject:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tokenFieldCell:hasMenuForRepresentedObject:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCellDelegate~1tokenFieldCell(_:writeRepresentedObjects:to:)/title",
          "value": "tokenFieldCell:writeRepresentedObjects:toPasteboard:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCellDelegate~1tokenFieldCell(_:writeRepresentedObjects:to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tokenFieldCell:writeRepresentedObjects:toPasteboard:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCellDelegate~1tokenFieldCell(_:shouldAdd:at:)/title",
          "value": "tokenFieldCell:shouldAddObjects:atIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCellDelegate~1tokenFieldCell(_:shouldAdd:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tokenFieldCell:shouldAddObjects:atIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCell/title",
          "value": "NSTokenFieldCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTokenFieldCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTokenFieldCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCellDelegate~1tokenFieldCell(_:completionsForSubstring:indexOfToken:indexOfSelectedItem:)/title",
          "value": "tokenFieldCell:completionsForSubstring:indexOfToken:indexOfSelectedItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCellDelegate~1tokenFieldCell(_:completionsForSubstring:indexOfToken:indexOfSelectedItem:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tokenFieldCell:completionsForSubstring:indexOfToken:indexOfSelectedItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCellDelegate~1tokenFieldCell(_:representedObjectForEditing:)/title",
          "value": "tokenFieldCell:representedObjectForEditingString:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCellDelegate~1tokenFieldCell(_:representedObjectForEditing:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tokenFieldCell:representedObjectForEditingString:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCellDelegate~1tokenFieldCell(_:styleForRepresentedObject:)/title",
          "value": "tokenFieldCell:styleForRepresentedObject:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCellDelegate~1tokenFieldCell(_:styleForRepresentedObject:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tokenFieldCell:styleForRepresentedObject:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstokenfieldcelldelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstokenfieldcelldelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
