{
  "abstract": [
    {
      "text": "A toolbar separator that aligns with the vertical split view in the same window.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTrackingSeparatorToolbarItem"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSTrackingSeparatorToolbarItem",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSTrackingSeparatorToolbarItem"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTrackingSeparatorToolbarItem"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSTrackingSeparatorToolbarItem"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTrackingSeparatorToolbarItem"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use a ",
              "type": "text"
            },
            {
              "code": "NSTrackingSeparatorToolbarItem",
              "type": "codeVoice"
            },
            {
              "text": " to divide an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbar",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " into sections that visually align with the views on either side of the divider of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTrackingSeparatorToolbarItem/splitView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". This keeps ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "s above the content that’s the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/target",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for the item’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/target",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "splitView",
              "type": "codeVoice"
            },
            {
              "text": " must be in the same window as the toolbar containing this item before showing the toolbar.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuItemValidation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMenuItemValidation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuItemValidation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMenuItemValidation"
        }
      ],
      "role": "symbol",
      "title": "NSMenuItemValidation",
      "type": "topic",
      "url": "/documentation/appkit/nsmenuitemvalidation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenuToolbarItem": {
      "abstract": [
        {
          "text": "A control that presents a menu in a window’s toolbar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMenuToolbarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenuToolbarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMenuToolbarItem"
        }
      ],
      "role": "symbol",
      "title": "NSMenuToolbarItem",
      "type": "topic",
      "url": "/documentation/appkit/nsmenutoolbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchToolbarItem": {
      "abstract": [
        {
          "text": "A toolbar item that contains a search field optimized for performing text-based searches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSearchToolbarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchToolbarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSearchToolbarItem"
        }
      ],
      "role": "symbol",
      "title": "NSSearchToolbarItem",
      "type": "topic",
      "url": "/documentation/appkit/nssearchtoolbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSToolbar": {
      "abstract": [
        {
          "text": "An object that manages the space above your app’s custom content and either below or integrated with the window’s title bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSToolbar"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSToolbar"
        }
      ],
      "role": "symbol",
      "title": "NSToolbar",
      "type": "topic",
      "url": "/documentation/appkit/nstoolbar"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem": {
      "abstract": [
        {
          "text": "A single item that appears in a window’s toolbar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSToolbarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSToolbarItem"
        }
      ],
      "role": "symbol",
      "title": "NSToolbarItem",
      "type": "topic",
      "url": "/documentation/appkit/nstoolbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/target": {
      "abstract": [
        {
          "text": "The object that defines the action method the toolbar item calls when clicked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "target"
        },
        {
          "kind": "text",
          "text": ": AnyObject?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem/target",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "target"
        }
      ],
      "role": "symbol",
      "title": "target",
      "type": "topic",
      "url": "/documentation/appkit/nstoolbaritem/target"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup": {
      "abstract": [
        {
          "text": "A group of subitems in a toolbar item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSToolbarItemGroup"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSToolbarItemGroup"
        }
      ],
      "role": "symbol",
      "title": "NSToolbarItemGroup",
      "type": "topic",
      "url": "/documentation/appkit/nstoolbaritemgroup"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup/ControlRepresentation-swift.enum": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ControlRepresentation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup/ControlRepresentation-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ControlRepresentation"
        }
      ],
      "role": "symbol",
      "title": "NSToolbarItemGroup.ControlRepresentation",
      "type": "topic",
      "url": "/documentation/appkit/nstoolbaritemgroup/controlrepresentation-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup/SelectionMode-swift.enum": {
      "abstract": [
        {
          "text": "A value that indicates how a grouped toolbar item selects its subitems.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SelectionMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup/SelectionMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SelectionMode"
        }
      ],
      "role": "symbol",
      "title": "NSToolbarItemGroup.SelectionMode",
      "type": "topic",
      "url": "/documentation/appkit/nstoolbaritemgroup/selectionmode-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTrackingSeparatorToolbarItem": {
      "abstract": [
        {
          "text": "A toolbar separator that aligns with the vertical split view in the same window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTrackingSeparatorToolbarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTrackingSeparatorToolbarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTrackingSeparatorToolbarItem"
        }
      ],
      "role": "symbol",
      "title": "NSTrackingSeparatorToolbarItem",
      "type": "topic",
      "url": "/documentation/appkit/nstrackingseparatortoolbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTrackingSeparatorToolbarItem/dividerIndex": {
      "abstract": [
        {
          "text": "The index of the split view divider to align with the tracking separator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dividerIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTrackingSeparatorToolbarItem/dividerIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dividerIndex"
        }
      ],
      "role": "symbol",
      "title": "dividerIndex",
      "type": "topic",
      "url": "/documentation/appkit/nstrackingseparatortoolbaritem/dividerindex"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTrackingSeparatorToolbarItem/init(identifier:splitView:dividerIndex:)": {
      "abstract": [
        {
          "text": "Creates a new tracking separator toolbar item and configures it to align with the divider of the split view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSToolbarItem",
          "text": "NSToolbarItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSToolbarItemIdentifier",
          "text": "Identifier"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "splitView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSplitView",
          "text": "NSSplitView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dividerIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTrackingSeparatorToolbarItem/init(identifier:splitView:dividerIndex:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trackingSeparatorToolbarItemWithIdentifier:splitView:dividerIndex:"
        }
      ],
      "role": "symbol",
      "title": "init(identifier:splitView:dividerIndex:)",
      "type": "topic",
      "url": "/documentation/appkit/nstrackingseparatortoolbaritem/init(identifier:splitview:dividerindex:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTrackingSeparatorToolbarItem/splitView": {
      "abstract": [
        {
          "text": "The vertical split view to align with the toolbar separator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSplitView",
          "text": "NSSplitView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTrackingSeparatorToolbarItem/splitView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "splitView"
        }
      ],
      "role": "symbol",
      "title": "splitView",
      "type": "topic",
      "url": "/documentation/appkit/nstrackingseparatortoolbaritem/splitview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSValidatedUserInterfaceItem": {
      "abstract": [
        {
          "text": "A protocol that a custom class can adopt to manage the automatic enablement of a UI control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSValidatedUserInterfaceItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSValidatedUserInterfaceItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSValidatedUserInterfaceItem"
        }
      ],
      "role": "symbol",
      "title": "NSValidatedUserInterfaceItem",
      "type": "topic",
      "url": "/documentation/appkit/nsvalidateduserinterfaceitem"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.apple.appkit/documentation/AppKit/NSMenuItemValidation",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.apple.appkit/documentation/AppKit/NSValidatedUserInterfaceItem",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Items",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem",
        "doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup",
        "doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup/ControlRepresentation-swift.enum",
        "doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup/SelectionMode-swift.enum",
        "doc://com.apple.appkit/documentation/AppKit/NSMenuToolbarItem",
        "doc://com.apple.appkit/documentation/AppKit/NSSearchToolbarItem"
      ],
      "title": "Items"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-tracking-separator",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTrackingSeparatorToolbarItem/init(identifier:splitView:dividerIndex:)"
      ],
      "title": "Creating a tracking separator"
    },
    {
      "anchor": "configuring-a-tracking-separator",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTrackingSeparatorToolbarItem/dividerIndex",
        "doc://com.apple.appkit/documentation/AppKit/NSTrackingSeparatorToolbarItem/splitView"
      ],
      "title": "configuring a tracking separator"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTrackingSeparatorToolbarItem"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTrackingSeparatorToolbarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTrackingSeparatorToolbarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-tracking-separator",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTrackingSeparatorToolbarItem/init(identifier:splitView:dividerIndex:)"
              ],
              "title": "Creating a tracking separator"
            },
            {
              "anchor": "configuring-a-tracking-separator",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTrackingSeparatorToolbarItem/dividerIndex",
                "doc://com.apple.appkit/documentation/AppKit/NSTrackingSeparatorToolbarItem/splitView"
              ],
              "title": "configuring a tracking separator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Items",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem",
                "doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup",
                "doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup/ControlRepresentation-swift.enum",
                "doc://com.apple.appkit/documentation/AppKit/NSToolbarItemGroup/SelectionMode-swift.enum",
                "doc://com.apple.appkit/documentation/AppKit/NSMenuToolbarItem",
                "doc://com.apple.appkit/documentation/AppKit/NSSearchToolbarItem"
              ],
              "title": "Items"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSTrackingSeparatorToolbarItem"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolbarItem",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSToolbarItem",
                    "text": "NSToolbarItem"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItem/title",
          "value": "NSToolbarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSToolbarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSToolbarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTrackingSeparatorToolbarItem/title",
          "value": "NSTrackingSeparatorToolbarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTrackingSeparatorToolbarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTrackingSeparatorToolbarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTrackingSeparatorToolbarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTrackingSeparatorToolbarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemValidation/title",
          "value": "NSMenuItemValidation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemValidation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenuItemValidation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuItemValidation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenuItemValidation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTrackingSeparatorToolbarItem~1init(identifier:splitView:dividerIndex:)/title",
          "value": "trackingSeparatorToolbarItemWithIdentifier:splitView:dividerIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTrackingSeparatorToolbarItem~1init(identifier:splitView:dividerIndex:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "trackingSeparatorToolbarItemWithIdentifier:splitView:dividerIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbar/title",
          "value": "NSToolbar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSToolbar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbar/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSToolbar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItemGroup/title",
          "value": "NSToolbarItemGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItemGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSToolbarItemGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItemGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSToolbarItemGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSValidatedUserInterfaceItem/title",
          "value": "NSValidatedUserInterfaceItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSValidatedUserInterfaceItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSValidatedUserInterfaceItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSValidatedUserInterfaceItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSValidatedUserInterfaceItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuToolbarItem/title",
          "value": "NSMenuToolbarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuToolbarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenuToolbarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenuToolbarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenuToolbarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItem~1target/title",
          "value": "target"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItem~1target/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "target"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItemGroup~1SelectionMode-swift.enum/title",
          "value": "NSToolbarItemGroupSelectionMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItemGroup~1SelectionMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSToolbarItemGroupSelectionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItemGroup~1SelectionMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSToolbarItemGroupSelectionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTrackingSeparatorToolbarItem~1splitView/title",
          "value": "splitView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTrackingSeparatorToolbarItem~1splitView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "splitView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTrackingSeparatorToolbarItem~1dividerIndex/title",
          "value": "dividerIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTrackingSeparatorToolbarItem~1dividerIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dividerIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchToolbarItem/title",
          "value": "NSSearchToolbarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchToolbarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchToolbarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchToolbarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchToolbarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItemGroup~1ControlRepresentation-swift.enum/title",
          "value": "NSToolbarItemGroupControlRepresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItemGroup~1ControlRepresentation-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSToolbarItemGroupControlRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSToolbarItemGroup~1ControlRepresentation-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSToolbarItemGroupControlRepresentation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstrackingseparatortoolbaritem"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstrackingseparatortoolbaritem"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
