{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStrikethroughMask"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSUnderlineStrikethroughMask",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSUnderlineStrikethroughMask"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSUnderlineStrikethroughMask"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.9",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSUnderlineStrikethroughMask"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSUnderlineStrikethroughMask"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySortButtonRole": {
      "abstract": [
        {
          "text": "The sort button role.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilitySortButtonRole"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySortButtonRole",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilitySortButtonRole",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitysortbuttonrole"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCalibratedBlackColorSpace": {
      "abstract": [
        {
          "text": "Calibrated color space with black and alpha components (pure black is 1.0)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCalibratedBlackColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCalibratedBlackColorSpace",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCalibratedBlackColorSpace",
      "type": "topic",
      "url": "/documentation/appkit/nscalibratedblackcolorspace"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDeviceBlackColorSpace": {
      "abstract": [
        {
          "text": "Device-dependent color space with black and alpha components (pure black is 1.0)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSDeviceBlackColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDeviceBlackColorSpace",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDeviceBlackColorSpace",
      "type": "topic",
      "url": "/documentation/appkit/nsdeviceblackcolorspace"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/JobDisposition-swift.struct/save": {
      "abstract": [
        {
          "text": "Save to a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "save"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintJobDispositionValue",
          "text": "JobDisposition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/JobDisposition-swift.struct/save",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrintSaveJob"
        }
      ],
      "role": "symbol",
      "title": "save",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/jobdisposition-swift.struct/save"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/jobDisposition-swift.property": {
      "abstract": [
        {
          "text": "The action specified for the job.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "jobDisposition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPrintJobDispositionValue",
          "text": "JobDisposition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/jobDisposition-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "jobDisposition"
        }
      ],
      "role": "symbol",
      "title": "jobDisposition",
      "type": "topic",
      "url": "/documentation/appkit/nsprintinfo/jobdisposition-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrintSavePath": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": " object that specifies the pathname to which the job file will be saved when the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/jobDisposition-swift.property",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintInfo/JobDisposition-swift.struct/save",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": "..",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPrintSavePath"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrintSavePath",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPrintSavePath",
      "type": "topic",
      "url": "/documentation/appkit/nsprintsavepath"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStrikethroughMask": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStrikethroughMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStrikethroughMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlineStrikethroughMask",
      "type": "topic",
      "url": "/documentation/appkit/nsunderlinestrikethroughmask"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySortButtonRole",
        "doc://com.apple.appkit/documentation/AppKit/NSCalibratedBlackColorSpace",
        "doc://com.apple.appkit/documentation/AppKit/NSDeviceBlackColorSpace",
        "doc://com.apple.appkit/documentation/AppKit/NSPrintSavePath"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1JobDisposition-swift.struct~1save/title",
          "value": "NSPrintSaveJob"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1JobDisposition-swift.struct~1save/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrintSaveJob"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1jobDisposition-swift.property/title",
          "value": "jobDisposition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrintInfo~1jobDisposition-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "jobDisposition"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsunderlinestrikethroughmask"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
