{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSUnderlinePatternDashDot"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSUnderlinePatternDashDot",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSUnderlinePatternDashDot"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSUnderlinePatternDashDot"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSUnderlinePatternDashDot"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSUnderlineStyle",
              "text": "NSUnderlineStyle"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSUnderlinePatternDashDot"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnderlineByWord": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlineByWord"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnderlineByWord",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlineByWord",
      "type": "topic",
      "url": "/documentation/appkit/nsunderlinebyword"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnderlinePatternDash": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlinePatternDash"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnderlinePatternDash",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlinePatternDash",
      "type": "topic",
      "url": "/documentation/appkit/nsunderlinepatterndash"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnderlinePatternDashDot": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlinePatternDashDot"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnderlinePatternDashDot",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlinePatternDashDot",
      "type": "topic",
      "url": "/documentation/appkit/nsunderlinepatterndashdot"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnderlinePatternDashDotDot": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlinePatternDashDotDot"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnderlinePatternDashDotDot",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlinePatternDashDotDot",
      "type": "topic",
      "url": "/documentation/appkit/nsunderlinepatterndashdotdot"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnderlinePatternDot": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlinePatternDot"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnderlinePatternDot",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlinePatternDot",
      "type": "topic",
      "url": "/documentation/appkit/nsunderlinepatterndot"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnderlinePatternSolid": {
      "abstract": [
        {
          "text": "********************** Deprecated ***********************",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlinePatternSolid"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnderlinePatternSolid",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlinePatternSolid",
      "type": "topic",
      "url": "/documentation/appkit/nsunderlinepatternsolid"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle": {
      "abstract": [
        {
          "text": "Constants for the underline style and strikethrough style attribute keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStyle"
        }
      ],
      "role": "symbol",
      "title": "NSUnderlineStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsunderlinestyle"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSUnderlinePatternSolid",
        "doc://com.apple.appkit/documentation/AppKit/NSUnderlinePatternDot",
        "doc://com.apple.appkit/documentation/AppKit/NSUnderlinePatternDash",
        "doc://com.apple.appkit/documentation/AppKit/NSUnderlinePatternDashDotDot",
        "doc://com.apple.appkit/documentation/AppKit/NSUnderlineByWord"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle/title",
          "value": "NSUnderlineStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsunderlinepatterndashdot"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
