{
  "abstract": [
    {
      "text": "An unknown color-space model.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/unknown",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSUnknownColorSpaceModel"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSUnknownColorSpaceModel",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSUnknownColorSpaceModel"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSUnknownColorSpaceModel"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSUnknownColorSpaceModel"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSColorSpaceModel",
              "text": "NSColorSpaceModel"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSUnknownColorSpaceModel"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCMYKColorSpaceModel": {
      "abstract": [
        {
          "text": "The CYMK (cyan, yellow, magenta, black) color-space model.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCMYKColorSpaceModel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCMYKColorSpaceModel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCMYKColorSpaceModel",
      "type": "topic",
      "url": "/documentation/appkit/nscmykcolorspacemodel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model": {
      "abstract": [
        {
          "text": "Constants that describe the abstract model on which color space objects are based.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Model"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Model"
        }
      ],
      "role": "symbol",
      "title": "NSColorSpace.Model",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/model"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/unknown": {
      "abstract": [
        {
          "text": "An unknown color-space model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSpaceModelUnknown"
        }
      ],
      "role": "symbol",
      "title": "NSColorSpace.Model.unknown",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/model/unknown"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDeviceNColorSpaceModel": {
      "abstract": [
        {
          "text": "DeviceN is a color-space model from Adobe Systems, Inc. used in PostScript and PDF color specification.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSDeviceNColorSpaceModel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDeviceNColorSpaceModel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDeviceNColorSpaceModel",
      "type": "topic",
      "url": "/documentation/appkit/nsdevicencolorspacemodel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGrayColorSpaceModel": {
      "abstract": [
        {
          "text": "The grayscale color-space model.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSGrayColorSpaceModel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGrayColorSpaceModel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSGrayColorSpaceModel",
      "type": "topic",
      "url": "/documentation/appkit/nsgraycolorspacemodel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSIndexedColorSpaceModel": {
      "abstract": [
        {
          "text": "An indexed color space, which identifies specified discrete colors in a color list by index number. An indexed color value (a color specification in indexed color space) consists of an index value that refers to a color in a color list.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSIndexedColorSpaceModel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSIndexedColorSpaceModel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSIndexedColorSpaceModel",
      "type": "topic",
      "url": "/documentation/appkit/nsindexedcolorspacemodel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLABColorSpaceModel": {
      "abstract": [
        {
          "text": "The L*a*b* device-independent color-space model, which represents colors relative to a reference white point.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLABColorSpaceModel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLABColorSpaceModel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLABColorSpaceModel",
      "type": "topic",
      "url": "/documentation/appkit/nslabcolorspacemodel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPatternColorSpaceModel": {
      "abstract": [
        {
          "text": "Identifies a pattern color space, which is simply an image that is repeated over and over again in a tiled pattern.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPatternColorSpaceModel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPatternColorSpaceModel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPatternColorSpaceModel",
      "type": "topic",
      "url": "/documentation/appkit/nspatterncolorspacemodel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRGBColorSpaceModel": {
      "abstract": [
        {
          "text": "The RGB (red green blue) color-space model.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRGBColorSpaceModel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRGBColorSpaceModel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRGBColorSpaceModel",
      "type": "topic",
      "url": "/documentation/appkit/nsrgbcolorspacemodel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnknownColorSpaceModel": {
      "abstract": [
        {
          "text": "An unknown color-space model.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnknownColorSpaceModel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnknownColorSpaceModel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnknownColorSpaceModel",
      "type": "topic",
      "url": "/documentation/appkit/nsunknowncolorspacemodel"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSGrayColorSpaceModel",
        "doc://com.apple.appkit/documentation/AppKit/NSRGBColorSpaceModel",
        "doc://com.apple.appkit/documentation/AppKit/NSCMYKColorSpaceModel",
        "doc://com.apple.appkit/documentation/AppKit/NSLABColorSpaceModel",
        "doc://com.apple.appkit/documentation/AppKit/NSDeviceNColorSpaceModel",
        "doc://com.apple.appkit/documentation/AppKit/NSIndexedColorSpaceModel",
        "doc://com.apple.appkit/documentation/AppKit/NSPatternColorSpaceModel"
      ],
      "title": "Deprecated Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1unknown/title",
          "value": "NSColorSpaceModelUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceModelUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model/title",
          "value": "NSColorSpaceModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceModel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsunknowncolorspacemodel"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
