{
  "abstract": [
    {
      "text": "The up arrow key.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSUpArrowFunctionKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@NSUpArrowFunctionKey@NSUpArrowFunctionKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSUpArrowFunctionKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSUpArrowFunctionKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSUpArrowFunctionKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSUpArrowFunctionKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDownArrowFunctionKey": {
      "abstract": [
        {
          "text": "The down arrow key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDownArrowFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDownArrowFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDownArrowFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSDownArrowFunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsdownarrowfunctionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEndFunctionKey": {
      "abstract": [
        {
          "text": "The end key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEndFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEndFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEndFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSEndFunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsendfunctionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHomeFunctionKey": {
      "abstract": [
        {
          "text": "The home key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSHomeFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHomeFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHomeFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSHomeFunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nshomefunctionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLeftArrowFunctionKey": {
      "abstract": [
        {
          "text": "The left arrow key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLeftArrowFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLeftArrowFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLeftArrowFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSLeftArrowFunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsleftarrowfunctionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSNextFunctionKey": {
      "abstract": [
        {
          "text": "The next key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSNextFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSNextFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSNextFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSNextFunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsnextfunctionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageDownFunctionKey": {
      "abstract": [
        {
          "text": "The page down key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPageDownFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageDownFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPageDownFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSPageDownFunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nspagedownfunctionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageUpFunctionKey": {
      "abstract": [
        {
          "text": "The page up key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPageUpFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageUpFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPageUpFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSPageUpFunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nspageupfunctionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPrevFunctionKey": {
      "abstract": [
        {
          "text": "Previous key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrevFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPrevFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPrevFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSPrevFunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsprevfunctionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRightArrowFunctionKey": {
      "abstract": [
        {
          "text": "The right arrow key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSRightArrowFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRightArrowFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRightArrowFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSRightArrowFunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsrightarrowfunctionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUpArrowFunctionKey": {
      "abstract": [
        {
          "text": "The up arrow key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUpArrowFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUpArrowFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUpArrowFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "NSUpArrowFunctionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsuparrowfunctionkey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Navigation-Related-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDownArrowFunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSLeftArrowFunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSRightArrowFunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSPageUpFunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSPageDownFunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSHomeFunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSEndFunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSPrevFunctionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSNextFunctionKey"
      ],
      "title": "Getting the Navigation-Related Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSUpArrowFunctionKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUpArrowFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Navigation-Related-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDownArrowFunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSLeftArrowFunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSRightArrowFunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSPageUpFunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSPageDownFunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSHomeFunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSEndFunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSPrevFunctionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSNextFunctionKey"
              ],
              "title": "Getting the Navigation-Related Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSUpArrowFunctionKey"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLeftArrowFunctionKey/title",
          "value": "NSLeftArrowFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLeftArrowFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLeftArrowFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageUpFunctionKey/title",
          "value": "NSPageUpFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageUpFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPageUpFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageDownFunctionKey/title",
          "value": "NSPageDownFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageDownFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPageDownFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUpArrowFunctionKey/title",
          "value": "NSUpArrowFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUpArrowFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUpArrowFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrevFunctionKey/title",
          "value": "NSPrevFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPrevFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPrevFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDownArrowFunctionKey/title",
          "value": "NSDownArrowFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDownArrowFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDownArrowFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSNextFunctionKey/title",
          "value": "NSNextFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSNextFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSNextFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRightArrowFunctionKey/title",
          "value": "NSRightArrowFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRightArrowFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRightArrowFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEndFunctionKey/title",
          "value": "NSEndFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEndFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEndFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHomeFunctionKey/title",
          "value": "NSHomeFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHomeFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHomeFunctionKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsuparrowfunctionkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsuparrowfunctionkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
