{
  "abstract": [
    {
      "text": "This constant is used by the ",
      "type": "text"
    },
    {
      "code": "NSRunLoop",
      "type": "codeVoice"
    },
    {
      "text": " method ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.documentation/documentation/foundation/runloop/1409310-perform",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/app-and-environment",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication",
        "doc://com.apple.appkit/documentation/AppKit/app-windows"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/nsupdatewindowsrunloopordering"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "NSUpdateWindowsRunLoopOrdering"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication": {
      "abstract": [
        {
          "text": "An object that manages an app’s main event loop and resources used by all of that app’s objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSApplication"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplication"
        }
      ],
      "role": "symbol",
      "title": "NSApplication",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/displayWindowRunLoopOrdering": {
      "abstract": [
        {
          "text": "The priority at which windows are displayed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayWindowRunLoopOrdering"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/displayWindowRunLoopOrdering",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDisplayWindowRunLoopOrdering"
        }
      ],
      "role": "symbol",
      "title": "displayWindowRunLoopOrdering",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/displaywindowrunloopordering"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/resetCursorRectsRunLoopOrdering": {
      "abstract": [
        {
          "text": "The priority at which cursor rects are reset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resetCursorRectsRunLoopOrdering"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/resetCursorRectsRunLoopOrdering",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSResetCursorRectsRunLoopOrdering"
        }
      ],
      "role": "symbol",
      "title": "resetCursorRectsRunLoopOrdering",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/resetcursorrectsrunloopordering"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/updateWindowsRunLoopOrdering": {
      "abstract": [
        {
          "text": "Run-loop message priority for handling window updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateWindowsRunLoopOrdering"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/updateWindowsRunLoopOrdering",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUpdateWindowsRunLoopOrdering"
        }
      ],
      "role": "symbol",
      "title": "updateWindowsRunLoopOrdering",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/updatewindowsrunloopordering"
    },
    "doc://com.apple.appkit/documentation/AppKit/app-and-environment": {
      "abstract": [
        {
          "text": "Learn about the objects that you use to interact with the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/app-and-environment",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App and Environment",
      "type": "topic",
      "url": "/documentation/appkit/app-and-environment"
    },
    "doc://com.apple.appkit/documentation/AppKit/app-windows": {
      "abstract": [
        {
          "text": "Show, hide, minimize, arrange, and update your app’s windows.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/app-windows",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App Windows",
      "type": "topic",
      "url": "/documentation/appkit/app-windows"
    },
    "doc://com.apple.documentation/documentation/foundation/runloop/1409310-perform": {
      "abstract": [
        {
          "text": "Schedules the sending of a message on the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "perform"
        },
        {
          "kind": "text",
          "text": "(Selector, "
        },
        {
          "kind": "identifier",
          "text": "target"
        },
        {
          "kind": "text",
          "text": ": Any, "
        },
        {
          "kind": "identifier",
          "text": "argument"
        },
        {
          "kind": "text",
          "text": ": Any?, "
        },
        {
          "kind": "identifier",
          "text": "order"
        },
        {
          "kind": "text",
          "text": ": Int, "
        },
        {
          "kind": "identifier",
          "text": "modes"
        },
        {
          "kind": "text",
          "text": ": [RunLoop.Mode])"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/runloop/1409310-perform",
      "kind": "symbol",
      "role": "symbol",
      "title": "perform(_:target:argument:order:modes:)",
      "type": "topic",
      "url": "/documentation/foundation/runloop/1409310-perform"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Run-Loops",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/displayWindowRunLoopOrdering",
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/resetCursorRectsRunLoopOrdering"
      ],
      "title": "Managing Run Loops"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSApplication/updateWindowsRunLoopOrdering"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/updateWindowsRunLoopOrdering"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Run-Loops",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/displayWindowRunLoopOrdering",
                "doc://com.apple.appkit/documentation/AppKit/NSApplication/resetCursorRectsRunLoopOrdering"
              ],
              "title": "Managing Run Loops"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1runloop~11409310-perform/title",
          "value": "performSelector:target:argument:order:modes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1updateWindowsRunLoopOrdering/title",
          "value": "NSUpdateWindowsRunLoopOrdering"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1updateWindowsRunLoopOrdering/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUpdateWindowsRunLoopOrdering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/title",
          "value": "NSApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1resetCursorRectsRunLoopOrdering/title",
          "value": "NSResetCursorRectsRunLoopOrdering"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1resetCursorRectsRunLoopOrdering/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSResetCursorRectsRunLoopOrdering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1displayWindowRunLoopOrdering/title",
          "value": "NSDisplayWindowRunLoopOrdering"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1displayWindowRunLoopOrdering/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDisplayWindowRunLoopOrdering"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsupdatewindowsrunloopordering"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsupdatewindowsrunloopordering"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
