{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation"},"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"text":"NSUserInterfaceLayoutOrientation","kind":"identifier"}],"title":"NSUserInterfaceLayoutOrientation","externalID":"c:@E@NSUserInterfaceLayoutOrientation","platforms":[{"name":"macOS","unavailable":false,"beta":false,"introducedAt":"10.9","deprecated":false}],"symbolKind":"enum","roleHeading":"Enumeration","modules":[{"name":"AppKit"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSUserInterfaceLayoutOrientation","kind":"identifier"}]},"abstract":[{"text":"The stack view layout directions, and user interface axes for hugging priority and clipping resistance.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSUserInterfaceLayoutOrientation","kind":"identifier"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"topicSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation/horizontal","doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation/vertical"],"title":"Constants","anchor":"Constants"},{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation/init(rawValue:)"],"title":"Initializers","anchor":"Initializers"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"relationshipsSections":[{"identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/s:SY","doc://com.externally.resolved.symbol/s:s8SendableP"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsuserinterfacelayoutorientation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsuserinterfacelayoutorientation"]}],"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation","doc://com.apple.appkit/documentation/AppKit/NSStackView/alignment","doc://com.apple.appkit/documentation/AppKit/NSStackView/spacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/useDefaultSpacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/edgeInsets","doc://com.apple.appkit/documentation/AppKit/NSStackView/hasEqualSpacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/distribution-swift.property","doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum"],"title":"Configuring the Stack View Layout","anchor":"Configuring-the-Stack-View-Layout"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.appkit/documentation/AppKit/NSStackView/distribution-swift.property":{"role":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/distribution-swift.property","navigatorTitle":[{"kind":"identifier","text":"distribution"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"distribution","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSStackView","text":"NSStackView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Distribution","preciseIdentifier":"c:@E@NSStackViewDistribution"}],"url":"/documentation/appkit/nsstackview/distribution-swift.property","title":"distribution","kind":"symbol","abstract":[]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum":{"role":"symbol","abstract":[],"title":"NSStackView.Distribution","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Distribution"}],"url":"/documentation/appkit/nsstackview/distribution-swift.enum","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Distribution"}]},"doc://com.externally.resolved.symbol/s:SY":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RawRepresentable","kind":"identifier"},{"text":"<","kind":"text"},{"text":"RawValue","kind":"typeIdentifier","preciseIdentifier":"s:SY8RawValueQa"},{"text":">","kind":"text"}],"url":"/documentation/Swift/RawRepresentable","title":"RawRepresentable","abstract":[{"text":"A type that can be converted to and from an associated raw value.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:SY","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/spacing":{"url":"/documentation/appkit/nsstackview/spacing","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/spacing","title":"spacing","type":"topic","navigatorTitle":[{"text":"spacing","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"spacing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The minimum spacing, in points, between adjacent views in the stack view."}]},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSInteger"}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes an integer."}],"title":"NSInteger"},"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation/vertical":{"url":"/documentation/appkit/nsuserinterfacelayoutorientation/vertical","title":"NSUserInterfaceLayoutOrientation.vertical","kind":"symbol","abstract":[{"type":"text","text":"The vertical orientation."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation/vertical","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vertical","kind":"identifier"}],"navigatorTitle":[{"text":"NSUserInterfaceLayoutOrientationVertical","kind":"identifier"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/hasEqualSpacing":{"url":"/documentation/appkit/nsstackview/hasequalspacing","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/hasEqualSpacing","title":"hasEqualSpacing","type":"topic","navigatorTitle":[{"text":"hasEqualSpacing","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasEqualSpacing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"A Boolean value that indicates whether the spacing between adjacent views should be equal to each other."}],"deprecated":true},"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation/horizontal":{"abstract":[{"text":"The horizontal orientation.","type":"text"}],"title":"NSUserInterfaceLayoutOrientation.horizontal","type":"topic","url":"/documentation/appkit/nsuserinterfacelayoutorientation/horizontal","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSUserInterfaceLayoutOrientationHorizontal"}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation/horizontal","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"horizontal"}]},"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation":{"title":"NSUserInterfaceLayoutOrientation","navigatorTitle":[{"kind":"identifier","text":"NSUserInterfaceLayoutOrientation"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation","role":"symbol","url":"/documentation/appkit/nsuserinterfacelayoutorientation","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSUserInterfaceLayoutOrientation"}],"abstract":[{"type":"text","text":"The stack view layout directions, and user interface axes for hugging priority and clipping resistance."}]},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"type":"topic","title":"Equatable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SQ","role":"symbol","url":"/documentation/Swift/Equatable"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/useDefaultSpacing":{"url":"/documentation/appkit/nsstackview/usedefaultspacing","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/useDefaultSpacing","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"NSStackViewSpacingUseDefault","kind":"identifier"}],"type":"topic","title":"useDefaultSpacing","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useDefaultSpacing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}]},"doc://com.externally.resolved.symbol/s:s8SendableP":{"identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","role":"symbol","type":"topic","url":"/documentation/Swift/Sendable","abstract":[{"text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"title":"Sendable","kind":"symbol"},"doc://com.externally.resolved.symbol/s:SH":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SQ","text":"Equatable"}],"url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"title":"Hashable"},"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"url":"/documentation/Swift/BitwiseCopyable","kind":"symbol","title":"BitwiseCopyable","identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","type":"topic","abstract":[{"text":"","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BitwiseCopyable"},{"kind":"text","text":" : ~Escapable"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation/init(rawValue:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation/init(rawValue:)","url":"/documentation/appkit/nsuserinterfacelayoutorientation/init(rawvalue:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"type":"topic","abstract":[],"role":"symbol","title":"init(rawValue:)"},"doc://com.apple.appkit/documentation/AppKit/NSStackView/alignment":{"url":"/documentation/appkit/nsstackview/alignment","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/alignment","title":"alignment","type":"topic","navigatorTitle":[{"text":"alignment","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alignment","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSLayoutConstraint","text":"NSLayoutConstraint","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSLayoutAttribute","text":"Attribute","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The view alignment within the stack view."}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation","url":"/documentation/appkit/nsstackview/orientation","navigatorTitle":[{"kind":"identifier","text":"orientation"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@NSUserInterfaceLayoutOrientation","kind":"typeIdentifier","text":"NSUserInterfaceLayoutOrientation"}],"kind":"symbol","type":"topic","title":"orientation","role":"symbol","abstract":[{"type":"text","text":"The horizontal or vertical layout direction of the stack view."}]},"doc://com.apple.appkit/documentation/AppKit/NSStackView/edgeInsets":{"url":"/documentation/appkit/nsstackview/edgeinsets","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStackView/edgeInsets","title":"edgeInsets","type":"topic","navigatorTitle":[{"text":"edgeInsets","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"edgeInsets","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@NSEdgeInsets","text":"NSEdgeInsets","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The geometric padding, in points, inside the stack view, surrounding its views."}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"introducedAt":"10.9","deprecated":false,"beta":false,"name":"macOS","unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Enumeration","path":"/metadata/roleHeading","op":"replace"},{"value":"NSUserInterfaceLayoutOrientation","path":"/metadata/title","op":"replace"},{"value":"enum","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"NSUserInterfaceLayoutOrientation"}],"path":"/metadata/fragments","op":"replace"},{"value":[{"text":"NSUserInterfaceLayoutOrientation","kind":"identifier"}],"path":"/metadata/navigatorTitle","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"path":"/hierarchy","op":"replace"},{"value":[{"title":"Constants","anchor":"Constants","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation/horizontal","doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutOrientation/vertical"]}],"path":"/topicSections","op":"replace"},{"value":null,"path":"/relationshipsSections","op":"replace"},{"value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStackView/orientation","doc://com.apple.appkit/documentation/AppKit/NSStackView/alignment","doc://com.apple.appkit/documentation/AppKit/NSStackView/spacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/useDefaultSpacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/edgeInsets","doc://com.apple.appkit/documentation/AppKit/NSStackView/hasEqualSpacing","doc://com.apple.appkit/documentation/AppKit/NSStackView/distribution-swift.property","doc://com.apple.appkit/documentation/AppKit/NSStackView/Distribution-swift.enum"],"anchor":"Configuring-the-Stack-View-Layout","generated":true,"title":"Configuring the Stack View Layout"}],"path":"/seeAlsoSections","op":"replace"},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSUserInterfaceLayoutOrientation"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}]}},{"value":"distribution","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1distribution-swift.property/title","op":"replace"},{"value":[{"text":"distribution","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1distribution-swift.property/fragments","op":"replace"},{"value":"NSStackViewDistribution","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum/title","op":"replace"},{"value":[{"text":"NSStackViewDistribution","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSStackViewDistribution"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1Distribution-swift.enum/navigatorTitle","op":"replace"},{"value":"spacing","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1spacing/title","op":"replace"},{"value":[{"kind":"identifier","text":"spacing"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1spacing/fragments","op":"replace"},{"value":"NSUserInterfaceLayoutOrientationVertical","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation~1vertical/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSUserInterfaceLayoutOrientationVertical"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation~1vertical/fragments","op":"replace"},{"value":"hasEqualSpacing","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1hasEqualSpacing/title"},{"value":[{"kind":"identifier","text":"hasEqualSpacing"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1hasEqualSpacing/fragments"},{"value":"NSUserInterfaceLayoutOrientationHorizontal","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation~1horizontal/title"},{"value":[{"text":"NSUserInterfaceLayoutOrientationHorizontal","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation~1horizontal/fragments"},{"value":"NSUserInterfaceLayoutOrientation","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation/title"},{"value":[{"text":"NSUserInterfaceLayoutOrientation","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation/fragments"},{"value":[{"kind":"identifier","text":"NSUserInterfaceLayoutOrientation"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutOrientation/navigatorTitle"},{"value":"NSStackViewSpacingUseDefault","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1useDefaultSpacing/title"},{"value":[{"kind":"identifier","text":"NSStackViewSpacingUseDefault"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1useDefaultSpacing/fragments"},{"value":"alignment","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1alignment/title"},{"value":[{"kind":"identifier","text":"alignment"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1alignment/fragments"},{"value":"orientation","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1orientation/title"},{"value":[{"text":"orientation","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1orientation/fragments"},{"value":"edgeInsets","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1edgeInsets/title"},{"value":[{"kind":"identifier","text":"edgeInsets"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStackView~1edgeInsets/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}