{
  "abstract": [
    {
      "text": "Change the view’s visibility, vibrancy, and focus ring and respond to appearance-related changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
        "doc://com.apple.appkit/documentation/AppKit/NSView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/nsview-appearance"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Appearance"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/appkit/nsview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/BackgroundStyle": {
      "abstract": [
        {
          "text": "Background styles to apply to a view’s cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BackgroundStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/BackgroundStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BackgroundStyle"
        }
      ],
      "role": "symbol",
      "title": "NSView.BackgroundStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsview/backgroundstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/allowsVibrancy": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the view ensures it is vibrant on top of other content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsVibrancy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/allowsVibrancy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsVibrancy"
        }
      ],
      "role": "symbol",
      "title": "allowsVibrancy",
      "type": "topic",
      "url": "/documentation/appkit/nsview/allowsvibrancy"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/defaultFocusRingType": {
      "abstract": [
        {
          "text": "Returns the default focus ring type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultFocusRingType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFocusRingType",
          "text": "NSFocusRingType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/defaultFocusRingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultFocusRingType"
        }
      ],
      "role": "symbol",
      "title": "defaultFocusRingType",
      "type": "topic",
      "url": "/documentation/appkit/nsview/defaultfocusringtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/drawFocusRingMask()": {
      "abstract": [
        {
          "text": "Draws the focus ring mask for the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawFocusRingMask"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/drawFocusRingMask()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawFocusRingMask"
        }
      ],
      "role": "symbol",
      "title": "drawFocusRingMask()",
      "type": "topic",
      "url": "/documentation/appkit/nsview/drawfocusringmask()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/focusRingMaskBounds": {
      "abstract": [
        {
          "text": "The focus ring mask bounds, specified in the view’s coordinate space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "focusRingMaskBounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/focusRingMaskBounds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "focusRingMaskBounds"
        }
      ],
      "role": "symbol",
      "title": "focusRingMaskBounds",
      "type": "topic",
      "url": "/documentation/appkit/nsview/focusringmaskbounds"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/focusRingType": {
      "abstract": [
        {
          "text": "The type of focus ring drawn around the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "focusRingType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFocusRingType",
          "text": "NSFocusRingType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/focusRingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "focusRingType"
        }
      ],
      "role": "symbol",
      "title": "focusRingType",
      "type": "topic",
      "url": "/documentation/appkit/nsview/focusringtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/isDrawingFindIndicator": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the view or one of its ancestors is being drawn for a find indicator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isDrawingFindIndicator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/isDrawingFindIndicator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawingFindIndicator"
        }
      ],
      "role": "symbol",
      "title": "isDrawingFindIndicator",
      "type": "topic",
      "url": "/documentation/appkit/nsview/isdrawingfindindicator"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/isHidden": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the view is hidden.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isHidden"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/isHidden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hidden"
        }
      ],
      "role": "symbol",
      "title": "isHidden",
      "type": "topic",
      "url": "/documentation/appkit/nsview/ishidden"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/isHiddenOrHasHiddenAncestor": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the view is hidden from sight because it, or one of its ancestors, is marked as hidden.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isHiddenOrHasHiddenAncestor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/isHiddenOrHasHiddenAncestor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hiddenOrHasHiddenAncestor"
        }
      ],
      "role": "symbol",
      "title": "isHiddenOrHasHiddenAncestor",
      "type": "topic",
      "url": "/documentation/appkit/nsview/ishiddenorhashiddenancestor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/noteFocusRingMaskChanged()": {
      "abstract": [
        {
          "text": "Invoked to notify the view that the focus ring mask requires updating.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noteFocusRingMaskChanged"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/noteFocusRingMaskChanged()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "noteFocusRingMaskChanged"
        }
      ],
      "role": "symbol",
      "title": "noteFocusRingMaskChanged()",
      "type": "topic",
      "url": "/documentation/appkit/nsview/notefocusringmaskchanged()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/setKeyboardFocusRingNeedsDisplay(_:)": {
      "abstract": [
        {
          "text": "Invalidates the area around the focus ring.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setKeyboardFocusRingNeedsDisplay"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/setKeyboardFocusRingNeedsDisplay(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setKeyboardFocusRingNeedsDisplayInRect:"
        }
      ],
      "role": "symbol",
      "title": "setKeyboardFocusRingNeedsDisplay(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/setkeyboardfocusringneedsdisplay(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/viewDidChangeBackingProperties()": {
      "abstract": [
        {
          "text": "Responds when the view’s backing store properties change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewDidChangeBackingProperties"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/viewDidChangeBackingProperties()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewDidChangeBackingProperties"
        }
      ],
      "role": "symbol",
      "title": "viewDidChangeBackingProperties()",
      "type": "topic",
      "url": "/documentation/appkit/nsview/viewdidchangebackingproperties()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/viewDidChangeEffectiveAppearance()": {
      "abstract": [
        {
          "text": "Informs the view that its effective appearance changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewDidChangeEffectiveAppearance"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/viewDidChangeEffectiveAppearance()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewDidChangeEffectiveAppearance"
        }
      ],
      "role": "symbol",
      "title": "viewDidChangeEffectiveAppearance()",
      "type": "topic",
      "url": "/documentation/appkit/nsview/viewdidchangeeffectiveappearance()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/viewDidHide()": {
      "abstract": [
        {
          "text": "Invoked when the view is hidden, either directly, or in response to an ancestor being hidden.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewDidHide"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/viewDidHide()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewDidHide"
        }
      ],
      "role": "symbol",
      "title": "viewDidHide()",
      "type": "topic",
      "url": "/documentation/appkit/nsview/viewdidhide()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/viewDidUnhide()": {
      "abstract": [
        {
          "text": "Invoked when the view is unhidden, either directly, or in response to an ancestor being unhidden",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewDidUnhide"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/viewDidUnhide()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewDidUnhide"
        }
      ],
      "role": "symbol",
      "title": "viewDidUnhide()",
      "type": "topic",
      "url": "/documentation/appkit/nsview/viewdidunhide()"
    },
    "doc://com.apple.appkit/documentation/AppKit/core-animation-support": {
      "abstract": [
        {
          "text": "Manage the layer object that provides the view’s visual representation and accelerates drawing operations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/core-animation-support",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Animation Support",
      "type": "topic",
      "url": "/documentation/appkit/core-animation-support"
    },
    "doc://com.apple.appkit/documentation/AppKit/related-ui": {
      "abstract": [
        {
          "text": "Manage contextual menus, cursors, tool tips, and other system-provided windows and content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/related-ui",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Related UI",
      "type": "topic",
      "url": "/documentation/appkit/related-ui"
    },
    "doc://com.apple.appkit/documentation/AppKit/view-coordinates": {
      "abstract": [
        {
          "text": "Manage the frame and bounds rectangles that determine the size and position of the view in the view hierarchy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/view-coordinates",
      "kind": "article",
      "role": "collectionGroup",
      "title": "View Coordinates",
      "type": "topic",
      "url": "/documentation/appkit/view-coordinates"
    },
    "doc://com.apple.appkit/documentation/AppKit/view-hierarchy": {
      "abstract": [
        {
          "text": "Manage the subviews, superview, and window of a view and respond to notifications when the view hierarchy changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/view-hierarchy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "View Hierarchy",
      "type": "topic",
      "url": "/documentation/appkit/view-hierarchy"
    },
    "doc://com.apple.appkit/documentation/AppKit/views-and-controls": {
      "abstract": [
        {
          "text": "Present your content onscreen and handle user input and events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Views and Controls",
      "type": "topic",
      "url": "/documentation/appkit/views-and-controls"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-view",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/view-hierarchy",
        "doc://com.apple.appkit/documentation/AppKit/view-coordinates",
        "doc://com.apple.appkit/documentation/AppKit/core-animation-support",
        "doc://com.apple.appkit/documentation/AppKit/related-ui"
      ],
      "title": "Configuring the view"
    }
  ],
  "topicSections": [
    {
      "anchor": "Showing-and-Hiding-the-View",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/isHidden",
        "doc://com.apple.appkit/documentation/AppKit/NSView/isHiddenOrHasHiddenAncestor",
        "doc://com.apple.appkit/documentation/AppKit/NSView/viewDidHide()",
        "doc://com.apple.appkit/documentation/AppKit/NSView/viewDidUnhide()"
      ],
      "title": "Showing and Hiding the View"
    },
    {
      "anchor": "Responding-to-Appearance-Changes",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/viewDidChangeEffectiveAppearance()",
        "doc://com.apple.appkit/documentation/AppKit/NSView/viewDidChangeBackingProperties()"
      ],
      "title": "Responding to Appearance Changes"
    },
    {
      "anchor": "Getting-the-Vibrancy-Setting",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/allowsVibrancy"
      ],
      "title": "Getting the Vibrancy Setting"
    },
    {
      "anchor": "Drawing-the-Focus-Ring",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/focusRingType",
        "doc://com.apple.appkit/documentation/AppKit/NSView/focusRingMaskBounds",
        "doc://com.apple.appkit/documentation/AppKit/NSView/drawFocusRingMask()",
        "doc://com.apple.appkit/documentation/AppKit/NSView/noteFocusRingMaskChanged()",
        "doc://com.apple.appkit/documentation/AppKit/NSView/setKeyboardFocusRingNeedsDisplay(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/defaultFocusRingType"
      ],
      "title": "Drawing the Focus Ring"
    },
    {
      "anchor": "Displaying-a-Find-Indicator",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/isDrawingFindIndicator"
      ],
      "title": "Displaying a Find Indicator"
    },
    {
      "anchor": "Configuring-a-Cells-Background",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/BackgroundStyle"
      ],
      "title": "Configuring a Cell’s Background"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Showing-and-Hiding-the-View",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/isHidden",
                "doc://com.apple.appkit/documentation/AppKit/NSView/isHiddenOrHasHiddenAncestor",
                "doc://com.apple.appkit/documentation/AppKit/NSView/viewDidHide()",
                "doc://com.apple.appkit/documentation/AppKit/NSView/viewDidUnhide()"
              ],
              "title": "Showing and Hiding the View"
            },
            {
              "anchor": "Responding-to-Appearance-Changes",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/viewDidChangeEffectiveAppearance()",
                "doc://com.apple.appkit/documentation/AppKit/NSView/viewDidChangeBackingProperties()"
              ],
              "title": "Responding to Appearance Changes"
            },
            {
              "anchor": "Getting-the-Vibrancy-Setting",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/allowsVibrancy"
              ],
              "title": "Getting the Vibrancy Setting"
            },
            {
              "anchor": "Drawing-the-Focus-Ring",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/focusRingType",
                "doc://com.apple.appkit/documentation/AppKit/NSView/focusRingMaskBounds",
                "doc://com.apple.appkit/documentation/AppKit/NSView/drawFocusRingMask()",
                "doc://com.apple.appkit/documentation/AppKit/NSView/noteFocusRingMaskChanged()",
                "doc://com.apple.appkit/documentation/AppKit/NSView/setKeyboardFocusRingNeedsDisplay(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/defaultFocusRingType"
              ],
              "title": "Drawing the Focus Ring"
            },
            {
              "anchor": "Displaying-a-Find-Indicator",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/isDrawingFindIndicator"
              ],
              "title": "Displaying a Find Indicator"
            },
            {
              "anchor": "Configuring-a-Cells-Background",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/BackgroundStyle"
              ],
              "title": "Configuring a Cell’s Background"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-view",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/view-hierarchy",
                "doc://com.apple.appkit/documentation/AppKit/view-coordinates",
                "doc://com.apple.appkit/documentation/AppKit/core-animation-support",
                "doc://com.apple.appkit/documentation/AppKit/related-ui"
              ],
              "title": "Configuring the view"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1isDrawingFindIndicator/title",
          "value": "drawingFindIndicator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1isDrawingFindIndicator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "drawingFindIndicator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1BackgroundStyle/title",
          "value": "NSBackgroundStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1BackgroundStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBackgroundStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1BackgroundStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBackgroundStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1viewDidChangeEffectiveAppearance()/title",
          "value": "viewDidChangeEffectiveAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1viewDidChangeEffectiveAppearance()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "viewDidChangeEffectiveAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1focusRingMaskBounds/title",
          "value": "focusRingMaskBounds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1focusRingMaskBounds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "focusRingMaskBounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1drawFocusRingMask()/title",
          "value": "drawFocusRingMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1drawFocusRingMask()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawFocusRingMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1defaultFocusRingType/title",
          "value": "defaultFocusRingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1defaultFocusRingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultFocusRingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1focusRingType/title",
          "value": "focusRingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1focusRingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "focusRingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1isHiddenOrHasHiddenAncestor/title",
          "value": "hiddenOrHasHiddenAncestor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1isHiddenOrHasHiddenAncestor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hiddenOrHasHiddenAncestor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1viewDidChangeBackingProperties()/title",
          "value": "viewDidChangeBackingProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1viewDidChangeBackingProperties()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "viewDidChangeBackingProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1isHidden/title",
          "value": "hidden"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1isHidden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hidden"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1viewDidUnhide()/title",
          "value": "viewDidUnhide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1viewDidUnhide()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "viewDidUnhide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1allowsVibrancy/title",
          "value": "allowsVibrancy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1allowsVibrancy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsVibrancy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title",
          "value": "NSView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1setKeyboardFocusRingNeedsDisplay(_:)/title",
          "value": "setKeyboardFocusRingNeedsDisplayInRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1setKeyboardFocusRingNeedsDisplay(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setKeyboardFocusRingNeedsDisplayInRect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1noteFocusRingMaskChanged()/title",
          "value": "noteFocusRingMaskChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1noteFocusRingMaskChanged()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "noteFocusRingMaskChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1viewDidHide()/title",
          "value": "viewDidHide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1viewDidHide()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "viewDidHide"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsview-appearance"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsview-appearance"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
