{
  "abstract": [
    {
      "text": "Create a printable version of your view’s content and handle pagination and printer-related behaviors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
        "doc://com.apple.appkit/documentation/AppKit/NSView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/nsview-printing"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Printing"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/appkit/nsview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/adjustPageHeightNew(_:top:bottom:limit:)": {
      "abstract": [
        {
          "text": "Overridden by subclasses to adjust page height during automatic pagination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjustPageHeightNew"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "top"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "bottom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "limit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/adjustPageHeightNew(_:top:bottom:limit:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "adjustPageHeightNew:top:bottom:limit:"
        }
      ],
      "role": "symbol",
      "title": "adjustPageHeightNew(_:top:bottom:limit:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/adjustpageheightnew(_:top:bottom:limit:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/adjustPageWidthNew(_:left:right:limit:)": {
      "abstract": [
        {
          "text": "Overridden by subclasses to adjust page width during automatic pagination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjustPageWidthNew"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "left"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "right"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "limit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/adjustPageWidthNew(_:left:right:limit:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "adjustPageWidthNew:left:right:limit:"
        }
      ],
      "role": "symbol",
      "title": "adjustPageWidthNew(_:left:right:limit:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/adjustpagewidthnew(_:left:right:limit:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/beginDocument()": {
      "abstract": [
        {
          "text": "Invoked at the beginning of the printing session, this method sets up the current graphics context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginDocument"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/beginDocument()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginDocument"
        }
      ],
      "role": "symbol",
      "title": "beginDocument()",
      "type": "topic",
      "url": "/documentation/appkit/nsview/begindocument()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/beginPage(in:atPlacement:)": {
      "abstract": [
        {
          "text": "Called at the beginning of each page, this method sets up the coordinate system so that a region inside the view’s bounds is translated to a specified location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginPage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "atPlacement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/beginPage(in:atPlacement:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginPageInRect:atPlacement:"
        }
      ],
      "role": "symbol",
      "title": "beginPage(in:atPlacement:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/beginpage(in:atplacement:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/dataWithEPS(inside:)": {
      "abstract": [
        {
          "text": "Returns EPS data that draws the region of the view within a specified rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataWithEPS"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "inside"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/dataWithEPS(inside:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dataWithEPSInsideRect:"
        }
      ],
      "role": "symbol",
      "title": "dataWithEPS(inside:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/datawitheps(inside:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/dataWithPDF(inside:)": {
      "abstract": [
        {
          "text": "Returns PDF data that draws the region of the view within a specified rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataWithPDF"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "inside"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/dataWithPDF(inside:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dataWithPDFInsideRect:"
        }
      ],
      "role": "symbol",
      "title": "dataWithPDF(inside:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/datawithpdf(inside:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/drawPageBorder(with:)": {
      "abstract": [
        {
          "text": "Allows applications that use the AppKit pagination facility to draw additional marks on each logical page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawPageBorder"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/drawPageBorder(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawPageBorderWithSize:"
        }
      ],
      "role": "symbol",
      "title": "drawPageBorder(with:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/drawpageborder(with:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/drawSheetBorder(with:)": {
      "abstract": [
        {
          "text": "Allows applications that use the AppKit pagination facility to draw additional marks on each printed sheet.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawSheetBorder"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/drawSheetBorder(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawSheetBorderWithSize:"
        }
      ],
      "role": "symbol",
      "title": "drawSheetBorder(with:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/drawsheetborder(with:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/endDocument()": {
      "abstract": [
        {
          "text": "This method is invoked at the end of the printing session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endDocument"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/endDocument()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endDocument"
        }
      ],
      "role": "symbol",
      "title": "endDocument()",
      "type": "topic",
      "url": "/documentation/appkit/nsview/enddocument()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/endPage()": {
      "abstract": [
        {
          "text": "Writes the end of a conforming page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endPage"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/endPage()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endPage"
        }
      ],
      "role": "symbol",
      "title": "endPage()",
      "type": "topic",
      "url": "/documentation/appkit/nsview/endpage()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/heightAdjustLimit": {
      "abstract": [
        {
          "text": "The fraction of the page that can be pushed onto the next page during automatic pagination to prevent items such as lines of text from being divided across pages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "heightAdjustLimit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/heightAdjustLimit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "heightAdjustLimit"
        }
      ],
      "role": "symbol",
      "title": "heightAdjustLimit",
      "type": "topic",
      "url": "/documentation/appkit/nsview/heightadjustlimit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/knowsPageRange(_:)": {
      "abstract": [
        {
          "text": "Returns ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/swift/true",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " if the view handles page boundaries, ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/swift/false",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " otherwise.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "knowsPageRange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRangePointer",
          "text": "NSRangePointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/knowsPageRange(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "knowsPageRange:"
        }
      ],
      "role": "symbol",
      "title": "knowsPageRange(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/knowspagerange(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/locationOfPrintRect(_:)": {
      "abstract": [
        {
          "text": "Invoked by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/printView(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to determine the location of the region of the view being printed on the physical page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locationOfPrintRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/locationOfPrintRect(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "locationOfPrintRect:"
        }
      ],
      "role": "symbol",
      "title": "locationOfPrintRect(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/locationofprintrect(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/pageFooter": {
      "abstract": [
        {
          "text": "A default footer string that includes the current page number and page count.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageFooter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/pageFooter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pageFooter"
        }
      ],
      "role": "symbol",
      "title": "pageFooter",
      "type": "topic",
      "url": "/documentation/appkit/nsview/pagefooter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/pageHeader": {
      "abstract": [
        {
          "text": "A default header string that includes the print job title and date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageHeader"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/pageHeader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pageHeader"
        }
      ],
      "role": "symbol",
      "title": "pageHeader",
      "type": "topic",
      "url": "/documentation/appkit/nsview/pageheader"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/printJobTitle": {
      "abstract": [
        {
          "text": "The view’s print job title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printJobTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/printJobTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printJobTitle"
        }
      ],
      "role": "symbol",
      "title": "printJobTitle",
      "type": "topic",
      "url": "/documentation/appkit/nsview/printjobtitle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/printView(_:)": {
      "abstract": [
        {
          "text": "This action method opens the Print panel, and if the user chooses an option other than canceling, prints the view and all its subviews to the device specified in the Print panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/printView(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "print:"
        }
      ],
      "role": "symbol",
      "title": "printView(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/printview(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/rectForPage(_:)": {
      "abstract": [
        {
          "text": "Implemented by subclasses to determine the portion of the view to be printed for the specified page number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rectForPage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/rectForPage(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rectForPage:"
        }
      ],
      "role": "symbol",
      "title": "rectForPage(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/rectforpage(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/widthAdjustLimit": {
      "abstract": [
        {
          "text": "The fraction of the page that can be pushed onto the next page during automatic pagination to prevent items such as small images or text columns from being divided across pages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widthAdjustLimit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/widthAdjustLimit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "widthAdjustLimit"
        }
      ],
      "role": "symbol",
      "title": "widthAdjustLimit",
      "type": "topic",
      "url": "/documentation/appkit/nsview/widthadjustlimit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/writeEPS(inside:to:)": {
      "abstract": [
        {
          "text": "Writes EPS data that draws the region of the view within a specified rectangle onto a pasteboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeEPS"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "inside"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/writeEPS(inside:to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writeEPSInsideRect:toPasteboard:"
        }
      ],
      "role": "symbol",
      "title": "writeEPS(inside:to:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/writeeps(inside:to:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/writePDF(inside:to:)": {
      "abstract": [
        {
          "text": "Writes PDF data that draws the region of the view within a specified rectangle onto a pasteboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writePDF"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "inside"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/writePDF(inside:to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writePDFInsideRect:toPasteboard:"
        }
      ],
      "role": "symbol",
      "title": "writePDF(inside:to:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/writepdf(inside:to:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/layout": {
      "abstract": [
        {
          "text": "Specify the size and position your view relative to other nearby views using rules that update your view hierarchy automatically.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/layout",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layout",
      "type": "topic",
      "url": "/documentation/appkit/layout"
    },
    "doc://com.apple.appkit/documentation/AppKit/nsview-drawing": {
      "abstract": [
        {
          "text": "Draw the content of custom views and update that content when the view’s size or appearance changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nsview-drawing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Drawing",
      "type": "topic",
      "url": "/documentation/appkit/nsview-drawing"
    },
    "doc://com.apple.appkit/documentation/AppKit/views-and-controls": {
      "abstract": [
        {
          "text": "Present your content onscreen and handle user input and events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Views and Controls",
      "type": "topic",
      "url": "/documentation/appkit/views-and-controls"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-the-views-content",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/layout",
        "doc://com.apple.appkit/documentation/AppKit/nsview-drawing"
      ],
      "title": "Managing the view’s content"
    }
  ],
  "topicSections": [
    {
      "anchor": "Printing-the-Views-Content",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/printView(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/beginPage(in:atPlacement:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/dataWithEPS(inside:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/dataWithPDF(inside:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/printJobTitle",
        "doc://com.apple.appkit/documentation/AppKit/NSView/pageHeader",
        "doc://com.apple.appkit/documentation/AppKit/NSView/pageFooter",
        "doc://com.apple.appkit/documentation/AppKit/NSView/writeEPS(inside:to:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/writePDF(inside:to:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/drawPageBorder(with:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/drawSheetBorder(with:)"
      ],
      "title": "Printing the View’s Content"
    },
    {
      "anchor": "Handling-Pagination",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/heightAdjustLimit",
        "doc://com.apple.appkit/documentation/AppKit/NSView/widthAdjustLimit",
        "doc://com.apple.appkit/documentation/AppKit/NSView/adjustPageWidthNew(_:left:right:limit:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/adjustPageHeightNew(_:top:bottom:limit:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/knowsPageRange(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/rectForPage(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/locationOfPrintRect(_:)"
      ],
      "title": "Handling Pagination"
    },
    {
      "anchor": "Writing-Conforming-Rendering-Instructions",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/beginDocument()",
        "doc://com.apple.appkit/documentation/AppKit/NSView/endDocument()",
        "doc://com.apple.appkit/documentation/AppKit/NSView/endPage()"
      ],
      "title": "Writing Conforming Rendering Instructions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Printing-the-Views-Content",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/printView(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/beginPage(in:atPlacement:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/dataWithEPS(inside:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/dataWithPDF(inside:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/printJobTitle",
                "doc://com.apple.appkit/documentation/AppKit/NSView/pageHeader",
                "doc://com.apple.appkit/documentation/AppKit/NSView/pageFooter",
                "doc://com.apple.appkit/documentation/AppKit/NSView/writeEPS(inside:to:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/writePDF(inside:to:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/drawPageBorder(with:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/drawSheetBorder(with:)"
              ],
              "title": "Printing the View’s Content"
            },
            {
              "anchor": "Handling-Pagination",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/heightAdjustLimit",
                "doc://com.apple.appkit/documentation/AppKit/NSView/widthAdjustLimit",
                "doc://com.apple.appkit/documentation/AppKit/NSView/adjustPageWidthNew(_:left:right:limit:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/adjustPageHeightNew(_:top:bottom:limit:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/knowsPageRange(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/rectForPage(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/locationOfPrintRect(_:)"
              ],
              "title": "Handling Pagination"
            },
            {
              "anchor": "Writing-Conforming-Rendering-Instructions",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/beginDocument()",
                "doc://com.apple.appkit/documentation/AppKit/NSView/endDocument()",
                "doc://com.apple.appkit/documentation/AppKit/NSView/endPage()"
              ],
              "title": "Writing Conforming Rendering Instructions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-the-views-content",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/layout",
                "doc://com.apple.appkit/documentation/AppKit/nsview-drawing"
              ],
              "title": "Managing the view’s content"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1widthAdjustLimit/title",
          "value": "widthAdjustLimit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1widthAdjustLimit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "widthAdjustLimit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1dataWithEPS(inside:)/title",
          "value": "dataWithEPSInsideRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1dataWithEPS(inside:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dataWithEPSInsideRect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1locationOfPrintRect(_:)/title",
          "value": "locationOfPrintRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1locationOfPrintRect(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "locationOfPrintRect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1writeEPS(inside:to:)/title",
          "value": "writeEPSInsideRect:toPasteboard:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1writeEPS(inside:to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writeEPSInsideRect:toPasteboard:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title",
          "value": "NSView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1printJobTitle/title",
          "value": "printJobTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1printJobTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "printJobTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1drawSheetBorder(with:)/title",
          "value": "drawSheetBorderWithSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1drawSheetBorder(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawSheetBorderWithSize:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1writePDF(inside:to:)/title",
          "value": "writePDFInsideRect:toPasteboard:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1writePDF(inside:to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writePDFInsideRect:toPasteboard:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1pageHeader/title",
          "value": "pageHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1pageHeader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pageHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1printView(_:)/title",
          "value": "print:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1printView(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "print:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1dataWithPDF(inside:)/title",
          "value": "dataWithPDFInsideRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1dataWithPDF(inside:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dataWithPDFInsideRect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1knowsPageRange(_:)/title",
          "value": "knowsPageRange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1knowsPageRange(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "knowsPageRange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1adjustPageWidthNew(_:left:right:limit:)/title",
          "value": "adjustPageWidthNew:left:right:limit:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1adjustPageWidthNew(_:left:right:limit:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "adjustPageWidthNew:left:right:limit:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rectForPage(_:)/title",
          "value": "rectForPage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rectForPage(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rectForPage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1heightAdjustLimit/title",
          "value": "heightAdjustLimit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1heightAdjustLimit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "heightAdjustLimit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1beginPage(in:atPlacement:)/title",
          "value": "beginPageInRect:atPlacement:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1beginPage(in:atPlacement:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginPageInRect:atPlacement:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1beginDocument()/title",
          "value": "beginDocument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1beginDocument()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1endPage()/title",
          "value": "endPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1endPage()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "endPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1adjustPageHeightNew(_:top:bottom:limit:)/title",
          "value": "adjustPageHeightNew:top:bottom:limit:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1adjustPageHeightNew(_:top:bottom:limit:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "adjustPageHeightNew:top:bottom:limit:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1endDocument()/title",
          "value": "endDocument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1endDocument()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "endDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1drawPageBorder(with:)/title",
          "value": "drawPageBorderWithSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1drawPageBorder(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawPageBorderWithSize:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1pageFooter/title",
          "value": "pageFooter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1pageFooter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pageFooter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsview-printing"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsview-printing"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
