{
  "abstract": [
    {
      "text": "An alert used to warn the user about a current or impending event. The purpose is more than informational but not critical. This is the default alert style.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSWarningAlertStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSWarningAlertStyle",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSWarningAlertStyle"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSWarningAlertStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.12",
        "introducedAt": "10.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSWarningAlertStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAlert/Style",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSAlertStyle",
              "text": "NSAlertStyle"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSWarningAlertStyle"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAlert/Style": {
      "abstract": [
        {
          "text": "The set of alert styles to style alerts in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Style"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAlert/Style",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Style"
        }
      ],
      "role": "symbol",
      "title": "NSAlert.Style",
      "type": "topic",
      "url": "/documentation/appkit/nsalert/style"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCriticalAlertStyle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCriticalAlertStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCriticalAlertStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCriticalAlertStyle",
      "type": "topic",
      "url": "/documentation/appkit/nscriticalalertstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInformationalAlertStyle": {
      "abstract": [
        {
          "text": "An alert used to inform the user about a current or impending event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSInformationalAlertStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInformationalAlertStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInformationalAlertStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsinformationalalertstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWarningAlertStyle": {
      "abstract": [
        {
          "text": "An alert used to warn the user about a current or impending event. The purpose is more than informational but not critical. This is the default alert style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSWarningAlertStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWarningAlertStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSWarningAlertStyle",
      "type": "topic",
      "url": "/documentation/appkit/nswarningalertstyle"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Symbols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCriticalAlertStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSInformationalAlertStyle"
      ],
      "title": "Deprecated Symbols"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAlert~1Style/title",
          "value": "NSAlertStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAlert~1Style/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAlertStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAlert~1Style/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAlertStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nswarningalertstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
