{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSWindowSharingErrorMinimum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@NSTextReadInapplicableDocumentTypeError@NSWindowSharingErrorMinimum",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSWindowSharingErrorMinimum"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSWindowSharingErrorMinimum"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSWindowSharingErrorMinimum"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSWindowSharingErrorMinimum"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontAssetDownloadError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFontAssetDownloadError"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontAssetDownloadError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFontAssetDownloadError",
      "type": "topic",
      "url": "/documentation/appkit/nsfontassetdownloaderror"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontErrorMaximum": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFontErrorMaximum"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontErrorMaximum",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFontErrorMaximum",
      "type": "topic",
      "url": "/documentation/appkit/nsfonterrormaximum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontErrorMinimum": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFontErrorMinimum"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontErrorMinimum",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFontErrorMinimum",
      "type": "topic",
      "url": "/documentation/appkit/nsfonterrorminimum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSServiceApplicationLaunchFailedError": {
      "abstract": [
        {
          "text": "The service providing application could not be launched.  This will typically contain an underlying error with an Launch Services error code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSServiceApplicationLaunchFailedError"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSServiceApplicationLaunchFailedError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSServiceApplicationLaunchFailedError",
      "type": "topic",
      "url": "/documentation/appkit/nsserviceapplicationlaunchfailederror"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSServiceApplicationNotFoundError": {
      "abstract": [
        {
          "text": "The service provider could not be found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSServiceApplicationNotFoundError"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSServiceApplicationNotFoundError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSServiceApplicationNotFoundError",
      "type": "topic",
      "url": "/documentation/appkit/nsserviceapplicationnotfounderror"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSServiceErrorMaximum": {
      "abstract": [
        {
          "text": "Inclusive service error range, for checking future error codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSServiceErrorMaximum"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSServiceErrorMaximum",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSServiceErrorMaximum",
      "type": "topic",
      "url": "/documentation/appkit/nsserviceerrormaximum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSServiceErrorMinimum": {
      "abstract": [
        {
          "text": "Inclusive service error range, for checking future error codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSServiceErrorMinimum"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSServiceErrorMinimum",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSServiceErrorMinimum",
      "type": "topic",
      "url": "/documentation/appkit/nsserviceerrorminimum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSServiceInvalidPasteboardDataError": {
      "abstract": [
        {
          "text": "The service providing app did not return a pasteboard with any of the promised types, or we couldn’t write the data from the pasteboard to the object receiving the returned data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSServiceInvalidPasteboardDataError"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSServiceInvalidPasteboardDataError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSServiceInvalidPasteboardDataError",
      "type": "topic",
      "url": "/documentation/appkit/nsserviceinvalidpasteboarddataerror"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSServiceMalformedServiceDictionaryError": {
      "abstract": [
        {
          "text": "The service dictionary did not contain the necessary keys.  Messages will typically be logged to the console giving more details.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSServiceMalformedServiceDictionaryError"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSServiceMalformedServiceDictionaryError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSServiceMalformedServiceDictionaryError",
      "type": "topic",
      "url": "/documentation/appkit/nsservicemalformedservicedictionaryerror"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSServiceMiscellaneousError": {
      "abstract": [
        {
          "text": "Other errors, representing programmatic mistakes in the service consuming application.  These show a generic error message to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSServiceMiscellaneousError"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSServiceMiscellaneousError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSServiceMiscellaneousError",
      "type": "topic",
      "url": "/documentation/appkit/nsservicemiscellaneouserror"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSServiceRequestTimedOutError": {
      "abstract": [
        {
          "text": "The service providing application did not open its service listening port in time, or the app didn’t respond to the request in time; see the Console log to figure out which (the errors are typically reported the same way to the user).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSServiceRequestTimedOutError"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSServiceRequestTimedOutError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSServiceRequestTimedOutError",
      "type": "topic",
      "url": "/documentation/appkit/nsservicerequesttimedouterror"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextReadInapplicableDocumentTypeError": {
      "abstract": [
        {
          "text": "Indicates a problem reading data with the specified format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextReadInapplicableDocumentTypeError"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextReadInapplicableDocumentTypeError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextReadInapplicableDocumentTypeError",
      "type": "topic",
      "url": "/documentation/appkit/nstextreadinapplicabledocumenttypeerror"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextReadWriteErrorMaximum": {
      "abstract": [
        {
          "text": "The end of a range of error codes reserved for future use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextReadWriteErrorMaximum"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextReadWriteErrorMaximum",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextReadWriteErrorMaximum",
      "type": "topic",
      "url": "/documentation/appkit/nstextreadwriteerrormaximum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextReadWriteErrorMinimum": {
      "abstract": [
        {
          "text": "The beginning of a range of error codes reserved for future use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextReadWriteErrorMinimum"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextReadWriteErrorMinimum",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextReadWriteErrorMinimum",
      "type": "topic",
      "url": "/documentation/appkit/nstextreadwriteerrorminimum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextWriteInapplicableDocumentTypeError": {
      "abstract": [
        {
          "text": "Indicates a problem writing data of the specified format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextWriteInapplicableDocumentTypeError"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextWriteInapplicableDocumentTypeError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextWriteInapplicableDocumentTypeError",
      "type": "topic",
      "url": "/documentation/appkit/nstextwriteinapplicabledocumenttypeerror"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindowSharingErrorMaximum": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWindowSharingErrorMaximum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindowSharingErrorMaximum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowSharingErrorMaximum"
        }
      ],
      "role": "symbol",
      "title": "NSWindowSharingErrorMaximum",
      "type": "topic",
      "url": "/documentation/appkit/nswindowsharingerrormaximum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindowSharingErrorMinimum": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWindowSharingErrorMinimum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindowSharingErrorMinimum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowSharingErrorMinimum"
        }
      ],
      "role": "symbol",
      "title": "NSWindowSharingErrorMinimum",
      "type": "topic",
      "url": "/documentation/appkit/nswindowsharingerrorminimum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindowSharingRequestAlreadyRequested": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWindowSharingRequestAlreadyRequested"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindowSharingRequestAlreadyRequested",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowSharingRequestAlreadyRequested"
        }
      ],
      "role": "symbol",
      "title": "NSWindowSharingRequestAlreadyRequested",
      "type": "topic",
      "url": "/documentation/appkit/nswindowsharingrequestalreadyrequested"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindowSharingRequestNoEligibleSession": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWindowSharingRequestNoEligibleSession"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindowSharingRequestNoEligibleSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowSharingRequestNoEligibleSession"
        }
      ],
      "role": "symbol",
      "title": "NSWindowSharingRequestNoEligibleSession",
      "type": "topic",
      "url": "/documentation/appkit/nswindowsharingrequestnoeligiblesession"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindowSharingRequestUnspecifiedError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWindowSharingRequestUnspecifiedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindowSharingRequestUnspecifiedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowSharingRequestUnspecifiedError"
        }
      ],
      "role": "symbol",
      "title": "NSWindowSharingRequestUnspecifiedError",
      "type": "topic",
      "url": "/documentation/appkit/nswindowsharingrequestunspecifiederror"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspaceAuthorizationInvalidError": {
      "abstract": [
        {
          "text": "The provided workspace authorization credentials expired or are invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWorkspaceAuthorizationInvalidError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspaceAuthorizationInvalidError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceAuthorizationInvalidError"
        }
      ],
      "role": "symbol",
      "title": "NSWorkspaceAuthorizationInvalidError",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspaceauthorizationinvaliderror"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspaceErrorMaximum": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWorkspaceErrorMaximum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspaceErrorMaximum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceErrorMaximum"
        }
      ],
      "role": "symbol",
      "title": "NSWorkspaceErrorMaximum",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspaceerrormaximum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWorkspaceErrorMinimum": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWorkspaceErrorMinimum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWorkspaceErrorMinimum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWorkspaceErrorMinimum"
        }
      ],
      "role": "symbol",
      "title": "NSWorkspaceErrorMinimum",
      "type": "topic",
      "url": "/documentation/appkit/nsworkspaceerrorminimum"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspaceAuthorizationInvalidError",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspaceErrorMaximum",
        "doc://com.apple.appkit/documentation/AppKit/NSWorkspaceErrorMinimum",
        "doc://com.apple.appkit/documentation/AppKit/NSWindowSharingErrorMaximum",
        "doc://com.apple.appkit/documentation/AppKit/NSWindowSharingRequestAlreadyRequested",
        "doc://com.apple.appkit/documentation/AppKit/NSWindowSharingRequestNoEligibleSession",
        "doc://com.apple.appkit/documentation/AppKit/NSWindowSharingRequestUnspecifiedError"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.3",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSWindowSharingErrorMinimum"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowSharingErrorMinimum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFontAssetDownloadError",
                "doc://com.apple.appkit/documentation/AppKit/NSFontErrorMaximum",
                "doc://com.apple.appkit/documentation/AppKit/NSFontErrorMinimum",
                "doc://com.apple.appkit/documentation/AppKit/NSTextReadInapplicableDocumentTypeError",
                "doc://com.apple.appkit/documentation/AppKit/NSTextWriteInapplicableDocumentTypeError",
                "doc://com.apple.appkit/documentation/AppKit/NSTextReadWriteErrorMinimum",
                "doc://com.apple.appkit/documentation/AppKit/NSTextReadWriteErrorMaximum",
                "doc://com.apple.appkit/documentation/AppKit/NSServiceApplicationLaunchFailedError",
                "doc://com.apple.appkit/documentation/AppKit/NSServiceApplicationNotFoundError",
                "doc://com.apple.appkit/documentation/AppKit/NSServiceErrorMaximum",
                "doc://com.apple.appkit/documentation/AppKit/NSServiceErrorMinimum",
                "doc://com.apple.appkit/documentation/AppKit/NSServiceInvalidPasteboardDataError",
                "doc://com.apple.appkit/documentation/AppKit/NSServiceMalformedServiceDictionaryError",
                "doc://com.apple.appkit/documentation/AppKit/NSServiceMiscellaneousError",
                "doc://com.apple.appkit/documentation/AppKit/NSServiceRequestTimedOutError"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSWindowSharingErrorMinimum"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowSharingRequestNoEligibleSession/title",
          "value": "NSWindowSharingRequestNoEligibleSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowSharingRequestNoEligibleSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowSharingRequestNoEligibleSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowSharingRequestAlreadyRequested/title",
          "value": "NSWindowSharingRequestAlreadyRequested"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowSharingRequestAlreadyRequested/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowSharingRequestAlreadyRequested"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspaceAuthorizationInvalidError/title",
          "value": "NSWorkspaceAuthorizationInvalidError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspaceAuthorizationInvalidError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceAuthorizationInvalidError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowSharingErrorMinimum/title",
          "value": "NSWindowSharingErrorMinimum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowSharingErrorMinimum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowSharingErrorMinimum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspaceErrorMaximum/title",
          "value": "NSWorkspaceErrorMaximum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspaceErrorMaximum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceErrorMaximum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowSharingRequestUnspecifiedError/title",
          "value": "NSWindowSharingRequestUnspecifiedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowSharingRequestUnspecifiedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowSharingRequestUnspecifiedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspaceErrorMinimum/title",
          "value": "NSWorkspaceErrorMinimum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspaceErrorMinimum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWorkspaceErrorMinimum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowSharingErrorMaximum/title",
          "value": "NSWindowSharingErrorMaximum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowSharingErrorMaximum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowSharingErrorMaximum"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nswindowsharingerrorminimum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nswindowsharingerrorminimum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
