{
  "abstract": [
    {
      "text": "A tab associated with a window that is part of a tabbing group.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSWindowTab"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSWindowTab",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSWindowTab"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSWindowTab"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSWindowTab"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSWindowTab"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindowTab",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " describes the way a window displays as part of a tabbed window group. The properties of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindowTab",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " are configurable at any time, but only take effect when the associated ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " displays in a tab.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "AppKit automatically creates an instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindowTab",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for each ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". You can access a window’s tab object using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/tab",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPanel": {
      "abstract": [
        {
          "text": "A special kind of window that typically performs a function that is auxiliary to the main window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPanel"
        }
      ],
      "role": "symbol",
      "title": "NSPanel",
      "type": "topic",
      "url": "/documentation/appkit/nspanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow": {
      "abstract": [
        {
          "text": "A window that an app displays on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "role": "symbol",
      "title": "NSWindow",
      "type": "topic",
      "url": "/documentation/appkit/nswindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/tab": {
      "abstract": [
        {
          "text": "An object that represents information about a window when it displays as a tab.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tab"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindowTab",
          "text": "NSWindowTab"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/tab",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tab"
        }
      ],
      "role": "symbol",
      "title": "tab",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/tab"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/tabbingIdentifier-swift.property": {
      "abstract": [
        {
          "text": "A value that allows a group of related windows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabbingIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSWindowTabbingIdentifier",
          "text": "TabbingIdentifier"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/tabbingIdentifier-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabbingIdentifier"
        }
      ],
      "role": "symbol",
      "title": "tabbingIdentifier",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/tabbingidentifier-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindowDelegate": {
      "abstract": [
        {
          "text": "A set of optional methods that a window’s delegate can implement to respond to events, such as window resizing, moving, exposing, and minimizing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWindowDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindowDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSWindowDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nswindowdelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindowTab": {
      "abstract": [
        {
          "text": "A tab associated with a window that is part of a tabbing group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWindowTab"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindowTab",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowTab"
        }
      ],
      "role": "symbol",
      "title": "NSWindowTab",
      "type": "topic",
      "url": "/documentation/appkit/nswindowtab"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindowTab/accessoryView": {
      "abstract": [
        {
          "text": "An optional accessory view for the tab.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessoryView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindowTab/accessoryView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessoryView"
        }
      ],
      "role": "symbol",
      "title": "accessoryView",
      "type": "topic",
      "url": "/documentation/appkit/nswindowtab/accessoryview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindowTab/attributedTitle": {
      "abstract": [
        {
          "text": "The title for the window tab, specified as an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributedTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindowTab/attributedTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attributedTitle"
        }
      ],
      "role": "symbol",
      "title": "attributedTitle",
      "type": "topic",
      "url": "/documentation/appkit/nswindowtab/attributedtitle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindowTab/title": {
      "abstract": [
        {
          "text": "The title for the window tab.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindowTab/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/appkit/nswindowtab/title"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindowTab/toolTip": {
      "abstract": [
        {
          "text": "The tooltip for this window tab.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toolTip"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindowTab/toolTip",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toolTip"
        }
      ],
      "role": "symbol",
      "title": "toolTip",
      "type": "topic",
      "url": "/documentation/appkit/nswindowtab/tooltip"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindowTabGroup": {
      "abstract": [
        {
          "text": "A group of windows that display together as a single tabbed window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWindowTabGroup"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindowTabGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowTabGroup"
        }
      ],
      "role": "symbol",
      "title": "NSWindowTabGroup",
      "type": "topic",
      "url": "/documentation/appkit/nswindowtabgroup"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/tabbingIdentifier-swift.property"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Windows",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWindow",
        "doc://com.apple.appkit/documentation/AppKit/NSPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSWindowDelegate",
        "doc://com.apple.appkit/documentation/AppKit/NSWindowTabGroup"
      ],
      "title": "Windows"
    }
  ],
  "topicSections": [
    {
      "anchor": "Customizing-the-Title",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWindowTab/title",
        "doc://com.apple.appkit/documentation/AppKit/NSWindowTab/attributedTitle"
      ],
      "title": "Customizing the Title"
    },
    {
      "anchor": "Customizing-the-Tooltip",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWindowTab/toolTip"
      ],
      "title": "Customizing the Tooltip"
    },
    {
      "anchor": "Adding-an-Accessory-View",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWindowTab/accessoryView"
      ],
      "title": "Adding an Accessory View"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSWindowTab"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowTab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowTab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Customizing-the-Title",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWindowTab/title",
                "doc://com.apple.appkit/documentation/AppKit/NSWindowTab/attributedTitle"
              ],
              "title": "Customizing the Title"
            },
            {
              "anchor": "Customizing-the-Tooltip",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWindowTab/toolTip"
              ],
              "title": "Customizing the Tooltip"
            },
            {
              "anchor": "Adding-an-Accessory-View",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWindowTab/accessoryView"
              ],
              "title": "Adding an Accessory View"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/tabbingIdentifier-swift.property"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Windows",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWindow",
                "doc://com.apple.appkit/documentation/AppKit/NSPanel",
                "doc://com.apple.appkit/documentation/AppKit/NSWindowDelegate",
                "doc://com.apple.appkit/documentation/AppKit/NSWindowTabGroup"
              ],
              "title": "Windows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSWindowTab"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowTab~1attributedTitle/title",
          "value": "attributedTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowTab~1attributedTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attributedTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1tabbingIdentifier-swift.property/title",
          "value": "tabbingIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1tabbingIdentifier-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tabbingIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title",
          "value": "NSWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1tab/title",
          "value": "tab"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1tab/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowTabGroup/title",
          "value": "NSWindowTabGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowTabGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowTabGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowTabGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowTabGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowTab~1title/title",
          "value": "title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowTab~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowDelegate/title",
          "value": "NSWindowDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowTab~1toolTip/title",
          "value": "toolTip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowTab~1toolTip/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "toolTip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowTab/title",
          "value": "NSWindowTab"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowTab/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowTab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowTab/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowTab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPanel/title",
          "value": "NSPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowTab~1accessoryView/title",
          "value": "accessoryView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindowTab~1accessoryView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "accessoryView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nswindowtab"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nswindowtab"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
