{
  "abstract": [
    {
      "text": "Review unsupported symbols and their replacements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/windows-panels-and-screens",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/nswindow-deprecated-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated Symbols"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow": {
      "abstract": [
        {
          "text": "A window that an app displays on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "role": "symbol",
      "title": "NSWindow",
      "type": "topic",
      "url": "/documentation/appkit/nswindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/BackingLocation-swift.enum": {
      "abstract": [
        {
          "text": "The following constants and the related data type represent a window’s possible backing locations.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BackingLocation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/BackingLocation-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BackingLocation"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.BackingLocation",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/backinglocation-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/backingLocation-swift.property": {
      "abstract": [
        {
          "text": "The location of the window’s backing store.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backingLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowBackingLocation",
          "text": "BackingLocation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/backingLocation-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backingLocation"
        }
      ],
      "role": "symbol",
      "title": "backingLocation",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/backinglocation-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/cacheImage(in:)": {
      "abstract": [
        {
          "text": "Stores the window’s raster image from a given rectangle expressed in the window’s base coordinate system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cacheImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/cacheImage(in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cacheImageInRect:"
        }
      ],
      "role": "symbol",
      "title": "cacheImage(in:)",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/cacheimage(in:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/canStoreColor()": {
      "abstract": [
        {
          "text": "Indicates whether the window has a depth limit that allows it to store color values.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canStoreColor"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/canStoreColor()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canStoreColor"
        }
      ],
      "role": "symbol",
      "title": "canStoreColor()",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/canstorecolor()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/convertBaseToScreen:": {
      "abstract": [
        {
          "text": "Converts a given point from the window’s base coordinate system to the screen coordinate system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "convertBaseToScreen:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/convertBaseToScreen:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertBaseToScreen:"
        }
      ],
      "role": "symbol",
      "title": "convertBaseToScreen:",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/convertbasetoscreen:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/convertScreenToBase:": {
      "abstract": [
        {
          "text": "Converts a given point from the screen coordinate system to the window’s base coordinate system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "convertScreenToBase:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/convertScreenToBase:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertScreenToBase:"
        }
      ],
      "role": "symbol",
      "title": "convertScreenToBase:",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/convertscreentobase:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/disableFlushing()": {
      "abstract": [
        {
          "text": "Disables the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/flush()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method for the window.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableFlushing"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/disableFlushing()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "disableFlushWindow"
        }
      ],
      "role": "symbol",
      "title": "disableFlushing()",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/disableflushing()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/discardCachedImage()": {
      "abstract": [
        {
          "text": "Discards all of the window’s cached image rectangles.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "discardCachedImage"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/discardCachedImage()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "discardCachedImage"
        }
      ],
      "role": "symbol",
      "title": "discardCachedImage()",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/discardcachedimage()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/drawers": {
      "abstract": [
        {
          "text": "The collection of drawers associated with the window.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDrawer",
          "text": "NSDrawer"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/drawers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawers"
        }
      ],
      "role": "symbol",
      "title": "drawers",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/drawers"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/enableFlushing()": {
      "abstract": [
        {
          "text": "Reenables the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/flush()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method for the window after it was disabled through a previous ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/disableFlushing()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " message.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enableFlushing"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/enableFlushing()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enableFlushWindow"
        }
      ],
      "role": "symbol",
      "title": "enableFlushing()",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/enableflushing()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/flush()": {
      "abstract": [
        {
          "text": "Flushes the window’s offscreen buffer to the screen if the window is buffered and flushing is enabled.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flush"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/flush()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "flushWindow"
        }
      ],
      "role": "symbol",
      "title": "flush()",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/flush()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/flushIfNeeded()": {
      "abstract": [
        {
          "text": "Flushes the window’s offscreen buffer to the screen if flushing is enabled and if the last ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/flush()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " message had no effect because flushing was disabled.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flushIfNeeded"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/flushIfNeeded()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "flushWindowIfNeeded"
        }
      ],
      "role": "symbol",
      "title": "flushIfNeeded()",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/flushifneeded()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/gState()": {
      "abstract": [
        {
          "text": "Returns the window’s graphics state object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gState"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/gState()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gState"
        }
      ],
      "role": "symbol",
      "title": "gState()",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/gstate()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/graphicsContext": {
      "abstract": [
        {
          "text": "The graphics context associated with the window for the current thread.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "graphicsContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSGraphicsContext",
          "text": "NSGraphicsContext"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/graphicsContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "graphicsContext"
        }
      ],
      "role": "symbol",
      "title": "graphicsContext",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/graphicscontext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/init(windowRef:)": {
      "abstract": [
        {
          "text": "Returns a Cocoa window created from a Carbon window.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "windowRef"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/init(windowRef:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithWindowRef:"
        }
      ],
      "role": "symbol",
      "title": "init(windowRef:)",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/init(windowref:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/isAutodisplay": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the window automatically displays views that need to be displayed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAutodisplay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/isAutodisplay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "autodisplay"
        }
      ],
      "role": "symbol",
      "title": "isAutodisplay",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/isautodisplay"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/isFlushWindowDisabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the window’s flushing ability is disabled.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isFlushWindowDisabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/isFlushWindowDisabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "flushWindowDisabled"
        }
      ],
      "role": "symbol",
      "title": "isFlushWindowDisabled",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/isflushwindowdisabled"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/isOneShot": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the window device the window manages is freed when it’s removed from the screen list.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isOneShot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/isOneShot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "oneShot"
        }
      ],
      "role": "symbol",
      "title": "isOneShot",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/isoneshot"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/menuChanged(_:)": {
      "abstract": [
        {
          "text": "This method does nothing; it is here for backward compatibility.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "menuChanged"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMenu",
          "text": "NSMenu"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/menuChanged(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "menuChanged:"
        }
      ],
      "role": "symbol",
      "title": "menuChanged(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/menuchanged(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/preferredBackingLocation": {
      "abstract": [
        {
          "text": "A Boolean value that indicates the preferred location for the window’s backing store.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredBackingLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowBackingLocation",
          "text": "BackingLocation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/preferredBackingLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredBackingLocation"
        }
      ],
      "role": "symbol",
      "title": "preferredBackingLocation",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/preferredbackinglocation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/restoreCachedImage()": {
      "abstract": [
        {
          "text": "Splices the window’s cached image rectangles, if any, back into its raster image (and buffer if it has one), undoing the effect of any drawing performed within those areas since they were established using ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/cacheImage(in:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restoreCachedImage"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/restoreCachedImage()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "restoreCachedImage"
        }
      ],
      "role": "symbol",
      "title": "restoreCachedImage()",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/restorecachedimage()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/showsResizeIndicator": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the window’s resize indicator is visible.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsResizeIndicator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/showsResizeIndicator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showsResizeIndicator"
        }
      ],
      "role": "symbol",
      "title": "showsResizeIndicator",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/showsresizeindicator"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/useOptimizedDrawing(_:)": {
      "abstract": [
        {
          "text": "Specifies whether the window is to optimize focusing and drawing when displaying its views.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "useOptimizedDrawing"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/useOptimizedDrawing(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "useOptimizedDrawing:"
        }
      ],
      "role": "symbol",
      "title": "useOptimizedDrawing(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/useoptimizeddrawing(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/userSpaceScaleFactor": {
      "abstract": [
        {
          "text": "Returns the scale factor applied to the window.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "userSpaceScaleFactor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/userSpaceScaleFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userSpaceScaleFactor"
        }
      ],
      "role": "symbol",
      "title": "userSpaceScaleFactor",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/userspacescalefactor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/windowRef": {
      "abstract": [
        {
          "text": "The Carbon window reference associated with the window, creating one if necessary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "windowRef"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/windowRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "windowRef"
        }
      ],
      "role": "symbol",
      "title": "windowRef",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/windowref"
    },
    "doc://com.apple.appkit/documentation/AppKit/windows-panels-and-screens": {
      "abstract": [
        {
          "text": "Organize your view hierarchies and facilitate their display onscreen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/windows-panels-and-screens",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Windows, Panels, and Screens",
      "type": "topic",
      "url": "/documentation/appkit/windows-panels-and-screens"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Methods",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/gState()",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/canStoreColor()",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/enableFlushing()",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/disableFlushing()",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/flush()",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/flushIfNeeded()",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/menuChanged(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/cacheImage(in:)",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/restoreCachedImage()",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/discardCachedImage()",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/useOptimizedDrawing(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/init(windowRef:)"
      ],
      "title": "Methods"
    },
    {
      "anchor": "Properties",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/backingLocation-swift.property",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/preferredBackingLocation",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/isOneShot",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/drawers",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/showsResizeIndicator",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/isFlushWindowDisabled",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/isAutodisplay",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/graphicsContext",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/windowRef"
      ],
      "title": "Properties"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/BackingLocation-swift.enum"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Methods",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/gState()",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/canStoreColor()",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/enableFlushing()",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/disableFlushing()",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/flush()",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/flushIfNeeded()",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/menuChanged(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/cacheImage(in:)",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/restoreCachedImage()",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/discardCachedImage()",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/useOptimizedDrawing(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/convertBaseToScreen:",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/convertScreenToBase:",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/userSpaceScaleFactor",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/init(windowRef:)"
              ],
              "title": "Methods"
            },
            {
              "anchor": "Properties",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/backingLocation-swift.property",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/preferredBackingLocation",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/isOneShot",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/drawers",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/showsResizeIndicator",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/isFlushWindowDisabled",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/isAutodisplay",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/graphicsContext",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/windowRef"
              ],
              "title": "Properties"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/BackingLocation-swift.enum"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1drawers/title",
          "value": "drawers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1drawers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "drawers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1isOneShot/title",
          "value": "oneShot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1isOneShot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "oneShot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title",
          "value": "NSWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1discardCachedImage()/title",
          "value": "discardCachedImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1discardCachedImage()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "discardCachedImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1menuChanged(_:)/title",
          "value": "menuChanged:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1menuChanged(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "menuChanged:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1flush()/title",
          "value": "flushWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1flush()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "flushWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1useOptimizedDrawing(_:)/title",
          "value": "useOptimizedDrawing:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1useOptimizedDrawing(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "useOptimizedDrawing:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1isFlushWindowDisabled/title",
          "value": "flushWindowDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1isFlushWindowDisabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "flushWindowDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1canStoreColor()/title",
          "value": "canStoreColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1canStoreColor()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "canStoreColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1flushIfNeeded()/title",
          "value": "flushWindowIfNeeded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1flushIfNeeded()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "flushWindowIfNeeded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1backingLocation-swift.property/title",
          "value": "backingLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1backingLocation-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backingLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1disableFlushing()/title",
          "value": "disableFlushWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1disableFlushing()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "disableFlushWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1BackingLocation-swift.enum/title",
          "value": "NSWindowBackingLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1BackingLocation-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowBackingLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1BackingLocation-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowBackingLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1graphicsContext/title",
          "value": "graphicsContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1graphicsContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "graphicsContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1isAutodisplay/title",
          "value": "autodisplay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1isAutodisplay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "autodisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1preferredBackingLocation/title",
          "value": "preferredBackingLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1preferredBackingLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredBackingLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1windowRef/title",
          "value": "windowRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1windowRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "windowRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1enableFlushing()/title",
          "value": "enableFlushWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1enableFlushing()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enableFlushWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1init(windowRef:)/title",
          "value": "initWithWindowRef:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1init(windowRef:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithWindowRef:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1cacheImage(in:)/title",
          "value": "cacheImageInRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1cacheImage(in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cacheImageInRect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1restoreCachedImage()/title",
          "value": "restoreCachedImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1restoreCachedImage()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "restoreCachedImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1gState()/title",
          "value": "gState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1gState()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "gState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1showsResizeIndicator/title",
          "value": "showsResizeIndicator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1showsResizeIndicator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "showsResizeIndicator"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nswindow-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nswindow-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
