{
  "abstract": [
    {
      "text": "The writing direction of the text.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSWritingDirectionAttributeName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSWritingDirectionAttributeName",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSWritingDirectionAttributeName"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSWritingDirectionAttributeName"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSWritingDirectionAttributeName"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSAttributedStringKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSAttributedStringKey",
              "text": "NSAttributedStringKey"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSWritingDirectionAttributeName"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value of this attribute is an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsarray",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object containing ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects representing the nested levels of writing direction overrides, in order from outermost to innermost.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This attribute provides a means to override the default bidirectional text algorithm, equivalent to using the Unicode bidi control characters ",
              "type": "text"
            },
            {
              "code": "LRE",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "RLE",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "LRO",
              "type": "codeVoice"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "code": "RLO",
              "type": "codeVoice"
            },
            {
              "text": " paired with ",
              "type": "text"
            },
            {
              "code": "PDF",
              "type": "codeVoice"
            },
            {
              "text": ", but as a higher-level attribute. (See ",
              "type": "text"
            },
            {
              "identifier": "http://unicode.org/reports/tr9/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for information about the Unicode bidi formatting codes.) The ",
              "type": "text"
            },
            {
              "code": "NSWritingDirectionAttributeName",
              "type": "codeVoice"
            },
            {
              "text": " constant is a character-level attribute that provides a higher-level alternative to the inclusion of explicit bidirectional control characters in text. It is the ",
              "type": "text"
            },
            {
              "code": "NSAttributedString",
              "type": "codeVoice"
            },
            {
              "text": " equivalent of the HTML markup using ",
              "type": "text"
            },
            {
              "code": "bdo",
              "type": "codeVoice"
            },
            {
              "text": " element with the ",
              "type": "text"
            },
            {
              "code": "dir",
              "type": "codeVoice"
            },
            {
              "text": " attribute.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The values of the ",
              "type": "text"
            },
            {
              "code": "NSNumber",
              "type": "codeVoice"
            },
            {
              "text": " objects should be ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "1",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "2",
              "type": "codeVoice"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "code": "3",
              "type": "codeVoice"
            },
            {
              "text": ", for ",
              "type": "text"
            },
            {
              "code": "LRE",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "RLE",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "LRO",
              "type": "codeVoice"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "code": "RLO",
              "type": "codeVoice"
            },
            {
              "text": " respectively, and combinations of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection/leftToRight",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection/rightToLeft",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextWritingDirectionEmbedding",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextWritingDirectionOverride",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", as shown in the following table.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Array ",
                      "type": "text"
                    },
                    {
                      "code": "NSNumber",
                      "type": "codeVoice"
                    },
                    {
                      "text": " Values",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Unicode Control Characters",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Writing Direction Constants",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "0",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "LRE",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "NSWritingDirectionLeftToRight | NSTextWritingDirectionEmbedding",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "1",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "RLE",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "NSWritingDirectionRightToLeft | NSTextWritingDirectionEmbedding",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "2",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "LRO",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "NSWritingDirectionLeftToRight | NSTextWritingDirectionOverride",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "3",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "RLO",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "NSWritingDirectionRightToLeft | NSTextWritingDirectionOverride",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBackgroundColorAttributeName": {
      "abstract": [
        {
          "text": "The color of the background behind the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBackgroundColorAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBackgroundColorAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBackgroundColorAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsbackgroundcolorattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBaselineOffsetAttributeName": {
      "abstract": [
        {
          "text": "The vertical offset for the position of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBaselineOffsetAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBaselineOffsetAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBaselineOffsetAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsbaselineoffsetattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontAttributeName": {
      "abstract": [
        {
          "text": "The font of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFontAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFontAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsfontattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSForegroundColorAttributeName": {
      "abstract": [
        {
          "text": "The color of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSForegroundColorAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSForegroundColorAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSForegroundColorAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsforegroundcolorattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGlyphInfoAttributeName": {
      "abstract": [
        {
          "text": "The name of a glyph info object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSGlyphInfoAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphInfoAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSGlyphInfoAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsglyphinfoattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSKernAttributeName": {
      "abstract": [
        {
          "text": "The kerning of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSKernAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSKernAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSKernAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nskernattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLigatureAttributeName": {
      "abstract": [
        {
          "text": "The ligature of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLigatureAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLigatureAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLigatureAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsligatureattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyleAttributeName": {
      "abstract": [
        {
          "text": "The paragraph style of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSParagraphStyleAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyleAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSParagraphStyleAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyleattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStrikethroughColorAttributeName": {
      "abstract": [
        {
          "text": "The color of the strikethrough.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStrikethroughColorAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStrikethroughColorAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStrikethroughColorAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsstrikethroughcolorattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStrikethroughStyleAttributeName": {
      "abstract": [
        {
          "text": "The strikethrough style of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStrikethroughStyleAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStrikethroughStyleAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStrikethroughStyleAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsstrikethroughstyleattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStrokeColorAttributeName": {
      "abstract": [
        {
          "text": "The color of the stroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStrokeColorAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStrokeColorAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStrokeColorAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsstrokecolorattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStrokeWidthAttributeName": {
      "abstract": [
        {
          "text": "The width of the stroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStrokeWidthAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStrokeWidthAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStrokeWidthAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsstrokewidthattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSuperscriptAttributeName": {
      "abstract": [
        {
          "text": "The superscript of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSSuperscriptAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSuperscriptAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSuperscriptAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nssuperscriptattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextWritingDirectionEmbedding": {
      "abstract": [
        {
          "text": "Text is embedded in text with another writing direction.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextWritingDirectionEmbedding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextWritingDirectionEmbedding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextWritingDirectionEmbedding"
        }
      ],
      "role": "symbol",
      "title": "NSTextWritingDirectionEmbedding",
      "type": "topic",
      "url": "/documentation/appkit/nstextwritingdirectionembedding"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextWritingDirectionOverride": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextWritingDirectionOverride"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextWritingDirectionOverride",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextWritingDirectionOverride"
        }
      ],
      "role": "symbol",
      "title": "NSTextWritingDirectionOverride",
      "type": "topic",
      "url": "/documentation/appkit/nstextwritingdirectionoverride"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTrackingAttributeName": {
      "abstract": [
        {
          "text": "The amount to modify the default tracking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTrackingAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTrackingAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTrackingAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nstrackingattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnderlineColorAttributeName": {
      "abstract": [
        {
          "text": "The color of the underline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlineColorAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnderlineColorAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlineColorAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsunderlinecolorattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection/leftToRight": {
      "abstract": [
        {
          "text": "The writing direction is left to right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftToRight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection/leftToRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingDirectionLeftToRight"
        }
      ],
      "role": "symbol",
      "title": "NSWritingDirection.leftToRight",
      "type": "topic",
      "url": "/documentation/appkit/nswritingdirection/lefttoright"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection/rightToLeft": {
      "abstract": [
        {
          "text": "The writing direction is right to left.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightToLeft"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection/rightToLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingDirectionRightToLeft"
        }
      ],
      "role": "symbol",
      "title": "NSWritingDirection.rightToLeft",
      "type": "topic",
      "url": "/documentation/appkit/nswritingdirection/righttoleft"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingDirectionAttributeName": {
      "abstract": [
        {
          "text": "The writing direction of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSWritingDirectionAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingDirectionAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSWritingDirectionAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nswritingdirectionattributename"
    },
    "doc://com.apple.documentation/documentation/foundation/nsarray": {
      "abstract": [
        {
          "text": "An object representing a static ordered collection, for use instead of an  constant in cases that require reference semantics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSArray"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsarray",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSArray",
      "type": "topic",
      "url": "/documentation/foundation/nsarray"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSAttributedStringKey": {
      "abstract": [
        {
          "text": "The attributes you apply to ranges of characters in an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "NSAttributedString.Key"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSAttributedStringKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedString.Key",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/key"
    },
    "http://unicode.org/reports/tr9/": {
      "identifier": "http://unicode.org/reports/tr9/",
      "title": "Unicode Standard Annex #9",
      "titleInlineContent": [
        {
          "text": "Unicode Standard Annex #9",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://unicode.org/reports/tr9/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-rendering-attribute-keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBackgroundColorAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSBaselineOffsetAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSFontAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSForegroundColorAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSGlyphInfoAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSKernAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSLigatureAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyleAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSStrikethroughColorAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSStrikethroughStyleAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSStrokeColorAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSStrokeWidthAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSSuperscriptAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSTrackingAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSUnderlineColorAttributeName"
      ],
      "title": "Getting rendering attribute keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirection~1leftToRight/title",
          "value": "NSWritingDirectionLeftToRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirection~1leftToRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingDirectionLeftToRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextWritingDirectionOverride/title",
          "value": "NSTextWritingDirectionOverride"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextWritingDirectionOverride/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextWritingDirectionOverride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextWritingDirectionEmbedding/title",
          "value": "NSTextWritingDirectionEmbedding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextWritingDirectionEmbedding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextWritingDirectionEmbedding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSAttributedStringKey/title",
          "value": "NSAttributedStringKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsarray/abstract",
          "value": [
            {
              "text": "A static ordered collection of objects.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirection~1rightToLeft/title",
          "value": "NSWritingDirectionRightToLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirection~1rightToLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingDirectionRightToLeft"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nswritingdirectionattributename"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
