{
  "abstract": [
    {
      "text": "Display and allow editing of the year, month and day elements of the date.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSYearMonthDayDatePickerElementFlag"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSYearMonthDayDatePickerElementFlag",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSYearMonthDayDatePickerElementFlag"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSYearMonthDayDatePickerElementFlag"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSYearMonthDayDatePickerElementFlag"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSDatePickerElementFlags",
              "text": "NSDatePickerElementFlags"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSYearMonthDayDatePickerElementFlag"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags": {
      "abstract": [
        {
          "text": "Constants that specify the date and time elements displayed by the picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ElementFlags"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ElementFlags"
        }
      ],
      "role": "symbol",
      "title": "NSDatePicker.ElementFlags",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker/elementflags"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEraDatePickerElementFlag": {
      "abstract": [
        {
          "text": "Display and allow editing of the era of the date, if applicable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSEraDatePickerElementFlag"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEraDatePickerElementFlag",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSEraDatePickerElementFlag",
      "type": "topic",
      "url": "/documentation/appkit/nseradatepickerelementflag"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHourMinuteDatePickerElementFlag": {
      "abstract": [
        {
          "text": "Display and allow editing of the hour and minute elements of the date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSHourMinuteDatePickerElementFlag"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHourMinuteDatePickerElementFlag",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSHourMinuteDatePickerElementFlag",
      "type": "topic",
      "url": "/documentation/appkit/nshourminutedatepickerelementflag"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHourMinuteSecondDatePickerElementFlag": {
      "abstract": [
        {
          "text": "Display and allow editing of the hour, minute and second elements of the date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSHourMinuteSecondDatePickerElementFlag"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHourMinuteSecondDatePickerElementFlag",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSHourMinuteSecondDatePickerElementFlag",
      "type": "topic",
      "url": "/documentation/appkit/nshourminuteseconddatepickerelementflag"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTimeZoneDatePickerElementFlag": {
      "abstract": [
        {
          "text": "Display and allow editing of the time zone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTimeZoneDatePickerElementFlag"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTimeZoneDatePickerElementFlag",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTimeZoneDatePickerElementFlag",
      "type": "topic",
      "url": "/documentation/appkit/nstimezonedatepickerelementflag"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSYearMonthDatePickerElementFlag": {
      "abstract": [
        {
          "text": "Display and allow editing of the year and month elements of the date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSYearMonthDatePickerElementFlag"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSYearMonthDatePickerElementFlag",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSYearMonthDatePickerElementFlag",
      "type": "topic",
      "url": "/documentation/appkit/nsyearmonthdatepickerelementflag"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSYearMonthDayDatePickerElementFlag": {
      "abstract": [
        {
          "text": "Display and allow editing of the year, month and day elements of the date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSYearMonthDayDatePickerElementFlag"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSYearMonthDayDatePickerElementFlag",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSYearMonthDayDatePickerElementFlag",
      "type": "topic",
      "url": "/documentation/appkit/nsyearmonthdaydatepickerelementflag"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSHourMinuteDatePickerElementFlag",
        "doc://com.apple.appkit/documentation/AppKit/NSHourMinuteSecondDatePickerElementFlag",
        "doc://com.apple.appkit/documentation/AppKit/NSTimeZoneDatePickerElementFlag",
        "doc://com.apple.appkit/documentation/AppKit/NSYearMonthDatePickerElementFlag",
        "doc://com.apple.appkit/documentation/AppKit/NSEraDatePickerElementFlag"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags/title",
          "value": "NSDatePickerElementFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePickerElementFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePickerElementFlags"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsyearmonthdaydatepickerelementflag"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
