{
  "abstract": [
    {
      "text": "Display a list-based interface for hierarchical data, where each level of hierarchy is indented from the previous one.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/views-and-controls"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/outline-view"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Outline View"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOutlineView": {
      "abstract": [
        {
          "text": "A view that uses a row-and-column format to display hierarchical data like directories and files that can be expanded and collapsed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOutlineView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOutlineView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOutlineView"
        }
      ],
      "role": "symbol",
      "title": "NSOutlineView",
      "type": "topic",
      "url": "/documentation/appkit/nsoutlineview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOutlineViewDataSource": {
      "abstract": [
        {
          "text": "A set of methods that an outline view calls to retrieve data and information about it from the data source delegate, and—optionally—to update data values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOutlineViewDataSource"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOutlineViewDataSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOutlineViewDataSource"
        }
      ],
      "role": "symbol",
      "title": "NSOutlineViewDataSource",
      "type": "topic",
      "url": "/documentation/appkit/nsoutlineviewdatasource"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOutlineViewDelegate": {
      "abstract": [
        {
          "text": "A set of optional methods implemented by delegates of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOutlineView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOutlineViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOutlineViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOutlineViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSOutlineViewDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nsoutlineviewdelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView": {
      "abstract": [
        {
          "text": "A view that draws text and handles user interactions with that text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "role": "symbol",
      "title": "NSTextView",
      "type": "topic",
      "url": "/documentation/appkit/nstextview"
    },
    "doc://com.apple.appkit/documentation/AppKit/browser-view": {
      "abstract": [
        {
          "text": "Provide a column-based interface for viewing and navigating hierarchical information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/browser-view",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Browser View",
      "type": "topic",
      "url": "/documentation/appkit/browser-view"
    },
    "doc://com.apple.appkit/documentation/AppKit/collection-view": {
      "abstract": [
        {
          "text": "Display one or more subviews in a highly configurable arrangement.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/collection-view",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Collection View",
      "type": "topic",
      "url": "/documentation/appkit/collection-view"
    },
    "doc://com.apple.appkit/documentation/AppKit/navigating-hierarchical-data-using-outline-and-split-views": {
      "abstract": [
        {
          "text": "Build a structured user interface that simplifies navigation in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/navigating-hierarchical-data-using-outline-and-split-views",
      "kind": "article",
      "role": "sampleCode",
      "title": "Navigating Hierarchical Data Using Outline and Split Views",
      "type": "topic",
      "url": "/documentation/appkit/navigating-hierarchical-data-using-outline-and-split-views"
    },
    "doc://com.apple.appkit/documentation/AppKit/table-view": {
      "abstract": [
        {
          "text": "Display custom data in rows and columns.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/table-view",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Table View",
      "type": "topic",
      "url": "/documentation/appkit/table-view"
    },
    "doc://com.apple.appkit/documentation/AppKit/views-and-controls": {
      "abstract": [
        {
          "text": "Present your content onscreen and handle user input and events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Views and Controls",
      "type": "topic",
      "url": "/documentation/appkit/views-and-controls"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Content-Views",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/browser-view",
        "doc://com.apple.appkit/documentation/AppKit/collection-view",
        "doc://com.apple.appkit/documentation/AppKit/table-view",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView"
      ],
      "title": "Content Views"
    }
  ],
  "topicSections": [
    {
      "anchor": "View",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSOutlineView",
        "doc://com.apple.appkit/documentation/AppKit/navigating-hierarchical-data-using-outline-and-split-views"
      ],
      "title": "View"
    },
    {
      "anchor": "Management",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSOutlineViewDataSource",
        "doc://com.apple.appkit/documentation/AppKit/NSOutlineViewDelegate"
      ],
      "title": "Management"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "View",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSOutlineView",
                "doc://com.apple.appkit/documentation/AppKit/navigating-hierarchical-data-using-outline-and-split-views"
              ],
              "title": "View"
            },
            {
              "anchor": "Management",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSOutlineViewDataSource",
                "doc://com.apple.appkit/documentation/AppKit/NSOutlineViewDelegate"
              ],
              "title": "Management"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Content-Views",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/browser-view",
                "doc://com.apple.appkit/documentation/AppKit/collection-view",
                "doc://com.apple.appkit/documentation/AppKit/table-view",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView"
              ],
              "title": "Content Views"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/title",
          "value": "NSTextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOutlineViewDelegate/title",
          "value": "NSOutlineViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOutlineViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOutlineViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOutlineViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOutlineViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOutlineViewDataSource/title",
          "value": "NSOutlineViewDataSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOutlineViewDataSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOutlineViewDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOutlineViewDataSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOutlineViewDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOutlineView/title",
          "value": "NSOutlineView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOutlineView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOutlineView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOutlineView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOutlineView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/outline-view"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/outline-view"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
