{
  "abstract": [
    {
      "text": "A display of a file system path or virtual path information.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/views-and-controls"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/path-control"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Path Control"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton": {
      "abstract": [
        {
          "text": "A control that defines an area on the screen that a user clicks to trigger an action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButton"
        }
      ],
      "role": "symbol",
      "title": "NSButton",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorWell": {
      "abstract": [
        {
          "text": "A control that displays a color value and lets the user change that color value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSColorWell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorWell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorWell"
        }
      ],
      "role": "symbol",
      "title": "NSColorWell",
      "type": "topic",
      "url": "/documentation/appkit/nscolorwell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSComboButton": {
      "abstract": [
        {
          "text": "A button with a pull-down menu and a default action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSComboButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSComboButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSComboButton"
        }
      ],
      "role": "symbol",
      "title": "NSComboButton",
      "type": "topic",
      "url": "/documentation/appkit/nscombobutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageView": {
      "abstract": [
        {
          "text": "A display of image data in a frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImageView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageView"
        }
      ],
      "role": "symbol",
      "title": "NSImageView",
      "type": "topic",
      "url": "/documentation/appkit/nsimageview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLevelIndicator": {
      "abstract": [
        {
          "text": "A visual representation of a level or quantity, using discrete values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLevelIndicator"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLevelIndicator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLevelIndicator"
        }
      ],
      "role": "symbol",
      "title": "NSLevelIndicator",
      "type": "topic",
      "url": "/documentation/appkit/nslevelindicator"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPathCell": {
      "abstract": [
        {
          "text": "The user interface of a path control object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPathCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPathCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPathCell"
        }
      ],
      "role": "symbol",
      "title": "NSPathCell",
      "type": "topic",
      "url": "/documentation/appkit/nspathcell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPathCellDelegate": {
      "abstract": [
        {
          "text": "A set of methods that enable the delegate of a path cell object to customize the Open panel or pop-up menu of a path whose style is set to ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPathControl/Style/popUp",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPathCellDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPathCellDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPathCellDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSPathCellDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nspathcelldelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPathComponentCell": {
      "abstract": [
        {
          "text": "A component of a path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPathComponentCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPathComponentCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPathComponentCell"
        }
      ],
      "role": "symbol",
      "title": "NSPathComponentCell",
      "type": "topic",
      "url": "/documentation/appkit/nspathcomponentcell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPathControl": {
      "abstract": [
        {
          "text": "A display of a file system path or virtual path information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPathControl"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPathControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPathControl"
        }
      ],
      "role": "symbol",
      "title": "NSPathControl",
      "type": "topic",
      "url": "/documentation/appkit/nspathcontrol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPathControl/Style/popUp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popUp"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPathControl/Style/popUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPathStylePopUp"
        }
      ],
      "role": "symbol",
      "title": "NSPathControl.Style.popUp",
      "type": "topic",
      "url": "/documentation/appkit/nspathcontrol/style/popup"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPathControlDelegate": {
      "abstract": [
        {
          "text": "A set of methods that can be implemented by the delegate of a path control object to support dragging to and from the control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPathControlDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPathControlDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPathControlDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSPathControlDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nspathcontroldelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPathControlItem": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPathControlItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPathControlItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPathControlItem"
        }
      ],
      "role": "symbol",
      "title": "NSPathControlItem",
      "type": "topic",
      "url": "/documentation/appkit/nspathcontrolitem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPopUpButton": {
      "abstract": [
        {
          "text": "A control for selecting an item from a list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPopUpButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPopUpButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPopUpButton"
        }
      ],
      "role": "symbol",
      "title": "NSPopUpButton",
      "type": "topic",
      "url": "/documentation/appkit/nspopupbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPredicateEditor": {
      "abstract": [
        {
          "text": "A defined set of rules that allows the editing of predicate objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPredicateEditor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPredicateEditor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPredicateEditor"
        }
      ],
      "role": "symbol",
      "title": "NSPredicateEditor",
      "type": "topic",
      "url": "/documentation/appkit/nspredicateeditor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicator": {
      "abstract": [
        {
          "text": "An interface that provides visual feedback to the user about the status of an ongoing task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSProgressIndicator"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSProgressIndicator"
        }
      ],
      "role": "symbol",
      "title": "NSProgressIndicator",
      "type": "topic",
      "url": "/documentation/appkit/nsprogressindicator"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRuleEditor": {
      "abstract": [
        {
          "text": "An interface for configuring a rule-based list of options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSRuleEditor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRuleEditor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRuleEditor"
        }
      ],
      "role": "symbol",
      "title": "NSRuleEditor",
      "type": "topic",
      "url": "/documentation/appkit/nsruleeditor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl": {
      "abstract": [
        {
          "text": "Display one or more buttons in a single horizontal group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSegmentedControl"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSegmentedControl"
        }
      ],
      "role": "symbol",
      "title": "NSSegmentedControl",
      "type": "topic",
      "url": "/documentation/appkit/nssegmentedcontrol"
    },
    "doc://com.apple.appkit/documentation/AppKit/combo-box": {
      "abstract": [
        {
          "text": "Display a list of values in a pop-up menu that lets the user select a value or type in a custom value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/combo-box",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Combo Box",
      "type": "topic",
      "url": "/documentation/appkit/combo-box"
    },
    "doc://com.apple.appkit/documentation/AppKit/date-picker": {
      "abstract": [
        {
          "text": "Display a calendar date and provide controls for editing the date value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/date-picker",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Date Picker",
      "type": "topic",
      "url": "/documentation/appkit/date-picker"
    },
    "doc://com.apple.appkit/documentation/AppKit/search-field": {
      "abstract": [
        {
          "text": "Provide a text field that is optimized for text-based search interfaces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/search-field",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Search Field",
      "type": "topic",
      "url": "/documentation/appkit/search-field"
    },
    "doc://com.apple.appkit/documentation/AppKit/slider": {
      "abstract": [
        {
          "text": "Display a range of values from which the user selects a single value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/slider",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Slider",
      "type": "topic",
      "url": "/documentation/appkit/slider"
    },
    "doc://com.apple.appkit/documentation/AppKit/views-and-controls": {
      "abstract": [
        {
          "text": "Present your content onscreen and handle user input and events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Views and Controls",
      "type": "topic",
      "url": "/documentation/appkit/views-and-controls"
    },
    "doc://com.apple.documentation/documentation/UIKit/responding-to-control-based-events-using-target-action": {
      "abstract": [
        {
          "text": "Handle user input by connecting buttons, sliders, and other controls to your app’s code using the target-action design pattern.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/responding-to-control-based-events-using-target-action",
      "kind": "article",
      "role": "article",
      "title": "Responding to control-based events using target-action",
      "type": "topic",
      "url": "/documentation/UIKit/responding-to-control-based-events-using-target-action"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Controls",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/UIKit/responding-to-control-based-events-using-target-action",
        "doc://com.apple.appkit/documentation/AppKit/NSButton",
        "doc://com.apple.appkit/documentation/AppKit/NSColorWell",
        "doc://com.apple.appkit/documentation/AppKit/combo-box",
        "doc://com.apple.appkit/documentation/AppKit/NSComboButton",
        "doc://com.apple.appkit/documentation/AppKit/date-picker",
        "doc://com.apple.appkit/documentation/AppKit/NSImageView",
        "doc://com.apple.appkit/documentation/AppKit/NSLevelIndicator",
        "doc://com.apple.appkit/documentation/AppKit/NSPopUpButton",
        "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicator",
        "doc://com.apple.appkit/documentation/AppKit/NSRuleEditor",
        "doc://com.apple.appkit/documentation/AppKit/NSPredicateEditor",
        "doc://com.apple.appkit/documentation/AppKit/search-field",
        "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl",
        "doc://com.apple.appkit/documentation/AppKit/slider"
      ],
      "title": "Controls"
    }
  ],
  "topicSections": [
    {
      "anchor": "View",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPathControl"
      ],
      "title": "View"
    },
    {
      "anchor": "Management",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPathControlDelegate"
      ],
      "title": "Management"
    },
    {
      "anchor": "Cells",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPathCell",
        "doc://com.apple.appkit/documentation/AppKit/NSPathCellDelegate",
        "doc://com.apple.appkit/documentation/AppKit/NSPathComponentCell",
        "doc://com.apple.appkit/documentation/AppKit/NSPathControlItem"
      ],
      "title": "Cells"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "View",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPathControl"
              ],
              "title": "View"
            },
            {
              "anchor": "Management",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPathControlDelegate"
              ],
              "title": "Management"
            },
            {
              "anchor": "Cells",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPathCell",
                "doc://com.apple.appkit/documentation/AppKit/NSPathCellDelegate",
                "doc://com.apple.appkit/documentation/AppKit/NSPathComponentCell",
                "doc://com.apple.appkit/documentation/AppKit/NSPathControlItem"
              ],
              "title": "Cells"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Controls",
              "generated": true,
              "identifiers": [
                "doc://com.apple.documentation/documentation/UIKit/responding-to-control-based-events-using-target-action",
                "doc://com.apple.appkit/documentation/AppKit/NSButton",
                "doc://com.apple.appkit/documentation/AppKit/NSColorWell",
                "doc://com.apple.appkit/documentation/AppKit/combo-box",
                "doc://com.apple.appkit/documentation/AppKit/NSComboButton",
                "doc://com.apple.appkit/documentation/AppKit/date-picker",
                "doc://com.apple.appkit/documentation/AppKit/NSImageView",
                "doc://com.apple.appkit/documentation/AppKit/NSLevelIndicator",
                "doc://com.apple.appkit/documentation/AppKit/NSPopUpButton",
                "doc://com.apple.appkit/documentation/AppKit/NSProgressIndicator",
                "doc://com.apple.appkit/documentation/AppKit/NSRuleEditor",
                "doc://com.apple.appkit/documentation/AppKit/NSPredicateEditor",
                "doc://com.apple.appkit/documentation/AppKit/search-field",
                "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl",
                "doc://com.apple.appkit/documentation/AppKit/slider"
              ],
              "title": "Controls"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageView/title",
          "value": "NSImageView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl/title",
          "value": "NSSegmentedControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSegmentedControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSegmentedControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathCellDelegate/title",
          "value": "NSPathCellDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathCellDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPathCellDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathCellDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPathCellDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell/title",
          "value": "NSColorWell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorWell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorWell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/title",
          "value": "NSButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathControl/title",
          "value": "NSPathControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPathControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathControl/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPathControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathComponentCell/title",
          "value": "NSPathComponentCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathComponentCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPathComponentCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathComponentCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPathComponentCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPredicateEditor/title",
          "value": "NSPredicateEditor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPredicateEditor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPredicateEditor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPredicateEditor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPredicateEditor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathControl~1Style~1popUp/title",
          "value": "NSPathStylePopUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathControl~1Style~1popUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPathStylePopUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathControlItem/title",
          "value": "NSPathControlItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathControlItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPathControlItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathControlItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPathControlItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathCell/title",
          "value": "NSPathCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPathCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPathCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboButton/title",
          "value": "NSComboButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSComboButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSComboButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSProgressIndicator/title",
          "value": "NSProgressIndicator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSProgressIndicator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSProgressIndicator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSProgressIndicator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSProgressIndicator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathControlDelegate/title",
          "value": "NSPathControlDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathControlDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPathControlDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPathControlDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPathControlDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor/title",
          "value": "NSRuleEditor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRuleEditor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRuleEditor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButton/title",
          "value": "NSPopUpButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPopUpButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopUpButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPopUpButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLevelIndicator/title",
          "value": "NSLevelIndicator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLevelIndicator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLevelIndicator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLevelIndicator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLevelIndicator"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/path-control"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/path-control"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
