{
  "abstract": [
    {
      "text": "Manage contextual menus, cursors, tool tips, and other system-provided windows and content.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
        "doc://com.apple.appkit/documentation/AppKit/NSView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/related-ui"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Related UI"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/appkit/nsview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/DefinitionOptionKey": {
      "abstract": [
        {
          "text": "Keys to include in your definition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DefinitionOptionKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/DefinitionOptionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DefinitionOptionKey"
        }
      ],
      "role": "symbol",
      "title": "NSView.DefinitionOptionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsview/definitionoptionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/DefinitionPresentationType": {
      "abstract": [
        {
          "text": "Presentation options for the window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DefinitionPresentationType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/DefinitionPresentationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DefinitionPresentationType"
        }
      ],
      "role": "symbol",
      "title": "NSView.DefinitionPresentationType",
      "type": "topic",
      "url": "/documentation/appkit/nsview/definitionpresentationtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/ToolTipTag": {
      "abstract": [
        {
          "text": "This type describes the rectangle used to identify a tooltip rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ToolTipTag"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/ToolTipTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ToolTipTag"
        }
      ],
      "role": "symbol",
      "title": "NSView.ToolTipTag",
      "type": "topic",
      "url": "/documentation/appkit/nsview/tooltiptag"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/addCursorRect(_:cursor:)": {
      "abstract": [
        {
          "text": "Establishes  the cursor to be used when the mouse pointer lies within a specified region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addCursorRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "cursor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCursor",
          "text": "NSCursor"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/addCursorRect(_:cursor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addCursorRect:cursor:"
        }
      ],
      "role": "symbol",
      "title": "addCursorRect(_:cursor:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/addcursorrect(_:cursor:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/addToolTip(_:owner:userData:)": {
      "abstract": [
        {
          "text": "Creates a tooltip for a defined area in the view and returns a tag that identifies the tooltip rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addToolTip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "owner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "userData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSToolTipTag",
          "text": "ToolTipTag"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/addToolTip(_:owner:userData:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addToolTipRect:owner:userData:"
        }
      ],
      "role": "symbol",
      "title": "addToolTip(_:owner:userData:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/addtooltip(_:owner:userdata:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/defaultMenu": {
      "abstract": [
        {
          "text": "Overridden by subclasses to return the default pop-up menu for instances of the receiving class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultMenu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMenu",
          "text": "NSMenu"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/defaultMenu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultMenu"
        }
      ],
      "role": "symbol",
      "title": "defaultMenu",
      "type": "topic",
      "url": "/documentation/appkit/nsview/defaultmenu"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/didCloseMenu(_:with:)": {
      "abstract": [
        {
          "text": "Called after a contextual menu that was displayed from the receiving view has been closed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didCloseMenu"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMenu",
          "text": "NSMenu"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/didCloseMenu(_:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "didCloseMenu:withEvent:"
        }
      ],
      "role": "symbol",
      "title": "didCloseMenu(_:with:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/didclosemenu(_:with:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/discardCursorRects()": {
      "abstract": [
        {
          "text": "Invalidates all cursor rectangles set up using ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/addCursorRect(_:cursor:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "discardCursorRects"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/discardCursorRects()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "discardCursorRects"
        }
      ],
      "role": "symbol",
      "title": "discardCursorRects()",
      "type": "topic",
      "url": "/documentation/appkit/nsview/discardcursorrects()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/displayLink(target:selector:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayLink"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "target"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "selector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CADisplayLink",
          "text": "CADisplayLink"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/displayLink(target:selector:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayLinkWithTarget:selector:"
        }
      ],
      "role": "symbol",
      "title": "displayLink(target:selector:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/displaylink(target:selector:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/focusView": {
      "abstract": [
        {
          "text": "The currently focused view object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "focusView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/focusView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "focusView"
        }
      ],
      "role": "symbol",
      "title": "focusView",
      "type": "topic",
      "url": "/documentation/appkit/nsview/focusview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/menu(for:)": {
      "abstract": [
        {
          "text": "Overridden by subclasses to return a context-sensitive pop-up menu for a given mouse-down event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "menu"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMenu",
          "text": "NSMenu"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/menu(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "menuForEvent:"
        }
      ],
      "role": "symbol",
      "title": "menu(for:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/menu(for:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/removeAllToolTips()": {
      "abstract": [
        {
          "text": "Removes all tooltips assigned to the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAllToolTips"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/removeAllToolTips()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllToolTips"
        }
      ],
      "role": "symbol",
      "title": "removeAllToolTips()",
      "type": "topic",
      "url": "/documentation/appkit/nsview/removealltooltips()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/removeCursorRect(_:cursor:)": {
      "abstract": [
        {
          "text": "Completely removes a cursor rectangle from the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeCursorRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "cursor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCursor",
          "text": "NSCursor"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/removeCursorRect(_:cursor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeCursorRect:cursor:"
        }
      ],
      "role": "symbol",
      "title": "removeCursorRect(_:cursor:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/removecursorrect(_:cursor:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/removeToolTip(_:)": {
      "abstract": [
        {
          "text": "Removes the tooltip identified by specified tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeToolTip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSToolTipTag",
          "text": "ToolTipTag"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/removeToolTip(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeToolTip:"
        }
      ],
      "role": "symbol",
      "title": "removeToolTip(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/removetooltip(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/resetCursorRects()": {
      "abstract": [
        {
          "text": "Overridden by subclasses to define their default cursor rectangles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resetCursorRects"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/resetCursorRects()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resetCursorRects"
        }
      ],
      "role": "symbol",
      "title": "resetCursorRects()",
      "type": "topic",
      "url": "/documentation/appkit/nsview/resetcursorrects()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:didAdd:)": {
      "abstract": [
        {
          "text": "Informs the client that ",
          "type": "text"
        },
        {
          "code": "aRulerView",
          "type": "codeVoice"
        },
        {
          "text": " allowed the user to add ",
          "type": "text"
        },
        {
          "code": "aMarker",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rulerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerView",
          "text": "NSRulerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didAdd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerMarker",
          "text": "NSRulerMarker"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:didAdd:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rulerView:didAddMarker:"
        }
      ],
      "role": "symbol",
      "title": "rulerView(_:didAdd:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/rulerview(_:didadd:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:didMove:)": {
      "abstract": [
        {
          "text": "Informs the client that ",
          "type": "text"
        },
        {
          "code": "aRulerView",
          "type": "codeVoice"
        },
        {
          "text": " allowed the user to move ",
          "type": "text"
        },
        {
          "code": "aMarker",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rulerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerView",
          "text": "NSRulerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didMove"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerMarker",
          "text": "NSRulerMarker"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:didMove:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rulerView:didMoveMarker:"
        }
      ],
      "role": "symbol",
      "title": "rulerView(_:didMove:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/rulerview(_:didmove:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:didRemove:)": {
      "abstract": [
        {
          "text": "Informs the client that ",
          "type": "text"
        },
        {
          "code": "aRulerView",
          "type": "codeVoice"
        },
        {
          "text": " allowed the user to remove ",
          "type": "text"
        },
        {
          "code": "aMarker",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rulerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerView",
          "text": "NSRulerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didRemove"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerMarker",
          "text": "NSRulerMarker"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:didRemove:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rulerView:didRemoveMarker:"
        }
      ],
      "role": "symbol",
      "title": "rulerView(_:didRemove:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/rulerview(_:didremove:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:handleMouseDownWith:)": {
      "abstract": [
        {
          "text": "Informs the client that the user has pressed the mouse button while the cursor is in the ruler area of ",
          "type": "text"
        },
        {
          "code": "aRulerView",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rulerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerView",
          "text": "NSRulerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handleMouseDownWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:handleMouseDownWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rulerView:handleMouseDown:"
        }
      ],
      "role": "symbol",
      "title": "rulerView(_:handleMouseDownWith:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/rulerview(_:handlemousedownwith:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:locationFor:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rulerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerView",
          "text": "NSRulerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "locationFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:locationFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rulerView:locationForPoint:"
        }
      ],
      "role": "symbol",
      "title": "rulerView(_:locationFor:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/rulerview(_:locationfor:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:pointForLocation:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rulerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerView",
          "text": "NSRulerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "pointForLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:pointForLocation:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rulerView:pointForLocation:"
        }
      ],
      "role": "symbol",
      "title": "rulerView(_:pointForLocation:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/rulerview(_:pointforlocation:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:shouldAdd:)": {
      "abstract": [
        {
          "text": "Requests permission for ",
          "type": "text"
        },
        {
          "code": "aRulerView",
          "type": "codeVoice"
        },
        {
          "text": " to add ",
          "type": "text"
        },
        {
          "code": "aMarker",
          "type": "codeVoice"
        },
        {
          "text": ", an NSRulerMarker being dragged onto the ruler by the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rulerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerView",
          "text": "NSRulerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldAdd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerMarker",
          "text": "NSRulerMarker"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:shouldAdd:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rulerView:shouldAddMarker:"
        }
      ],
      "role": "symbol",
      "title": "rulerView(_:shouldAdd:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/rulerview(_:shouldadd:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:shouldMove:)": {
      "abstract": [
        {
          "text": "Requests permission for ",
          "type": "text"
        },
        {
          "code": "aRulerView",
          "type": "codeVoice"
        },
        {
          "text": " to move ",
          "type": "text"
        },
        {
          "code": "aMarker",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rulerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerView",
          "text": "NSRulerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldMove"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerMarker",
          "text": "NSRulerMarker"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:shouldMove:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rulerView:shouldMoveMarker:"
        }
      ],
      "role": "symbol",
      "title": "rulerView(_:shouldMove:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/rulerview(_:shouldmove:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:shouldRemove:)": {
      "abstract": [
        {
          "text": "Requests permission for ",
          "type": "text"
        },
        {
          "code": "aRulerView",
          "type": "codeVoice"
        },
        {
          "text": " to remove ",
          "type": "text"
        },
        {
          "code": "aMarker",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rulerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerView",
          "text": "NSRulerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldRemove"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerMarker",
          "text": "NSRulerMarker"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:shouldRemove:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rulerView:shouldRemoveMarker:"
        }
      ],
      "role": "symbol",
      "title": "rulerView(_:shouldRemove:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/rulerview(_:shouldremove:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:willAdd:atLocation:)": {
      "abstract": [
        {
          "text": "Informs the client that ",
          "type": "text"
        },
        {
          "code": "aRulerView",
          "type": "codeVoice"
        },
        {
          "text": " will add the new NSRulerMarker, ",
          "type": "text"
        },
        {
          "code": "aMarker",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rulerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerView",
          "text": "NSRulerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willAdd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerMarker",
          "text": "NSRulerMarker"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "atLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:willAdd:atLocation:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rulerView:willAddMarker:atLocation:"
        }
      ],
      "role": "symbol",
      "title": "rulerView(_:willAdd:atLocation:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/rulerview(_:willadd:atlocation:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:willMove:toLocation:)": {
      "abstract": [
        {
          "text": "Informs the client that ",
          "type": "text"
        },
        {
          "code": "aRulerView",
          "type": "codeVoice"
        },
        {
          "text": " will move ",
          "type": "text"
        },
        {
          "code": "aMarker",
          "type": "codeVoice"
        },
        {
          "text": ", an NSRulerMarker already on the ruler view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rulerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerView",
          "text": "NSRulerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willMove"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerMarker",
          "text": "NSRulerMarker"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:willMove:toLocation:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rulerView:willMoveMarker:toLocation:"
        }
      ],
      "role": "symbol",
      "title": "rulerView(_:willMove:toLocation:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/rulerview(_:willmove:tolocation:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:willSetClientView:)": {
      "abstract": [
        {
          "text": "Informs the client view that ",
          "type": "text"
        },
        {
          "code": "aRulerView",
          "type": "codeVoice"
        },
        {
          "text": " is about to be appropriated by ",
          "type": "text"
        },
        {
          "code": "newClient",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rulerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRulerView",
          "text": "NSRulerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willSetClientView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:willSetClientView:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rulerView:willSetClientView:"
        }
      ],
      "role": "symbol",
      "title": "rulerView(_:willSetClientView:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/rulerview(_:willsetclientview:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/showDefinition(for:at:)": {
      "abstract": [
        {
          "text": "Shows a window displaying the definition of the attributed string at the specified point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showDefinition"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/showDefinition(for:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showDefinitionForAttributedString:atPoint:"
        }
      ],
      "role": "symbol",
      "title": "showDefinition(for:at:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/showdefinition(for:at:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/showDefinition(for:range:options:baselineOriginProvider:)": {
      "abstract": [
        {
          "text": "Shows a window displaying the definition of the specified range of the attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showDefinition"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "range"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSDefinitionOptionKey",
          "text": "DefinitionOptionKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "baselineOriginProvider"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/showDefinition(for:range:options:baselineOriginProvider:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showDefinitionForAttributedString:range:options:baselineOriginProvider:"
        }
      ],
      "role": "symbol",
      "title": "showDefinition(for:range:options:baselineOriginProvider:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/showdefinition(for:range:options:baselineoriginprovider:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/toolTip": {
      "abstract": [
        {
          "text": "The text for the views tooltip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toolTip"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/toolTip",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toolTip"
        }
      ],
      "role": "symbol",
      "title": "toolTip",
      "type": "topic",
      "url": "/documentation/appkit/nsview/tooltip"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/willOpenMenu(_:with:)": {
      "abstract": [
        {
          "text": "Called just before a contextual menu for a view is opened on screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willOpenMenu"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMenu",
          "text": "NSMenu"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/willOpenMenu(_:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "willOpenMenu:withEvent:"
        }
      ],
      "role": "symbol",
      "title": "willOpenMenu(_:with:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/willopenmenu(_:with:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/core-animation-support": {
      "abstract": [
        {
          "text": "Manage the layer object that provides the views visual representation and accelerates drawing operations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/core-animation-support",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Animation Support",
      "type": "topic",
      "url": "/documentation/appkit/core-animation-support"
    },
    "doc://com.apple.appkit/documentation/AppKit/nsview-appearance": {
      "abstract": [
        {
          "text": "Change the views visibility, vibrancy, and focus ring and respond to appearance-related changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nsview-appearance",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Appearance",
      "type": "topic",
      "url": "/documentation/appkit/nsview-appearance"
    },
    "doc://com.apple.appkit/documentation/AppKit/view-coordinates": {
      "abstract": [
        {
          "text": "Manage the frame and bounds rectangles that determine the size and position of the view in the view hierarchy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/view-coordinates",
      "kind": "article",
      "role": "collectionGroup",
      "title": "View Coordinates",
      "type": "topic",
      "url": "/documentation/appkit/view-coordinates"
    },
    "doc://com.apple.appkit/documentation/AppKit/view-hierarchy": {
      "abstract": [
        {
          "text": "Manage the subviews, superview, and window of a view and respond to notifications when the view hierarchy changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/view-hierarchy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "View Hierarchy",
      "type": "topic",
      "url": "/documentation/appkit/view-hierarchy"
    },
    "doc://com.apple.appkit/documentation/AppKit/views-and-controls": {
      "abstract": [
        {
          "text": "Present your content onscreen and handle user input and events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Views and Controls",
      "type": "topic",
      "url": "/documentation/appkit/views-and-controls"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-view",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/view-hierarchy",
        "doc://com.apple.appkit/documentation/AppKit/view-coordinates",
        "doc://com.apple.appkit/documentation/AppKit/nsview-appearance",
        "doc://com.apple.appkit/documentation/AppKit/core-animation-support"
      ],
      "title": "Configuring the view"
    }
  ],
  "topicSections": [
    {
      "anchor": "Managing-Contextual-Menus",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/menu(for:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/defaultMenu",
        "doc://com.apple.appkit/documentation/AppKit/NSView/willOpenMenu(_:with:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/didCloseMenu(_:with:)"
      ],
      "title": "Managing Contextual Menus"
    },
    {
      "anchor": "Responding-to-Cursor-Movements",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/addCursorRect(_:cursor:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/removeCursorRect(_:cursor:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/discardCursorRects()",
        "doc://com.apple.appkit/documentation/AppKit/NSView/resetCursorRects()"
      ],
      "title": "Responding to Cursor Movements"
    },
    {
      "anchor": "Providing-a-Tool-Tip",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/toolTip",
        "doc://com.apple.appkit/documentation/AppKit/NSView/addToolTip(_:owner:userData:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/removeAllToolTips()",
        "doc://com.apple.appkit/documentation/AppKit/NSView/removeToolTip(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/ToolTipTag"
      ],
      "title": "Providing a Tool Tip"
    },
    {
      "anchor": "Displaying-Definition-Windows",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/showDefinition(for:at:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/showDefinition(for:range:options:baselineOriginProvider:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/DefinitionOptionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSView/DefinitionPresentationType"
      ],
      "title": "Displaying Definition Windows"
    },
    {
      "anchor": "Getting-the-Focus-View",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/focusView"
      ],
      "title": "Getting the Focus View"
    },
    {
      "anchor": "Synchronizing-with-Ruler-Views",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:didAdd:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:didMove:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:didRemove:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:handleMouseDownWith:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:locationFor:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:pointForLocation:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:shouldAdd:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:shouldMove:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:shouldRemove:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:willAdd:atLocation:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:willMove:toLocation:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:willSetClientView:)"
      ],
      "title": "Synchronizing with Ruler Views"
    },
    {
      "anchor": "Synchronizing-with-the-displays-refresh-rate",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/displayLink(target:selector:)"
      ],
      "title": "Synchronizing with the displays refresh rate"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Managing-Contextual-Menus",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/menu(for:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/defaultMenu",
                "doc://com.apple.appkit/documentation/AppKit/NSView/willOpenMenu(_:with:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/didCloseMenu(_:with:)"
              ],
              "title": "Managing Contextual Menus"
            },
            {
              "anchor": "Responding-to-Cursor-Movements",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/addCursorRect(_:cursor:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/removeCursorRect(_:cursor:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/discardCursorRects()",
                "doc://com.apple.appkit/documentation/AppKit/NSView/resetCursorRects()"
              ],
              "title": "Responding to Cursor Movements"
            },
            {
              "anchor": "Providing-a-Tool-Tip",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/toolTip",
                "doc://com.apple.appkit/documentation/AppKit/NSView/addToolTip(_:owner:userData:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/removeAllToolTips()",
                "doc://com.apple.appkit/documentation/AppKit/NSView/removeToolTip(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/ToolTipTag"
              ],
              "title": "Providing a Tool Tip"
            },
            {
              "anchor": "Displaying-Definition-Windows",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/showDefinition(for:at:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/showDefinition(for:range:options:baselineOriginProvider:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/DefinitionOptionKey",
                "doc://com.apple.appkit/documentation/AppKit/NSView/DefinitionPresentationType"
              ],
              "title": "Displaying Definition Windows"
            },
            {
              "anchor": "Getting-the-Focus-View",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/focusView"
              ],
              "title": "Getting the Focus View"
            },
            {
              "anchor": "Synchronizing-with-Ruler-Views",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:didAdd:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:didMove:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:didRemove:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:handleMouseDownWith:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:locationFor:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:pointForLocation:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:shouldAdd:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:shouldMove:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:shouldRemove:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:willAdd:atLocation:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:willMove:toLocation:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/rulerView(_:willSetClientView:)"
              ],
              "title": "Synchronizing with Ruler Views"
            },
            {
              "anchor": "Synchronizing-with-the-displays-refresh-rate",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/displayLink(target:selector:)"
              ],
              "title": "Synchronizing with the displays refresh rate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-view",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/view-hierarchy",
                "doc://com.apple.appkit/documentation/AppKit/view-coordinates",
                "doc://com.apple.appkit/documentation/AppKit/nsview-appearance",
                "doc://com.apple.appkit/documentation/AppKit/core-animation-support"
              ],
              "title": "Configuring the view"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:didRemove:)/title",
          "value": "rulerView:didRemoveMarker:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:didRemove:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rulerView:didRemoveMarker:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1displayLink(target:selector:)/title",
          "value": "displayLinkWithTarget:selector:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1displayLink(target:selector:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "displayLinkWithTarget:selector:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1removeToolTip(_:)/title",
          "value": "removeToolTip:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1removeToolTip(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeToolTip:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1DefinitionOptionKey/title",
          "value": "NSDefinitionOptionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1DefinitionOptionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDefinitionOptionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1DefinitionOptionKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDefinitionOptionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1menu(for:)/title",
          "value": "menuForEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1menu(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "menuForEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:handleMouseDownWith:)/title",
          "value": "rulerView:handleMouseDown:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:handleMouseDownWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rulerView:handleMouseDown:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1willOpenMenu(_:with:)/title",
          "value": "willOpenMenu:withEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1willOpenMenu(_:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "willOpenMenu:withEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:didAdd:)/title",
          "value": "rulerView:didAddMarker:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:didAdd:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rulerView:didAddMarker:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:pointForLocation:)/title",
          "value": "rulerView:pointForLocation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:pointForLocation:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rulerView:pointForLocation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1showDefinition(for:range:options:baselineOriginProvider:)/title",
          "value": "showDefinitionForAttributedString:range:options:baselineOriginProvider:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1showDefinition(for:range:options:baselineOriginProvider:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "showDefinitionForAttributedString:range:options:baselineOriginProvider:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title",
          "value": "NSView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1didCloseMenu(_:with:)/title",
          "value": "didCloseMenu:withEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1didCloseMenu(_:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "didCloseMenu:withEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1defaultMenu/title",
          "value": "defaultMenu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1defaultMenu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultMenu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1resetCursorRects()/title",
          "value": "resetCursorRects"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1resetCursorRects()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resetCursorRects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1removeAllToolTips()/title",
          "value": "removeAllToolTips"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1removeAllToolTips()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeAllToolTips"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1focusView/title",
          "value": "focusView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1focusView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "focusView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1removeCursorRect(_:cursor:)/title",
          "value": "removeCursorRect:cursor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1removeCursorRect(_:cursor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeCursorRect:cursor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1DefinitionPresentationType/title",
          "value": "NSDefinitionPresentationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1DefinitionPresentationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDefinitionPresentationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1DefinitionPresentationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDefinitionPresentationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:locationFor:)/title",
          "value": "rulerView:locationForPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:locationFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rulerView:locationForPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:didMove:)/title",
          "value": "rulerView:didMoveMarker:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:didMove:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rulerView:didMoveMarker:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1addCursorRect(_:cursor:)/title",
          "value": "addCursorRect:cursor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1addCursorRect(_:cursor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addCursorRect:cursor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:willMove:toLocation:)/title",
          "value": "rulerView:willMoveMarker:toLocation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:willMove:toLocation:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rulerView:willMoveMarker:toLocation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1addToolTip(_:owner:userData:)/title",
          "value": "addToolTipRect:owner:userData:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1addToolTip(_:owner:userData:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addToolTipRect:owner:userData:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:shouldMove:)/title",
          "value": "rulerView:shouldMoveMarker:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:shouldMove:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rulerView:shouldMoveMarker:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:shouldRemove:)/title",
          "value": "rulerView:shouldRemoveMarker:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:shouldRemove:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rulerView:shouldRemoveMarker:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:willSetClientView:)/title",
          "value": "rulerView:willSetClientView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:willSetClientView:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rulerView:willSetClientView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:willAdd:atLocation:)/title",
          "value": "rulerView:willAddMarker:atLocation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:willAdd:atLocation:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rulerView:willAddMarker:atLocation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:shouldAdd:)/title",
          "value": "rulerView:shouldAddMarker:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rulerView(_:shouldAdd:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rulerView:shouldAddMarker:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1toolTip/title",
          "value": "toolTip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1toolTip/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "toolTip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1discardCursorRects()/title",
          "value": "discardCursorRects"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1discardCursorRects()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "discardCursorRects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1showDefinition(for:at:)/title",
          "value": "showDefinitionForAttributedString:atPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1showDefinition(for:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "showDefinitionForAttributedString:atPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1ToolTipTag/title",
          "value": "NSToolTipTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1ToolTipTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSToolTipTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1ToolTipTag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSToolTipTag"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/related-ui"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/related-ui"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
