{
  "abstract": [
    {
      "text": "Attributes that are specific to ruler views.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/deprecated-symbols",
        "doc://com.apple.appkit/documentation/AppKit/nsaccessibility"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/ruler-view-attributes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Ruler View Attributes"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/markerGroupUIElement": {
      "abstract": [
        {
          "text": "A marker group user interface element (",
          "type": "text"
        },
        {
          "code": "id",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "markerGroupUIElement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/markerGroupUIElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityMarkerGroupUIElementAttribute"
        }
      ],
      "role": "symbol",
      "title": "markerGroupUIElement",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/markergroupuielement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/markerType": {
      "abstract": [
        {
          "text": "The type of the marker (",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": "). See Ruler Marker Type Values for possible values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "markerType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/markerType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityMarkerTypeAttribute"
        }
      ],
      "role": "symbol",
      "title": "markerType",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/markertype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/markerTypeDescription": {
      "abstract": [
        {
          "text": "The description of the marker type (",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "markerTypeDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/markerTypeDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityMarkerTypeDescriptionAttribute"
        }
      ],
      "role": "symbol",
      "title": "markerTypeDescription",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/markertypedescription"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/markerUIElements": {
      "abstract": [
        {
          "text": "An array of marker user interface elements (",
          "type": "text"
        },
        {
          "code": "NSArray",
          "type": "codeVoice"
        },
        {
          "text": ")",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "markerUIElements"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/markerUIElements",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityMarkerUIElementsAttribute"
        }
      ],
      "role": "symbol",
      "title": "markerUIElements",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/markeruielements"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/markerValues": {
      "abstract": [
        {
          "text": "The marker values (",
          "type": "text"
        },
        {
          "code": "NSArray",
          "type": "codeVoice"
        },
        {
          "text": " of ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "markerValues"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/markerValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityMarkerValuesAttribute"
        }
      ],
      "role": "symbol",
      "title": "markerValues",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/markervalues"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/unitDescription": {
      "abstract": [
        {
          "text": "The description of ruler units (",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unitDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/unitDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityUnitDescriptionAttribute"
        }
      ],
      "role": "symbol",
      "title": "unitDescription",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/unitdescription"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/units": {
      "abstract": [
        {
          "text": "The ruler units (",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": "). See Measurement Unit Attributes for possible values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "units"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityAttributeName",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/units",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityUnitsAttribute"
        }
      ],
      "role": "symbol",
      "title": "units",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute/units"
    },
    "doc://com.apple.appkit/documentation/AppKit/app-specific-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to the app object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/app-specific-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App-Specific Attributes",
      "type": "topic",
      "url": "/documentation/appkit/app-specific-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/cell-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to individual table cells.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/cell-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cell Attributes",
      "type": "topic",
      "url": "/documentation/appkit/cell-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/cell-based-table-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to cell-based tables.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/cell-based-table-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cell-Based Table Attributes",
      "type": "topic",
      "url": "/documentation/appkit/cell-based-table-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/cell-based-table-parameterized-attributes": {
      "abstract": [
        {
          "text": "Parameterized attributes specific to cell-based tables.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/cell-based-table-parameterized-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cell-Based Table Parameterized Attributes",
      "type": "topic",
      "url": "/documentation/appkit/cell-based-table-parameterized-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review symbols that are no longer supported, and find the replacements to use instead.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/appkit/deprecated-symbols"
    },
    "doc://com.apple.appkit/documentation/AppKit/grid-view-attributes": {
      "abstract": [
        {
          "text": "Attributes that are used with grid views, such as thumbnails and media browsers that present a grid of items. The children of a grid are ordered.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/grid-view-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Grid View Attributes",
      "type": "topic",
      "url": "/documentation/appkit/grid-view-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/layout-area-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to layout areas.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/layout-area-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layout Area Attributes",
      "type": "topic",
      "url": "/documentation/appkit/layout-area-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/layout-area-parameterized-attributes": {
      "abstract": [
        {
          "text": "Parameterized attributes that are specific to layout areas.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/layout-area-parameterized-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layout Area Parameterized Attributes",
      "type": "topic",
      "url": "/documentation/appkit/layout-area-parameterized-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/layout-item-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to the items in a layout area.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/layout-item-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layout Item Attributes",
      "type": "topic",
      "url": "/documentation/appkit/layout-item-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/nsaccessibility": {
      "abstract": [
        {
          "text": "A legacy, informal protocol that Apple doesn’t recommend for active use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nsaccessibility",
      "kind": "article",
      "role": "collectionGroup",
      "title": "NSAccessibility",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility"
    },
    "doc://com.apple.appkit/documentation/AppKit/outline-view-attributes": {
      "abstract": [
        {
          "text": "Attributes that are used in outline views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/outline-view-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Outline View Attributes",
      "type": "topic",
      "url": "/documentation/appkit/outline-view-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/standard-attributes": {
      "abstract": [
        {
          "text": "Standard attributes that can be adopted by any accessibility object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/standard-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Standard Attributes",
      "type": "topic",
      "url": "/documentation/appkit/standard-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/table-view-and-outline-view-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to tables and outlines.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/table-view-and-outline-view-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Table View and Outline View Attributes",
      "type": "topic",
      "url": "/documentation/appkit/table-view-and-outline-view-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/text-attributed-string-attributes-and-constants": {
      "abstract": [
        {
          "text": "Attributes and key constants used with attributed strings.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/text-attributed-string-attributes-and-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text Attributed-String Attributes and Constants",
      "type": "topic",
      "url": "/documentation/appkit/text-attributed-string-attributes-and-constants"
    },
    "doc://com.apple.appkit/documentation/AppKit/text-specific-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/text-specific-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text-Specific Attributes",
      "type": "topic",
      "url": "/documentation/appkit/text-specific-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/text-specific-parameterized-attributes": {
      "abstract": [
        {
          "text": "Parameterized attributes specific to text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/text-specific-parameterized-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text-Specific Parameterized Attributes",
      "type": "topic",
      "url": "/documentation/appkit/text-specific-parameterized-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/window-specific-attributes": {
      "abstract": [
        {
          "text": "Attributes specific to windows.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/window-specific-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Window-Specific Attributes",
      "type": "topic",
      "url": "/documentation/appkit/window-specific-attributes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/standard-attributes",
        "doc://com.apple.appkit/documentation/AppKit/text-specific-attributes",
        "doc://com.apple.appkit/documentation/AppKit/text-specific-parameterized-attributes",
        "doc://com.apple.appkit/documentation/AppKit/text-attributed-string-attributes-and-constants",
        "doc://com.apple.appkit/documentation/AppKit/window-specific-attributes",
        "doc://com.apple.appkit/documentation/AppKit/app-specific-attributes",
        "doc://com.apple.appkit/documentation/AppKit/grid-view-attributes",
        "doc://com.apple.appkit/documentation/AppKit/table-view-and-outline-view-attributes",
        "doc://com.apple.appkit/documentation/AppKit/outline-view-attributes",
        "doc://com.apple.appkit/documentation/AppKit/cell-based-table-attributes",
        "doc://com.apple.appkit/documentation/AppKit/cell-based-table-parameterized-attributes",
        "doc://com.apple.appkit/documentation/AppKit/cell-attributes",
        "doc://com.apple.appkit/documentation/AppKit/layout-area-attributes",
        "doc://com.apple.appkit/documentation/AppKit/layout-area-parameterized-attributes",
        "doc://com.apple.appkit/documentation/AppKit/layout-item-attributes"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/markerGroupUIElement",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/markerType",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/markerTypeDescription",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/markerUIElements",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/markerValues",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/unitDescription",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/units"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/markerGroupUIElement",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/markerType",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/markerTypeDescription",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/markerUIElements",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/markerValues",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/unitDescription",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute/units"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/standard-attributes",
                "doc://com.apple.appkit/documentation/AppKit/text-specific-attributes",
                "doc://com.apple.appkit/documentation/AppKit/text-specific-parameterized-attributes",
                "doc://com.apple.appkit/documentation/AppKit/text-attributed-string-attributes-and-constants",
                "doc://com.apple.appkit/documentation/AppKit/window-specific-attributes",
                "doc://com.apple.appkit/documentation/AppKit/app-specific-attributes",
                "doc://com.apple.appkit/documentation/AppKit/grid-view-attributes",
                "doc://com.apple.appkit/documentation/AppKit/table-view-and-outline-view-attributes",
                "doc://com.apple.appkit/documentation/AppKit/outline-view-attributes",
                "doc://com.apple.appkit/documentation/AppKit/cell-based-table-attributes",
                "doc://com.apple.appkit/documentation/AppKit/cell-based-table-parameterized-attributes",
                "doc://com.apple.appkit/documentation/AppKit/cell-attributes",
                "doc://com.apple.appkit/documentation/AppKit/layout-area-attributes",
                "doc://com.apple.appkit/documentation/AppKit/layout-area-parameterized-attributes",
                "doc://com.apple.appkit/documentation/AppKit/layout-item-attributes"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1markerType/title",
          "value": "NSAccessibilityMarkerTypeAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1markerType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityMarkerTypeAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1markerUIElements/title",
          "value": "NSAccessibilityMarkerUIElementsAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1markerUIElements/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityMarkerUIElementsAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1units/title",
          "value": "NSAccessibilityUnitsAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1units/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityUnitsAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1markerTypeDescription/title",
          "value": "NSAccessibilityMarkerTypeDescriptionAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1markerTypeDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityMarkerTypeDescriptionAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1unitDescription/title",
          "value": "NSAccessibilityUnitDescriptionAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1unitDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityUnitDescriptionAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1markerGroupUIElement/title",
          "value": "NSAccessibilityMarkerGroupUIElementAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1markerGroupUIElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityMarkerGroupUIElementAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1markerValues/title",
          "value": "NSAccessibilityMarkerValuesAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute~1markerValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityMarkerValuesAttribute"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/ruler-view-attributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/ruler-view-attributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
