{
  "abstract": [
    {
      "text": "The following constants are used to describe special cases for a controller’s selection.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/cocoa-bindings",
        "doc://com.apple.appkit/documentation/AppKit/nsplaceholders"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/selection-markers"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Selection Markers"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMultipleValuesMarker": {
      "abstract": [
        {
          "text": "This marker indicates that a key’s value contains multiple values that differ.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMultipleValuesMarker"
        },
        {
          "kind": "text",
          "text": ": AnyObject"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMultipleValuesMarker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMultipleValuesMarker"
        }
      ],
      "role": "symbol",
      "title": "NSMultipleValuesMarker",
      "type": "topic",
      "url": "/documentation/appkit/nsmultiplevaluesmarker"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSNoSelectionMarker": {
      "abstract": [
        {
          "text": "This marker indicates that the controller’s selection is currently empty.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSNoSelectionMarker"
        },
        {
          "kind": "text",
          "text": ": AnyObject"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSNoSelectionMarker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSNoSelectionMarker"
        }
      ],
      "role": "symbol",
      "title": "NSNoSelectionMarker",
      "type": "topic",
      "url": "/documentation/appkit/nsnoselectionmarker"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSNotApplicableMarker": {
      "abstract": [
        {
          "text": "This marker indicates that an object is not key-value coding compliant for the requested key.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSNotApplicableMarker"
        },
        {
          "kind": "text",
          "text": ": AnyObject"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSNotApplicableMarker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSNotApplicableMarker"
        }
      ],
      "role": "symbol",
      "title": "NSNotApplicableMarker",
      "type": "topic",
      "url": "/documentation/appkit/nsnotapplicablemarker"
    },
    "doc://com.apple.appkit/documentation/AppKit/cocoa-bindings": {
      "abstract": [
        {
          "text": "Automatically synchronize your data model with your app’s interface using Cocoa Bindings.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/cocoa-bindings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cocoa Bindings",
      "type": "topic",
      "url": "/documentation/appkit/cocoa-bindings"
    },
    "doc://com.apple.appkit/documentation/AppKit/nsplaceholders": {
      "abstract": [
        {
          "text": "A set of methods that an object can implement to register default placeholders to be displayed for a binding, when no other placeholder is specified.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nsplaceholders",
      "kind": "article",
      "role": "collectionGroup",
      "title": "NSPlaceholders",
      "type": "topic",
      "url": "/documentation/appkit/nsplaceholders"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSMultipleValuesMarker",
        "doc://com.apple.appkit/documentation/AppKit/NSNoSelectionMarker",
        "doc://com.apple.appkit/documentation/AppKit/NSNotApplicableMarker"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSMultipleValuesMarker",
                "doc://com.apple.appkit/documentation/AppKit/NSNoSelectionMarker",
                "doc://com.apple.appkit/documentation/AppKit/NSNotApplicableMarker"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSNoSelectionMarker/title",
          "value": "NSNoSelectionMarker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSNoSelectionMarker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSNoSelectionMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMultipleValuesMarker/title",
          "value": "NSMultipleValuesMarker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMultipleValuesMarker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMultipleValuesMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSNotApplicableMarker/title",
          "value": "NSNotApplicableMarker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSNotApplicableMarker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSNotApplicableMarker"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/selection-markers"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/selection-markers"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
