{
  "abstract": [
    {
      "text": "Configure the contents of your app’s Services menu.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/app-and-environment"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/services-functions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Services Functions"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCloudSharingServiceDelegate": {
      "abstract": [
        {
          "text": "A set of methods for responding to the life cycle events of the cloud-sharing service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCloudSharingServiceDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCloudSharingServiceDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCloudSharingServiceDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSCloudSharingServiceDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nscloudsharingservicedelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPerformService(_:_:)": {
      "abstract": [
        {
          "text": "Programmatically invokes a Services menu service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPerformService"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPerformService(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPerformService"
        }
      ],
      "role": "symbol",
      "title": "NSPerformService(_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsperformservice(_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPreviewRepresentableActivityItem": {
      "abstract": [
        {
          "text": "An interface you adopt in custom objects that you want to share using the macOS share sheet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPreviewRepresentableActivityItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPreviewRepresentableActivityItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPreviewRepresentableActivityItem"
        }
      ],
      "role": "symbol",
      "title": "NSPreviewRepresentableActivityItem",
      "type": "topic",
      "url": "/documentation/appkit/nspreviewrepresentableactivityitem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRegisterServicesProvider(_:_:)": {
      "abstract": [
        {
          "text": "Registers a service provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSRegisterServicesProvider"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSServiceProviderName",
          "text": "NSServiceProviderName"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRegisterServicesProvider(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRegisterServicesProvider"
        }
      ],
      "role": "symbol",
      "title": "NSRegisterServicesProvider(_:_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsregisterservicesprovider(_:_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSServiceProviderName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSServiceProviderName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSServiceProviderName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSServiceProviderName"
        }
      ],
      "role": "symbol",
      "title": "NSServiceProviderName",
      "type": "topic",
      "url": "/documentation/appkit/nsserviceprovidername"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSServicesMenuRequestor": {
      "abstract": [
        {
          "text": "A set of methods that support interaction with items users can share through a sharing service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSServicesMenuRequestor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSServicesMenuRequestor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSServicesMenuRequestor"
        }
      ],
      "role": "symbol",
      "title": "NSServicesMenuRequestor",
      "type": "topic",
      "url": "/documentation/appkit/nsservicesmenurequestor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingService": {
      "abstract": [
        {
          "text": "An object that facilitates the sharing of content with social media services, or with apps like Mail or Safari.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSharingService"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingService"
        }
      ],
      "role": "symbol",
      "title": "NSSharingService",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservice"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingServicePicker": {
      "abstract": [
        {
          "text": "A list of sharing services that the user can choose from.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSharingServicePicker"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingServicePicker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingServicePicker"
        }
      ],
      "role": "symbol",
      "title": "NSSharingServicePicker",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservicepicker"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerToolbarItem": {
      "abstract": [
        {
          "text": "A toolbar item that displays the macOS share sheet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSharingServicePickerToolbarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerToolbarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingServicePickerToolbarItem"
        }
      ],
      "role": "symbol",
      "title": "NSSharingServicePickerToolbarItem",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservicepickertoolbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnregisterServicesProvider(_:)": {
      "abstract": [
        {
          "text": "Unregisters a service provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUnregisterServicesProvider"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSServiceProviderName",
          "text": "NSServiceProviderName"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnregisterServicesProvider(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnregisterServicesProvider"
        }
      ],
      "role": "symbol",
      "title": "NSUnregisterServicesProvider(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsunregisterservicesprovider(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUpdateDynamicServices()": {
      "abstract": [
        {
          "text": "Causes the services information for the system to be updated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUpdateDynamicServices"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUpdateDynamicServices()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUpdateDynamicServices"
        }
      ],
      "role": "symbol",
      "title": "NSUpdateDynamicServices()",
      "type": "topic",
      "url": "/documentation/appkit/nsupdatedynamicservices()"
    },
    "doc://com.apple.appkit/documentation/AppKit/app-and-environment": {
      "abstract": [
        {
          "text": "Learn about the objects that you use to interact with the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/app-and-environment",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App and Environment",
      "type": "topic",
      "url": "/documentation/appkit/app-and-environment"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "App-Services",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSharingService",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingServicePicker",
        "doc://com.apple.appkit/documentation/AppKit/NSPreviewRepresentableActivityItem",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerToolbarItem",
        "doc://com.apple.appkit/documentation/AppKit/NSServicesMenuRequestor",
        "doc://com.apple.appkit/documentation/AppKit/NSCloudSharingServiceDelegate"
      ],
      "title": "App Services"
    }
  ],
  "topicSections": [
    {
      "anchor": "Registering-Services",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSRegisterServicesProvider(_:_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSUnregisterServicesProvider(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSUpdateDynamicServices()",
        "doc://com.apple.appkit/documentation/AppKit/NSServiceProviderName"
      ],
      "title": "Registering Services"
    },
    {
      "anchor": "Performing-Services",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPerformService(_:_:)"
      ],
      "title": "Performing Services"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Registering-Services",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSRegisterServicesProvider(_:_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSUnregisterServicesProvider(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSUpdateDynamicServices()",
                "doc://com.apple.appkit/documentation/AppKit/NSServiceProviderName"
              ],
              "title": "Registering Services"
            },
            {
              "anchor": "Performing-Services",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPerformService(_:_:)"
              ],
              "title": "Performing Services"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "App-Services",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSharingService",
                "doc://com.apple.appkit/documentation/AppKit/NSSharingServicePicker",
                "doc://com.apple.appkit/documentation/AppKit/NSPreviewRepresentableActivityItem",
                "doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerToolbarItem",
                "doc://com.apple.appkit/documentation/AppKit/NSServicesMenuRequestor",
                "doc://com.apple.appkit/documentation/AppKit/NSCloudSharingServiceDelegate"
              ],
              "title": "App Services"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUpdateDynamicServices()/title",
          "value": "NSUpdateDynamicServices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUpdateDynamicServices()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUpdateDynamicServices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSServicesMenuRequestor/title",
          "value": "NSServicesMenuRequestor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSServicesMenuRequestor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSServicesMenuRequestor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSServicesMenuRequestor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSServicesMenuRequestor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCloudSharingServiceDelegate/title",
          "value": "NSCloudSharingServiceDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCloudSharingServiceDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCloudSharingServiceDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCloudSharingServiceDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCloudSharingServiceDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService/title",
          "value": "NSSharingService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingService/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerToolbarItem/title",
          "value": "NSSharingServicePickerToolbarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerToolbarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServicePickerToolbarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerToolbarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServicePickerToolbarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePicker/title",
          "value": "NSSharingServicePicker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePicker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServicePicker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePicker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServicePicker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPerformService(_:_:)/title",
          "value": "NSPerformService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPerformService(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPerformService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnregisterServicesProvider(_:)/title",
          "value": "NSUnregisterServicesProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnregisterServicesProvider(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnregisterServicesProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSServiceProviderName/title",
          "value": "NSServiceProviderName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSServiceProviderName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSServiceProviderName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSServiceProviderName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSServiceProviderName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRegisterServicesProvider(_:_:)/title",
          "value": "NSRegisterServicesProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRegisterServicesProvider(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRegisterServicesProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPreviewRepresentableActivityItem/title",
          "value": "NSPreviewRepresentableActivityItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPreviewRepresentableActivityItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPreviewRepresentableActivityItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPreviewRepresentableActivityItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPreviewRepresentableActivityItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/services-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/services-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
