{
  "abstract": [
    {
      "text": "Retrieve the standard color objects for common colors like red, blue, green, black, white, and more.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/color",
        "doc://com.apple.appkit/documentation/AppKit/NSColor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/standard-colors"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Standard Colors"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For design guidance, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/color#system-colors",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor": {
      "abstract": [
        {
          "text": "An object that stores color data and sometimes opacity (alpha value).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColor"
        }
      ],
      "role": "symbol",
      "title": "NSColor",
      "type": "topic",
      "url": "/documentation/appkit/nscolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/black": {
      "abstract": [
        {
          "text": "Returns a color object whose grayscale value is ",
          "type": "text"
        },
        {
          "code": "0.0",
          "type": "codeVoice"
        },
        {
          "text": " and whose alpha value is ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "black"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/black",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "blackColor"
        }
      ],
      "role": "symbol",
      "title": "black",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/black"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/blue": {
      "abstract": [
        {
          "text": "Returns a color object whose RGB value is ",
          "type": "text"
        },
        {
          "code": "0.0",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "0.0",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": " and whose alpha value is ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "blue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/blue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "blueColor"
        }
      ],
      "role": "symbol",
      "title": "blue",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/blue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/brown": {
      "abstract": [
        {
          "text": "Returns a color object whose RGB value is ",
          "type": "text"
        },
        {
          "code": "0.6",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "0.4",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "0.2",
          "type": "codeVoice"
        },
        {
          "text": " and whose alpha value is ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "brown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/brown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "brownColor"
        }
      ],
      "role": "symbol",
      "title": "brown",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/brown"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/clear": {
      "abstract": [
        {
          "text": "Returns a color object whose grayscale and alpha values are both ",
          "type": "text"
        },
        {
          "code": "0.0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/clear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clearColor"
        }
      ],
      "role": "symbol",
      "title": "clear",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/clear"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/cyan": {
      "abstract": [
        {
          "text": "Returns a color object whose RGB value is ",
          "type": "text"
        },
        {
          "code": "0.0",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": " and whose alpha value is ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cyan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/cyan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cyanColor"
        }
      ],
      "role": "symbol",
      "title": "cyan",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/cyan"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/darkGray": {
      "abstract": [
        {
          "text": "Returns a color object whose grayscale value is ",
          "type": "text"
        },
        {
          "code": "1/3",
          "type": "codeVoice"
        },
        {
          "text": " and whose alpha value is ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "darkGray"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/darkGray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "darkGrayColor"
        }
      ],
      "role": "symbol",
      "title": "darkGray",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/darkgray"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/gray": {
      "abstract": [
        {
          "text": "Returns a color object whose grayscale value is ",
          "type": "text"
        },
        {
          "code": "0.5",
          "type": "codeVoice"
        },
        {
          "text": " and whose alpha value is ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gray"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/gray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "grayColor"
        }
      ],
      "role": "symbol",
      "title": "gray",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/gray"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/green": {
      "abstract": [
        {
          "text": "Returns a color object whose RGB value is ",
          "type": "text"
        },
        {
          "code": "0.0",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "0.0",
          "type": "codeVoice"
        },
        {
          "text": " and whose alpha value is ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "green"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/green",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "greenColor"
        }
      ],
      "role": "symbol",
      "title": "green",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/green"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/lightGray": {
      "abstract": [
        {
          "text": "Returns a color object whose grayscale value is ",
          "type": "text"
        },
        {
          "code": "2/3",
          "type": "codeVoice"
        },
        {
          "text": " and whose alpha value is ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lightGray"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/lightGray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lightGrayColor"
        }
      ],
      "role": "symbol",
      "title": "lightGray",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/lightgray"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/magenta": {
      "abstract": [
        {
          "text": "Returns a color object whose RGB value is ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "0.0",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": " and whose alpha value is ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "magenta"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/magenta",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "magentaColor"
        }
      ],
      "role": "symbol",
      "title": "magenta",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/magenta"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/orange": {
      "abstract": [
        {
          "text": "Returns a color object whose RGB value is ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "0.5",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "0.0",
          "type": "codeVoice"
        },
        {
          "text": " and whose alpha value is ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/orange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "orangeColor"
        }
      ],
      "role": "symbol",
      "title": "orange",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/orange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/purple": {
      "abstract": [
        {
          "text": "Returns a color object whose RGB value is ",
          "type": "text"
        },
        {
          "code": "0.5",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "0.0",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "0.5",
          "type": "codeVoice"
        },
        {
          "text": " and whose alpha value is ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "purple"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/purple",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "purpleColor"
        }
      ],
      "role": "symbol",
      "title": "purple",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/purple"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/red": {
      "abstract": [
        {
          "text": "Returns a color object whose RGB value is ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "0.0",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "0.0",
          "type": "codeVoice"
        },
        {
          "text": " and whose alpha value is ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "red"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/red",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "redColor"
        }
      ],
      "role": "symbol",
      "title": "red",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/red"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/systemBlue": {
      "abstract": [
        {
          "text": "Returns a color object for blue that automatically adapts to vibrancy and accessibility settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemBlue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/systemBlue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "systemBlueColor"
        }
      ],
      "role": "symbol",
      "title": "systemBlue",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/systemblue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/systemBrown": {
      "abstract": [
        {
          "text": "Returns a color object for brown that automatically adapts to vibrancy and accessibility settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemBrown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/systemBrown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "systemBrownColor"
        }
      ],
      "role": "symbol",
      "title": "systemBrown",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/systembrown"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/systemCyan": {
      "abstract": [
        {
          "text": "Returns a color object for cyan that automatically adapts to vibrancy and accessibility settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemCyan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/systemCyan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "systemCyanColor"
        }
      ],
      "role": "symbol",
      "title": "systemCyan",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/systemcyan"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/systemGray": {
      "abstract": [
        {
          "text": "Returns a color object for gray that automatically adapts to vibrancy and accessibility settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemGray"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/systemGray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "systemGrayColor"
        }
      ],
      "role": "symbol",
      "title": "systemGray",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/systemgray"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/systemGreen": {
      "abstract": [
        {
          "text": "Returns a color object for green that automatically adapts to vibrancy and accessibility settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemGreen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/systemGreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "systemGreenColor"
        }
      ],
      "role": "symbol",
      "title": "systemGreen",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/systemgreen"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/systemIndigo": {
      "abstract": [
        {
          "text": "Returns a color object for indigo that automatically adapts to vibrancy and accessibility settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemIndigo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/systemIndigo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "systemIndigoColor"
        }
      ],
      "role": "symbol",
      "title": "systemIndigo",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/systemindigo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/systemMint": {
      "abstract": [
        {
          "text": "Returns a color object for mint that automatically adapts to vibrancy and accessibility settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemMint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/systemMint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "systemMintColor"
        }
      ],
      "role": "symbol",
      "title": "systemMint",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/systemmint"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/systemOrange": {
      "abstract": [
        {
          "text": "Returns a color object for orange that automatically adapts to vibrancy and accessibility settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemOrange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/systemOrange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "systemOrangeColor"
        }
      ],
      "role": "symbol",
      "title": "systemOrange",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/systemorange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/systemPink": {
      "abstract": [
        {
          "text": "Returns a color object for pink that automatically adapts to vibrancy and accessibility settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemPink"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/systemPink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "systemPinkColor"
        }
      ],
      "role": "symbol",
      "title": "systemPink",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/systempink"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/systemPurple": {
      "abstract": [
        {
          "text": "Returns a color object for purple that automatically adapts to vibrancy and accessibility settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemPurple"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/systemPurple",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "systemPurpleColor"
        }
      ],
      "role": "symbol",
      "title": "systemPurple",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/systempurple"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/systemRed": {
      "abstract": [
        {
          "text": "Returns a color object for red that automatically adapts to vibrancy and accessibility settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemRed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/systemRed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "systemRedColor"
        }
      ],
      "role": "symbol",
      "title": "systemRed",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/systemred"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/systemTeal": {
      "abstract": [
        {
          "text": "Returns a color object for teal that automatically adapts to vibrancy and accessibility settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemTeal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/systemTeal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "systemTealColor"
        }
      ],
      "role": "symbol",
      "title": "systemTeal",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/systemteal"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/systemYellow": {
      "abstract": [
        {
          "text": "Returns a color object for yellow that automatically adapts to vibrancy and accessibility settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemYellow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/systemYellow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "systemYellowColor"
        }
      ],
      "role": "symbol",
      "title": "systemYellow",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/systemyellow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/white": {
      "abstract": [
        {
          "text": "Returns a color object whose grayscale and alpha values are both ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "white"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/white",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "whiteColor"
        }
      ],
      "role": "symbol",
      "title": "white",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/white"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/yellow": {
      "abstract": [
        {
          "text": "Returns a color object whose RGB value is ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "0.0",
          "type": "codeVoice"
        },
        {
          "text": " and whose alpha value is ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "yellow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/yellow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "yellowColor"
        }
      ],
      "role": "symbol",
      "title": "yellow",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/yellow"
    },
    "doc://com.apple.appkit/documentation/AppKit/color": {
      "abstract": [
        {
          "text": "Represent colors using built-in or custom formats, and give users options for selecting and applying colors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/color",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Color",
      "type": "topic",
      "url": "/documentation/appkit/color"
    },
    "doc://com.apple.appkit/documentation/AppKit/color-creation": {
      "abstract": [
        {
          "text": "Load colors from asset catalogs, and create colors from raw component values, such as those used by grayscale, RGB, HSB, and CMYK colors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/color-creation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Color Creation",
      "type": "topic",
      "url": "/documentation/appkit/color-creation"
    },
    "doc://com.apple.appkit/documentation/AppKit/ui-element-colors": {
      "abstract": [
        {
          "text": "Retrieve standard color objects for use with windows, controls, labels, text, selections and other content in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/ui-element-colors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "UI Element Colors",
      "type": "topic",
      "url": "/documentation/appkit/ui-element-colors"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/color#system-colors": {
      "identifier": "https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/color#system-colors",
      "title": "Human Interface Guidelines",
      "titleInlineContent": [
        {
          "text": "Human Interface Guidelines",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/color#system-colors"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-and-Creating-Colors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/ui-element-colors",
        "doc://com.apple.appkit/documentation/AppKit/color-creation"
      ],
      "title": "Getting and Creating Colors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Adaptable-System-Colors",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColor/systemBlue",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/systemBrown",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/systemCyan",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/systemGray",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/systemGreen",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/systemIndigo",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/systemMint",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/systemOrange",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/systemPink",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/systemPurple",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/systemRed",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/systemTeal",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/systemYellow"
      ],
      "title": "Adaptable System Colors"
    },
    {
      "anchor": "Transparent-Color",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColor/clear"
      ],
      "title": "Transparent Color"
    },
    {
      "anchor": "Fixed-Colors",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColor/black",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/blue",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/brown",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/cyan",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/darkGray",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/gray",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/green",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/lightGray",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/magenta",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/orange",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/purple",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/red",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/white",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/yellow"
      ],
      "title": "Fixed Colors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Adaptable-System-Colors",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColor/systemBlue",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/systemBrown",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/systemCyan",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/systemGray",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/systemGreen",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/systemIndigo",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/systemMint",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/systemOrange",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/systemPink",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/systemPurple",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/systemRed",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/systemTeal",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/systemYellow"
              ],
              "title": "Adaptable System Colors"
            },
            {
              "anchor": "Transparent-Color",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColor/clear"
              ],
              "title": "Transparent Color"
            },
            {
              "anchor": "Fixed-Colors",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColor/black",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/blue",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/brown",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/cyan",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/darkGray",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/gray",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/green",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/lightGray",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/magenta",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/orange",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/purple",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/red",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/white",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/yellow"
              ],
              "title": "Fixed Colors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-and-Creating-Colors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/ui-element-colors",
                "doc://com.apple.appkit/documentation/AppKit/color-creation"
              ],
              "title": "Getting and Creating Colors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1clear/title",
          "value": "clearColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1clear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "clearColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1white/title",
          "value": "whiteColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1white/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "whiteColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1purple/title",
          "value": "purpleColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1purple/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "purpleColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1brown/title",
          "value": "brownColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1brown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "brownColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1systemIndigo/title",
          "value": "systemIndigoColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1systemIndigo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "systemIndigoColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1systemRed/title",
          "value": "systemRedColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1systemRed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "systemRedColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1systemPink/title",
          "value": "systemPinkColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1systemPink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "systemPinkColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor/title",
          "value": "NSColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1systemPurple/title",
          "value": "systemPurpleColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1systemPurple/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "systemPurpleColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1systemGreen/title",
          "value": "systemGreenColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1systemGreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "systemGreenColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1systemYellow/title",
          "value": "systemYellowColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1systemYellow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "systemYellowColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1blue/title",
          "value": "blueColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1blue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "blueColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1systemBlue/title",
          "value": "systemBlueColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1systemBlue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "systemBlueColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1systemGray/title",
          "value": "systemGrayColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1systemGray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "systemGrayColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1green/title",
          "value": "greenColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1green/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "greenColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1systemCyan/title",
          "value": "systemCyanColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1systemCyan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "systemCyanColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1cyan/title",
          "value": "cyanColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1cyan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cyanColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1systemTeal/title",
          "value": "systemTealColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1systemTeal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "systemTealColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1red/title",
          "value": "redColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1red/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "redColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1gray/title",
          "value": "grayColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1gray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "grayColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1darkGray/title",
          "value": "darkGrayColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1darkGray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "darkGrayColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1magenta/title",
          "value": "magentaColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1magenta/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "magentaColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1yellow/title",
          "value": "yellowColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1yellow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "yellowColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1orange/title",
          "value": "orangeColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1orange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "orangeColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1lightGray/title",
          "value": "lightGrayColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1lightGray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lightGrayColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1black/title",
          "value": "blackColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1black/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "blackColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1systemOrange/title",
          "value": "systemOrangeColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1systemOrange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "systemOrangeColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1systemBrown/title",
          "value": "systemBrownColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1systemBrown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "systemBrownColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1systemMint/title",
          "value": "systemMintColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1systemMint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "systemMintColor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/standard-colors"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/standard-colors"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
