{
  "abstract": [
    {
      "text": "Incorporate scanned documents and pictures from a user’s iPhone, iPad, or iPod touch into your Mac app using Continuity Camera.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/images-and-pdf"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/supporting-continuity-camera-in-your-mac-app"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Supporting Continuity Camera in Your Mac App"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "With Continuity Camera in macOS 10.14 and later, and iOS 12 and later, you can use your iPhone, iPad, or iPod touch to scan documents or take a picture of something nearby and then access those documents or pictures instantly from your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your app works with images, this feature can be a convenient way to get images into the app. For example, a text-editing app can use this feature to easily incorporate images into a document. It can also be a handy way to bring images into a social media app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Apps using ",
              "type": "text"
            },
            {
              "code": "NSTextView",
              "type": "codeVoice"
            },
            {
              "text": " get Continuity Camera support automatically. When the user Control-clicks in an app’s text view, a Continuity Camera menu item appears. The user can then capture a photo or scan a document on their iPhone or iPad, and it automatically appears in the text view. The image is then accessible as an attachment in the ",
              "type": "text"
            },
            {
              "code": "NSTextView",
              "type": "codeVoice"
            },
            {
              "text": " text storage object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3993602",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you’re not using ",
              "type": "text"
            },
            {
              "code": "NSTextView",
              "type": "codeVoice"
            },
            {
              "text": ", you need to add support to your macOS interface to enable Continuity Camera, and to merge photos taken from the user’s iOS device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Enable-Support-in-Your-Responder-Objects",
          "level": 3,
          "text": "Enable Support in Your Responder Objects",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You must tell AppKit that your app can take advantage of any image data originating from Continuity Camera. You do this in responder objects, such as a view controller.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When the Continuity Camera menu item appears, AppKit calls the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSResponder/validRequestor(forSendType:returnType:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method of your responder objects in the current responder chain to find an object that can handle image data from Continuity Camera. Override this method to let AppKit know that your responder object supports image data that Continuity Camera generates. When the user captures a photo or scans a document using Continuity Camera, AppKit places the image data on the pasteboard and calls the designated responder object to handle the data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Your responder’s ",
              "type": "text"
            },
            {
              "code": "validRequestor(forSendType:returnType:)",
              "type": "codeVoice"
            },
            {
              "text": " implementation must verify that it can receive pasteboard image data of the specified type, then return the object to receive the image data when AppKit places it on the pasteboard. Your ",
              "type": "text"
            },
            {
              "code": "validRequestor(forSendType:returnType:)",
              "type": "codeVoice"
            },
            {
              "text": " method can designate the same receiver object to handle the image data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Here’s an example implementation:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "override func validRequestor(forSendType sendType: NSPasteboard.PasteboardType?, returnType: NSPasteboard.PasteboardType?) -> Any? {",
            "    if let pasteboardType = returnType,",
            "        // The service is image-related.",
            "        NSImage.imageTypes.contains(pasteboardType.rawValue) {",
            "        return self  // This object can receive image data.",
            "    } else {",
            "        // Let objects in the responder chain handle the message.",
            "        return super.validRequestor(forSendType: sendType, returnType: returnType)",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Note that your ",
              "type": "text"
            },
            {
              "code": "validRequestor(forSendType:returnType:)",
              "type": "codeVoice"
            },
            {
              "text": " method can return a different object to receive the image data. For example, implement the ",
              "type": "text"
            },
            {
              "code": "validRequestor(forSendType:returnType:)",
              "type": "codeVoice"
            },
            {
              "text": " method in your view controller and perform the checks, but return a view object to incorporate the data. You can also return a parent or managing object instead. For example, the following code implements ",
              "type": "text"
            },
            {
              "code": "validRequestor(forSendType:returnType:)",
              "type": "codeVoice"
            },
            {
              "text": " in a window controller, but returns the active view controller to target the pasted image:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "override func validRequestor(forSendType sendType: NSPasteboard.PasteboardType?, returnType: NSPasteboard.PasteboardType?) -> Any? {",
            "    if let pasteboardType = returnType,",
            "        // The service is image-related.",
            "        NSImage.imageTypes.contains(pasteboardType.rawValue) {",
            "        // Specify the active view controller to receive the image data.",
            "        return self.contentViewController  ",
            "    } else {",
            "        // Let objects in the responder chain handle the message.",
            "        return super.validRequestor(forSendType: sendType, returnType: returnType)",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "After you implement ",
              "type": "text"
            },
            {
              "code": "validRequestor(forSendType:returnType:)",
              "type": "codeVoice"
            },
            {
              "text": " and specify an object to receive the image data, AppKit enables the Continuity Camera menu item for the designated menus in your app, including contextual menus associated with your view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-a-Continuity-Camera-Menu-Item",
          "level": 3,
          "text": "Add a Continuity Camera Menu Item",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The user initiates Continuity Camera by using a menu item in one of your app’s menu bar menus or contextual menus. You can add a Continuity Camera menu item to any of your app’s menu bar menus, or have AppKit automatically add a Continuity Camera menu item to one of your app’s contextual menus. A good place to include a Continuity Camera menu item is in menus that contain options for performing editing-related activities, such as the File and Insert menus.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To add a Continuity Camera menu item to one of your app’s menu bar menus, locate the storyboard file where your menu bar is defined, and follow these steps in Interface Builder:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add an item to your app’s menu.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set the name of the item, such as “Take Picture.” AppKit provides the name later.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In the Identity inspector, set the Identifier property of the menu item to ",
                      "type": "text"
                    },
                    {
                      "code": "NSMenuItemImportFromDeviceIdentifier",
                      "type": "codeVoice"
                    },
                    {
                      "text": " (defined in ",
                      "type": "text"
                    },
                    {
                      "code": "NSMenuItem.h",
                      "type": "codeVoice"
                    },
                    {
                      "text": ").",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Here’s how it looks:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3150811",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your app doesn’t use a storyboard, you can programmatically add the menu item by following these steps:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Get the app’s main menu bar.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Get the desired menu item for the insertion from the menu bar.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Get the submenu for the menu item.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create the Camera menu item and specify the name, such as “Take Picture.”",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set the Identifier property for the Camera menu item to ",
                      "type": "text"
                    },
                    {
                      "code": "NSMenuItem.importFromDeviceIdentifier",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add the Camera menu item to the submenu.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "A good place to do this is in your app delegate’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplicationDelegate/applicationWillFinishLaunching(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method as the following example shows:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "    func applicationWillFinishLaunching(_ aNotification: Notification) {        ",
            "        let mainMenu = NSApplication.shared.mainMenu",
            "        // Get the File menu item.",
            "        guard let fileMenu = mainMenu?.item(at: 1) else { return }",
            "        // Get the File menu item submenu.",
            "        guard let subMenu = fileMenu.submenu else { return }",
            "        // Create the Camera menu item.",
            "        let cameraMenuItem =",
            "            NSMenuItem(title: \"Take Picture\", action: nil, keyEquivalent: \"\")",
            "        // Specify the Continuity Camera menu item identifier.",
            "        cameraMenuItem.identifier = NSMenuItem.importFromDeviceIdentifier",
            "        // Add the Camera menu item to the File menu.",
            "        subMenu.addItem(cameraMenuItem)",
            "    }"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "You don’t add a Continuity Camera menu item directly to your app’s contextual menus. Instead, you enable the appropriate support in your app’s responder objects as the previous section describes, and AppKit adds the menu item for you.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, the following code demonstrates how to display a contextual menu in response to a mouse-down event, and have AppKit insert the menu item. This code overrides the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseDown(with:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method and creates a menu. It then invokes the ",
              "type": "text"
            },
            {
              "code": "NSMenu",
              "type": "codeVoice"
            },
            {
              "text": " class method ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenu/popUpContextMenu(_:with:for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", passing the event object related to the mouse-down event and the view that owns the contextual menu. AppKit automatically inserts the Continuity Camera menu item in the contextual menu for you.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "override func mouseDown(with event: NSEvent) {    ",
            "    let theMenu = NSMenu(title: \"Contextual Menu\")",
            "    /*",
            "     Display a contextual menu over the view for the mouse-down event.",
            "     AppKit automatically inserts the Continuity Camera menu item.",
            "     */",
            "    NSMenu.popUpContextMenu(theMenu, with: event, for: self.view)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "When the user selects the Continuity Camera menu item, the system automatically launches the Continuity Camera interface on the user’s device. After the user captures an image, AppKit places that image on the app’s pasteboard.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Incorporate-the-Image-Data-from-the-Pasteboard",
          "level": 3,
          "text": "Incorporate the Image Data from the Pasteboard",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You need to incorporate the captured images into your app after AppKit places them on the pasteboard. AppKit then calls the active responder object’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSServicesMenuRequestor/readSelection(from:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to read the image data. The ",
              "type": "text"
            },
            {
              "code": "readSelection(from:)",
              "type": "codeVoice"
            },
            {
              "text": " method supports Continuity Camera image data and other types of data in your app. Use that method to determine whether the image is in a format your app supports, and incorporate that image data into your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Here’s an example implementation of the ",
              "type": "text"
            },
            {
              "code": "readSelection(from:)",
              "type": "codeVoice"
            },
            {
              "text": " method:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func readSelection(from pasteboard: NSPasteboard) -> Bool {",
            "    // Verify that the pasteboard contains image data.",
            "    guard pasteboard.canReadItem(withDataConformingToTypes: NSImage.imageTypes) else {",
            "        return false",
            "    }",
            "    // Load the image.",
            "    guard let image = NSImage(pasteboard: pasteboard) else {",
            "        return false",
            "    }",
            "    // Incorporate the image into the app.",
            "    self.myImageView.image = image",
            "    // This method has successfully read the pasteboard data.",
            "    return true",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplicationDelegate/applicationWillFinishLaunching(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the app’s initialization is about to complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationWillFinishLaunching"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplicationDelegate/applicationWillFinishLaunching(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationWillFinishLaunching:"
        }
      ],
      "role": "symbol",
      "title": "applicationWillFinishLaunching(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplicationdelegate/applicationwillfinishlaunching(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenu/popUpContextMenu(_:with:for:)": {
      "abstract": [
        {
          "text": "Displays a contextual menu over a view for an event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popUpContextMenu"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMenu",
          "text": "NSMenu"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenu/popUpContextMenu(_:with:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "popUpContextMenu:withEvent:forView:"
        }
      ],
      "role": "symbol",
      "title": "popUpContextMenu(_:with:for:)",
      "type": "topic",
      "url": "/documentation/appkit/nsmenu/popupcontextmenu(_:with:for:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseDown(with:)": {
      "abstract": [
        {
          "text": "Informs the receiver that the user has pressed the left mouse button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mouseDown"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseDown(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mouseDown:"
        }
      ],
      "role": "symbol",
      "title": "mouseDown(with:)",
      "type": "topic",
      "url": "/documentation/appkit/nsresponder/mousedown(with:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSResponder/validRequestor(forSendType:returnType:)": {
      "abstract": [
        {
          "text": "Overridden by subclasses to determine what services are available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "validRequestor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forSendType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardType",
          "text": "PasteboardType"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "returnType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardType",
          "text": "PasteboardType"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSResponder/validRequestor(forSendType:returnType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "validRequestorForSendType:returnType:"
        }
      ],
      "role": "symbol",
      "title": "validRequestor(forSendType:returnType:)",
      "type": "topic",
      "url": "/documentation/appkit/nsresponder/validrequestor(forsendtype:returntype:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSServicesMenuRequestor/readSelection(from:)": {
      "abstract": [
        {
          "text": "Reads data from the pasteboard and uses it to replace the current selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readSelection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSServicesMenuRequestor/readSelection(from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readSelectionFromPasteboard:"
        }
      ],
      "role": "symbol",
      "title": "readSelection(from:)",
      "type": "topic",
      "url": "/documentation/appkit/nsservicesmenurequestor/readselection(from:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/animation": {
      "abstract": [
        {
          "text": "Animate your views and other content to create a more engaging experience for users.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/animation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Animation",
      "type": "topic",
      "url": "/documentation/appkit/animation"
    },
    "doc://com.apple.appkit/documentation/AppKit/appearance-customization": {
      "abstract": [
        {
          "text": "Add Dark Mode support to your app, and use appearance proxies to modify your UI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/appearance-customization",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Appearance Customization",
      "type": "topic",
      "url": "/documentation/appkit/appearance-customization"
    },
    "doc://com.apple.appkit/documentation/AppKit/images-and-pdf": {
      "abstract": [
        {
          "text": "Create and manage images, in bitmap, PDF, and other formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/images-and-pdf",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Images and PDF",
      "type": "topic",
      "url": "/documentation/appkit/images-and-pdf"
    },
    "doc://com.apple.appkit/documentation/AppKit/sound-speech-and-haptics": {
      "abstract": [
        {
          "text": "Play sounds and haptic feedback, and incorporate speech recognition and synthesis into your interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/sound-speech-and-haptics",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sound, Speech, and Haptics",
      "type": "topic",
      "url": "/documentation/appkit/sound-speech-and-haptics"
    },
    "doc://com.apple.appkit/documentation/AppKit/view-layout": {
      "abstract": [
        {
          "text": "Position and size views using a stack view or Auto Layout constraints.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/view-layout",
      "kind": "article",
      "role": "collectionGroup",
      "title": "View Layout",
      "type": "topic",
      "url": "/documentation/appkit/view-layout"
    },
    "doc://com.apple.appkit/documentation/AppKit/view-management": {
      "abstract": [
        {
          "text": "Manage your user interface, including the size and position of views in a window.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/view-management",
      "kind": "article",
      "role": "collectionGroup",
      "title": "View Management",
      "type": "topic",
      "url": "/documentation/appkit/view-management"
    },
    "doc://com.apple.appkit/documentation/AppKit/views-and-controls": {
      "abstract": [
        {
          "text": "Present your content onscreen and handle user input and events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Views and Controls",
      "type": "topic",
      "url": "/documentation/appkit/views-and-controls"
    },
    "doc://com.apple.appkit/documentation/AppKit/windows-panels-and-screens": {
      "abstract": [
        {
          "text": "Organize your view hierarchies and facilitate their display onscreen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/windows-panels-and-screens",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Windows, Panels, and Screens",
      "type": "topic",
      "url": "/documentation/appkit/windows-panels-and-screens"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "media-3150811": {
      "alt": "A screenshot of a storyboard for an app’s menus, showing the settings that the preceding steps describe.",
      "identifier": "media-3150811",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/9d530057f1aab0d4fa901cec894c403b/media-3150811@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/a6458e8c9a87b938d70cbb6f720833ea/media-3150811~dark@2x.png"
        }
      ]
    },
    "media-3993602": {
      "alt": "A screenshot showing a text view where the user Control-clicks to display the Continuity Camera dialog for taking a photo with an iOS device. The dialog shows the name of the iOS device and a Cancel button to allow the user to dismiss the dialog without taking a photo.",
      "identifier": "media-3993602",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/59306d29d65bae59ff9f0bc4871cc13c/media-3993602@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "User-Interface",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
        "doc://com.apple.appkit/documentation/AppKit/view-management",
        "doc://com.apple.appkit/documentation/AppKit/view-layout",
        "doc://com.apple.appkit/documentation/AppKit/appearance-customization",
        "doc://com.apple.appkit/documentation/AppKit/animation",
        "doc://com.apple.appkit/documentation/AppKit/windows-panels-and-screens",
        "doc://com.apple.appkit/documentation/AppKit/sound-speech-and-haptics"
      ],
      "title": "User Interface"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "User-Interface",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
                "doc://com.apple.appkit/documentation/AppKit/view-management",
                "doc://com.apple.appkit/documentation/AppKit/view-layout",
                "doc://com.apple.appkit/documentation/AppKit/appearance-customization",
                "doc://com.apple.appkit/documentation/AppKit/animation",
                "doc://com.apple.appkit/documentation/AppKit/windows-panels-and-screens",
                "doc://com.apple.appkit/documentation/AppKit/sound-speech-and-haptics"
              ],
              "title": "User Interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1validRequestor(forSendType:returnType:)/title",
          "value": "validRequestorForSendType:returnType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1validRequestor(forSendType:returnType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "validRequestorForSendType:returnType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSServicesMenuRequestor~1readSelection(from:)/title",
          "value": "readSelectionFromPasteboard:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSServicesMenuRequestor~1readSelection(from:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readSelectionFromPasteboard:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseDown(with:)/title",
          "value": "mouseDown:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseDown(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mouseDown:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1popUpContextMenu(_:with:for:)/title",
          "value": "popUpContextMenu:withEvent:forView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1popUpContextMenu(_:with:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "popUpContextMenu:withEvent:forView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplicationDelegate~1applicationWillFinishLaunching(_:)/title",
          "value": "applicationWillFinishLaunching:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplicationDelegate~1applicationWillFinishLaunching(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "applicationWillFinishLaunching:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/supporting-continuity-camera-in-your-mac-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/supporting-continuity-camera-in-your-mac-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
