{
  "abstract": [
    {
      "text": "Display custom data in rows and columns.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "beta": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/views-and-controls"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/table-view"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Table View"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableCellView": {
      "abstract": [
        {
          "text": "A reusable container view shown for a particular cell in a table view that uses rows for content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableCellView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableCellView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableCellView"
        }
      ],
      "role": "symbol",
      "title": "NSTableCellView",
      "type": "topic",
      "url": "/documentation/appkit/nstablecellview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableColumn": {
      "abstract": [
        {
          "text": "The display characteristics and identifier for a column in a table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableColumn"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableColumn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableColumn"
        }
      ],
      "role": "symbol",
      "title": "NSTableColumn",
      "type": "topic",
      "url": "/documentation/appkit/nstablecolumn"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/ResizingOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ResizingOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/ResizingOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ResizingOptions"
        }
      ],
      "role": "symbol",
      "title": "NSTableColumn.ResizingOptions",
      "type": "topic",
      "url": "/documentation/appkit/nstablecolumn/resizingoptions"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableHeaderCell": {
      "abstract": [
        {
          "text": "An object that a table header view uses to draw the content of the column headers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableHeaderCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableHeaderCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableHeaderCell"
        }
      ],
      "role": "symbol",
      "title": "NSTableHeaderCell",
      "type": "topic",
      "url": "/documentation/appkit/nstableheadercell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableHeaderView": {
      "abstract": [
        {
          "text": "An object that draws headers over a table view’s columns and handles mouse events in those headers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableHeaderView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableHeaderView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableHeaderView"
        }
      ],
      "role": "symbol",
      "title": "NSTableHeaderView",
      "type": "topic",
      "url": "/documentation/appkit/nstableheaderview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableRowView": {
      "abstract": [
        {
          "text": "The view shown for a row in a table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableRowView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableRowView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableRowView"
        }
      ],
      "role": "symbol",
      "title": "NSTableRowView",
      "type": "topic",
      "url": "/documentation/appkit/nstablerowview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView": {
      "abstract": [
        {
          "text": "A set of related records, displayed in rows that represent individual records and columns that represent the attributes of those records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableView"
        }
      ],
      "role": "symbol",
      "title": "NSTableView",
      "type": "topic",
      "url": "/documentation/appkit/nstableview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource": {
      "abstract": [
        {
          "text": "A set of methods that a table view uses to provide data to a table view and to allow the editing of the table view’s data source object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableViewDataSource"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewDataSource"
        }
      ],
      "role": "symbol",
      "title": "NSTableViewDataSource",
      "type": "topic",
      "url": "/documentation/appkit/nstableviewdatasource"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate": {
      "abstract": [
        {
          "text": "A set of optional methods you implement in a table view delegate to customize the behavior of the table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSTableViewDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nstableviewdelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableViewDiffableDataSource-c5gl": {
      "abstract": [
        {
          "text": "The object you use to manage data and provide items for a table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableViewDiffableDataSource"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableViewDiffableDataSource-c5gl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewDiffableDataSource"
        }
      ],
      "role": "symbol",
      "title": "NSTableViewDiffableDataSource",
      "type": "topic",
      "url": "/documentation/appkit/nstableviewdiffabledatasource-c5gl"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableViewDiffableDataSourceReference": {
      "abstract": [
        {
          "text": "The object you use to manage data and provide items for a table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableViewDiffableDataSourceReference"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableViewDiffableDataSourceReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewDiffableDataSourceReference"
        }
      ],
      "role": "symbol",
      "title": "NSTableViewDiffableDataSourceReference",
      "type": "topic",
      "url": "/documentation/appkit/nstableviewdiffabledatasourcereference"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction": {
      "abstract": [
        {
          "text": "A single action to present when the user swipes horizontally on a table row.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableViewRowAction"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewRowAction"
        }
      ],
      "role": "symbol",
      "title": "NSTableViewRowAction",
      "type": "topic",
      "url": "/documentation/appkit/nstableviewrowaction"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView": {
      "abstract": [
        {
          "text": "A view that draws text and handles user interactions with that text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "role": "symbol",
      "title": "NSTextView",
      "type": "topic",
      "url": "/documentation/appkit/nstextview"
    },
    "doc://com.apple.appkit/documentation/AppKit/browser-view": {
      "abstract": [
        {
          "text": "Provide a column-based interface for viewing and navigating hierarchical information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/browser-view",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Browser View",
      "type": "topic",
      "url": "/documentation/appkit/browser-view"
    },
    "doc://com.apple.appkit/documentation/AppKit/collection-view": {
      "abstract": [
        {
          "text": "Display one or more subviews in a highly configurable arrangement.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/collection-view",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Collection View",
      "type": "topic",
      "url": "/documentation/appkit/collection-view"
    },
    "doc://com.apple.appkit/documentation/AppKit/outline-view": {
      "abstract": [
        {
          "text": "Display a list-based interface for hierarchical data, where each level of hierarchy is indented from the previous one.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/outline-view",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Outline View",
      "type": "topic",
      "url": "/documentation/appkit/outline-view"
    },
    "doc://com.apple.appkit/documentation/AppKit/views-and-controls": {
      "abstract": [
        {
          "text": "Present your content onscreen and handle user input and events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Views and Controls",
      "type": "topic",
      "url": "/documentation/appkit/views-and-controls"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Content-Views",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/browser-view",
        "doc://com.apple.appkit/documentation/AppKit/collection-view",
        "doc://com.apple.appkit/documentation/AppKit/outline-view",
        "doc://com.apple.appkit/documentation/AppKit/NSTextView"
      ],
      "title": "Content Views"
    }
  ],
  "topicSections": [
    {
      "anchor": "Views",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableView",
        "doc://com.apple.appkit/documentation/AppKit/NSTableCellView"
      ],
      "title": "Views"
    },
    {
      "anchor": "Management",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource",
        "doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate",
        "doc://com.apple.appkit/documentation/AppKit/NSTableViewDiffableDataSource-c5gl"
      ],
      "title": "Management"
    },
    {
      "anchor": "Rows-and-Columns",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableHeaderView",
        "doc://com.apple.appkit/documentation/AppKit/NSTableHeaderCell",
        "doc://com.apple.appkit/documentation/AppKit/NSTableRowView",
        "doc://com.apple.appkit/documentation/AppKit/NSTableColumn",
        "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction",
        "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/ResizingOptions"
      ],
      "title": "Rows and Columns"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Views",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTableView",
                "doc://com.apple.appkit/documentation/AppKit/NSTableCellView"
              ],
              "title": "Views"
            },
            {
              "anchor": "Management",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTableViewDataSource",
                "doc://com.apple.appkit/documentation/AppKit/NSTableViewDelegate",
                "doc://com.apple.appkit/documentation/AppKit/NSTableViewDiffableDataSourceReference"
              ],
              "title": "Management"
            },
            {
              "anchor": "Rows-and-Columns",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTableHeaderView",
                "doc://com.apple.appkit/documentation/AppKit/NSTableHeaderCell",
                "doc://com.apple.appkit/documentation/AppKit/NSTableRowView",
                "doc://com.apple.appkit/documentation/AppKit/NSTableColumn",
                "doc://com.apple.appkit/documentation/AppKit/NSTableViewRowAction",
                "doc://com.apple.appkit/documentation/AppKit/NSTableColumn/ResizingOptions"
              ],
              "title": "Rows and Columns"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Content-Views",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/browser-view",
                "doc://com.apple.appkit/documentation/AppKit/collection-view",
                "doc://com.apple.appkit/documentation/AppKit/outline-view",
                "doc://com.apple.appkit/documentation/AppKit/NSTextView"
              ],
              "title": "Content Views"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableCellView/title",
          "value": "NSTableCellView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableCellView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableCellView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableCellView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableCellView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn/title",
          "value": "NSTableColumn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableColumn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableColumn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/title",
          "value": "NSTableView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableHeaderCell/title",
          "value": "NSTableHeaderCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableHeaderCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableHeaderCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableHeaderCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableHeaderCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewRowAction/title",
          "value": "NSTableViewRowAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewRowAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewRowAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewRowAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewRowAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableRowView/title",
          "value": "NSTableRowView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableRowView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableRowView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableRowView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableRowView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/title",
          "value": "NSTextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate/title",
          "value": "NSTableViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource/title",
          "value": "NSTableViewDataSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDataSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1ResizingOptions/title",
          "value": "NSTableColumnResizingOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1ResizingOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableColumnResizingOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableColumn~1ResizingOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableColumnResizingOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDiffableDataSourceReference/title",
          "value": "NSTableViewDiffableDataSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDiffableDataSourceReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewDiffableDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableViewDiffableDataSourceReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewDiffableDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableHeaderView/title",
          "value": "NSTableHeaderView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableHeaderView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableHeaderView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableHeaderView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableHeaderView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/table-view"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/table-view"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
