{
  "abstract": [
    {
      "text": "These constants are obsolete and should not be used.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/deprecated-symbols"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/tags-of-views-in-the-fontpanel"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Tags of Views in the FontPanel"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/runModal(for:)": {
      "abstract": [
        {
          "text": "Starts a modal event loop for the specified window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "runModal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSModalResponse",
          "text": "ModalResponse"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/runModal(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runModalForWindow:"
        }
      ],
      "role": "symbol",
      "title": "runModal(for:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/runmodal(for:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/runModalSession(_:)": {
      "abstract": [
        {
          "text": "Runs a given modal session, as defined in a previous invocation of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/beginModalSession(for:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "runModalSession"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSModalSession",
          "text": "ModalSession"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSApplication",
          "text": "NSApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSModalResponse",
          "text": "ModalResponse"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/runModalSession(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runModalSession:"
        }
      ],
      "role": "symbol",
      "title": "runModalSession(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/runmodalsession(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFPCurrentField": {
      "abstract": [
        {
          "text": "Show the Current field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFPCurrentField"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFPCurrentField",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFPCurrentField",
      "type": "topic",
      "url": "/documentation/appkit/nsfpcurrentfield"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFPPreviewButton": {
      "abstract": [
        {
          "text": "Show the Preview button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFPPreviewButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFPPreviewButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFPPreviewButton",
      "type": "topic",
      "url": "/documentation/appkit/nsfppreviewbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFPPreviewField": {
      "abstract": [
        {
          "text": "Show the Preview field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFPPreviewField"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFPPreviewField",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFPPreviewField",
      "type": "topic",
      "url": "/documentation/appkit/nsfppreviewfield"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFPRevertButton": {
      "abstract": [
        {
          "text": "Show the Revert button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFPRevertButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFPRevertButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFPRevertButton",
      "type": "topic",
      "url": "/documentation/appkit/nsfprevertbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFPSetButton": {
      "abstract": [
        {
          "text": "Show the Set button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFPSetButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFPSetButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFPSetButton",
      "type": "topic",
      "url": "/documentation/appkit/nsfpsetbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFPSizeField": {
      "abstract": [
        {
          "text": "Show the Size field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFPSizeField"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFPSizeField",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFPSizeField",
      "type": "topic",
      "url": "/documentation/appkit/nsfpsizefield"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFPSizeTitle": {
      "abstract": [
        {
          "text": "Show the Size title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFPSizeTitle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFPSizeTitle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFPSizeTitle",
      "type": "topic",
      "url": "/documentation/appkit/nsfpsizetitle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSInterfaceStyle": {
      "abstract": [
        {
          "text": "These constants are used in ",
          "type": "text"
        },
        {
          "code": "NSResponder",
          "type": "codeVoice"
        },
        {
          "text": "’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSResponder/interfaceStyle",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSInterfaceStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSInterfaceStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInterfaceStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsinterfacestyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMultibyteGlyphPacking": {
      "abstract": [
        {
          "text": "A constant for glyph packing.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMultibyteGlyphPacking"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMultibyteGlyphPacking",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMultibyteGlyphPacking"
        }
      ],
      "role": "symbol",
      "title": "NSMultibyteGlyphPacking",
      "type": "topic",
      "url": "/documentation/appkit/nsmultibyteglyphpacking"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGlobalOption": {
      "abstract": [
        {
          "text": "Constants that specify OpenGL options.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOpenGLGlobalOption"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGlobalOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOpenGLGlobalOption"
        }
      ],
      "role": "symbol",
      "title": "NSOpenGLGlobalOption",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglglobaloption"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSResponder/interfaceStyle": {
      "abstract": [
        {
          "text": "Returns the receiver’s interface style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "interfaceStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSResponder/interfaceStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "interfaceStyle"
        }
      ],
      "role": "symbol",
      "title": "interfaceStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsresponder/interfacestyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection/leftToRight": {
      "abstract": [
        {
          "text": "The writing direction is left to right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftToRight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection/leftToRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingDirectionLeftToRight"
        }
      ],
      "role": "symbol",
      "title": "NSWritingDirection.leftToRight",
      "type": "topic",
      "url": "/documentation/appkit/nswritingdirection/lefttoright"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection/rightToLeft": {
      "abstract": [
        {
          "text": "The writing direction is right to left.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightToLeft"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection/rightToLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingDirectionRightToLeft"
        }
      ],
      "role": "symbol",
      "title": "NSWritingDirection.rightToLeft",
      "type": "topic",
      "url": "/documentation/appkit/nswritingdirection/righttoleft"
    },
    "doc://com.apple.appkit/documentation/AppKit/additional-writing-directions": {
      "abstract": [
        {
          "text": "Additional values to be added to ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection/leftToRight",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingDirection/rightToLeft",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", when used with ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/1524497-writingdirection",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/additional-writing-directions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Additional Writing Directions",
      "type": "topic",
      "url": "/documentation/appkit/additional-writing-directions"
    },
    "doc://com.apple.appkit/documentation/AppKit/data-entry-types": {
      "abstract": [
        {
          "text": "These constants specify how a cell formats numeric data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/data-entry-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Data Entry Types",
      "type": "topic",
      "url": "/documentation/appkit/data-entry-types"
    },
    "doc://com.apple.appkit/documentation/AppKit/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review symbols that are no longer supported, and find the replacements to use instead.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/appkit/deprecated-symbols"
    },
    "doc://com.apple.appkit/documentation/AppKit/glyph-attributes": {
      "abstract": [
        {
          "text": "Attributes that are used only inside the glyph generation machinery, but must also be shared between components.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/glyph-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Glyph Attributes",
      "type": "topic",
      "url": "/documentation/appkit/glyph-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/nsbuttontypes-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nsbuttontypes-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/appkit/nsbuttontypes-anonymous"
    },
    "doc://com.apple.appkit/documentation/AppKit/return-values-for-modal-operations": {
      "abstract": [
        {
          "text": "Historical return values for ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/runModal(for:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/runModalSession(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/return-values-for-modal-operations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Return values for modal operations",
      "type": "topic",
      "url": "/documentation/appkit/return-values-for-modal-operations"
    },
    "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/1524497-writingdirection": {
      "abstract": [
        {
          "text": "The writing direction of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "writingDirection"
        },
        {
          "kind": "text",
          "text": ": NSAttributedString.Key"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/1524497-writingdirection",
      "kind": "symbol",
      "role": "symbol",
      "title": "writingDirection",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/key/1524497-writingdirection"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSMultibyteGlyphPacking",
        "doc://com.apple.appkit/documentation/AppKit/glyph-attributes",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGlobalOption",
        "doc://com.apple.appkit/documentation/AppKit/data-entry-types",
        "doc://com.apple.appkit/documentation/AppKit/nsbuttontypes-anonymous",
        "doc://com.apple.appkit/documentation/AppKit/additional-writing-directions",
        "doc://com.apple.appkit/documentation/AppKit/return-values-for-modal-operations"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFPPreviewButton",
                "doc://com.apple.appkit/documentation/AppKit/NSFPRevertButton",
                "doc://com.apple.appkit/documentation/AppKit/NSFPSetButton",
                "doc://com.apple.appkit/documentation/AppKit/NSFPPreviewField",
                "doc://com.apple.appkit/documentation/AppKit/NSFPSizeField",
                "doc://com.apple.appkit/documentation/AppKit/NSFPSizeTitle",
                "doc://com.apple.appkit/documentation/AppKit/NSFPCurrentField"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSMultibyteGlyphPacking",
                "doc://com.apple.appkit/documentation/AppKit/glyph-attributes",
                "doc://com.apple.appkit/documentation/AppKit/NSOpenGLGlobalOption",
                "doc://com.apple.appkit/documentation/AppKit/NSInterfaceStyle",
                "doc://com.apple.appkit/documentation/AppKit/data-entry-types",
                "doc://com.apple.appkit/documentation/AppKit/nsbuttontypes-anonymous",
                "doc://com.apple.appkit/documentation/AppKit/additional-writing-directions",
                "doc://com.apple.appkit/documentation/AppKit/return-values-for-modal-operations"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1runModalSession(_:)/title",
          "value": "runModalSession:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1runModalSession(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runModalSession:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirection~1rightToLeft/title",
          "value": "NSWritingDirectionRightToLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirection~1rightToLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingDirectionRightToLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMultibyteGlyphPacking/title",
          "value": "NSMultibyteGlyphPacking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMultibyteGlyphPacking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMultibyteGlyphPacking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMultibyteGlyphPacking/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMultibyteGlyphPacking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLGlobalOption/title",
          "value": "NSOpenGLGlobalOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLGlobalOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLGlobalOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSOpenGLGlobalOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOpenGLGlobalOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirection~1leftToRight/title",
          "value": "NSWritingDirectionLeftToRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirection~1leftToRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingDirectionLeftToRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1runModal(for:)/title",
          "value": "runModalForWindow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1runModal(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runModalForWindow:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/tags-of-views-in-the-fontpanel"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/tags-of-views-in-the-fontpanel"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
