{
  "abstract": [
    {
      "text": "AppKit-specific keys you use to apply attributes to ranges of characters in an attributed string.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/textkit",
        "doc://com.apple.appkit/documentation/AppKit/textkit-string-attributes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/textkit-string-attribute-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "TextKit string attribute keys"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "AppKit defines these attribute keys you use to specify attribute values in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsmutableattributedstring",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityAnnotationTextAttribute": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityAnnotationTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityAnnotationTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityAnnotationTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityannotationtextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityAttachmentTextAttribute": {
      "abstract": [
        {
          "text": "Text attachment (",
          "type": "text"
        },
        {
          "code": "id",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityAttachmentTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityAttachmentTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityAttachmentTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityattachmenttextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityAutocorrectedTextAttribute": {
      "abstract": [
        {
          "text": "Autocorrected text (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " as a Boolean value).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityAutocorrectedTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityAutocorrectedTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityAutocorrectedTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityautocorrectedtextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityBackgroundColorTextAttribute": {
      "abstract": [
        {
          "text": "Text background color (",
          "type": "text"
        },
        {
          "code": "CGColorRef",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityBackgroundColorTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityBackgroundColorTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityBackgroundColorTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitybackgroundcolortextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomTextAttribute": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityCustomTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityCustomTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitycustomtextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityFontTextAttribute": {
      "abstract": [
        {
          "text": "Font keys (",
          "type": "text"
        },
        {
          "code": "NSDictionary",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityFontTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityFontTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityFontTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityfonttextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityForegroundColorTextAttribute": {
      "abstract": [
        {
          "text": "Text foreground color (",
          "type": "text"
        },
        {
          "code": "CGColorRef",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityForegroundColorTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityForegroundColorTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityForegroundColorTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityforegroundcolortextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityLanguageTextAttribute": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityLanguageTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityLanguageTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityLanguageTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitylanguagetextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityLinkTextAttribute": {
      "abstract": [
        {
          "text": "Text link (",
          "type": "text"
        },
        {
          "code": "id",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityLinkTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityLinkTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityLinkTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitylinktextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityListItemIndexTextAttribute": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityListItemIndexTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityListItemIndexTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityListItemIndexTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitylistitemindextextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityListItemLevelTextAttribute": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityListItemLevelTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityListItemLevelTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityListItemLevelTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitylistitemleveltextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityListItemPrefixTextAttribute": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityListItemPrefixTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityListItemPrefixTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityListItemPrefixTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitylistitemprefixtextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityMarkedMisspelledTextAttribute": {
      "abstract": [
        {
          "text": "Misspelled text that is visibly marked as misspelled (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " as a Boolean value). If you’re implementing a custom text-editing app, use ",
          "type": "text"
        },
        {
          "code": "NSAccessibilityMarkedMisspelledTextAttribute",
          "type": "codeVoice"
        },
        {
          "text": " to ensure that VoiceOver properly identifies misspelled text to users.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityMarkedMisspelledTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityMarkedMisspelledTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityMarkedMisspelledTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitymarkedmisspelledtextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityMisspelledTextAttribute": {
      "abstract": [
        {
          "text": "Misspelled text that isn’t necessarily visibly marked as misspelled (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " as a Boolean value). Beginning in macOS 10.9, VoiceOver no longer checks for this attribute; instead, VoiceOver uses ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityMarkedMisspelledTextAttribute",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityMisspelledTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityMisspelledTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityMisspelledTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitymisspelledtextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityShadowTextAttribute": {
      "abstract": [
        {
          "text": "Text shadow (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " as a Boolean value).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityShadowTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityShadowTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityShadowTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityshadowtextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStrikethroughColorTextAttribute": {
      "abstract": [
        {
          "text": "Text strikethrough color (",
          "type": "text"
        },
        {
          "code": "CGColorRef",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityStrikethroughColorTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStrikethroughColorTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityStrikethroughColorTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitystrikethroughcolortextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStrikethroughTextAttribute": {
      "abstract": [
        {
          "text": "Text strikethrough (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " as a Boolean value).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityStrikethroughTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStrikethroughTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityStrikethroughTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitystrikethroughtextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySuperscriptTextAttribute": {
      "abstract": [
        {
          "text": "Text superscript style (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": "). Values > 0 are superscript; values < 0 are subscript.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilitySuperscriptTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySuperscriptTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilitySuperscriptTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitysuperscripttextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTextAlignmentAttribute": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityTextAlignmentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTextAlignmentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityTextAlignmentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitytextalignmentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityUnderlineColorTextAttribute": {
      "abstract": [
        {
          "text": "Text underline color (",
          "type": "text"
        },
        {
          "code": "CGColorRef",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityUnderlineColorTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityUnderlineColorTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityUnderlineColorTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityunderlinecolortextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityUnderlineTextAttribute": {
      "abstract": [
        {
          "text": "Text underline style (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityUnderlineTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityUnderlineTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityUnderlineTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityunderlinetextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAdaptiveImageGlyphAttributeName": {
      "abstract": [
        {
          "text": "The adaptive image glyph for the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAdaptiveImageGlyphAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAdaptiveImageGlyphAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAdaptiveImageGlyphAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsadaptiveimageglyphattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAttachmentAttributeName": {
      "abstract": [
        {
          "text": "The attachment for the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAttachmentAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAttachmentAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttachmentAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsattachmentattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBackgroundColorAttributeName": {
      "abstract": [
        {
          "text": "The color of the background behind the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBackgroundColorAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBackgroundColorAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBackgroundColorAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsbackgroundcolorattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBaselineOffsetAttributeName": {
      "abstract": [
        {
          "text": "The vertical offset for the position of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBaselineOffsetAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBaselineOffsetAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBaselineOffsetAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsbaselineoffsetattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCharacterShapeAttributeName": {
      "abstract": [
        {
          "text": "The character shape attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCharacterShapeAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCharacterShapeAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCharacterShapeAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nscharactershapeattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursorAttributeName": {
      "abstract": [
        {
          "text": "The cursor object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCursorAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursorAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCursorAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nscursorattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSExpansionAttributeName": {
      "abstract": [
        {
          "text": "The expansion factor of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSExpansionAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSExpansionAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExpansionAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsexpansionattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontAttributeName": {
      "abstract": [
        {
          "text": "The font of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFontAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFontAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsfontattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSForegroundColorAttributeName": {
      "abstract": [
        {
          "text": "The color of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSForegroundColorAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSForegroundColorAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSForegroundColorAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsforegroundcolorattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGlyphInfoAttributeName": {
      "abstract": [
        {
          "text": "The name of a glyph info object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSGlyphInfoAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGlyphInfoAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSGlyphInfoAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsglyphinfoattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSKernAttributeName": {
      "abstract": [
        {
          "text": "The kerning of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSKernAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSKernAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSKernAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nskernattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLigatureAttributeName": {
      "abstract": [
        {
          "text": "The ligature of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLigatureAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLigatureAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLigatureAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsligatureattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLinkAttributeName": {
      "abstract": [
        {
          "text": "The link for the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLinkAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLinkAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLinkAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nslinkattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMarkedClauseSegmentAttributeName": {
      "abstract": [
        {
          "text": "The index of the marked clause segment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMarkedClauseSegmentAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMarkedClauseSegmentAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMarkedClauseSegmentAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsmarkedclausesegmentattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSObliquenessAttributeName": {
      "abstract": [
        {
          "text": "The obliqueness of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSObliquenessAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSObliquenessAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObliquenessAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsobliquenessattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyleAttributeName": {
      "abstract": [
        {
          "text": "The paragraph style of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSParagraphStyleAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyleAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSParagraphStyleAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsparagraphstyleattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSShadowAttributeName": {
      "abstract": [
        {
          "text": "The shadow of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSShadowAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSShadowAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSShadowAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsshadowattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpellingState": {
      "abstract": [
        {
          "text": "Constants for the spelling state attribute key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSSpellingState"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpellingState",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSpellingState",
      "type": "topic",
      "url": "/documentation/appkit/nsspellingstate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSpellingStateAttributeName": {
      "abstract": [
        {
          "text": "The spelling state of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSSpellingStateAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSpellingStateAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSpellingStateAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsspellingstateattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStrikethroughColorAttributeName": {
      "abstract": [
        {
          "text": "The color of the strikethrough.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStrikethroughColorAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStrikethroughColorAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStrikethroughColorAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsstrikethroughcolorattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStrikethroughStyleAttributeName": {
      "abstract": [
        {
          "text": "The strikethrough style of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStrikethroughStyleAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStrikethroughStyleAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStrikethroughStyleAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsstrikethroughstyleattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStrokeColorAttributeName": {
      "abstract": [
        {
          "text": "The color of the stroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStrokeColorAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStrokeColorAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStrokeColorAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsstrokecolorattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStrokeWidthAttributeName": {
      "abstract": [
        {
          "text": "The width of the stroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStrokeWidthAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStrokeWidthAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStrokeWidthAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsstrokewidthattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSuperscriptAttributeName": {
      "abstract": [
        {
          "text": "The superscript of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSSuperscriptAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSuperscriptAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSuperscriptAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nssuperscriptattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextAlternativesAttributeName": {
      "abstract": [
        {
          "text": "The alternatives for the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextAlternativesAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextAlternativesAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextAlternativesAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nstextalternativesattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextEffectAttributeName": {
      "abstract": [
        {
          "text": "An attribute that applies a text effect to the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextEffectAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextEffectAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextEffectAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nstexteffectattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextEffectStyle": {
      "abstract": [
        {
          "text": "Constants for the type of effect to apply to the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextEffectStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextEffectStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextEffectStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstexteffectstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorScheme": {
      "abstract": [
        {
          "text": "Constants that specify the highlight color to use with the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextHighlightColorScheme"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorScheme",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextHighlightColorScheme",
      "type": "topic",
      "url": "/documentation/appkit/nstexthighlightcolorscheme"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorSchemeAttributeName": {
      "abstract": [
        {
          "text": "The custom highlight color to apply to the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextHighlightColorSchemeAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorSchemeAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextHighlightColorSchemeAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nstexthighlightcolorschemeattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightStyle": {
      "abstract": [
        {
          "text": "Constants that specify the type of highlight to apply to text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextHighlightStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextHighlightStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstexthighlightstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightStyleAttributeName": {
      "abstract": [
        {
          "text": "An attribute that adds a highlight color to the text to emphasize it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextHighlightStyleAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightStyleAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextHighlightStyleAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nstexthighlightstyleattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSToolTipAttributeName": {
      "abstract": [
        {
          "text": "The tooltip text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSToolTipAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToolTipAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSToolTipAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nstooltipattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTrackingAttributeName": {
      "abstract": [
        {
          "text": "The amount to modify the default tracking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTrackingAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTrackingAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTrackingAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nstrackingattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnderlineColorAttributeName": {
      "abstract": [
        {
          "text": "The color of the underline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlineColorAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnderlineColorAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlineColorAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsunderlinecolorattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle": {
      "abstract": [
        {
          "text": "Constants for the underline style and strikethrough style attribute keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStyle"
        }
      ],
      "role": "symbol",
      "title": "NSUnderlineStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsunderlinestyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyleAttributeName": {
      "abstract": [
        {
          "text": "The underline style of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStyleAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyleAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlineStyleAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsunderlinestyleattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUsesScreenFontsDocumentAttribute": {
      "abstract": [
        {
          "text": "The screen fonts attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUsesScreenFontsDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUsesScreenFontsDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUsesScreenFontsDocumentAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsusesscreenfontsdocumentattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVerticalGlyphFormAttributeName": {
      "abstract": [
        {
          "text": "The vertical glyph form of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSVerticalGlyphFormAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVerticalGlyphFormAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSVerticalGlyphFormAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nsverticalglyphformattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingDirectionAttributeName": {
      "abstract": [
        {
          "text": "The writing direction of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSWritingDirectionAttributeName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingDirectionAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSWritingDirectionAttributeName",
      "type": "topic",
      "url": "/documentation/appkit/nswritingdirectionattributename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingDirectionFormatType": {
      "abstract": [
        {
          "text": "Constants for the writing direction attribute key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWritingDirectionFormatType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingDirectionFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingDirectionFormatType"
        }
      ],
      "role": "symbol",
      "title": "NSWritingDirectionFormatType",
      "type": "topic",
      "url": "/documentation/appkit/nswritingdirectionformattype"
    },
    "doc://com.apple.appkit/documentation/AppKit/textkit": {
      "abstract": [
        {
          "text": "Manage text storage and perform custom layout of text-based content in your app’s views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/textkit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TextKit",
      "type": "topic",
      "url": "/documentation/appkit/textkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/textkit-string-attributes": {
      "abstract": [
        {
          "text": "AppKit-specific keys and values for displaying text and managing documents.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/textkit-string-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TextKit string attributes",
      "type": "topic",
      "url": "/documentation/appkit/textkit-string-attributes"
    },
    "doc://com.apple.documentation/documentation/foundation/nsattributedstring": {
      "abstract": [
        {
          "text": "A string of text that manages data, layout, and stylistic information for ranges of characters to support rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSAttributedString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedString",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring"
    },
    "doc://com.apple.documentation/documentation/foundation/nsmutableattributedstring": {
      "abstract": [
        {
          "text": "A mutable string with associated attributes (such as visual style, hyperlinks, or accessibility data) for portions of its text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSMutableAttributedString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsmutableattributedstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMutableAttributedString",
      "type": "topic",
      "url": "/documentation/foundation/nsmutableattributedstring"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-text-content-attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorScheme",
        "doc://com.apple.appkit/documentation/AppKit/NSTextEffectStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSSpellingState",
        "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingDirectionFormatType"
      ],
      "title": "Getting text content attributes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-rendering-attribute-keys",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBackgroundColorAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSBaselineOffsetAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSFontAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSForegroundColorAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSGlyphInfoAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSKernAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSLigatureAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSParagraphStyleAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSStrikethroughColorAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSStrikethroughStyleAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSStrokeColorAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSStrokeWidthAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSSuperscriptAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSTrackingAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSUnderlineColorAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSUnderlineStyleAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingDirectionAttributeName"
      ],
      "title": "Getting rendering attribute keys"
    },
    {
      "anchor": "Getting-text-attribute-keys",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCursorAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSLinkAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSMarkedClauseSegmentAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSShadowAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSSpellingStateAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSTextAlternativesAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSTextEffectAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightColorSchemeAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSTextHighlightStyleAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSToolTipAttributeName"
      ],
      "title": "Getting text attribute keys"
    },
    {
      "anchor": "Getting-attachment-attribute-keys",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAdaptiveImageGlyphAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSAttachmentAttributeName"
      ],
      "title": "Getting attachment attribute keys"
    },
    {
      "anchor": "Getting-accessibility-attribute-keys",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTextAlignmentAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityAnnotationTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityAttachmentTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityAutocorrectedTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityBackgroundColorTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityFontTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityForegroundColorTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityLanguageTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityLinkTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityListItemIndexTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityListItemLevelTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityListItemPrefixTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityMarkedMisspelledTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityMisspelledTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityShadowTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStrikethroughTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStrikethroughColorTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySuperscriptTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityUnderlineTextAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityUnderlineColorTextAttribute"
      ],
      "title": "Getting accessibility attribute keys"
    },
    {
      "anchor": "Deprecated-keys",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSExpansionAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSObliquenessAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSVerticalGlyphFormAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSCharacterShapeAttributeName",
        "doc://com.apple.appkit/documentation/AppKit/NSUsesScreenFontsDocumentAttribute"
      ],
      "title": "Deprecated keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirectionFormatType/title",
          "value": "NSWritingDirectionFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirectionFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingDirectionFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingDirectionFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingDirectionFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle/title",
          "value": "NSUnderlineStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUnderlineStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/textkit-string-attribute-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
