{
  "abstract": [
    {
      "text": "Attributes and key constants used with attributed strings.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/deprecated-symbols",
        "doc://com.apple.appkit/documentation/AppKit/nsaccessibility"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/text-attributed-string-attributes-and-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Text Attributed-String Attributes and Constants"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey/fontFamily": {
      "abstract": [
        {
          "text": "An optional key for a font family.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fontFamily"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityFontAttributeKey",
          "text": "FontAttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey/fontFamily",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityFontFamilyKey"
        }
      ],
      "role": "symbol",
      "title": "fontFamily",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/fontattributekey/fontfamily"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey/fontName": {
      "abstract": [
        {
          "text": "A required key for a font name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fontName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityFontAttributeKey",
          "text": "FontAttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey/fontName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityFontNameKey"
        }
      ],
      "role": "symbol",
      "title": "fontName",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/fontattributekey/fontname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey/fontSize": {
      "abstract": [
        {
          "text": "A required key for a font size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fontSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityFontAttributeKey",
          "text": "FontAttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey/fontSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityFontSizeKey"
        }
      ],
      "role": "symbol",
      "title": "fontSize",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/fontattributekey/fontsize"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey/visibleName": {
      "abstract": [
        {
          "text": "An optional key for font visibility.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visibleName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityFontAttributeKey",
          "text": "FontAttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey/visibleName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityVisibleNameKey"
        }
      ],
      "role": "symbol",
      "title": "visibleName",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/fontattributekey/visiblename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityAttachmentTextAttribute": {
      "abstract": [
        {
          "text": "Text attachment (",
          "type": "text"
        },
        {
          "code": "id",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityAttachmentTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityAttachmentTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityAttachmentTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityattachmenttextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityAutocorrectedTextAttribute": {
      "abstract": [
        {
          "text": "Autocorrected text (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " as a Boolean value).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityAutocorrectedTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityAutocorrectedTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityAutocorrectedTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityautocorrectedtextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityBackgroundColorTextAttribute": {
      "abstract": [
        {
          "text": "Text background color (",
          "type": "text"
        },
        {
          "code": "CGColorRef",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityBackgroundColorTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityBackgroundColorTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityBackgroundColorTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitybackgroundcolortextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityFontTextAttribute": {
      "abstract": [
        {
          "text": "Font keys (",
          "type": "text"
        },
        {
          "code": "NSDictionary",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityFontTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityFontTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityFontTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityfonttextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityForegroundColorTextAttribute": {
      "abstract": [
        {
          "text": "Text foreground color (",
          "type": "text"
        },
        {
          "code": "CGColorRef",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityForegroundColorTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityForegroundColorTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityForegroundColorTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityforegroundcolortextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityLinkTextAttribute": {
      "abstract": [
        {
          "text": "Text link (",
          "type": "text"
        },
        {
          "code": "id",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityLinkTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityLinkTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityLinkTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitylinktextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityMarkedMisspelledTextAttribute": {
      "abstract": [
        {
          "text": "Misspelled text that is visibly marked as misspelled (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " as a Boolean value). If you’re implementing a custom text-editing app, use ",
          "type": "text"
        },
        {
          "code": "NSAccessibilityMarkedMisspelledTextAttribute",
          "type": "codeVoice"
        },
        {
          "text": " to ensure that VoiceOver properly identifies misspelled text to users.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityMarkedMisspelledTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityMarkedMisspelledTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityMarkedMisspelledTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitymarkedmisspelledtextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityMisspelledTextAttribute": {
      "abstract": [
        {
          "text": "Misspelled text that isn’t necessarily visibly marked as misspelled (",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " as a Boolean value). Beginning in macOS 10.9, VoiceOver no longer checks for this attribute; instead, VoiceOver uses ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityMarkedMisspelledTextAttribute",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityMisspelledTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityMisspelledTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityMisspelledTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitymisspelledtextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityShadowTextAttribute": {
      "abstract": [
        {
          "text": "Text shadow (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " as a Boolean value).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityShadowTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityShadowTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityShadowTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityshadowtextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStrikethroughColorTextAttribute": {
      "abstract": [
        {
          "text": "Text strikethrough color (",
          "type": "text"
        },
        {
          "code": "CGColorRef",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityStrikethroughColorTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStrikethroughColorTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityStrikethroughColorTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitystrikethroughcolortextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStrikethroughTextAttribute": {
      "abstract": [
        {
          "text": "Text strikethrough (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " as a Boolean value).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityStrikethroughTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStrikethroughTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityStrikethroughTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitystrikethroughtextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySuperscriptTextAttribute": {
      "abstract": [
        {
          "text": "Text superscript style (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": "). Values > 0 are superscript; values < 0 are subscript.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilitySuperscriptTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySuperscriptTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilitySuperscriptTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitysuperscripttextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityUnderlineColorTextAttribute": {
      "abstract": [
        {
          "text": "Text underline color (",
          "type": "text"
        },
        {
          "code": "CGColorRef",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityUnderlineColorTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityUnderlineColorTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityUnderlineColorTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityunderlinecolortextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityUnderlineTextAttribute": {
      "abstract": [
        {
          "text": "Text underline style (",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityUnderlineTextAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityUnderlineTextAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityUnderlineTextAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityunderlinetextattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/app-specific-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to the app object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/app-specific-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App-Specific Attributes",
      "type": "topic",
      "url": "/documentation/appkit/app-specific-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/cell-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to individual table cells.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/cell-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cell Attributes",
      "type": "topic",
      "url": "/documentation/appkit/cell-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/cell-based-table-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to cell-based tables.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/cell-based-table-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cell-Based Table Attributes",
      "type": "topic",
      "url": "/documentation/appkit/cell-based-table-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/cell-based-table-parameterized-attributes": {
      "abstract": [
        {
          "text": "Parameterized attributes specific to cell-based tables.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/cell-based-table-parameterized-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cell-Based Table Parameterized Attributes",
      "type": "topic",
      "url": "/documentation/appkit/cell-based-table-parameterized-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review symbols that are no longer supported, and find the replacements to use instead.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/appkit/deprecated-symbols"
    },
    "doc://com.apple.appkit/documentation/AppKit/grid-view-attributes": {
      "abstract": [
        {
          "text": "Attributes that are used with grid views, such as thumbnails and media browsers that present a grid of items. The children of a grid are ordered.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/grid-view-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Grid View Attributes",
      "type": "topic",
      "url": "/documentation/appkit/grid-view-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/layout-area-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to layout areas.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/layout-area-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layout Area Attributes",
      "type": "topic",
      "url": "/documentation/appkit/layout-area-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/layout-area-parameterized-attributes": {
      "abstract": [
        {
          "text": "Parameterized attributes that are specific to layout areas.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/layout-area-parameterized-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layout Area Parameterized Attributes",
      "type": "topic",
      "url": "/documentation/appkit/layout-area-parameterized-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/layout-item-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to the items in a layout area.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/layout-item-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layout Item Attributes",
      "type": "topic",
      "url": "/documentation/appkit/layout-item-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/nsaccessibility": {
      "abstract": [
        {
          "text": "A legacy, informal protocol that Apple doesn’t recommend for active use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nsaccessibility",
      "kind": "article",
      "role": "collectionGroup",
      "title": "NSAccessibility",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility"
    },
    "doc://com.apple.appkit/documentation/AppKit/outline-view-attributes": {
      "abstract": [
        {
          "text": "Attributes that are used in outline views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/outline-view-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Outline View Attributes",
      "type": "topic",
      "url": "/documentation/appkit/outline-view-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/slider-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to sliders.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/slider-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Slider Attributes",
      "type": "topic",
      "url": "/documentation/appkit/slider-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/standard-attributes": {
      "abstract": [
        {
          "text": "Standard attributes that can be adopted by any accessibility object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/standard-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Standard Attributes",
      "type": "topic",
      "url": "/documentation/appkit/standard-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/table-view-and-outline-view-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to tables and outlines.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/table-view-and-outline-view-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Table View and Outline View Attributes",
      "type": "topic",
      "url": "/documentation/appkit/table-view-and-outline-view-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/text-specific-attributes": {
      "abstract": [
        {
          "text": "Attributes that are specific to text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/text-specific-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text-Specific Attributes",
      "type": "topic",
      "url": "/documentation/appkit/text-specific-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/text-specific-parameterized-attributes": {
      "abstract": [
        {
          "text": "Parameterized attributes specific to text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/text-specific-parameterized-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text-Specific Parameterized Attributes",
      "type": "topic",
      "url": "/documentation/appkit/text-specific-parameterized-attributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/window-specific-attributes": {
      "abstract": [
        {
          "text": "Attributes specific to windows.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/window-specific-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Window-Specific Attributes",
      "type": "topic",
      "url": "/documentation/appkit/window-specific-attributes"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/standard-attributes",
        "doc://com.apple.appkit/documentation/AppKit/text-specific-attributes",
        "doc://com.apple.appkit/documentation/AppKit/text-specific-parameterized-attributes",
        "doc://com.apple.appkit/documentation/AppKit/window-specific-attributes",
        "doc://com.apple.appkit/documentation/AppKit/app-specific-attributes",
        "doc://com.apple.appkit/documentation/AppKit/grid-view-attributes",
        "doc://com.apple.appkit/documentation/AppKit/table-view-and-outline-view-attributes",
        "doc://com.apple.appkit/documentation/AppKit/outline-view-attributes",
        "doc://com.apple.appkit/documentation/AppKit/cell-based-table-attributes",
        "doc://com.apple.appkit/documentation/AppKit/cell-based-table-parameterized-attributes",
        "doc://com.apple.appkit/documentation/AppKit/cell-attributes",
        "doc://com.apple.appkit/documentation/AppKit/layout-area-attributes",
        "doc://com.apple.appkit/documentation/AppKit/layout-area-parameterized-attributes",
        "doc://com.apple.appkit/documentation/AppKit/layout-item-attributes",
        "doc://com.apple.appkit/documentation/AppKit/slider-attributes"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey/fontName",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey/fontFamily",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey/visibleName",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey/fontSize"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityAttachmentTextAttribute",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityAutocorrectedTextAttribute",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityBackgroundColorTextAttribute",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityForegroundColorTextAttribute",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityUnderlineColorTextAttribute",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStrikethroughColorTextAttribute",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityUnderlineTextAttribute",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySuperscriptTextAttribute",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityStrikethroughTextAttribute",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityShadowTextAttribute",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityLinkTextAttribute",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityMarkedMisspelledTextAttribute",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityMisspelledTextAttribute",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityFontTextAttribute",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey/fontName",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey/fontFamily",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey/visibleName",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey/fontSize"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/standard-attributes",
                "doc://com.apple.appkit/documentation/AppKit/text-specific-attributes",
                "doc://com.apple.appkit/documentation/AppKit/text-specific-parameterized-attributes",
                "doc://com.apple.appkit/documentation/AppKit/window-specific-attributes",
                "doc://com.apple.appkit/documentation/AppKit/app-specific-attributes",
                "doc://com.apple.appkit/documentation/AppKit/grid-view-attributes",
                "doc://com.apple.appkit/documentation/AppKit/table-view-and-outline-view-attributes",
                "doc://com.apple.appkit/documentation/AppKit/outline-view-attributes",
                "doc://com.apple.appkit/documentation/AppKit/cell-based-table-attributes",
                "doc://com.apple.appkit/documentation/AppKit/cell-based-table-parameterized-attributes",
                "doc://com.apple.appkit/documentation/AppKit/cell-attributes",
                "doc://com.apple.appkit/documentation/AppKit/layout-area-attributes",
                "doc://com.apple.appkit/documentation/AppKit/layout-area-parameterized-attributes",
                "doc://com.apple.appkit/documentation/AppKit/layout-item-attributes",
                "doc://com.apple.appkit/documentation/AppKit/slider-attributes"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1FontAttributeKey~1visibleName/title",
          "value": "NSAccessibilityVisibleNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1FontAttributeKey~1visibleName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityVisibleNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1FontAttributeKey~1fontSize/title",
          "value": "NSAccessibilityFontSizeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1FontAttributeKey~1fontSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityFontSizeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1FontAttributeKey~1fontName/title",
          "value": "NSAccessibilityFontNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1FontAttributeKey~1fontName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityFontNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1FontAttributeKey~1fontFamily/title",
          "value": "NSAccessibilityFontFamilyKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1FontAttributeKey~1fontFamily/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityFontFamilyKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/text-attributed-string-attributes-and-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/text-attributed-string-attributes-and-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
