{
  "abstract": [
    {
      "text": "Display interactive content and controls in the Touch Bar.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/touch-bar"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Touch Bar"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButtonTouchBarItem": {
      "abstract": [
        {
          "text": "A bar item that provides a button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSButtonTouchBarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButtonTouchBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButtonTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSButtonTouchBarItem",
      "type": "topic",
      "url": "/documentation/appkit/nsbuttontouchbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItem": {
      "abstract": [
        {
          "text": "A bar item that, along with its delegate, provides a list of textual suggestions for the current text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCandidateListTouchBarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCandidateListTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSCandidateListTouchBarItem",
      "type": "topic",
      "url": "/documentation/appkit/nscandidatelisttouchbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorPickerTouchBarItem": {
      "abstract": [
        {
          "text": "A bar item that provides a system-defined color picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSColorPickerTouchBarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorPickerTouchBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorPickerTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSColorPickerTouchBarItem",
      "type": "topic",
      "url": "/documentation/appkit/nscolorpickertouchbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCustomTouchBarItem": {
      "abstract": [
        {
          "text": "A bar item that contains a responder of your choice, such as a view, a button, or a scrubber.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCustomTouchBarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCustomTouchBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCustomTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSCustomTouchBarItem",
      "type": "topic",
      "url": "/documentation/appkit/nscustomtouchbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGroupTouchBarItem": {
      "abstract": [
        {
          "text": "A bar item that provides a bar to contain other items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSGroupTouchBarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGroupTouchBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGroupTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSGroupTouchBarItem",
      "type": "topic",
      "url": "/documentation/appkit/nsgrouptouchbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem": {
      "abstract": [
        {
          "text": "A bar item that provides a picker control with multiple options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPickerTouchBarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPickerTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSPickerTouchBarItem",
      "type": "topic",
      "url": "/documentation/appkit/nspickertouchbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify display styles for picker bar items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ControlRepresentation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ControlRepresentation"
        }
      ],
      "role": "symbol",
      "title": "NSPickerTouchBarItem.ControlRepresentation",
      "type": "topic",
      "url": "/documentation/appkit/nspickertouchbaritem/controlrepresentation-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/SelectionMode-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify selection modes for picker bar items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SelectionMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/SelectionMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SelectionMode"
        }
      ],
      "role": "symbol",
      "title": "NSPickerTouchBarItem.SelectionMode",
      "type": "topic",
      "url": "/documentation/appkit/nspickertouchbaritem/selectionmode-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPopoverTouchBarItem": {
      "abstract": [
        {
          "text": "A bar item that provides a two-state control that can expand into its second state, showing the contents of a bar that it owns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPopoverTouchBarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPopoverTouchBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPopoverTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSPopoverTouchBarItem",
      "type": "topic",
      "url": "/documentation/appkit/nspopovertouchbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubber": {
      "abstract": [
        {
          "text": "A customizable item picker control for the Touch Bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScrubber"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrubber"
        }
      ],
      "role": "symbol",
      "title": "NSScrubber",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubber"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberArrangedView": {
      "abstract": [
        {
          "text": "An abstract base class for the views whose layout is managed by a scrubber.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScrubberArrangedView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberArrangedView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrubberArrangedView"
        }
      ],
      "role": "symbol",
      "title": "NSScrubberArrangedView",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberarrangedview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberDataSource": {
      "abstract": [
        {
          "text": "A set of methods that a scrubber data source object implements to provide items to the scrubber from an associated data collection in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScrubberDataSource"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberDataSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrubberDataSource"
        }
      ],
      "role": "symbol",
      "title": "NSScrubberDataSource",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberdatasource"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberDelegate": {
      "abstract": [
        {
          "text": "A set of methods that a scrubber delegate implements to respond to user interactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScrubberDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrubberDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSScrubberDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberdelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberFlowLayout": {
      "abstract": [
        {
          "text": "A concrete layout object that arranges items end-to-end in a linear strip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScrubberFlowLayout"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberFlowLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrubberFlowLayout"
        }
      ],
      "role": "symbol",
      "title": "NSScrubberFlowLayout",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberflowlayout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberFlowLayoutDelegate": {
      "abstract": [
        {
          "text": "A protocol that a scrubber delegate can adopt to provide the size of an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScrubberFlowLayoutDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberFlowLayoutDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrubberFlowLayoutDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSScrubberFlowLayoutDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberflowlayoutdelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberImageItemView": {
      "abstract": [
        {
          "text": "A concrete view subclass for displaying images in a scrubber items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScrubberImageItemView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberImageItemView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrubberImageItemView"
        }
      ],
      "role": "symbol",
      "title": "NSScrubberImageItemView",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberimageitemview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberItemView": {
      "abstract": [
        {
          "text": "An item at a specific index position in the scrubber.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScrubberItemView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberItemView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrubberItemView"
        }
      ],
      "role": "symbol",
      "title": "NSScrubberItemView",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberitemview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout": {
      "abstract": [
        {
          "text": "An abstract class that describes the layout of items within a scrubber control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScrubberLayout"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrubberLayout"
        }
      ],
      "role": "symbol",
      "title": "NSScrubberLayout",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberlayout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayoutAttributes": {
      "abstract": [
        {
          "text": "The layout of a scrubber item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScrubberLayoutAttributes"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayoutAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrubberLayoutAttributes"
        }
      ],
      "role": "symbol",
      "title": "NSScrubberLayoutAttributes",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberlayoutattributes"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberProportionalLayout": {
      "abstract": [
        {
          "text": "A concrete layout object that sizes each item to some fraction of the scrubber’s visible size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScrubberProportionalLayout"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberProportionalLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrubberProportionalLayout"
        }
      ],
      "role": "symbol",
      "title": "NSScrubberProportionalLayout",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberproportionallayout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberSelectionStyle": {
      "abstract": [
        {
          "text": "An abstract class that provides decorative accessory views for selected and highlighted items within a scrubber control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScrubberSelectionStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberSelectionStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrubberSelectionStyle"
        }
      ],
      "role": "symbol",
      "title": "NSScrubberSelectionStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberselectionstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberSelectionView": {
      "abstract": [
        {
          "text": "An abstract base class for specifying the appearance of a highlighted or selected item in a scrubber.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScrubberSelectionView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberSelectionView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrubberSelectionView"
        }
      ],
      "role": "symbol",
      "title": "NSScrubberSelectionView",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubberselectionview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScrubberTextItemView": {
      "abstract": [
        {
          "text": "A concrete view subclass for displaying text for an item in a scrubber.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScrubberTextItemView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScrubberTextItemView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrubberTextItemView"
        }
      ],
      "role": "symbol",
      "title": "NSScrubberTextItemView",
      "type": "topic",
      "url": "/documentation/appkit/nsscrubbertextitemview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerTouchBarItem": {
      "abstract": [
        {
          "text": "A bar item that, along with its delegate, provides a list of objects eligible for sharing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSharingServicePickerTouchBarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerTouchBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingServicePickerTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSSharingServicePickerTouchBarItem",
      "type": "topic",
      "url": "/documentation/appkit/nssharingservicepickertouchbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSliderTouchBarItem": {
      "abstract": [
        {
          "text": "A bar item that provides a slider control for choosing a value in a range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSliderTouchBarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSliderTouchBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSliderTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSSliderTouchBarItem",
      "type": "topic",
      "url": "/documentation/appkit/nsslidertouchbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSStepperTouchBarItem": {
      "abstract": [
        {
          "text": "A bar item that provides a stepper control for incrementing or decrementing a value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStepperTouchBarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSStepperTouchBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStepperTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSStepperTouchBarItem",
      "type": "topic",
      "url": "/documentation/appkit/nssteppertouchbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTouchBar": {
      "abstract": [
        {
          "text": "An object that provides dynamic contextual controls in the Touch Bar of supported models of MacBook Pro.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTouchBar"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouchBar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTouchBar"
        }
      ],
      "role": "symbol",
      "title": "NSTouchBar",
      "type": "topic",
      "url": "/documentation/appkit/nstouchbar"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTouchBarDelegate": {
      "abstract": [
        {
          "text": "A protocol that allows you to provide the items for a bar dynamically.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTouchBarDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouchBarDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTouchBarDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSTouchBarDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nstouchbardelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTouchBarItem": {
      "abstract": [
        {
          "text": "A UI control shown in the Touch Bar on supported models of MacBook Pro.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTouchBarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouchBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSTouchBarItem",
      "type": "topic",
      "url": "/documentation/appkit/nstouchbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTouchBarProvider": {
      "abstract": [
        {
          "text": "A protocol that an object adopts to create a bar object in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTouchBarProvider"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouchBarProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTouchBarProvider"
        }
      ],
      "role": "symbol",
      "title": "NSTouchBarProvider",
      "type": "topic",
      "url": "/documentation/appkit/nstouchbarprovider"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions": {
      "abstract": [
        {
          "text": "An object that specifies how user interface elements resize themselves when space is constrained.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserInterfaceCompressionOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUserInterfaceCompressionOptions"
        }
      ],
      "role": "symbol",
      "title": "NSUserInterfaceCompressionOptions",
      "type": "topic",
      "url": "/documentation/appkit/nsuserinterfacecompressionoptions"
    },
    "doc://com.apple.appkit/documentation/AppKit/accessibility-for-appkit": {
      "abstract": [
        {
          "text": "Make your AppKit apps accessible to everyone who uses macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/accessibility-for-appkit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Accessibility for AppKit",
      "type": "topic",
      "url": "/documentation/appkit/accessibility-for-appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/creating-and-customizing-the-touch-bar": {
      "abstract": [
        {
          "text": "Adopt Touch Bar support by displaying interactive content and controls for your macOS apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/creating-and-customizing-the-touch-bar",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating and Customizing the Touch Bar",
      "type": "topic",
      "url": "/documentation/appkit/creating-and-customizing-the-touch-bar"
    },
    "doc://com.apple.appkit/documentation/AppKit/drag-and-drop": {
      "abstract": [
        {
          "text": "Support the direct manipulation of your app’s content using drag and drop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/drag-and-drop",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Drag and Drop",
      "type": "topic",
      "url": "/documentation/appkit/drag-and-drop"
    },
    "doc://com.apple.appkit/documentation/AppKit/gestures": {
      "abstract": [
        {
          "text": "Encapsulate your app’s event-handling logic in gesture recognizers so that you can reuse that code throughout your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/gestures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Gestures",
      "type": "topic",
      "url": "/documentation/appkit/gestures"
    },
    "doc://com.apple.appkit/documentation/AppKit/integrating-a-toolbar-and-touch-bar-into-your-app": {
      "abstract": [
        {
          "text": "Provide users quick access to your app’s features from a toolbar and corresponding Touch Bar.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/integrating-a-toolbar-and-touch-bar-into-your-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Integrating a Toolbar and Touch Bar into Your App",
      "type": "topic",
      "url": "/documentation/appkit/integrating-a-toolbar-and-touch-bar-into-your-app"
    },
    "doc://com.apple.appkit/documentation/AppKit/menus-cursors-and-the-dock": {
      "abstract": [
        {
          "text": "Implement menus and cursors to facilitate interactions with your app, and use your app’s Dock tile to convey updated information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/menus-cursors-and-the-dock",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Menus, Cursors, and the Dock",
      "type": "topic",
      "url": "/documentation/appkit/menus-cursors-and-the-dock"
    },
    "doc://com.apple.appkit/documentation/AppKit/mouse-keyboard-and-trackpad": {
      "abstract": [
        {
          "text": "Handle events related to mouse, keyboard, and trackpad input.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/mouse-keyboard-and-trackpad",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mouse, Keyboard, and Trackpad",
      "type": "topic",
      "url": "/documentation/appkit/mouse-keyboard-and-trackpad"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "User-Interactions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/mouse-keyboard-and-trackpad",
        "doc://com.apple.appkit/documentation/AppKit/menus-cursors-and-the-dock",
        "doc://com.apple.appkit/documentation/AppKit/gestures",
        "doc://com.apple.appkit/documentation/AppKit/drag-and-drop",
        "doc://com.apple.appkit/documentation/AppKit/accessibility-for-appkit"
      ],
      "title": "User Interactions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/integrating-a-toolbar-and-touch-bar-into-your-app",
        "doc://com.apple.appkit/documentation/AppKit/creating-and-customizing-the-touch-bar",
        "doc://com.apple.appkit/documentation/AppKit/NSTouchBar",
        "doc://com.apple.appkit/documentation/AppKit/NSTouchBarDelegate",
        "doc://com.apple.appkit/documentation/AppKit/NSTouchBarProvider"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Touch-Bar-items",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTouchBarItem",
        "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItem",
        "doc://com.apple.appkit/documentation/AppKit/NSColorPickerTouchBarItem",
        "doc://com.apple.appkit/documentation/AppKit/NSCustomTouchBarItem",
        "doc://com.apple.appkit/documentation/AppKit/NSGroupTouchBarItem",
        "doc://com.apple.appkit/documentation/AppKit/NSPopoverTouchBarItem",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerTouchBarItem",
        "doc://com.apple.appkit/documentation/AppKit/NSSliderTouchBarItem",
        "doc://com.apple.appkit/documentation/AppKit/NSStepperTouchBarItem",
        "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions",
        "doc://com.apple.appkit/documentation/AppKit/NSButtonTouchBarItem",
        "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem",
        "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum",
        "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/SelectionMode-swift.enum"
      ],
      "title": "Touch Bar items"
    },
    {
      "anchor": "Scrubbers",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScrubber",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberDataSource",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberDelegate"
      ],
      "title": "Scrubbers"
    },
    {
      "anchor": "Scrubber-items",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberItemView",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberArrangedView",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberImageItemView",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberSelectionStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberSelectionView",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberTextItemView"
      ],
      "title": "Scrubber items"
    },
    {
      "anchor": "Scrubber-layouts",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberFlowLayout",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberFlowLayoutDelegate",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberProportionalLayout",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayoutAttributes",
        "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout"
      ],
      "title": "Scrubber layouts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/integrating-a-toolbar-and-touch-bar-into-your-app",
                "doc://com.apple.appkit/documentation/AppKit/creating-and-customizing-the-touch-bar",
                "doc://com.apple.appkit/documentation/AppKit/NSTouchBar",
                "doc://com.apple.appkit/documentation/AppKit/NSTouchBarDelegate",
                "doc://com.apple.appkit/documentation/AppKit/NSTouchBarProvider"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Touch-Bar-items",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTouchBarItem",
                "doc://com.apple.appkit/documentation/AppKit/NSCandidateListTouchBarItem",
                "doc://com.apple.appkit/documentation/AppKit/NSColorPickerTouchBarItem",
                "doc://com.apple.appkit/documentation/AppKit/NSCustomTouchBarItem",
                "doc://com.apple.appkit/documentation/AppKit/NSGroupTouchBarItem",
                "doc://com.apple.appkit/documentation/AppKit/NSPopoverTouchBarItem",
                "doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerTouchBarItem",
                "doc://com.apple.appkit/documentation/AppKit/NSSliderTouchBarItem",
                "doc://com.apple.appkit/documentation/AppKit/NSStepperTouchBarItem",
                "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions",
                "doc://com.apple.appkit/documentation/AppKit/NSButtonTouchBarItem",
                "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem",
                "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/ControlRepresentation-swift.enum",
                "doc://com.apple.appkit/documentation/AppKit/NSPickerTouchBarItem/SelectionMode-swift.enum"
              ],
              "title": "Touch Bar items"
            },
            {
              "anchor": "Scrubbers",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScrubber",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberDataSource",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberDelegate"
              ],
              "title": "Scrubbers"
            },
            {
              "anchor": "Scrubber-items",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberItemView",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberArrangedView",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberImageItemView",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberSelectionStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberSelectionView",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberTextItemView"
              ],
              "title": "Scrubber items"
            },
            {
              "anchor": "Scrubber-layouts",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberFlowLayout",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberFlowLayoutDelegate",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberProportionalLayout",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayoutAttributes",
                "doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout"
              ],
              "title": "Scrubber layouts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "User-Interactions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/mouse-keyboard-and-trackpad",
                "doc://com.apple.appkit/documentation/AppKit/menus-cursors-and-the-dock",
                "doc://com.apple.appkit/documentation/AppKit/gestures",
                "doc://com.apple.appkit/documentation/AppKit/drag-and-drop",
                "doc://com.apple.appkit/documentation/AppKit/accessibility-for-appkit"
              ],
              "title": "User Interactions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBar/title",
          "value": "NSTouchBar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBar/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButtonTouchBarItem/title",
          "value": "NSButtonTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButtonTouchBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButtonTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopoverTouchBarItem/title",
          "value": "NSPopoverTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopoverTouchBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPopoverTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPopoverTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPopoverTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout/title",
          "value": "NSScrubberLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGroupTouchBarItem/title",
          "value": "NSGroupTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGroupTouchBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGroupTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGroupTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGroupTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceCompressionOptions/title",
          "value": "NSUserInterfaceCompressionOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceCompressionOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceCompressionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceCompressionOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceCompressionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayoutAttributes/title",
          "value": "NSScrubberLayoutAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayoutAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayoutAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerTouchBarItem/title",
          "value": "NSSharingServicePickerTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerTouchBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServicePickerTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingServicePickerTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem/title",
          "value": "NSPickerTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberFlowLayoutDelegate/title",
          "value": "NSScrubberFlowLayoutDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberFlowLayoutDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberFlowLayoutDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberFlowLayoutDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberFlowLayoutDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderTouchBarItem/title",
          "value": "NSSliderTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderTouchBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSliderTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSliderTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSliderTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarProvider/title",
          "value": "NSTouchBarProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchBarProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchBarProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberItemView/title",
          "value": "NSScrubberItemView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberItemView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberItemView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberItemView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberItemView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberFlowLayout/title",
          "value": "NSScrubberFlowLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberFlowLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberFlowLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberFlowLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberFlowLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberProportionalLayout/title",
          "value": "NSScrubberProportionalLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberProportionalLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberProportionalLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberProportionalLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberProportionalLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarItem/title",
          "value": "NSTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberDataSource/title",
          "value": "NSScrubberDataSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberDataSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberDataSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberArrangedView/title",
          "value": "NSScrubberArrangedView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberArrangedView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberArrangedView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberArrangedView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberArrangedView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1ControlRepresentation-swift.enum/title",
          "value": "NSPickerTouchBarItemControlRepresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1ControlRepresentation-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItemControlRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1ControlRepresentation-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItemControlRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberSelectionView/title",
          "value": "NSScrubberSelectionView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberSelectionView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberSelectionView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberSelectionView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberSelectionView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStepperTouchBarItem/title",
          "value": "NSStepperTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStepperTouchBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStepperTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStepperTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStepperTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubber/title",
          "value": "NSScrubber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubber/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberImageItemView/title",
          "value": "NSScrubberImageItemView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberImageItemView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberImageItemView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberImageItemView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberImageItemView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberTextItemView/title",
          "value": "NSScrubberTextItemView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberTextItemView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberTextItemView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberTextItemView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberTextItemView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCustomTouchBarItem/title",
          "value": "NSCustomTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCustomTouchBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCustomTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCustomTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCustomTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCandidateListTouchBarItem/title",
          "value": "NSCandidateListTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCandidateListTouchBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCandidateListTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCandidateListTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCandidateListTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberSelectionStyle/title",
          "value": "NSScrubberSelectionStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberSelectionStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberSelectionStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberSelectionStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberSelectionStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberDelegate/title",
          "value": "NSScrubberDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrubberDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarDelegate/title",
          "value": "NSTouchBarDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchBarDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchBarDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickerTouchBarItem/title",
          "value": "NSColorPickerTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickerTouchBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorPickerTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorPickerTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorPickerTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1SelectionMode-swift.enum/title",
          "value": "NSPickerTouchBarItemSelectionMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1SelectionMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItemSelectionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPickerTouchBarItem~1SelectionMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPickerTouchBarItemSelectionMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/touch-bar"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/touch-bar"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
