{
  "abstract": [
    {
      "text": "Manage the subviews, superview, and window of a view and respond to notifications when the view hierarchy changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
        "doc://com.apple.appkit/documentation/AppKit/NSView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/view-hierarchy"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "View Hierarchy"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/appkit/nsview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/addSubview(_:)": {
      "abstract": [
        {
          "text": "Adds a view to the view’s subviews so it’s displayed above its siblings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addSubview"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/addSubview(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addSubview:"
        }
      ],
      "role": "symbol",
      "title": "addSubview(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/addsubview(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/addSubview(_:positioned:relativeTo:)": {
      "abstract": [
        {
          "text": "Inserts a view among the view’s subviews so it’s displayed immediately above or below another view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addSubview"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "positioned"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowOrderingMode",
          "text": "OrderingMode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "relativeTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/addSubview(_:positioned:relativeTo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addSubview:positioned:relativeTo:"
        }
      ],
      "role": "symbol",
      "title": "addSubview(_:positioned:relativeTo:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/addsubview(_:positioned:relativeto:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/ancestorShared(with:)": {
      "abstract": [
        {
          "text": "Returns the closest ancestor shared by the view and another specified view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ancestorShared"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/ancestorShared(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ancestorSharedWithView:"
        }
      ],
      "role": "symbol",
      "title": "ancestorShared(with:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/ancestorshared(with:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/didAddSubview(_:)": {
      "abstract": [
        {
          "text": "Overridden by subclasses to perform additional actions when subviews are added to the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didAddSubview"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/didAddSubview(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "didAddSubview:"
        }
      ],
      "role": "symbol",
      "title": "didAddSubview(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/didaddsubview(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/enclosingMenuItem": {
      "abstract": [
        {
          "text": "The menu item containing the view or any of its superviews in the view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enclosingMenuItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMenuItem",
          "text": "NSMenuItem"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/enclosingMenuItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enclosingMenuItem"
        }
      ],
      "role": "symbol",
      "title": "enclosingMenuItem",
      "type": "topic",
      "url": "/documentation/appkit/nsview/enclosingmenuitem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/enclosingScrollView": {
      "abstract": [
        {
          "text": "The nearest ancestor scroll view that contains the current view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enclosingScrollView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSScrollView",
          "text": "NSScrollView"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/enclosingScrollView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enclosingScrollView"
        }
      ],
      "role": "symbol",
      "title": "enclosingScrollView",
      "type": "topic",
      "url": "/documentation/appkit/nsview/enclosingscrollview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/isDescendant(of:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the view is a subview of the specified view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isDescendant"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/isDescendant(of:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isDescendantOf:"
        }
      ],
      "role": "symbol",
      "title": "isDescendant(of:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/isdescendant(of:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/opaqueAncestor": {
      "abstract": [
        {
          "text": "The view’s closest opaque ancestor, which might be the view itself.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "opaqueAncestor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/opaqueAncestor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "opaqueAncestor"
        }
      ],
      "role": "symbol",
      "title": "opaqueAncestor",
      "type": "topic",
      "url": "/documentation/appkit/nsview/opaqueancestor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/removeFromSuperview()": {
      "abstract": [
        {
          "text": "Unlinks the view from its superview and its window, removes it from the responder chain, and invalidates its cursor rectangles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeFromSuperview"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/removeFromSuperview()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeFromSuperview"
        }
      ],
      "role": "symbol",
      "title": "removeFromSuperview()",
      "type": "topic",
      "url": "/documentation/appkit/nsview/removefromsuperview()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/removeFromSuperviewWithoutNeedingDisplay()": {
      "abstract": [
        {
          "text": "Unlinks the view from its superview and its window and removes it from the responder chain, but does not invalidate its cursor rectangles to cause redrawing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeFromSuperviewWithoutNeedingDisplay"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/removeFromSuperviewWithoutNeedingDisplay()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeFromSuperviewWithoutNeedingDisplay"
        }
      ],
      "role": "symbol",
      "title": "removeFromSuperviewWithoutNeedingDisplay()",
      "type": "topic",
      "url": "/documentation/appkit/nsview/removefromsuperviewwithoutneedingdisplay()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/replaceSubview(_:with:)": {
      "abstract": [
        {
          "text": "Replaces one of the view’s subviews with another view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "replaceSubview"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/replaceSubview(_:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "replaceSubview:with:"
        }
      ],
      "role": "symbol",
      "title": "replaceSubview(_:with:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/replacesubview(_:with:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/sortSubviews(_:context:)": {
      "abstract": [
        {
          "text": "Orders the view’s immediate subviews using the specified comparator function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sortSubviews"
        },
        {
          "kind": "text",
          "text": "(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSComparisonResult",
          "text": "ComparisonResult"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "context"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/sortSubviews(_:context:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sortSubviewsUsingFunction:context:"
        }
      ],
      "role": "symbol",
      "title": "sortSubviews(_:context:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/sortsubviews(_:context:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/subviews": {
      "abstract": [
        {
          "text": "The array of views embedded in the current view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subviews"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/subviews",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subviews"
        }
      ],
      "role": "symbol",
      "title": "subviews",
      "type": "topic",
      "url": "/documentation/appkit/nsview/subviews"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/superview": {
      "abstract": [
        {
          "text": "The view that is the parent of the current view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "superview"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/superview",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "superview"
        }
      ],
      "role": "symbol",
      "title": "superview",
      "type": "topic",
      "url": "/documentation/appkit/nsview/superview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/tag": {
      "abstract": [
        {
          "text": "The view’s tag, which is an integer that you use to identify the view within your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/tag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tag"
        }
      ],
      "role": "symbol",
      "title": "tag",
      "type": "topic",
      "url": "/documentation/appkit/nsview/tag"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/viewDidMoveToSuperview()": {
      "abstract": [
        {
          "text": "Informs the view that its superview has changed (possibly to ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewDidMoveToSuperview"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/viewDidMoveToSuperview()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewDidMoveToSuperview"
        }
      ],
      "role": "symbol",
      "title": "viewDidMoveToSuperview()",
      "type": "topic",
      "url": "/documentation/appkit/nsview/viewdidmovetosuperview()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/viewDidMoveToWindow()": {
      "abstract": [
        {
          "text": "Informs the view that it has been added to a new view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewDidMoveToWindow"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/viewDidMoveToWindow()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewDidMoveToWindow"
        }
      ],
      "role": "symbol",
      "title": "viewDidMoveToWindow()",
      "type": "topic",
      "url": "/documentation/appkit/nsview/viewdidmovetowindow()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/viewWillMove(toSuperview:)": {
      "abstract": [
        {
          "text": "Informs the view that its superview is about to change to the specified superview (which may be ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewWillMove"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "toSuperview"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/viewWillMove(toSuperview:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewWillMoveToSuperview:"
        }
      ],
      "role": "symbol",
      "title": "viewWillMove(toSuperview:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/viewwillmove(tosuperview:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/viewWillMove(toWindow:)": {
      "abstract": [
        {
          "text": "Informs the view that it’s being added to the view hierarchy of the specified window object (which may be ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewWillMove"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "toWindow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/viewWillMove(toWindow:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewWillMoveToWindow:"
        }
      ],
      "role": "symbol",
      "title": "viewWillMove(toWindow:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/viewwillmove(towindow:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/viewWithTag(_:)": {
      "abstract": [
        {
          "text": "Returns the view’s nearest descendant (including itself) with a specific tag, or ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": " if no subview has that tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewWithTag"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/viewWithTag(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewWithTag:"
        }
      ],
      "role": "symbol",
      "title": "viewWithTag(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/viewwithtag(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/willRemoveSubview(_:)": {
      "abstract": [
        {
          "text": "Overridden by subclasses to perform additional actions before subviews are removed from the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willRemoveSubview"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/willRemoveSubview(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "willRemoveSubview:"
        }
      ],
      "role": "symbol",
      "title": "willRemoveSubview(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/willremovesubview(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/window": {
      "abstract": [
        {
          "text": "The view’s window object, if it is installed in a window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "window"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/window",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "window"
        }
      ],
      "role": "symbol",
      "title": "window",
      "type": "topic",
      "url": "/documentation/appkit/nsview/window"
    },
    "doc://com.apple.appkit/documentation/AppKit/core-animation-support": {
      "abstract": [
        {
          "text": "Manage the layer object that provides the view’s visual representation and accelerates drawing operations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/core-animation-support",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Animation Support",
      "type": "topic",
      "url": "/documentation/appkit/core-animation-support"
    },
    "doc://com.apple.appkit/documentation/AppKit/nsview-appearance": {
      "abstract": [
        {
          "text": "Change the view’s visibility, vibrancy, and focus ring and respond to appearance-related changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nsview-appearance",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Appearance",
      "type": "topic",
      "url": "/documentation/appkit/nsview-appearance"
    },
    "doc://com.apple.appkit/documentation/AppKit/related-ui": {
      "abstract": [
        {
          "text": "Manage contextual menus, cursors, tool tips, and other system-provided windows and content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/related-ui",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Related UI",
      "type": "topic",
      "url": "/documentation/appkit/related-ui"
    },
    "doc://com.apple.appkit/documentation/AppKit/view-coordinates": {
      "abstract": [
        {
          "text": "Manage the frame and bounds rectangles that determine the size and position of the view in the view hierarchy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/view-coordinates",
      "kind": "article",
      "role": "collectionGroup",
      "title": "View Coordinates",
      "type": "topic",
      "url": "/documentation/appkit/view-coordinates"
    },
    "doc://com.apple.appkit/documentation/AppKit/views-and-controls": {
      "abstract": [
        {
          "text": "Present your content onscreen and handle user input and events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Views and Controls",
      "type": "topic",
      "url": "/documentation/appkit/views-and-controls"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-view",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/view-coordinates",
        "doc://com.apple.appkit/documentation/AppKit/nsview-appearance",
        "doc://com.apple.appkit/documentation/AppKit/core-animation-support",
        "doc://com.apple.appkit/documentation/AppKit/related-ui"
      ],
      "title": "Configuring the view"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-Related-Objects",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/superview",
        "doc://com.apple.appkit/documentation/AppKit/NSView/subviews",
        "doc://com.apple.appkit/documentation/AppKit/NSView/window",
        "doc://com.apple.appkit/documentation/AppKit/NSView/opaqueAncestor",
        "doc://com.apple.appkit/documentation/AppKit/NSView/isDescendant(of:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/ancestorShared(with:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/enclosingMenuItem",
        "doc://com.apple.appkit/documentation/AppKit/NSView/enclosingScrollView"
      ],
      "title": "Getting the Related Objects"
    },
    {
      "anchor": "Adding-and-Removing-Subviews",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/addSubview(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/addSubview(_:positioned:relativeTo:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/removeFromSuperview()",
        "doc://com.apple.appkit/documentation/AppKit/NSView/removeFromSuperviewWithoutNeedingDisplay()",
        "doc://com.apple.appkit/documentation/AppKit/NSView/replaceSubview(_:with:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/sortSubviews(_:context:)"
      ],
      "title": "Adding and Removing Subviews"
    },
    {
      "anchor": "Responding-to-View-Related-Notifications",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/didAddSubview(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/viewDidMoveToSuperview()",
        "doc://com.apple.appkit/documentation/AppKit/NSView/viewDidMoveToWindow()",
        "doc://com.apple.appkit/documentation/AppKit/NSView/viewWillMove(toSuperview:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/viewWillMove(toWindow:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/willRemoveSubview(_:)"
      ],
      "title": "Responding to View-Related Notifications"
    },
    {
      "anchor": "Identifying-Views-by-Tag",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/viewWithTag(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/tag"
      ],
      "title": "Identifying Views by Tag"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-Related-Objects",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/superview",
                "doc://com.apple.appkit/documentation/AppKit/NSView/subviews",
                "doc://com.apple.appkit/documentation/AppKit/NSView/window",
                "doc://com.apple.appkit/documentation/AppKit/NSView/opaqueAncestor",
                "doc://com.apple.appkit/documentation/AppKit/NSView/isDescendant(of:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/ancestorShared(with:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/enclosingMenuItem",
                "doc://com.apple.appkit/documentation/AppKit/NSView/enclosingScrollView"
              ],
              "title": "Getting the Related Objects"
            },
            {
              "anchor": "Adding-and-Removing-Subviews",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/addSubview(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/addSubview(_:positioned:relativeTo:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/removeFromSuperview()",
                "doc://com.apple.appkit/documentation/AppKit/NSView/removeFromSuperviewWithoutNeedingDisplay()",
                "doc://com.apple.appkit/documentation/AppKit/NSView/replaceSubview(_:with:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/sortSubviews(_:context:)"
              ],
              "title": "Adding and Removing Subviews"
            },
            {
              "anchor": "Responding-to-View-Related-Notifications",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/didAddSubview(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/viewDidMoveToSuperview()",
                "doc://com.apple.appkit/documentation/AppKit/NSView/viewDidMoveToWindow()",
                "doc://com.apple.appkit/documentation/AppKit/NSView/viewWillMove(toSuperview:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/viewWillMove(toWindow:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/willRemoveSubview(_:)"
              ],
              "title": "Responding to View-Related Notifications"
            },
            {
              "anchor": "Identifying-Views-by-Tag",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/viewWithTag(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/tag"
              ],
              "title": "Identifying Views by Tag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-view",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/view-coordinates",
                "doc://com.apple.appkit/documentation/AppKit/nsview-appearance",
                "doc://com.apple.appkit/documentation/AppKit/core-animation-support",
                "doc://com.apple.appkit/documentation/AppKit/related-ui"
              ],
              "title": "Configuring the view"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1addSubview(_:positioned:relativeTo:)/title",
          "value": "addSubview:positioned:relativeTo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1addSubview(_:positioned:relativeTo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addSubview:positioned:relativeTo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1viewWillMove(toWindow:)/title",
          "value": "viewWillMoveToWindow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1viewWillMove(toWindow:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "viewWillMoveToWindow:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1viewWillMove(toSuperview:)/title",
          "value": "viewWillMoveToSuperview:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1viewWillMove(toSuperview:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "viewWillMoveToSuperview:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1subviews/title",
          "value": "subviews"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1subviews/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subviews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1replaceSubview(_:with:)/title",
          "value": "replaceSubview:with:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1replaceSubview(_:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "replaceSubview:with:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1superview/title",
          "value": "superview"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1superview/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "superview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1window/title",
          "value": "window"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1window/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "window"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1didAddSubview(_:)/title",
          "value": "didAddSubview:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1didAddSubview(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "didAddSubview:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1removeFromSuperviewWithoutNeedingDisplay()/title",
          "value": "removeFromSuperviewWithoutNeedingDisplay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1removeFromSuperviewWithoutNeedingDisplay()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeFromSuperviewWithoutNeedingDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1isDescendant(of:)/title",
          "value": "isDescendantOf:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1isDescendant(of:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "isDescendantOf:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1willRemoveSubview(_:)/title",
          "value": "willRemoveSubview:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1willRemoveSubview(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "willRemoveSubview:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1ancestorShared(with:)/title",
          "value": "ancestorSharedWithView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1ancestorShared(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "ancestorSharedWithView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title",
          "value": "NSView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1viewWithTag(_:)/title",
          "value": "viewWithTag:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1viewWithTag(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "viewWithTag:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1opaqueAncestor/title",
          "value": "opaqueAncestor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1opaqueAncestor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "opaqueAncestor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1tag/title",
          "value": "tag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1tag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1addSubview(_:)/title",
          "value": "addSubview:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1addSubview(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addSubview:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1sortSubviews(_:context:)/title",
          "value": "sortSubviewsUsingFunction:context:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1sortSubviews(_:context:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sortSubviewsUsingFunction:context:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1viewDidMoveToWindow()/title",
          "value": "viewDidMoveToWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1viewDidMoveToWindow()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "viewDidMoveToWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1enclosingMenuItem/title",
          "value": "enclosingMenuItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1enclosingMenuItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enclosingMenuItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1removeFromSuperview()/title",
          "value": "removeFromSuperview"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1removeFromSuperview()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeFromSuperview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1enclosingScrollView/title",
          "value": "enclosingScrollView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1enclosingScrollView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enclosingScrollView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1viewDidMoveToSuperview()/title",
          "value": "viewDidMoveToSuperview"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1viewDidMoveToSuperview()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "viewDidMoveToSuperview"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/view-hierarchy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/view-hierarchy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
