{
  "abstract": [
    {
      "text": "Manage the frame and bounds rectangles that determine the size and position of the view in the view hierarchy.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
        "doc://com.apple.appkit/documentation/AppKit/NSView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/view-coordinates"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "View Coordinates"
  },
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/appkit/nsview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/backingAlignedRect(_:options:)": {
      "abstract": [
        {
          "text": "Returns a backing store pixel-aligned rectangle in local view coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backingAlignedRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSAlignmentOptions",
          "text": "AlignmentOptions"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/backingAlignedRect(_:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backingAlignedRect:options:"
        }
      ],
      "role": "symbol",
      "title": "backingAlignedRect(_:options:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/backingalignedrect(_:options:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/bounds": {
      "abstract": [
        {
          "text": "The view’s bounds rectangle, which expresses its location and size in its own coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/bounds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bounds"
        }
      ],
      "role": "symbol",
      "title": "bounds",
      "type": "topic",
      "url": "/documentation/appkit/nsview/bounds"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/boundsDidChangeNotification": {
      "abstract": [
        {
          "text": "Posted whenever the ",
          "type": "text"
        },
        {
          "code": "NSView",
          "type": "codeVoice"
        },
        {
          "text": "‘s bounds rectangle changes to a new value independently of the frame rectangle, but only when the view’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/postsBoundsChangedNotifications",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property is ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/swift/true",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "boundsDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/boundsDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewBoundsDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "boundsDidChangeNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsview/boundsdidchangenotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/boundsRotation": {
      "abstract": [
        {
          "text": "The angle of rotation, measured in degrees, applied to the view’s bounds rectangle relative to its frame rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "boundsRotation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/boundsRotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "boundsRotation"
        }
      ],
      "role": "symbol",
      "title": "boundsRotation",
      "type": "topic",
      "url": "/documentation/appkit/nsview/boundsrotation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/centerScanRect(_:)": {
      "abstract": [
        {
          "text": "Converts the corners of a specified rectangle to lie on the center of device pixels, which is useful in compensating for rendering overscanning when the coordinate system has been scaled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centerScanRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/centerScanRect(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "centerScanRect:"
        }
      ],
      "role": "symbol",
      "title": "centerScanRect(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/centerscanrect(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/convert(_:from:)-1dq9l": {
      "abstract": [
        {
          "text": "Converts a point from the coordinate system of a given view to that of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/convert(_:from:)-1dq9l",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertPoint:fromView:"
        }
      ],
      "role": "symbol",
      "title": "convert(_:from:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/convert(_:from:)-1dq9l"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/convert(_:from:)-40x0w": {
      "abstract": [
        {
          "text": "Converts a size from another view’s coordinate system to that of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/convert(_:from:)-40x0w",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertSize:fromView:"
        }
      ],
      "role": "symbol",
      "title": "convert(_:from:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/convert(_:from:)-40x0w"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/convert(_:from:)-7fbb6": {
      "abstract": [
        {
          "text": "Converts a rectangle from the coordinate system of another view to that of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/convert(_:from:)-7fbb6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertRect:fromView:"
        }
      ],
      "role": "symbol",
      "title": "convert(_:from:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/convert(_:from:)-7fbb6"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/convert(_:to:)-3cqqt": {
      "abstract": [
        {
          "text": "Converts a rectangle from the view’s coordinate system to that of another view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/convert(_:to:)-3cqqt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertRect:toView:"
        }
      ],
      "role": "symbol",
      "title": "convert(_:to:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/convert(_:to:)-3cqqt"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/convert(_:to:)-5nptx": {
      "abstract": [
        {
          "text": "Converts a size from the view’s coordinate system to that of another view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/convert(_:to:)-5nptx",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertSize:toView:"
        }
      ],
      "role": "symbol",
      "title": "convert(_:to:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/convert(_:to:)-5nptx"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/convert(_:to:)-6u9ir": {
      "abstract": [
        {
          "text": "Converts a point from the view’s coordinate system to that of a given view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/convert(_:to:)-6u9ir",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertPoint:toView:"
        }
      ],
      "role": "symbol",
      "title": "convert(_:to:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/convert(_:to:)-6u9ir"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/convertFromBacking(_:)-229ps": {
      "abstract": [
        {
          "text": "Converts a point from its pixel aligned backing store coordinate system to the view’s interior coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convertFromBacking"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/convertFromBacking(_:)-229ps",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertPointFromBacking:"
        }
      ],
      "role": "symbol",
      "title": "convertFromBacking(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/convertfrombacking(_:)-229ps"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/convertFromBacking(_:)-2njpa": {
      "abstract": [
        {
          "text": "Converts a rectangle from its pixel aligned backing store coordinate system to the view’s interior coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convertFromBacking"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/convertFromBacking(_:)-2njpa",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertRectFromBacking:"
        }
      ],
      "role": "symbol",
      "title": "convertFromBacking(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/convertfrombacking(_:)-2njpa"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/convertFromBacking(_:)-4agf9": {
      "abstract": [
        {
          "text": "Converts a size from its pixel aligned backing store coordinate system to the view’s interior coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convertFromBacking"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/convertFromBacking(_:)-4agf9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertSizeFromBacking:"
        }
      ],
      "role": "symbol",
      "title": "convertFromBacking(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/convertfrombacking(_:)-4agf9"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/convertFromLayer(_:)-3nsbu": {
      "abstract": [
        {
          "text": "Convert the point from the layer’s interior coordinate system to the view’s interior coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convertFromLayer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/convertFromLayer(_:)-3nsbu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertPointFromLayer:"
        }
      ],
      "role": "symbol",
      "title": "convertFromLayer(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/convertfromlayer(_:)-3nsbu"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/convertFromLayer(_:)-3usqp": {
      "abstract": [
        {
          "text": "Convert the size from the layer’s interior coordinate system to the view’s interior coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convertFromLayer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/convertFromLayer(_:)-3usqp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertSizeFromLayer:"
        }
      ],
      "role": "symbol",
      "title": "convertFromLayer(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/convertfromlayer(_:)-3usqp"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/convertFromLayer(_:)-8s5bi": {
      "abstract": [
        {
          "text": "Convert the rectangle from the layer’s interior coordinate system to the view’s interior coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convertFromLayer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/convertFromLayer(_:)-8s5bi",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertRectFromLayer:"
        }
      ],
      "role": "symbol",
      "title": "convertFromLayer(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/convertfromlayer(_:)-8s5bi"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/convertToBacking(_:)-2xx45": {
      "abstract": [
        {
          "text": "Converts a point from the view’s interior coordinate system to its pixel aligned backing store coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convertToBacking"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/convertToBacking(_:)-2xx45",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertPointToBacking:"
        }
      ],
      "role": "symbol",
      "title": "convertToBacking(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/converttobacking(_:)-2xx45"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/convertToBacking(_:)-3zors": {
      "abstract": [
        {
          "text": "Converts a rectangle from the view’s interior coordinate system to its pixel aligned backing store coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convertToBacking"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/convertToBacking(_:)-3zors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertRectToBacking:"
        }
      ],
      "role": "symbol",
      "title": "convertToBacking(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/converttobacking(_:)-3zors"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/convertToBacking(_:)-4ra9y": {
      "abstract": [
        {
          "text": "Converts a size from the view’s interior coordinate system to its pixel aligned backing store coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convertToBacking"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/convertToBacking(_:)-4ra9y",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertSizeToBacking:"
        }
      ],
      "role": "symbol",
      "title": "convertToBacking(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/converttobacking(_:)-4ra9y"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/convertToLayer(_:)-160pw": {
      "abstract": [
        {
          "text": "Convert the size from the view’s interior coordinate system to the layer’s interior coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convertToLayer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/convertToLayer(_:)-160pw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertRectToLayer:"
        }
      ],
      "role": "symbol",
      "title": "convertToLayer(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/converttolayer(_:)-160pw"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/convertToLayer(_:)-2vozx": {
      "abstract": [
        {
          "text": "Convert the size from the view’s interior coordinate system to the layer’s interior coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convertToLayer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/convertToLayer(_:)-2vozx",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertSizeToLayer:"
        }
      ],
      "role": "symbol",
      "title": "convertToLayer(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/converttolayer(_:)-2vozx"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/convertToLayer(_:)-44u7d": {
      "abstract": [
        {
          "text": "Convert the size from the view’s interior coordinate system to the layer’s interior coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convertToLayer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/convertToLayer(_:)-44u7d",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertPointToLayer:"
        }
      ],
      "role": "symbol",
      "title": "convertToLayer(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/converttolayer(_:)-44u7d"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/frame": {
      "abstract": [
        {
          "text": "The view’s frame rectangle, which defines its position and size in its superview’s coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/frame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "frame"
        }
      ],
      "role": "symbol",
      "title": "frame",
      "type": "topic",
      "url": "/documentation/appkit/nsview/frame"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/frameDidChangeNotification": {
      "abstract": [
        {
          "text": "Posted whenever the view’s frame rectangle changes to a new value, but only when the view’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/postsFrameChangedNotifications",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property is ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/swift/true",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frameDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/frameDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewFrameDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "frameDidChangeNotification",
      "type": "topic",
      "url": "/documentation/appkit/nsview/framedidchangenotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/frameRotation": {
      "abstract": [
        {
          "text": "The angle of rotation, measured in degrees, applied to the view’s frame rectangle relative to its superview’s coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frameRotation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/frameRotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "frameRotation"
        }
      ],
      "role": "symbol",
      "title": "frameRotation",
      "type": "topic",
      "url": "/documentation/appkit/nsview/framerotation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/isFlipped": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the view uses a flipped coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isFlipped"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/isFlipped",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "flipped"
        }
      ],
      "role": "symbol",
      "title": "isFlipped",
      "type": "topic",
      "url": "/documentation/appkit/nsview/isflipped"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/isRotatedFromBase": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the view or any of its ancestors has ever had a rotation factor applied to its frame or bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isRotatedFromBase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/isRotatedFromBase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rotatedFromBase"
        }
      ],
      "role": "symbol",
      "title": "isRotatedFromBase",
      "type": "topic",
      "url": "/documentation/appkit/nsview/isrotatedfrombase"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/isRotatedOrScaledFromBase": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the view or any of its ancestors has ever had a rotation factor applied to its frame or bounds, or has been scaled from the window’s base coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isRotatedOrScaledFromBase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/isRotatedOrScaledFromBase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rotatedOrScaledFromBase"
        }
      ],
      "role": "symbol",
      "title": "isRotatedOrScaledFromBase",
      "type": "topic",
      "url": "/documentation/appkit/nsview/isrotatedorscaledfrombase"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/postsBoundsChangedNotifications": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the view posts notifications when its bounds rectangle changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postsBoundsChangedNotifications"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/postsBoundsChangedNotifications",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "postsBoundsChangedNotifications"
        }
      ],
      "role": "symbol",
      "title": "postsBoundsChangedNotifications",
      "type": "topic",
      "url": "/documentation/appkit/nsview/postsboundschangednotifications"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/postsFrameChangedNotifications": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the view posts notifications when its frame rectangle changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postsFrameChangedNotifications"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/postsFrameChangedNotifications",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "postsFrameChangedNotifications"
        }
      ],
      "role": "symbol",
      "title": "postsFrameChangedNotifications",
      "type": "topic",
      "url": "/documentation/appkit/nsview/postsframechangednotifications"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/rotate(byDegrees:)": {
      "abstract": [
        {
          "text": "Rotates the view’s bounds rectangle by a specified degree value around the origin of the coordinate system, (0.0, 0.0).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rotate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "byDegrees"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/rotate(byDegrees:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rotateByAngle:"
        }
      ],
      "role": "symbol",
      "title": "rotate(byDegrees:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/rotate(bydegrees:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/scaleUnitSquare(to:)": {
      "abstract": [
        {
          "text": "Scales the view’s coordinate system so that the unit square scales to the specified dimensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleUnitSquare"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/scaleUnitSquare(to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scaleUnitSquareToSize:"
        }
      ],
      "role": "symbol",
      "title": "scaleUnitSquare(to:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/scaleunitsquare(to:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/setBoundsOrigin(_:)": {
      "abstract": [
        {
          "text": "Sets the origin of the view’s bounds rectangle to a specified point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setBoundsOrigin"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/setBoundsOrigin(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setBoundsOrigin:"
        }
      ],
      "role": "symbol",
      "title": "setBoundsOrigin(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/setboundsorigin(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/setBoundsSize(_:)": {
      "abstract": [
        {
          "text": "Sets the size of the view’s bounds rectangle to specified dimensions, inversely scaling its coordinate system relative to its frame rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setBoundsSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/setBoundsSize(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setBoundsSize:"
        }
      ],
      "role": "symbol",
      "title": "setBoundsSize(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/setboundssize(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/setFrameOrigin(_:)": {
      "abstract": [
        {
          "text": "Sets the origin of the view’s frame rectangle to the specified point, effectively repositioning it within its superview.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setFrameOrigin"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/setFrameOrigin(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFrameOrigin:"
        }
      ],
      "role": "symbol",
      "title": "setFrameOrigin(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/setframeorigin(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/setFrameSize(_:)": {
      "abstract": [
        {
          "text": "Sets the size of the view’s frame rectangle to the specified dimensions, resizing it within its superview without affecting its coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setFrameSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/setFrameSize(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFrameSize:"
        }
      ],
      "role": "symbol",
      "title": "setFrameSize(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/setframesize(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/translateOrigin(to:)": {
      "abstract": [
        {
          "text": "Translates the view’s coordinate system so that its origin moves to a new location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "translateOrigin"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/translateOrigin(to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "translateOriginToPoint:"
        }
      ],
      "role": "symbol",
      "title": "translateOrigin(to:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/translateorigin(to:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/core-animation-support": {
      "abstract": [
        {
          "text": "Manage the layer object that provides the view’s visual representation and accelerates drawing operations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/core-animation-support",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Animation Support",
      "type": "topic",
      "url": "/documentation/appkit/core-animation-support"
    },
    "doc://com.apple.appkit/documentation/AppKit/nsview-appearance": {
      "abstract": [
        {
          "text": "Change the view’s visibility, vibrancy, and focus ring and respond to appearance-related changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/nsview-appearance",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Appearance",
      "type": "topic",
      "url": "/documentation/appkit/nsview-appearance"
    },
    "doc://com.apple.appkit/documentation/AppKit/related-ui": {
      "abstract": [
        {
          "text": "Manage contextual menus, cursors, tool tips, and other system-provided windows and content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/related-ui",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Related UI",
      "type": "topic",
      "url": "/documentation/appkit/related-ui"
    },
    "doc://com.apple.appkit/documentation/AppKit/view-hierarchy": {
      "abstract": [
        {
          "text": "Manage the subviews, superview, and window of a view and respond to notifications when the view hierarchy changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/view-hierarchy",
      "kind": "article",
      "role": "collectionGroup",
      "title": "View Hierarchy",
      "type": "topic",
      "url": "/documentation/appkit/view-hierarchy"
    },
    "doc://com.apple.appkit/documentation/AppKit/views-and-controls": {
      "abstract": [
        {
          "text": "Present your content onscreen and handle user input and events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/views-and-controls",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Views and Controls",
      "type": "topic",
      "url": "/documentation/appkit/views-and-controls"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-view",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/view-hierarchy",
        "doc://com.apple.appkit/documentation/AppKit/nsview-appearance",
        "doc://com.apple.appkit/documentation/AppKit/core-animation-support",
        "doc://com.apple.appkit/documentation/AppKit/related-ui"
      ],
      "title": "Configuring the view"
    }
  ],
  "topicSections": [
    {
      "anchor": "Modifying-the-Frame-Rectangle",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/frame",
        "doc://com.apple.appkit/documentation/AppKit/NSView/setFrameOrigin(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/setFrameSize(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/frameRotation",
        "doc://com.apple.appkit/documentation/AppKit/NSView/frameDidChangeNotification",
        "doc://com.apple.appkit/documentation/AppKit/NSView/postsFrameChangedNotifications"
      ],
      "title": "Modifying the Frame Rectangle"
    },
    {
      "anchor": "Modifying-the-Bounds-Rectangle",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/bounds",
        "doc://com.apple.appkit/documentation/AppKit/NSView/setBoundsOrigin(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/setBoundsSize(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/boundsRotation",
        "doc://com.apple.appkit/documentation/AppKit/NSView/boundsDidChangeNotification",
        "doc://com.apple.appkit/documentation/AppKit/NSView/postsBoundsChangedNotifications"
      ],
      "title": "Modifying the Bounds Rectangle"
    },
    {
      "anchor": "Examining-Coordinate-System-Modifications",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/isFlipped",
        "doc://com.apple.appkit/documentation/AppKit/NSView/isRotatedFromBase",
        "doc://com.apple.appkit/documentation/AppKit/NSView/isRotatedOrScaledFromBase"
      ],
      "title": "Examining Coordinate System Modifications"
    },
    {
      "anchor": "Modifying-the-Coordinate-System",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/translateOrigin(to:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/scaleUnitSquare(to:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/rotate(byDegrees:)"
      ],
      "title": "Modifying the Coordinate System"
    },
    {
      "anchor": "Converting-Coordinate-Values",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/backingAlignedRect(_:options:)",
        "doc://com.apple.appkit/documentation/AppKit/NSView/convertFromBacking(_:)-229ps",
        "doc://com.apple.appkit/documentation/AppKit/NSView/convertToBacking(_:)-2xx45",
        "doc://com.apple.appkit/documentation/AppKit/NSView/convertFromLayer(_:)-3nsbu",
        "doc://com.apple.appkit/documentation/AppKit/NSView/convertToLayer(_:)-44u7d",
        "doc://com.apple.appkit/documentation/AppKit/NSView/convertFromBacking(_:)-2njpa",
        "doc://com.apple.appkit/documentation/AppKit/NSView/convertToBacking(_:)-3zors",
        "doc://com.apple.appkit/documentation/AppKit/NSView/convertFromLayer(_:)-8s5bi",
        "doc://com.apple.appkit/documentation/AppKit/NSView/convertToLayer(_:)-160pw",
        "doc://com.apple.appkit/documentation/AppKit/NSView/convertFromBacking(_:)-4agf9",
        "doc://com.apple.appkit/documentation/AppKit/NSView/convertToBacking(_:)-4ra9y",
        "doc://com.apple.appkit/documentation/AppKit/NSView/convertFromLayer(_:)-3usqp",
        "doc://com.apple.appkit/documentation/AppKit/NSView/convertToLayer(_:)-2vozx",
        "doc://com.apple.appkit/documentation/AppKit/NSView/convert(_:from:)-1dq9l",
        "doc://com.apple.appkit/documentation/AppKit/NSView/convert(_:to:)-6u9ir",
        "doc://com.apple.appkit/documentation/AppKit/NSView/convert(_:from:)-40x0w",
        "doc://com.apple.appkit/documentation/AppKit/NSView/convert(_:to:)-5nptx",
        "doc://com.apple.appkit/documentation/AppKit/NSView/convert(_:from:)-7fbb6",
        "doc://com.apple.appkit/documentation/AppKit/NSView/convert(_:to:)-3cqqt",
        "doc://com.apple.appkit/documentation/AppKit/NSView/centerScanRect(_:)"
      ],
      "title": "Converting Coordinate Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Modifying-the-Frame-Rectangle",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/frame",
                "doc://com.apple.appkit/documentation/AppKit/NSView/setFrameOrigin(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/setFrameSize(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/frameRotation",
                "doc://com.apple.appkit/documentation/AppKit/NSView/frameDidChangeNotification",
                "doc://com.apple.appkit/documentation/AppKit/NSView/postsFrameChangedNotifications"
              ],
              "title": "Modifying the Frame Rectangle"
            },
            {
              "anchor": "Modifying-the-Bounds-Rectangle",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/bounds",
                "doc://com.apple.appkit/documentation/AppKit/NSView/setBoundsOrigin(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/setBoundsSize(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/boundsRotation",
                "doc://com.apple.appkit/documentation/AppKit/NSView/boundsDidChangeNotification",
                "doc://com.apple.appkit/documentation/AppKit/NSView/postsBoundsChangedNotifications"
              ],
              "title": "Modifying the Bounds Rectangle"
            },
            {
              "anchor": "Examining-Coordinate-System-Modifications",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/isFlipped",
                "doc://com.apple.appkit/documentation/AppKit/NSView/isRotatedFromBase",
                "doc://com.apple.appkit/documentation/AppKit/NSView/isRotatedOrScaledFromBase"
              ],
              "title": "Examining Coordinate System Modifications"
            },
            {
              "anchor": "Modifying-the-Coordinate-System",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/translateOrigin(to:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/scaleUnitSquare(to:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/rotate(byDegrees:)"
              ],
              "title": "Modifying the Coordinate System"
            },
            {
              "anchor": "Converting-Coordinate-Values",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/backingAlignedRect(_:options:)",
                "doc://com.apple.appkit/documentation/AppKit/NSView/convertFromBacking(_:)-229ps",
                "doc://com.apple.appkit/documentation/AppKit/NSView/convertToBacking(_:)-2xx45",
                "doc://com.apple.appkit/documentation/AppKit/NSView/convertFromLayer(_:)-3nsbu",
                "doc://com.apple.appkit/documentation/AppKit/NSView/convertToLayer(_:)-44u7d",
                "doc://com.apple.appkit/documentation/AppKit/NSView/convertFromBacking(_:)-2njpa",
                "doc://com.apple.appkit/documentation/AppKit/NSView/convertToBacking(_:)-3zors",
                "doc://com.apple.appkit/documentation/AppKit/NSView/convertFromLayer(_:)-8s5bi",
                "doc://com.apple.appkit/documentation/AppKit/NSView/convertToLayer(_:)-160pw",
                "doc://com.apple.appkit/documentation/AppKit/NSView/convertFromBacking(_:)-4agf9",
                "doc://com.apple.appkit/documentation/AppKit/NSView/convertToBacking(_:)-4ra9y",
                "doc://com.apple.appkit/documentation/AppKit/NSView/convertFromLayer(_:)-3usqp",
                "doc://com.apple.appkit/documentation/AppKit/NSView/convertToLayer(_:)-2vozx",
                "doc://com.apple.appkit/documentation/AppKit/NSView/convert(_:from:)-1dq9l",
                "doc://com.apple.appkit/documentation/AppKit/NSView/convert(_:to:)-6u9ir",
                "doc://com.apple.appkit/documentation/AppKit/NSView/convert(_:from:)-40x0w",
                "doc://com.apple.appkit/documentation/AppKit/NSView/convert(_:to:)-5nptx",
                "doc://com.apple.appkit/documentation/AppKit/NSView/convert(_:from:)-7fbb6",
                "doc://com.apple.appkit/documentation/AppKit/NSView/convert(_:to:)-3cqqt",
                "doc://com.apple.appkit/documentation/AppKit/NSView/centerScanRect(_:)"
              ],
              "title": "Converting Coordinate Values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-view",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/view-hierarchy",
                "doc://com.apple.appkit/documentation/AppKit/nsview-appearance",
                "doc://com.apple.appkit/documentation/AppKit/core-animation-support",
                "doc://com.apple.appkit/documentation/AppKit/related-ui"
              ],
              "title": "Configuring the view"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convertToLayer(_:)-2vozx/title",
          "value": "convertSizeToLayer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convertToLayer(_:)-2vozx/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertSizeToLayer:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1backingAlignedRect(_:options:)/title",
          "value": "backingAlignedRect:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1backingAlignedRect(_:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "backingAlignedRect:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convertFromLayer(_:)-8s5bi/title",
          "value": "convertRectFromLayer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convertFromLayer(_:)-8s5bi/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertRectFromLayer:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1postsBoundsChangedNotifications/title",
          "value": "postsBoundsChangedNotifications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1postsBoundsChangedNotifications/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "postsBoundsChangedNotifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rotate(byDegrees:)/title",
          "value": "rotateByAngle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1rotate(byDegrees:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rotateByAngle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1scaleUnitSquare(to:)/title",
          "value": "scaleUnitSquareToSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1scaleUnitSquare(to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scaleUnitSquareToSize:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convertFromBacking(_:)-4agf9/title",
          "value": "convertSizeFromBacking:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convertFromBacking(_:)-4agf9/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertSizeFromBacking:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1boundsRotation/title",
          "value": "boundsRotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1boundsRotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "boundsRotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convert(_:from:)-40x0w/title",
          "value": "convertSize:fromView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convert(_:from:)-40x0w/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertSize:fromView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1setBoundsSize(_:)/title",
          "value": "setBoundsSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1setBoundsSize(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setBoundsSize:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convert(_:to:)-6u9ir/title",
          "value": "convertPoint:toView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convert(_:to:)-6u9ir/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertPoint:toView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1setFrameSize(_:)/title",
          "value": "setFrameSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1setFrameSize(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setFrameSize:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1frameRotation/title",
          "value": "frameRotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1frameRotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "frameRotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1translateOrigin(to:)/title",
          "value": "translateOriginToPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1translateOrigin(to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "translateOriginToPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convertFromLayer(_:)-3nsbu/title",
          "value": "convertPointFromLayer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convertFromLayer(_:)-3nsbu/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertPointFromLayer:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convertFromLayer(_:)-3usqp/title",
          "value": "convertSizeFromLayer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convertFromLayer(_:)-3usqp/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertSizeFromLayer:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convertToBacking(_:)-4ra9y/title",
          "value": "convertSizeToBacking:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convertToBacking(_:)-4ra9y/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertSizeToBacking:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title",
          "value": "NSView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convert(_:from:)-1dq9l/title",
          "value": "convertPoint:fromView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convert(_:from:)-1dq9l/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertPoint:fromView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1setBoundsOrigin(_:)/title",
          "value": "setBoundsOrigin:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1setBoundsOrigin(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setBoundsOrigin:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convertToLayer(_:)-160pw/title",
          "value": "convertRectToLayer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convertToLayer(_:)-160pw/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertRectToLayer:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1frameDidChangeNotification/title",
          "value": "NSViewFrameDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1frameDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewFrameDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1setFrameOrigin(_:)/title",
          "value": "setFrameOrigin:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1setFrameOrigin(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setFrameOrigin:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1postsFrameChangedNotifications/title",
          "value": "postsFrameChangedNotifications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1postsFrameChangedNotifications/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "postsFrameChangedNotifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1boundsDidChangeNotification/title",
          "value": "NSViewBoundsDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1boundsDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewBoundsDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1frame/title",
          "value": "frame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1frame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "frame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1isRotatedOrScaledFromBase/title",
          "value": "rotatedOrScaledFromBase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1isRotatedOrScaledFromBase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rotatedOrScaledFromBase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1isFlipped/title",
          "value": "flipped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1isFlipped/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "flipped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convert(_:from:)-7fbb6/title",
          "value": "convertRect:fromView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convert(_:from:)-7fbb6/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertRect:fromView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1isRotatedFromBase/title",
          "value": "rotatedFromBase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1isRotatedFromBase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rotatedFromBase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1centerScanRect(_:)/title",
          "value": "centerScanRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1centerScanRect(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "centerScanRect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convertFromBacking(_:)-229ps/title",
          "value": "convertPointFromBacking:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convertFromBacking(_:)-229ps/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertPointFromBacking:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convertFromBacking(_:)-2njpa/title",
          "value": "convertRectFromBacking:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convertFromBacking(_:)-2njpa/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertRectFromBacking:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convertToLayer(_:)-44u7d/title",
          "value": "convertPointToLayer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convertToLayer(_:)-44u7d/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertPointToLayer:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1bounds/title",
          "value": "bounds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1bounds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convertToBacking(_:)-3zors/title",
          "value": "convertRectToBacking:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convertToBacking(_:)-3zors/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertRectToBacking:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convert(_:to:)-5nptx/title",
          "value": "convertSize:toView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convert(_:to:)-5nptx/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertSize:toView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convert(_:to:)-3cqqt/title",
          "value": "convertRect:toView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convert(_:to:)-3cqqt/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertRect:toView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convertToBacking(_:)-2xx45/title",
          "value": "convertPointToBacking:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1convertToBacking(_:)-2xx45/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertPointToBacking:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/view-coordinates"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/view-coordinates"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
