{
  "abstract": [
    {
      "text": "Add support for Writing Tools to your app’s text views.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/writing-tools"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Writing Tools"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Writing Tools provides a simple way for people to improve what",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "they write using your app. Text views that support Writing Tools",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "gain the ability to proofread, rewrite, summarize, or compose",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "content with the help of system-provided large language models",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "(LLMs) and Apple Intelligence.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Writing Tools supports both the standard system views and custom text",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "views you create. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextField",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " classes",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "automatically support Writing Tools, but you can customize that support",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to suit your app’s requirements. You can also add Writing Tools support",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to any ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in your app that contains text.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextField": {
      "abstract": [
        {
          "text": "Text the user can select or edit to send an action message to a target when the user presses the Return key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextField"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextField"
        }
      ],
      "role": "symbol",
      "title": "NSTextField",
      "type": "topic",
      "url": "/documentation/appkit/nstextfield"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextPreview": {
      "abstract": [
        {
          "text": "A snapshot of the text in your view, which the system uses to create",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "user-visible effects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextPreview"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextPreview",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextPreview"
        }
      ],
      "role": "symbol",
      "title": "NSTextPreview",
      "type": "topic",
      "url": "/documentation/appkit/nstextpreview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextView": {
      "abstract": [
        {
          "text": "A view that draws text and handles user interactions with that text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextView"
        }
      ],
      "role": "symbol",
      "title": "NSTextView",
      "type": "topic",
      "url": "/documentation/appkit/nstextview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/appkit/nsview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior": {
      "abstract": [
        {
          "text": "Constants that specify the Writing Tools experience for the underlying view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWritingToolsBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsBehavior"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsBehavior",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolsbehavior"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator": {
      "abstract": [
        {
          "text": "An object that manages interactions between Writing Tools and",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "your custom text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWritingToolsCoordinator"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsCoordinator"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsCoordinator",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolscoordinator"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/AnimationParameters": {
      "abstract": [
        {
          "text": "An object you use to configure additional tasks or animations to",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "run alongside the Writing Tools animations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnimationParameters"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/AnimationParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnimationParameters"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsCoordinator.AnimationParameters",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolscoordinator/animationparameters"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context": {
      "abstract": [
        {
          "text": "A data object that you use to share your custom view’s text with Writing Tools.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Context"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Context"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsCoordinator.Context",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolscoordinator/context"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Delegate-swift.protocol": {
      "abstract": [
        {
          "text": "An interface that you use to manage interactions between Writing Tools",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "and your custom text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Delegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Delegate-swift.protocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Delegate"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsCoordinator.Delegate",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolscoordinator/delegate-swift.protocol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsResultOptions": {
      "abstract": [
        {
          "text": "Constants to specify what type of content to allow in Writing Tools",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "suggestions or rewrites.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWritingToolsResultOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsResultOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsResultOptions"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsResultOptions",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolsresultoptions"
    },
    "doc://com.apple.appkit/documentation/AppKit/adding-writing-tools-support-to-a-custom-nsview": {
      "abstract": [
        {
          "text": "Integrate Writing Tools support, including support for inline replacement",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "animations, to your custom text views on macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/adding-writing-tools-support-to-a-custom-nsview",
      "kind": "article",
      "role": "article",
      "title": "Adding Writing Tools support to a custom AppKit view",
      "type": "topic",
      "url": "/documentation/appkit/adding-writing-tools-support-to-a-custom-nsview"
    },
    "doc://com.apple.appkit/documentation/AppKit/customizing-writing-tools-behavior-for-system-views": {
      "abstract": [
        {
          "text": "Modify the behavior of Writing Tools in standard macOS text views,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "and adjust your app’s behavior while the feature is active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/customizing-writing-tools-behavior-for-system-views",
      "kind": "article",
      "role": "article",
      "title": "Customizing Writing Tools behavior for AppKit views",
      "type": "topic",
      "url": "/documentation/appkit/customizing-writing-tools-behavior-for-system-views"
    },
    "doc://com.apple.appkit/documentation/AppKit/fonts": {
      "abstract": [
        {
          "text": "Manage the fonts used to display text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/fonts",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Fonts",
      "type": "topic",
      "url": "/documentation/appkit/fonts"
    },
    "doc://com.apple.appkit/documentation/AppKit/supporting-writing-tools-via-the-pasteboard": {
      "abstract": [
        {
          "text": "Adopt a simplified version of the Writing Tools experience in a custom",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "view using the pasteboard and macOS services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/supporting-writing-tools-via-the-pasteboard",
      "kind": "article",
      "role": "article",
      "title": "Supporting Writing Tools via the pasteboard",
      "type": "topic",
      "url": "/documentation/appkit/supporting-writing-tools-via-the-pasteboard"
    },
    "doc://com.apple.appkit/documentation/AppKit/text-display": {
      "abstract": [
        {
          "text": "Display text and check spelling.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/text-display",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text Display",
      "type": "topic",
      "url": "/documentation/appkit/text-display"
    },
    "doc://com.apple.appkit/documentation/AppKit/textkit": {
      "abstract": [
        {
          "text": "Manage text storage and perform custom layout of text-based content in your app’s views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/textkit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TextKit",
      "type": "topic",
      "url": "/documentation/appkit/textkit"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Text",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/text-display",
        "doc://com.apple.appkit/documentation/AppKit/textkit",
        "doc://com.apple.appkit/documentation/AppKit/fonts"
      ],
      "title": "Text"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuration",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/customizing-writing-tools-behavior-for-system-views",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsResultOptions"
      ],
      "title": "Configuration"
    },
    {
      "anchor": "Writing-Tools-for-custom-views",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/supporting-writing-tools-via-the-pasteboard",
        "doc://com.apple.appkit/documentation/AppKit/adding-writing-tools-support-to-a-custom-nsview",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Delegate-swift.protocol",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/AnimationParameters"
      ],
      "title": "Writing Tools for custom views"
    },
    {
      "anchor": "Text-previews",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextPreview"
      ],
      "title": "Text previews"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuration",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/customizing-writing-tools-behavior-for-system-views",
                "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior",
                "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsResultOptions"
              ],
              "title": "Configuration"
            },
            {
              "anchor": "Writing-Tools-for-custom-views",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/supporting-writing-tools-via-the-pasteboard",
                "doc://com.apple.appkit/documentation/AppKit/adding-writing-tools-support-to-a-custom-nsview",
                "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator",
                "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Delegate-swift.protocol",
                "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/Context",
                "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsCoordinator/AnimationParameters"
              ],
              "title": "Writing Tools for custom views"
            },
            {
              "anchor": "Text-previews",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextPreview"
              ],
              "title": "Text previews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Text",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/text-display",
                "doc://com.apple.appkit/documentation/AppKit/textkit",
                "doc://com.apple.appkit/documentation/AppKit/fonts"
              ],
              "title": "Text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator/title",
          "value": "NSWritingToolsCoordinator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/title",
          "value": "NSTextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextPreview/title",
          "value": "NSTextPreview"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextPreview/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextPreview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextPreview/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextPreview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/title",
          "value": "NSTextField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1AnimationParameters/title",
          "value": "NSWritingToolsCoordinatorAnimationParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1AnimationParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsCoordinatorAnimationParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1AnimationParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsCoordinatorAnimationParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsBehavior/title",
          "value": "NSWritingToolsBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsResultOptions/title",
          "value": "NSWritingToolsResultOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsResultOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsResultOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsResultOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsResultOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1Context/title",
          "value": "NSWritingToolsCoordinatorContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1Context/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsCoordinatorContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1Context/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsCoordinatorContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1Delegate-swift.protocol/title",
          "value": "NSWritingToolsCoordinatorDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1Delegate-swift.protocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsCoordinatorDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsCoordinator~1Delegate-swift.protocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsCoordinatorDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title",
          "value": "NSView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/writing-tools"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/writing-tools"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
