{"metadata":{"externalID":"c:@E@UIKeyboardType@UIKeyboardTypeASCIICapable","platforms":[{"deprecated":false,"unavailable":false,"beta":false,"name":"iOS"},{"deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS"},{"deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst"},{"deprecated":false,"unavailable":false,"beta":false,"name":"tvOS"},{"deprecated":false,"unavailable":false,"beta":false,"name":"visionOS"}],"roleHeading":"Case","modules":[{"name":"UIKit"}],"title":"UIKeyboardType.asciiCapable","symbolKind":"case","navigatorTitle":[{"text":"UIKeyboardTypeASCIICapable","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"asciiCapable","kind":"identifier"}]},"seeAlsoSections":[{"generated":true,"anchor":"Constants","title":"Constants","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/default","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numbersAndPunctuation","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/URL","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numberPad","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/phonePad","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/namePhonePad","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/emailAddress","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/decimalPad","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/twitter","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/webSearch","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapableNumberPad","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/alphabet"]}],"abstract":[{"type":"text","text":"Specifies a keyboard that displays standard ASCII characters."}],"variants":[{"paths":["/documentation/uikit/uikeyboardtype/asciicapable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uikeyboardtype/asciicapable"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapable"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"asciiCapable","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType"]]},"kind":"symbol","references":{"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapable":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"asciiCapable","kind":"identifier"}],"type":"topic","title":"UIKeyboardType.asciiCapable","url":"/documentation/uikit/uikeyboardtype/asciicapable","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapable","navigatorTitle":[{"text":"UIKeyboardTypeASCIICapable","kind":"identifier"}],"abstract":[{"type":"text","text":"Specifies a keyboard that displays standard ASCII characters."}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType":{"role":"symbol","abstract":[{"text":"Constants that specify the type of keyboard to display for a text-based view.","type":"text"}],"url":"/documentation/uikit/uikeyboardtype","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIKeyboardType"}],"title":"UIKeyboardType","navigatorTitle":[{"kind":"identifier","text":"UIKeyboardType"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numberPad":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberPad"}],"type":"topic","abstract":[{"text":"Specifies a numeric keypad for PIN entry.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIKeyboardTypeNumberPad"}],"kind":"symbol","url":"/documentation/uikit/uikeyboardtype/numberpad","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numberPad","title":"UIKeyboardType.numberPad"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapableNumberPad":{"navigatorTitle":[{"kind":"identifier","text":"UIKeyboardTypeASCIICapableNumberPad"}],"url":"/documentation/uikit/uikeyboardtype/asciicapablenumberpad","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"asciiCapableNumberPad"}],"kind":"symbol","abstract":[{"text":"Specifies a number pad that outputs only ASCII digits.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapableNumberPad","title":"UIKeyboardType.asciiCapableNumberPad","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/namePhonePad":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"namePhonePad"}],"type":"topic","abstract":[{"text":"Specifies a keypad for entering a person’s name or phone number.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIKeyboardTypeNamePhonePad"}],"kind":"symbol","url":"/documentation/uikit/uikeyboardtype/namephonepad","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/namePhonePad","title":"UIKeyboardType.namePhonePad"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/URL":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"URL","kind":"identifier"}],"url":"/documentation/uikit/uikeyboardtype/url","navigatorTitle":[{"text":"UIKeyboardTypeURL","kind":"identifier"}],"title":"UIKeyboardType.URL","abstract":[{"text":"Specifies a keyboard for URL entry.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/URL"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/twitter":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"twitter"}],"url":"/documentation/uikit/uikeyboardtype/twitter","navigatorTitle":[{"kind":"identifier","text":"UIKeyboardTypeTwitter"}],"title":"UIKeyboardType.twitter","abstract":[{"type":"text","text":"Specifies a keyboard for Twitter text entry, with easy access to the at (”"},{"code":"@","type":"codeVoice"},{"type":"text","text":"”) and hash (”"},{"type":"codeVoice","code":"#"},{"type":"text","text":"”) characters."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/twitter"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/alphabet":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alphabet","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIKeyboardType","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIKeyboardType"}],"deprecated":true,"type":"topic","title":"alphabet","url":"/documentation/uikit/uikeyboardtype/alphabet","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/alphabet","navigatorTitle":[{"text":"UIKeyboardTypeAlphabet","kind":"identifier"}],"abstract":[{"type":"text","text":"Specifies a keyboard for alphabetic entry."}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numbersAndPunctuation":{"navigatorTitle":[{"kind":"identifier","text":"UIKeyboardTypeNumbersAndPunctuation"}],"url":"/documentation/uikit/uikeyboardtype/numbersandpunctuation","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"numbersAndPunctuation"}],"kind":"symbol","abstract":[{"text":"Specifies the numbers and punctuation keyboard.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numbersAndPunctuation","title":"UIKeyboardType.numbersAndPunctuation","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/phonePad":{"role":"symbol","title":"UIKeyboardType.phonePad","navigatorTitle":[{"text":"UIKeyboardTypePhonePad","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phonePad","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Specifies a keypad for entering telephone numbers.","type":"text"}],"url":"/documentation/uikit/uikeyboardtype/phonepad","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/phonePad"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/decimalPad":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decimalPad"}],"url":"/documentation/uikit/uikeyboardtype/decimalpad","navigatorTitle":[{"kind":"identifier","text":"UIKeyboardTypeDecimalPad"}],"title":"UIKeyboardType.decimalPad","abstract":[{"type":"text","text":"Specifies a keyboard with numbers and a decimal point."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/decimalPad"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/emailAddress":{"navigatorTitle":[{"kind":"identifier","text":"UIKeyboardTypeEmailAddress"}],"title":"UIKeyboardType.emailAddress","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"emailAddress"}],"abstract":[{"text":"Specifies a keyboard for entering email addresses.","type":"text"}],"url":"/documentation/uikit/uikeyboardtype/emailaddress","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/emailAddress"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/webSearch":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"webSearch"}],"abstract":[{"text":"Specifies a keyboard for web search terms and URL entry.","type":"text"}],"title":"UIKeyboardType.webSearch","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/webSearch","navigatorTitle":[{"kind":"identifier","text":"UIKeyboardTypeWebSearch"}],"url":"/documentation/uikit/uikeyboardtype/websearch","type":"topic","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/default":{"role":"symbol","title":"UIKeyboardType.default","navigatorTitle":[{"kind":"identifier","text":"UIKeyboardTypeDefault"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}],"kind":"symbol","abstract":[{"type":"text","text":"Specifies the default keyboard for the current input method."}],"url":"/documentation/uikit/uikeyboardtype/default","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/default"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"name":"iOS","deprecated":false,"beta":false,"unavailable":false},{"name":"iPadOS","deprecated":false,"beta":false,"unavailable":false},{"name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false},{"name":"tvOS","deprecated":false,"beta":false,"unavailable":false},{"name":"visionOS","deprecated":false,"beta":false,"unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"/metadata/title","op":"replace","value":"UIKeyboardTypeASCIICapable"},{"path":"/metadata/symbolKind","op":"replace","value":"case"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"UIKeyboardTypeASCIICapable","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType"]]}},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"title":"Constants","anchor":"Constants","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/default","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numbersAndPunctuation","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/URL","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numberPad","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/phonePad","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/namePhonePad","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/emailAddress","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/decimalPad","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/twitter","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/webSearch","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapableNumberPad","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/alphabet"]}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"UIKeyboardTypeASCIICapable"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}]},"op":"replace"},{"value":"UIKeyboardTypeASCIICapable","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1asciiCapable/title","op":"replace"},{"value":[{"text":"UIKeyboardTypeASCIICapable","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1asciiCapable/fragments","op":"replace"},{"value":"UIKeyboardType","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType/title","op":"replace"},{"value":[{"text":"UIKeyboardType","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType/fragments","op":"replace"},{"value":[{"text":"UIKeyboardType","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType/navigatorTitle","op":"replace"},{"value":"UIKeyboardTypeNumberPad","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1numberPad/title","op":"replace"},{"value":[{"text":"UIKeyboardTypeNumberPad","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1numberPad/fragments","op":"replace"},{"value":"UIKeyboardTypeASCIICapableNumberPad","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1asciiCapableNumberPad/title","op":"replace"},{"value":[{"kind":"identifier","text":"UIKeyboardTypeASCIICapableNumberPad"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1asciiCapableNumberPad/fragments","op":"replace"},{"value":"UIKeyboardTypeNamePhonePad","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1namePhonePad/title","op":"replace"},{"value":[{"kind":"identifier","text":"UIKeyboardTypeNamePhonePad"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1namePhonePad/fragments","op":"replace"},{"value":"UIKeyboardTypeURL","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1URL/title","op":"replace"},{"value":[{"kind":"identifier","text":"UIKeyboardTypeURL"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1URL/fragments","op":"replace"},{"value":"UIKeyboardTypeTwitter","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1twitter/title","op":"replace"},{"value":[{"text":"UIKeyboardTypeTwitter","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1twitter/fragments","op":"replace"},{"value":"UIKeyboardTypeAlphabet","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1alphabet/title","op":"replace"},{"value":[{"text":"UIKeyboardTypeAlphabet","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1alphabet/fragments","op":"replace"},{"value":"UIKeyboardTypeNumbersAndPunctuation","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1numbersAndPunctuation/title","op":"replace"},{"value":[{"kind":"identifier","text":"UIKeyboardTypeNumbersAndPunctuation"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1numbersAndPunctuation/fragments","op":"replace"},{"value":"UIKeyboardTypePhonePad","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1phonePad/title","op":"replace"},{"value":[{"text":"UIKeyboardTypePhonePad","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1phonePad/fragments","op":"replace"},{"value":"UIKeyboardTypeDecimalPad","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1decimalPad/title","op":"replace"},{"value":[{"text":"UIKeyboardTypeDecimalPad","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1decimalPad/fragments","op":"replace"},{"value":"UIKeyboardTypeEmailAddress","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1emailAddress/title","op":"replace"},{"value":[{"kind":"identifier","text":"UIKeyboardTypeEmailAddress"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1emailAddress/fragments","op":"replace"},{"value":"UIKeyboardTypeWebSearch","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1webSearch/title","op":"replace"},{"value":[{"kind":"identifier","text":"UIKeyboardTypeWebSearch"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1webSearch/fragments","op":"replace"},{"value":"UIKeyboardTypeDefault","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1default/title","op":"replace"},{"value":[{"text":"UIKeyboardTypeDefault","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1default/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}