{
  "abstract": [
    {
      "text": "Specifies a number pad that outputs only ASCII digits.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapableNumberPad"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIKeyboardType@UIKeyboardTypeASCIICapableNumberPad",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "asciiCapableNumberPad"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIKeyboardTypeASCIICapableNumberPad"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIKeyboardType.asciiCapableNumberPad"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "asciiCapableNumberPad"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType": {
      "abstract": [
        {
          "text": "Constants that specify the type of keyboard to display for a text-based view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIKeyboardType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardType"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardType",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardtype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/URL": {
      "abstract": [
        {
          "text": "Specifies a keyboard for URL entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "URL"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/URL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardTypeURL"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardType.URL",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardtype/url"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/alphabet": {
      "abstract": [
        {
          "text": "Specifies a keyboard for alphabetic entry.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alphabet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIKeyboardType",
          "text": "UIKeyboardType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/alphabet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardTypeAlphabet"
        }
      ],
      "role": "symbol",
      "title": "alphabet",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardtype/alphabet"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapable": {
      "abstract": [
        {
          "text": "Specifies a keyboard that displays standard ASCII characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "asciiCapable"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardTypeASCIICapable"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardType.asciiCapable",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardtype/asciicapable"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapableNumberPad": {
      "abstract": [
        {
          "text": "Specifies a number pad that outputs only ASCII digits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "asciiCapableNumberPad"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapableNumberPad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardTypeASCIICapableNumberPad"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardType.asciiCapableNumberPad",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardtype/asciicapablenumberpad"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/decimalPad": {
      "abstract": [
        {
          "text": "Specifies a keyboard with numbers and a decimal point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decimalPad"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/decimalPad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardTypeDecimalPad"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardType.decimalPad",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardtype/decimalpad"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/default": {
      "abstract": [
        {
          "text": "Specifies the default keyboard for the current input method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardTypeDefault"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardType.default",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardtype/default"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/emailAddress": {
      "abstract": [
        {
          "text": "Specifies a keyboard for entering email addresses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emailAddress"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/emailAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardTypeEmailAddress"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardType.emailAddress",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardtype/emailaddress"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/namePhonePad": {
      "abstract": [
        {
          "text": "Specifies a keypad for entering a person’s name or phone number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "namePhonePad"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/namePhonePad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardTypeNamePhonePad"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardType.namePhonePad",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardtype/namephonepad"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numberPad": {
      "abstract": [
        {
          "text": "Specifies a numeric keypad for PIN entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberPad"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numberPad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardTypeNumberPad"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardType.numberPad",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardtype/numberpad"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numbersAndPunctuation": {
      "abstract": [
        {
          "text": "Specifies the numbers and punctuation keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numbersAndPunctuation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numbersAndPunctuation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardTypeNumbersAndPunctuation"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardType.numbersAndPunctuation",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardtype/numbersandpunctuation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/phonePad": {
      "abstract": [
        {
          "text": "Specifies a keypad for entering telephone numbers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "phonePad"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/phonePad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardTypePhonePad"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardType.phonePad",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardtype/phonepad"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/twitter": {
      "abstract": [
        {
          "text": "Specifies a keyboard for Twitter text entry, with easy access to the at (”",
          "type": "text"
        },
        {
          "code": "@",
          "type": "codeVoice"
        },
        {
          "text": "”) and hash (”",
          "type": "text"
        },
        {
          "code": "#",
          "type": "codeVoice"
        },
        {
          "text": "”) characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "twitter"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/twitter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardTypeTwitter"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardType.twitter",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardtype/twitter"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/webSearch": {
      "abstract": [
        {
          "text": "Specifies a keyboard for web search terms and URL entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webSearch"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/webSearch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardTypeWebSearch"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardType.webSearch",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardtype/websearch"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/default",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapable",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numbersAndPunctuation",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/URL",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numberPad",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/phonePad",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/namePhonePad",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/emailAddress",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/decimalPad",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/twitter",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/webSearch",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/alphabet"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIKeyboardTypeASCIICapableNumberPad"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardTypeASCIICapableNumberPad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/default",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapable",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numbersAndPunctuation",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/URL",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numberPad",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/phonePad",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/namePhonePad",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/emailAddress",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/decimalPad",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/twitter",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/webSearch",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/alphabet"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIKeyboardTypeASCIICapableNumberPad"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1asciiCapable/title",
          "value": "UIKeyboardTypeASCIICapable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1asciiCapable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardTypeASCIICapable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1namePhonePad/title",
          "value": "UIKeyboardTypeNamePhonePad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1namePhonePad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardTypeNamePhonePad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1numbersAndPunctuation/title",
          "value": "UIKeyboardTypeNumbersAndPunctuation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1numbersAndPunctuation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardTypeNumbersAndPunctuation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1decimalPad/title",
          "value": "UIKeyboardTypeDecimalPad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1decimalPad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardTypeDecimalPad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1emailAddress/title",
          "value": "UIKeyboardTypeEmailAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1emailAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardTypeEmailAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1default/title",
          "value": "UIKeyboardTypeDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardTypeDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1alphabet/title",
          "value": "UIKeyboardTypeAlphabet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1alphabet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardTypeAlphabet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1URL/title",
          "value": "UIKeyboardTypeURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1URL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardTypeURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1twitter/title",
          "value": "UIKeyboardTypeTwitter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1twitter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardTypeTwitter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1numberPad/title",
          "value": "UIKeyboardTypeNumberPad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1numberPad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardTypeNumberPad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1webSearch/title",
          "value": "UIKeyboardTypeWebSearch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1webSearch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardTypeWebSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1phonePad/title",
          "value": "UIKeyboardTypePhonePad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1phonePad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardTypePhonePad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType/title",
          "value": "UIKeyboardType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1asciiCapableNumberPad/title",
          "value": "UIKeyboardTypeASCIICapableNumberPad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1asciiCapableNumberPad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardTypeASCIICapableNumberPad"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uikeyboardtype/asciicapablenumberpad"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uikeyboardtype/asciicapablenumberpad"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
