{"variants":[{"paths":["/documentation/uikit/uikeyboardtype/phonepad"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uikeyboardtype/phonepad"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType"]]},"abstract":[{"text":"Specifies a keypad for entering telephone numbers.","type":"text"}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phonePad","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","role":"symbol","navigatorTitle":[{"text":"UIKeyboardTypePhonePad","kind":"identifier"}],"externalID":"c:@E@UIKeyboardType@UIKeyboardTypePhonePad","modules":[{"name":"UIKit"}],"platforms":[{"deprecated":false,"name":"iOS","beta":false,"unavailable":false},{"deprecated":false,"name":"iPadOS","beta":false,"unavailable":false},{"deprecated":false,"name":"Mac Catalyst","beta":false,"unavailable":false},{"deprecated":false,"name":"tvOS","beta":false,"unavailable":false},{"deprecated":false,"name":"visionOS","beta":false,"unavailable":false}],"title":"UIKeyboardType.phonePad"},"seeAlsoSections":[{"generated":true,"title":"Constants","anchor":"Constants","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/default","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapable","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numbersAndPunctuation","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/URL","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numberPad","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/namePhonePad","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/emailAddress","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/decimalPad","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/twitter","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/webSearch","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapableNumberPad","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/alphabet"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phonePad","kind":"identifier"}]}]},{"kind":"mentions","mentions":["doc://com.apple.uikit/documentation/UIKit/configuring-a-custom-keyboard-interface"]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"Discussion","text":"Discussion"},{"inlineContent":[{"type":"text","text":"This keyboard type prominently features the numbers "},{"type":"codeVoice","code":"0"},{"type":"text","text":" through "},{"type":"codeVoice","code":"9"},{"type":"text","text":" and the “"},{"type":"codeVoice","code":"*"},{"type":"text","text":"” and “"},{"type":"codeVoice","code":"#"},{"type":"text","text":"” characters. This keyboard type does not support auto-capitalization."}],"type":"paragraph"}]}],"sections":[],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/phonePad","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapableNumberPad":{"navigatorTitle":[{"kind":"identifier","text":"UIKeyboardTypeASCIICapableNumberPad"}],"url":"/documentation/uikit/uikeyboardtype/asciicapablenumberpad","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"asciiCapableNumberPad"}],"kind":"symbol","abstract":[{"text":"Specifies a number pad that outputs only ASCII digits.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapableNumberPad","title":"UIKeyboardType.asciiCapableNumberPad","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/phonePad":{"role":"symbol","title":"UIKeyboardType.phonePad","navigatorTitle":[{"text":"UIKeyboardTypePhonePad","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phonePad","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Specifies a keypad for entering telephone numbers.","type":"text"}],"url":"/documentation/uikit/uikeyboardtype/phonepad","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/phonePad"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapable":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"asciiCapable","kind":"identifier"}],"type":"topic","title":"UIKeyboardType.asciiCapable","url":"/documentation/uikit/uikeyboardtype/asciicapable","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapable","navigatorTitle":[{"text":"UIKeyboardTypeASCIICapable","kind":"identifier"}],"abstract":[{"type":"text","text":"Specifies a keyboard that displays standard ASCII characters."}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numbersAndPunctuation":{"navigatorTitle":[{"kind":"identifier","text":"UIKeyboardTypeNumbersAndPunctuation"}],"url":"/documentation/uikit/uikeyboardtype/numbersandpunctuation","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"numbersAndPunctuation"}],"kind":"symbol","abstract":[{"text":"Specifies the numbers and punctuation keyboard.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numbersAndPunctuation","title":"UIKeyboardType.numbersAndPunctuation","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/alphabet":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alphabet","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIKeyboardType","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIKeyboardType"}],"deprecated":true,"type":"topic","title":"alphabet","url":"/documentation/uikit/uikeyboardtype/alphabet","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/alphabet","navigatorTitle":[{"text":"UIKeyboardTypeAlphabet","kind":"identifier"}],"abstract":[{"type":"text","text":"Specifies a keyboard for alphabetic entry."}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/configuring-a-custom-keyboard-interface":{"identifier":"doc://com.apple.uikit/documentation/UIKit/configuring-a-custom-keyboard-interface","abstract":[{"text":"Design a flexible, functional, and responsive interface for editing text.","type":"text"}],"title":"Configuring a custom keyboard interface","role":"article","url":"/documentation/uikit/configuring-a-custom-keyboard-interface","kind":"article","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/twitter":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"twitter"}],"url":"/documentation/uikit/uikeyboardtype/twitter","navigatorTitle":[{"kind":"identifier","text":"UIKeyboardTypeTwitter"}],"title":"UIKeyboardType.twitter","abstract":[{"type":"text","text":"Specifies a keyboard for Twitter text entry, with easy access to the at (”"},{"code":"@","type":"codeVoice"},{"type":"text","text":"”) and hash (”"},{"type":"codeVoice","code":"#"},{"type":"text","text":"”) characters."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/twitter"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/decimalPad":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decimalPad"}],"url":"/documentation/uikit/uikeyboardtype/decimalpad","navigatorTitle":[{"kind":"identifier","text":"UIKeyboardTypeDecimalPad"}],"title":"UIKeyboardType.decimalPad","abstract":[{"type":"text","text":"Specifies a keyboard with numbers and a decimal point."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/decimalPad"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/webSearch":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"webSearch"}],"abstract":[{"text":"Specifies a keyboard for web search terms and URL entry.","type":"text"}],"title":"UIKeyboardType.webSearch","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/webSearch","navigatorTitle":[{"kind":"identifier","text":"UIKeyboardTypeWebSearch"}],"url":"/documentation/uikit/uikeyboardtype/websearch","type":"topic","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numberPad":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberPad"}],"type":"topic","abstract":[{"text":"Specifies a numeric keypad for PIN entry.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIKeyboardTypeNumberPad"}],"kind":"symbol","url":"/documentation/uikit/uikeyboardtype/numberpad","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numberPad","title":"UIKeyboardType.numberPad"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType":{"role":"symbol","abstract":[{"text":"Constants that specify the type of keyboard to display for a text-based view.","type":"text"}],"url":"/documentation/uikit/uikeyboardtype","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIKeyboardType"}],"title":"UIKeyboardType","navigatorTitle":[{"kind":"identifier","text":"UIKeyboardType"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/namePhonePad":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"namePhonePad"}],"type":"topic","abstract":[{"text":"Specifies a keypad for entering a person’s name or phone number.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIKeyboardTypeNamePhonePad"}],"kind":"symbol","url":"/documentation/uikit/uikeyboardtype/namephonepad","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/namePhonePad","title":"UIKeyboardType.namePhonePad"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/emailAddress":{"navigatorTitle":[{"kind":"identifier","text":"UIKeyboardTypeEmailAddress"}],"title":"UIKeyboardType.emailAddress","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"emailAddress"}],"abstract":[{"text":"Specifies a keyboard for entering email addresses.","type":"text"}],"url":"/documentation/uikit/uikeyboardtype/emailaddress","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/emailAddress"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/URL":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"URL","kind":"identifier"}],"url":"/documentation/uikit/uikeyboardtype/url","navigatorTitle":[{"text":"UIKeyboardTypeURL","kind":"identifier"}],"title":"UIKeyboardType.URL","abstract":[{"text":"Specifies a keyboard for URL entry.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/URL"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/default":{"role":"symbol","title":"UIKeyboardType.default","navigatorTitle":[{"kind":"identifier","text":"UIKeyboardTypeDefault"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}],"kind":"symbol","abstract":[{"type":"text","text":"Specifies the default keyboard for the current input method."}],"url":"/documentation/uikit/uikeyboardtype/default","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/default"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"unavailable":false,"name":"iOS","beta":false},{"deprecated":false,"unavailable":false,"name":"iPadOS","beta":false},{"deprecated":false,"unavailable":false,"name":"Mac Catalyst","beta":false},{"deprecated":false,"unavailable":false,"name":"tvOS","beta":false},{"deprecated":false,"unavailable":false,"name":"visionOS","beta":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Enumeration Case","path":"/metadata/roleHeading","op":"replace"},{"value":"UIKeyboardTypePhonePad","path":"/metadata/title","op":"replace"},{"value":"case","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"UIKeyboardTypePhonePad","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType"]]},"path":"/hierarchy","op":"replace"},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"title":"Constants","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/default","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapable","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numbersAndPunctuation","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/URL","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numberPad","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/namePhonePad","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/emailAddress","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/decimalPad","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/twitter","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/webSearch","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapableNumberPad","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/alphabet"],"anchor":"Constants"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"UIKeyboardTypePhonePad","kind":"identifier"}],"languages":["occ"]}]}},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1asciiCapableNumberPad/title","value":"UIKeyboardTypeASCIICapableNumberPad","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1asciiCapableNumberPad/fragments","value":[{"kind":"identifier","text":"UIKeyboardTypeASCIICapableNumberPad"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1phonePad/title","value":"UIKeyboardTypePhonePad","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1phonePad/fragments","value":[{"kind":"identifier","text":"UIKeyboardTypePhonePad"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1asciiCapable/title","value":"UIKeyboardTypeASCIICapable","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1asciiCapable/fragments","value":[{"text":"UIKeyboardTypeASCIICapable","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1numbersAndPunctuation/title","value":"UIKeyboardTypeNumbersAndPunctuation","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1numbersAndPunctuation/fragments","value":[{"text":"UIKeyboardTypeNumbersAndPunctuation","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1alphabet/title","value":"UIKeyboardTypeAlphabet","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1alphabet/fragments","value":[{"text":"UIKeyboardTypeAlphabet","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1twitter/title","value":"UIKeyboardTypeTwitter","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1twitter/fragments","value":[{"kind":"identifier","text":"UIKeyboardTypeTwitter"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1decimalPad/title","value":"UIKeyboardTypeDecimalPad","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1decimalPad/fragments","value":[{"text":"UIKeyboardTypeDecimalPad","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1webSearch/title","value":"UIKeyboardTypeWebSearch","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1webSearch/fragments","value":[{"text":"UIKeyboardTypeWebSearch","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1numberPad/title","value":"UIKeyboardTypeNumberPad","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1numberPad/fragments","value":[{"kind":"identifier","text":"UIKeyboardTypeNumberPad"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType/title","value":"UIKeyboardType","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType/fragments","value":[{"text":"UIKeyboardType","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType/navigatorTitle","value":[{"text":"UIKeyboardType","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1namePhonePad/title","value":"UIKeyboardTypeNamePhonePad","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1namePhonePad/fragments","value":[{"text":"UIKeyboardTypeNamePhonePad","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1emailAddress/title","value":"UIKeyboardTypeEmailAddress","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1emailAddress/fragments","value":[{"text":"UIKeyboardTypeEmailAddress","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1URL/title","value":"UIKeyboardTypeURL","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1URL/fragments","value":[{"text":"UIKeyboardTypeURL","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1default/title","value":"UIKeyboardTypeDefault","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1default/fragments","value":[{"kind":"identifier","text":"UIKeyboardTypeDefault"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}