{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/twitter"},"metadata":{"modules":[{"name":"UIKit"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"twitter","kind":"identifier"}],"navigatorTitle":[{"text":"UIKeyboardTypeTwitter","kind":"identifier"}],"role":"symbol","platforms":[{"deprecated":false,"beta":false,"unavailable":false,"name":"iOS","introducedAt":"5.0"},{"deprecated":false,"beta":false,"unavailable":false,"name":"iPadOS","introducedAt":"5.0"},{"deprecated":false,"beta":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"unavailable":false,"deprecated":false,"name":"tvOS","beta":false},{"unavailable":false,"deprecated":false,"introducedAt":"1.0","name":"visionOS","beta":false}],"externalID":"c:@E@UIKeyboardType@UIKeyboardTypeTwitter","roleHeading":"Case","symbolKind":"case","title":"UIKeyboardType.twitter"},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"twitter"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Specifies a keyboard for Twitter text entry, with easy access to the at (”"},{"type":"codeVoice","code":"@"},{"type":"text","text":"”) and hash (”"},{"type":"codeVoice","code":"#"},{"type":"text","text":"”) characters."}],"seeAlsoSections":[{"anchor":"Constants","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/default","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapable","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numbersAndPunctuation","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/URL","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numberPad","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/phonePad","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/namePhonePad","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/emailAddress","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/decimalPad","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/webSearch","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapableNumberPad","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/alphabet"],"title":"Constants"}],"variants":[{"paths":["/documentation/uikit/uikeyboardtype/twitter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uikeyboardtype/twitter"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType":{"role":"symbol","abstract":[{"text":"Constants that specify the type of keyboard to display for a text-based view.","type":"text"}],"url":"/documentation/uikit/uikeyboardtype","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIKeyboardType"}],"title":"UIKeyboardType","navigatorTitle":[{"kind":"identifier","text":"UIKeyboardType"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numberPad":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberPad"}],"type":"topic","abstract":[{"text":"Specifies a numeric keypad for PIN entry.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIKeyboardTypeNumberPad"}],"kind":"symbol","url":"/documentation/uikit/uikeyboardtype/numberpad","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numberPad","title":"UIKeyboardType.numberPad"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/twitter":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"twitter"}],"url":"/documentation/uikit/uikeyboardtype/twitter","navigatorTitle":[{"kind":"identifier","text":"UIKeyboardTypeTwitter"}],"title":"UIKeyboardType.twitter","abstract":[{"type":"text","text":"Specifies a keyboard for Twitter text entry, with easy access to the at (”"},{"code":"@","type":"codeVoice"},{"type":"text","text":"”) and hash (”"},{"type":"codeVoice","code":"#"},{"type":"text","text":"”) characters."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/twitter"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/webSearch":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"webSearch"}],"abstract":[{"text":"Specifies a keyboard for web search terms and URL entry.","type":"text"}],"title":"UIKeyboardType.webSearch","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/webSearch","navigatorTitle":[{"kind":"identifier","text":"UIKeyboardTypeWebSearch"}],"url":"/documentation/uikit/uikeyboardtype/websearch","type":"topic","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapable":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"asciiCapable","kind":"identifier"}],"type":"topic","title":"UIKeyboardType.asciiCapable","url":"/documentation/uikit/uikeyboardtype/asciicapable","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapable","navigatorTitle":[{"text":"UIKeyboardTypeASCIICapable","kind":"identifier"}],"abstract":[{"type":"text","text":"Specifies a keyboard that displays standard ASCII characters."}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/emailAddress":{"navigatorTitle":[{"kind":"identifier","text":"UIKeyboardTypeEmailAddress"}],"title":"UIKeyboardType.emailAddress","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"emailAddress"}],"abstract":[{"text":"Specifies a keyboard for entering email addresses.","type":"text"}],"url":"/documentation/uikit/uikeyboardtype/emailaddress","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/emailAddress"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/default":{"role":"symbol","title":"UIKeyboardType.default","navigatorTitle":[{"kind":"identifier","text":"UIKeyboardTypeDefault"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}],"kind":"symbol","abstract":[{"type":"text","text":"Specifies the default keyboard for the current input method."}],"url":"/documentation/uikit/uikeyboardtype/default","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/default"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/URL":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"URL","kind":"identifier"}],"url":"/documentation/uikit/uikeyboardtype/url","navigatorTitle":[{"text":"UIKeyboardTypeURL","kind":"identifier"}],"title":"UIKeyboardType.URL","abstract":[{"text":"Specifies a keyboard for URL entry.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/URL"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapableNumberPad":{"navigatorTitle":[{"kind":"identifier","text":"UIKeyboardTypeASCIICapableNumberPad"}],"url":"/documentation/uikit/uikeyboardtype/asciicapablenumberpad","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"asciiCapableNumberPad"}],"kind":"symbol","abstract":[{"text":"Specifies a number pad that outputs only ASCII digits.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapableNumberPad","title":"UIKeyboardType.asciiCapableNumberPad","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/namePhonePad":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"namePhonePad"}],"type":"topic","abstract":[{"text":"Specifies a keypad for entering a person’s name or phone number.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIKeyboardTypeNamePhonePad"}],"kind":"symbol","url":"/documentation/uikit/uikeyboardtype/namephonepad","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/namePhonePad","title":"UIKeyboardType.namePhonePad"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/phonePad":{"role":"symbol","title":"UIKeyboardType.phonePad","navigatorTitle":[{"text":"UIKeyboardTypePhonePad","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phonePad","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Specifies a keypad for entering telephone numbers.","type":"text"}],"url":"/documentation/uikit/uikeyboardtype/phonepad","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/phonePad"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/decimalPad":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decimalPad"}],"url":"/documentation/uikit/uikeyboardtype/decimalpad","navigatorTitle":[{"kind":"identifier","text":"UIKeyboardTypeDecimalPad"}],"title":"UIKeyboardType.decimalPad","abstract":[{"type":"text","text":"Specifies a keyboard with numbers and a decimal point."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/decimalPad"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/alphabet":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alphabet","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIKeyboardType","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIKeyboardType"}],"deprecated":true,"type":"topic","title":"alphabet","url":"/documentation/uikit/uikeyboardtype/alphabet","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/alphabet","navigatorTitle":[{"text":"UIKeyboardTypeAlphabet","kind":"identifier"}],"abstract":[{"type":"text","text":"Specifies a keyboard for alphabetic entry."}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numbersAndPunctuation":{"navigatorTitle":[{"kind":"identifier","text":"UIKeyboardTypeNumbersAndPunctuation"}],"url":"/documentation/uikit/uikeyboardtype/numbersandpunctuation","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"numbersAndPunctuation"}],"kind":"symbol","abstract":[{"text":"Specifies the numbers and punctuation keyboard.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numbersAndPunctuation","title":"UIKeyboardType.numbersAndPunctuation","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"introducedAt":"5.0","name":"iOS","unavailable":false,"deprecated":false},{"beta":false,"introducedAt":"5.0","name":"iPadOS","unavailable":false,"deprecated":false},{"beta":false,"introducedAt":"13.1","name":"Mac Catalyst","unavailable":false,"deprecated":false},{"beta":false,"name":"tvOS","unavailable":false,"deprecated":false},{"beta":false,"introducedAt":"1.0","name":"visionOS","unavailable":false,"deprecated":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"/metadata/title","value":"UIKeyboardTypeTwitter"},{"op":"replace","path":"/metadata/symbolKind","value":"case"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"UIKeyboardTypeTwitter"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Constants","anchor":"Constants","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/default","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapable","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numbersAndPunctuation","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/URL","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/numberPad","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/phonePad","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/namePhonePad","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/emailAddress","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/decimalPad","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/webSearch","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/asciiCapableNumberPad","doc://com.apple.uikit/documentation/UIKit/UIKeyboardType/alphabet"]}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"UIKeyboardTypeTwitter"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType/title","value":"UIKeyboardType"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType/fragments","value":[{"kind":"identifier","text":"UIKeyboardType"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType/navigatorTitle","value":[{"text":"UIKeyboardType","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1numberPad/title","value":"UIKeyboardTypeNumberPad"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1numberPad/fragments","value":[{"kind":"identifier","text":"UIKeyboardTypeNumberPad"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1twitter/title","value":"UIKeyboardTypeTwitter"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1twitter/fragments","value":[{"kind":"identifier","text":"UIKeyboardTypeTwitter"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1webSearch/title","value":"UIKeyboardTypeWebSearch","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1webSearch/fragments","value":[{"kind":"identifier","text":"UIKeyboardTypeWebSearch"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1asciiCapable/title","value":"UIKeyboardTypeASCIICapable","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1asciiCapable/fragments","value":[{"kind":"identifier","text":"UIKeyboardTypeASCIICapable"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1emailAddress/title","value":"UIKeyboardTypeEmailAddress","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1emailAddress/fragments","value":[{"text":"UIKeyboardTypeEmailAddress","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1default/title","value":"UIKeyboardTypeDefault","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1default/fragments","value":[{"kind":"identifier","text":"UIKeyboardTypeDefault"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1URL/title","value":"UIKeyboardTypeURL","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1URL/fragments","value":[{"text":"UIKeyboardTypeURL","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1asciiCapableNumberPad/title","value":"UIKeyboardTypeASCIICapableNumberPad","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1asciiCapableNumberPad/fragments","value":[{"kind":"identifier","text":"UIKeyboardTypeASCIICapableNumberPad"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1namePhonePad/title","value":"UIKeyboardTypeNamePhonePad","op":"replace"},{"op":"replace","value":[{"text":"UIKeyboardTypeNamePhonePad","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1namePhonePad/fragments"},{"op":"replace","value":"UIKeyboardTypePhonePad","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1phonePad/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIKeyboardTypePhonePad"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1phonePad/fragments"},{"op":"replace","value":"UIKeyboardTypeDecimalPad","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1decimalPad/title"},{"op":"replace","value":[{"text":"UIKeyboardTypeDecimalPad","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1decimalPad/fragments"},{"op":"replace","value":"UIKeyboardTypeAlphabet","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1alphabet/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIKeyboardTypeAlphabet"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1alphabet/fragments"},{"op":"replace","value":"UIKeyboardTypeNumbersAndPunctuation","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1numbersAndPunctuation/title"},{"op":"replace","value":[{"text":"UIKeyboardTypeNumbersAndPunctuation","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType~1numbersAndPunctuation/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}