{
  "abstract": [
    {
      "text": "The absolute time, in seconds, to use for scheduling haptic and audio events.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corehaptics/documentation/CoreHaptics",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/currentTime"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CHHapticEngine(py)currentTime",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "currentTime"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSTimeInterval",
        "text": "TimeInterval"
      }
    ],
    "modules": [
      {
        "name": "Core Haptics"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "currentTime"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "currentTime"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "currentTime"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSTimeInterval",
              "text": "TimeInterval"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This time applies to all haptic and audio events sent to and managed by the Core Haptics engine. Use the current time as a way to determine or track the start times of haptic and audio events, created as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects. It corresponds to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/relativeTime",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/duration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties of haptic events.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The Core Haptics engine time doesn’t correlate to time used in media playback classes from other frameworks, such as ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioPlayer",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corehaptics/documentation/CoreHaptics": {
      "abstract": [
        {
          "text": "Compose and play haptic patterns to customize your iOS app’s haptic feedback.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Haptics",
      "type": "topic",
      "url": "/documentation/corehaptics"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine": {
      "abstract": [
        {
          "text": "An object that represents the connection to the haptic server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CHHapticEngine"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticEngine"
        }
      ],
      "role": "symbol",
      "title": "CHHapticEngine",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticengine"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/currentTime": {
      "abstract": [
        {
          "text": "The absolute time, in seconds, to use for scheduling haptic and audio events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/currentTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentTime"
        }
      ],
      "role": "symbol",
      "title": "currentTime",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticengine/currenttime"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent": {
      "abstract": [
        {
          "text": "An object that describes a single haptic or audio event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CHHapticEvent"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticEvent"
        }
      ],
      "role": "symbol",
      "title": "CHHapticEvent",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticevent"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/duration": {
      "abstract": [
        {
          "text": "The duration of the haptic event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/duration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "duration"
        }
      ],
      "role": "symbol",
      "title": "duration",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticevent/duration"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/relativeTime": {
      "abstract": [
        {
          "text": "The start time of the event, relative to other events in the same pattern.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "relativeTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/relativeTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "relativeTime"
        }
      ],
      "role": "symbol",
      "title": "relativeTime",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticevent/relativetime"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticTimeImmediate": {
      "abstract": [
        {
          "text": "A time constant used to schedule a command immediately.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CHHapticTimeImmediate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticTimeImmediate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticTimeImmediate"
        }
      ],
      "role": "symbol",
      "title": "CHHapticTimeImmediate",
      "type": "topic",
      "url": "/documentation/corehaptics/chhaptictimeimmediate"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioPlayer": {
      "abstract": [
        {
          "text": "An object that plays audio data from a file or buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioPlayer"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioPlayer",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioPlayer",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioPlayer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval": {
      "abstract": [
        {
          "text": "A number of seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval",
      "kind": "symbol",
      "role": "symbol",
      "title": "TimeInterval",
      "type": "topic",
      "url": "/documentation/foundation/timeinterval"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Current-Media-Time",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticTimeImmediate"
      ],
      "title": "Getting the Current Media Time"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "currentTime"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corehaptics/documentation/CoreHaptics",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Current-Media-Time",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticTimeImmediate"
              ],
              "title": "Getting the Current Media Time"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSTimeInterval",
                    "text": "NSTimeInterval"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "currentTime"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1currentTime/title",
          "value": "currentTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1currentTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1duration/title",
          "value": "duration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1duration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "duration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioPlayer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioPlayer"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1relativeTime/title",
          "value": "relativeTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1relativeTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "relativeTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine/title",
          "value": "CHHapticEngine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSTimeInterval/title",
          "value": "NSTimeInterval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent/title",
          "value": "CHHapticEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticTimeImmediate/title",
          "value": "CHHapticTimeImmediate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticTimeImmediate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticTimeImmediate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corehaptics/chhapticengine/currenttime"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corehaptics/chhapticengine/currenttime"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
