{
  "abstract": [
    {
      "text": "Possible actions to take after the haptic engine finishes execution.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corehaptics/documentation/CoreHaptics",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/FinishedAction"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CoreHaptics",
    "externalID": "c:@E@CHHapticEngineFinishedAction",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FinishedAction"
      }
    ],
    "modules": [
      {
        "name": "Core Haptics"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FinishedAction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CHHapticEngine.FinishedAction"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FinishedAction"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corehaptics/documentation/CoreHaptics": {
      "abstract": [
        {
          "text": "Compose and play haptic patterns to customize your iOS app’s haptic feedback.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Haptics",
      "type": "topic",
      "url": "/documentation/corehaptics"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine": {
      "abstract": [
        {
          "text": "An object that represents the connection to the haptic server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CHHapticEngine"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticEngine"
        }
      ],
      "role": "symbol",
      "title": "CHHapticEngine",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticengine"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/FinishedAction": {
      "abstract": [
        {
          "text": "Possible actions to take after the haptic engine finishes execution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FinishedAction"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/FinishedAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FinishedAction"
        }
      ],
      "role": "symbol",
      "title": "CHHapticEngine.FinishedAction",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticengine/finishedaction"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/FinishedAction/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/FinishedAction/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticengine/finishedaction/init(rawvalue:)"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/FinishedAction/leaveEngineRunning": {
      "abstract": [
        {
          "text": "Keeps the engine running after it finishes playing all haptic patterns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leaveEngineRunning"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/FinishedAction/leaveEngineRunning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticEngineFinishedActionLeaveEngineRunning"
        }
      ],
      "role": "symbol",
      "title": "CHHapticEngine.FinishedAction.leaveEngineRunning",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticengine/finishedaction/leaveenginerunning"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/FinishedAction/stopEngine": {
      "abstract": [
        {
          "text": "Stops the engine after it finishes playing all haptic patterns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopEngine"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/FinishedAction/stopEngine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticEngineFinishedActionStopEngine"
        }
      ],
      "role": "symbol",
      "title": "CHHapticEngine.FinishedAction.stopEngine",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticengine/finishedaction/stopengine"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/FinishedHandler": {
      "abstract": [
        {
          "text": "A type alias for a completion handler to execute after finishing haptic playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FinishedHandler"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/FinishedHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FinishedHandler"
        }
      ],
      "role": "symbol",
      "title": "CHHapticEngine.FinishedHandler",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticengine/finishedhandler"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/notifyWhenPlayersFinished(finishedHandler:)": {
      "abstract": [
        {
          "text": "Notifies you when all haptic pattern players have finished playing their haptic patterns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notifyWhenPlayersFinished"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "finishedHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticEngine",
          "text": "CHHapticEngine"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticEngineFinishedHandler",
          "text": "FinishedHandler"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/notifyWhenPlayersFinished(finishedHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "notifyWhenPlayersFinished:"
        }
      ],
      "role": "symbol",
      "title": "notifyWhenPlayersFinished(finishedHandler:)",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticengine/notifywhenplayersfinished(finishedhandler:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Monitoring-Finished-Playback",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/notifyWhenPlayersFinished(finishedHandler:)",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/FinishedHandler"
      ],
      "title": "Monitoring Finished Playback"
    }
  ],
  "topicSections": [
    {
      "anchor": "Finished-Actions",
      "identifiers": [
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/FinishedAction/leaveEngineRunning",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/FinishedAction/stopEngine"
      ],
      "title": "Finished Actions"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/FinishedAction/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CHHapticEngineFinishedAction"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngineFinishedAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngineFinishedAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corehaptics/documentation/CoreHaptics"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Finished-Actions",
              "identifiers": [
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/FinishedAction/leaveEngineRunning",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/FinishedAction/stopEngine"
              ],
              "title": "Finished Actions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Monitoring-Finished-Playback",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/notifyWhenPlayersFinished(finishedHandler:)",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/FinishedHandler"
              ],
              "title": "Monitoring Finished Playback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CHHapticEngineFinishedAction"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine/title",
          "value": "CHHapticEngine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1FinishedAction~1leaveEngineRunning/title",
          "value": "CHHapticEngineFinishedActionLeaveEngineRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1FinishedAction~1leaveEngineRunning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngineFinishedActionLeaveEngineRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1FinishedAction~1stopEngine/title",
          "value": "CHHapticEngineFinishedActionStopEngine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1FinishedAction~1stopEngine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngineFinishedActionStopEngine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1FinishedAction/title",
          "value": "CHHapticEngineFinishedAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1FinishedAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngineFinishedAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1FinishedAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngineFinishedAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1notifyWhenPlayersFinished(finishedHandler:)/title",
          "value": "notifyWhenPlayersFinished:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1notifyWhenPlayersFinished(finishedHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "notifyWhenPlayersFinished:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1FinishedHandler/title",
          "value": "CHHapticEngineFinishedHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1FinishedHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngineFinishedHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1FinishedHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngineFinishedHandler"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corehaptics/chhapticengine/finishedaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corehaptics/chhapticengine/finishedaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
