{
  "abstract": [
    {
      "text": "The enumeration of reasons the haptic engine stopped running.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corehaptics/documentation/CoreHaptics",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CoreHaptics",
    "externalID": "c:@E@CHHapticEngineStoppedReason",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "StoppedReason"
      }
    ],
    "modules": [
      {
        "name": "Core Haptics"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "StoppedReason"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CHHapticEngine.StoppedReason"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "StoppedReason"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corehaptics/documentation/CoreHaptics": {
      "abstract": [
        {
          "text": "Compose and play haptic patterns to customize your iOS app’s haptic feedback.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Haptics",
      "type": "topic",
      "url": "/documentation/corehaptics"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine": {
      "abstract": [
        {
          "text": "An object that represents the connection to the haptic server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CHHapticEngine"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticEngine"
        }
      ],
      "role": "symbol",
      "title": "CHHapticEngine",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticengine"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedHandler-swift.typealias": {
      "abstract": [
        {
          "text": "A typealias for the block that the haptic engine calls after it stops due to an external cause.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "StoppedHandler"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedHandler-swift.typealias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "StoppedHandler"
        }
      ],
      "role": "symbol",
      "title": "CHHapticEngine.StoppedHandler",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticengine/stoppedhandler-swift.typealias"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason": {
      "abstract": [
        {
          "text": "The enumeration of reasons the haptic engine stopped running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "StoppedReason"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "StoppedReason"
        }
      ],
      "role": "symbol",
      "title": "CHHapticEngine.StoppedReason",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticengine/stoppedreason"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/applicationSuspended": {
      "abstract": [
        {
          "text": "The system suspended your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationSuspended"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/applicationSuspended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticEngineStoppedReasonApplicationSuspended"
        }
      ],
      "role": "symbol",
      "title": "CHHapticEngine.StoppedReason.applicationSuspended",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticengine/stoppedreason/applicationsuspended"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/audioSessionInterrupt": {
      "abstract": [
        {
          "text": "The system interrupted the audio session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioSessionInterrupt"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/audioSessionInterrupt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticEngineStoppedReasonAudioSessionInterrupt"
        }
      ],
      "role": "symbol",
      "title": "CHHapticEngine.StoppedReason.audioSessionInterrupt",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticengine/stoppedreason/audiosessioninterrupt"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/engineDestroyed": {
      "abstract": [
        {
          "text": "The system destroyed the engine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "engineDestroyed"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/engineDestroyed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticEngineStoppedReasonEngineDestroyed"
        }
      ],
      "role": "symbol",
      "title": "CHHapticEngine.StoppedReason.engineDestroyed",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticengine/stoppedreason/enginedestroyed"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/gameControllerDisconnect": {
      "abstract": [
        {
          "text": "The engine stopped because the associated game controller disconnected from the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gameControllerDisconnect"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/gameControllerDisconnect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticEngineStoppedReasonGameControllerDisconnect"
        }
      ],
      "role": "symbol",
      "title": "CHHapticEngine.StoppedReason.gameControllerDisconnect",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticengine/stoppedreason/gamecontrollerdisconnect"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/idleTimeout": {
      "abstract": [
        {
          "text": "The engine shut down because you’ve enabled automatic shutdown, and the engine reached its idle timeout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "idleTimeout"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/idleTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticEngineStoppedReasonIdleTimeout"
        }
      ],
      "role": "symbol",
      "title": "CHHapticEngine.StoppedReason.idleTimeout",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticengine/stoppedreason/idletimeout"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticengine/stoppedreason/init(rawvalue:)"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/notifyWhenFinished": {
      "abstract": [
        {
          "text": "You’ve asked the system to notify you when it shuts down the engine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notifyWhenFinished"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/notifyWhenFinished",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticEngineStoppedReasonNotifyWhenFinished"
        }
      ],
      "role": "symbol",
      "title": "CHHapticEngine.StoppedReason.notifyWhenFinished",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticengine/stoppedreason/notifywhenfinished"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/systemError": {
      "abstract": [
        {
          "text": "A system error stopped the engine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemError"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/systemError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticEngineStoppedReasonSystemError"
        }
      ],
      "role": "symbol",
      "title": "CHHapticEngine.StoppedReason.systemError",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticengine/stoppedreason/systemerror"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/stoppedHandler-swift.property": {
      "abstract": [
        {
          "text": "A closure the haptic engine calls when it stops due to external causes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stoppedHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticEngine",
          "text": "CHHapticEngine"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticEngineStoppedHandler",
          "text": "StoppedHandler"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/stoppedHandler-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stoppedHandler"
        }
      ],
      "role": "symbol",
      "title": "stoppedHandler",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticengine/stoppedhandler-swift.property"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-Haptic-Engine-Stoppages",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/stoppedHandler-swift.property",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedHandler-swift.typealias"
      ],
      "title": "Handling Haptic Engine Stoppages"
    }
  ],
  "topicSections": [
    {
      "anchor": "Stopped-Reasons",
      "identifiers": [
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/audioSessionInterrupt",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/applicationSuspended",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/engineDestroyed",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/gameControllerDisconnect",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/idleTimeout",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/notifyWhenFinished",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/systemError"
      ],
      "title": "Stopped Reasons"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CHHapticEngineStoppedReason"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngineStoppedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngineStoppedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corehaptics/documentation/CoreHaptics"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Stopped-Reasons",
              "identifiers": [
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/audioSessionInterrupt",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/applicationSuspended",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/engineDestroyed",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/gameControllerDisconnect",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/idleTimeout",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/notifyWhenFinished",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedReason/systemError"
              ],
              "title": "Stopped Reasons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Handling-Haptic-Engine-Stoppages",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/stoppedHandler-swift.property",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEngine/StoppedHandler-swift.typealias"
              ],
              "title": "Handling Haptic Engine Stoppages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CHHapticEngineStoppedReason"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1StoppedReason~1idleTimeout/title",
          "value": "CHHapticEngineStoppedReasonIdleTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1StoppedReason~1idleTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngineStoppedReasonIdleTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1StoppedReason~1systemError/title",
          "value": "CHHapticEngineStoppedReasonSystemError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1StoppedReason~1systemError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngineStoppedReasonSystemError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1StoppedReason~1engineDestroyed/title",
          "value": "CHHapticEngineStoppedReasonEngineDestroyed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1StoppedReason~1engineDestroyed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngineStoppedReasonEngineDestroyed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1StoppedReason~1applicationSuspended/title",
          "value": "CHHapticEngineStoppedReasonApplicationSuspended"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1StoppedReason~1applicationSuspended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngineStoppedReasonApplicationSuspended"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1StoppedReason/title",
          "value": "CHHapticEngineStoppedReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1StoppedReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngineStoppedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1StoppedReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngineStoppedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1StoppedHandler-swift.typealias/title",
          "value": "CHHapticEngineStoppedHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1StoppedHandler-swift.typealias/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngineStoppedHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1StoppedHandler-swift.typealias/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngineStoppedHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine/title",
          "value": "CHHapticEngine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1StoppedReason~1gameControllerDisconnect/title",
          "value": "CHHapticEngineStoppedReasonGameControllerDisconnect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1StoppedReason~1gameControllerDisconnect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngineStoppedReasonGameControllerDisconnect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1stoppedHandler-swift.property/title",
          "value": "stoppedHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1stoppedHandler-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "stoppedHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1StoppedReason~1audioSessionInterrupt/title",
          "value": "CHHapticEngineStoppedReasonAudioSessionInterrupt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1StoppedReason~1audioSessionInterrupt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngineStoppedReasonAudioSessionInterrupt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1StoppedReason~1notifyWhenFinished/title",
          "value": "CHHapticEngineStoppedReasonNotifyWhenFinished"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEngine~1StoppedReason~1notifyWhenFinished/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEngineStoppedReasonNotifyWhenFinished"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corehaptics/chhapticengine/stoppedreason"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corehaptics/chhapticengine/stoppedreason"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
