{
  "abstract": [
    {
      "text": "Creates a predicate that evaluates the current user presence against that specified in the presence event.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTrigger(withPresence:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "HomeKit",
    "externalID": "c:objc(cs)HMEventTrigger(cm)predicateForEvaluatingTriggerWithPresence:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "predicateForEvaluatingTrigger"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "withPresence"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)HMPresenceEvent",
        "text": "HMPresenceEvent"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSPredicate",
        "text": "NSPredicate"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "predicateForEvaluatingTriggerWithPresence:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "predicateForEvaluatingTrigger(withPresence:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "predicateForEvaluatingTrigger"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "withPresence"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "presenceEvent"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMPresenceEvent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)HMPresenceEvent",
              "text": "HMPresenceEvent"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSPredicate",
              "text": "NSPredicate"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMPresenceEvent",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to evaluate as part of the predicate.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "presenceEvent"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A predicate object that represents a condition to evaluate before executing the scene.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicKeyPath": {
      "abstract": [
        {
          "text": "Specifies the key path for a characteristic in a predicate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicKeyPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicKeyPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicKeyPath"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicKeyPath",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristickeypath"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueKeyPath": {
      "abstract": [
        {
          "text": "Specifies the key path for a characteristic value in a predicate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueKeyPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueKeyPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueKeyPath"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueKeyPath",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluekeypath"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger": {
      "abstract": [
        {
          "text": "A trigger to activate an action set based on a set of events and optional conditions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMEventTrigger"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMEventTrigger"
        }
      ],
      "role": "symbol",
      "title": "HMEventTrigger",
      "type": "topic",
      "url": "/documentation/homekit/hmeventtrigger"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicate(forEvaluatingTriggerOccurringBetweenSignificantEvent:secondSignificantEvent:)": {
      "abstract": [
        {
          "text": "Creates a predicate that evaluates whether the event occurred between two significant events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forEvaluatingTriggerOccurringBetweenSignificantEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMSignificantTimeEvent",
          "text": "HMSignificantTimeEvent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "secondSignificantEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMSignificantTimeEvent",
          "text": "HMSignificantTimeEvent"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicate(forEvaluatingTriggerOccurringBetweenSignificantEvent:secondSignificantEvent:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "predicateForEvaluatingTriggerOccurringBetweenSignificantEvent:secondSignificantEvent:"
        }
      ],
      "role": "symbol",
      "title": "predicate(forEvaluatingTriggerOccurringBetweenSignificantEvent:secondSignificantEvent:)",
      "type": "topic",
      "url": "/documentation/homekit/hmeventtrigger/predicate(forevaluatingtriggeroccurringbetweensignificantevent:secondsignificantevent:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTrigger(_:relatedBy:toValue:)": {
      "abstract": [
        {
          "text": "Creates a predicate that evaluates whether a characteristic value relates to the specified value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicateForEvaluatingTrigger"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMCharacteristic",
          "text": "HMCharacteristic"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "relatedBy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSComparisonPredicate",
          "text": "NSComparisonPredicate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPredicateOperatorType",
          "text": "Operator"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTrigger(_:relatedBy:toValue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "predicateForEvaluatingTriggerWithCharacteristic:relatedBy:toValue:"
        }
      ],
      "role": "symbol",
      "title": "predicateForEvaluatingTrigger(_:relatedBy:toValue:)",
      "type": "topic",
      "url": "/documentation/homekit/hmeventtrigger/predicateforevaluatingtrigger(_:relatedby:tovalue:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTrigger(occurringAfter:)": {
      "abstract": [
        {
          "text": "Creates a predicate that evaluates whether the event occurred at or after the specified time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicateForEvaluatingTrigger"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "occurringAfter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation14DateComponentsV",
          "text": "DateComponents"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTrigger(occurringAfter:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "predicateForEvaluatingTriggerOccurringAfterDateWithComponents:"
        }
      ],
      "role": "symbol",
      "title": "predicateForEvaluatingTrigger(occurringAfter:)",
      "type": "topic",
      "url": "/documentation/homekit/hmeventtrigger/predicateforevaluatingtrigger(occurringafter:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTrigger(occurringBefore:)": {
      "abstract": [
        {
          "text": "Creates a predicate that evaluates whether the event occurred before the specified time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicateForEvaluatingTrigger"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "occurringBefore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation14DateComponentsV",
          "text": "DateComponents"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTrigger(occurringBefore:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "predicateForEvaluatingTriggerOccurringBeforeDateWithComponents:"
        }
      ],
      "role": "symbol",
      "title": "predicateForEvaluatingTrigger(occurringBefore:)",
      "type": "topic",
      "url": "/documentation/homekit/hmeventtrigger/predicateforevaluatingtrigger(occurringbefore:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTrigger(occurringOn:)": {
      "abstract": [
        {
          "text": "Creates a predicate that evaluates whether the event occurred at the specified time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicateForEvaluatingTrigger"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "occurringOn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation14DateComponentsV",
          "text": "DateComponents"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTrigger(occurringOn:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "predicateForEvaluatingTriggerOccurringOnDateWithComponents:"
        }
      ],
      "role": "symbol",
      "title": "predicateForEvaluatingTrigger(occurringOn:)",
      "type": "topic",
      "url": "/documentation/homekit/hmeventtrigger/predicateforevaluatingtrigger(occurringon:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTrigger(withPresence:)": {
      "abstract": [
        {
          "text": "Creates a predicate that evaluates the current user presence against that specified in the presence event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicateForEvaluatingTrigger"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withPresence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMPresenceEvent",
          "text": "HMPresenceEvent"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTrigger(withPresence:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "predicateForEvaluatingTriggerWithPresence:"
        }
      ],
      "role": "symbol",
      "title": "predicateForEvaluatingTrigger(withPresence:)",
      "type": "topic",
      "url": "/documentation/homekit/hmeventtrigger/predicateforevaluatingtrigger(withpresence:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTriggerOccurring(afterSignificantEvent:)": {
      "abstract": [
        {
          "text": "Creates a predicate that evaluates whether the event occurred after a significant event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicateForEvaluatingTriggerOccurring"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "afterSignificantEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMSignificantTimeEvent",
          "text": "HMSignificantTimeEvent"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTriggerOccurring(afterSignificantEvent:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "predicateForEvaluatingTriggerOccurringAfterSignificantEvent:"
        }
      ],
      "role": "symbol",
      "title": "predicateForEvaluatingTriggerOccurring(afterSignificantEvent:)",
      "type": "topic",
      "url": "/documentation/homekit/hmeventtrigger/predicateforevaluatingtriggeroccurring(aftersignificantevent:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTriggerOccurring(beforeSignificantEvent:)": {
      "abstract": [
        {
          "text": "Creates a predicate that evaluates whether the event occurred before a significant event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicateForEvaluatingTriggerOccurring"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "beforeSignificantEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMSignificantTimeEvent",
          "text": "HMSignificantTimeEvent"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTriggerOccurring(beforeSignificantEvent:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "predicateForEvaluatingTriggerOccurringBeforeSignificantEvent:"
        }
      ],
      "role": "symbol",
      "title": "predicateForEvaluatingTriggerOccurring(beforeSignificantEvent:)",
      "type": "topic",
      "url": "/documentation/homekit/hmeventtrigger/predicateforevaluatingtriggeroccurring(beforesignificantevent:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTriggerOccurringBetweenDate(with:secondDateWith:)": {
      "abstract": [
        {
          "text": "Creates a predicate that evaluates whether the event occurred between the specified times.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicateForEvaluatingTriggerOccurringBetweenDate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation14DateComponentsV",
          "text": "DateComponents"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "secondDateWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation14DateComponentsV",
          "text": "DateComponents"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTriggerOccurringBetweenDate(with:secondDateWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "predicateForEvaluatingTriggerOccurringBetweenDateWithComponents:secondDateWithComponents:"
        }
      ],
      "role": "symbol",
      "title": "predicateForEvaluatingTriggerOccurringBetweenDate(with:secondDateWith:)",
      "type": "topic",
      "url": "/documentation/homekit/hmeventtrigger/predicateforevaluatingtriggeroccurringbetweendate(with:seconddatewith:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMPresenceEvent": {
      "abstract": [
        {
          "text": "An event that triggers based on the presence of users in the home.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMPresenceEvent"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMPresenceEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMPresenceEvent"
        }
      ],
      "role": "symbol",
      "title": "HMPresenceEvent",
      "type": "topic",
      "url": "/documentation/homekit/hmpresenceevent"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMPresenceKeyPath": {
      "abstract": [
        {
          "text": "Specifies the key path for a presence event in a predicate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMPresenceKeyPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMPresenceKeyPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMPresenceKeyPath"
        }
      ],
      "role": "symbol",
      "title": "HMPresenceKeyPath",
      "type": "topic",
      "url": "/documentation/homekit/hmpresencekeypath"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate": {
      "abstract": [
        {
          "text": "A definition of logical conditions for constraining a search for a fetch or for in-memory filtering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSPredicate"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPredicate",
      "type": "topic",
      "url": "/documentation/foundation/nspredicate"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-predicates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTriggerOccurring(beforeSignificantEvent:)",
        "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTriggerOccurring(afterSignificantEvent:)",
        "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicate(forEvaluatingTriggerOccurringBetweenSignificantEvent:secondSignificantEvent:)",
        "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTrigger(occurringBefore:)",
        "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTrigger(occurringOn:)",
        "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTrigger(occurringAfter:)",
        "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTriggerOccurringBetweenDate(with:secondDateWith:)",
        "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTrigger(_:relatedBy:toValue:)",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicKeyPath",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueKeyPath",
        "doc://com.apple.homekit/documentation/HomeKit/HMPresenceKeyPath"
      ],
      "title": "Creating predicates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "predicateForEvaluatingTriggerWithPresence:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "predicateForEvaluatingTriggerWithPresence:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit",
                "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-predicates",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTriggerOccurring(beforeSignificantEvent:)",
                "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTriggerOccurring(afterSignificantEvent:)",
                "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicate(forEvaluatingTriggerOccurringBetweenSignificantEvent:secondSignificantEvent:)",
                "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTrigger(occurringBefore:)",
                "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTrigger(occurringOn:)",
                "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTrigger(occurringAfter:)",
                "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTriggerOccurringBetweenDate(with:secondDateWith:)",
                "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/predicateForEvaluatingTrigger(_:relatedBy:toValue:)",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicKeyPath",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueKeyPath",
                "doc://com.apple.homekit/documentation/HomeKit/HMPresenceKeyPath"
              ],
              "title": "Creating predicates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSPredicate",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSPredicate",
                    "text": "NSPredicate"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "predicateForEvaluatingTriggerWithPresence:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMPresenceEvent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)HMPresenceEvent",
                    "text": "HMPresenceEvent"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "presenceEvent"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMPresenceEvent",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " to evaluate as part of the predicate.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "presenceEvent"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A predicate object that represents a condition to evaluate before executing the scene.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger~1predicateForEvaluatingTriggerOccurring(beforeSignificantEvent:)/title",
          "value": "predicateForEvaluatingTriggerOccurringBeforeSignificantEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger~1predicateForEvaluatingTriggerOccurring(beforeSignificantEvent:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "predicateForEvaluatingTriggerOccurringBeforeSignificantEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMPresenceKeyPath/title",
          "value": "HMPresenceKeyPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMPresenceKeyPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMPresenceKeyPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger/title",
          "value": "HMEventTrigger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMEventTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMEventTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger~1predicateForEvaluatingTrigger(withPresence:)/title",
          "value": "predicateForEvaluatingTriggerWithPresence:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger~1predicateForEvaluatingTrigger(withPresence:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "predicateForEvaluatingTriggerWithPresence:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger~1predicateForEvaluatingTrigger(_:relatedBy:toValue:)/title",
          "value": "predicateForEvaluatingTriggerWithCharacteristic:relatedBy:toValue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger~1predicateForEvaluatingTrigger(_:relatedBy:toValue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "predicateForEvaluatingTriggerWithCharacteristic:relatedBy:toValue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger~1predicateForEvaluatingTriggerOccurringBetweenDate(with:secondDateWith:)/title",
          "value": "predicateForEvaluatingTriggerOccurringBetweenDateWithComponents:secondDateWithComponents:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger~1predicateForEvaluatingTriggerOccurringBetweenDate(with:secondDateWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "predicateForEvaluatingTriggerOccurringBetweenDateWithComponents:secondDateWithComponents:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMPresenceEvent/title",
          "value": "HMPresenceEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMPresenceEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMPresenceEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMPresenceEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMPresenceEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger~1predicate(forEvaluatingTriggerOccurringBetweenSignificantEvent:secondSignificantEvent:)/title",
          "value": "predicateForEvaluatingTriggerOccurringBetweenSignificantEvent:secondSignificantEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger~1predicate(forEvaluatingTriggerOccurringBetweenSignificantEvent:secondSignificantEvent:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "predicateForEvaluatingTriggerOccurringBetweenSignificantEvent:secondSignificantEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger~1predicateForEvaluatingTrigger(occurringBefore:)/title",
          "value": "predicateForEvaluatingTriggerOccurringBeforeDateWithComponents:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger~1predicateForEvaluatingTrigger(occurringBefore:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "predicateForEvaluatingTriggerOccurringBeforeDateWithComponents:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger~1predicateForEvaluatingTriggerOccurring(afterSignificantEvent:)/title",
          "value": "predicateForEvaluatingTriggerOccurringAfterSignificantEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger~1predicateForEvaluatingTriggerOccurring(afterSignificantEvent:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "predicateForEvaluatingTriggerOccurringAfterSignificantEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicKeyPath/title",
          "value": "HMCharacteristicKeyPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicKeyPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicKeyPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger~1predicateForEvaluatingTrigger(occurringOn:)/title",
          "value": "predicateForEvaluatingTriggerOccurringOnDateWithComponents:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger~1predicateForEvaluatingTrigger(occurringOn:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "predicateForEvaluatingTriggerOccurringOnDateWithComponents:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueKeyPath/title",
          "value": "HMCharacteristicValueKeyPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueKeyPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueKeyPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger~1predicateForEvaluatingTrigger(occurringAfter:)/title",
          "value": "predicateForEvaluatingTriggerOccurringAfterDateWithComponents:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger~1predicateForEvaluatingTrigger(occurringAfter:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "predicateForEvaluatingTriggerOccurringAfterDateWithComponents:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmeventtrigger/predicateforevaluatingtrigger(withpresence:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmeventtrigger/predicateforevaluatingtrigger(withpresence:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
