{
  "abstract": [
    {
      "text": "An error code that indicates the extension’s parent app isn’t in a valid location for activation.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemextensions/documentation/SystemExtensions",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/unsupportedParentBundleLocation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@OSSystemExtensionErrorCode@OSSystemExtensionErrorUnsupportedParentBundleLocation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unsupportedParentBundleLocation"
      }
    ],
    "modules": [
      {
        "name": "System Extensions"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "OSSystemExtensionErrorUnsupportedParentBundleLocation"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "OSSystemExtensionError.Code.unsupportedParentBundleLocation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unsupportedParentBundleLocation"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The expected location of a driver extension is in the ",
              "type": "text"
            },
            {
              "code": "Contents/Library/SystemExtensions",
              "type": "codeVoice"
            },
            {
              "text": " directory of a macOS app. The app itself must be in one of the system’s ",
              "type": "text"
            },
            {
              "code": "Applications",
              "type": "codeVoice"
            },
            {
              "text": " directories.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions": {
      "abstract": [
        {
          "text": "Install and manage user space code that extends the capabilities of macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions",
      "kind": "symbol",
      "role": "collection",
      "title": "System Extensions",
      "type": "topic",
      "url": "/documentation/systemextensions"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError": {
      "abstract": [
        {
          "text": "An error that describes a failed extension manager request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSSystemExtensionError"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSystemExtensionError"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionError",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code": {
      "abstract": [
        {
          "text": "Error codes for system extensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionError.Code",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/code"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/authorizationRequired": {
      "abstract": [
        {
          "text": "An error code that indicates the system was unable to obtain the proper authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorizationRequired"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/authorizationRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSystemExtensionErrorAuthorizationRequired"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionError.Code.authorizationRequired",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/code/authorizationrequired"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/codeSignatureInvalid": {
      "abstract": [
        {
          "text": "An error code that indicates the extension’s signature is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "codeSignatureInvalid"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/codeSignatureInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSystemExtensionErrorCodeSignatureInvalid"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionError.Code.codeSignatureInvalid",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/code/codesignatureinvalid"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/duplicateExtensionIdentifer": {
      "abstract": [
        {
          "text": "An error code that indicates the extension identifier duplicates an existing identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duplicateExtensionIdentifer"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/duplicateExtensionIdentifer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSystemExtensionErrorDuplicateExtensionIdentifer"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionError.Code.duplicateExtensionIdentifer",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/code/duplicateextensionidentifer"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/extensionMissingIdentifier": {
      "abstract": [
        {
          "text": "An error code that indicates the extension identifier is missing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensionMissingIdentifier"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/extensionMissingIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSystemExtensionErrorExtensionMissingIdentifier"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionError.Code.extensionMissingIdentifier",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/code/extensionmissingidentifier"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/extensionNotFound": {
      "abstract": [
        {
          "text": "An error code that indicates the manager can’t find the system extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensionNotFound"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/extensionNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSystemExtensionErrorExtensionNotFound"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionError.Code.extensionNotFound",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/code/extensionnotfound"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/forbiddenBySystemPolicy": {
      "abstract": [
        {
          "text": "An error code that indicates the system policy prohibits activating the system extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forbiddenBySystemPolicy"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/forbiddenBySystemPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSystemExtensionErrorForbiddenBySystemPolicy"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionError.Code.forbiddenBySystemPolicy",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/code/forbiddenbysystempolicy"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/missingEntitlement": {
      "abstract": [
        {
          "text": "An error code that indicates the system extension lacks a required entitlement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingEntitlement"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/missingEntitlement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSystemExtensionErrorMissingEntitlement"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionError.Code.missingEntitlement",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/code/missingentitlement"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/requestCanceled": {
      "abstract": [
        {
          "text": "An error code that indicates the system extension manager request was canceled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestCanceled"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/requestCanceled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSystemExtensionErrorRequestCanceled"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionError.Code.requestCanceled",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/code/requestcanceled"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/requestSuperseded": {
      "abstract": [
        {
          "text": "An error code that indicates the system extension request failed because the system already has a pending request for the same identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestSuperseded"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/requestSuperseded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSystemExtensionErrorRequestSuperseded"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionError.Code.requestSuperseded",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/code/requestsuperseded"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/unknown": {
      "abstract": [
        {
          "text": "An error code that indicates an unknown error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSystemExtensionErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionError.Code.unknown",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/code/unknown"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/unknownExtensionCategory": {
      "abstract": [
        {
          "text": "An error code that indicates the extension manager can’t recognize the extension’s category identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownExtensionCategory"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/unknownExtensionCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSystemExtensionErrorUnknownExtensionCategory"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionError.Code.unknownExtensionCategory",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/code/unknownextensioncategory"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/unsupportedParentBundleLocation": {
      "abstract": [
        {
          "text": "An error code that indicates the extension’s parent app isn’t in a valid location for activation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedParentBundleLocation"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/unsupportedParentBundleLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSystemExtensionErrorUnsupportedParentBundleLocation"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionError.Code.unsupportedParentBundleLocation",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/code/unsupportedparentbundlelocation"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/validationFailed": {
      "abstract": [
        {
          "text": "An error code that indicates the manager can’t validate the extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "validationFailed"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/validationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSystemExtensionErrorValidationFailed"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionError.Code.validationFailed",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/code/validationfailed"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/unknown",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/missingEntitlement",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/extensionNotFound",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/extensionMissingIdentifier",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/duplicateExtensionIdentifer",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/unknownExtensionCategory",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/codeSignatureInvalid",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/validationFailed",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/forbiddenBySystemPolicy",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/requestCanceled",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/requestSuperseded",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/authorizationRequired"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "OSSystemExtensionErrorUnsupportedParentBundleLocation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionErrorUnsupportedParentBundleLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.systemextensions/documentation/SystemExtensions",
                "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/unknown",
                "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/missingEntitlement",
                "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/extensionNotFound",
                "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/extensionMissingIdentifier",
                "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/duplicateExtensionIdentifer",
                "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/unknownExtensionCategory",
                "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/codeSignatureInvalid",
                "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/validationFailed",
                "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/forbiddenBySystemPolicy",
                "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/requestCanceled",
                "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/requestSuperseded",
                "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code/authorizationRequired"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "OSSystemExtensionErrorUnsupportedParentBundleLocation"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code~1validationFailed/title",
          "value": "OSSystemExtensionErrorValidationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code~1validationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionErrorValidationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code~1unsupportedParentBundleLocation/title",
          "value": "OSSystemExtensionErrorUnsupportedParentBundleLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code~1unsupportedParentBundleLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionErrorUnsupportedParentBundleLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code~1codeSignatureInvalid/title",
          "value": "OSSystemExtensionErrorCodeSignatureInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code~1codeSignatureInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionErrorCodeSignatureInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code~1requestSuperseded/title",
          "value": "OSSystemExtensionErrorRequestSuperseded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code~1requestSuperseded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionErrorRequestSuperseded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code~1missingEntitlement/title",
          "value": "OSSystemExtensionErrorMissingEntitlement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code~1missingEntitlement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionErrorMissingEntitlement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code~1requestCanceled/title",
          "value": "OSSystemExtensionErrorRequestCanceled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code~1requestCanceled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionErrorRequestCanceled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code/title",
          "value": "OSSystemExtensionErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code~1forbiddenBySystemPolicy/title",
          "value": "OSSystemExtensionErrorForbiddenBySystemPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code~1forbiddenBySystemPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionErrorForbiddenBySystemPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code~1extensionMissingIdentifier/title",
          "value": "OSSystemExtensionErrorExtensionMissingIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code~1extensionMissingIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionErrorExtensionMissingIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code~1authorizationRequired/title",
          "value": "OSSystemExtensionErrorAuthorizationRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code~1authorizationRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionErrorAuthorizationRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code~1duplicateExtensionIdentifer/title",
          "value": "OSSystemExtensionErrorDuplicateExtensionIdentifer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code~1duplicateExtensionIdentifer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionErrorDuplicateExtensionIdentifer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code~1unknownExtensionCategory/title",
          "value": "OSSystemExtensionErrorUnknownExtensionCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code~1unknownExtensionCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionErrorUnknownExtensionCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code~1unknown/title",
          "value": "OSSystemExtensionErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code~1extensionNotFound/title",
          "value": "OSSystemExtensionErrorExtensionNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code~1extensionNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionErrorExtensionNotFound"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemextensions/ossystemextensionerror/code/unsupportedparentbundlelocation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemextensions/ossystemextensionerror/code/unsupportedparentbundlelocation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
