{
  "abstract": [
    {
      "text": "Update your apps to use new features, and test your apps against API changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.ios-ipados-release-notes/documentation/ios-ipados-release-notes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.ios-ipados-release-notes/documentation/iOS-iPadOS-Release-Notes/ios-ipados-14_5-release-notes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "iOS & iPadOS 14.5 Release Notes"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The iOS & iPadOS 14.5 SDK provides support to develop apps for iPhone, iPad, and iPod touch devices running iOS & iPadOS 14.5. The SDK comes bundled with Xcode 12.5, available from the Mac App Store. For information on the compatibility requirements for Xcode 12.5, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Xcode-Release-Notes/xcode-12_5-release-notes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Accessibility",
          "level": 3,
          "text": "Accessibility",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Many SF Symbols now have default accessibility labels. (70305995)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Battery-Health",
          "level": 3,
          "text": "Battery Health",
          "type": "heading"
        },
        {
          "anchor": "Resolved-Issues",
          "level": 4,
          "text": "Resolved Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "iPhone 11, iPhone 11 Pro, and iPhone 11 Pro Max battery health reporting system will recalibrate maximum battery capacity and peak performance capability to address inaccurate estimates of battery health reporting for some users. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://support.apple.com/HT212247",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Combine",
          "level": 3,
          "text": "Combine",
          "type": "heading"
        },
        {
          "anchor": "Resolved-Issues",
          "level": 4,
          "text": "Resolved Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Using ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Combine/Published",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " in a subclass of a type conforming to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Combine/ObservableObject",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " now correctly publishes changes. (71816443)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Display",
          "level": 3,
          "text": "Display",
          "type": "heading"
        },
        {
          "anchor": "Resolved-Issues",
          "level": 4,
          "text": "Resolved Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "iOS & iPadOS 14.5 includes an optimization to reduce the appearance of a dim glow that might appear at reduced brightness levels with black backgrounds.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Privacy",
          "level": 3,
          "text": "Privacy",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "iPad (8th generation),  iPad Air (4th generation), iPad Pro 11-inch (2nd generation), and iPad Pro 12.9-inch (4th generation) now mute the built-in microphone when its Smart Folio is closed. To avoid unnecessarily recording the muted signal, the default behavior is to interrupt an audio session that is using the built-in microphone when the Smart Folio is closed. You can opt out of the playback interruption when the Smart Folio is closed by using the new ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioSession/CategoryOptions-swift.struct",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioSession/CategoryOptions-swift.struct/overrideMutedMicrophoneInterruption",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", allowing the audio session to continue playing uninterrupted while microphone input remains muted. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/handling-audio-interruptions",
                      "isActive": true,
                      "overridingTitle": "Responding to Audio Session Interruptions",
                      "overridingTitleInlineContent": [
                        {
                          "text": "Responding to Audio Session Interruptions",
                          "type": "text"
                        }
                      ],
                      "type": "reference"
                    },
                    {
                      "text": ". (57042856)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Siri",
          "level": 3,
          "text": "Siri",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For Music, Podcasts, and Audiobooks requests, updated dialogs for app selection are now available. To ensure your app is set up to participate in Siri app selection, see  ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SiriKit/improving-siri-media-interactions-and-app-selection",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". (74555773)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "SKAdNetwork",
          "level": 3,
          "text": "SKAdNetwork",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "With view-through attribution, ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKAdNetwork",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " now supports all ad formats for promoting apps. (70345857)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Resolved-Issues",
          "level": 4,
          "text": "Resolved Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "You’re now able to use either version 1.0 or version 2.0 signatures when generated using iOS & iPadOS 14.5 and later. (71474331)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "SwiftUI",
          "level": 3,
          "text": "SwiftUI",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Added ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/TitleAndIconLabelStyle",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", a new style for ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Label",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " views that shows both the title and icon of the label using a system-standard layout. In most cases, labels show both title and icon by default. However, some containers might apply a different default label style to their content, such as only showing icons within toolbars on macOS and iOS. To opt in to showing both the title and the icon, apply the title and icon label style: ",
                      "type": "text"
                    },
                    {
                      "code": "Label(\"Lightning\", systemImage: \"bolt.fill\").labelStyle(TitleAndIconLabelStyle())",
                      "type": "codeVoice"
                    },
                    {
                      "text": ". (64646578)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Types conforming to any style protocol, such as ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ButtonStyle",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ToggleStyle",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", are now enforced to be value types. Styles must be structures or enumerations, not classes, and conforming a class to a style protocol may trigger an assertion. This is the same restriction that the system has always enforced on types conforming to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". (62886135)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Resolved-Issues",
          "level": 4,
          "text": "Resolved Issues",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "You can now apply multiple ",
                      "type": "text"
                    },
                    {
                      "text": "doc://com.apple.documentation/documentation/swiftui/anyview/sheet(ispresented:ondismiss:content:)",
                      "type": "text"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "text": "doc://com.apple.documentation/documentation/swiftui/anyview/fullscreencover(item:ondismiss:content:)",
                      "type": "text"
                    },
                    {
                      "text": " modifiers in the same view hierarchy. (74246633)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Drop locations are now accurate when using ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/onDrop(of:delegate:)-6lin8",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". (74030674)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "text": "doc://com.apple.documentation/documentation/swiftui/ellipse/keyboardshortcut(_:)-1xmih",
                      "type": "text"
                    },
                    {
                      "text": " modifier now works in UIKit lifecycle apps. (73792634)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Changes to pages that you provide to a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/TabView",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " with ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/PageTabViewStyle",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " are now correctly reflected in the view. (65701336)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The dismissal animation of a popover modifier when running in a compact horizontal size class now renders as expected. (52606403)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Setting ",
                      "type": "text"
                    },
                    {
                      "text": "doc://com.apple.documentation/documentation/swiftui/text/preferredcolorscheme(_:)",
                      "type": "text"
                    },
                    {
                      "text": " to ",
                      "type": "text"
                    },
                    {
                      "code": "nil",
                      "type": "codeVoice"
                    },
                    {
                      "text": " now correctly resets to the system’s preferred color scheme. (67000774)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/NavigationView",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " push and pop now correctly respects disabled animations. (70062477)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/HoverEffect",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " no longer causes a ghosting effect, especially over Text. (71344349)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Using the pointer on iPadOS no longer confuses certain gestures. (71344436)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/onHover(perform:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " is now recognized as expected in a stack. (71344436)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The destination of ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/NavigationLink",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " that only differs by local state now resets that state when switching between links as expected. (72117345)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Dynamic properties such as ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/State",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Environment",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", and others now work correctly in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ButtonStyle",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " instances. (62886135)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/AppStorage",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property wrappers now work as expected when contained inside an ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Combine/ObservableObject",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", causing the system to emit the ",
                      "type": "text"
                    },
                    {
                      "text": "doc://com.apple.documentation/documentation/combine/observableobject/objectwillchange-2oa5v",
                      "type": "text"
                    },
                    {
                      "text": " publisher. (65562845)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ProgressView",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " instances initialized with a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/progress",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " object now correctly track updates to the ",
                      "type": "text"
                    },
                    {
                      "code": "Progress",
                      "type": "codeVoice"
                    },
                    {
                      "text": " object from background threads, and no longer issue a “not allowed” console warning. (69999449)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Using ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ScrollViewProxy/scrollTo(_:anchor:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " without specifying an anchor now scrolls the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/List",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " the minimum amount to make it visible. (70184639)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/TabView",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " with ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/PageTabViewStyle",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " now correctly invokes ",
                      "type": "text"
                    },
                    {
                      "text": "doc://com.apple.documentation/documentation/swiftui/anyview/onappear(perform:)",
                      "type": "text"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "text": "doc://com.apple.documentation/documentation/swiftui/anyview/ondisappear(perform:)",
                      "type": "text"
                    },
                    {
                      "text": " for its tabs. (71225006)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/InlinePickerStyle",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " now resolves as an in-line section if applied to a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Picker",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " within a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/List",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " on iOS, watchOS, and tvOS, using a checkmark to indicate the selected option. (71383311)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "WebKit",
          "level": 3,
          "text": "WebKit",
          "type": "heading"
        },
        {
          "anchor": "New-Features",
          "level": 4,
          "text": "New Features",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Apps and websites can now receive privacy-preserving attributions for ad clicks which navigate users to websites. (70502338)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Xcode",
          "level": 3,
          "text": "Xcode",
          "type": "heading"
        },
        {
          "anchor": "Deprecations",
          "level": 4,
          "text": "Deprecations",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Don’t use the iOS ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/MinimumOSVersion",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " information property list key to declare the minimum release of macOS in which your app runs. Use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersion",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " instead. (73890473)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "items": [
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Future releases of macOS ignore the ",
                              "type": "text"
                            },
                            {
                              "code": "MinimumOSVersion",
                              "type": "codeVoice"
                            },
                            {
                              "text": " key in Mac apps, including apps built with Mac Catalyst.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Future releases of macOS use the ",
                              "type": "text"
                            },
                            {
                              "code": "LSMinimumSystemVersion",
                              "type": "codeVoice"
                            },
                            {
                              "text": " key in iOS apps built with Xcode 12.5 or later. If an iOS app doesn’t include an ",
                              "type": "text"
                            },
                            {
                              "code": "LSMinimumSystemVersion",
                              "type": "codeVoice"
                            },
                            {
                              "text": " key, future releases of macOS compare the app’s ",
                              "type": "text"
                            },
                            {
                              "code": "MinimumOSVersion",
                              "type": "codeVoice"
                            },
                            {
                              "text": " with the version of its Mac Catalyst runtime to determine compatibility.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    }
                  ],
                  "type": "unorderedList"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioSession/CategoryOptions-swift.struct": {
      "abstract": [
        {
          "text": "Constants that specify optional audio behaviors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CategoryOptions"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioSession/CategoryOptions-swift.struct",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioSession.CategoryOptions",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioSession/CategoryOptions-swift.struct"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioSession/CategoryOptions-swift.struct/overrideMutedMicrophoneInterruption": {
      "abstract": [
        {
          "text": "An option that indicates whether the system interrupts the audio session when it mutes the built-in microphone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overrideMutedMicrophoneInterruption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSession",
          "text": "AVAudioSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAudioSessionCategoryOptions",
          "text": "CategoryOptions"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioSession/CategoryOptions-swift.struct/overrideMutedMicrophoneInterruption",
      "kind": "symbol",
      "role": "symbol",
      "title": "overrideMutedMicrophoneInterruption",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioSession/CategoryOptions-swift.struct/overrideMutedMicrophoneInterruption"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/handling-audio-interruptions": {
      "abstract": [
        {
          "text": "Observe audio session notifications to ensure that your app responds appropriately to interruptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/handling-audio-interruptions",
      "kind": "article",
      "role": "article",
      "title": "Handling audio interruptions",
      "type": "topic",
      "url": "/documentation/AVFAudio/handling-audio-interruptions"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersion": {
      "abstract": [
        {
          "text": "The minimum version of the operating system required for the app to run in macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersion",
      "kind": "symbol",
      "role": "symbol",
      "title": "LSMinimumSystemVersion",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/LSMinimumSystemVersion"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/MinimumOSVersion": {
      "abstract": [
        {
          "text": "The minimum version of the operating system required for the app to run in iOS, iPadOS, tvOS, and watchOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/MinimumOSVersion",
      "kind": "symbol",
      "role": "symbol",
      "title": "MinimumOSVersion",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/MinimumOSVersion"
    },
    "doc://com.apple.documentation/documentation/Combine/ObservableObject": {
      "abstract": [
        {
          "text": "A type of object with a publisher that emits before the object has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ObservableObject"
        },
        {
          "kind": "text",
          "text": " : AnyObject"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Combine/ObservableObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "ObservableObject",
      "type": "topic",
      "url": "/documentation/Combine/ObservableObject"
    },
    "doc://com.apple.documentation/documentation/Combine/Published": {
      "abstract": [
        {
          "text": "A type that publishes a property marked with an attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@propertyWrapper"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Published"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Combine/Published",
      "kind": "symbol",
      "role": "symbol",
      "title": "Published",
      "type": "topic",
      "url": "/documentation/Combine/Published"
    },
    "doc://com.apple.documentation/documentation/SiriKit/improving-siri-media-interactions-and-app-selection": {
      "abstract": [
        {
          "text": "Fine-tune voice controls and improve Siri Suggestions by sharing app capabilities, customized names, and listening habits with the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SiriKit/improving-siri-media-interactions-and-app-selection",
      "kind": "article",
      "role": "article",
      "title": "Improving Siri Media Interactions and App Selection",
      "type": "topic",
      "url": "/documentation/SiriKit/improving-siri-media-interactions-and-app-selection"
    },
    "doc://com.apple.documentation/documentation/StoreKit/SKAdNetwork": {
      "abstract": [
        {
          "text": "A class that validates advertisement-driven app installations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKAdNetwork"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKAdNetwork",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKAdNetwork",
      "type": "topic",
      "url": "/documentation/StoreKit/SKAdNetwork"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/AppStorage": {
      "abstract": [
        {
          "text": "A property wrapper type that reflects a value from `UserDefaults` and invalidates a view on a change in value in that user default.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@propertyWrapper"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AppStorage"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/AppStorage",
      "kind": "symbol",
      "role": "symbol",
      "title": "AppStorage",
      "type": "topic",
      "url": "/documentation/SwiftUI/AppStorage"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/ButtonStyle": {
      "abstract": [
        {
          "text": "A type that applies standard interaction behavior and a custom appearance to all buttons within a view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ButtonStyle"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ButtonStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "ButtonStyle",
      "type": "topic",
      "url": "/documentation/SwiftUI/ButtonStyle"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Environment": {
      "abstract": [
        {
          "text": "A property wrapper that reads a value from a view’s environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@propertyWrapper"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Environment"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Environment",
      "kind": "symbol",
      "role": "symbol",
      "title": "Environment",
      "type": "topic",
      "url": "/documentation/SwiftUI/Environment"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/HoverEffect": {
      "abstract": [
        {
          "text": "An effect applied when the pointer hovers over a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HoverEffect"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/HoverEffect",
      "kind": "symbol",
      "role": "symbol",
      "title": "HoverEffect",
      "type": "topic",
      "url": "/documentation/SwiftUI/HoverEffect"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/InlinePickerStyle": {
      "abstract": [
        {
          "text": "A `PickerStyle` where each option is displayed inline with other views in the current container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "InlinePickerStyle"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/InlinePickerStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "InlinePickerStyle",
      "type": "topic",
      "url": "/documentation/SwiftUI/InlinePickerStyle"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Label": {
      "abstract": [
        {
          "text": "A standard label for user interface items, consisting of an icon with a title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Title"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Icon"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Title"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Icon"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Label",
      "kind": "symbol",
      "role": "symbol",
      "title": "Label",
      "type": "topic",
      "url": "/documentation/SwiftUI/Label"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/List": {
      "abstract": [
        {
          "text": "A container that presents rows of data arranged in a single column, optionally providing the ability to select one or more members.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "List"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "SelectionValue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "SelectionValue"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SH",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/List",
      "kind": "symbol",
      "role": "symbol",
      "title": "List",
      "type": "topic",
      "url": "/documentation/SwiftUI/List"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/NavigationLink": {
      "abstract": [
        {
          "text": "A view that controls a navigation presentation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NavigationLink"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Destination"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Destination"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/NavigationLink",
      "kind": "symbol",
      "role": "symbol",
      "title": "NavigationLink",
      "type": "topic",
      "url": "/documentation/SwiftUI/NavigationLink"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/NavigationView": {
      "abstract": [
        {
          "text": "A view for presenting a stack of views that represents a visible path in a navigation hierarchy.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NavigationView"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/NavigationView",
      "kind": "symbol",
      "role": "symbol",
      "title": "NavigationView",
      "type": "topic",
      "url": "/documentation/SwiftUI/NavigationView"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/PageTabViewStyle": {
      "abstract": [
        {
          "text": "A `TabViewStyle` that displays a paged scrolling `TabView`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PageTabViewStyle"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/PageTabViewStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "PageTabViewStyle",
      "type": "topic",
      "url": "/documentation/SwiftUI/PageTabViewStyle"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Picker": {
      "abstract": [
        {
          "text": "A control for selecting from a set of mutually exclusive values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Picker"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "SelectionValue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "SelectionValue"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SH",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Picker",
      "kind": "symbol",
      "role": "symbol",
      "title": "Picker",
      "type": "topic",
      "url": "/documentation/SwiftUI/Picker"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/ProgressView": {
      "abstract": [
        {
          "text": "A view that shows the progress toward completion of a task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ProgressView"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "CurrentValueLabel"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "CurrentValueLabel"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ProgressView",
      "kind": "symbol",
      "role": "symbol",
      "title": "ProgressView",
      "type": "topic",
      "url": "/documentation/SwiftUI/ProgressView"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/ScrollViewProxy/scrollTo(_:anchor:)": {
      "abstract": [
        {
          "text": "Scans all scroll views contained by the proxy for the first with a child view with identifier `id`, and then scrolls to that view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollTo"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "id"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "anchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI9UnitPointV",
          "text": "UnitPoint"
        },
        {
          "kind": "text",
          "text": "? = nil) "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "ID"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SH",
          "text": "Hashable"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ScrollViewProxy/scrollTo(_:anchor:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "scrollTo(_:anchor:)",
      "type": "topic",
      "url": "/documentation/SwiftUI/ScrollViewProxy/scrollTo(_:anchor:)"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/State": {
      "abstract": [
        {
          "text": "A property wrapper type that can read and write a value managed by SwiftUI.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@propertyWrapper"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "State"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/State",
      "kind": "symbol",
      "role": "symbol",
      "title": "State",
      "type": "topic",
      "url": "/documentation/SwiftUI/State"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/TabView": {
      "abstract": [
        {
          "text": "A view that switches between multiple child views using interactive user interface elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TabView"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "SelectionValue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "SelectionValue"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SH",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/TabView",
      "kind": "symbol",
      "role": "symbol",
      "title": "TabView",
      "type": "topic",
      "url": "/documentation/SwiftUI/TabView"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/TitleAndIconLabelStyle": {
      "abstract": [
        {
          "text": "A label style that shows both the title and icon of the label using a system-standard layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TitleAndIconLabelStyle"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/TitleAndIconLabelStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "TitleAndIconLabelStyle",
      "type": "topic",
      "url": "/documentation/SwiftUI/TitleAndIconLabelStyle"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/ToggleStyle": {
      "abstract": [
        {
          "text": "The appearance and behavior of a toggle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ToggleStyle"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/ToggleStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "ToggleStyle",
      "type": "topic",
      "url": "/documentation/SwiftUI/ToggleStyle"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/View": {
      "abstract": [
        {
          "text": "A type that represents part of your app’s user interface and provides modifiers that you use to configure views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View",
      "kind": "symbol",
      "role": "symbol",
      "title": "View",
      "type": "topic",
      "url": "/documentation/SwiftUI/View"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/View/onDrop(of:delegate:)-6lin8": {
      "abstract": [
        {
          "text": "Defines the destination of a drag and drop operation using behavior controlled by the delegate that you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "nonisolated"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "onDrop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "supportedContentTypes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22UniformTypeIdentifiers6UTTypeV",
          "text": "UTType"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI12DropDelegateP",
          "text": "DropDelegate"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": "\n"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/onDrop(of:delegate:)-6lin8",
      "kind": "symbol",
      "role": "symbol",
      "title": "onDrop(of:delegate:)",
      "type": "topic",
      "url": "/documentation/SwiftUI/View/onDrop(of:delegate:)-6lin8"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/View/onHover(perform:)": {
      "abstract": [
        {
          "text": "Adds an action to perform when the user moves the pointer over or away from the view’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "nonisolated"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "onHover"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "perform"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "action"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "@escaping"
        },
        {
          "kind": "text",
          "text": " ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": "\n"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/onHover(perform:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "onHover(perform:)",
      "type": "topic",
      "url": "/documentation/SwiftUI/View/onHover(perform:)"
    },
    "doc://com.apple.documentation/documentation/Xcode-Release-Notes/xcode-12_5-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode-Release-Notes/xcode-12_5-release-notes",
      "kind": "article",
      "role": "article",
      "title": "Xcode 12.5 Release Notes",
      "type": "topic",
      "url": "/documentation/Xcode-Release-Notes/xcode-12_5-release-notes"
    },
    "doc://com.apple.documentation/documentation/foundation/progress": {
      "abstract": [
        {
          "text": "An object that conveys ongoing progress to the user for a specified task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "Progress"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/progress",
      "kind": "symbol",
      "role": "symbol",
      "title": "Progress",
      "type": "topic",
      "url": "/documentation/foundation/progress"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.ios-ipados-release-notes/documentation/iOS-iPadOS-Release-Notes/ios-ipados-14-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ios-ipados-release-notes/documentation/iOS-iPadOS-Release-Notes/ios-ipados-14-release-notes",
      "kind": "article",
      "role": "article",
      "title": "iOS & iPadOS 14 Release Notes",
      "type": "topic",
      "url": "/documentation/ios-ipados-release-notes/ios-ipados-14-release-notes"
    },
    "doc://com.apple.ios-ipados-release-notes/documentation/iOS-iPadOS-Release-Notes/ios-ipados-14_2-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ios-ipados-release-notes/documentation/iOS-iPadOS-Release-Notes/ios-ipados-14_2-release-notes",
      "kind": "article",
      "role": "article",
      "title": "iOS & iPadOS 14.2 Release Notes",
      "type": "topic",
      "url": "/documentation/ios-ipados-release-notes/ios-ipados-14_2-release-notes"
    },
    "doc://com.apple.ios-ipados-release-notes/documentation/iOS-iPadOS-Release-Notes/ios-ipados-14_3-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ios-ipados-release-notes/documentation/iOS-iPadOS-Release-Notes/ios-ipados-14_3-release-notes",
      "kind": "article",
      "role": "article",
      "title": "iOS & iPadOS 14.3 Release Notes",
      "type": "topic",
      "url": "/documentation/ios-ipados-release-notes/ios-ipados-14_3-release-notes"
    },
    "doc://com.apple.ios-ipados-release-notes/documentation/iOS-iPadOS-Release-Notes/ios-ipados-14_4-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ios-ipados-release-notes/documentation/iOS-iPadOS-Release-Notes/ios-ipados-14_4-release-notes",
      "kind": "article",
      "role": "article",
      "title": "iOS & iPadOS 14.4 Release Notes",
      "type": "topic",
      "url": "/documentation/ios-ipados-release-notes/ios-ipados-14_4-release-notes"
    },
    "doc://com.apple.ios-ipados-release-notes/documentation/iOS-iPadOS-Release-Notes/ios-ipados-14_5_1-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ios-ipados-release-notes/documentation/iOS-iPadOS-Release-Notes/ios-ipados-14_5_1-release-notes",
      "kind": "article",
      "role": "article",
      "title": "iOS & iPadOS 14.5.1 Release Notes",
      "type": "topic",
      "url": "/documentation/ios-ipados-release-notes/ios-ipados-14_5_1-release-notes"
    },
    "doc://com.apple.ios-ipados-release-notes/documentation/iOS-iPadOS-Release-Notes/ios-ipados-14_6-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ios-ipados-release-notes/documentation/iOS-iPadOS-Release-Notes/ios-ipados-14_6-release-notes",
      "kind": "article",
      "role": "article",
      "title": "iOS & iPadOS 14.6 Release Notes",
      "type": "topic",
      "url": "/documentation/ios-ipados-release-notes/ios-ipados-14_6-release-notes"
    },
    "doc://com.apple.ios-ipados-release-notes/documentation/iOS-iPadOS-Release-Notes/ios-ipados-14_7-release-notes": {
      "abstract": [
        {
          "text": "Update your apps to use new features, and test your apps against API changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ios-ipados-release-notes/documentation/iOS-iPadOS-Release-Notes/ios-ipados-14_7-release-notes",
      "kind": "article",
      "role": "article",
      "title": "iOS & iPadOS 14.7 Release Notes",
      "type": "topic",
      "url": "/documentation/ios-ipados-release-notes/ios-ipados-14_7-release-notes"
    },
    "doc://com.apple.ios-ipados-release-notes/documentation/ios-ipados-release-notes": {
      "abstract": [
        {
          "text": "Learn about changes to the iOS & iPadOS SDK.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ios-ipados-release-notes/documentation/ios-ipados-release-notes",
      "kind": "article",
      "role": "collection",
      "title": "iOS & iPadOS Release Notes",
      "type": "topic",
      "url": "/documentation/ios-ipados-release-notes"
    },
    "https://support.apple.com/HT212247": {
      "identifier": "https://support.apple.com/HT212247",
      "title": "About recalibration of battery health reporting in iOS 14.5",
      "titleInlineContent": [
        {
          "text": "About recalibration of battery health reporting in iOS 14.5",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/HT212247"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "iOS--iPadOS-14",
      "generated": true,
      "identifiers": [
        "doc://com.apple.ios-ipados-release-notes/documentation/iOS-iPadOS-Release-Notes/ios-ipados-14_7-release-notes",
        "doc://com.apple.ios-ipados-release-notes/documentation/iOS-iPadOS-Release-Notes/ios-ipados-14_6-release-notes",
        "doc://com.apple.ios-ipados-release-notes/documentation/iOS-iPadOS-Release-Notes/ios-ipados-14_5_1-release-notes",
        "doc://com.apple.ios-ipados-release-notes/documentation/iOS-iPadOS-Release-Notes/ios-ipados-14_4-release-notes",
        "doc://com.apple.ios-ipados-release-notes/documentation/iOS-iPadOS-Release-Notes/ios-ipados-14_3-release-notes",
        "doc://com.apple.ios-ipados-release-notes/documentation/iOS-iPadOS-Release-Notes/ios-ipados-14_2-release-notes",
        "doc://com.apple.ios-ipados-release-notes/documentation/iOS-iPadOS-Release-Notes/ios-ipados-14-release-notes"
      ],
      "title": "iOS & iPadOS 14"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKAdNetwork/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKAdNetwork"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioSession~1CategoryOptions-swift.struct~1overrideMutedMicrophoneInterruption/title",
          "value": "AVAudioSessionCategoryOptionOverrideMutedMicrophoneInterruption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioSession~1CategoryOptions-swift.struct~1overrideMutedMicrophoneInterruption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionCategoryOptionOverrideMutedMicrophoneInterruption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioSession~1CategoryOptions-swift.struct/title",
          "value": "AVAudioSessionCategoryOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioSession~1CategoryOptions-swift.struct/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioSessionCategoryOptions"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1progress/title",
          "value": "NSProgress"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
