{
  "abstract": [
    {
      "text": "A media type that indicates an artist.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/artist"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INMediaItemType@INMediaItemTypeArtist",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "artist"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INMediaItemTypeArtist"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INMediaItemType.artist"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "artist"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType": {
      "abstract": [
        {
          "text": "The type of content the media item describes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INMediaItemType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemType"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/album": {
      "abstract": [
        {
          "text": "A media type that indicates an album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "album"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/album",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemTypeAlbum"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType.album",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/album"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/artist": {
      "abstract": [
        {
          "text": "A media type that indicates an artist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "artist"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/artist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemTypeArtist"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType.artist",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/artist"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/music": {
      "abstract": [
        {
          "text": "A media type that indicates music.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "music"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/music",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemTypeMusic"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType.music",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/music"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/musicStation": {
      "abstract": [
        {
          "text": "A media type that indicates a music station.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "musicStation"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/musicStation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemTypeMusicStation"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType.musicStation",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/musicstation"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/musicVideo": {
      "abstract": [
        {
          "text": "A media type that indicates a music video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "musicVideo"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/musicVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemTypeMusicVideo"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType.musicVideo",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/musicvideo"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/playlist": {
      "abstract": [
        {
          "text": "A media type that indicates a playlist of music.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playlist"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/playlist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemTypePlaylist"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType.playlist",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/playlist"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/song": {
      "abstract": [
        {
          "text": "A media type that indicates a song.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "song"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/song",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemTypeSong"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType.song",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/song"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Music",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/album",
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/musicStation",
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/musicVideo",
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/playlist",
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/song",
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/music"
      ],
      "title": "Music"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INMediaItemTypeArtist"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypeArtist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INMediaItemType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Music",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/album",
                "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/musicStation",
                "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/musicVideo",
                "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/playlist",
                "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/song",
                "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/music"
              ],
              "title": "Music"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INMediaItemTypeArtist"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1album/title",
          "value": "INMediaItemTypeAlbum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1album/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypeAlbum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1artist/title",
          "value": "INMediaItemTypeArtist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1artist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypeArtist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1song/title",
          "value": "INMediaItemTypeSong"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1song/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypeSong"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1music/title",
          "value": "INMediaItemTypeMusic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1music/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypeMusic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1musicStation/title",
          "value": "INMediaItemTypeMusicStation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1musicStation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypeMusicStation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType/title",
          "value": "INMediaItemType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1musicVideo/title",
          "value": "INMediaItemTypeMusicVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1musicVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypeMusicVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1playlist/title",
          "value": "INMediaItemTypePlaylist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1playlist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypePlaylist"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inmediaitemtype/artist"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inmediaitemtype/artist"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
