{
  "abstract": [
    {
      "text": "The descriptor for a SuperSpeedPlus isochronous USB endpoint companion.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSourceDescriptors"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSourceDescriptors/sspCompanionDescriptor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@IOUSBHostIOSourceDescriptors@FI@sspCompanionDescriptor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sspCompanionDescriptor"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@IOUSBSuperSpeedPlusIsochronousEndpointCompanionDescriptor",
        "text": "IOUSBSuperSpeedPlusIsochronousEndpointCompanionDescriptor"
      }
    ],
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "sspCompanionDescriptor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "sspCompanionDescriptor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sspCompanionDescriptor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@IOUSBSuperSpeedPlusIsochronousEndpointCompanionDescriptor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@IOUSBSuperSpeedPlusIsochronousEndpointCompanionDescriptor",
              "text": "IOUSBSuperSpeedPlusIsochronousEndpointCompanionDescriptor"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This descriptor may be necessary for ",
              "type": "text"
            },
            {
              "code": "bcdUSB",
              "type": "codeVoice"
            },
            {
              "text": " versions 0x0300 and greater, depending on device operating speed and values set in the descriptors. See USB 3.2, 9.5 for more information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSourceDescriptors": {
      "abstract": [
        {
          "text": "The descriptors for a single endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostIOSourceDescriptors"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSourceDescriptors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostIOSourceDescriptors"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostIOSourceDescriptors",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostiosourcedescriptors"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSourceDescriptors/bcdUSB": {
      "abstract": [
        {
          "text": "The USB version that the device supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bcdUSB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSourceDescriptors/bcdUSB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bcdUSB"
        }
      ],
      "role": "symbol",
      "title": "bcdUSB",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostiosourcedescriptors/bcdusb"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSourceDescriptors/descriptor": {
      "abstract": [
        {
          "text": "The descriptor for a USB endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBEndpointDescriptor",
          "text": "IOUSBEndpointDescriptor"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSourceDescriptors/descriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptor"
        }
      ],
      "role": "symbol",
      "title": "descriptor",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostiosourcedescriptors/descriptor"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSourceDescriptors/ssCompanionDescriptor": {
      "abstract": [
        {
          "text": "The descriptor for a SuperSpeed USB endpoint companion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ssCompanionDescriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBSuperSpeedEndpointCompanionDescriptor",
          "text": "IOUSBSuperSpeedEndpointCompanionDescriptor"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSourceDescriptors/ssCompanionDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ssCompanionDescriptor"
        }
      ],
      "role": "symbol",
      "title": "ssCompanionDescriptor",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostiosourcedescriptors/sscompaniondescriptor"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSourceDescriptors/sspCompanionDescriptor": {
      "abstract": [
        {
          "text": "The descriptor for a SuperSpeedPlus isochronous USB endpoint companion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sspCompanionDescriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOUSBSuperSpeedPlusIsochronousEndpointCompanionDescriptor",
          "text": "IOUSBSuperSpeedPlusIsochronousEndpointCompanionDescriptor"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSourceDescriptors/sspCompanionDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sspCompanionDescriptor"
        }
      ],
      "role": "symbol",
      "title": "sspCompanionDescriptor",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostiosourcedescriptors/sspcompaniondescriptor"
    },
    "doc://com.externally.resolved.symbol/c:@S@IOUSBSuperSpeedPlusIsochronousEndpointCompanionDescriptor": {
      "abstract": [
        {
          "text": "The descriptor for a SuperSpeedPlus Isochronous USB Endpoint Companion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBSuperSpeedPlusIsochronousEndpointCompanionDescriptor"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@IOUSBSuperSpeedPlusIsochronousEndpointCompanionDescriptor",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOUSBSuperSpeedPlusIsochronousEndpointCompanionDescriptor",
      "type": "topic",
      "url": "/documentation/USBDriverKit/IOUSBSuperSpeedPlusIsochronousEndpointCompanionDescriptor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Descriptors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSourceDescriptors/bcdUSB",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSourceDescriptors/descriptor",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSourceDescriptors/ssCompanionDescriptor"
      ],
      "title": "Descriptors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "sspCompanionDescriptor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sspCompanionDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iousbhost/documentation/IOUSBHost",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSourceDescriptors"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Descriptors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSourceDescriptors/bcdUSB",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSourceDescriptors/descriptor",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostIOSourceDescriptors/ssCompanionDescriptor"
              ],
              "title": "Descriptors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@IOUSBSuperSpeedPlusIsochronousEndpointCompanionDescriptor",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@IOUSBSuperSpeedPlusIsochronousEndpointCompanionDescriptor",
                    "text": "IOUSBSuperSpeedPlusIsochronousEndpointCompanionDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "sspCompanionDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIOSourceDescriptors~1ssCompanionDescriptor/title",
          "value": "ssCompanionDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIOSourceDescriptors~1ssCompanionDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ssCompanionDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIOSourceDescriptors~1sspCompanionDescriptor/title",
          "value": "sspCompanionDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIOSourceDescriptors~1sspCompanionDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sspCompanionDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIOSourceDescriptors~1bcdUSB/title",
          "value": "bcdUSB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIOSourceDescriptors~1bcdUSB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bcdUSB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIOSourceDescriptors~1descriptor/title",
          "value": "descriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIOSourceDescriptors~1descriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "descriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIOSourceDescriptors/title",
          "value": "IOUSBHostIOSourceDescriptors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIOSourceDescriptors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIOSourceDescriptors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostIOSourceDescriptors/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostIOSourceDescriptors"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/iousbhostiosourcedescriptors/sspcompaniondescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iousbhost/iousbhostiosourcedescriptors/sspcompaniondescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
