{
  "abstract": [
    {
      "text": "An error that occurs when CloudKit rejects a record because the server’s version is different.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/serverRecordChanged"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CKErrorCode@CKErrorServerRecordChanged",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "serverRecordChanged"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CKErrorServerRecordChanged"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CKError.Code.serverRecordChanged"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "serverRecordChanged"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This error indicates that the server’s version of the record is newer than the local version the client’s trying to save. Your app needs to handle this error, resolve any conflicts in the record, and attempt another save of the record, if necessary.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "CloudKit provides your app with three copies of the record in this error’s ",
              "type": "text"
            },
            {
              "code": "userInfo",
              "type": "codeVoice"
            },
            {
              "text": " dictionary to assist with comparing and merging the changes:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordChangedErrorClientRecordKey",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ": The local record that the client’s trying to save.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordChangedErrorServerRecordKey",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ": The record that exists on the server.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordChangedErrorAncestorRecordKey",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ": The original version of the record.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "When a conflict occurs, your app needs to merge all changes into the record for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordChangedErrorServerRecordKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key and attempt a new save using that record. Merging into either of the other two copies of the record results in another conflict error because those records have the old record change tag.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError": {
      "abstract": [
        {
          "text": "A type that describes a CloudKit error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKError"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKError"
        }
      ],
      "role": "symbol",
      "title": "CKError",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code": {
      "abstract": [
        {
          "text": "The error codes that CloudKit returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/accountTemporarilyUnavailable": {
      "abstract": [
        {
          "text": "An error that occurs when the user’s iCloud account is temporarily unavailable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accountTemporarilyUnavailable"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/accountTemporarilyUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorAccountTemporarilyUnavailable"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.accountTemporarilyUnavailable",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/accounttemporarilyunavailable"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/alreadyShared": {
      "abstract": [
        {
          "text": "An error that occurs when CloudKit attempts to share a record with an existing share.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alreadyShared"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/alreadyShared",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorAlreadyShared"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.alreadyShared",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/alreadyshared"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/assetFileModified": {
      "abstract": [
        {
          "text": "An error that occurs when the system modifies an asset while saving it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "assetFileModified"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/assetFileModified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorAssetFileModified"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.assetFileModified",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/assetfilemodified"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/assetFileNotFound": {
      "abstract": [
        {
          "text": "An error that occurs when the system can’t find the specified asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "assetFileNotFound"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/assetFileNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorAssetFileNotFound"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.assetFileNotFound",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/assetfilenotfound"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/assetNotAvailable": {
      "abstract": [
        {
          "text": "An error that occurs when the system can’t access the specified asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "assetNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/assetNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorAssetNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.assetNotAvailable",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/assetnotavailable"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/badContainer": {
      "abstract": [
        {
          "text": "An error that occurs when you use an unknown or unauthorized container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badContainer"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/badContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorBadContainer"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.badContainer",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/badcontainer"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/badDatabase": {
      "abstract": [
        {
          "text": "An error that occurs when the operation can’t complete for the specified database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badDatabase"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/badDatabase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorBadDatabase"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.badDatabase",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/baddatabase"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/batchRequestFailed": {
      "abstract": [
        {
          "text": "An error that occurs when the system rejects the entire batch of changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "batchRequestFailed"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/batchRequestFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorBatchRequestFailed"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.batchRequestFailed",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/batchrequestfailed"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/changeTokenExpired": {
      "abstract": [
        {
          "text": "An error that occurs when the change token expires.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeTokenExpired"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/changeTokenExpired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorChangeTokenExpired"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.changeTokenExpired",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/changetokenexpired"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/constraintViolation": {
      "abstract": [
        {
          "text": "An error that occurs when the server rejects the request because of a unique constraint violation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constraintViolation"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/constraintViolation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorConstraintViolation"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.constraintViolation",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/constraintviolation"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/incompatibleVersion": {
      "abstract": [
        {
          "text": "An error that occurs when the current app version is older than the oldest allowed version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "incompatibleVersion"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/incompatibleVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorIncompatibleVersion"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.incompatibleVersion",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/incompatibleversion"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/internalError": {
      "abstract": [
        {
          "text": "A nonrecoverable error that CloudKit encounters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalError"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/internalError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorInternalError"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.internalError",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/internalerror"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/invalidArguments": {
      "abstract": [
        {
          "text": "An error that occurs when the request contains invalid information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidArguments"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/invalidArguments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorInvalidArguments"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.invalidArguments",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/invalidarguments"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/limitExceeded": {
      "abstract": [
        {
          "text": "An error that occurs when a request’s size exceeds the limit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "limitExceeded"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/limitExceeded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorLimitExceeded"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.limitExceeded",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/limitexceeded"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/managedAccountRestricted": {
      "abstract": [
        {
          "text": "An error that occurs when CloudKit rejects a request due to a managed-account restriction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "managedAccountRestricted"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/managedAccountRestricted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorManagedAccountRestricted"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.managedAccountRestricted",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/managedaccountrestricted"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/serverRecordChanged": {
      "abstract": [
        {
          "text": "An error that occurs when CloudKit rejects a record because the server’s version is different.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serverRecordChanged"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/serverRecordChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKErrorServerRecordChanged"
        }
      ],
      "role": "symbol",
      "title": "CKError.Code.serverRecordChanged",
      "type": "topic",
      "url": "/documentation/cloudkit/ckerror/code/serverrecordchanged"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordChangedErrorAncestorRecordKey": {
      "abstract": [
        {
          "text": "The key to retrieve the original version of the record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKRecordChangedErrorAncestorRecordKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordChangedErrorAncestorRecordKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKRecordChangedErrorAncestorRecordKey"
        }
      ],
      "role": "symbol",
      "title": "CKRecordChangedErrorAncestorRecordKey",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordchangederrorancestorrecordkey"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordChangedErrorClientRecordKey": {
      "abstract": [
        {
          "text": "The key to retrieve the local version of the record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKRecordChangedErrorClientRecordKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordChangedErrorClientRecordKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKRecordChangedErrorClientRecordKey"
        }
      ],
      "role": "symbol",
      "title": "CKRecordChangedErrorClientRecordKey",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordchangederrorclientrecordkey"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordChangedErrorServerRecordKey": {
      "abstract": [
        {
          "text": "The key to retrieve the server’s version of the record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKRecordChangedErrorServerRecordKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordChangedErrorServerRecordKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKRecordChangedErrorServerRecordKey"
        }
      ],
      "role": "symbol",
      "title": "CKRecordChangedErrorServerRecordKey",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordchangederrorserverrecordkey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/accountTemporarilyUnavailable",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/alreadyShared",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/assetFileModified",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/assetFileNotFound",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/assetNotAvailable",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/badContainer",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/badDatabase",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/batchRequestFailed",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/changeTokenExpired",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/constraintViolation",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/incompatibleVersion",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/internalError",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/invalidArguments",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/limitExceeded",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/managedAccountRestricted"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CKErrorServerRecordChanged"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorServerRecordChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cloudkit/documentation/CloudKit",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/accountTemporarilyUnavailable",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/alreadyShared",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/assetFileModified",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/assetFileNotFound",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/assetNotAvailable",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/badContainer",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/badDatabase",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/batchRequestFailed",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/changeTokenExpired",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/constraintViolation",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/incompatibleVersion",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/internalError",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/invalidArguments",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/limitExceeded",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKError/Code/managedAccountRestricted"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CKErrorServerRecordChanged"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1batchRequestFailed/title",
          "value": "CKErrorBatchRequestFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1batchRequestFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorBatchRequestFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1incompatibleVersion/title",
          "value": "CKErrorIncompatibleVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1incompatibleVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorIncompatibleVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordChangedErrorAncestorRecordKey/title",
          "value": "CKRecordChangedErrorAncestorRecordKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordChangedErrorAncestorRecordKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordChangedErrorAncestorRecordKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1changeTokenExpired/title",
          "value": "CKErrorChangeTokenExpired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1changeTokenExpired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorChangeTokenExpired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1alreadyShared/title",
          "value": "CKErrorAlreadyShared"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1alreadyShared/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorAlreadyShared"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1assetNotAvailable/title",
          "value": "CKErrorAssetNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1assetNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorAssetNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordChangedErrorServerRecordKey/title",
          "value": "CKRecordChangedErrorServerRecordKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordChangedErrorServerRecordKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordChangedErrorServerRecordKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1assetFileNotFound/title",
          "value": "CKErrorAssetFileNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1assetFileNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorAssetFileNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1serverRecordChanged/title",
          "value": "CKErrorServerRecordChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1serverRecordChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorServerRecordChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1assetFileModified/title",
          "value": "CKErrorAssetFileModified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1assetFileModified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorAssetFileModified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1managedAccountRestricted/title",
          "value": "CKErrorManagedAccountRestricted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1managedAccountRestricted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorManagedAccountRestricted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1badDatabase/title",
          "value": "CKErrorBadDatabase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1badDatabase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorBadDatabase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1limitExceeded/title",
          "value": "CKErrorLimitExceeded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1limitExceeded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorLimitExceeded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1invalidArguments/title",
          "value": "CKErrorInvalidArguments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1invalidArguments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorInvalidArguments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code/title",
          "value": "CKErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordChangedErrorClientRecordKey/title",
          "value": "CKRecordChangedErrorClientRecordKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordChangedErrorClientRecordKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordChangedErrorClientRecordKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1accountTemporarilyUnavailable/title",
          "value": "CKErrorAccountTemporarilyUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1accountTemporarilyUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorAccountTemporarilyUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1constraintViolation/title",
          "value": "CKErrorConstraintViolation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1constraintViolation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorConstraintViolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1badContainer/title",
          "value": "CKErrorBadContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1badContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorBadContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1internalError/title",
          "value": "CKErrorInternalError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKError~1Code~1internalError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKErrorInternalError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/ckerror/code/serverrecordchanged"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cloudkit/ckerror/code/serverrecordchanged"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
