{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRangedDescription"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRangedDescription/mFormat"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@AudioStreamRangedDescription@FI@mFormat",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "mFormat"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@AudioStreamBasicDescription",
        "text": "AudioStreamBasicDescription"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "mFormat"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "mFormat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "mFormat"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@AudioStreamBasicDescription",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@AudioStreamBasicDescription",
              "text": "AudioStreamBasicDescription"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRangedDescription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioStreamRangedDescription"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRangedDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioStreamRangedDescription"
        }
      ],
      "role": "symbol",
      "title": "AudioStreamRangedDescription",
      "type": "topic",
      "url": "/documentation/coreaudio/audiostreamrangeddescription"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRangedDescription/mFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioStreamBasicDescription",
          "text": "AudioStreamBasicDescription"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRangedDescription/mFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mFormat"
        }
      ],
      "role": "symbol",
      "title": "mFormat",
      "type": "topic",
      "url": "/documentation/coreaudio/audiostreamrangeddescription/mformat"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@S@AudioStreamBasicDescription": {
      "abstract": [
        {
          "text": "A format specification for an audio stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioStreamBasicDescription"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@AudioStreamBasicDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioStreamBasicDescription",
      "type": "topic",
      "url": "/documentation/CoreAudioTypes/AudioStreamBasicDescription"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "mFormat"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudio/documentation/CoreAudio",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRangedDescription"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@AudioStreamBasicDescription",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@AudioStreamBasicDescription",
                    "text": "AudioStreamBasicDescription"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "mFormat"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamRangedDescription/title",
          "value": "AudioStreamRangedDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamRangedDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamRangedDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamRangedDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamRangedDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@S@AudioStreamBasicDescription/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioStreamBasicDescription"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamRangedDescription~1mFormat/title",
          "value": "mFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamRangedDescription~1mFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mFormat"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/audiostreamrangeddescription/mformat"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/audiostreamrangeddescription/mformat"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
