{
  "abstract": [
    {
      "text": "Appends an optionally-formatted instance of an Objective-C subclass",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "to a string interpolation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.SwiftUI/documentation/SwiftUI",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey/StringInterpolation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey/StringInterpolation/appendInterpolation(_:formatter:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:7SwiftUI18LocalizedStringKeyV0D13InterpolationV06appendF0_9formatteryx_So11NSFormatterCSgtSo8NSObjectCRbzlF::OverloadGroup",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "appendInterpolation"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "_"
      },
      {
        "kind": "text",
        "text": ":"
      },
      {
        "kind": "externalParam",
        "text": "formatter"
      },
      {
        "kind": "text",
        "text": ":)"
      }
    ],
    "modules": [
      {
        "name": "SwiftUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "appendInterpolation"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "_"
      },
      {
        "kind": "text",
        "text": ":"
      },
      {
        "kind": "externalParam",
        "text": "formatter"
      },
      {
        "kind": "text",
        "text": ":)"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "appendInterpolation(_:formatter:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "otherDeclarations": {
            "declarations": [
              {
                "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey/StringInterpolation/appendInterpolation(_:formatter:)-9vdw4",
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "mutating"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "func"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "appendInterpolation"
                  },
                  {
                    "kind": "text",
                    "text": "<"
                  },
                  {
                    "kind": "genericParameter",
                    "text": "Subject"
                  },
                  {
                    "kind": "text",
                    "text": ">("
                  },
                  {
                    "kind": "externalParam",
                    "text": "_"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "subject"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "kind": "typeIdentifier",
                    "text": "Subject"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "externalParam",
                    "text": "formatter"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSFormatter",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSFormatter",
                    "text": "Formatter"
                  },
                  {
                    "kind": "text",
                    "text": "? = nil) "
                  },
                  {
                    "kind": "keyword",
                    "text": "where"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "text": "Subject"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "highlight": "changed",
                    "identifier": "doc://com.externally.resolved.symbol/s:10Foundation20ReferenceConvertibleP",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "s:10Foundation20ReferenceConvertibleP",
                    "text": "ReferenceConvertible"
                  }
                ]
              }
            ],
            "displayIndex": 0
          },
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "mutating"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "appendInterpolation"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "genericParameter",
              "text": "Subject"
            },
            {
              "kind": "text",
              "text": ">("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "subject"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "Subject"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "formatter"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSFormatter",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSFormatter",
              "text": "Formatter"
            },
            {
              "kind": "text",
              "text": "? = nil) "
            },
            {
              "kind": "keyword",
              "text": "where"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "text": "Subject"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "highlight": "changed",
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "to append.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "subject"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A formatter to convert ",
                  "type": "text"
                },
                {
                  "code": "subject",
                  "type": "codeVoice"
                },
                {
                  "text": " to a string",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "representation.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "formatter"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Don’t call this method directly; it’s used by the compiler when",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "interpreting string interpolations.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following example shows how to use a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/measurement",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "value and a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/measurementformatter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to create a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that uses the formatter",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "style",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/formatter/unitstyle/long",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "when generating the measurement’s string representation. Rather than",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "calling ",
              "type": "text"
            },
            {
              "code": "appendInterpolation(_:formatter)",
              "type": "codeVoice"
            },
            {
              "text": " directly, the code",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "gets the formatting behavior implicitly by using the ",
              "type": "text"
            },
            {
              "code": "\\()",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "string interpolation syntax.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let siResistance = Measurement(value: 640, unit: UnitElectricResistance.ohms)",
            "let formatter = MeasurementFormatter()",
            "formatter.unitStyle = .long",
            "let key = LocalizedStringKey (\"Resistance: \\(siResistance, formatter: formatter)\")",
            "let text1 = Text(key) // Text contains \"Resistance: 640 ohms\""
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "SwiftUI-PageImage-card.png": {
      "alt": "A black Swift logo on a swirly blue and purple background.",
      "identifier": "SwiftUI-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/b1de0de086f81a5d0eac3839a0af6e6f/SwiftUI-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/1450d0b30a6b024e10c148e3f31dafe9/SwiftUI-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI": {
      "abstract": [
        {
          "text": "Declare the user interface and behavior for your app on every platform.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI",
      "images": [
        {
          "identifier": "SwiftUI-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "SwiftUI",
      "type": "topic",
      "url": "/documentation/swiftui"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey": {
      "abstract": [
        {
          "text": "The key used to look up an entry in a strings file or strings dictionary",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LocalizedStringKey"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LocalizedStringKey"
        }
      ],
      "role": "symbol",
      "title": "LocalizedStringKey",
      "type": "topic",
      "url": "/documentation/swiftui/localizedstringkey"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey/StringInterpolation": {
      "abstract": [
        {
          "text": "Represents the contents of a string literal with interpolations",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "while it’s being built, for use in creating a localized string key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "StringInterpolation"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey/StringInterpolation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "StringInterpolation"
        }
      ],
      "role": "symbol",
      "title": "LocalizedStringKey.StringInterpolation",
      "type": "topic",
      "url": "/documentation/swiftui/localizedstringkey/stringinterpolation"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey/StringInterpolation/appendInterpolation(_:)": {
      "abstract": [
        {
          "text": "Appends an attributed string to a string interpolation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appendInterpolation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": ":)"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey/StringInterpolation/appendInterpolation(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "appendInterpolation(_:)",
      "type": "topic",
      "url": "/documentation/swiftui/localizedstringkey/stringinterpolation/appendinterpolation(_:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey/StringInterpolation/appendInterpolation(_:format:)": {
      "abstract": [
        {
          "text": "Appends the formatted representation  of a nonstring type",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "supported by a corresponding format style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appendInterpolation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": ":"
        },
        {
          "kind": "externalParam",
          "text": "format"
        },
        {
          "kind": "text",
          "text": ":)"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey/StringInterpolation/appendInterpolation(_:format:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "appendInterpolation(_:format:)",
      "type": "topic",
      "url": "/documentation/swiftui/localizedstringkey/stringinterpolation/appendinterpolation(_:format:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey/StringInterpolation/appendInterpolation(_:formatter:)": {
      "abstract": [
        {
          "text": "Appends an optionally-formatted instance of an Objective-C subclass",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "to a string interpolation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appendInterpolation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": ":"
        },
        {
          "kind": "externalParam",
          "text": "formatter"
        },
        {
          "kind": "text",
          "text": ":)"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey/StringInterpolation/appendInterpolation(_:formatter:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "appendInterpolation(_:formatter:)",
      "type": "topic",
      "url": "/documentation/swiftui/localizedstringkey/stringinterpolation/appendinterpolation(_:formatter:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey/StringInterpolation/appendInterpolation(_:formatter:)-9vdw4": {
      "abstract": [
        {
          "text": "Appends an optionally-formatted instance of a Foundation type",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "to a string interpolation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appendInterpolation"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Subject"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "Subject"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "formatter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFormatter",
          "text": "Formatter"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey/StringInterpolation/appendInterpolation(_:formatter:)-9vdw4",
      "kind": "symbol",
      "role": "symbol",
      "title": "appendInterpolation(_:formatter:)",
      "type": "topic",
      "url": "/documentation/swiftui/localizedstringkey/stringinterpolation/appendinterpolation(_:formatter:)-9vdw4"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey/StringInterpolation/appendInterpolation(_:specifier:)": {
      "abstract": [
        {
          "text": "Appends a type, convertible to a string with a format specifier,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "to a string interpolation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appendInterpolation"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "specifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey/StringInterpolation/appendInterpolation(_:specifier:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "appendInterpolation(_:specifier:)",
      "type": "topic",
      "url": "/documentation/swiftui/localizedstringkey/stringinterpolation/appendinterpolation(_:specifier:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey/StringInterpolation/appendInterpolation(_:style:)": {
      "abstract": [
        {
          "text": "Appends a formatted date to a string interpolation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appendInterpolation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "style"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4TextV",
          "text": "Text"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4TextV9DateStyleV",
          "text": "DateStyle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey/StringInterpolation/appendInterpolation(_:style:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "appendInterpolation(_:style:)",
      "type": "topic",
      "url": "/documentation/swiftui/localizedstringkey/stringinterpolation/appendinterpolation(_:style:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey/StringInterpolation/appendInterpolation(timerInterval:pauseTime:countsDown:showsHours:)": {
      "abstract": [
        {
          "text": "Appends a timer interval to a string interpolation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appendInterpolation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "timerInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SN",
          "text": "ClosedRange"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "pauseTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "countsDown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "showsHours"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey/StringInterpolation/appendInterpolation(timerInterval:pauseTime:countsDown:showsHours:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "appendInterpolation(timerInterval:pauseTime:countsDown:showsHours:)",
      "type": "topic",
      "url": "/documentation/swiftui/localizedstringkey/stringinterpolation/appendinterpolation(timerinterval:pausetime:countsdown:showshours:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey/StringInterpolation/appendLiteral(_:)": {
      "abstract": [
        {
          "text": "Appends a literal string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appendLiteral"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey/StringInterpolation/appendLiteral(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "appendLiteral(_:)",
      "type": "topic",
      "url": "/documentation/swiftui/localizedstringkey/stringinterpolation/appendliteral(_:)"
    },
    "doc://com.apple.documentation/documentation/foundation/formatter/unitstyle/long": {
      "abstract": [
        {
          "text": "Specifies a long unit style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "case "
        },
        {
          "kind": "identifier",
          "text": "long"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/formatter/unitstyle/long",
      "kind": "symbol",
      "role": "symbol",
      "title": "Formatter.UnitStyle.long",
      "type": "topic",
      "url": "/documentation/foundation/formatter/unitstyle/long"
    },
    "doc://com.apple.documentation/documentation/foundation/measurement": {
      "abstract": [
        {
          "text": "A numeric quantity labeled with a unit of measure, with support for unit conversion and unit-aware calculations. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "Measurement"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/measurement",
      "kind": "symbol",
      "role": "symbol",
      "title": "Measurement",
      "type": "topic",
      "url": "/documentation/foundation/measurement"
    },
    "doc://com.apple.documentation/documentation/foundation/measurementformatter": {
      "abstract": [
        {
          "text": "A formatter that provides localized representations of units and measurements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "MeasurementFormatter"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/measurementformatter",
      "kind": "symbol",
      "role": "symbol",
      "title": "MeasurementFormatter",
      "type": "topic",
      "url": "/documentation/foundation/measurementformatter"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSFormatter": {
      "abstract": [
        {
          "text": "An abstract class that declares an interface for objects that create, interpret, and validate the textual representation of values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "Formatter"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSFormatter",
      "kind": "symbol",
      "role": "symbol",
      "title": "Formatter",
      "type": "topic",
      "url": "/documentation/foundation/formatter"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation20ReferenceConvertibleP": {
      "abstract": [
        {
          "text": "A decoration applied to types that are backed by a Foundation reference type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "ReferenceConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation20ReferenceConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ReferenceConvertible",
      "type": "topic",
      "url": "/documentation/foundation/referenceconvertible"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Appending-to-an-interpolation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey/StringInterpolation/appendInterpolation(_:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey/StringInterpolation/appendInterpolation(_:specifier:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey/StringInterpolation/appendInterpolation(_:format:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey/StringInterpolation/appendInterpolation(_:style:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey/StringInterpolation/appendInterpolation(timerInterval:pauseTime:countsDown:showsHours:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/LocalizedStringKey/StringInterpolation/appendLiteral(_:)"
      ],
      "title": "Appending to an interpolation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSFormatter/title",
          "value": "NSFormatter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1formatter~1unitstyle~1long/title",
          "value": "NSFormattingUnitStyleLong"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1measurementformatter/title",
          "value": "NSMeasurementFormatter"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/swiftui/localizedstringkey/stringinterpolation/appendinterpolation(_:formatter:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
