{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"altitudeAngle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"Discussion","type":"heading","text":"Discussion"},{"inlineContent":[{"type":"text","text":"A value of "},{"type":"codeVoice","code":"0"},{"type":"text","text":" radians indicates that the stylus is parallel to the surface. The value of this property is "},{"type":"codeVoice","code":"Pi/2"},{"type":"text","text":" when the stylus is perpendicular to the surface."}],"type":"paragraph"}],"kind":"content"}],"seeAlsoSections":[{"title":"Getting touch attributes","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITouch/tapCount","doc://com.apple.uikit/documentation/UIKit/UITouch/timestamp","doc://com.apple.uikit/documentation/UIKit/UITouch/type","doc://com.apple.uikit/documentation/UIKit/UITouch/TouchType","doc://com.apple.uikit/documentation/UIKit/UITouch/phase-swift.property","doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum","doc://com.apple.uikit/documentation/UIKit/UITouch/force","doc://com.apple.uikit/documentation/UIKit/UITouch/maximumPossibleForce","doc://com.apple.uikit/documentation/UIKit/UITouch/azimuthAngle(in:)","doc://com.apple.uikit/documentation/UIKit/UITouch/azimuthUnitVector(in:)","doc://com.apple.uikit/documentation/UIKit/UITouch/rollAngle"],"generated":true,"anchor":"Getting-touch-attributes"}],"kind":"symbol","identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UITouch/altitudeAngle","interfaceLanguage":"swift"},"variants":[{"paths":["/documentation/uikit/uitouch/altitudeangle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uitouch/altitudeangle"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The altitude (in radians) of the stylus."}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITouch"]]},"metadata":{"platforms":[{"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"9.1","beta":false},{"name":"iPadOS","deprecated":false,"unavailable":false,"introducedAt":"9.1","beta":false},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"introducedAt":"13.1","beta":false},{"name":"tvOS","deprecated":false,"unavailable":false,"introducedAt":"9.0","beta":false},{"name":"visionOS","deprecated":false,"unavailable":false,"introducedAt":"1.0","beta":false}],"symbolKind":"property","title":"altitudeAngle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"altitudeAngle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"navigatorTitle":[{"kind":"identifier","text":"altitudeAngle"}],"role":"symbol","externalID":"c:objc(cs)UITouch(py)altitudeAngle","modules":[{"name":"UIKit"}],"roleHeading":"Instance Property"},"references":{"doc://com.apple.uikit/documentation/UIKit/UITouch/tapCount":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tapCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"role":"symbol","abstract":[{"type":"text","text":"The number of times the finger was tapped for this given touch."}],"title":"tapCount","type":"topic","url":"/documentation/uikit/uitouch/tapcount","identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/tapCount","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"tapCount"}]},"doc://com.apple.uikit/documentation/UIKit/UITouch/TouchType":{"title":"UITouch.TouchType","kind":"symbol","navigatorTitle":[{"text":"TouchType","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/TouchType","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TouchType"}],"abstract":[{"type":"text","text":"The type of touch received."}],"url":"/documentation/uikit/uitouch/touchtype"},"doc://com.apple.uikit/documentation/UIKit/UITouch/altitudeAngle":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The altitude (in radians) of the stylus."}],"navigatorTitle":[{"kind":"identifier","text":"altitudeAngle"}],"title":"altitudeAngle","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/altitudeAngle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"altitudeAngle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}],"url":"/documentation/uikit/uitouch/altitudeangle"},"doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum","type":"topic","url":"/documentation/uikit/uitouch/phase-swift.enum","abstract":[{"text":"The phase of a touch event.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Phase"}],"navigatorTitle":[{"kind":"identifier","text":"Phase"}],"title":"UITouch.Phase","kind":"symbol","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITouch/maximumPossibleForce":{"kind":"symbol","abstract":[{"text":"The maximum possible force for a touch.","type":"text"}],"url":"/documentation/uikit/uitouch/maximumpossibleforce","navigatorTitle":[{"text":"maximumPossibleForce","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maximumPossibleForce","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"title":"maximumPossibleForce","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/maximumPossibleForce","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITouch/azimuthUnitVector(in:)":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"azimuthUnitVectorInView:"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/azimuthUnitVector(in:)","title":"azimuthUnitVector(in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"azimuthUnitVector"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:@S@CGVector","kind":"typeIdentifier","text":"CGVector"}],"abstract":[{"type":"text","text":"Returns a unit vector that points in the direction of the azimuth of the stylus."}],"url":"/documentation/uikit/uitouch/azimuthunitvector(in:)"},"doc://com.apple.uikit/documentation/UIKit/UITouch/rollAngle":{"type":"topic","abstract":[{"text":"A value that represents the current barrel-roll angle of Apple Pencil.","type":"text"}],"url":"/documentation/uikit/uitouch/rollangle","identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/rollAngle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rollAngle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"navigatorTitle":[{"kind":"identifier","text":"rollAngle"}],"title":"rollAngle","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITouch/force":{"navigatorTitle":[{"kind":"identifier","text":"force"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"force"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}],"kind":"symbol","url":"/documentation/uikit/uitouch/force","title":"force","identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/force","type":"topic","role":"symbol","abstract":[{"text":"The force of the touch, where a value of ","type":"text"},{"type":"codeVoice","code":"1.0"},{"type":"text","text":" represents the force of an average touch (predetermined by the system, not user-specific)."}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV":{"kind":"symbol","role":"symbol","title":"CGFloat","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"CGFloat"}],"identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV","url":"/documentation/corefoundation/cgfloat","abstract":[{"type":"text","text":"The basic type for floating-point scalar values in Core Graphics and related frameworks."}],"type":"topic"},"doc://com.externally.resolved.symbol/c:@T@CGFloat":{"abstract":[{"type":"text","text":"The basic type for all floating-point values."}],"identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat","role":"symbol","url":"/documentation/corefoundation/cgfloat","kind":"symbol","type":"topic","title":"CGFloat"},"doc://com.apple.uikit/documentation/UIKit/UITouch/timestamp":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"timestamp","kind":"identifier"}],"abstract":[{"type":"text","text":"The time when the touch occurred or when it was last mutated."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/timestamp","url":"/documentation/uikit/uitouch/timestamp","type":"topic","title":"timestamp","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITouch/type":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch","text":"UITouch"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UITouchType","text":"TouchType"}],"navigatorTitle":[{"kind":"identifier","text":"type"}],"abstract":[{"text":"The type of the touch.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/type","url":"/documentation/uikit/uitouch/type","type":"topic","title":"type","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITouch/azimuthAngle(in:)":{"url":"/documentation/uikit/uitouch/azimuthangle(in:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/azimuthAngle(in:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"azimuthAngleInView:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"azimuthAngle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}],"type":"topic","title":"azimuthAngle(in:)","kind":"symbol","abstract":[{"type":"text","text":"Returns the azimuth angle (in radians) of the stylus."}]},"doc://com.apple.uikit/documentation/UIKit/UITouch/phase-swift.property":{"kind":"symbol","title":"phase","abstract":[{"type":"text","text":"The phase of the touch."}],"url":"/documentation/uikit/uitouch/phase-swift.property","identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/phase-swift.property","type":"topic","navigatorTitle":[{"text":"phase","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phase","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITouch","text":"UITouch","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UITouchPhase","text":"Phase","kind":"typeIdentifier"}]},"doc://com.apple.uikit/documentation/UIKit/UITouch":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITouch"}],"type":"topic","title":"UITouch","url":"/documentation/uikit/uitouch","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch","navigatorTitle":[{"kind":"identifier","text":"UITouch"}],"abstract":[{"text":"An object representing the location, size, movement, and force of a touch occurring on the screen.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"introducedAt":"9.1","unavailable":false,"name":"iOS","deprecated":false},{"beta":false,"introducedAt":"9.1","unavailable":false,"name":"iPadOS","deprecated":false},{"beta":false,"introducedAt":"13.1","unavailable":false,"name":"Mac Catalyst","deprecated":false},{"beta":false,"introducedAt":"9.0","unavailable":false,"name":"tvOS","deprecated":false},{"beta":false,"introducedAt":"1.0","unavailable":false,"name":"visionOS","deprecated":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"altitudeAngle"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"altitudeAngle"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITouch"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Getting touch attributes","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITouch/tapCount","doc://com.apple.uikit/documentation/UIKit/UITouch/timestamp","doc://com.apple.uikit/documentation/UIKit/UITouch/type","doc://com.apple.uikit/documentation/UIKit/UITouch/TouchType","doc://com.apple.uikit/documentation/UIKit/UITouch/phase-swift.property","doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum","doc://com.apple.uikit/documentation/UIKit/UITouch/force","doc://com.apple.uikit/documentation/UIKit/UITouch/maximumPossibleForce","doc://com.apple.uikit/documentation/UIKit/UITouch/azimuthAngle(in:)","doc://com.apple.uikit/documentation/UIKit/UITouch/azimuthUnitVector(in:)","doc://com.apple.uikit/documentation/UIKit/UITouch/rollAngle"],"generated":true,"anchor":"Getting-touch-attributes"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat","text":"CGFloat"},{"kind":"text","text":" "},{"kind":"identifier","text":"altitudeAngle"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1tapCount/title","value":"tapCount"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1tapCount/fragments","value":[{"text":"tapCount","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1TouchType/title","value":"UITouchType"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1TouchType/fragments","value":[{"kind":"identifier","text":"UITouchType"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1TouchType/navigatorTitle","value":[{"text":"UITouchType","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1altitudeAngle/title","value":"altitudeAngle"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1altitudeAngle/fragments","value":[{"text":"altitudeAngle","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1Phase-swift.enum/title","value":"UITouchPhase"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1Phase-swift.enum/fragments","value":[{"kind":"identifier","text":"UITouchPhase"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1Phase-swift.enum/navigatorTitle","value":[{"text":"UITouchPhase","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1maximumPossibleForce/title","op":"replace","value":"maximumPossibleForce"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1maximumPossibleForce/fragments","op":"replace","value":[{"text":"maximumPossibleForce","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1azimuthUnitVector(in:)/title","op":"replace","value":"azimuthUnitVectorInView:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1azimuthUnitVector(in:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"azimuthUnitVectorInView:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1rollAngle/title","op":"replace","value":"rollAngle"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1rollAngle/fragments","op":"replace","value":[{"kind":"identifier","text":"rollAngle"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1force/title","op":"replace","value":"force"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1force/fragments","op":"replace","value":[{"text":"force","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1timestamp/title","op":"replace","value":"timestamp"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1timestamp/fragments","op":"replace","value":[{"text":"timestamp","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1type/title","op":"replace","value":"type"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1type/fragments","op":"replace","value":[{"text":"type","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1azimuthAngle(in:)/title","op":"replace","value":"azimuthAngleInView:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1azimuthAngle(in:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"azimuthAngleInView:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1phase-swift.property/title","op":"replace","value":"phase"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1phase-swift.property/fragments","op":"replace","value":[{"text":"phase","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch/title","op":"replace","value":"UITouch"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch/fragments","op":"replace","value":[{"text":"UITouch","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch/navigatorTitle","op":"replace","value":[{"text":"UITouch","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}