{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UITouch/gestureRecognizers"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITouch"]]},"abstract":[{"text":"The gesture recognizers that are receiving the touch object.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gestureRecognizers","kind":"identifier"},{"text":": [","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer","kind":"typeIdentifier"},{"text":"]? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The objects in the array are instances of a subclass of the abstract base class "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer","isActive":true},{"type":"text","text":". If there are no gesture recognizers currently receiving the touch, this property contains an empty array."}]}],"kind":"content"}],"metadata":{"role":"symbol","modules":[{"name":"UIKit"}],"roleHeading":"Instance Property","title":"gestureRecognizers","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizers"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)UIGestureRecognizer","kind":"typeIdentifier","text":"UIGestureRecognizer"},{"kind":"text","text":"]?"}],"platforms":[{"name":"iOS","introducedAt":"3.2","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","introducedAt":"3.2","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false,"unavailable":false,"beta":false},{"name":"tvOS","deprecated":false,"unavailable":false,"beta":false},{"name":"visionOS","introducedAt":"1.0","deprecated":false,"unavailable":false,"beta":false}],"navigatorTitle":[{"kind":"identifier","text":"gestureRecognizers"}],"externalID":"c:objc(cs)UITouch(py)gestureRecognizers"},"variants":[{"paths":["/documentation/uikit/uitouch/gesturerecognizers"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uitouch/gesturerecognizers"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITouch":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITouch"}],"type":"topic","title":"UITouch","url":"/documentation/uikit/uitouch","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch","navigatorTitle":[{"kind":"identifier","text":"UITouch"}],"abstract":[{"text":"An object representing the location, size, movement, and force of a touch occurring on the screen.","type":"text"}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITouch/gestureRecognizers":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/gestureRecognizers","url":"/documentation/uikit/uitouch/gesturerecognizers","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gestureRecognizers","kind":"identifier"},{"text":": [","kind":"text"},{"text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"kind":"symbol","role":"symbol","abstract":[{"text":"The gesture recognizers that are receiving the touch object.","type":"text"}],"navigatorTitle":[{"text":"gestureRecognizers","kind":"identifier"}],"title":"gestureRecognizers","type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer":{"abstract":[{"type":"text","text":"The base class for concrete gesture recognizers."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIGestureRecognizer","kind":"identifier"}],"role":"symbol","url":"/documentation/uikit/uigesturerecognizer","navigatorTitle":[{"text":"UIGestureRecognizer","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer","type":"topic","title":"UIGestureRecognizer","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"3.2","beta":false},{"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"3.2","beta":false},{"deprecated":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.1","beta":false},{"deprecated":false,"unavailable":false,"name":"tvOS","beta":false},{"deprecated":false,"unavailable":false,"name":"visionOS","introducedAt":"1.0","beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"gestureRecognizers","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"gestureRecognizers","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITouch"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"add","value":null,"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<UIGestureRecognizer *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"gestureRecognizers"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"value":"UITouch","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch/title"},{"value":[{"text":"UITouch","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch/fragments"},{"value":[{"text":"UITouch","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch/navigatorTitle"},{"value":"gestureRecognizers","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1gestureRecognizers/title"},{"value":[{"text":"gestureRecognizers","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1gestureRecognizers/fragments"},{"value":"UIGestureRecognizer","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer/title"},{"value":[{"text":"UIGestureRecognizer","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer/fragments"},{"value":[{"kind":"identifier","text":"UIGestureRecognizer"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}