{"metadata":{"title":"previousLocation(in:)","role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"previousLocation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?) -> ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"}],"platforms":[{"name":"iOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"2.0"},{"name":"iPadOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"2.0"},{"name":"Mac Catalyst","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"13.1"},{"name":"tvOS","unavailable":false,"beta":false,"deprecated":false},{"name":"visionOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"1.0"}],"modules":[{"name":"UIKit"}],"navigatorTitle":[{"text":"previousLocationInView:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)UITouch(im)previousLocationInView:"},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UITouch/previousLocation(in:)-22sws"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"previousLocation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":" "},{"kind":"internalParam","text":"view"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView","identifier":"doc://com.apple.uikit/documentation/UIKit/UIView"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint","identifier":"doc://com.externally.resolved.symbol/c:@S@CGPoint"}]}]},{"kind":"parameters","parameters":[{"name":"view","content":[{"type":"paragraph","inlineContent":[{"text":"The view object in whose coordinate system you want the touch located. A custom view that is handling the touch may specify ","type":"text"},{"type":"codeVoice","code":"self"},{"text":" to get the touch location in its own coordinate system. Pass ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" to get the touch location in the window’s coordinates.","type":"text"}]}]}]},{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method returns the previous location of a "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch"},{"type":"text","text":" object in the coordinate system of the specified view. Because the touch object might have been forwarded to a view from another view, this method performs any necessary conversion of the touch location to the coordinate system of the specified view."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITouch"]]},"abstract":[{"type":"text","text":"Returns the previous location of the touch in the coordinate system of the given view."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"anchor":"Getting-the-location-of-a-touch","title":"Getting the location of a touch","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITouch/location(in:)-8rd36","doc://com.apple.uikit/documentation/UIKit/UITouch/view","doc://com.apple.uikit/documentation/UIKit/UITouch/window","doc://com.apple.uikit/documentation/UIKit/UITouch/majorRadius","doc://com.apple.uikit/documentation/UIKit/UITouch/majorRadiusTolerance","doc://com.apple.uikit/documentation/UIKit/UITouch/preciseLocation(in:)","doc://com.apple.uikit/documentation/UIKit/UITouch/precisePreviousLocation(in:)"]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uitouch/previouslocation(in:)-22sws"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uitouch/previouslocation(in:)-22sws"]}],"kind":"symbol","references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITouch/preciseLocation(in:)":{"navigatorTitle":[{"kind":"identifier","text":"preciseLocationInView:"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/preciseLocation(in:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"preciseLocation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"}],"url":"/documentation/uikit/uitouch/preciselocation(in:)","abstract":[{"type":"text","text":"Returns a precise location for the touch, when available."}],"title":"preciseLocation(in:)","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITouch/majorRadiusTolerance":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"majorRadiusTolerance","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The tolerance (in points) of the touch’s radius."}],"title":"majorRadiusTolerance","identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/majorRadiusTolerance","navigatorTitle":[{"text":"majorRadiusTolerance","kind":"identifier"}],"url":"/documentation/uikit/uitouch/majorradiustolerance","type":"topic","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITouch/previousLocation(in:)-22sws":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previousLocation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?) -> ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"}],"abstract":[{"text":"Returns the previous location of the touch in the coordinate system of the given view.","type":"text"}],"title":"previousLocation(in:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/previousLocation(in:)-22sws","navigatorTitle":[{"text":"previousLocationInView:","kind":"identifier"}],"url":"/documentation/uikit/uitouch/previouslocation(in:)-22sws","type":"topic","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITouch/precisePreviousLocation(in:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"precisePreviousLocation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"}],"type":"topic","title":"precisePreviousLocation(in:)","url":"/documentation/uikit/uitouch/precisepreviouslocation(in:)","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/precisePreviousLocation(in:)","navigatorTitle":[{"kind":"identifier","text":"precisePreviousLocationInView:"}],"abstract":[{"text":"Returns a precise previous location for the touch, when available.","type":"text"}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITouch/location(in:)-8rd36":{"role":"symbol","abstract":[{"type":"text","text":"Returns the current location of the touch in the coordinate system of the given view."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"location","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/location(in:)-8rd36","title":"location(in:)","navigatorTitle":[{"text":"locationInView:","kind":"identifier"}],"type":"topic","kind":"symbol","url":"/documentation/uikit/uitouch/location(in:)-8rd36"},"doc://com.externally.resolved.symbol/c:@S@CGPoint":{"role":"symbol","abstract":[{"type":"text","text":"A structure that contains a point in a two-dimensional coordinate system."}],"type":"topic","url":"/documentation/corefoundation/cgpoint","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@S@CGPoint","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"CGPoint"}],"title":"CGPoint"},"doc://com.apple.uikit/documentation/UIKit/UITouch/window":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"window","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIWindow","text":"UIWindow","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","title":"window","url":"/documentation/uikit/uitouch/window","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/window","navigatorTitle":[{"text":"window","kind":"identifier"}],"abstract":[{"type":"text","text":"The window in which the touch initially occurred."}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIView":{"title":"UIView","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIView","abstract":[{"text":"An object that manages the content for a rectangular area on the screen.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"UIView","kind":"identifier"}],"url":"/documentation/uikit/uiview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIView","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UITouch/view":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"view"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":"?"}],"title":"view","identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/view","role":"symbol","type":"topic","url":"/documentation/uikit/uitouch/view","abstract":[{"type":"text","text":"The view to which touches are being delivered, if any."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"view"}]},"doc://com.apple.uikit/documentation/UIKit/UITouch":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITouch"}],"type":"topic","title":"UITouch","url":"/documentation/uikit/uitouch","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch","navigatorTitle":[{"kind":"identifier","text":"UITouch"}],"abstract":[{"text":"An object representing the location, size, movement, and force of a touch occurring on the screen.","type":"text"}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITouch/majorRadius":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/majorRadius","abstract":[{"type":"text","text":"The radius (in points) of the touch."}],"title":"majorRadius","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"majorRadius","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"navigatorTitle":[{"kind":"identifier","text":"majorRadius"}],"role":"symbol","url":"/documentation/uikit/uitouch/majorradius","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"name":"iOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"2.0"},{"name":"iPadOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"2.0"},{"name":"Mac Catalyst","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"13.1"},{"name":"tvOS","unavailable":false,"beta":false,"deprecated":false},{"name":"visionOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"1.0"}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"previousLocationInView:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"previousLocationInView:","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITouch"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"anchor":"Getting-the-location-of-a-touch","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITouch/location(in:)-8rd36","doc://com.apple.uikit/documentation/UIKit/UITouch/view","doc://com.apple.uikit/documentation/UIKit/UITouch/window","doc://com.apple.uikit/documentation/UIKit/UITouch/majorRadius","doc://com.apple.uikit/documentation/UIKit/UITouch/majorRadiusTolerance","doc://com.apple.uikit/documentation/UIKit/UITouch/preciseLocation(in:)","doc://com.apple.uikit/documentation/UIKit/UITouch/precisePreviousLocation(in:)"],"title":"Getting the location of a touch"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","identifier":"doc://com.externally.resolved.symbol/c:@S@CGPoint"},{"kind":"text","text":") "},{"kind":"identifier","text":"previousLocationInView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView","identifier":"doc://com.apple.uikit/documentation/UIKit/UIView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"view"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view object in whose coordinate system you want the touch located. A custom view that is handling the touch may specify "},{"type":"codeVoice","code":"self"},{"type":"text","text":" to get the touch location in its own coordinate system. Pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" to get the touch location in the window’s coordinates."}]}],"name":"view"}]},"path":"/primaryContentSections/1"},{"op":"replace","value":{"kind":"content","content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"inlineContent":[{"type":"text","text":"This method returns the previous location of a "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch","isActive":true},{"type":"text","text":" object in the coordinate system of the specified view. Because the touch object might have been forwarded to a view from another view, this method performs any necessary conversion of the touch location to the coordinate system of the specified view."}],"type":"paragraph"}]},"path":"/primaryContentSections/2"},{"op":"replace","value":"preciseLocationInView:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1preciseLocation(in:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"preciseLocationInView:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1preciseLocation(in:)/fragments"},{"op":"replace","value":"majorRadiusTolerance","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1majorRadiusTolerance/title"},{"op":"replace","value":[{"text":"majorRadiusTolerance","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1majorRadiusTolerance/fragments"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1previousLocation(in:)-22sws/title","value":"previousLocationInView:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1previousLocation(in:)-22sws/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"previousLocationInView:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1precisePreviousLocation(in:)/title","value":"precisePreviousLocationInView:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1precisePreviousLocation(in:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"precisePreviousLocationInView:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1location(in:)-8rd36/title","value":"locationInView:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1location(in:)-8rd36/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"locationInView:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1window/title","value":"window"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1window/fragments","value":[{"text":"window","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/title","value":"UIView"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/fragments","value":[{"kind":"identifier","text":"UIView"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/navigatorTitle","value":[{"text":"UIView","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1view/title","value":"view"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1view/fragments","value":[{"text":"view","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch/title","value":"UITouch"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch/fragments","value":[{"kind":"identifier","text":"UITouch"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch/navigatorTitle","value":[{"kind":"identifier","text":"UITouch"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1majorRadius/title","value":"majorRadius"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1majorRadius/fragments","value":[{"text":"majorRadius","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}