{"metadata":{"externalID":"c:objc(cs)UITouch(py)window","navigatorTitle":[{"text":"window","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"window"},{"text":": ","kind":"text"},{"text":"UIWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIWindow"},{"text":"?","kind":"text"}],"platforms":[{"deprecated":false,"introducedAt":"2.0","beta":false,"name":"iOS","unavailable":false},{"deprecated":false,"introducedAt":"2.0","beta":false,"name":"iPadOS","unavailable":false},{"deprecated":false,"introducedAt":"13.1","beta":false,"name":"Mac Catalyst","unavailable":false},{"deprecated":false,"name":"tvOS","beta":false,"unavailable":false},{"deprecated":false,"name":"visionOS","beta":false,"introducedAt":"1.0","unavailable":false}],"roleHeading":"Instance Property","symbolKind":"property","title":"window","modules":[{"name":"UIKit"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uitouch/window"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uitouch/window"]}],"abstract":[{"type":"text","text":"The window in which the touch initially occurred."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UITouch/window"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"window","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow","identifier":"doc://com.apple.uikit/documentation/UIKit/UIWindow","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},{"content":[{"text":"Discussion","level":2,"anchor":"Discussion","type":"heading"},{"inlineContent":[{"text":"The value of the property is the window in which the touch originally occurred. This window might not be the same window that currently contains the touch.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITouch"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"generated":true,"title":"Getting the location of a touch","anchor":"Getting-the-location-of-a-touch","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITouch/location(in:)-8rd36","doc://com.apple.uikit/documentation/UIKit/UITouch/previousLocation(in:)-22sws","doc://com.apple.uikit/documentation/UIKit/UITouch/view","doc://com.apple.uikit/documentation/UIKit/UITouch/majorRadius","doc://com.apple.uikit/documentation/UIKit/UITouch/majorRadiusTolerance","doc://com.apple.uikit/documentation/UIKit/UITouch/preciseLocation(in:)","doc://com.apple.uikit/documentation/UIKit/UITouch/precisePreviousLocation(in:)"]}],"references":{"doc://com.apple.uikit/documentation/UIKit/UITouch/majorRadiusTolerance":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"majorRadiusTolerance","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The tolerance (in points) of the touch’s radius."}],"title":"majorRadiusTolerance","identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/majorRadiusTolerance","navigatorTitle":[{"text":"majorRadiusTolerance","kind":"identifier"}],"url":"/documentation/uikit/uitouch/majorradiustolerance","type":"topic","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITouch/preciseLocation(in:)":{"navigatorTitle":[{"kind":"identifier","text":"preciseLocationInView:"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/preciseLocation(in:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"preciseLocation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"}],"url":"/documentation/uikit/uitouch/preciselocation(in:)","abstract":[{"type":"text","text":"Returns a precise location for the touch, when available."}],"title":"preciseLocation(in:)","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITouch/location(in:)-8rd36":{"role":"symbol","abstract":[{"type":"text","text":"Returns the current location of the touch in the coordinate system of the given view."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"location","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/location(in:)-8rd36","title":"location(in:)","navigatorTitle":[{"text":"locationInView:","kind":"identifier"}],"type":"topic","kind":"symbol","url":"/documentation/uikit/uitouch/location(in:)-8rd36"},"doc://com.apple.uikit/documentation/UIKit/UITouch/view":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"view"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":"?"}],"title":"view","identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/view","role":"symbol","type":"topic","url":"/documentation/uikit/uitouch/view","abstract":[{"type":"text","text":"The view to which touches are being delivered, if any."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"view"}]},"doc://com.apple.uikit/documentation/UIKit/UITouch/majorRadius":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/majorRadius","abstract":[{"type":"text","text":"The radius (in points) of the touch."}],"title":"majorRadius","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"majorRadius","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"navigatorTitle":[{"kind":"identifier","text":"majorRadius"}],"role":"symbol","url":"/documentation/uikit/uitouch/majorradius","kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITouch/precisePreviousLocation(in:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"precisePreviousLocation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"}],"type":"topic","title":"precisePreviousLocation(in:)","url":"/documentation/uikit/uitouch/precisepreviouslocation(in:)","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/precisePreviousLocation(in:)","navigatorTitle":[{"kind":"identifier","text":"precisePreviousLocationInView:"}],"abstract":[{"text":"Returns a precise previous location for the touch, when available.","type":"text"}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITouch/window":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"window","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIWindow","text":"UIWindow","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","title":"window","url":"/documentation/uikit/uitouch/window","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/window","navigatorTitle":[{"text":"window","kind":"identifier"}],"abstract":[{"type":"text","text":"The window in which the touch initially occurred."}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITouch":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITouch"}],"type":"topic","title":"UITouch","url":"/documentation/uikit/uitouch","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch","navigatorTitle":[{"kind":"identifier","text":"UITouch"}],"abstract":[{"text":"An object representing the location, size, movement, and force of a touch occurring on the screen.","type":"text"}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITouch/previousLocation(in:)-22sws":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previousLocation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?) -> ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"}],"abstract":[{"text":"Returns the previous location of the touch in the coordinate system of the given view.","type":"text"}],"title":"previousLocation(in:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UITouch/previousLocation(in:)-22sws","navigatorTitle":[{"text":"previousLocationInView:","kind":"identifier"}],"url":"/documentation/uikit/uitouch/previouslocation(in:)-22sws","type":"topic","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIWindow":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIWindow","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The backdrop for your app’s user interface and the object that dispatches events to your views."}],"role":"symbol","navigatorTitle":[{"text":"UIWindow","kind":"identifier"}],"kind":"symbol","url":"/documentation/uikit/uiwindow","identifier":"doc://com.apple.uikit/documentation/UIKit/UIWindow","title":"UIWindow"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"name":"iOS","introducedAt":"2.0","deprecated":false,"beta":false},{"unavailable":false,"name":"iPadOS","introducedAt":"2.0","deprecated":false,"beta":false},{"deprecated":false,"name":"Mac Catalyst","beta":false,"introducedAt":"13.1","unavailable":false},{"deprecated":false,"name":"tvOS","beta":false,"unavailable":false},{"deprecated":false,"name":"visionOS","beta":false,"introducedAt":"1.0","unavailable":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"window","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"window","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITouch"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"anchor":"Getting-the-location-of-a-touch","title":"Getting the location of a touch","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITouch/location(in:)-8rd36","doc://com.apple.uikit/documentation/UIKit/UITouch/previousLocation(in:)-22sws","doc://com.apple.uikit/documentation/UIKit/UITouch/view","doc://com.apple.uikit/documentation/UIKit/UITouch/majorRadius","doc://com.apple.uikit/documentation/UIKit/UITouch/majorRadiusTolerance","doc://com.apple.uikit/documentation/UIKit/UITouch/preciseLocation(in:)","doc://com.apple.uikit/documentation/UIKit/UITouch/precisePreviousLocation(in:)"]}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow","identifier":"doc://com.apple.uikit/documentation/UIKit/UIWindow"},{"kind":"text","text":" * "},{"kind":"identifier","text":"window"},{"kind":"text","text":";"}]}]},"path":"/primaryContentSections/0"},{"op":"replace","value":"majorRadiusTolerance","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1majorRadiusTolerance/title"},{"op":"replace","value":[{"text":"majorRadiusTolerance","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1majorRadiusTolerance/fragments"},{"op":"replace","value":"preciseLocationInView:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1preciseLocation(in:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"preciseLocationInView:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1preciseLocation(in:)/fragments"},{"op":"replace","value":"locationInView:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1location(in:)-8rd36/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"locationInView:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1location(in:)-8rd36/fragments"},{"op":"replace","value":"view","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1view/title"},{"op":"replace","value":[{"text":"view","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1view/fragments"},{"op":"replace","value":"majorRadius","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1majorRadius/title"},{"op":"replace","value":[{"text":"majorRadius","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1majorRadius/fragments"},{"op":"replace","value":"precisePreviousLocationInView:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1precisePreviousLocation(in:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"precisePreviousLocationInView:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1precisePreviousLocation(in:)/fragments"},{"op":"replace","value":"window","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1window/title"},{"op":"replace","value":[{"kind":"identifier","text":"window"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1window/fragments"},{"op":"replace","value":"UITouch","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch/title"},{"op":"replace","value":[{"text":"UITouch","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UITouch"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch/navigatorTitle"},{"op":"replace","value":"previousLocationInView:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1previousLocation(in:)-22sws/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"previousLocationInView:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1previousLocation(in:)-22sws/fragments"},{"op":"replace","value":"UIWindow","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindow/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIWindow"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindow/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UIWindow"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindow/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}