{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type24"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SMPTETimeType@kSMPTETimeType24",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "type24"
      }
    ],
    "modules": [
      {
        "name": "Core Audio Types"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kSMPTETimeType24"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "3.0",
        "name": "watchOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SMPTETimeType.type24"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "type24"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "24 video frames per second—standard for 16mm and 35mm film.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes": {
      "abstract": [
        {
          "text": "Use specialized data types to interact with audio streams, complex buffers, and audiovisual timestamps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio Types",
      "type": "topic",
      "url": "/documentation/coreaudiotypes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType": {
      "abstract": [
        {
          "text": "Constants that define SMPTE time types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SMPTETimeType"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SMPTETimeType"
        }
      ],
      "role": "symbol",
      "title": "SMPTETimeType",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/smptetimetype"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type2398": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type2398"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type2398",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMPTETimeType2398"
        }
      ],
      "role": "symbol",
      "title": "SMPTETimeType.type2398",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/smptetimetype/type2398"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type24": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type24"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type24",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMPTETimeType24"
        }
      ],
      "role": "symbol",
      "title": "SMPTETimeType.type24",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/smptetimetype/type24"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type25": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type25"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type25",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMPTETimeType25"
        }
      ],
      "role": "symbol",
      "title": "SMPTETimeType.type25",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/smptetimetype/type25"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type2997": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type2997"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type2997",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMPTETimeType2997"
        }
      ],
      "role": "symbol",
      "title": "SMPTETimeType.type2997",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/smptetimetype/type2997"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type2997Drop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type2997Drop"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type2997Drop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMPTETimeType2997Drop"
        }
      ],
      "role": "symbol",
      "title": "SMPTETimeType.type2997Drop",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/smptetimetype/type2997drop"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type30": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type30"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type30",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMPTETimeType30"
        }
      ],
      "role": "symbol",
      "title": "SMPTETimeType.type30",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/smptetimetype/type30"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type30Drop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type30Drop"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type30Drop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMPTETimeType30Drop"
        }
      ],
      "role": "symbol",
      "title": "SMPTETimeType.type30Drop",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/smptetimetype/type30drop"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type50": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type50"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMPTETimeType50"
        }
      ],
      "role": "symbol",
      "title": "SMPTETimeType.type50",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/smptetimetype/type50"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type5994": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type5994"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type5994",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMPTETimeType5994"
        }
      ],
      "role": "symbol",
      "title": "SMPTETimeType.type5994",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/smptetimetype/type5994"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type5994Drop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type5994Drop"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type5994Drop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMPTETimeType5994Drop"
        }
      ],
      "role": "symbol",
      "title": "SMPTETimeType.type5994Drop",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/smptetimetype/type5994drop"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type60": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type60"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMPTETimeType60"
        }
      ],
      "role": "symbol",
      "title": "SMPTETimeType.type60",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/smptetimetype/type60"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type60Drop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type60Drop"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type60Drop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSMPTETimeType60Drop"
        }
      ],
      "role": "symbol",
      "title": "SMPTETimeType.type60Drop",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/smptetimetype/type60drop"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type2398",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type25",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type2997",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type2997Drop",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type30",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type30Drop",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type50",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type5994",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type5994Drop",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type60",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type60Drop"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kSMPTETimeType24"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMPTETimeType24"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type2398",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type25",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type2997",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type2997Drop",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type30",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type30Drop",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type50",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type5994",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type5994Drop",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type60",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETimeType/type60Drop"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kSMPTETimeType24"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeType/title",
          "value": "SMPTETimeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SMPTETimeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SMPTETimeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeType~1type24/title",
          "value": "kSMPTETimeType24"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeType~1type24/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMPTETimeType24"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeType~1type30/title",
          "value": "kSMPTETimeType30"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeType~1type30/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMPTETimeType30"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeType~1type60Drop/title",
          "value": "kSMPTETimeType60Drop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeType~1type60Drop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMPTETimeType60Drop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeType~1type30Drop/title",
          "value": "kSMPTETimeType30Drop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeType~1type30Drop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMPTETimeType30Drop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeType~1type50/title",
          "value": "kSMPTETimeType50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeType~1type50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMPTETimeType50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeType~1type2997/title",
          "value": "kSMPTETimeType2997"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeType~1type2997/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMPTETimeType2997"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeType~1type2398/title",
          "value": "kSMPTETimeType2398"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeType~1type2398/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMPTETimeType2398"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeType~1type60/title",
          "value": "kSMPTETimeType60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeType~1type60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMPTETimeType60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeType~1type5994/title",
          "value": "kSMPTETimeType5994"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeType~1type5994/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMPTETimeType5994"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeType~1type5994Drop/title",
          "value": "kSMPTETimeType5994Drop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeType~1type5994Drop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMPTETimeType5994Drop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeType~1type2997Drop/title",
          "value": "kSMPTETimeType2997Drop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeType~1type2997Drop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMPTETimeType2997Drop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeType~1type25/title",
          "value": "kSMPTETimeType25"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETimeType~1type25/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSMPTETimeType25"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiotypes/smptetimetype/type24"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiotypes/smptetimetype/type24"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
