{
  "abstract": [
    {
      "text": "Provides the receiver with an updated persistable content key for a specific key request.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySession(_:didUpdatePersistableContentKey:forContentKeyIdentifier:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)AVContentKeySessionDelegate(im)contentKeySession:didUpdatePersistableContentKey:forContentKeyIdentifier:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "contentKeySession"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AVContentKeySession",
        "text": "AVContentKeySession"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "didUpdatePersistableContentKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation4DataV",
        "text": "Data"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "forContentKeyIdentifier"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "contentKeySession:didUpdatePersistableContentKey:forContentKeyIdentifier:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "contentKeySession(_:didUpdatePersistableContentKey:forContentKeyIdentifier:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "contentKeySession"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "session"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVContentKeySession",
              "text": "AVContentKeySession"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "didUpdatePersistableContentKey"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "persistableContentKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DataV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation4DataV",
              "text": "Data"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "forContentKeyIdentifier"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "keyIdentifier"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The content key session that is providing the updated persistable content key.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "session"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The updated persistent content key data. This data can be stored offline and used to answer future content key requests with the matching key identifier.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "persistableContentKey"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A container- and protocol-specific identifier for the updated persistent content key.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "keyIdentifier"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the content key session provides updated persistable content key data, previous key data is no longer valid and cannot be used to answer future loading requests.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/RetryReason": {
      "abstract": [
        {
          "text": "The reason for asking the client to retry a content key request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RetryReason"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/RetryReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RetryReason"
        }
      ],
      "role": "symbol",
      "title": "AVContentKeyRequest.RetryReason",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeyrequest/retryreason"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession": {
      "abstract": [
        {
          "text": "An object that creates and tracks decryption keys for media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContentKeySession"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentKeySession"
        }
      ],
      "role": "symbol",
      "title": "AVContentKeySession",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysession"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate": {
      "abstract": [
        {
          "text": "A protocol that handles content key requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContentKeySessionDelegate"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentKeySessionDelegate"
        }
      ],
      "role": "symbol",
      "title": "AVContentKeySessionDelegate",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysessiondelegate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySession(_:contentKeyRequest:didFailWithError:)": {
      "abstract": [
        {
          "text": "Tells the receiver that the content key request failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentKeySession"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVContentKeySession",
          "text": "AVContentKeySession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "contentKeyRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVContentKeyRequest",
          "text": "AVContentKeyRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFailWithError"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySession(_:contentKeyRequest:didFailWithError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentKeySession:contentKeyRequest:didFailWithError:"
        }
      ],
      "role": "symbol",
      "title": "contentKeySession(_:contentKeyRequest:didFailWithError:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysessiondelegate/contentkeysession(_:contentkeyrequest:didfailwitherror:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySession(_:contentKeyRequestDidSucceed:)": {
      "abstract": [
        {
          "text": "Tells the content key session that the response to a content key requeset was successfully processed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentKeySession"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVContentKeySession",
          "text": "AVContentKeySession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "contentKeyRequestDidSucceed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVContentKeyRequest",
          "text": "AVContentKeyRequest"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySession(_:contentKeyRequestDidSucceed:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentKeySession:contentKeyRequestDidSucceed:"
        }
      ],
      "role": "symbol",
      "title": "contentKeySession(_:contentKeyRequestDidSucceed:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysessiondelegate/contentkeysession(_:contentkeyrequestdidsucceed:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySession(_:didProvide:forInitializationData:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentKeySession"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVContentKeySession",
          "text": "AVContentKeySession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didProvide"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVContentKeyRequest",
          "text": "AVContentKeyRequest"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "forInitializationData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySession(_:didProvide:forInitializationData:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentKeySession:didProvideContentKeyRequests:forInitializationData:"
        }
      ],
      "role": "symbol",
      "title": "contentKeySession(_:didProvide:forInitializationData:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysessiondelegate/contentkeysession(_:didprovide:forinitializationdata:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySession(_:didUpdatePersistableContentKey:forContentKeyIdentifier:)": {
      "abstract": [
        {
          "text": "Provides the receiver with an updated persistable content key for a specific key request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentKeySession"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVContentKeySession",
          "text": "AVContentKeySession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdatePersistableContentKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "forContentKeyIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySession(_:didUpdatePersistableContentKey:forContentKeyIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentKeySession:didUpdatePersistableContentKey:forContentKeyIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "contentKeySession(_:didUpdatePersistableContentKey:forContentKeyIdentifier:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysessiondelegate/contentkeysession(_:didupdatepersistablecontentkey:forcontentkeyidentifier:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySession(_:externalProtectionStatusDidChangeFor:)": {
      "abstract": [
        {
          "text": "Tells the delegate when external protection state has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentKeySession"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVContentKeySession",
          "text": "AVContentKeySession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "externalProtectionStatusDidChangeFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVContentKey",
          "text": "AVContentKey"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySession(_:externalProtectionStatusDidChangeFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentKeySession:externalProtectionStatusDidChangeForContentKey:"
        }
      ],
      "role": "symbol",
      "title": "contentKeySession(_:externalProtectionStatusDidChangeFor:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysessiondelegate/contentkeysession(_:externalprotectionstatusdidchangefor:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySession(_:shouldRetry:reason:)": {
      "abstract": [
        {
          "text": "Provides the receiver with a content key request object to retry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentKeySession"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVContentKeySession",
          "text": "AVContentKeySession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldRetry"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVContentKeyRequest",
          "text": "AVContentKeyRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "reason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVContentKeyRequest",
          "text": "AVContentKeyRequest"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVContentKeyRequestRetryReason",
          "text": "RetryReason"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySession(_:shouldRetry:reason:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentKeySession:shouldRetryContentKeyRequest:reason:"
        }
      ],
      "role": "symbol",
      "title": "contentKeySession(_:shouldRetry:reason:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysessiondelegate/contentkeysession(_:shouldretry:reason:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySessionContentProtectionSessionIdentifierDidChange(_:)": {
      "abstract": [
        {
          "text": "Tells the receiver the content protection session identifier changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentKeySessionContentProtectionSessionIdentifierDidChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVContentKeySession",
          "text": "AVContentKeySession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySessionContentProtectionSessionIdentifierDidChange(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentKeySessionContentProtectionSessionIdentifierDidChange:"
        }
      ],
      "role": "symbol",
      "title": "contentKeySessionContentProtectionSessionIdentifierDidChange(_:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysessiondelegate/contentkeysessioncontentprotectionsessionidentifierdidchange(_:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySessionDidGenerateExpiredSessionReport(_:)": {
      "abstract": [
        {
          "text": "Notifies the sender that an expired session report has been generated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentKeySessionDidGenerateExpiredSessionReport"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVContentKeySession",
          "text": "AVContentKeySession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySessionDidGenerateExpiredSessionReport(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentKeySessionDidGenerateExpiredSessionReport:"
        }
      ],
      "role": "symbol",
      "title": "contentKeySessionDidGenerateExpiredSessionReport(_:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysessiondelegate/contentkeysessiondidgenerateexpiredsessionreport(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSData": {
      "abstract": [
        {
          "text": "A static byte buffer that bridges to ; use  when you need reference semantics or other Foundation-specific behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSData"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSData",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSData",
      "type": "topic",
      "url": "/documentation/foundation/nsdata"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation4DataV": {
      "abstract": [
        {
          "text": "A byte buffer in memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DataV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Data",
      "type": "topic",
      "url": "/documentation/foundation/data"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Updating-and-Retrying-Content-Key-Requests",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySession(_:didProvide:forInitializationData:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySession(_:externalProtectionStatusDidChangeFor:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySession(_:shouldRetry:reason:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/RetryReason",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySessionContentProtectionSessionIdentifierDidChange(_:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySession(_:contentKeyRequest:didFailWithError:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySession(_:contentKeyRequestDidSucceed:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySessionDidGenerateExpiredSessionReport(_:)"
      ],
      "title": "Updating and Retrying Content Key Requests"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "contentKeySession:didUpdatePersistableContentKey:forContentKeyIdentifier:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "contentKeySession:didUpdatePersistableContentKey:forContentKeyIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Updating-and-Retrying-Content-Key-Requests",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySession(_:didProvide:forInitializationData:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySession(_:externalProtectionStatusDidChangeFor:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySession(_:shouldRetry:reason:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/RetryReason",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySessionContentProtectionSessionIdentifierDidChange(_:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySession(_:contentKeyRequest:didFailWithError:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySession(_:contentKeyRequestDidSucceed:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate/contentKeySessionDidGenerateExpiredSessionReport(_:)"
              ],
              "title": "Updating and Retrying Content Key Requests"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "contentKeySession:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AVContentKeySession",
                    "text": "AVContentKeySession"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "session"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "didUpdatePersistableContentKey:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSData",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSData",
                    "text": "NSData"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "persistableContentKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "forContentKeyIdentifier:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "keyword",
                    "text": "id"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "keyIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The content key session that is providing the updated persistable content key.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "session"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The updated persistent content key data. This data can be stored offline and used to answer future content key requests with the matching key identifier.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "persistableContentKey"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A container- and protocol-specific identifier for the updated persistent content key.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "keyIdentifier"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySessionDelegate~1contentKeySessionDidGenerateExpiredSessionReport(_:)/title",
          "value": "contentKeySessionDidGenerateExpiredSessionReport:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySessionDelegate~1contentKeySessionDidGenerateExpiredSessionReport(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "contentKeySessionDidGenerateExpiredSessionReport:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySessionDelegate~1contentKeySession(_:didUpdatePersistableContentKey:forContentKeyIdentifier:)/title",
          "value": "contentKeySession:didUpdatePersistableContentKey:forContentKeyIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySessionDelegate~1contentKeySession(_:didUpdatePersistableContentKey:forContentKeyIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "contentKeySession:didUpdatePersistableContentKey:forContentKeyIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySessionDelegate~1contentKeySession(_:shouldRetry:reason:)/title",
          "value": "contentKeySession:shouldRetryContentKeyRequest:reason:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySessionDelegate~1contentKeySession(_:shouldRetry:reason:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "contentKeySession:shouldRetryContentKeyRequest:reason:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySessionDelegate~1contentKeySession(_:externalProtectionStatusDidChangeFor:)/title",
          "value": "contentKeySession:externalProtectionStatusDidChangeForContentKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySessionDelegate~1contentKeySession(_:externalProtectionStatusDidChangeFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "contentKeySession:externalProtectionStatusDidChangeForContentKey:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySessionDelegate~1contentKeySession(_:contentKeyRequestDidSucceed:)/title",
          "value": "contentKeySession:contentKeyRequestDidSucceed:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySessionDelegate~1contentKeySession(_:contentKeyRequestDidSucceed:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "contentKeySession:contentKeyRequestDidSucceed:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySessionDelegate/title",
          "value": "AVContentKeySessionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySessionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeySessionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySessionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeySessionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession/title",
          "value": "AVContentKeySession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeySession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeySession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSData/abstract",
          "value": [
            {
              "text": "A static byte buffer in memory.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1RetryReason/title",
          "value": "AVContentKeyRequestRetryReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1RetryReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeyRequestRetryReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1RetryReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeyRequestRetryReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySessionDelegate~1contentKeySession(_:didProvide:forInitializationData:)/title",
          "value": "contentKeySession:didProvideContentKeyRequests:forInitializationData:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySessionDelegate~1contentKeySession(_:didProvide:forInitializationData:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "contentKeySession:didProvideContentKeyRequests:forInitializationData:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySessionDelegate~1contentKeySession(_:contentKeyRequest:didFailWithError:)/title",
          "value": "contentKeySession:contentKeyRequest:didFailWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySessionDelegate~1contentKeySession(_:contentKeyRequest:didFailWithError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "contentKeySession:contentKeyRequest:didFailWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySessionDelegate~1contentKeySessionContentProtectionSessionIdentifierDidChange(_:)/title",
          "value": "contentKeySessionContentProtectionSessionIdentifierDidChange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySessionDelegate~1contentKeySessionContentProtectionSessionIdentifierDidChange(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "contentKeySessionContentProtectionSessionIdentifierDidChange:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcontentkeysessiondelegate/contentkeysession(_:didupdatepersistablecontentkey:forcontentkeyidentifier:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcontentkeysessiondelegate/contentkeysession(_:didupdatepersistablecontentkey:forcontentkeyidentifier:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
