{
  "abstract": [
    {
      "text": "The y-axis direction of each particle is always fixed with respect to the point of view camera.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleOrientationMode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleOrientationMode/billboardYAligned"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SCNParticleOrientationMode@SCNParticleOrientationModeBillboardYAligned",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "billboardYAligned"
      }
    ],
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCNParticleOrientationModeBillboardYAligned"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SCNParticleOrientationMode.billboardYAligned"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "billboardYAligned"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this mode to allow each particle to rotate freely about its y-axis (as determined by the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleAngle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleAngularVelocity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties or the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/ParticleProperty/angle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key), but prevent it from rotating around any other axis.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleOrientationMode": {
      "abstract": [
        {
          "text": "Options for restricting the orientation of particles, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/orientationMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNParticleOrientationMode"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleOrientationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNParticleOrientationMode"
        }
      ],
      "role": "symbol",
      "title": "SCNParticleOrientationMode",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticleorientationmode"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleOrientationMode/billboardScreenAligned": {
      "abstract": [
        {
          "text": "Each particle’s orientation is always fixed with respect to the point of view camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "billboardScreenAligned"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleOrientationMode/billboardScreenAligned",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNParticleOrientationModeBillboardScreenAligned"
        }
      ],
      "role": "symbol",
      "title": "SCNParticleOrientationMode.billboardScreenAligned",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticleorientationmode/billboardscreenaligned"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleOrientationMode/billboardViewAligned": {
      "abstract": [
        {
          "text": "Each particle always faces the point of view camera (but may rotate about an axis parallel to the view direction).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "billboardViewAligned"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleOrientationMode/billboardViewAligned",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNParticleOrientationModeBillboardViewAligned"
        }
      ],
      "role": "symbol",
      "title": "SCNParticleOrientationMode.billboardViewAligned",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticleorientationmode/billboardviewaligned"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleOrientationMode/billboardYAligned": {
      "abstract": [
        {
          "text": "The y-axis direction of each particle is always fixed with respect to the point of view camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "billboardYAligned"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleOrientationMode/billboardYAligned",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNParticleOrientationModeBillboardYAligned"
        }
      ],
      "role": "symbol",
      "title": "SCNParticleOrientationMode.billboardYAligned",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticleorientationmode/billboardyaligned"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleOrientationMode/free": {
      "abstract": [
        {
          "text": "Particle orientations are not restricted; they may rotate freely in all axes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "free"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleOrientationMode/free",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNParticleOrientationModeFree"
        }
      ],
      "role": "symbol",
      "title": "SCNParticleOrientationMode.free",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticleorientationmode/free"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/ParticleProperty/angle": {
      "abstract": [
        {
          "text": "The rotation angle, in radians, of the particle about its axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "angle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNParticleSystem",
          "text": "SCNParticleSystem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNParticleProperty",
          "text": "ParticleProperty"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/ParticleProperty/angle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNParticlePropertyAngle"
        }
      ],
      "role": "symbol",
      "title": "angle",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/particleproperty/angle"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/orientationMode": {
      "abstract": [
        {
          "text": "The mode defining whether and how particles may rotate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orientationMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNParticleOrientationMode",
          "text": "SCNParticleOrientationMode"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/orientationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "orientationMode"
        }
      ],
      "role": "symbol",
      "title": "orientationMode",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/orientationmode"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleAngle": {
      "abstract": [
        {
          "text": "The rotation angle, in degrees, of newly spawned particles. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "particleAngle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleAngle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "particleAngle"
        }
      ],
      "role": "symbol",
      "title": "particleAngle",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/particleangle"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleAngularVelocity": {
      "abstract": [
        {
          "text": "The initial spin rate, in degrees per second, of newly spawned particles. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "particleAngularVelocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleSystem/particleAngularVelocity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "particleAngularVelocity"
        }
      ],
      "role": "symbol",
      "title": "particleAngularVelocity",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlesystem/particleangularvelocity"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleOrientationMode/billboardScreenAligned",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleOrientationMode/billboardViewAligned",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleOrientationMode/free"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCNParticleOrientationModeBillboardYAligned"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleOrientationModeBillboardYAligned"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.scenekit/documentation/SceneKit",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleOrientationMode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleOrientationMode/billboardScreenAligned",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleOrientationMode/billboardViewAligned",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleOrientationMode/free"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SCNParticleOrientationModeBillboardYAligned"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleOrientationMode~1billboardViewAligned/title",
          "value": "SCNParticleOrientationModeBillboardViewAligned"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleOrientationMode~1billboardViewAligned/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleOrientationModeBillboardViewAligned"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleOrientationMode~1free/title",
          "value": "SCNParticleOrientationModeFree"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleOrientationMode~1free/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleOrientationModeFree"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleOrientationMode~1billboardScreenAligned/title",
          "value": "SCNParticleOrientationModeBillboardScreenAligned"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleOrientationMode~1billboardScreenAligned/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleOrientationModeBillboardScreenAligned"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1ParticleProperty~1angle/title",
          "value": "SCNParticlePropertyAngle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1ParticleProperty~1angle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticlePropertyAngle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1particleAngularVelocity/title",
          "value": "particleAngularVelocity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1particleAngularVelocity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "particleAngularVelocity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1particleAngle/title",
          "value": "particleAngle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1particleAngle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "particleAngle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleOrientationMode/title",
          "value": "SCNParticleOrientationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleOrientationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleOrientationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleOrientationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleOrientationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleOrientationMode~1billboardYAligned/title",
          "value": "SCNParticleOrientationModeBillboardYAligned"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleOrientationMode~1billboardYAligned/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleOrientationModeBillboardYAligned"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1orientationMode/title",
          "value": "orientationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleSystem~1orientationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "orientationMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scnparticleorientationmode/billboardyaligned"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scnparticleorientationmode/billboardyaligned"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
