{
  "abstract": [
    {
      "text": "The default Smart Playlist that iTunes creates of the user’s music shows and movies.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMusicShowsAndMovies"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ITLibDistinguishedPlaylistKind@ITLibDistinguishedPlaylistKindMusicShowsAndMovies",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kindMusicShowsAndMovies"
      }
    ],
    "modules": [
      {
        "name": "iTunes Library"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ITLibDistinguishedPlaylistKindMusicShowsAndMovies"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ITLibDistinguishedPlaylistKind.kindMusicShowsAndMovies"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kindMusicShowsAndMovies"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary": {
      "abstract": [
        {
          "text": "Retrieve the properties of the media in the user’s iTunes library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "iTunes Library",
      "type": "topic",
      "url": "/documentation/ituneslibrary"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind": {
      "abstract": [
        {
          "text": "These constants specify the possible kinds of distinguished playlists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKind"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKind"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kind90sMusic": {
      "abstract": [
        {
          "text": "The default Smart Playlist that iTunes creates of the user’s music from the 1990s.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kind90sMusic"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kind90sMusic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKind90sMusic"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kind90sMusic",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kind90smusic"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindAudiobooks": {
      "abstract": [
        {
          "text": "The playlist contains all the audiobooks in the iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindAudiobooks"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindAudiobooks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindAudiobooks"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindAudiobooks",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindaudiobooks"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindBooks": {
      "abstract": [
        {
          "text": "The playlist contains all the audiobooks in the iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindBooks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ITLibDistinguishedPlaylistKind",
          "text": "ITLibDistinguishedPlaylistKind"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindBooks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindBooks"
        }
      ],
      "role": "symbol",
      "title": "kindBooks",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindbooks"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMovies": {
      "abstract": [
        {
          "text": "The playlist contains all the movies in the iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindMovies"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMovies",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindMovies"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindMovies",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindmovies"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMusic": {
      "abstract": [
        {
          "text": "The playlist contains all the music items in the iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindMusic"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMusic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindMusic"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindMusic",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindmusic"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMusicShowsAndMovies": {
      "abstract": [
        {
          "text": "The default Smart Playlist that iTunes creates of the user’s music shows and movies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindMusicShowsAndMovies"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMusicShowsAndMovies",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindMusicShowsAndMovies"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindMusicShowsAndMovies",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindmusicshowsandmovies"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMyTopRated": {
      "abstract": [
        {
          "text": "The default Smart Playlist that iTunes creates of the user’s top rated media items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindMyTopRated"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMyTopRated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindMyTopRated"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindMyTopRated",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindmytoprated"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindNone": {
      "abstract": [
        {
          "text": "The playlist isn’t a distinguished playlist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindNone"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindNone"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindNone",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindnone"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindPodcasts": {
      "abstract": [
        {
          "text": "The playlist contains all the podcasts in the iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindPodcasts"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindPodcasts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindPodcasts"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindPodcasts",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindpodcasts"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindPurchases": {
      "abstract": [
        {
          "text": "The playlist contains all the user’s purchases from the iTunes Store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindPurchases"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindPurchases",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindPurchases"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindPurchases",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindpurchases"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindRecentlyPlayed": {
      "abstract": [
        {
          "text": "The default Smart Playlist that iTunes creates of the user’s most recently played media items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindRecentlyPlayed"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindRecentlyPlayed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindRecentlyPlayed"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindRecentlyPlayed",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindrecentlyplayed"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindRingtones": {
      "abstract": [
        {
          "text": "The playlist contains all the iOS ringtones in the iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindRingtones"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindRingtones",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindRingtones"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindRingtones",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindringtones"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindTVShows": {
      "abstract": [
        {
          "text": "The playlist contains all the TV shows in the iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindTVShows"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindTVShows",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindTVShows"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindTVShows",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindtvshows"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindTop25MostPlayed": {
      "abstract": [
        {
          "text": "The default Smart Playlist that iTunes creates of the user’s 25 most played media items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindTop25MostPlayed"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindTop25MostPlayed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindTop25MostPlayed"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindTop25MostPlayed",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindtop25mostplayed"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindVoiceMemos": {
      "abstract": [
        {
          "text": "The playlist contains all the voice memos in the iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindVoiceMemos"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindVoiceMemos",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindVoiceMemos"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindVoiceMemos",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindvoicememos"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindiTunesU": {
      "abstract": [
        {
          "text": "The playlist contains all the user’s iTunes U items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindiTunesU"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindiTunesU",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibDistinguishedPlaylistKindiTunesU"
        }
      ],
      "role": "symbol",
      "title": "ITLibDistinguishedPlaylistKind.kindiTunesU",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kinditunesu"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Distinguished-Playlist-Kinds",
      "generated": true,
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindNone",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMovies",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindTVShows",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMusic",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindAudiobooks",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindBooks",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindRingtones",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindPodcasts",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindVoiceMemos",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindPurchases",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindiTunesU",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kind90sMusic",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMyTopRated",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindTop25MostPlayed",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindRecentlyPlayed"
      ],
      "title": "Distinguished Playlist Kinds"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ITLibDistinguishedPlaylistKindMusicShowsAndMovies"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindMusicShowsAndMovies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Distinguished-Playlist-Kinds",
              "generated": true,
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindNone",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMovies",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindTVShows",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMusic",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindAudiobooks",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindBooks",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindRingtones",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindPodcasts",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindVoiceMemos",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindPurchases",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindiTunesU",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kind90sMusic",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindMyTopRated",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindTop25MostPlayed",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibDistinguishedPlaylistKind/kindRecentlyPlayed"
              ],
              "title": "Distinguished Playlist Kinds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ITLibDistinguishedPlaylistKindMusicShowsAndMovies"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindRingtones/title",
          "value": "ITLibDistinguishedPlaylistKindRingtones"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindRingtones/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindRingtones"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind/title",
          "value": "ITLibDistinguishedPlaylistKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindVoiceMemos/title",
          "value": "ITLibDistinguishedPlaylistKindVoiceMemos"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindVoiceMemos/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindVoiceMemos"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindNone/title",
          "value": "ITLibDistinguishedPlaylistKindNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindTVShows/title",
          "value": "ITLibDistinguishedPlaylistKindTVShows"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindTVShows/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindTVShows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindPodcasts/title",
          "value": "ITLibDistinguishedPlaylistKindPodcasts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindPodcasts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindPodcasts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindAudiobooks/title",
          "value": "ITLibDistinguishedPlaylistKindAudiobooks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindAudiobooks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindAudiobooks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindPurchases/title",
          "value": "ITLibDistinguishedPlaylistKindPurchases"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindPurchases/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindPurchases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindTop25MostPlayed/title",
          "value": "ITLibDistinguishedPlaylistKindTop25MostPlayed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindTop25MostPlayed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindTop25MostPlayed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindMusicShowsAndMovies/title",
          "value": "ITLibDistinguishedPlaylistKindMusicShowsAndMovies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindMusicShowsAndMovies/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindMusicShowsAndMovies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindiTunesU/title",
          "value": "ITLibDistinguishedPlaylistKindiTunesU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindiTunesU/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindiTunesU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kind90sMusic/title",
          "value": "ITLibDistinguishedPlaylistKind90sMusic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kind90sMusic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKind90sMusic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindMusic/title",
          "value": "ITLibDistinguishedPlaylistKindMusic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindMusic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindMusic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindRecentlyPlayed/title",
          "value": "ITLibDistinguishedPlaylistKindRecentlyPlayed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindRecentlyPlayed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindRecentlyPlayed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindMyTopRated/title",
          "value": "ITLibDistinguishedPlaylistKindMyTopRated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindMyTopRated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindMyTopRated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindBooks/title",
          "value": "ITLibDistinguishedPlaylistKindBooks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindBooks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindBooks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindMovies/title",
          "value": "ITLibDistinguishedPlaylistKindMovies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibDistinguishedPlaylistKind~1kindMovies/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibDistinguishedPlaylistKindMovies"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindmusicshowsandmovies"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/ituneslibrary/itlibdistinguishedplaylistkind/kindmusicshowsandmovies"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
