{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The view that acts as the superview for the views involved in the transition.","type":"text"}],"metadata":{"externalID":"c:objc(pl)UIViewControllerContextTransitioning(py)containerView","required":true,"role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"containerView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"}],"roleHeading":"Instance Property","title":"containerView","platforms":[{"deprecated":false,"introducedAt":"2.0","beta":false,"name":"iOS","unavailable":false},{"deprecated":false,"introducedAt":"2.0","beta":false,"name":"iPadOS","unavailable":false},{"introducedAt":"13.1","beta":false,"name":"Mac Catalyst","unavailable":false,"deprecated":false},{"beta":false,"name":"tvOS","unavailable":false,"deprecated":false},{"introducedAt":"1.0","beta":false,"name":"visionOS","unavailable":false,"deprecated":false}],"navigatorTitle":[{"kind":"identifier","text":"containerView"}],"modules":[{"name":"UIKit"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning"]]},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/containerView","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"containerView","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIView","text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"inlineContent":[{"text":"The view that contains both views involved in the transition.","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"The container view acts as the superview of all other views (including those of the presenting and presented view controllers) during the animation sequence. UIKit sets this view for you and automatically adds the view of the presenting view controller to it. The animator object is responsible for adding the view of the presented view controller, and the animator object or presentation controller must use this view as the container for all other views involved in the transition."}],"type":"paragraph"}]}],"seeAlsoSections":[{"title":"Accessing the transition objects","generated":true,"anchor":"Accessing-the-transition-objects","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/viewController(forKey:)","doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/view(forKey:)"]}],"sections":[],"variants":[{"paths":["/documentation/uikit/uiviewcontrollercontexttransitioning/containerview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uiviewcontrollercontexttransitioning/containerview"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/viewController(forKey:)":{"title":"viewController(forKey:)","navigatorTitle":[{"text":"viewControllerForKey:","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/viewController(forKey:)","type":"topic","url":"/documentation/uikit/uiviewcontrollercontexttransitioning/viewcontroller(forkey:)","abstract":[{"type":"text","text":"Returns a view controller involved in the transition."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"viewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@UITransitionContextViewControllerKey","text":"UITransitionContextViewControllerKey","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"required":true,"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIViewControllerContextTransitioning","kind":"identifier"}],"url":"/documentation/uikit/uiviewcontrollercontexttransitioning","kind":"symbol","type":"topic","title":"UIViewControllerContextTransitioning","navigatorTitle":[{"text":"UIViewControllerContextTransitioning","kind":"identifier"}],"abstract":[{"text":"A set of methods that provide contextual information for transition animations between view controllers.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/containerView":{"type":"topic","required":true,"role":"symbol","abstract":[{"type":"text","text":"The view that acts as the superview for the views involved in the transition."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"containerView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/containerView","kind":"symbol","url":"/documentation/uikit/uiviewcontrollercontexttransitioning/containerview","title":"containerView","navigatorTitle":[{"text":"containerView","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/view(forKey:)":{"kind":"symbol","title":"view(forKey:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"view","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UITransitionContextViewKey","preciseIdentifier":"c:@T@UITransitionContextViewKey","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/view(forKey:)","type":"topic","navigatorTitle":[{"text":"viewForKey:","kind":"identifier"}],"url":"/documentation/uikit/uiviewcontrollercontexttransitioning/view(forkey:)","required":true,"abstract":[{"type":"text","text":"Returns the specified view involved in the transition."}]},"doc://com.apple.uikit/documentation/UIKit/UIView":{"title":"UIView","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIView","abstract":[{"text":"An object that manages the content for a rectangular area on the screen.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"UIView","kind":"identifier"}],"url":"/documentation/uikit/uiview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIView","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"value":[{"beta":false,"deprecated":false,"name":"iOS","unavailable":false},{"beta":false,"deprecated":false,"name":"iPadOS","unavailable":false},{"beta":false,"name":"Mac Catalyst","unavailable":false,"deprecated":false},{"beta":false,"name":"tvOS","unavailable":false,"deprecated":false},{"beta":false,"name":"visionOS","unavailable":false,"deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"containerView","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"containerView","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/viewController(forKey:)","doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/view(forKey:)"],"anchor":"Accessing-the-transition-objects","title":"Accessing the transition objects"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIView","text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"containerView","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning~1viewController(forKey:)/title","value":"viewControllerForKey:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning~1viewController(forKey:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewControllerForKey:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning/title","value":"UIViewControllerContextTransitioning","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning/fragments","value":[{"text":"UIViewControllerContextTransitioning","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning/navigatorTitle","value":[{"text":"UIViewControllerContextTransitioning","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning~1containerView/title","value":"containerView","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning~1containerView/fragments","value":[{"kind":"identifier","text":"containerView"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning~1view(forKey:)/title","value":"viewForKey:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning~1view(forKey:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewForKey:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/title","value":"UIView","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/fragments","op":"replace","value":[{"text":"UIView","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIView"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}