{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finalFrame","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"vc","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@S@CGRect","preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The view controller whose frame rectangle you want.","type":"text"}]}],"name":"vc"}]},{"content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"text":"The frame rectangle for the view or ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/coregraphics/cgrectzero","type":"reference"},{"text":" if the frame rectangle is not known or the view is not visible.","type":"text"}],"type":"paragraph"}],"kind":"content"},{"content":[{"text":"Discussion","level":2,"anchor":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"The rectangle returned by this method represents the size of the corresponding view at the end of the transition. For the view being covered during the presentation, the value returned by this method might be "},{"identifier":"doc://com.apple.documentation/documentation/coregraphics/cgrectzero","type":"reference","isActive":true},{"type":"text","text":" but it might also be a valid frame rectangle."}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/finalFrame(for:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uiviewcontrollercontexttransitioning/finalframe(for:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uiviewcontrollercontexttransitioning/finalframe(for:)"]}],"metadata":{"symbolKind":"method","externalID":"c:objc(pl)UIViewControllerContextTransitioning(im)finalFrameForViewController:","title":"finalFrame(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"}],"modules":[{"name":"UIKit"}],"role":"symbol","roleHeading":"Instance Method","platforms":[{"deprecated":false,"introducedAt":"2.0","name":"iOS","beta":false,"unavailable":false},{"deprecated":false,"introducedAt":"2.0","name":"iPadOS","beta":false,"unavailable":false},{"deprecated":false,"introducedAt":"13.1","name":"Mac Catalyst","beta":false,"unavailable":false},{"deprecated":false,"name":"tvOS","beta":false,"unavailable":false},{"deprecated":false,"introducedAt":"1.0","name":"visionOS","beta":false,"unavailable":false}],"required":true,"navigatorTitle":[{"text":"finalFrameForViewController:","kind":"identifier"}]},"abstract":[{"text":"Returns the ending frame rectangle for the specified view controller’s view.","type":"text"}],"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/initialFrame(for:)"],"title":"Getting the transition frame rectangles","anchor":"Getting-the-transition-frame-rectangles","generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/initialFrame(for:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/initialFrame(for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialFrame","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"}],"url":"/documentation/uikit/uiviewcontrollercontexttransitioning/initialframe(for:)","kind":"symbol","required":true,"abstract":[{"text":"Returns the starting frame rectangle for the specified view controller’s view.","type":"text"}],"navigatorTitle":[{"text":"initialFrameForViewController:","kind":"identifier"}],"type":"topic","title":"initialFrame(for:)","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.externally.resolved.symbol/c:@S@CGRect":{"identifier":"doc://com.externally.resolved.symbol/c:@S@CGRect","abstract":[{"text":"A structure that contains the location and dimensions of a rectangle.","type":"text"}],"title":"CGRect","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"CGRect"}],"role":"symbol","url":"/documentation/corefoundation/cgrect","kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/finalFrame(for:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/finalFrame(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"}],"url":"/documentation/uikit/uiviewcontrollercontexttransitioning/finalframe(for:)","kind":"symbol","required":true,"abstract":[{"type":"text","text":"Returns the ending frame rectangle for the specified view controller’s view."}],"navigatorTitle":[{"kind":"identifier","text":"finalFrameForViewController:"}],"type":"topic","title":"finalFrame(for:)","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIViewControllerContextTransitioning","kind":"identifier"}],"url":"/documentation/uikit/uiviewcontrollercontexttransitioning","kind":"symbol","type":"topic","title":"UIViewControllerContextTransitioning","navigatorTitle":[{"text":"UIViewControllerContextTransitioning","kind":"identifier"}],"abstract":[{"text":"A set of methods that provide contextual information for transition animations between view controllers.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning"},"doc://com.apple.documentation/documentation/coregraphics/cgrectzero":{"fragments":[{"text":"let ","kind":"text"},{"text":"CGRectZero","kind":"identifier"},{"text":": CGRect","kind":"text"}],"type":"topic","title":"CGRectZero","role":"symbol","abstract":[{"type":"text","text":"A rectangle constant with location `(0,0)`, and width and height of 0. The zero rectangle is equivalent to `CGRectMake(0,0,0,0)`."}],"identifier":"doc://com.apple.documentation/documentation/coregraphics/cgrectzero","url":"/documentation/coregraphics/cgrectzero","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIViewController":{"role":"symbol","kind":"symbol","url":"/documentation/uikit/uiviewcontroller","title":"UIViewController","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewController","navigatorTitle":[{"text":"UIViewController","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIViewController","kind":"identifier"}],"abstract":[{"text":"An object that manages a view hierarchy for your UIKit app.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"name":"iOS","beta":false,"deprecated":false},{"unavailable":false,"name":"iPadOS","beta":false,"deprecated":false},{"unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false},{"unavailable":false,"name":"tvOS","beta":false,"deprecated":false},{"unavailable":false,"name":"visionOS","beta":false,"deprecated":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"finalFrameForViewController:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"finalFrameForViewController:","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"anchor":"Getting-the-transition-frame-rectangles","title":"Getting the transition frame rectangles","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/initialFrame(for:)"],"generated":true}],"path":"/seeAlsoSections"},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","identifier":"doc://com.externally.resolved.symbol/c:@S@CGRect","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"finalFrameForViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"vc","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"}},{"op":"replace","value":{"parameters":[{"name":"vc","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view controller whose frame rectangle you want."}]}]}],"kind":"parameters"},"path":"/primaryContentSections/1"},{"path":"/primaryContentSections/2","op":"replace","value":{"content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The frame rectangle for the view or "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/coregraphics/cgrectzero"},{"type":"text","text":" if the frame rectangle is not known or the view is not visible."}]}],"kind":"content"}},{"op":"replace","value":"initialFrameForViewController:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning~1initialFrame(for:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initialFrameForViewController:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning~1initialFrame(for:)/fragments"},{"op":"replace","value":"finalFrameForViewController:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning~1finalFrame(for:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"finalFrameForViewController:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning~1finalFrame(for:)/fragments"},{"op":"replace","value":"UIViewControllerContextTransitioning","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIViewControllerContextTransitioning"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning/fragments"},{"op":"replace","value":[{"text":"UIViewControllerContextTransitioning","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning/navigatorTitle"},{"op":"replace","value":"UIViewController","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/title"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/fragments","value":[{"text":"UIViewController","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/navigatorTitle","value":[{"text":"UIViewController","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}