{"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/isInteractive","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"A Boolean value indicating whether the transition is currently interactive."}],"kind":"symbol","metadata":{"modules":[{"name":"UIKit"}],"title":"isInteractive","externalID":"c:objc(pl)UIViewControllerContextTransitioning(py)interactive","required":true,"platforms":[{"unavailable":false,"beta":false,"deprecated":false,"name":"iOS"},{"unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS"},{"unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst"},{"unavailable":false,"beta":false,"deprecated":false,"name":"tvOS"},{"unavailable":false,"beta":false,"deprecated":false,"name":"visionOS"}],"navigatorTitle":[{"kind":"identifier","text":"interactive"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInteractive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Property","role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isInteractive","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"Discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"A transition is interactive only if the view controller’s delegate provides a corresponding interactive animator object.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Interactive transitions are drive by user-generated events. One common scenario is to use a gesture recognizer to report on the current progress of the animation. The gesture recognizer calls methods of this context object that indicate the completion percentage of the transition or indicate that the transition was canceled or completed by the user.","type":"text"}]}],"kind":"content"}],"sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/isAnimated","doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/presentationStyle"],"anchor":"Getting-the-transition-behaviors","title":"Getting the transition behaviors","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uiviewcontrollercontexttransitioning/isinteractive"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uiviewcontrollercontexttransitioning/isinteractive"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning"]]},"references":{"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","url":"/documentation/Swift/Bool","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bool"}],"title":"Bool"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIViewControllerContextTransitioning","kind":"identifier"}],"url":"/documentation/uikit/uiviewcontrollercontexttransitioning","kind":"symbol","type":"topic","title":"UIViewControllerContextTransitioning","navigatorTitle":[{"text":"UIViewControllerContextTransitioning","kind":"identifier"}],"abstract":[{"text":"A set of methods that provide contextual information for transition animations between view controllers.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/isAnimated":{"required":true,"navigatorTitle":[{"text":"animated","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/isAnimated","title":"isAnimated","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isAnimated","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"/documentation/uikit/uiviewcontrollercontexttransitioning/isanimated","role":"symbol","type":"topic","abstract":[{"text":"A Boolean value indicating whether the transition should be animated.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"abstract":[{"text":"Type to represent a Boolean value.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","role":"symbol","url":"/documentation/objectivec/bool","kind":"symbol","type":"topic","title":"BOOL"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/isInteractive":{"required":true,"navigatorTitle":[{"text":"interactive","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/isInteractive","title":"isInteractive","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInteractive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"/documentation/uikit/uiviewcontrollercontexttransitioning/isinteractive","role":"symbol","type":"topic","abstract":[{"text":"A Boolean value indicating whether the transition is currently interactive.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/presentationStyle":{"required":true,"navigatorTitle":[{"text":"presentationStyle","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/presentationStyle","title":"presentationStyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIModalPresentationStyle","preciseIdentifier":"c:@E@UIModalPresentationStyle"}],"url":"/documentation/uikit/uiviewcontrollercontexttransitioning/presentationstyle","role":"symbol","type":"topic","abstract":[{"text":"Returns the presentation style for the view controller transition.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"name":"iOS","beta":false,"deprecated":false},{"unavailable":false,"name":"iPadOS","beta":false,"deprecated":false},{"unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false},{"deprecated":false,"name":"tvOS","beta":false,"unavailable":false},{"deprecated":false,"name":"visionOS","beta":false,"unavailable":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"interactive","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"interactive"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning"]]},"op":"replace","path":"/hierarchy"},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Getting the transition behaviors","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/isAnimated","doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning/presentationStyle"],"generated":true,"anchor":"Getting-the-transition-behaviors"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"getter"},{"kind":"text","text":"="},{"kind":"identifier","text":"isInteractive"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"interactive"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning/title","op":"replace","value":"UIViewControllerContextTransitioning"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning/fragments","op":"replace","value":[{"kind":"identifier","text":"UIViewControllerContextTransitioning"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning/navigatorTitle","value":[{"text":"UIViewControllerContextTransitioning","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning~1isAnimated/title","value":"animated","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning~1isAnimated/fragments","value":[{"text":"animated","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning~1isInteractive/title","value":"interactive","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning~1isInteractive/fragments","value":[{"kind":"identifier","text":"interactive"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning~1presentationStyle/title","value":"presentationStyle","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning~1presentationStyle/fragments","value":[{"text":"presentationStyle","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}