{
  "abstract": [
    {
      "text": "Returns the searchable attributes for the specified managed object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData",
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/attributeSet(for:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSCoreDataCoreSpotlightDelegate(im)attributeSetForObject:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "attributeSet"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSManagedObject",
        "text": "NSManagedObject"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CSSearchableItemAttributeSet",
        "text": "CSSearchableItemAttributeSet"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "attributeSetForObject:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "attributeSet(for:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "attributeSet"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "object"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSManagedObject",
              "text": "NSManagedObject"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)CSSearchableItemAttributeSet",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CSSearchableItemAttributeSet",
              "text": "CSSearchableItemAttributeSet"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The managed object to index.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "object"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreSpotlight/CSSearchableItemAttributeSet",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that provides the searchable item’s attributes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If you enable ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPropertyDescription/isIndexedBySpotlight",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " on a property description that describes a relationship, override this method and return the necessary set of attributes. Core Data doesn’t automatically infer indexable information for relationships.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "To prevent Core Spotlight from indexing a specific managed object, override this method and return ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " for that object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate": {
      "abstract": [
        {
          "text": "A set of methods that enable integration with Core Spotlight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCoreDataCoreSpotlightDelegate"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCoreDataCoreSpotlightDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSCoreDataCoreSpotlightDelegate",
      "type": "topic",
      "url": "/documentation/coredata/nscoredatacorespotlightdelegate"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/attributeSet(for:)": {
      "abstract": [
        {
          "text": "Returns the searchable attributes for the specified managed object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributeSet"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObject",
          "text": "NSManagedObject"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CSSearchableItemAttributeSet",
          "text": "CSSearchableItemAttributeSet"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/attributeSet(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attributeSetForObject:"
        }
      ],
      "role": "symbol",
      "title": "attributeSet(for:)",
      "type": "topic",
      "url": "/documentation/coredata/nscoredatacorespotlightdelegate/attributeset(for:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/deleteSpotlightIndex(completionHandler:)": {
      "abstract": [
        {
          "text": "Deletes all searchable items from the configured index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteSpotlightIndex"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/deleteSpotlightIndex(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deleteSpotlightIndexWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "deleteSpotlightIndex(completionHandler:)",
      "type": "topic",
      "url": "/documentation/coredata/nscoredatacorespotlightdelegate/deletespotlightindex(completionhandler:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/startSpotlightIndexing()": {
      "abstract": [
        {
          "text": "Starts the indexing of the store’s entities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startSpotlightIndexing"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/startSpotlightIndexing()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startSpotlightIndexing"
        }
      ],
      "role": "symbol",
      "title": "startSpotlightIndexing()",
      "type": "topic",
      "url": "/documentation/coredata/nscoredatacorespotlightdelegate/startspotlightindexing()"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/stopSpotlightIndexing()": {
      "abstract": [
        {
          "text": "Stops the indexing of the store’s entities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopSpotlightIndexing"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/stopSpotlightIndexing()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopSpotlightIndexing"
        }
      ],
      "role": "symbol",
      "title": "stopSpotlightIndexing()",
      "type": "topic",
      "url": "/documentation/coredata/nscoredatacorespotlightdelegate/stopspotlightindexing()"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObject": {
      "abstract": [
        {
          "text": "The base class that all Core Data model objects inherit from.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSManagedObject"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSManagedObject"
        }
      ],
      "role": "symbol",
      "title": "NSManagedObject",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobject"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPropertyDescription/isIndexedBySpotlight": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether Core Data adds the property’s value to the Core Spotlight index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isIndexedBySpotlight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPropertyDescription/isIndexedBySpotlight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indexedBySpotlight"
        }
      ],
      "role": "symbol",
      "title": "isIndexedBySpotlight",
      "type": "topic",
      "url": "/documentation/coredata/nspropertydescription/isindexedbyspotlight"
    },
    "doc://com.apple.documentation/documentation/CoreSpotlight/CSSearchableItemAttributeSet": {
      "abstract": [
        {
          "text": "The detailed metadata for a searchable item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSearchableItemAttributeSet"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreSpotlight/CSSearchableItemAttributeSet",
      "kind": "symbol",
      "role": "symbol",
      "title": "CSSearchableItemAttributeSet",
      "type": "topic",
      "url": "/documentation/CoreSpotlight/CSSearchableItemAttributeSet"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)CSSearchableItemAttributeSet": {
      "abstract": [
        {
          "text": "The detailed metadata for a searchable item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSearchableItemAttributeSet"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)CSSearchableItemAttributeSet",
      "kind": "symbol",
      "role": "symbol",
      "title": "CSSearchableItemAttributeSet",
      "type": "topic",
      "url": "/documentation/CoreSpotlight/CSSearchableItemAttributeSet"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-the-Index",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/deleteSpotlightIndex(completionHandler:)",
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/startSpotlightIndexing()",
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/stopSpotlightIndexing()"
      ],
      "title": "Managing the Index"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "attributeSetForObject:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "attributeSetForObject:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coredata/documentation/CoreData",
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-the-Index",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/deleteSpotlightIndex(completionHandler:)",
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/startSpotlightIndexing()",
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/stopSpotlightIndexing()"
              ],
              "title": "Managing the Index"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)CSSearchableItemAttributeSet",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CSSearchableItemAttributeSet",
                    "text": "CSSearchableItemAttributeSet"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "attributeSetForObject:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSManagedObject",
                    "text": "NSManagedObject"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "object"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The managed object to index.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "object"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "An instance of ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/CoreSpotlight/CSSearchableItemAttributeSet",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " that provides the searchable item’s attributes.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1deleteSpotlightIndex(completionHandler:)/title",
          "value": "deleteSpotlightIndexWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1deleteSpotlightIndex(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deleteSpotlightIndexWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)CSSearchableItemAttributeSet/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CSSearchableItemAttributeSet"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate/title",
          "value": "NSCoreDataCoreSpotlightDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCoreDataCoreSpotlightDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCoreDataCoreSpotlightDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPropertyDescription~1isIndexedBySpotlight/title",
          "value": "indexedBySpotlight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPropertyDescription~1isIndexedBySpotlight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "indexedBySpotlight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1stopSpotlightIndexing()/title",
          "value": "stopSpotlightIndexing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1stopSpotlightIndexing()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopSpotlightIndexing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1attributeSet(for:)/title",
          "value": "attributeSetForObject:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1attributeSet(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "attributeSetForObject:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObject/title",
          "value": "NSManagedObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreSpotlight~1CSSearchableItemAttributeSet/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CSSearchableItemAttributeSet"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1startSpotlightIndexing()/title",
          "value": "startSpotlightIndexing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1startSpotlightIndexing()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startSpotlightIndexing"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nscoredatacorespotlightdelegate/attributeset(for:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/nscoredatacorespotlightdelegate/attributeset(for:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
