{
  "abstract": [
    {
      "text": "The automatic animation that’s appropriate to the window type. This is the default.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum/default"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSWindowAnimationBehavior@NSWindowAnimationBehaviorDefault",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "`default`"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSWindowAnimationBehaviorDefault"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSWindow.AnimationBehavior.default"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "`default`"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow": {
      "abstract": [
        {
          "text": "A window that an app displays on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "role": "symbol",
      "title": "NSWindow",
      "type": "topic",
      "url": "/documentation/appkit/nswindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum": {
      "abstract": [
        {
          "text": "Constants that control the automatic window animation behavior windows use when ordering to the front or out of view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnimationBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnimationBehavior"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.AnimationBehavior",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/animationbehavior-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum/alertPanel": {
      "abstract": [
        {
          "text": "The animation behavior that’s appropriate to the alert window style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alertPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum/alertPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowAnimationBehaviorAlertPanel"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.AnimationBehavior.alertPanel",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/animationbehavior-swift.enum/alertpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum/default": {
      "abstract": [
        {
          "text": "The automatic animation that’s appropriate to the window type. This is the default.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowAnimationBehaviorDefault"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.AnimationBehavior.default",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/animationbehavior-swift.enum/default"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum/documentWindow": {
      "abstract": [
        {
          "text": "The animation behavior that’s appropriate to the document window style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentWindow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum/documentWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowAnimationBehaviorDocumentWindow"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.AnimationBehavior.documentWindow",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/animationbehavior-swift.enum/documentwindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum/none": {
      "abstract": [
        {
          "text": "No automatic animation used. This may be useful when you perform your own window animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowAnimationBehaviorNone"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.AnimationBehavior.none",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/animationbehavior-swift.enum/none"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum/utilityWindow": {
      "abstract": [
        {
          "text": "The animation behavior that’s appropriate to the utility window style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "utilityWindow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum/utilityWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowAnimationBehaviorUtilityWindow"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.AnimationBehavior.utilityWindow",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/animationbehavior-swift.enum/utilitywindow"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum/none",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum/documentWindow",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum/utilityWindow",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum/alertPanel"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSWindowAnimationBehaviorDefault"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowAnimationBehaviorDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum/none",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum/documentWindow",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum/utilityWindow",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/AnimationBehavior-swift.enum/alertPanel"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSWindowAnimationBehaviorDefault"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1AnimationBehavior-swift.enum~1alertPanel/title",
          "value": "NSWindowAnimationBehaviorAlertPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1AnimationBehavior-swift.enum~1alertPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowAnimationBehaviorAlertPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1AnimationBehavior-swift.enum~1none/title",
          "value": "NSWindowAnimationBehaviorNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1AnimationBehavior-swift.enum~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowAnimationBehaviorNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1AnimationBehavior-swift.enum~1default/title",
          "value": "NSWindowAnimationBehaviorDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1AnimationBehavior-swift.enum~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowAnimationBehaviorDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title",
          "value": "NSWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1AnimationBehavior-swift.enum~1utilityWindow/title",
          "value": "NSWindowAnimationBehaviorUtilityWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1AnimationBehavior-swift.enum~1utilityWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowAnimationBehaviorUtilityWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1AnimationBehavior-swift.enum/title",
          "value": "NSWindowAnimationBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1AnimationBehavior-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowAnimationBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1AnimationBehavior-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowAnimationBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1AnimationBehavior-swift.enum~1documentWindow/title",
          "value": "NSWindowAnimationBehaviorDocumentWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1AnimationBehavior-swift.enum~1documentWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowAnimationBehaviorDocumentWindow"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nswindow/animationbehavior-swift.enum/default"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nswindow/animationbehavior-swift.enum/default"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
