{
  "abstract": [
    {
      "text": "An object that represents a pass.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.walletpasses/documentation/WalletPasses"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "data",
    "url": "doc://com.apple.walletpasses/documentation/WalletPasses/Pass"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "data:WalletPasses:Pass",
    "fragments": [
      {
        "kind": "text",
        "text": "object "
      },
      {
        "kind": "identifier",
        "text": "Pass"
      }
    ],
    "modules": [
      {
        "name": "Wallet Passes"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Pass"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Object",
    "symbolKind": "dictionary",
    "title": "Pass"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "data"
          ],
          "platforms": [
            "Unsupported OS: iOS",
            "Unsupported OS: watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "Pass"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "items": [
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A URL that links to your accessiblity content, or the venue’s.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This key works only for poster event tickets.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "accessibilityURL",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A URL that can link to experiences that someone can add to the pass.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This key works only for poster event tickets.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "addOnURL",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A URL the system passes to the associated app from ",
                  "type": "text"
                },
                {
                  "code": "associatedStoreIdentifiers",
                  "type": "codeVoice"
                },
                {
                  "text": " during launch.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "The app receives this URL in the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:didFinishLaunchingWithOptions:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:open:options:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " methods of its app delegate.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This key isn’t supported for watchOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "appLaunchURL",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of App Store identifiers for apps associated with the pass. The associated app on a device is the first item in the array that’s compatible with that device.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "A link to launch the app is on the back of the pass. If the app isn’t installed, the link opens the App Store.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This key works only for payment passes.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This key isn’t supported for watchOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "associatedStoreIdentifiers",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "[number]"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of additional App Store identifiers for apps associated with the pass. The associated app on a device is the first item in the array that’s compatible with that device.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This key works only for poster event tickets. A link to launch the app is in the event guide of the pass. If the app isn’t installed, the link opens the App Store.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This key isn’t supported for watchOS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "auxiliaryStoreIdentifiers",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "[number]"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The authentication token to use with the web service in the ",
                  "type": "text"
                },
                {
                  "code": "webServiceURL",
                  "type": "codeVoice"
                },
                {
                  "text": " key.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "authenticationToken",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A background color for the pass, specified as a CSS-style RGB triple, such as ",
                  "type": "text"
                },
                {
                  "code": "rgb(23, 187, 82)",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "backgroundColor",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A URL that links to the bag policy of the venue for the event that the pass represents.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This key works only for poster event tickets.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "bagPolicyURL",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An object that represents a barcode on a pass.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This object is deprecated. Use ",
                  "type": "text"
                },
                {
                  "code": "barcodes",
                  "type": "codeVoice"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "barcode",
          "required": false,
          "type": [
            {
              "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/Barcode-data.dictionary",
              "kind": "typeIdentifier",
              "preciseIdentifier": "data:WalletPasses:Pass.Barcode",
              "text": "Pass.Barcode"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of objects that represent possible barcodes on a pass. The system uses the first displayable barcode for the device.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "barcodes",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "["
            },
            {
              "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/Barcodes-data.dictionary",
              "kind": "typeIdentifier",
              "preciseIdentifier": "data:WalletPasses:Pass.Barcodes",
              "text": "Pass.Barcodes"
            },
            {
              "kind": "text",
              "text": "]"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of objects that represent the identity of Bluetooth Low Energy beacons the system uses to show a relevant pass.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "beacons",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "["
            },
            {
              "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/Beacons-data.dictionary",
              "kind": "typeIdentifier",
              "preciseIdentifier": "data:WalletPasses:Pass.Beacons",
              "text": "Pass.Beacons"
            },
            {
              "kind": "text",
              "text": "]"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An object that contains the information for a boarding pass.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "boardingPass",
          "required": false,
          "type": [
            {
              "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/BoardingPass-data.dictionary",
              "kind": "typeIdentifier",
              "preciseIdentifier": "data:WalletPasses:Pass.BoardingPass",
              "text": "Pass.BoardingPass"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The preferred email address to contact the venue, event, or issuer.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This key works only for poster event tickets.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "contactVenueEmail",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The phone number for contacting the venue, event, or issuer.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This key works only for poster event tickets.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "contactVenuePhoneNumber",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A URL that links to the website of the venue, event, or issuer.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This key works only for poster event tickets.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "contactVenueWebsite",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An object that contains the information for a coupon.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "coupon",
          "required": false,
          "type": [
            {
              "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/Coupon-data.dictionary",
              "kind": "typeIdentifier",
              "preciseIdentifier": "data:WalletPasses:Pass.Coupon",
              "text": "Pass.Coupon"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A short description that iOS accessibility technologies use for a pass.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "description",
          "required": true,
          "type": [
            {
              "kind": "text",
              "text": "localizable string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A URL that links to directions for the event.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This key works only for poster event tickets.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "directionsInformationURL",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The text to display next to the logo on the pass.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This key works only for poster event tickets",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "eventLogoText",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "localizable string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An object that contains the information for an event ticket.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "eventTicket",
          "required": false,
          "type": [
            {
              "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/EventTicket-data.dictionary",
              "kind": "typeIdentifier",
              "preciseIdentifier": "data:WalletPasses:Pass.EventTicket",
              "text": "Pass.EventTicket"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The date and time the pass expires. The value needs to be a complete date that includes hours and minutes, and may optionally include seconds.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "expirationDate",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A background color for the footer of the pass, specified as a CSS-style RGB triple, such as ",
                  "type": "text"
                },
                {
                  "code": "rgb(100, 10, 110)",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This key works only for poster event tickets.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "footerBackgroundColor",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A foreground color for the pass, specified as a CSS-style RGB triple, such as ",
                  "type": "text"
                },
                {
                  "code": "rgb(100, 10, 110)",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "foregroundColor",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The version of the file format. The value needs to be ",
                  "type": "text"
                },
                {
                  "code": "1",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "formatVersion",
          "required": true,
          "type": [
            {
              "kind": "text",
              "text": "number"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An object that contains the information for a generic pass.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "generic",
          "required": false,
          "type": [
            {
              "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/Generic-data.dictionary",
              "kind": "typeIdentifier",
              "preciseIdentifier": "data:WalletPasses:Pass.Generic",
              "text": "Pass.Generic"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An identifier the system uses to group related boarding passes or event tickets. Wallet displays passes with the same ",
                  "type": "text"
                },
                {
                  "code": "groupingIdentifier",
                  "type": "codeVoice"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "code": "passTypeIdentifier",
                  "type": "codeVoice"
                },
                {
                  "text": ", and type as a group.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Use this identifier to group passes that are tightly related, such as boarding passes for different connections on the same trip.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "groupingIdentifier",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A color for the label text of the pass, specified as a CSS-style RGB triple, such as ",
                  "type": "text"
                },
                {
                  "code": "rgb(100, 10, 110)",
                  "type": "codeVoice"
                },
                {
                  "text": ". If you don’t provide a value, the system determines the label color.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "labelColor",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of up to 10 objects that represent geographic locations the system uses to show a relevant pass.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "locations",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "["
            },
            {
              "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/Locations-data.dictionary",
              "kind": "typeIdentifier",
              "preciseIdentifier": "data:WalletPasses:Pass.Locations",
              "text": "Pass.Locations"
            },
            {
              "kind": "text",
              "text": "]"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The text to display next to the logo on the pass.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This key doesn’t work for poster event tickets.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "logoText",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "localizable string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The maximum distance, in meters, from a location in the ",
                  "type": "text"
                },
                {
                  "code": "locations",
                  "type": "codeVoice"
                },
                {
                  "text": " array at which the pass is relevant. The system uses the smaller of this distance or the default distance.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "maxDistance",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "number"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A URL that links to a site for ordering merchandise for the event that the pass represents.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This key works only for poster event tickets.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "merchandiseURL",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An object that contains the information to use for Value-Added Services protocol transactions.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "nfc",
          "required": false,
          "type": [
            {
              "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/NFC-data.dictionary",
              "kind": "typeIdentifier",
              "preciseIdentifier": "data:WalletPasses:Pass.NFC",
              "text": "Pass.NFC"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A URL that links to the food ordering page for the event that the pass represents.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This key works only for poster event tickets.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "orderFoodURL",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The name of the organization.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "organizationName",
          "required": true,
          "type": [
            {
              "kind": "text",
              "text": "localizable string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A URL that links to parking information for the event that the pass represents.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This key works only for poster event tickets.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "parkingInformationURL",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The pass type identifier that’s registered with Apple. The value needs to be the same as the distribution certificate that signs the pass.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "passTypeIdentifier",
          "required": true,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of schemes to validate the pass with. The system validates the pass and its contents to ensure they meet the schemes’ requirements, falling back to the designed type if validation fails for all the provided schemes.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "preferredStyleSchemes",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "[string]"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A URL that links to a site to purchase parking for the event that the pass represents.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This key works only for poster event tickets.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "purchaseParkingURL",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The date and time when the pass becomes relevant, as a W3C timestamp, such as the start time of a movie. The value needs to be a complete date that includes hours and minutes, and may optionally include seconds.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "For information about the W3C timestamp format, see ",
                  "type": "text"
                },
                {
                  "identifier": "http://www.w3.org/TR/NOTE-datetime",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " on the W3C website.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This object is deprecated. Use ",
                  "type": "text"
                },
                {
                  "code": "relevantDates",
                  "type": "codeVoice"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "relevantDate",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of objects that represent date intervals that the system uses to show a relevant pass.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "relevantDates",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "["
            },
            {
              "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/RelevantDates-data.dictionary",
              "kind": "typeIdentifier",
              "preciseIdentifier": "data:WalletPasses:Pass.RelevantDates",
              "text": "Pass.RelevantDates"
            },
            {
              "kind": "text",
              "text": "]"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A URL that links to the selling flow for the ticket the pass represents.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This key works only for poster event tickets.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "sellURL",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An object that contains machine-readable metadata the system uses to offer a pass and suggest related actions. For example, setting Don’t Disturb mode for the duration of a movie.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "semantics",
          "required": false,
          "type": [
            {
              "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/SemanticTags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "data:WalletPasses:SemanticTags",
              "text": "SemanticTags"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An alphanumeric serial number. The combination of the serial number and pass type identifier needs to be unique for each pass.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "serialNumber",
          "required": true,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A Boolean value introduced in iOS 11 that controls whether to show the Share button on the back of a pass. A value of ",
                  "type": "text"
                },
                {
                  "code": "true",
                  "type": "codeVoice"
                },
                {
                  "text": " removes the button. The default value is ",
                  "type": "text"
                },
                {
                  "code": "false",
                  "type": "codeVoice"
                },
                {
                  "text": ". This flag has no effect in earlier versions of iOS, nor does it prevent sharing the pass in some other way.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "sharingProhibited",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "boolean"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An object that contains the information for a store card.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "storeCard",
          "required": false,
          "type": [
            {
              "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/StoreCard-data.dictionary",
              "kind": "typeIdentifier",
              "preciseIdentifier": "data:WalletPasses:Pass.StoreCard",
              "text": "Pass.StoreCard"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A Boolean value that controls whether to display the strip image without a shine effect. The default value is ",
                  "type": "text"
                },
                {
                  "code": "true",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "suppressStripShine",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "boolean"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A Boolean value that controls whether to display the header darkening gradient on poster event tickets. The default value is ",
                  "type": "text"
                },
                {
                  "code": "false",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This key works only for poster event tickets.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "suppressHeaderDarkening",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "boolean"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The Team ID for the Apple Developer Program account that registered the pass type identifier.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "teamIdentifier",
          "required": true,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A URL that links to the transferring flow for the ticket that the pass represents.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This key works only for poster event tickets.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "transferURL",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A URL that links to information about transit options in the area of the event that the pass represents.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This key works only for poster event tickets.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "transitInformationURL",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A Boolean value that controls whether Wallet computes the foreground and label color that the pass uses. The system derives the background color from the background image of the pass.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This key works only for poster event tickets.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This key ignores the values that ",
                  "type": "text"
                },
                {
                  "code": "foregroundColor",
                  "type": "codeVoice"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "labelColor",
                  "type": "codeVoice"
                },
                {
                  "text": " specify.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "useAutomaticColors",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "boolean"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A JSON dictionary that contains any custom information for companion apps. The data doesn’t appear to the user.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "For example, a pass for a cafe might include information about the customer’s favorite drink and sandwich in a machine-readable form. The companion app uses the data for placing an order for ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "the usual",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "userInfo",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "any JSON data"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A Boolean value that indicates that the pass is void, such as a redeemed, one-time-use coupon. The default value is ",
                  "type": "text"
                },
                {
                  "code": "false",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "voided",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "boolean"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The URL for a web service that you use to update or personalize the pass. The URL can include an optional port number.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "webServiceURL",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        }
      ],
      "kind": "properties",
      "title": "Properties"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.walletpasses/documentation/WalletPasses/supporting-semantic-tags-in-wallet-passes",
        "doc://com.apple.walletpasses/documentation/WalletPasses/showing-a-pass-on-the-lock-screen",
        "doc://com.apple.walletpasses/documentation/WalletPasses/distributing-and-updating-a-pass",
        "doc://com.apple.walletpasses/documentation/WalletPasses/creating-the-source-for-a-pass",
        "doc://com.apple.walletpasses/documentation/WalletPasses/building-a-pass",
        "doc://com.apple.walletpasses/documentation/WalletPasses/adding-a-web-service-to-update-passes"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:didFinishLaunchingWithOptions:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the launch process is almost done and the app is almost ready to run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "application"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "application"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFinishLaunchingWithOptions"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "launchOptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIApplicationLaunchOptionsKey",
          "text": "LaunchOptionsKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]? = nil) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:didFinishLaunchingWithOptions:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "application(_:didFinishLaunchingWithOptions:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIApplicationDelegate/application(_:didFinishLaunchingWithOptions:)"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:open:options:)": {
      "abstract": [
        {
          "text": "Asks the delegate to open a resource specified by a URL, and provides a dictionary of launch options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "application"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "app"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "open"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIApplicationOpenURLOptionsKey",
          "text": "OpenURLOptionsKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "] = [:]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:open:options:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "application(_:open:options:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIApplicationDelegate/application(_:open:options:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.walletpasses/documentation/WalletPasses": {
      "abstract": [
        {
          "text": "Create, distribute, and update passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses",
      "kind": "symbol",
      "role": "collection",
      "title": "Wallet Passes",
      "type": "topic",
      "url": "/documentation/walletpasses"
    },
    "doc://com.apple.walletpasses/documentation/WalletPasses/Pass": {
      "abstract": [
        {
          "text": "An object that represents a pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "Pass"
        }
      ],
      "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/Pass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pass"
        }
      ],
      "role": "symbol",
      "title": "Pass",
      "type": "topic",
      "url": "/documentation/walletpasses/pass"
    },
    "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/Barcode-data.dictionary": {
      "abstract": [
        {
          "text": "An object that represents a barcode shown on a pass.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "Pass.Barcode"
        }
      ],
      "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/Barcode-data.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pass.Barcode"
        }
      ],
      "role": "symbol",
      "title": "Pass.Barcode",
      "type": "topic",
      "url": "/documentation/walletpasses/pass/barcode-data.dictionary"
    },
    "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/Barcodes-data.dictionary": {
      "abstract": [
        {
          "text": "An object that represents a barcode on a pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "Pass.Barcodes"
        }
      ],
      "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/Barcodes-data.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pass.Barcodes"
        }
      ],
      "role": "symbol",
      "title": "Pass.Barcodes",
      "type": "topic",
      "url": "/documentation/walletpasses/pass/barcodes-data.dictionary"
    },
    "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/Beacons-data.dictionary": {
      "abstract": [
        {
          "text": "An object that represents the identifier of a Bluetooth Low Energy beacon the system uses to show a relevant pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "Pass.Beacons"
        }
      ],
      "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/Beacons-data.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pass.Beacons"
        }
      ],
      "role": "symbol",
      "title": "Pass.Beacons",
      "type": "topic",
      "url": "/documentation/walletpasses/pass/beacons-data.dictionary"
    },
    "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/BoardingPass-data.dictionary": {
      "abstract": [
        {
          "text": "An object that represents the groups of fields that display the information for a boarding pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "Pass.BoardingPass"
        }
      ],
      "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/BoardingPass-data.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pass.BoardingPass"
        }
      ],
      "role": "symbol",
      "title": "Pass.BoardingPass",
      "type": "topic",
      "url": "/documentation/walletpasses/pass/boardingpass-data.dictionary"
    },
    "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/Coupon-data.dictionary": {
      "abstract": [
        {
          "text": "An object that represents the groups of fields that display the information for a coupon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "Pass.Coupon"
        }
      ],
      "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/Coupon-data.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pass.Coupon"
        }
      ],
      "role": "symbol",
      "title": "Pass.Coupon",
      "type": "topic",
      "url": "/documentation/walletpasses/pass/coupon-data.dictionary"
    },
    "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/EventTicket-data.dictionary": {
      "abstract": [
        {
          "text": "An object that represents the groups of fields that display the information for an event ticket.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "Pass.EventTicket"
        }
      ],
      "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/EventTicket-data.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pass.EventTicket"
        }
      ],
      "role": "symbol",
      "title": "Pass.EventTicket",
      "type": "topic",
      "url": "/documentation/walletpasses/pass/eventticket-data.dictionary"
    },
    "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/Generic-data.dictionary": {
      "abstract": [
        {
          "text": "An object that represents the groups of fields that display the information for a generic pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "Pass.Generic"
        }
      ],
      "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/Generic-data.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pass.Generic"
        }
      ],
      "role": "symbol",
      "title": "Pass.Generic",
      "type": "topic",
      "url": "/documentation/walletpasses/pass/generic-data.dictionary"
    },
    "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/Locations-data.dictionary": {
      "abstract": [
        {
          "text": "An object that represents a location that the system uses to show a relevant pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "Pass.Locations"
        }
      ],
      "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/Locations-data.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pass.Locations"
        }
      ],
      "role": "symbol",
      "title": "Pass.Locations",
      "type": "topic",
      "url": "/documentation/walletpasses/pass/locations-data.dictionary"
    },
    "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/NFC-data.dictionary": {
      "abstract": [
        {
          "text": "An object that represents the near-field communication (NFC) payload the device passes to an Apple Pay terminal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "Pass.NFC"
        }
      ],
      "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/NFC-data.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pass.NFC"
        }
      ],
      "role": "symbol",
      "title": "Pass.NFC",
      "type": "topic",
      "url": "/documentation/walletpasses/pass/nfc-data.dictionary"
    },
    "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/RelevantDates-data.dictionary": {
      "abstract": [
        {
          "text": "An object that represents a date interval that the system uses to show a relevant pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "Pass.RelevantDates"
        }
      ],
      "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/RelevantDates-data.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pass.RelevantDates"
        }
      ],
      "role": "symbol",
      "title": "Pass.RelevantDates",
      "type": "topic",
      "url": "/documentation/walletpasses/pass/relevantdates-data.dictionary"
    },
    "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/StoreCard-data.dictionary": {
      "abstract": [
        {
          "text": "An object that represents groups of fields that show the information for a store card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "Pass.StoreCard"
        }
      ],
      "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/StoreCard-data.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pass.StoreCard"
        }
      ],
      "role": "symbol",
      "title": "Pass.StoreCard",
      "type": "topic",
      "url": "/documentation/walletpasses/pass/storecard-data.dictionary"
    },
    "doc://com.apple.walletpasses/documentation/WalletPasses/PassFieldContent": {
      "abstract": [
        {
          "text": "An object that represents the information to display in a field on a pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "PassFieldContent"
        }
      ],
      "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/PassFieldContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PassFieldContent"
        }
      ],
      "role": "symbol",
      "title": "PassFieldContent",
      "type": "topic",
      "url": "/documentation/walletpasses/passfieldcontent"
    },
    "doc://com.apple.walletpasses/documentation/WalletPasses/PassFields": {
      "abstract": [
        {
          "text": "An object that represents the groups of fields that display information on the front and back of a pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "PassFields"
        }
      ],
      "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/PassFields",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PassFields"
        }
      ],
      "role": "symbol",
      "title": "PassFields",
      "type": "topic",
      "url": "/documentation/walletpasses/passfields"
    },
    "doc://com.apple.walletpasses/documentation/WalletPasses/Personalize": {
      "abstract": [
        {
          "text": "An object that contains the personalization information for a rewards pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "Personalize"
        }
      ],
      "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/Personalize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Personalize"
        }
      ],
      "role": "symbol",
      "title": "Personalize",
      "type": "topic",
      "url": "/documentation/walletpasses/personalize"
    },
    "doc://com.apple.walletpasses/documentation/WalletPasses/SemanticTagType": {
      "abstract": [
        {
          "text": "A compilation of data object types for semantic tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "SemanticTagType"
        }
      ],
      "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/SemanticTagType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SemanticTagType"
        }
      ],
      "role": "symbol",
      "title": "SemanticTagType",
      "type": "topic",
      "url": "/documentation/walletpasses/semantictagtype"
    },
    "doc://com.apple.walletpasses/documentation/WalletPasses/SemanticTags": {
      "abstract": [
        {
          "text": "An object that contains machine-readable metadata the system uses to offer a pass and suggest related actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "SemanticTags"
        }
      ],
      "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/SemanticTags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SemanticTags"
        }
      ],
      "role": "symbol",
      "title": "SemanticTags",
      "type": "topic",
      "url": "/documentation/walletpasses/semantictags"
    },
    "doc://com.apple.walletpasses/documentation/WalletPasses/adding-a-web-service-to-update-passes": {
      "abstract": [
        {
          "text": "Implement a web server to register, update, and unregister a pass on a device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/adding-a-web-service-to-update-passes",
      "kind": "article",
      "role": "article",
      "title": "Adding a Web Service to Update Passes",
      "type": "topic",
      "url": "/documentation/walletpasses/adding-a-web-service-to-update-passes"
    },
    "doc://com.apple.walletpasses/documentation/WalletPasses/building-a-pass": {
      "abstract": [
        {
          "text": "Build a distributable pass.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/building-a-pass",
      "kind": "article",
      "role": "article",
      "title": "Building a Pass",
      "type": "topic",
      "url": "/documentation/walletpasses/building-a-pass"
    },
    "doc://com.apple.walletpasses/documentation/WalletPasses/creating-the-source-for-a-pass": {
      "abstract": [
        {
          "text": "Create the directory structure and add source files and images to define a pass.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/creating-the-source-for-a-pass",
      "kind": "article",
      "role": "article",
      "title": "Creating the Source for a Pass",
      "type": "topic",
      "url": "/documentation/walletpasses/creating-the-source-for-a-pass"
    },
    "doc://com.apple.walletpasses/documentation/WalletPasses/distributing-and-updating-a-pass": {
      "abstract": [
        {
          "text": "Distribute a pass to your users or update an existing pass.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/distributing-and-updating-a-pass",
      "kind": "article",
      "role": "article",
      "title": "Distributing and updating a pass",
      "type": "topic",
      "url": "/documentation/walletpasses/distributing-and-updating-a-pass"
    },
    "doc://com.apple.walletpasses/documentation/WalletPasses/showing-a-pass-on-the-lock-screen": {
      "abstract": [
        {
          "text": "Add information to your pass so the system can display it on the Lock Screen at a relevant time and place.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/showing-a-pass-on-the-lock-screen",
      "kind": "article",
      "role": "article",
      "title": "Showing a Pass on the Lock Screen",
      "type": "topic",
      "url": "/documentation/walletpasses/showing-a-pass-on-the-lock-screen"
    },
    "doc://com.apple.walletpasses/documentation/WalletPasses/supporting-semantic-tags-in-wallet-passes": {
      "abstract": [
        {
          "text": "Enable the system to offer suggestions for actions related to passes by adding machine-readable metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.walletpasses/documentation/WalletPasses/supporting-semantic-tags-in-wallet-passes",
      "kind": "article",
      "role": "article",
      "title": "Supporting semantic tags in Wallet passes",
      "type": "topic",
      "url": "/documentation/walletpasses/supporting-semantic-tags-in-wallet-passes"
    },
    "http://www.w3.org/TR/NOTE-datetime": {
      "identifier": "http://www.w3.org/TR/NOTE-datetime",
      "title": "Time and Date Formats",
      "titleInlineContent": [
        {
          "text": "Time and Date Formats",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://www.w3.org/TR/NOTE-datetime"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.walletpasses/documentation/WalletPasses/creating-the-source-for-a-pass",
        "doc://com.apple.walletpasses/documentation/WalletPasses/building-a-pass",
        "doc://com.apple.walletpasses/documentation/WalletPasses/distributing-and-updating-a-pass"
      ],
      "title": "Essentials"
    }
  ],
  "topicSections": [
    {
      "anchor": "Setting-the-pass-type",
      "identifiers": [
        "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/BoardingPass-data.dictionary",
        "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/Coupon-data.dictionary",
        "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/EventTicket-data.dictionary",
        "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/Generic-data.dictionary"
      ],
      "title": "Setting the pass type"
    },
    {
      "anchor": "Adding-content",
      "identifiers": [
        "doc://com.apple.walletpasses/documentation/WalletPasses/PassFields",
        "doc://com.apple.walletpasses/documentation/WalletPasses/PassFieldContent"
      ],
      "title": "Adding content"
    },
    {
      "anchor": "Adding-system-suggestions",
      "identifiers": [
        "doc://com.apple.walletpasses/documentation/WalletPasses/supporting-semantic-tags-in-wallet-passes",
        "doc://com.apple.walletpasses/documentation/WalletPasses/SemanticTags",
        "doc://com.apple.walletpasses/documentation/WalletPasses/SemanticTagType"
      ],
      "title": "Adding system suggestions"
    },
    {
      "anchor": "Adding-barcodes",
      "identifiers": [
        "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/Barcodes-data.dictionary",
        "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/Barcode-data.dictionary"
      ],
      "title": "Adding barcodes"
    },
    {
      "anchor": "Adding-relevance",
      "identifiers": [
        "doc://com.apple.walletpasses/documentation/WalletPasses/showing-a-pass-on-the-lock-screen",
        "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/Locations-data.dictionary",
        "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/Beacons-data.dictionary",
        "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/RelevantDates-data.dictionary"
      ],
      "title": "Adding relevance"
    },
    {
      "anchor": "Adding-near-field-communications",
      "identifiers": [
        "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/NFC-data.dictionary"
      ],
      "title": "Adding near-field communications"
    },
    {
      "anchor": "Adding-personalization-information",
      "identifiers": [
        "doc://com.apple.walletpasses/documentation/WalletPasses/Pass/StoreCard-data.dictionary",
        "doc://com.apple.walletpasses/documentation/WalletPasses/Personalize"
      ],
      "title": "Adding personalization information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didFinishLaunchingWithOptions:)/title",
          "value": "application:didFinishLaunchingWithOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didFinishLaunchingWithOptions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "application:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIApplication",
              "text": "UIApplication"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "application"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "didFinishLaunchingWithOptions:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSDictionary",
              "text": "NSDictionary<NSString *,id>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "launchOptions"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplicationDelegate~1application(_:open:options:)/title",
          "value": "application:openURL:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplicationDelegate~1application(_:open:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "application:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIApplication",
              "text": "UIApplication"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "app"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "openURL:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSURL",
              "text": "NSURL"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "url"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "options:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSDictionary",
              "text": "NSDictionary<NSString *,id>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/walletpasses/pass"
      ],
      "traits": [
        {
          "interfaceLanguage": "data"
        }
      ]
    }
  ]
}
