{
  "abstract": [
    {
      "text": "A state that indicates matching is done.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/didFinish"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTFontDescriptorMatchingState@kCTFontDescriptorMatchingDidFinish",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "didFinish"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCTFontDescriptorMatchingDidFinish"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CTFontDescriptorMatchingState.didFinish"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "didFinish"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState": {
      "abstract": [
        {
          "text": "Constants that track the progress of font descriptor matching.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontDescriptorMatchingState"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontDescriptorMatchingState"
        }
      ],
      "role": "symbol",
      "title": "CTFontDescriptorMatchingState",
      "type": "topic",
      "url": "/documentation/coretext/ctfontdescriptormatchingstate"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/didBegin": {
      "abstract": [
        {
          "text": "A state that indicates matching is about to begin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didBegin"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/didBegin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontDescriptorMatchingDidBegin"
        }
      ],
      "role": "symbol",
      "title": "CTFontDescriptorMatchingState.didBegin",
      "type": "topic",
      "url": "/documentation/coretext/ctfontdescriptormatchingstate/didbegin"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/didFailWithError": {
      "abstract": [
        {
          "text": "A state that indicates an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didFailWithError"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/didFailWithError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontDescriptorMatchingDidFailWithError"
        }
      ],
      "role": "symbol",
      "title": "CTFontDescriptorMatchingState.didFailWithError",
      "type": "topic",
      "url": "/documentation/coretext/ctfontdescriptormatchingstate/didfailwitherror"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/didFinish": {
      "abstract": [
        {
          "text": "A state that indicates matching is done.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didFinish"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/didFinish",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontDescriptorMatchingDidFinish"
        }
      ],
      "role": "symbol",
      "title": "CTFontDescriptorMatchingState.didFinish",
      "type": "topic",
      "url": "/documentation/coretext/ctfontdescriptormatchingstate/didfinish"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/didFinishDownloading": {
      "abstract": [
        {
          "text": "A state that indicates downloading is done.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didFinishDownloading"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/didFinishDownloading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontDescriptorMatchingDidFinishDownloading"
        }
      ],
      "role": "symbol",
      "title": "CTFontDescriptorMatchingState.didFinishDownloading",
      "type": "topic",
      "url": "/documentation/coretext/ctfontdescriptormatchingstate/didfinishdownloading"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/didMatch": {
      "abstract": [
        {
          "text": "A state that indicates the font descriptor match is successful.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didMatch"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/didMatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontDescriptorMatchingDidMatch"
        }
      ],
      "role": "symbol",
      "title": "CTFontDescriptorMatchingState.didMatch",
      "type": "topic",
      "url": "/documentation/coretext/ctfontdescriptormatchingstate/didmatch"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/downloading": {
      "abstract": [
        {
          "text": "A state that indicates downloading is in progress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downloading"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/downloading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontDescriptorMatchingDownloading"
        }
      ],
      "role": "symbol",
      "title": "CTFontDescriptorMatchingState.downloading",
      "type": "topic",
      "url": "/documentation/coretext/ctfontdescriptormatchingstate/downloading"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/stalled": {
      "abstract": [
        {
          "text": "A state that indicates that matching is stalled, such as while waiting for a server response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stalled"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/stalled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontDescriptorMatchingStalled"
        }
      ],
      "role": "symbol",
      "title": "CTFontDescriptorMatchingState.stalled",
      "type": "topic",
      "url": "/documentation/coretext/ctfontdescriptormatchingstate/stalled"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/willBeginDownloading": {
      "abstract": [
        {
          "text": "A state that indicates downloading is about to begin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willBeginDownloading"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/willBeginDownloading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontDescriptorMatchingWillBeginDownloading"
        }
      ],
      "role": "symbol",
      "title": "CTFontDescriptorMatchingState.willBeginDownloading",
      "type": "topic",
      "url": "/documentation/coretext/ctfontdescriptormatchingstate/willbegindownloading"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/willBeginQuerying": {
      "abstract": [
        {
          "text": "A state that indicates communication with the server is about to begin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willBeginQuerying"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/willBeginQuerying",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontDescriptorMatchingWillBeginQuerying"
        }
      ],
      "role": "symbol",
      "title": "CTFontDescriptorMatchingState.willBeginQuerying",
      "type": "topic",
      "url": "/documentation/coretext/ctfontdescriptormatchingstate/willbeginquerying"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/didBegin",
        "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/willBeginQuerying",
        "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/stalled",
        "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/willBeginDownloading",
        "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/downloading",
        "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/didFinishDownloading",
        "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/didMatch",
        "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/didFailWithError"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCTFontDescriptorMatchingDidFinish"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontDescriptorMatchingDidFinish"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText",
                "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/didBegin",
                "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/willBeginQuerying",
                "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/stalled",
                "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/willBeginDownloading",
                "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/downloading",
                "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/didFinishDownloading",
                "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/didMatch",
                "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState/didFailWithError"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCTFontDescriptorMatchingDidFinish"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState~1willBeginDownloading/title",
          "value": "kCTFontDescriptorMatchingWillBeginDownloading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState~1willBeginDownloading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontDescriptorMatchingWillBeginDownloading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState/title",
          "value": "CTFontDescriptorMatchingState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontDescriptorMatchingState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontDescriptorMatchingState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState~1didFinish/title",
          "value": "kCTFontDescriptorMatchingDidFinish"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState~1didFinish/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontDescriptorMatchingDidFinish"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState~1downloading/title",
          "value": "kCTFontDescriptorMatchingDownloading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState~1downloading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontDescriptorMatchingDownloading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState~1didFinishDownloading/title",
          "value": "kCTFontDescriptorMatchingDidFinishDownloading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState~1didFinishDownloading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontDescriptorMatchingDidFinishDownloading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState~1didMatch/title",
          "value": "kCTFontDescriptorMatchingDidMatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState~1didMatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontDescriptorMatchingDidMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState~1willBeginQuerying/title",
          "value": "kCTFontDescriptorMatchingWillBeginQuerying"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState~1willBeginQuerying/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontDescriptorMatchingWillBeginQuerying"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState~1didBegin/title",
          "value": "kCTFontDescriptorMatchingDidBegin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState~1didBegin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontDescriptorMatchingDidBegin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState~1didFailWithError/title",
          "value": "kCTFontDescriptorMatchingDidFailWithError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState~1didFailWithError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontDescriptorMatchingDidFailWithError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState~1stalled/title",
          "value": "kCTFontDescriptorMatchingStalled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState~1stalled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontDescriptorMatchingStalled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctfontdescriptormatchingstate/didfinish"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctfontdescriptormatchingstate/didfinish"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
