{
  "abstract": [
    {
      "text": "Sent when the user taps Save or Cancel. If the user tapped Save, the current address book has been saved to the Address Book database.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbookui/documentation/AddressBookUI",
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABNewPersonViewControllerDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABNewPersonViewControllerDelegate/newPersonViewController(_:didCompleteWithNewPerson:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)ABNewPersonViewControllerDelegate(im)newPersonViewController:didCompleteWithNewPerson:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "newPersonViewController"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ABNewPersonViewController",
        "text": "ABNewPersonViewController"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "didCompleteWithNewPerson"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@ABRecordRef",
        "text": "ABRecord"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "Address Book UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "newPersonViewController:didCompleteWithNewPerson:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "newPersonViewController(_:didCompleteWithNewPerson:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "newPersonViewController"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "newPersonView"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABNewPersonViewController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ABNewPersonViewController",
              "text": "ABNewPersonViewController"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "didCompleteWithNewPerson"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "person"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@ABRecordRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ABRecordRef",
              "text": "ABRecord"
            },
            {
              "kind": "text",
              "text": "?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On Save, the newly created (and saved) person record.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "On Cancel, ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "person"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the user tapped Save, pending changes in the current address book (",
              "type": "text"
            },
            {
              "code": "ABAddressBook",
              "type": "codeVoice"
            },
            {
              "text": ") have been saved by the time this message is sent to the receiver.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The receiver must dismiss ",
              "type": "text"
            },
            {
              "code": "newPersonViewController",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.addressbookui/documentation/AddressBookUI": {
      "abstract": [
        {
          "text": "Access users’ contacts and display them in a graphical interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book UI",
      "type": "topic",
      "url": "/documentation/addressbookui"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABNewPersonViewController": {
      "abstract": [
        {
          "text": "A view controller presenting an interface to create a contact.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABNewPersonViewController"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABNewPersonViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABNewPersonViewController"
        }
      ],
      "role": "symbol",
      "title": "ABNewPersonViewController",
      "type": "topic",
      "url": "/documentation/addressbookui/abnewpersonviewcontroller"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABNewPersonViewControllerDelegate": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "ABNewPersonViewControllerDelegate",
          "type": "codeVoice"
        },
        {
          "text": " protocol declares the interface that ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABNewPersonViewController",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " delegates must implement.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABNewPersonViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABNewPersonViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABNewPersonViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "ABNewPersonViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/addressbookui/abnewpersonviewcontrollerdelegate"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABNewPersonViewControllerDelegate/newPersonViewController(_:didCompleteWithNewPerson:)": {
      "abstract": [
        {
          "text": "Sent when the user taps Save or Cancel. If the user tapped Save, the current address book has been saved to the Address Book database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "newPersonViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABNewPersonViewController",
          "text": "ABNewPersonViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didCompleteWithNewPerson"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABNewPersonViewControllerDelegate/newPersonViewController(_:didCompleteWithNewPerson:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newPersonViewController:didCompleteWithNewPerson:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "newPersonViewController(_:didCompleteWithNewPerson:)",
      "type": "topic",
      "url": "/documentation/addressbookui/abnewpersonviewcontrollerdelegate/newpersonviewcontroller(_:didcompletewithnewperson:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@ABRecordRef": {
      "abstract": [
        {
          "text": "A reference to an ABRecord object or any of its derivedopaque types.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@ABRecordRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABRecord",
      "type": "topic",
      "url": "/documentation/AddressBook/ABRecord-swift.typealias"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "newPersonViewController:didCompleteWithNewPerson:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newPersonViewController:didCompleteWithNewPerson:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.addressbookui/documentation/AddressBookUI",
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABNewPersonViewControllerDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "newPersonViewController:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABNewPersonViewController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)ABNewPersonViewController",
                    "text": "ABNewPersonViewController"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "newPersonView"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "didCompleteWithNewPerson:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@ABRecordRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@ABRecordRef",
                    "text": "ABRecordRef"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "person"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "On Save, the newly created (and saved) person record.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "On Cancel, ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "person"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABNewPersonViewControllerDelegate~1newPersonViewController(_:didCompleteWithNewPerson:)/title",
          "value": "newPersonViewController:didCompleteWithNewPerson:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABNewPersonViewControllerDelegate~1newPersonViewController(_:didCompleteWithNewPerson:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newPersonViewController:didCompleteWithNewPerson:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABNewPersonViewControllerDelegate/title",
          "value": "ABNewPersonViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABNewPersonViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABNewPersonViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABNewPersonViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABNewPersonViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@ABRecordRef/title",
          "value": "ABRecordRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@ABRecordRef/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFTypeRef",
              "text": "CFTypeRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ABRecordRef"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABNewPersonViewController/title",
          "value": "ABNewPersonViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABNewPersonViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABNewPersonViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABNewPersonViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABNewPersonViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbookui/abnewpersonviewcontrollerdelegate/newpersonviewcontroller(_:didcompletewithnewperson:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbookui/abnewpersonviewcontrollerdelegate/newpersonviewcontroller(_:didcompletewithnewperson:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
