{"metadata":{"title":"delegate()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":"() -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"platforms":[{"deprecated":false,"beta":false,"introducedAt":"10.3","name":"macOS","unavailable":false}],"externalID":"c:objc(cs)SFAuthorizationView(im)delegate","symbolKind":"method","modules":[{"name":"Security Interface"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":"() -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!"}]}]}],"seeAlsoSections":[{"title":"Setting and getting the delegate for the view","identifiers":["doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationView/setDelegate(_:)"],"generated":true,"anchor":"Setting-and-getting-the-delegate-for-the-view"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.securityinterface/documentation/SecurityInterface","doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationView"]]},"abstract":[{"type":"text","text":"Returns the delegate for this view."}],"identifier":{"url":"doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationView/delegate()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/securityinterface/sfauthorizationview/delegate()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/securityinterface/sfauthorizationview/delegate()"]}],"references":{"doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationView":{"navigatorTitle":[{"kind":"identifier","text":"SFAuthorizationView"}],"url":"/documentation/securityinterface/sfauthorizationview","kind":"symbol","title":"SFAuthorizationView","abstract":[{"type":"text","text":"The class responsible for displaying a lock icon that can be used to indicate that a user interface has restricted access."}],"identifier":"doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SFAuthorizationView"}],"type":"topic","role":"symbol"},"doc://com.apple.securityinterface/documentation/SecurityInterface":{"abstract":[{"text":"Provide user interface elements for security features such as authorization, access to digital certificates, and access to items in keychains.","type":"text"}],"role":"collection","title":"Security Interface","url":"/documentation/securityinterface","identifier":"doc://com.apple.securityinterface/documentation/SecurityInterface","type":"topic","kind":"symbol"},"doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationView/setDelegate(_:)":{"url":"/documentation/securityinterface/sfauthorizationview/setdelegate(_:)","kind":"symbol","type":"topic","identifier":"doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationView/setDelegate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDelegate"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!)"}],"title":"setDelegate(_:)","abstract":[{"type":"text","text":"Sets the delegate for this authorization view."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setDelegate:"}]},"doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationView/delegate()":{"identifier":"doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationView/delegate()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":"() -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"kind":"symbol","abstract":[{"text":"Returns the delegate for this view.","type":"text"}],"title":"delegate()","url":"/documentation/securityinterface/sfauthorizationview/delegate()","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"text":"","type":"text"}],"role":"overview","title":"Technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","kind":"technologies"},"doc://com.externally.resolved.symbol/s:ScM":{"fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","url":"/documentation/Swift/MainActor","kind":"symbol","type":"topic","abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"role":"symbol","title":"MainActor"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"path":"/metadata/platforms","op":"replace","value":[{"introducedAt":"10.3","unavailable":false,"name":"macOS","beta":false,"deprecated":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"delegate"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"delegate"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.securityinterface/documentation/SecurityInterface","doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationView"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"anchor":"Setting-and-getting-the-delegate-for-the-view","title":"Setting and getting the delegate for the view","identifiers":["doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationView/setDelegate(_:)"],"generated":true}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"value":"SFAuthorizationView","op":"replace","path":"/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationView/title"},{"value":[{"text":"SFAuthorizationView","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationView/fragments"},{"value":[{"kind":"identifier","text":"SFAuthorizationView"}],"op":"replace","path":"/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationView/navigatorTitle"},{"value":"setDelegate:","path":"/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationView~1setDelegate(_:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"setDelegate:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationView~1setDelegate(_:)/fragments","op":"replace"},{"value":"delegate","path":"/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationView~1delegate()/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"delegate"}],"path":"/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationView~1delegate()/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}