{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.securityinterface/documentation/SecurityInterface","doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationView"]]},"abstract":[{"text":"Sets the delegate for this authorization view.","type":"text"}],"seeAlsoSections":[{"identifiers":["doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationView/delegate()"],"generated":true,"anchor":"Setting-and-getting-the-delegate-for-the-view","title":"Setting and getting the delegate for the view"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/securityinterface/sfauthorizationview/setdelegate(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/securityinterface/sfauthorizationview/setdelegate(_:)"]}],"kind":"symbol","identifier":{"url":"doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationView/setDelegate(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDelegate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!)"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The object to which messages about the state of the authorization object should be sent."}]}],"name":"delegate"}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you want to be notified of state changes (for example, when the user clicks the button), set a delegate and implement the delegate methods described in the delegate methods section."}]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"Security Interface"}],"externalID":"c:objc(cs)SFAuthorizationView(im)setDelegate:","symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"!)","kind":"text"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"setDelegate:","kind":"identifier"}],"platforms":[{"unavailable":false,"introducedAt":"10.3","name":"macOS","deprecated":false,"beta":false}],"title":"setDelegate(_:)"},"references":{"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"text":"","type":"text"}],"role":"overview","title":"Technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","kind":"technologies"},"doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationView/setDelegate(_:)":{"url":"/documentation/securityinterface/sfauthorizationview/setdelegate(_:)","kind":"symbol","type":"topic","identifier":"doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationView/setDelegate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDelegate"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!)"}],"title":"setDelegate(_:)","abstract":[{"type":"text","text":"Sets the delegate for this authorization view."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setDelegate:"}]},"doc://com.apple.securityinterface/documentation/SecurityInterface":{"abstract":[{"text":"Provide user interface elements for security features such as authorization, access to digital certificates, and access to items in keychains.","type":"text"}],"role":"collection","title":"Security Interface","url":"/documentation/securityinterface","identifier":"doc://com.apple.securityinterface/documentation/SecurityInterface","type":"topic","kind":"symbol"},"doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationView/delegate()":{"identifier":"doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationView/delegate()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":"() -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"kind":"symbol","abstract":[{"text":"Returns the delegate for this view.","type":"text"}],"title":"delegate()","url":"/documentation/securityinterface/sfauthorizationview/delegate()","role":"symbol"},"doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationView":{"navigatorTitle":[{"kind":"identifier","text":"SFAuthorizationView"}],"url":"/documentation/securityinterface/sfauthorizationview","kind":"symbol","title":"SFAuthorizationView","abstract":[{"type":"text","text":"The class responsible for displaying a lock icon that can be used to indicate that a user interface has restricted access."}],"identifier":"doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SFAuthorizationView"}],"type":"topic","role":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","url":"/documentation/Swift/MainActor","kind":"symbol","type":"topic","abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"role":"symbol","title":"MainActor"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"name":"macOS","beta":false,"deprecated":false,"introducedAt":"10.3"}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"setDelegate:","path":"/metadata/title","op":"replace"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"setDelegate:","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.securityinterface/documentation/SecurityInterface","doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationView"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationView/delegate()"],"anchor":"Setting-and-getting-the-delegate-for-the-view","title":"Setting and getting the delegate for the view","generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setDelegate:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["macOS"]}]}},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The object to which messages about the state of the authorization object should be sent.","type":"text"}]}],"name":"delegate"}]},"op":"replace","path":"/primaryContentSections/1"},{"op":"replace","path":"/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationView~1setDelegate(_:)/title","value":"setDelegate:"},{"op":"replace","path":"/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationView~1setDelegate(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDelegate:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationView~1delegate()/title","value":"delegate"},{"op":"replace","path":"/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationView~1delegate()/fragments","value":[{"text":"- ","kind":"text"},{"text":"delegate","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationView/title","value":"SFAuthorizationView"},{"op":"replace","path":"/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationView/fragments","value":[{"kind":"identifier","text":"SFAuthorizationView"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationView/navigatorTitle","value":[{"kind":"identifier","text":"SFAuthorizationView"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}