{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iosurface/documentation/IOSurface",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/chromaRed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@IOSurfaceComponentName@kIOSurfaceComponentNameChromaRed",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "chromaRed"
      }
    ],
    "modules": [
      {
        "name": "IOSurface"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kIOSurfaceComponentNameChromaRed"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "IOSurfaceComponentName.chromaRed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "chromaRed"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iosurface/documentation/IOSurface": {
      "abstract": [
        {
          "text": "Share hardware-accelerated buffer data (framebuffers and textures) across multiple processes. Manage image memory more efficiently.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface",
      "kind": "symbol",
      "role": "collection",
      "title": "IOSurface",
      "type": "topic",
      "url": "/documentation/iosurface"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfaceComponentName"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfaceComponentName"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceComponentName",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacecomponentname"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/alpha": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alpha"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/alpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceComponentNameAlpha"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceComponentName.alpha",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacecomponentname/alpha"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/blue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "blue"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/blue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceComponentNameBlue"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceComponentName.blue",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacecomponentname/blue"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/chromaBlue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "chromaBlue"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/chromaBlue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceComponentNameChromaBlue"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceComponentName.chromaBlue",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacecomponentname/chromablue"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/chromaRed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "chromaRed"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/chromaRed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceComponentNameChromaRed"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceComponentName.chromaRed",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacecomponentname/chromared"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/green": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "green"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/green",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceComponentNameGreen"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceComponentName.green",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacecomponentname/green"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/luma": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "luma"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/luma",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceComponentNameLuma"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceComponentName.luma",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacecomponentname/luma"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/red": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "red"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/red",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceComponentNameRed"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceComponentName.red",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacecomponentname/red"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/unknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfaceComponentNameUnknown"
        }
      ],
      "role": "symbol",
      "title": "IOSurfaceComponentName.unknown",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacecomponentname/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/alpha",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/blue",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/chromaBlue",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/green",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/luma",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/red",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/unknown"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kIOSurfaceComponentNameChromaRed"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceComponentNameChromaRed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iosurface/documentation/IOSurface",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/alpha",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/blue",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/chromaBlue",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/green",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/luma",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/red",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfaceComponentName/unknown"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kIOSurfaceComponentNameChromaRed"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceComponentName~1chromaBlue/title",
          "value": "kIOSurfaceComponentNameChromaBlue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceComponentName~1chromaBlue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceComponentNameChromaBlue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceComponentName~1green/title",
          "value": "kIOSurfaceComponentNameGreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceComponentName~1green/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceComponentNameGreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceComponentName~1unknown/title",
          "value": "kIOSurfaceComponentNameUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceComponentName~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceComponentNameUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceComponentName~1blue/title",
          "value": "kIOSurfaceComponentNameBlue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceComponentName~1blue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceComponentNameBlue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceComponentName~1red/title",
          "value": "kIOSurfaceComponentNameRed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceComponentName~1red/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceComponentNameRed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceComponentName~1alpha/title",
          "value": "kIOSurfaceComponentNameAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceComponentName~1alpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceComponentNameAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceComponentName~1luma/title",
          "value": "kIOSurfaceComponentNameLuma"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceComponentName~1luma/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceComponentNameLuma"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceComponentName/title",
          "value": "IOSurfaceComponentName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceComponentName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceComponentName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceComponentName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfaceComponentName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceComponentName~1chromaRed/title",
          "value": "kIOSurfaceComponentNameChromaRed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfaceComponentName~1chromaRed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfaceComponentNameChromaRed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iosurface/iosurfacecomponentname/chromared"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iosurface/iosurfacecomponentname/chromared"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
