{
  "abstract": [
    {
      "text": "Creates a batch-insertion request for a named managed entity, and specifies a closure that provides data dictionaries for insertion.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData",
        "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/batchInsertRequestWithEntityName:dictionaryHandler:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSBatchInsertRequest(cm)batchInsertRequestWithEntityName:dictionaryHandler:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "batchInsertRequestWithEntityName:dictionaryHandler:"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "batchInsertRequestWithEntityName:dictionaryHandler:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "batchInsertRequestWithEntityName:dictionaryHandler:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "batchInsertRequestWithEntityName:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "entityName"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dictionaryHandler:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " (^)("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSMutableDictionary",
              "text": "NSMutableDictionary<NSString *,id>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "obj"
            },
            {
              "kind": "text",
              "text": ")) "
            },
            {
              "kind": "internalParam",
              "text": "handler"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The name of the managed entity to insert data into.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "entityName"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A closure that provides a dictionary that represents an object to insert. The dictionary contains an attribute name key and a value.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "handler"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A batch-insertion request.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Core Data repeatedly calls the provided closure until it returns ",
              "type": "text"
            },
            {
              "code": "true",
              "type": "codeVoice"
            },
            {
              "text": ", then finishes the request and saves the data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest": {
      "abstract": [
        {
          "text": "A request to insert a batch of data in a persistent store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBatchInsertRequest"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBatchInsertRequest"
        }
      ],
      "role": "symbol",
      "title": "NSBatchInsertRequest",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchinsertrequest"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/batchInsertRequestWithEntityName:dictionaryHandler:": {
      "abstract": [
        {
          "text": "Creates a batch-insertion request for a named managed entity, and specifies a closure that provides data dictionaries for insertion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "batchInsertRequestWithEntityName:dictionaryHandler:"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/batchInsertRequestWithEntityName:dictionaryHandler:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "batchInsertRequestWithEntityName:dictionaryHandler:"
        }
      ],
      "role": "symbol",
      "title": "batchInsertRequestWithEntityName:dictionaryHandler:",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchinsertrequest/batchinsertrequestwithentityname:dictionaryhandler:"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/batchInsertRequestWithEntityName:managedObjectHandler:": {
      "abstract": [
        {
          "text": "Creates a batch-insertion request for a named managed entity, and specifies a closure that inserts data into the entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "batchInsertRequestWithEntityName:managedObjectHandler:"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/batchInsertRequestWithEntityName:managedObjectHandler:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "batchInsertRequestWithEntityName:managedObjectHandler:"
        }
      ],
      "role": "symbol",
      "title": "batchInsertRequestWithEntityName:managedObjectHandler:",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchinsertrequest/batchinsertrequestwithentityname:managedobjecthandler:"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/batchInsertRequestWithEntityName:objects:": {
      "abstract": [
        {
          "text": "Creates a batch-insertion request for a named managed entity, and provides an array of data dictionaries for insertion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "batchInsertRequestWithEntityName:objects:"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/batchInsertRequestWithEntityName:objects:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "batchInsertRequestWithEntityName:objects:"
        }
      ],
      "role": "symbol",
      "title": "batchInsertRequestWithEntityName:objects:",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchinsertrequest/batchinsertrequestwithentityname:objects:"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/init()": {
      "abstract": [
        {
          "text": "Creates a Core Data batch-insertion request.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchinsertrequest/init()"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/init(entity:dictionaryHandler:)": {
      "abstract": [
        {
          "text": "Creates a batch-insertion request for a managed entity, and specifies a closure that provides data dictionaries for insertion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "entity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEntityDescription",
          "text": "NSEntityDescription"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dictionaryHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMutableDictionary",
          "text": "NSMutableDictionary"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/init(entity:dictionaryHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithEntity:dictionaryHandler:"
        }
      ],
      "role": "symbol",
      "title": "init(entity:dictionaryHandler:)",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchinsertrequest/init(entity:dictionaryhandler:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/init(entity:managedObjectHandler:)": {
      "abstract": [
        {
          "text": "Creates a batch-insertion request for a managed entity, and specifies a closure that inserts data into the entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "entity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEntityDescription",
          "text": "NSEntityDescription"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "managedObjectHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObject",
          "text": "NSManagedObject"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/init(entity:managedObjectHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithEntity:managedObjectHandler:"
        }
      ],
      "role": "symbol",
      "title": "init(entity:managedObjectHandler:)",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchinsertrequest/init(entity:managedobjecthandler:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/init(entity:objects:)": {
      "abstract": [
        {
          "text": "Creates a batch-insertion request for a managed entity, and provides an array of data dictionaries for insertion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "entity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEntityDescription",
          "text": "NSEntityDescription"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "objects"
        },
        {
          "kind": "text",
          "text": ": [["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]])"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/init(entity:objects:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithEntity:objects:"
        }
      ],
      "role": "symbol",
      "title": "init(entity:objects:)",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchinsertrequest/init(entity:objects:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/init(entityName:dictionaryHandler:)": {
      "abstract": [
        {
          "text": "Creates a batch-insertion request for a named managed entity, and specifies a closure that provides data dictionaries for insertion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "entityName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dictionaryHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMutableDictionary",
          "text": "NSMutableDictionary"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/init(entityName:dictionaryHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithEntityName:dictionaryHandler:"
        }
      ],
      "role": "symbol",
      "title": "init(entityName:dictionaryHandler:)",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchinsertrequest/init(entityname:dictionaryhandler:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/init(entityName:managedObjectHandler:)": {
      "abstract": [
        {
          "text": "Creates a batch-insertion request for a named managed entity, and specifies a closure that inserts data into the entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "entityName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "managedObjectHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObject",
          "text": "NSManagedObject"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/init(entityName:managedObjectHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithEntityName:managedObjectHandler:"
        }
      ],
      "role": "symbol",
      "title": "init(entityName:managedObjectHandler:)",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchinsertrequest/init(entityname:managedobjecthandler:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/init(entityName:objects:)": {
      "abstract": [
        {
          "text": "Creates a batch-insertion request for a named managed entity, and provides an array of data dictionaries for insertion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "entityName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "objects"
        },
        {
          "kind": "text",
          "text": ": [["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]])"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/init(entityName:objects:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithEntityName:objects:"
        }
      ],
      "role": "symbol",
      "title": "init(entityName:objects:)",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchinsertrequest/init(entityname:objects:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Request",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/init(entity:dictionaryHandler:)",
        "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/init(entity:managedObjectHandler:)",
        "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/init(entityName:dictionaryHandler:)",
        "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/init(entityName:managedObjectHandler:)",
        "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/batchInsertRequestWithEntityName:managedObjectHandler:",
        "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/init(entity:objects:)",
        "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/init(entityName:objects:)",
        "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/batchInsertRequestWithEntityName:objects:",
        "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest/init()"
      ],
      "title": "Creating a Request"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequest~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequest~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequest~1init(entityName:dictionaryHandler:)/title",
          "value": "initWithEntityName:dictionaryHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequest~1init(entityName:dictionaryHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithEntityName:dictionaryHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequest~1init(entityName:managedObjectHandler:)/title",
          "value": "initWithEntityName:managedObjectHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequest~1init(entityName:managedObjectHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithEntityName:managedObjectHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequest~1init(entityName:objects:)/title",
          "value": "initWithEntityName:objects:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequest~1init(entityName:objects:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithEntityName:objects:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequest~1init(entity:objects:)/title",
          "value": "initWithEntity:objects:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequest~1init(entity:objects:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithEntity:objects:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequest/title",
          "value": "NSBatchInsertRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBatchInsertRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBatchInsertRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequest~1init(entity:managedObjectHandler:)/title",
          "value": "initWithEntity:managedObjectHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequest~1init(entity:managedObjectHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithEntity:managedObjectHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequest~1init(entity:dictionaryHandler:)/title",
          "value": "initWithEntity:dictionaryHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequest~1init(entity:dictionaryHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithEntity:dictionaryHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nsbatchinsertrequest/batchinsertrequestwithentityname:dictionaryhandler:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
