{
  "abstract": [
    {
      "text": "Sets the action to perform on the specified dispatch queue when the slider’s value changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSlider"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSlider/setActionQueue:action:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVCaptureSlider(im)setActionQueue:action:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "setActionQueue:action:"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setActionQueue:action:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setActionQueue:action:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "setActionQueue:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@dispatch_queue_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_queue_t",
              "text": "dispatch_queue_t"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "actionQueue"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "action:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " (^)("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:f",
              "text": "float"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "newValue"
            },
            {
              "kind": "text",
              "text": ")) "
            },
            {
              "kind": "internalParam",
              "text": "action"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A dispatch queue on which to call the action.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "actionQueue"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The action to perform in response to changes to the slider’s value.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "action"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the action modifies a property of the camera system, the specified dispatch queue must represent the camera system’s same exclusive execution context (see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Swift/SerialExecutor/isSameExclusiveExecutionContext(other:)-3ptya",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ").",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSlider": {
      "abstract": [
        {
          "text": "A slider control that selects a value from a bounded range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureSlider"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSlider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureSlider"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureSlider",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureslider"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSlider/setActionQueue:action:": {
      "abstract": [
        {
          "text": "Sets the action to perform on the specified dispatch queue when the slider’s value changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setActionQueue:action:"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSlider/setActionQueue:action:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setActionQueue:action:"
        }
      ],
      "role": "symbol",
      "title": "setActionQueue:action:",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureslider/setactionqueue:action:"
    },
    "doc://com.apple.documentation/documentation/Swift/SerialExecutor/isSameExclusiveExecutionContext(other:)-3ptya": {
      "abstract": [
        {
          "text": "If this executor has complex equality semantics, and the runtime needs to compare two executors, it will first attempt the usual pointer-based equality / check, / and if it fails it will compare the types of both executors, if they are the same, / it will finally invoke this method, in an attempt to let the executor itself decide / if this and the `other` executor represent the same serial, exclusive, isolation context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSameExclusiveExecutionContext"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "other"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/SerialExecutor/isSameExclusiveExecutionContext(other:)-3ptya",
      "kind": "symbol",
      "role": "symbol",
      "title": "isSameExclusiveExecutionContext(other:)",
      "type": "topic",
      "url": "/documentation/Swift/SerialExecutor/isSameExclusiveExecutionContext(other:)-3ptya"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@dispatch_queue_t": {
      "abstract": [
        {
          "text": "A lightweight object to which your application submits blocks for subsequent execution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@dispatch_queue_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_queue_t",
      "type": "topic",
      "url": "/documentation/Dispatch/dispatch_queue_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@dispatch_queue_t/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_dispatch_queue",
              "text": "NSObject<OS_dispatch_queue>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "dispatch_queue_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSlider/title",
          "value": "AVCaptureSlider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSlider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureSlider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSlider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureSlider"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcaptureslider/setactionqueue:action:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
