{
  "abstract": [
    {
      "text": "Creates a waiter that waits on group of expectations for up to the specified timeout, optionally enforcing their order of fulfillment.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest",
        "doc://com.apple.xctest/documentation/XCTest/XCTWaiter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/fulfillment(of:timeout:enforceOrder:)-swift.type.method"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "XCTest",
    "externalID": "s:So9XCTWaiterC6XCTestE11fulfillment2of7timeout12enforceOrderSo0A6ResultVSaySo0B11ExpectationCG_SdSbtYaFZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "fulfillment"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "of"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)XCTestExpectation",
        "text": "XCTestExpectation"
      },
      {
        "kind": "text",
        "text": "], "
      },
      {
        "kind": "externalParam",
        "text": "timeout"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSTimeInterval",
        "text": "TimeInterval"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "enforceOrder"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      },
      {
        "kind": "text",
        "text": ") "
      },
      {
        "kind": "keyword",
        "text": "async"
      },
      {
        "kind": "text",
        "text": " -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)XCTWaiter",
        "text": "XCTWaiter"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@XCTWaiterResult",
        "text": "Result"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "fulfillment(of:timeout:enforceOrder:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@nonobjc"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "fulfillment"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "of"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "expectations"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)XCTestExpectation",
              "text": "XCTestExpectation"
            },
            {
              "kind": "text",
              "text": "], "
            },
            {
              "kind": "externalParam",
              "text": "timeout"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "seconds"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSTimeInterval",
              "text": "TimeInterval"
            },
            {
              "kind": "text",
              "text": " = .infinity, "
            },
            {
              "kind": "externalParam",
              "text": "enforceOrder"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "enforceOrderOfFulfillment"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " = false) "
            },
            {
              "kind": "keyword",
              "text": "async"
            },
            {
              "kind": "text",
              "text": " -> "
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiter",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)XCTWaiter",
              "text": "XCTWaiter"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/Result",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@XCTWaiterResult",
              "text": "Result"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of expectations the test must satisfy.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "expectations"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The time, in seconds, the test allows for the fulfillment of the expectations.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "seconds"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "If ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/swift/true",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", the test must satisfy the expectations in the order they appear in the array.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "enforceOrderOfFulfillment"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A value describing the outcome of waiting for ",
              "type": "text"
            },
            {
              "code": "expectations",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this Concurrency safe alternative to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/wait(for:timeout:enforceOrder:)-swift.type.method",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in your Swift code. A call to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/wait(for:timeout:enforceOrder:)-swift.type.method",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " runs synchronously and blocks the calling thread, which can cause deadlocks or priority inversion.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Expectations can only appear in the array once. The call may return before the timeout if the test fulfills all the expectations you provide.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If you don’t specify a timeout when calling this function, enable test timeouts to prevent unfulfilled expectation from hanging the test.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "The test discards the waiter after the wait completes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTWaiter": {
      "abstract": [
        {
          "text": "Waits for the fulfillment of a group of expectations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTWaiter"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTWaiter"
        }
      ],
      "role": "symbol",
      "title": "XCTWaiter",
      "type": "topic",
      "url": "/documentation/xctest/xctwaiter"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/Result": {
      "abstract": [
        {
          "text": "Result states returned by a waiter when it completes, times out, fails, or is interrupted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Result"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/Result",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Result"
        }
      ],
      "role": "symbol",
      "title": "XCTWaiter.Result",
      "type": "topic",
      "url": "/documentation/xctest/xctwaiter/result"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/fulfillment(of:timeout:enforceOrder:)-swift.method": {
      "abstract": [
        {
          "text": "Waits on a group of expectations for up to the specified timeout, optionally enforcing their order of fulfillment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fulfillment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestExpectation",
          "text": "XCTestExpectation"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "timeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "enforceOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTWaiter",
          "text": "XCTWaiter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCTWaiterResult",
          "text": "Result"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/fulfillment(of:timeout:enforceOrder:)-swift.method",
      "kind": "symbol",
      "role": "symbol",
      "title": "fulfillment(of:timeout:enforceOrder:)",
      "type": "topic",
      "url": "/documentation/xctest/xctwaiter/fulfillment(of:timeout:enforceorder:)-swift.method"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/fulfillment(of:timeout:enforceOrder:)-swift.type.method": {
      "abstract": [
        {
          "text": "Creates a waiter that waits on group of expectations for up to the specified timeout, optionally enforcing their order of fulfillment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fulfillment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestExpectation",
          "text": "XCTestExpectation"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "timeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "enforceOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTWaiter",
          "text": "XCTWaiter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCTWaiterResult",
          "text": "Result"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/fulfillment(of:timeout:enforceOrder:)-swift.type.method",
      "kind": "symbol",
      "role": "symbol",
      "title": "fulfillment(of:timeout:enforceOrder:)",
      "type": "topic",
      "url": "/documentation/xctest/xctwaiter/fulfillment(of:timeout:enforceorder:)-swift.type.method"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/wait(for:)-swift.method": {
      "abstract": [
        {
          "text": "Waits on a group of expectations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wait"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestExpectation",
          "text": "XCTestExpectation"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTWaiter",
          "text": "XCTWaiter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCTWaiterResult",
          "text": "Result"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/wait(for:)-swift.method",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "waitForExpectations:"
        }
      ],
      "role": "symbol",
      "title": "wait(for:)",
      "type": "topic",
      "url": "/documentation/xctest/xctwaiter/wait(for:)-swift.method"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/wait(for:)-swift.type.method": {
      "abstract": [
        {
          "text": "Creates a waiter that waits on a group of expectations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wait"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestExpectation",
          "text": "XCTestExpectation"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTWaiter",
          "text": "XCTWaiter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCTWaiterResult",
          "text": "Result"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/wait(for:)-swift.type.method",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "waitForExpectations:"
        }
      ],
      "role": "symbol",
      "title": "wait(for:)",
      "type": "topic",
      "url": "/documentation/xctest/xctwaiter/wait(for:)-swift.type.method"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/wait(for:enforceOrder:)-swift.method": {
      "abstract": [
        {
          "text": "Waits on a group of expectations optionally enforcing their order of fulfillment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wait"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestExpectation",
          "text": "XCTestExpectation"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "enforceOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTWaiter",
          "text": "XCTWaiter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCTWaiterResult",
          "text": "Result"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/wait(for:enforceOrder:)-swift.method",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "waitForExpectations:enforceOrder:"
        }
      ],
      "role": "symbol",
      "title": "wait(for:enforceOrder:)",
      "type": "topic",
      "url": "/documentation/xctest/xctwaiter/wait(for:enforceorder:)-swift.method"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/wait(for:enforceOrder:)-swift.type.method": {
      "abstract": [
        {
          "text": "Creates a waiter that waits on a group of expectations optionally enforcing their order of fulfillment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wait"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestExpectation",
          "text": "XCTestExpectation"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "enforceOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTWaiter",
          "text": "XCTWaiter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCTWaiterResult",
          "text": "Result"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/wait(for:enforceOrder:)-swift.type.method",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "waitForExpectations:enforceOrder:"
        }
      ],
      "role": "symbol",
      "title": "wait(for:enforceOrder:)",
      "type": "topic",
      "url": "/documentation/xctest/xctwaiter/wait(for:enforceorder:)-swift.type.method"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/wait(for:timeout:)-swift.method": {
      "abstract": [
        {
          "text": "Waits on a group of expectations for up to the specified timeout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wait"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestExpectation",
          "text": "XCTestExpectation"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "timeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTWaiter",
          "text": "XCTWaiter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCTWaiterResult",
          "text": "Result"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/wait(for:timeout:)-swift.method",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "waitForExpectations:timeout:"
        }
      ],
      "role": "symbol",
      "title": "wait(for:timeout:)",
      "type": "topic",
      "url": "/documentation/xctest/xctwaiter/wait(for:timeout:)-swift.method"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/wait(for:timeout:)-swift.type.method": {
      "abstract": [
        {
          "text": "Creates a waiter that waits on a group of expectations for up to the specified timeout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wait"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestExpectation",
          "text": "XCTestExpectation"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "timeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTWaiter",
          "text": "XCTWaiter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCTWaiterResult",
          "text": "Result"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/wait(for:timeout:)-swift.type.method",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "waitForExpectations:timeout:"
        }
      ],
      "role": "symbol",
      "title": "wait(for:timeout:)",
      "type": "topic",
      "url": "/documentation/xctest/xctwaiter/wait(for:timeout:)-swift.type.method"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/wait(for:timeout:enforceOrder:)-swift.method": {
      "abstract": [
        {
          "text": "Waits on a group of expectations for up to the specified timeout, optionally enforcing their order of fulfillment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wait"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestExpectation",
          "text": "XCTestExpectation"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "timeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "enforceOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTWaiter",
          "text": "XCTWaiter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCTWaiterResult",
          "text": "Result"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/wait(for:timeout:enforceOrder:)-swift.method",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "waitForExpectations:timeout:enforceOrder:"
        }
      ],
      "role": "symbol",
      "title": "wait(for:timeout:enforceOrder:)",
      "type": "topic",
      "url": "/documentation/xctest/xctwaiter/wait(for:timeout:enforceorder:)-swift.method"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/wait(for:timeout:enforceOrder:)-swift.type.method": {
      "abstract": [
        {
          "text": "Creates a waiter that waits on a group of expectations for up to the specified timeout, optionally enforcing their order of fulfillment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wait"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTestExpectation",
          "text": "XCTestExpectation"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "timeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "enforceOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCTWaiter",
          "text": "XCTWaiter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCTWaiterResult",
          "text": "Result"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/wait(for:timeout:enforceOrder:)-swift.type.method",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "waitForExpectations:timeout:enforceOrder:"
        }
      ],
      "role": "symbol",
      "title": "wait(for:timeout:enforceOrder:)",
      "type": "topic",
      "url": "/documentation/xctest/xctwaiter/wait(for:timeout:enforceorder:)-swift.type.method"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation": {
      "abstract": [
        {
          "text": "An expected outcome in an asynchronous test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTestExpectation"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTestExpectation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTestExpectation"
        }
      ],
      "role": "symbol",
      "title": "XCTestExpectation",
      "type": "topic",
      "url": "/documentation/xctest/xctestexpectation"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval": {
      "abstract": [
        {
          "text": "A number of seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSTimeInterval",
      "kind": "symbol",
      "role": "symbol",
      "title": "TimeInterval",
      "type": "topic",
      "url": "/documentation/foundation/timeinterval"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Waiting-for-Expectations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/fulfillment(of:timeout:enforceOrder:)-swift.method",
        "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/wait(for:)-swift.method",
        "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/wait(for:enforceOrder:)-swift.method",
        "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/wait(for:timeout:)-swift.method",
        "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/wait(for:timeout:enforceOrder:)-swift.method",
        "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/wait(for:)-swift.type.method",
        "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/wait(for:enforceOrder:)-swift.type.method",
        "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/wait(for:timeout:)-swift.type.method",
        "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/wait(for:timeout:enforceOrder:)-swift.type.method",
        "doc://com.apple.xctest/documentation/XCTest/XCTWaiter/Result"
      ],
      "title": "Waiting for Expectations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter~1wait(for:timeout:enforceOrder:)-swift.method/title",
          "value": "waitForExpectations:timeout:enforceOrder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter~1wait(for:timeout:enforceOrder:)-swift.method/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "waitForExpectations:timeout:enforceOrder:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter~1wait(for:timeout:enforceOrder:)-swift.type.method/title",
          "value": "waitForExpectations:timeout:enforceOrder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter~1wait(for:timeout:enforceOrder:)-swift.type.method/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "waitForExpectations:timeout:enforceOrder:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter~1wait(for:)-swift.method/title",
          "value": "waitForExpectations:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter~1wait(for:)-swift.method/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "waitForExpectations:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter~1Result/title",
          "value": "XCTWaiterResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter~1Result/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTWaiterResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter~1Result/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTWaiterResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestExpectation/title",
          "value": "XCTestExpectation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestExpectation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestExpectation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTestExpectation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTestExpectation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter~1wait(for:timeout:)-swift.method/title",
          "value": "waitForExpectations:timeout:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter~1wait(for:timeout:)-swift.method/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "waitForExpectations:timeout:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSTimeInterval/title",
          "value": "NSTimeInterval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter~1wait(for:timeout:)-swift.type.method/title",
          "value": "waitForExpectations:timeout:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter~1wait(for:timeout:)-swift.type.method/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "waitForExpectations:timeout:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter~1wait(for:enforceOrder:)-swift.type.method/title",
          "value": "waitForExpectations:enforceOrder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter~1wait(for:enforceOrder:)-swift.type.method/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "waitForExpectations:enforceOrder:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter/title",
          "value": "XCTWaiter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTWaiter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTWaiter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter~1wait(for:)-swift.type.method/title",
          "value": "waitForExpectations:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter~1wait(for:)-swift.type.method/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "waitForExpectations:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter~1wait(for:enforceOrder:)-swift.method/title",
          "value": "waitForExpectations:enforceOrder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTWaiter~1wait(for:enforceOrder:)-swift.method/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "waitForExpectations:enforceOrder:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xctwaiter/fulfillment(of:timeout:enforceorder:)-swift.type.method"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
