{
  "abstract": [
    {
      "text": "A relative change to the level value.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/relativeLevelSetting"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INSetSeatSettingsInCarIntent(py)relativeLevelSetting",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "relativeLevelSetting"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@INRelativeSetting",
        "text": "INRelativeSetting"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "relativeLevelSetting"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.0",
        "message": "INSetSeatSettingsInCarIntent is deprecated. There is no replacement.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.0",
        "message": "INSetSeatSettingsInCarIntent is deprecated. There is no replacement.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "13.1",
        "message": "INSetSeatSettingsInCarIntent is deprecated. There is no replacement.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "INSetSeatSettingsInCarIntent is deprecated. There is no replacement.",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "relativeLevelSetting"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "relativeLevelSetting"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INRelativeSetting",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@INRelativeSetting",
              "text": "INRelativeSetting"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this property to adjust the heating, cooling, or massage level to the next or previous setting. The value of this property is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INRelativeSetting/unknown",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " when the user modified the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/level-5i2i",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " directly.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The intent object contains a value for this property or the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/level-5i2i",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property, but not both.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRelativeSetting": {
      "abstract": [
        {
          "text": "Constants indicating relative settings.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRelativeSetting"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRelativeSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRelativeSetting"
        }
      ],
      "role": "symbol",
      "title": "INRelativeSetting",
      "type": "topic",
      "url": "/documentation/intents/inrelativesetting"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRelativeSetting/unknown": {
      "abstract": [
        {
          "text": "An unknown setting.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRelativeSetting/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRelativeSettingUnknown"
        }
      ],
      "role": "symbol",
      "title": "INRelativeSetting.unknown",
      "type": "topic",
      "url": "/documentation/intents/inrelativesetting/unknown"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent": {
      "abstract": [
        {
          "text": "A request to change the seat-related settings in a CarPlay-enabled vehicle.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetSeatSettingsInCarIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetSeatSettingsInCarIntent"
        }
      ],
      "role": "symbol",
      "title": "INSetSeatSettingsInCarIntent",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableCooling-6bcu7": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether to enable the seat cooling system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "enableCooling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableCooling-6bcu7",
      "kind": "symbol",
      "role": "symbol",
      "title": "enableCooling",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintent/enablecooling-6bcu7"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableCooling-8qqx3": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether to enable the seat cooling system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enableCooling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableCooling-8qqx3",
      "kind": "symbol",
      "role": "symbol",
      "title": "enableCooling",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintent/enablecooling-8qqx3"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableHeating-5qj7i": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether to enable the seat heating system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "enableHeating"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableHeating-5qj7i",
      "kind": "symbol",
      "role": "symbol",
      "title": "enableHeating",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintent/enableheating-5qj7i"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableHeating-8auz2": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether to enable the seat heating system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enableHeating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableHeating-8auz2",
      "kind": "symbol",
      "role": "symbol",
      "title": "enableHeating",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintent/enableheating-8auz2"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableMassage-46ndx": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether to enable the seat massage system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enableMassage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableMassage-46ndx",
      "kind": "symbol",
      "role": "symbol",
      "title": "enableMassage",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintent/enablemassage-46ndx"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableMassage-5jf2s": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether to enable the seat massage system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "enableMassage"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableMassage-5jf2s",
      "kind": "symbol",
      "role": "symbol",
      "title": "enableMassage",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintent/enablemassage-5jf2s"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/level-5i2i": {
      "abstract": [
        {
          "text": "An integer value indicating the desired level for the seat setting.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "level"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/level-5i2i",
      "kind": "symbol",
      "role": "symbol",
      "title": "level",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintent/level-5i2i"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/level-94975": {
      "abstract": [
        {
          "text": "An integer value indicating the desired level for the seat setting.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "level"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/level-94975",
      "kind": "symbol",
      "role": "symbol",
      "title": "level",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintent/level-94975"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/relativeLevelSetting": {
      "abstract": [
        {
          "text": "A relative change to the level value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "relativeLevelSetting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INRelativeSetting",
          "text": "INRelativeSetting"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/relativeLevelSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "relativeLevelSetting"
        }
      ],
      "role": "symbol",
      "title": "relativeLevelSetting",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintent/relativelevelsetting"
    },
    "https://developer.apple.com/support/deprecated-sirikit-intent-domains": {
      "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
      "title": "Deprecated SiriKit Intent Domains",
      "titleInlineContent": [
        {
          "text": "Deprecated SiriKit Intent Domains",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/deprecated-sirikit-intent-domains"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-New-Settings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableCooling-8qqx3",
        "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableHeating-8auz2",
        "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableMassage-46ndx",
        "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/level-94975"
      ],
      "title": "Getting the New Settings"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "relativeLevelSetting"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "relativeLevelSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-New-Settings",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableCooling-6bcu7",
                "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableHeating-5qj7i",
                "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableMassage-5jf2s",
                "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/level-5i2i"
              ],
              "title": "Getting the New Settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "atomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INRelativeSetting",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@INRelativeSetting",
                    "text": "INRelativeSetting"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "relativeLevelSetting"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              },
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INRelativeSetting",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@INRelativeSetting",
                    "text": "INRelativeSetting"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "relativeLevelSetting"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntent/title",
          "value": "INSetSeatSettingsInCarIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetSeatSettingsInCarIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetSeatSettingsInCarIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntent~1relativeLevelSetting/title",
          "value": "relativeLevelSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntent~1relativeLevelSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "relativeLevelSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRelativeSetting~1unknown/title",
          "value": "INRelativeSettingUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRelativeSetting~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRelativeSettingUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRelativeSetting/title",
          "value": "INRelativeSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRelativeSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRelativeSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRelativeSetting/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRelativeSetting"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/insetseatsettingsincarintent/relativelevelsetting"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/insetseatsettingsincarintent/relativelevelsetting"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
