{
  "abstract": [
    {
      "text": "The Adobe-Japan2 mapping.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeJapan2"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTCharacterCollection@kCTCharacterCollectionAdobeJapan2",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "adobeJapan2"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCTCharacterCollectionAdobeJapan2"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CTCharacterCollection.adobeJapan2"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "adobeJapan2"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection": {
      "abstract": [
        {
          "text": "Constants that specify character collections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTCharacterCollection"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCharacterCollection"
        }
      ],
      "role": "symbol",
      "title": "CTCharacterCollection",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeCNS1": {
      "abstract": [
        {
          "text": "The Adobe-CNS1 mapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adobeCNS1"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeCNS1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTCharacterCollectionAdobeCNS1"
        }
      ],
      "role": "symbol",
      "title": "CTCharacterCollection.adobeCNS1",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection/adobecns1"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeGB1": {
      "abstract": [
        {
          "text": "The Adobe-GB1 mapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adobeGB1"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeGB1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTCharacterCollectionAdobeGB1"
        }
      ],
      "role": "symbol",
      "title": "CTCharacterCollection.adobeGB1",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection/adobegb1"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeJapan1": {
      "abstract": [
        {
          "text": "The Adobe-Japan1 mapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adobeJapan1"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeJapan1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTCharacterCollectionAdobeJapan1"
        }
      ],
      "role": "symbol",
      "title": "CTCharacterCollection.adobeJapan1",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection/adobejapan1"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeJapan2": {
      "abstract": [
        {
          "text": "The Adobe-Japan2 mapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adobeJapan2"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeJapan2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTCharacterCollectionAdobeJapan2"
        }
      ],
      "role": "symbol",
      "title": "CTCharacterCollection.adobeJapan2",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection/adobejapan2"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeKorea1": {
      "abstract": [
        {
          "text": "The Adobe-Korea1 mapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adobeKorea1"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeKorea1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTCharacterCollectionAdobeKorea1"
        }
      ],
      "role": "symbol",
      "title": "CTCharacterCollection.adobeKorea1",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection/adobekorea1"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/identityMapping": {
      "abstract": [
        {
          "text": "The character identifier is equal to the glyph index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identityMapping"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/identityMapping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTCharacterCollectionIdentityMapping"
        }
      ],
      "role": "symbol",
      "title": "CTCharacterCollection.identityMapping",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection/identitymapping"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/identityMapping",
        "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeCNS1",
        "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeGB1",
        "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeJapan1",
        "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeKorea1"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCTCharacterCollectionAdobeJapan2"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTCharacterCollectionAdobeJapan2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText",
                "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/identityMapping",
                "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeCNS1",
                "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeGB1",
                "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeJapan1",
                "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeKorea1"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCTCharacterCollectionAdobeJapan2"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1adobeJapan1/title",
          "value": "kCTCharacterCollectionAdobeJapan1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1adobeJapan1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTCharacterCollectionAdobeJapan1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1adobeKorea1/title",
          "value": "kCTCharacterCollectionAdobeKorea1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1adobeKorea1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTCharacterCollectionAdobeKorea1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection/title",
          "value": "CTCharacterCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCharacterCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCharacterCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1adobeJapan2/title",
          "value": "kCTCharacterCollectionAdobeJapan2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1adobeJapan2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTCharacterCollectionAdobeJapan2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1identityMapping/title",
          "value": "kCTCharacterCollectionIdentityMapping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1identityMapping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTCharacterCollectionIdentityMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1adobeGB1/title",
          "value": "kCTCharacterCollectionAdobeGB1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1adobeGB1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTCharacterCollectionAdobeGB1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1adobeCNS1/title",
          "value": "kCTCharacterCollectionAdobeCNS1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1adobeCNS1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTCharacterCollectionAdobeCNS1"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctcharactercollection/adobejapan2"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctcharactercollection/adobejapan2"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
