{
  "abstract": [
    {
      "text": "The character identifier is equal to the glyph index.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/identityMapping",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTIdentityMappingCharacterCollection"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTCharacterCollection@kCTIdentityMappingCharacterCollection",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCTIdentityMappingCharacterCollection"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CTCharacterCollection",
        "text": "CTCharacterCollection"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCTIdentityMappingCharacterCollection"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "3.2",
        "message": "Deprecated",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "3.2",
        "message": "Deprecated",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Deprecated",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.11",
        "introducedAt": "10.5",
        "message": "Deprecated",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Deprecated",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "kCTIdentityMappingCharacterCollection"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCTIdentityMappingCharacterCollection"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CTCharacterCollection",
              "text": "CTCharacterCollection"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection": {
      "abstract": [
        {
          "text": "Constants that specify character collections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTCharacterCollection"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCharacterCollection"
        }
      ],
      "role": "symbol",
      "title": "CTCharacterCollection",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/identityMapping": {
      "abstract": [
        {
          "text": "The character identifier is equal to the glyph index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identityMapping"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/identityMapping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTCharacterCollectionIdentityMapping"
        }
      ],
      "role": "symbol",
      "title": "CTCharacterCollection.identityMapping",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection/identitymapping"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeCNS1CharacterCollection": {
      "abstract": [
        {
          "text": "The Adobe-CNS1 mapping.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTAdobeCNS1CharacterCollection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTCharacterCollection",
          "text": "CTCharacterCollection"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeCNS1CharacterCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTAdobeCNS1CharacterCollection"
        }
      ],
      "role": "symbol",
      "title": "kCTAdobeCNS1CharacterCollection",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection/kctadobecns1charactercollection"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeGB1CharacterCollection": {
      "abstract": [
        {
          "text": "The Adobe-GB1 mapping.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTAdobeGB1CharacterCollection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTCharacterCollection",
          "text": "CTCharacterCollection"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeGB1CharacterCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTAdobeGB1CharacterCollection"
        }
      ],
      "role": "symbol",
      "title": "kCTAdobeGB1CharacterCollection",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection/kctadobegb1charactercollection"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeJapan1CharacterCollection": {
      "abstract": [
        {
          "text": "The Adobe-Japan1 mapping.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTAdobeJapan1CharacterCollection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTCharacterCollection",
          "text": "CTCharacterCollection"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeJapan1CharacterCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTAdobeJapan1CharacterCollection"
        }
      ],
      "role": "symbol",
      "title": "kCTAdobeJapan1CharacterCollection",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection/kctadobejapan1charactercollection"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeJapan2CharacterCollection": {
      "abstract": [
        {
          "text": "The Adobe-Japan2 mapping.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTAdobeJapan2CharacterCollection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTCharacterCollection",
          "text": "CTCharacterCollection"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeJapan2CharacterCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTAdobeJapan2CharacterCollection"
        }
      ],
      "role": "symbol",
      "title": "kCTAdobeJapan2CharacterCollection",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection/kctadobejapan2charactercollection"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeKorea1CharacterCollection": {
      "abstract": [
        {
          "text": "The Adobe-Korea1 mapping.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTAdobeKorea1CharacterCollection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTCharacterCollection",
          "text": "CTCharacterCollection"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeKorea1CharacterCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTAdobeKorea1CharacterCollection"
        }
      ],
      "role": "symbol",
      "title": "kCTAdobeKorea1CharacterCollection",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection/kctadobekorea1charactercollection"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTIdentityMappingCharacterCollection": {
      "abstract": [
        {
          "text": "The character identifier is equal to the glyph index.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTIdentityMappingCharacterCollection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTCharacterCollection",
          "text": "CTCharacterCollection"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTIdentityMappingCharacterCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTIdentityMappingCharacterCollection"
        }
      ],
      "role": "symbol",
      "title": "kCTIdentityMappingCharacterCollection",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection/kctidentitymappingcharactercollection"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeCNS1CharacterCollection",
        "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeGB1CharacterCollection",
        "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeJapan1CharacterCollection",
        "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeJapan2CharacterCollection",
        "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeKorea1CharacterCollection"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "3.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "3.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.11",
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCTIdentityMappingCharacterCollection"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTIdentityMappingCharacterCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText",
                "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeCNS1CharacterCollection",
                "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeGB1CharacterCollection",
                "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeJapan1CharacterCollection",
                "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeJapan2CharacterCollection",
                "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeKorea1CharacterCollection"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCTIdentityMappingCharacterCollection"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/identityMapping",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1kCTAdobeKorea1CharacterCollection/title",
          "value": "kCTAdobeKorea1CharacterCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1kCTAdobeKorea1CharacterCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTAdobeKorea1CharacterCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection/title",
          "value": "CTCharacterCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCharacterCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCharacterCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1kCTIdentityMappingCharacterCollection/title",
          "value": "kCTIdentityMappingCharacterCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1kCTIdentityMappingCharacterCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTIdentityMappingCharacterCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1kCTAdobeJapan1CharacterCollection/title",
          "value": "kCTAdobeJapan1CharacterCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1kCTAdobeJapan1CharacterCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTAdobeJapan1CharacterCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1kCTAdobeJapan2CharacterCollection/title",
          "value": "kCTAdobeJapan2CharacterCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1kCTAdobeJapan2CharacterCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTAdobeJapan2CharacterCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1kCTAdobeGB1CharacterCollection/title",
          "value": "kCTAdobeGB1CharacterCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1kCTAdobeGB1CharacterCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTAdobeGB1CharacterCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1identityMapping/title",
          "value": "kCTCharacterCollectionIdentityMapping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1identityMapping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTCharacterCollectionIdentityMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1kCTAdobeCNS1CharacterCollection/title",
          "value": "kCTAdobeCNS1CharacterCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1kCTAdobeCNS1CharacterCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTAdobeCNS1CharacterCollection"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctcharactercollection/kctidentitymappingcharactercollection"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctcharactercollection/kctidentitymappingcharactercollection"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
