{
  "abstract": [
    {
      "text": "Constants that indicate the audio route selection.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avkit/documentation/AVKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.avkit/documentation/AVKit/AVAudioSessionRouteSelection"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVAudioSessionRouteSelection",
    "fragments": [
      {
        "kind": "identifier",
        "text": "AVAudioSessionRouteSelection"
      }
    ],
    "modules": [
      {
        "name": "AVKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAudioSessionRouteSelection"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "AVAudioSessionRouteSelection"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteSelection"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avkit/documentation/AVKit": {
      "abstract": [
        {
          "text": "Create user interfaces for media playback, complete with transport controls, chapter navigation, picture-in-picture support, and display of subtitles and closed captions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AVKit",
      "type": "topic",
      "url": "/documentation/avkit"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVAudioSessionRouteSelection": {
      "abstract": [
        {
          "text": "Constants that indicate the audio route selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteSelection"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVAudioSessionRouteSelection",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioSessionRouteSelection",
      "type": "topic",
      "url": "/documentation/avkit/avaudiosessionrouteselection"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVAudioSessionRouteSelection/AVAudioSessionRouteSelectionExternal": {
      "abstract": [
        {
          "text": "An external device selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteSelectionExternal"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVAudioSessionRouteSelection/AVAudioSessionRouteSelectionExternal",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioSessionRouteSelectionExternal",
      "type": "topic",
      "url": "/documentation/avkit/avaudiosessionrouteselection/avaudiosessionrouteselectionexternal"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVAudioSessionRouteSelection/AVAudioSessionRouteSelectionLocal": {
      "abstract": [
        {
          "text": "A local device selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteSelectionLocal"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVAudioSessionRouteSelection/AVAudioSessionRouteSelectionLocal",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioSessionRouteSelectionLocal",
      "type": "topic",
      "url": "/documentation/avkit/avaudiosessionrouteselection/avaudiosessionrouteselectionlocal"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVAudioSessionRouteSelection/AVAudioSessionRouteSelectionNone": {
      "abstract": [
        {
          "text": "No route selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteSelectionNone"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVAudioSessionRouteSelection/AVAudioSessionRouteSelectionNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioSessionRouteSelectionNone",
      "type": "topic",
      "url": "/documentation/avkit/avaudiosessionrouteselection/avaudiosessionrouteselectionnone"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView": {
      "abstract": [
        {
          "text": "A view that presents a list of nearby media receivers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVRoutePickerView"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVRoutePickerView"
        }
      ],
      "role": "symbol",
      "title": "AVRoutePickerView",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerview"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Playback-Route-Selection",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView"
      ],
      "title": "Playback Route Selection"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVAudioSessionRouteSelection/AVAudioSessionRouteSelectionExternal",
        "doc://com.apple.avkit/documentation/AVKit/AVAudioSessionRouteSelection/AVAudioSessionRouteSelectionLocal",
        "doc://com.apple.avkit/documentation/AVKit/AVAudioSessionRouteSelection/AVAudioSessionRouteSelectionNone"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView/title",
          "value": "AVRoutePickerView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avkit/avaudiosessionrouteselection"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
