{
  "abstract": [
    {
      "text": "An interface that responds to events from a continuity device picker view controller.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avkit/documentation/AVKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)AVContinuityDevicePickerViewControllerDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVContinuityDevicePickerViewControllerDelegate"
      }
    ],
    "modules": [
      {
        "name": "AVKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVContinuityDevicePickerViewControllerDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "AVContinuityDevicePickerViewControllerDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVContinuityDevicePickerViewControllerDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Your app can respond to the various outcome events from an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance with the following steps:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Adopt the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " protocol with one of the app’s classes.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create an instance of that class.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Assign that instance to the view controller’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewController/delegate",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avkit/documentation/AVKit": {
      "abstract": [
        {
          "text": "Create user interfaces for media playback, complete with transport controls, chapter navigation, picture-in-picture support, and display of subtitles and closed captions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AVKit",
      "type": "topic",
      "url": "/documentation/avkit"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContentProposalViewController": {
      "abstract": [
        {
          "text": "A view controller that proposes content to watch next.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContentProposalViewController"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContentProposalViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentProposalViewController"
        }
      ],
      "role": "symbol",
      "title": "AVContentProposalViewController",
      "type": "topic",
      "url": "/documentation/avkit/avcontentproposalviewcontroller"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewController": {
      "abstract": [
        {
          "text": "A view controller that provides an interface to a person so they can select and connect a continuity device to the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContinuityDevicePickerViewController"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContinuityDevicePickerViewController"
        }
      ],
      "role": "symbol",
      "title": "AVContinuityDevicePickerViewController",
      "type": "topic",
      "url": "/documentation/avkit/avcontinuitydevicepickerviewcontroller"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewController/delegate": {
      "abstract": [
        {
          "text": "The delegate that responds to events from the continuity device picker view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)AVContinuityDevicePickerViewControllerDelegate",
          "text": "AVContinuityDevicePickerViewControllerDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewController/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/avkit/avcontinuitydevicepickerviewcontroller/delegate"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate": {
      "abstract": [
        {
          "text": "An interface that responds to events from a continuity device picker view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContinuityDevicePickerViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContinuityDevicePickerViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "AVContinuityDevicePickerViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/avkit/avcontinuitydevicepickerviewcontrollerdelegate"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePicker(_:didConnect:)": {
      "abstract": [
        {
          "text": "Informs the delegate when a person selects and connects a continuity device to the system with a continuity device picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "continuityDevicePicker"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVContinuityDevicePickerViewController",
          "text": "AVContinuityDevicePickerViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didConnect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVContinuityDevice",
          "text": "AVContinuityDevice"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePicker(_:didConnect:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "continuityDevicePicker:didConnectDevice:"
        }
      ],
      "role": "symbol",
      "title": "continuityDevicePicker(_:didConnect:)",
      "type": "topic",
      "url": "/documentation/avkit/avcontinuitydevicepickerviewcontrollerdelegate/continuitydevicepicker(_:didconnect:)"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePickerDidCancel(_:)": {
      "abstract": [
        {
          "text": "Informs the delegate when a person declines to select a continuity device by dismissing an app’s continuity device picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "continuityDevicePickerDidCancel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVContinuityDevicePickerViewController",
          "text": "AVContinuityDevicePickerViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePickerDidCancel(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "continuityDevicePickerDidCancel:"
        }
      ],
      "role": "symbol",
      "title": "continuityDevicePickerDidCancel(_:)",
      "type": "topic",
      "url": "/documentation/avkit/avcontinuitydevicepickerviewcontrollerdelegate/continuitydevicepickerdidcancel(_:)"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePickerDidEndPresenting(_:)": {
      "abstract": [
        {
          "text": "Informs the delegate that a continuity device picker is no longer presenting its UI to a person.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "continuityDevicePickerDidEndPresenting"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVContinuityDevicePickerViewController",
          "text": "AVContinuityDevicePickerViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePickerDidEndPresenting(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "continuityDevicePickerDidEndPresenting:"
        }
      ],
      "role": "symbol",
      "title": "continuityDevicePickerDidEndPresenting(_:)",
      "type": "topic",
      "url": "/documentation/avkit/avcontinuitydevicepickerviewcontrollerdelegate/continuitydevicepickerdidendpresenting(_:)"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePickerWillBeginPresenting(_:)": {
      "abstract": [
        {
          "text": "Informs the delegate that a continuity device picker is about to present its UI so that a person can select and connect a continuity device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "continuityDevicePickerWillBeginPresenting"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVContinuityDevicePickerViewController",
          "text": "AVContinuityDevicePickerViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePickerWillBeginPresenting(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "continuityDevicePickerWillBeginPresenting:"
        }
      ],
      "role": "symbol",
      "title": "continuityDevicePickerWillBeginPresenting(_:)",
      "type": "topic",
      "url": "/documentation/avkit/avcontinuitydevicepickerviewcontrollerdelegate/continuitydevicepickerwillbeginpresenting(_:)"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVDisplayManager": {
      "abstract": [
        {
          "text": "A tvOS management object that controls whether a TV switches modes to match the video’s native mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVDisplayManager"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVDisplayManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVDisplayManager"
        }
      ],
      "role": "symbol",
      "title": "AVDisplayManager",
      "type": "topic",
      "url": "/documentation/avkit/avdisplaymanager"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVInterstitialTimeRange": {
      "abstract": [
        {
          "text": "A time range in an audiovisual presentation for content with an interstitial designation, such as advertisements or legal notices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVInterstitialTimeRange"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVInterstitialTimeRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVInterstitialTimeRange"
        }
      ],
      "role": "symbol",
      "title": "AVInterstitialTimeRange",
      "type": "topic",
      "url": "/documentation/avkit/avinterstitialtimerange"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVNavigationMarkersGroup": {
      "abstract": [
        {
          "text": "A set of markers for navigating playback of an audiovisual presentation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVNavigationMarkersGroup"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVNavigationMarkersGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVNavigationMarkersGroup"
        }
      ],
      "role": "symbol",
      "title": "AVNavigationMarkersGroup",
      "type": "topic",
      "url": "/documentation/avkit/avnavigationmarkersgroup"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController": {
      "abstract": [
        {
          "text": "A view controller that displays content from a player and presents a native user interface to control playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerViewController"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerViewController"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerViewController",
      "type": "topic",
      "url": "/documentation/avkit/avplayerviewcontroller"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate": {
      "abstract": [
        {
          "text": "A protocol that defines the methods to implement to respond to player view controller events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/avkit/avplayerviewcontrollerdelegate"
    },
    "doc://com.apple.avkit/documentation/AVKit/customizing-the-tvos-playback-experience": {
      "abstract": [
        {
          "text": "Adopt the latest features of the redesigned tvOS player user interface to provide a more streamlined way to watch your content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/customizing-the-tvos-playback-experience",
      "kind": "article",
      "role": "article",
      "title": "Customizing the tvOS Playback Experience",
      "type": "topic",
      "url": "/documentation/avkit/customizing-the-tvos-playback-experience"
    },
    "doc://com.apple.avkit/documentation/AVKit/presenting-content-proposals-in-tvos": {
      "abstract": [
        {
          "text": "Display a preview of an upcoming media item at the conclusion of the currently playing media item.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/presenting-content-proposals-in-tvos",
      "kind": "article",
      "role": "article",
      "title": "Presenting Content Proposals in tvOS",
      "type": "topic",
      "url": "/documentation/avkit/presenting-content-proposals-in-tvos"
    },
    "doc://com.apple.avkit/documentation/AVKit/presenting-navigation-markers": {
      "abstract": [
        {
          "text": "Present navigation markers in the Chapters panel to help users quickly navigate your content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/presenting-navigation-markers",
      "kind": "article",
      "role": "article",
      "title": "Presenting Navigation Markers",
      "type": "topic",
      "url": "/documentation/avkit/presenting-navigation-markers"
    },
    "doc://com.apple.avkit/documentation/AVKit/supporting-continuity-camera-in-your-tvos-app": {
      "abstract": [
        {
          "text": "Capture high-quality photos, video, and audio in your Apple TV app by connecting",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "an iPhone or iPad as a continuity device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/supporting-continuity-camera-in-your-tvos-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Supporting Continuity Camera in your tvOS app",
      "type": "topic",
      "url": "/documentation/avkit/supporting-continuity-camera-in-your-tvos-app"
    },
    "doc://com.apple.avkit/documentation/AVKit/working-with-interstitial-content": {
      "abstract": [
        {
          "text": "Present additional content alongside your main media presentation using HTTP Live Streaming support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/working-with-interstitial-content",
      "kind": "article",
      "role": "article",
      "title": "Working with Interstitial Content",
      "type": "topic",
      "url": "/documentation/avkit/working-with-interstitial-content"
    },
    "doc://com.apple.avkit/documentation/AVKit/working-with-overlays-and-parental-controls-in-tvos": {
      "abstract": [
        {
          "text": "Add interactive overlays, parental controls, and livestream channel flipping using a player view controller.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/working-with-overlays-and-parental-controls-in-tvos",
      "kind": "article",
      "role": "sampleCode",
      "title": "Working with Overlays and Parental Controls in tvOS",
      "type": "topic",
      "url": "/documentation/avkit/working-with-overlays-and-parental-controls-in-tvos"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "tvOS-Playback-and-Capture",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/customizing-the-tvos-playback-experience",
        "doc://com.apple.avkit/documentation/AVKit/presenting-navigation-markers",
        "doc://com.apple.avkit/documentation/AVKit/working-with-interstitial-content",
        "doc://com.apple.avkit/documentation/AVKit/presenting-content-proposals-in-tvos",
        "doc://com.apple.avkit/documentation/AVKit/working-with-overlays-and-parental-controls-in-tvos",
        "doc://com.apple.avkit/documentation/AVKit/supporting-continuity-camera-in-your-tvos-app",
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController",
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate",
        "doc://com.apple.avkit/documentation/AVKit/AVInterstitialTimeRange",
        "doc://com.apple.avkit/documentation/AVKit/AVNavigationMarkersGroup",
        "doc://com.apple.avkit/documentation/AVKit/AVContentProposalViewController",
        "doc://com.apple.avkit/documentation/AVKit/AVDisplayManager",
        "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewController"
      ],
      "title": "tvOS Playback and Capture"
    }
  ],
  "topicSections": [
    {
      "anchor": "Responding-to-continuity-device-events",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePickerWillBeginPresenting(_:)",
        "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePickerDidCancel(_:)",
        "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePicker(_:didConnect:)",
        "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePickerDidEndPresenting(_:)"
      ],
      "title": "Responding to continuity device events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVContinuityDevicePickerViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContinuityDevicePickerViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContinuityDevicePickerViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avkit/documentation/AVKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Responding-to-continuity-device-events",
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePickerWillBeginPresenting(_:)",
                "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePickerDidCancel(_:)",
                "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePicker(_:didConnect:)",
                "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate/continuityDevicePickerDidEndPresenting(_:)"
              ],
              "title": "Responding to continuity device events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "tvOS-Playback-and-Capture",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/customizing-the-tvos-playback-experience",
                "doc://com.apple.avkit/documentation/AVKit/presenting-navigation-markers",
                "doc://com.apple.avkit/documentation/AVKit/working-with-interstitial-content",
                "doc://com.apple.avkit/documentation/AVKit/presenting-content-proposals-in-tvos",
                "doc://com.apple.avkit/documentation/AVKit/working-with-overlays-and-parental-controls-in-tvos",
                "doc://com.apple.avkit/documentation/AVKit/supporting-continuity-camera-in-your-tvos-app",
                "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController",
                "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate",
                "doc://com.apple.avkit/documentation/AVKit/AVInterstitialTimeRange",
                "doc://com.apple.avkit/documentation/AVKit/AVNavigationMarkersGroup",
                "doc://com.apple.avkit/documentation/AVKit/AVContentProposalViewController",
                "doc://com.apple.avkit/documentation/AVKit/AVDisplayManager",
                "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewController"
              ],
              "title": "tvOS Playback and Capture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVContinuityDevicePickerViewControllerDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewControllerDelegate/title",
          "value": "AVContinuityDevicePickerViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContinuityDevicePickerViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContinuityDevicePickerViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate/title",
          "value": "AVPlayerViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVInterstitialTimeRange/title",
          "value": "AVInterstitialTimeRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVInterstitialTimeRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVInterstitialTimeRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVInterstitialTimeRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVInterstitialTimeRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVNavigationMarkersGroup/title",
          "value": "AVNavigationMarkersGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVNavigationMarkersGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVNavigationMarkersGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVNavigationMarkersGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVNavigationMarkersGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewControllerDelegate~1continuityDevicePickerDidEndPresenting(_:)/title",
          "value": "continuityDevicePickerDidEndPresenting:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewControllerDelegate~1continuityDevicePickerDidEndPresenting(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "continuityDevicePickerDidEndPresenting:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposalViewController/title",
          "value": "AVContentProposalViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposalViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentProposalViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposalViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentProposalViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewControllerDelegate~1continuityDevicePicker(_:didConnect:)/title",
          "value": "continuityDevicePicker:didConnectDevice:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewControllerDelegate~1continuityDevicePicker(_:didConnect:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "continuityDevicePicker:didConnectDevice:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewControllerDelegate~1continuityDevicePickerDidCancel(_:)/title",
          "value": "continuityDevicePickerDidCancel:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewControllerDelegate~1continuityDevicePickerDidCancel(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "continuityDevicePickerDidCancel:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewControllerDelegate~1continuityDevicePickerWillBeginPresenting(_:)/title",
          "value": "continuityDevicePickerWillBeginPresenting:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewControllerDelegate~1continuityDevicePickerWillBeginPresenting(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "continuityDevicePickerWillBeginPresenting:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewController~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewController~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVDisplayManager/title",
          "value": "AVDisplayManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVDisplayManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVDisplayManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVDisplayManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVDisplayManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewController/title",
          "value": "AVContinuityDevicePickerViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContinuityDevicePickerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContinuityDevicePickerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController/title",
          "value": "AVPlayerViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avkit/avcontinuitydevicepickerviewcontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avkit/avcontinuitydevicepickerviewcontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
