{
  "abstract": [
    {
      "text": "An object that describes the content to propose playing after the current item finishes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avkit/documentation/AVKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avkit/documentation/AVKit/AVContentProposal"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVContentProposal",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVContentProposal"
      }
    ],
    "modules": [
      {
        "name": "AVKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVContentProposal"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVContentProposal"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVContentProposal"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.avkit/documentation/AVKit/presenting-content-proposals-in-tvos"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A content proposal object models the data about the proposed content such as its title, preview image, presentation time, and content URL. You make a content proposal eligible for presentation by setting it as the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayerItem/nextContentProposal",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " of the current ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayerItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let proposal = AVContentProposal(contentTimeForTransition: time,",
            "                                 title: title,",
            "                                 previewImage: image)",
            "// Set the proposal as the nextContentProposal of the current player item",
            "currentPlayerItem.nextContentProposal = proposal"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avkit/documentation/AVKit": {
      "abstract": [
        {
          "text": "Create user interfaces for media playback, complete with transport controls, chapter navigation, picture-in-picture support, and display of subtitles and closed captions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AVKit",
      "type": "topic",
      "url": "/documentation/avkit"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContentProposal": {
      "abstract": [
        {
          "text": "An object that describes the content to propose playing after the current item finishes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContentProposal"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContentProposal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentProposal"
        }
      ],
      "role": "symbol",
      "title": "AVContentProposal",
      "type": "topic",
      "url": "/documentation/avkit/avcontentproposal"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/automaticAcceptanceInterval": {
      "abstract": [
        {
          "text": "The interval between the time playback ends and automatic acceptance of this content proposal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automaticAcceptanceInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/automaticAcceptanceInterval",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticAcceptanceInterval"
        }
      ],
      "role": "symbol",
      "title": "automaticAcceptanceInterval",
      "type": "topic",
      "url": "/documentation/avkit/avcontentproposal/automaticacceptanceinterval"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/contentTimeForTransition": {
      "abstract": [
        {
          "text": "The time within the timeline of the current player item when the content proposal presentation should begin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentTimeForTransition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/contentTimeForTransition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentTimeForTransition"
        }
      ],
      "role": "symbol",
      "title": "contentTimeForTransition",
      "type": "topic",
      "url": "/documentation/avkit/avcontentproposal/contenttimefortransition"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/init(contentTimeForTransition:title:previewImage:)": {
      "abstract": [
        {
          "text": "Creates a new content proposal with the specified transition time, title, and preview image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "contentTimeForTransition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "previewImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/init(contentTimeForTransition:title:previewImage:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithContentTimeForTransition:title:previewImage:"
        }
      ],
      "role": "symbol",
      "title": "init(contentTimeForTransition:title:previewImage:)",
      "type": "topic",
      "url": "/documentation/avkit/avcontentproposal/init(contenttimefortransition:title:previewimage:)"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/metadata": {
      "abstract": [
        {
          "text": "Optional custom metadata associated with the proposed item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMetadataItem",
          "text": "AVMetadataItem"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/metadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metadata"
        }
      ],
      "role": "symbol",
      "title": "metadata",
      "type": "topic",
      "url": "/documentation/avkit/avcontentproposal/metadata"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/previewImage": {
      "abstract": [
        {
          "text": "The preview image of the proposed item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previewImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/previewImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "previewImage"
        }
      ],
      "role": "symbol",
      "title": "previewImage",
      "type": "topic",
      "url": "/documentation/avkit/avcontentproposal/previewimage"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/title": {
      "abstract": [
        {
          "text": "The title of the proposed content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/avkit/avcontentproposal/title"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/url": {
      "abstract": [
        {
          "text": "The URL of the proposed content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/url",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "URL"
        }
      ],
      "role": "symbol",
      "title": "url",
      "type": "topic",
      "url": "/documentation/avkit/avcontentproposal/url"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContentProposalViewController/contentProposal": {
      "abstract": [
        {
          "text": "A prosal of content to play.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentProposal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVContentProposal",
          "text": "AVContentProposal"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContentProposalViewController/contentProposal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentProposal"
        }
      ],
      "role": "symbol",
      "title": "contentProposal",
      "type": "topic",
      "url": "/documentation/avkit/avcontentproposalviewcontroller/contentproposal"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContentProposalViewController/dateOfAutomaticAcceptance": {
      "abstract": [
        {
          "text": "The date that the system automatically accepts a proposal if the user doesn’t intervene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dateOfAutomaticAcceptance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContentProposalViewController/dateOfAutomaticAcceptance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dateOfAutomaticAcceptance"
        }
      ],
      "role": "symbol",
      "title": "dateOfAutomaticAcceptance",
      "type": "topic",
      "url": "/documentation/avkit/avcontentproposalviewcontroller/dateofautomaticacceptance"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContentProposalViewController/playerLayoutGuide": {
      "abstract": [
        {
          "text": "A layout guide that tracks the size and location of the player view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playerLayoutGuide"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UILayoutGuide",
          "text": "UILayoutGuide"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContentProposalViewController/playerLayoutGuide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playerLayoutGuide"
        }
      ],
      "role": "symbol",
      "title": "playerLayoutGuide",
      "type": "topic",
      "url": "/documentation/avkit/avcontentproposalviewcontroller/playerlayoutguide"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContentProposalViewController/preferredPlayerViewFrame": {
      "abstract": [
        {
          "text": "The preferred presentation frame of the player view while the content proposal is active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredPlayerViewFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContentProposalViewController/preferredPlayerViewFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredPlayerViewFrame"
        }
      ],
      "role": "symbol",
      "title": "preferredPlayerViewFrame",
      "type": "topic",
      "url": "/documentation/avkit/avcontentproposalviewcontroller/preferredplayerviewframe"
    },
    "doc://com.apple.avkit/documentation/AVKit/presenting-content-proposals-in-tvos": {
      "abstract": [
        {
          "text": "Display a preview of an upcoming media item at the conclusion of the currently playing media item.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/presenting-content-proposals-in-tvos",
      "kind": "article",
      "role": "article",
      "title": "Presenting Content Proposals in tvOS",
      "type": "topic",
      "url": "/documentation/avkit/presenting-content-proposals-in-tvos"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVPlayerItem": {
      "abstract": [
        {
          "text": "An object that models the timing and presentation state of an asset during playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerItem"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayerItem",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVPlayerItem",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVPlayerItem"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVPlayerItem/nextContentProposal": {
      "abstract": [
        {
          "text": "The item proposed to follow the current content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nextContentProposal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVContentProposal",
          "text": "AVContentProposal"
        },
        {
          "kind": "text",
          "text": "? { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayerItem/nextContentProposal",
      "kind": "symbol",
      "role": "symbol",
      "title": "nextContentProposal",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVPlayerItem/nextContentProposal"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-Proposal",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVContentProposalViewController/contentProposal",
        "doc://com.apple.avkit/documentation/AVKit/AVContentProposalViewController/dateOfAutomaticAcceptance",
        "doc://com.apple.avkit/documentation/AVKit/AVContentProposalViewController/playerLayoutGuide",
        "doc://com.apple.avkit/documentation/AVKit/AVContentProposalViewController/preferredPlayerViewFrame"
      ],
      "title": "Configuring the Proposal"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Content-Proposal",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/init(contentTimeForTransition:title:previewImage:)"
      ],
      "title": "Creating a Content Proposal"
    },
    {
      "anchor": "Configuring-the-Content-Proposal",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/contentTimeForTransition",
        "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/title",
        "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/previewImage",
        "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/metadata",
        "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/automaticAcceptanceInterval",
        "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/url"
      ],
      "title": "Configuring the Content Proposal"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVContentProposal"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentProposal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentProposal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avkit/documentation/AVKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Content-Proposal",
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/init(contentTimeForTransition:title:previewImage:)"
              ],
              "title": "Creating a Content Proposal"
            },
            {
              "anchor": "Configuring-the-Content-Proposal",
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/contentTimeForTransition",
                "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/title",
                "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/previewImage",
                "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/metadata",
                "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/automaticAcceptanceInterval",
                "doc://com.apple.avkit/documentation/AVKit/AVContentProposal/url"
              ],
              "title": "Configuring the Content Proposal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-Proposal",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVContentProposalViewController/contentProposal",
                "doc://com.apple.avkit/documentation/AVKit/AVContentProposalViewController/dateOfAutomaticAcceptance",
                "doc://com.apple.avkit/documentation/AVKit/AVContentProposalViewController/playerLayoutGuide",
                "doc://com.apple.avkit/documentation/AVKit/AVContentProposalViewController/preferredPlayerViewFrame"
              ],
              "title": "Configuring the Proposal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVContentProposal"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposalViewController~1preferredPlayerViewFrame/title",
          "value": "preferredPlayerViewFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposalViewController~1preferredPlayerViewFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredPlayerViewFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVPlayerItem/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVPlayerItem"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVPlayerItem~1nextContentProposal/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "strong"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVContentProposal",
              "text": "AVContentProposal"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "nextContentProposal"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposalViewController~1contentProposal/title",
          "value": "contentProposal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposalViewController~1contentProposal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentProposal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal~1init(contentTimeForTransition:title:previewImage:)/title",
          "value": "initWithContentTimeForTransition:title:previewImage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal~1init(contentTimeForTransition:title:previewImage:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithContentTimeForTransition:title:previewImage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal~1metadata/title",
          "value": "metadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal~1metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposalViewController~1playerLayoutGuide/title",
          "value": "playerLayoutGuide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposalViewController~1playerLayoutGuide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playerLayoutGuide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal~1title/title",
          "value": "title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal~1url/title",
          "value": "URL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal~1url/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "URL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal/title",
          "value": "AVContentProposal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentProposal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentProposal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal~1contentTimeForTransition/title",
          "value": "contentTimeForTransition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal~1contentTimeForTransition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentTimeForTransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal~1previewImage/title",
          "value": "previewImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal~1previewImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "previewImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal~1automaticAcceptanceInterval/title",
          "value": "automaticAcceptanceInterval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposal~1automaticAcceptanceInterval/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticAcceptanceInterval"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposalViewController~1dateOfAutomaticAcceptance/title",
          "value": "dateOfAutomaticAcceptance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposalViewController~1dateOfAutomaticAcceptance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dateOfAutomaticAcceptance"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avkit/avcontentproposal"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avkit/avcontentproposal"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
