{
  "abstract": [
    {
      "text": "An object that controls video experiences.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avkit/documentation/AVKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avkit/documentation/AVKit/AVExperienceController"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:5AVKit22AVExperienceControllerC",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVExperienceController"
      }
    ],
    "modules": [
      {
        "name": "AVKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVExperienceController"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVExperienceController"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "final"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVExperienceController"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this class to control, observe, and respond to experience changes for an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". A player view controller’s presentation APIs will no longer be honored after attaching an experience controller. Using the other presentation APIs may preclude the use of this class.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avkit/documentation/AVKit": {
      "abstract": [
        {
          "text": "Create user interfaces for media playback, complete with transport controls, chapter navigation, picture-in-picture support, and display of subtitles and closed captions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AVKit",
      "type": "topic",
      "url": "/documentation/avkit"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVExperienceController": {
      "abstract": [
        {
          "text": "An object that controls video experiences.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVExperienceController"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVExperienceController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVExperienceController"
        }
      ],
      "role": "symbol",
      "title": "AVExperienceController",
      "type": "topic",
      "url": "/documentation/avkit/avexperiencecontroller"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/Configuration-swift.struct": {
      "abstract": [
        {
          "text": "A structure that stores per-experience configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/Configuration-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "role": "symbol",
      "title": "AVExperienceController.Configuration",
      "type": "topic",
      "url": "/documentation/avkit/avexperiencecontroller/configuration-swift.struct"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/Delegate-swift.protocol": {
      "abstract": [
        {
          "text": "A protocol that defines the methods to implement to respond to experience changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Delegate"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/Delegate-swift.protocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Delegate"
        }
      ],
      "role": "symbol",
      "title": "AVExperienceController.Delegate",
      "type": "topic",
      "url": "/documentation/avkit/avexperiencecontroller/delegate-swift.protocol"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/ExpandedConfiguration": {
      "abstract": [
        {
          "text": "A structure that specifies options for an expanded experience.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpandedConfiguration"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/ExpandedConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ExpandedConfiguration"
        }
      ],
      "role": "symbol",
      "title": "AVExperienceController.ExpandedConfiguration",
      "type": "topic",
      "url": "/documentation/avkit/avexperiencecontroller/expandedconfiguration"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/Experience-swift.enum": {
      "abstract": [
        {
          "text": "The types of experiences the system supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Experience"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/Experience-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Experience"
        }
      ],
      "role": "symbol",
      "title": "AVExperienceController.Experience",
      "type": "topic",
      "url": "/documentation/avkit/avexperiencecontroller/experience-swift.enum"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/Experiences": {
      "abstract": [
        {
          "text": "A structure that represents a collection of experiences to use with an experience controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Experiences"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/Experiences",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Experiences"
        }
      ],
      "role": "symbol",
      "title": "AVExperienceController.Experiences",
      "type": "topic",
      "url": "/documentation/avkit/avexperiencecontroller/experiences"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/TransitionContext": {
      "abstract": [
        {
          "text": "The state of the transition provided to the delegate object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TransitionContext"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/TransitionContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TransitionContext"
        }
      ],
      "role": "symbol",
      "title": "AVExperienceController.TransitionContext",
      "type": "topic",
      "url": "/documentation/avkit/avexperiencecontroller/transitioncontext"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/allowedExperiences": {
      "abstract": [
        {
          "text": "The set of experiences the application supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowedExperiences"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5AVKit22AVExperienceControllerC",
          "text": "AVExperienceController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5AVKit22AVExperienceControllerC11ExperiencesV",
          "text": "Experiences"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/allowedExperiences",
      "kind": "symbol",
      "role": "symbol",
      "title": "allowedExperiences",
      "type": "topic",
      "url": "/documentation/avkit/avexperiencecontroller/allowedexperiences"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/availableExperiences": {
      "abstract": [
        {
          "text": "The allowed experiences that are available to use on the device at this time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availableExperiences"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5AVKit22AVExperienceControllerC",
          "text": "AVExperienceController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5AVKit22AVExperienceControllerC11ExperiencesV",
          "text": "Experiences"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/availableExperiences",
      "kind": "symbol",
      "role": "symbol",
      "title": "availableExperiences",
      "type": "topic",
      "url": "/documentation/avkit/avexperiencecontroller/availableexperiences"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/configuration-swift.property": {
      "abstract": [
        {
          "text": "The configuration options per experience.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5AVKit22AVExperienceControllerC",
          "text": "AVExperienceController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5AVKit22AVExperienceControllerC13ConfigurationV",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/configuration-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "configuration",
      "type": "topic",
      "url": "/documentation/avkit/avexperiencecontroller/configuration-swift.property"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/delegate-swift.property": {
      "abstract": [
        {
          "text": "A delegate object for the experience controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5AVKit22AVExperienceControllerC",
          "text": "AVExperienceController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5AVKit22AVExperienceControllerC8DelegateP",
          "text": "Delegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/delegate-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/avkit/avexperiencecontroller/delegate-swift.property"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/experience-swift.property": {
      "abstract": [
        {
          "text": "The current experience.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "experience"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5AVKit22AVExperienceControllerC",
          "text": "AVExperienceController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5AVKit22AVExperienceControllerC10ExperienceO",
          "text": "Experience"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/experience-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "experience",
      "type": "topic",
      "url": "/documentation/avkit/avexperiencecontroller/experience-swift.property"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/transition(to:)": {
      "abstract": [
        {
          "text": "Transitions the video to a different experience.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transition"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5AVKit22AVExperienceControllerC",
          "text": "AVExperienceController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5AVKit22AVExperienceControllerC10ExperienceO",
          "text": "Experience"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5AVKit22AVExperienceControllerC",
          "text": "AVExperienceController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5AVKit22AVExperienceControllerC17TransitionContextV",
          "text": "TransitionContext"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5AVKit22AVExperienceControllerC17TransitionContextV0D6ResultO",
          "text": "TransitionResult"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/transition(to:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "transition(to:)",
      "type": "topic",
      "url": "/documentation/avkit/avexperiencecontroller/transition(to:)"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVGroupExperienceCoordinator": {
      "abstract": [
        {
          "text": "An object that synchronizes viewing environment state across participants in a SharePlay session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVGroupExperienceCoordinator"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVGroupExperienceCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVGroupExperienceCoordinator"
        }
      ],
      "role": "symbol",
      "title": "AVGroupExperienceCoordinator",
      "type": "topic",
      "url": "/documentation/avkit/avgroupexperiencecoordinator"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVMultiviewManager": {
      "abstract": [
        {
          "text": "An object that manages viewing multiple videos at once.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMultiviewManager"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVMultiviewManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMultiviewManager"
        }
      ],
      "role": "symbol",
      "title": "AVMultiviewManager",
      "type": "topic",
      "url": "/documentation/avkit/avmultiviewmanager"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController": {
      "abstract": [
        {
          "text": "A view controller that displays content from a player and presents a native user interface to control playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerViewController"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerViewController"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerViewController",
      "type": "topic",
      "url": "/documentation/avkit/avplayerviewcontroller"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate": {
      "abstract": [
        {
          "text": "A protocol that defines the methods to implement to respond to player view controller events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/avkit/avplayerviewcontrollerdelegate"
    },
    "doc://com.apple.avkit/documentation/AVKit/adopting-the-system-player-interface-in-visionos": {
      "abstract": [
        {
          "text": "Provide an optimized viewing experience for watching 3D video content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/adopting-the-system-player-interface-in-visionos",
      "kind": "article",
      "role": "article",
      "title": "Adopting the system player interface in visionOS",
      "type": "topic",
      "url": "/documentation/avkit/adopting-the-system-player-interface-in-visionos"
    },
    "doc://com.apple.avkit/documentation/AVKit/creating-a-multiview-video-playback-experience-in-visionos": {
      "abstract": [
        {
          "text": "Build an interface that plays multiple videos simultaneously and handles transitions to different experience types gracefully.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/creating-a-multiview-video-playback-experience-in-visionos",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating a multiview video playback experience in visionOS",
      "type": "topic",
      "url": "/documentation/avkit/creating-a-multiview-video-playback-experience-in-visionos"
    },
    "doc://com.apple.avkit/documentation/AVKit/trimming-and-exporting-media-in-visionos": {
      "abstract": [
        {
          "text": "Display standard controls in your app to edit the timeline of the currently playing media.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/trimming-and-exporting-media-in-visionos",
      "kind": "article",
      "role": "article",
      "title": "Trimming and exporting media in visionOS",
      "type": "topic",
      "url": "/documentation/avkit/trimming-and-exporting-media-in-visionos"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "visionOS-Playback",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/creating-a-multiview-video-playback-experience-in-visionos",
        "doc://com.apple.avkit/documentation/AVKit/adopting-the-system-player-interface-in-visionos",
        "doc://com.apple.avkit/documentation/AVKit/trimming-and-exporting-media-in-visionos",
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController",
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate",
        "doc://com.apple.avkit/documentation/AVKit/AVMultiviewManager",
        "doc://com.apple.avkit/documentation/AVKit/AVGroupExperienceCoordinator"
      ],
      "title": "visionOS Playback"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuring-the-experience",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/allowedExperiences",
        "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/availableExperiences",
        "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/Experiences",
        "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/experience-swift.property",
        "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/Experience-swift.enum",
        "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/configuration-swift.property",
        "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/Configuration-swift.struct"
      ],
      "title": "Configuring the experience"
    },
    {
      "anchor": "Transitioning-experiences",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/transition(to:)"
      ],
      "title": "Transitioning experiences"
    },
    {
      "anchor": "Configuring-a-delegate",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/delegate-swift.property",
        "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/Delegate-swift.protocol"
      ],
      "title": "Configuring a delegate"
    },
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/ExpandedConfiguration",
        "doc://com.apple.avkit/documentation/AVKit/AVExperienceController/TransitionContext"
      ],
      "title": "Structures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController/title",
          "value": "AVPlayerViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate/title",
          "value": "AVPlayerViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerViewControllerDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avkit/avexperiencecontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
