{
  "abstract": [
    {
      "text": "The identifier for an external user profile published through the Now Playing Info Center.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avkit/documentation/AVKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierExternalUserProfileIdentifier"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@AVKitMetadataIdentifierExternalUserProfileIdentifier",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVKitMetadataIdentifierExternalUserProfileIdentifier"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "AVKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVKitMetadataIdentifierExternalUserProfileIdentifier"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.1",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "AVKitMetadataIdentifierExternalUserProfileIdentifier"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVKitMetadataIdentifierExternalUserProfileIdentifier"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avkit/documentation/AVKit": {
      "abstract": [
        {
          "text": "Create user interfaces for media playback, complete with transport controls, chapter navigation, picture-in-picture support, and display of subtitles and closed captions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AVKit",
      "type": "topic",
      "url": "/documentation/avkit"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierExternalContentIdentifier": {
      "abstract": [
        {
          "text": "The identifier for external content published through the Now Playing Info Center.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVKitMetadataIdentifierExternalContentIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierExternalContentIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVKitMetadataIdentifierExternalContentIdentifier"
        }
      ],
      "role": "symbol",
      "title": "AVKitMetadataIdentifierExternalContentIdentifier",
      "type": "topic",
      "url": "/documentation/avkit/avkitmetadataidentifierexternalcontentidentifier"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierExternalUserProfileIdentifier": {
      "abstract": [
        {
          "text": "The identifier for an external user profile published through the Now Playing Info Center.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVKitMetadataIdentifierExternalUserProfileIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierExternalUserProfileIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVKitMetadataIdentifierExternalUserProfileIdentifier"
        }
      ],
      "role": "symbol",
      "title": "AVKitMetadataIdentifierExternalUserProfileIdentifier",
      "type": "topic",
      "url": "/documentation/avkit/avkitmetadataidentifierexternaluserprofileidentifier"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierPlaybackProgress": {
      "abstract": [
        {
          "text": "The playback progress published through the Now Playing Info Center.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVKitMetadataIdentifierPlaybackProgress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierPlaybackProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVKitMetadataIdentifierPlaybackProgress"
        }
      ],
      "role": "symbol",
      "title": "AVKitMetadataIdentifierPlaybackProgress",
      "type": "topic",
      "url": "/documentation/avkit/avkitmetadataidentifierplaybackprogress"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierServiceIdentifier": {
      "abstract": [
        {
          "text": "The service identifier published through the Now Playing Info Center.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVKitMetadataIdentifierServiceIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierServiceIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVKitMetadataIdentifierServiceIdentifier"
        }
      ],
      "role": "symbol",
      "title": "AVKitMetadataIdentifierServiceIdentifier",
      "type": "topic",
      "url": "/documentation/avkit/avkitmetadataidentifierserviceidentifier"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Nondisplayed-Metadata",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierPlaybackProgress",
        "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierExternalContentIdentifier",
        "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierServiceIdentifier"
      ],
      "title": "Nondisplayed Metadata"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.1",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVKitMetadataIdentifierExternalUserProfileIdentifier"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVKitMetadataIdentifierExternalUserProfileIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avkit/documentation/AVKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Nondisplayed-Metadata",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierPlaybackProgress",
                "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierExternalContentIdentifier",
                "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierServiceIdentifier"
              ],
              "title": "Nondisplayed Metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVKitMetadataIdentifierExternalUserProfileIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitMetadataIdentifierExternalContentIdentifier/title",
          "value": "AVKitMetadataIdentifierExternalContentIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitMetadataIdentifierExternalContentIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVKitMetadataIdentifierExternalContentIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitMetadataIdentifierPlaybackProgress/title",
          "value": "AVKitMetadataIdentifierPlaybackProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitMetadataIdentifierPlaybackProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVKitMetadataIdentifierPlaybackProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitMetadataIdentifierServiceIdentifier/title",
          "value": "AVKitMetadataIdentifierServiceIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitMetadataIdentifierServiceIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVKitMetadataIdentifierServiceIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitMetadataIdentifierExternalUserProfileIdentifier/title",
          "value": "AVKitMetadataIdentifierExternalUserProfileIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitMetadataIdentifierExternalUserProfileIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVKitMetadataIdentifierExternalUserProfileIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avkit/avkitmetadataidentifierexternaluserprofileidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avkit/avkitmetadataidentifierexternaluserprofileidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
