{
  "abstract": [
    {
      "text": "Additional metadata that an asset contains.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avkit/documentation/AVKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avkit/documentation/AVKit/avkit-metadata-identifiers"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "AVKit Metadata Identifiers"
  },
  "references": {
    "doc://com.apple.avkit/documentation/AVKit": {
      "abstract": [
        {
          "text": "Create user interfaces for media playback, complete with transport controls, chapter navigation, picture-in-picture support, and display of subtitles and closed captions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AVKit",
      "type": "topic",
      "url": "/documentation/avkit"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierApproximateEndDate": {
      "abstract": [
        {
          "text": "The approximate end date for a live event stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVKitMetadataIdentifierApproximateEndDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierApproximateEndDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVKitMetadataIdentifierApproximateEndDate"
        }
      ],
      "role": "symbol",
      "title": "AVKitMetadataIdentifierApproximateEndDate",
      "type": "topic",
      "url": "/documentation/avkit/avkitmetadataidentifierapproximateenddate"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierApproximateStartDate": {
      "abstract": [
        {
          "text": "The approximate start date for a live event stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVKitMetadataIdentifierApproximateStartDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierApproximateStartDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVKitMetadataIdentifierApproximateStartDate"
        }
      ],
      "role": "symbol",
      "title": "AVKitMetadataIdentifierApproximateStartDate",
      "type": "topic",
      "url": "/documentation/avkit/avkitmetadataidentifierapproximatestartdate"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierExactEndDate": {
      "abstract": [
        {
          "text": "The exact end date for a live event stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVKitMetadataIdentifierExactEndDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierExactEndDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVKitMetadataIdentifierExactEndDate"
        }
      ],
      "role": "symbol",
      "title": "AVKitMetadataIdentifierExactEndDate",
      "type": "topic",
      "url": "/documentation/avkit/avkitmetadataidentifierexactenddate"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierExactStartDate": {
      "abstract": [
        {
          "text": "The exact start date for a live event stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVKitMetadataIdentifierExactStartDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierExactStartDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVKitMetadataIdentifierExactStartDate"
        }
      ],
      "role": "symbol",
      "title": "AVKitMetadataIdentifierExactStartDate",
      "type": "topic",
      "url": "/documentation/avkit/avkitmetadataidentifierexactstartdate"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierExternalContentIdentifier": {
      "abstract": [
        {
          "text": "The identifier for external content published through the Now Playing Info Center.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVKitMetadataIdentifierExternalContentIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierExternalContentIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVKitMetadataIdentifierExternalContentIdentifier"
        }
      ],
      "role": "symbol",
      "title": "AVKitMetadataIdentifierExternalContentIdentifier",
      "type": "topic",
      "url": "/documentation/avkit/avkitmetadataidentifierexternalcontentidentifier"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierExternalUserProfileIdentifier": {
      "abstract": [
        {
          "text": "The identifier for an external user profile published through the Now Playing Info Center.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVKitMetadataIdentifierExternalUserProfileIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierExternalUserProfileIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVKitMetadataIdentifierExternalUserProfileIdentifier"
        }
      ],
      "role": "symbol",
      "title": "AVKitMetadataIdentifierExternalUserProfileIdentifier",
      "type": "topic",
      "url": "/documentation/avkit/avkitmetadataidentifierexternaluserprofileidentifier"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierPlaybackProgress": {
      "abstract": [
        {
          "text": "The playback progress published through the Now Playing Info Center.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVKitMetadataIdentifierPlaybackProgress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierPlaybackProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVKitMetadataIdentifierPlaybackProgress"
        }
      ],
      "role": "symbol",
      "title": "AVKitMetadataIdentifierPlaybackProgress",
      "type": "topic",
      "url": "/documentation/avkit/avkitmetadataidentifierplaybackprogress"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierServiceIdentifier": {
      "abstract": [
        {
          "text": "The service identifier published through the Now Playing Info Center.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVKitMetadataIdentifierServiceIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierServiceIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVKitMetadataIdentifierServiceIdentifier"
        }
      ],
      "role": "symbol",
      "title": "AVKitMetadataIdentifierServiceIdentifier",
      "type": "topic",
      "url": "/documentation/avkit/avkitmetadataidentifierserviceidentifier"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Displayed-Metadata",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierExactStartDate",
        "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierExactEndDate",
        "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierApproximateStartDate",
        "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierApproximateEndDate"
      ],
      "title": "Displayed Metadata"
    },
    {
      "anchor": "Nondisplayed-Metadata",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierPlaybackProgress",
        "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierExternalContentIdentifier",
        "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierExternalUserProfileIdentifier",
        "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierServiceIdentifier"
      ],
      "title": "Nondisplayed Metadata"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Displayed-Metadata",
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierExactStartDate",
                "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierExactEndDate",
                "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierApproximateStartDate",
                "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierApproximateEndDate"
              ],
              "title": "Displayed Metadata"
            },
            {
              "anchor": "Nondisplayed-Metadata",
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierPlaybackProgress",
                "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierExternalContentIdentifier",
                "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierExternalUserProfileIdentifier",
                "doc://com.apple.avkit/documentation/AVKit/AVKitMetadataIdentifierServiceIdentifier"
              ],
              "title": "Nondisplayed Metadata"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitMetadataIdentifierExternalContentIdentifier/title",
          "value": "AVKitMetadataIdentifierExternalContentIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitMetadataIdentifierExternalContentIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVKitMetadataIdentifierExternalContentIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitMetadataIdentifierServiceIdentifier/title",
          "value": "AVKitMetadataIdentifierServiceIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitMetadataIdentifierServiceIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVKitMetadataIdentifierServiceIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitMetadataIdentifierApproximateEndDate/title",
          "value": "AVKitMetadataIdentifierApproximateEndDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitMetadataIdentifierApproximateEndDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVKitMetadataIdentifierApproximateEndDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitMetadataIdentifierExternalUserProfileIdentifier/title",
          "value": "AVKitMetadataIdentifierExternalUserProfileIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitMetadataIdentifierExternalUserProfileIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVKitMetadataIdentifierExternalUserProfileIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitMetadataIdentifierPlaybackProgress/title",
          "value": "AVKitMetadataIdentifierPlaybackProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitMetadataIdentifierPlaybackProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVKitMetadataIdentifierPlaybackProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitMetadataIdentifierExactEndDate/title",
          "value": "AVKitMetadataIdentifierExactEndDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitMetadataIdentifierExactEndDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVKitMetadataIdentifierExactEndDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitMetadataIdentifierExactStartDate/title",
          "value": "AVKitMetadataIdentifierExactStartDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitMetadataIdentifierExactStartDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVKitMetadataIdentifierExactStartDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitMetadataIdentifierApproximateStartDate/title",
          "value": "AVKitMetadataIdentifierApproximateStartDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitMetadataIdentifierApproximateStartDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVKitMetadataIdentifierApproximateStartDate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avkit/avkit-metadata-identifiers"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avkit/avkit-metadata-identifiers"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
