{
  "abstract": [
    {
      "text": "A controller that responds to user-initiated Picture in Picture playback of video in a floating, resizable window.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avkit/documentation/AVKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVPictureInPictureController",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVPictureInPictureController"
      }
    ],
    "modules": [
      {
        "name": "AVKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVPictureInPictureController"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVPictureInPictureController"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVPictureInPictureController"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-in-a-custom-player",
        "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-for-video-calls"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To use Picture in Picture, you need to configure your app to support background audio playback. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/configuring-your-app-for-media-playback",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more details.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Before presenting a user interface to start Picture in Picture, call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/isPictureInPictureSupported()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to determine if the current device supports the feature, and check the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/isPictureInPicturePossible",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property value to determine whether PiP is possible in the current context.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The framework doesn’t support subclassing ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avkit/documentation/AVKit": {
      "abstract": [
        {
          "text": "Create user interfaces for media playback, complete with transport controls, chapter navigation, picture-in-picture support, and display of subtitles and closed captions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AVKit",
      "type": "topic",
      "url": "/documentation/avkit"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController": {
      "abstract": [
        {
          "text": "A controller that responds to user-initiated Picture in Picture playback of video in a floating, resizable window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPictureInPictureController"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPictureInPictureController"
        }
      ],
      "role": "symbol",
      "title": "AVPictureInPictureController",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturecontroller"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/ContentSource-swift.class": {
      "abstract": [
        {
          "text": "An object that represents the source of the content to present in Picture in Picture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ContentSource"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/ContentSource-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ContentSource"
        }
      ],
      "role": "symbol",
      "title": "AVPictureInPictureController.ContentSource",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturecontroller/contentsource-swift.class"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/canStartPictureInPictureAutomaticallyFromInline": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether Picture in Picture starts automatically when the controller embeds its content inline and the app transitions to the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canStartPictureInPictureAutomaticallyFromInline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/canStartPictureInPictureAutomaticallyFromInline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canStartPictureInPictureAutomaticallyFromInline"
        }
      ],
      "role": "symbol",
      "title": "canStartPictureInPictureAutomaticallyFromInline",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturecontroller/canstartpictureinpictureautomaticallyfrominline"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/canStopPictureInPicture": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether Picture in Picture is active and is able to stop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canStopPictureInPicture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/canStopPictureInPicture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canStopPictureInPicture"
        }
      ],
      "role": "symbol",
      "title": "canStopPictureInPicture",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturecontroller/canstoppictureinpicture"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/contentSource-swift.property": {
      "abstract": [
        {
          "text": "The source of the controller’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPictureInPictureController",
          "text": "AVPictureInPictureController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPictureInPictureControllerContentSource",
          "text": "ContentSource"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/contentSource-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentSource"
        }
      ],
      "role": "symbol",
      "title": "contentSource",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturecontroller/contentsource-swift.property"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/delegate": {
      "abstract": [
        {
          "text": "A delegate object for a Picture in Picture controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)AVPictureInPictureControllerDelegate",
          "text": "AVPictureInPictureControllerDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturecontroller/delegate"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/init(contentSource:)": {
      "abstract": [
        {
          "text": "Creates a Picture in Picture controller with a content source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "contentSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPictureInPictureController",
          "text": "AVPictureInPictureController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPictureInPictureControllerContentSource",
          "text": "ContentSource"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/init(contentSource:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithContentSource:"
        }
      ],
      "role": "symbol",
      "title": "init(contentSource:)",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturecontroller/init(contentsource:)"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/init(playerLayer:)": {
      "abstract": [
        {
          "text": "Creates a Picture in Picture controller with a player layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "playerLayer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPlayerLayer",
          "text": "AVPlayerLayer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/init(playerLayer:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithPlayerLayer:"
        }
      ],
      "role": "symbol",
      "title": "init(playerLayer:)",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturecontroller/init(playerlayer:)"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/invalidatePlaybackState()": {
      "abstract": [
        {
          "text": "Invalidates the controller’s current playback state and fetches the updated state from the sample buffer playback delegate object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidatePlaybackState"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/invalidatePlaybackState()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "invalidatePlaybackState"
        }
      ],
      "role": "symbol",
      "title": "invalidatePlaybackState()",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturecontroller/invalidateplaybackstate()"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/isPictureInPictureActive": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the Picture in Picture window is onscreen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPictureInPictureActive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/isPictureInPictureActive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pictureInPictureActive"
        }
      ],
      "role": "symbol",
      "title": "isPictureInPictureActive",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturecontroller/ispictureinpictureactive"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/isPictureInPicturePossible": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether Picture in Picture playback is currently possible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPictureInPicturePossible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/isPictureInPicturePossible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pictureInPicturePossible"
        }
      ],
      "role": "symbol",
      "title": "isPictureInPicturePossible",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturecontroller/ispictureinpicturepossible"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/isPictureInPictureSupported()": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the current device supports Picture in Picture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPictureInPictureSupported"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/isPictureInPictureSupported()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isPictureInPictureSupported"
        }
      ],
      "role": "symbol",
      "title": "isPictureInPictureSupported()",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturecontroller/ispictureinpicturesupported()"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/isPictureInPictureSuspended": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the system suspends the controller’s Picture in Picture window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPictureInPictureSuspended"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/isPictureInPictureSuspended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pictureInPictureSuspended"
        }
      ],
      "role": "symbol",
      "title": "isPictureInPictureSuspended",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturecontroller/ispictureinpicturesuspended"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/pictureInPictureButtonStartImage": {
      "abstract": [
        {
          "text": "A system-default template image for the button that starts Picture in Picture in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pictureInPictureButtonStartImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/pictureInPictureButtonStartImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pictureInPictureButtonStartImage"
        }
      ],
      "role": "symbol",
      "title": "pictureInPictureButtonStartImage",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturecontroller/pictureinpicturebuttonstartimage"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/pictureInPictureButtonStartImage(compatibleWith:)": {
      "abstract": [
        {
          "text": "Returns a system-default template image that’s compatible with a trait collection for the button that starts Picture in Picture in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pictureInPictureButtonStartImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "compatibleWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITraitCollection",
          "text": "UITraitCollection"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/pictureInPictureButtonStartImage(compatibleWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pictureInPictureButtonStartImageCompatibleWithTraitCollection:"
        }
      ],
      "role": "symbol",
      "title": "pictureInPictureButtonStartImage(compatibleWith:)",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturecontroller/pictureinpicturebuttonstartimage(compatiblewith:)"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/pictureInPictureButtonStopImage": {
      "abstract": [
        {
          "text": "A system-default template image for the button that stops Picture in Picture in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pictureInPictureButtonStopImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/pictureInPictureButtonStopImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pictureInPictureButtonStopImage"
        }
      ],
      "role": "symbol",
      "title": "pictureInPictureButtonStopImage",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturecontroller/pictureinpicturebuttonstopimage"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/pictureInPictureButtonStopImage(compatibleWith:)": {
      "abstract": [
        {
          "text": "Returns a system-default template image that’s compatible with a trait collection for the button that stops Picture in Picture in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pictureInPictureButtonStopImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "compatibleWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITraitCollection",
          "text": "UITraitCollection"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/pictureInPictureButtonStopImage(compatibleWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pictureInPictureButtonStopImageCompatibleWithTraitCollection:"
        }
      ],
      "role": "symbol",
      "title": "pictureInPictureButtonStopImage(compatibleWith:)",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturecontroller/pictureinpicturebuttonstopimage(compatiblewith:)"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/playerLayer": {
      "abstract": [
        {
          "text": "The layer that displays the video content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playerLayer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPlayerLayer",
          "text": "AVPlayerLayer"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/playerLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playerLayer"
        }
      ],
      "role": "symbol",
      "title": "playerLayer",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturecontroller/playerlayer"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/requiresLinearPlayback": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the controller allows the user to skip media content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requiresLinearPlayback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/requiresLinearPlayback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requiresLinearPlayback"
        }
      ],
      "role": "symbol",
      "title": "requiresLinearPlayback",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturecontroller/requireslinearplayback"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/startPictureInPicture()": {
      "abstract": [
        {
          "text": "Starts Picture in Picture, if possible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startPictureInPicture"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/startPictureInPicture()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startPictureInPicture"
        }
      ],
      "role": "symbol",
      "title": "startPictureInPicture()",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturecontroller/startpictureinpicture()"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/stopPictureInPicture()": {
      "abstract": [
        {
          "text": "Stops Picture in Picture, if active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopPictureInPicture"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/stopPictureInPicture()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopPictureInPicture"
        }
      ],
      "role": "symbol",
      "title": "stopPictureInPicture()",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturecontroller/stoppictureinpicture()"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureControllerDelegate": {
      "abstract": [
        {
          "text": "A protocol to adopt to respond to Picture in Picture events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPictureInPictureControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPictureInPictureControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "AVPictureInPictureControllerDelegate",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturecontrollerdelegate"
    },
    "doc://com.apple.avkit/documentation/AVKit/accessing-the-camera-while-multitasking-on-ipad": {
      "abstract": [
        {
          "text": "Operate the camera in Split View, Slide Over, Picture in Picture, and Stage Manager modes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/accessing-the-camera-while-multitasking-on-ipad",
      "kind": "article",
      "role": "article",
      "title": "Accessing the camera while multitasking on iPad",
      "type": "topic",
      "url": "/documentation/avkit/accessing-the-camera-while-multitasking-on-ipad"
    },
    "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-for-video-calls": {
      "abstract": [
        {
          "text": "Add multitasking capability to your video-call apps by using Picture in Picture (PiP).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-for-video-calls",
      "kind": "article",
      "role": "article",
      "title": "Adopting Picture in Picture for video calls",
      "type": "topic",
      "url": "/documentation/avkit/adopting-picture-in-picture-for-video-calls"
    },
    "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-in-a-custom-player": {
      "abstract": [
        {
          "text": "Add controls to your custom player user interface to invoke Picture in Picture (PiP) playback.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-in-a-custom-player",
      "kind": "article",
      "role": "article",
      "title": "Adopting Picture in Picture in a Custom Player",
      "type": "topic",
      "url": "/documentation/avkit/adopting-picture-in-picture-in-a-custom-player"
    },
    "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-in-a-standard-player": {
      "abstract": [
        {
          "text": "Add Picture in Picture (PiP) playback to your app using a player view controller.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-in-a-standard-player",
      "kind": "article",
      "role": "article",
      "title": "Adopting Picture in Picture in a Standard Player",
      "type": "topic",
      "url": "/documentation/avkit/adopting-picture-in-picture-in-a-standard-player"
    },
    "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-playback-in-tvos": {
      "abstract": [
        {
          "text": "Add advanced multitasking capabilities to your video apps by using Picture in Picture playback in tvOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-playback-in-tvos",
      "kind": "article",
      "role": "sampleCode",
      "title": "Adopting Picture in Picture Playback in tvOS",
      "type": "topic",
      "url": "/documentation/avkit/adopting-picture-in-picture-playback-in-tvos"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/configuring-your-app-for-media-playback": {
      "abstract": [
        {
          "text": "Configure apps to enable standard media playback behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/configuring-your-app-for-media-playback",
      "kind": "article",
      "role": "article",
      "title": "Configuring your app for media playback",
      "type": "topic",
      "url": "/documentation/AVFoundation/configuring-your-app-for-media-playback"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Picture-in-Picture",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-playback-in-tvos",
        "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-in-a-standard-player",
        "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-in-a-custom-player",
        "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-for-video-calls",
        "doc://com.apple.avkit/documentation/AVKit/accessing-the-camera-while-multitasking-on-ipad"
      ],
      "title": "Picture in Picture"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Controller",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/init(contentSource:)",
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/init(playerLayer:)"
      ],
      "title": "Creating a Controller"
    },
    {
      "anchor": "Configuring-the-Content-Source",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/contentSource-swift.property",
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/ContentSource-swift.class"
      ],
      "title": "Configuring the Content Source"
    },
    {
      "anchor": "Accessing-the-Player-Layer",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/playerLayer"
      ],
      "title": "Accessing the Player Layer"
    },
    {
      "anchor": "Configuring-Playback-Behavior",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/requiresLinearPlayback"
      ],
      "title": "Configuring Playback Behavior"
    },
    {
      "anchor": "Accessing-the-Delegate-Object",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/delegate",
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureControllerDelegate"
      ],
      "title": "Accessing the Delegate Object"
    },
    {
      "anchor": "Accessing-Picture-in-Picture-State",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/isPictureInPictureSupported()",
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/isPictureInPicturePossible",
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/isPictureInPictureActive",
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/isPictureInPictureSuspended"
      ],
      "title": "Accessing Picture in Picture State"
    },
    {
      "anchor": "Controlling-Picture-in-Picture-Playback",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/canStopPictureInPicture",
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/canStartPictureInPictureAutomaticallyFromInline",
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/startPictureInPicture()",
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/stopPictureInPicture()"
      ],
      "title": "Controlling Picture in Picture Playback"
    },
    {
      "anchor": "Retrieving-Picture-in-Picture-Template-Images",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/pictureInPictureButtonStartImage",
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/pictureInPictureButtonStopImage",
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/pictureInPictureButtonStartImage(compatibleWith:)",
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/pictureInPictureButtonStopImage(compatibleWith:)"
      ],
      "title": "Retrieving Picture in Picture Template Images"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/invalidatePlaybackState()"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVPictureInPictureController"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPictureInPictureController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPictureInPictureController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avkit/documentation/AVKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Controller",
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/init(contentSource:)",
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/init(playerLayer:)"
              ],
              "title": "Creating a Controller"
            },
            {
              "anchor": "Configuring-the-Content-Source",
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/contentSource-swift.property",
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/ContentSource-swift.class"
              ],
              "title": "Configuring the Content Source"
            },
            {
              "anchor": "Accessing-the-Player-Layer",
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/playerLayer"
              ],
              "title": "Accessing the Player Layer"
            },
            {
              "anchor": "Configuring-Playback-Behavior",
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/requiresLinearPlayback"
              ],
              "title": "Configuring Playback Behavior"
            },
            {
              "anchor": "Accessing-the-Delegate-Object",
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/delegate",
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureControllerDelegate"
              ],
              "title": "Accessing the Delegate Object"
            },
            {
              "anchor": "Accessing-Picture-in-Picture-State",
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/isPictureInPictureSupported()",
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/isPictureInPicturePossible",
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/isPictureInPictureActive",
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/isPictureInPictureSuspended"
              ],
              "title": "Accessing Picture in Picture State"
            },
            {
              "anchor": "Controlling-Picture-in-Picture-Playback",
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/canStopPictureInPicture",
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/canStartPictureInPictureAutomaticallyFromInline",
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/startPictureInPicture()",
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/stopPictureInPicture()"
              ],
              "title": "Controlling Picture in Picture Playback"
            },
            {
              "anchor": "Retrieving-Picture-in-Picture-Template-Images",
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/pictureInPictureButtonStartImage",
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/pictureInPictureButtonStopImage",
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/pictureInPictureButtonStartImage(compatibleWith:)",
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/pictureInPictureButtonStopImage(compatibleWith:)"
              ],
              "title": "Retrieving Picture in Picture Template Images"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/invalidatePlaybackState()"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Picture-in-Picture",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-playback-in-tvos",
                "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-in-a-standard-player",
                "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-in-a-custom-player",
                "doc://com.apple.avkit/documentation/AVKit/adopting-picture-in-picture-for-video-calls",
                "doc://com.apple.avkit/documentation/AVKit/accessing-the-camera-while-multitasking-on-ipad"
              ],
              "title": "Picture in Picture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVPictureInPictureController"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1isPictureInPictureSuspended/title",
          "value": "pictureInPictureSuspended"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1isPictureInPictureSuspended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pictureInPictureSuspended"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController/title",
          "value": "AVPictureInPictureController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPictureInPictureController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPictureInPictureController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1canStartPictureInPictureAutomaticallyFromInline/title",
          "value": "canStartPictureInPictureAutomaticallyFromInline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1canStartPictureInPictureAutomaticallyFromInline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canStartPictureInPictureAutomaticallyFromInline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1ContentSource-swift.class/title",
          "value": "AVPictureInPictureControllerContentSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1ContentSource-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPictureInPictureControllerContentSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1ContentSource-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPictureInPictureControllerContentSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1canStopPictureInPicture/title",
          "value": "canStopPictureInPicture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1canStopPictureInPicture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canStopPictureInPicture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1requiresLinearPlayback/title",
          "value": "requiresLinearPlayback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1requiresLinearPlayback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requiresLinearPlayback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1pictureInPictureButtonStopImage/title",
          "value": "pictureInPictureButtonStopImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1pictureInPictureButtonStopImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pictureInPictureButtonStopImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1isPictureInPictureSupported()/title",
          "value": "isPictureInPictureSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1isPictureInPictureSupported()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "isPictureInPictureSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1invalidatePlaybackState()/title",
          "value": "invalidatePlaybackState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1invalidatePlaybackState()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "invalidatePlaybackState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1playerLayer/title",
          "value": "playerLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1playerLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playerLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1init(contentSource:)/title",
          "value": "initWithContentSource:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1init(contentSource:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithContentSource:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureControllerDelegate/title",
          "value": "AVPictureInPictureControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPictureInPictureControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPictureInPictureControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1pictureInPictureButtonStartImage(compatibleWith:)/title",
          "value": "pictureInPictureButtonStartImageCompatibleWithTraitCollection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1pictureInPictureButtonStartImage(compatibleWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "pictureInPictureButtonStartImageCompatibleWithTraitCollection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1isPictureInPicturePossible/title",
          "value": "pictureInPicturePossible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1isPictureInPicturePossible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pictureInPicturePossible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1startPictureInPicture()/title",
          "value": "startPictureInPicture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1startPictureInPicture()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startPictureInPicture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1pictureInPictureButtonStartImage/title",
          "value": "pictureInPictureButtonStartImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1pictureInPictureButtonStartImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pictureInPictureButtonStartImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1isPictureInPictureActive/title",
          "value": "pictureInPictureActive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1isPictureInPictureActive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pictureInPictureActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1init(playerLayer:)/title",
          "value": "initWithPlayerLayer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1init(playerLayer:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithPlayerLayer:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1pictureInPictureButtonStopImage(compatibleWith:)/title",
          "value": "pictureInPictureButtonStopImageCompatibleWithTraitCollection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1pictureInPictureButtonStopImage(compatibleWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "pictureInPictureButtonStopImageCompatibleWithTraitCollection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1contentSource-swift.property/title",
          "value": "contentSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1contentSource-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1stopPictureInPicture()/title",
          "value": "stopPictureInPicture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1stopPictureInPicture()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopPictureInPicture"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avkit/avpictureinpicturecontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avkit/avpictureinpicturecontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
