{
  "abstract": [
    {
      "text": "A protocol for controlling playback from a sample buffer display layer in Picture in Picture.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avkit/documentation/AVKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureSampleBufferPlaybackDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)AVPictureInPictureSampleBufferPlaybackDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVPictureInPictureSampleBufferPlaybackDelegate"
      }
    ],
    "modules": [
      {
        "name": "AVKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVPictureInPictureSampleBufferPlaybackDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "AVPictureInPictureSampleBufferPlaybackDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVPictureInPictureSampleBufferPlaybackDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avkit/documentation/AVKit": {
      "abstract": [
        {
          "text": "Create user interfaces for media playback, complete with transport controls, chapter navigation, picture-in-picture support, and display of subtitles and closed captions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AVKit",
      "type": "topic",
      "url": "/documentation/avkit"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/ContentSource-swift.class/sampleBufferPlaybackDelegate": {
      "abstract": [
        {
          "text": "A delegate object that responds to sample buffer playback events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sampleBufferPlaybackDelegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)AVPictureInPictureSampleBufferPlaybackDelegate",
          "text": "AVPictureInPictureSampleBufferPlaybackDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/ContentSource-swift.class/sampleBufferPlaybackDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sampleBufferPlaybackDelegate"
        }
      ],
      "role": "symbol",
      "title": "sampleBufferPlaybackDelegate",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturecontroller/contentsource-swift.class/samplebufferplaybackdelegate"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureSampleBufferPlaybackDelegate": {
      "abstract": [
        {
          "text": "A protocol for controlling playback from a sample buffer display layer in Picture in Picture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPictureInPictureSampleBufferPlaybackDelegate"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureSampleBufferPlaybackDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPictureInPictureSampleBufferPlaybackDelegate"
        }
      ],
      "role": "symbol",
      "title": "AVPictureInPictureSampleBufferPlaybackDelegate",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturesamplebufferplaybackdelegate"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureSampleBufferPlaybackDelegate/pictureInPictureController(_:didTransitionToRenderSize:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the system Picture in Picture window changes size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pictureInPictureController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPictureInPictureController",
          "text": "AVPictureInPictureController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didTransitionToRenderSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMVideoDimensions",
          "text": "CMVideoDimensions"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureSampleBufferPlaybackDelegate/pictureInPictureController(_:didTransitionToRenderSize:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pictureInPictureController:didTransitionToRenderSize:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "pictureInPictureController(_:didTransitionToRenderSize:)",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturesamplebufferplaybackdelegate/pictureinpicturecontroller(_:didtransitiontorendersize:)"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureSampleBufferPlaybackDelegate/pictureInPictureController(_:setPlaying:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user requested to begin or pause playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pictureInPictureController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPictureInPictureController",
          "text": "AVPictureInPictureController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "setPlaying"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureSampleBufferPlaybackDelegate/pictureInPictureController(_:setPlaying:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pictureInPictureController:setPlaying:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "pictureInPictureController(_:setPlaying:)",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturesamplebufferplaybackdelegate/pictureinpicturecontroller(_:setplaying:)"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureSampleBufferPlaybackDelegate/pictureInPictureController(_:skipByInterval:completion:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user has requested skipping forward or backward by the indicated time interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pictureInPictureController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPictureInPictureController",
          "text": "AVPictureInPictureController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "skipByInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureSampleBufferPlaybackDelegate/pictureInPictureController(_:skipByInterval:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pictureInPictureController:skipByInterval:completionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "pictureInPictureController(_:skipByInterval:completion:)",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturesamplebufferplaybackdelegate/pictureinpicturecontroller(_:skipbyinterval:completion:)"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureSampleBufferPlaybackDelegate/pictureInPictureControllerIsPlaybackPaused(_:)": {
      "abstract": [
        {
          "text": "Asks delegate to indicate whether the playback UI reflects a playing or paused state, regardless of the current playback rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pictureInPictureControllerIsPlaybackPaused"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPictureInPictureController",
          "text": "AVPictureInPictureController"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureSampleBufferPlaybackDelegate/pictureInPictureControllerIsPlaybackPaused(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pictureInPictureControllerIsPlaybackPaused:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "pictureInPictureControllerIsPlaybackPaused(_:)",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturesamplebufferplaybackdelegate/pictureinpicturecontrollerisplaybackpaused(_:)"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureSampleBufferPlaybackDelegate/pictureInPictureControllerShouldProhibitBackgroundAudioPlayback(_:)": {
      "abstract": [
        {
          "text": "Asks the delegate whether to always prohibit background audio playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pictureInPictureControllerShouldProhibitBackgroundAudioPlayback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPictureInPictureController",
          "text": "AVPictureInPictureController"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureSampleBufferPlaybackDelegate/pictureInPictureControllerShouldProhibitBackgroundAudioPlayback(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pictureInPictureControllerShouldProhibitBackgroundAudioPlayback:"
        }
      ],
      "role": "symbol",
      "title": "pictureInPictureControllerShouldProhibitBackgroundAudioPlayback(_:)",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturesamplebufferplaybackdelegate/pictureinpicturecontrollershouldprohibitbackgroundaudioplayback(_:)"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureSampleBufferPlaybackDelegate/pictureInPictureControllerTimeRangeForPlayback(_:)": {
      "abstract": [
        {
          "text": "Asks the delegate for the current playable time range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pictureInPictureControllerTimeRangeForPlayback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPictureInPictureController",
          "text": "AVPictureInPictureController"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureSampleBufferPlaybackDelegate/pictureInPictureControllerTimeRangeForPlayback(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pictureInPictureControllerTimeRangeForPlayback:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "pictureInPictureControllerTimeRangeForPlayback(_:)",
      "type": "topic",
      "url": "/documentation/avkit/avpictureinpicturesamplebufferplaybackdelegate/pictureinpicturecontrollertimerangeforplayback(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-Delegate",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/ContentSource-swift.class/sampleBufferPlaybackDelegate"
      ],
      "title": "Configuring the Delegate"
    }
  ],
  "topicSections": [
    {
      "anchor": "Responding-to-Playback-Events",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureSampleBufferPlaybackDelegate/pictureInPictureController(_:setPlaying:)",
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureSampleBufferPlaybackDelegate/pictureInPictureControllerTimeRangeForPlayback(_:)",
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureSampleBufferPlaybackDelegate/pictureInPictureControllerIsPlaybackPaused(_:)",
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureSampleBufferPlaybackDelegate/pictureInPictureController(_:didTransitionToRenderSize:)",
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureSampleBufferPlaybackDelegate/pictureInPictureController(_:skipByInterval:completion:)",
        "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureSampleBufferPlaybackDelegate/pictureInPictureControllerShouldProhibitBackgroundAudioPlayback(_:)"
      ],
      "title": "Responding to Playback Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVPictureInPictureSampleBufferPlaybackDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPictureInPictureSampleBufferPlaybackDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPictureInPictureSampleBufferPlaybackDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avkit/documentation/AVKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Responding-to-Playback-Events",
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureSampleBufferPlaybackDelegate/pictureInPictureController(_:setPlaying:)",
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureSampleBufferPlaybackDelegate/pictureInPictureControllerTimeRangeForPlayback(_:)",
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureSampleBufferPlaybackDelegate/pictureInPictureControllerIsPlaybackPaused(_:)",
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureSampleBufferPlaybackDelegate/pictureInPictureController(_:didTransitionToRenderSize:)",
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureSampleBufferPlaybackDelegate/pictureInPictureController(_:skipByInterval:completion:)",
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureSampleBufferPlaybackDelegate/pictureInPictureControllerShouldProhibitBackgroundAudioPlayback(_:)"
              ],
              "title": "Responding to Playback Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-Delegate",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVPictureInPictureController/ContentSource-swift.class/sampleBufferPlaybackDelegate"
              ],
              "title": "Configuring the Delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVPictureInPictureSampleBufferPlaybackDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureSampleBufferPlaybackDelegate~1pictureInPictureController(_:skipByInterval:completion:)/title",
          "value": "pictureInPictureController:skipByInterval:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureSampleBufferPlaybackDelegate~1pictureInPictureController(_:skipByInterval:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pictureInPictureController:skipByInterval:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureSampleBufferPlaybackDelegate~1pictureInPictureControllerIsPlaybackPaused(_:)/title",
          "value": "pictureInPictureControllerIsPlaybackPaused:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureSampleBufferPlaybackDelegate~1pictureInPictureControllerIsPlaybackPaused(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pictureInPictureControllerIsPlaybackPaused:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureSampleBufferPlaybackDelegate~1pictureInPictureControllerTimeRangeForPlayback(_:)/title",
          "value": "pictureInPictureControllerTimeRangeForPlayback:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureSampleBufferPlaybackDelegate~1pictureInPictureControllerTimeRangeForPlayback(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pictureInPictureControllerTimeRangeForPlayback:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureSampleBufferPlaybackDelegate~1pictureInPictureControllerShouldProhibitBackgroundAudioPlayback(_:)/title",
          "value": "pictureInPictureControllerShouldProhibitBackgroundAudioPlayback:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureSampleBufferPlaybackDelegate~1pictureInPictureControllerShouldProhibitBackgroundAudioPlayback(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pictureInPictureControllerShouldProhibitBackgroundAudioPlayback:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureSampleBufferPlaybackDelegate~1pictureInPictureController(_:setPlaying:)/title",
          "value": "pictureInPictureController:setPlaying:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureSampleBufferPlaybackDelegate~1pictureInPictureController(_:setPlaying:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pictureInPictureController:setPlaying:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureSampleBufferPlaybackDelegate/title",
          "value": "AVPictureInPictureSampleBufferPlaybackDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureSampleBufferPlaybackDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPictureInPictureSampleBufferPlaybackDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureSampleBufferPlaybackDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPictureInPictureSampleBufferPlaybackDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1ContentSource-swift.class~1sampleBufferPlaybackDelegate/title",
          "value": "sampleBufferPlaybackDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureController~1ContentSource-swift.class~1sampleBufferPlaybackDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sampleBufferPlaybackDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureSampleBufferPlaybackDelegate~1pictureInPictureController(_:didTransitionToRenderSize:)/title",
          "value": "pictureInPictureController:didTransitionToRenderSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPictureInPictureSampleBufferPlaybackDelegate~1pictureInPictureController(_:didTransitionToRenderSize:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pictureInPictureController:didTransitionToRenderSize:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avkit/avpictureinpicturesamplebufferplaybackdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avkit/avpictureinpicturesamplebufferplaybackdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
