{
  "abstract": [
    {
      "text": "A protocol that defines the methods to implement to respond to Picture in Picture playback events.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avkit/documentation/AVKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)AVPlayerViewPictureInPictureDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVPlayerViewPictureInPictureDelegate"
      }
    ],
    "modules": [
      {
        "name": "AVKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVPlayerViewPictureInPictureDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "AVPlayerViewPictureInPictureDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVPlayerViewPictureInPictureDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avkit/documentation/AVKit": {
      "abstract": [
        {
          "text": "Create user interfaces for media playback, complete with transport controls, chapter navigation, picture-in-picture support, and display of subtitles and closed captions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AVKit",
      "type": "topic",
      "url": "/documentation/avkit"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerView/allowsPictureInPicturePlayback": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the player view allows Picture in Picture playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsPictureInPicturePlayback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerView/allowsPictureInPicturePlayback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsPictureInPicturePlayback"
        }
      ],
      "role": "symbol",
      "title": "allowsPictureInPicturePlayback",
      "type": "topic",
      "url": "/documentation/avkit/avplayerview/allowspictureinpictureplayback"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerView/pictureInPictureDelegate": {
      "abstract": [
        {
          "text": "The Picture in Picture delegate object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pictureInPictureDelegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)AVPlayerViewPictureInPictureDelegate",
          "text": "AVPlayerViewPictureInPictureDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerView/pictureInPictureDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pictureInPictureDelegate"
        }
      ],
      "role": "symbol",
      "title": "pictureInPictureDelegate",
      "type": "topic",
      "url": "/documentation/avkit/avplayerview/pictureinpicturedelegate"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate": {
      "abstract": [
        {
          "text": "A protocol that defines the methods to implement to respond to Picture in Picture playback events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerViewPictureInPictureDelegate"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerViewPictureInPictureDelegate"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerViewPictureInPictureDelegate",
      "type": "topic",
      "url": "/documentation/avkit/avplayerviewpictureinpicturedelegate"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate/playerView(_:failedToStartPictureInPictureWithError:)": {
      "abstract": [
        {
          "text": "Tells the delegate that Picture in Picture playback failed to start.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPlayerView",
          "text": "AVPlayerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "failedToStartPictureInPictureWithError"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate/playerView(_:failedToStartPictureInPictureWithError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playerView:failedToStartPictureInPictureWithError:"
        }
      ],
      "role": "symbol",
      "title": "playerView(_:failedToStartPictureInPictureWithError:)",
      "type": "topic",
      "url": "/documentation/avkit/avplayerviewpictureinpicturedelegate/playerview(_:failedtostartpictureinpicturewitherror:)"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate/playerView(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)": {
      "abstract": [
        {
          "text": "Tells the delegate to restore the user interface before Picture in Picture playback stops.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPlayerView",
          "text": "AVPlayerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "restoreUserInterfaceForPictureInPictureStopWithCompletionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate/playerView(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playerView:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "playerView(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)",
      "type": "topic",
      "url": "/documentation/avkit/avplayerviewpictureinpicturedelegate/playerview(_:restoreuserinterfaceforpictureinpicturestopwithcompletionhandler:)"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate/playerViewDidStartPicture(inPicture:)": {
      "abstract": [
        {
          "text": "Tells the delegate that Picture in Picture playback started.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playerViewDidStartPicture"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "inPicture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPlayerView",
          "text": "AVPlayerView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate/playerViewDidStartPicture(inPicture:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playerViewDidStartPictureInPicture:"
        }
      ],
      "role": "symbol",
      "title": "playerViewDidStartPicture(inPicture:)",
      "type": "topic",
      "url": "/documentation/avkit/avplayerviewpictureinpicturedelegate/playerviewdidstartpicture(inpicture:)"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate/playerViewDidStopPicture(inPicture:)": {
      "abstract": [
        {
          "text": "Tells the delegate that Picture in Picture playback stopped.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playerViewDidStopPicture"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "inPicture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPlayerView",
          "text": "AVPlayerView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate/playerViewDidStopPicture(inPicture:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playerViewDidStopPictureInPicture:"
        }
      ],
      "role": "symbol",
      "title": "playerViewDidStopPicture(inPicture:)",
      "type": "topic",
      "url": "/documentation/avkit/avplayerviewpictureinpicturedelegate/playerviewdidstoppicture(inpicture:)"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate/playerViewShouldAutomaticallyDismissAtPicture(inPictureStart:)": {
      "abstract": [
        {
          "text": "Asks the delegate if the player view should miniaturize when Picture in Picture starts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playerViewShouldAutomaticallyDismissAtPicture"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "inPictureStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPlayerView",
          "text": "AVPlayerView"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate/playerViewShouldAutomaticallyDismissAtPicture(inPictureStart:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playerViewShouldAutomaticallyDismissAtPictureInPictureStart:"
        }
      ],
      "role": "symbol",
      "title": "playerViewShouldAutomaticallyDismissAtPicture(inPictureStart:)",
      "type": "topic",
      "url": "/documentation/avkit/avplayerviewpictureinpicturedelegate/playerviewshouldautomaticallydismissatpicture(inpicturestart:)"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate/playerViewWillStartPicture(inPicture:)": {
      "abstract": [
        {
          "text": "Tells the delegate that Picture in Picture playback is about to start.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playerViewWillStartPicture"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "inPicture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPlayerView",
          "text": "AVPlayerView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate/playerViewWillStartPicture(inPicture:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playerViewWillStartPictureInPicture:"
        }
      ],
      "role": "symbol",
      "title": "playerViewWillStartPicture(inPicture:)",
      "type": "topic",
      "url": "/documentation/avkit/avplayerviewpictureinpicturedelegate/playerviewwillstartpicture(inpicture:)"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate/playerViewWillStopPicture(inPicture:)": {
      "abstract": [
        {
          "text": "Tells the delegate that Picture in Picture playback is about to stop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playerViewWillStopPicture"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "inPicture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPlayerView",
          "text": "AVPlayerView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate/playerViewWillStopPicture(inPicture:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playerViewWillStopPictureInPicture:"
        }
      ],
      "role": "symbol",
      "title": "playerViewWillStopPicture(inPicture:)",
      "type": "topic",
      "url": "/documentation/avkit/avplayerviewpictureinpicturedelegate/playerviewwillstoppicture(inpicture:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Picture-in-Picture",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerView/allowsPictureInPicturePlayback",
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerView/pictureInPictureDelegate"
      ],
      "title": "Configuring Picture in Picture"
    }
  ],
  "topicSections": [
    {
      "anchor": "Responding-to-Picture-in-Picture-Playback-Events",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate/playerViewWillStartPicture(inPicture:)",
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate/playerViewDidStartPicture(inPicture:)",
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate/playerViewWillStopPicture(inPicture:)",
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate/playerViewDidStopPicture(inPicture:)",
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate/playerView(_:failedToStartPictureInPictureWithError:)",
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate/playerView(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)",
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate/playerViewShouldAutomaticallyDismissAtPicture(inPictureStart:)"
      ],
      "title": "Responding to Picture in Picture Playback Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVPlayerViewPictureInPictureDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerViewPictureInPictureDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerViewPictureInPictureDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avkit/documentation/AVKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Responding-to-Picture-in-Picture-Playback-Events",
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate/playerViewWillStartPicture(inPicture:)",
                "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate/playerViewDidStartPicture(inPicture:)",
                "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate/playerViewWillStopPicture(inPicture:)",
                "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate/playerViewDidStopPicture(inPicture:)",
                "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate/playerView(_:failedToStartPictureInPictureWithError:)",
                "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate/playerView(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)",
                "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewPictureInPictureDelegate/playerViewShouldAutomaticallyDismissAtPicture(inPictureStart:)"
              ],
              "title": "Responding to Picture in Picture Playback Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Picture-in-Picture",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVPlayerView/allowsPictureInPicturePlayback",
                "doc://com.apple.avkit/documentation/AVKit/AVPlayerView/pictureInPictureDelegate"
              ],
              "title": "Configuring Picture in Picture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVPlayerViewPictureInPictureDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewPictureInPictureDelegate/title",
          "value": "AVPlayerViewPictureInPictureDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewPictureInPictureDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerViewPictureInPictureDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewPictureInPictureDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerViewPictureInPictureDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewPictureInPictureDelegate~1playerView(_:failedToStartPictureInPictureWithError:)/title",
          "value": "playerView:failedToStartPictureInPictureWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewPictureInPictureDelegate~1playerView(_:failedToStartPictureInPictureWithError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "playerView:failedToStartPictureInPictureWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewPictureInPictureDelegate~1playerView(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)/title",
          "value": "playerView:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewPictureInPictureDelegate~1playerView(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "playerView:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewPictureInPictureDelegate~1playerViewWillStartPicture(inPicture:)/title",
          "value": "playerViewWillStartPictureInPicture:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewPictureInPictureDelegate~1playerViewWillStartPicture(inPicture:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "playerViewWillStartPictureInPicture:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerView~1pictureInPictureDelegate/title",
          "value": "pictureInPictureDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerView~1pictureInPictureDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pictureInPictureDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewPictureInPictureDelegate~1playerViewDidStopPicture(inPicture:)/title",
          "value": "playerViewDidStopPictureInPicture:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewPictureInPictureDelegate~1playerViewDidStopPicture(inPicture:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "playerViewDidStopPictureInPicture:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewPictureInPictureDelegate~1playerViewDidStartPicture(inPicture:)/title",
          "value": "playerViewDidStartPictureInPicture:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewPictureInPictureDelegate~1playerViewDidStartPicture(inPicture:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "playerViewDidStartPictureInPicture:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewPictureInPictureDelegate~1playerViewShouldAutomaticallyDismissAtPicture(inPictureStart:)/title",
          "value": "playerViewShouldAutomaticallyDismissAtPictureInPictureStart:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewPictureInPictureDelegate~1playerViewShouldAutomaticallyDismissAtPicture(inPictureStart:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "playerViewShouldAutomaticallyDismissAtPictureInPictureStart:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerView~1allowsPictureInPicturePlayback/title",
          "value": "allowsPictureInPicturePlayback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerView~1allowsPictureInPicturePlayback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsPictureInPicturePlayback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewPictureInPictureDelegate~1playerViewWillStopPicture(inPicture:)/title",
          "value": "playerViewWillStopPictureInPicture:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewPictureInPictureDelegate~1playerViewWillStopPicture(inPicture:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "playerViewWillStopPictureInPicture:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avkit/avplayerviewpictureinpicturedelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avkit/avplayerviewpictureinpicturedelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
