{
  "abstract": [
    {
      "text": "Constants that define the button styles a route picker view supports.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avkit/documentation/AVKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewButtonStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVRoutePickerViewButtonStyle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVRoutePickerViewButtonStyle"
      }
    ],
    "modules": [
      {
        "name": "AVKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVRoutePickerViewButtonStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "AVRoutePickerViewButtonStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVRoutePickerViewButtonStyle"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avkit/documentation/AVKit": {
      "abstract": [
        {
          "text": "Create user interfaces for media playback, complete with transport controls, chapter navigation, picture-in-picture support, and display of subtitles and closed captions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AVKit",
      "type": "topic",
      "url": "/documentation/avkit"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState": {
      "abstract": [
        {
          "text": "Constants that describe the available button states.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ButtonState"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ButtonState"
        }
      ],
      "role": "symbol",
      "title": "AVRoutePickerView.ButtonState",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerview/buttonstate"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/activeTintColor": {
      "abstract": [
        {
          "text": "The view’s tint color when AirPlay is active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activeTintColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/activeTintColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activeTintColor"
        }
      ],
      "role": "symbol",
      "title": "activeTintColor",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerview/activetintcolor"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/isRoutePickerButtonBordered": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the route picker button has a border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isRoutePickerButtonBordered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/isRoutePickerButtonBordered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "routePickerButtonBordered"
        }
      ],
      "role": "symbol",
      "title": "isRoutePickerButtonBordered",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerview/isroutepickerbuttonbordered"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/prioritizesVideoDevices": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the route picker sorts video output devices to the top of the list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prioritizesVideoDevices"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/prioritizesVideoDevices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prioritizesVideoDevices"
        }
      ],
      "role": "symbol",
      "title": "prioritizesVideoDevices",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerview/prioritizesvideodevices"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/routePickerButtonColor(for:)": {
      "abstract": [
        {
          "text": "Returns the color of the picker button for the specified state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "routePickerButtonColor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVRoutePickerView",
          "text": "AVRoutePickerView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVRoutePickerViewButtonState",
          "text": "ButtonState"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/routePickerButtonColor(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "routePickerButtonColorForState:"
        }
      ],
      "role": "symbol",
      "title": "routePickerButtonColor(for:)",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerview/routepickerbuttoncolor(for:)"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/routePickerButtonStyle": {
      "abstract": [
        {
          "text": "The button style for the route picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "routePickerButtonStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVRoutePickerViewButtonStyle",
          "text": "AVRoutePickerViewButtonStyle"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/routePickerButtonStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "routePickerButtonStyle"
        }
      ],
      "role": "symbol",
      "title": "routePickerButtonStyle",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerview/routepickerbuttonstyle"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/setRoutePickerButtonColor(_:for:)": {
      "abstract": [
        {
          "text": "Sets the route picker button color for the specified state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setRoutePickerButtonColor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVRoutePickerView",
          "text": "AVRoutePickerView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVRoutePickerViewButtonState",
          "text": "ButtonState"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/setRoutePickerButtonColor(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setRoutePickerButtonColor:forState:"
        }
      ],
      "role": "symbol",
      "title": "setRoutePickerButtonColor(_:for:)",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerview/setroutepickerbuttoncolor(_:for:)"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewButtonStyle": {
      "abstract": [
        {
          "text": "Constants that define the button styles a route picker view supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVRoutePickerViewButtonStyle"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewButtonStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVRoutePickerViewButtonStyle"
        }
      ],
      "role": "symbol",
      "title": "AVRoutePickerViewButtonStyle",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerviewbuttonstyle"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewButtonStyle/custom": {
      "abstract": [
        {
          "text": "A custom button style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "custom"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewButtonStyle/custom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVRoutePickerViewButtonStyleCustom"
        }
      ],
      "role": "symbol",
      "title": "AVRoutePickerViewButtonStyle.custom",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerviewbuttonstyle/custom"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewButtonStyle/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewButtonStyle/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerviewbuttonstyle/init(rawvalue:)"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewButtonStyle/plain": {
      "abstract": [
        {
          "text": "A plain button style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "plain"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewButtonStyle/plain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVRoutePickerViewButtonStylePlain"
        }
      ],
      "role": "symbol",
      "title": "AVRoutePickerViewButtonStyle.plain",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerviewbuttonstyle/plain"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewButtonStyle/system": {
      "abstract": [
        {
          "text": "A system-defined button style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "system"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewButtonStyle/system",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVRoutePickerViewButtonStyleSystem"
        }
      ],
      "role": "symbol",
      "title": "AVRoutePickerViewButtonStyle.system",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerviewbuttonstyle/system"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-route-picker-view",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/activeTintColor",
        "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/isRoutePickerButtonBordered",
        "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/prioritizesVideoDevices",
        "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/routePickerButtonStyle",
        "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/routePickerButtonColor(for:)",
        "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/setRoutePickerButtonColor(_:for:)",
        "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState"
      ],
      "title": "Configuring the route picker view"
    }
  ],
  "topicSections": [
    {
      "anchor": "Button-Styles",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewButtonStyle/custom",
        "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewButtonStyle/plain",
        "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewButtonStyle/system"
      ],
      "title": "Button Styles"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewButtonStyle/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVRoutePickerViewButtonStyle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerViewButtonStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerViewButtonStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avkit/documentation/AVKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Button-Styles",
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewButtonStyle/custom",
                "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewButtonStyle/plain",
                "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerViewButtonStyle/system"
              ],
              "title": "Button Styles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-route-picker-view",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/activeTintColor",
                "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/isRoutePickerButtonBordered",
                "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/prioritizesVideoDevices",
                "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/routePickerButtonStyle",
                "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/routePickerButtonColor(for:)",
                "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/setRoutePickerButtonColor(_:for:)",
                "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState"
              ],
              "title": "Configuring the route picker view"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVRoutePickerViewButtonStyle"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerViewButtonStyle~1custom/title",
          "value": "AVRoutePickerViewButtonStyleCustom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerViewButtonStyle~1custom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerViewButtonStyleCustom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState/title",
          "value": "AVRoutePickerViewButtonState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerViewButtonState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerViewButtonState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1setRoutePickerButtonColor(_:for:)/title",
          "value": "setRoutePickerButtonColor:forState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1setRoutePickerButtonColor(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setRoutePickerButtonColor:forState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1activeTintColor/title",
          "value": "activeTintColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1activeTintColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activeTintColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerViewButtonStyle~1plain/title",
          "value": "AVRoutePickerViewButtonStylePlain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerViewButtonStyle~1plain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerViewButtonStylePlain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1prioritizesVideoDevices/title",
          "value": "prioritizesVideoDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1prioritizesVideoDevices/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "prioritizesVideoDevices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1routePickerButtonColor(for:)/title",
          "value": "routePickerButtonColorForState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1routePickerButtonColor(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "routePickerButtonColorForState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1routePickerButtonStyle/title",
          "value": "routePickerButtonStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1routePickerButtonStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "routePickerButtonStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerViewButtonStyle/title",
          "value": "AVRoutePickerViewButtonStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerViewButtonStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerViewButtonStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerViewButtonStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerViewButtonStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerViewButtonStyle~1system/title",
          "value": "AVRoutePickerViewButtonStyleSystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerViewButtonStyle~1system/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerViewButtonStyleSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1isRoutePickerButtonBordered/title",
          "value": "routePickerButtonBordered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1isRoutePickerButtonBordered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "routePickerButtonBordered"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avkit/avroutepickerviewbuttonstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avkit/avroutepickerviewbuttonstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
