{
  "abstract": [
    {
      "text": "Constants that define the types of analysis a player view controller may perform on a paused video frame.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avkit/documentation/AVKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVVideoFrameAnalysisType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVVideoFrameAnalysisType"
      }
    ],
    "modules": [
      {
        "name": "AVKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVVideoFrameAnalysisType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AVVideoFrameAnalysisType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVVideoFrameAnalysisType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avkit/documentation/AVKit": {
      "abstract": [
        {
          "text": "Create user interfaces for media playback, complete with transport controls, chapter navigation, picture-in-picture support, and display of subtitles and closed captions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AVKit",
      "type": "topic",
      "url": "/documentation/avkit"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerView/allowsVideoFrameAnalysis": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to perform video frame analysis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsVideoFrameAnalysis"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerView/allowsVideoFrameAnalysis",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsVideoFrameAnalysis"
        }
      ],
      "role": "symbol",
      "title": "allowsVideoFrameAnalysis",
      "type": "topic",
      "url": "/documentation/avkit/avplayerview/allowsvideoframeanalysis"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerView/videoFrameAnalysisTypes": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoFrameAnalysisTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVVideoFrameAnalysisType",
          "text": "AVVideoFrameAnalysisType"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerView/videoFrameAnalysisTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "videoFrameAnalysisTypes"
        }
      ],
      "role": "symbol",
      "title": "videoFrameAnalysisTypes",
      "type": "topic",
      "url": "/documentation/avkit/avplayerview/videoframeanalysistypes"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType": {
      "abstract": [
        {
          "text": "Constants that define the types of analysis a player view controller may perform on a paused video frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoFrameAnalysisType"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoFrameAnalysisType"
        }
      ],
      "role": "symbol",
      "title": "AVVideoFrameAnalysisType",
      "type": "topic",
      "url": "/documentation/avkit/avvideoframeanalysistype"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/AVVideoFrameAnalysisTypeNone": {
      "abstract": [
        {
          "text": "A type that performs no analysis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVVideoFrameAnalysisTypeNone"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/AVVideoFrameAnalysisTypeNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVVideoFrameAnalysisTypeNone",
      "type": "topic",
      "url": "/documentation/avkit/avvideoframeanalysistype/avvideoframeanalysistypenone"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/default": {
      "abstract": [
        {
          "text": "The default types of analysis to perform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVVideoFrameAnalysisType",
          "text": "AVVideoFrameAnalysisType"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoFrameAnalysisTypeDefault"
        }
      ],
      "role": "symbol",
      "title": "default",
      "type": "topic",
      "url": "/documentation/avkit/avvideoframeanalysistype/default"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a type from a string value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/avkit/avvideoframeanalysistype/init(rawvalue:)"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/machineReadableCode": {
      "abstract": [
        {
          "text": "A type that recognizes machine-readable codes, such as QR codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "machineReadableCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVVideoFrameAnalysisType",
          "text": "AVVideoFrameAnalysisType"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/machineReadableCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoFrameAnalysisTypeMachineReadableCode"
        }
      ],
      "role": "symbol",
      "title": "machineReadableCode",
      "type": "topic",
      "url": "/documentation/avkit/avvideoframeanalysistype/machinereadablecode"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/subject": {
      "abstract": [
        {
          "text": "A type that finds a subject that a user can copy out of frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVVideoFrameAnalysisType",
          "text": "AVVideoFrameAnalysisType"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/subject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoFrameAnalysisTypeSubject"
        }
      ],
      "role": "symbol",
      "title": "subject",
      "type": "topic",
      "url": "/documentation/avkit/avvideoframeanalysistype/subject"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/text": {
      "abstract": [
        {
          "text": "A type that finds text in a paused video frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "text"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVVideoFrameAnalysisType",
          "text": "AVVideoFrameAnalysisType"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/text",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoFrameAnalysisTypeText"
        }
      ],
      "role": "symbol",
      "title": "text",
      "type": "topic",
      "url": "/documentation/avkit/avvideoframeanalysistype/text"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/visualSearch": {
      "abstract": [
        {
          "text": "A type that identifies objects, landmarks, art, and so on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visualSearch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVVideoFrameAnalysisType",
          "text": "AVVideoFrameAnalysisType"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/visualSearch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoFrameAnalysisTypeVisualSearch"
        }
      ],
      "role": "symbol",
      "title": "visualSearch",
      "type": "topic",
      "url": "/documentation/avkit/avvideoframeanalysistype/visualsearch"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Frame-Analysis",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerView/allowsVideoFrameAnalysis",
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerView/videoFrameAnalysisTypes"
      ],
      "title": "Configuring Frame Analysis"
    }
  ],
  "topicSections": [
    {
      "anchor": "Analysis-types",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/default",
        "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/text",
        "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/subject",
        "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/visualSearch",
        "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/machineReadableCode"
      ],
      "title": "Analysis types"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVVideoFrameAnalysisType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoFrameAnalysisType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoFrameAnalysisType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avkit/documentation/AVKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Analysis-types",
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/default",
                "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/text",
                "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/subject",
                "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/visualSearch",
                "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/machineReadableCode",
                "doc://com.apple.avkit/documentation/AVKit/AVVideoFrameAnalysisType/AVVideoFrameAnalysisTypeNone"
              ],
              "title": "Analysis types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Frame-Analysis",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVPlayerView/allowsVideoFrameAnalysis",
                "doc://com.apple.avkit/documentation/AVKit/AVPlayerView/videoFrameAnalysisTypes"
              ],
              "title": "Configuring Frame Analysis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVVideoFrameAnalysisType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVVideoFrameAnalysisType~1subject/title",
          "value": "AVVideoFrameAnalysisTypeSubject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVVideoFrameAnalysisType~1subject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoFrameAnalysisTypeSubject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVVideoFrameAnalysisType~1visualSearch/title",
          "value": "AVVideoFrameAnalysisTypeVisualSearch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVVideoFrameAnalysisType~1visualSearch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoFrameAnalysisTypeVisualSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVVideoFrameAnalysisType~1text/title",
          "value": "AVVideoFrameAnalysisTypeText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVVideoFrameAnalysisType~1text/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoFrameAnalysisTypeText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerView~1videoFrameAnalysisTypes/title",
          "value": "videoFrameAnalysisTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerView~1videoFrameAnalysisTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "videoFrameAnalysisTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVVideoFrameAnalysisType~1default/title",
          "value": "AVVideoFrameAnalysisTypeDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVVideoFrameAnalysisType~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoFrameAnalysisTypeDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVVideoFrameAnalysisType~1machineReadableCode/title",
          "value": "AVVideoFrameAnalysisTypeMachineReadableCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVVideoFrameAnalysisType~1machineReadableCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoFrameAnalysisTypeMachineReadableCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVVideoFrameAnalysisType/title",
          "value": "AVVideoFrameAnalysisType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVVideoFrameAnalysisType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoFrameAnalysisType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVVideoFrameAnalysisType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoFrameAnalysisType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerView~1allowsVideoFrameAnalysis/title",
          "value": "allowsVideoFrameAnalysis"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerView~1allowsVideoFrameAnalysis/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsVideoFrameAnalysis"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avkit/avvideoframeanalysistype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avkit/avvideoframeanalysistype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
