{
  "abstract": [
    {
      "text": "Error code constants for framework operations.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avkit/documentation/AVKit",
        "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avkit/documentation/AVKit/error-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Error Constants"
  },
  "references": {
    "doc://com.apple.avkit/documentation/AVKit": {
      "abstract": [
        {
          "text": "Create user interfaces for media playback, complete with transport controls, chapter navigation, picture-in-picture support, and display of subtitles and closed captions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AVKit",
      "type": "topic",
      "url": "/documentation/avkit"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents a framework error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVKitError"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVKitError"
        }
      ],
      "role": "symbol",
      "title": "AVKitError",
      "type": "topic",
      "url": "/documentation/avkit/avkiterror-swift.struct"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Constants that identify framework error codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "AVKitError.Code",
      "type": "topic",
      "url": "/documentation/avkit/avkiterror-swift.struct/code"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct/contentDisallowedByPasscode": {
      "abstract": [
        {
          "text": "A restriction disallows access to this content, but the user can override the restriction by entering the device passcode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentDisallowedByPasscode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC10AVKitErrorLeV",
          "text": "AVKitError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVKitError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct/contentDisallowedByPasscode",
      "kind": "symbol",
      "role": "symbol",
      "title": "contentDisallowedByPasscode",
      "type": "topic",
      "url": "/documentation/avkit/avkiterror-swift.struct/contentdisallowedbypasscode"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct/contentDisallowedByProfile": {
      "abstract": [
        {
          "text": "An installed profile restricts access to this content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentDisallowedByProfile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC10AVKitErrorLeV",
          "text": "AVKitError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVKitError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct/contentDisallowedByProfile",
      "kind": "symbol",
      "role": "symbol",
      "title": "contentDisallowedByProfile",
      "type": "topic",
      "url": "/documentation/avkit/avkiterror-swift.struct/contentdisallowedbyprofile"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct/contentRatingUnknown": {
      "abstract": [
        {
          "text": "The media content rating is missing or unrecognized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentRatingUnknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC10AVKitErrorLeV",
          "text": "AVKitError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVKitError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct/contentRatingUnknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "contentRatingUnknown",
      "type": "topic",
      "url": "/documentation/avkit/avkiterror-swift.struct/contentratingunknown"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct/pictureInPictureStartFailed": {
      "abstract": [
        {
          "text": "The system failed to start Picture in Picture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pictureInPictureStartFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC10AVKitErrorLeV",
          "text": "AVKitError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVKitError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct/pictureInPictureStartFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "pictureInPictureStartFailed",
      "type": "topic",
      "url": "/documentation/avkit/avkiterror-swift.struct/pictureinpicturestartfailed"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct/unknown": {
      "abstract": [
        {
          "text": "An unknown error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC10AVKitErrorLeV",
          "text": "AVKitError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVKitError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/avkit/avkiterror-swift.struct/unknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-an-Error",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct/Code"
      ],
      "title": "Inspecting an Error"
    }
  ],
  "topicSections": [
    {
      "abstract": [
        {
          "text": "Error code constants for framework operations.",
          "type": "text"
        }
      ],
      "anchor": "Error-Code-Constants",
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct/unknown",
        "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct/contentRatingUnknown",
        "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct/contentDisallowedByPasscode",
        "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct/contentDisallowedByProfile",
        "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct/pictureInPictureStartFailed"
      ],
      "title": "Error Code Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-an-Error",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVKitError-swift.struct/Code"
              ],
              "title": "Inspecting an Error"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitError-swift.struct~1Code/title",
          "value": "AVKitError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVKitError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVKitError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVKitError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avkit/error-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avkit/error-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
