{
  "abstract": [
    {
      "text": "Present navigation markers in the Chapters panel to help users quickly navigate your content.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avkit/documentation/AVKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avkit/documentation/AVKit/presenting-navigation-markers"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Presenting Navigation Markers"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To help users navigate your content, the Chapters panel presents navigation markers that represent points of interest within the media’s timeline. Users can skip to desired content by selecting a marker with the Siri Remote.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3905733",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Set-the-Navigation-Markers",
          "level": 3,
          "text": "Set the Navigation Markers",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In tvOS, a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayerItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " contains a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayerItem/navigationMarkerGroups",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property you use to supply chapter information. Set this property to an array of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avkit/documentation/AVKit/AVNavigationMarkersGroup",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects to define the navigation markers for the current media.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Although the player item defines the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayerItem/navigationMarkerGroups",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property as an array, the system only supports the first group in the array.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avkit/documentation/AVKit/AVNavigationMarkersGroup",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " contains one or more ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVTimedMetadataGroup",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects, each representing an individual marker presented in the player’s Info panel. Each ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVTimedMetadataGroup",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " stores a time range in the asset’s timeline to which this marker applies, an array of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVMetadataItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects to define the marker’s title, and, optionally, its thumbnail artwork.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3905734",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code shows how you can present a chapter list for your media:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "struct Chapter {",
            "    let title: String",
            "    let imageName: String",
            "    let startTime: TimeInterval",
            "    let endTime: TimeInterval",
            "}",
            "",
            "...",
            "",
            "func setupPlayback() {",
            "    ...",
            "    playerItem.navigationMarkerGroups = makeNavigationMarkerGroups()",
            "    ...",
            "}",
            "",
            "private func makeNavigationMarkerGroups() -> [AVNavigationMarkersGroup] {",
            "    ",
            "    let chapters = [",
            "        Chapter(title: \"Chapter 1\", imageName: \"chapter1\", startTime: 0.0, endTime: 60.0),",
            "        Chapter(title: \"Chapter 2\", imageName: \"chapter2\", startTime: 60.0, endTime: 120.0),",
            "        Chapter(title: \"Chapter 3\", imageName: \"chapter3\", startTime: 120.0, endTime: 180.0),",
            "        Chapter(title: \"Chapter 4\", imageName: \"chapter4\", startTime: 180.0, endTime: 240.0)",
            "    ]",
            "    ",
            "    var metadataGroups = [AVTimedMetadataGroup]()",
            "    ",
            "    // Iterate over the defined chapters and build a timed metadata group object for each.",
            "    chapters.forEach { chapter in",
            "        metadataGroups.append(makeTimedMetadataGroup(for: chapter))",
            "    }",
            "    ",
            "    return [AVNavigationMarkersGroup(title: nil, ",
            "                                     timedNavigationMarkers: metadataGroups)]",
            "}",
            "",
            "private func makeTimedMetadataGroup(for chapter: Chapter) -> AVTimedMetadataGroup {",
            "    var metadata = [AVMetadataItem]()",
            "    ",
            "    // Create a metadata item that contains the chapter title.",
            "    let titleItem = makeMetadataItem(.commonIdentifierTitle, value: chapter.title)",
            "    metadata.append(titleItem)",
            "    if let image = UIImage(named: chapter.imageName), ",
            "       let pngData = image.pngData() {",
            "        // Create a metadata item that contains the chapter thumbnail.",
            "        let imageItem = makeMetadataItem(.commonIdentifierArtwork, value: pngData)",
            "        metadata.append(imageItem)",
            "    }",
            "    ",
            "    // Create a time range for the metadata group.",
            "    let timescale: Int32 = 600",
            "    let startTime = CMTime(seconds: chapter.startTime, preferredTimescale: timescale)",
            "    let endTime = CMTime(seconds: chapter.endTime, preferredTimescale: timescale)",
            "    let timeRange = CMTimeRangeFromTimeToTime(start: startTime, end: endTime)",
            "    ",
            "    return AVTimedMetadataGroup(items: metadata, timeRange: timeRange)",
            "}",
            "",
            "private func makeMetadataItem(_ identifier: AVMetadataIdentifier, value: Any) -> AVMetadataItem {",
            "    let item = AVMutableMetadataItem()",
            "    item.identifier = identifier",
            "    item.value = value as? NSCopying & NSObjectProtocol",
            "    item.extendedLanguageTag = \"und\"",
            "    return item.copy() as! AVMetadataItem",
            "}",
            ""
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avkit/documentation/AVKit": {
      "abstract": [
        {
          "text": "Create user interfaces for media playback, complete with transport controls, chapter navigation, picture-in-picture support, and display of subtitles and closed captions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AVKit",
      "type": "topic",
      "url": "/documentation/avkit"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContentProposalViewController": {
      "abstract": [
        {
          "text": "A view controller that proposes content to watch next.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContentProposalViewController"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContentProposalViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentProposalViewController"
        }
      ],
      "role": "symbol",
      "title": "AVContentProposalViewController",
      "type": "topic",
      "url": "/documentation/avkit/avcontentproposalviewcontroller"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewController": {
      "abstract": [
        {
          "text": "A view controller that provides an interface to a person so they can select and connect a continuity device to the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContinuityDevicePickerViewController"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContinuityDevicePickerViewController"
        }
      ],
      "role": "symbol",
      "title": "AVContinuityDevicePickerViewController",
      "type": "topic",
      "url": "/documentation/avkit/avcontinuitydevicepickerviewcontroller"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate": {
      "abstract": [
        {
          "text": "An interface that responds to events from a continuity device picker view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContinuityDevicePickerViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContinuityDevicePickerViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "AVContinuityDevicePickerViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/avkit/avcontinuitydevicepickerviewcontrollerdelegate"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVDisplayManager": {
      "abstract": [
        {
          "text": "A tvOS management object that controls whether a TV switches modes to match the video’s native mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVDisplayManager"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVDisplayManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVDisplayManager"
        }
      ],
      "role": "symbol",
      "title": "AVDisplayManager",
      "type": "topic",
      "url": "/documentation/avkit/avdisplaymanager"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVInterstitialTimeRange": {
      "abstract": [
        {
          "text": "A time range in an audiovisual presentation for content with an interstitial designation, such as advertisements or legal notices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVInterstitialTimeRange"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVInterstitialTimeRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVInterstitialTimeRange"
        }
      ],
      "role": "symbol",
      "title": "AVInterstitialTimeRange",
      "type": "topic",
      "url": "/documentation/avkit/avinterstitialtimerange"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVNavigationMarkersGroup": {
      "abstract": [
        {
          "text": "A set of markers for navigating playback of an audiovisual presentation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVNavigationMarkersGroup"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVNavigationMarkersGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVNavigationMarkersGroup"
        }
      ],
      "role": "symbol",
      "title": "AVNavigationMarkersGroup",
      "type": "topic",
      "url": "/documentation/avkit/avnavigationmarkersgroup"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController": {
      "abstract": [
        {
          "text": "A view controller that displays content from a player and presents a native user interface to control playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerViewController"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerViewController"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerViewController",
      "type": "topic",
      "url": "/documentation/avkit/avplayerviewcontroller"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate": {
      "abstract": [
        {
          "text": "A protocol that defines the methods to implement to respond to player view controller events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/avkit/avplayerviewcontrollerdelegate"
    },
    "doc://com.apple.avkit/documentation/AVKit/customizing-the-tvos-playback-experience": {
      "abstract": [
        {
          "text": "Adopt the latest features of the redesigned tvOS player user interface to provide a more streamlined way to watch your content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/customizing-the-tvos-playback-experience",
      "kind": "article",
      "role": "article",
      "title": "Customizing the tvOS Playback Experience",
      "type": "topic",
      "url": "/documentation/avkit/customizing-the-tvos-playback-experience"
    },
    "doc://com.apple.avkit/documentation/AVKit/presenting-content-proposals-in-tvos": {
      "abstract": [
        {
          "text": "Display a preview of an upcoming media item at the conclusion of the currently playing media item.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/presenting-content-proposals-in-tvos",
      "kind": "article",
      "role": "article",
      "title": "Presenting Content Proposals in tvOS",
      "type": "topic",
      "url": "/documentation/avkit/presenting-content-proposals-in-tvos"
    },
    "doc://com.apple.avkit/documentation/AVKit/supporting-continuity-camera-in-your-tvos-app": {
      "abstract": [
        {
          "text": "Capture high-quality photos, video, and audio in your Apple TV app by connecting",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "an iPhone or iPad as a continuity device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/supporting-continuity-camera-in-your-tvos-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Supporting Continuity Camera in your tvOS app",
      "type": "topic",
      "url": "/documentation/avkit/supporting-continuity-camera-in-your-tvos-app"
    },
    "doc://com.apple.avkit/documentation/AVKit/working-with-interstitial-content": {
      "abstract": [
        {
          "text": "Present additional content alongside your main media presentation using HTTP Live Streaming support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/working-with-interstitial-content",
      "kind": "article",
      "role": "article",
      "title": "Working with Interstitial Content",
      "type": "topic",
      "url": "/documentation/avkit/working-with-interstitial-content"
    },
    "doc://com.apple.avkit/documentation/AVKit/working-with-overlays-and-parental-controls-in-tvos": {
      "abstract": [
        {
          "text": "Add interactive overlays, parental controls, and livestream channel flipping using a player view controller.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/working-with-overlays-and-parental-controls-in-tvos",
      "kind": "article",
      "role": "sampleCode",
      "title": "Working with Overlays and Parental Controls in tvOS",
      "type": "topic",
      "url": "/documentation/avkit/working-with-overlays-and-parental-controls-in-tvos"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVMetadataItem": {
      "abstract": [
        {
          "text": "A metadata item for an audiovisual asset or one of its tracks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetadataItem"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVMetadataItem",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVMetadataItem",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVMetadataItem"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVPlayerItem": {
      "abstract": [
        {
          "text": "An object that models the timing and presentation state of an asset during playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerItem"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayerItem",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVPlayerItem",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVPlayerItem"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVPlayerItem/navigationMarkerGroups": {
      "abstract": [
        {
          "text": "The time marker groups that provide ways to navigate the player item’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "navigationMarkerGroups"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVNavigationMarkersGroup",
          "text": "AVNavigationMarkersGroup"
        },
        {
          "kind": "text",
          "text": "] { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayerItem/navigationMarkerGroups",
      "kind": "symbol",
      "role": "symbol",
      "title": "navigationMarkerGroups",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVPlayerItem/navigationMarkerGroups"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVTimedMetadataGroup": {
      "abstract": [
        {
          "text": "A collection of metadata items that are valid for use during a specific time range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVTimedMetadataGroup"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVTimedMetadataGroup",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVTimedMetadataGroup",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVTimedMetadataGroup"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "media-3905733": {
      "alt": "An image of Apple TV Chapters panel that shows a horizontal list of chapter markers.",
      "identifier": "media-3905733",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/afe7e5a11839436e35a4de772857de6a/media-3905733@2x.png"
        }
      ]
    },
    "media-3905734": {
      "alt": "A top-down component diagram showing a player item containing navigation markers groups at the top. The middle component shows a navigation markers group containing timed metadata groups. The bottom component shows a timed metadata group containing multiple metadata items.",
      "identifier": "media-3905734",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/b848aa4715a84b0d69f4d9d5879de6fe/media-3905734@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/14109881ece043c06a606bd739139772/media-3905734~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "tvOS-Playback-and-Capture",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/customizing-the-tvos-playback-experience",
        "doc://com.apple.avkit/documentation/AVKit/working-with-interstitial-content",
        "doc://com.apple.avkit/documentation/AVKit/presenting-content-proposals-in-tvos",
        "doc://com.apple.avkit/documentation/AVKit/working-with-overlays-and-parental-controls-in-tvos",
        "doc://com.apple.avkit/documentation/AVKit/supporting-continuity-camera-in-your-tvos-app",
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController",
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate",
        "doc://com.apple.avkit/documentation/AVKit/AVInterstitialTimeRange",
        "doc://com.apple.avkit/documentation/AVKit/AVNavigationMarkersGroup",
        "doc://com.apple.avkit/documentation/AVKit/AVContentProposalViewController",
        "doc://com.apple.avkit/documentation/AVKit/AVDisplayManager",
        "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewController",
        "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate"
      ],
      "title": "tvOS Playback and Capture"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "tvOS-Playback-and-Capture",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/customizing-the-tvos-playback-experience",
                "doc://com.apple.avkit/documentation/AVKit/working-with-interstitial-content",
                "doc://com.apple.avkit/documentation/AVKit/presenting-content-proposals-in-tvos",
                "doc://com.apple.avkit/documentation/AVKit/working-with-overlays-and-parental-controls-in-tvos",
                "doc://com.apple.avkit/documentation/AVKit/supporting-continuity-camera-in-your-tvos-app",
                "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController",
                "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewControllerDelegate",
                "doc://com.apple.avkit/documentation/AVKit/AVInterstitialTimeRange",
                "doc://com.apple.avkit/documentation/AVKit/AVNavigationMarkersGroup",
                "doc://com.apple.avkit/documentation/AVKit/AVContentProposalViewController",
                "doc://com.apple.avkit/documentation/AVKit/AVDisplayManager",
                "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewController",
                "doc://com.apple.avkit/documentation/AVKit/AVContinuityDevicePickerViewControllerDelegate"
              ],
              "title": "tvOS Playback and Capture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController/title",
          "value": "AVPlayerViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewControllerDelegate/title",
          "value": "AVContinuityDevicePickerViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContinuityDevicePickerViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContinuityDevicePickerViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVDisplayManager/title",
          "value": "AVDisplayManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVDisplayManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVDisplayManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVDisplayManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVDisplayManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposalViewController/title",
          "value": "AVContentProposalViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposalViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentProposalViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContentProposalViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentProposalViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVTimedMetadataGroup/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVTimedMetadataGroup"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVMetadataGroup",
              "text": "AVMetadataGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVInterstitialTimeRange/title",
          "value": "AVInterstitialTimeRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVInterstitialTimeRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVInterstitialTimeRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVInterstitialTimeRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVInterstitialTimeRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewController/title",
          "value": "AVContinuityDevicePickerViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContinuityDevicePickerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVContinuityDevicePickerViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContinuityDevicePickerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVNavigationMarkersGroup/title",
          "value": "AVNavigationMarkersGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVNavigationMarkersGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVNavigationMarkersGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVNavigationMarkersGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVNavigationMarkersGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVPlayerItem~1navigationMarkerGroups/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<AVNavigationMarkersGroup *>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "navigationMarkerGroups"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVMetadataItem/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVMetadataItem"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVPlayerItem/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVPlayerItem"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate/title",
          "value": "AVPlayerViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerViewControllerDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avkit/presenting-navigation-markers"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avkit/presenting-navigation-markers"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
