{
  "abstract": [
    {
      "text": "The framework sets the altitude using a high-resolution digital-elevation model.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum/precise"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ARAltitudeSource@ARAltitudeSourcePrecise",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "precise"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ARAltitudeSourcePrecise"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ARGeoAnchor.AltitudeSource.precise"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "precise"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor": {
      "abstract": [
        {
          "text": "An anchor that identifies a geographic location using latitude, longitude, and altitude data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARGeoAnchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARGeoAnchor"
        }
      ],
      "role": "symbol",
      "title": "ARGeoAnchor",
      "type": "topic",
      "url": "/documentation/arkit/argeoanchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum": {
      "abstract": [
        {
          "text": "Options for setting a location anchor’s altitude.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AltitudeSource"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AltitudeSource"
        }
      ],
      "role": "symbol",
      "title": "ARGeoAnchor.AltitudeSource",
      "type": "topic",
      "url": "/documentation/arkit/argeoanchor/altitudesource-swift.enum"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum/coarse": {
      "abstract": [
        {
          "text": "The framework sets the altitude using a coarse digital-elevation model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coarse"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum/coarse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARAltitudeSourceCoarse"
        }
      ],
      "role": "symbol",
      "title": "ARGeoAnchor.AltitudeSource.coarse",
      "type": "topic",
      "url": "/documentation/arkit/argeoanchor/altitudesource-swift.enum/coarse"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum/precise": {
      "abstract": [
        {
          "text": "The framework sets the altitude using a high-resolution digital-elevation model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "precise"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum/precise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARAltitudeSourcePrecise"
        }
      ],
      "role": "symbol",
      "title": "ARGeoAnchor.AltitudeSource.precise",
      "type": "topic",
      "url": "/documentation/arkit/argeoanchor/altitudesource-swift.enum/precise"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum/unknown": {
      "abstract": [
        {
          "text": "Altitude isn’t yet set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARAltitudeSourceUnknown"
        }
      ],
      "role": "symbol",
      "title": "ARGeoAnchor.AltitudeSource.unknown",
      "type": "topic",
      "url": "/documentation/arkit/argeoanchor/altitudesource-swift.enum/unknown"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum/userDefined": {
      "abstract": [
        {
          "text": "The app defines the altitude.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userDefined"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum/userDefined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARAltitudeSourceUserDefined"
        }
      ],
      "role": "symbol",
      "title": "ARGeoAnchor.AltitudeSource.userDefined",
      "type": "topic",
      "url": "/documentation/arkit/argeoanchor/altitudesource-swift.enum/userdefined"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Sources",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum/coarse",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum/userDefined",
        "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum/unknown"
      ],
      "title": "Sources"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ARAltitudeSourcePrecise"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARAltitudeSourcePrecise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.arkit/documentation/ARKit",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Sources",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum/coarse",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum/userDefined",
                "doc://com.apple.arkit/documentation/ARKit/ARGeoAnchor/AltitudeSource-swift.enum/unknown"
              ],
              "title": "Sources"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ARAltitudeSourcePrecise"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor~1AltitudeSource-swift.enum~1coarse/title",
          "value": "ARAltitudeSourceCoarse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor~1AltitudeSource-swift.enum~1coarse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARAltitudeSourceCoarse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor~1AltitudeSource-swift.enum~1precise/title",
          "value": "ARAltitudeSourcePrecise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor~1AltitudeSource-swift.enum~1precise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARAltitudeSourcePrecise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor/title",
          "value": "ARGeoAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARGeoAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor~1AltitudeSource-swift.enum/title",
          "value": "ARAltitudeSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor~1AltitudeSource-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARAltitudeSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor~1AltitudeSource-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARAltitudeSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor~1AltitudeSource-swift.enum~1userDefined/title",
          "value": "ARAltitudeSourceUserDefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor~1AltitudeSource-swift.enum~1userDefined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARAltitudeSourceUserDefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor~1AltitudeSource-swift.enum~1unknown/title",
          "value": "ARAltitudeSourceUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARGeoAnchor~1AltitudeSource-swift.enum~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARAltitudeSourceUnknown"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/argeoanchor/altitudesource-swift.enum/precise"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/argeoanchor/altitudesource-swift.enum/precise"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
