{"sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t/size"],"title":"Specifying a context’s properties","anchor":"Specifying-a-contexts-properties","generated":true}],"abstract":[{"type":"text","text":"A pointer to the opaque graph context object."}],"variants":[{"paths":["/documentation/accelerate/bnns_graph_context_t/data"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/accelerate/bnns_graph_context_t/data"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","roleHeading":"Instance Property","title":"data","platforms":[{"name":"iOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"18.0"},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"18.0","name":"iPadOS"},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"18.0","name":"Mac Catalyst"},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"15.0","name":"macOS"},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"18.0","name":"tvOS"},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"2.0","name":"visionOS"},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"11.0","name":"watchOS"}],"externalID":"c:@SA@bnns_graph_context_t@FI@data","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UnsafeMutableRawPointer","kind":"typeIdentifier","preciseIdentifier":"s:Sv"},{"text":"?","kind":"text"}],"symbolKind":"property","modules":[{"name":"Accelerate"}],"navigatorTitle":[{"text":"data","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate","doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Sv","text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t/data","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.externally.resolved.symbol/s:Sv":{"abstract":[{"type":"text","text":"A raw pointer for accessing and manipulating untyped data."}],"fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UnsafeMutableRawPointer","kind":"identifier"}],"title":"UnsafeMutableRawPointer","type":"topic","url":"/documentation/Swift/UnsafeMutableRawPointer","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sv","kind":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t/size":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"size"}],"title":"size","type":"topic","abstract":[{"type":"text","text":"The size, in bytes, of the opaque graph context object."}],"url":"/documentation/accelerate/bnns_graph_context_t/size","identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t/size","role":"symbol","kind":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate":{"abstract":[{"text":"Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.","type":"text"}],"type":"topic","title":"Accelerate","identifier":"doc://com.apple.accelerate/documentation/Accelerate","kind":"symbol","url":"/documentation/accelerate","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","kind":"technologies","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t/data":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t/data","role":"symbol","title":"data","url":"/documentation/accelerate/bnns_graph_context_t/data","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"data"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A pointer to the opaque graph context object."}]},"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t":{"url":"/documentation/accelerate/bnns_graph_context_t","identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t","kind":"symbol","type":"topic","abstract":[{"text":"An object that wraps a compiled graph object.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"bnns_graph_context_t"}],"role":"symbol","title":"bnns_graph_context_t","navigatorTitle":[{"kind":"identifier","text":"bnns_graph_context_t"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"beta":false,"deprecated":false,"name":"iOS"},{"unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS"},{"unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst"},{"unavailable":false,"beta":false,"deprecated":false,"name":"macOS"},{"unavailable":false,"beta":false,"deprecated":false,"name":"tvOS"},{"unavailable":false,"beta":false,"deprecated":false,"name":"visionOS"},{"unavailable":false,"beta":false,"deprecated":false,"name":"watchOS"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","value":"data","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"data","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate","doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"generated":true,"title":"Specifying a context’s properties","identifiers":["doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t/size"],"anchor":"Specifying-a-contexts-properties"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"data","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_context_t~1size/title","value":"size","op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_context_t~1size/fragments","value":[{"text":"size","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_context_t~1data/title","value":"data","op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_context_t~1data/fragments","value":[{"kind":"identifier","text":"data"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_context_t/title","value":"bnns_graph_context_t","op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_context_t/fragments","value":[{"text":"bnns_graph_context_t","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_context_t/navigatorTitle","value":[{"text":"bnns_graph_context_t","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}