{
  "abstract": [
    {
      "text": "Creates and initializes a collaboration share options object with the array of groups.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/shareOptionsWithOptionsGroups:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SWCollaborationShareOptions(cm)shareOptionsWithOptionsGroups:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "shareOptionsWithOptionsGroups:"
      }
    ],
    "modules": [
      {
        "name": "Shared With You Core"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "shareOptionsWithOptionsGroups:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "shareOptionsWithOptionsGroups:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SWCollaborationShareOptions",
              "text": "SWCollaborationShareOptions"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "identifier",
              "text": "shareOptionsWithOptionsGroups:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<SWCollaborationOptionsGroup *>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "optionsGroups"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationOptionsGroup",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " objects to customize how the system shares the collaboration.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "optionsGroups"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "code": "SWCollaborationShareOptions",
              "type": "codeVoice"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore": {
      "abstract": [
        {
          "text": "Surface shared content and collaborate in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Shared With You Core",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationOptionsGroup": {
      "abstract": [
        {
          "text": "An object that represents a group of collaboration options that the system displays together.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWCollaborationOptionsGroup"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationOptionsGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWCollaborationOptionsGroup"
        }
      ],
      "role": "symbol",
      "title": "SWCollaborationOptionsGroup",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swcollaborationoptionsgroup"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions": {
      "abstract": [
        {
          "text": "An object that represents the state of the collaboration options for the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWCollaborationShareOptions"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWCollaborationShareOptions"
        }
      ],
      "role": "symbol",
      "title": "SWCollaborationShareOptions",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swcollaborationshareoptions"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/init(coder:)": {
      "abstract": [
        {
          "text": "Creates and initializes a collaboration share options object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/init(coder:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCoder:"
        }
      ],
      "role": "symbol",
      "title": "init(coder:)",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swcollaborationshareoptions/init(coder:)"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/init(optionsGroups:)": {
      "abstract": [
        {
          "text": "Creates and initializes a collaboration share options object with the array of groups.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "optionsGroups"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SWCollaborationOptionsGroup",
          "text": "SWCollaborationOptionsGroup"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/init(optionsGroups:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithOptionsGroups:"
        }
      ],
      "role": "symbol",
      "title": "init(optionsGroups:)",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swcollaborationshareoptions/init(optionsgroups:)"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/init(optionsGroups:summary:)": {
      "abstract": [
        {
          "text": "Creates and initializes a collaboration share options object the array of groups and a summary string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "optionsGroups"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SWCollaborationOptionsGroup",
          "text": "SWCollaborationOptionsGroup"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "summary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/init(optionsGroups:summary:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithOptionsGroups:summary:"
        }
      ],
      "role": "symbol",
      "title": "init(optionsGroups:summary:)",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swcollaborationshareoptions/init(optionsgroups:summary:)"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/shareOptionsWithOptionsGroups:": {
      "abstract": [
        {
          "text": "Creates and initializes a collaboration share options object with the array of groups.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "shareOptionsWithOptionsGroups:"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/shareOptionsWithOptionsGroups:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shareOptionsWithOptionsGroups:"
        }
      ],
      "role": "symbol",
      "title": "shareOptionsWithOptionsGroups:",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swcollaborationshareoptions/shareoptionswithoptionsgroups:"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/shareOptionsWithOptionsGroups:summary:": {
      "abstract": [
        {
          "text": "Creates and initializes a collaboration share options object the array of groups and a summary string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "shareOptionsWithOptionsGroups:summary:"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/shareOptionsWithOptionsGroups:summary:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shareOptionsWithOptionsGroups:summary:"
        }
      ],
      "role": "symbol",
      "title": "shareOptionsWithOptionsGroups:summary:",
      "type": "topic",
      "url": "/documentation/sharedwithyoucore/swcollaborationshareoptions/shareoptionswithoptionsgroups:summary:"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-share-options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/init(coder:)",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/init(optionsGroups:)",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/init(optionsGroups:summary:)",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYouCore/SWCollaborationShareOptions/shareOptionsWithOptionsGroups:summary:"
      ],
      "title": "Creating share options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationShareOptions~1init(optionsGroups:)/title",
          "value": "initWithOptionsGroups:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationShareOptions~1init(optionsGroups:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithOptionsGroups:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationShareOptions/title",
          "value": "SWCollaborationShareOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationShareOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWCollaborationShareOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationShareOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWCollaborationShareOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationOptionsGroup/title",
          "value": "SWCollaborationOptionsGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationOptionsGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWCollaborationOptionsGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationOptionsGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWCollaborationOptionsGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationShareOptions~1init(coder:)/title",
          "value": "initWithCoder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationShareOptions~1init(coder:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCoder:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationShareOptions~1init(optionsGroups:summary:)/title",
          "value": "initWithOptionsGroups:summary:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYouCore~1SWCollaborationShareOptions~1init(optionsGroups:summary:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithOptionsGroups:summary:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sharedwithyoucore/swcollaborationshareoptions/shareoptionswithoptionsgroups:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
