{
  "abstract": [
    {
      "text": "A change that requires the system to redraw a view’s content.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSView",
        "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidations/Display"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So6NSViewC6AppKitE13InvalidationsO7DisplayV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Display"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Display"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.1",
        "name": "Swift",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "NSView.Invalidations.Display"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Display"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSViewInvalidating/display",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to create an instance of this type.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/appkit/nsview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidations": {
      "abstract": [
        {
          "text": "Changes that cause aspects of a view to be invalid and require an update.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Invalidations"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Invalidations"
        }
      ],
      "role": "symbol",
      "title": "NSView.Invalidations",
      "type": "topic",
      "url": "/documentation/appkit/nsview/invalidations"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidations/Constraints": {
      "abstract": [
        {
          "text": "A change that invalidates a view’s constraints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Constraints"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidations/Constraints",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Constraints"
        }
      ],
      "role": "symbol",
      "title": "NSView.Invalidations.Constraints",
      "type": "topic",
      "url": "/documentation/appkit/nsview/invalidations/constraints"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidations/Display": {
      "abstract": [
        {
          "text": "A change that requires the system to redraw a view’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Display"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidations/Display",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Display"
        }
      ],
      "role": "symbol",
      "title": "NSView.Invalidations.Display",
      "type": "topic",
      "url": "/documentation/appkit/nsview/invalidations/display"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidations/Display/init()": {
      "abstract": [
        {
          "text": "Creates the invalidation type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidations/Display/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/appkit/nsview/invalidations/display/init()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidations/IntrinsicContentSize": {
      "abstract": [
        {
          "text": "A change that invalidates a view’s intrinsic size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IntrinsicContentSize"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidations/IntrinsicContentSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IntrinsicContentSize"
        }
      ],
      "role": "symbol",
      "title": "NSView.Invalidations.IntrinsicContentSize",
      "type": "topic",
      "url": "/documentation/appkit/nsview/invalidations/intrinsiccontentsize"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidations/Layout": {
      "abstract": [
        {
          "text": "A change that invalidates the layout of the containing view’s subviews.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Layout"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidations/Layout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Layout"
        }
      ],
      "role": "symbol",
      "title": "NSView.Invalidations.Layout",
      "type": "topic",
      "url": "/documentation/appkit/nsview/invalidations/layout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidations/RestorableState": {
      "abstract": [
        {
          "text": "A change that invalidates the restorable state of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RestorableState"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidations/RestorableState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RestorableState"
        }
      ],
      "role": "symbol",
      "title": "NSView.Invalidations.RestorableState",
      "type": "topic",
      "url": "/documentation/appkit/nsview/invalidations/restorablestate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidations/Tuple": {
      "abstract": [
        {
          "text": "A change that invalidates a combination of factors covered by the other invalidation types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Tuple"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidations/Tuple",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Tuple"
        }
      ],
      "role": "symbol",
      "title": "NSView.Invalidations.Tuple",
      "type": "topic",
      "url": "/documentation/appkit/nsview/invalidations/tuple"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/display()": {
      "abstract": [
        {
          "text": "Displays the view and all its subviews if possible, invoking each of the ",
          "type": "text"
        },
        {
          "code": "NSView",
          "type": "codeVoice"
        },
        {
          "text": " methods ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/lockFocus()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/draw(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/unlockFocus()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " as necessary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "display"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/display()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "display"
        }
      ],
      "role": "symbol",
      "title": "display()",
      "type": "topic",
      "url": "/documentation/appkit/nsview/display()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/draw(_:)": {
      "abstract": [
        {
          "text": "Overridden by subclasses to draw the view’s image within the specified rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draw"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/draw(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawRect:"
        }
      ],
      "role": "symbol",
      "title": "draw(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsview/draw(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/lockFocus()": {
      "abstract": [
        {
          "text": "Locks the focus on the view, so subsequent commands take effect in the view’s window and coordinate system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lockFocus"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/lockFocus()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lockFocus"
        }
      ],
      "role": "symbol",
      "title": "lockFocus()",
      "type": "topic",
      "url": "/documentation/appkit/nsview/lockfocus()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/unlockFocus()": {
      "abstract": [
        {
          "text": "Unlocks focus from the current view.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unlockFocus"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/unlockFocus()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unlockFocus"
        }
      ],
      "role": "symbol",
      "title": "unlockFocus()",
      "type": "topic",
      "url": "/documentation/appkit/nsview/unlockfocus()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSViewInvalidating": {
      "abstract": [
        {
          "text": "Implements a type of invalidation that can occur on a view that requires an update.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSViewInvalidating"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSViewInvalidating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewInvalidating"
        }
      ],
      "role": "symbol",
      "title": "NSViewInvalidating",
      "type": "topic",
      "url": "/documentation/appkit/nsviewinvalidating"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSViewInvalidating/display": {
      "abstract": [
        {
          "text": "A change that requires the system to redraw a view’s content.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Self",
            "type": "codeVoice"
          },
          {
            "text": " is ",
            "type": "text"
          },
          {
            "code": "NSView.Invalidations.Display",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "display"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So6NSViewC6AppKitE13InvalidationsO",
          "text": "Invalidations"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So6NSViewC6AppKitE13InvalidationsO7DisplayV",
          "text": "Display"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSViewInvalidating/display",
      "kind": "symbol",
      "role": "symbol",
      "title": "display",
      "type": "topic",
      "url": "/documentation/appkit/nsviewinvalidating/display"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSViewInvalidating"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Types-of-Invalidations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidations/Constraints",
        "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidations/IntrinsicContentSize",
        "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidations/Layout",
        "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidations/RestorableState",
        "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidations/Tuple"
      ],
      "title": "Types of Invalidations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-the-invalidation-type",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/display()",
        "doc://com.apple.appkit/documentation/AppKit/NSView/Invalidations/Display/init()"
      ],
      "title": "Creating the invalidation type"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1lockFocus()/title",
          "value": "lockFocus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1lockFocus()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "lockFocus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1display()/title",
          "value": "display"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1display()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "display"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1unlockFocus()/title",
          "value": "unlockFocus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1unlockFocus()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "unlockFocus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title",
          "value": "NSView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1draw(_:)/title",
          "value": "drawRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1draw(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawRect:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsview/invalidations/display"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
