{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/modelio/mdlaxisalignedboundingbox/init(maxbounds:minbounds:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.modelio/documentation/ModelIO/MDLAxisAlignedBoundingBox/init(maxBounds:minBounds:)"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"maxBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@vector_float3","text":"vector_float3","identifier":"doc://com.externally.resolved.symbol/c:@T@vector_float3","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"minBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@vector_float3","text":"vector_float3","identifier":"doc://com.externally.resolved.symbol/c:@T@vector_float3","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"sections":[],"metadata":{"role":"symbol","externalID":"s:So25MDLAxisAlignedBoundingBoxa9maxBounds03minF0ABs5SIMD3VySfG_AGtcfc","roleHeading":"Initializer","title":"init(maxBounds:minBounds:)","symbolKind":"init","modules":[{"name":"Model I/O"}],"platforms":[{"introducedAt":"9.0","unavailable":false,"beta":false,"name":"iOS","deprecated":false},{"introducedAt":"9.0","unavailable":false,"beta":false,"name":"iPadOS","deprecated":false},{"introducedAt":"13.0","unavailable":false,"beta":false,"name":"Mac Catalyst","deprecated":false},{"introducedAt":"10.11","unavailable":false,"beta":false,"name":"macOS","deprecated":false},{"introducedAt":"9.0","unavailable":false,"beta":false,"name":"tvOS","deprecated":false},{"introducedAt":"1.0","unavailable":false,"beta":false,"name":"visionOS","deprecated":false}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"maxBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"vector_float3","kind":"typeIdentifier","preciseIdentifier":"c:@T@vector_float3"},{"text":", ","kind":"text"},{"text":"minBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"vector_float3","kind":"typeIdentifier","preciseIdentifier":"c:@T@vector_float3"},{"text":")","kind":"text"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO","doc://com.apple.modelio/documentation/ModelIO/MDLAxisAlignedBoundingBox"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.modelio/documentation/ModelIO/MDLAxisAlignedBoundingBox/init(maxBounds:minBounds:)":{"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAxisAlignedBoundingBox/init(maxBounds:minBounds:)","url":"/documentation/modelio/mdlaxisalignedboundingbox/init(maxbounds:minbounds:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"maxBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@vector_float3","text":"vector_float3","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"minBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@vector_float3","text":"vector_float3","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"init(maxBounds:minBounds:)","type":"topic","abstract":[]},"doc://com.apple.modelio/documentation/ModelIO":{"identifier":"doc://com.apple.modelio/documentation/ModelIO","title":"Model I/O","role":"collection","kind":"symbol","abstract":[{"text":"Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.","type":"text"}],"type":"topic","url":"/documentation/modelio"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","kind":"technologies","role":"overview","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLObject/boundingBox(atTime:)":{"title":"boundingBox(atTime:)","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"boundingBox","kind":"identifier"},{"text":"(","kind":"text"},{"text":"atTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":") -> ","kind":"text"},{"text":"MDLAxisAlignedBoundingBox","kind":"typeIdentifier","preciseIdentifier":"c:@SA@MDLAxisAlignedBoundingBox"}],"url":"/documentation/modelio/mdlobject/boundingbox(attime:)","abstract":[{"text":"Returns the minimum region entirely enclosing the object’s contents at the specified time sample.","type":"text"}],"navigatorTitle":[{"text":"boundingBoxAtTime:","kind":"identifier"}],"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLObject/boundingBox(atTime:)"},"doc://com.apple.modelio/documentation/ModelIO/MDLAxisAlignedBoundingBox":{"title":"MDLAxisAlignedBoundingBox","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLAxisAlignedBoundingBox","type":"topic","navigatorTitle":[{"text":"MDLAxisAlignedBoundingBox","kind":"identifier"}],"url":"/documentation/modelio/mdlaxisalignedboundingbox","abstract":[{"type":"text","text":"The minimal volume containing an object, used by the "},{"isActive":true,"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLObject/boundingBox(atTime:)","type":"reference"},{"text":" method.","type":"text"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MDLAxisAlignedBoundingBox","kind":"identifier"}],"kind":"symbol"},"doc://com.externally.resolved.symbol/c:@T@vector_float3":{"url":"/documentation/SpriteKit/vector_float3","title":"vector_float3","fragments":[{"text":"typedef","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:]3f","text":"float __attribute__((ext_vector_type(3)))","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"vector_float3"},{"text":";","kind":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@vector_float3","role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"A floating point vector type used to perform physics calculations.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLObject~1boundingBox(atTime:)/title","value":"boundingBoxAtTime:"},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLObject~1boundingBox(atTime:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"boundingBoxAtTime:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAxisAlignedBoundingBox/title","value":"MDLAxisAlignedBoundingBox"},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAxisAlignedBoundingBox/fragments","value":[{"kind":"identifier","text":"MDLAxisAlignedBoundingBox"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAxisAlignedBoundingBox/navigatorTitle","value":[{"kind":"identifier","text":"MDLAxisAlignedBoundingBox"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}