{
  "abstract": [
    {
      "text": "A pseudonymn for a real application identifier.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sensorkit/documentation/SensorKit",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage/reportApplicationIdentifier"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SRApplicationUsage(py)reportApplicationIdentifier",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "reportApplicationIdentifier"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "reportApplicationIdentifier"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "reportApplicationIdentifier"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "reportApplicationIdentifier"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value of this property uniquely refers to a single app throughout the report without revealing the app’s true identity. For user privacy, the system assigns this property a pseudonymous string in cases where the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage/bundleIdentifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport": {
      "abstract": [
        {
          "text": "The frequency and relative duration that the user uses their device, particular Apple apps, or websites.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRDeviceUsageReport"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageReport"
        }
      ],
      "role": "symbol",
      "title": "SRDeviceUsageReport",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage": {
      "abstract": [
        {
          "text": "An object that describes the user’s app activity over a period of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ApplicationUsage"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ApplicationUsage"
        }
      ],
      "role": "symbol",
      "title": "SRDeviceUsageReport.ApplicationUsage",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/applicationusage"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage/bundleIdentifier": {
      "abstract": [
        {
          "text": "The bundle identifier of the app in use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bundleIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage/bundleIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bundleIdentifier"
        }
      ],
      "role": "symbol",
      "title": "bundleIdentifier",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/applicationusage/bundleidentifier"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage/reportApplicationIdentifier": {
      "abstract": [
        {
          "text": "A pseudonymn for a real application identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportApplicationIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage/reportApplicationIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportApplicationIdentifier"
        }
      ],
      "role": "symbol",
      "title": "reportApplicationIdentifier",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/applicationusage/reportapplicationidentifier"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage/supplementalCategories": {
      "abstract": [
        {
          "text": "Categories that provide more information about an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supplementalCategories"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRSupplementalCategory",
          "text": "SRSupplementalCategory"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage/supplementalCategories",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supplementalCategories"
        }
      ],
      "role": "symbol",
      "title": "supplementalCategories",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/applicationusage/supplementalcategories"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRSupplementalCategory": {
      "abstract": [
        {
          "text": "A more detailed category that provides additional context to the app category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRSupplementalCategory"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRSupplementalCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRSupplementalCategory"
        }
      ],
      "role": "symbol",
      "title": "SRSupplementalCategory",
      "type": "topic",
      "url": "/documentation/sensorkit/srsupplementalcategory"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Identifying-the-App",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage/bundleIdentifier",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage/supplementalCategories",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRSupplementalCategory"
      ],
      "title": "Identifying the App"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "reportApplicationIdentifier"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reportApplicationIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sensorkit/documentation/SensorKit",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Identifying-the-App",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage/bundleIdentifier",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/ApplicationUsage/supplementalCategories",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRSupplementalCategory"
              ],
              "title": "Identifying the App"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "reportApplicationIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSupplementalCategory/title",
          "value": "SRSupplementalCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSupplementalCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSupplementalCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSupplementalCategory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRSupplementalCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1ApplicationUsage/title",
          "value": "SRApplicationUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1ApplicationUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRApplicationUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1ApplicationUsage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRApplicationUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1ApplicationUsage~1supplementalCategories/title",
          "value": "supplementalCategories"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1ApplicationUsage~1supplementalCategories/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supplementalCategories"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1ApplicationUsage~1reportApplicationIdentifier/title",
          "value": "reportApplicationIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1ApplicationUsage~1reportApplicationIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reportApplicationIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1ApplicationUsage~1bundleIdentifier/title",
          "value": "bundleIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1ApplicationUsage~1bundleIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bundleIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport/title",
          "value": "SRDeviceUsageReport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageReport"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit/srdeviceusagereport/applicationusage/reportapplicationidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sensorkit/srdeviceusagereport/applicationusage/reportapplicationidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
