{
  "abstract": [
    {
      "text": "A color space object that represents a gray color space with a gamma value of 2.2.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericGamma22Gray"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSColorSpace(cpy)genericGamma22GrayColorSpace",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "genericGamma22Gray"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSColorSpace",
        "text": "NSColorSpace"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "genericGamma22GrayColorSpace"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "genericGamma22Gray"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "genericGamma22Gray"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSColorSpace",
              "text": "NSColorSpace"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "NSColorSpace",
              "type": "codeVoice"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace": {
      "abstract": [
        {
          "text": "An object that represents a custom color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSpace"
        }
      ],
      "role": "symbol",
      "title": "NSColorSpace",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/adobeRGB1998": {
      "abstract": [
        {
          "text": "A color space object that represents an Adobe RGB (1998) color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adobeRGB1998"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/adobeRGB1998",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "adobeRGB1998ColorSpace"
        }
      ],
      "role": "symbol",
      "title": "adobeRGB1998",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/adobergb1998"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/deviceCMYK": {
      "abstract": [
        {
          "text": "A color space object that represents a calibrated or device-dependent CMYK color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceCMYK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/deviceCMYK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceCMYKColorSpace"
        }
      ],
      "role": "symbol",
      "title": "deviceCMYK",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/devicecmyk"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/deviceGray": {
      "abstract": [
        {
          "text": "A color space object that represents a calibrated or device-dependent gray color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceGray"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/deviceGray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceGrayColorSpace"
        }
      ],
      "role": "symbol",
      "title": "deviceGray",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/devicegray"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/deviceRGB": {
      "abstract": [
        {
          "text": "A color space object that represents a calibrated or device-dependent RGB color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceRGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/deviceRGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceRGBColorSpace"
        }
      ],
      "role": "symbol",
      "title": "deviceRGB",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/devicergb"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/displayP3": {
      "abstract": [
        {
          "text": "A color space object that represents a P3 Display color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayP3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/displayP3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayP3ColorSpace"
        }
      ],
      "role": "symbol",
      "title": "displayP3",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/displayp3"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/extendedGenericGamma22Gray": {
      "abstract": [
        {
          "text": "A color space object that represents an extended gray color space with a gamma value of 2.2.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extendedGenericGamma22Gray"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/extendedGenericGamma22Gray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "extendedGenericGamma22GrayColorSpace"
        }
      ],
      "role": "symbol",
      "title": "extendedGenericGamma22Gray",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/extendedgenericgamma22gray"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/extendedSRGB": {
      "abstract": [
        {
          "text": "A color space object that represents an extended sRGB color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extendedSRGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/extendedSRGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "extendedSRGBColorSpace"
        }
      ],
      "role": "symbol",
      "title": "extendedSRGB",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/extendedsrgb"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericCMYK": {
      "abstract": [
        {
          "text": "A color space object that represents a device-independent CMYK color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "genericCMYK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericCMYK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "genericCMYKColorSpace"
        }
      ],
      "role": "symbol",
      "title": "genericCMYK",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/genericcmyk"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericGamma22Gray": {
      "abstract": [
        {
          "text": "A color space object that represents a gray color space with a gamma value of 2.2.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "genericGamma22Gray"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericGamma22Gray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "genericGamma22GrayColorSpace"
        }
      ],
      "role": "symbol",
      "title": "genericGamma22Gray",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/genericgamma22gray"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericGray": {
      "abstract": [
        {
          "text": "A color space object that represents a device-independent gray color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "genericGray"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericGray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "genericGrayColorSpace"
        }
      ],
      "role": "symbol",
      "title": "genericGray",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/genericgray"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericRGB": {
      "abstract": [
        {
          "text": "A color space object that represents a device-independent RGB color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "genericRGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericRGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "genericRGBColorSpace"
        }
      ],
      "role": "symbol",
      "title": "genericRGB",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/genericrgb"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/sRGB": {
      "abstract": [
        {
          "text": "A color space object that represents an sRGB color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sRGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/sRGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sRGBColorSpace"
        }
      ],
      "role": "symbol",
      "title": "sRGB",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/srgb"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-a-Named-Color-Space",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/deviceRGB",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericRGB",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/deviceCMYK",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericCMYK",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/deviceGray",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericGray",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/sRGB",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/extendedSRGB",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/displayP3",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/extendedGenericGamma22Gray",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/adobeRGB1998"
      ],
      "title": "Getting a Named Color Space"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "genericGamma22GrayColorSpace"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "genericGamma22GrayColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-a-Named-Color-Space",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/deviceRGB",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericRGB",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/deviceCMYK",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericCMYK",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/deviceGray",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/genericGray",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/sRGB",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/extendedSRGB",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/displayP3",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/extendedGenericGamma22Gray",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/adobeRGB1998"
              ],
              "title": "Getting a Named Color Space"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "class"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSColorSpace",
                    "text": "NSColorSpace"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "genericGamma22GrayColorSpace"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1adobeRGB1998/title",
          "value": "adobeRGB1998ColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1adobeRGB1998/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "adobeRGB1998ColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace/title",
          "value": "NSColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1genericRGB/title",
          "value": "genericRGBColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1genericRGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "genericRGBColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1deviceGray/title",
          "value": "deviceGrayColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1deviceGray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deviceGrayColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1extendedGenericGamma22Gray/title",
          "value": "extendedGenericGamma22GrayColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1extendedGenericGamma22Gray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "extendedGenericGamma22GrayColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1deviceCMYK/title",
          "value": "deviceCMYKColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1deviceCMYK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deviceCMYKColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1sRGB/title",
          "value": "sRGBColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1sRGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sRGBColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1genericCMYK/title",
          "value": "genericCMYKColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1genericCMYK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "genericCMYKColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1genericGamma22Gray/title",
          "value": "genericGamma22GrayColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1genericGamma22Gray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "genericGamma22GrayColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1deviceRGB/title",
          "value": "deviceRGBColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1deviceRGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deviceRGBColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1extendedSRGB/title",
          "value": "extendedSRGBColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1extendedSRGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "extendedSRGBColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1displayP3/title",
          "value": "displayP3ColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1displayP3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayP3ColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1genericGray/title",
          "value": "genericGrayColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1genericGray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "genericGrayColorSpace"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nscolorspace/genericgamma22gray"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nscolorspace/genericgamma22gray"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
