{
  "abstract": [
    {
      "text": "Constants that describe the abstract model on which color space objects are based.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@E@NSColorSpaceModel",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Model"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Model"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSColorSpace.Model"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Model"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCMYKColorSpaceModel": {
      "abstract": [
        {
          "text": "The CYMK (cyan, yellow, magenta, black) color-space model.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCMYKColorSpaceModel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCMYKColorSpaceModel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCMYKColorSpaceModel",
      "type": "topic",
      "url": "/documentation/appkit/nscmykcolorspacemodel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace": {
      "abstract": [
        {
          "text": "An object that represents a custom color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSpace"
        }
      ],
      "role": "symbol",
      "title": "NSColorSpace",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model": {
      "abstract": [
        {
          "text": "Constants that describe the abstract model on which color space objects are based.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Model"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Model"
        }
      ],
      "role": "symbol",
      "title": "NSColorSpace.Model",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/model"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/cmyk": {
      "abstract": [
        {
          "text": "The CMYK (cyan-magenta-yellow-black) color-space model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cmyk"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/cmyk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSpaceModelCMYK"
        }
      ],
      "role": "symbol",
      "title": "NSColorSpace.Model.cmyk",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/model/cmyk"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/deviceN": {
      "abstract": [
        {
          "text": "The DeviceN color-space model from Adobe Systems, Inc.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceN"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/deviceN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSpaceModelDeviceN"
        }
      ],
      "role": "symbol",
      "title": "NSColorSpace.Model.deviceN",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/model/devicen"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/gray": {
      "abstract": [
        {
          "text": "The grayscale color-space model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gray"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/gray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSpaceModelGray"
        }
      ],
      "role": "symbol",
      "title": "NSColorSpace.Model.gray",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/model/gray"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/indexed": {
      "abstract": [
        {
          "text": "An indexed color space, which identifies discrete colors in a color list by index number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indexed"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/indexed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSpaceModelIndexed"
        }
      ],
      "role": "symbol",
      "title": "NSColorSpace.Model.indexed",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/model/indexed"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/model/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/lab": {
      "abstract": [
        {
          "text": "The L*a*b* device-independent color-space model, which represents colors relative to a reference white point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lab"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/lab",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSpaceModelLAB"
        }
      ],
      "role": "symbol",
      "title": "NSColorSpace.Model.lab",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/model/lab"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/patterned": {
      "abstract": [
        {
          "text": "A pattern color space, which is a repeated image that creates a tiled pattern.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "patterned"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/patterned",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSpaceModelPatterned"
        }
      ],
      "role": "symbol",
      "title": "NSColorSpace.Model.patterned",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/model/patterned"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/rgb": {
      "abstract": [
        {
          "text": "The RGB (red-green-blue) color-space model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rgb"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/rgb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSpaceModelRGB"
        }
      ],
      "role": "symbol",
      "title": "NSColorSpace.Model.rgb",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/model/rgb"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/unknown": {
      "abstract": [
        {
          "text": "An unknown color-space model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSpaceModelUnknown"
        }
      ],
      "role": "symbol",
      "title": "NSColorSpace.Model.unknown",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/model/unknown"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/cgColorSpace": {
      "abstract": [
        {
          "text": "The Core Graphics color-space object that represents a color space equivalent to the color space’s.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cgColorSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorSpaceRef",
          "text": "CGColorSpace"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/cgColorSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGColorSpace"
        }
      ],
      "role": "symbol",
      "title": "cgColorSpace",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/cgcolorspace"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/colorSpaceModel": {
      "abstract": [
        {
          "text": "The model on which the color space is based.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorSpaceModel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSColorSpaceModel",
          "text": "Model"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/colorSpaceModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorSpaceModel"
        }
      ],
      "role": "symbol",
      "title": "colorSpaceModel",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/colorspacemodel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/colorSyncProfile": {
      "abstract": [
        {
          "text": "The ColorSync profile from which the color space was created.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorSyncProfile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/colorSyncProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorSyncProfile"
        }
      ],
      "role": "symbol",
      "title": "colorSyncProfile",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/colorsyncprofile"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/iccProfileData": {
      "abstract": [
        {
          "text": "The ICC profile data from which the color space was created.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iccProfileData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/iccProfileData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICCProfileData"
        }
      ],
      "role": "symbol",
      "title": "iccProfileData",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/iccprofiledata"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/localizedName": {
      "abstract": [
        {
          "text": "The localized name of the color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/localizedName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedName"
        }
      ],
      "role": "symbol",
      "title": "localizedName",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/localizedname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/numberOfColorComponents": {
      "abstract": [
        {
          "text": "The number of components, excluding alpha, the color space supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfColorComponents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/numberOfColorComponents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfColorComponents"
        }
      ],
      "role": "symbol",
      "title": "numberOfColorComponents",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace/numberofcolorcomponents"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDeviceNColorSpaceModel": {
      "abstract": [
        {
          "text": "DeviceN is a color-space model from Adobe Systems, Inc. used in PostScript and PDF color specification.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSDeviceNColorSpaceModel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDeviceNColorSpaceModel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDeviceNColorSpaceModel",
      "type": "topic",
      "url": "/documentation/appkit/nsdevicencolorspacemodel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGrayColorSpaceModel": {
      "abstract": [
        {
          "text": "The grayscale color-space model.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSGrayColorSpaceModel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGrayColorSpaceModel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSGrayColorSpaceModel",
      "type": "topic",
      "url": "/documentation/appkit/nsgraycolorspacemodel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSIndexedColorSpaceModel": {
      "abstract": [
        {
          "text": "An indexed color space, which identifies specified discrete colors in a color list by index number. An indexed color value (a color specification in indexed color space) consists of an index value that refers to a color in a color list.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSIndexedColorSpaceModel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSIndexedColorSpaceModel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSIndexedColorSpaceModel",
      "type": "topic",
      "url": "/documentation/appkit/nsindexedcolorspacemodel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLABColorSpaceModel": {
      "abstract": [
        {
          "text": "The L*a*b* device-independent color-space model, which represents colors relative to a reference white point.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLABColorSpaceModel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLABColorSpaceModel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLABColorSpaceModel",
      "type": "topic",
      "url": "/documentation/appkit/nslabcolorspacemodel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPatternColorSpaceModel": {
      "abstract": [
        {
          "text": "Identifies a pattern color space, which is simply an image that is repeated over and over again in a tiled pattern.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPatternColorSpaceModel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPatternColorSpaceModel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPatternColorSpaceModel",
      "type": "topic",
      "url": "/documentation/appkit/nspatterncolorspacemodel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRGBColorSpaceModel": {
      "abstract": [
        {
          "text": "The RGB (red green blue) color-space model.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRGBColorSpaceModel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRGBColorSpaceModel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRGBColorSpaceModel",
      "type": "topic",
      "url": "/documentation/appkit/nsrgbcolorspacemodel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUnknownColorSpaceModel": {
      "abstract": [
        {
          "text": "An unknown color-space model.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnknownColorSpaceModel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUnknownColorSpaceModel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnknownColorSpaceModel",
      "type": "topic",
      "url": "/documentation/appkit/nsunknowncolorspacemodel"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Color-Space-Data-and-Attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/cgColorSpace",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/colorSpaceModel",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/colorSyncProfile",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/iccProfileData",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/localizedName",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/numberOfColorComponents"
      ],
      "title": "Accessing Color Space Data and Attributes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Color-Spaces",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/unknown",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/gray",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/rgb",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/cmyk",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/lab",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/deviceN",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/indexed",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/patterned"
      ],
      "title": "Color Spaces"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSColorSpaceModel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Color-Spaces",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/unknown",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/gray",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/rgb",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/cmyk",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/lab",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/deviceN",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/indexed",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/Model/patterned"
              ],
              "title": "Color Spaces"
            },
            {
              "anchor": "Deprecated-Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSUnknownColorSpaceModel",
                "doc://com.apple.appkit/documentation/AppKit/NSGrayColorSpaceModel",
                "doc://com.apple.appkit/documentation/AppKit/NSRGBColorSpaceModel",
                "doc://com.apple.appkit/documentation/AppKit/NSCMYKColorSpaceModel",
                "doc://com.apple.appkit/documentation/AppKit/NSLABColorSpaceModel",
                "doc://com.apple.appkit/documentation/AppKit/NSDeviceNColorSpaceModel",
                "doc://com.apple.appkit/documentation/AppKit/NSIndexedColorSpaceModel",
                "doc://com.apple.appkit/documentation/AppKit/NSPatternColorSpaceModel"
              ],
              "title": "Deprecated Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Color-Space-Data-and-Attributes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/cgColorSpace",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/colorSpaceModel",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/colorSyncProfile",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/iccProfileData",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/localizedName",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpace/numberOfColorComponents"
              ],
              "title": "Accessing Color Space Data and Attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSColorSpaceModel"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1numberOfColorComponents/title",
          "value": "numberOfColorComponents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1numberOfColorComponents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfColorComponents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model/title",
          "value": "NSColorSpaceModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1lab/title",
          "value": "NSColorSpaceModelLAB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1lab/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceModelLAB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1unknown/title",
          "value": "NSColorSpaceModelUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceModelUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1colorSyncProfile/title",
          "value": "colorSyncProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1colorSyncProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "colorSyncProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1deviceN/title",
          "value": "NSColorSpaceModelDeviceN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1deviceN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceModelDeviceN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1cgColorSpace/title",
          "value": "CGColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1cgColorSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1cmyk/title",
          "value": "NSColorSpaceModelCMYK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1cmyk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceModelCMYK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1gray/title",
          "value": "NSColorSpaceModelGray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1gray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceModelGray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace/title",
          "value": "NSColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1patterned/title",
          "value": "NSColorSpaceModelPatterned"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1patterned/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceModelPatterned"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1indexed/title",
          "value": "NSColorSpaceModelIndexed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1indexed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceModelIndexed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1localizedName/title",
          "value": "localizedName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1localizedName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1colorSpaceModel/title",
          "value": "colorSpaceModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1colorSpaceModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "colorSpaceModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1iccProfileData/title",
          "value": "ICCProfileData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1iccProfileData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICCProfileData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1rgb/title",
          "value": "NSColorSpaceModelRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace~1Model~1rgb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceModelRGB"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nscolorspace/model"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nscolorspace/model"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
