{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/1411865-anonymous"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "IOBluetooth UI"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Anonymous"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI": {
      "abstract": [
        {
          "text": "Present an interface through which users can pair their devices with other Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth UI",
      "type": "topic",
      "url": "/documentation/iobluetoothui"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/1411883-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/1411883-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iobluetoothui/1411883-anonymous"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/BluetoothKeyboardReturnType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothKeyboardReturnType"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/BluetoothKeyboardReturnType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothKeyboardReturnType"
        }
      ],
      "role": "symbol",
      "title": "BluetoothKeyboardReturnType",
      "type": "topic",
      "url": "/documentation/iobluetoothui/bluetoothkeyboardreturntype"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetoothUI Enumerations",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothui-enumerations"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kIOBluetoothUISuccess": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOBluetoothUISuccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kIOBluetoothUISuccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOBluetoothUISuccess"
        }
      ],
      "role": "symbol",
      "title": "kIOBluetoothUISuccess",
      "type": "topic",
      "url": "/documentation/iobluetoothui/kiobluetoothuisuccess"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kIOBluetoothUIUserCanceledErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOBluetoothUIUserCanceledErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kIOBluetoothUIUserCanceledErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOBluetoothUIUserCanceledErr"
        }
      ],
      "role": "symbol",
      "title": "kIOBluetoothUIUserCanceledErr",
      "type": "topic",
      "url": "/documentation/iobluetoothui/kiobluetoothuiusercancelederr"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/1411883-anonymous",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/BluetoothKeyboardReturnType"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kIOBluetoothUISuccess",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kIOBluetoothUIUserCanceledErr"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kIOBluetoothUISuccess",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kIOBluetoothUIUserCanceledErr"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1kIOBluetoothUIUserCanceledErr/title",
          "value": "kIOBluetoothUIUserCanceledErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1kIOBluetoothUIUserCanceledErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOBluetoothUIUserCanceledErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1BluetoothKeyboardReturnType/title",
          "value": "BluetoothKeyboardReturnType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1BluetoothKeyboardReturnType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothKeyboardReturnType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1BluetoothKeyboardReturnType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothKeyboardReturnType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1kIOBluetoothUISuccess/title",
          "value": "kIOBluetoothUISuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1kIOBluetoothUISuccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOBluetoothUISuccess"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetoothui/1411865-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetoothui/1411865-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
