{
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "IOBluetooth UI"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "IOBluetoothUI Enumerations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI": {
      "abstract": [
        {
          "text": "Present an interface through which users can pair their devices with other Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth UI",
      "type": "topic",
      "url": "/documentation/iobluetoothui"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/1411865-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/1411865-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iobluetoothui/1411865-anonymous"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/1411883-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/1411883-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/iobluetoothui/1411883-anonymous"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/BluetoothKeyboardReturnType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothKeyboardReturnType"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/BluetoothKeyboardReturnType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothKeyboardReturnType"
        }
      ],
      "role": "symbol",
      "title": "BluetoothKeyboardReturnType",
      "type": "topic",
      "url": "/documentation/iobluetoothui/bluetoothkeyboardreturntype"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetoothUI Constants",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothui-constants"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetoothUI Functions",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothui-functions"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothuiuserlib-h": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothuiuserlib-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetoothUIUserLib.h",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothuiuserlib-h"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothuiuserlib-h",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-constants",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-functions"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/1411883-anonymous",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/1411865-anonymous",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/BluetoothKeyboardReturnType"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/BluetoothKeyboardReturnType"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothuiuserlib-h",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-constants",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-functions"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1BluetoothKeyboardReturnType/title",
          "value": "BluetoothKeyboardReturnType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1BluetoothKeyboardReturnType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothKeyboardReturnType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1BluetoothKeyboardReturnType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothKeyboardReturnType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetoothui/iobluetoothui-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetoothui/iobluetoothui-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
