{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-functions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "IOBluetooth UI"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "IOBluetoothUI Functions"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI": {
      "abstract": [
        {
          "text": "Present an interface through which users can pair their devices with other Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth UI",
      "type": "topic",
      "url": "/documentation/iobluetoothui"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothGetDeviceSelectorController()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothGetDeviceSelectorController"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOBluetoothDeviceSelectorControllerRef",
          "text": "IOBluetoothDeviceSelectorControllerRef"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothGetDeviceSelectorController()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothGetDeviceSelectorController"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothGetDeviceSelectorController()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothgetdeviceselectorcontroller()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothGetPairingController()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothGetPairingController"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOBluetoothPairingControllerRef",
          "text": "IOBluetoothPairingControllerRef"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothGetPairingController()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothGetPairingController"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothGetPairingController()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothgetpairingcontroller()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothValidateHardwareWithDescription(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothValidateHardwareWithDescription"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOReturn",
          "text": "IOReturn"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothValidateHardwareWithDescription(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothValidateHardwareWithDescription"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothValidateHardwareWithDescription(_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothvalidatehardwarewithdescription(_:_:)"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetoothUI Constants",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothui-constants"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetoothUI Enumerations",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothui-enumerations"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothuiuserlib-h": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothuiuserlib-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetoothUIUserLib.h",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothuiuserlib-h"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothuiuserlib-h",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-enumerations",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-constants"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions",
      "identifiers": [
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothGetDeviceSelectorController()",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothGetPairingController()",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothValidateHardwareWithDescription(_:_:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions",
              "identifiers": [
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothGetDeviceSelectorController()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothGetPairingController()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothValidateHardwareWithDescription(_:_:)"
              ],
              "title": "Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothuiuserlib-h",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-enumerations",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-constants"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothGetDeviceSelectorController()/title",
          "value": "IOBluetoothGetDeviceSelectorController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothGetDeviceSelectorController()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothGetDeviceSelectorController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothValidateHardwareWithDescription(_:_:)/title",
          "value": "IOBluetoothValidateHardwareWithDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothValidateHardwareWithDescription(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothValidateHardwareWithDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothGetPairingController()/title",
          "value": "IOBluetoothGetPairingController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothGetPairingController()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothGetPairingController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetoothui/iobluetoothui-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetoothui/iobluetoothui-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
