{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "IOBluetooth UI"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "IOBluetoothUI Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI": {
      "abstract": [
        {
          "text": "Present an interface through which users can pair their devices with other Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth UI",
      "type": "topic",
      "url": "/documentation/iobluetoothui"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetoothUI Enumerations",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothui-enumerations"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetoothUI Functions",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothui-functions"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothuiuserlib-h": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothuiuserlib-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetoothUIUserLib.h",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothuiuserlib-h"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kBluetoothKeyboardANSIReturn": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothKeyboardANSIReturn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothKeyboardReturnType",
          "text": "BluetoothKeyboardReturnType"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kBluetoothKeyboardANSIReturn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothKeyboardANSIReturn"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothKeyboardANSIReturn",
      "type": "topic",
      "url": "/documentation/iobluetoothui/kbluetoothkeyboardansireturn"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kBluetoothKeyboardISOReturn": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothKeyboardISOReturn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothKeyboardReturnType",
          "text": "BluetoothKeyboardReturnType"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kBluetoothKeyboardISOReturn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothKeyboardISOReturn"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothKeyboardISOReturn",
      "type": "topic",
      "url": "/documentation/iobluetoothui/kbluetoothkeyboardisoreturn"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kBluetoothKeyboardJISReturn": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothKeyboardJISReturn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothKeyboardReturnType",
          "text": "BluetoothKeyboardReturnType"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kBluetoothKeyboardJISReturn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothKeyboardJISReturn"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothKeyboardJISReturn",
      "type": "topic",
      "url": "/documentation/iobluetoothui/kbluetoothkeyboardjisreturn"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kBluetoothKeyboardNoReturn": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothKeyboardNoReturn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothKeyboardReturnType",
          "text": "BluetoothKeyboardReturnType"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kBluetoothKeyboardNoReturn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothKeyboardNoReturn"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothKeyboardNoReturn",
      "type": "topic",
      "url": "/documentation/iobluetoothui/kbluetoothkeyboardnoreturn"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothuiuserlib-h",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-enumerations",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-functions"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kBluetoothKeyboardANSIReturn",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kBluetoothKeyboardISOReturn",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kBluetoothKeyboardJISReturn",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kBluetoothKeyboardNoReturn"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kBluetoothKeyboardANSIReturn",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kBluetoothKeyboardISOReturn",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kBluetoothKeyboardJISReturn",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kBluetoothKeyboardNoReturn"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothuiuserlib-h",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-enumerations",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-functions"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1kBluetoothKeyboardJISReturn/title",
          "value": "kBluetoothKeyboardJISReturn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1kBluetoothKeyboardJISReturn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothKeyboardJISReturn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1kBluetoothKeyboardISOReturn/title",
          "value": "kBluetoothKeyboardISOReturn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1kBluetoothKeyboardISOReturn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothKeyboardISOReturn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1kBluetoothKeyboardNoReturn/title",
          "value": "kBluetoothKeyboardNoReturn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1kBluetoothKeyboardNoReturn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothKeyboardNoReturn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1kBluetoothKeyboardANSIReturn/title",
          "value": "kBluetoothKeyboardANSIReturn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1kBluetoothKeyboardANSIReturn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothKeyboardANSIReturn"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetoothui/iobluetoothui-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetoothui/iobluetoothui-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
