{
  "abstract": [
    {
      "text": "A NSWindowController subclass to display a window to initiate pairing to other bluetooth devices.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)IOBluetoothDeviceSelectorController",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IOBluetoothDeviceSelectorController"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOBluetoothDeviceSelectorController"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "IOBluetoothDeviceSelectorController"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceSelectorController"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Implementation of a window controller to return a NSArray of selected bluetooth devices. This class will handle connecting to the Bluetooth Daemon for the purposes of searches, and displaying the results. This controller will return a NSArray of IOBluetoothDevice objects to the user.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI": {
      "abstract": [
        {
          "text": "Present an interface through which users can pair their devices with other Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth UI",
      "type": "topic",
      "url": "/documentation/iobluetoothui"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothAccessibilityIgnoredImageCell": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothAccessibilityIgnoredImageCell"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothAccessibilityIgnoredImageCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothAccessibilityIgnoredImageCell"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothAccessibilityIgnoredImageCell",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothaccessibilityignoredimagecell"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothAccessibilityIgnoredTextFieldCell": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothAccessibilityIgnoredTextFieldCell"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothAccessibilityIgnoredTextFieldCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothAccessibilityIgnoredTextFieldCell"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothAccessibilityIgnoredTextFieldCell",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothaccessibilityignoredtextfieldcell"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController": {
      "abstract": [
        {
          "text": "A NSWindowController subclass to display a window to initiate pairing to other bluetooth devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceSelectorController"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceSelectorController"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothDeviceSelectorController",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/addAllowedUUID(_:)": {
      "abstract": [
        {
          "text": "Adds a UUID to the list of UUIDs that are used to validate the user’s selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addAllowedUUID"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOBluetoothSDPUUID",
          "text": "IOBluetoothSDPUUID"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/addAllowedUUID(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addAllowedUUID:"
        }
      ],
      "role": "symbol",
      "title": "addAllowedUUID(_:)",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/addalloweduuid(_:)"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/addAllowedUUIDArray(_:)": {
      "abstract": [
        {
          "text": "Adds an array of UUIDs to the list of UUIDs that are used to validate the user’s selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addAllowedUUIDArray"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/addAllowedUUIDArray(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addAllowedUUIDArray:"
        }
      ],
      "role": "symbol",
      "title": "addAllowedUUIDArray(_:)",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/addalloweduuidarray(_:)"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/beginSheetModal(for:modalDelegate:didEnd:contextInfo:)": {
      "abstract": [
        {
          "text": "Runs the device selector panel as a sheet on the target window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginSheetModal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "modalDelegate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "didEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "contextInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOReturn",
          "text": "IOReturn"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/beginSheetModal(for:modalDelegate:didEnd:contextInfo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginSheetModalForWindow:modalDelegate:didEndSelector:contextInfo:"
        }
      ],
      "role": "symbol",
      "title": "beginSheetModal(for:modalDelegate:didEnd:contextInfo:)",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/beginsheetmodal(for:modaldelegate:didend:contextinfo:)"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/clearAllowedUUIDs()": {
      "abstract": [
        {
          "text": "Resets the controller back to the default state where it will accept any device the user selects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clearAllowedUUIDs"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/clearAllowedUUIDs()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clearAllowedUUIDs"
        }
      ],
      "role": "symbol",
      "title": "clearAllowedUUIDs()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/clearalloweduuids()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/deviceSelector()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceSelector"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOBluetoothDeviceSelectorController",
          "text": "IOBluetoothDeviceSelectorController"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/deviceSelector()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceSelector"
        }
      ],
      "role": "symbol",
      "title": "deviceSelector()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/deviceselector()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getCancel()": {
      "abstract": [
        {
          "text": "Returns the title of the default/cancel button in the device selector panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getCancel"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getCancel()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getCancel"
        }
      ],
      "role": "symbol",
      "title": "getCancel()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/getcancel()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getDescriptionText()": {
      "abstract": [
        {
          "text": "Returns the description text that appears in the device selector panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getDescriptionText"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getDescriptionText()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getDescriptionText"
        }
      ],
      "role": "symbol",
      "title": "getDescriptionText()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/getdescriptiontext()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getHeader()": {
      "abstract": [
        {
          "text": "Returns the header text that appears in the device selector panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getHeader"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getHeader()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getHeader"
        }
      ],
      "role": "symbol",
      "title": "getHeader()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/getheader()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getOptions()": {
      "abstract": [
        {
          "text": "Returns the option bits that control the panel’s behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getOptions"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOBluetoothServiceBrowserControllerOptions",
          "text": "IOBluetoothServiceBrowserControllerOptions"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getOptions()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getOptions"
        }
      ],
      "role": "symbol",
      "title": "getOptions()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/getoptions()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getPrompt()": {
      "abstract": [
        {
          "text": "Returns the title of the default/select button in the device selector panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getPrompt"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getPrompt()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getPrompt"
        }
      ],
      "role": "symbol",
      "title": "getPrompt()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/getprompt()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getResults()": {
      "abstract": [
        {
          "text": "Returns the result of the user’s selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getResults"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getResults()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getResults"
        }
      ],
      "role": "symbol",
      "title": "getResults()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/getresults()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getSearchAttributes()": {
      "abstract": [
        {
          "text": "Returns the search attributes that control the panel’s search/inquiry behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getSearchAttributes"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOBluetoothDeviceSearchAttributes",
          "text": "IOBluetoothDeviceSearchAttributes"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getSearchAttributes()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getSearchAttributes"
        }
      ],
      "role": "symbol",
      "title": "getSearchAttributes()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/getsearchattributes()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getTitle()": {
      "abstract": [
        {
          "text": "Returns the title of the device selector panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getTitle"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getTitle()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getTitle"
        }
      ],
      "role": "symbol",
      "title": "getTitle()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/gettitle()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/runModal()": {
      "abstract": [
        {
          "text": "Runs the device selector panel in a modal session to allow the user to select a Bluetooth device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "runModal"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/runModal()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runModal"
        }
      ],
      "role": "symbol",
      "title": "runModal()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/runmodal()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setCancel(_:)": {
      "abstract": [
        {
          "text": "Sets the title of the default/cancel button in the device selector panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setCancel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setCancel(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setCancel:"
        }
      ],
      "role": "symbol",
      "title": "setCancel(_:)",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/setcancel(_:)"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setDescriptionText(_:)": {
      "abstract": [
        {
          "text": "Sets the description text that appears in the device selector panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDescriptionText"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setDescriptionText(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDescriptionText:"
        }
      ],
      "role": "symbol",
      "title": "setDescriptionText(_:)",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/setdescriptiontext(_:)"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setHeader(_:)": {
      "abstract": [
        {
          "text": "Sets the header text that appears in the device selector panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setHeader(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setHeader:"
        }
      ],
      "role": "symbol",
      "title": "setHeader(_:)",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/setheader(_:)"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setOptions(_:)": {
      "abstract": [
        {
          "text": "Sets the option bits that control the panel’s behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setOptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOBluetoothServiceBrowserControllerOptions",
          "text": "IOBluetoothServiceBrowserControllerOptions"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setOptions(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setOptions:"
        }
      ],
      "role": "symbol",
      "title": "setOptions(_:)",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/setoptions(_:)"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setPrompt(_:)": {
      "abstract": [
        {
          "text": "Sets the title of the default/select button in the device selector panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setPrompt"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setPrompt(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPrompt:"
        }
      ],
      "role": "symbol",
      "title": "setPrompt(_:)",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/setprompt(_:)"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setSearchAttributes(_:)": {
      "abstract": [
        {
          "text": "Sets the search attributes that control the panel’s search/inquiry behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setSearchAttributes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@IOBluetoothDeviceSearchAttributes",
          "text": "IOBluetoothDeviceSearchAttributes"
        },
        {
          "kind": "text",
          "text": ">!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setSearchAttributes(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setSearchAttributes:"
        }
      ],
      "role": "symbol",
      "title": "setSearchAttributes(_:)",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/setsearchattributes(_:)"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setTitle(_:)": {
      "abstract": [
        {
          "text": "Sets the title of the panel when not run as a sheet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTitle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setTitle(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTitle:"
        }
      ],
      "role": "symbol",
      "title": "setTitle(_:)",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller/settitle(_:)"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorControllerRef": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceSelectorControllerRef"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorControllerRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceSelectorControllerRef"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothDeviceSelectorControllerRef",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontrollerref"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothObjectPushUIController": {
      "abstract": [
        {
          "text": "An NSWindowController subclass that supports the creation of an IOBluetoothObjectPushUIController object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothObjectPushUIController"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothObjectPushUIController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothObjectPushUIController"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothObjectPushUIController",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothobjectpushuicontroller"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController": {
      "abstract": [
        {
          "text": "A NSWindowController subclass to display a window to initiate pairing to other bluetooth devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothPairingController"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothPairingController"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothPairingController",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpairingcontroller"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingControllerRef": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothPairingControllerRef"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingControllerRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothPairingControllerRef"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothPairingControllerRef",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpairingcontrollerref"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothPasskeyDisplay"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothPasskeyDisplay"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothPasskeyDisplay",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothServiceBrowserController": {
      "abstract": [
        {
          "text": "A NSWindowController subclass to display a window to search for and perform SDP queries on bluetooth devices within range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothServiceBrowserController"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothServiceBrowserController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothServiceBrowserController"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothServiceBrowserController",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothservicebrowsercontroller"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothServiceBrowserControllerRef": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothServiceBrowserControllerRef"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothServiceBrowserControllerRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothServiceBrowserControllerRef"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothServiceBrowserControllerRef",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothservicebrowsercontrollerref"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSWindowController": {
      "abstract": [
        {
          "text": "A controller that manages a window, usually a window stored in a nib file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWindowController"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSWindowController",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSWindowController",
      "type": "topic",
      "url": "/documentation/AppKit/NSWindowController"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSeguePerforming": {
      "abstract": [
        {
          "text": "A set of methods that support the mediation of a custom segue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSeguePerforming"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSeguePerforming",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSeguePerforming",
      "type": "topic",
      "url": "/documentation/AppKit/NSSeguePerforming"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSStandardKeyBindingResponding": {
      "abstract": [
        {
          "text": "Methods that responder subclasses implement to support key binding commands, such as inserting tabs and newlines, or moving the insertion point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStandardKeyBindingResponding"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSStandardKeyBindingResponding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStandardKeyBindingResponding",
      "type": "topic",
      "url": "/documentation/AppKit/NSStandardKeyBindingResponding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider": {
      "abstract": [
        {
          "text": "A protocol that an object adopts to create a bar object in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTouchBarProvider"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTouchBarProvider",
      "type": "topic",
      "url": "/documentation/AppKit/NSTouchBarProvider"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSUserActivityRestoring": {
      "abstract": [
        {
          "text": "A protocol that marks classes to restore the state of your app to continue a user activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserActivityRestoring"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSUserActivityRestoring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUserActivityRestoring",
      "type": "topic",
      "url": "/documentation/AppKit/NSUserActivityRestoring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSWindowController"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSeguePerforming",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSStandardKeyBindingResponding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSUserActivityRestoring"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothAccessibilityIgnoredImageCell",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothAccessibilityIgnoredTextFieldCell",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorControllerRef",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothObjectPushUIController",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingControllerRef",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothServiceBrowserController",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothServiceBrowserControllerRef"
      ],
      "title": "Classes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Methods",
      "identifiers": [
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/addAllowedUUID(_:)",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/addAllowedUUIDArray(_:)",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/beginSheetModal(for:modalDelegate:didEnd:contextInfo:)",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/clearAllowedUUIDs()",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getCancel()",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getDescriptionText()",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getHeader()",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getOptions()",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getPrompt()",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getResults()",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getSearchAttributes()",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getTitle()",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/runModal()",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setCancel(_:)",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setDescriptionText(_:)",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setHeader(_:)",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setOptions(_:)",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setPrompt(_:)",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setSearchAttributes(_:)",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setTitle(_:)"
      ],
      "title": "Instance Methods"
    },
    {
      "anchor": "Type-Methods",
      "identifiers": [
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/deviceSelector()"
      ],
      "title": "Type Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOBluetoothDeviceSelectorController"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceSelectorController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceSelectorController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Methods",
              "identifiers": [
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/addAllowedUUID(_:)",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/addAllowedUUIDArray(_:)",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/beginSheetModal(for:modalDelegate:didEnd:contextInfo:)",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/clearAllowedUUIDs()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getCancel()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getDescriptionText()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getHeader()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getOptions()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getPrompt()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getResults()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getSearchAttributes()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/getTitle()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/runModal()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setCancel(_:)",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setDescriptionText(_:)",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setHeader(_:)",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setOptions(_:)",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setPrompt(_:)",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setSearchAttributes(_:)",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/setTitle(_:)"
              ],
              "title": "Instance Methods"
            },
            {
              "anchor": "Type-Methods",
              "identifiers": [
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController/deviceSelector()"
              ],
              "title": "Type Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSWindowController"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothAccessibilityIgnoredImageCell",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothAccessibilityIgnoredTextFieldCell",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorControllerRef",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothObjectPushUIController",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingControllerRef",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothServiceBrowserController",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothServiceBrowserControllerRef"
              ],
              "title": "Classes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "IOBluetoothDeviceSelectorController"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSWindowController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSWindowController",
                    "text": "NSWindowController"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSUserActivityRestoring/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSUserActivityRestoring"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController/title",
          "value": "IOBluetoothDeviceSelectorController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceSelectorController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceSelectorController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController/title",
          "value": "IOBluetoothPairingController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothPairingController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothPairingController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1deviceSelector()/title",
          "value": "deviceSelector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1deviceSelector()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "deviceSelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1setTitle(_:)/title",
          "value": "setTitle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1setTitle(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setTitle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getPrompt()/title",
          "value": "getPrompt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getPrompt()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getPrompt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getCancel()/title",
          "value": "getCancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getCancel()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getCancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1setSearchAttributes(_:)/title",
          "value": "setSearchAttributes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1setSearchAttributes(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setSearchAttributes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay/title",
          "value": "IOBluetoothPasskeyDisplay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothPasskeyDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothPasskeyDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getOptions()/title",
          "value": "getOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getOptions()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1addAllowedUUIDArray(_:)/title",
          "value": "addAllowedUUIDArray:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1addAllowedUUIDArray(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addAllowedUUIDArray:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothObjectPushUIController/title",
          "value": "IOBluetoothObjectPushUIController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothObjectPushUIController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothObjectPushUIController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothObjectPushUIController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothObjectPushUIController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothServiceBrowserControllerRef/title",
          "value": "IOBluetoothServiceBrowserControllerRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothServiceBrowserControllerRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothServiceBrowserControllerRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothServiceBrowserControllerRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothServiceBrowserControllerRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSStandardKeyBindingResponding/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSStandardKeyBindingResponding"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothServiceBrowserController/title",
          "value": "IOBluetoothServiceBrowserController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothServiceBrowserController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothServiceBrowserController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothServiceBrowserController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothServiceBrowserController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1setCancel(_:)/title",
          "value": "setCancel:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1setCancel(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setCancel:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1beginSheetModal(for:modalDelegate:didEnd:contextInfo:)/title",
          "value": "beginSheetModalForWindow:modalDelegate:didEndSelector:contextInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1beginSheetModal(for:modalDelegate:didEnd:contextInfo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginSheetModalForWindow:modalDelegate:didEndSelector:contextInfo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1clearAllowedUUIDs()/title",
          "value": "clearAllowedUUIDs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1clearAllowedUUIDs()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "clearAllowedUUIDs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothAccessibilityIgnoredImageCell/title",
          "value": "IOBluetoothAccessibilityIgnoredImageCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothAccessibilityIgnoredImageCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothAccessibilityIgnoredImageCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothAccessibilityIgnoredImageCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothAccessibilityIgnoredImageCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSTouchBarProvider/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTouchBarProvider"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSSeguePerforming/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSSeguePerforming"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1setHeader(_:)/title",
          "value": "setHeader:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1setHeader(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setHeader:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getResults()/title",
          "value": "getResults"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getResults()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getResults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingControllerRef/title",
          "value": "IOBluetoothPairingControllerRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingControllerRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothPairingControllerRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingControllerRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothPairingControllerRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getHeader()/title",
          "value": "getHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getHeader()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1addAllowedUUID(_:)/title",
          "value": "addAllowedUUID:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1addAllowedUUID(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addAllowedUUID:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getSearchAttributes()/title",
          "value": "getSearchAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getSearchAttributes()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getSearchAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSWindowController/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSWindowController"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSResponder",
              "text": "NSResponder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getDescriptionText()/title",
          "value": "getDescriptionText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getDescriptionText()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getDescriptionText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1setPrompt(_:)/title",
          "value": "setPrompt:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1setPrompt(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPrompt:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1runModal()/title",
          "value": "runModal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1runModal()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runModal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1setDescriptionText(_:)/title",
          "value": "setDescriptionText:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1setDescriptionText(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setDescriptionText:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorControllerRef/title",
          "value": "IOBluetoothDeviceSelectorControllerRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorControllerRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceSelectorControllerRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorControllerRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceSelectorControllerRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothAccessibilityIgnoredTextFieldCell/title",
          "value": "IOBluetoothAccessibilityIgnoredTextFieldCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothAccessibilityIgnoredTextFieldCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothAccessibilityIgnoredTextFieldCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothAccessibilityIgnoredTextFieldCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothAccessibilityIgnoredTextFieldCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getTitle()/title",
          "value": "getTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1getTitle()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1setOptions(_:)/title",
          "value": "setOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController~1setOptions(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setOptions:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
