{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)IOBluetoothPasskeyDisplay",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IOBluetoothPasskeyDisplay"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOBluetoothPasskeyDisplay"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "IOBluetoothPasskeyDisplay"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IOBluetoothPasskeyDisplay"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI": {
      "abstract": [
        {
          "text": "Present an interface through which users can pair their devices with other Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth UI",
      "type": "topic",
      "url": "/documentation/iobluetoothui"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothAccessibilityIgnoredImageCell": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothAccessibilityIgnoredImageCell"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothAccessibilityIgnoredImageCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothAccessibilityIgnoredImageCell"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothAccessibilityIgnoredImageCell",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothaccessibilityignoredimagecell"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothAccessibilityIgnoredTextFieldCell": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothAccessibilityIgnoredTextFieldCell"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothAccessibilityIgnoredTextFieldCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothAccessibilityIgnoredTextFieldCell"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothAccessibilityIgnoredTextFieldCell",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothaccessibilityignoredtextfieldcell"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController": {
      "abstract": [
        {
          "text": "A NSWindowController subclass to display a window to initiate pairing to other bluetooth devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceSelectorController"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceSelectorController"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothDeviceSelectorController",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontroller"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorControllerRef": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceSelectorControllerRef"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorControllerRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceSelectorControllerRef"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothDeviceSelectorControllerRef",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothdeviceselectorcontrollerref"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothObjectPushUIController": {
      "abstract": [
        {
          "text": "An NSWindowController subclass that supports the creation of an IOBluetoothObjectPushUIController object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothObjectPushUIController"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothObjectPushUIController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothObjectPushUIController"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothObjectPushUIController",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothobjectpushuicontroller"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController": {
      "abstract": [
        {
          "text": "A NSWindowController subclass to display a window to initiate pairing to other bluetooth devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothPairingController"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothPairingController"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothPairingController",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpairingcontroller"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingControllerRef": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothPairingControllerRef"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingControllerRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothPairingControllerRef"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothPairingControllerRef",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpairingcontrollerref"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothPasskeyDisplay"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothPasskeyDisplay"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothPasskeyDisplay",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/advancePasskeyIndicator()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "advancePasskeyIndicator"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/advancePasskeyIndicator()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "advancePasskeyIndicator"
        }
      ],
      "role": "symbol",
      "title": "advancePasskeyIndicator()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/advancepasskeyindicator()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/backgroundImageConstraint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundImageConstraint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/backgroundImageConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backgroundImageConstraint"
        }
      ],
      "role": "symbol",
      "title": "backgroundImageConstraint",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/backgroundimageconstraint"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/centeredView": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centeredView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/centeredView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "centeredView"
        }
      ],
      "role": "symbol",
      "title": "centeredView",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/centeredview"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/isIncomingRequest-c.ivar": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "isIncomingRequest"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/isIncomingRequest-c.ivar",
      "kind": "symbol",
      "role": "symbol",
      "title": "isIncomingRequest",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/isincomingrequest-c.ivar"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/isIncomingRequest-swift.property": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isIncomingRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/isIncomingRequest-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isIncomingRequest"
        }
      ],
      "role": "symbol",
      "title": "isIncomingRequest",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/isincomingrequest-swift.property"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/mBackgroundImage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mBackgroundImage"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/mBackgroundImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "mBackgroundImage",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/mbackgroundimage"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/mPasskeyCharacters": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mPasskeyCharacters"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/mPasskeyCharacters",
      "kind": "symbol",
      "role": "symbol",
      "title": "mPasskeyCharacters",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/mpasskeycharacters"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/mPasskeyIndex": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mPasskeyIndex"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/mPasskeyIndex",
      "kind": "symbol",
      "role": "symbol",
      "title": "mPasskeyIndex",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/mpasskeyindex"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/mPasskeyString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mPasskeyString"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/mPasskeyString",
      "kind": "symbol",
      "role": "symbol",
      "title": "mPasskeyString",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/mpasskeystring"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/mReturnHighlightImage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mReturnHighlightImage"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/mReturnHighlightImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "mReturnHighlightImage",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/mreturnhighlightimage"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/mReturnImage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mReturnImage"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/mReturnImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "mReturnImage",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/mreturnimage"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/mReturnImageView": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mReturnImageView"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/mReturnImageView",
      "kind": "symbol",
      "role": "symbol",
      "title": "mReturnImageView",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/mreturnimageview"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/passkey-c.ivar": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "passkey"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/passkey-c.ivar",
      "kind": "symbol",
      "role": "symbol",
      "title": "passkey",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/passkey-c.ivar"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/passkey-swift.property": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "passkey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/passkey-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "passkey"
        }
      ],
      "role": "symbol",
      "title": "passkey",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/passkey-swift.property"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/resetAll": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "resetAll"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/resetAll",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resetAll"
        }
      ],
      "role": "symbol",
      "title": "resetAll",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/resetall"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/resetPasskeyIndicator()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resetPasskeyIndicator"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/resetPasskeyIndicator()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resetPasskeyIndicator"
        }
      ],
      "role": "symbol",
      "title": "resetPasskeyIndicator()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/resetpasskeyindicator()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/retreatPasskeyIndicator()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "retreatPasskeyIndicator"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/retreatPasskeyIndicator()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "retreatPasskeyIndicator"
        }
      ],
      "role": "symbol",
      "title": "retreatPasskeyIndicator()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/retreatpasskeyindicator()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/returnHighlightImage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "returnHighlightImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/returnHighlightImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "returnHighlightImage"
        }
      ],
      "role": "symbol",
      "title": "returnHighlightImage",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/returnhighlightimage"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/returnImage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "returnImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/returnImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "returnImage"
        }
      ],
      "role": "symbol",
      "title": "returnImage",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/returnimage"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setPasskey(_:for:usingSSP:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setPasskey"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOBluetoothDevice",
          "text": "IOBluetoothDevice"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "usingSSP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setPasskey(_:for:usingSSP:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPasskey:forDevice:usingSSP:"
        }
      ],
      "role": "symbol",
      "title": "setPasskey(_:for:usingSSP:)",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/setpasskey(_:for:usingssp:)"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setPasskeyIndicatorEnabled:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setPasskeyIndicatorEnabled:"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setPasskeyIndicatorEnabled:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPasskeyIndicatorEnabled:"
        }
      ],
      "role": "symbol",
      "title": "setPasskeyIndicatorEnabled:",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/setpasskeyindicatorenabled:"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setPasskeyString:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setPasskeyString:"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setPasskeyString:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPasskeyString:"
        }
      ],
      "role": "symbol",
      "title": "setPasskeyString:",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/setpasskeystring:"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setupUIForDevice:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setupUIForDevice:"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setupUIForDevice:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setupUIForDevice:"
        }
      ],
      "role": "symbol",
      "title": "setupUIForDevice:",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/setupuifordevice:"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setupUIForSSPDevice:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setupUIForSSPDevice:"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setupUIForSSPDevice:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setupUIForSSPDevice:"
        }
      ],
      "role": "symbol",
      "title": "setupUIForSSPDevice:",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/setupuiforsspdevice:"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/sharedDisplayView()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sharedDisplayView"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOBluetoothPasskeyDisplay",
          "text": "IOBluetoothPasskeyDisplay"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/sharedDisplayView()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sharedDisplayView"
        }
      ],
      "role": "symbol",
      "title": "sharedDisplayView()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/shareddisplayview()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/showFeedback": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "showFeedback"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/showFeedback",
      "kind": "symbol",
      "role": "symbol",
      "title": "showFeedback",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/showfeedback"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/usePasskeyNotificaitons": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usePasskeyNotificaitons"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/usePasskeyNotificaitons",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "usePasskeyNotificaitons"
        }
      ],
      "role": "symbol",
      "title": "usePasskeyNotificaitons",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/usepasskeynotificaitons"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/usePasskeyNotifications": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "usePasskeyNotifications"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/usePasskeyNotifications",
      "kind": "symbol",
      "role": "symbol",
      "title": "usePasskeyNotifications",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothpasskeydisplay/usepasskeynotifications"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothServiceBrowserController": {
      "abstract": [
        {
          "text": "A NSWindowController subclass to display a window to search for and perform SDP queries on bluetooth devices within range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothServiceBrowserController"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothServiceBrowserController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothServiceBrowserController"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothServiceBrowserController",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothservicebrowsercontroller"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothServiceBrowserControllerRef": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothServiceBrowserControllerRef"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothServiceBrowserControllerRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothServiceBrowserControllerRef"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothServiceBrowserControllerRef",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothservicebrowsercontrollerref"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSView",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/AppKit/NSView"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSAccessibility": {
      "abstract": [
        {
          "text": "The complete list of properties and methods for accessible elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityProtocol"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSAccessibility",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityProtocol",
      "type": "topic",
      "url": "/documentation/AppKit/NSAccessibilityProtocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSAccessibilityElement": {
      "abstract": [
        {
          "text": "A role-based protocol that declares the minimum interface necessary to interact with an assistive app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityElementProtocol"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSAccessibilityElement",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAccessibilityElementProtocol",
      "type": "topic",
      "url": "/documentation/AppKit/NSAccessibilityElementProtocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSAnimatablePropertyContainer": {
      "abstract": [
        {
          "text": "A set of methods that defines a way to add animation to an existing class with a minimum of API impact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAnimatablePropertyContainer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSAnimatablePropertyContainer",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAnimatablePropertyContainer",
      "type": "topic",
      "url": "/documentation/AppKit/NSAnimatablePropertyContainer"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSAppearanceCustomization": {
      "abstract": [
        {
          "text": "A set of methods for getting and setting the appearance attributes of a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAppearanceCustomization"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSAppearanceCustomization",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAppearanceCustomization",
      "type": "topic",
      "url": "/documentation/AppKit/NSAppearanceCustomization"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSDraggingDestination": {
      "abstract": [
        {
          "text": "A set of methods that the destination object (or recipient) of a dragged image must implement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDraggingDestination"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSDraggingDestination",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDraggingDestination",
      "type": "topic",
      "url": "/documentation/AppKit/NSDraggingDestination"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSStandardKeyBindingResponding": {
      "abstract": [
        {
          "text": "Methods that responder subclasses implement to support key binding commands, such as inserting tabs and newlines, or moving the insertion point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStandardKeyBindingResponding"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSStandardKeyBindingResponding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStandardKeyBindingResponding",
      "type": "topic",
      "url": "/documentation/AppKit/NSStandardKeyBindingResponding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider": {
      "abstract": [
        {
          "text": "A protocol that an object adopts to create a bar object in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTouchBarProvider"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTouchBarProvider",
      "type": "topic",
      "url": "/documentation/AppKit/NSTouchBarProvider"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSUserActivityRestoring": {
      "abstract": [
        {
          "text": "A protocol that marks classes to restore the state of your app to continue a user activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserActivityRestoring"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSUserActivityRestoring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUserActivityRestoring",
      "type": "topic",
      "url": "/documentation/AppKit/NSUserActivityRestoring"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSUserInterfaceItemIdentification": {
      "abstract": [
        {
          "text": "A set of methods used to associate a unique identifier with objects in your user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserInterfaceItemIdentification"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSUserInterfaceItemIdentification",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUserInterfaceItemIdentification",
      "type": "topic",
      "url": "/documentation/AppKit/NSUserInterfaceItemIdentification"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSView"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSAccessibilityElement",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSAccessibility",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSAnimatablePropertyContainer",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSAppearanceCustomization",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSDraggingDestination",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSStandardKeyBindingResponding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSUserActivityRestoring",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSUserInterfaceItemIdentification",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothAccessibilityIgnoredImageCell",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothAccessibilityIgnoredTextFieldCell",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorControllerRef",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothObjectPushUIController",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingControllerRef",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothServiceBrowserController",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothServiceBrowserControllerRef"
      ],
      "title": "Classes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/backgroundImageConstraint",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/centeredView",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/isIncomingRequest-swift.property",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/passkey-swift.property",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/returnHighlightImage",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/returnImage",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/usePasskeyNotificaitons"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "identifiers": [
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/advancePasskeyIndicator()",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/resetPasskeyIndicator()",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/retreatPasskeyIndicator()",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setPasskey(_:for:usingSSP:)"
      ],
      "title": "Instance Methods"
    },
    {
      "anchor": "Type-Methods",
      "identifiers": [
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/sharedDisplayView()"
      ],
      "title": "Type Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOBluetoothPasskeyDisplay"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothPasskeyDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothPasskeyDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/backgroundImageConstraint",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/centeredView",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/isIncomingRequest-swift.property",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/passkey-swift.property",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/returnHighlightImage",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/returnImage",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/usePasskeyNotificaitons"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Instance-Methods",
              "identifiers": [
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/advancePasskeyIndicator()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/resetPasskeyIndicator()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/retreatPasskeyIndicator()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setPasskey(_:for:usingSSP:)",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/resetAll",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setPasskeyIndicatorEnabled:",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setPasskeyString:",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setupUIForDevice:",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/setupUIForSSPDevice:"
              ],
              "title": "Instance Methods"
            },
            {
              "anchor": "Type-Methods",
              "identifiers": [
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/sharedDisplayView()"
              ],
              "title": "Type Methods"
            },
            {
              "anchor": "Instance-Variables",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/isIncomingRequest-c.ivar",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/mBackgroundImage",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/mPasskeyCharacters",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/mPasskeyIndex",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/mPasskeyString",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/mReturnHighlightImage",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/mReturnImage",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/mReturnImageView",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/passkey-c.ivar",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/showFeedback",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPasskeyDisplay/usePasskeyNotifications"
              ],
              "title": "Instance Variables"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSView"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothAccessibilityIgnoredImageCell",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothAccessibilityIgnoredTextFieldCell",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorController",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothDeviceSelectorControllerRef",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothObjectPushUIController",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingController",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothPairingControllerRef",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothServiceBrowserController",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothServiceBrowserControllerRef"
              ],
              "title": "Classes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "IOBluetoothPasskeyDisplay"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSView",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSView",
                    "text": "NSView"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSAppearanceCustomization/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSAppearanceCustomization"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1passkey-swift.property/title",
          "value": "passkey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1passkey-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "passkey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1resetPasskeyIndicator()/title",
          "value": "resetPasskeyIndicator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1resetPasskeyIndicator()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resetPasskeyIndicator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1isIncomingRequest-swift.property/title",
          "value": "isIncomingRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1isIncomingRequest-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isIncomingRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1backgroundImageConstraint/title",
          "value": "backgroundImageConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1backgroundImageConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backgroundImageConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1sharedDisplayView()/title",
          "value": "sharedDisplayView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1sharedDisplayView()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "sharedDisplayView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSAccessibility/title",
          "value": "NSAccessibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSAccessibility/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSAccessibility"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSAccessibilityElement/title",
          "value": "NSAccessibilityElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSAccessibilityElement/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSAccessibilityElement"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothAccessibilityIgnoredImageCell/title",
          "value": "IOBluetoothAccessibilityIgnoredImageCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothAccessibilityIgnoredImageCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothAccessibilityIgnoredImageCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothAccessibilityIgnoredImageCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothAccessibilityIgnoredImageCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1retreatPasskeyIndicator()/title",
          "value": "retreatPasskeyIndicator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1retreatPasskeyIndicator()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "retreatPasskeyIndicator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1centeredView/title",
          "value": "centeredView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1centeredView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "centeredView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothObjectPushUIController/title",
          "value": "IOBluetoothObjectPushUIController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothObjectPushUIController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothObjectPushUIController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothObjectPushUIController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothObjectPushUIController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSTouchBarProvider/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTouchBarProvider"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1returnHighlightImage/title",
          "value": "returnHighlightImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1returnHighlightImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "returnHighlightImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSView/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSView"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSResponder",
              "text": "NSResponder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothServiceBrowserControllerRef/title",
          "value": "IOBluetoothServiceBrowserControllerRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothServiceBrowserControllerRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothServiceBrowserControllerRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothServiceBrowserControllerRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothServiceBrowserControllerRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1setPasskey(_:for:usingSSP:)/title",
          "value": "setPasskey:forDevice:usingSSP:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1setPasskey(_:for:usingSSP:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPasskey:forDevice:usingSSP:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1advancePasskeyIndicator()/title",
          "value": "advancePasskeyIndicator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1advancePasskeyIndicator()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "advancePasskeyIndicator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController/title",
          "value": "IOBluetoothDeviceSelectorController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceSelectorController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceSelectorController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothAccessibilityIgnoredTextFieldCell/title",
          "value": "IOBluetoothAccessibilityIgnoredTextFieldCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothAccessibilityIgnoredTextFieldCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothAccessibilityIgnoredTextFieldCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothAccessibilityIgnoredTextFieldCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothAccessibilityIgnoredTextFieldCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1returnImage/title",
          "value": "returnImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1returnImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "returnImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSUserInterfaceItemIdentification/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSUserInterfaceItemIdentification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSDraggingDestination/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSDraggingDestination"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay/title",
          "value": "IOBluetoothPasskeyDisplay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothPasskeyDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothPasskeyDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSStandardKeyBindingResponding/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSStandardKeyBindingResponding"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSAnimatablePropertyContainer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSAnimatablePropertyContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController/title",
          "value": "IOBluetoothPairingController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothPairingController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothPairingController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothServiceBrowserController/title",
          "value": "IOBluetoothServiceBrowserController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothServiceBrowserController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothServiceBrowserController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothServiceBrowserController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothServiceBrowserController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSUserActivityRestoring/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSUserActivityRestoring"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorControllerRef/title",
          "value": "IOBluetoothDeviceSelectorControllerRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorControllerRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceSelectorControllerRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothDeviceSelectorControllerRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceSelectorControllerRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingControllerRef/title",
          "value": "IOBluetoothPairingControllerRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingControllerRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothPairingControllerRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPairingControllerRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothPairingControllerRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1usePasskeyNotificaitons/title",
          "value": "usePasskeyNotificaitons"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothPasskeyDisplay~1usePasskeyNotificaitons/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "usePasskeyNotificaitons"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetoothui/iobluetoothpasskeydisplay"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetoothui/iobluetoothpasskeydisplay"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
