{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothuiuserlib-h"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "IOBluetooth UI"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "IOBluetoothUIUserLib.h"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Included-Headers",
          "level": 3,
          "text": "Included Headers",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "<IOBluetooth/IOBluetoothUserLib.h>",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI": {
      "abstract": [
        {
          "text": "Present an interface through which users can pair their devices with other Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth UI",
      "type": "topic",
      "url": "/documentation/iobluetoothui"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothServiceBrowserControllerOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothServiceBrowserControllerOptions"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothServiceBrowserControllerOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothServiceBrowserControllerOptions"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothServiceBrowserControllerOptions",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothservicebrowsercontrolleroptions"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetoothUI Constants",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothui-constants"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetoothUI Enumerations",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothui-enumerations"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetoothUI Functions",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothui-functions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-enumerations",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-constants",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-functions"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "abstract": [
        {
          "text": "See the Overview section above for header-level documentation.",
          "type": "text"
        }
      ],
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothServiceBrowserControllerOptions"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "abstract": [
                {
                  "text": "See the Overview section above for header-level documentation.",
                  "type": "text"
                }
              ],
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothServiceBrowserControllerOptions"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-enumerations",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-constants",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/iobluetoothui-functions"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothServiceBrowserControllerOptions/title",
          "value": "IOBluetoothServiceBrowserControllerOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothServiceBrowserControllerOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothServiceBrowserControllerOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothServiceBrowserControllerOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothServiceBrowserControllerOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetoothui/iobluetoothuiuserlib-h"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetoothui/iobluetoothuiuserlib-h"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
