{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothValidateHardwareWithDescription(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@IOBluetoothValidateHardwareWithDescription",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IOBluetoothValidateHardwareWithDescription"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      },
      {
        "kind": "text",
        "text": "!) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@IOReturn",
        "text": "IOReturn"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOBluetoothValidateHardwareWithDescription"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "IOBluetoothValidateHardwareWithDescription(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IOBluetoothValidateHardwareWithDescription"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "cancelButtonTitle"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "descriptionText"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            },
            {
              "kind": "text",
              "text": "!) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@IOReturn",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@IOReturn",
              "text": "IOReturn"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI": {
      "abstract": [
        {
          "text": "Present an interface through which users can pair their devices with other Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth UI",
      "type": "topic",
      "url": "/documentation/iobluetoothui"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothGetDeviceSelectorController()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothGetDeviceSelectorController"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOBluetoothDeviceSelectorControllerRef",
          "text": "IOBluetoothDeviceSelectorControllerRef"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothGetDeviceSelectorController()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothGetDeviceSelectorController"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothGetDeviceSelectorController()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothgetdeviceselectorcontroller()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothGetPairingController()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothGetPairingController"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOBluetoothPairingControllerRef",
          "text": "IOBluetoothPairingControllerRef"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothGetPairingController()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothGetPairingController"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothGetPairingController()",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothgetpairingcontroller()"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothValidateHardwareWithDescription(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothValidateHardwareWithDescription"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOReturn",
          "text": "IOReturn"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothValidateHardwareWithDescription(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothValidateHardwareWithDescription"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothValidateHardwareWithDescription(_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothvalidatehardwarewithdescription(_:_:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    },
    "doc://com.externally.resolved.symbol/c:@T@IOReturn": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "IOReturn"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@IOReturn",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOReturn",
      "type": "topic",
      "url": "/documentation/iokit/ioreturn"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothGetDeviceSelectorController()",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothGetPairingController()"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOBluetoothValidateHardwareWithDescription"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothValidateHardwareWithDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothGetDeviceSelectorController()",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothGetPairingController()"
              ],
              "title": "Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@IOReturn",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@IOReturn",
                    "text": "IOReturn"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "IOBluetoothValidateHardwareWithDescription"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "cancelButtonTitle"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "descriptionText"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothValidateHardwareWithDescription(_:_:)/title",
          "value": "IOBluetoothValidateHardwareWithDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothValidateHardwareWithDescription(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothValidateHardwareWithDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothGetPairingController()/title",
          "value": "IOBluetoothGetPairingController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothGetPairingController()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothGetPairingController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothGetDeviceSelectorController()/title",
          "value": "IOBluetoothGetDeviceSelectorController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothGetDeviceSelectorController()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothGetDeviceSelectorController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetoothui/iobluetoothvalidatehardwarewithdescription(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetoothui/iobluetoothvalidatehardwarewithdescription(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
