{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothServiceBrowserControllerOptions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@IOBluetoothServiceBrowserControllerOptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IOBluetoothServiceBrowserControllerOptions"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOBluetoothServiceBrowserControllerOptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "IOBluetoothServiceBrowserControllerOptions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IOBluetoothServiceBrowserControllerOptions"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Option values to customize the behavior of an IOBluetoothServiceBrowserController object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI": {
      "abstract": [
        {
          "text": "Present an interface through which users can pair their devices with other Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth UI",
      "type": "topic",
      "url": "/documentation/iobluetoothui"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothServiceBrowserControllerOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothServiceBrowserControllerOptions"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/IOBluetoothServiceBrowserControllerOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothServiceBrowserControllerOptions"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothServiceBrowserControllerOptions",
      "type": "topic",
      "url": "/documentation/iobluetoothui/iobluetoothservicebrowsercontrolleroptions"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kIOBluetoothServiceBrowserControllerOptionsAutoStartInquiry": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOBluetoothServiceBrowserControllerOptionsAutoStartInquiry"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kIOBluetoothServiceBrowserControllerOptionsAutoStartInquiry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOBluetoothServiceBrowserControllerOptionsAutoStartInquiry"
        }
      ],
      "role": "symbol",
      "title": "kIOBluetoothServiceBrowserControllerOptionsAutoStartInquiry",
      "type": "topic",
      "url": "/documentation/iobluetoothui/kiobluetoothservicebrowsercontrolleroptionsautostartinquiry"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kIOBluetoothServiceBrowserControllerOptionsDisconnectWhenDone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOBluetoothServiceBrowserControllerOptionsDisconnectWhenDone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kIOBluetoothServiceBrowserControllerOptionsDisconnectWhenDone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOBluetoothServiceBrowserControllerOptionsDisconnectWhenDone"
        }
      ],
      "role": "symbol",
      "title": "kIOBluetoothServiceBrowserControllerOptionsDisconnectWhenDone",
      "type": "topic",
      "url": "/documentation/iobluetoothui/kiobluetoothservicebrowsercontrolleroptionsdisconnectwhendone"
    },
    "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kIOBluetoothServiceBrowserControllerOptionsNone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOBluetoothServiceBrowserControllerOptionsNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kIOBluetoothServiceBrowserControllerOptionsNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOBluetoothServiceBrowserControllerOptionsNone"
        }
      ],
      "role": "symbol",
      "title": "kIOBluetoothServiceBrowserControllerOptionsNone",
      "type": "topic",
      "url": "/documentation/iobluetoothui/kiobluetoothservicebrowsercontrolleroptionsnone"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kIOBluetoothServiceBrowserControllerOptionsNone",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kIOBluetoothServiceBrowserControllerOptionsAutoStartInquiry",
        "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kIOBluetoothServiceBrowserControllerOptionsDisconnectWhenDone"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOBluetoothServiceBrowserControllerOptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothServiceBrowserControllerOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothServiceBrowserControllerOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kIOBluetoothServiceBrowserControllerOptionsNone",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kIOBluetoothServiceBrowserControllerOptionsAutoStartInquiry",
                "doc://com.apple.iobluetoothui/documentation/IOBluetoothUI/kIOBluetoothServiceBrowserControllerOptionsDisconnectWhenDone"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "IOBluetoothServiceBrowserControllerOptions"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1kIOBluetoothServiceBrowserControllerOptionsDisconnectWhenDone/title",
          "value": "kIOBluetoothServiceBrowserControllerOptionsDisconnectWhenDone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1kIOBluetoothServiceBrowserControllerOptionsDisconnectWhenDone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOBluetoothServiceBrowserControllerOptionsDisconnectWhenDone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1kIOBluetoothServiceBrowserControllerOptionsAutoStartInquiry/title",
          "value": "kIOBluetoothServiceBrowserControllerOptionsAutoStartInquiry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1kIOBluetoothServiceBrowserControllerOptionsAutoStartInquiry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOBluetoothServiceBrowserControllerOptionsAutoStartInquiry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1kIOBluetoothServiceBrowserControllerOptionsNone/title",
          "value": "kIOBluetoothServiceBrowserControllerOptionsNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1kIOBluetoothServiceBrowserControllerOptionsNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOBluetoothServiceBrowserControllerOptionsNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothServiceBrowserControllerOptions/title",
          "value": "IOBluetoothServiceBrowserControllerOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothServiceBrowserControllerOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothServiceBrowserControllerOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetoothui~1documentation~1IOBluetoothUI~1IOBluetoothServiceBrowserControllerOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothServiceBrowserControllerOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetoothui/iobluetoothservicebrowsercontrolleroptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetoothui/iobluetoothservicebrowsercontrolleroptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
