{
  "abstract": [
    {
      "text": "The error code to indicate an invalid billing address or billing name.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/billingContactInvalidError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC18PKPaymentErrorCodeLeV021billingContactInvalidB0SoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "billingContactInvalidError"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC18PKPaymentErrorCodeLeV",
        "text": "PKPaymentError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@PKPaymentErrorCode",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "billingContactInvalidError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "billingContactInvalidError"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC18PKPaymentErrorCodeLeV",
              "text": "PKPaymentError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@PKPaymentErrorCode",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this error code if the billing contact information on the Apple Pay sheet has an error in the address or name.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentError": {
      "abstract": [
        {
          "text": "An error type that you create to indicate problems with address or contact information on an Apple Pay sheet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentError"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentError",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymenterror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code": {
      "abstract": [
        {
          "text": "An error code that you provide to indicate problems with address or contact information on an Apple Pay sheet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentError.Code",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymenterror/code"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/billingContactInvalidError": {
      "abstract": [
        {
          "text": "The error code to indicate an invalid billing address or billing name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "billingContactInvalidError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC18PKPaymentErrorCodeLeV",
          "text": "PKPaymentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKPaymentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/billingContactInvalidError",
      "kind": "symbol",
      "role": "symbol",
      "title": "billingContactInvalidError",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymenterror/billingcontactinvaliderror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/couponCodeExpiredError": {
      "abstract": [
        {
          "text": "The error code that indicates an expired coupon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "couponCodeExpiredError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC18PKPaymentErrorCodeLeV",
          "text": "PKPaymentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKPaymentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/couponCodeExpiredError",
      "kind": "symbol",
      "role": "symbol",
      "title": "couponCodeExpiredError",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymenterror/couponcodeexpirederror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/couponCodeInvalidError": {
      "abstract": [
        {
          "text": "The error code that indicates an invalid coupon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "couponCodeInvalidError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC18PKPaymentErrorCodeLeV",
          "text": "PKPaymentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKPaymentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/couponCodeInvalidError",
      "kind": "symbol",
      "role": "symbol",
      "title": "couponCodeInvalidError",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymenterror/couponcodeinvaliderror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/shippingAddressUnserviceableError": {
      "abstract": [
        {
          "text": "The error code for an unserviceable shipping address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shippingAddressUnserviceableError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC18PKPaymentErrorCodeLeV",
          "text": "PKPaymentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKPaymentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/shippingAddressUnserviceableError",
      "kind": "symbol",
      "role": "symbol",
      "title": "shippingAddressUnserviceableError",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymenterror/shippingaddressunserviceableerror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/shippingContactInvalidError": {
      "abstract": [
        {
          "text": "The error code to indicate an invalid shipping address, email, phone, or name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shippingContactInvalidError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC18PKPaymentErrorCodeLeV",
          "text": "PKPaymentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKPaymentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/shippingContactInvalidError",
      "kind": "symbol",
      "role": "symbol",
      "title": "shippingContactInvalidError",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymenterror/shippingcontactinvaliderror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/unknownError": {
      "abstract": [
        {
          "text": "The error code for an unknown error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC18PKPaymentErrorCodeLeV",
          "text": "PKPaymentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKPaymentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/unknownError",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknownError",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymenterror/unknownerror"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Identifying-the-error",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/shippingContactInvalidError",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/shippingAddressUnserviceableError",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/couponCodeExpiredError",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/couponCodeInvalidError",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/unknownError",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code"
      ],
      "title": "Identifying the error"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentError~1Code/title",
          "value": "PKPaymentErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkpaymenterror/billingcontactinvaliderror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
