{
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_tcc_modify_t"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_tcc_modify_t/init(service:identity:identity_type:update_type:instigator_token:instigator:responsible_token:responsible:right:reason:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So21es_event_tcc_modify_ta7service8identity0F5_type07update_G016instigator_token0I0012responsible_J00K05right6reasonABSo0a8_string_J2_ta_ANSo0a1_c1_f1_G2_taSo0a1_c1_b1_G2_taSo06audit_J2_taSpySo0A10_process_taGSgSpyATGSgAXSo0a1_c15_authorization_L2_taSo0a1_c1_q1_M2_tatcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "service"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@es_string_token_t",
        "text": "es_string_token_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "identity"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@es_string_token_t",
        "text": "es_string_token_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "identity_type"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@es_tcc_identity_type_t",
        "text": "es_tcc_identity_type_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "update_type"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@es_tcc_event_type_t",
        "text": "es_tcc_event_type_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "instigator_token"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@audit_token_t",
        "text": "audit_token_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "instigator"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@es_process_t",
        "text": "es_process_t"
      },
      {
        "kind": "text",
        "text": ">?, "
      },
      {
        "kind": "externalParam",
        "text": "responsible_token"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@audit_token_t",
        "text": "audit_token_t"
      },
      {
        "kind": "text",
        "text": ">?, "
      },
      {
        "kind": "externalParam",
        "text": "responsible"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@es_process_t",
        "text": "es_process_t"
      },
      {
        "kind": "text",
        "text": ">?, "
      },
      {
        "kind": "externalParam",
        "text": "right"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@es_tcc_authorization_right_t",
        "text": "es_tcc_authorization_right_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "reason"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
        "text": "es_tcc_authorization_reason_t"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Endpoint Security"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(service:identity:identity_type:update_type:instigator_token:instigator:responsible_token:responsible:right:reason:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "service"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_string_token_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@es_string_token_t",
              "text": "es_string_token_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "identity"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_string_token_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@es_string_token_t",
              "text": "es_string_token_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "identity_type"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_identity_type_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@es_tcc_identity_type_t",
              "text": "es_tcc_identity_type_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "update_type"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_event_type_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@es_tcc_event_type_t",
              "text": "es_tcc_event_type_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "instigator_token"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@audit_token_t",
              "text": "audit_token_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "instigator"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@es_process_t",
              "text": "es_process_t"
            },
            {
              "kind": "text",
              "text": ">?, "
            },
            {
              "kind": "externalParam",
              "text": "responsible_token"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@audit_token_t",
              "text": "audit_token_t"
            },
            {
              "kind": "text",
              "text": ">?, "
            },
            {
              "kind": "externalParam",
              "text": "responsible"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@es_process_t",
              "text": "es_process_t"
            },
            {
              "kind": "text",
              "text": ">?, "
            },
            {
              "kind": "externalParam",
              "text": "right"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_right_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@es_tcc_authorization_right_t",
              "text": "es_tcc_authorization_right_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "reason"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_reason_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
              "text": "es_tcc_authorization_reason_t"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity": {
      "abstract": [
        {
          "text": "Develop system extensions that enhance user security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
      "kind": "symbol",
      "role": "collection",
      "title": "Endpoint Security",
      "type": "topic",
      "url": "/documentation/endpointsecurity"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_tcc_modify_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_tcc_modify_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_tcc_modify_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_tcc_modify_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_tcc_modify_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_tcc_modify_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_tcc_modify_t/init(service:identity:identity_type:update_type:instigator_token:instigator:responsible_token:responsible:right:reason:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "service"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_string_token_t",
          "text": "es_string_token_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "identity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_string_token_t",
          "text": "es_string_token_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "identity_type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_identity_type_t",
          "text": "es_tcc_identity_type_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "update_type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_event_type_t",
          "text": "es_tcc_event_type_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "instigator_token"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@audit_token_t",
          "text": "audit_token_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "instigator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_process_t",
          "text": "es_process_t"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "responsible_token"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@audit_token_t",
          "text": "audit_token_t"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "responsible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@es_process_t",
          "text": "es_process_t"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "right"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_right_t",
          "text": "es_tcc_authorization_right_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "reason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@es_tcc_authorization_reason_t",
          "text": "es_tcc_authorization_reason_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_tcc_modify_t/init(service:identity:identity_type:update_type:instigator_token:instigator:responsible_token:responsible:right:reason:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(service:identity:identity_type:update_type:instigator_token:instigator:responsible_token:responsible:right:reason:)",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_tcc_modify_t/init(service:identity:identity_type:update_type:instigator_token:instigator:responsible_token:responsible:right:reason:)"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t": {
      "abstract": [
        {
          "text": "A type that describes a process, as delivered by an Endpoint Security message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_process_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_process_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_process_t"
        }
      ],
      "role": "symbol",
      "title": "es_process_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_process_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_string_token_t": {
      "abstract": [
        {
          "text": "A pointer to a null-terminated string, and the length in bytes of that string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_string_token_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_string_token_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_string_token_t"
        }
      ],
      "role": "symbol",
      "title": "es_string_token_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_string_token_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_reason_t": {
      "abstract": [
        {
          "text": "ess_tcc_authorization_reason_t",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_reason_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_tcc_authorization_reason_t"
        }
      ],
      "role": "symbol",
      "title": "es_tcc_authorization_reason_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_reason_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_right_t": {
      "abstract": [
        {
          "text": "ess_tcc_authorization_right_t",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_tcc_authorization_right_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_authorization_right_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_tcc_authorization_right_t"
        }
      ],
      "role": "symbol",
      "title": "es_tcc_authorization_right_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_authorization_right_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_event_type_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_tcc_event_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_event_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_tcc_event_type_t"
        }
      ],
      "role": "symbol",
      "title": "es_tcc_event_type_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_event_type_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_identity_type_t": {
      "abstract": [
        {
          "text": "es_tcc_identity_type_t",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_tcc_identity_type_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_tcc_identity_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_tcc_identity_type_t"
        }
      ],
      "role": "symbol",
      "title": "es_tcc_identity_type_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_tcc_identity_type_t"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_tcc_modify_t/title",
          "value": "es_event_tcc_modify_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_tcc_modify_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_tcc_modify_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_tcc_modify_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_tcc_modify_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_string_token_t/title",
          "value": "es_string_token_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_string_token_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_string_token_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_string_token_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_string_token_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_authorization_right_t/title",
          "value": "es_tcc_authorization_right_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_authorization_right_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_tcc_authorization_right_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_authorization_right_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_tcc_authorization_right_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_authorization_reason_t/title",
          "value": "es_tcc_authorization_reason_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_authorization_reason_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_tcc_authorization_reason_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_authorization_reason_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_tcc_authorization_reason_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t/title",
          "value": "es_process_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_process_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_process_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_process_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_event_type_t/title",
          "value": "es_tcc_event_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_event_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_tcc_event_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_event_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_tcc_event_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_identity_type_t/title",
          "value": "es_tcc_identity_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_identity_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_tcc_identity_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_tcc_identity_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_tcc_identity_type_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/endpointsecurity/es_event_tcc_modify_t/init(service:identity:identity_type:update_type:instigator_token:instigator:responsible_token:responsible:right:reason:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
