{
  "abstract": [
    {
      "text": "Initiates a request to find players for a hosted match that uses matchmaking rules.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit",
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker/findMatchedPlayers(_:withCompletionHandler:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)GKMatchmaker(im)findMatchedPlayers:withCompletionHandler:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "findMatchedPlayers"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)GKMatchRequest",
        "text": "GKMatchRequest"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "withCompletionHandler"
      },
      {
        "kind": "text",
        "text": ": ("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)GKMatchedPlayers",
        "text": "GKMatchedPlayers"
      },
      {
        "kind": "text",
        "text": "?, (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5ErrorP",
        "text": "Error"
      },
      {
        "kind": "text",
        "text": ")?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "findMatchedPlayers:withCompletionHandler:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.2",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.2",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.1",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "findMatchedPlayers(_:withCompletionHandler:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "findMatchedPlayers"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "request"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)GKMatchRequest",
              "text": "GKMatchRequest"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "withCompletionHandler"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "completionHandler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchedPlayers",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)GKMatchedPlayers",
              "text": "GKMatchedPlayers"
            },
            {
              "kind": "text",
              "text": "?, (any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ")?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "findMatchedPlayers"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "request"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)GKMatchRequest",
              "text": "GKMatchRequest"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "async"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "throws"
            },
            {
              "kind": "text",
              "text": " -> "
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchedPlayers",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)GKMatchedPlayers",
              "text": "GKMatchedPlayers"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The configuration for the match.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "request"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The block that GameKit calls when it completes the request.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "This block receives the following parameters:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "items": [
                {
                  "definition": {
                    "content": [
                      {
                        "inlineContent": [
                          {
                            "text": "The players that join the match, including their properties that matchmaking rules uses. If unsuccessful, this parameter is ",
                            "type": "text"
                          },
                          {
                            "code": "nil",
                            "type": "codeVoice"
                          },
                          {
                            "text": ".",
                            "type": "text"
                          }
                        ],
                        "type": "paragraph"
                      }
                    ]
                  },
                  "term": {
                    "inlineContent": [
                      {
                        "code": "matchedPlayers",
                        "type": "codeVoice"
                      }
                    ]
                  }
                },
                {
                  "definition": {
                    "content": [
                      {
                        "inlineContent": [
                          {
                            "text": "Describes an error if it occurs, or ",
                            "type": "text"
                          },
                          {
                            "code": "nil",
                            "type": "codeVoice"
                          },
                          {
                            "text": " if the operation completes.",
                            "type": "text"
                          }
                        ],
                        "type": "paragraph"
                      }
                    ]
                  },
                  "term": {
                    "inlineContent": [
                      {
                        "code": "error",
                        "type": "codeVoice"
                      }
                    ]
                  }
                }
              ],
              "type": "termList"
            }
          ],
          "name": "completionHandler"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To find players using matchmaking rules, set the rules-related properties in ",
              "type": "text"
            },
            {
              "code": "request",
              "type": "codeVoice"
            },
            {
              "text": " (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/queueName",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and optionally, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/properties",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") before you call this method. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamekit/documentation/GameKit/matchmaking-rules",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest": {
      "abstract": [
        {
          "text": "An object that encapsulates the parameters to create a real-time or turn-based match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKMatchRequest"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKMatchRequest"
        }
      ],
      "role": "symbol",
      "title": "GKMatchRequest",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/properties": {
      "abstract": [
        {
          "text": "The criteria for the local player that Game Center uses to find other players when using matchmaking rules.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "properties"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/properties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "properties"
        }
      ],
      "role": "symbol",
      "title": "properties",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest/properties"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/queueName": {
      "abstract": [
        {
          "text": "The name of the queue that Game Center places the match request in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "queueName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest/queueName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "queueName"
        }
      ],
      "role": "symbol",
      "title": "queueName",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchrequest/queuename"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchedPlayers": {
      "abstract": [
        {
          "text": "An object that represents matchmaking results, including the players that join the match and their properties that matchmaking rules uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKMatchedPlayers"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchedPlayers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKMatchedPlayers"
        }
      ],
      "role": "symbol",
      "title": "GKMatchedPlayers",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchedplayers"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker": {
      "abstract": [
        {
          "text": "An object that creates matches with other players without presenting an interface to the players.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKMatchmaker"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKMatchmaker"
        }
      ],
      "role": "symbol",
      "title": "GKMatchmaker",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchmaker"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker/addPlayers(to:matchRequest:completionHandler:)": {
      "abstract": [
        {
          "text": "Invites additional players to an existing match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addPlayers"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKMatch",
          "text": "GKMatch"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "matchRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKMatchRequest",
          "text": "GKMatchRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker/addPlayers(to:matchRequest:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addPlayersToMatch:matchRequest:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "addPlayers(to:matchRequest:completionHandler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchmaker/addplayers(to:matchrequest:completionhandler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker/cancel()": {
      "abstract": [
        {
          "text": "Cancels a matchmaking request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancel"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker/cancel()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancel"
        }
      ],
      "role": "symbol",
      "title": "cancel()",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchmaker/cancel()"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker/cancelPendingInvite(to:)": {
      "abstract": [
        {
          "text": "Cancels a pending invitation to another player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelPendingInvite"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKPlayer",
          "text": "GKPlayer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker/cancelPendingInvite(to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancelPendingInviteToPlayer:"
        }
      ],
      "role": "symbol",
      "title": "cancelPendingInvite(to:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchmaker/cancelpendinginvite(to:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker/findMatch(for:withCompletionHandler:)": {
      "abstract": [
        {
          "text": "Initiates a request to find players for a peer-to-peer match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "findMatch"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKMatchRequest",
          "text": "GKMatchRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withCompletionHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKMatch",
          "text": "GKMatch"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker/findMatch(for:withCompletionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "findMatchForRequest:withCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "findMatch(for:withCompletionHandler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchmaker/findmatch(for:withcompletionhandler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker/findMatchedPlayers(_:withCompletionHandler:)": {
      "abstract": [
        {
          "text": "Initiates a request to find players for a hosted match that uses matchmaking rules.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "findMatchedPlayers"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKMatchRequest",
          "text": "GKMatchRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withCompletionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKMatchedPlayers",
          "text": "GKMatchedPlayers"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker/findMatchedPlayers(_:withCompletionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "findMatchedPlayers:withCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "findMatchedPlayers(_:withCompletionHandler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchmaker/findmatchedplayers(_:withcompletionhandler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker/findPlayers(forHostedRequest:withCompletionHandler:)": {
      "abstract": [
        {
          "text": "Initiates a request to find players for a hosted match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "findPlayers"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forHostedRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKMatchRequest",
          "text": "GKMatchRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withCompletionHandler"
        },
        {
          "kind": "text",
          "text": ": ((["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKPlayer",
          "text": "GKPlayer"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker/findPlayers(forHostedRequest:withCompletionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "findPlayersForHostedRequest:withCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "findPlayers(forHostedRequest:withCompletionHandler:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchmaker/findplayers(forhostedrequest:withcompletionhandler:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker/finishMatchmaking(for:)": {
      "abstract": [
        {
          "text": "Informs the server when programmatic matchmaking finishes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "finishMatchmaking"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKMatch",
          "text": "GKMatch"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker/finishMatchmaking(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "finishMatchmakingForMatch:"
        }
      ],
      "role": "symbol",
      "title": "finishMatchmaking(for:)",
      "type": "topic",
      "url": "/documentation/gamekit/gkmatchmaker/finishmatchmaking(for:)"
    },
    "doc://com.apple.gamekit/documentation/GameKit/matchmaking-rules": {
      "abstract": [
        {
          "text": "Game Center applies different type of rules you create in a particular order to find the best matches.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/matchmaking-rules",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Matchmaking rules",
      "type": "topic",
      "url": "/documentation/gamekit/matchmaking-rules"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Matching-players",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker/findMatch(for:withCompletionHandler:)",
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker/findPlayers(forHostedRequest:withCompletionHandler:)",
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchedPlayers",
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker/addPlayers(to:matchRequest:completionHandler:)",
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker/finishMatchmaking(for:)",
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker/cancel()",
        "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker/cancelPendingInvite(to:)"
      ],
      "title": "Matching players"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.2",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.2",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.1",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "findMatchedPlayers:withCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "findMatchedPlayers:withCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamekit/documentation/GameKit",
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Matching-players",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker/findMatch(for:withCompletionHandler:)",
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker/findPlayers(forHostedRequest:withCompletionHandler:)",
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchedPlayers",
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker/addPlayers(to:matchRequest:completionHandler:)",
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker/finishMatchmaking(for:)",
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker/cancel()",
                "doc://com.apple.gamekit/documentation/GameKit/GKMatchmaker/cancelPendingInvite(to:)"
              ],
              "title": "Matching players"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "findMatchedPlayers:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchRequest",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)GKMatchRequest",
                    "text": "GKMatchRequest"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "request"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "withCompletionHandler:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)("
                  },
                  {
                    "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKMatchedPlayers",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)GKMatchedPlayers",
                    "text": "GKMatchedPlayers"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "matchedPlayers"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ")) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "completionHandler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The configuration for the match.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "request"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The block that GameKit calls when it completes the request.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "This block receives the following parameters:",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "items": [
                      {
                        "definition": {
                          "content": [
                            {
                              "inlineContent": [
                                {
                                  "text": "The players that join the match, including their properties that matchmaking rules uses. If unsuccessful, this parameter is ",
                                  "type": "text"
                                },
                                {
                                  "code": "nil",
                                  "type": "codeVoice"
                                },
                                {
                                  "text": ".",
                                  "type": "text"
                                }
                              ],
                              "type": "paragraph"
                            }
                          ]
                        },
                        "term": {
                          "inlineContent": [
                            {
                              "code": "matchedPlayers",
                              "type": "codeVoice"
                            }
                          ]
                        }
                      },
                      {
                        "definition": {
                          "content": [
                            {
                              "inlineContent": [
                                {
                                  "text": "Describes an error if it occurs, or ",
                                  "type": "text"
                                },
                                {
                                  "code": "nil",
                                  "type": "codeVoice"
                                },
                                {
                                  "text": " if the operation completes.",
                                  "type": "text"
                                }
                              ],
                              "type": "paragraph"
                            }
                          ]
                        },
                        "term": {
                          "inlineContent": [
                            {
                              "code": "error",
                              "type": "codeVoice"
                            }
                          ]
                        }
                      }
                    ],
                    "type": "termList"
                  }
                ],
                "name": "completionHandler"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchmaker~1cancelPendingInvite(to:)/title",
          "value": "cancelPendingInviteToPlayer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchmaker~1cancelPendingInvite(to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cancelPendingInviteToPlayer:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1queueName/title",
          "value": "queueName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1queueName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "queueName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1properties/title",
          "value": "properties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest~1properties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchmaker~1findMatch(for:withCompletionHandler:)/title",
          "value": "findMatchForRequest:withCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchmaker~1findMatch(for:withCompletionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "findMatchForRequest:withCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchmaker~1findPlayers(forHostedRequest:withCompletionHandler:)/title",
          "value": "findPlayersForHostedRequest:withCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchmaker~1findPlayers(forHostedRequest:withCompletionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "findPlayersForHostedRequest:withCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchmaker~1addPlayers(to:matchRequest:completionHandler:)/title",
          "value": "addPlayersToMatch:matchRequest:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchmaker~1addPlayers(to:matchRequest:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addPlayersToMatch:matchRequest:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchedPlayers/title",
          "value": "GKMatchedPlayers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchedPlayers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMatchedPlayers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchedPlayers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMatchedPlayers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchmaker~1cancel()/title",
          "value": "cancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchmaker~1cancel()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest/title",
          "value": "GKMatchRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMatchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMatchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchmaker/title",
          "value": "GKMatchmaker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchmaker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMatchmaker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchmaker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKMatchmaker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchmaker~1findMatchedPlayers(_:withCompletionHandler:)/title",
          "value": "findMatchedPlayers:withCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchmaker~1findMatchedPlayers(_:withCompletionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "findMatchedPlayers:withCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchmaker~1finishMatchmaking(for:)/title",
          "value": "finishMatchmakingForMatch:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKMatchmaker~1finishMatchmaking(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "finishMatchmakingForMatch:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/gkmatchmaker/findmatchedplayers(_:withcompletionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamekit/gkmatchmaker/findmatchedplayers(_:withcompletionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
