{
  "abstract": [
    {
      "text": "Period of the effect, in microseconds.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC/dwPeriod"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@FFPERIODIC@FI@dwPeriod",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "dwPeriod"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@DWORD",
        "text": "DWORD"
      }
    ],
    "modules": [
      {
        "name": "Force Feedback"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "dwPeriod"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "dwPeriod"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dwPeriod"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/DWORD",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@DWORD",
              "text": "DWORD"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback": {
      "abstract": [
        {
          "text": "Control force feedback devices attached to the system. Develop plug-ins that enable communication with force feedback hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback",
      "kind": "symbol",
      "role": "collection",
      "title": "Force Feedback",
      "type": "topic",
      "url": "/documentation/forcefeedback"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/DWORD": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DWORD"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/DWORD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DWORD"
        }
      ],
      "role": "symbol",
      "title": "DWORD",
      "type": "topic",
      "url": "/documentation/forcefeedback/dword"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC": {
      "abstract": [
        {
          "text": "A structure containing type-specific information for certain effects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFPERIODIC"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFPERIODIC"
        }
      ],
      "role": "symbol",
      "title": "FFPERIODIC",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffperiodic"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC/dwMagnitude": {
      "abstract": [
        {
          "text": "Magnitude of the effect, in the range from 0 through 10,000. If an envelope is applied to this effect, the value represents the magnitude of the sustain. If no envelope is applied, the value represents the amplitude of the entire effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dwMagnitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC/dwMagnitude",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dwMagnitude"
        }
      ],
      "role": "symbol",
      "title": "dwMagnitude",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffperiodic/dwmagnitude"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC/dwPeriod": {
      "abstract": [
        {
          "text": "Period of the effect, in microseconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dwPeriod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC/dwPeriod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dwPeriod"
        }
      ],
      "role": "symbol",
      "title": "dwPeriod",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffperiodic/dwperiod"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC/dwPhase": {
      "abstract": [
        {
          "text": "Position in the cycle of the periodic effect at which playback begins, in the range from 0 through 35,999.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dwPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DWORD",
          "text": "DWORD"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC/dwPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dwPhase"
        }
      ],
      "role": "symbol",
      "title": "dwPhase",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffperiodic/dwphase"
    },
    "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC/lOffset": {
      "abstract": [
        {
          "text": "Offset of the effect. The range of forces generated by the effect is ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "lOffset",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " minus ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "dwMagnitude",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " to ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "lOffset",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " plus ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "dwMagnitude",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": ". The value of the ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "lOffset",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " member is also the baseline for any envelope that is applied to the effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LONG",
          "text": "LONG"
        }
      ],
      "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC/lOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lOffset"
        }
      ],
      "role": "symbol",
      "title": "lOffset",
      "type": "topic",
      "url": "/documentation/forcefeedback/ffperiodic/loffset"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC/dwMagnitude",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC/dwPhase",
        "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC/lOffset"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "dwPeriod"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dwPeriod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC/dwMagnitude",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC/dwPhase",
                "doc://com.apple.forcefeedback/documentation/ForceFeedback/FFPERIODIC/lOffset"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.forcefeedback/documentation/ForceFeedback/DWORD",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@DWORD",
                    "text": "DWORD"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "dwPeriod"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFPERIODIC/title",
          "value": "FFPERIODIC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFPERIODIC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFPERIODIC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFPERIODIC/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFPERIODIC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFPERIODIC~1dwPeriod/title",
          "value": "dwPeriod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFPERIODIC~1dwPeriod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dwPeriod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFPERIODIC~1dwPhase/title",
          "value": "dwPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFPERIODIC~1dwPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dwPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1DWORD/title",
          "value": "DWORD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1DWORD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DWORD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1DWORD/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DWORD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFPERIODIC~1lOffset/title",
          "value": "lOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFPERIODIC~1lOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFPERIODIC~1dwMagnitude/title",
          "value": "dwMagnitude"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.forcefeedback~1documentation~1ForceFeedback~1FFPERIODIC~1dwMagnitude/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dwMagnitude"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/forcefeedback/ffperiodic/dwperiod"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/forcefeedback/ffperiodic/dwperiod"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
