{
  "abstract": [
    {
      "text": "The value for Friday.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions/friday"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INDayOfWeekOptions@INDayOfWeekOptionFriday",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "friday"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@INDayOfWeekOptions",
        "text": "INDayOfWeekOptions"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INDayOfWeekOptionFriday"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "friday"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "friday"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@INDayOfWeekOptions",
              "text": "INDayOfWeekOptions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions": {
      "abstract": [
        {
          "text": "Days of the week.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INDayOfWeekOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDayOfWeekOptions"
        }
      ],
      "role": "symbol",
      "title": "INDayOfWeekOptions",
      "type": "topic",
      "url": "/documentation/intents/indayofweekoptions"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions/friday": {
      "abstract": [
        {
          "text": "The value for Friday.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "friday"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INDayOfWeekOptions",
          "text": "INDayOfWeekOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions/friday",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDayOfWeekOptionFriday"
        }
      ],
      "role": "symbol",
      "title": "friday",
      "type": "topic",
      "url": "/documentation/intents/indayofweekoptions/friday"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions/monday": {
      "abstract": [
        {
          "text": "The value for Monday.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monday"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INDayOfWeekOptions",
          "text": "INDayOfWeekOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions/monday",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDayOfWeekOptionMonday"
        }
      ],
      "role": "symbol",
      "title": "monday",
      "type": "topic",
      "url": "/documentation/intents/indayofweekoptions/monday"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions/saturday": {
      "abstract": [
        {
          "text": "The value for Saturday.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "saturday"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INDayOfWeekOptions",
          "text": "INDayOfWeekOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions/saturday",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDayOfWeekOptionSaturday"
        }
      ],
      "role": "symbol",
      "title": "saturday",
      "type": "topic",
      "url": "/documentation/intents/indayofweekoptions/saturday"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions/sunday": {
      "abstract": [
        {
          "text": "The value for Sunday.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sunday"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INDayOfWeekOptions",
          "text": "INDayOfWeekOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions/sunday",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDayOfWeekOptionSunday"
        }
      ],
      "role": "symbol",
      "title": "sunday",
      "type": "topic",
      "url": "/documentation/intents/indayofweekoptions/sunday"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions/thursday": {
      "abstract": [
        {
          "text": "The value for Thursday.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thursday"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INDayOfWeekOptions",
          "text": "INDayOfWeekOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions/thursday",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDayOfWeekOptionThursday"
        }
      ],
      "role": "symbol",
      "title": "thursday",
      "type": "topic",
      "url": "/documentation/intents/indayofweekoptions/thursday"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions/tuesday": {
      "abstract": [
        {
          "text": "The value for Tuesday.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tuesday"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INDayOfWeekOptions",
          "text": "INDayOfWeekOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions/tuesday",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDayOfWeekOptionTuesday"
        }
      ],
      "role": "symbol",
      "title": "tuesday",
      "type": "topic",
      "url": "/documentation/intents/indayofweekoptions/tuesday"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions/wednesday": {
      "abstract": [
        {
          "text": "The value for Wednesday.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wednesday"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INDayOfWeekOptions",
          "text": "INDayOfWeekOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions/wednesday",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDayOfWeekOptionWednesday"
        }
      ],
      "role": "symbol",
      "title": "wednesday",
      "type": "topic",
      "url": "/documentation/intents/indayofweekoptions/wednesday"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Days-of-the-Week",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions/monday",
        "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions/tuesday",
        "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions/wednesday",
        "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions/thursday",
        "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions/saturday",
        "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions/sunday"
      ],
      "title": "Days of the Week"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INDayOfWeekOptionFriday"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDayOfWeekOptionFriday"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Days-of-the-Week",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions/monday",
                "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions/tuesday",
                "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions/wednesday",
                "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions/thursday",
                "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions/saturday",
                "doc://com.apple.sirikit/documentation/Intents/INDayOfWeekOptions/sunday"
              ],
              "title": "Days of the Week"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INDayOfWeekOptionFriday"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDayOfWeekOptions/title",
          "value": "INDayOfWeekOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDayOfWeekOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDayOfWeekOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDayOfWeekOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INDayOfWeekOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDayOfWeekOptions~1thursday/title",
          "value": "INDayOfWeekOptionThursday"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDayOfWeekOptions~1thursday/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDayOfWeekOptionThursday"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDayOfWeekOptions~1wednesday/title",
          "value": "INDayOfWeekOptionWednesday"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDayOfWeekOptions~1wednesday/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDayOfWeekOptionWednesday"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDayOfWeekOptions~1monday/title",
          "value": "INDayOfWeekOptionMonday"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDayOfWeekOptions~1monday/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDayOfWeekOptionMonday"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDayOfWeekOptions~1tuesday/title",
          "value": "INDayOfWeekOptionTuesday"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDayOfWeekOptions~1tuesday/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDayOfWeekOptionTuesday"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDayOfWeekOptions~1sunday/title",
          "value": "INDayOfWeekOptionSunday"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDayOfWeekOptions~1sunday/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDayOfWeekOptionSunday"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDayOfWeekOptions~1saturday/title",
          "value": "INDayOfWeekOptionSaturday"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDayOfWeekOptions~1saturday/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDayOfWeekOptionSaturday"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDayOfWeekOptions~1friday/title",
          "value": "INDayOfWeekOptionFriday"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDayOfWeekOptions~1friday/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDayOfWeekOptionFriday"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/indayofweekoptions/friday"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/indayofweekoptions/friday"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
