{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeChamber"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AUReverbRoomType@kReverbRoomType_LargeChamber",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "reverbRoomType_LargeChamber"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kReverbRoomType_LargeChamber"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AUReverbRoomType.reverbRoomType_LargeChamber"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "reverbRoomType_LargeChamber"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUReverbRoomType"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUReverbRoomType"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_Cathedral": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbRoomType_Cathedral"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_Cathedral",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbRoomType_Cathedral"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType.reverbRoomType_Cathedral",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype/reverbroomtype_cathedral"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeChamber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbRoomType_LargeChamber"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeChamber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbRoomType_LargeChamber"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType.reverbRoomType_LargeChamber",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype/reverbroomtype_largechamber"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeHall": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbRoomType_LargeHall"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeHall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbRoomType_LargeHall"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType.reverbRoomType_LargeHall",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype/reverbroomtype_largehall"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeHall2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbRoomType_LargeHall2"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeHall2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbRoomType_LargeHall2"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType.reverbRoomType_LargeHall2",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype/reverbroomtype_largehall2"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeRoom": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbRoomType_LargeRoom"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeRoom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbRoomType_LargeRoom"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType.reverbRoomType_LargeRoom",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype/reverbroomtype_largeroom"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeRoom2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbRoomType_LargeRoom2"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeRoom2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbRoomType_LargeRoom2"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType.reverbRoomType_LargeRoom2",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype/reverbroomtype_largeroom2"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumChamber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbRoomType_MediumChamber"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumChamber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbRoomType_MediumChamber"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType.reverbRoomType_MediumChamber",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype/reverbroomtype_mediumchamber"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumHall": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbRoomType_MediumHall"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumHall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbRoomType_MediumHall"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType.reverbRoomType_MediumHall",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype/reverbroomtype_mediumhall"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumHall2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbRoomType_MediumHall2"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumHall2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbRoomType_MediumHall2"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType.reverbRoomType_MediumHall2",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype/reverbroomtype_mediumhall2"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumHall3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbRoomType_MediumHall3"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumHall3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbRoomType_MediumHall3"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType.reverbRoomType_MediumHall3",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype/reverbroomtype_mediumhall3"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumRoom": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbRoomType_MediumRoom"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumRoom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbRoomType_MediumRoom"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType.reverbRoomType_MediumRoom",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype/reverbroomtype_mediumroom"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_Plate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbRoomType_Plate"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_Plate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbRoomType_Plate"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType.reverbRoomType_Plate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype/reverbroomtype_plate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_SmallRoom": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbRoomType_SmallRoom"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_SmallRoom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReverbRoomType_SmallRoom"
        }
      ],
      "role": "symbol",
      "title": "AUReverbRoomType.reverbRoomType_SmallRoom",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aureverbroomtype/reverbroomtype_smallroom"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_Cathedral",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeHall",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeHall2",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeRoom",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeRoom2",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumChamber",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumHall",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumHall2",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumHall3",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumRoom",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_Plate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_SmallRoom"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kReverbRoomType_LargeChamber"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbRoomType_LargeChamber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_Cathedral",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeHall",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeHall2",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeRoom",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_LargeRoom2",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumChamber",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumHall",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumHall2",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumHall3",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_MediumRoom",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_Plate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUReverbRoomType/reverbRoomType_SmallRoom"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kReverbRoomType_LargeChamber"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_LargeHall2/title",
          "value": "kReverbRoomType_LargeHall2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_LargeHall2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbRoomType_LargeHall2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_MediumHall/title",
          "value": "kReverbRoomType_MediumHall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_MediumHall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbRoomType_MediumHall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_LargeHall/title",
          "value": "kReverbRoomType_LargeHall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_LargeHall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbRoomType_LargeHall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_LargeChamber/title",
          "value": "kReverbRoomType_LargeChamber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_LargeChamber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbRoomType_LargeChamber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_SmallRoom/title",
          "value": "kReverbRoomType_SmallRoom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_SmallRoom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbRoomType_SmallRoom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_MediumChamber/title",
          "value": "kReverbRoomType_MediumChamber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_MediumChamber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbRoomType_MediumChamber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_LargeRoom/title",
          "value": "kReverbRoomType_LargeRoom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_LargeRoom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbRoomType_LargeRoom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType/title",
          "value": "AUReverbRoomType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUReverbRoomType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUReverbRoomType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_MediumHall2/title",
          "value": "kReverbRoomType_MediumHall2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_MediumHall2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbRoomType_MediumHall2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_MediumHall3/title",
          "value": "kReverbRoomType_MediumHall3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_MediumHall3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbRoomType_MediumHall3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_MediumRoom/title",
          "value": "kReverbRoomType_MediumRoom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_MediumRoom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbRoomType_MediumRoom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_Cathedral/title",
          "value": "kReverbRoomType_Cathedral"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_Cathedral/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbRoomType_Cathedral"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_Plate/title",
          "value": "kReverbRoomType_Plate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_Plate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbRoomType_Plate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_LargeRoom2/title",
          "value": "kReverbRoomType_LargeRoom2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUReverbRoomType~1reverbRoomType_LargeRoom2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReverbRoomType_LargeRoom2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/aureverbroomtype/reverbroomtype_largechamber"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/aureverbroomtype/reverbroomtype_largechamber"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
