{
  "abstract": [
    {
      "text": "The window can be resized by the user.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/resizable"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSWindowStyleMask@NSWindowStyleMaskResizable",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "resizable"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSWindow",
        "text": "NSWindow"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSWindowStyleMask",
        "text": "StyleMask"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSWindowStyleMaskResizable"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "resizable"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "resizable"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSWindow",
              "text": "NSWindow"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSWindowStyleMask",
              "text": "StyleMask"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPanel": {
      "abstract": [
        {
          "text": "A special kind of window that typically performs a function that is auxiliary to the main window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPanel"
        }
      ],
      "role": "symbol",
      "title": "NSPanel",
      "type": "topic",
      "url": "/documentation/appkit/nspanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow": {
      "abstract": [
        {
          "text": "A window that an app displays on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "role": "symbol",
      "title": "NSWindow",
      "type": "topic",
      "url": "/documentation/appkit/nswindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct": {
      "abstract": [
        {
          "text": "Constants that specify the style of a window, and that you can combine with the C bitwise OR operator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "StyleMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "StyleMask"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.StyleMask",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/stylemask-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/borderless": {
      "abstract": [
        {
          "text": "The window displays none of the usual peripheral elements. Useful only for display or caching purposes. A window that uses ",
          "type": "text"
        },
        {
          "code": "NSWindowStyleMaskBorderless",
          "type": "codeVoice"
        },
        {
          "text": " can’t become key or main, unless the value of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/canBecomeKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/canBecomeMain",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/swift/true",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ". Note that you can set a window’s or panel’s style mask to ",
          "type": "text"
        },
        {
          "code": "NSWindowStyleMaskBorderless",
          "type": "codeVoice"
        },
        {
          "text": " in Interface Builder by deselecting Title Bar in the Appearance section of the Attributes inspector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "borderless"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowStyleMask",
          "text": "StyleMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/borderless",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowStyleMaskBorderless"
        }
      ],
      "role": "symbol",
      "title": "borderless",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/stylemask-swift.struct/borderless"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/closable": {
      "abstract": [
        {
          "text": "The window displays a close button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "closable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowStyleMask",
          "text": "StyleMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/closable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowStyleMaskClosable"
        }
      ],
      "role": "symbol",
      "title": "closable",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/stylemask-swift.struct/closable"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/docModalWindow": {
      "abstract": [
        {
          "text": "The window is a document-modal panel (or  a subclass of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPanel",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "docModalWindow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowStyleMask",
          "text": "StyleMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/docModalWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowStyleMaskDocModalWindow"
        }
      ],
      "role": "symbol",
      "title": "docModalWindow",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/stylemask-swift.struct/docmodalwindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/fullScreen": {
      "abstract": [
        {
          "text": "The window can appear full screen. A fullscreen window does not draw its title bar, and may have special handling for its toolbar. (This mask is automatically toggled when ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/toggleFullScreen(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " is called.)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullScreen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowStyleMask",
          "text": "StyleMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/fullScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowStyleMaskFullScreen"
        }
      ],
      "role": "symbol",
      "title": "fullScreen",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/stylemask-swift.struct/fullscreen"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/fullSizeContentView": {
      "abstract": [
        {
          "text": "When set, the window’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/contentView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " consumes the full size of the window. Although you can combine this constant with other window style masks, it is respected only for windows with a title bar. Note that using this mask opts in to layer-backing. Use the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/contentLayoutRect",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " or the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/contentLayoutGuide",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to lay out views underneath the title bar–toolbar area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullSizeContentView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowStyleMask",
          "text": "StyleMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/fullSizeContentView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowStyleMaskFullSizeContentView"
        }
      ],
      "role": "symbol",
      "title": "fullSizeContentView",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/stylemask-swift.struct/fullsizecontentview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/hudWindow": {
      "abstract": [
        {
          "text": "The window is a HUD panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hudWindow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowStyleMask",
          "text": "StyleMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/hudWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowStyleMaskHUDWindow"
        }
      ],
      "role": "symbol",
      "title": "hudWindow",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/stylemask-swift.struct/hudwindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/miniaturizable": {
      "abstract": [
        {
          "text": "The window displays a minimize button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "miniaturizable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowStyleMask",
          "text": "StyleMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/miniaturizable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowStyleMaskMiniaturizable"
        }
      ],
      "role": "symbol",
      "title": "miniaturizable",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/stylemask-swift.struct/miniaturizable"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/nonactivatingPanel": {
      "abstract": [
        {
          "text": "The window is a panel or a subclass of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPanel",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " that does not activate the owning app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonactivatingPanel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowStyleMask",
          "text": "StyleMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/nonactivatingPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowStyleMaskNonactivatingPanel"
        }
      ],
      "role": "symbol",
      "title": "nonactivatingPanel",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/stylemask-swift.struct/nonactivatingpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/resizable": {
      "abstract": [
        {
          "text": "The window can be resized by the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resizable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowStyleMask",
          "text": "StyleMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/resizable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowStyleMaskResizable"
        }
      ],
      "role": "symbol",
      "title": "resizable",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/stylemask-swift.struct/resizable"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/texturedBackground": {
      "abstract": [
        {
          "text": "The window uses a textured background that darkens when the window is key or main and lightens when it is inactive, and may have a second gradient in the section below the window content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "texturedBackground"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowStyleMask",
          "text": "StyleMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/texturedBackground",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowStyleMaskTexturedBackground"
        }
      ],
      "role": "symbol",
      "title": "texturedBackground",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/stylemask-swift.struct/texturedbackground"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/titled": {
      "abstract": [
        {
          "text": "The window displays a title bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowStyleMask",
          "text": "StyleMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/titled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowStyleMaskTitled"
        }
      ],
      "role": "symbol",
      "title": "titled",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/stylemask-swift.struct/titled"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/unifiedTitleAndToolbar": {
      "abstract": [
        {
          "text": "This constant has no effect, because all windows that include a toolbar use the unified style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unifiedTitleAndToolbar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowStyleMask",
          "text": "StyleMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/unifiedTitleAndToolbar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowStyleMaskUnifiedTitleAndToolbar"
        }
      ],
      "role": "symbol",
      "title": "unifiedTitleAndToolbar",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/stylemask-swift.struct/unifiedtitleandtoolbar"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/utilityWindow": {
      "abstract": [
        {
          "text": "The window is a panel or a subclass of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPanel",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "utilityWindow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowStyleMask",
          "text": "StyleMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/utilityWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowStyleMaskUtilityWindow"
        }
      ],
      "role": "symbol",
      "title": "utilityWindow",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/stylemask-swift.struct/utilitywindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/canBecomeKey": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the window can become the key window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canBecomeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/canBecomeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canBecomeKeyWindow"
        }
      ],
      "role": "symbol",
      "title": "canBecomeKey",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/canbecomekey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/canBecomeMain": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the window can become the application’s main window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canBecomeMain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/canBecomeMain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canBecomeMainWindow"
        }
      ],
      "role": "symbol",
      "title": "canBecomeMain",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/canbecomemain"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/contentLayoutGuide": {
      "abstract": [
        {
          "text": "A value used by Auto Layout constraints to automatically bind to the value of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/contentLayoutRect",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentLayoutGuide"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/contentLayoutGuide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentLayoutGuide"
        }
      ],
      "role": "symbol",
      "title": "contentLayoutGuide",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/contentlayoutguide"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/contentLayoutRect": {
      "abstract": [
        {
          "text": "The area inside the window that is for non-obscured content, in window coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentLayoutRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/contentLayoutRect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentLayoutRect"
        }
      ],
      "role": "symbol",
      "title": "contentLayoutRect",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/contentlayoutrect"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/contentView": {
      "abstract": [
        {
          "text": "The window’s content view, the highest accessible view object in the window’s view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/contentView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentView"
        }
      ],
      "role": "symbol",
      "title": "contentView",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/contentview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/toggleFullScreen(_:)": {
      "abstract": [
        {
          "text": "Takes the window into or out of fullscreen mode,",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toggleFullScreen"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/toggleFullScreen(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toggleFullScreen:"
        }
      ],
      "role": "symbol",
      "title": "toggleFullScreen(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/togglefullscreen(_:)"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/borderless",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/titled",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/closable",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/miniaturizable",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/texturedBackground",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/unifiedTitleAndToolbar",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/fullScreen",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/fullSizeContentView",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/utilityWindow",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/docModalWindow",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/nonactivatingPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/hudWindow"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSWindowStyleMaskResizable"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowStyleMaskResizable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/borderless",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/titled",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/closable",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/miniaturizable",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/texturedBackground",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/unifiedTitleAndToolbar",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/fullScreen",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/fullSizeContentView",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/utilityWindow",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/docModalWindow",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/nonactivatingPanel",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/StyleMask-swift.struct/hudWindow"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSWindowStyleMaskResizable"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct~1closable/title",
          "value": "NSWindowStyleMaskClosable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct~1closable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowStyleMaskClosable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1contentLayoutRect/title",
          "value": "contentLayoutRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1contentLayoutRect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentLayoutRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1canBecomeKey/title",
          "value": "canBecomeKeyWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1canBecomeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canBecomeKeyWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1contentView/title",
          "value": "contentView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1contentView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct~1unifiedTitleAndToolbar/title",
          "value": "NSWindowStyleMaskUnifiedTitleAndToolbar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct~1unifiedTitleAndToolbar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowStyleMaskUnifiedTitleAndToolbar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct~1fullSizeContentView/title",
          "value": "NSWindowStyleMaskFullSizeContentView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct~1fullSizeContentView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowStyleMaskFullSizeContentView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct~1nonactivatingPanel/title",
          "value": "NSWindowStyleMaskNonactivatingPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct~1nonactivatingPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowStyleMaskNonactivatingPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct~1miniaturizable/title",
          "value": "NSWindowStyleMaskMiniaturizable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct~1miniaturizable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowStyleMaskMiniaturizable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct/title",
          "value": "NSWindowStyleMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowStyleMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowStyleMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1canBecomeMain/title",
          "value": "canBecomeMainWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1canBecomeMain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canBecomeMainWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1toggleFullScreen(_:)/title",
          "value": "toggleFullScreen:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1toggleFullScreen(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "toggleFullScreen:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct~1texturedBackground/title",
          "value": "NSWindowStyleMaskTexturedBackground"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct~1texturedBackground/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowStyleMaskTexturedBackground"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct~1resizable/title",
          "value": "NSWindowStyleMaskResizable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct~1resizable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowStyleMaskResizable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPanel/title",
          "value": "NSPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct~1titled/title",
          "value": "NSWindowStyleMaskTitled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct~1titled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowStyleMaskTitled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title",
          "value": "NSWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct~1utilityWindow/title",
          "value": "NSWindowStyleMaskUtilityWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct~1utilityWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowStyleMaskUtilityWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct~1docModalWindow/title",
          "value": "NSWindowStyleMaskDocModalWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct~1docModalWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowStyleMaskDocModalWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct~1borderless/title",
          "value": "NSWindowStyleMaskBorderless"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct~1borderless/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowStyleMaskBorderless"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct~1fullScreen/title",
          "value": "NSWindowStyleMaskFullScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct~1fullScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowStyleMaskFullScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1contentLayoutGuide/title",
          "value": "contentLayoutGuide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1contentLayoutGuide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentLayoutGuide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct~1hudWindow/title",
          "value": "NSWindowStyleMaskHUDWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1StyleMask-swift.struct~1hudWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowStyleMaskHUDWindow"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nswindow/stylemask-swift.struct/resizable"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nswindow/stylemask-swift.struct/resizable"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
