{
  "abstract": [
    {
      "text": "The type of file system your app extension provides.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://FSKit/documentation/FSKit",
        "doc://FSKit/documentation/FSKit/UnaryFileSystemExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://FSKit/documentation/FSKit/UnaryFileSystemExtension/FileSystem-swift.associatedtype"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:5FSKit24UnaryFileSystemExtensionP0cD0Qa",
    "fragments": [
      {
        "kind": "keyword",
        "text": "associatedtype"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FileSystem"
      },
      {
        "kind": "text",
        "text": " : "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)FSUnaryFileSystem",
        "text": "FSUnaryFileSystem"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)FSUnaryFileSystemOperations",
        "text": "FSUnaryFileSystemOperations"
      }
    ],
    "modules": [
      {
        "name": "FSKit"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Associated Type",
    "symbolKind": "associatedtype",
    "title": "FileSystem"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "associatedtype"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FileSystem"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://FSKit/documentation/FSKit/FSUnaryFileSystem",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)FSUnaryFileSystem",
              "text": "FSUnaryFileSystem"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://FSKit/documentation/FSKit/FSUnaryFileSystemOperations",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)FSUnaryFileSystemOperations",
              "text": "FSUnaryFileSystemOperations"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://FSKit/documentation/FSKit": {
      "abstract": [
        {
          "text": "Implement a file system that runs in user space.",
          "type": "text"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit",
      "kind": "symbol",
      "role": "collection",
      "title": "FSKit",
      "type": "topic",
      "url": "/documentation/fskit"
    },
    "doc://FSKit/documentation/FSKit/FSUnaryFileSystem": {
      "abstract": [
        {
          "text": "An abstract base class for implementing a minimal file system.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSUnaryFileSystem"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSUnaryFileSystem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSUnaryFileSystem"
        }
      ],
      "role": "symbol",
      "title": "FSUnaryFileSystem",
      "type": "topic",
      "url": "/documentation/fskit/fsunaryfilesystem"
    },
    "doc://FSKit/documentation/FSKit/FSUnaryFileSystemOperations": {
      "abstract": [
        {
          "text": "Operations performed by a unary file system.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSUnaryFileSystemOperations"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSUnaryFileSystemOperations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSUnaryFileSystemOperations"
        }
      ],
      "role": "symbol",
      "title": "FSUnaryFileSystemOperations",
      "type": "topic",
      "url": "/documentation/fskit/fsunaryfilesystemoperations"
    },
    "doc://FSKit/documentation/FSKit/UnaryFileSystemExtension": {
      "abstract": [
        {
          "text": "A protocol for implementing a minimal file system as an app extension.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnaryFileSystemExtension"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/UnaryFileSystemExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UnaryFileSystemExtension"
        }
      ],
      "role": "symbol",
      "title": "UnaryFileSystemExtension",
      "type": "topic",
      "url": "/documentation/fskit/unaryfilesystemextension"
    },
    "doc://FSKit/documentation/FSKit/UnaryFileSystemExtension/FileSystem-swift.associatedtype": {
      "abstract": [
        {
          "text": "The type of file system your app extension provides.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "associatedtype"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FileSystem"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSUnaryFileSystem",
          "text": "FSUnaryFileSystem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)FSUnaryFileSystemOperations",
          "text": "FSUnaryFileSystemOperations"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/UnaryFileSystemExtension/FileSystem-swift.associatedtype",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "FileSystem",
      "type": "topic",
      "url": "/documentation/fskit/unaryfilesystemextension/filesystem-swift.associatedtype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSUnaryFileSystem/title",
          "value": "FSUnaryFileSystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSUnaryFileSystem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSUnaryFileSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSUnaryFileSystem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSUnaryFileSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSUnaryFileSystemOperations/title",
          "value": "FSUnaryFileSystemOperations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSUnaryFileSystemOperations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSUnaryFileSystemOperations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSUnaryFileSystemOperations/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSUnaryFileSystemOperations"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fskit/unaryfilesystemextension/filesystem-swift.associatedtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
