{
  "abstract": [
    {
      "text": "An array of texture coordinate values for each point in the face mesh.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/ARFaceGeometry"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARFaceGeometry/textureCoordinates-u42d"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "ARKit",
    "externalID": "s:So14ARFaceGeometryC5ARKitE18textureCoordinatesSays5SIMD2VySfGGvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "textureCoordinates"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@vector_float2",
        "text": "vector_float2"
      },
      {
        "kind": "text",
        "text": "]"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "textureCoordinates"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@nonobjc"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "textureCoordinates"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@vector_float2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vector_float2",
              "text": "vector_float2"
            },
            {
              "kind": "text",
              "text": "] { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Each ",
              "type": "text"
            },
            {
              "code": "float2",
              "type": "codeVoice"
            },
            {
              "text": " value in this array represents the UV texture coordinates for the vertex at the corresponding index in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceGeometry/vertices-fhdb",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " buffer.Face mesh topology is constant across ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceGeometry",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instances, so the values in this array always maps the same vertex indices to the same texture coordinates.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFaceGeometry": {
      "abstract": [
        {
          "text": "A 3D mesh describing face topology for use in face-tracking AR sessions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARFaceGeometry"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceGeometry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARFaceGeometry"
        }
      ],
      "role": "symbol",
      "title": "ARFaceGeometry",
      "type": "topic",
      "url": "/documentation/arkit/arfacegeometry"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFaceGeometry/textureCoordinates-u42d": {
      "abstract": [
        {
          "text": "An array of texture coordinate values for each point in the face mesh.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textureCoordinates"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_float2",
          "text": "vector_float2"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceGeometry/textureCoordinates-u42d",
      "kind": "symbol",
      "role": "symbol",
      "title": "textureCoordinates",
      "type": "topic",
      "url": "/documentation/arkit/arfacegeometry/texturecoordinates-u42d"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFaceGeometry/triangleCount": {
      "abstract": [
        {
          "text": "The number of triangles described by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceGeometry/triangleIndices-3tb1o",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "triangleCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceGeometry/triangleCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "triangleCount"
        }
      ],
      "role": "symbol",
      "title": "triangleCount",
      "type": "topic",
      "url": "/documentation/arkit/arfacegeometry/trianglecount"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFaceGeometry/triangleIndices-3tb1o": {
      "abstract": [
        {
          "text": "A buffer of indices describing the triangle mesh formed by the face geometry’s vertex data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "triangleIndices"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceGeometry/triangleIndices-3tb1o",
      "kind": "symbol",
      "role": "symbol",
      "title": "triangleIndices",
      "type": "topic",
      "url": "/documentation/arkit/arfacegeometry/triangleindices-3tb1o"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFaceGeometry/triangleIndices-8isy8": {
      "abstract": [
        {
          "text": "An array of indices describing the triangle mesh formed by the face geometry’s vertex data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "triangleIndices"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceGeometry/triangleIndices-8isy8",
      "kind": "symbol",
      "role": "symbol",
      "title": "triangleIndices",
      "type": "topic",
      "url": "/documentation/arkit/arfacegeometry/triangleindices-8isy8"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFaceGeometry/vertices-7qq1y": {
      "abstract": [
        {
          "text": "An array of vertex positions for each point in the face mesh.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vertices"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float3",
          "text": "simd_float3"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceGeometry/vertices-7qq1y",
      "kind": "symbol",
      "role": "symbol",
      "title": "vertices",
      "type": "topic",
      "url": "/documentation/arkit/arfacegeometry/vertices-7qq1y"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARFaceGeometry/vertices-fhdb": {
      "abstract": [
        {
          "text": "A buffer of vertex positions for each point in the face mesh.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vertices"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARFaceGeometry/vertices-fhdb",
      "kind": "symbol",
      "role": "symbol",
      "title": "vertices",
      "type": "topic",
      "url": "/documentation/arkit/arfacegeometry/vertices-fhdb"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@vector_float2": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vector_float2"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_float2",
          "text": "simd_float2"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@vector_float2",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_float2",
      "type": "topic",
      "url": "/documentation/simd/vector_float2"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Mesh-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARFaceGeometry/vertices-7qq1y",
        "doc://com.apple.arkit/documentation/ARKit/ARFaceGeometry/triangleCount",
        "doc://com.apple.arkit/documentation/ARKit/ARFaceGeometry/triangleIndices-8isy8"
      ],
      "title": "Accessing Mesh Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceGeometry/title",
          "value": "ARFaceGeometry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceGeometry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARFaceGeometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceGeometry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARFaceGeometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceGeometry~1triangleCount/title",
          "value": "triangleCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARFaceGeometry~1triangleCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "triangleCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@vector_float2/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@simd_float2",
              "text": "simd_float2"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vector_float2"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/arfacegeometry/texturecoordinates-u42d"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
