{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/audiotoolbox/audiobalancefadetype/init(rawvalue:)"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.audiotoolbox/documentation/AudioToolbox","doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBalanceFadeType"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt32V","text":"UInt32","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:s6UInt32V"},{"text":")","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"Audio Toolbox"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","roleHeading":"Initializer","symbolKind":"init","title":"init(rawValue:)","platforms":[{"name":"iOS","unavailable":false,"beta":false,"deprecated":false},{"name":"iPadOS","unavailable":false,"beta":false,"deprecated":false},{"name":"Mac Catalyst","unavailable":false,"beta":false,"deprecated":false},{"name":"macOS","unavailable":false,"beta":false,"deprecated":false},{"name":"tvOS","unavailable":false,"beta":false,"deprecated":false},{"name":"visionOS","deprecated":false,"unavailable":false,"beta":false}],"externalID":"s:So20AudioBalanceFadeTypeV8rawValueABSgs6UInt32V_tcfc"},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBalanceFadeType/init(rawValue:)"},"references":{"doc://com.externally.resolved.symbol/s:s6UInt32V":{"title":"UInt32","role":"symbol","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:s6UInt32V","abstract":[{"type":"text","text":"A 32-bit unsigned integer value type."}],"kind":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UInt32","kind":"identifier"}],"url":"/documentation/Swift/UInt32"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox":{"type":"topic","kind":"symbol","title":"Audio Toolbox","role":"collection","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox","abstract":[{"text":"Record or play audio, convert formats, parse audio streams, and configure your audio session.","type":"text"}],"url":"/documentation/audiotoolbox"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBalanceFadeType":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBalanceFadeType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioBalanceFadeType"}],"abstract":[{"type":"text","text":"Identifiers for audio balance fade types."}],"url":"/documentation/audiotoolbox/audiobalancefadetype","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AudioBalanceFadeType"}],"title":"AudioBalanceFadeType"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","type":"topic","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","role":"overview"},"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBalanceFadeType/init(rawValue:)":{"kind":"symbol","url":"/documentation/audiotoolbox/audiobalancefadetype/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt32V","text":"UInt32","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","title":"init(rawValue:)","identifier":"doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioBalanceFadeType/init(rawValue:)","abstract":[],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"AudioBalanceFadeType","path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioBalanceFadeType/title","op":"replace"},{"value":[{"kind":"identifier","text":"AudioBalanceFadeType"}],"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioBalanceFadeType/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AudioBalanceFadeType"}],"path":"/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioBalanceFadeType/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}