{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nscell/calcdrawinfo(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nscell/calcdrawinfo(_:)"]}],"metadata":{"platforms":[{"beta":false,"deprecated":false,"unavailable":false,"name":"macOS"}],"role":"symbol","externalID":"c:objc(cs)NSCell(im)calcDrawInfo:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"calcDrawInfo","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSRect","text":"NSRect","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"calcDrawInfo:","kind":"identifier"}],"title":"calcDrawInfo(_:)","modules":[{"name":"AppKit"}],"symbolKind":"method","roleHeading":"Instance Method"},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCell"]]},"abstract":[{"type":"text","text":"Recalculates the cell geometry."}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calcDrawInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"rect","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect","identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The reference rectangle to use when calculating the cell information.","type":"text"}]}],"name":"rect"}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Objects (such as controls) that manage ","type":"text"},{"type":"codeVoice","code":"NSCell"},{"text":" objects generally maintain a flag that informs them if any of their cells have been modified in such a way that the location or size of the cell should be recomputed. If so, ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl/calcSize()","isActive":true,"type":"reference"},{"text":" method of ","type":"text"},{"type":"codeVoice","code":"NSControl"},{"text":" is automatically invoked prior to the display of the cell, and that method invokes the ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/calcDrawInfo(_:)","isActive":true,"type":"reference"},{"text":" method of the cell.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The default implementation of this method does nothing.","type":"text"}]}]}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSCell/calcDrawInfo(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"title":"Determining Cell Size","anchor":"Determining-Cell-Size","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize","doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize(forBounds:)","doc://com.apple.appkit/documentation/AppKit/NSCell/drawingRect(forBounds:)","doc://com.apple.appkit/documentation/AppKit/NSCell/imageRect(forBounds:)","doc://com.apple.appkit/documentation/AppKit/NSCell/titleRect(forBounds:)","doc://com.apple.appkit/documentation/AppKit/NSCell/controlSize"]}],"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSCell/titleRect(forBounds:)":{"type":"topic","abstract":[{"type":"text","text":"Returns the rectangle in which the receiver draws its title text."}],"title":"titleRect(forBounds:)","kind":"symbol","navigatorTitle":[{"text":"titleRectForBounds:","kind":"identifier"}],"url":"/documentation/appkit/nscell/titlerect(forbounds:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleRect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect"},{"text":") -> ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/titleRect(forBounds:)"},"doc://com.apple.appkit/documentation/AppKit/NSCell/controlSize":{"title":"controlSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"controlSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSControl","preciseIdentifier":"c:objc(cs)NSControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ControlSize","preciseIdentifier":"c:@E@NSControlSize"}],"kind":"symbol","abstract":[{"text":"The size of the cell.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/appkit/nscell/controlsize","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/controlSize","navigatorTitle":[{"kind":"identifier","text":"controlSize"}]},"doc://com.apple.appkit/documentation/AppKit/NSCell/imageRect(forBounds:)":{"type":"topic","abstract":[{"type":"text","text":"Returns the rectangle in which the receiver draws its image."}],"title":"imageRect(forBounds:)","url":"/documentation/appkit/nscell/imagerect(forbounds:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageRect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect"},{"text":") -> ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"imageRectForBounds:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/imageRect(forBounds:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSCell":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell","abstract":[{"type":"text","text":"A mechanism for displaying text or images in a view object without the overhead of a full "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView"},{"type":"text","text":" subclass."}],"role":"symbol","navigatorTitle":[{"text":"NSCell","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCell","kind":"identifier"}],"title":"NSCell","kind":"symbol","url":"/documentation/appkit/nscell","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize":{"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cellSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSSize","text":"NSSize","kind":"typeIdentifier"}],"url":"/documentation/appkit/nscell/cellsize","title":"cellSize","navigatorTitle":[{"text":"cellSize","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize","abstract":[{"type":"text","text":"The minimum size needed to display the cell."}]},"doc://com.apple.appkit/documentation/AppKit/NSCell/calcDrawInfo(_:)":{"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calcDrawInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect"},{"text":")","kind":"text"}],"url":"/documentation/appkit/nscell/calcdrawinfo(_:)","title":"calcDrawInfo(_:)","navigatorTitle":[{"text":"calcDrawInfo:","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/calcDrawInfo(_:)","abstract":[{"type":"text","text":"Recalculates the cell geometry."}]},"doc://com.apple.appkit/documentation/AppKit/NSControl/calcSize()":{"url":"/documentation/appkit/nscontrol/calcsize()","kind":"symbol","deprecated":true,"navigatorTitle":[{"text":"calcSize","kind":"identifier"}],"role":"symbol","type":"topic","title":"calcSize()","abstract":[{"text":"Recomputes any internal sizing information for the receiver, if necessary.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"calcSize"},{"text":"()","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl/calcSize()"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSView":{"abstract":[{"text":"The infrastructure for drawing, printing, and handling events in an app.","type":"text"}],"url":"/documentation/appkit/nsview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSView"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView","title":"NSView","navigatorTitle":[{"kind":"identifier","text":"NSView"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize(forBounds:)":{"type":"topic","abstract":[{"type":"text","text":"Returns the minimum size needed to display the receiver, constraining it to the specified rectangle."}],"title":"cellSize(forBounds:)","url":"/documentation/appkit/nscell/cellsize(forbounds:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cellSize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSSize","preciseIdentifier":"c:@T@NSSize","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"cellSizeForBounds:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize(forBounds:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSCell/drawingRect(forBounds:)":{"type":"topic","abstract":[{"type":"text","text":"Returns the rectangle within which the receiver draws itself"}],"title":"drawingRect(forBounds:)","kind":"symbol","navigatorTitle":[{"text":"drawingRectForBounds:","kind":"identifier"}],"url":"/documentation/appkit/nscell/drawingrect(forbounds:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"drawingRect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect"},{"text":") -> ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/drawingRect(forBounds:)"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.externally.resolved.symbol/c:@T@NSRect":{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","role":"symbol","type":"topic","url":"/documentation/foundation/nsrect","abstract":[{"text":"A rectangle.","type":"text"}],"fragments":[{"text":"typealias ","kind":"text"},{"text":"NSRect","kind":"identifier"}],"title":"NSRect","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"deprecated":false,"name":"macOS","beta":false,"unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"calcDrawInfo:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"calcDrawInfo:"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCell"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize","doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize(forBounds:)","doc://com.apple.appkit/documentation/AppKit/NSCell/drawingRect(forBounds:)","doc://com.apple.appkit/documentation/AppKit/NSCell/imageRect(forBounds:)","doc://com.apple.appkit/documentation/AppKit/NSCell/titleRect(forBounds:)","doc://com.apple.appkit/documentation/AppKit/NSCell/controlSize"],"generated":true,"anchor":"Determining-Cell-Size","title":"Determining Cell Size"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"calcDrawInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect","identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect"},{"text":") ","kind":"text"},{"text":"rect","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"},"op":"replace"},{"path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"name":"rect","content":[{"inlineContent":[{"type":"text","text":"The reference rectangle to use when calculating the cell information."}],"type":"paragraph"}]}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1titleRect(forBounds:)/title","value":"titleRectForBounds:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1titleRect(forBounds:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"titleRectForBounds:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1controlSize/title","value":"controlSize","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1controlSize/fragments","value":[{"kind":"identifier","text":"controlSize"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1imageRect(forBounds:)/title","value":"imageRectForBounds:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1imageRect(forBounds:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"imageRectForBounds:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/title","value":"NSCell","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/fragments","value":[{"kind":"identifier","text":"NSCell"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/navigatorTitle","value":[{"kind":"identifier","text":"NSCell"}],"op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1cellSize/title","value":"cellSize"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1cellSize/fragments","value":[{"kind":"identifier","text":"cellSize"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1calcDrawInfo(_:)/title","value":"calcDrawInfo:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1calcDrawInfo(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"calcDrawInfo:"}]},{"op":"replace","value":"calcSize","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1calcSize()/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"calcSize"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1calcSize()/fragments"},{"op":"replace","value":"NSView","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSView"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments"},{"op":"replace","value":[{"text":"NSView","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle"},{"op":"replace","value":"cellSizeForBounds:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1cellSize(forBounds:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cellSizeForBounds:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1cellSize(forBounds:)/fragments"},{"op":"replace","value":"drawingRectForBounds:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1drawingRect(forBounds:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"drawingRectForBounds:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1drawingRect(forBounds:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}