{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Returns the minimum size needed to display the receiver, constraining it to the specified rectangle.","type":"text"}],"seeAlsoSections":[{"title":"Determining Cell Size","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCell/calcDrawInfo(_:)","doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize","doc://com.apple.appkit/documentation/AppKit/NSCell/drawingRect(forBounds:)","doc://com.apple.appkit/documentation/AppKit/NSCell/imageRect(forBounds:)","doc://com.apple.appkit/documentation/AppKit/NSCell/titleRect(forBounds:)","doc://com.apple.appkit/documentation/AppKit/NSCell/controlSize"],"generated":true,"anchor":"Determining-Cell-Size"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCell"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nscell/cellsize(forbounds:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nscell/cellsize(forbounds:)"]}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize(forBounds:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cellSize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forBounds","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"rect","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect","identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect"},{"text":") -> ","kind":"text"},{"text":"NSSize","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSSize","identifier":"doc://com.externally.resolved.symbol/c:@T@NSSize"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The size of the cell, or the size of the "},{"type":"codeVoice","code":"aRect"},{"type":"text","text":" parameter if the cell is not a text or image cell. If the cell is an image cell but no image has been set, returns "},{"type":"codeVoice","code":"NSZeroSize"},{"type":"text","text":"."}]}],"name":"rect"}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"Discussion"},{"inlineContent":[{"text":"This method takes into account of the size of the image or text within a certain offset determined by the border type of the cell. If the receiver is of text type, the text is resized to fit within ","type":"text"},{"code":"aRect","type":"codeVoice"},{"text":" (as much as ","type":"text"},{"code":"aRect","type":"codeVoice"},{"text":" is within the bounds of the cell).","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"To support constraint-based layout, when the content of a custom cell changes in such a way that the return value of this method would change, the cell needs to notify its control of the change by calling the control’s "},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl/invalidateIntrinsicContentSize(for:)","type":"reference"},{"type":"text","text":" method."}],"type":"paragraph"}]}],"metadata":{"modules":[{"name":"AppKit"}],"navigatorTitle":[{"kind":"identifier","text":"cellSizeForBounds:"}],"platforms":[{"deprecated":false,"name":"macOS","beta":false,"unavailable":false}],"title":"cellSize(forBounds:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellSize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forBounds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect","text":"NSRect"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSSize","text":"NSSize"}],"symbolKind":"method","externalID":"c:objc(cs)NSCell(im)cellSizeForBounds:","role":"symbol"},"references":{"doc://com.apple.appkit/documentation/AppKit/NSCell/calcDrawInfo(_:)":{"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calcDrawInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect"},{"text":")","kind":"text"}],"url":"/documentation/appkit/nscell/calcdrawinfo(_:)","title":"calcDrawInfo(_:)","navigatorTitle":[{"text":"calcDrawInfo:","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/calcDrawInfo(_:)","abstract":[{"type":"text","text":"Recalculates the cell geometry."}]},"doc://com.apple.appkit/documentation/AppKit/NSView":{"abstract":[{"text":"The infrastructure for drawing, printing, and handling events in an app.","type":"text"}],"url":"/documentation/appkit/nsview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSView"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView","title":"NSView","navigatorTitle":[{"kind":"identifier","text":"NSView"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSCell/titleRect(forBounds:)":{"type":"topic","abstract":[{"type":"text","text":"Returns the rectangle in which the receiver draws its title text."}],"title":"titleRect(forBounds:)","kind":"symbol","navigatorTitle":[{"text":"titleRectForBounds:","kind":"identifier"}],"url":"/documentation/appkit/nscell/titlerect(forbounds:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleRect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect"},{"text":") -> ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/titleRect(forBounds:)"},"doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize(forBounds:)":{"type":"topic","abstract":[{"type":"text","text":"Returns the minimum size needed to display the receiver, constraining it to the specified rectangle."}],"title":"cellSize(forBounds:)","url":"/documentation/appkit/nscell/cellsize(forbounds:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cellSize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSSize","preciseIdentifier":"c:@T@NSSize","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"cellSizeForBounds:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize(forBounds:)","kind":"symbol"},"doc://com.externally.resolved.symbol/c:@T@NSRect":{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","role":"symbol","type":"topic","url":"/documentation/foundation/nsrect","abstract":[{"text":"A rectangle.","type":"text"}],"fragments":[{"text":"typealias ","kind":"text"},{"text":"NSRect","kind":"identifier"}],"title":"NSRect","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSCell":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell","abstract":[{"type":"text","text":"A mechanism for displaying text or images in a view object without the overhead of a full "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView"},{"type":"text","text":" subclass."}],"role":"symbol","navigatorTitle":[{"text":"NSCell","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCell","kind":"identifier"}],"title":"NSCell","kind":"symbol","url":"/documentation/appkit/nscell","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.externally.resolved.symbol/c:@T@NSSize":{"abstract":[{"type":"text","text":"A two-dimensional size."}],"url":"/documentation/foundation/nssize","kind":"symbol","role":"symbol","title":"NSSize","identifier":"doc://com.externally.resolved.symbol/c:@T@NSSize","type":"topic","fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSSize"}]},"doc://com.apple.appkit/documentation/AppKit/NSCell/controlSize":{"title":"controlSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"controlSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSControl","preciseIdentifier":"c:objc(cs)NSControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ControlSize","preciseIdentifier":"c:@E@NSControlSize"}],"kind":"symbol","abstract":[{"text":"The size of the cell.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/appkit/nscell/controlsize","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/controlSize","navigatorTitle":[{"kind":"identifier","text":"controlSize"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSCell/imageRect(forBounds:)":{"type":"topic","abstract":[{"type":"text","text":"Returns the rectangle in which the receiver draws its image."}],"title":"imageRect(forBounds:)","url":"/documentation/appkit/nscell/imagerect(forbounds:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageRect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect"},{"text":") -> ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"imageRectForBounds:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/imageRect(forBounds:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSControl/invalidateIntrinsicContentSize(for:)":{"url":"/documentation/appkit/nscontrol/invalidateintrinsiccontentsize(for:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl/invalidateIntrinsicContentSize(for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidateIntrinsicContentSize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCell","text":"NSCell","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"invalidateIntrinsicContentSize(for:)","abstract":[{"text":"Notifies the control that the intrinsic content size for its cell is no longer valid.","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"invalidateIntrinsicContentSizeForCell:","kind":"identifier"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize":{"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cellSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSSize","text":"NSSize","kind":"typeIdentifier"}],"url":"/documentation/appkit/nscell/cellsize","title":"cellSize","navigatorTitle":[{"text":"cellSize","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize","abstract":[{"type":"text","text":"The minimum size needed to display the cell."}]},"doc://com.apple.appkit/documentation/AppKit/NSCell/drawingRect(forBounds:)":{"type":"topic","abstract":[{"type":"text","text":"Returns the rectangle within which the receiver draws itself"}],"title":"drawingRect(forBounds:)","kind":"symbol","navigatorTitle":[{"text":"drawingRectForBounds:","kind":"identifier"}],"url":"/documentation/appkit/nscell/drawingrect(forbounds:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"drawingRect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect"},{"text":") -> ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/drawingRect(forBounds:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"path":"/metadata/platforms","op":"replace","value":[{"deprecated":false,"name":"macOS","beta":false,"unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"cellSizeForBounds:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"cellSizeForBounds:","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCell"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCell/calcDrawInfo(_:)","doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize","doc://com.apple.appkit/documentation/AppKit/NSCell/drawingRect(forBounds:)","doc://com.apple.appkit/documentation/AppKit/NSCell/imageRect(forBounds:)","doc://com.apple.appkit/documentation/AppKit/NSCell/titleRect(forBounds:)","doc://com.apple.appkit/documentation/AppKit/NSCell/controlSize"],"title":"Determining Cell Size","anchor":"Determining-Cell-Size"}]},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSSize","preciseIdentifier":"c:@T@NSSize","text":"NSSize"},{"kind":"text","text":") "},{"kind":"identifier","text":"cellSizeForBounds:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","preciseIdentifier":"c:@T@NSRect","text":"NSRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"rect"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"op":"replace","path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"name":"rect","content":[{"inlineContent":[{"text":"The size of the cell, or the size of the ","type":"text"},{"type":"codeVoice","code":"aRect"},{"text":" parameter if the cell is not a text or image cell. If the cell is an image cell but no image has been set, returns ","type":"text"},{"type":"codeVoice","code":"NSZeroSize"},{"text":".","type":"text"}],"type":"paragraph"}]}]}},{"op":"replace","value":"calcDrawInfo:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1calcDrawInfo(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"calcDrawInfo:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1calcDrawInfo(_:)/fragments"},{"op":"replace","value":"NSView","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSView"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSView"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle"},{"op":"replace","value":"titleRectForBounds:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1titleRect(forBounds:)/title"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1titleRect(forBounds:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"titleRectForBounds:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1cellSize(forBounds:)/title","value":"cellSizeForBounds:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1cellSize(forBounds:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"cellSizeForBounds:","kind":"identifier"}]},{"value":"NSCell","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSCell"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSCell"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/navigatorTitle","op":"replace"},{"value":"controlSize","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1controlSize/title","op":"replace"},{"value":[{"kind":"identifier","text":"controlSize"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1controlSize/fragments","op":"replace"},{"value":"imageRectForBounds:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1imageRect(forBounds:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"imageRectForBounds:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1imageRect(forBounds:)/fragments","op":"replace"},{"value":"invalidateIntrinsicContentSizeForCell:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1invalidateIntrinsicContentSize(for:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"invalidateIntrinsicContentSizeForCell:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1invalidateIntrinsicContentSize(for:)/fragments","op":"replace"},{"value":"cellSize","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1cellSize/title","op":"replace"},{"value":[{"kind":"identifier","text":"cellSize"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1cellSize/fragments","op":"replace"},{"value":"drawingRectForBounds:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1drawingRect(forBounds:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"drawingRectForBounds:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1drawingRect(forBounds:)/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}