{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nscell/cellsize"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nscell/cellsize"]}],"abstract":[{"type":"text","text":"The minimum size needed to display the cell."}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cellSize","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSSize","text":"NSSize","preciseIdentifier":"c:@T@NSSize","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"Discussion"},{"inlineContent":[{"text":"This property contains the smallest cell size (in points) required to draw its contents. If the cell is not a text or image cell, the cell size is set to (","type":"text"},{"type":"codeVoice","code":"10000"},{"text":", ","type":"text"},{"type":"codeVoice","code":"10000"},{"type":"text","text":"). If an image cell does not yet have an associated image, the cell size is "},{"identifier":"doc://com.apple.documentation/documentation/foundation/nszerosize","type":"reference","isActive":true},{"type":"text","text":".This method takes into account of the size of the image or text in the cell along with any margin areas required by the cell’s border, if any."}],"type":"paragraph"}]}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCell"]]},"metadata":{"platforms":[{"beta":false,"unavailable":false,"deprecated":false,"name":"macOS"}],"title":"cellSize","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"cellSize"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellSize"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSSize","kind":"typeIdentifier","text":"NSSize"}],"modules":[{"name":"AppKit"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:objc(cs)NSCell(py)cellSize"},"seeAlsoSections":[{"title":"Determining Cell Size","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCell/calcDrawInfo(_:)","doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize(forBounds:)","doc://com.apple.appkit/documentation/AppKit/NSCell/drawingRect(forBounds:)","doc://com.apple.appkit/documentation/AppKit/NSCell/imageRect(forBounds:)","doc://com.apple.appkit/documentation/AppKit/NSCell/titleRect(forBounds:)","doc://com.apple.appkit/documentation/AppKit/NSCell/controlSize"],"generated":true,"anchor":"Determining-Cell-Size"}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize(forBounds:)":{"type":"topic","abstract":[{"type":"text","text":"Returns the minimum size needed to display the receiver, constraining it to the specified rectangle."}],"title":"cellSize(forBounds:)","url":"/documentation/appkit/nscell/cellsize(forbounds:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cellSize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSSize","preciseIdentifier":"c:@T@NSSize","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"cellSizeForBounds:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize(forBounds:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSView":{"abstract":[{"text":"The infrastructure for drawing, printing, and handling events in an app.","type":"text"}],"url":"/documentation/appkit/nsview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSView"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView","title":"NSView","navigatorTitle":[{"kind":"identifier","text":"NSView"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSCell/titleRect(forBounds:)":{"type":"topic","abstract":[{"type":"text","text":"Returns the rectangle in which the receiver draws its title text."}],"title":"titleRect(forBounds:)","kind":"symbol","navigatorTitle":[{"text":"titleRectForBounds:","kind":"identifier"}],"url":"/documentation/appkit/nscell/titlerect(forbounds:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleRect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect"},{"text":") -> ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/titleRect(forBounds:)"},"doc://com.apple.appkit/documentation/AppKit/NSCell/calcDrawInfo(_:)":{"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calcDrawInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect"},{"text":")","kind":"text"}],"url":"/documentation/appkit/nscell/calcdrawinfo(_:)","title":"calcDrawInfo(_:)","navigatorTitle":[{"text":"calcDrawInfo:","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/calcDrawInfo(_:)","abstract":[{"type":"text","text":"Recalculates the cell geometry."}]},"doc://com.apple.appkit/documentation/AppKit/NSCell/drawingRect(forBounds:)":{"type":"topic","abstract":[{"type":"text","text":"Returns the rectangle within which the receiver draws itself"}],"title":"drawingRect(forBounds:)","kind":"symbol","navigatorTitle":[{"text":"drawingRectForBounds:","kind":"identifier"}],"url":"/documentation/appkit/nscell/drawingrect(forbounds:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"drawingRect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect"},{"text":") -> ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/drawingRect(forBounds:)"},"doc://com.apple.appkit/documentation/AppKit/NSCell":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell","abstract":[{"type":"text","text":"A mechanism for displaying text or images in a view object without the overhead of a full "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView"},{"type":"text","text":" subclass."}],"role":"symbol","navigatorTitle":[{"text":"NSCell","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCell","kind":"identifier"}],"title":"NSCell","kind":"symbol","url":"/documentation/appkit/nscell","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCell/controlSize":{"title":"controlSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"controlSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSControl","preciseIdentifier":"c:objc(cs)NSControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ControlSize","preciseIdentifier":"c:@E@NSControlSize"}],"kind":"symbol","abstract":[{"text":"The size of the cell.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/appkit/nscell/controlsize","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/controlSize","navigatorTitle":[{"kind":"identifier","text":"controlSize"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize":{"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cellSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSSize","text":"NSSize","kind":"typeIdentifier"}],"url":"/documentation/appkit/nscell/cellsize","title":"cellSize","navigatorTitle":[{"text":"cellSize","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize","abstract":[{"type":"text","text":"The minimum size needed to display the cell."}]},"doc://com.apple.documentation/documentation/foundation/nszerosize":{"role":"symbol","type":"topic","identifier":"doc://com.apple.documentation/documentation/foundation/nszerosize","fragments":[{"text":"let ","kind":"text"},{"text":"NSZeroSize","kind":"identifier"},{"text":": NSSize","kind":"text"}],"kind":"symbol","url":"/documentation/foundation/nszerosize","abstract":[{"text":"An `NSSize` structure set to `0` in both dimensions.","type":"text"}],"title":"NSZeroSize"},"doc://com.apple.appkit/documentation/AppKit/NSCell/imageRect(forBounds:)":{"type":"topic","abstract":[{"type":"text","text":"Returns the rectangle in which the receiver draws its image."}],"title":"imageRect(forBounds:)","url":"/documentation/appkit/nscell/imagerect(forbounds:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageRect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect"},{"text":") -> ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"imageRectForBounds:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/imageRect(forBounds:)","kind":"symbol"},"doc://com.externally.resolved.symbol/c:@T@NSSize":{"abstract":[{"type":"text","text":"A two-dimensional size."}],"url":"/documentation/foundation/nssize","kind":"symbol","role":"symbol","title":"NSSize","identifier":"doc://com.externally.resolved.symbol/c:@T@NSSize","type":"topic","fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSSize"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"name":"macOS","deprecated":false,"unavailable":false,"beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"cellSize","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"cellSize","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCell"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCell/calcDrawInfo(_:)","doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize(forBounds:)","doc://com.apple.appkit/documentation/AppKit/NSCell/drawingRect(forBounds:)","doc://com.apple.appkit/documentation/AppKit/NSCell/imageRect(forBounds:)","doc://com.apple.appkit/documentation/AppKit/NSCell/titleRect(forBounds:)","doc://com.apple.appkit/documentation/AppKit/NSCell/controlSize"],"title":"Determining Cell Size","anchor":"Determining-Cell-Size"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSSize","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSSize","preciseIdentifier":"c:@T@NSSize"},{"text":" ","kind":"text"},{"text":"cellSize","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"]}]},"op":"replace","path":"/primaryContentSections/0"},{"value":"cellSizeForBounds:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1cellSize(forBounds:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"cellSizeForBounds:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1cellSize(forBounds:)/fragments","op":"replace"},{"value":"NSView","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSView"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments","op":"replace"},{"value":[{"text":"NSView","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle","op":"replace"},{"value":"titleRectForBounds:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1titleRect(forBounds:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"titleRectForBounds:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1titleRect(forBounds:)/fragments","op":"replace"},{"value":"calcDrawInfo:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1calcDrawInfo(_:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"calcDrawInfo:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1calcDrawInfo(_:)/fragments","op":"replace"},{"value":"drawingRectForBounds:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1drawingRect(forBounds:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"drawingRectForBounds:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1drawingRect(forBounds:)/fragments"},{"value":"NSCell","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/title"},{"value":[{"text":"NSCell","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/fragments"},{"value":[{"kind":"identifier","text":"NSCell"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/navigatorTitle"},{"value":"controlSize","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1controlSize/title"},{"value":[{"text":"controlSize","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1controlSize/fragments"},{"value":"cellSize","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1cellSize/title"},{"value":[{"text":"cellSize","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1cellSize/fragments"},{"value":"imageRectForBounds:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1imageRect(forBounds:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"imageRectForBounds:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1imageRect(forBounds:)/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}