{"variants":[{"paths":["/documentation/appkit/nscell/controlsize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nscell/controlsize"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","title":"controlSize","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"controlSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSControl","preciseIdentifier":"c:objc(cs)NSControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"ControlSize","preciseIdentifier":"c:@E@NSControlSize","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"controlSize","kind":"identifier"}],"modules":[{"name":"AppKit"}],"role":"symbol","externalID":"c:objc(cs)NSCell(py)controlSize","platforms":[{"deprecated":false,"unavailable":false,"name":"macOS","beta":false}]},"abstract":[{"type":"text","text":"The size of the cell."}],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCell/calcDrawInfo(_:)","doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize","doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize(forBounds:)","doc://com.apple.appkit/documentation/AppKit/NSCell/drawingRect(forBounds:)","doc://com.apple.appkit/documentation/AppKit/NSCell/imageRect(forBounds:)","doc://com.apple.appkit/documentation/AppKit/NSCell/titleRect(forBounds:)"],"anchor":"Determining-Cell-Size","generated":true,"title":"Determining Cell Size"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"controlSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSControl","preciseIdentifier":"c:objc(cs)NSControl","identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"ControlSize","preciseIdentifier":"c:@E@NSControlSize","identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl/ControlSize-swift.enum","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Use this property to change the rendered size of the cell and its control. For a list of possible values, see ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl/ControlSize-swift.enum","isActive":true,"type":"reference"},{"text":".","type":"text"}]},{"inlineContent":[{"type":"text","text":"Changing the cell’s control size does not change the font used by the cell. Use the "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSFont/systemFontSize(for:)","isActive":true},{"type":"text","text":" class method of "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSFont","isActive":true},{"type":"text","text":" to obtain an appropriate font based on the new control size."}],"type":"paragraph"}]}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCell"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSCell/controlSize"},"references":{"doc://com.apple.appkit/documentation/AppKit/NSView":{"abstract":[{"text":"The infrastructure for drawing, printing, and handling events in an app.","type":"text"}],"url":"/documentation/appkit/nsview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSView"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView","title":"NSView","navigatorTitle":[{"kind":"identifier","text":"NSView"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSCell":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell","abstract":[{"type":"text","text":"A mechanism for displaying text or images in a view object without the overhead of a full "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView"},{"type":"text","text":" subclass."}],"role":"symbol","navigatorTitle":[{"text":"NSCell","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCell","kind":"identifier"}],"title":"NSCell","kind":"symbol","url":"/documentation/appkit/nscell","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSControl":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl","navigatorTitle":[{"kind":"identifier","text":"NSControl"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSControl"}],"title":"NSControl","role":"symbol","abstract":[{"text":"A specialized view, such as a button or text field, that notifies your app of relevant events using the target-action design pattern.","type":"text"}],"kind":"symbol","type":"topic","url":"/documentation/appkit/nscontrol"},"doc://com.apple.appkit/documentation/AppKit/NSFont":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSFont"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSFont"}],"url":"/documentation/appkit/nsfont","identifier":"doc://com.apple.appkit/documentation/AppKit/NSFont","title":"NSFont","abstract":[{"text":"The representation of a font in an app.","type":"text"}],"kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize(forBounds:)":{"type":"topic","abstract":[{"type":"text","text":"Returns the minimum size needed to display the receiver, constraining it to the specified rectangle."}],"title":"cellSize(forBounds:)","url":"/documentation/appkit/nscell/cellsize(forbounds:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cellSize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSSize","preciseIdentifier":"c:@T@NSSize","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"cellSizeForBounds:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize(forBounds:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSCell/calcDrawInfo(_:)":{"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calcDrawInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect"},{"text":")","kind":"text"}],"url":"/documentation/appkit/nscell/calcdrawinfo(_:)","title":"calcDrawInfo(_:)","navigatorTitle":[{"text":"calcDrawInfo:","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/calcDrawInfo(_:)","abstract":[{"type":"text","text":"Recalculates the cell geometry."}]},"doc://com.apple.appkit/documentation/AppKit/NSControl/ControlSize-swift.enum":{"kind":"symbol","url":"/documentation/appkit/nscontrol/controlsize-swift.enum","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ControlSize"}],"abstract":[{"type":"text","text":"A constant for specifying a cell’s size."}],"title":"NSControl.ControlSize","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ControlSize"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl/ControlSize-swift.enum","type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSFont/systemFontSize(for:)":{"abstract":[{"type":"text","text":"Returns the font size used for the specified control size."}],"title":"systemFontSize(for:)","navigatorTitle":[{"text":"systemFontSizeForControlSize:","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"systemFontSize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSControl","preciseIdentifier":"c:objc(cs)NSControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"ControlSize","preciseIdentifier":"c:@E@NSControlSize","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSFont/systemFontSize(for:)","url":"/documentation/appkit/nsfont/systemfontsize(for:)","role":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCell/drawingRect(forBounds:)":{"type":"topic","abstract":[{"type":"text","text":"Returns the rectangle within which the receiver draws itself"}],"title":"drawingRect(forBounds:)","kind":"symbol","navigatorTitle":[{"text":"drawingRectForBounds:","kind":"identifier"}],"url":"/documentation/appkit/nscell/drawingrect(forbounds:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"drawingRect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect"},{"text":") -> ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/drawingRect(forBounds:)"},"doc://com.apple.appkit/documentation/AppKit/NSCell/titleRect(forBounds:)":{"type":"topic","abstract":[{"type":"text","text":"Returns the rectangle in which the receiver draws its title text."}],"title":"titleRect(forBounds:)","kind":"symbol","navigatorTitle":[{"text":"titleRectForBounds:","kind":"identifier"}],"url":"/documentation/appkit/nscell/titlerect(forbounds:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleRect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect"},{"text":") -> ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/titleRect(forBounds:)"},"doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize":{"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cellSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSSize","text":"NSSize","kind":"typeIdentifier"}],"url":"/documentation/appkit/nscell/cellsize","title":"cellSize","navigatorTitle":[{"text":"cellSize","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize","abstract":[{"type":"text","text":"The minimum size needed to display the cell."}]},"doc://com.apple.appkit/documentation/AppKit/NSCell/controlSize":{"title":"controlSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"controlSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSControl","preciseIdentifier":"c:objc(cs)NSControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ControlSize","preciseIdentifier":"c:@E@NSControlSize"}],"kind":"symbol","abstract":[{"text":"The size of the cell.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/appkit/nscell/controlsize","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/controlSize","navigatorTitle":[{"kind":"identifier","text":"controlSize"}]},"doc://com.apple.appkit/documentation/AppKit/NSCell/imageRect(forBounds:)":{"type":"topic","abstract":[{"type":"text","text":"Returns the rectangle in which the receiver draws its image."}],"title":"imageRect(forBounds:)","url":"/documentation/appkit/nscell/imagerect(forbounds:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageRect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect"},{"text":") -> ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"imageRectForBounds:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/imageRect(forBounds:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"beta":false,"unavailable":false,"name":"macOS"}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Property","path":"/metadata/roleHeading","op":"replace"},{"value":"controlSize","path":"/metadata/title","op":"replace"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"controlSize"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCell"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"generated":true,"title":"Determining Cell Size","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCell/calcDrawInfo(_:)","doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize","doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize(forBounds:)","doc://com.apple.appkit/documentation/AppKit/NSCell/drawingRect(forBounds:)","doc://com.apple.appkit/documentation/AppKit/NSCell/imageRect(forBounds:)","doc://com.apple.appkit/documentation/AppKit/NSCell/titleRect(forBounds:)"],"anchor":"Determining-Cell-Size"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSControlSize","preciseIdentifier":"c:@E@NSControlSize","identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl/ControlSize-swift.enum","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"controlSize","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}]},"path":"/primaryContentSections/0","op":"replace"},{"value":"NSView","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments","value":[{"text":"NSView","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle","value":[{"text":"NSView","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/title","value":"NSCell","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/fragments","value":[{"text":"NSCell","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/navigatorTitle","value":[{"kind":"identifier","text":"NSCell"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl/title","op":"replace","value":"NSControl"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl/fragments","op":"replace","value":[{"kind":"identifier","text":"NSControl"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSControl"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/title","op":"replace","value":"NSFont"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/fragments","value":[{"text":"NSFont","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/navigatorTitle","value":[{"text":"NSFont","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1cellSize(forBounds:)/title","value":"cellSizeForBounds:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1cellSize(forBounds:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cellSizeForBounds:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1calcDrawInfo(_:)/title","value":"calcDrawInfo:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1calcDrawInfo(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"calcDrawInfo:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1ControlSize-swift.enum/title","value":"NSControlSize","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1ControlSize-swift.enum/fragments","value":[{"kind":"identifier","text":"NSControlSize"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1ControlSize-swift.enum/navigatorTitle","value":[{"text":"NSControlSize","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1systemFontSize(for:)/title","value":"systemFontSizeForControlSize:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1systemFontSize(for:)/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"systemFontSizeForControlSize:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1drawingRect(forBounds:)/title","value":"drawingRectForBounds:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1drawingRect(forBounds:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"drawingRectForBounds:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1titleRect(forBounds:)/title","value":"titleRectForBounds:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1titleRect(forBounds:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"titleRectForBounds:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1cellSize/title","value":"cellSize","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1cellSize/fragments","value":[{"text":"cellSize","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1controlSize/title","value":"controlSize","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1controlSize/fragments","value":[{"kind":"identifier","text":"controlSize"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1imageRect(forBounds:)/title","value":"imageRectForBounds:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1imageRect(forBounds:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"imageRectForBounds:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}