{
  "abstract": [
    {
      "text": "Returns the position of the underlined mnemonic character in the receiver’s title.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Mnemonics are not used.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSCell"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSCell/mnemonicLocation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSCell(im)mnemonicLocation",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "mnemonicLocation"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "mnemonicLocation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.8",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "mnemonicLocation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "mnemonicLocation"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A zero-based index into the receiver’s title string indicating the position of the character. If there is no mnemonic character, this method returns ",
              "type": "text"
            },
            {
              "code": "NSNotFound",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Mnemonics are not supported in macOS.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell": {
      "abstract": [
        {
          "text": "A mechanism for displaying text or images in a view object without the overhead of a full ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " subclass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCell"
        }
      ],
      "role": "symbol",
      "title": "NSCell",
      "type": "topic",
      "url": "/documentation/appkit/nscell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell/entryType": {
      "abstract": [
        {
          "text": "Returns the type of data the user can type into the receiver.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "entryType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/entryType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "entryType"
        }
      ],
      "role": "symbol",
      "title": "entryType",
      "type": "topic",
      "url": "/documentation/appkit/nscell/entrytype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell/isEntryAcceptable:": {
      "abstract": [
        {
          "text": "Returns whether a string representing a numeric or date value is formatted in a suitable way for the cell’s entry type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "isEntryAcceptable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/isEntryAcceptable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isEntryAcceptable:"
        }
      ],
      "role": "symbol",
      "title": "isEntryAcceptable:",
      "type": "topic",
      "url": "/documentation/appkit/nscell/isentryacceptable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell/mnemonic": {
      "abstract": [
        {
          "text": "Returns the character in the receiver’s title that appears underlined for use as a mnemonic.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "mnemonic"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/mnemonic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mnemonic"
        }
      ],
      "role": "symbol",
      "title": "mnemonic",
      "type": "topic",
      "url": "/documentation/appkit/nscell/mnemonic"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell/mnemonicLocation": {
      "abstract": [
        {
          "text": "Returns the position of the underlined mnemonic character in the receiver’s title.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "mnemonicLocation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/mnemonicLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mnemonicLocation"
        }
      ],
      "role": "symbol",
      "title": "mnemonicLocation",
      "type": "topic",
      "url": "/documentation/appkit/nscell/mnemoniclocation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell/setEntryType:": {
      "abstract": [
        {
          "text": "Sets how numeric data is formatted in the receiver and places restrictions on acceptable input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setEntryType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/setEntryType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setEntryType:"
        }
      ],
      "role": "symbol",
      "title": "setEntryType:",
      "type": "topic",
      "url": "/documentation/appkit/nscell/setentrytype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell/setFloatingPointFormat:left:right:": {
      "abstract": [
        {
          "text": "Sets the auto-ranging and floating point number format of the receiver’s cell.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setFloatingPointFormat:left:right:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/setFloatingPointFormat:left:right:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFloatingPointFormat:left:right:"
        }
      ],
      "role": "symbol",
      "title": "setFloatingPointFormat:left:right:",
      "type": "topic",
      "url": "/documentation/appkit/nscell/setfloatingpointformat:left:right:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell/setMnemonicLocation:": {
      "abstract": [
        {
          "text": "Sets the character of the receiver’s title to be used as a mnemonic character.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setMnemonicLocation:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/setMnemonicLocation:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setMnemonicLocation:"
        }
      ],
      "role": "symbol",
      "title": "setMnemonicLocation:",
      "type": "topic",
      "url": "/documentation/appkit/nscell/setmnemoniclocation:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell/setTitleWithMnemonic:": {
      "abstract": [
        {
          "text": "Sets the title of the receiver with one character in the string denoted as an access key.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setTitleWithMnemonic:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/setTitleWithMnemonic:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTitleWithMnemonic:"
        }
      ],
      "role": "symbol",
      "title": "setTitleWithMnemonic:",
      "type": "topic",
      "url": "/documentation/appkit/nscell/settitlewithmnemonic:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/appkit/nsview"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCell/setEntryType:",
        "doc://com.apple.appkit/documentation/AppKit/NSCell/entryType",
        "doc://com.apple.appkit/documentation/AppKit/NSCell/isEntryAcceptable:",
        "doc://com.apple.appkit/documentation/AppKit/NSCell/setFloatingPointFormat:left:right:",
        "doc://com.apple.appkit/documentation/AppKit/NSCell/setTitleWithMnemonic:",
        "doc://com.apple.appkit/documentation/AppKit/NSCell/mnemonic",
        "doc://com.apple.appkit/documentation/AppKit/NSCell/setMnemonicLocation:"
      ],
      "title": "Deprecated Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title",
          "value": "NSView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/title",
          "value": "NSCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCell"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nscell/mnemoniclocation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
