{
  "abstract": [
    {
      "text": "Sets the auto-ranging and floating point number format of the receiver’s cell.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use a formatter instead. See ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/formatter",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSCell"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSCell/setFloatingPointFormat:left:right:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSCell(im)setFloatingPointFormat:left:right:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "setFloatingPointFormat:left:right:"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setFloatingPointFormat:left:right:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setFloatingPointFormat:left:right:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "setFloatingPointFormat:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "autoRange"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "left:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "leftDigits"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "right:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "rightDigits"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "If ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/swift/true",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", auto-ranging is enabled, otherwise it is disabled.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "autoRange"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of digits to display to the left of the decimal point.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "leftDigits"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of digits to display to the right of the decimal point.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "rightDigits"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Sets whether floating-point numbers are auto-ranged in the receiver and sets the sizes of the fields to the left and right of the decimal point. If ",
              "type": "text"
            },
            {
              "code": "autoRange",
              "type": "codeVoice"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "leftDigits",
              "type": "codeVoice"
            },
            {
              "text": " specifies the maximum number of digits to the left of the decimal point, and ",
              "type": "text"
            },
            {
              "code": "rightDigits",
              "type": "codeVoice"
            },
            {
              "text": " specifies the number of digits to the right (the fractional digit places will be padded with zeros to fill this width). However, if a number is too large to fit its integer part in ",
              "type": "text"
            },
            {
              "code": "leftDigits",
              "type": "codeVoice"
            },
            {
              "text": " digits, as many places as are needed on the left are effectively removed from ",
              "type": "text"
            },
            {
              "code": "rightDigits",
              "type": "codeVoice"
            },
            {
              "text": " when the number is displayed.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If ",
              "type": "text"
            },
            {
              "code": "autoRange",
              "type": "codeVoice"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "leftDigits",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "rightDigits",
              "type": "codeVoice"
            },
            {
              "text": " are simply added to form a maximum total field width for the receiver (plus 1 for the decimal point). The fractional part will be padded with zeros on the right to fill this width, or truncated as much as possible (up to removing the decimal point and displaying the number as an integer). The integer portion of a number is never truncated—that is, it is displayed in full no matter what the field width limit is.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following example sets a cell used to display dollar amounts up to 99,999.99:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "    [[currencyDollarsField cell] setEntryType:NSFloatType];",
            "    [[currencyDollarsField cell] setFloatingPointFormat:NO left:5  right:2];"
          ],
          "syntax": "objc",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell": {
      "abstract": [
        {
          "text": "A mechanism for displaying text or images in a view object without the overhead of a full ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " subclass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCell"
        }
      ],
      "role": "symbol",
      "title": "NSCell",
      "type": "topic",
      "url": "/documentation/appkit/nscell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell/entryType": {
      "abstract": [
        {
          "text": "Returns the type of data the user can type into the receiver.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "entryType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/entryType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "entryType"
        }
      ],
      "role": "symbol",
      "title": "entryType",
      "type": "topic",
      "url": "/documentation/appkit/nscell/entrytype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell/formatter": {
      "abstract": [
        {
          "text": "The cell’s formatter object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formatter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFormatter",
          "text": "Formatter"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/formatter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "formatter"
        }
      ],
      "role": "symbol",
      "title": "formatter",
      "type": "topic",
      "url": "/documentation/appkit/nscell/formatter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell/isEntryAcceptable:": {
      "abstract": [
        {
          "text": "Returns whether a string representing a numeric or date value is formatted in a suitable way for the cell’s entry type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "isEntryAcceptable:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/isEntryAcceptable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isEntryAcceptable:"
        }
      ],
      "role": "symbol",
      "title": "isEntryAcceptable:",
      "type": "topic",
      "url": "/documentation/appkit/nscell/isentryacceptable:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell/mnemonic": {
      "abstract": [
        {
          "text": "Returns the character in the receiver’s title that appears underlined for use as a mnemonic.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "mnemonic"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/mnemonic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mnemonic"
        }
      ],
      "role": "symbol",
      "title": "mnemonic",
      "type": "topic",
      "url": "/documentation/appkit/nscell/mnemonic"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell/mnemonicLocation": {
      "abstract": [
        {
          "text": "Returns the position of the underlined mnemonic character in the receiver’s title.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "mnemonicLocation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/mnemonicLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mnemonicLocation"
        }
      ],
      "role": "symbol",
      "title": "mnemonicLocation",
      "type": "topic",
      "url": "/documentation/appkit/nscell/mnemoniclocation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell/setEntryType:": {
      "abstract": [
        {
          "text": "Sets how numeric data is formatted in the receiver and places restrictions on acceptable input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setEntryType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/setEntryType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setEntryType:"
        }
      ],
      "role": "symbol",
      "title": "setEntryType:",
      "type": "topic",
      "url": "/documentation/appkit/nscell/setentrytype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell/setFloatingPointFormat:left:right:": {
      "abstract": [
        {
          "text": "Sets the auto-ranging and floating point number format of the receiver’s cell.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setFloatingPointFormat:left:right:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/setFloatingPointFormat:left:right:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFloatingPointFormat:left:right:"
        }
      ],
      "role": "symbol",
      "title": "setFloatingPointFormat:left:right:",
      "type": "topic",
      "url": "/documentation/appkit/nscell/setfloatingpointformat:left:right:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell/setMnemonicLocation:": {
      "abstract": [
        {
          "text": "Sets the character of the receiver’s title to be used as a mnemonic character.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setMnemonicLocation:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/setMnemonicLocation:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setMnemonicLocation:"
        }
      ],
      "role": "symbol",
      "title": "setMnemonicLocation:",
      "type": "topic",
      "url": "/documentation/appkit/nscell/setmnemoniclocation:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell/setTitleWithMnemonic:": {
      "abstract": [
        {
          "text": "Sets the title of the receiver with one character in the string denoted as an access key.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setTitleWithMnemonic:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/setTitleWithMnemonic:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTitleWithMnemonic:"
        }
      ],
      "role": "symbol",
      "title": "setTitleWithMnemonic:",
      "type": "topic",
      "url": "/documentation/appkit/nscell/settitlewithmnemonic:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/appkit/nsview"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCell/setEntryType:",
        "doc://com.apple.appkit/documentation/AppKit/NSCell/entryType",
        "doc://com.apple.appkit/documentation/AppKit/NSCell/isEntryAcceptable:",
        "doc://com.apple.appkit/documentation/AppKit/NSCell/setTitleWithMnemonic:",
        "doc://com.apple.appkit/documentation/AppKit/NSCell/mnemonic",
        "doc://com.apple.appkit/documentation/AppKit/NSCell/setMnemonicLocation:",
        "doc://com.apple.appkit/documentation/AppKit/NSCell/mnemonicLocation"
      ],
      "title": "Deprecated Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1formatter/title",
          "value": "formatter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1formatter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "formatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/title",
          "value": "NSCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title",
          "value": "NSView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nscell/setfloatingpointformat:left:right:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
