{
  "abstract": [
    {
      "text": "Attempted to start an invalid recording session.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.replaykit/documentation/ReplayKit",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/recordingInvalidSession"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@RPRecordingErrorCode@RPRecordingErrorRecordingInvalidSession",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "recordingInvalidSession"
      }
    ],
    "modules": [
      {
        "name": "ReplayKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "RPRecordingErrorRecordingInvalidSession"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "RPRecordingErrorCode.recordingInvalidSession"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "recordingInvalidSession"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit": {
      "abstract": [
        {
          "text": "Record or stream video from the screen, and audio from the app and microphone.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ReplayKit",
      "type": "topic",
      "url": "/documentation/replaykit"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode": {
      "abstract": [
        {
          "text": "The ReplayKit error domain codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPRecordingErrorCode"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorCode"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/activePhoneCall": {
      "abstract": [
        {
          "text": "Unable to record due to an active phone call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activePhoneCall"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/activePhoneCall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorActivePhoneCall"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.activePhoneCall",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/activephonecall"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/attemptToStartInRecordingState": {
      "abstract": [
        {
          "text": "Attempted to start a recording that’s already in a recording state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attemptToStartInRecordingState"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/attemptToStartInRecordingState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorAttemptToStartInRecordingState"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.attemptToStartInRecordingState",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/attempttostartinrecordingstate"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/attemptToStopNonRecording": {
      "abstract": [
        {
          "text": "Attempted to stop a recording that’s not in a recording state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attemptToStopNonRecording"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/attemptToStopNonRecording",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorAttemptToStopNonRecording"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.attemptToStopNonRecording",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/attempttostopnonrecording"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/broadcastInvalidSession": {
      "abstract": [
        {
          "text": "Attempted to start a broadcast without a prior session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "broadcastInvalidSession"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/broadcastInvalidSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorBroadcastInvalidSession"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.broadcastInvalidSession",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/broadcastinvalidsession"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/broadcastSetupFailed": {
      "abstract": [
        {
          "text": "The broadcast set up failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "broadcastSetupFailed"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/broadcastSetupFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorBroadcastSetupFailed"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.broadcastSetupFailed",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/broadcastsetupfailed"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/carPlay": {
      "abstract": [
        {
          "text": "Failed to start recording because CarPlay is active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "carPlay"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/carPlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorCarPlay"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.carPlay",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/carplay"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/codeSuccessful": {
      "abstract": [
        {
          "text": "Successfully saved the recording to the Camera Roll.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "codeSuccessful"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/codeSuccessful",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorCodeSuccessful"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.codeSuccessful",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/codesuccessful"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/contentResize": {
      "abstract": [
        {
          "text": "Recording interrupted by multitasking and content resizing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentResize"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/contentResize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorContentResize"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.contentResize",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/contentresize"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/disabled": {
      "abstract": [
        {
          "text": "Recording disabled via parental controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disabled"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/disabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorDisabled"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.disabled",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/disabled"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/entitlements": {
      "abstract": [
        {
          "text": "Recording failed due to missing entitlements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "entitlements"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/entitlements",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorEntitlements"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.entitlements",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/entitlements"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failed": {
      "abstract": [
        {
          "text": "Recording error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failed"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorFailed"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.failed",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/failed"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedApplicationConnectionInterrupted": {
      "abstract": [
        {
          "text": "The recording failed because the app’s connection was interrupted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedApplicationConnectionInterrupted"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedApplicationConnectionInterrupted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorFailedApplicationConnectionInterrupted"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.failedApplicationConnectionInterrupted",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/failedapplicationconnectioninterrupted"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedApplicationConnectionInvalid": {
      "abstract": [
        {
          "text": "The recording failed because the app’s connection is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedApplicationConnectionInvalid"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedApplicationConnectionInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorFailedApplicationConnectionInvalid"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.failedApplicationConnectionInvalid",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/failedapplicationconnectioninvalid"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedAssetWriterExportCanceled": {
      "abstract": [
        {
          "text": "The recording failed because the user canceled the export.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedAssetWriterExportCanceled"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedAssetWriterExportCanceled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorFailedAssetWriterExportCanceled"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.failedAssetWriterExportCanceled",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/failedassetwriterexportcanceled"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedAssetWriterExportFailed": {
      "abstract": [
        {
          "text": "The recording failed due to an error exporting the movie.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedAssetWriterExportFailed"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedAssetWriterExportFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorFailedAssetWriterExportFailed"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.failedAssetWriterExportFailed",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/failedassetwriterexportfailed"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/recordingInvalidSession": {
      "abstract": [
        {
          "text": "Attempted to start an invalid recording session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordingInvalidSession"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/recordingInvalidSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPRecordingErrorRecordingInvalidSession"
        }
      ],
      "role": "symbol",
      "title": "RPRecordingErrorCode.recordingInvalidSession",
      "type": "topic",
      "url": "/documentation/replaykit/rprecordingerrorcode/recordinginvalidsession"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/activePhoneCall",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/attemptToStartInRecordingState",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/attemptToStopNonRecording",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/broadcastInvalidSession",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/broadcastSetupFailed",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/carPlay",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/codeSuccessful",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/contentResize",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/disabled",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/entitlements",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failed",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedApplicationConnectionInterrupted",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedApplicationConnectionInvalid",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedAssetWriterExportCanceled",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedAssetWriterExportFailed"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "RPRecordingErrorRecordingInvalidSession"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorRecordingInvalidSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.replaykit/documentation/ReplayKit",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/activePhoneCall",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/attemptToStartInRecordingState",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/attemptToStopNonRecording",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/broadcastInvalidSession",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/broadcastSetupFailed",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/carPlay",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/codeSuccessful",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/contentResize",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/disabled",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/entitlements",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failed",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedApplicationConnectionInterrupted",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedApplicationConnectionInvalid",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedAssetWriterExportCanceled",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPRecordingErrorCode/failedAssetWriterExportFailed"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "RPRecordingErrorRecordingInvalidSession"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1contentResize/title",
          "value": "RPRecordingErrorContentResize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1contentResize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorContentResize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failed/title",
          "value": "RPRecordingErrorFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedAssetWriterExportFailed/title",
          "value": "RPRecordingErrorFailedAssetWriterExportFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedAssetWriterExportFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorFailedAssetWriterExportFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1activePhoneCall/title",
          "value": "RPRecordingErrorActivePhoneCall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1activePhoneCall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorActivePhoneCall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1codeSuccessful/title",
          "value": "RPRecordingErrorCodeSuccessful"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1codeSuccessful/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorCodeSuccessful"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1broadcastSetupFailed/title",
          "value": "RPRecordingErrorBroadcastSetupFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1broadcastSetupFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorBroadcastSetupFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1entitlements/title",
          "value": "RPRecordingErrorEntitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1entitlements/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorEntitlements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedApplicationConnectionInvalid/title",
          "value": "RPRecordingErrorFailedApplicationConnectionInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedApplicationConnectionInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorFailedApplicationConnectionInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1recordingInvalidSession/title",
          "value": "RPRecordingErrorRecordingInvalidSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1recordingInvalidSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorRecordingInvalidSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedAssetWriterExportCanceled/title",
          "value": "RPRecordingErrorFailedAssetWriterExportCanceled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedAssetWriterExportCanceled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorFailedAssetWriterExportCanceled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1attemptToStartInRecordingState/title",
          "value": "RPRecordingErrorAttemptToStartInRecordingState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1attemptToStartInRecordingState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorAttemptToStartInRecordingState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1broadcastInvalidSession/title",
          "value": "RPRecordingErrorBroadcastInvalidSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1broadcastInvalidSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorBroadcastInvalidSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1attemptToStopNonRecording/title",
          "value": "RPRecordingErrorAttemptToStopNonRecording"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1attemptToStopNonRecording/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorAttemptToStopNonRecording"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1disabled/title",
          "value": "RPRecordingErrorDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1disabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedApplicationConnectionInterrupted/title",
          "value": "RPRecordingErrorFailedApplicationConnectionInterrupted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1failedApplicationConnectionInterrupted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorFailedApplicationConnectionInterrupted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1carPlay/title",
          "value": "RPRecordingErrorCarPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode~1carPlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorCarPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode/title",
          "value": "RPRecordingErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPRecordingErrorCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPRecordingErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/replaykit/rprecordingerrorcode/recordinginvalidsession"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/replaykit/rprecordingerrorcode/recordinginvalidsession"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
