{
  "abstract": [
    {
      "text": "Removes text alternatives from the text input object for the current selection",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit",
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/removeTextAlternatives()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)BETextInput(im)removeTextAlternatives",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "removeTextAlternatives"
      },
      {
        "kind": "text",
        "text": "()"
      }
    ],
    "modules": [
      {
        "name": "BrowserEngineKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "removeTextAlternatives"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "removeTextAlternatives()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "removeTextAlternatives"
            },
            {
              "kind": "text",
              "text": "()"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/integrating-custom-browser-text-views-with-uikit"
      ]
    }
  ],
  "references": {
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit": {
      "abstract": [
        {
          "text": "Create a browser that renders content using an alternative browser engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit",
      "kind": "symbol",
      "role": "collection",
      "title": "BrowserEngineKit",
      "type": "topic",
      "url": "/documentation/browserenginekit"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput": {
      "abstract": [
        {
          "text": "A protocol to which text views conform to asynchronously integrate with the text system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BETextInput"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BETextInput"
        }
      ],
      "role": "symbol",
      "title": "BETextInput",
      "type": "topic",
      "url": "/documentation/browserenginekit/betextinput"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/removeTextAlternatives()": {
      "abstract": [
        {
          "text": "Removes text alternatives from the text input object for the current selection",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeTextAlternatives"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/removeTextAlternatives()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeTextAlternatives"
        }
      ],
      "role": "symbol",
      "title": "removeTextAlternatives()",
      "type": "topic",
      "url": "/documentation/browserenginekit/betextinput/removetextalternatives()"
    },
    "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/integrating-custom-browser-text-views-with-uikit": {
      "abstract": [
        {
          "text": "Process keyboard interactions asynchronously in your iOS browser app’s text view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/integrating-custom-browser-text-views-with-uikit",
      "kind": "article",
      "role": "article",
      "title": "Integrating custom browser text views with UIKit",
      "type": "topic",
      "url": "/documentation/browserenginekit/integrating-custom-browser-text-views-with-uikit"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "removeTextAlternatives"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeTextAlternatives"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit",
                "doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "removeTextAlternatives"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput/title",
          "value": "BETextInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BETextInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1removeTextAlternatives()/title",
          "value": "removeTextAlternatives"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1removeTextAlternatives()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeTextAlternatives"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/browserenginekit/betextinput/removetextalternatives()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/browserenginekit/betextinput/removetextalternatives()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
