{"seeAlsoSections":[{"generated":true,"anchor":"Selecting-text","title":"Selecting text","identifiers":["doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectedText","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectedTextRange","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/isSelectionAtDocumentStart","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/caretRect(for:)","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectWordForReplacement()","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/updateSelection(extent:boundary:completionHandler:)","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectText(in:at:completionHandler:)","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectPosition(at:completionHandler:)","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectPosition(at:for:completionHandler:)","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/adjustSelection(by:completionHandler:)","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/move(byOffset:)","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/moveSelection(atBoundary:in:completionHandler:)","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectTextForEditMenuWithLocation(inView:completionHandler:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput"]]},"identifier":{"url":"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectionRects(for:)","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"selectionRectsForRange:"}],"roleHeading":"Instance Method","modules":[{"name":"BrowserEngineKit"}],"platforms":[{"unavailable":false,"name":"iOS","introducedAt":"17.4","beta":false,"deprecated":false},{"unavailable":false,"name":"iPadOS","introducedAt":"17.4","beta":false,"deprecated":false},{"unavailable":false,"name":"tvOS","introducedAt":"17.4","beta":false,"deprecated":false},{"deprecated":false,"introducedAt":"1.1","unavailable":false,"beta":false,"name":"visionOS"}],"externalID":"c:objc(pl)BETextInput(im)selectionRectsForRange:","role":"symbol","title":"selectionRects(for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectionRects","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextRange","text":"UITextRange"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextSelectionRect","text":"UITextSelectionRect"},{"kind":"text","text":"]"}],"symbolKind":"method","required":true},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"selectionRects"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"range"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)UITextRange","text":"UITextRange","preciseIdentifier":"c:objc(cs)UITextRange"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)UITextSelectionRect","text":"UITextSelectionRect","preciseIdentifier":"c:objc(cs)UITextSelectionRect"},{"kind":"text","text":"]"}],"platforms":["iOS","tvOS","visionOS"]}],"kind":"declarations"},{"parameters":[{"name":"range","content":[{"type":"paragraph","inlineContent":[{"text":"The range of text for which to return selection rectangles.","type":"text"}]}]}],"kind":"parameters"},{"mentions":["doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/integrating-custom-browser-text-views-with-uikit"],"kind":"mentions"},{"content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Returns an array of selection rectangles corresponding to the given text range.","type":"text"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/browserenginekit/betextinput/selectionrects(for:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/browserenginekit/betextinput/selectionrects(for:)"]}],"abstract":[{"text":"Returns an array of selection rects corresponding to the range of text.","type":"text"}],"kind":"symbol","references":{"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/move(byOffset:)":{"identifier":"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/move(byOffset:)","navigatorTitle":[{"text":"moveByOffset:","kind":"identifier"}],"type":"topic","title":"move(byOffset:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"move","kind":"identifier"},{"text":"(","kind":"text"},{"text":"byOffset","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"url":"/documentation/browserenginekit/betextinput/move(byoffset:)","role":"symbol","abstract":[{"text":"Adjusts the current selection by ","type":"text"},{"code":"offset","type":"codeVoice"},{"text":" in character granularity units","type":"text"}],"required":true},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","url":"/documentation/technologies","title":"Technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","abstract":[{"text":"","type":"text"}]},"doc://com.externally.resolved.symbol/c:objc(cs)UITextRange":{"type":"topic","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)UITextRange","title":"UITextRange","role":"symbol","fragments":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITextRange","kind":"identifier"}],"abstract":[{"type":"text","text":"A range of characters in a text container with a starting index and an ending index in string backing a text-entry object."}],"url":"/documentation/UIKit/UITextRange","kind":"symbol"},"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectTextForEditMenuWithLocation(inView:completionHandler:)":{"identifier":"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectTextForEditMenuWithLocation(inView:completionHandler:)","required":true,"role":"symbol","title":"selectTextForEditMenuWithLocation(inView:completionHandler:)","type":"topic","url":"/documentation/browserenginekit/betextinput/selecttextforeditmenuwithlocation(inview:completionhandler:)","kind":"symbol","navigatorTitle":[{"text":"selectTextForEditMenuWithLocationInView:completionHandler:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectTextForEditMenuWithLocation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":", "},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"NSRange","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Indicates the edit menu is being shown at the given location in the text input view’s"},{"type":"text","text":" "},{"type":"text","text":"coordinate space."}]},"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/adjustSelection(by:completionHandler:)":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adjustSelection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"by"},{"text":": ","kind":"text"},{"text":"BEDirectionalTextRange","kind":"typeIdentifier","preciseIdentifier":"c:@SA@BEDirectionalTextRange"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"type":"topic","url":"/documentation/browserenginekit/betextinput/adjustselection(by:completionhandler:)","navigatorTitle":[{"text":"adjustSelectionByRange:completionHandler:","kind":"identifier"}],"identifier":"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/adjustSelection(by:completionHandler:)","title":"adjustSelection(by:completionHandler:)","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Adjusts the selection by the moving the selected range by the given "},{"type":"codeVoice","code":"range"},{"type":"text","text":", in character granularity units."}]},"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectWordForReplacement()":{"identifier":"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectWordForReplacement()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectWordForReplacement","kind":"identifier"},{"text":"()","kind":"text"}],"required":true,"kind":"symbol","role":"symbol","abstract":[{"text":"Selects a word with autocorrect replacement suggestions when it is tapped","type":"text"}],"navigatorTitle":[{"text":"selectWordForReplacement","kind":"identifier"}],"title":"selectWordForReplacement()","url":"/documentation/browserenginekit/betextinput/selectwordforreplacement()","type":"topic"},"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectedText":{"url":"/documentation/browserenginekit/betextinput/selectedtext","identifier":"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectedText","kind":"symbol","type":"topic","abstract":[{"text":"String representing the selected text.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"selectedText"}],"title":"selectedText","role":"symbol","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedText"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}]},"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectPosition(at:completionHandler:)":{"identifier":"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectPosition(at:completionHandler:)","navigatorTitle":[{"text":"selectPositionAtPoint:completionHandler:","kind":"identifier"}],"type":"topic","title":"selectPosition(at:completionHandler:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectPosition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"url":"/documentation/browserenginekit/betextinput/selectposition(at:completionhandler:)","role":"symbol","abstract":[{"text":"Sets the selection caret to the given point","type":"text"}],"required":true},"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectedTextRange":{"identifier":"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectedTextRange","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedTextRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextRange","preciseIdentifier":"c:objc(cs)UITextRange"},{"kind":"text","text":"?"}],"required":true,"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Range representing the selected text."}],"navigatorTitle":[{"kind":"identifier","text":"selectedTextRange"}],"title":"selectedTextRange","url":"/documentation/browserenginekit/betextinput/selectedtextrange","type":"topic"},"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/moveSelection(atBoundary:in:completionHandler:)":{"identifier":"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/moveSelection(atBoundary:in:completionHandler:)","required":true,"role":"symbol","title":"moveSelection(atBoundary:in:completionHandler:)","type":"topic","url":"/documentation/browserenginekit/betextinput/moveselection(atboundary:in:completionhandler:)","kind":"symbol","navigatorTitle":[{"text":"moveSelectionAtBoundary:inStorageDirection:completionHandler:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveSelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"atBoundary","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UITextGranularity","kind":"typeIdentifier","preciseIdentifier":"c:@E@UITextGranularity"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UITextStorageDirection","preciseIdentifier":"c:@E@UITextStorageDirection","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Moves the caret to relative to the current position in the ","type":"text"},{"code":"direction","type":"codeVoice"},{"text":" to the given ","type":"text"},{"code":"granularity","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"direction","type":"codeVoice"},{"type":"text","text":" is “forward” or “backward” in accordance with the directionality of the language."}]},"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput":{"url":"/documentation/browserenginekit/betextinput","identifier":"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput","kind":"symbol","type":"topic","abstract":[{"text":"A protocol to which text views conform to asynchronously integrate with the text system.","type":"text"}],"navigatorTitle":[{"text":"BETextInput","kind":"identifier"}],"title":"BETextInput","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BETextInput","kind":"identifier"}]},"doc://com.externally.resolved.symbol/c:objc(cs)UITextSelectionRect":{"type":"topic","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)UITextSelectionRect","title":"UITextSelectionRect","role":"symbol","fragments":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextSelectionRect"}],"abstract":[{"type":"text","text":"An encapsulation of information about a selected range of text in a document."}],"url":"/documentation/UIKit/UITextSelectionRect","kind":"symbol"},"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/updateSelection(extent:boundary:completionHandler:)":{"identifier":"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/updateSelection(extent:boundary:completionHandler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateSelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"extent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"text":"boundary","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UITextGranularity","kind":"typeIdentifier","preciseIdentifier":"c:@E@UITextGranularity"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"kind":"symbol","role":"symbol","abstract":[{"text":"Includes the text up to the given point in the current text selection.","type":"text"}],"navigatorTitle":[{"text":"updateSelectionWithExtentPoint:boundary:completionHandler:","kind":"identifier"}],"title":"updateSelection(extent:boundary:completionHandler:)","url":"/documentation/browserenginekit/betextinput/updateselection(extent:boundary:completionhandler:)","type":"topic"},"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/integrating-custom-browser-text-views-with-uikit":{"identifier":"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/integrating-custom-browser-text-views-with-uikit","type":"topic","title":"Integrating custom browser text views with UIKit","kind":"article","url":"/documentation/browserenginekit/integrating-custom-browser-text-views-with-uikit","role":"article","abstract":[{"text":"Process keyboard interactions asynchronously in your iOS browser app’s text view.","type":"text"}]},"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit":{"kind":"symbol","url":"/documentation/browserenginekit","title":"BrowserEngineKit","type":"topic","identifier":"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit","role":"collection","abstract":[{"text":"Create a browser that renders content using an alternative browser engine.","type":"text"}]},"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/caretRect(for:)":{"url":"/documentation/browserenginekit/betextinput/caretrect(for:)","identifier":"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/caretRect(for:)","kind":"symbol","type":"topic","abstract":[{"text":"Returns a rectangle to draw the caret at a specified insertion point.","type":"text"}],"navigatorTitle":[{"text":"caretRectForPosition:","kind":"identifier"}],"title":"caretRect(for:)","role":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"caretRect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITextPosition","text":"UITextPosition","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"}]},"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectText(in:at:completionHandler:)":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectText","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UITextGranularity","text":"UITextGranularity","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"type":"topic","url":"/documentation/browserenginekit/betextinput/selecttext(in:at:completionhandler:)","navigatorTitle":[{"text":"selectTextInGranularity:atPoint:completionHandler:","kind":"identifier"}],"identifier":"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectText(in:at:completionHandler:)","title":"selectText(in:at:completionHandler:)","role":"symbol","kind":"symbol","abstract":[{"text":"Selects the text within the given granularity at the given point in the text view.","type":"text"}]},"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectionRects(for:)":{"kind":"symbol","url":"/documentation/browserenginekit/betextinput/selectionrects(for:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectionRects"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UITextRange","kind":"typeIdentifier","text":"UITextRange"},{"kind":"text","text":") -> ["},{"preciseIdentifier":"c:objc(cs)UITextSelectionRect","kind":"typeIdentifier","text":"UITextSelectionRect"},{"kind":"text","text":"]"}],"title":"selectionRects(for:)","type":"topic","identifier":"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectionRects(for:)","role":"symbol","abstract":[{"text":"Returns an array of selection rects corresponding to the range of text.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"selectionRectsForRange:"}]},"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/isSelectionAtDocumentStart":{"identifier":"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/isSelectionAtDocumentStart","required":true,"kind":"symbol","abstract":[{"text":"Represents whether the current selection is at the beginning of the document","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"selectionAtDocumentStart"}],"url":"/documentation/browserenginekit/betextinput/isselectionatdocumentstart","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSelectionAtDocumentStart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isSelectionAtDocumentStart"},"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectPosition(at:for:completionHandler:)":{"navigatorTitle":[{"text":"selectPositionAtPoint:withContextRequest:completionHandler:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectPosition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"BETextDocumentRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)BETextDocumentRequest"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"BETextDocumentContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)BETextDocumentContext"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"title":"selectPosition(at:for:completionHandler:)","required":true,"identifier":"doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectPosition(at:for:completionHandler:)","type":"topic","abstract":[{"text":"Sets the selection caret to the given point.  Also includes a convenience document context request.","type":"text"}],"url":"/documentation/browserenginekit/betextinput/selectposition(at:for:completionhandler:)","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"name":"iOS","introducedAt":"17.4","unavailable":false,"deprecated":false,"beta":false},{"unavailable":false,"name":"iPadOS","introducedAt":"17.4","beta":false,"deprecated":false},{"unavailable":false,"name":"tvOS","introducedAt":"17.4","beta":false,"deprecated":false},{"unavailable":false,"name":"visionOS","introducedAt":"1.1","beta":false,"deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"selectionRectsForRange:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"selectionRectsForRange:","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"generated":true,"title":"Selecting text","anchor":"Selecting-text","identifiers":["doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectedText","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectedTextRange","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/isSelectionAtDocumentStart","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/caretRect(for:)","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectWordForReplacement()","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/updateSelection(extent:boundary:completionHandler:)","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectText(in:at:completionHandler:)","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectPosition(at:completionHandler:)","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectPosition(at:for:completionHandler:)","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/adjustSelection(by:completionHandler:)","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/move(byOffset:)","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/moveSelection(atBoundary:in:completionHandler:)","doc://com.apple.BrowserEngineKit/documentation/BrowserEngineKit/BETextInput/selectTextForEditMenuWithLocation(inView:completionHandler:)"]}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","tvOS","visionOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<UITextSelectionRect *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"selectionRectsForRange:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITextRange","text":"UITextRange","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)UITextRange"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"range"},{"kind":"text","text":";"}]}]},"op":"replace","path":"/primaryContentSections/0"},{"path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"name":"range","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The range of text for which to return selection rectangles."}]}]}]},"op":"replace"},{"value":"moveByOffset:","op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1move(byOffset:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveByOffset:"}],"op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1move(byOffset:)/fragments"},{"value":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UITextRange"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)UITextRange/fragments"},{"value":"selectTextForEditMenuWithLocationInView:completionHandler:","op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1selectTextForEditMenuWithLocation(inView:completionHandler:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"selectTextForEditMenuWithLocationInView:completionHandler:"}],"op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1selectTextForEditMenuWithLocation(inView:completionHandler:)/fragments"},{"value":"adjustSelectionByRange:completionHandler:","op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1adjustSelection(by:completionHandler:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"adjustSelectionByRange:completionHandler:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1adjustSelection(by:completionHandler:)/fragments"},{"value":"selectWordForReplacement","op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1selectWordForReplacement()/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"selectWordForReplacement"}],"op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1selectWordForReplacement()/fragments"},{"value":"selectedText","op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1selectedText/title"},{"value":[{"text":"selectedText","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1selectedText/fragments"},{"value":"selectPositionAtPoint:completionHandler:","op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1selectPosition(at:completionHandler:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"selectPositionAtPoint:completionHandler:"}],"op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1selectPosition(at:completionHandler:)/fragments"},{"value":"selectedTextRange","op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1selectedTextRange/title"},{"value":[{"kind":"identifier","text":"selectedTextRange"}],"op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1selectedTextRange/fragments"},{"value":"moveSelectionAtBoundary:inStorageDirection:completionHandler:","op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1moveSelection(atBoundary:in:completionHandler:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveSelectionAtBoundary:inStorageDirection:completionHandler:"}],"op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1moveSelection(atBoundary:in:completionHandler:)/fragments"},{"value":"BETextInput","op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput/title"},{"value":[{"text":"BETextInput","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput/fragments"},{"value":[{"kind":"identifier","text":"BETextInput"}],"op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput/navigatorTitle"},{"value":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITextSelectionRect","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)UITextSelectionRect/fragments"},{"value":"updateSelectionWithExtentPoint:boundary:completionHandler:","op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1updateSelection(extent:boundary:completionHandler:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"updateSelectionWithExtentPoint:boundary:completionHandler:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1updateSelection(extent:boundary:completionHandler:)/fragments"},{"value":"caretRectForPosition:","op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1caretRect(for:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"caretRectForPosition:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1caretRect(for:)/fragments"},{"value":"selectTextInGranularity:atPoint:completionHandler:","op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1selectText(in:at:completionHandler:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"selectTextInGranularity:atPoint:completionHandler:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1selectText(in:at:completionHandler:)/fragments"},{"value":"selectionRectsForRange:","op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1selectionRects(for:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"selectionRectsForRange:"}],"op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1selectionRects(for:)/fragments"},{"value":"selectionAtDocumentStart","op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1isSelectionAtDocumentStart/title"},{"value":[{"text":"selectionAtDocumentStart","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1isSelectionAtDocumentStart/fragments"},{"value":"selectPositionAtPoint:withContextRequest:completionHandler:","op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1selectPosition(at:for:completionHandler:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"selectPositionAtPoint:withContextRequest:completionHandler:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.BrowserEngineKit~1documentation~1BrowserEngineKit~1BETextInput~1selectPosition(at:for:completionHandler:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}