{
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@VTFrameProcessorError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Video Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "VTFrameProcessorError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "code": [
            "@enum       \tVTFrameProcessorError",
            "@abstract\t\tVTFrameProcessor  error codes.",
            "@discussion\t\tThese error codes are returned in the NSError object in the event a method fails.",
            "@constant\t\tVTFrameProcessorUnknownError",
            "\tReturned if the processor failed for unknown reason.",
            "@constant\t\tVTFrameProcessorUnsupportedResolution",
            "\tReturned if the processor failed due to an unsupported resolution.",
            "@constant\t\tVTFrameProcessorSessionNotStarted",
            "\tReturned if the session is used to process frames without being started.",
            "@constant\t\tVTFrameProcessorSessionAlreadyActive",
            "\tReturned if a startSessionWithConfiguration call is made on a session which has already been started.",
            "@constant\t\tVTFrameProcessorFatalError",
            "\tReturned if a fatal error is encoutnered during processing.",
            "@constant\t\tVTFrameProcessorSessionLevelError",
            "\tReturned if processing failed and current session should be stopped.",
            "@constant\t\tVTFrameProcessorInitializationFailed",
            "\tReturned if the session failed to initialize the processing pipeline.",
            "@constant\t\tVTFrameProcessorUnsupportedInput",
            "\tReturned to indicate that one or more frames is in a format which is not supproted by the processor.",
            "@constant\t\tVTFrameProcessorMemoryAllocationFailure",
            "\tReturned if the session or processor is unable to allocate required memory.",
            "@constant\t\tVTFrameProcessorRevisionNotSupported",
            "\tReturned if the specifed revision is not supported by the configured processor.",
            "@constant\t\tVTFrameProcessorProcessingError",
            "\tReturned if the processor encountered an issue preventing it from processing the provided frame.",
            "@constant\t\tVTFrameProcessorInvalidParameterError",
            "\tReturned if one of the provided parameters is not valid.",
            "@constant\t\tVTFrameProcessorInvalidFrameTiming",
            "\tReturned if one of the provided VTFrameProcessorFrame objects has a PTS which is not supported by the processor, either invalid or out-of-order."
          ],
          "syntax": null,
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox": {
      "abstract": [
        {
          "text": "Work directly with hardware-accelerated video encoding and decoding capabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Video Toolbox",
      "type": "topic",
      "url": "/documentation/videotoolbox"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VTFrameProcessorError"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameProcessorError"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessorError",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessorError.Code",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/code"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/fatalError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fatalError"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/fatalError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameProcessorFatalError"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessorError.Code.fatalError",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/code/fatalerror"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/code/init(rawvalue:)"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/initializationFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initializationFailed"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/initializationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameProcessorInitializationFailed"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessorError.Code.initializationFailed",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/code/initializationfailed"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/invalidFrameTiming": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidFrameTiming"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/invalidFrameTiming",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameProcessorInvalidFrameTiming"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessorError.Code.invalidFrameTiming",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/code/invalidframetiming"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/invalidParameterError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidParameterError"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/invalidParameterError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameProcessorInvalidParameterError"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessorError.Code.invalidParameterError",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/code/invalidparametererror"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/memoryAllocationFailure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "memoryAllocationFailure"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/memoryAllocationFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameProcessorMemoryAllocationFailure"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessorError.Code.memoryAllocationFailure",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/code/memoryallocationfailure"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/processingError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "processingError"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/processingError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameProcessorProcessingError"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessorError.Code.processingError",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/code/processingerror"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/revisionNotSupported": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "revisionNotSupported"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/revisionNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameProcessorRevisionNotSupported"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessorError.Code.revisionNotSupported",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/code/revisionnotsupported"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/sessionAlreadyActive": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionAlreadyActive"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/sessionAlreadyActive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameProcessorSessionAlreadyActive"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessorError.Code.sessionAlreadyActive",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/code/sessionalreadyactive"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/sessionLevelError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionLevelError"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/sessionLevelError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameProcessorSessionLevelError"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessorError.Code.sessionLevelError",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/code/sessionlevelerror"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/sessionNotStarted": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionNotStarted"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/sessionNotStarted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameProcessorSessionNotStarted"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessorError.Code.sessionNotStarted",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/code/sessionnotstarted"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/unknownError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownError"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/unknownError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameProcessorUnknownError"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessorError.Code.unknownError",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/code/unknownerror"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/unsupportedInput": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedInput"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/unsupportedInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameProcessorUnsupportedInput"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessorError.Code.unsupportedInput",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/code/unsupportedinput"
    },
    "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/unsupportedResolution": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedResolution"
        }
      ],
      "identifier": "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/unsupportedResolution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VTFrameProcessorUnsupportedResolution"
        }
      ],
      "role": "symbol",
      "title": "VTFrameProcessorError.Code.unsupportedResolution",
      "type": "topic",
      "url": "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/code/unsupportedresolution"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/fatalError",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/initializationFailed",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/invalidFrameTiming",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/invalidParameterError",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/memoryAllocationFailure",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/processingError",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/revisionNotSupported",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/sessionAlreadyActive",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/sessionLevelError",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/sessionNotStarted",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/unknownError",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/unsupportedInput",
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/unsupportedResolution"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VTFrameProcessorError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/fatalError",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/initializationFailed",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/invalidFrameTiming",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/invalidParameterError",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/memoryAllocationFailure",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/processingError",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/revisionNotSupported",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/sessionAlreadyActive",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/sessionLevelError",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/sessionNotStarted",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/unknownError",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/unsupportedInput",
                "doc://com.apple.videotoolbox/documentation/VideoToolbox/VTFrameProcessorError-swift.struct/Code/unsupportedResolution"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VTFrameProcessorError"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code~1unsupportedInput/title",
          "value": "VTFrameProcessorUnsupportedInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code~1unsupportedInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorUnsupportedInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code/title",
          "value": "VTFrameProcessorError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code~1revisionNotSupported/title",
          "value": "VTFrameProcessorRevisionNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code~1revisionNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorRevisionNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code~1sessionAlreadyActive/title",
          "value": "VTFrameProcessorSessionAlreadyActive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code~1sessionAlreadyActive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorSessionAlreadyActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code~1fatalError/title",
          "value": "VTFrameProcessorFatalError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code~1fatalError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorFatalError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code~1sessionNotStarted/title",
          "value": "VTFrameProcessorSessionNotStarted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code~1sessionNotStarted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorSessionNotStarted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code~1unsupportedResolution/title",
          "value": "VTFrameProcessorUnsupportedResolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code~1unsupportedResolution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorUnsupportedResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code~1initializationFailed/title",
          "value": "VTFrameProcessorInitializationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code~1initializationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorInitializationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code~1memoryAllocationFailure/title",
          "value": "VTFrameProcessorMemoryAllocationFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code~1memoryAllocationFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorMemoryAllocationFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code~1invalidParameterError/title",
          "value": "VTFrameProcessorInvalidParameterError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code~1invalidParameterError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorInvalidParameterError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code~1invalidFrameTiming/title",
          "value": "VTFrameProcessorInvalidFrameTiming"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code~1invalidFrameTiming/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorInvalidFrameTiming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code~1sessionLevelError/title",
          "value": "VTFrameProcessorSessionLevelError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code~1sessionLevelError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorSessionLevelError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code~1processingError/title",
          "value": "VTFrameProcessorProcessingError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code~1processingError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorProcessingError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code~1unknownError/title",
          "value": "VTFrameProcessorUnknownError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.videotoolbox~1documentation~1VideoToolbox~1VTFrameProcessorError-swift.struct~1Code~1unknownError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VTFrameProcessorUnknownError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/videotoolbox/vtframeprocessorerror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
