{"metadata":{"role":"symbol","externalID":"s:9PencilKit9PKDrawingV22requiredContentVersionSo09PKContentF0Vvp","platforms":[{"name":"iOS","beta":false,"introducedAt":"17.0","unavailable":false,"deprecated":false},{"name":"iPadOS","beta":false,"introducedAt":"17.0","unavailable":false,"deprecated":false},{"name":"Mac Catalyst","beta":false,"introducedAt":"17.0","unavailable":false,"deprecated":false},{"name":"macOS","beta":false,"introducedAt":"14.0","unavailable":false,"deprecated":false},{"deprecated":false,"unavailable":false,"name":"visionOS","beta":false,"introducedAt":"1.0"}],"symbolKind":"property","title":"requiredContentVersion","roleHeading":"Instance Property","modules":[{"name":"PencilKit"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredContentVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKContentVersion","preciseIdentifier":"c:@E@PKContentVersion"}]},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.pencilkit/documentation/PencilKit","doc://com.apple.pencilkit/documentation/PencilKit/PKDrawing-swift.struct"]]},"variants":[{"paths":["/documentation/pencilkit/pkdrawing-swift.struct/requiredcontentversion"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.pencilkit/documentation/PencilKit/PKDrawing-swift.struct/requiredContentVersion"},"abstract":[{"text":"The version of PencilKit necessary to use the drawing.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredContentVersion"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@PKContentVersion","kind":"typeIdentifier","identifier":"doc://com.apple.pencilkit/documentation/PencilKit/PKContentVersion","text":"PKContentVersion"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.pencilkit/documentation/PencilKit/PKContentVersion":{"type":"topic","url":"/documentation/pencilkit/pkcontentversion","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PKContentVersion"}],"abstract":[{"text":"Constants that represent versions of PencilKit for backward compatibility.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PKContentVersion"}],"title":"PKContentVersion","role":"symbol","identifier":"doc://com.apple.pencilkit/documentation/PencilKit/PKContentVersion"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","url":"/documentation/technologies","kind":"technologies","abstract":[{"text":"","type":"text"}],"title":"Technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.pencilkit/documentation/PencilKit/PKDrawing-swift.struct/requiredContentVersion":{"url":"/documentation/pencilkit/pkdrawing-swift.struct/requiredcontentversion","kind":"symbol","type":"topic","title":"requiredContentVersion","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredContentVersion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PKContentVersion","kind":"typeIdentifier","preciseIdentifier":"c:@E@PKContentVersion"}],"role":"symbol","identifier":"doc://com.apple.pencilkit/documentation/PencilKit/PKDrawing-swift.struct/requiredContentVersion","abstract":[{"text":"The version of PencilKit necessary to use the drawing.","type":"text"}]},"doc://com.apple.pencilkit/documentation/PencilKit":{"type":"topic","url":"/documentation/pencilkit","kind":"symbol","abstract":[{"type":"text","text":"Capture touch and Apple Pencil input as a drawing, and display that content from your app."}],"title":"PencilKit","role":"collection","identifier":"doc://com.apple.pencilkit/documentation/PencilKit"},"doc://com.apple.pencilkit/documentation/PencilKit/PKDrawing-swift.struct":{"navigatorTitle":[{"kind":"identifier","text":"PKDrawing"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PKDrawing"}],"title":"PKDrawing","kind":"symbol","abstract":[{"type":"text","text":"A structure representing the drawing information captured by a canvas view."}],"identifier":"doc://com.apple.pencilkit/documentation/PencilKit/PKDrawing-swift.struct","role":"symbol","url":"/documentation/pencilkit/pkdrawing-swift.struct"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKContentVersion/title","value":"PKContentVersion"},{"op":"replace","path":"/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKContentVersion/fragments","value":[{"kind":"identifier","text":"PKContentVersion"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKContentVersion/navigatorTitle","value":[{"kind":"identifier","text":"PKContentVersion"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}