{
  "abstract": [
    {
      "text": "An error that indicates the file can’t register because of a duplicate font name.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/duplicatedName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTFontManagerError@kCTFontManagerErrorDuplicatedName",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "duplicatedName"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCTFontManagerErrorDuplicatedName"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CTFontManagerError.duplicatedName"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "duplicatedName"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError": {
      "abstract": [
        {
          "text": "Errors that prevent unregistration of fonts for a specified font file URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontManagerError"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontManagerError"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/alreadyRegistered": {
      "abstract": [
        {
          "text": "An error that indicates the file is already registered in the specified scope.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alreadyRegistered"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/alreadyRegistered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorAlreadyRegistered"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.alreadyRegistered",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/alreadyregistered"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/assetNotFound": {
      "abstract": [
        {
          "text": "An error that indicates the asset isn’t found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "assetNotFound"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/assetNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorAssetNotFound"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.assetNotFound",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/assetnotfound"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/cancelledByUser": {
      "abstract": [
        {
          "text": "An error that indicates the user cancelled the operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelledByUser"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/cancelledByUser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorCancelledByUser"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.cancelledByUser",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/cancelledbyuser"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/duplicatedName": {
      "abstract": [
        {
          "text": "An error that indicates the file can’t register because of a duplicate font name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duplicatedName"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/duplicatedName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorDuplicatedName"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.duplicatedName",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/duplicatedname"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/exceededResourceLimit": {
      "abstract": [
        {
          "text": "An error that indicates an operation failure due to a system limitation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exceededResourceLimit"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/exceededResourceLimit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorExceededResourceLimit"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.exceededResourceLimit",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/exceededresourcelimit"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/fileNotFound": {
      "abstract": [
        {
          "text": "An error that indicates the file doesn’t exist at the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileNotFound"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/fileNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorFileNotFound"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.fileNotFound",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/filenotfound"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/inUse": {
      "abstract": [
        {
          "text": "An error that indicates the font file is actively in use and can’t be unregistered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inUse"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/inUse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorInUse"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.inUse",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/inuse"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/insufficientInfo": {
      "abstract": [
        {
          "text": "An error that indicates the font descriptor doesn’t have the necessary information to specify a font file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientInfo"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/insufficientInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorInsufficientInfo"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.insufficientInfo",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/insufficientinfo"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/insufficientPermissions": {
      "abstract": [
        {
          "text": "An error that indicates insufficient permissions to access the file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientPermissions"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/insufficientPermissions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorInsufficientPermissions"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.insufficientPermissions",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/insufficientpermissions"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/invalidFilePath": {
      "abstract": [
        {
          "text": "An error that indicates the file isn’t in an allowed location, which must be either in the app’s bundle or an on-demand resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidFilePath"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/invalidFilePath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorInvalidFilePath"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.invalidFilePath",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/invalidfilepath"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/invalidFontData": {
      "abstract": [
        {
          "text": "An error that indicates the file contains invalid font data that could cause system problems.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidFontData"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/invalidFontData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorInvalidFontData"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.invalidFontData",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/invalidfontdata"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/missingEntitlement": {
      "abstract": [
        {
          "text": "An error that indicates the file can’t be processed because the provider doesn’t have a necessary entitlement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingEntitlement"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/missingEntitlement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorMissingEntitlement"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.missingEntitlement",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/missingentitlement"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/notRegistered": {
      "abstract": [
        {
          "text": "An error that indicates the file isn’t registered in the specified scope.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notRegistered"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/notRegistered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorNotRegistered"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.notRegistered",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/notregistered"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/registrationFailed": {
      "abstract": [
        {
          "text": "An error that indicates the file can’t be processed due to an unexpected FontProvider error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registrationFailed"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/registrationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorRegistrationFailed"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.registrationFailed",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/registrationfailed"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/systemRequired": {
      "abstract": [
        {
          "text": "An error that indicates the file is required by the system and can’t be unregistered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemRequired"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/systemRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorSystemRequired"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.systemRequired",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/systemrequired"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/unrecognizedFormat": {
      "abstract": [
        {
          "text": "An error that indicates the file’s format is unrecognized or unsupported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unrecognizedFormat"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/unrecognizedFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorUnrecognizedFormat"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.unrecognizedFormat",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/unrecognizedformat"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/fileNotFound",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/insufficientPermissions",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/unrecognizedFormat",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/invalidFontData",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/alreadyRegistered",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/exceededResourceLimit",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/assetNotFound",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/notRegistered",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/inUse",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/systemRequired",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/registrationFailed",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/missingEntitlement",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/insufficientInfo",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/cancelledByUser",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/invalidFilePath"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCTFontManagerErrorDuplicatedName"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorDuplicatedName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/fileNotFound",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/insufficientPermissions",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/unrecognizedFormat",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/invalidFontData",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/alreadyRegistered",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/exceededResourceLimit",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/assetNotFound",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/notRegistered",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/inUse",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/systemRequired",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/registrationFailed",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/missingEntitlement",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/insufficientInfo",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/cancelledByUser",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/invalidFilePath"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCTFontManagerErrorDuplicatedName"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1unrecognizedFormat/title",
          "value": "kCTFontManagerErrorUnrecognizedFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1unrecognizedFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorUnrecognizedFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1alreadyRegistered/title",
          "value": "kCTFontManagerErrorAlreadyRegistered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1alreadyRegistered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorAlreadyRegistered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1insufficientInfo/title",
          "value": "kCTFontManagerErrorInsufficientInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1insufficientInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorInsufficientInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1systemRequired/title",
          "value": "kCTFontManagerErrorSystemRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1systemRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorSystemRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError/title",
          "value": "CTFontManagerError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1exceededResourceLimit/title",
          "value": "kCTFontManagerErrorExceededResourceLimit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1exceededResourceLimit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorExceededResourceLimit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1notRegistered/title",
          "value": "kCTFontManagerErrorNotRegistered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1notRegistered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorNotRegistered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1registrationFailed/title",
          "value": "kCTFontManagerErrorRegistrationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1registrationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorRegistrationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1invalidFilePath/title",
          "value": "kCTFontManagerErrorInvalidFilePath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1invalidFilePath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorInvalidFilePath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1insufficientPermissions/title",
          "value": "kCTFontManagerErrorInsufficientPermissions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1insufficientPermissions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorInsufficientPermissions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1assetNotFound/title",
          "value": "kCTFontManagerErrorAssetNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1assetNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorAssetNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1duplicatedName/title",
          "value": "kCTFontManagerErrorDuplicatedName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1duplicatedName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorDuplicatedName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1fileNotFound/title",
          "value": "kCTFontManagerErrorFileNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1fileNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorFileNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1missingEntitlement/title",
          "value": "kCTFontManagerErrorMissingEntitlement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1missingEntitlement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorMissingEntitlement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1invalidFontData/title",
          "value": "kCTFontManagerErrorInvalidFontData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1invalidFontData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorInvalidFontData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1inUse/title",
          "value": "kCTFontManagerErrorInUse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1inUse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorInUse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1cancelledByUser/title",
          "value": "kCTFontManagerErrorCancelledByUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1cancelledByUser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorCancelledByUser"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctfontmanagererror/duplicatedname"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctfontmanagererror/duplicatedname"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
