{
  "abstract": [
    {
      "text": "An error code that indicates a problem with a configuration, typically in a descriptor or an archive’s inability to add linked functions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct/unexpectedElement"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC21MTLBinaryArchiveErrorLeV17unexpectedElementSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unexpectedElement"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC21MTLBinaryArchiveErrorLeV",
        "text": "MTLBinaryArchiveError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MTLBinaryArchiveError",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "unexpectedElement"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unexpectedElement"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC21MTLBinaryArchiveErrorLeV",
              "text": "MTLBinaryArchiveError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MTLBinaryArchiveError",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct": {
      "abstract": [
        {
          "text": "An error that occurred when creating a binary shader archive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLBinaryArchiveError"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBinaryArchiveError"
        }
      ],
      "role": "symbol",
      "title": "MTLBinaryArchiveError",
      "type": "topic",
      "url": "/documentation/metal/mtlbinaryarchiveerror-swift.struct"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes when creating binary archives of compiled shader code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MTLBinaryArchiveError.Code",
      "type": "topic",
      "url": "/documentation/metal/mtlbinaryarchiveerror-swift.struct/code"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct/compilationFailure": {
      "abstract": [
        {
          "text": "An error code that indicates the archive’s inability to compile its contents, typically when serializing it to a URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compilationFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21MTLBinaryArchiveErrorLeV",
          "text": "MTLBinaryArchiveError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLBinaryArchiveError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct/compilationFailure",
      "kind": "symbol",
      "role": "symbol",
      "title": "compilationFailure",
      "type": "topic",
      "url": "/documentation/metal/mtlbinaryarchiveerror-swift.struct/compilationfailure"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct/internalError": {
      "abstract": [
        {
          "text": "An error code that indicates the Metal framework has an internal problem.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21MTLBinaryArchiveErrorLeV",
          "text": "MTLBinaryArchiveError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLBinaryArchiveError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct/internalError",
      "kind": "symbol",
      "role": "symbol",
      "title": "internalError",
      "type": "topic",
      "url": "/documentation/metal/mtlbinaryarchiveerror-swift.struct/internalerror"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct/invalidFile": {
      "abstract": [
        {
          "text": "An error code that indicates an app is using an invalid reference to an archive file, typically related to a URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21MTLBinaryArchiveErrorLeV",
          "text": "MTLBinaryArchiveError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLBinaryArchiveError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct/invalidFile",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidFile",
      "type": "topic",
      "url": "/documentation/metal/mtlbinaryarchiveerror-swift.struct/invalidfile"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct/none": {
      "abstract": [
        {
          "text": "An error code that represents the absence of any problems.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21MTLBinaryArchiveErrorLeV",
          "text": "MTLBinaryArchiveError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLBinaryArchiveError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct/none",
      "kind": "symbol",
      "role": "symbol",
      "title": "none",
      "type": "topic",
      "url": "/documentation/metal/mtlbinaryarchiveerror-swift.struct/none"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct/unexpectedElement": {
      "abstract": [
        {
          "text": "An error code that indicates a problem with a configuration, typically in a descriptor or an archive’s inability to add linked functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unexpectedElement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21MTLBinaryArchiveErrorLeV",
          "text": "MTLBinaryArchiveError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLBinaryArchiveError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct/unexpectedElement",
      "kind": "symbol",
      "role": "symbol",
      "title": "unexpectedElement",
      "type": "topic",
      "url": "/documentation/metal/mtlbinaryarchiveerror-swift.struct/unexpectedelement"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct/none",
        "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct/invalidFile",
        "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct/compilationFailure",
        "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct/internalError",
        "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct/Code"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinaryArchiveError-swift.struct~1Code/title",
          "value": "MTLBinaryArchiveError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinaryArchiveError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBinaryArchiveError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinaryArchiveError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBinaryArchiveError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlbinaryarchiveerror-swift.struct/unexpectedelement"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
