{
  "abstract": [
    {
      "text": "A transparent black style.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/lightContent",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/UIStatusBarStyleBlackTranslucent"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIStatusBarStyle@UIStatusBarStyleBlackTranslucent",
    "fragments": [
      {
        "kind": "identifier",
        "text": "UIStatusBarStyleBlackTranslucent"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIStatusBarStyleBlackTranslucent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "7.0",
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "7.0",
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "UIStatusBarStyleBlackTranslucent"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "UIStatusBarStyleBlackTranslucent"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle": {
      "abstract": [
        {
          "text": "Constants that describe the style of the device’s status bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIStatusBarStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIStatusBarStyle"
        }
      ],
      "role": "symbol",
      "title": "UIStatusBarStyle",
      "type": "topic",
      "url": "/documentation/uikit/uistatusbarstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/UIStatusBarStyleBlackOpaque": {
      "abstract": [
        {
          "text": "An opaque black style.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIStatusBarStyleBlackOpaque"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/UIStatusBarStyleBlackOpaque",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIStatusBarStyleBlackOpaque",
      "type": "topic",
      "url": "/documentation/uikit/uistatusbarstyle/uistatusbarstyleblackopaque"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/UIStatusBarStyleBlackTranslucent": {
      "abstract": [
        {
          "text": "A transparent black style.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIStatusBarStyleBlackTranslucent"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/UIStatusBarStyleBlackTranslucent",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIStatusBarStyleBlackTranslucent",
      "type": "topic",
      "url": "/documentation/uikit/uistatusbarstyle/uistatusbarstyleblacktranslucent"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/lightContent": {
      "abstract": [
        {
          "text": "A light status bar, intended for use on dark backgrounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lightContent"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/lightContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIStatusBarStyleLightContent"
        }
      ],
      "role": "symbol",
      "title": "UIStatusBarStyle.lightContent",
      "type": "topic",
      "url": "/documentation/uikit/uistatusbarstyle/lightcontent"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/UIStatusBarStyleBlackOpaque"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStatusBarStyle~1lightContent/title",
          "value": "UIStatusBarStyleLightContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStatusBarStyle~1lightContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStatusBarStyleLightContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStatusBarStyle/title",
          "value": "UIStatusBarStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStatusBarStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStatusBarStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStatusBarStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStatusBarStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uistatusbarstyle/uistatusbarstyleblacktranslucent"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
