{
  "abstract": [
    {
      "text": "Creates a room-capture view with the given AR session.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.RoomPlan/documentation/RoomPlan",
        "doc://com.apple.RoomPlan/documentation/RoomPlan/RoomCaptureView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.RoomPlan/documentation/RoomPlan/RoomCaptureView/init(frame:arSession:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:8RoomPlan0A11CaptureViewC5frame9arSessionACSo6CGRectV_So9ARSessionCtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "frame"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@CGRect",
        "text": "CGRect"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "arSession"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ARSession",
        "text": "ARSession"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "RoomPlan"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "16.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(frame:arSession:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "attribute",
              "text": "@preconcurrency"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "frame"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@CGRect",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGRect",
              "text": "CGRect"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "arSession"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)ARSession",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ARSession",
              "text": "ARSession"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A structure that positions and shapes the view.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "frame"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A world-tracking session that your app creates and runs with an ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " before calling this function. If you pass an ",
                  "type": "text"
                },
                {
                  "code": "ARSession",
                  "type": "codeVoice"
                },
                {
                  "text": " instance, RoomPlan preserves all of the AR session’s settings.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "arSession"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "By providing your own ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ARKit/ARSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, you can continue your app’s existing AR experience by seamlessly transitioning into a room-scanning session wtih RoomPlan. In addition, continuing an ",
              "type": "text"
            },
            {
              "code": "ARSession",
              "type": "codeVoice"
            },
            {
              "text": " across multiple room-capture sessions — specifically, different rooms in the same vicinity — enables you to merge multiple ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RoomPlan/documentation/RoomPlan/CapturedRoom",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects into a single captured structure. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RoomPlan/documentation/RoomPlan/CapturedStructure",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can access the ",
              "type": "text"
            },
            {
              "code": "arSession",
              "type": "codeVoice"
            },
            {
              "text": " at runtime through this class’s room-capture session (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RoomPlan/documentation/RoomPlan/RoomCaptureView/captureSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") property. See the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RoomPlan/documentation/RoomPlan/RoomCaptureSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RoomPlan/documentation/RoomPlan/RoomCaptureSession/arSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.RoomPlan/documentation/RoomPlan": {
      "abstract": [
        {
          "text": "Create a 3D model of a room by interactively guiding people to scan their physical environment using a device’s camera.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.RoomPlan/documentation/RoomPlan",
      "kind": "symbol",
      "role": "collection",
      "title": "RoomPlan",
      "type": "topic",
      "url": "/documentation/roomplan"
    },
    "doc://com.apple.RoomPlan/documentation/RoomPlan/CapturedRoom": {
      "abstract": [
        {
          "text": "A structure that provides the key details of a scanned room.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CapturedRoom"
        }
      ],
      "identifier": "doc://com.apple.RoomPlan/documentation/RoomPlan/CapturedRoom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CapturedRoom"
        }
      ],
      "role": "symbol",
      "title": "CapturedRoom",
      "type": "topic",
      "url": "/documentation/roomplan/capturedroom"
    },
    "doc://com.apple.RoomPlan/documentation/RoomPlan/CapturedStructure": {
      "abstract": [
        {
          "text": "An object that holds the results of the merger of multiple capture sessions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CapturedStructure"
        }
      ],
      "identifier": "doc://com.apple.RoomPlan/documentation/RoomPlan/CapturedStructure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CapturedStructure"
        }
      ],
      "role": "symbol",
      "title": "CapturedStructure",
      "type": "topic",
      "url": "/documentation/roomplan/capturedstructure"
    },
    "doc://com.apple.RoomPlan/documentation/RoomPlan/RoomCaptureSession": {
      "abstract": [
        {
          "text": "An object that manages the room-scanning process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RoomCaptureSession"
        }
      ],
      "identifier": "doc://com.apple.RoomPlan/documentation/RoomPlan/RoomCaptureSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RoomCaptureSession"
        }
      ],
      "role": "symbol",
      "title": "RoomCaptureSession",
      "type": "topic",
      "url": "/documentation/roomplan/roomcapturesession"
    },
    "doc://com.apple.RoomPlan/documentation/RoomPlan/RoomCaptureSession/arSession": {
      "abstract": [
        {
          "text": "An object that manages an ARKit session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arSession"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSession",
          "text": "ARSession"
        }
      ],
      "identifier": "doc://com.apple.RoomPlan/documentation/RoomPlan/RoomCaptureSession/arSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "arSession",
      "type": "topic",
      "url": "/documentation/roomplan/roomcapturesession/arsession"
    },
    "doc://com.apple.RoomPlan/documentation/RoomPlan/RoomCaptureView": {
      "abstract": [
        {
          "text": "A view that enables the user to scan their room with the device’s camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RoomCaptureView"
        }
      ],
      "identifier": "doc://com.apple.RoomPlan/documentation/RoomPlan/RoomCaptureView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RoomCaptureView"
        }
      ],
      "role": "symbol",
      "title": "RoomCaptureView",
      "type": "topic",
      "url": "/documentation/roomplan/roomcaptureview"
    },
    "doc://com.apple.RoomPlan/documentation/RoomPlan/RoomCaptureView/captureSession": {
      "abstract": [
        {
          "text": "An object that notifies a delegate of particular events in the room-scanning life cycle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "captureSession"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8RoomPlan0A14CaptureSessionC",
          "text": "RoomCaptureSession"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.RoomPlan/documentation/RoomPlan/RoomCaptureView/captureSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "captureSession",
      "type": "topic",
      "url": "/documentation/roomplan/roomcaptureview/capturesession"
    },
    "doc://com.apple.RoomPlan/documentation/RoomPlan/RoomCaptureView/init(coder:)": {
      "abstract": [
        {
          "text": "Creates a view by deserializing from the specified coder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.RoomPlan/documentation/RoomPlan/RoomCaptureView/init(coder:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(coder:)",
      "type": "topic",
      "url": "/documentation/roomplan/roomcaptureview/init(coder:)"
    },
    "doc://com.apple.RoomPlan/documentation/RoomPlan/RoomCaptureView/init(frame:)": {
      "abstract": [
        {
          "text": "Creates a view that sizes to the specified frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "frame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.RoomPlan/documentation/RoomPlan/RoomCaptureView/init(frame:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(frame:)",
      "type": "topic",
      "url": "/documentation/roomplan/roomcaptureview/init(frame:)"
    },
    "doc://com.apple.RoomPlan/documentation/RoomPlan/RoomCaptureView/init(frame:arSession:)": {
      "abstract": [
        {
          "text": "Creates a room-capture view with the given AR session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "frame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "arSession"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSession",
          "text": "ARSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.RoomPlan/documentation/RoomPlan/RoomCaptureView/init(frame:arSession:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(frame:arSession:)",
      "type": "topic",
      "url": "/documentation/roomplan/roomcaptureview/init(frame:arsession:)"
    },
    "doc://com.apple.documentation/documentation/ARKit/ARSession": {
      "abstract": [
        {
          "text": "The object that manages the major tasks associated with every AR experience, such as motion tracking, camera passthrough, and image analysis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARSession"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit/ARSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARSession",
      "type": "topic",
      "url": "/documentation/ARKit/ARSession"
    },
    "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration": {
      "abstract": [
        {
          "text": "A configuration that tracks the position of a device in relation to objects in the environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARWorldTrackingConfiguration"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit/ARWorldTrackingConfiguration",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARWorldTrackingConfiguration",
      "type": "topic",
      "url": "/documentation/ARKit/ARWorldTrackingConfiguration"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@S@CGRect": {
      "abstract": [
        {
          "text": "A structure that contains the location and dimensions of a rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@CGRect",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGRect",
      "type": "topic",
      "url": "/documentation/corefoundation/cgrect"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)ARSession": {
      "abstract": [
        {
          "text": "The object that manages the major tasks associated with every AR experience, such as motion tracking, camera passthrough, and image analysis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARSession"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)ARSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARSession",
      "type": "topic",
      "url": "/documentation/ARKit/ARSession"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-room-capture-view",
      "generated": true,
      "identifiers": [
        "doc://com.apple.RoomPlan/documentation/RoomPlan/RoomCaptureView/init(frame:)",
        "doc://com.apple.RoomPlan/documentation/RoomPlan/RoomCaptureView/init(coder:)"
      ],
      "title": "Creating a room-capture view"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ARKit~1ARWorldTrackingConfiguration/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ARWorldTrackingConfiguration"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ARConfiguration",
              "text": "ARConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)ARSession/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ARSession"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ARKit~1ARSession/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ARSession"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/roomplan/roomcaptureview/init(frame:arsession:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
