{
  "abstract": [
    {
      "text": "Creates a lightweight migration stage with the specified version checksums.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData",
        "doc://com.apple.coredata/documentation/CoreData/NSLightweightMigrationStage"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSLightweightMigrationStage/initWithVersionChecksums:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSLightweightMigrationStage(im)initWithVersionChecksums:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "initWithVersionChecksums:"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithVersionChecksums:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "initWithVersionChecksums:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "initWithVersionChecksums:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<NSString *>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "versionChecksums"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The array of version checksums.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "versionChecksums"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An initialized lightweight migration manager, or ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if Core Data can’t create one.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To determine an object model’s version checksum, use its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectModel/versionChecksum",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property. Alternatively, you can find the checksum in the versioned model’s ",
              "type": "text"
            },
            {
              "code": "VersionInfo.plist",
              "type": "codeVoice"
            },
            {
              "text": " file or in Xcode’s build log.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSLightweightMigrationStage": {
      "abstract": [
        {
          "text": "An object that describes a series of models suitable for lightweight migration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLightweightMigrationStage"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSLightweightMigrationStage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLightweightMigrationStage"
        }
      ],
      "role": "symbol",
      "title": "NSLightweightMigrationStage",
      "type": "topic",
      "url": "/documentation/coredata/nslightweightmigrationstage"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSLightweightMigrationStage/initWithVersionChecksums:": {
      "abstract": [
        {
          "text": "Creates a lightweight migration stage with the specified version checksums.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithVersionChecksums:"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSLightweightMigrationStage/initWithVersionChecksums:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithVersionChecksums:"
        }
      ],
      "role": "symbol",
      "title": "initWithVersionChecksums:",
      "type": "topic",
      "url": "/documentation/coredata/nslightweightmigrationstage/initwithversionchecksums:"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectModel/versionChecksum": {
      "abstract": [
        {
          "text": "The Base64-encoded 128-bit model version hash.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "versionChecksum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectModel/versionChecksum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "versionChecksum"
        }
      ],
      "role": "symbol",
      "title": "versionChecksum",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectmodel/versionchecksum"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectModel~1versionChecksum/title",
          "value": "versionChecksum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectModel~1versionChecksum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "versionChecksum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSLightweightMigrationStage/title",
          "value": "NSLightweightMigrationStage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSLightweightMigrationStage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLightweightMigrationStage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSLightweightMigrationStage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLightweightMigrationStage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nslightweightmigrationstage/initwithversionchecksums:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
