{"metadata":{"modules":[{"name":"AppKit"}],"required":true,"platforms":[{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","externalID":"c:objc(pl)NSUserInterfaceItemSearching(im)localizedTitlesForItem:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"localizedTitles","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forItem","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"localizedTitlesForItem:","kind":"identifier"}],"title":"localizedTitles(forItem:)"},"abstract":[{"type":"text","text":"Returns an array of localized strings that will form the help menu item."}],"kind":"symbol","identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemSearching/localizedTitles(forItem:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["/documentation/appkit/nsuserinterfaceitemsearching/localizedtitles(foritem:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsuserinterfaceitemsearching/localizedtitles(foritem:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemSearching"]]},"seeAlsoSections":[{"anchor":"Show-Help-Menu","title":"Show Help Menu","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemSearching/showAllHelpTopics(forSearch:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedTitles"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forItem"},{"kind":"text","text":" "},{"kind":"internalParam","text":"item"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"String","identifier":"doc://com.externally.resolved.symbol/s:SS","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"At item in the help menu."}]}],"name":"item"}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"text":"An ","type":"text"},{"code":"NSArray","type":"codeVoice"},{"text":" of ","type":"text"},{"code":"NSStrings","type":"codeVoice"},{"text":" (localized for display in the menu) that will be combined with separators to form the menu item title.","type":"text"}]}],"kind":"content"}],"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemSearching/showAllHelpTopics(forSearch:)":{"abstract":[{"text":"If this method is implemented, a “Show All Help Topics” item will appear in the menu and this method is called when the user selects it.","type":"text"}],"url":"/documentation/appkit/nsuserinterfaceitemsearching/showallhelptopics(forsearch:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showAllHelpTopics","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forSearch","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"showAllHelpTopics(forSearch:)","type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemSearching/showAllHelpTopics(forSearch:)","navigatorTitle":[{"text":"showAllHelpTopicsForSearchString:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemSearching/localizedTitles(forItem:)":{"url":"/documentation/appkit/nsuserinterfaceitemsearching/localizedtitles(foritem:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemSearching/localizedTitles(forItem:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedTitles"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forItem"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":") -> ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]"}],"title":"localizedTitles(forItem:)","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"localizedTitlesForItem:"}],"required":true,"abstract":[{"type":"text","text":"Returns an array of localized strings that will form the help menu item."}]},"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemSearching":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemSearching","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSUserInterfaceItemSearching"}],"title":"NSUserInterfaceItemSearching","kind":"symbol","type":"topic","url":"/documentation/appkit/nsuserinterfaceitemsearching","abstract":[{"text":"A set of methods an app can implement to provide Spotlight for Help for its own custom help data.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NSUserInterfaceItemSearching"}]},"doc://com.externally.resolved.symbol/s:SS":{"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SS","url":"/documentation/Swift/String","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"String","kind":"identifier"}],"type":"topic","title":"String","role":"symbol","abstract":[{"text":"A Unicode string value that is a collection of characters.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"deprecated":false,"name":"macOS","unavailable":false,"beta":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"localizedTitlesForItem:","path":"/metadata/title","op":"replace"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"localizedTitlesForItem:","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemSearching"]]},"path":"/hierarchy"},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemSearching/showAllHelpTopics(forSearch:)"],"title":"Show Help Menu","anchor":"Show-Help-Menu"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"localizedTitlesForItem:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"item"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"/primaryContentSections/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"item","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"At item in the help menu."}]}]}]}},{"value":{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"An "},{"type":"codeVoice","code":"NSArray"},{"text":" of ","type":"text"},{"type":"codeVoice","code":"NSStrings"},{"text":" (localized for display in the menu) that will be combined with separators to form the menu item title.","type":"text"}],"type":"paragraph"}],"kind":"content"},"op":"replace","path":"/primaryContentSections/2"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemSearching~1showAllHelpTopics(forSearch:)/title","op":"replace","value":"showAllHelpTopicsForSearchString:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemSearching~1showAllHelpTopics(forSearch:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"showAllHelpTopicsForSearchString:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemSearching~1localizedTitles(forItem:)/title","op":"replace","value":"localizedTitlesForItem:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemSearching~1localizedTitles(forItem:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"localizedTitlesForItem:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemSearching/title","op":"replace","value":"NSUserInterfaceItemSearching"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemSearching/fragments","op":"replace","value":[{"kind":"identifier","text":"NSUserInterfaceItemSearching"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemSearching/navigatorTitle","op":"replace","value":[{"text":"NSUserInterfaceItemSearching","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}