{"metadata":{"modules":[{"name":"AppKit"}],"platforms":[{"unavailable":false,"beta":false,"name":"macOS","deprecated":false}],"externalID":"c:objc(pl)NSUserInterfaceItemSearching(im)performActionForItem:","title":"performAction(forItem:)","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"performAction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forItem","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"performActionForItem:"}],"role":"symbol"},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemSearching"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemSearching/performAction(forItem:)"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"anchor":"Search-Help-Content","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemSearching/searchForItems(withSearch:resultLimit:matchedItemHandler:)"],"title":"Search Help Content","generated":true}],"abstract":[{"text":"Invoked when the user selects a search result in Help menu.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"performAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forItem"},{"kind":"text","text":" "},{"kind":"internalParam","text":"item"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An item in the help menu."}]}],"name":"item"}],"kind":"parameters"},{"kind":"content","content":[{"text":"Discussion","anchor":"Discussion","type":"heading","level":2},{"inlineContent":[{"text":"The default implementation brings up Help Viewer for a Help item.","type":"text"}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsuserinterfaceitemsearching/performaction(foritem:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsuserinterfaceitemsearching/performaction(foritem:)"]}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemSearching/searchForItems(withSearch:resultLimit:matchedItemHandler:)":{"abstract":[{"type":"text","text":"Search for the specified items, with the result limit."}],"role":"symbol","title":"searchForItems(withSearch:resultLimit:matchedItemHandler:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"searchForItemsWithSearchString:resultLimit:matchedItemHandler:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemSearching/searchForItems(withSearch:resultLimit:matchedItemHandler:)","url":"/documentation/appkit/nsuserinterfaceitemsearching/searchforitems(withsearch:resultlimit:matcheditemhandler:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchForItems"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withSearch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"resultLimit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"text":"matchedItemHandler","kind":"externalParam"},{"text":": ([","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemSearching/performAction(forItem:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"performAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forItem"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"performActionForItem:","kind":"identifier"}],"url":"/documentation/appkit/nsuserinterfaceitemsearching/performaction(foritem:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemSearching/performAction(forItem:)","type":"topic","title":"performAction(forItem:)","abstract":[{"type":"text","text":"Invoked when the user selects a search result in Help menu."}],"role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemSearching":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemSearching","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSUserInterfaceItemSearching"}],"title":"NSUserInterfaceItemSearching","kind":"symbol","type":"topic","url":"/documentation/appkit/nsuserinterfaceitemsearching","abstract":[{"text":"A set of methods an app can implement to provide Spotlight for Help for its own custom help data.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NSUserInterfaceItemSearching"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS"}],"op":"replace"},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"performActionForItem:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"performActionForItem:"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemSearching"]]}},{"op":"add","path":"/topicSections","value":null},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceItemSearching/searchForItems(withSearch:resultLimit:matchedItemHandler:)"],"title":"Search Help Content","anchor":"Search-Help-Content","generated":true}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"performActionForItem:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"item"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"text":"An item in the help menu.","type":"text"}],"type":"paragraph"}],"name":"item"}],"kind":"parameters"},"path":"/primaryContentSections/1"},{"value":"searchForItemsWithSearchString:resultLimit:matchedItemHandler:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemSearching~1searchForItems(withSearch:resultLimit:matchedItemHandler:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"searchForItemsWithSearchString:resultLimit:matchedItemHandler:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemSearching~1searchForItems(withSearch:resultLimit:matchedItemHandler:)/fragments","op":"replace"},{"value":"performActionForItem:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemSearching~1performAction(forItem:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"performActionForItem:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemSearching~1performAction(forItem:)/fragments","op":"replace"},{"value":"NSUserInterfaceItemSearching","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemSearching/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSUserInterfaceItemSearching"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemSearching/fragments","op":"replace"},{"value":[{"text":"NSUserInterfaceItemSearching","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceItemSearching/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}