{
  "abstract": [
    {
      "text": "Aligns to the trailing edge.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/trailing"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSRectAlignment@NSRectAlignmentTrailing",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "trailing"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSRectAlignmentTrailing"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSRectAlignment.trailing"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "trailing"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment": {
      "abstract": [
        {
          "text": "Constants that specify alignment to an edge or a set of edges depending on the user interface layout direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSRectAlignment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRectAlignment"
        }
      ],
      "role": "symbol",
      "title": "NSRectAlignment",
      "type": "topic",
      "url": "/documentation/uikit/nsrectalignment"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/bottom": {
      "abstract": [
        {
          "text": "Aligns to the bottom edge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottom"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/bottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRectAlignmentBottom"
        }
      ],
      "role": "symbol",
      "title": "NSRectAlignment.bottom",
      "type": "topic",
      "url": "/documentation/uikit/nsrectalignment/bottom"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/bottomLeading": {
      "abstract": [
        {
          "text": "Aligns to the bottom and leading edges.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomLeading"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/bottomLeading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRectAlignmentBottomLeading"
        }
      ],
      "role": "symbol",
      "title": "NSRectAlignment.bottomLeading",
      "type": "topic",
      "url": "/documentation/uikit/nsrectalignment/bottomleading"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/bottomTrailing": {
      "abstract": [
        {
          "text": "Aligns to the bottom and trailing edges.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomTrailing"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/bottomTrailing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRectAlignmentBottomTrailing"
        }
      ],
      "role": "symbol",
      "title": "NSRectAlignment.bottomTrailing",
      "type": "topic",
      "url": "/documentation/uikit/nsrectalignment/bottomtrailing"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/leading": {
      "abstract": [
        {
          "text": "Aligns to the leading edge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leading"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/leading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRectAlignmentLeading"
        }
      ],
      "role": "symbol",
      "title": "NSRectAlignment.leading",
      "type": "topic",
      "url": "/documentation/uikit/nsrectalignment/leading"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/none": {
      "abstract": [
        {
          "text": "Has no specified alignment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRectAlignmentNone"
        }
      ],
      "role": "symbol",
      "title": "NSRectAlignment.none",
      "type": "topic",
      "url": "/documentation/uikit/nsrectalignment/none"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/top": {
      "abstract": [
        {
          "text": "Aligns to the top edge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "top"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/top",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRectAlignmentTop"
        }
      ],
      "role": "symbol",
      "title": "NSRectAlignment.top",
      "type": "topic",
      "url": "/documentation/uikit/nsrectalignment/top"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/topLeading": {
      "abstract": [
        {
          "text": "Aligns to the top and leading edges.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topLeading"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/topLeading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRectAlignmentTopLeading"
        }
      ],
      "role": "symbol",
      "title": "NSRectAlignment.topLeading",
      "type": "topic",
      "url": "/documentation/uikit/nsrectalignment/topleading"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/topTrailing": {
      "abstract": [
        {
          "text": "Aligns to the top and trailing edges.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topTrailing"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/topTrailing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRectAlignmentTopTrailing"
        }
      ],
      "role": "symbol",
      "title": "NSRectAlignment.topTrailing",
      "type": "topic",
      "url": "/documentation/uikit/nsrectalignment/toptrailing"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/trailing": {
      "abstract": [
        {
          "text": "Aligns to the trailing edge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trailing"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/trailing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRectAlignmentTrailing"
        }
      ],
      "role": "symbol",
      "title": "NSRectAlignment.trailing",
      "type": "topic",
      "url": "/documentation/uikit/nsrectalignment/trailing"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Alignments",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/none",
        "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/top",
        "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/topLeading",
        "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/leading",
        "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/bottomLeading",
        "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/bottom",
        "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/bottomTrailing",
        "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/topTrailing"
      ],
      "title": "Alignments"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSRectAlignmentTrailing"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignmentTrailing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Alignments",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/none",
                "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/top",
                "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/topLeading",
                "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/leading",
                "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/bottomLeading",
                "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/bottom",
                "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/bottomTrailing",
                "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/topTrailing"
              ],
              "title": "Alignments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSRectAlignmentTrailing"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1leading/title",
          "value": "NSRectAlignmentLeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1leading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignmentLeading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1topTrailing/title",
          "value": "NSRectAlignmentTopTrailing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1topTrailing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignmentTopTrailing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1bottom/title",
          "value": "NSRectAlignmentBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1bottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignmentBottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment/title",
          "value": "NSRectAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1bottomLeading/title",
          "value": "NSRectAlignmentBottomLeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1bottomLeading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignmentBottomLeading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1bottomTrailing/title",
          "value": "NSRectAlignmentBottomTrailing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1bottomTrailing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignmentBottomTrailing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1trailing/title",
          "value": "NSRectAlignmentTrailing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1trailing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignmentTrailing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1none/title",
          "value": "NSRectAlignmentNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignmentNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1topLeading/title",
          "value": "NSRectAlignmentTopLeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1topLeading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignmentTopLeading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1top/title",
          "value": "NSRectAlignmentTop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1top/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignmentTop"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/nsrectalignment/trailing"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/nsrectalignment/trailing"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
