{
  "abstract": [
    {
      "text": "The matching property on a list of product IDs.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/productIDArray"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "IOUSBHost",
    "externalID": "c:@IOUSBHostMatchingPropertyKeyProductIDArray",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "productIDArray"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@IOUSBHostMatchingPropertyKey",
        "text": "IOUSBHostMatchingPropertyKey"
      }
    ],
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOUSBHostMatchingPropertyKeyProductIDArray"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "productIDArray"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "productIDArray"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@IOUSBHostMatchingPropertyKey",
              "text": "IOUSBHostMatchingPropertyKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey": {
      "abstract": [
        {
          "text": "Properties for implementing the matching service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostMatchingPropertyKey",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostmatchingpropertykey"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/configurationValue": {
      "abstract": [
        {
          "text": "The matching property for the device’s current configuration value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostMatchingPropertyKey",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/configurationValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKeyConfigurationValue"
        }
      ],
      "role": "symbol",
      "title": "configurationValue",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostmatchingpropertykey/configurationvalue"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/deviceReleaseNumber": {
      "abstract": [
        {
          "text": "The matching property for the device’s release number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceReleaseNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostMatchingPropertyKey",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/deviceReleaseNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKeyDeviceReleaseNumber"
        }
      ],
      "role": "symbol",
      "title": "deviceReleaseNumber",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostmatchingpropertykey/devicereleasenumber"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/productID": {
      "abstract": [
        {
          "text": "The matching property for the device’s product ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "productID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostMatchingPropertyKey",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/productID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKeyProductID"
        }
      ],
      "role": "symbol",
      "title": "productID",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostmatchingpropertykey/productid"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/productIDArray": {
      "abstract": [
        {
          "text": "The matching property on a list of product IDs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "productIDArray"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostMatchingPropertyKey",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/productIDArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKeyProductIDArray"
        }
      ],
      "role": "symbol",
      "title": "productIDArray",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostmatchingpropertykey/productidarray"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/productIDMask": {
      "abstract": [
        {
          "text": "The matching property on a mask of product IDs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "productIDMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostMatchingPropertyKey",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/productIDMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKeyProductIDMask"
        }
      ],
      "role": "symbol",
      "title": "productIDMask",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostmatchingpropertykey/productidmask"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/speed": {
      "abstract": [
        {
          "text": "The matching property for the device’s enumeration speed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "speed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostMatchingPropertyKey",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/speed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKeySpeed"
        }
      ],
      "role": "symbol",
      "title": "speed",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostmatchingpropertykey/speed"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/vendorID": {
      "abstract": [
        {
          "text": "The matching property for the device’s vendor ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vendorID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOUSBHostMatchingPropertyKey",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/vendorID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKeyVendorID"
        }
      ],
      "role": "symbol",
      "title": "vendorID",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostmatchingpropertykey/vendorid"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Device-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/vendorID",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/productID",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/deviceReleaseNumber",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/configurationValue",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/speed",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/productIDMask"
      ],
      "title": "Device Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOUSBHostMatchingPropertyKeyProductIDArray"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKeyProductIDArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iousbhost/documentation/IOUSBHost"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Device-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/vendorID",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/productID",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/deviceReleaseNumber",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/configurationValue",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/speed",
                "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey/productIDMask"
              ],
              "title": "Device Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@IOUSBHostMatchingPropertyKey",
                    "text": "IOUSBHostMatchingPropertyKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "IOUSBHostMatchingPropertyKeyProductIDArray"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1configurationValue/title",
          "value": "IOUSBHostMatchingPropertyKeyConfigurationValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1configurationValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKeyConfigurationValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey/title",
          "value": "IOUSBHostMatchingPropertyKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1productID/title",
          "value": "IOUSBHostMatchingPropertyKeyProductID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1productID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKeyProductID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1deviceReleaseNumber/title",
          "value": "IOUSBHostMatchingPropertyKeyDeviceReleaseNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1deviceReleaseNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKeyDeviceReleaseNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1productIDArray/title",
          "value": "IOUSBHostMatchingPropertyKeyProductIDArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1productIDArray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKeyProductIDArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1productIDMask/title",
          "value": "IOUSBHostMatchingPropertyKeyProductIDMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1productIDMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKeyProductIDMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1vendorID/title",
          "value": "IOUSBHostMatchingPropertyKeyVendorID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1vendorID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKeyVendorID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1speed/title",
          "value": "IOUSBHostMatchingPropertyKeySpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey~1speed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKeySpeed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/iousbhostmatchingpropertykey/productidarray"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iousbhost/iousbhostmatchingpropertykey/productidarray"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
