{
  "abstract": [
    {
      "text": "Make text legible on all devices the player chooses to run your game on.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/adapting-your-game-interface-for-smaller-screens"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Adapting your game interface for smaller screens"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Great games create engaging, immersive experiences through thoughtful design. Develop a game that’s responsive and easy to use by considering all aspects of design, including display sizes, device orientation, and text legibility. It’s crucial to plan this phase as early as possible and allocate sufficient resources and time within your team to ensure effective adaptation. For platform-specific design guidance, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/design/human-interface-guidelines/platforms",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Menus and labels — which can display a combination of text, symbols, or interface icons — are ubiquitous throughout a game’s interface, so most players already know how to use them. Utilizing menus and labels consistently in your game can help make your experience feel familiar and easy to learn.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Consider the best practices below to ensure that your in-game menus and UI components interact well on all platforms:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Adopt consistent layouts that adapt to various contexts.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Render adaptable menus and labels.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Handle multiple interaction methods.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Test on all supported devices.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "In addition to menus and labels, take advantage of high-resolution displays, Apple silicon, external game controllers, headphones, and speakers. To learn more about creating games for Apple platforms, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/games/pathway/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Render-adaptable-menus-and-labels",
          "level": 3,
          "text": "Render adaptable menus and labels",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Apple devices have a variety of screen characteristics, such as sizes, resolutions, and aspect ratios. When people download your game from the App Store, they expect to enjoy it on all their devices, whether they use iPhone SE or iPad Pro. Making the menus and labels in your game look and work great on every screen is important.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When using Apple devices, people can change the text size of the whole system via the Settings app, and they expect the text in your menus and labels to stay consistent with the setting. Make sure the text in your menus and labels adapt to different settings.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The system-provided UI frameworks, such as SwiftUI, UIKit, and AppKit, have the capability to automatically lay out UI elements based on different screen characteristics, and can automatically adjust the layout for right-to-left languages such as Arabic and Hebrew. An app’s UI that you implement with these frameworks automatically adapts to different screens and languages.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Whenever possible, use the menus and labels the UI frameworks provide to implement your app’s UI, and configure them in the following way so they automatically adapt to the platforms:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Adopt the layout mechanism the UI frameworks provide to let the system position your menus and labels. Avoid using fixed-size UI elements. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/design/human-interface-guidelines/layout",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Adopt text styles when setting up your menus and labels. Avoid using fixed-size fonts. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/scaling-fonts-automatically",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "For apps that draw menus and labels with code or implement them using middleware, make the menus and labels adaptable by doing the following:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Streamline design for smaller interfaces. Start with essential functionality for compact devices. Utilize the advantages of larger screens and enhanced capabilities to enrich the user experience with additional features and access options.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Make your menus and labels adapt to different device orientations, if your app supports both portrait and landscape mode.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use aspect ratios to maintain proportion. Consider which UI elements need to maintain a consistent aspect ratio, preserving their width-to-height proportions across different screen sizes and resolutions.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "When drawing text for your menus and labels:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Choose an appropriate font and size so the text is comfortably legible. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/design/human-interface-guidelines/typography",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Update the text size when the user changes the preferred content size.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Make the text no smaller than the recommended minimum text size for each platform so it’s readable on all devices.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The system uses points to measure font size. ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "Points",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " are a logical unit independent from the physical screen size and resolution. If necessary, use the following code to convert a font size from points to drawable pixels:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "func sizeOfFontInDrawablePixels(with layer: CAMetalLayer, fontSizeInPoints: CGFloat) -> CGFloat {",
                    "    // Calculates how many drawable pixels are in one abstract point.",
                    "    // Assumes the CAMetalLayer.contentsGravity is set to its default value of 'resize'.",
                    "    let pixelsInPoint = Double(layer.drawableSize.width / layer.bounds.size.width)",
                    "    let fontSizeInPixels = pixelsInPoint * fontSizeInPoints",
                    "    return fontSizeInPixels",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "- (CGFloat)sizeOfFontInDrawablePixelsWithLayer:(CAMetalLayer *)layer fontSizeInPoints:(CGFloat)fontSizeInPoints {",
                    "    // Calculates how many drawable pixels are in one abstract point.",
                    "    // Assumes the CAMetalLayer.contentsGravity is set to its default value of 'kCAGravityResize'.",
                    "    CGFloat pixelsInPoint = layer.drawableSize.width / layer.bounds.size.width;",
                    "    CGFloat fontSizeInPixels = pixelsInPoint * fontSizeInPoints;",
                    "    return fontSizeInPixels;",
                    "}"
                  ],
                  "syntax": "objective-c",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "anchor": "Handle-multiple-interaction-methods",
          "level": 3,
          "text": "Handle multiple interaction methods",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Consider how your game handles interactions with different input methods, like mouse, keyboard, game controllers, touch, and spatial user interactions. Take advantage of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/GameController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " framework to create a unified approach to handling these interactions for your players. To learn more about receiving controller input by either polling or callbacks, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/GameController/handling-input-events",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Below are considerations for smaller devices:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Consider menu navigation element size. Ensure that these elements are large enough, especially for touch input, even if the proportions remain unchanged.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use accessibility APIs and developer tools. Deliver high-quality experiences for everyone, including players with disabilities.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Take advantage of built-in accessibility features like Multi-Touch, VoiceOver, Switch Control, Guided Access, Text to Speech, closed-captioned or audio-described video, and more. See ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/accessibility/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more information about building accessible games on Apple platforms.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Test-on-all-supported-devices",
          "level": 3,
          "text": "Test on all supported devices",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use a physical device to test the behavior and user experience for your game’s menus on every supported device. Otherwise, use Simulator or an approximated environment on Mac, with proper display resolution, scale, and interaction methods. For more guidance on testing your game in Simulator, see the resources below:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Xcode/running-your-app-in-simulator-or-on-a-device",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Xcode/testing-in-simulator-versus-testing-on-hardware-devices",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Xcode/testing-complex-hardware-device-scenarios-in-simulator",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Xcode/identifying-graphics-and-animations-issues-in-simulator",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "If you use middleware in your games, follow their guidelines on testing multiple form factors.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/GameController"
    },
    "doc://com.apple.documentation/documentation/GameController/handling-input-events": {
      "abstract": [
        {
          "text": "Receive controller input using either polling or callbacks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/GameController/handling-input-events",
      "kind": "article",
      "role": "article",
      "title": "Handling input events",
      "type": "topic",
      "url": "/documentation/GameController/handling-input-events"
    },
    "doc://com.apple.documentation/documentation/UIKit/scaling-fonts-automatically": {
      "abstract": [
        {
          "text": "Scale text in your interface automatically using Dynamic Type.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/scaling-fonts-automatically",
      "kind": "article",
      "role": "article",
      "title": "Scaling Fonts Automatically",
      "type": "topic",
      "url": "/documentation/UIKit/scaling-fonts-automatically"
    },
    "doc://com.apple.documentation/documentation/Xcode/identifying-graphics-and-animations-issues-in-simulator": {
      "abstract": [
        {
          "text": "Reveal performance and display issues in your views with color overlays, and slow down animations to debug and improve them.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/identifying-graphics-and-animations-issues-in-simulator",
      "kind": "article",
      "role": "article",
      "title": "Identifying graphics and animations issues in Simulator",
      "type": "topic",
      "url": "/documentation/Xcode/identifying-graphics-and-animations-issues-in-simulator"
    },
    "doc://com.apple.documentation/documentation/Xcode/running-your-app-in-simulator-or-on-a-device": {
      "abstract": [
        {
          "text": "Launch your app in a simulated iOS, iPadOS, tvOS, visionOS, or watchOS device, or on a device connected to a Mac.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/running-your-app-in-simulator-or-on-a-device",
      "kind": "article",
      "role": "article",
      "title": "Running your app in Simulator or on a device",
      "type": "topic",
      "url": "/documentation/Xcode/running-your-app-in-simulator-or-on-a-device"
    },
    "doc://com.apple.documentation/documentation/Xcode/testing-complex-hardware-device-scenarios-in-simulator": {
      "abstract": [
        {
          "text": "Test hardware device-specific scenarios, such as Face ID or Touch ID authentication, fall detection, getting a memory warning, or location changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/testing-complex-hardware-device-scenarios-in-simulator",
      "kind": "article",
      "role": "article",
      "title": "Testing complex hardware device scenarios in Simulator",
      "type": "topic",
      "url": "/documentation/Xcode/testing-complex-hardware-device-scenarios-in-simulator"
    },
    "doc://com.apple.documentation/documentation/Xcode/testing-in-simulator-versus-testing-on-hardware-devices": {
      "abstract": [
        {
          "text": "Review the differences between Simulator and hardware devices to determine which you should choose to test a scenario.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/testing-in-simulator-versus-testing-on-hardware-devices",
      "kind": "article",
      "role": "article",
      "title": "Testing in Simulator versus testing on hardware devices",
      "type": "topic",
      "url": "/documentation/Xcode/testing-in-simulator-versus-testing-on-hardware-devices"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/managing-your-game-window-for-metal-in-macos": {
      "abstract": [
        {
          "text": "Set up a window and view for optimally displaying your Metal content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/managing-your-game-window-for-metal-in-macos",
      "kind": "article",
      "role": "article",
      "title": "Managing your game window for Metal in macOS",
      "type": "topic",
      "url": "/documentation/metal/managing-your-game-window-for-metal-in-macos"
    },
    "https://developer.apple.com/accessibility/": {
      "identifier": "https://developer.apple.com/accessibility/",
      "title": "Accessibility",
      "titleInlineContent": [
        {
          "text": "Accessibility",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/accessibility/"
    },
    "https://developer.apple.com/design/human-interface-guidelines/layout": {
      "identifier": "https://developer.apple.com/design/human-interface-guidelines/layout",
      "title": "Human Interface Guidelines > Layout",
      "titleInlineContent": [
        {
          "text": "Human Interface Guidelines > Layout",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/design/human-interface-guidelines/layout"
    },
    "https://developer.apple.com/design/human-interface-guidelines/platforms": {
      "identifier": "https://developer.apple.com/design/human-interface-guidelines/platforms",
      "title": "Human Interface Guidelines > Platforms",
      "titleInlineContent": [
        {
          "text": "Human Interface Guidelines > Platforms",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/design/human-interface-guidelines/platforms"
    },
    "https://developer.apple.com/design/human-interface-guidelines/typography": {
      "identifier": "https://developer.apple.com/design/human-interface-guidelines/typography",
      "title": "Human Interface Guidelines > Typography",
      "titleInlineContent": [
        {
          "text": "Human Interface Guidelines > Typography",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/design/human-interface-guidelines/typography"
    },
    "https://developer.apple.com/games/pathway/": {
      "identifier": "https://developer.apple.com/games/pathway/",
      "title": "Games Pathway",
      "titleInlineContent": [
        {
          "text": "Games Pathway",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/games/pathway/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "User-Interface",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/managing-your-game-window-for-metal-in-macos"
      ],
      "title": "User Interface"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "User-Interface",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/managing-your-game-window-for-metal-in-macos"
              ],
              "title": "User Interface"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/adapting-your-game-interface-for-smaller-screens"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/adapting-your-game-interface-for-smaller-screens"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
