{
  "abstract": [
    {
      "text": "Explicitly enumerate a ray’s intersections with acceleration structures by creating an intersection query object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/metal-sample-code-library"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/ray-tracing-with-acceleration-structures"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/control-the-ray-tracing-process-using-intersection-queries"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "12.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Control the Ray Tracing Process Using Intersection Queries"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This sample code project is associated with WWDC21 session ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc21/10149/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "2efa33e6c5c7/ControlTheRayTracingProcessUsingIntersectionQueries.zip": {
      "checksum": "2efa33e6c5c791633f522744caeb76ff6be198f85ae152e83fb036c84d2b1f18b2c385f0bf39b1d3106211dff245f9eed918da7ece9f5a957151ca8579c991b6",
      "identifier": "2efa33e6c5c7/ControlTheRayTracingProcessUsingIntersectionQueries.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/2efa33e6c5c7/ControlTheRayTracingProcessUsingIntersectionQueries.zip"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/accelerating-ray-tracing-and-motion-blur-using-metal": {
      "abstract": [
        {
          "text": "Generate ray-traced images with motion blur using GPU-based parallel processing.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/accelerating-ray-tracing-and-motion-blur-using-metal",
      "kind": "article",
      "role": "sampleCode",
      "title": "Accelerating ray tracing and motion blur using Metal",
      "type": "topic",
      "url": "/documentation/metal/accelerating-ray-tracing-and-motion-blur-using-metal"
    },
    "doc://com.apple.metal/documentation/Metal/accelerating-ray-tracing-using-metal": {
      "abstract": [
        {
          "text": "Implement ray-traced rendering using GPU-based parallel processing.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/accelerating-ray-tracing-using-metal",
      "kind": "article",
      "role": "sampleCode",
      "title": "Accelerating ray tracing using Metal",
      "type": "topic",
      "url": "/documentation/metal/accelerating-ray-tracing-using-metal"
    },
    "doc://com.apple.metal/documentation/Metal/metal-sample-code-library": {
      "abstract": [
        {
          "text": "Explore the complete set of Metal samples.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-sample-code-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Sample Code Library",
      "type": "topic",
      "url": "/documentation/metal/metal-sample-code-library"
    },
    "doc://com.apple.metal/documentation/Metal/ray-tracing-with-acceleration-structures": {
      "abstract": [
        {
          "text": "Build a representation of your scene’s geometry using triangles and bounding volumes to quickly trace rays through the scene.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/ray-tracing-with-acceleration-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Ray Tracing with Acceleration Structures",
      "type": "topic",
      "url": "/documentation/metal/ray-tracing-with-acceleration-structures"
    },
    "doc://com.apple.metal/documentation/Metal/rendering-a-curve-primitive-in-a-ray-tracing-scene": {
      "abstract": [
        {
          "text": "Implement ray traced rendering using GPU-based parallel processing.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/rendering-a-curve-primitive-in-a-ray-tracing-scene",
      "kind": "article",
      "role": "sampleCode",
      "title": "Rendering a curve primitive in a ray tracing scene",
      "type": "topic",
      "url": "/documentation/metal/rendering-a-curve-primitive-in-a-ray-tracing-scene"
    },
    "doc://com.apple.metal/documentation/Metal/rendering-reflections-in-real-time-using-ray-tracing": {
      "abstract": [
        {
          "text": "Implement realistic real-time lighting by dynamically generating reflection maps",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "by encoding a ray-tracing compute pass.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/rendering-reflections-in-real-time-using-ray-tracing",
      "kind": "article",
      "role": "sampleCode",
      "title": "Rendering reflections in real time using ray tracing",
      "type": "topic",
      "url": "/documentation/metal/rendering-reflections-in-real-time-using-ray-tracing"
    },
    "https://developer.apple.com/wwdc21/10149/": {
      "identifier": "https://developer.apple.com/wwdc21/10149/",
      "title": "10149: Enhance Your App with Metal Ray Tracing",
      "titleInlineContent": [
        {
          "text": "10149: Enhance Your App with Metal Ray Tracing",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc21/10149/"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "2efa33e6c5c7/ControlTheRayTracingProcessUsingIntersectionQueries.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Ray-Tracing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/rendering-reflections-in-real-time-using-ray-tracing",
        "doc://com.apple.metal/documentation/Metal/accelerating-ray-tracing-using-metal",
        "doc://com.apple.metal/documentation/Metal/accelerating-ray-tracing-and-motion-blur-using-metal",
        "doc://com.apple.metal/documentation/Metal/rendering-a-curve-primitive-in-a-ray-tracing-scene"
      ],
      "title": "Ray Tracing"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Ray-Tracing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/rendering-reflections-in-real-time-using-ray-tracing",
                "doc://com.apple.metal/documentation/Metal/accelerating-ray-tracing-using-metal",
                "doc://com.apple.metal/documentation/Metal/accelerating-ray-tracing-and-motion-blur-using-metal",
                "doc://com.apple.metal/documentation/Metal/rendering-a-curve-primitive-in-a-ray-tracing-scene"
              ],
              "title": "Ray Tracing"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/control-the-ray-tracing-process-using-intersection-queries"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/control-the-ray-tracing-process-using-intersection-queries"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
