{
  "abstract": [
    {
      "text": "Learn how Metal organizes compute-processing workloads.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/compute-passes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/creating-threads-and-threadgroups"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Creating Threads and Threadgroups"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Recall from ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/processing-a-texture-in-a-compute-function",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that when you dispatch your compute pass, Metal executes your kernel function over a 1D, 2D, or 3D grid. Each point in the grid represents a single instance of your kernel function, referred to as a ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "thread",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ". For example, in image processing, the grid is typically a 2D matrix of threads—representing the entire image—with each thread corresponding to a single pixel of the image being processed.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Threads are organized into ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "threadgroups",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " that are executed together and can share a common block of memory. While sometimes kernel functions are designed so that threads run independently of each other, it’s also common for threads in a threadgroup to collaborate on their working set.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Identification-of-Threads-by-Position-in-Grid",
          "level": 3,
          "text": "Identification of Threads by Position in Grid",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "identifier": "/documentation/metal/compute_passes/creating_threads_and_threadgroups#2928936",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " shows how an image being processed by a compute kernel is divided into threadgroups and how each threadgroup is composed of individual threads. Each thread processes a single pixel.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2928936",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A thread can be identified by its position in the grid; it’s this unique position that allows your kernel function to do something different for each thread. The sample kernel function in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/processing-a-texture-in-a-compute-function",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", below, shows how a thread’s position in the grid is passed into the function as a parameter. In this case, the parameter, ",
              "type": "text"
            },
            {
              "code": "gid",
              "type": "codeVoice"
            },
            {
              "text": ", is a vector representing 2D coordinates and is used to both read from and write to a particular location in a texture.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "kernel void",
            "grayscaleKernel(texture2d<half, access::read>  inTexture  [[texture(AAPLTextureIndexInput)]],",
            "                texture2d<half, access::write> outTexture [[texture(AAPLTextureIndexOutput)]],",
            "                uint2                          gid        [[thread_position_in_grid]])",
            "{",
            "    if((gid.x >= outTexture.get_width()) || (gid.y >= outTexture.get_height()))",
            "    {",
            "        return;",
            "    }",
            "    half4 inColor  = inTexture.read(gid);",
            "    half  gray     = dot(inColor.rgb, kRec709Luma);",
            "    outTexture.write(half4(gray, gray, gray, 1.0), gid);",
            "}"
          ],
          "syntax": "metal",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "code": "[[thread_position_in_grid]]",
              "type": "codeVoice"
            },
            {
              "text": " is an ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "attribute qualifier",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ". Attribute qualifiers, identifiable by their double square-bracket syntax, allow kernel parameters to be bound to resources and built-in variables, in this case the thread’s position in the grid to the kernel function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, given a grid of 16 x 16 threads partitioned into 2 x 4 threadgroups of 8 x 4 threads, a single thread (shown in ",
              "type": "text"
            },
            {
              "identifier": "/documentation/metal/compute_passes/creating_threads_and_threadgroups#2929009",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in red) has a position in the grid of (9,10):",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2929009",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Identification-of-Threads-by-Position-in-Threadgroup",
          "level": 3,
          "text": "Identification of Threads by Position in Threadgroup",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A thread’s position in its threadgroup is also available as the attribute qualifier ",
              "type": "text"
            },
            {
              "code": "[[thread_position_in_threadgroup]]",
              "type": "codeVoice"
            },
            {
              "text": ", and a threadgroup’s position in the grid is available as ",
              "type": "text"
            },
            {
              "code": "[[threadgroup_position_in_grid]]",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Depending on the shape of the grid, these position attributes are either a scalar value, or a two- or three-element vector. In the case of a 2D grid, position attributes are two-element vectors, with the origin at the top-left.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The thread identified in ",
              "type": "text"
            },
            {
              "identifier": "/documentation/metal/compute_passes/creating_threads_and_threadgroups#2929009",
              "isActive": true,
              "overridingTitle": "Figure 2",
              "overridingTitleInlineContent": [
                {
                  "text": "Figure 2",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " is in the threadgroup with a position in the grid of (1,2), and its position in that threadgroup is (1,2), as shown in ",
              "type": "text"
            },
            {
              "identifier": "/documentation/metal/compute_passes/creating_threads_and_threadgroups#2929421",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2929421",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Using the following code, you can also calculate a thread’s position in the grid based on its position in its threadgroup and that threadgroup’s size and position in the grid:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "kernel void ",
            "myKernel(uint2 threadgroup_position_in_grid   [[ threadgroup_position_in_grid ]],",
            "         uint2 thread_position_in_threadgroup [[ thread_position_in_threadgroup ]],",
            "         uint2 threads_per_threadgroup        [[ threads_per_threadgroup ]]) ",
            "{",
            "    ",
            "    uint2 thread_position_in_grid = ",
            "        (threadgroup_position_in_grid * threads_per_threadgroup) + ",
            "        thread_position_in_threadgroup;",
            "}"
          ],
          "syntax": "metal",
          "type": "codeListing"
        },
        {
          "anchor": "SIMD-Groups",
          "level": 3,
          "text": "SIMD Groups",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The threads in a threadgroup are further organized into single-instruction, multiple-data (SIMD) groups, also known as ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "warps",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "wavefronts",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", that execute concurrently. The threads in a SIMD group execute the same code. Avoid writing code that could cause your kernel function to ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "diverge",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": "; that is, to follow different code paths. A typical example of divergence is caused by using an ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "if",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " statement. Even if a single thread in a SIMD group takes a different path from the others, all threads in that group execute both branches, and the execution time for the group is the sum of the execution time of both branches.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The division of threadgroups into SIMD groups is defined by Metal. It remains constant for the duration of a kernel’s execution, across dispatches of a given kernel with the same launch parameters, and from one threadgroup to another within the dispatch.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The number of threads in a SIMD group is returned by the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLComputePipelineState/threadExecutionWidth",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " of your compute pipeline state object. Attribute qualifiers allow you to access a SIMD group’s scalar index within a threadgroup, and a thread’s scalar index within a SIMD group:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The unique scalar index of a SIMD group in its threadgroup.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "[[simdgroup_index_in_threadgroup]]",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The unique scalar index of a thread in its SIMD group, also known as the ",
                        "type": "text"
                      },
                      {
                        "inlineContent": [
                          {
                            "text": "lane ID",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "[[thread_index_in_simdgroup]]",
                    "type": "codeVoice"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "Although threadgroups can be multidimensional, SIMD groups are 1D. Therefore, a thread’s position within a SIMD group is a scalar value for all threadgroup shapes. The SIMD group size remains constant and is unaffected by the threadgroup size.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, using the same 16 x 16 grid shown in ",
              "type": "text"
            },
            {
              "identifier": "/documentation/metal/compute_passes/creating_threads_and_threadgroups#2929009",
              "isActive": true,
              "overridingTitle": "Figure 2",
              "overridingTitleInlineContent": [
                {
                  "text": "Figure 2",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": ", with a thread execution width of 16, a single 8 x 4 threadgroup consists of 2 SIMD groups. Because a SIMD group contains 16 threads, each SIMD group constitutes 2 rows in the threadgroup:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2928945",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The thread shown in red in ",
              "type": "text"
            },
            {
              "identifier": "/documentation/metal/compute_passes/creating_threads_and_threadgroups#2929426",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " has a ",
              "type": "text"
            },
            {
              "code": "[[simdgroup_index_in_threadgroup]]",
              "type": "codeVoice"
            },
            {
              "text": " value of 1 and a ",
              "type": "text"
            },
            {
              "code": "[[thread_index_in_simdgroup]]",
              "type": "codeVoice"
            },
            {
              "text": " value of 1:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2929426",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "/documentation/metal/compute_passes/creating_threads_and_threadgroups#2928936": {
      "identifier": "/documentation/metal/compute_passes/creating_threads_and_threadgroups#2928936",
      "title": "Figure 1",
      "titleInlineContent": [
        {
          "text": "Figure 1",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "/documentation/metal/compute_passes/creating_threads_and_threadgroups#2928936"
    },
    "/documentation/metal/compute_passes/creating_threads_and_threadgroups#2929009": {
      "identifier": "/documentation/metal/compute_passes/creating_threads_and_threadgroups#2929009",
      "title": "Figure 2",
      "titleInlineContent": [
        {
          "text": "Figure 2",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "/documentation/metal/compute_passes/creating_threads_and_threadgroups#2929009"
    },
    "/documentation/metal/compute_passes/creating_threads_and_threadgroups#2929421": {
      "identifier": "/documentation/metal/compute_passes/creating_threads_and_threadgroups#2929421",
      "title": "Figure 3",
      "titleInlineContent": [
        {
          "text": "Figure 3",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "/documentation/metal/compute_passes/creating_threads_and_threadgroups#2929421"
    },
    "/documentation/metal/compute_passes/creating_threads_and_threadgroups#2929426": {
      "identifier": "/documentation/metal/compute_passes/creating_threads_and_threadgroups#2929426",
      "title": "Figure 5",
      "titleInlineContent": [
        {
          "text": "Figure 5",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "/documentation/metal/compute_passes/creating_threads_and_threadgroups#2929426"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLComputeCommandEncoder": {
      "abstract": [
        {
          "text": "An interface for dispatching commands to encode in a compute pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLComputeCommandEncoder"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLComputeCommandEncoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLComputeCommandEncoder"
        }
      ],
      "role": "symbol",
      "title": "MTLComputeCommandEncoder",
      "type": "topic",
      "url": "/documentation/metal/mtlcomputecommandencoder"
    },
    "doc://com.apple.metal/documentation/Metal/MTLComputePipelineState/threadExecutionWidth": {
      "abstract": [
        {
          "text": "The number of threads that the GPU executes simultaneously.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "threadExecutionWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLComputePipelineState/threadExecutionWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "threadExecutionWidth"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "threadExecutionWidth",
      "type": "topic",
      "url": "/documentation/metal/mtlcomputepipelinestate/threadexecutionwidth"
    },
    "doc://com.apple.metal/documentation/Metal/calculating-threadgroup-and-grid-sizes": {
      "abstract": [
        {
          "text": "Calculate the optimum sizes for threadgroups and grids when dispatching compute-processing workloads.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/calculating-threadgroup-and-grid-sizes",
      "kind": "article",
      "role": "article",
      "title": "Calculating Threadgroup and Grid Sizes",
      "type": "topic",
      "url": "/documentation/metal/calculating-threadgroup-and-grid-sizes"
    },
    "doc://com.apple.metal/documentation/Metal/compute-passes": {
      "abstract": [
        {
          "text": "Encode a compute pass that runs computations in parallel on a thread grid, processing and manipulating Metal resource data on multiple cores of a GPU.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/compute-passes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Compute Passes",
      "type": "topic",
      "url": "/documentation/metal/compute-passes"
    },
    "doc://com.apple.metal/documentation/Metal/processing-a-texture-in-a-compute-function": {
      "abstract": [
        {
          "text": "Perform parallel calculations on structured data by placing the data in textures.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/processing-a-texture-in-a-compute-function",
      "kind": "article",
      "role": "sampleCode",
      "title": "Processing a Texture in a Compute Function",
      "type": "topic",
      "url": "/documentation/metal/processing-a-texture-in-a-compute-function"
    },
    "media-2928936": {
      "alt": "A grid divided into threadgroups that are composed of individual threads.",
      "identifier": "media-2928936",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/968ef737b344f13ae030c348b9ec2267/media-2928936@2x.png"
        }
      ]
    },
    "media-2928945": {
      "alt": "A threadgroup composed of 2 SIMD groups.",
      "identifier": "media-2928945",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/85c2ac05dedad457f78499527ecec88a/media-2928945@2x.png"
        }
      ]
    },
    "media-2929009": {
      "alt": "The position of a single thread in a 16 x 16 grid.",
      "identifier": "media-2929009",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/f81f3847d494742e2d253658ddbe8804/media-2929009@2x.png"
        }
      ]
    },
    "media-2929421": {
      "alt": "The position of a single thread in a threadgroup.",
      "identifier": "media-2929421",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c931c075f557ee6b7e5fae31270cde1f/media-2929421@2x.png"
        }
      ]
    },
    "media-2929426": {
      "alt": "The position of a single thread in a SIMD group.",
      "identifier": "media-2929426",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/604a6149e5d08c9ce8c3f7146c7e7e44/media-2929426@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Encoding-a-Compute-Pass",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/calculating-threadgroup-and-grid-sizes",
        "doc://com.apple.metal/documentation/Metal/MTLComputeCommandEncoder"
      ],
      "title": "Encoding a Compute Pass"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Encoding-a-Compute-Pass",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/calculating-threadgroup-and-grid-sizes",
                "doc://com.apple.metal/documentation/Metal/MTLComputeCommandEncoder"
              ],
              "title": "Encoding a Compute Pass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComputePipelineState~1threadExecutionWidth/title",
          "value": "threadExecutionWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComputePipelineState~1threadExecutionWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "threadExecutionWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComputeCommandEncoder/title",
          "value": "MTLComputeCommandEncoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComputeCommandEncoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLComputeCommandEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComputeCommandEncoder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLComputeCommandEncoder"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/creating-threads-and-threadgroups"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/creating-threads-and-threadgroups"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
