{
  "abstract": [
    {
      "text": "Define custom shader behavior at runtime by creating functions from existing ones and preferentially linking to others in a dynamic library.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/shader-libraries"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/customizing-shaders-using-function-pointers-and-stitching"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "12.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "13.4",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Customizing shaders using function pointers and stitching"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This sample code project is associated with WWDC2021 session ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc21/10229/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and WWDC2022 session ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc22/6596",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "7baf5a6c7514/CustomizingShadersUsingFunctionPointersAndStitching.zip": {
      "checksum": "7baf5a6c75141f52bae24fb3f2a664ef6a04f07f0f6919d364bdef31f12f1ada0be0c409809d8fde112976a8d6ef7ac5dbc8e0e24f57497e80a8110623496eb6",
      "identifier": "7baf5a6c7514/CustomizingShadersUsingFunctionPointersAndStitching.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/7baf5a6c7514/CustomizingShadersUsingFunctionPointersAndStitching.zip"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingAttribute": {
      "abstract": [
        {
          "text": "A protocol to identify types that customize how the Metal compiler stitches a function together.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFunctionStitchingAttribute"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFunctionStitchingAttribute"
        }
      ],
      "role": "symbol",
      "title": "MTLFunctionStitchingAttribute",
      "type": "topic",
      "url": "/documentation/metal/mtlfunctionstitchingattribute"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingAttributeAlwaysInline": {
      "abstract": [
        {
          "text": "An attribute to specify that Metal needs to inline all of the function calls when generating the stitched function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFunctionStitchingAttributeAlwaysInline"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingAttributeAlwaysInline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFunctionStitchingAttributeAlwaysInline"
        }
      ],
      "role": "symbol",
      "title": "MTLFunctionStitchingAttributeAlwaysInline",
      "type": "topic",
      "url": "/documentation/metal/mtlfunctionstitchingattributealwaysinline"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingFunctionNode": {
      "abstract": [
        {
          "text": "A call graph node that describes a function call and its inputs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFunctionStitchingFunctionNode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingFunctionNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFunctionStitchingFunctionNode"
        }
      ],
      "role": "symbol",
      "title": "MTLFunctionStitchingFunctionNode",
      "type": "topic",
      "url": "/documentation/metal/mtlfunctionstitchingfunctionnode"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingGraph": {
      "abstract": [
        {
          "text": "A description of a new stitched function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFunctionStitchingGraph"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingGraph",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFunctionStitchingGraph"
        }
      ],
      "role": "symbol",
      "title": "MTLFunctionStitchingGraph",
      "type": "topic",
      "url": "/documentation/metal/mtlfunctionstitchinggraph"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingInputNode": {
      "abstract": [
        {
          "text": "A call graph node that describes an input to the call graph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFunctionStitchingInputNode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingInputNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFunctionStitchingInputNode"
        }
      ],
      "role": "symbol",
      "title": "MTLFunctionStitchingInputNode",
      "type": "topic",
      "url": "/documentation/metal/mtlfunctionstitchinginputnode"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingNode": {
      "abstract": [
        {
          "text": "A protocol to identify call graph nodes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFunctionStitchingNode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFunctionStitchingNode"
        }
      ],
      "role": "symbol",
      "title": "MTLFunctionStitchingNode",
      "type": "topic",
      "url": "/documentation/metal/mtlfunctionstitchingnode"
    },
    "doc://com.apple.metal/documentation/Metal/MTLStitchedLibraryDescriptor": {
      "abstract": [
        {
          "text": "A description of a new library of procedurally generated functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLStitchedLibraryDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLStitchedLibraryDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLStitchedLibraryDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLStitchedLibraryDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlstitchedlibrarydescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/shader-libraries": {
      "abstract": [
        {
          "text": "Manage and load your app’s Metal shaders.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/shader-libraries",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Shader Libraries",
      "type": "topic",
      "url": "/documentation/metal/shader-libraries"
    },
    "https://developer.apple.com/wwdc21/10229/": {
      "identifier": "https://developer.apple.com/wwdc21/10229/",
      "title": "10229: Discover compilation workflows in Metal",
      "titleInlineContent": [
        {
          "text": "10229: Discover compilation workflows in Metal",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc21/10229/"
    },
    "https://developer.apple.com/wwdc22/6596": {
      "identifier": "https://developer.apple.com/wwdc22/6596",
      "title": "6596: Target and optimize GPU binaries with Metal 3",
      "titleInlineContent": [
        {
          "text": "6596: Target and optimize GPU binaries with Metal 3",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc22/6596"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "7baf5a6c7514/CustomizingShadersUsingFunctionPointersAndStitching.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Stitched-Function-Libraries",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLStitchedLibraryDescriptor",
        "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingGraph",
        "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingInputNode",
        "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingFunctionNode",
        "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingNode",
        "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingAttributeAlwaysInline",
        "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingAttribute"
      ],
      "title": "Stitched Function Libraries"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Stitched-Function-Libraries",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLStitchedLibraryDescriptor",
                "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingGraph",
                "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingInputNode",
                "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingFunctionNode",
                "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingNode",
                "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingAttributeAlwaysInline",
                "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingAttribute"
              ],
              "title": "Stitched Function Libraries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingAttributeAlwaysInline/title",
          "value": "MTLFunctionStitchingAttributeAlwaysInline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingAttributeAlwaysInline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionStitchingAttributeAlwaysInline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingAttributeAlwaysInline/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionStitchingAttributeAlwaysInline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingGraph/title",
          "value": "MTLFunctionStitchingGraph"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingGraph/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionStitchingGraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingGraph/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionStitchingGraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingFunctionNode/title",
          "value": "MTLFunctionStitchingFunctionNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingFunctionNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionStitchingFunctionNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingFunctionNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionStitchingFunctionNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingAttribute/title",
          "value": "MTLFunctionStitchingAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionStitchingAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingAttribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionStitchingAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingInputNode/title",
          "value": "MTLFunctionStitchingInputNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingInputNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionStitchingInputNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingInputNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionStitchingInputNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStitchedLibraryDescriptor/title",
          "value": "MTLStitchedLibraryDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStitchedLibraryDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStitchedLibraryDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStitchedLibraryDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStitchedLibraryDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingNode/title",
          "value": "MTLFunctionStitchingNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionStitchingNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionStitchingNode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/customizing-shaders-using-function-pointers-and-stitching"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/customizing-shaders-using-function-pointers-and-stitching"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
