{
  "abstract": [
    {
      "text": "Implement a custom operation that uses Metal kernels to accelerate neural-network training performance.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/metal-sample-code-library"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/customizing-a-tensorflow-operation"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Customizing a TensorFlow operation"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This sample code project is associated with WWDC22 session ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc22/10063/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Configure-the-sample-code",
          "level": 3,
          "text": "Configure the sample code",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Follow the instructions in ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/metal/tensorflow-plugin/",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Install ffmpeg using ",
                      "type": "text"
                    },
                    {
                      "code": "brew",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "code": [
                    "brew install ffmpeg"
                  ],
                  "syntax": null,
                  "type": "codeListing"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Install the required Python packages.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "code": [
                    "pip install -r requirements.txt"
                  ],
                  "syntax": null,
                  "type": "codeListing"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use ",
                      "type": "text"
                    },
                    {
                      "code": "make",
                      "type": "codeVoice"
                    },
                    {
                      "text": " to build the custom operation with Xcode.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "code": [
                    "cd hash_encoder",
                    "make",
                    "cd .."
                  ],
                  "syntax": null,
                  "type": "codeListing"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Run the sample.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "code": [
                    "python tiny_nerf_hash.py"
                  ],
                  "syntax": null,
                  "type": "codeListing"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "View the resutls in the ",
                      "type": "text"
                    },
                    {
                      "code": "result_nerf_hash",
                      "type": "codeVoice"
                    },
                    {
                      "text": " folder.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "To compare the performance benefits provided by this sample, you can run the original NeRF sample code included with the project.  View the resutls in the ",
                      "type": "text"
                    },
                    {
                      "code": "result_nerf_mlp",
                      "type": "codeVoice"
                    },
                    {
                      "text": " folder.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "code": [
                    "python tiny_nerf_mlp.py"
                  ],
                  "syntax": null,
                  "type": "codeListing"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The sample uses low-resolution (100x100) images by default. You can alternatively use a high-resolution version of the data to produce a clearer rendering.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "da6dd297d52f/CustomizingATensorFlowOperation.zip": {
      "checksum": "da6dd297d52fd5f71e862c63fab4d97d3ff718f9c306f19b89e813f69d71ef66912e192cc23dd5c8d27b83dfd7a8642e9ddb29db042c58be97f4faf1103b3b0d",
      "identifier": "da6dd297d52f/CustomizingATensorFlowOperation.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/da6dd297d52f/CustomizingATensorFlowOperation.zip"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/customizing-a-pytorch-operation": {
      "abstract": [
        {
          "text": "Implement a custom operation in PyTorch that uses Metal kernels to improve performance.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/customizing-a-pytorch-operation",
      "kind": "article",
      "role": "sampleCode",
      "title": "Customizing a PyTorch operation",
      "type": "topic",
      "url": "/documentation/metal/customizing-a-pytorch-operation"
    },
    "doc://com.apple.metal/documentation/Metal/metal-sample-code-library": {
      "abstract": [
        {
          "text": "Explore the complete set of Metal samples.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-sample-code-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Sample Code Library",
      "type": "topic",
      "url": "/documentation/metal/metal-sample-code-library"
    },
    "doc://com.apple.metal/documentation/Metal/performing-calculations-on-a-gpu": {
      "abstract": [
        {
          "text": "Use Metal to find GPUs and perform calculations on them.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/performing-calculations-on-a-gpu",
      "kind": "article",
      "role": "sampleCode",
      "title": "Performing Calculations on a GPU",
      "type": "topic",
      "url": "/documentation/metal/performing-calculations-on-a-gpu"
    },
    "doc://com.apple.metal/documentation/Metal/selecting-device-objects-for-compute-processing": {
      "abstract": [
        {
          "text": "Switch dynamically between multiple GPUs to efficiently execute a compute-intensive simulation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/selecting-device-objects-for-compute-processing",
      "kind": "article",
      "role": "sampleCode",
      "title": "Selecting Device Objects for Compute Processing",
      "type": "topic",
      "url": "/documentation/metal/selecting-device-objects-for-compute-processing"
    },
    "https://developer.apple.com/metal/tensorflow-plugin/": {
      "identifier": "https://developer.apple.com/metal/tensorflow-plugin/",
      "title": "Getting started with tensorflow-metal",
      "titleInlineContent": [
        {
          "text": "Getting started with tensorflow-metal",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/metal/tensorflow-plugin/"
    },
    "https://developer.apple.com/wwdc22/10063/": {
      "identifier": "https://developer.apple.com/wwdc22/10063/",
      "title": "10063: Accelerate machine learning with Metal",
      "titleInlineContent": [
        {
          "text": "10063: Accelerate machine learning with Metal",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc22/10063/"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "da6dd297d52f/CustomizingATensorFlowOperation.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Compute-Workflows",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/performing-calculations-on-a-gpu",
        "doc://com.apple.metal/documentation/Metal/selecting-device-objects-for-compute-processing",
        "doc://com.apple.metal/documentation/Metal/customizing-a-pytorch-operation"
      ],
      "title": "Compute Workflows"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Compute-Workflows",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/performing-calculations-on-a-gpu",
                "doc://com.apple.metal/documentation/Metal/selecting-device-objects-for-compute-processing",
                "doc://com.apple.metal/documentation/Metal/customizing-a-pytorch-operation"
              ],
              "title": "Compute Workflows"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/customizing-a-tensorflow-operation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/customizing-a-tensorflow-operation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
