{
  "abstract": [
    {
      "text": "Check whether a display supports EDR.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/hdr-content"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/determining-support-for-edr-values"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Determining Support for EDR Values"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To find out whether a display can support EDR values, read the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppKit/NSScreen/maximumPotentialExtendedDynamicRangeColorComponentValue",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property on an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppKit/NSScreen",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object for that display. A value greater than 1.0 indicates that the display supports EDR values; otherwise, the display supports only SDR values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This property’s value is independent of the current state of the display. It’s possible for a display to support EDR but to be unable to present those values right now. For information about the current state of the display, check the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppKit/NSScreen/maximumExtendedDynamicRangeColorComponentValue",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AppKit/NSScreen": {
      "abstract": [
        {
          "text": "An object that describes the attributes of a computer’s monitor or screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScreen"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSScreen",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSScreen",
      "type": "topic",
      "url": "/documentation/AppKit/NSScreen"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSScreen/maximumExtendedDynamicRangeColorComponentValue": {
      "abstract": [
        {
          "text": "The current maximum color component value for the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumExtendedDynamicRangeColorComponentValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSScreen/maximumExtendedDynamicRangeColorComponentValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "maximumExtendedDynamicRangeColorComponentValue",
      "type": "topic",
      "url": "/documentation/AppKit/NSScreen/maximumExtendedDynamicRangeColorComponentValue"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSScreen/maximumPotentialExtendedDynamicRangeColorComponentValue": {
      "abstract": [
        {
          "text": "The maximum possible color component value for the screen when it’s in extended dynamic range (EDR) mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumPotentialExtendedDynamicRangeColorComponentValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSScreen/maximumPotentialExtendedDynamicRangeColorComponentValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "maximumPotentialExtendedDynamicRangeColorComponentValue",
      "type": "topic",
      "url": "/documentation/AppKit/NSScreen/maximumPotentialExtendedDynamicRangeColorComponentValue"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/displaying-hdr-content-in-a-metal-layer": {
      "abstract": [
        {
          "text": "Bring your high dynamic range (HDR) content to compatible Mac displays.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/displaying-hdr-content-in-a-metal-layer",
      "kind": "article",
      "role": "article",
      "title": "Displaying HDR Content in a Metal Layer",
      "type": "topic",
      "url": "/documentation/metal/displaying-hdr-content-in-a-metal-layer"
    },
    "doc://com.apple.metal/documentation/Metal/hdr-content": {
      "abstract": [
        {
          "text": "Take advantage of high dynamic range to present more vibrant colors in your apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/hdr-content",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HDR Content",
      "type": "topic",
      "url": "/documentation/metal/hdr-content"
    },
    "doc://com.apple.metal/documentation/Metal/implementing-tone-mapping-on-reference-displays": {
      "abstract": [
        {
          "text": "Detect reference displays and keep your content within the capabilities of the display hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/implementing-tone-mapping-on-reference-displays",
      "kind": "article",
      "role": "article",
      "title": "Implementing Tone Mapping on Reference Displays",
      "type": "topic",
      "url": "/documentation/metal/implementing-tone-mapping-on-reference-displays"
    },
    "doc://com.apple.metal/documentation/Metal/performing-your-own-tone-mapping": {
      "abstract": [
        {
          "text": "Apply your own tone mapping to get the exact behavior you want.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/performing-your-own-tone-mapping",
      "kind": "article",
      "role": "article",
      "title": "Performing Your Own Tone Mapping",
      "type": "topic",
      "url": "/documentation/metal/performing-your-own-tone-mapping"
    },
    "doc://com.apple.metal/documentation/Metal/processing-hdr-images-with-metal": {
      "abstract": [
        {
          "text": "Implement a post-processing pipeline using the latest features on Apple GPUs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/processing-hdr-images-with-metal",
      "kind": "article",
      "role": "sampleCode",
      "title": "Processing HDR Images with Metal",
      "type": "topic",
      "url": "/documentation/metal/processing-hdr-images-with-metal"
    },
    "doc://com.apple.metal/documentation/Metal/using-color-spaces-to-display-hdr-content": {
      "abstract": [
        {
          "text": "Use a color space when you don’t need to edit or process the pixel data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/using-color-spaces-to-display-hdr-content",
      "kind": "article",
      "role": "article",
      "title": "Using Color Spaces to Display HDR Content",
      "type": "topic",
      "url": "/documentation/metal/using-color-spaces-to-display-hdr-content"
    },
    "doc://com.apple.metal/documentation/Metal/using-system-tone-mapping-on-video-content": {
      "abstract": [
        {
          "text": "Use EDR metadata to apply the default system tone mapping to a layer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/using-system-tone-mapping-on-video-content",
      "kind": "article",
      "role": "article",
      "title": "Using System Tone Mapping on Video Content",
      "type": "topic",
      "url": "/documentation/metal/using-system-tone-mapping-on-video-content"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "High-Dynamic-Range-Content",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/processing-hdr-images-with-metal",
        "doc://com.apple.metal/documentation/Metal/displaying-hdr-content-in-a-metal-layer",
        "doc://com.apple.metal/documentation/Metal/using-color-spaces-to-display-hdr-content",
        "doc://com.apple.metal/documentation/Metal/using-system-tone-mapping-on-video-content",
        "doc://com.apple.metal/documentation/Metal/performing-your-own-tone-mapping",
        "doc://com.apple.metal/documentation/Metal/implementing-tone-mapping-on-reference-displays"
      ],
      "title": "High Dynamic Range Content"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "High-Dynamic-Range-Content",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/processing-hdr-images-with-metal",
                "doc://com.apple.metal/documentation/Metal/displaying-hdr-content-in-a-metal-layer",
                "doc://com.apple.metal/documentation/Metal/using-color-spaces-to-display-hdr-content",
                "doc://com.apple.metal/documentation/Metal/using-system-tone-mapping-on-video-content",
                "doc://com.apple.metal/documentation/Metal/performing-your-own-tone-mapping",
                "doc://com.apple.metal/documentation/Metal/implementing-tone-mapping-on-reference-displays"
              ],
              "title": "High Dynamic Range Content"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSScreen~1maximumPotentialExtendedDynamicRangeColorComponentValue/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CGFloat",
              "text": "CGFloat"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "maximumPotentialExtendedDynamicRangeColorComponentValue"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSScreen/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSScreen"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSScreen~1maximumExtendedDynamicRangeColorComponentValue/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CGFloat",
              "text": "CGFloat"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "maximumExtendedDynamicRangeColorComponentValue"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/determining-support-for-edr-values"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/determining-support-for-edr-values"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
