{
  "abstract": [
    {
      "text": "Use the device object’s properties to determine how you perform tasks in Metal.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/gpu-devices-and-work-submission"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/detecting-gpu-features-and-metal-software-versions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Detecting GPU Features and Metal Software Versions"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "GPUs don’t support a single common feature set. Instead, different GPUs support different capabilities. Newer, more powerful GPUs support more advanced features, letting you perform more complex tasks or perform the same task using a different technique the GPU can process more efficiently.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You need to determine which Metal features that a specific device object supports and use that information to choose your app’s behavior. For example, you might:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create multiple rendering or compute paths, and have your app dynamically choose the best option for each GPU.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Restrict some features to specific GPUs or implement different levels of functionality. For example, in a game, you might remove shadows or reduce the complexity of shadows on older GPUs.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Restrict your app so that it only runs when some GPUs are available; however, you should only use this option in extreme cases.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The version of Metal running on the system and the GPU you’re targeting determine which features are available. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object provides information about the software and hardware capabilities for a specific GPU. To see a summary of the features available in each family, see the Metal Feature Set Tables:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://developer.apple.com/metal/metal-feature-set-tables.zip",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "A new version of Metal adds multiple features to device object at the same time. You should design your app around collections of common functionality. For example, on iOS, you might design two major rendering paths: one for current and future GPUs, and one for earlier GPUs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Determine-GPU-Feature-Support",
          "level": 3,
          "text": "Determine GPU Feature Support",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Metal organizes GPUs into four major families:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use the ",
                      "type": "text"
                    },
                    {
                      "inlineContent": [
                        {
                          "text": "Common",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " family to create apps that target a range of GPUs on multiple platforms.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use the ",
                      "type": "text"
                    },
                    {
                      "inlineContent": [
                        {
                          "text": "Apple",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " family to create apps that target Apple GPUs.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use the ",
                      "type": "text"
                    },
                    {
                      "inlineContent": [
                        {
                          "text": "Mac",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " family to create apps that target GPUs on macOS systems.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use the ",
                      "type": "text"
                    },
                    {
                      "inlineContent": [
                        {
                          "text": "Mac Catalyst",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " family when building an iPadOS app to run on macOS.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "A GPU can be a member of more than one family; in most cases, a GPU supports one of the Common families and then one or more families specific to the build target.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "More recent GPUs have higher version numbers and support larger feature sets. A higher GPU version is always a superset of an earlier version in the same GPU family. For details on the individual families and version numbers, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLGPUFamily",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The code below shows how to test whether a GPU supports a particular GPU family:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "if #available(macOS 10.15, *) {",
                    "    if self.device.supportsFamily(.familyMac2) {",
                    "        // Enable features that require Mac family 2.",
                    "    }",
                    "}",
                    "else {",
                    "    // Fallback on earlier OS versions.",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "if (@available(macOS 10.15, *)) {",
                    "    if ([device supportsFamily:MTLGPUFamilyMac2])",
                    "    {",
                    "        // Enable features that require Mac family 2.",
                    "    }",
                    "}",
                    "else",
                    "{",
                    "    // Fallback on earlier OS versions.",
                    "}"
                  ],
                  "syntax": "objective-c",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "anchor": "Determine-Metal-Version-Availability",
          "level": 3,
          "text": "Determine Metal Version Availability",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Each new Metal release adds new features for supported GPUs. In addition to checking for a GPU with the correct family, ensure that the features your app needs are also there. Use ",
              "type": "text"
            },
            {
              "code": "available",
              "type": "codeVoice"
            },
            {
              "text": " statements to query whether the framework supports the features you need, as shown in the code below.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "if #available(macOS 10.15, iOS 13, tvOS 13, *) {",
                    "     // Enable newer features.",
                    "}",
                    "else",
                    "{",
                    "    // Fallback on earlier OS versions.",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "if (@available(macOS 10.15, iOS 13, tvOS 13, *)) {",
                    "    // Enable newer features.",
                    "}",
                    "else",
                    "{",
                    "    // Fallback on earlier OS versions.",
                    "}"
                  ],
                  "syntax": "objective-c",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "anchor": "Find-Variations-in-a-GPU-Family",
          "level": 3,
          "text": "Find Variations in a GPU Family",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "GPUs in the same family can vary in small ways. Some features aren’t supported uniformly across a family. Use the device object to test for the existence of these features using an API specific to each feature.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, Metal’s argument buffer feature has two tiers of support; the second tier is significantly better than the first. The code below shows how to test for tier 2 support:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "if self.device.argumentBuffersSupport == .tier2",
                    "{",
                    "    // Enable tier 2 argument buffer support in renderer.",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "if (device.argumentBuffersSupport == MTLArgumentBuffersTier2)",
                    "{",
                    "    // Enable tier 2 argument buffer support in renderer.",
                    "}"
                  ],
                  "syntax": "objective-c",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "anchor": "Discover-Feature-Availability-in-Earlier-Operating-Systems",
          "level": 3,
          "text": "Discover Feature Availability in Earlier Operating Systems",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the GPU Family API isn’t available, test for features using ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "feature sets",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ". A feature set combines a Metal GPU family number with a software revision number. For example, to test for the first release of Metal that supported Apple family 4 GPUs, use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily4_v1",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", as shown here:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "if self.device.supportsFeatureSet(.iOS_GPUFamily4_v1)",
                    "{",
                    "    // Enable family 4 rendering path.",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "if ([device supportsFeatureSet: MTLFeatureSet_iOS_GPUFamily4_v1])",
                    "{",
                    "    // Enable family 4 rendering path.",
                    "}"
                  ],
                  "syntax": "objective-c",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "Metal added new feature set enumerations in new versions of Apple operating systems to support new software features and GPU families, so there are many different enumeration values representing different collections of features. If a GPU supports a feature set, it supports all features provided by earlier members of the same family, and all features in earlier software revisions. For example, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily4_v2",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is version 2 of family 4, so it supports the same features as version 1, as well as all features supported by families 1, 2, and 3. You don’t need to test for those feature sets separately. Test for feature sets, from newest to oldest, until you successfully find a feature set that your app and the GPU both support.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCreateSystemDefaultDevice()": {
      "abstract": [
        {
          "text": "Returns the device instance Metal selects as the default.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCreateSystemDefaultDevice"
        },
        {
          "kind": "text",
          "text": "() -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDevice",
          "text": "MTLDevice"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCreateSystemDefaultDevice()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCreateSystemDefaultDevice"
        }
      ],
      "role": "symbol",
      "title": "MTLCreateSystemDefaultDevice()",
      "type": "topic",
      "url": "/documentation/metal/mtlcreatesystemdefaultdevice()"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice": {
      "abstract": [
        {
          "text": "The main Metal interface to a GPU that apps use to draw graphics and run computations in parallel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDevice"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDevice"
        }
      ],
      "role": "symbol",
      "title": "MTLDevice",
      "type": "topic",
      "url": "/documentation/metal/mtldevice"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily4_v1": {
      "abstract": [
        {
          "text": "The GPU family 4, version 1 feature set for iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOS_GPUFamily4_v1"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily4_v1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_iOS_GPUFamily4_v1"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.iOS_GPUFamily4_v1",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/ios_gpufamily4_v1"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily4_v2": {
      "abstract": [
        {
          "text": "The GPU family 4, version 2 feature set for iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOS_GPUFamily4_v2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily4_v2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_iOS_GPUFamily4_v2"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.iOS_GPUFamily4_v2",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/ios_gpufamily4_v2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLGPUFamily": {
      "abstract": [
        {
          "text": "Represents the functionality for families of GPUs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLGPUFamily"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLGPUFamily",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLGPUFamily"
        }
      ],
      "role": "symbol",
      "title": "MTLGPUFamily",
      "type": "topic",
      "url": "/documentation/metal/mtlgpufamily"
    },
    "doc://com.apple.metal/documentation/Metal/getting-the-default-gpu": {
      "abstract": [
        {
          "text": "Select the system’s default GPU device on which to run your Metal code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/getting-the-default-gpu",
      "kind": "article",
      "role": "article",
      "title": "Getting the Default GPU",
      "type": "topic",
      "url": "/documentation/metal/getting-the-default-gpu"
    },
    "doc://com.apple.metal/documentation/Metal/gpu-devices-and-work-submission": {
      "abstract": [
        {
          "text": "Find any available GPU, submit work to it with command buffers, suspend work, and coordinate between multiple GPUs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/gpu-devices-and-work-submission",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GPU Devices and Work Submission",
      "type": "topic",
      "url": "/documentation/metal/gpu-devices-and-work-submission"
    },
    "doc://com.apple.metal/documentation/Metal/multi-gpu-systems": {
      "abstract": [
        {
          "text": "Locate and work with internal and external GPUs and their displays, video memory, and performance tradeoffs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/multi-gpu-systems",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Multi-GPU Systems",
      "type": "topic",
      "url": "/documentation/metal/multi-gpu-systems"
    },
    "https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf": {
      "identifier": "https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf",
      "title": "Metal feature set tables (PDF)",
      "titleInlineContent": [
        {
          "text": "Metal feature set tables (PDF)",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf"
    },
    "https://developer.apple.com/metal/metal-feature-set-tables.zip": {
      "identifier": "https://developer.apple.com/metal/metal-feature-set-tables.zip",
      "title": "Metal feature set tables (Numbers)",
      "titleInlineContent": [
        {
          "text": "Metal feature set tables (Numbers)",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/metal/metal-feature-set-tables.zip"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Locating-and-Inspecting-a-GPU-Device",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/getting-the-default-gpu",
        "doc://com.apple.metal/documentation/Metal/MTLCreateSystemDefaultDevice()",
        "doc://com.apple.metal/documentation/Metal/MTLDevice",
        "doc://com.apple.metal/documentation/Metal/multi-gpu-systems"
      ],
      "title": "Locating and Inspecting a GPU Device"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Locating-and-Inspecting-a-GPU-Device",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/getting-the-default-gpu",
                "doc://com.apple.metal/documentation/Metal/MTLCreateSystemDefaultDevice()",
                "doc://com.apple.metal/documentation/Metal/MTLDevice",
                "doc://com.apple.metal/documentation/Metal/multi-gpu-systems"
              ],
              "title": "Locating and Inspecting a GPU Device"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/title",
          "value": "MTLDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCreateSystemDefaultDevice()/title",
          "value": "MTLCreateSystemDefaultDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCreateSystemDefaultDevice()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCreateSystemDefaultDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily4_v1/title",
          "value": "MTLFeatureSet_iOS_GPUFamily4_v1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily4_v1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_iOS_GPUFamily4_v1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily4_v2/title",
          "value": "MTLFeatureSet_iOS_GPUFamily4_v2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily4_v2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_iOS_GPUFamily4_v2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily/title",
          "value": "MTLGPUFamily"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLGPUFamily"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLGPUFamily"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/detecting-gpu-features-and-metal-software-versions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/detecting-gpu-features-and-metal-software-versions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
