{
  "abstract": [
    {
      "text": "Locate and identify a GPU and the features it supports, and sample its counters.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/gpu-devices-and-work-submission",
        "doc://com.apple.metal/documentation/Metal/MTLDevice"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/device-inspection"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Device Inspection"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArchitecture": {
      "abstract": [
        {
          "text": "A class that contains the architectural details of a GPU device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLArchitecture"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArchitecture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArchitecture"
        }
      ],
      "role": "symbol",
      "title": "MTLArchitecture",
      "type": "topic",
      "url": "/documentation/metal/mtlarchitecture"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterSamplingPoint": {
      "abstract": [
        {
          "text": "Options for different times when you can sample GPU counters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCounterSamplingPoint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterSamplingPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCounterSamplingPoint"
        }
      ],
      "role": "symbol",
      "title": "MTLCounterSamplingPoint",
      "type": "topic",
      "url": "/documentation/metal/mtlcountersamplingpoint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice": {
      "abstract": [
        {
          "text": "The main Metal interface to a GPU that apps use to draw graphics and run computations in parallel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDevice"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDevice"
        }
      ],
      "role": "symbol",
      "title": "MTLDevice",
      "type": "topic",
      "url": "/documentation/metal/mtldevice"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/architecture": {
      "abstract": [
        {
          "text": "The architectural details of the GPU device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "architecture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLArchitecture",
          "text": "MTLArchitecture"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/architecture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "architecture"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "architecture",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/architecture"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/areBarycentricCoordsSupported": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the GPU supports barycentric coordinates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "areBarycentricCoordsSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/areBarycentricCoordsSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "barycentricCoordsSupported"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "areBarycentricCoordsSupported",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/arebarycentriccoordssupported"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/areProgrammableSamplePositionsSupported": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the GPU supports programmable sample positions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "areProgrammableSamplePositionsSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/areProgrammableSamplePositionsSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "programmableSamplePositionsSupported"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "areProgrammableSamplePositionsSupported",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/areprogrammablesamplepositionssupported"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/areRasterOrderGroupsSupported": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the GPU supports raster order groups.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "areRasterOrderGroupsSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/areRasterOrderGroupsSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rasterOrderGroupsSupported"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "areRasterOrderGroupsSupported",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/arerasterordergroupssupported"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/counterSets": {
      "abstract": [
        {
          "text": "The counter sets supported by the device object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "counterSets"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLCounterSet",
          "text": "MTLCounterSet"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/counterSets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "counterSets"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "counterSets",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/countersets"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/currentAllocatedSize": {
      "abstract": [
        {
          "text": "The total amount of memory, in bytes, the GPU device is using for all of its resources.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentAllocatedSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/currentAllocatedSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentAllocatedSize"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "currentAllocatedSize",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/currentallocatedsize"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/hasUnifiedMemory": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the GPU shares all of its memory with the CPU.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasUnifiedMemory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/hasUnifiedMemory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasUnifiedMemory"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "hasUnifiedMemory",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/hasunifiedmemory"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/isDepth24Stencil8PixelFormatSupported": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a device supports a packed depth-and-stencil pixel format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isDepth24Stencil8PixelFormatSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/isDepth24Stencil8PixelFormatSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "depth24Stencil8PixelFormatSupported"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "isDepth24Stencil8PixelFormatSupported",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/isdepth24stencil8pixelformatsupported"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/isHeadless": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a GPU device doesn’t have a connection to a display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isHeadless"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/isHeadless",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "headless"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "isHeadless",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/isheadless"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/isLowPower": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the GPU lowers its performance to conserve energy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isLowPower"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/isLowPower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lowPower"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "isLowPower",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/islowpower"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/isRemovable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the GPU is removable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isRemovable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/isRemovable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removable"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "isRemovable",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/isremovable"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/location": {
      "abstract": [
        {
          "text": "The physical location of the GPU relative to the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "location"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLDeviceLocation",
          "text": "MTLDeviceLocation"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/location",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "location"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "location",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/location"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/locationNumber": {
      "abstract": [
        {
          "text": "A specific GPU position based on its general location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locationNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/locationNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "locationNumber"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "locationNumber",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/locationnumber"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/makeCounterSampleBuffer(descriptor:)": {
      "abstract": [
        {
          "text": "Creates a counter sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeCounterSampleBuffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLCounterSampleBufferDescriptor",
          "text": "MTLCounterSampleBufferDescriptor"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLCounterSampleBuffer",
          "text": "MTLCounterSampleBuffer"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/makeCounterSampleBuffer(descriptor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newCounterSampleBufferWithDescriptor:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeCounterSampleBuffer(descriptor:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/makecountersamplebuffer(descriptor:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/maxThreadgroupMemoryLength": {
      "abstract": [
        {
          "text": "The maximum threadgroup memory available to a compute kernel, in bytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxThreadgroupMemoryLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/maxThreadgroupMemoryLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxThreadgroupMemoryLength"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "maxThreadgroupMemoryLength",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/maxthreadgroupmemorylength"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/maxThreadsPerThreadgroup": {
      "abstract": [
        {
          "text": "The maximum number of threads along each dimension of a threadgroup.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxThreadsPerThreadgroup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MTLSize",
          "text": "MTLSize"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/maxThreadsPerThreadgroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxThreadsPerThreadgroup"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "maxThreadsPerThreadgroup",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/maxthreadsperthreadgroup"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/maxTransferRate": {
      "abstract": [
        {
          "text": "The highest theoretical rate, in bytes per second, the system can copy between system memory and the GPU’s dedicated memory (VRAM).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxTransferRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/maxTransferRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxTransferRate"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "maxTransferRate",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/maxtransferrate"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/name": {
      "abstract": [
        {
          "text": "The full name of the GPU device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/name"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/peerCount": {
      "abstract": [
        {
          "text": "The total number of GPUs in the peer group, if applicable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peerCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/peerCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "peerCount"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "peerCount",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/peercount"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/peerGroupID": {
      "abstract": [
        {
          "text": "The peer group ID the GPU belongs to, if applicable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peerGroupID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/peerGroupID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "peerGroupID"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "peerGroupID",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/peergroupid"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/peerIndex": {
      "abstract": [
        {
          "text": "The unique identifier for a GPU in a peer group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peerIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/peerIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "peerIndex"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "peerIndex",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/peerindex"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/readWriteTextureSupport": {
      "abstract": [
        {
          "text": "The GPU device’s texture support tier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readWriteTextureSupport"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLReadWriteTextureTier",
          "text": "MTLReadWriteTextureTier"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/readWriteTextureSupport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readWriteTextureSupport"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "readWriteTextureSupport",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/readwritetexturesupport"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/recommendedMaxWorkingSetSize": {
      "abstract": [
        {
          "text": "An approximation of how much memory, in bytes, this GPU device can allocate without affecting its runtime performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recommendedMaxWorkingSetSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/recommendedMaxWorkingSetSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recommendedMaxWorkingSetSize"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "recommendedMaxWorkingSetSize",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/recommendedmaxworkingsetsize"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/registryID": {
      "abstract": [
        {
          "text": "The GPU device’s registry identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registryID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/registryID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "registryID"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "registryID",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/registryid"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/sampleTimestamps()": {
      "abstract": [
        {
          "text": "Captures and returns a CPU timestamp and a GPU timestamp from the same moment in time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sampleTimestamps"
        },
        {
          "kind": "text",
          "text": "() -> (cpu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLTimestamp",
          "text": "MTLTimestamp"
        },
        {
          "kind": "text",
          "text": ", gpu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLTimestamp",
          "text": "MTLTimestamp"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/sampleTimestamps()",
      "kind": "symbol",
      "role": "symbol",
      "title": "sampleTimestamps()",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/sampletimestamps()"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/sampleTimestamps:gpuTimestamp:": {
      "abstract": [
        {
          "text": "Captures and returns a CPU timestamp and a GPU timestamp from the same moment in time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "sampleTimestamps:gpuTimestamp:"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/sampleTimestamps:gpuTimestamp:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sampleTimestamps:gpuTimestamp:"
        }
      ],
      "role": "symbol",
      "title": "sampleTimestamps:gpuTimestamp:",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/sampletimestamps:gputimestamp:"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/supports32BitFloatFiltering": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the GPU can filter a texture with a 32-bit floating-point format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supports32BitFloatFiltering"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/supports32BitFloatFiltering",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supports32BitFloatFiltering"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "supports32BitFloatFiltering",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/supports32bitfloatfiltering"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/supports32BitMSAA": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the GPU can allocate 32-bit integer texture formats and resolve to 32-bit floating-point texture formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supports32BitMSAA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/supports32BitMSAA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supports32BitMSAA"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "supports32BitMSAA",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/supports32bitmsaa"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsBCTextureCompression": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether you can use textures that use BC compression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsBCTextureCompression"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsBCTextureCompression",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsBCTextureCompression"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "supportsBCTextureCompression",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/supportsbctexturecompression"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsCounterSampling(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether you can read GPU counters at the specified command boundary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsCounterSampling"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLCounterSamplingPoint",
          "text": "MTLCounterSamplingPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsCounterSampling(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsCounterSampling:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "supportsCounterSampling(_:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/supportscountersampling(_:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFamily(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the GPU device supports the feature set of a specific GPU family.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsFamily"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLGPUFamily",
          "text": "MTLGPUFamily"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFamily(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsFamily:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "supportsFamily(_:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/supportsfamily(_:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFeatureSet(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the GPU device supports a specific feature set.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsFeatureSet"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLFeatureSet",
          "text": "MTLFeatureSet"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFeatureSet(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsFeatureSet:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "supportsFeatureSet(_:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/supportsfeatureset(_:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFunctionPointers": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the GPU device supports pointers to compute kernel functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsFunctionPointers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFunctionPointers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsFunctionPointers"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "supportsFunctionPointers",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/supportsfunctionpointers"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFunctionPointersFromRender": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the GPU device supports pointers to render functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsFunctionPointersFromRender"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFunctionPointersFromRender",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsFunctionPointersFromRender"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "supportsFunctionPointersFromRender",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/supportsfunctionpointersfromrender"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsPrimitiveMotionBlur": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the GPU device supports motion blur for ray tracing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsPrimitiveMotionBlur"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsPrimitiveMotionBlur",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsPrimitiveMotionBlur"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "supportsPrimitiveMotionBlur",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/supportsprimitivemotionblur"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsPullModelInterpolation": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the GPU can compute multiple interpolations of a fragment function’s input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsPullModelInterpolation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsPullModelInterpolation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsPullModelInterpolation"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "supportsPullModelInterpolation",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/supportspullmodelinterpolation"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsQueryTextureLOD": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether you can query the texture level of detail from within a shader.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsQueryTextureLOD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsQueryTextureLOD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsQueryTextureLOD"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "supportsQueryTextureLOD",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/supportsquerytexturelod"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsRaytracing": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the GPU device supports ray tracing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsRaytracing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsRaytracing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsRaytracing"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "supportsRaytracing",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/supportsraytracing"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsRaytracingFromRender": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether you can call ray-tracing functions from a vertex or fragment shader.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsRaytracingFromRender"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsRaytracingFromRender",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsRaytracingFromRender"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "supportsRaytracingFromRender",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/supportsraytracingfromrender"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsShaderBarycentricCoordinates": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the GPU supports barycentric coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsShaderBarycentricCoordinates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsShaderBarycentricCoordinates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsShaderBarycentricCoordinates"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "supportsShaderBarycentricCoordinates",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/supportsshaderbarycentriccoordinates"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsVertexAmplificationCount(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the GPU supports an amplification factor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsVertexAmplificationCount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsVertexAmplificationCount(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsVertexAmplificationCount:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "supportsVertexAmplificationCount(_:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/supportsvertexamplificationcount(_:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDeviceLocation": {
      "abstract": [
        {
          "text": "Indicates the location of the GPU relative to the system it’s connect to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDeviceLocation"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDeviceLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDeviceLocation"
        }
      ],
      "role": "symbol",
      "title": "MTLDeviceLocation",
      "type": "topic",
      "url": "/documentation/metal/mtldevicelocation"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet": {
      "abstract": [
        {
          "text": "The device feature sets that define specific platform, hardware, and software configurations.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFeatureSet"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset"
    },
    "doc://com.apple.metal/documentation/Metal/MTLGPUFamily": {
      "abstract": [
        {
          "text": "Represents the functionality for families of GPUs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLGPUFamily"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLGPUFamily",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLGPUFamily"
        }
      ],
      "role": "symbol",
      "title": "MTLGPUFamily",
      "type": "topic",
      "url": "/documentation/metal/mtlgpufamily"
    },
    "doc://com.apple.metal/documentation/Metal/gpu-devices-and-work-submission": {
      "abstract": [
        {
          "text": "Find any available GPU, submit work to it with command buffers, suspend work, and coordinate between multiple GPUs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/gpu-devices-and-work-submission",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GPU Devices and Work Submission",
      "type": "topic",
      "url": "/documentation/metal/gpu-devices-and-work-submission"
    },
    "doc://com.apple.metal/documentation/Metal/pipeline-state-creation": {
      "abstract": [
        {
          "text": "Create pipeline states for render and compute passes, samplers, depth and stencil states, and indirect command buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/pipeline-state-creation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Pipeline State Creation",
      "type": "topic",
      "url": "/documentation/metal/pipeline-state-creation"
    },
    "doc://com.apple.metal/documentation/Metal/resource-creation": {
      "abstract": [
        {
          "text": "Load assets with input/output queues and make various resource instances, such as buffers, textures, acceleration structures, and memory heaps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/resource-creation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Resource Creation",
      "type": "topic",
      "url": "/documentation/metal/resource-creation"
    },
    "doc://com.apple.metal/documentation/Metal/shader-library-and-archive-creation": {
      "abstract": [
        {
          "text": "Create static and dynamic shader libraries, and binary shader archives.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/shader-library-and-archive-creation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Shader Library and Archive Creation",
      "type": "topic",
      "url": "/documentation/metal/shader-library-and-archive-creation"
    },
    "doc://com.apple.metal/documentation/Metal/work-submission": {
      "abstract": [
        {
          "text": "Create queues that submit work to the GPU or load assets into GPU resources, and indirect command buffers that group your frequent commands together.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/work-submission",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Work Submission",
      "type": "topic",
      "url": "/documentation/metal/work-submission"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-GPU-Devices",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/work-submission",
        "doc://com.apple.metal/documentation/Metal/pipeline-state-creation",
        "doc://com.apple.metal/documentation/Metal/resource-creation",
        "doc://com.apple.metal/documentation/Metal/shader-library-and-archive-creation"
      ],
      "title": "Working with GPU Devices"
    }
  ],
  "topicSections": [
    {
      "anchor": "Checking-a-GPU-Devices-Feature-Support",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFamily(_:)",
        "doc://com.apple.metal/documentation/Metal/MTLGPUFamily",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFeatureSet(_:)",
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet"
      ],
      "title": "Checking a GPU Device’s Feature Support"
    },
    {
      "anchor": "Checking-Compute-Support",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLDevice/maxThreadgroupMemoryLength",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/maxThreadsPerThreadgroup"
      ],
      "title": "Checking Compute Support"
    },
    {
      "anchor": "Checking-Render-Support",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsRaytracing",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsPrimitiveMotionBlur",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsRaytracingFromRender",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/supports32BitMSAA",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsPullModelInterpolation",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsShaderBarycentricCoordinates",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsVertexAmplificationCount(_:)",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/areProgrammableSamplePositionsSupported",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/areRasterOrderGroupsSupported",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/areBarycentricCoordsSupported"
      ],
      "title": "Checking Render Support"
    },
    {
      "anchor": "Checking-Texture-and-Sampler-Support",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLDevice/supports32BitFloatFiltering",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsBCTextureCompression",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/isDepth24Stencil8PixelFormatSupported",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsQueryTextureLOD",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/readWriteTextureSupport"
      ],
      "title": "Checking Texture and Sampler Support"
    },
    {
      "anchor": "Checking-Function-Pointer-Support",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFunctionPointers",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFunctionPointersFromRender"
      ],
      "title": "Checking Function Pointer Support"
    },
    {
      "anchor": "Checking-a-GPU-Devices-Memory",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLDevice/currentAllocatedSize",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/recommendedMaxWorkingSetSize",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/hasUnifiedMemory",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/maxTransferRate"
      ],
      "title": "Checking a GPU Device’s Memory"
    },
    {
      "anchor": "Sampling-a-GPU-Devices-Counters",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLDevice/counterSets",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsCounterSampling(_:)",
        "doc://com.apple.metal/documentation/Metal/MTLCounterSamplingPoint",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/makeCounterSampleBuffer(descriptor:)"
      ],
      "title": "Sampling a GPU Device’s Counters"
    },
    {
      "anchor": "Sampling-GPU-and-CPU-Timestamps-Simultaneously",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLDevice/sampleTimestamps()"
      ],
      "title": "Sampling GPU and CPU Timestamps Simultaneously"
    },
    {
      "anchor": "Identifying-a-GPU-Device",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLDevice/name",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/architecture",
        "doc://com.apple.metal/documentation/Metal/MTLArchitecture",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/registryID",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/location",
        "doc://com.apple.metal/documentation/Metal/MTLDeviceLocation",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/locationNumber",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/isLowPower",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/isRemovable",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/isHeadless",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/peerGroupID",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/peerCount",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/peerIndex"
      ],
      "title": "Identifying a GPU Device"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Checking-a-GPU-Devices-Feature-Support",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFamily(_:)",
                "doc://com.apple.metal/documentation/Metal/MTLGPUFamily",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFeatureSet(_:)",
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet"
              ],
              "title": "Checking a GPU Device’s Feature Support"
            },
            {
              "anchor": "Checking-Compute-Support",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLDevice/maxThreadgroupMemoryLength",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/maxThreadsPerThreadgroup"
              ],
              "title": "Checking Compute Support"
            },
            {
              "anchor": "Checking-Render-Support",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsRaytracing",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsPrimitiveMotionBlur",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsRaytracingFromRender",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/supports32BitMSAA",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsPullModelInterpolation",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsShaderBarycentricCoordinates",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsVertexAmplificationCount(_:)",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/areProgrammableSamplePositionsSupported",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/areRasterOrderGroupsSupported",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/areBarycentricCoordsSupported"
              ],
              "title": "Checking Render Support"
            },
            {
              "anchor": "Checking-Texture-and-Sampler-Support",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLDevice/supports32BitFloatFiltering",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsBCTextureCompression",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/isDepth24Stencil8PixelFormatSupported",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsQueryTextureLOD",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/readWriteTextureSupport"
              ],
              "title": "Checking Texture and Sampler Support"
            },
            {
              "anchor": "Checking-Function-Pointer-Support",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFunctionPointers",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFunctionPointersFromRender"
              ],
              "title": "Checking Function Pointer Support"
            },
            {
              "anchor": "Checking-a-GPU-Devices-Memory",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLDevice/currentAllocatedSize",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/recommendedMaxWorkingSetSize",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/hasUnifiedMemory",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/maxTransferRate"
              ],
              "title": "Checking a GPU Device’s Memory"
            },
            {
              "anchor": "Sampling-a-GPU-Devices-Counters",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLDevice/counterSets",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsCounterSampling(_:)",
                "doc://com.apple.metal/documentation/Metal/MTLCounterSamplingPoint",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/makeCounterSampleBuffer(descriptor:)"
              ],
              "title": "Sampling a GPU Device’s Counters"
            },
            {
              "anchor": "Sampling-GPU-and-CPU-Timestamps-Simultaneously",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLDevice/sampleTimestamps:gpuTimestamp:"
              ],
              "title": "Sampling GPU and CPU Timestamps Simultaneously"
            },
            {
              "anchor": "Identifying-a-GPU-Device",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLDevice/name",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/architecture",
                "doc://com.apple.metal/documentation/Metal/MTLArchitecture",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/registryID",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/location",
                "doc://com.apple.metal/documentation/Metal/MTLDeviceLocation",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/locationNumber",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/isLowPower",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/isRemovable",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/isHeadless",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/peerGroupID",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/peerCount",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/peerIndex"
              ],
              "title": "Identifying a GPU Device"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-GPU-Devices",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/work-submission",
                "doc://com.apple.metal/documentation/Metal/pipeline-state-creation",
                "doc://com.apple.metal/documentation/Metal/resource-creation",
                "doc://com.apple.metal/documentation/Metal/shader-library-and-archive-creation"
              ],
              "title": "Working with GPU Devices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1areBarycentricCoordsSupported/title",
          "value": "barycentricCoordsSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1areBarycentricCoordsSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "barycentricCoordsSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1areProgrammableSamplePositionsSupported/title",
          "value": "programmableSamplePositionsSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1areProgrammableSamplePositionsSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "programmableSamplePositionsSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsFunctionPointersFromRender/title",
          "value": "supportsFunctionPointersFromRender"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsFunctionPointersFromRender/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsFunctionPointersFromRender"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1readWriteTextureSupport/title",
          "value": "readWriteTextureSupport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1readWriteTextureSupport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "readWriteTextureSupport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1isLowPower/title",
          "value": "lowPower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1isLowPower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lowPower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1isHeadless/title",
          "value": "headless"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1isHeadless/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "headless"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsVertexAmplificationCount(_:)/title",
          "value": "supportsVertexAmplificationCount:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsVertexAmplificationCount(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "supportsVertexAmplificationCount:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1recommendedMaxWorkingSetSize/title",
          "value": "recommendedMaxWorkingSetSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1recommendedMaxWorkingSetSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recommendedMaxWorkingSetSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArchitecture/title",
          "value": "MTLArchitecture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArchitecture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArchitecture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArchitecture/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArchitecture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceLocation/title",
          "value": "MTLDeviceLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDeviceLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDeviceLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsFeatureSet(_:)/title",
          "value": "supportsFeatureSet:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsFeatureSet(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "supportsFeatureSet:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterSamplingPoint/title",
          "value": "MTLCounterSamplingPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterSamplingPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCounterSamplingPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterSamplingPoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCounterSamplingPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1hasUnifiedMemory/title",
          "value": "hasUnifiedMemory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1hasUnifiedMemory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasUnifiedMemory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsShaderBarycentricCoordinates/title",
          "value": "supportsShaderBarycentricCoordinates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsShaderBarycentricCoordinates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsShaderBarycentricCoordinates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1architecture/title",
          "value": "architecture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1architecture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "architecture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsFamily(_:)/title",
          "value": "supportsFamily:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsFamily(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "supportsFamily:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeCounterSampleBuffer(descriptor:)/title",
          "value": "newCounterSampleBufferWithDescriptor:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeCounterSampleBuffer(descriptor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newCounterSampleBufferWithDescriptor:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsPrimitiveMotionBlur/title",
          "value": "supportsPrimitiveMotionBlur"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsPrimitiveMotionBlur/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsPrimitiveMotionBlur"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1maxThreadgroupMemoryLength/title",
          "value": "maxThreadgroupMemoryLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1maxThreadgroupMemoryLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxThreadgroupMemoryLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet/title",
          "value": "MTLFeatureSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1isRemovable/title",
          "value": "removable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1isRemovable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "removable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1maxTransferRate/title",
          "value": "maxTransferRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1maxTransferRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxTransferRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsFunctionPointers/title",
          "value": "supportsFunctionPointers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsFunctionPointers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsFunctionPointers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1registryID/title",
          "value": "registryID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1registryID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "registryID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1counterSets/title",
          "value": "counterSets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1counterSets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "counterSets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsRaytracingFromRender/title",
          "value": "supportsRaytracingFromRender"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsRaytracingFromRender/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsRaytracingFromRender"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1location/title",
          "value": "location"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1location/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "location"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsPullModelInterpolation/title",
          "value": "supportsPullModelInterpolation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsPullModelInterpolation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsPullModelInterpolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1peerIndex/title",
          "value": "peerIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1peerIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "peerIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/title",
          "value": "MTLDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supports32BitFloatFiltering/title",
          "value": "supports32BitFloatFiltering"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supports32BitFloatFiltering/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supports32BitFloatFiltering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily/title",
          "value": "MTLGPUFamily"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLGPUFamily"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLGPUFamily"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsRaytracing/title",
          "value": "supportsRaytracing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsRaytracing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsRaytracing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1peerCount/title",
          "value": "peerCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1peerCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "peerCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1areRasterOrderGroupsSupported/title",
          "value": "rasterOrderGroupsSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1areRasterOrderGroupsSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rasterOrderGroupsSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1peerGroupID/title",
          "value": "peerGroupID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1peerGroupID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "peerGroupID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsCounterSampling(_:)/title",
          "value": "supportsCounterSampling:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsCounterSampling(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "supportsCounterSampling:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supports32BitMSAA/title",
          "value": "supports32BitMSAA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supports32BitMSAA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supports32BitMSAA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1currentAllocatedSize/title",
          "value": "currentAllocatedSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1currentAllocatedSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentAllocatedSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsBCTextureCompression/title",
          "value": "supportsBCTextureCompression"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsBCTextureCompression/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsBCTextureCompression"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1maxThreadsPerThreadgroup/title",
          "value": "maxThreadsPerThreadgroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1maxThreadsPerThreadgroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxThreadsPerThreadgroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1isDepth24Stencil8PixelFormatSupported/title",
          "value": "depth24Stencil8PixelFormatSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1isDepth24Stencil8PixelFormatSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "depth24Stencil8PixelFormatSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsQueryTextureLOD/title",
          "value": "supportsQueryTextureLOD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsQueryTextureLOD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsQueryTextureLOD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1locationNumber/title",
          "value": "locationNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1locationNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "locationNumber"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/device-inspection"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/device-inspection"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
