{
  "abstract": [
    {
      "text": "Assign resources to fragment shaders, including buffers, textures, acceleration structures, sampler states, and function tables.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/render-passes",
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/fragment-shader-resource-preparation-commands"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Fragment Shader Resource Preparation Commands"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "All fragment shaders share an argument table for each resource type, such as buffers, textures, and sampler states. These argument tables are separate from other shader types, each of which have their own argument tables, one for each resource type.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder": {
      "abstract": [
        {
          "text": "An interface that encodes a render pass into a command buffer, including all its draw calls and configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLRenderCommandEncoder"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLRenderCommandEncoder"
        }
      ],
      "role": "symbol",
      "title": "MTLRenderCommandEncoder",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentAccelerationStructure(_:bufferIndex:)": {
      "abstract": [
        {
          "text": "Assigns an acceleration structure to an entry in the fragment shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setFragmentAccelerationStructure"
        },
        {
          "kind": "text",
          "text": "((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLAccelerationStructure",
          "text": "MTLAccelerationStructure"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "bufferIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentAccelerationStructure(_:bufferIndex:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFragmentAccelerationStructure:atBufferIndex:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setFragmentAccelerationStructure(_:bufferIndex:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setfragmentaccelerationstructure(_:bufferindex:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentBuffer(_:offset:index:)": {
      "abstract": [
        {
          "text": "Assigns a buffer to an entry in the fragment shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setFragmentBuffer"
        },
        {
          "kind": "text",
          "text": "((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLBuffer",
          "text": "MTLBuffer"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "offset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "index"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentBuffer(_:offset:index:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFragmentBuffer:offset:atIndex:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setFragmentBuffer(_:offset:index:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setfragmentbuffer(_:offset:index:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentBufferOffset(_:index:)": {
      "abstract": [
        {
          "text": "Updates an entry in the fragment shader argument table with a new location within the entry’s current buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setFragmentBufferOffset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "index"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentBufferOffset(_:index:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFragmentBufferOffset:atIndex:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setFragmentBufferOffset(_:index:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setfragmentbufferoffset(_:index:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentBuffers(_:offsets:range:)": {
      "abstract": [
        {
          "text": "Assigns multiple buffers to a range of entries in the fragment shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setFragmentBuffers"
        },
        {
          "kind": "text",
          "text": "([(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLBuffer",
          "text": "MTLBuffer"
        },
        {
          "kind": "text",
          "text": ")?], "
        },
        {
          "kind": "externalParam",
          "text": "offsets"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "range"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sn",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentBuffers(_:offsets:range:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setFragmentBuffers(_:offsets:range:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setfragmentbuffers(_:offsets:range:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentBuffers:offsets:withRange:": {
      "abstract": [
        {
          "text": "Assigns multiple buffers to a range of entries in the fragment shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setFragmentBuffers:offsets:withRange:"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentBuffers:offsets:withRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFragmentBuffers:offsets:withRange:"
        }
      ],
      "role": "symbol",
      "title": "setFragmentBuffers:offsets:withRange:",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setfragmentbuffers:offsets:withrange:"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentBytes(_:length:index:)": {
      "abstract": [
        {
          "text": "Creates a buffer from bytes and assigns it to an entry in the fragment shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setFragmentBytes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "length"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "index"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentBytes(_:length:index:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFragmentBytes:length:atIndex:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setFragmentBytes(_:length:index:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setfragmentbytes(_:length:index:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentIntersectionFunctionTable(_:bufferIndex:)": {
      "abstract": [
        {
          "text": "Assigns an intersection function table to an entry in the fragment shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setFragmentIntersectionFunctionTable"
        },
        {
          "kind": "text",
          "text": "((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLIntersectionFunctionTable",
          "text": "MTLIntersectionFunctionTable"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "bufferIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentIntersectionFunctionTable(_:bufferIndex:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFragmentIntersectionFunctionTable:atBufferIndex:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setFragmentIntersectionFunctionTable(_:bufferIndex:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setfragmentintersectionfunctiontable(_:bufferindex:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentIntersectionFunctionTables(_:bufferRange:)": {
      "abstract": [
        {
          "text": "Assigns multiple intersection function tables to a range of entries in the fragment shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setFragmentIntersectionFunctionTables"
        },
        {
          "kind": "text",
          "text": "([(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLIntersectionFunctionTable",
          "text": "MTLIntersectionFunctionTable"
        },
        {
          "kind": "text",
          "text": ")?], "
        },
        {
          "kind": "externalParam",
          "text": "bufferRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sn",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentIntersectionFunctionTables(_:bufferRange:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setFragmentIntersectionFunctionTables(_:bufferRange:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setfragmentintersectionfunctiontables(_:bufferrange:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentIntersectionFunctionTables:withBufferRange:": {
      "abstract": [
        {
          "text": "Assigns multiple intersection function tables to a range of entries in the fragment shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setFragmentIntersectionFunctionTables:withBufferRange:"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentIntersectionFunctionTables:withBufferRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFragmentIntersectionFunctionTables:withBufferRange:"
        }
      ],
      "role": "symbol",
      "title": "setFragmentIntersectionFunctionTables:withBufferRange:",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setfragmentintersectionfunctiontables:withbufferrange:"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentSamplerState(_:index:)": {
      "abstract": [
        {
          "text": "Assigns a sampler state to an entry in the fragment shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setFragmentSamplerState"
        },
        {
          "kind": "text",
          "text": "((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLSamplerState",
          "text": "MTLSamplerState"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "index"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentSamplerState(_:index:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFragmentSamplerState:atIndex:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setFragmentSamplerState(_:index:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setfragmentsamplerstate(_:index:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentSamplerState(_:lodMinClamp:lodMaxClamp:index:)": {
      "abstract": [
        {
          "text": "Assigns a sampler state and clamp values to an entry in the fragment shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setFragmentSamplerState"
        },
        {
          "kind": "text",
          "text": "((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLSamplerState",
          "text": "MTLSamplerState"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "lodMinClamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "lodMaxClamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "index"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentSamplerState(_:lodMinClamp:lodMaxClamp:index:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFragmentSamplerState:lodMinClamp:lodMaxClamp:atIndex:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setFragmentSamplerState(_:lodMinClamp:lodMaxClamp:index:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setfragmentsamplerstate(_:lodminclamp:lodmaxclamp:index:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentSamplerStates(_:lodMinClamps:lodMaxClamps:range:)": {
      "abstract": [
        {
          "text": "Assigns multiple sampler states and clamp values to a range of entries in the fragment shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setFragmentSamplerStates"
        },
        {
          "kind": "text",
          "text": "([(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLSamplerState",
          "text": "MTLSamplerState"
        },
        {
          "kind": "text",
          "text": ")?], "
        },
        {
          "kind": "externalParam",
          "text": "lodMinClamps"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "lodMaxClamps"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "range"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sn",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentSamplerStates(_:lodMinClamps:lodMaxClamps:range:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setFragmentSamplerStates(_:lodMinClamps:lodMaxClamps:range:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setfragmentsamplerstates(_:lodminclamps:lodmaxclamps:range:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentSamplerStates(_:range:)": {
      "abstract": [
        {
          "text": "Assigns multiple sampler states to a range of entries in the fragment shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setFragmentSamplerStates"
        },
        {
          "kind": "text",
          "text": "([(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLSamplerState",
          "text": "MTLSamplerState"
        },
        {
          "kind": "text",
          "text": ")?], "
        },
        {
          "kind": "externalParam",
          "text": "range"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sn",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentSamplerStates(_:range:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setFragmentSamplerStates(_:range:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setfragmentsamplerstates(_:range:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentSamplerStates:lodMinClamps:lodMaxClamps:withRange:": {
      "abstract": [
        {
          "text": "Assigns multiple sampler states and clamp values to a range of entries in the fragment shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setFragmentSamplerStates:lodMinClamps:lodMaxClamps:withRange:"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentSamplerStates:lodMinClamps:lodMaxClamps:withRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFragmentSamplerStates:lodMinClamps:lodMaxClamps:withRange:"
        }
      ],
      "role": "symbol",
      "title": "setFragmentSamplerStates:lodMinClamps:lodMaxClamps:withRange:",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setfragmentsamplerstates:lodminclamps:lodmaxclamps:withrange:"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentSamplerStates:withRange:": {
      "abstract": [
        {
          "text": "Assigns multiple sampler states to a range of entries in the fragment shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setFragmentSamplerStates:withRange:"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentSamplerStates:withRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFragmentSamplerStates:withRange:"
        }
      ],
      "role": "symbol",
      "title": "setFragmentSamplerStates:withRange:",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setfragmentsamplerstates:withrange:"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentTexture(_:index:)": {
      "abstract": [
        {
          "text": "Assigns a texture to an entry in the fragment shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setFragmentTexture"
        },
        {
          "kind": "text",
          "text": "((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "index"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentTexture(_:index:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFragmentTexture:atIndex:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setFragmentTexture(_:index:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setfragmenttexture(_:index:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentTextures(_:range:)": {
      "abstract": [
        {
          "text": "Assigns multiple textures to a range of entries in the fragment shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setFragmentTextures"
        },
        {
          "kind": "text",
          "text": "([(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": ")?], "
        },
        {
          "kind": "externalParam",
          "text": "range"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sn",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentTextures(_:range:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setFragmentTextures(_:range:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setfragmenttextures(_:range:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentTextures:withRange:": {
      "abstract": [
        {
          "text": "Assigns multiple textures to a range of entries in the fragment shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setFragmentTextures:withRange:"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentTextures:withRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFragmentTextures:withRange:"
        }
      ],
      "role": "symbol",
      "title": "setFragmentTextures:withRange:",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setfragmenttextures:withrange:"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentVisibleFunctionTable(_:bufferIndex:)": {
      "abstract": [
        {
          "text": "Assigns a visible function table to an entry in the fragment shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setFragmentVisibleFunctionTable"
        },
        {
          "kind": "text",
          "text": "((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLVisibleFunctionTable",
          "text": "MTLVisibleFunctionTable"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "bufferIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentVisibleFunctionTable(_:bufferIndex:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFragmentVisibleFunctionTable:atBufferIndex:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setFragmentVisibleFunctionTable(_:bufferIndex:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setfragmentvisiblefunctiontable(_:bufferindex:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentVisibleFunctionTables(_:bufferRange:)": {
      "abstract": [
        {
          "text": "Assigns multiple visible function tables to a range of entries in the fragment shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setFragmentVisibleFunctionTables"
        },
        {
          "kind": "text",
          "text": "([(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLVisibleFunctionTable",
          "text": "MTLVisibleFunctionTable"
        },
        {
          "kind": "text",
          "text": ")?], "
        },
        {
          "kind": "externalParam",
          "text": "bufferRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sn",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentVisibleFunctionTables(_:bufferRange:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setFragmentVisibleFunctionTables(_:bufferRange:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setfragmentvisiblefunctiontables(_:bufferrange:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentVisibleFunctionTables:withBufferRange:": {
      "abstract": [
        {
          "text": "Assigns multiple visible function tables to a range of entries in the fragment shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setFragmentVisibleFunctionTables:withBufferRange:"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentVisibleFunctionTables:withBufferRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFragmentVisibleFunctionTables:withBufferRange:"
        }
      ],
      "role": "symbol",
      "title": "setFragmentVisibleFunctionTables:withBufferRange:",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setfragmentvisiblefunctiontables:withbufferrange:"
    },
    "doc://com.apple.metal/documentation/Metal/argument-buffer-resource-preparation-commands": {
      "abstract": [
        {
          "text": "Load individual resources and multiple resources within a heap into GPU memory so that they’re available to shaders through argument buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/argument-buffer-resource-preparation-commands",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Argument Buffer Resource Preparation Commands",
      "type": "topic",
      "url": "/documentation/metal/argument-buffer-resource-preparation-commands"
    },
    "doc://com.apple.metal/documentation/Metal/mesh-and-object-shader-resource-preparation-commands": {
      "abstract": [
        {
          "text": "Assign resources to mesh and object shaders, including buffers, textures, acceleration structures, sampler states, and function tables.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/mesh-and-object-shader-resource-preparation-commands",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mesh and Object Shader Resource Preparation Commands",
      "type": "topic",
      "url": "/documentation/metal/mesh-and-object-shader-resource-preparation-commands"
    },
    "doc://com.apple.metal/documentation/Metal/render-passes": {
      "abstract": [
        {
          "text": "Encode a render pass to draw graphics into an image.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/render-passes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Render Passes",
      "type": "topic",
      "url": "/documentation/metal/render-passes"
    },
    "doc://com.apple.metal/documentation/Metal/tile-shaders-resource-preparation-commands": {
      "abstract": [
        {
          "text": "Assign resources to tile shaders, including buffers, textures, acceleration structures, sampler states, and function tables.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/tile-shaders-resource-preparation-commands",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Tile Shaders Resource Preparation Commands",
      "type": "topic",
      "url": "/documentation/metal/tile-shaders-resource-preparation-commands"
    },
    "doc://com.apple.metal/documentation/Metal/vertex-shader-resource-preparation-commands": {
      "abstract": [
        {
          "text": "Assign resources to vertex shaders, including buffers, textures, acceleration structures, sampler states, and function tables.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/vertex-shader-resource-preparation-commands",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Vertex Shader Resource Preparation Commands",
      "type": "topic",
      "url": "/documentation/metal/vertex-shader-resource-preparation-commands"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Encoding-Resource-Preparation-Commands",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/mesh-and-object-shader-resource-preparation-commands",
        "doc://com.apple.metal/documentation/Metal/vertex-shader-resource-preparation-commands",
        "doc://com.apple.metal/documentation/Metal/tile-shaders-resource-preparation-commands",
        "doc://com.apple.metal/documentation/Metal/argument-buffer-resource-preparation-commands"
      ],
      "title": "Encoding Resource Preparation Commands"
    }
  ],
  "topicSections": [
    {
      "anchor": "Assigning-Buffers",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentBuffer(_:offset:index:)",
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentBuffers(_:offsets:range:)",
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentBytes(_:length:index:)",
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentBufferOffset(_:index:)"
      ],
      "title": "Assigning Buffers"
    },
    {
      "anchor": "Assigning-Textures",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentTexture(_:index:)",
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentTextures(_:range:)"
      ],
      "title": "Assigning Textures"
    },
    {
      "anchor": "Assigning-Sampler-States",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentSamplerState(_:index:)",
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentSamplerState(_:lodMinClamp:lodMaxClamp:index:)",
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentSamplerStates(_:range:)",
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentSamplerStates(_:lodMinClamps:lodMaxClamps:range:)"
      ],
      "title": "Assigning Sampler States"
    },
    {
      "anchor": "Assigning-Acceleration-Structures",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentAccelerationStructure(_:bufferIndex:)"
      ],
      "title": "Assigning Acceleration Structures"
    },
    {
      "anchor": "Assigning-Visible-Function-Tables",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentVisibleFunctionTable(_:bufferIndex:)",
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentVisibleFunctionTables(_:bufferRange:)"
      ],
      "title": "Assigning Visible Function Tables"
    },
    {
      "anchor": "Assigning-Intersection-Function-Tables",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentIntersectionFunctionTable(_:bufferIndex:)",
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentIntersectionFunctionTables(_:bufferRange:)"
      ],
      "title": "Assigning Intersection Function Tables"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Assigning-Buffers",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentBuffer(_:offset:index:)",
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentBuffers:offsets:withRange:",
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentBytes(_:length:index:)",
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentBufferOffset(_:index:)"
              ],
              "title": "Assigning Buffers"
            },
            {
              "anchor": "Assigning-Textures",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentTexture(_:index:)",
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentTextures:withRange:"
              ],
              "title": "Assigning Textures"
            },
            {
              "anchor": "Assigning-Sampler-States",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentSamplerState(_:index:)",
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentSamplerState(_:lodMinClamp:lodMaxClamp:index:)",
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentSamplerStates:withRange:",
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentSamplerStates:lodMinClamps:lodMaxClamps:withRange:"
              ],
              "title": "Assigning Sampler States"
            },
            {
              "anchor": "Assigning-Acceleration-Structures",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentAccelerationStructure(_:bufferIndex:)"
              ],
              "title": "Assigning Acceleration Structures"
            },
            {
              "anchor": "Assigning-Visible-Function-Tables",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentVisibleFunctionTable(_:bufferIndex:)",
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentVisibleFunctionTables:withBufferRange:"
              ],
              "title": "Assigning Visible Function Tables"
            },
            {
              "anchor": "Assigning-Intersection-Function-Tables",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentIntersectionFunctionTable(_:bufferIndex:)",
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setFragmentIntersectionFunctionTables:withBufferRange:"
              ],
              "title": "Assigning Intersection Function Tables"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Encoding-Resource-Preparation-Commands",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/mesh-and-object-shader-resource-preparation-commands",
                "doc://com.apple.metal/documentation/Metal/vertex-shader-resource-preparation-commands",
                "doc://com.apple.metal/documentation/Metal/tile-shaders-resource-preparation-commands",
                "doc://com.apple.metal/documentation/Metal/argument-buffer-resource-preparation-commands"
              ],
              "title": "Encoding Resource Preparation Commands"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder/title",
          "value": "MTLRenderCommandEncoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderCommandEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderCommandEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setFragmentIntersectionFunctionTable(_:bufferIndex:)/title",
          "value": "setFragmentIntersectionFunctionTable:atBufferIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setFragmentIntersectionFunctionTable(_:bufferIndex:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setFragmentIntersectionFunctionTable:atBufferIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setFragmentSamplerState(_:lodMinClamp:lodMaxClamp:index:)/title",
          "value": "setFragmentSamplerState:lodMinClamp:lodMaxClamp:atIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setFragmentSamplerState(_:lodMinClamp:lodMaxClamp:index:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setFragmentSamplerState:lodMinClamp:lodMaxClamp:atIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setFragmentBytes(_:length:index:)/title",
          "value": "setFragmentBytes:length:atIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setFragmentBytes(_:length:index:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setFragmentBytes:length:atIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setFragmentBuffer(_:offset:index:)/title",
          "value": "setFragmentBuffer:offset:atIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setFragmentBuffer(_:offset:index:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setFragmentBuffer:offset:atIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setFragmentAccelerationStructure(_:bufferIndex:)/title",
          "value": "setFragmentAccelerationStructure:atBufferIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setFragmentAccelerationStructure(_:bufferIndex:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setFragmentAccelerationStructure:atBufferIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setFragmentVisibleFunctionTable(_:bufferIndex:)/title",
          "value": "setFragmentVisibleFunctionTable:atBufferIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setFragmentVisibleFunctionTable(_:bufferIndex:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setFragmentVisibleFunctionTable:atBufferIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setFragmentSamplerState(_:index:)/title",
          "value": "setFragmentSamplerState:atIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setFragmentSamplerState(_:index:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setFragmentSamplerState:atIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setFragmentBufferOffset(_:index:)/title",
          "value": "setFragmentBufferOffset:atIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setFragmentBufferOffset(_:index:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setFragmentBufferOffset:atIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setFragmentTexture(_:index:)/title",
          "value": "setFragmentTexture:atIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setFragmentTexture(_:index:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setFragmentTexture:atIndex:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/fragment-shader-resource-preparation-commands"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/fragment-shader-resource-preparation-commands"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
