{
  "abstract": [
    {
      "text": "Take advantage of high dynamic range to present more vibrant colors in your apps and games.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/hdr-content"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "role": "collectionGroup",
    "title": "HDR Content"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "High dynamic range (HDR) content has a wider range of brightness levels than standard definition content. Certain displays, which macOS refers to as extended dynamic range (EDR) displays, can physically replicate those extra brightness values on a screen. You can use Metal to detect EDR displays and work with HDR content, such as from a video asset or directly from your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/determining-support-for-edr-values": {
      "abstract": [
        {
          "text": "Check whether a display supports EDR.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/determining-support-for-edr-values",
      "kind": "article",
      "role": "article",
      "title": "Determining Support for EDR Values",
      "type": "topic",
      "url": "/documentation/metal/determining-support-for-edr-values"
    },
    "doc://com.apple.metal/documentation/Metal/displaying-hdr-content-in-a-metal-layer": {
      "abstract": [
        {
          "text": "Bring your high dynamic range (HDR) content to compatible Mac displays.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/displaying-hdr-content-in-a-metal-layer",
      "kind": "article",
      "role": "article",
      "title": "Displaying HDR Content in a Metal Layer",
      "type": "topic",
      "url": "/documentation/metal/displaying-hdr-content-in-a-metal-layer"
    },
    "doc://com.apple.metal/documentation/Metal/implementing-tone-mapping-on-reference-displays": {
      "abstract": [
        {
          "text": "Detect reference displays and keep your content within the capabilities of the display hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/implementing-tone-mapping-on-reference-displays",
      "kind": "article",
      "role": "article",
      "title": "Implementing Tone Mapping on Reference Displays",
      "type": "topic",
      "url": "/documentation/metal/implementing-tone-mapping-on-reference-displays"
    },
    "doc://com.apple.metal/documentation/Metal/onscreen-presentation": {
      "abstract": [
        {
          "text": "Show the output from a GPU’s rendering pass to the user in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/onscreen-presentation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Onscreen Presentation",
      "type": "topic",
      "url": "/documentation/metal/onscreen-presentation"
    },
    "doc://com.apple.metal/documentation/Metal/performing-your-own-tone-mapping": {
      "abstract": [
        {
          "text": "Apply your own tone mapping to get the exact behavior you want.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/performing-your-own-tone-mapping",
      "kind": "article",
      "role": "article",
      "title": "Performing Your Own Tone Mapping",
      "type": "topic",
      "url": "/documentation/metal/performing-your-own-tone-mapping"
    },
    "doc://com.apple.metal/documentation/Metal/processing-hdr-images-with-metal": {
      "abstract": [
        {
          "text": "Implement a post-processing pipeline using the latest features on Apple GPUs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/processing-hdr-images-with-metal",
      "kind": "article",
      "role": "sampleCode",
      "title": "Processing HDR Images with Metal",
      "type": "topic",
      "url": "/documentation/metal/processing-hdr-images-with-metal"
    },
    "doc://com.apple.metal/documentation/Metal/using-color-spaces-to-display-hdr-content": {
      "abstract": [
        {
          "text": "Use a color space when you don’t need to edit or process the pixel data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/using-color-spaces-to-display-hdr-content",
      "kind": "article",
      "role": "article",
      "title": "Using Color Spaces to Display HDR Content",
      "type": "topic",
      "url": "/documentation/metal/using-color-spaces-to-display-hdr-content"
    },
    "doc://com.apple.metal/documentation/Metal/using-system-tone-mapping-on-video-content": {
      "abstract": [
        {
          "text": "Use EDR metadata to apply the default system tone mapping to a layer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/using-system-tone-mapping-on-video-content",
      "kind": "article",
      "role": "article",
      "title": "Using System Tone Mapping on Video Content",
      "type": "topic",
      "url": "/documentation/metal/using-system-tone-mapping-on-video-content"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Presentation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/onscreen-presentation"
      ],
      "title": "Presentation"
    }
  ],
  "topicSections": [
    {
      "anchor": "High-Dynamic-Range-Content",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/processing-hdr-images-with-metal",
        "doc://com.apple.metal/documentation/Metal/displaying-hdr-content-in-a-metal-layer",
        "doc://com.apple.metal/documentation/Metal/determining-support-for-edr-values",
        "doc://com.apple.metal/documentation/Metal/using-color-spaces-to-display-hdr-content",
        "doc://com.apple.metal/documentation/Metal/using-system-tone-mapping-on-video-content",
        "doc://com.apple.metal/documentation/Metal/performing-your-own-tone-mapping",
        "doc://com.apple.metal/documentation/Metal/implementing-tone-mapping-on-reference-displays"
      ],
      "title": "High Dynamic Range Content"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "High-Dynamic-Range-Content",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/processing-hdr-images-with-metal",
                "doc://com.apple.metal/documentation/Metal/displaying-hdr-content-in-a-metal-layer",
                "doc://com.apple.metal/documentation/Metal/determining-support-for-edr-values",
                "doc://com.apple.metal/documentation/Metal/using-color-spaces-to-display-hdr-content",
                "doc://com.apple.metal/documentation/Metal/using-system-tone-mapping-on-video-content",
                "doc://com.apple.metal/documentation/Metal/performing-your-own-tone-mapping",
                "doc://com.apple.metal/documentation/Metal/implementing-tone-mapping-on-reference-displays"
              ],
              "title": "High Dynamic Range Content"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Presentation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/onscreen-presentation"
              ],
              "title": "Presentation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/hdr-content"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/hdr-content"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
