{
  "abstract": [
    {
      "text": "Fix performance glitches and develop default settings for smooth experiences on Apple platforms using the powerful suite of Metal development tools.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/improving-your-games-graphics-performance-and-settings"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Improving your game’s graphics performance and settings"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Metal games range from having modest performance requirements to pushing hardware to their limits. Players expect smooth frame rates and animation, and when that doesn’t happen, they’re perceived as glitches in the game. You can investigate the underlying cause of these glitches, and organize your work by creating a data collection plan to measure your performance data before and after you make improvements.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "After you understand the performance characteristics of your game, you can tailor the player experience for different devices depending on the available set of features, computing power, and memory resources. You can also identify the game’s features that are performance or image-quality oriented and choose a subset that work for the entire game, and in a variety of circumstances. There are many tools like Instruments, Metal HUD, and GPU Debugger to aide you as you investigate performance bottlenecks in your Metal game.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Avoid-frame-glitches",
          "level": 3,
          "text": "Avoid frame glitches",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Ideally, players perceive that a game runs smoothly if there are no noticeable frame glitches. A frame glitch is commonly defined as any kind of rendering error, hitch, sudden visual change, and low or uneven frame rate. Hitching occurs when a frame takes too long to render and ends up missing the time it was supposed to display onscreen. Streaming resources and loading shaders inefficiently cause sudden visual changes to the game graphics. And inconsistent frame rates cause the game to fluctuate from a steady frame rate to a lower frame rate, especially when a player wants the best frame rate to perform well, such as during an action scene.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "These frame glitches happen on either the CPU or GPU timeline. For example, a game streams data and loads shaders on the CPU timeline while your renderer runs shaders and executes rendering passes on the GPU timeline. If a game has a bottleneck on one of these timelines, it can create delays on the other.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you want a frame to render at a specific frames per second (fps) rate, then profile the game to ensure that it doesn’t exceed a certain time interval per frame, measured in milliseconds (ms). For example, 30 fps is about 33 ms, 40 fps is 25 ms, and 60 fps is about 16 ms. If you design a game to work at 60 fps, then it’s best if the game’s CPU time not exceed 16 ms and the GPU time not exceed 16 ms. Apple ProMotion displays support different frame rates so the game can use a rate like 30, 40, and 60 fps. Note that the CPU and GPU timelines can overlap so each timeline can take up to 16 ms. The following diagram shows a well-paced CPU and GPU timeline:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "improving-your-games-graphics-performance-and-settings-1",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Typically, the frame time isn’t consistent. The number of objects visible on the screen varies, the game might be streaming in the next level, shadow maps might need an update, and so on. If the encoding and rendering times remain within their time budgets, your game’s motion remains smooth. However, if there’s considerable change from one frame to another when they’re almost the same, it’s important to understand the cause. The following diagram shows when this variance isn’t an issue:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "improving-your-games-graphics-performance-and-settings-2",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "An unexpected long task can create a frame glitch in the timeline. For example, the game might introduce a data dependency while it loads textures, models, or shaders for a rendering pass. Some game tasks can increase the CPU utilization and affect the game’s rendering thread. The following diagram shows a long game task on the CPU timeline delaying the encoding of a frame, resulting in a glitch. Profile all parts of the game with Instruments to rule those out.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "improving-your-games-graphics-performance-and-settings-3",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To solve this type of problem, reorganize a long task for the renderer to split it over several frames. Plan to schedule those tasks on a different thread, or manage any dependencies ahead of time so they don’t create stalls. The following diagram shows that splitting the long task resolves this glitch and restores the encoding thread’s optimal timeline:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "improving-your-games-graphics-performance-and-settings-4",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Apply the same approach to the GPU timeline too. Consider a cache to store temporary resources, like shadow maps, or use GPU culling to reduce geometric complexity. Note that tasks that aren’t part of every frame create opportunities to add delays. Carefully understand all parts of the game’s rendering pipeline to locate and eliminate glitches. There are some techniques to measure, understand, and fix these performance problems.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Think-through-performance-problems",
          "level": 3,
          "text": "Think through performance problems",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Performance problems typically have several underlying reasons, or root causes. Root causes are usually separate issues that affect the game to different degrees. The process to fix these issues is measure, analyze, and improve. The first step in investigating performance problems is to measure with tools. Analyze these data measurements to identify the performance problem’s root causes. Some problems are easy to find and fix, but most need investigation. After identifying the root causes, prioritize fixing the problem that affects the game’s performance most. After this improvement, re-measure the game until it meets its performance requirements or repeat this improvement process.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The “five whys” technique is a helpful way to find and scope the root cause of a performance problem. Repeatedly ask and answer the question “why?” five times to gain a more specific understanding of the problem. Here are some sample questions and answers:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Why does my game have frame glitches? On the Metal system trace in Instruments, some frames take longer than 33 ms to render.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Why does the frame time exceed 33 ms? The system trace shows that the game spends 22 ms rendering the G-buffer.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Why does it take 22 ms to render the G-buffer? Measuring the time of the vertex shader stage shows 16 ms, and the fragment shader takes 6 ms to render.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Why does it take 16 ms for the vertex shader to run? A GPU trace shows that the vertex shader is processing 5,000,000 vertices and it looks ALU bound.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Why is the vertex shader ALU bound? The vertex shader uses several matrix multiplications and doesn’t use half-precision types.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "This process creates opportunities to ask additional side questions. Focus on one line of questions at a time and write down the other ones to investigate them afterward. In the example, there was a choice to examine the vertex shader time or the fragment shader time. Because the vertex shader time seems to be the source of the bottleneck, that’s the first place to look. Later, investigate the fragment shader to see if there’s a problem. It’s helpful to put these questions and answers on a diagram or board to see the whole picture. When you make an improvement to the game, then take a full profile again to compare the results and investigate where the next bottleneck is.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Organize-your-work-with-a-plan",
          "level": 3,
          "text": "Organize your work with a plan",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To stay organized, create a data collection plan to decide the key data points in the investigation and validate whether you achieved the desired results. Include a process to store the investigation data when you collect it because the game and its data might change during development. This makes it easier to document a specific problem or validate the improvements you made to the game.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "There are two kinds of performance data: specific collections and general collections. An Instruments trace or GPU Debugger trace is an example of a specific data collection that focuses on a moment in the game. An example of a general data collection is a recording of the frame rate over an entire level, or the game, such as using the Metal HUD or onscreen telemetry.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Tips for creating a plan to collect data:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Include the time and date of the data measurement in a descriptive format. For example, you could use ",
                      "type": "text"
                    },
                    {
                      "code": "YYYYMMDD-HHMM-ToolName-Description-OtherUsefulInformation",
                      "type": "codeVoice"
                    },
                    {
                      "text": " in the filename.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Describe the place in the game where you captured the data and relevant details like the game’s time of day, game coordinates, and player and camera orientations.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add the name of the measurement tool to the data, such as Metal HUD, GPU Debugger trace, Instruments Metal system trace, or in-game telemetry.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Here’s an example of recording a measurement of the frame rate. Capture a video of the game with the Metal HUD and onscreen telemetry turned on during a play-through. The Metal HUD logging option prints performance data to the console, and this can be converted to a file format like comma-separated values (CSV) to analyze the data with a spreadsheet. Scrub through the video to look for glitches. After making an improvement, re-record a similar video and compare the results to understand the improvement. For tips on screen recording, see the following resources:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://support.apple.com/en-us/102618",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://support.apple.com/en-us/102653",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Match the data with the kind of improvement you’re trying to make. For instance, if the goal is to improve the frame rate, then recording the GPU frame time is essential. In this case, record a Metal system trace with Instruments for about 5 to 10 seconds. A second example using Metal HUD is to log and display the game’s memory utilization, especially if there’s instability caused by excess resources in memory. These kinds of performance data measurements help inform decisions for the right initial defaults in a variety of situations, like the player’s device capabilities, preferred frame rate, or image quality.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Choose-the-initial-defaults-for-your-game",
          "level": 3,
          "text": "Choose the initial defaults for your game",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Performance data is useful for selecting good default settings. Choose a few sets of options that work all of the time, rather than presenting all of the options to players. Avoid setting combinations that lead to instability or poor performance. Optimize the game for the range of devices that players may use, and to adjust the default settings based on the device the game is running on. For instance, the game can select a set of defaults based on the amount of memory and the type of processor. For example, the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIDevice/userInterfaceIdiom",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " API on iOS returns the kind of device that the game is running on. Refer to the article ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Xcode/running-code-on-a-specific-version",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for details on customizing the game’s behavior on different Apple platforms.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Each device the game runs on — like iPhone, iPad, or Mac — has different ranges of performance characteristics. Players expect fewer, but tuned, settings for a game running on iPhone compared with Mac. Design a few settings that work well with smaller, portable devices, such as a performance mode that prioritizes battery life and frame rate, and a quality mode that prioritizes image quality. For all devices, tune settings to optimize input latency, frame pacing, and interoperability with the other features on the device. For example, test whether the player can record their screens or switch apps without requiring a restart.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Determine-the-set-of-options-that-work-for-the-entire-game",
          "level": 3,
          "text": "Determine the set of options that work for the entire game",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the data collection plan from earlier to monitor the key details for the entire game. The following list of data points can help determine if the game is stable, stays within its memory budget, and has a good frame rate:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Time of measurement",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Frame time and present time",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Memory usage",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set of options or graphics settings for the game",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "If the game doesn’t meet the required performance targets, this data helps to find the cause. The game might need additional texture and geometry optimizations in a level, renderer fixes, shader improvements, or different graphics settings for a device. Repeat this process until game play is smooth throughout the entire game and meets its performance targets.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Limit-the-systems-burst-performance",
          "level": 3,
          "text": "Limit the system’s burst performance",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use sustained execution mode to limit the burst performance of the system while the game runs. Include the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.sustained-execution",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " entitlement and set the App Category in the ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " to one of the Games categories. Use this entitlement to obtain accurate performance measurements while the game runs. Benchmark and test various areas in the game to tune the sustained performance on different devices.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Detect-the-devices-capabilities-to-choose-the-settings",
          "level": 3,
          "text": "Detect the device’s capabilities to choose the settings",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The game can adjust its runtime performance characteristics by applying these recommendations:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Inspect the Metal feature capabilities (`",
                      "type": "text"
                    },
                    {
                      "code": "MTLGPUFamilyApple8",
                      "type": "codeVoice"
                    },
                    {
                      "text": "`, ",
                      "type": "text"
                    },
                    {
                      "code": "MTLGPUFamilyApple9",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", and so on) with ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFamily(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.kernel.increased-memory-limit",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " entitlement for extra memory on certain iOS devices. Check ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/os/3191911-os_proc_available_memory",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " for the amount of available runtime device memory.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use Quality of Service (QoS) and Grand Central Dispatch (GCD) as shown in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Apple-Silicon/tuning-your-code-s-performance-for-apple-silicon",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "To more finely tune your apps and games, you can call the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/kernel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "doc://com.apple.documentation/documentation/kernel/1387446-sysctlbyname",
              "type": "text"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "See",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "doc://com.apple.documentation/documentation/kernel/1387446-sysctlbyname/determining_system_capabilities",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/download/apple-silicon-cpu-optimization-guide/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "for information about checking the specifics of a device, such as:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "hw.perflevels",
                      "type": "codeVoice"
                    },
                    {
                      "text": " for the number of types of general purpose cores in the system",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "hw.perflevel0.logicalcpu",
                      "type": "codeVoice"
                    },
                    {
                      "text": " for the number of performance cores",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "hw.perflevel1.logicalcpu",
                      "type": "codeVoice"
                    },
                    {
                      "text": " for the number of efficiency cores",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Support-features-on-devices-with-hardware-support",
          "level": 3,
          "text": "Support features on devices with hardware support",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When the game starts, query for the GPU family support with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFamily(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " API and use the device’s supported hardware features, if they’re available. For instance, prefer to enable hardware-accelerated ray tracing when the hardware supports it. If the game needs more memory to use a feature than is available, then disable that feature as a last resort and provide a fallback if possible. Players prefer to use a feature that’s supported in hardware.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Hardware-accelerated mesh shaders and ray tracing are supported on ",
                  "type": "text"
                },
                {
                  "code": "MTLGPUFamilyApple9",
                  "type": "codeVoice"
                },
                {
                  "text": " GPU families.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Adapt-the-game-for-battery-life-or-low-power-mode",
          "level": 3,
          "text": "Adapt the game for battery life or low-power mode",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When designing games that run on a portable device, consider detecting when the app goes into low-power mode. See the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/processinfo/1617047-islowpowermodeenabled",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " API for more information on getting a notification when the system goes into low-power mode. This technique allows a game to adapt its graphics settings so that it uses less energy. For example, the game can:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Lower the rendering resolution",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Limit the frame rate",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use less-detailed models, textures, and shaders",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Metal-Developer-Workflow-PageImage-card.png": {
      "alt": null,
      "identifier": "Metal-Developer-Workflow-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/713b476e42e48070365a2abf70bc49b0/Metal-Developer-Workflow-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e226f618b21dde7899eba5de3bd4641a/Metal-Developer-Workflow-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/Apple-Silicon/tuning-your-code-s-performance-for-apple-silicon": {
      "abstract": [
        {
          "text": "Improve your code to get the best performance from both Apple silicon and Intel-based Mac computers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Apple-Silicon/tuning-your-code-s-performance-for-apple-silicon",
      "kind": "article",
      "role": "article",
      "title": "Tuning Your Code’s Performance for Apple Silicon",
      "type": "topic",
      "url": "/documentation/Apple-Silicon/tuning-your-code-s-performance-for-apple-silicon"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.kernel.increased-memory-limit": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether core features of your app may perform better with a higher memory limit on supported devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.kernel.increased-memory-limit",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.kernel.increased-memory-limit",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.kernel.increased-memory-limit"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.sustained-execution": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your app performs consistently when the system constrains it to a sustainable performance level.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.sustained-execution",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.sustained-execution",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.sustained-execution"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIDevice/userInterfaceIdiom": {
      "abstract": [
        {
          "text": "The style of interface to use on the current device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userInterfaceIdiom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIUserInterfaceIdiom",
          "text": "UIUserInterfaceIdiom"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIDevice/userInterfaceIdiom",
      "kind": "symbol",
      "role": "symbol",
      "title": "userInterfaceIdiom",
      "type": "topic",
      "url": "/documentation/UIKit/UIDevice/userInterfaceIdiom"
    },
    "doc://com.apple.documentation/documentation/Xcode/Analyzing-the-memory-usage-of-your-Metal-app": {
      "abstract": [
        {
          "text": "Keep your app alive in the background by managing its memory footprint.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/Analyzing-the-memory-usage-of-your-Metal-app",
      "kind": "article",
      "role": "article",
      "title": "Analyzing the memory usage of your Metal app",
      "type": "topic",
      "url": "/documentation/Xcode/Analyzing-the-memory-usage-of-your-Metal-app"
    },
    "doc://com.apple.documentation/documentation/Xcode/Analyzing-the-performance-of-your-Metal-app": {
      "abstract": [
        {
          "text": "Ensure consistent, smooth rendering by profiling your app’s frame time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/Analyzing-the-performance-of-your-Metal-app",
      "kind": "article",
      "role": "article",
      "title": "Analyzing the performance of your Metal app",
      "type": "topic",
      "url": "/documentation/Xcode/Analyzing-the-performance-of-your-Metal-app"
    },
    "doc://com.apple.documentation/documentation/Xcode/Metal-debugger": {
      "abstract": [
        {
          "text": "Debug and profile your Metal workload with a GPU trace.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/Metal-debugger",
      "kind": "article",
      "role": "article",
      "title": "Metal debugger",
      "type": "topic",
      "url": "/documentation/Xcode/Metal-debugger"
    },
    "doc://com.apple.documentation/documentation/Xcode/Metal-developer-workflows": {
      "abstract": [
        {
          "text": "Locate and fix issues related to your app’s use of the Metal API and GPU functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/Metal-developer-workflows",
      "images": [
        {
          "identifier": "Metal-Developer-Workflow-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Metal developer workflows",
      "type": "topic",
      "url": "/documentation/Xcode/Metal-developer-workflows"
    },
    "doc://com.apple.documentation/documentation/Xcode/running-code-on-a-specific-version": {
      "abstract": [
        {
          "text": "Add conditional compilation markers around code that requires a particular family of devices or minimum operating system version to run.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/running-code-on-a-specific-version",
      "kind": "article",
      "role": "article",
      "title": "Running code on a specific platform or OS version",
      "type": "topic",
      "url": "/documentation/Xcode/running-code-on-a-specific-version"
    },
    "doc://com.apple.documentation/documentation/foundation/processinfo/1617047-islowpowermodeenabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates the current state of Low Power Mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "isLowPowerModeEnabled"
        },
        {
          "kind": "text",
          "text": ": Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/processinfo/1617047-islowpowermodeenabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "isLowPowerModeEnabled",
      "type": "topic",
      "url": "/documentation/foundation/processinfo/1617047-islowpowermodeenabled"
    },
    "doc://com.apple.documentation/documentation/kernel": {
      "abstract": [
        {
          "text": "Develop kernel-resident device drivers and kernel extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/kernel",
      "kind": "symbol",
      "role": "collection",
      "title": "Kernel",
      "type": "topic",
      "url": "/documentation/kernel"
    },
    "doc://com.apple.documentation/documentation/os/3191911-os_proc_available_memory": {
      "abstract": [
        {
          "text": "Determines the amount of memory available to the current app. ",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/os/3191911-os_proc_available_memory",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_proc_available_memory",
      "type": "topic",
      "url": "/documentation/os/3191911-os_proc_available_memory"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFamily(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the GPU device supports the feature set of a specific GPU family.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsFamily"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLGPUFamily",
          "text": "MTLGPUFamily"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFamily(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsFamily:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "supportsFamily(_:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/supportsfamily(_:)"
    },
    "doc://com.apple.metal/documentation/Metal/capturing-metal-commands-programmatically": {
      "abstract": [
        {
          "text": "Invoke Metal’s frame capture from your app, then save the resulting GPU trace to a file or view it in Xcode.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/capturing-metal-commands-programmatically",
      "kind": "article",
      "role": "sampleCode",
      "title": "Capturing Metal Commands Programmatically",
      "type": "topic",
      "url": "/documentation/metal/capturing-metal-commands-programmatically"
    },
    "doc://com.apple.metal/documentation/Metal/developing-metal-apps-that-run-in-simulator": {
      "abstract": [
        {
          "text": "Prototype and test your Metal apps in Simulator.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/developing-metal-apps-that-run-in-simulator",
      "kind": "article",
      "role": "article",
      "title": "Developing Metal apps that run in Simulator",
      "type": "topic",
      "url": "/documentation/metal/developing-metal-apps-that-run-in-simulator"
    },
    "doc://com.apple.metal/documentation/Metal/gpu-counters-and-counter-sample-buffers": {
      "abstract": [
        {
          "text": "Retrieve runtime data from a GPU device by sampling one or more of its counters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/gpu-counters-and-counter-sample-buffers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GPU Counters and Counter Sample Buffers",
      "type": "topic",
      "url": "/documentation/metal/gpu-counters-and-counter-sample-buffers"
    },
    "doc://com.apple.metal/documentation/Metal/metal-debugging-types": {
      "abstract": [
        {
          "text": "Create capture managers and capture scopes, and review a GPU device’s log after it runs a command buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-debugging-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Debugging Types",
      "type": "topic",
      "url": "/documentation/metal/metal-debugging-types"
    },
    "doc://com.apple.metal/documentation/Metal/supporting-simulator-in-a-metal-app": {
      "abstract": [
        {
          "text": "Configure alternative render paths in your Metal app to enable running your app in Simulator.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/supporting-simulator-in-a-metal-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Supporting Simulator in a Metal app",
      "type": "topic",
      "url": "/documentation/metal/supporting-simulator-in-a-metal-app"
    },
    "https://developer.apple.com/download/apple-silicon-cpu-optimization-guide/": {
      "identifier": "https://developer.apple.com/download/apple-silicon-cpu-optimization-guide/",
      "title": "Apple Silicon CPU Optimization Guide",
      "titleInlineContent": [
        {
          "text": "Apple Silicon CPU Optimization Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/download/apple-silicon-cpu-optimization-guide/"
    },
    "https://support.apple.com/en-us/102618": {
      "identifier": "https://support.apple.com/en-us/102618",
      "title": "How to record the screen on your Mac",
      "titleInlineContent": [
        {
          "text": "How to record the screen on your Mac",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/en-us/102618"
    },
    "https://support.apple.com/en-us/102653": {
      "identifier": "https://support.apple.com/en-us/102653",
      "title": "Record the screen on your iPhone, iPad, or iPod touch",
      "titleInlineContent": [
        {
          "text": "Record the screen on your iPhone, iPad, or iPod touch",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/en-us/102653"
    },
    "improving-your-games-graphics-performance-and-settings-1": {
      "alt": "A diagram that depicts the CPU, GPU, and display timelines for the encoding, rendering, and display of a sequence of five frames. The timing is uniform showing that there are no frame pacing problems.",
      "identifier": "improving-your-games-graphics-performance-and-settings-1",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/6127a4b2ba981eb86502a0e11e61a466/improving-your-games-graphics-performance-and-settings-1@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/1e1c548e6356917ad36895a84ff29d78/improving-your-games-graphics-performance-and-settings-1~dark@2x.png"
        }
      ]
    },
    "improving-your-games-graphics-performance-and-settings-2": {
      "alt": "A diagram depicting the CPU, GPU, and display timelines for the encoding, rendering, and display for a sequence of five frames. The blocks aren’t uniformly sized, but remain within the time limits and don’t create frame pacing problems.",
      "identifier": "improving-your-games-graphics-performance-and-settings-2",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/a4e16b45cf3ea2b4ea8d85a2803301bc/improving-your-games-graphics-performance-and-settings-2@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/b8445e95236dc83ed495a251d4293130/improving-your-games-graphics-performance-and-settings-2~dark@2x.png"
        }
      ]
    },
    "improving-your-games-graphics-performance-and-settings-3": {
      "alt": "A diagram depicting the CPU, GPU, and display timelines for the encoding, rendering, and display for a sequence of five frames. There’s a long task inserted into the CPU timeline that delays the encoding of one of the frames so that it causes the previous frame to be shown for twice as long, resulting in a hitch on the display.",
      "identifier": "improving-your-games-graphics-performance-and-settings-3",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/86aa662fb11204a098600750d12b827a/improving-your-games-graphics-performance-and-settings-3@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/9d780b01d314cd914ccc512c4f98b50e/improving-your-games-graphics-performance-and-settings-3~dark@2x.png"
        }
      ]
    },
    "improving-your-games-graphics-performance-and-settings-4": {
      "alt": "A diagram depicting the CPU, GPU, and display timelines for the encoding, rendering, and display for a sequence of five frames. The long task from the previous diagram is split so that it doesn’t delay the encoding of the frames and result in a hitch on the display.",
      "identifier": "improving-your-games-graphics-performance-and-settings-4",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d5b6650062d1aca8a130436bfc00a104/improving-your-games-graphics-performance-and-settings-4@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/8398c6bbc27706b4c8e55910b65473cf/improving-your-games-graphics-performance-and-settings-4~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Developer-Tools",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/Xcode/Metal-developer-workflows",
        "doc://com.apple.documentation/documentation/Xcode/Metal-debugger",
        "doc://com.apple.metal/documentation/Metal/capturing-metal-commands-programmatically",
        "doc://com.apple.metal/documentation/Metal/supporting-simulator-in-a-metal-app",
        "doc://com.apple.documentation/documentation/Xcode/Analyzing-the-memory-usage-of-your-Metal-app",
        "doc://com.apple.documentation/documentation/Xcode/Analyzing-the-performance-of-your-Metal-app",
        "doc://com.apple.metal/documentation/Metal/developing-metal-apps-that-run-in-simulator",
        "doc://com.apple.metal/documentation/Metal/gpu-counters-and-counter-sample-buffers",
        "doc://com.apple.metal/documentation/Metal/metal-debugging-types"
      ],
      "title": "Developer Tools"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Developer-Tools",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/capturing-metal-commands-programmatically",
                "doc://com.apple.metal/documentation/Metal/supporting-simulator-in-a-metal-app",
                "doc://com.apple.metal/documentation/Metal/developing-metal-apps-that-run-in-simulator",
                "doc://com.apple.metal/documentation/Metal/gpu-counters-and-counter-sample-buffers",
                "doc://com.apple.metal/documentation/Metal/metal-debugging-types"
              ],
              "title": "Developer Tools"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsFamily(_:)/title",
          "value": "supportsFamily:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsFamily(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "supportsFamily:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIDevice~1userInterfaceIdiom/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UIUserInterfaceIdiom",
              "text": "UIUserInterfaceIdiom"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "userInterfaceIdiom"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1processinfo~11617047-islowpowermodeenabled/title",
          "value": "lowPowerModeEnabled"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/improving-your-games-graphics-performance-and-settings"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/improving-your-games-graphics-performance-and-settings"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
