{
  "abstract": [
    {
      "text": "Print debugging messages that a shader generates using shader logging.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/logging-shader-debug-messages"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Logging shader debug messages"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "With shader logging, you can print debugging messages directly from the shader in your app, to help identify issues you may not catch otherwise. You can view these messages from the Console app, the log command-line tool, or the Xcode debug area.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Enable-shader-logging",
          "level": 3,
          "text": "Enable shader logging",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To enable shader logging, you first need to enable the compiler setting in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLCompileOptions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". You can either do this directly through Xcode, or while building your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLLibrary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Shader logging is only available in Metal 3.2 and later. It’s also only available in iOS 18 and later, iPadOS 18 and later, macOS 15 and later, tvOS 18 and later, and visionOS 2 and later.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To enable the compiler setting through Xcode:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Choose your project in the Project Navigator and select the target you want to enable logging for. Click Build Settings at the top.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Search for “Other Metal Compiler Flags”.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add ",
                      "type": "text"
                    },
                    {
                      "code": "-fmetal-enable-logging",
                      "type": "codeVoice"
                    },
                    {
                      "text": " as a compile flag.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The following image shows an Xcode project’s build settings with the compiler flag set:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4484952",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can also enable the same compiler setting through the command line:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "xcrun metal -std=metal3.2 -fmetal-enable-logging -o helloTriangle.metallib helloTriangle.metal"
          ],
          "syntax": "shell",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "If you’re creating a Metal Library by compiling source code using ",
              "type": "text"
            },
            {
              "code": "newLibraryWithSource",
              "type": "codeVoice"
            },
            {
              "text": ", use the ",
              "type": "text"
            },
            {
              "code": "MTLCompileOptions",
              "type": "codeVoice"
            },
            {
              "text": " object’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/enableLogging",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to set the compile option:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "MTLCompileOptions *options = [MTLCompileOptions new];",
            "options.libraryType = MTLLibraryTypeExecutable;",
            "options.enableLogging = true;",
            "id<MTLLibrary> myLibrary = newLibraryWithSource: (NSString *) myShaderPath",
            "                                        options: (MTLCompileOptions *) options",
            "                                          error: (NSError * _Nullable *) error;"
          ],
          "syntax": "objective-c",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "After you set the compiler settings, set the app’s environment variables. The two environment variables that influence logging are ",
              "type": "text"
            },
            {
              "code": "MTL_LOG_LEVEL",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "MTL_LOG_BUFFER_SIZE",
              "type": "codeVoice"
            },
            {
              "text": ". If you define only one of the variables, the other assumes its default value. The default value for ",
              "type": "text"
            },
            {
              "code": "MTL_LOG_LEVEL",
              "type": "codeVoice"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "code": "MTLLogLevelDebug",
              "type": "codeVoice"
            },
            {
              "text": ", and the default value for ",
              "type": "text"
            },
            {
              "code": "MTL_LOG_BUFFER_SIZE",
              "type": "codeVoice"
            },
            {
              "text": " is 1024 bytes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To set the environment variables:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Open your Xcode project.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "From the Xcode menu, select Product > Scheme > Edit Scheme.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In the new window, select Run > Arguments.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add the variables by clicking the plus button under “Environment Variables”.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The following image shows an Xcode project with both of the logging environment variables:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4484950",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "code": "MTL_LOG_BUFFER_SIZE",
              "type": "codeVoice"
            },
            {
              "text": " is the storage capacity for the logging data, in bytes. Anticipating the volume of data can help you determine a buffer size to use. If the shader generates many logs, use a larger buffer size. The minimum capacity is 1 KB, and the maximum is 1 GB. When the log buffer reaches its capacity, the system discards any subsequent messages.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Draining of the log buffer is heavily dependent on the duration of the command buffers, and only happens after the command buffer finishes. As a result, the system may not maintain the sequence of messages.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "MTL_LOG_LEVEL",
              "type": "codeVoice"
            },
            {
              "text": " variable is the minimum logging level you want to use. The system doesn’t add any messages to the log buffer with a level lower than the one you set. The acceptable log level values are:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The log level that captures diagnostic information.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "MTLLogLevelDebug",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The log level that captures additional information.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "MTLLogLevelInfo",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The log level that captures notifications.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "MTLLogLevelNotice",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The log level that captures error information.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "MTLLogLevelError",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The log level that captures fault information.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "MTLLogLevelFault",
                    "type": "codeVoice"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "anchor": "Generate-and-view-the-log-messages",
          "level": 3,
          "text": "Generate and view the log messages",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After you enable shader logging, add ",
              "type": "text"
            },
            {
              "code": "os_log",
              "type": "codeVoice"
            },
            {
              "text": " functions to your shader to begin generating the log messages:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "uint index [[thread_position_in_grid]];",
            "",
            "[[kernel]] void myKernel()",
            "{",
            "    if (index == 7)",
            "    {",
            "        metal::os_log_default.log_info(\"Hello There!\")",
            "    }",
            "}"
          ],
          "syntax": "metal",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "If you want to filter the log messages you preview, use ",
              "type": "text"
            },
            {
              "code": "os_log",
              "type": "codeVoice"
            },
            {
              "text": " functions along with subsystems and categories. To specify the subsystems and categories, create an ",
              "type": "text"
            },
            {
              "code": "os_log",
              "type": "codeVoice"
            },
            {
              "text": " object. You can then use this object and call logging functions similarly to the code snippet above. The subsystem, category, and format strings should be less than 1024 characters per message. Exceeding this limit can result in truncated messages:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "constant os_log logger(/*subsystem=*/\"com.metal.xyz\", /*category=*/\"abc\");",
            "",
            "uint index [[thread_position_in_grid]];",
            "",
            "[[kernel]] void myKernel()",
            "{",
            "    if (index == 7)",
            "    {",
            "        logger.log_info(\"Hello There!\");",
            "    }",
            "}"
          ],
          "syntax": "metal",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Logging functions, like any other function, execute once per thread. In a multithreaded kernel, you’re responsible for limiting the logging to either a single or specific number of threads. Failing to do so causes you to call logging functions for each thread, which can quickly fill up the log buffer. This can lead to dropping messages, and a reduction in system performance.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To learn more about generating log messages, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/os/generating-log-messages-from-your-code",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can view the shader logs using the Console app, the log command-line tool, or through the Xcode debug area. If you’re using ",
              "type": "text"
            },
            {
              "code": "log_info()",
              "type": "codeVoice"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "code": "log_debug()",
              "type": "codeVoice"
            },
            {
              "text": ", make sure to include info or debug messages by selecting the appropriate option in the Console app. To show or hide these messages, select Action > Include Info Messages/Include Debug Messages from the Console menu:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4481526",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To view the logs through the Xcode debug console, set the environment variable ",
              "type": "text"
            },
            {
              "code": "MTL_LOG_TO_STDERR",
              "type": "codeVoice"
            },
            {
              "text": " to 1.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Use-shader-logging-via-the-API",
          "level": 3,
          "text": "Use shader logging via the API",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The above methods enable shader logging for the entire app. However, if you want to enable logging for a specific command buffer or command queue, you can use the Metal API, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLLogState",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To create an ",
              "type": "text"
            },
            {
              "code": "MTLLogState",
              "type": "codeVoice"
            },
            {
              "text": ", first create a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLLogStateDescriptor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and set its buffer size and log level:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "MTLLogStateDescriptor *logStateDesc = [MTLLogStateDescriptor new];",
            "logStateDesc.bufferSize = 2048;",
            "logStateDesc.level = MTLLogLevelDebug;"
          ],
          "syntax": "objective-c",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "You can then create the ",
              "type": "text"
            },
            {
              "code": "MTLLogState",
              "type": "codeVoice"
            },
            {
              "text": " using the descriptor:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "id<MTLLogState> logState = [device newLogStateWithDescriptor:logStateDesc error:&error];"
          ],
          "syntax": "objective-c",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "This ",
              "type": "text"
            },
            {
              "code": "LogState",
              "type": "codeVoice"
            },
            {
              "text": " can attach to one or more command buffers by setting its ",
              "type": "text"
            },
            {
              "code": "logState",
              "type": "codeVoice"
            },
            {
              "text": " property in the ",
              "type": "text"
            },
            {
              "code": "CommandBufferDescriptor",
              "type": "codeVoice"
            },
            {
              "text": ". If you attach this same log state to multiple command buffers, they all share a single log buffer to store the log data:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "MTLCommandBufferDescriptor *cbufDesc = [MTLCommandBufferDescriptor new];",
            "cbufDesc.logState = logState;",
            "id<MTLCommandBuffer> cbuf = [queue commandBufferWithDescriptor:cbufDesc];"
          ],
          "syntax": "objective-c",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Through a similar process, you can attach the log state to a command queue:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "MTLCommandQueueDescriptor *cqDesc = [MTLCommandQueueDescriptor new];",
            "cqDesc.logState = logState;",
            "id<MTLCommandQueue> cq = [device newCommandQueueWithDescriptor:cqDesc];"
          ],
          "syntax": "objective-c",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Multiple instances of ",
              "type": "text"
            },
            {
              "code": "MTLLogState",
              "type": "codeVoice"
            },
            {
              "text": " occupy separate memory. Avoid creating excessive log states with large log buffers, as this can lead to your app exceeding its memory limit. If you share a log state between buffers, the system may delay or block the draining of the buffer until all command buffers finish. If the buffer drains, you may see log messages that an unfinished buffer generated.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "By default, you can still view all log messages through either the Console app or the ",
              "type": "text"
            },
            {
              "code": "log",
              "type": "codeVoice"
            },
            {
              "text": " command-line tool. However, log handlers give you an alternative method to preview the logs. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLLogState/addLogHandler(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method allows you to add one or more log handlers to a log state. You can also filter and customize the way you preview the messages by using a subsystem and category:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "[logState addLogHandler:^(NSString *substring, NSString *category,",
            "                          MTLLogLevel level, NSString *message)",
            "{",
            "    if ([substring isEqualToString:@\"com.metal.xyz\"] && ",
            "        [category isEqualToString:@\"abc\"])",
            "    {",
            "        NSLog(@\"%@\", message);",
            "    }",
            "}];"
          ],
          "syntax": "objective-c",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "In the absence of using log handlers, your CPU adds a default handler that internally calls ",
              "type": "text"
            },
            {
              "code": "OSLog",
              "type": "codeVoice"
            },
            {
              "text": " functions to preview logging. For more information on viewing log messages, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/os/viewing-log-messages",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Xcode/Optimizing-GPU-performance": {
      "abstract": [
        {
          "text": "Find and address performance bottlenecks using the Metal debugger.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/Optimizing-GPU-performance",
      "kind": "article",
      "role": "article",
      "title": "Optimizing GPU performance",
      "type": "topic",
      "url": "/documentation/Xcode/Optimizing-GPU-performance"
    },
    "doc://com.apple.documentation/documentation/Xcode/stepping-through-code-and-inspecting-variables-to-isolate-bugs": {
      "abstract": [
        {
          "text": "Find the cause of your bugs by watching variables change as you step through your source code in the debugger.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/stepping-through-code-and-inspecting-variables-to-isolate-bugs",
      "kind": "article",
      "role": "article",
      "title": "Stepping through code and inspecting variables to isolate bugs",
      "type": "topic",
      "url": "/documentation/Xcode/stepping-through-code-and-inspecting-variables-to-isolate-bugs"
    },
    "doc://com.apple.documentation/documentation/os/generating-log-messages-from-your-code": {
      "abstract": [
        {
          "text": "Record useful debugging and analysis information, and include dynamic content in your messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/os/generating-log-messages-from-your-code",
      "kind": "article",
      "role": "article",
      "title": "Generating Log Messages from Your Code",
      "type": "topic",
      "url": "/documentation/os/generating-log-messages-from-your-code"
    },
    "doc://com.apple.documentation/documentation/os/viewing-log-messages": {
      "abstract": [
        {
          "text": "Use various tools to retrieve log information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/os/viewing-log-messages",
      "kind": "article",
      "role": "article",
      "title": "Viewing Log Messages",
      "type": "topic",
      "url": "/documentation/os/viewing-log-messages"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCompileOptions": {
      "abstract": [
        {
          "text": "Compilation settings for a Metal shader library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCompileOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCompileOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCompileOptions"
        }
      ],
      "role": "symbol",
      "title": "MTLCompileOptions",
      "type": "topic",
      "url": "/documentation/metal/mtlcompileoptions"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/enableLogging": {
      "abstract": [
        {
          "text": "A Boolean value that enables shader logging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enableLogging"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCompileOptions/enableLogging",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enableLogging"
        }
      ],
      "role": "symbol",
      "title": "enableLogging",
      "type": "topic",
      "url": "/documentation/metal/mtlcompileoptions/enablelogging"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLibrary": {
      "abstract": [
        {
          "text": "A collection of Metal shader functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLLibrary"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLibrary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLibrary"
        }
      ],
      "role": "symbol",
      "title": "MTLLibrary",
      "type": "topic",
      "url": "/documentation/metal/mtllibrary"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLogState": {
      "abstract": [
        {
          "text": "A container for shader log messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLLogState"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLogState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLogState"
        }
      ],
      "role": "symbol",
      "title": "MTLLogState",
      "type": "topic",
      "url": "/documentation/metal/mtllogstate"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLogState/addLogHandler(_:)": {
      "abstract": [
        {
          "text": "Adds a log handler to customize the presentation of shader logging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addLogHandler"
        },
        {
          "kind": "text",
          "text": "(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLLogLevel",
          "text": "MTLLogLevel"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLogState/addLogHandler(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addLogHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "addLogHandler(_:)",
      "type": "topic",
      "url": "/documentation/metal/mtllogstate/addloghandler(_:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLogStateDescriptor": {
      "abstract": [
        {
          "text": "An interface that represents a log state configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLLogStateDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLogStateDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLogStateDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLLogStateDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtllogstatedescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/shader-libraries": {
      "abstract": [
        {
          "text": "Manage and load your app’s Metal shaders.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/shader-libraries",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Shader Libraries",
      "type": "topic",
      "url": "/documentation/metal/shader-libraries"
    },
    "doc://com.apple.metal/documentation/Metal/using-function-specialization-to-build-pipeline-variants": {
      "abstract": [
        {
          "text": "Create pipelines for different levels of detail from a common shader source.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/using-function-specialization-to-build-pipeline-variants",
      "kind": "article",
      "role": "sampleCode",
      "title": "Using Function Specialization to Build Pipeline Variants",
      "type": "topic",
      "url": "/documentation/metal/using-function-specialization-to-build-pipeline-variants"
    },
    "media-4481526": {
      "alt": "An image showing the Console app with a message that reads “Hello There!” in a log from a shader.",
      "identifier": "media-4481526",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/538e4c10d65c8bcf48e1ae60003c8f9b/media-4481526@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/6bb881157f46d705de50cc309ccad386/media-4481526~dark@2x.png"
        }
      ]
    },
    "media-4484950": {
      "alt": "An image showing an Xcode project’s environment variables set. The MTL_LOG_LEVEL variable is set with a value of MTLLogLevelDebug, and the MTL_LOG_BUFFER_SIZE is set with a value of 2048.",
      "identifier": "media-4484950",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/4ae21aa29ad17143cfbc1f3ce5c9b902/media-4484950@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/47a1745713c0ab6622f2d896fded2a87/media-4484950~dark@2x.png"
        }
      ]
    },
    "media-4484952": {
      "alt": "An image showing an Xcode project’s build settings with the -fmetal-enable-logging compiler flag set. The image also shows the Metal Language Revision set to use Metal 3.2.",
      "identifier": "media-4484952",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ece9104ce19c53da29a81f3bb8d2a9c8/media-4484952@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/9d86bb901d241d25a6b3fc0cd461954e/media-4484952~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Shaders",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/Xcode/stepping-through-code-and-inspecting-variables-to-isolate-bugs",
        "doc://com.apple.documentation/documentation/Xcode/Optimizing-GPU-performance",
        "doc://com.apple.metal/documentation/Metal/using-function-specialization-to-build-pipeline-variants",
        "doc://com.apple.metal/documentation/Metal/shader-libraries"
      ],
      "title": "Shaders"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Shaders",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/using-function-specialization-to-build-pipeline-variants",
                "doc://com.apple.metal/documentation/Metal/shader-libraries"
              ],
              "title": "Shaders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogState/title",
          "value": "MTLLogState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLogState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLogState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogStateDescriptor/title",
          "value": "MTLLogStateDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogStateDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLogStateDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogStateDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLogStateDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompileOptions/title",
          "value": "MTLCompileOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompileOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCompileOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompileOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCompileOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompileOptions~1enableLogging/title",
          "value": "enableLogging"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompileOptions~1enableLogging/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enableLogging"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLibrary/title",
          "value": "MTLLibrary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLibrary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLibrary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogState~1addLogHandler(_:)/title",
          "value": "addLogHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogState~1addLogHandler(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addLogHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/logging-shader-debug-messages"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/logging-shader-debug-messages"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
