{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/metal-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Metal Enumerations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgumentBuffersTier": {
      "abstract": [
        {
          "text": "The values that determine the limits and capabilities of argument buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLArgumentBuffersTier"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgumentBuffersTier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgumentBuffersTier"
        }
      ],
      "role": "symbol",
      "title": "MTLArgumentBuffersTier",
      "type": "topic",
      "url": "/documentation/metal/mtlargumentbufferstier"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLogStateError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLLogStateError"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLogStateError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLogStateError"
        }
      ],
      "role": "symbol",
      "title": "MTLLogStateError",
      "type": "topic",
      "url": "/documentation/metal/mtllogstateerror"
    },
    "doc://com.apple.metal/documentation/Metal/MTLMathFloatingPointFunctions": {
      "abstract": [
        {
          "text": "Indicates which FP32 math functions Metal uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLMathFloatingPointFunctions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLMathFloatingPointFunctions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLMathFloatingPointFunctions"
        }
      ],
      "role": "symbol",
      "title": "MTLMathFloatingPointFunctions",
      "type": "topic",
      "url": "/documentation/metal/mtlmathfloatingpointfunctions"
    },
    "doc://com.apple.metal/documentation/Metal/MTLMathMode": {
      "abstract": [
        {
          "text": "An indication of whether the compiler can perform optimizations for floating-point arithmetic that may violate the IEEE 754 standard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLMathMode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLMathMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLMathMode"
        }
      ],
      "role": "symbol",
      "title": "MTLMathMode",
      "type": "topic",
      "url": "/documentation/metal/mtlmathmode"
    },
    "doc://com.apple.metal/documentation/Metal/MTLMatrixLayout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLMatrixLayout"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLMatrixLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLMatrixLayout"
        }
      ],
      "role": "symbol",
      "title": "MTLMatrixLayout",
      "type": "topic",
      "url": "/documentation/metal/mtlmatrixlayout"
    },
    "doc://com.apple.metal/documentation/Metal/MTLReadWriteTextureTier": {
      "abstract": [
        {
          "text": "The support level for read-write texture formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLReadWriteTextureTier"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLReadWriteTextureTier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLReadWriteTextureTier"
        }
      ],
      "role": "symbol",
      "title": "MTLReadWriteTextureTier",
      "type": "topic",
      "url": "/documentation/metal/mtlreadwritetexturetier"
    },
    "doc://com.apple.metal/documentation/Metal/MTLShaderValidation": {
      "abstract": [
        {
          "text": "Indicates whether shader validation in an enabled or disabled state, or neither state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLShaderValidation"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLShaderValidation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLShaderValidation"
        }
      ],
      "role": "symbol",
      "title": "MTLShaderValidation",
      "type": "topic",
      "url": "/documentation/metal/mtlshadervalidation"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTransformType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLTransformType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTransformType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTransformType"
        }
      ],
      "role": "symbol",
      "title": "MTLTransformType",
      "type": "topic",
      "url": "/documentation/metal/mtltransformtype"
    },
    "doc://com.apple.metal/documentation/Metal/metal-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Constants",
      "type": "topic",
      "url": "/documentation/metal/metal-constants"
    },
    "doc://com.apple.metal/documentation/Metal/metal-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Data Types",
      "type": "topic",
      "url": "/documentation/metal/metal-data-types"
    },
    "doc://com.apple.metal/documentation/Metal/metal-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Functions",
      "type": "topic",
      "url": "/documentation/metal/metal-functions"
    },
    "doc://com.apple.metal/documentation/Metal/metal-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Macros",
      "type": "topic",
      "url": "/documentation/metal/metal-macros"
    },
    "doc://com.apple.metal/documentation/Metal/metal-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Structures",
      "type": "topic",
      "url": "/documentation/metal/metal-structures"
    },
    "doc://com.apple.metal/documentation/Metal/metal-variables": {
      "abstract": [],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-variables",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Variables",
      "type": "topic",
      "url": "/documentation/metal/metal-variables"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/metal-structures",
        "doc://com.apple.metal/documentation/Metal/metal-constants",
        "doc://com.apple.metal/documentation/Metal/metal-data-types",
        "doc://com.apple.metal/documentation/Metal/metal-variables"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLArgumentBuffersTier",
        "doc://com.apple.metal/documentation/Metal/MTLLogStateError",
        "doc://com.apple.metal/documentation/Metal/MTLMathFloatingPointFunctions",
        "doc://com.apple.metal/documentation/Metal/MTLMathMode",
        "doc://com.apple.metal/documentation/Metal/MTLMatrixLayout",
        "doc://com.apple.metal/documentation/Metal/MTLReadWriteTextureTier",
        "doc://com.apple.metal/documentation/Metal/MTLShaderValidation",
        "doc://com.apple.metal/documentation/Metal/MTLTransformType"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLArgumentBuffersTier",
                "doc://com.apple.metal/documentation/Metal/MTLLogStateError",
                "doc://com.apple.metal/documentation/Metal/MTLMathFloatingPointFunctions",
                "doc://com.apple.metal/documentation/Metal/MTLMathMode",
                "doc://com.apple.metal/documentation/Metal/MTLMatrixLayout",
                "doc://com.apple.metal/documentation/Metal/MTLReadWriteTextureTier",
                "doc://com.apple.metal/documentation/Metal/MTLShaderValidation",
                "doc://com.apple.metal/documentation/Metal/MTLTransformType"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/metal-structures",
                "doc://com.apple.metal/documentation/Metal/metal-constants",
                "doc://com.apple.metal/documentation/Metal/metal-functions",
                "doc://com.apple.metal/documentation/Metal/metal-data-types",
                "doc://com.apple.metal/documentation/Metal/metal-variables",
                "doc://com.apple.metal/documentation/Metal/metal-macros"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMathMode/title",
          "value": "MTLMathMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMathMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLMathMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMathMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLMathMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMathFloatingPointFunctions/title",
          "value": "MTLMathFloatingPointFunctions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMathFloatingPointFunctions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLMathFloatingPointFunctions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMathFloatingPointFunctions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLMathFloatingPointFunctions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTransformType/title",
          "value": "MTLTransformType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTransformType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTransformType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTransformType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTransformType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLShaderValidation/title",
          "value": "MTLShaderValidation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLShaderValidation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLShaderValidation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLShaderValidation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLShaderValidation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLReadWriteTextureTier/title",
          "value": "MTLReadWriteTextureTier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLReadWriteTextureTier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLReadWriteTextureTier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLReadWriteTextureTier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLReadWriteTextureTier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMatrixLayout/title",
          "value": "MTLMatrixLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMatrixLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLMatrixLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMatrixLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLMatrixLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogStateError/title",
          "value": "MTLLogStateError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogStateError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLogStateError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogStateError/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLogStateError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentBuffersTier/title",
          "value": "MTLArgumentBuffersTier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentBuffersTier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentBuffersTier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentBuffersTier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentBuffersTier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/metal-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/metal-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
