{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/metal-variables"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Metal Variables"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLResourceCPUCacheModeMask": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLResourceCPUCacheModeMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLResourceCPUCacheModeMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLResourceCPUCacheModeMask"
        }
      ],
      "role": "symbol",
      "title": "MTLResourceCPUCacheModeMask",
      "type": "topic",
      "url": "/documentation/metal/mtlresourcecpucachemodemask"
    },
    "doc://com.apple.metal/documentation/Metal/MTLResourceCPUCacheModeShift": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLResourceCPUCacheModeShift"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLResourceCPUCacheModeShift",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLResourceCPUCacheModeShift"
        }
      ],
      "role": "symbol",
      "title": "MTLResourceCPUCacheModeShift",
      "type": "topic",
      "url": "/documentation/metal/mtlresourcecpucachemodeshift"
    },
    "doc://com.apple.metal/documentation/Metal/MTLResourceHazardTrackingModeMask": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLResourceHazardTrackingModeMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLResourceHazardTrackingModeMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLResourceHazardTrackingModeMask"
        }
      ],
      "role": "symbol",
      "title": "MTLResourceHazardTrackingModeMask",
      "type": "topic",
      "url": "/documentation/metal/mtlresourcehazardtrackingmodemask"
    },
    "doc://com.apple.metal/documentation/Metal/MTLResourceHazardTrackingModeShift": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLResourceHazardTrackingModeShift"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLResourceHazardTrackingModeShift",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLResourceHazardTrackingModeShift"
        }
      ],
      "role": "symbol",
      "title": "MTLResourceHazardTrackingModeShift",
      "type": "topic",
      "url": "/documentation/metal/mtlresourcehazardtrackingmodeshift"
    },
    "doc://com.apple.metal/documentation/Metal/MTLResourceStorageModeMask": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLResourceStorageModeMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLResourceStorageModeMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLResourceStorageModeMask"
        }
      ],
      "role": "symbol",
      "title": "MTLResourceStorageModeMask",
      "type": "topic",
      "url": "/documentation/metal/mtlresourcestoragemodemask"
    },
    "doc://com.apple.metal/documentation/Metal/MTLResourceStorageModeShift": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLResourceStorageModeShift"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLResourceStorageModeShift",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLResourceStorageModeShift"
        }
      ],
      "role": "symbol",
      "title": "MTLResourceStorageModeShift",
      "type": "topic",
      "url": "/documentation/metal/mtlresourcestoragemodeshift"
    },
    "doc://com.apple.metal/documentation/Metal/NSDeviceCertification/iPhonePerformanceGaming": {
      "abstract": [
        {
          "text": "The performance gaming tier for iPhone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iPhonePerformanceGaming"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSDeviceCertification",
          "text": "NSDeviceCertification"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/NSDeviceCertification/iPhonePerformanceGaming",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDeviceCertificationiPhonePerformanceGaming"
        }
      ],
      "role": "symbol",
      "title": "iPhonePerformanceGaming",
      "type": "topic",
      "url": "/documentation/metal/nsdevicecertification/iphoneperformancegaming"
    },
    "doc://com.apple.metal/documentation/Metal/NSProcessInfoPerformanceProfileDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSProcessInfoPerformanceProfileDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/NSProcessInfoPerformanceProfileDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSProcessInfoPerformanceProfileDidChangeNotification",
      "type": "topic",
      "url": "/documentation/metal/nsprocessinfoperformanceprofiledidchangenotification"
    },
    "doc://com.apple.metal/documentation/Metal/NSProcessPerformanceProfile/default": {
      "abstract": [
        {
          "text": "The default performance profile for a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSProcessPerformanceProfile",
          "text": "NSProcessPerformanceProfile"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/NSProcessPerformanceProfile/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSProcessPerformanceProfileDefault"
        }
      ],
      "role": "symbol",
      "title": "default",
      "type": "topic",
      "url": "/documentation/metal/nsprocessperformanceprofile/default"
    },
    "doc://com.apple.metal/documentation/Metal/NSProcessPerformanceProfile/sustained": {
      "abstract": [
        {
          "text": "The performance profile for a device representing sustained performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sustained"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSProcessPerformanceProfile",
          "text": "NSProcessPerformanceProfile"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/NSProcessPerformanceProfile/sustained",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSProcessPerformanceProfileSustained"
        }
      ],
      "role": "symbol",
      "title": "sustained",
      "type": "topic",
      "url": "/documentation/metal/nsprocessperformanceprofile/sustained"
    },
    "doc://com.apple.metal/documentation/Metal/metal-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Constants",
      "type": "topic",
      "url": "/documentation/metal/metal-constants"
    },
    "doc://com.apple.metal/documentation/Metal/metal-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Data Types",
      "type": "topic",
      "url": "/documentation/metal/metal-data-types"
    },
    "doc://com.apple.metal/documentation/Metal/metal-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Enumerations",
      "type": "topic",
      "url": "/documentation/metal/metal-enumerations"
    },
    "doc://com.apple.metal/documentation/Metal/metal-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Functions",
      "type": "topic",
      "url": "/documentation/metal/metal-functions"
    },
    "doc://com.apple.metal/documentation/Metal/metal-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Macros",
      "type": "topic",
      "url": "/documentation/metal/metal-macros"
    },
    "doc://com.apple.metal/documentation/Metal/metal-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Structures",
      "type": "topic",
      "url": "/documentation/metal/metal-structures"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/metal-structures",
        "doc://com.apple.metal/documentation/Metal/metal-enumerations",
        "doc://com.apple.metal/documentation/Metal/metal-constants",
        "doc://com.apple.metal/documentation/Metal/metal-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Global-Variables",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLResourceCPUCacheModeMask",
        "doc://com.apple.metal/documentation/Metal/MTLResourceCPUCacheModeShift",
        "doc://com.apple.metal/documentation/Metal/MTLResourceHazardTrackingModeMask",
        "doc://com.apple.metal/documentation/Metal/MTLResourceHazardTrackingModeShift",
        "doc://com.apple.metal/documentation/Metal/MTLResourceStorageModeMask",
        "doc://com.apple.metal/documentation/Metal/MTLResourceStorageModeShift",
        "doc://com.apple.metal/documentation/Metal/NSDeviceCertification/iPhonePerformanceGaming",
        "doc://com.apple.metal/documentation/Metal/NSProcessPerformanceProfile/default",
        "doc://com.apple.metal/documentation/Metal/NSProcessPerformanceProfile/sustained"
      ],
      "title": "Global Variables"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Global-Variables",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLResourceCPUCacheModeMask",
                "doc://com.apple.metal/documentation/Metal/MTLResourceCPUCacheModeShift",
                "doc://com.apple.metal/documentation/Metal/MTLResourceHazardTrackingModeMask",
                "doc://com.apple.metal/documentation/Metal/MTLResourceHazardTrackingModeShift",
                "doc://com.apple.metal/documentation/Metal/MTLResourceStorageModeMask",
                "doc://com.apple.metal/documentation/Metal/MTLResourceStorageModeShift",
                "doc://com.apple.metal/documentation/Metal/NSDeviceCertification/iPhonePerformanceGaming",
                "doc://com.apple.metal/documentation/Metal/NSProcessInfoPerformanceProfileDidChangeNotification",
                "doc://com.apple.metal/documentation/Metal/NSProcessPerformanceProfile/default",
                "doc://com.apple.metal/documentation/Metal/NSProcessPerformanceProfile/sustained"
              ],
              "title": "Global Variables"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/metal-structures",
                "doc://com.apple.metal/documentation/Metal/metal-enumerations",
                "doc://com.apple.metal/documentation/Metal/metal-constants",
                "doc://com.apple.metal/documentation/Metal/metal-functions",
                "doc://com.apple.metal/documentation/Metal/metal-data-types",
                "doc://com.apple.metal/documentation/Metal/metal-macros"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1NSProcessPerformanceProfile~1default/title",
          "value": "NSProcessPerformanceProfileDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1NSProcessPerformanceProfile~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSProcessPerformanceProfileDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceStorageModeMask/title",
          "value": "MTLResourceStorageModeMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceStorageModeMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResourceStorageModeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1NSProcessPerformanceProfile~1sustained/title",
          "value": "NSProcessPerformanceProfileSustained"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1NSProcessPerformanceProfile~1sustained/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSProcessPerformanceProfileSustained"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1NSDeviceCertification~1iPhonePerformanceGaming/title",
          "value": "NSDeviceCertificationiPhonePerformanceGaming"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1NSDeviceCertification~1iPhonePerformanceGaming/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeviceCertificationiPhonePerformanceGaming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceHazardTrackingModeMask/title",
          "value": "MTLResourceHazardTrackingModeMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceHazardTrackingModeMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResourceHazardTrackingModeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceStorageModeShift/title",
          "value": "MTLResourceStorageModeShift"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceStorageModeShift/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResourceStorageModeShift"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceCPUCacheModeShift/title",
          "value": "MTLResourceCPUCacheModeShift"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceCPUCacheModeShift/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResourceCPUCacheModeShift"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceHazardTrackingModeShift/title",
          "value": "MTLResourceHazardTrackingModeShift"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceHazardTrackingModeShift/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResourceHazardTrackingModeShift"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceCPUCacheModeMask/title",
          "value": "MTLResourceCPUCacheModeMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceCPUCacheModeMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResourceCPUCacheModeMask"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/metal-variables"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/metal-variables"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
