{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/metal-structures"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Metal Structures"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct": {
      "abstract": [
        {
          "text": "An error that occurred when creating a binary shader archive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLBinaryArchiveError"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBinaryArchiveError"
        }
      ],
      "role": "symbol",
      "title": "MTLBinaryArchiveError",
      "type": "topic",
      "url": "/documentation/metal/mtlbinaryarchiveerror-swift.struct"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct": {
      "abstract": [
        {
          "text": "The command buffer error codes that indicate why the GPU doesn’t finish executing a command buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCommandBufferError"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferError"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct"
    },
    "doc://com.apple.metal/documentation/Metal/MTLComponentTransform": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLComponentTransform"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLComponentTransform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLComponentTransform"
        }
      ],
      "role": "symbol",
      "title": "MTLComponentTransform",
      "type": "topic",
      "url": "/documentation/metal/mtlcomponenttransform"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterSampleBufferError-swift.struct": {
      "abstract": [
        {
          "text": "The error codes that indicate why a GPU driver can’t create a counter sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCounterSampleBufferError"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterSampleBufferError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCounterSampleBufferError"
        }
      ],
      "role": "symbol",
      "title": "MTLCounterSampleBufferError",
      "type": "topic",
      "url": "/documentation/metal/mtlcountersamplebuffererror-swift.struct"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct": {
      "abstract": [
        {
          "text": "Errors when compiling dynamic libraries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDynamicLibraryError"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDynamicLibraryError"
        }
      ],
      "role": "symbol",
      "title": "MTLDynamicLibraryError",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOError-swift.struct": {
      "abstract": [
        {
          "text": "The categories of errors for creating an input/output file handle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIOError"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOError"
        }
      ],
      "role": "symbol",
      "title": "MTLIOError",
      "type": "topic",
      "url": "/documentation/metal/mtlioerror-swift.struct"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPackedFloatQuaternion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLPackedFloatQuaternion"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPackedFloatQuaternion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPackedFloatQuaternion"
        }
      ],
      "role": "symbol",
      "title": "MTLPackedFloatQuaternion",
      "type": "topic",
      "url": "/documentation/metal/mtlpackedfloatquaternion"
    },
    "doc://com.apple.metal/documentation/Metal/MTLStitchedLibraryOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLStitchedLibraryOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLStitchedLibraryOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLStitchedLibraryOptions"
        }
      ],
      "role": "symbol",
      "title": "MTLStitchedLibraryOptions",
      "type": "topic",
      "url": "/documentation/metal/mtlstitchedlibraryoptions"
    },
    "doc://com.apple.metal/documentation/Metal/NSDeviceCertification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDeviceCertification"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/NSDeviceCertification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDeviceCertification"
        }
      ],
      "role": "symbol",
      "title": "NSDeviceCertification",
      "type": "topic",
      "url": "/documentation/metal/nsdevicecertification"
    },
    "doc://com.apple.metal/documentation/Metal/NSProcessPerformanceProfile": {
      "abstract": [
        {
          "text": "A value describing the device’s performance profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSProcessPerformanceProfile"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/NSProcessPerformanceProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSProcessPerformanceProfile"
        }
      ],
      "role": "symbol",
      "title": "NSProcessPerformanceProfile",
      "type": "topic",
      "url": "/documentation/metal/nsprocessperformanceprofile"
    },
    "doc://com.apple.metal/documentation/Metal/metal-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Constants",
      "type": "topic",
      "url": "/documentation/metal/metal-constants"
    },
    "doc://com.apple.metal/documentation/Metal/metal-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Data Types",
      "type": "topic",
      "url": "/documentation/metal/metal-data-types"
    },
    "doc://com.apple.metal/documentation/Metal/metal-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Enumerations",
      "type": "topic",
      "url": "/documentation/metal/metal-enumerations"
    },
    "doc://com.apple.metal/documentation/Metal/metal-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Functions",
      "type": "topic",
      "url": "/documentation/metal/metal-functions"
    },
    "doc://com.apple.metal/documentation/Metal/metal-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Macros",
      "type": "topic",
      "url": "/documentation/metal/metal-macros"
    },
    "doc://com.apple.metal/documentation/Metal/metal-variables": {
      "abstract": [],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-variables",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Variables",
      "type": "topic",
      "url": "/documentation/metal/metal-variables"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/metal-enumerations",
        "doc://com.apple.metal/documentation/Metal/metal-constants",
        "doc://com.apple.metal/documentation/Metal/metal-data-types",
        "doc://com.apple.metal/documentation/Metal/metal-variables"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Structures",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct",
        "doc://com.apple.metal/documentation/Metal/MTLComponentTransform",
        "doc://com.apple.metal/documentation/Metal/MTLCounterSampleBufferError-swift.struct",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct",
        "doc://com.apple.metal/documentation/Metal/MTLIOError-swift.struct",
        "doc://com.apple.metal/documentation/Metal/MTLPackedFloatQuaternion",
        "doc://com.apple.metal/documentation/Metal/MTLStitchedLibraryOptions",
        "doc://com.apple.metal/documentation/Metal/NSDeviceCertification",
        "doc://com.apple.metal/documentation/Metal/NSProcessPerformanceProfile"
      ],
      "title": "Structures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Structures",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLComponentTransform",
                "doc://com.apple.metal/documentation/Metal/MTLPackedFloatQuaternion",
                "doc://com.apple.metal/documentation/Metal/MTLStitchedLibraryOptions",
                "doc://com.apple.metal/documentation/Metal/NSDeviceCertification",
                "doc://com.apple.metal/documentation/Metal/NSProcessPerformanceProfile"
              ],
              "title": "Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/metal-enumerations",
                "doc://com.apple.metal/documentation/Metal/metal-constants",
                "doc://com.apple.metal/documentation/Metal/metal-functions",
                "doc://com.apple.metal/documentation/Metal/metal-data-types",
                "doc://com.apple.metal/documentation/Metal/metal-variables",
                "doc://com.apple.metal/documentation/Metal/metal-macros"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStitchedLibraryOptions/title",
          "value": "MTLStitchedLibraryOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStitchedLibraryOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStitchedLibraryOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStitchedLibraryOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStitchedLibraryOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComponentTransform/title",
          "value": "MTLComponentTransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComponentTransform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLComponentTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComponentTransform/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLComponentTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1NSProcessPerformanceProfile/title",
          "value": "NSProcessPerformanceProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1NSProcessPerformanceProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSProcessPerformanceProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1NSProcessPerformanceProfile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSProcessPerformanceProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1NSDeviceCertification/title",
          "value": "NSDeviceCertification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1NSDeviceCertification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeviceCertification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1NSDeviceCertification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeviceCertification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPackedFloatQuaternion/title",
          "value": "MTLPackedFloatQuaternion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPackedFloatQuaternion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPackedFloatQuaternion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPackedFloatQuaternion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPackedFloatQuaternion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/metal-structures"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/metal-structures"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
