{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/metal-data-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Metal Data Types"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/NSDeviceCertification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDeviceCertification"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/NSDeviceCertification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDeviceCertification"
        }
      ],
      "role": "symbol",
      "title": "NSDeviceCertification",
      "type": "topic",
      "url": "/documentation/metal/nsdevicecertification"
    },
    "doc://com.apple.metal/documentation/Metal/NSProcessPerformanceProfile": {
      "abstract": [
        {
          "text": "A value describing the device’s performance profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSProcessPerformanceProfile"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/NSProcessPerformanceProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSProcessPerformanceProfile"
        }
      ],
      "role": "symbol",
      "title": "NSProcessPerformanceProfile",
      "type": "topic",
      "url": "/documentation/metal/nsprocessperformanceprofile"
    },
    "doc://com.apple.metal/documentation/Metal/metal-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Constants",
      "type": "topic",
      "url": "/documentation/metal/metal-constants"
    },
    "doc://com.apple.metal/documentation/Metal/metal-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Enumerations",
      "type": "topic",
      "url": "/documentation/metal/metal-enumerations"
    },
    "doc://com.apple.metal/documentation/Metal/metal-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Functions",
      "type": "topic",
      "url": "/documentation/metal/metal-functions"
    },
    "doc://com.apple.metal/documentation/Metal/metal-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Macros",
      "type": "topic",
      "url": "/documentation/metal/metal-macros"
    },
    "doc://com.apple.metal/documentation/Metal/metal-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Structures",
      "type": "topic",
      "url": "/documentation/metal/metal-structures"
    },
    "doc://com.apple.metal/documentation/Metal/metal-variables": {
      "abstract": [],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-variables",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Variables",
      "type": "topic",
      "url": "/documentation/metal/metal-variables"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/metal-structures",
        "doc://com.apple.metal/documentation/Metal/metal-enumerations",
        "doc://com.apple.metal/documentation/Metal/metal-constants",
        "doc://com.apple.metal/documentation/Metal/metal-variables"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/NSDeviceCertification",
        "doc://com.apple.metal/documentation/Metal/NSProcessPerformanceProfile"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/NSDeviceCertification",
                "doc://com.apple.metal/documentation/Metal/NSProcessPerformanceProfile"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/metal-structures",
                "doc://com.apple.metal/documentation/Metal/metal-enumerations",
                "doc://com.apple.metal/documentation/Metal/metal-constants",
                "doc://com.apple.metal/documentation/Metal/metal-functions",
                "doc://com.apple.metal/documentation/Metal/metal-variables",
                "doc://com.apple.metal/documentation/Metal/metal-macros"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1NSProcessPerformanceProfile/title",
          "value": "NSProcessPerformanceProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1NSProcessPerformanceProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSProcessPerformanceProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1NSProcessPerformanceProfile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSProcessPerformanceProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1NSDeviceCertification/title",
          "value": "NSDeviceCertification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1NSDeviceCertification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeviceCertification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1NSDeviceCertification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeviceCertification"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/metal-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/metal-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
