{
  "abstract": [
    {
      "text": "A collection of model data for GPU-accelerated intersection of rays with the model.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructure"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MTLAccelerationStructure",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLAccelerationStructure"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLAccelerationStructure"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "MTLAccelerationStructure"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructure"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLResource",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)MTLResource",
              "text": "MTLResource"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.metal/documentation/Metal/improving-cpu-performance-by-using-argument-buffers"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To accelerate ray tracing, the device object needs to reorganize your model data into an optimized data structure for intersection testing on that GPU. Create  ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructure",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects to contain your model data and reference them in compute and render  commands that execute ray-tracing operations.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You don’t define classes that implement this protocol. To create an acceleration structure, you create a descriptor object and configure its properties with your model data. Then call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/makeAccelerationStructure(descriptor:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method on the Metal device object to create the object and reserve memory for the structure. To populate the structure with the data, use a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureCommandEncoder",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to encode GPU commands.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Metal provides multiple descriptor classes, each describing a different type of model data. Choose the appropriate descriptor for each acceleration structure you want to make. Most often, you create an acceleration structure for each list of triangles or bounding boxes. Then collect related geometry structures into a primitive acceleration structure. Create instance acceleration structures when you need to reference instances of primitive acceleration structures at different locations within a scene.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The table below summarizes the descriptor classes:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Descriptor class",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Usage",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureTriangleGeometryDescriptor",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Describes an acceleration structure for a list of triangles.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureBoundingBoxGeometryDescriptor",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Describes an acceleration structure for a list of bounding boxes.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPrimitiveAccelerationStructureDescriptor",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Describes an acceleration structure for a list of bounding-box or triangle acceleration structures, effectively creating a union of all of the underlying geometry.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Describes an acceleration structure for a list of instances of primitive acceleration structures.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructure": {
      "abstract": [
        {
          "text": "A collection of model data for GPU-accelerated intersection of rays with the model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructure"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructure"
        }
      ],
      "role": "symbol",
      "title": "MTLAccelerationStructure",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructure"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructure/gpuResourceID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gpuResourceID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MTLResourceID",
          "text": "MTLResourceID"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructure/gpuResourceID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gpuResourceID"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "gpuResourceID",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructure/gpuresourceid"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructure/size": {
      "abstract": [
        {
          "text": "The size of the acceleration structure’s memory allocation, in bytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructure/size",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "size"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "size",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructure/size"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureBoundingBoxGeometryDescriptor": {
      "abstract": [
        {
          "text": "A description of a list of bounding boxes to turn into an acceleration structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureBoundingBoxGeometryDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureBoundingBoxGeometryDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureBoundingBoxGeometryDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLAccelerationStructureBoundingBoxGeometryDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructureboundingboxgeometrydescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureCommandEncoder": {
      "abstract": [
        {
          "text": "An object for encoding commands that build or refit acceleration structures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureCommandEncoder"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureCommandEncoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureCommandEncoder"
        }
      ],
      "role": "symbol",
      "title": "MTLAccelerationStructureCommandEncoder",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructurecommandencoder"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureDescriptor": {
      "abstract": [
        {
          "text": "A base class for classes that define the configuration for a new acceleration structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLAccelerationStructureDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructuredescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureRefitOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureRefitOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureRefitOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureRefitOptions"
        }
      ],
      "role": "symbol",
      "title": "MTLAccelerationStructureRefitOptions",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructurerefitoptions"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureTriangleGeometryDescriptor": {
      "abstract": [
        {
          "text": "A description of a list of triangle primitives to turn into an acceleration structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureTriangleGeometryDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureTriangleGeometryDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureTriangleGeometryDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLAccelerationStructureTriangleGeometryDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructuretrianglegeometrydescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureUsage": {
      "abstract": [
        {
          "text": "Options that describe which tasks you can perform on an acceleration structure and how the system performs those tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureUsage"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureUsage"
        }
      ],
      "role": "symbol",
      "title": "MTLAccelerationStructureUsage",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructureusage"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAllocation": {
      "abstract": [
        {
          "text": "A memory allocation from a Metal GPU device, such as a memory heap, texture, or data buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAllocation"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAllocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAllocation"
        }
      ],
      "role": "symbol",
      "title": "MTLAllocation",
      "type": "topic",
      "url": "/documentation/metal/mtlallocation"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/makeAccelerationStructure(descriptor:)": {
      "abstract": [
        {
          "text": "Creates a new ray-tracing acceleration structure from a descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeAccelerationStructure"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLAccelerationStructureDescriptor",
          "text": "MTLAccelerationStructureDescriptor"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLAccelerationStructure",
          "text": "MTLAccelerationStructure"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/makeAccelerationStructure(descriptor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newAccelerationStructureWithDescriptor:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeAccelerationStructure(descriptor:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/makeaccelerationstructure(descriptor:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor": {
      "abstract": [
        {
          "text": "A description of an acceleration structure that derives from instances of primitive acceleration structures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLInstanceAccelerationStructureDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLInstanceAccelerationStructureDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLInstanceAccelerationStructureDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlinstanceaccelerationstructuredescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPrimitiveAccelerationStructureDescriptor": {
      "abstract": [
        {
          "text": "A description of an acceleration structure that contains geometry primitives.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLPrimitiveAccelerationStructureDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPrimitiveAccelerationStructureDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPrimitiveAccelerationStructureDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLPrimitiveAccelerationStructureDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlprimitiveaccelerationstructuredescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLResource": {
      "abstract": [
        {
          "text": "An allocation of memory accessible to a GPU.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLResource"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLResource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLResource"
        }
      ],
      "role": "symbol",
      "title": "MTLResource",
      "type": "topic",
      "url": "/documentation/metal/mtlresource"
    },
    "doc://com.apple.metal/documentation/Metal/improving-cpu-performance-by-using-argument-buffers": {
      "abstract": [
        {
          "text": "Optimize your app’s performance by grouping your resources into argument buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/improving-cpu-performance-by-using-argument-buffers",
      "kind": "article",
      "role": "article",
      "title": "Improving CPU Performance by Using Argument Buffers",
      "type": "topic",
      "url": "/documentation/metal/improving-cpu-performance-by-using-argument-buffers"
    },
    "doc://com.apple.metal/documentation/Metal/improving-ray-tracing-data-access-using-per-primitive-data": {
      "abstract": [
        {
          "text": "Simplify data access and improve GPU utilization by storing custom primitive data directly in the acceleration structure.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/improving-ray-tracing-data-access-using-per-primitive-data",
      "kind": "article",
      "role": "article",
      "title": "Improving Ray-Tracing Data Access Using Per-Primitive Data",
      "type": "topic",
      "url": "/documentation/metal/improving-ray-tracing-data-access-using-per-primitive-data"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLAllocation",
        "doc://com.apple.metal/documentation/Metal/MTLResource",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Acceleration-Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/improving-ray-tracing-data-access-using-per-primitive-data",
        "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureDescriptor",
        "doc://com.apple.metal/documentation/Metal/MTLPrimitiveAccelerationStructureDescriptor",
        "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor",
        "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureCommandEncoder",
        "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureUsage",
        "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureRefitOptions"
      ],
      "title": "Acceleration Structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Reading-the-Structures-Size",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructure/size"
      ],
      "title": "Reading the Structure’s Size"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructure/gpuResourceID"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLAccelerationStructure"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Reading-the-Structures-Size",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructure/size"
              ],
              "title": "Reading the Structure’s Size"
            },
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructure/gpuResourceID"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLResource"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Acceleration-Structures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/improving-ray-tracing-data-access-using-per-primitive-data",
                "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureDescriptor",
                "doc://com.apple.metal/documentation/Metal/MTLPrimitiveAccelerationStructureDescriptor",
                "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor",
                "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureCommandEncoder",
                "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureUsage",
                "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureRefitOptions"
              ],
              "title": "Acceleration Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLAccelerationStructure"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.apple.metal/documentation/Metal/MTLResource",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)MTLResource",
                    "text": "MTLResource"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureBoundingBoxGeometryDescriptor/title",
          "value": "MTLAccelerationStructureBoundingBoxGeometryDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureBoundingBoxGeometryDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureBoundingBoxGeometryDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureBoundingBoxGeometryDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureBoundingBoxGeometryDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructure/title",
          "value": "MTLAccelerationStructure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructure/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPrimitiveAccelerationStructureDescriptor/title",
          "value": "MTLPrimitiveAccelerationStructureDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPrimitiveAccelerationStructureDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPrimitiveAccelerationStructureDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPrimitiveAccelerationStructureDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPrimitiveAccelerationStructureDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor/title",
          "value": "MTLInstanceAccelerationStructureDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLInstanceAccelerationStructureDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLInstanceAccelerationStructureDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResource/title",
          "value": "MTLResource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureTriangleGeometryDescriptor/title",
          "value": "MTLAccelerationStructureTriangleGeometryDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureTriangleGeometryDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureTriangleGeometryDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureTriangleGeometryDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureTriangleGeometryDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureDescriptor/title",
          "value": "MTLAccelerationStructureDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructure~1size/title",
          "value": "size"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructure~1size/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureCommandEncoder/title",
          "value": "MTLAccelerationStructureCommandEncoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureCommandEncoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureCommandEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureCommandEncoder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureCommandEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureRefitOptions/title",
          "value": "MTLAccelerationStructureRefitOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureRefitOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureRefitOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureRefitOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureRefitOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAllocation/title",
          "value": "MTLAllocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAllocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAllocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAllocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAllocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructure~1gpuResourceID/title",
          "value": "gpuResourceID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructure~1gpuResourceID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gpuResourceID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeAccelerationStructure(descriptor:)/title",
          "value": "newAccelerationStructureWithDescriptor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeAccelerationStructure(descriptor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newAccelerationStructureWithDescriptor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureUsage/title",
          "value": "MTLAccelerationStructureUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureUsage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureUsage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlaccelerationstructure"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlaccelerationstructure"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
