{
  "abstract": [
    {
      "text": "Function access restrictions to argument data in the shading language code.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLArgumentAccess"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@MTLArgumentAccess",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLArgumentAccess"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLArgumentAccess"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "8.0",
        "name": "iOS",
        "renamed": "MTLBindingAccess",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "8.0",
        "name": "iPadOS",
        "renamed": "MTLBindingAccess",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "renamed": "MTLBindingAccess",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "10.11",
        "name": "macOS",
        "renamed": "MTLBindingAccess",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "name": "tvOS",
        "renamed": "MTLBindingAccess",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "renamed": "MTLBindingAccess",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "MTLArgumentAccess"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLArgumentAccess"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingAccess",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MTLBindingAccess",
              "text": "MTLBindingAccess"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgument": {
      "abstract": [
        {
          "text": "Information about an argument of a graphics or compute function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLArgument"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgument"
        }
      ],
      "role": "symbol",
      "title": "MTLArgument",
      "type": "topic",
      "url": "/documentation/metal/mtlargument"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgumentAccess": {
      "abstract": [
        {
          "text": "Function access restrictions to argument data in the shading language code.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLArgumentAccess"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgumentAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgumentAccess"
        }
      ],
      "role": "symbol",
      "title": "MTLArgumentAccess",
      "type": "topic",
      "url": "/documentation/metal/mtlargumentaccess"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgumentType": {
      "abstract": [
        {
          "text": "The resource type for an argument of a function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLArgumentType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgumentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgumentType"
        }
      ],
      "role": "symbol",
      "title": "MTLArgumentType",
      "type": "topic",
      "url": "/documentation/metal/mtlargumenttype"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttribute": {
      "abstract": [
        {
          "text": "An object that describes an attribute defined in the stage-in argument for a shader.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAttribute"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttribute"
        }
      ],
      "role": "symbol",
      "title": "MTLAttribute",
      "type": "topic",
      "url": "/documentation/metal/mtlattribute"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedArgument": {
      "abstract": [
        {
          "text": "A convenience type alias for an autoreleased argument instance.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAutoreleasedArgument"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedArgument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAutoreleasedArgument"
        }
      ],
      "role": "symbol",
      "title": "MTLAutoreleasedArgument",
      "type": "topic",
      "url": "/documentation/metal/mtlautoreleasedargument"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingAccess": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLBindingAccess"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBindingAccess"
        }
      ],
      "role": "symbol",
      "title": "MTLBindingAccess",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingaccess"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/MTLArgumentAccessReadOnly": {
      "abstract": [
        {
          "text": "The function can only read its argument data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTLArgumentAccessReadOnly"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/MTLArgumentAccessReadOnly",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLArgumentAccessReadOnly",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingaccess/mtlargumentaccessreadonly"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/MTLArgumentAccessReadWrite": {
      "abstract": [
        {
          "text": "The function can either read or write its argument data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTLArgumentAccessReadWrite"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/MTLArgumentAccessReadWrite",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLArgumentAccessReadWrite",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingaccess/mtlargumentaccessreadwrite"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/MTLArgumentAccessWriteOnly": {
      "abstract": [
        {
          "text": "The function can only write its argument data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTLArgumentAccessWriteOnly"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/MTLArgumentAccessWriteOnly",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLArgumentAccessWriteOnly",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingaccess/mtlargumentaccesswriteonly"
    },
    "doc://com.apple.metal/documentation/Metal/MTLVertexAttribute": {
      "abstract": [
        {
          "text": "An object that represents an attribute of a vertex function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLVertexAttribute"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLVertexAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLVertexAttribute"
        }
      ],
      "role": "symbol",
      "title": "MTLVertexAttribute",
      "type": "topic",
      "url": "/documentation/metal/mtlvertexattribute"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Function-Arguments",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLAttribute",
        "doc://com.apple.metal/documentation/Metal/MTLVertexAttribute",
        "doc://com.apple.metal/documentation/Metal/MTLArgument",
        "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedArgument",
        "doc://com.apple.metal/documentation/Metal/MTLArgumentType"
      ],
      "title": "Function Arguments"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLArgumentAccess"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Specifying-Access-Options",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/MTLArgumentAccessReadOnly",
                "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/MTLArgumentAccessWriteOnly",
                "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/MTLArgumentAccessReadWrite"
              ],
              "title": "Specifying Access Options"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Function-Arguments",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLAttribute",
                "doc://com.apple.metal/documentation/Metal/MTLVertexAttribute",
                "doc://com.apple.metal/documentation/Metal/MTLArgument",
                "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedArgument",
                "doc://com.apple.metal/documentation/Metal/MTLArgumentType"
              ],
              "title": "Function Arguments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingAccess",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@MTLBindingAccess",
                    "text": "MTLBindingAccess"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLArgumentAccess"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAutoreleasedArgument/title",
          "value": "MTLAutoreleasedArgument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAutoreleasedArgument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAutoreleasedArgument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAutoreleasedArgument/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAutoreleasedArgument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentAccess/title",
          "value": "MTLArgumentAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentAccess/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttribute/title",
          "value": "MTLAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingAccess/title",
          "value": "MTLBindingAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingAccess/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgument/title",
          "value": "MTLArgument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgument/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexAttribute/title",
          "value": "MTLVertexAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexAttribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType/title",
          "value": "MTLArgumentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlargumentaccess"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlargumentaccess"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
