{
  "abstract": [
    {
      "text": "The resource type for an argument of a function.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLArgumentType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLArgumentType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLArgumentType"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLArgumentType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.0",
        "introducedAt": "8.0",
        "name": "iOS",
        "renamed": "MTLBindingType",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.0",
        "introducedAt": "8.0",
        "name": "iPadOS",
        "renamed": "MTLBindingType",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.0",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "renamed": "MTLBindingType",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "10.11",
        "name": "macOS",
        "renamed": "MTLBindingType",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.0",
        "name": "tvOS",
        "renamed": "MTLBindingType",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "renamed": "MTLBindingType",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTLArgumentType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLArgumentType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgument": {
      "abstract": [
        {
          "text": "Information about an argument of a graphics or compute function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLArgument"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgument"
        }
      ],
      "role": "symbol",
      "title": "MTLArgument",
      "type": "topic",
      "url": "/documentation/metal/mtlargument"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgumentAccess": {
      "abstract": [
        {
          "text": "Function access restrictions to argument data in the shading language code.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLArgumentAccess"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgumentAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgumentAccess"
        }
      ],
      "role": "symbol",
      "title": "MTLArgumentAccess",
      "type": "topic",
      "url": "/documentation/metal/mtlargumentaccess"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgumentType": {
      "abstract": [
        {
          "text": "The resource type for an argument of a function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLArgumentType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgumentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgumentType"
        }
      ],
      "role": "symbol",
      "title": "MTLArgumentType",
      "type": "topic",
      "url": "/documentation/metal/mtlargumenttype"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgumentType/buffer": {
      "abstract": [
        {
          "text": "The argument is a buffer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buffer"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgumentType/buffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgumentTypeBuffer"
        }
      ],
      "role": "symbol",
      "title": "MTLArgumentType.buffer",
      "type": "topic",
      "url": "/documentation/metal/mtlargumenttype/buffer"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgumentType/imageblock": {
      "abstract": [
        {
          "text": "The argument is an imageblock.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageblock"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgumentType/imageblock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgumentTypeImageblock"
        }
      ],
      "role": "symbol",
      "title": "MTLArgumentType.imageblock",
      "type": "topic",
      "url": "/documentation/metal/mtlargumenttype/imageblock"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgumentType/imageblockData": {
      "abstract": [
        {
          "text": "The argument is imageblock data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageblockData"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgumentType/imageblockData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgumentTypeImageblockData"
        }
      ],
      "role": "symbol",
      "title": "MTLArgumentType.imageblockData",
      "type": "topic",
      "url": "/documentation/metal/mtlargumenttype/imageblockdata"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgumentType/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgumentType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/metal/mtlargumenttype/init(rawvalue:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgumentType/instanceAccelerationStructure": {
      "abstract": [
        {
          "text": "The argument is a top-level ray tracing acceleration structure for a set of instances.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instanceAccelerationStructure"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgumentType/instanceAccelerationStructure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgumentTypeInstanceAccelerationStructure"
        }
      ],
      "role": "symbol",
      "title": "MTLArgumentType.instanceAccelerationStructure",
      "type": "topic",
      "url": "/documentation/metal/mtlargumenttype/instanceaccelerationstructure"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgumentType/intersectionFunctionTable": {
      "abstract": [
        {
          "text": "The argument is an intersection function table.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "intersectionFunctionTable"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgumentType/intersectionFunctionTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgumentTypeIntersectionFunctionTable"
        }
      ],
      "role": "symbol",
      "title": "MTLArgumentType.intersectionFunctionTable",
      "type": "topic",
      "url": "/documentation/metal/mtlargumenttype/intersectionfunctiontable"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgumentType/primitiveAccelerationStructure": {
      "abstract": [
        {
          "text": "The argument is a bottom-level ray tracing acceleraton structure for a set of primitives.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primitiveAccelerationStructure"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgumentType/primitiveAccelerationStructure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgumentTypePrimitiveAccelerationStructure"
        }
      ],
      "role": "symbol",
      "title": "MTLArgumentType.primitiveAccelerationStructure",
      "type": "topic",
      "url": "/documentation/metal/mtlargumenttype/primitiveaccelerationstructure"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgumentType/sampler": {
      "abstract": [
        {
          "text": "The argument is a texture sampler.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sampler"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgumentType/sampler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgumentTypeSampler"
        }
      ],
      "role": "symbol",
      "title": "MTLArgumentType.sampler",
      "type": "topic",
      "url": "/documentation/metal/mtlargumenttype/sampler"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgumentType/texture": {
      "abstract": [
        {
          "text": "The argument is a texture.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "texture"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgumentType/texture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgumentTypeTexture"
        }
      ],
      "role": "symbol",
      "title": "MTLArgumentType.texture",
      "type": "topic",
      "url": "/documentation/metal/mtlargumenttype/texture"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgumentType/threadgroupMemory": {
      "abstract": [
        {
          "text": "The argument is a pointer to threadgroup memory.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "threadgroupMemory"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgumentType/threadgroupMemory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgumentTypeThreadgroupMemory"
        }
      ],
      "role": "symbol",
      "title": "MTLArgumentType.threadgroupMemory",
      "type": "topic",
      "url": "/documentation/metal/mtlargumenttype/threadgroupmemory"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgumentType/visibleFunctionTable": {
      "abstract": [
        {
          "text": "The argument is a visible function table.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visibleFunctionTable"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgumentType/visibleFunctionTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgumentTypeVisibleFunctionTable"
        }
      ],
      "role": "symbol",
      "title": "MTLArgumentType.visibleFunctionTable",
      "type": "topic",
      "url": "/documentation/metal/mtlargumenttype/visiblefunctiontable"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttribute": {
      "abstract": [
        {
          "text": "An object that describes an attribute defined in the stage-in argument for a shader.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAttribute"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttribute"
        }
      ],
      "role": "symbol",
      "title": "MTLAttribute",
      "type": "topic",
      "url": "/documentation/metal/mtlattribute"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedArgument": {
      "abstract": [
        {
          "text": "A convenience type alias for an autoreleased argument instance.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAutoreleasedArgument"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedArgument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAutoreleasedArgument"
        }
      ],
      "role": "symbol",
      "title": "MTLAutoreleasedArgument",
      "type": "topic",
      "url": "/documentation/metal/mtlautoreleasedargument"
    },
    "doc://com.apple.metal/documentation/Metal/MTLVertexAttribute": {
      "abstract": [
        {
          "text": "An object that represents an attribute of a vertex function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLVertexAttribute"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLVertexAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLVertexAttribute"
        }
      ],
      "role": "symbol",
      "title": "MTLVertexAttribute",
      "type": "topic",
      "url": "/documentation/metal/mtlvertexattribute"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Function-Arguments",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLAttribute",
        "doc://com.apple.metal/documentation/Metal/MTLVertexAttribute",
        "doc://com.apple.metal/documentation/Metal/MTLArgument",
        "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedArgument",
        "doc://com.apple.metal/documentation/Metal/MTLArgumentAccess"
      ],
      "title": "Function Arguments"
    }
  ],
  "topicSections": [
    {
      "anchor": "Argument-Types",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLArgumentType/buffer",
        "doc://com.apple.metal/documentation/Metal/MTLArgumentType/threadgroupMemory",
        "doc://com.apple.metal/documentation/Metal/MTLArgumentType/texture",
        "doc://com.apple.metal/documentation/Metal/MTLArgumentType/sampler",
        "doc://com.apple.metal/documentation/Metal/MTLArgumentType/imageblock",
        "doc://com.apple.metal/documentation/Metal/MTLArgumentType/imageblockData",
        "doc://com.apple.metal/documentation/Metal/MTLArgumentType/visibleFunctionTable",
        "doc://com.apple.metal/documentation/Metal/MTLArgumentType/intersectionFunctionTable",
        "doc://com.apple.metal/documentation/Metal/MTLArgumentType/primitiveAccelerationStructure",
        "doc://com.apple.metal/documentation/Metal/MTLArgumentType/instanceAccelerationStructure"
      ],
      "title": "Argument Types"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLArgumentType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.0",
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.0",
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLArgumentType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Argument-Types",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLArgumentType/buffer",
                "doc://com.apple.metal/documentation/Metal/MTLArgumentType/threadgroupMemory",
                "doc://com.apple.metal/documentation/Metal/MTLArgumentType/texture",
                "doc://com.apple.metal/documentation/Metal/MTLArgumentType/sampler",
                "doc://com.apple.metal/documentation/Metal/MTLArgumentType/imageblock",
                "doc://com.apple.metal/documentation/Metal/MTLArgumentType/imageblockData",
                "doc://com.apple.metal/documentation/Metal/MTLArgumentType/visibleFunctionTable",
                "doc://com.apple.metal/documentation/Metal/MTLArgumentType/intersectionFunctionTable",
                "doc://com.apple.metal/documentation/Metal/MTLArgumentType/primitiveAccelerationStructure",
                "doc://com.apple.metal/documentation/Metal/MTLArgumentType/instanceAccelerationStructure"
              ],
              "title": "Argument Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Function-Arguments",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLAttribute",
                "doc://com.apple.metal/documentation/Metal/MTLVertexAttribute",
                "doc://com.apple.metal/documentation/Metal/MTLArgument",
                "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedArgument",
                "doc://com.apple.metal/documentation/Metal/MTLArgumentAccess"
              ],
              "title": "Function Arguments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLArgumentType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1imageblockData/title",
          "value": "MTLArgumentTypeImageblockData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1imageblockData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentTypeImageblockData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1imageblock/title",
          "value": "MTLArgumentTypeImageblock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1imageblock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentTypeImageblock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType/title",
          "value": "MTLArgumentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1primitiveAccelerationStructure/title",
          "value": "MTLArgumentTypePrimitiveAccelerationStructure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1primitiveAccelerationStructure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentTypePrimitiveAccelerationStructure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgument/title",
          "value": "MTLArgument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgument/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1instanceAccelerationStructure/title",
          "value": "MTLArgumentTypeInstanceAccelerationStructure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1instanceAccelerationStructure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentTypeInstanceAccelerationStructure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1sampler/title",
          "value": "MTLArgumentTypeSampler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1sampler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentTypeSampler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttribute/title",
          "value": "MTLAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentAccess/title",
          "value": "MTLArgumentAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentAccess/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1visibleFunctionTable/title",
          "value": "MTLArgumentTypeVisibleFunctionTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1visibleFunctionTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentTypeVisibleFunctionTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexAttribute/title",
          "value": "MTLVertexAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexAttribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAutoreleasedArgument/title",
          "value": "MTLAutoreleasedArgument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAutoreleasedArgument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAutoreleasedArgument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAutoreleasedArgument/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAutoreleasedArgument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1threadgroupMemory/title",
          "value": "MTLArgumentTypeThreadgroupMemory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1threadgroupMemory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentTypeThreadgroupMemory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1intersectionFunctionTable/title",
          "value": "MTLArgumentTypeIntersectionFunctionTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1intersectionFunctionTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentTypeIntersectionFunctionTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1texture/title",
          "value": "MTLArgumentTypeTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1texture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentTypeTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1buffer/title",
          "value": "MTLArgumentTypeBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentType~1buffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentTypeBuffer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlargumenttype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlargumenttype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
