{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLBindingAccess"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLBindingAccess",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLBindingAccess"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLBindingAccess"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTLBindingAccess"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLBindingAccess"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedComputePipelineReflection": {
      "abstract": [
        {
          "text": "A convenience type alias for an autoreleased compute pipeline reflection object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAutoreleasedComputePipelineReflection"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedComputePipelineReflection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAutoreleasedComputePipelineReflection"
        }
      ],
      "role": "symbol",
      "title": "MTLAutoreleasedComputePipelineReflection",
      "type": "topic",
      "url": "/documentation/metal/mtlautoreleasedcomputepipelinereflection"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedRenderPipelineReflection": {
      "abstract": [
        {
          "text": "A convenience type alias for an autoreleased pipeline reflection instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAutoreleasedRenderPipelineReflection"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedRenderPipelineReflection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAutoreleasedRenderPipelineReflection"
        }
      ],
      "role": "symbol",
      "title": "MTLAutoreleasedRenderPipelineReflection",
      "type": "topic",
      "url": "/documentation/metal/mtlautoreleasedrenderpipelinereflection"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBinding": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLBinding"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBinding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBinding"
        }
      ],
      "role": "symbol",
      "title": "MTLBinding",
      "type": "topic",
      "url": "/documentation/metal/mtlbinding"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingAccess": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLBindingAccess"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBindingAccess"
        }
      ],
      "role": "symbol",
      "title": "MTLBindingAccess",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingaccess"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/MTLArgumentAccessReadOnly": {
      "abstract": [
        {
          "text": "The function can only read its argument data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTLArgumentAccessReadOnly"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/MTLArgumentAccessReadOnly",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLArgumentAccessReadOnly",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingaccess/mtlargumentaccessreadonly"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/MTLArgumentAccessReadWrite": {
      "abstract": [
        {
          "text": "The function can either read or write its argument data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTLArgumentAccessReadWrite"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/MTLArgumentAccessReadWrite",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLArgumentAccessReadWrite",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingaccess/mtlargumentaccessreadwrite"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/MTLArgumentAccessWriteOnly": {
      "abstract": [
        {
          "text": "The function can only write its argument data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTLArgumentAccessWriteOnly"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/MTLArgumentAccessWriteOnly",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLArgumentAccessWriteOnly",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingaccess/mtlargumentaccesswriteonly"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingaccess/init(rawvalue:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/readOnly": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readOnly"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/readOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBindingAccessReadOnly"
        }
      ],
      "role": "symbol",
      "title": "MTLBindingAccess.readOnly",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingaccess/readonly"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/readWrite": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readWrite"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/readWrite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBindingAccessReadWrite"
        }
      ],
      "role": "symbol",
      "title": "MTLBindingAccess.readWrite",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingaccess/readwrite"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/writeOnly": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeOnly"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/writeOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBindingAccessWriteOnly"
        }
      ],
      "role": "symbol",
      "title": "MTLBindingAccess.writeOnly",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingaccess/writeonly"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLBindingType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBindingType"
        }
      ],
      "role": "symbol",
      "title": "MTLBindingType",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingtype"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBufferBinding": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLBufferBinding"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBufferBinding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBufferBinding"
        }
      ],
      "role": "symbol",
      "title": "MTLBufferBinding",
      "type": "topic",
      "url": "/documentation/metal/mtlbufferbinding"
    },
    "doc://com.apple.metal/documentation/Metal/MTLComputePipelineReflection": {
      "abstract": [
        {
          "text": "Information about the arguments of a compute function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLComputePipelineReflection"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLComputePipelineReflection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLComputePipelineReflection"
        }
      ],
      "role": "symbol",
      "title": "MTLComputePipelineReflection",
      "type": "topic",
      "url": "/documentation/metal/mtlcomputepipelinereflection"
    },
    "doc://com.apple.metal/documentation/Metal/MTLObjectPayloadBinding": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLObjectPayloadBinding"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLObjectPayloadBinding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLObjectPayloadBinding"
        }
      ],
      "role": "symbol",
      "title": "MTLObjectPayloadBinding",
      "type": "topic",
      "url": "/documentation/metal/mtlobjectpayloadbinding"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineReflection": {
      "abstract": [
        {
          "text": "Information about the arguments of a graphics function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLRenderPipelineReflection"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineReflection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLRenderPipelineReflection"
        }
      ],
      "role": "symbol",
      "title": "MTLRenderPipelineReflection",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpipelinereflection"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureBinding": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLTextureBinding"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureBinding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTextureBinding"
        }
      ],
      "role": "symbol",
      "title": "MTLTextureBinding",
      "type": "topic",
      "url": "/documentation/metal/mtltexturebinding"
    },
    "doc://com.apple.metal/documentation/Metal/MTLThreadgroupBinding": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLThreadgroupBinding"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLThreadgroupBinding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLThreadgroupBinding"
        }
      ],
      "role": "symbol",
      "title": "MTLThreadgroupBinding",
      "type": "topic",
      "url": "/documentation/metal/mtlthreadgroupbinding"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Introspection-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLComputePipelineReflection",
        "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedComputePipelineReflection",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineReflection",
        "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedRenderPipelineReflection",
        "doc://com.apple.metal/documentation/Metal/MTLBindingType",
        "doc://com.apple.metal/documentation/Metal/MTLBinding",
        "doc://com.apple.metal/documentation/Metal/MTLBufferBinding",
        "doc://com.apple.metal/documentation/Metal/MTLTextureBinding",
        "doc://com.apple.metal/documentation/Metal/MTLThreadgroupBinding",
        "doc://com.apple.metal/documentation/Metal/MTLObjectPayloadBinding"
      ],
      "title": "Introspection Data"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/readOnly",
        "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/readWrite",
        "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/writeOnly"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLBindingAccess"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/MTLArgumentAccessReadOnly",
                "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/MTLArgumentAccessReadWrite",
                "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/MTLArgumentAccessWriteOnly",
                "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/readOnly",
                "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/readWrite",
                "doc://com.apple.metal/documentation/Metal/MTLBindingAccess/writeOnly"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Introspection-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLComputePipelineReflection",
                "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedComputePipelineReflection",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineReflection",
                "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedRenderPipelineReflection",
                "doc://com.apple.metal/documentation/Metal/MTLBindingType",
                "doc://com.apple.metal/documentation/Metal/MTLBinding",
                "doc://com.apple.metal/documentation/Metal/MTLBufferBinding",
                "doc://com.apple.metal/documentation/Metal/MTLTextureBinding",
                "doc://com.apple.metal/documentation/Metal/MTLThreadgroupBinding",
                "doc://com.apple.metal/documentation/Metal/MTLObjectPayloadBinding"
              ],
              "title": "Introspection Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLBindingAccess"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureBinding/title",
          "value": "MTLTextureBinding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureBinding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureBinding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBufferBinding/title",
          "value": "MTLBufferBinding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBufferBinding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBufferBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBufferBinding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBufferBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingAccess/title",
          "value": "MTLBindingAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingAccess/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingAccess~1writeOnly/title",
          "value": "MTLBindingAccessWriteOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingAccess~1writeOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingAccessWriteOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingAccess~1readWrite/title",
          "value": "MTLBindingAccessReadWrite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingAccess~1readWrite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingAccessReadWrite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComputePipelineReflection/title",
          "value": "MTLComputePipelineReflection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComputePipelineReflection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLComputePipelineReflection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComputePipelineReflection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLComputePipelineReflection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineReflection/title",
          "value": "MTLRenderPipelineReflection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineReflection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPipelineReflection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineReflection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPipelineReflection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinding/title",
          "value": "MTLBinding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAutoreleasedComputePipelineReflection/title",
          "value": "MTLAutoreleasedComputePipelineReflection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAutoreleasedComputePipelineReflection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAutoreleasedComputePipelineReflection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAutoreleasedComputePipelineReflection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAutoreleasedComputePipelineReflection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAutoreleasedRenderPipelineReflection/title",
          "value": "MTLAutoreleasedRenderPipelineReflection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAutoreleasedRenderPipelineReflection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAutoreleasedRenderPipelineReflection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAutoreleasedRenderPipelineReflection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAutoreleasedRenderPipelineReflection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType/title",
          "value": "MTLBindingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLObjectPayloadBinding/title",
          "value": "MTLObjectPayloadBinding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLObjectPayloadBinding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLObjectPayloadBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLObjectPayloadBinding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLObjectPayloadBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLThreadgroupBinding/title",
          "value": "MTLThreadgroupBinding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLThreadgroupBinding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLThreadgroupBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLThreadgroupBinding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLThreadgroupBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingAccess~1readOnly/title",
          "value": "MTLBindingAccessReadOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingAccess~1readOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingAccessReadOnly"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlbindingaccess"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlbindingaccess"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
