{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLBindingType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLBindingType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLBindingType"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLBindingType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTLBindingType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLBindingType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedComputePipelineReflection": {
      "abstract": [
        {
          "text": "A convenience type alias for an autoreleased compute pipeline reflection object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAutoreleasedComputePipelineReflection"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedComputePipelineReflection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAutoreleasedComputePipelineReflection"
        }
      ],
      "role": "symbol",
      "title": "MTLAutoreleasedComputePipelineReflection",
      "type": "topic",
      "url": "/documentation/metal/mtlautoreleasedcomputepipelinereflection"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedRenderPipelineReflection": {
      "abstract": [
        {
          "text": "A convenience type alias for an autoreleased pipeline reflection instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAutoreleasedRenderPipelineReflection"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedRenderPipelineReflection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAutoreleasedRenderPipelineReflection"
        }
      ],
      "role": "symbol",
      "title": "MTLAutoreleasedRenderPipelineReflection",
      "type": "topic",
      "url": "/documentation/metal/mtlautoreleasedrenderpipelinereflection"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBinding": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLBinding"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBinding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBinding"
        }
      ],
      "role": "symbol",
      "title": "MTLBinding",
      "type": "topic",
      "url": "/documentation/metal/mtlbinding"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingAccess": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLBindingAccess"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBindingAccess"
        }
      ],
      "role": "symbol",
      "title": "MTLBindingAccess",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingaccess"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLBindingType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBindingType"
        }
      ],
      "role": "symbol",
      "title": "MTLBindingType",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingtype"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingType/buffer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buffer"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingType/buffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBindingTypeBuffer"
        }
      ],
      "role": "symbol",
      "title": "MTLBindingType.buffer",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingtype/buffer"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingType/imageblock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageblock"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingType/imageblock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBindingTypeImageblock"
        }
      ],
      "role": "symbol",
      "title": "MTLBindingType.imageblock",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingtype/imageblock"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingType/imageblockData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageblockData"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingType/imageblockData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBindingTypeImageblockData"
        }
      ],
      "role": "symbol",
      "title": "MTLBindingType.imageblockData",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingtype/imageblockdata"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingtype/init(rawvalue:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingType/instanceAccelerationStructure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instanceAccelerationStructure"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingType/instanceAccelerationStructure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBindingTypeInstanceAccelerationStructure"
        }
      ],
      "role": "symbol",
      "title": "MTLBindingType.instanceAccelerationStructure",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingtype/instanceaccelerationstructure"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingType/intersectionFunctionTable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "intersectionFunctionTable"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingType/intersectionFunctionTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBindingTypeIntersectionFunctionTable"
        }
      ],
      "role": "symbol",
      "title": "MTLBindingType.intersectionFunctionTable",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingtype/intersectionfunctiontable"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingType/objectPayload": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "objectPayload"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingType/objectPayload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBindingTypeObjectPayload"
        }
      ],
      "role": "symbol",
      "title": "MTLBindingType.objectPayload",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingtype/objectpayload"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingType/primitiveAccelerationStructure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primitiveAccelerationStructure"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingType/primitiveAccelerationStructure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBindingTypePrimitiveAccelerationStructure"
        }
      ],
      "role": "symbol",
      "title": "MTLBindingType.primitiveAccelerationStructure",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingtype/primitiveaccelerationstructure"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingType/sampler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sampler"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingType/sampler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBindingTypeSampler"
        }
      ],
      "role": "symbol",
      "title": "MTLBindingType.sampler",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingtype/sampler"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingType/texture": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "texture"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingType/texture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBindingTypeTexture"
        }
      ],
      "role": "symbol",
      "title": "MTLBindingType.texture",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingtype/texture"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingType/threadgroupMemory": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "threadgroupMemory"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingType/threadgroupMemory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBindingTypeThreadgroupMemory"
        }
      ],
      "role": "symbol",
      "title": "MTLBindingType.threadgroupMemory",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingtype/threadgroupmemory"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingType/visibleFunctionTable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visibleFunctionTable"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingType/visibleFunctionTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBindingTypeVisibleFunctionTable"
        }
      ],
      "role": "symbol",
      "title": "MTLBindingType.visibleFunctionTable",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingtype/visiblefunctiontable"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBufferBinding": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLBufferBinding"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBufferBinding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBufferBinding"
        }
      ],
      "role": "symbol",
      "title": "MTLBufferBinding",
      "type": "topic",
      "url": "/documentation/metal/mtlbufferbinding"
    },
    "doc://com.apple.metal/documentation/Metal/MTLComputePipelineReflection": {
      "abstract": [
        {
          "text": "Information about the arguments of a compute function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLComputePipelineReflection"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLComputePipelineReflection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLComputePipelineReflection"
        }
      ],
      "role": "symbol",
      "title": "MTLComputePipelineReflection",
      "type": "topic",
      "url": "/documentation/metal/mtlcomputepipelinereflection"
    },
    "doc://com.apple.metal/documentation/Metal/MTLObjectPayloadBinding": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLObjectPayloadBinding"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLObjectPayloadBinding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLObjectPayloadBinding"
        }
      ],
      "role": "symbol",
      "title": "MTLObjectPayloadBinding",
      "type": "topic",
      "url": "/documentation/metal/mtlobjectpayloadbinding"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineReflection": {
      "abstract": [
        {
          "text": "Information about the arguments of a graphics function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLRenderPipelineReflection"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineReflection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLRenderPipelineReflection"
        }
      ],
      "role": "symbol",
      "title": "MTLRenderPipelineReflection",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpipelinereflection"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureBinding": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLTextureBinding"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureBinding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTextureBinding"
        }
      ],
      "role": "symbol",
      "title": "MTLTextureBinding",
      "type": "topic",
      "url": "/documentation/metal/mtltexturebinding"
    },
    "doc://com.apple.metal/documentation/Metal/MTLThreadgroupBinding": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLThreadgroupBinding"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLThreadgroupBinding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLThreadgroupBinding"
        }
      ],
      "role": "symbol",
      "title": "MTLThreadgroupBinding",
      "type": "topic",
      "url": "/documentation/metal/mtlthreadgroupbinding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Introspection-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLComputePipelineReflection",
        "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedComputePipelineReflection",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineReflection",
        "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedRenderPipelineReflection",
        "doc://com.apple.metal/documentation/Metal/MTLBinding",
        "doc://com.apple.metal/documentation/Metal/MTLBindingAccess",
        "doc://com.apple.metal/documentation/Metal/MTLBufferBinding",
        "doc://com.apple.metal/documentation/Metal/MTLTextureBinding",
        "doc://com.apple.metal/documentation/Metal/MTLThreadgroupBinding",
        "doc://com.apple.metal/documentation/Metal/MTLObjectPayloadBinding"
      ],
      "title": "Introspection Data"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLBindingType/buffer",
        "doc://com.apple.metal/documentation/Metal/MTLBindingType/imageblock",
        "doc://com.apple.metal/documentation/Metal/MTLBindingType/imageblockData",
        "doc://com.apple.metal/documentation/Metal/MTLBindingType/instanceAccelerationStructure",
        "doc://com.apple.metal/documentation/Metal/MTLBindingType/intersectionFunctionTable",
        "doc://com.apple.metal/documentation/Metal/MTLBindingType/objectPayload",
        "doc://com.apple.metal/documentation/Metal/MTLBindingType/primitiveAccelerationStructure",
        "doc://com.apple.metal/documentation/Metal/MTLBindingType/sampler",
        "doc://com.apple.metal/documentation/Metal/MTLBindingType/texture",
        "doc://com.apple.metal/documentation/Metal/MTLBindingType/threadgroupMemory",
        "doc://com.apple.metal/documentation/Metal/MTLBindingType/visibleFunctionTable"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLBindingType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLBindingType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLBindingType/buffer",
                "doc://com.apple.metal/documentation/Metal/MTLBindingType/imageblock",
                "doc://com.apple.metal/documentation/Metal/MTLBindingType/imageblockData",
                "doc://com.apple.metal/documentation/Metal/MTLBindingType/instanceAccelerationStructure",
                "doc://com.apple.metal/documentation/Metal/MTLBindingType/intersectionFunctionTable",
                "doc://com.apple.metal/documentation/Metal/MTLBindingType/objectPayload",
                "doc://com.apple.metal/documentation/Metal/MTLBindingType/primitiveAccelerationStructure",
                "doc://com.apple.metal/documentation/Metal/MTLBindingType/sampler",
                "doc://com.apple.metal/documentation/Metal/MTLBindingType/texture",
                "doc://com.apple.metal/documentation/Metal/MTLBindingType/threadgroupMemory",
                "doc://com.apple.metal/documentation/Metal/MTLBindingType/visibleFunctionTable"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Introspection-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLComputePipelineReflection",
                "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedComputePipelineReflection",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineReflection",
                "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedRenderPipelineReflection",
                "doc://com.apple.metal/documentation/Metal/MTLBinding",
                "doc://com.apple.metal/documentation/Metal/MTLBindingAccess",
                "doc://com.apple.metal/documentation/Metal/MTLBufferBinding",
                "doc://com.apple.metal/documentation/Metal/MTLTextureBinding",
                "doc://com.apple.metal/documentation/Metal/MTLThreadgroupBinding",
                "doc://com.apple.metal/documentation/Metal/MTLObjectPayloadBinding"
              ],
              "title": "Introspection Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLBindingType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType~1imageblockData/title",
          "value": "MTLBindingTypeImageblockData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType~1imageblockData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingTypeImageblockData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType/title",
          "value": "MTLBindingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType~1imageblock/title",
          "value": "MTLBindingTypeImageblock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType~1imageblock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingTypeImageblock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineReflection/title",
          "value": "MTLRenderPipelineReflection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineReflection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPipelineReflection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineReflection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPipelineReflection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType~1threadgroupMemory/title",
          "value": "MTLBindingTypeThreadgroupMemory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType~1threadgroupMemory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingTypeThreadgroupMemory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLObjectPayloadBinding/title",
          "value": "MTLObjectPayloadBinding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLObjectPayloadBinding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLObjectPayloadBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLObjectPayloadBinding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLObjectPayloadBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType~1buffer/title",
          "value": "MTLBindingTypeBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType~1buffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingTypeBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType~1texture/title",
          "value": "MTLBindingTypeTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType~1texture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingTypeTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType~1sampler/title",
          "value": "MTLBindingTypeSampler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType~1sampler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingTypeSampler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAutoreleasedRenderPipelineReflection/title",
          "value": "MTLAutoreleasedRenderPipelineReflection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAutoreleasedRenderPipelineReflection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAutoreleasedRenderPipelineReflection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAutoreleasedRenderPipelineReflection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAutoreleasedRenderPipelineReflection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType~1intersectionFunctionTable/title",
          "value": "MTLBindingTypeIntersectionFunctionTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType~1intersectionFunctionTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingTypeIntersectionFunctionTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType~1instanceAccelerationStructure/title",
          "value": "MTLBindingTypeInstanceAccelerationStructure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType~1instanceAccelerationStructure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingTypeInstanceAccelerationStructure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType~1visibleFunctionTable/title",
          "value": "MTLBindingTypeVisibleFunctionTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType~1visibleFunctionTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingTypeVisibleFunctionTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBufferBinding/title",
          "value": "MTLBufferBinding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBufferBinding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBufferBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBufferBinding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBufferBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType~1primitiveAccelerationStructure/title",
          "value": "MTLBindingTypePrimitiveAccelerationStructure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType~1primitiveAccelerationStructure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingTypePrimitiveAccelerationStructure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinding/title",
          "value": "MTLBinding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAutoreleasedComputePipelineReflection/title",
          "value": "MTLAutoreleasedComputePipelineReflection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAutoreleasedComputePipelineReflection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAutoreleasedComputePipelineReflection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAutoreleasedComputePipelineReflection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAutoreleasedComputePipelineReflection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType~1objectPayload/title",
          "value": "MTLBindingTypeObjectPayload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType~1objectPayload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingTypeObjectPayload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureBinding/title",
          "value": "MTLTextureBinding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureBinding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureBinding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComputePipelineReflection/title",
          "value": "MTLComputePipelineReflection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComputePipelineReflection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLComputePipelineReflection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComputePipelineReflection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLComputePipelineReflection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLThreadgroupBinding/title",
          "value": "MTLThreadgroupBinding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLThreadgroupBinding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLThreadgroupBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLThreadgroupBinding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLThreadgroupBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingAccess/title",
          "value": "MTLBindingAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingAccess/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingAccess"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlbindingtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlbindingtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
