{
  "abstract": [
    {
      "text": "The source and destination blend factors are often needed to complete specification of a blend operation. In most cases, the blend factor for both RGB values (",
      "type": "text"
    },
    {
      "inlineContent": [
        {
          "text": "F(rgb)",
          "type": "text"
        }
      ],
      "type": "emphasis"
    },
    {
      "text": ") and alpha values (",
      "type": "text"
    },
    {
      "inlineContent": [
        {
          "text": "F(a)",
          "type": "text"
        }
      ],
      "type": "emphasis"
    },
    {
      "text": ") are similar to one another, but in some cases, such as ",
      "type": "text"
    },
    {
      "code": "MTLBlendFactorSourceAlphaSaturated",
      "type": "codeVoice"
    },
    {
      "text": ", the blend factor is slightly different. Four blend factors (",
      "type": "text"
    },
    {
      "code": "MTLBlendFactorBlendColor",
      "type": "codeVoice"
    },
    {
      "text": ", ",
      "type": "text"
    },
    {
      "code": "MTLBlendFactorOneMinusBlendColor",
      "type": "codeVoice"
    },
    {
      "text": ", ",
      "type": "text"
    },
    {
      "code": "MTLBlendFactorBlendAlpha",
      "type": "codeVoice"
    },
    {
      "text": ", and ",
      "type": "text"
    },
    {
      "code": "MTLBlendFactorOneMinusBlendAlpha",
      "type": "codeVoice"
    },
    {
      "text": ") refer to a constant blend color value that is set by the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setBlendColor(red:green:blue:alpha:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " method of ",
      "type": "text"
    },
    {
      "code": "MTLRenderCommandEncoder",
      "type": "codeVoice"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLBlendFactor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLBlendFactor"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLBlendFactor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTLBlendFactor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLBlendFactor"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor": {
      "abstract": [
        {
          "text": "The source and destination blend factors are often needed to complete specification of a blend operation. In most cases, the blend factor for both RGB values (",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "F(rgb)",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ") and alpha values (",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "F(a)",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ") are similar to one another, but in some cases, such as ",
          "type": "text"
        },
        {
          "code": "MTLBlendFactorSourceAlphaSaturated",
          "type": "codeVoice"
        },
        {
          "text": ", the blend factor is slightly different. Four blend factors (",
          "type": "text"
        },
        {
          "code": "MTLBlendFactorBlendColor",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "MTLBlendFactorOneMinusBlendColor",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "MTLBlendFactorBlendAlpha",
          "type": "codeVoice"
        },
        {
          "text": ", and ",
          "type": "text"
        },
        {
          "code": "MTLBlendFactorOneMinusBlendAlpha",
          "type": "codeVoice"
        },
        {
          "text": ") refer to a constant blend color value that is set by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setBlendColor(red:green:blue:alpha:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method of ",
          "type": "text"
        },
        {
          "code": "MTLRenderCommandEncoder",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLBlendFactor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactor"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/blendAlpha": {
      "abstract": [
        {
          "text": "Blend factor of alpha value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "blendAlpha"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/blendAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorBlendAlpha"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.blendAlpha",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/blendalpha"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/blendColor": {
      "abstract": [
        {
          "text": "Blend factor of RGB values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "blendColor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/blendColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorBlendColor"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.blendColor",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/blendcolor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/destinationAlpha": {
      "abstract": [
        {
          "text": "Blend factor of destination alpha.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "destinationAlpha"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/destinationAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorDestinationAlpha"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.destinationAlpha",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/destinationalpha"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/destinationColor": {
      "abstract": [
        {
          "text": "Blend factor of destination values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "destinationColor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/destinationColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorDestinationColor"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.destinationColor",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/destinationcolor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/init(rawvalue:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/one": {
      "abstract": [
        {
          "text": "Blend factor of one.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "one"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/one",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorOne"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.one",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/one"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusBlendAlpha": {
      "abstract": [
        {
          "text": "Blend factor of one minus alpha value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneMinusBlendAlpha"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusBlendAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorOneMinusBlendAlpha"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.oneMinusBlendAlpha",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/oneminusblendalpha"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusBlendColor": {
      "abstract": [
        {
          "text": "Blend factor of one minus RGB values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneMinusBlendColor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusBlendColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorOneMinusBlendColor"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.oneMinusBlendColor",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/oneminusblendcolor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusDestinationAlpha": {
      "abstract": [
        {
          "text": "Blend factor of one minus destination alpha.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneMinusDestinationAlpha"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusDestinationAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorOneMinusDestinationAlpha"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.oneMinusDestinationAlpha",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/oneminusdestinationalpha"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusDestinationColor": {
      "abstract": [
        {
          "text": "Blend factor of one minus destination values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneMinusDestinationColor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusDestinationColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorOneMinusDestinationColor"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.oneMinusDestinationColor",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/oneminusdestinationcolor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusSource1Alpha": {
      "abstract": [
        {
          "text": "Blend factor of one minus source alpha. This option supports dual-source blending and reads from the second color output of the fragment function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneMinusSource1Alpha"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusSource1Alpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorOneMinusSource1Alpha"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.oneMinusSource1Alpha",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/oneminussource1alpha"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusSource1Color": {
      "abstract": [
        {
          "text": "Blend factor of one minus source values. This option supports dual-source blending and reads from the second color output of the fragment function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneMinusSource1Color"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusSource1Color",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorOneMinusSource1Color"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.oneMinusSource1Color",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/oneminussource1color"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusSourceAlpha": {
      "abstract": [
        {
          "text": "Blend factor of one minus source alpha.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneMinusSourceAlpha"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusSourceAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorOneMinusSourceAlpha"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.oneMinusSourceAlpha",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/oneminussourcealpha"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusSourceColor": {
      "abstract": [
        {
          "text": "Blend factor of one minus source values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneMinusSourceColor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusSourceColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorOneMinusSourceColor"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.oneMinusSourceColor",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/oneminussourcecolor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/source1Alpha": {
      "abstract": [
        {
          "text": "Blend factor of source alpha. This option supports dual-source blending and reads from the second color output of the fragment function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "source1Alpha"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/source1Alpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorSource1Alpha"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.source1Alpha",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/source1alpha"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/source1Color": {
      "abstract": [
        {
          "text": "Blend factor of source values. This option supports dual-source blending and reads from the second color output of the fragment function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "source1Color"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/source1Color",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorSource1Color"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.source1Color",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/source1color"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/sourceAlpha": {
      "abstract": [
        {
          "text": "Blend factor of source alpha.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceAlpha"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/sourceAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorSourceAlpha"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.sourceAlpha",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/sourcealpha"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/sourceAlphaSaturated": {
      "abstract": [
        {
          "text": "Blend factor of the minimum of either source alpha or one minus destination alpha.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceAlphaSaturated"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/sourceAlphaSaturated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorSourceAlphaSaturated"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.sourceAlphaSaturated",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/sourcealphasaturated"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/sourceColor": {
      "abstract": [
        {
          "text": "Blend factor of source values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceColor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/sourceColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorSourceColor"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.sourceColor",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/sourcecolor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/zero": {
      "abstract": [
        {
          "text": "Blend factor of zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zero"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/zero",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorZero"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.zero",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/zero"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendOperation": {
      "abstract": [
        {
          "text": "For every pixel, ",
          "type": "text"
        },
        {
          "code": "MTLBlendOperation",
          "type": "codeVoice"
        },
        {
          "text": " determines how to combine and weight the source fragment values with the destination values. Some blend operations multiply the source values by a source blend factor (SBF), multiply the destination values by a destination blend factor (DBF), and then combine the results using addition or subtraction. Other blend operations use either a minimum or maximum function to determine the result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLBlendOperation"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendOperation"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendOperation",
      "type": "topic",
      "url": "/documentation/metal/mtlblendoperation"
    },
    "doc://com.apple.metal/documentation/Metal/MTLColorWriteMask": {
      "abstract": [
        {
          "text": "Values used to specify a mask to permit or restrict writing to color channels of a color value. The values ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.metal/documentation/Metal/MTLColorWriteMask/red",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.metal/documentation/Metal/MTLColorWriteMask/green",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.metal/documentation/Metal/MTLColorWriteMask/blue",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.metal/documentation/Metal/MTLColorWriteMask/alpha",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " select one color channel each, and they can be bitwise combined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLColorWriteMask"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLColorWriteMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLColorWriteMask"
        }
      ],
      "role": "symbol",
      "title": "MTLColorWriteMask",
      "type": "topic",
      "url": "/documentation/metal/mtlcolorwritemask"
    },
    "doc://com.apple.metal/documentation/Metal/MTLColorWriteMask/alpha": {
      "abstract": [
        {
          "text": "The alpha color channel is enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLColorWriteMask",
          "text": "MTLColorWriteMask"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLColorWriteMask/alpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLColorWriteMaskAlpha"
        }
      ],
      "role": "symbol",
      "title": "alpha",
      "type": "topic",
      "url": "/documentation/metal/mtlcolorwritemask/alpha"
    },
    "doc://com.apple.metal/documentation/Metal/MTLColorWriteMask/blue": {
      "abstract": [
        {
          "text": "The blue color channel is enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "blue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLColorWriteMask",
          "text": "MTLColorWriteMask"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLColorWriteMask/blue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLColorWriteMaskBlue"
        }
      ],
      "role": "symbol",
      "title": "blue",
      "type": "topic",
      "url": "/documentation/metal/mtlcolorwritemask/blue"
    },
    "doc://com.apple.metal/documentation/Metal/MTLColorWriteMask/green": {
      "abstract": [
        {
          "text": "The green color channel is enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "green"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLColorWriteMask",
          "text": "MTLColorWriteMask"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLColorWriteMask/green",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLColorWriteMaskGreen"
        }
      ],
      "role": "symbol",
      "title": "green",
      "type": "topic",
      "url": "/documentation/metal/mtlcolorwritemask/green"
    },
    "doc://com.apple.metal/documentation/Metal/MTLColorWriteMask/red": {
      "abstract": [
        {
          "text": "The red color channel is enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "red"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLColorWriteMask",
          "text": "MTLColorWriteMask"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLColorWriteMask/red",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLColorWriteMaskRed"
        }
      ],
      "role": "symbol",
      "title": "red",
      "type": "topic",
      "url": "/documentation/metal/mtlcolorwritemask/red"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setBlendColor(red:green:blue:alpha:)": {
      "abstract": [
        {
          "text": "Configures each pixel component value, including alpha, for the render pipeline’s constant blend color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setBlendColor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "red"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "green"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "blue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "alpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setBlendColor(red:green:blue:alpha:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setBlendColorRed:green:blue:alpha:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setBlendColor(red:green:blue:alpha:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setblendcolor(red:green:blue:alpha:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLBlendOperation",
        "doc://com.apple.metal/documentation/Metal/MTLColorWriteMask"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/zero",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/one",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/sourceColor",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusSourceColor",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/sourceAlpha",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusSourceAlpha",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/destinationColor",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusDestinationColor",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/destinationAlpha",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusDestinationAlpha",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/sourceAlphaSaturated",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/blendColor",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusBlendColor",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/blendAlpha",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusBlendAlpha",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/source1Color",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusSource1Color",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/source1Alpha",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusSource1Alpha"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLBlendFactor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/zero",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/one",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/sourceColor",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusSourceColor",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/sourceAlpha",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusSourceAlpha",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/destinationColor",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusDestinationColor",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/destinationAlpha",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusDestinationAlpha",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/sourceAlphaSaturated",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/blendColor",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusBlendColor",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/blendAlpha",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusBlendAlpha",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/source1Color",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusSource1Color",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/source1Alpha",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusSource1Alpha"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLBlendOperation",
                "doc://com.apple.metal/documentation/Metal/MTLColorWriteMask"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLBlendFactor"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setBlendColor(red:green:blue:alpha:)/title",
          "value": "setBlendColorRed:green:blue:alpha:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setBlendColor(red:green:blue:alpha:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setBlendColorRed:green:blue:alpha:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1sourceColor/title",
          "value": "MTLBlendFactorSourceColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1sourceColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorSourceColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1sourceAlpha/title",
          "value": "MTLBlendFactorSourceAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1sourceAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorSourceAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLColorWriteMask/title",
          "value": "MTLColorWriteMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLColorWriteMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLColorWriteMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLColorWriteMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLColorWriteMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1destinationColor/title",
          "value": "MTLBlendFactorDestinationColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1destinationColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorDestinationColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1oneMinusBlendAlpha/title",
          "value": "MTLBlendFactorOneMinusBlendAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1oneMinusBlendAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorOneMinusBlendAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1blendColor/title",
          "value": "MTLBlendFactorBlendColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1blendColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorBlendColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1one/title",
          "value": "MTLBlendFactorOne"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1one/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorOne"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1source1Color/title",
          "value": "MTLBlendFactorSource1Color"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1source1Color/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorSource1Color"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1oneMinusDestinationColor/title",
          "value": "MTLBlendFactorOneMinusDestinationColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1oneMinusDestinationColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorOneMinusDestinationColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1oneMinusBlendColor/title",
          "value": "MTLBlendFactorOneMinusBlendColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1oneMinusBlendColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorOneMinusBlendColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendOperation/title",
          "value": "MTLBlendOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1sourceAlphaSaturated/title",
          "value": "MTLBlendFactorSourceAlphaSaturated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1sourceAlphaSaturated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorSourceAlphaSaturated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor/title",
          "value": "MTLBlendFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1oneMinusSourceAlpha/title",
          "value": "MTLBlendFactorOneMinusSourceAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1oneMinusSourceAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorOneMinusSourceAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1oneMinusSourceColor/title",
          "value": "MTLBlendFactorOneMinusSourceColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1oneMinusSourceColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorOneMinusSourceColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1oneMinusSource1Color/title",
          "value": "MTLBlendFactorOneMinusSource1Color"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1oneMinusSource1Color/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorOneMinusSource1Color"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLColorWriteMask~1blue/title",
          "value": "MTLColorWriteMaskBlue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLColorWriteMask~1blue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLColorWriteMaskBlue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1zero/title",
          "value": "MTLBlendFactorZero"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1zero/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorZero"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1oneMinusDestinationAlpha/title",
          "value": "MTLBlendFactorOneMinusDestinationAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1oneMinusDestinationAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorOneMinusDestinationAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1blendAlpha/title",
          "value": "MTLBlendFactorBlendAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1blendAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorBlendAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1source1Alpha/title",
          "value": "MTLBlendFactorSource1Alpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1source1Alpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorSource1Alpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1oneMinusSource1Alpha/title",
          "value": "MTLBlendFactorOneMinusSource1Alpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1oneMinusSource1Alpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorOneMinusSource1Alpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLColorWriteMask~1alpha/title",
          "value": "MTLColorWriteMaskAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLColorWriteMask~1alpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLColorWriteMaskAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1destinationAlpha/title",
          "value": "MTLBlendFactorDestinationAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1destinationAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorDestinationAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLColorWriteMask~1green/title",
          "value": "MTLColorWriteMaskGreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLColorWriteMask~1green/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLColorWriteMaskGreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLColorWriteMask~1red/title",
          "value": "MTLColorWriteMaskRed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLColorWriteMask~1red/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLColorWriteMaskRed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlblendfactor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlblendfactor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
