{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLComponentTransform"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@MTLComponentTransform",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLComponentTransform"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLComponentTransform"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "MTLComponentTransform"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLComponentTransform"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct": {
      "abstract": [
        {
          "text": "An error that occurred when creating a binary shader archive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLBinaryArchiveError"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBinaryArchiveError"
        }
      ],
      "role": "symbol",
      "title": "MTLBinaryArchiveError",
      "type": "topic",
      "url": "/documentation/metal/mtlbinaryarchiveerror-swift.struct"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct": {
      "abstract": [
        {
          "text": "The command buffer error codes that indicate why the GPU doesn’t finish executing a command buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCommandBufferError"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferError"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct"
    },
    "doc://com.apple.metal/documentation/Metal/MTLComponentTransform": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLComponentTransform"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLComponentTransform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLComponentTransform"
        }
      ],
      "role": "symbol",
      "title": "MTLComponentTransform",
      "type": "topic",
      "url": "/documentation/metal/mtlcomponenttransform"
    },
    "doc://com.apple.metal/documentation/Metal/MTLComponentTransform/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLComponentTransform/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/metal/mtlcomponenttransform/init()"
    },
    "doc://com.apple.metal/documentation/Metal/MTLComponentTransform/init(scale:shear:pivot:rotation:translation:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "scale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "MTLPackedFloat3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "MTLPackedFloat3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "pivot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "MTLPackedFloat3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rotation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MTLPackedFloatQuaternion",
          "text": "MTLPackedFloatQuaternion"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "translation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "MTLPackedFloat3"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLComponentTransform/init(scale:shear:pivot:rotation:translation:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(scale:shear:pivot:rotation:translation:)",
      "type": "topic",
      "url": "/documentation/metal/mtlcomponenttransform/init(scale:shear:pivot:rotation:translation:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLComponentTransform/pivot": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pivot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "MTLPackedFloat3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLComponentTransform/pivot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pivot"
        }
      ],
      "role": "symbol",
      "title": "pivot",
      "type": "topic",
      "url": "/documentation/metal/mtlcomponenttransform/pivot"
    },
    "doc://com.apple.metal/documentation/Metal/MTLComponentTransform/rotation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rotation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MTLPackedFloatQuaternion",
          "text": "MTLPackedFloatQuaternion"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLComponentTransform/rotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rotation"
        }
      ],
      "role": "symbol",
      "title": "rotation",
      "type": "topic",
      "url": "/documentation/metal/mtlcomponenttransform/rotation"
    },
    "doc://com.apple.metal/documentation/Metal/MTLComponentTransform/scale": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "MTLPackedFloat3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLComponentTransform/scale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scale"
        }
      ],
      "role": "symbol",
      "title": "scale",
      "type": "topic",
      "url": "/documentation/metal/mtlcomponenttransform/scale"
    },
    "doc://com.apple.metal/documentation/Metal/MTLComponentTransform/shear": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "MTLPackedFloat3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLComponentTransform/shear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shear"
        }
      ],
      "role": "symbol",
      "title": "shear",
      "type": "topic",
      "url": "/documentation/metal/mtlcomponenttransform/shear"
    },
    "doc://com.apple.metal/documentation/Metal/MTLComponentTransform/translation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "translation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "MTLPackedFloat3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLComponentTransform/translation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "translation"
        }
      ],
      "role": "symbol",
      "title": "translation",
      "type": "topic",
      "url": "/documentation/metal/mtlcomponenttransform/translation"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterSampleBufferError-swift.struct": {
      "abstract": [
        {
          "text": "The error codes that indicate why a GPU driver can’t create a counter sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCounterSampleBufferError"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterSampleBufferError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCounterSampleBufferError"
        }
      ],
      "role": "symbol",
      "title": "MTLCounterSampleBufferError",
      "type": "topic",
      "url": "/documentation/metal/mtlcountersamplebuffererror-swift.struct"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct": {
      "abstract": [
        {
          "text": "Errors when compiling dynamic libraries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDynamicLibraryError"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDynamicLibraryError"
        }
      ],
      "role": "symbol",
      "title": "MTLDynamicLibraryError",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOError-swift.struct": {
      "abstract": [
        {
          "text": "The categories of errors for creating an input/output file handle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIOError"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOError"
        }
      ],
      "role": "symbol",
      "title": "MTLIOError",
      "type": "topic",
      "url": "/documentation/metal/mtlioerror-swift.struct"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPackedFloatQuaternion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLPackedFloatQuaternion"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPackedFloatQuaternion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPackedFloatQuaternion"
        }
      ],
      "role": "symbol",
      "title": "MTLPackedFloatQuaternion",
      "type": "topic",
      "url": "/documentation/metal/mtlpackedfloatquaternion"
    },
    "doc://com.apple.metal/documentation/Metal/MTLStitchedLibraryOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLStitchedLibraryOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLStitchedLibraryOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLStitchedLibraryOptions"
        }
      ],
      "role": "symbol",
      "title": "MTLStitchedLibraryOptions",
      "type": "topic",
      "url": "/documentation/metal/mtlstitchedlibraryoptions"
    },
    "doc://com.apple.metal/documentation/Metal/NSDeviceCertification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDeviceCertification"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/NSDeviceCertification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDeviceCertification"
        }
      ],
      "role": "symbol",
      "title": "NSDeviceCertification",
      "type": "topic",
      "url": "/documentation/metal/nsdevicecertification"
    },
    "doc://com.apple.metal/documentation/Metal/NSProcessPerformanceProfile": {
      "abstract": [
        {
          "text": "A value describing the device’s performance profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSProcessPerformanceProfile"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/NSProcessPerformanceProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSProcessPerformanceProfile"
        }
      ],
      "role": "symbol",
      "title": "NSProcessPerformanceProfile",
      "type": "topic",
      "url": "/documentation/metal/nsprocessperformanceprofile"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct",
        "doc://com.apple.metal/documentation/Metal/MTLCounterSampleBufferError-swift.struct",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct",
        "doc://com.apple.metal/documentation/Metal/MTLIOError-swift.struct",
        "doc://com.apple.metal/documentation/Metal/MTLPackedFloatQuaternion",
        "doc://com.apple.metal/documentation/Metal/MTLStitchedLibraryOptions",
        "doc://com.apple.metal/documentation/Metal/NSDeviceCertification",
        "doc://com.apple.metal/documentation/Metal/NSProcessPerformanceProfile"
      ],
      "title": "Structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLComponentTransform/init()",
        "doc://com.apple.metal/documentation/Metal/MTLComponentTransform/init(scale:shear:pivot:rotation:translation:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLComponentTransform/pivot",
        "doc://com.apple.metal/documentation/Metal/MTLComponentTransform/rotation",
        "doc://com.apple.metal/documentation/Metal/MTLComponentTransform/scale",
        "doc://com.apple.metal/documentation/Metal/MTLComponentTransform/shear",
        "doc://com.apple.metal/documentation/Metal/MTLComponentTransform/translation"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLComponentTransform"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLComponentTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLComponentTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLComponentTransform/pivot",
                "doc://com.apple.metal/documentation/Metal/MTLComponentTransform/rotation",
                "doc://com.apple.metal/documentation/Metal/MTLComponentTransform/scale",
                "doc://com.apple.metal/documentation/Metal/MTLComponentTransform/shear",
                "doc://com.apple.metal/documentation/Metal/MTLComponentTransform/translation"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Structures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLPackedFloatQuaternion",
                "doc://com.apple.metal/documentation/Metal/MTLStitchedLibraryOptions",
                "doc://com.apple.metal/documentation/Metal/NSDeviceCertification",
                "doc://com.apple.metal/documentation/Metal/NSProcessPerformanceProfile"
              ],
              "title": "Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLComponentTransform"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStitchedLibraryOptions/title",
          "value": "MTLStitchedLibraryOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStitchedLibraryOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStitchedLibraryOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStitchedLibraryOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStitchedLibraryOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComponentTransform~1translation/title",
          "value": "translation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComponentTransform~1translation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "translation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPackedFloatQuaternion/title",
          "value": "MTLPackedFloatQuaternion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPackedFloatQuaternion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPackedFloatQuaternion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPackedFloatQuaternion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPackedFloatQuaternion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1NSDeviceCertification/title",
          "value": "NSDeviceCertification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1NSDeviceCertification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeviceCertification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1NSDeviceCertification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeviceCertification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1NSProcessPerformanceProfile/title",
          "value": "NSProcessPerformanceProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1NSProcessPerformanceProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSProcessPerformanceProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1NSProcessPerformanceProfile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSProcessPerformanceProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComponentTransform~1scale/title",
          "value": "scale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComponentTransform~1scale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComponentTransform/title",
          "value": "MTLComponentTransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComponentTransform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLComponentTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComponentTransform/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLComponentTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComponentTransform~1rotation/title",
          "value": "rotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComponentTransform~1rotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComponentTransform~1pivot/title",
          "value": "pivot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComponentTransform~1pivot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pivot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComponentTransform~1shear/title",
          "value": "shear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComponentTransform~1shear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shear"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlcomponenttransform"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlcomponenttransform"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
