{
  "abstract": [
    {
      "text": "The data structure for storing the data you resolve from a statistic counter set.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@MTLCounterResultStatistic",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLCounterResultStatistic"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLCounterResultStatistic"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "MTLCounterResultStatistic"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLCounterResultStatistic"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.metal/documentation/Metal/converting-a-gpus-counter-data-into-a-readable-format"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For steps that explain how to resolve data from a counter set, such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounterSet/statistic",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/converting-a-gpus-counter-data-into-a-readable-format",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommonCounterSet/statistic": {
      "abstract": [
        {
          "text": "The common name for the counter set that contains GPU workload statistics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statistic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLCommonCounterSet",
          "text": "MTLCommonCounterSet"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounterSet/statistic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommonCounterSetStatistic"
        }
      ],
      "role": "symbol",
      "title": "statistic",
      "type": "topic",
      "url": "/documentation/metal/mtlcommoncounterset/statistic"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterErrorValue": {
      "abstract": [
        {
          "text": "A sentinel value for an entry in a counter sample buffer that indicates the entry’s data is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCounterErrorValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterErrorValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCounterErrorValue"
        }
      ],
      "role": "symbol",
      "title": "MTLCounterErrorValue",
      "type": "topic",
      "url": "/documentation/metal/mtlcountererrorvalue"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterResultStageUtilization": {
      "abstract": [
        {
          "text": "The data structure for storing the data you resolve from a stage-utilization counter set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCounterResultStageUtilization"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterResultStageUtilization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCounterResultStageUtilization"
        }
      ],
      "role": "symbol",
      "title": "MTLCounterResultStageUtilization",
      "type": "topic",
      "url": "/documentation/metal/mtlcounterresultstageutilization"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic": {
      "abstract": [
        {
          "text": "The data structure for storing the data you resolve from a statistic counter set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCounterResultStatistic"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCounterResultStatistic"
        }
      ],
      "role": "symbol",
      "title": "MTLCounterResultStatistic",
      "type": "topic",
      "url": "/documentation/metal/mtlcounterresultstatistic"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/clipperInvocations": {
      "abstract": [
        {
          "text": "The number of primitives a render pass sends to the clip stage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clipperInvocations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/clipperInvocations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clipperInvocations"
        }
      ],
      "role": "symbol",
      "title": "clipperInvocations",
      "type": "topic",
      "url": "/documentation/metal/mtlcounterresultstatistic/clipperinvocations"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/clipperPrimitivesOut": {
      "abstract": [
        {
          "text": "The number of primitives the clip stage produces during a render pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clipperPrimitivesOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/clipperPrimitivesOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clipperPrimitivesOut"
        }
      ],
      "role": "symbol",
      "title": "clipperPrimitivesOut",
      "type": "topic",
      "url": "/documentation/metal/mtlcounterresultstatistic/clipperprimitivesout"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/computeKernelInvocations": {
      "abstract": [
        {
          "text": "The number of times a pass calls any compute kernel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "computeKernelInvocations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/computeKernelInvocations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "computeKernelInvocations"
        }
      ],
      "role": "symbol",
      "title": "computeKernelInvocations",
      "type": "topic",
      "url": "/documentation/metal/mtlcounterresultstatistic/computekernelinvocations"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/fragmentInvocations": {
      "abstract": [
        {
          "text": "The number of times a render pass calls fragment shaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fragmentInvocations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/fragmentInvocations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fragmentInvocations"
        }
      ],
      "role": "symbol",
      "title": "fragmentInvocations",
      "type": "topic",
      "url": "/documentation/metal/mtlcounterresultstatistic/fragmentinvocations"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/fragmentsPassed": {
      "abstract": [
        {
          "text": "The number of fragments a render pass sends to the visibility and blend stages because they pass the scissor, depth, and stencil tests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fragmentsPassed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/fragmentsPassed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fragmentsPassed"
        }
      ],
      "role": "symbol",
      "title": "fragmentsPassed",
      "type": "topic",
      "url": "/documentation/metal/mtlcounterresultstatistic/fragmentspassed"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/init()": {
      "abstract": [
        {
          "text": "Creates a default statistics result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/metal/mtlcounterresultstatistic/init()"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/init(tessellationInputPatches:vertexInvocations:postTessellationVertexInvocations:clipperInvocations:clipperPrimitivesOut:fragmentInvocations:fragmentsPassed:computeKernelInvocations:)": {
      "abstract": [
        {
          "text": "Creates a statistics result from statistic values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "tessellationInputPatches"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "vertexInvocations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "postTessellationVertexInvocations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "clipperInvocations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "clipperPrimitivesOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fragmentInvocations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fragmentsPassed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "computeKernelInvocations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/init(tessellationInputPatches:vertexInvocations:postTessellationVertexInvocations:clipperInvocations:clipperPrimitivesOut:fragmentInvocations:fragmentsPassed:computeKernelInvocations:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(tessellationInputPatches:vertexInvocations:postTessellationVertexInvocations:clipperInvocations:clipperPrimitivesOut:fragmentInvocations:fragmentsPassed:computeKernelInvocations:)",
      "type": "topic",
      "url": "/documentation/metal/mtlcounterresultstatistic/init(tessellationinputpatches:vertexinvocations:posttessellationvertexinvocations:clipperinvocations:clipperprimitivesout:fragmentinvocations:fragmentspassed:computekernelinvocations:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/postTessellationVertexInvocations": {
      "abstract": [
        {
          "text": "The number of vertices a render pass sends to a post-tessellation vertex shader.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postTessellationVertexInvocations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/postTessellationVertexInvocations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "postTessellationVertexInvocations"
        }
      ],
      "role": "symbol",
      "title": "postTessellationVertexInvocations",
      "type": "topic",
      "url": "/documentation/metal/mtlcounterresultstatistic/posttessellationvertexinvocations"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/tessellationInputPatches": {
      "abstract": [
        {
          "text": "The number of tessellation patches a render pass sends to the tessellation stage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tessellationInputPatches"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/tessellationInputPatches",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tessellationInputPatches"
        }
      ],
      "role": "symbol",
      "title": "tessellationInputPatches",
      "type": "topic",
      "url": "/documentation/metal/mtlcounterresultstatistic/tessellationinputpatches"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/vertexInvocations": {
      "abstract": [
        {
          "text": "The number of times a render pass calls any vertex shader.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vertexInvocations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/vertexInvocations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vertexInvocations"
        }
      ],
      "role": "symbol",
      "title": "vertexInvocations",
      "type": "topic",
      "url": "/documentation/metal/mtlcounterresultstatistic/vertexinvocations"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterResultTimestamp": {
      "abstract": [
        {
          "text": "The data structure for storing the data you resolve from a timestamp counter set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCounterResultTimestamp"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterResultTimestamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCounterResultTimestamp"
        }
      ],
      "role": "symbol",
      "title": "MTLCounterResultTimestamp",
      "type": "topic",
      "url": "/documentation/metal/mtlcounterresulttimestamp"
    },
    "doc://com.apple.metal/documentation/Metal/converting-a-gpus-counter-data-into-a-readable-format": {
      "abstract": [
        {
          "text": "Inspect and use the data within a GPU’s counter sample buffer by resolving it into a standard format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/converting-a-gpus-counter-data-into-a-readable-format",
      "kind": "article",
      "role": "article",
      "title": "Converting a GPU’s Counter Data into a Readable Format",
      "type": "topic",
      "url": "/documentation/metal/converting-a-gpus-counter-data-into-a-readable-format"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Counter-Sample-Data-Output",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/converting-a-gpus-counter-data-into-a-readable-format",
        "doc://com.apple.metal/documentation/Metal/MTLCounterResultTimestamp",
        "doc://com.apple.metal/documentation/Metal/MTLCounterResultStageUtilization",
        "doc://com.apple.metal/documentation/Metal/MTLCounterErrorValue"
      ],
      "title": "Counter Sample Data Output"
    }
  ],
  "topicSections": [
    {
      "anchor": "Statistics-Values",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/tessellationInputPatches",
        "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/vertexInvocations",
        "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/postTessellationVertexInvocations",
        "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/clipperInvocations",
        "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/clipperPrimitivesOut",
        "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/fragmentInvocations",
        "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/fragmentsPassed",
        "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/computeKernelInvocations"
      ],
      "title": "Statistics Values"
    },
    {
      "anchor": "Swift-Support",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/init()",
        "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/init(tessellationInputPatches:vertexInvocations:postTessellationVertexInvocations:clipperInvocations:clipperPrimitivesOut:fragmentInvocations:fragmentsPassed:computeKernelInvocations:)"
      ],
      "title": "Swift Support"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLCounterResultStatistic"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCounterResultStatistic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCounterResultStatistic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Statistics-Values",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/tessellationInputPatches",
                "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/vertexInvocations",
                "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/postTessellationVertexInvocations",
                "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/clipperInvocations",
                "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/clipperPrimitivesOut",
                "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/fragmentInvocations",
                "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/fragmentsPassed",
                "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/computeKernelInvocations"
              ],
              "title": "Statistics Values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Counter-Sample-Data-Output",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/converting-a-gpus-counter-data-into-a-readable-format",
                "doc://com.apple.metal/documentation/Metal/MTLCounterResultTimestamp",
                "doc://com.apple.metal/documentation/Metal/MTLCounterResultStageUtilization",
                "doc://com.apple.metal/documentation/Metal/MTLCounterErrorValue"
              ],
              "title": "Counter Sample Data Output"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLCounterResultStatistic"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1computeKernelInvocations/title",
          "value": "computeKernelInvocations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1computeKernelInvocations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "computeKernelInvocations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1fragmentInvocations/title",
          "value": "fragmentInvocations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1fragmentInvocations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fragmentInvocations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1tessellationInputPatches/title",
          "value": "tessellationInputPatches"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1tessellationInputPatches/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tessellationInputPatches"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic/title",
          "value": "MTLCounterResultStatistic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCounterResultStatistic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCounterResultStatistic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1fragmentsPassed/title",
          "value": "fragmentsPassed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1fragmentsPassed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fragmentsPassed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultTimestamp/title",
          "value": "MTLCounterResultTimestamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultTimestamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCounterResultTimestamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultTimestamp/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCounterResultTimestamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterErrorValue/title",
          "value": "MTLCounterErrorValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterErrorValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCounterErrorValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1vertexInvocations/title",
          "value": "vertexInvocations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1vertexInvocations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vertexInvocations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1clipperInvocations/title",
          "value": "clipperInvocations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1clipperInvocations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "clipperInvocations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1postTessellationVertexInvocations/title",
          "value": "postTessellationVertexInvocations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1postTessellationVertexInvocations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "postTessellationVertexInvocations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounterSet~1statistic/title",
          "value": "MTLCommonCounterSetStatistic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounterSet~1statistic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterSetStatistic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStageUtilization/title",
          "value": "MTLCounterResultStageUtilization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStageUtilization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCounterResultStageUtilization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStageUtilization/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCounterResultStageUtilization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1clipperPrimitivesOut/title",
          "value": "clipperPrimitivesOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1clipperPrimitivesOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "clipperPrimitivesOut"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlcounterresultstatistic"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlcounterresultstatistic"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
