{
  "abstract": [
    {
      "text": "A Swift closure or an Objective-C block that Metal calls",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "when the system adds or removes a GPU device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLDeviceNotificationHandler"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@MTLDeviceNotificationHandler",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLDeviceNotificationHandler"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLDeviceNotificationHandler"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "MTLDeviceNotificationHandler"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLDeviceNotificationHandler"
            },
            {
              "kind": "text",
              "text": " = (any "
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)MTLDevice",
              "text": "MTLDevice"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLDeviceNotificationName",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@MTLDeviceNotificationName",
              "text": "MTLDeviceNotificationName"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " that represents the GPU that’s sending the notification.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "device"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A notification that represents a change to a GPU device in the system.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "notifyName"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/coregraphics/1493900-cgdirectdisplaycopycurrentmetald": {
      "abstract": [
        {
          "text": "Returns the GPU device instance that’s currently driving a display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "CGDirectDisplayCopyCurrentMetalDevice"
        },
        {
          "kind": "text",
          "text": "(CGDirectDisplayID) -> (any MTLDevice)?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coregraphics/1493900-cgdirectdisplaycopycurrentmetald",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGDirectDisplayCopyCurrentMetalDevice(_:)",
      "type": "topic",
      "url": "/documentation/coregraphics/1493900-cgdirectdisplaycopycurrentmetald"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCopyAllDevices()": {
      "abstract": [
        {
          "text": "Returns an array of all the Metal device instances in the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCopyAllDevices"
        },
        {
          "kind": "text",
          "text": "() -> [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDevice",
          "text": "MTLDevice"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCopyAllDevices()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCopyAllDevices"
        }
      ],
      "role": "symbol",
      "title": "MTLCopyAllDevices()",
      "type": "topic",
      "url": "/documentation/metal/mtlcopyalldevices()"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCopyAllDevicesWithObserver": {
      "abstract": [
        {
          "text": "Returns an array of all the Metal GPU devices in the system and registers a notification handler that Metal calls when the device list changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTLCopyAllDevicesWithObserver"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCopyAllDevicesWithObserver",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLCopyAllDevicesWithObserver",
      "type": "topic",
      "url": "/documentation/metal/mtlcopyalldeviceswithobserver"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCopyAllDevicesWithObserver(handler:)": {
      "abstract": [
        {
          "text": "Returns an array of all the Metal GPU devices in the system and registers a notification handler that Metal calls when the device list changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCopyAllDevicesWithObserver"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLDeviceNotificationHandler",
          "text": "MTLDeviceNotificationHandler"
        },
        {
          "kind": "text",
          "text": ") -> (devices"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDevice",
          "text": "MTLDevice"
        },
        {
          "kind": "text",
          "text": "], observer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSObject",
          "text": "NSObject"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCopyAllDevicesWithObserver(handler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLCopyAllDevicesWithObserver(handler:)",
      "type": "topic",
      "url": "/documentation/metal/mtlcopyalldeviceswithobserver(handler:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice": {
      "abstract": [
        {
          "text": "The main Metal interface to a GPU that apps use to draw graphics and run computations in parallel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDevice"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDevice"
        }
      ],
      "role": "symbol",
      "title": "MTLDevice",
      "type": "topic",
      "url": "/documentation/metal/mtldevice"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDeviceNotificationHandler": {
      "abstract": [
        {
          "text": "A Swift closure or an Objective-C block that Metal calls",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "when the system adds or removes a GPU device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDeviceNotificationHandler"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDeviceNotificationHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDeviceNotificationHandler"
        }
      ],
      "role": "symbol",
      "title": "MTLDeviceNotificationHandler",
      "type": "topic",
      "url": "/documentation/metal/mtldevicenotificationhandler"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDeviceNotificationName": {
      "abstract": [
        {
          "text": "A notification that represents a change to a GPU device in the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDeviceNotificationName"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDeviceNotificationName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDeviceNotificationName"
        }
      ],
      "role": "symbol",
      "title": "MTLDeviceNotificationName",
      "type": "topic",
      "url": "/documentation/metal/mtldevicenotificationname"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRemoveDeviceObserver(_:)": {
      "abstract": [
        {
          "text": "Removes a registered observer of device notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLRemoveDeviceObserver"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRemoveDeviceObserver(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLRemoveDeviceObserver"
        }
      ],
      "role": "symbol",
      "title": "MTLRemoveDeviceObserver(_:)",
      "type": "topic",
      "url": "/documentation/metal/mtlremovedeviceobserver(_:)"
    },
    "doc://com.apple.metal/documentation/Metal/finding-multiple-gpus-on-an-intel-based-mac": {
      "abstract": [
        {
          "text": "Locate, identify, and choose suitable GPUs for your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/finding-multiple-gpus-on-an-intel-based-mac",
      "kind": "article",
      "role": "article",
      "title": "Finding Multiple GPUs on an Intel-based Mac",
      "type": "topic",
      "url": "/documentation/metal/finding-multiple-gpus-on-an-intel-based-mac"
    },
    "doc://com.apple.metal/documentation/Metal/getting-the-gpu-that-drives-a-views-display": {
      "abstract": [
        {
          "text": "Keep up to date with the optimal device for your display.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/getting-the-gpu-that-drives-a-views-display",
      "kind": "article",
      "role": "article",
      "title": "Getting the GPU that Drives a View’s Display",
      "type": "topic",
      "url": "/documentation/metal/getting-the-gpu-that-drives-a-views-display"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Locating-GPUs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/finding-multiple-gpus-on-an-intel-based-mac",
        "doc://com.apple.metal/documentation/Metal/getting-the-gpu-that-drives-a-views-display",
        "doc://com.apple.metal/documentation/Metal/MTLCopyAllDevices()",
        "doc://com.apple.metal/documentation/Metal/MTLCopyAllDevicesWithObserver(handler:)",
        "doc://com.apple.metal/documentation/Metal/MTLRemoveDeviceObserver(_:)",
        "doc://com.apple.documentation/documentation/coregraphics/1493900-cgdirectdisplaycopycurrentmetald",
        "doc://com.apple.metal/documentation/Metal/MTLDeviceNotificationName"
      ],
      "title": "Locating GPUs"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLDeviceNotificationHandler"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDeviceNotificationHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDeviceNotificationHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Locating-GPUs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/finding-multiple-gpus-on-an-intel-based-mac",
                "doc://com.apple.metal/documentation/Metal/getting-the-gpu-that-drives-a-views-display",
                "doc://com.apple.metal/documentation/Metal/MTLCopyAllDevices()",
                "doc://com.apple.metal/documentation/Metal/MTLCopyAllDevicesWithObserver",
                "doc://com.apple.metal/documentation/Metal/MTLRemoveDeviceObserver(_:)",
                "doc://com.apple.documentation/documentation/coregraphics/1493900-cgdirectdisplaycopycurrentmetald",
                "doc://com.apple.metal/documentation/Metal/MTLDeviceNotificationName"
              ],
              "title": "Locating GPUs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:BFv(#*Qoobjc(pl)MTLDevice#*$objc(cs)NSString)",
                    "text": "void (^)(id<MTLDevice>, NSString *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLDeviceNotificationHandler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/title",
          "value": "MTLDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceNotificationHandler/title",
          "value": "MTLDeviceNotificationHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceNotificationHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDeviceNotificationHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceNotificationHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDeviceNotificationHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1coregraphics~11493900-cgdirectdisplaycopycurrentmetald/title",
          "value": "CGDirectDisplayCopyCurrentMetalDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceNotificationName/title",
          "value": "MTLDeviceNotificationName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceNotificationName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDeviceNotificationName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceNotificationName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDeviceNotificationName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRemoveDeviceObserver(_:)/title",
          "value": "MTLRemoveDeviceObserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRemoveDeviceObserver(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRemoveDeviceObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCopyAllDevices()/title",
          "value": "MTLCopyAllDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCopyAllDevices()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCopyAllDevices"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtldevicenotificationhandler"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtldevicenotificationhandler"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
