{
  "abstract": [
    {
      "text": "The device feature sets that define specific platform, hardware, and software configurations.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.metal/documentation/Metal/MTLGPUFamily",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLFeatureSet",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLFeatureSet"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLFeatureSet"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.0",
        "introducedAt": "8.0",
        "message": "Use MTLGPUFamily instead",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.0",
        "introducedAt": "8.0",
        "message": "Use MTLGPUFamily instead",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.0",
        "introducedAt": "13.1",
        "message": "Use MTLGPUFamily instead",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "10.11",
        "message": "Use MTLGPUFamily instead",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.0",
        "introducedAt": "9.0",
        "message": "Use MTLGPUFamily instead",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Use MTLGPUFamily instead",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTLFeatureSet"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLFeatureSet"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If your app is running on an operating system that supports the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFamily(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, use that method instead. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/detecting-gpu-features-and-metal-software-versions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more information about ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLGPUFamily",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " — the replacement for this enumeration —  and the feature set tables. This type doesn’t define constants for GPU families introduced after iOS GPU family 5.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Metal feature sets define the feature availability, implementation limits, and pixel format capabilities for each device. The table shows the GPU families and their corresponding GPU hardware.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "GPU family",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "GPU hardware",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "iOS GPU family 1",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Apple A7 devices",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "iOS GPU family 2 ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " tvOS GPU family 1",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Apple A8 devices",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "iOS GPU family 3 ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " tvOS GPU family 2",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Apple A9 devices ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " Apple A10 devices",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "iOS GPU family 4",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Apple A11 devices",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "iOS GPU family 5",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Apple A12 devices",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "macOS GPU family 1",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "iMac Pro models ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " iMac models from 2012 or later ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " MacBook models from 2015 or later ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " MacBook Pro models from 2012 or later ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " MacBook Air models from 2012 or later ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " Mac mini models from 2012 or later ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " Mac Pro models from late 2013",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "macOS GPU family 2",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "iMac models from 2015 or later ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " MacBook Pro models from 2016 or later ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " MacBook models from 2016 or later ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " iMac Pro models from 2017 or later",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "For more information on Mac support for Metal, see ",
              "type": "text"
            },
            {
              "identifier": "https://support.apple.com/en-us/HT205073",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFamily(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the GPU device supports the feature set of a specific GPU family.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsFamily"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLGPUFamily",
          "text": "MTLGPUFamily"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFamily(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsFamily:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "supportsFamily(_:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/supportsfamily(_:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFeatureSet(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the GPU device supports a specific feature set.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsFeatureSet"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLFeatureSet",
          "text": "MTLFeatureSet"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFeatureSet(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsFeatureSet:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "supportsFeatureSet(_:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/supportsfeatureset(_:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet": {
      "abstract": [
        {
          "text": "The device feature sets that define specific platform, hardware, and software configurations.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFeatureSet"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v1": {
      "abstract": [
        {
          "text": "The GPU family 1, version 1 feature set for iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOS_GPUFamily1_v1"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_iOS_GPUFamily1_v1"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.iOS_GPUFamily1_v1",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/ios_gpufamily1_v1"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v2": {
      "abstract": [
        {
          "text": "The GPU family 1, version 2 feature set for iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOS_GPUFamily1_v2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_iOS_GPUFamily1_v2"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.iOS_GPUFamily1_v2",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/ios_gpufamily1_v2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v3": {
      "abstract": [
        {
          "text": "The GPU family 1, version 3 feature set for iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOS_GPUFamily1_v3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_iOS_GPUFamily1_v3"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.iOS_GPUFamily1_v3",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/ios_gpufamily1_v3"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v4": {
      "abstract": [
        {
          "text": "The GPU family 1, version 4 feature set for iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOS_GPUFamily1_v4"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_iOS_GPUFamily1_v4"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.iOS_GPUFamily1_v4",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/ios_gpufamily1_v4"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v5": {
      "abstract": [
        {
          "text": "The GPU family 1, version 5 feature set for iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOS_GPUFamily1_v5"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_iOS_GPUFamily1_v5"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.iOS_GPUFamily1_v5",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/ios_gpufamily1_v5"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily2_v1": {
      "abstract": [
        {
          "text": "The GPU family 2, version 1 feature set for iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOS_GPUFamily2_v1"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily2_v1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_iOS_GPUFamily2_v1"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.iOS_GPUFamily2_v1",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/ios_gpufamily2_v1"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily2_v2": {
      "abstract": [
        {
          "text": "The GPU family 2, version 2 feature set for iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOS_GPUFamily2_v2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily2_v2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_iOS_GPUFamily2_v2"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.iOS_GPUFamily2_v2",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/ios_gpufamily2_v2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily2_v3": {
      "abstract": [
        {
          "text": "The GPU family 2, version 3 feature set for iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOS_GPUFamily2_v3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily2_v3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_iOS_GPUFamily2_v3"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.iOS_GPUFamily2_v3",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/ios_gpufamily2_v3"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily2_v4": {
      "abstract": [
        {
          "text": "The GPU family 2, version 4 feature set for iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOS_GPUFamily2_v4"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily2_v4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_iOS_GPUFamily2_v4"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.iOS_GPUFamily2_v4",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/ios_gpufamily2_v4"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily2_v5": {
      "abstract": [
        {
          "text": "The GPU family 2, version 5 feature set for iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOS_GPUFamily2_v5"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily2_v5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_iOS_GPUFamily2_v5"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.iOS_GPUFamily2_v5",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/ios_gpufamily2_v5"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily3_v1": {
      "abstract": [
        {
          "text": "The GPU family 3, version 1 feature set for iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOS_GPUFamily3_v1"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily3_v1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_iOS_GPUFamily3_v1"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.iOS_GPUFamily3_v1",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/ios_gpufamily3_v1"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily3_v2": {
      "abstract": [
        {
          "text": "The GPU family 3, version 2 feature set for iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOS_GPUFamily3_v2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily3_v2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_iOS_GPUFamily3_v2"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.iOS_GPUFamily3_v2",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/ios_gpufamily3_v2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily3_v3": {
      "abstract": [
        {
          "text": "The GPU family 3, version 3 feature set for iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOS_GPUFamily3_v3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily3_v3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_iOS_GPUFamily3_v3"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.iOS_GPUFamily3_v3",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/ios_gpufamily3_v3"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily3_v4": {
      "abstract": [
        {
          "text": "The GPU family 3, version 4 feature set for iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOS_GPUFamily3_v4"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily3_v4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_iOS_GPUFamily3_v4"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.iOS_GPUFamily3_v4",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/ios_gpufamily3_v4"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily4_v1": {
      "abstract": [
        {
          "text": "The GPU family 4, version 1 feature set for iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOS_GPUFamily4_v1"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily4_v1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_iOS_GPUFamily4_v1"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.iOS_GPUFamily4_v1",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/ios_gpufamily4_v1"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily4_v2": {
      "abstract": [
        {
          "text": "The GPU family 4, version 2 feature set for iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOS_GPUFamily4_v2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily4_v2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_iOS_GPUFamily4_v2"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.iOS_GPUFamily4_v2",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/ios_gpufamily4_v2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily5_v1": {
      "abstract": [
        {
          "text": "The GPU family 5, version 1 feature set for iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOS_GPUFamily5_v1"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily5_v1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_iOS_GPUFamily5_v1"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.iOS_GPUFamily5_v1",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/ios_gpufamily5_v1"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/init(rawvalue:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/macOS_GPUFamily1_v1": {
      "abstract": [
        {
          "text": "The GPU family 1, version 1 feature set for macOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS_GPUFamily1_v1"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/macOS_GPUFamily1_v1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_macOS_GPUFamily1_v1"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.macOS_GPUFamily1_v1",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/macos_gpufamily1_v1"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/macOS_GPUFamily1_v2": {
      "abstract": [
        {
          "text": "The GPU family 1, version 2 feature set for macOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS_GPUFamily1_v2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/macOS_GPUFamily1_v2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_macOS_GPUFamily1_v2"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.macOS_GPUFamily1_v2",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/macos_gpufamily1_v2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/macOS_GPUFamily1_v3": {
      "abstract": [
        {
          "text": "The GPU family 1, version 3 feature set for macOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS_GPUFamily1_v3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/macOS_GPUFamily1_v3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_macOS_GPUFamily1_v3"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.macOS_GPUFamily1_v3",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/macos_gpufamily1_v3"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/macOS_GPUFamily1_v4": {
      "abstract": [
        {
          "text": "The GPU family 1, version 4 feature set for macOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS_GPUFamily1_v4"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/macOS_GPUFamily1_v4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_macOS_GPUFamily1_v4"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.macOS_GPUFamily1_v4",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/macos_gpufamily1_v4"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/macOS_GPUFamily2_v1": {
      "abstract": [
        {
          "text": "The GPU family 2, version 1 feature set for macOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS_GPUFamily2_v1"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/macOS_GPUFamily2_v1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_macOS_GPUFamily2_v1"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.macOS_GPUFamily2_v1",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/macos_gpufamily2_v1"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/macOS_ReadWriteTextureTier2": {
      "abstract": [
        {
          "text": "The read-write texture, tier 2 feature set for macOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS_ReadWriteTextureTier2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/macOS_ReadWriteTextureTier2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_macOS_ReadWriteTextureTier2"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.macOS_ReadWriteTextureTier2",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/macos_readwritetexturetier2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/osx_GPUFamily1_v1": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "osx_GPUFamily1_v1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLFeatureSet",
          "text": "MTLFeatureSet"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/osx_GPUFamily1_v1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_OSX_GPUFamily1_v1"
        }
      ],
      "role": "symbol",
      "title": "osx_GPUFamily1_v1",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/osx_gpufamily1_v1"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/osx_GPUFamily1_v2": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "osx_GPUFamily1_v2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLFeatureSet",
          "text": "MTLFeatureSet"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/osx_GPUFamily1_v2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_OSX_GPUFamily1_v2"
        }
      ],
      "role": "symbol",
      "title": "osx_GPUFamily1_v2",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/osx_gpufamily1_v2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/osx_ReadWriteTextureTier2": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "osx_ReadWriteTextureTier2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLFeatureSet",
          "text": "MTLFeatureSet"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/osx_ReadWriteTextureTier2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_OSX_ReadWriteTextureTier2"
        }
      ],
      "role": "symbol",
      "title": "osx_ReadWriteTextureTier2",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/osx_readwritetexturetier2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/tvOS_GPUFamily1_v1-swift.enum.case": {
      "abstract": [
        {
          "text": "The GPU family 1, version 1 feature set for tvOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tvOS_GPUFamily1_v1"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/tvOS_GPUFamily1_v1-swift.enum.case",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_tvOS_GPUFamily1_v1"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.tvOS_GPUFamily1_v1",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/tvos_gpufamily1_v1-swift.enum.case"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/tvOS_GPUFamily1_v2": {
      "abstract": [
        {
          "text": "The GPU family 1, version 2 feature set for tvOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tvOS_GPUFamily1_v2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/tvOS_GPUFamily1_v2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_tvOS_GPUFamily1_v2"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.tvOS_GPUFamily1_v2",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/tvos_gpufamily1_v2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/tvOS_GPUFamily1_v3": {
      "abstract": [
        {
          "text": "The GPU family 1, version 3 feature set for tvOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tvOS_GPUFamily1_v3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/tvOS_GPUFamily1_v3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_tvOS_GPUFamily1_v3"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.tvOS_GPUFamily1_v3",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/tvos_gpufamily1_v3"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/tvOS_GPUFamily1_v4": {
      "abstract": [
        {
          "text": "The GPU family 1, version 4 feature set for tvOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tvOS_GPUFamily1_v4"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/tvOS_GPUFamily1_v4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_tvOS_GPUFamily1_v4"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.tvOS_GPUFamily1_v4",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/tvos_gpufamily1_v4"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/tvOS_GPUFamily2_v1": {
      "abstract": [
        {
          "text": "The GPU family 2, version 1 feature set for tvOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tvOS_GPUFamily2_v1"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/tvOS_GPUFamily2_v1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_tvOS_GPUFamily2_v1"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.tvOS_GPUFamily2_v1",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/tvos_gpufamily2_v1"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/tvOS_GPUFamily2_v2": {
      "abstract": [
        {
          "text": "The GPU family 2, version 2 feature set for tvOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tvOS_GPUFamily2_v2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/tvOS_GPUFamily2_v2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_tvOS_GPUFamily2_v2"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.tvOS_GPUFamily2_v2",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/tvos_gpufamily2_v2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/tvos_GPUFamily1_v1-swift.type.property": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tvos_GPUFamily1_v1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLFeatureSet",
          "text": "MTLFeatureSet"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/tvos_GPUFamily1_v1-swift.type.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_TVOS_GPUFamily1_v1"
        }
      ],
      "role": "symbol",
      "title": "tvos_GPUFamily1_v1",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/tvos_gpufamily1_v1-swift.type.property"
    },
    "doc://com.apple.metal/documentation/Metal/MTLGPUFamily": {
      "abstract": [
        {
          "text": "Represents the functionality for families of GPUs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLGPUFamily"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLGPUFamily",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLGPUFamily"
        }
      ],
      "role": "symbol",
      "title": "MTLGPUFamily",
      "type": "topic",
      "url": "/documentation/metal/mtlgpufamily"
    },
    "doc://com.apple.metal/documentation/Metal/detecting-gpu-features-and-metal-software-versions": {
      "abstract": [
        {
          "text": "Use the device object’s properties to determine how you perform tasks in Metal.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/detecting-gpu-features-and-metal-software-versions",
      "kind": "article",
      "role": "article",
      "title": "Detecting GPU Features and Metal Software Versions",
      "type": "topic",
      "url": "/documentation/metal/detecting-gpu-features-and-metal-software-versions"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "https://support.apple.com/en-us/HT205073": {
      "identifier": "https://support.apple.com/en-us/HT205073",
      "title": "Mac computers that support Metal",
      "titleInlineContent": [
        {
          "text": "Mac computers that support Metal",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/en-us/HT205073"
    },
    "spacer": {
      "alt": null,
      "identifier": "spacer",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/67dc4b07a8d84366d4cc0e812eb40b4a/spacer.png"
        }
      ]
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Checking-a-GPU-Devices-Feature-Support",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFamily(_:)",
        "doc://com.apple.metal/documentation/Metal/MTLGPUFamily",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFeatureSet(_:)"
      ],
      "title": "Checking a GPU Device’s Feature Support"
    }
  ],
  "topicSections": [
    {
      "anchor": "iOS-GPU-Family-5",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily5_v1"
      ],
      "title": "iOS GPU Family 5"
    },
    {
      "anchor": "iOS-GPU-Family-4",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily4_v2",
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily4_v1"
      ],
      "title": "iOS GPU Family 4"
    },
    {
      "anchor": "iOS-GPU-Family-3",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily3_v4",
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily3_v3",
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily3_v2",
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily3_v1"
      ],
      "title": "iOS GPU Family 3"
    },
    {
      "anchor": "iOS-GPU-Family-2",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily2_v5",
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily2_v4",
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily2_v3",
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily2_v2",
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily2_v1"
      ],
      "title": "iOS GPU Family 2"
    },
    {
      "anchor": "iOS-GPU-Family-1",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v5",
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v4",
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v3",
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v2",
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v1"
      ],
      "title": "iOS GPU Family 1"
    },
    {
      "anchor": "tvOS-GPU-Family-2",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/tvOS_GPUFamily2_v2",
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/tvOS_GPUFamily2_v1"
      ],
      "title": "tvOS GPU Family 2"
    },
    {
      "anchor": "tvOS-GPU-Family-1",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/tvOS_GPUFamily1_v4",
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/tvOS_GPUFamily1_v3",
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/tvOS_GPUFamily1_v2",
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/tvOS_GPUFamily1_v1-swift.enum.case"
      ],
      "title": "tvOS GPU Family 1"
    },
    {
      "anchor": "macOS-GPU-Family-2",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/macOS_GPUFamily2_v1"
      ],
      "title": "macOS GPU Family 2"
    },
    {
      "anchor": "macOS-GPU-Family-1",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/macOS_GPUFamily1_v4",
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/macOS_GPUFamily1_v3",
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/macOS_GPUFamily1_v2",
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/macOS_GPUFamily1_v1"
      ],
      "title": "macOS GPU Family 1"
    },
    {
      "anchor": "macOS-Tier-2",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/macOS_ReadWriteTextureTier2"
      ],
      "title": "macOS Tier 2"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/osx_GPUFamily1_v1",
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/osx_GPUFamily1_v2",
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/osx_ReadWriteTextureTier2",
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/tvos_GPUFamily1_v1-swift.type.property"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.0",
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.0",
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.0",
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLFeatureSet"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "iOS-GPU-Family-5",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily5_v1"
              ],
              "title": "iOS GPU Family 5"
            },
            {
              "anchor": "iOS-GPU-Family-4",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily4_v2",
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily4_v1"
              ],
              "title": "iOS GPU Family 4"
            },
            {
              "anchor": "iOS-GPU-Family-3",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily3_v4",
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily3_v3",
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily3_v2",
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily3_v1"
              ],
              "title": "iOS GPU Family 3"
            },
            {
              "anchor": "iOS-GPU-Family-2",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily2_v5",
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily2_v4",
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily2_v3",
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily2_v2",
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily2_v1"
              ],
              "title": "iOS GPU Family 2"
            },
            {
              "anchor": "iOS-GPU-Family-1",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v5",
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v4",
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v3",
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v2",
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v1"
              ],
              "title": "iOS GPU Family 1"
            },
            {
              "anchor": "tvOS-GPU-Family-2",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/tvOS_GPUFamily2_v2",
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/tvOS_GPUFamily2_v1"
              ],
              "title": "tvOS GPU Family 2"
            },
            {
              "anchor": "tvOS-GPU-Family-1",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/tvOS_GPUFamily1_v4",
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/tvOS_GPUFamily1_v3",
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/tvOS_GPUFamily1_v2",
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/tvOS_GPUFamily1_v1-swift.enum.case"
              ],
              "title": "tvOS GPU Family 1"
            },
            {
              "anchor": "macOS-GPU-Family-2",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/macOS_GPUFamily2_v1"
              ],
              "title": "macOS GPU Family 2"
            },
            {
              "anchor": "macOS-GPU-Family-1",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/macOS_GPUFamily1_v4",
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/macOS_GPUFamily1_v3",
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/macOS_GPUFamily1_v2",
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/macOS_GPUFamily1_v1"
              ],
              "title": "macOS GPU Family 1"
            },
            {
              "anchor": "macOS-Tier-2",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/macOS_ReadWriteTextureTier2"
              ],
              "title": "macOS Tier 2"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/osx_GPUFamily1_v1",
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/osx_GPUFamily1_v2",
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/osx_ReadWriteTextureTier2",
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/tvos_GPUFamily1_v1-swift.type.property"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Checking-a-GPU-Devices-Feature-Support",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFamily(_:)",
                "doc://com.apple.metal/documentation/Metal/MTLGPUFamily",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFeatureSet(_:)"
              ],
              "title": "Checking a GPU Device’s Feature Support"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLFeatureSet"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.metal/documentation/Metal/MTLGPUFamily",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1tvos_GPUFamily1_v1-swift.type.property/title",
          "value": "MTLFeatureSet_TVOS_GPUFamily1_v1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1tvos_GPUFamily1_v1-swift.type.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_TVOS_GPUFamily1_v1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1macOS_GPUFamily1_v3/title",
          "value": "MTLFeatureSet_macOS_GPUFamily1_v3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1macOS_GPUFamily1_v3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_macOS_GPUFamily1_v3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily2_v4/title",
          "value": "MTLFeatureSet_iOS_GPUFamily2_v4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily2_v4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_iOS_GPUFamily2_v4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily2_v2/title",
          "value": "MTLFeatureSet_iOS_GPUFamily2_v2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily2_v2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_iOS_GPUFamily2_v2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily/title",
          "value": "MTLGPUFamily"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLGPUFamily"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLGPUFamily"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1macOS_GPUFamily1_v2/title",
          "value": "MTLFeatureSet_macOS_GPUFamily1_v2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1macOS_GPUFamily1_v2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_macOS_GPUFamily1_v2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1osx_GPUFamily1_v1/title",
          "value": "MTLFeatureSet_OSX_GPUFamily1_v1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1osx_GPUFamily1_v1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_OSX_GPUFamily1_v1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1macOS_GPUFamily1_v1/title",
          "value": "MTLFeatureSet_macOS_GPUFamily1_v1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1macOS_GPUFamily1_v1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_macOS_GPUFamily1_v1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily2_v3/title",
          "value": "MTLFeatureSet_iOS_GPUFamily2_v3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily2_v3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_iOS_GPUFamily2_v3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1macOS_GPUFamily1_v4/title",
          "value": "MTLFeatureSet_macOS_GPUFamily1_v4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1macOS_GPUFamily1_v4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_macOS_GPUFamily1_v4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsFamily(_:)/title",
          "value": "supportsFamily:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsFamily(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "supportsFamily:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily4_v1/title",
          "value": "MTLFeatureSet_iOS_GPUFamily4_v1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily4_v1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_iOS_GPUFamily4_v1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily1_v4/title",
          "value": "MTLFeatureSet_iOS_GPUFamily1_v4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily1_v4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_iOS_GPUFamily1_v4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily4_v2/title",
          "value": "MTLFeatureSet_iOS_GPUFamily4_v2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily4_v2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_iOS_GPUFamily4_v2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1osx_GPUFamily1_v2/title",
          "value": "MTLFeatureSet_OSX_GPUFamily1_v2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1osx_GPUFamily1_v2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_OSX_GPUFamily1_v2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily1_v5/title",
          "value": "MTLFeatureSet_iOS_GPUFamily1_v5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily1_v5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_iOS_GPUFamily1_v5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily3_v2/title",
          "value": "MTLFeatureSet_iOS_GPUFamily3_v2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily3_v2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_iOS_GPUFamily3_v2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily1_v2/title",
          "value": "MTLFeatureSet_iOS_GPUFamily1_v2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily1_v2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_iOS_GPUFamily1_v2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily1_v1/title",
          "value": "MTLFeatureSet_iOS_GPUFamily1_v1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily1_v1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_iOS_GPUFamily1_v1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily3_v1/title",
          "value": "MTLFeatureSet_iOS_GPUFamily3_v1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily3_v1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_iOS_GPUFamily3_v1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily5_v1/title",
          "value": "MTLFeatureSet_iOS_GPUFamily5_v1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily5_v1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_iOS_GPUFamily5_v1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet/title",
          "value": "MTLFeatureSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1tvOS_GPUFamily2_v2/title",
          "value": "MTLFeatureSet_tvOS_GPUFamily2_v2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1tvOS_GPUFamily2_v2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_tvOS_GPUFamily2_v2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1tvOS_GPUFamily1_v2/title",
          "value": "MTLFeatureSet_tvOS_GPUFamily1_v2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1tvOS_GPUFamily1_v2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_tvOS_GPUFamily1_v2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1tvOS_GPUFamily2_v1/title",
          "value": "MTLFeatureSet_tvOS_GPUFamily2_v1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1tvOS_GPUFamily2_v1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_tvOS_GPUFamily2_v1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1osx_ReadWriteTextureTier2/title",
          "value": "MTLFeatureSet_OSX_ReadWriteTextureTier2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1osx_ReadWriteTextureTier2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_OSX_ReadWriteTextureTier2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsFeatureSet(_:)/title",
          "value": "supportsFeatureSet:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsFeatureSet(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "supportsFeatureSet:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily3_v3/title",
          "value": "MTLFeatureSet_iOS_GPUFamily3_v3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily3_v3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_iOS_GPUFamily3_v3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily3_v4/title",
          "value": "MTLFeatureSet_iOS_GPUFamily3_v4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily3_v4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_iOS_GPUFamily3_v4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1tvOS_GPUFamily1_v4/title",
          "value": "MTLFeatureSet_tvOS_GPUFamily1_v4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1tvOS_GPUFamily1_v4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_tvOS_GPUFamily1_v4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1macOS_GPUFamily2_v1/title",
          "value": "MTLFeatureSet_macOS_GPUFamily2_v1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1macOS_GPUFamily2_v1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_macOS_GPUFamily2_v1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1macOS_ReadWriteTextureTier2/title",
          "value": "MTLFeatureSet_macOS_ReadWriteTextureTier2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1macOS_ReadWriteTextureTier2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_macOS_ReadWriteTextureTier2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily2_v1/title",
          "value": "MTLFeatureSet_iOS_GPUFamily2_v1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily2_v1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_iOS_GPUFamily2_v1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily2_v5/title",
          "value": "MTLFeatureSet_iOS_GPUFamily2_v5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily2_v5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_iOS_GPUFamily2_v5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1tvOS_GPUFamily1_v3/title",
          "value": "MTLFeatureSet_tvOS_GPUFamily1_v3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1tvOS_GPUFamily1_v3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_tvOS_GPUFamily1_v3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily1_v3/title",
          "value": "MTLFeatureSet_iOS_GPUFamily1_v3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily1_v3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_iOS_GPUFamily1_v3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1tvOS_GPUFamily1_v1-swift.enum.case/title",
          "value": "MTLFeatureSet_tvOS_GPUFamily1_v1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1tvOS_GPUFamily1_v1-swift.enum.case/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_tvOS_GPUFamily1_v1"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlfeatureset"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlfeatureset"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
