{
  "abstract": [
    {
      "text": "A log entry a Metal device generates when the it runs a command buffer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLFunctionLog"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MTLFunctionLog",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLFunctionLog"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLFunctionLog"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "MTLFunctionLog"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLFunctionLog"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFunctionLog": {
      "abstract": [
        {
          "text": "A log entry a Metal device generates when the it runs a command buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFunctionLog"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionLog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFunctionLog"
        }
      ],
      "role": "symbol",
      "title": "MTLFunctionLog",
      "type": "topic",
      "url": "/documentation/metal/mtlfunctionlog"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFunctionLog/debugLocation": {
      "abstract": [
        {
          "text": "If known, the location of the logging command within a shader source file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "debugLocation"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLFunctionLogDebugLocation",
          "text": "MTLFunctionLogDebugLocation"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionLog/debugLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "debugLocation"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "debugLocation",
      "type": "topic",
      "url": "/documentation/metal/mtlfunctionlog/debuglocation"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFunctionLog/encoderLabel": {
      "abstract": [
        {
          "text": "The label for the encoder that logged the message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encoderLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionLog/encoderLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "encoderLabel"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "encoderLabel",
      "type": "topic",
      "url": "/documentation/metal/mtlfunctionlog/encoderlabel"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFunctionLog/function": {
      "abstract": [
        {
          "text": "When known, the function object corresponding to the logged message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "function"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLFunction",
          "text": "MTLFunction"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionLog/function",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "function"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "function",
      "type": "topic",
      "url": "/documentation/metal/mtlfunctionlog/function"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFunctionLog/type": {
      "abstract": [
        {
          "text": "The type of message that was logged.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLFunctionLogType",
          "text": "MTLFunctionLogType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionLog/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/metal/mtlfunctionlog/type"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFunctionLogDebugLocation": {
      "abstract": [
        {
          "text": "The source code that logged a debug message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFunctionLogDebugLocation"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionLogDebugLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFunctionLogDebugLocation"
        }
      ],
      "role": "symbol",
      "title": "MTLFunctionLogDebugLocation",
      "type": "topic",
      "url": "/documentation/metal/mtlfunctionlogdebuglocation"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFunctionLogType": {
      "abstract": [
        {
          "text": "Options for different kinds of function logs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFunctionLogType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionLogType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFunctionLogType"
        }
      ],
      "role": "symbol",
      "title": "MTLFunctionLogType",
      "type": "topic",
      "url": "/documentation/metal/mtlfunctionlogtype"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLogContainer-c.protocol": {
      "abstract": [
        {
          "text": "A collection of logged messages, created when a Metal device runs a command buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTLLogContainer"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLogContainer-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLLogContainer",
      "type": "topic",
      "url": "/documentation/metal/mtllogcontainer-c.protocol"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLogContainer-swift.struct": {
      "abstract": [
        {
          "text": "A collection of logged messages, created when a Metal device runs a command buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLLogContainer"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLogContainer-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLogContainer"
        }
      ],
      "role": "symbol",
      "title": "MTLLogContainer",
      "type": "topic",
      "url": "/documentation/metal/mtllogcontainer-swift.struct"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Shader-Logs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLLogContainer-swift.struct"
      ],
      "title": "Shader Logs"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-Log-Messsage",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLFunctionLog/type",
        "doc://com.apple.metal/documentation/Metal/MTLFunctionLogType"
      ],
      "title": "Getting the Log Messsage"
    },
    {
      "anchor": "Getting-Execution-Details",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLFunctionLog/debugLocation",
        "doc://com.apple.metal/documentation/Metal/MTLFunctionLog/encoderLabel",
        "doc://com.apple.metal/documentation/Metal/MTLFunctionLog/function",
        "doc://com.apple.metal/documentation/Metal/MTLFunctionLogDebugLocation"
      ],
      "title": "Getting Execution Details"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLFunctionLog"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-Log-Messsage",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLFunctionLog/type",
                "doc://com.apple.metal/documentation/Metal/MTLFunctionLogType"
              ],
              "title": "Getting the Log Messsage"
            },
            {
              "anchor": "Getting-Execution-Details",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLFunctionLog/debugLocation",
                "doc://com.apple.metal/documentation/Metal/MTLFunctionLog/encoderLabel",
                "doc://com.apple.metal/documentation/Metal/MTLFunctionLog/function",
                "doc://com.apple.metal/documentation/Metal/MTLFunctionLogDebugLocation"
              ],
              "title": "Getting Execution Details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Shader-Logs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLLogContainer-c.protocol"
              ],
              "title": "Shader Logs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLFunctionLog"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionLog/title",
          "value": "MTLFunctionLog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionLog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionLog/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionLogDebugLocation/title",
          "value": "MTLFunctionLogDebugLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionLogDebugLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionLogDebugLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionLogDebugLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionLogDebugLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionLog~1function/title",
          "value": "function"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionLog~1function/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "function"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionLog~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionLog~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionLog~1debugLocation/title",
          "value": "debugLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionLog~1debugLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "debugLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionLogType/title",
          "value": "MTLFunctionLogType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionLogType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionLogType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionLogType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionLogType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionLog~1encoderLabel/title",
          "value": "encoderLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionLog~1encoderLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "encoderLabel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlfunctionlog"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlfunctionlog"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
