{
  "abstract": [
    {
      "text": "A call graph node that describes a function call and its inputs.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingFunctionNode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTLFunctionStitchingFunctionNode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLFunctionStitchingFunctionNode"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLFunctionStitchingFunctionNode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTLFunctionStitchingFunctionNode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLFunctionStitchingFunctionNode"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When the Metal device object evaluates the function graph to compile the stitched function, it evaluates the nodes stored in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingFunctionNode/arguments",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property that it hasn’t already evaluated, and then calls the function specified by ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingFunctionNode/name",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to generate the node’s output.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the function has side effects on the input data, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingFunctionNode/controlDependencies",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property on other nodes to specify whether the Metal device object must evaluate this node first.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingAttribute": {
      "abstract": [
        {
          "text": "A protocol to identify types that customize how the Metal compiler stitches a function together.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFunctionStitchingAttribute"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFunctionStitchingAttribute"
        }
      ],
      "role": "symbol",
      "title": "MTLFunctionStitchingAttribute",
      "type": "topic",
      "url": "/documentation/metal/mtlfunctionstitchingattribute"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingAttributeAlwaysInline": {
      "abstract": [
        {
          "text": "An attribute to specify that Metal needs to inline all of the function calls when generating the stitched function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFunctionStitchingAttributeAlwaysInline"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingAttributeAlwaysInline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFunctionStitchingAttributeAlwaysInline"
        }
      ],
      "role": "symbol",
      "title": "MTLFunctionStitchingAttributeAlwaysInline",
      "type": "topic",
      "url": "/documentation/metal/mtlfunctionstitchingattributealwaysinline"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingFunctionNode": {
      "abstract": [
        {
          "text": "A call graph node that describes a function call and its inputs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFunctionStitchingFunctionNode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingFunctionNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFunctionStitchingFunctionNode"
        }
      ],
      "role": "symbol",
      "title": "MTLFunctionStitchingFunctionNode",
      "type": "topic",
      "url": "/documentation/metal/mtlfunctionstitchingfunctionnode"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingFunctionNode/arguments": {
      "abstract": [
        {
          "text": "An ordered list of the nodes that provide the function’s arguments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arguments"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLFunctionStitchingNode",
          "text": "MTLFunctionStitchingNode"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingFunctionNode/arguments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "arguments"
        }
      ],
      "role": "symbol",
      "title": "arguments",
      "type": "topic",
      "url": "/documentation/metal/mtlfunctionstitchingfunctionnode/arguments"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingFunctionNode/controlDependencies": {
      "abstract": [
        {
          "text": "The list of nodes that must execute before executing the node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "controlDependencies"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLFunctionStitchingFunctionNode",
          "text": "MTLFunctionStitchingFunctionNode"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingFunctionNode/controlDependencies",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "controlDependencies"
        }
      ],
      "role": "symbol",
      "title": "controlDependencies",
      "type": "topic",
      "url": "/documentation/metal/mtlfunctionstitchingfunctionnode/controldependencies"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingFunctionNode/init(name:arguments:controlDependencies:)": {
      "abstract": [
        {
          "text": "Creates a new function node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "arguments"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLFunctionStitchingNode",
          "text": "MTLFunctionStitchingNode"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "controlDependencies"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLFunctionStitchingFunctionNode",
          "text": "MTLFunctionStitchingFunctionNode"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingFunctionNode/init(name:arguments:controlDependencies:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithName:arguments:controlDependencies:"
        }
      ],
      "role": "symbol",
      "title": "init(name:arguments:controlDependencies:)",
      "type": "topic",
      "url": "/documentation/metal/mtlfunctionstitchingfunctionnode/init(name:arguments:controldependencies:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingFunctionNode/name": {
      "abstract": [
        {
          "text": "The name of the function to call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingFunctionNode/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/metal/mtlfunctionstitchingfunctionnode/name"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingGraph": {
      "abstract": [
        {
          "text": "A description of a new stitched function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFunctionStitchingGraph"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingGraph",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFunctionStitchingGraph"
        }
      ],
      "role": "symbol",
      "title": "MTLFunctionStitchingGraph",
      "type": "topic",
      "url": "/documentation/metal/mtlfunctionstitchinggraph"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingInputNode": {
      "abstract": [
        {
          "text": "A call graph node that describes an input to the call graph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFunctionStitchingInputNode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingInputNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFunctionStitchingInputNode"
        }
      ],
      "role": "symbol",
      "title": "MTLFunctionStitchingInputNode",
      "type": "topic",
      "url": "/documentation/metal/mtlfunctionstitchinginputnode"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingNode": {
      "abstract": [
        {
          "text": "A protocol to identify call graph nodes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFunctionStitchingNode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFunctionStitchingNode"
        }
      ],
      "role": "symbol",
      "title": "MTLFunctionStitchingNode",
      "type": "topic",
      "url": "/documentation/metal/mtlfunctionstitchingnode"
    },
    "doc://com.apple.metal/documentation/Metal/MTLStitchedLibraryDescriptor": {
      "abstract": [
        {
          "text": "A description of a new library of procedurally generated functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLStitchedLibraryDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLStitchedLibraryDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLStitchedLibraryDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLStitchedLibraryDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlstitchedlibrarydescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/customizing-shaders-using-function-pointers-and-stitching": {
      "abstract": [
        {
          "text": "Define custom shader behavior at runtime by creating functions from existing ones and preferentially linking to others in a dynamic library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/customizing-shaders-using-function-pointers-and-stitching",
      "kind": "article",
      "role": "sampleCode",
      "title": "Customizing shaders using function pointers and stitching",
      "type": "topic",
      "url": "/documentation/metal/customizing-shaders-using-function-pointers-and-stitching"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingNode",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Stitched-Function-Libraries",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/customizing-shaders-using-function-pointers-and-stitching",
        "doc://com.apple.metal/documentation/Metal/MTLStitchedLibraryDescriptor",
        "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingGraph",
        "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingInputNode",
        "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingNode",
        "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingAttributeAlwaysInline",
        "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingAttribute"
      ],
      "title": "Stitched Function Libraries"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializing-a-Function-Node",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingFunctionNode/init(name:arguments:controlDependencies:)"
      ],
      "title": "Initializing a Function Node"
    },
    {
      "anchor": "Configuring-a-Function-Node",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingFunctionNode/name",
        "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingFunctionNode/arguments",
        "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingFunctionNode/controlDependencies"
      ],
      "title": "Configuring a Function Node"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLFunctionStitchingFunctionNode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionStitchingFunctionNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionStitchingFunctionNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializing-a-Function-Node",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingFunctionNode/init(name:arguments:controlDependencies:)"
              ],
              "title": "Initializing a Function Node"
            },
            {
              "anchor": "Configuring-a-Function-Node",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingFunctionNode/name",
                "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingFunctionNode/arguments",
                "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingFunctionNode/controlDependencies"
              ],
              "title": "Configuring a Function Node"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingNode"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Stitched-Function-Libraries",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/customizing-shaders-using-function-pointers-and-stitching",
                "doc://com.apple.metal/documentation/Metal/MTLStitchedLibraryDescriptor",
                "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingGraph",
                "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingInputNode",
                "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingNode",
                "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingAttributeAlwaysInline",
                "doc://com.apple.metal/documentation/Metal/MTLFunctionStitchingAttribute"
              ],
              "title": "Stitched Function Libraries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLFunctionStitchingFunctionNode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingGraph/title",
          "value": "MTLFunctionStitchingGraph"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingGraph/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionStitchingGraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingGraph/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionStitchingGraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingFunctionNode~1init(name:arguments:controlDependencies:)/title",
          "value": "initWithName:arguments:controlDependencies:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingFunctionNode~1init(name:arguments:controlDependencies:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithName:arguments:controlDependencies:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStitchedLibraryDescriptor/title",
          "value": "MTLStitchedLibraryDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStitchedLibraryDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStitchedLibraryDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStitchedLibraryDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStitchedLibraryDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingInputNode/title",
          "value": "MTLFunctionStitchingInputNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingInputNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionStitchingInputNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingInputNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionStitchingInputNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingAttribute/title",
          "value": "MTLFunctionStitchingAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionStitchingAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingAttribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionStitchingAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingFunctionNode~1arguments/title",
          "value": "arguments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingFunctionNode~1arguments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "arguments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingFunctionNode/title",
          "value": "MTLFunctionStitchingFunctionNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingFunctionNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionStitchingFunctionNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingFunctionNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionStitchingFunctionNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingFunctionNode~1controlDependencies/title",
          "value": "controlDependencies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingFunctionNode~1controlDependencies/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "controlDependencies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingNode/title",
          "value": "MTLFunctionStitchingNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionStitchingNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionStitchingNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingAttributeAlwaysInline/title",
          "value": "MTLFunctionStitchingAttributeAlwaysInline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingAttributeAlwaysInline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionStitchingAttributeAlwaysInline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingAttributeAlwaysInline/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFunctionStitchingAttributeAlwaysInline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingFunctionNode~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFunctionStitchingFunctionNode~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlfunctionstitchingfunctionnode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlfunctionstitchingfunctionnode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
