{
  "abstract": [
    {
      "text": "Represents the functionality for families of GPUs.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLGPUFamily"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLGPUFamily",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLGPUFamily"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLGPUFamily"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTLGPUFamily"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLGPUFamily"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.metal/documentation/Metal/detecting-gpu-features-and-metal-software-versions"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Check whether a GPU supports the features of a specific family by calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFamily(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method of a GPU’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice": {
      "abstract": [
        {
          "text": "The main Metal interface to a GPU that apps use to draw graphics and run computations in parallel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDevice"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDevice"
        }
      ],
      "role": "symbol",
      "title": "MTLDevice",
      "type": "topic",
      "url": "/documentation/metal/mtldevice"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFamily(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the GPU device supports the feature set of a specific GPU family.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsFamily"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLGPUFamily",
          "text": "MTLGPUFamily"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFamily(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsFamily:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "supportsFamily(_:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/supportsfamily(_:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFeatureSet(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the GPU device supports a specific feature set.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsFeatureSet"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLFeatureSet",
          "text": "MTLFeatureSet"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFeatureSet(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsFeatureSet:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "supportsFeatureSet(_:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/supportsfeatureset(_:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet": {
      "abstract": [
        {
          "text": "The device feature sets that define specific platform, hardware, and software configurations.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFeatureSet"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset"
    },
    "doc://com.apple.metal/documentation/Metal/MTLGPUFamily": {
      "abstract": [
        {
          "text": "Represents the functionality for families of GPUs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLGPUFamily"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLGPUFamily",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLGPUFamily"
        }
      ],
      "role": "symbol",
      "title": "MTLGPUFamily",
      "type": "topic",
      "url": "/documentation/metal/mtlgpufamily"
    },
    "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple1": {
      "abstract": [
        {
          "text": "Represents the Apple family 1 GPU features that correspond to the Apple A7 GPUs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apple1"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLGPUFamilyApple1"
        }
      ],
      "role": "symbol",
      "title": "MTLGPUFamily.apple1",
      "type": "topic",
      "url": "/documentation/metal/mtlgpufamily/apple1"
    },
    "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple2": {
      "abstract": [
        {
          "text": "Represents the Apple family 2 GPU features that correspond to the Apple A8 GPUs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apple2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLGPUFamilyApple2"
        }
      ],
      "role": "symbol",
      "title": "MTLGPUFamily.apple2",
      "type": "topic",
      "url": "/documentation/metal/mtlgpufamily/apple2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple3": {
      "abstract": [
        {
          "text": "Represents the Apple family 3 GPU features that correspond to the Apple A9 and A10 GPUs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apple3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLGPUFamilyApple3"
        }
      ],
      "role": "symbol",
      "title": "MTLGPUFamily.apple3",
      "type": "topic",
      "url": "/documentation/metal/mtlgpufamily/apple3"
    },
    "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple4": {
      "abstract": [
        {
          "text": "Represents the Apple family 4 GPU features that correspond to the Apple A11 GPUs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apple4"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLGPUFamilyApple4"
        }
      ],
      "role": "symbol",
      "title": "MTLGPUFamily.apple4",
      "type": "topic",
      "url": "/documentation/metal/mtlgpufamily/apple4"
    },
    "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple5": {
      "abstract": [
        {
          "text": "Represents the Apple family 5 GPU features that correspond to the Apple A12 GPUs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apple5"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLGPUFamilyApple5"
        }
      ],
      "role": "symbol",
      "title": "MTLGPUFamily.apple5",
      "type": "topic",
      "url": "/documentation/metal/mtlgpufamily/apple5"
    },
    "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple6": {
      "abstract": [
        {
          "text": "Represents the Apple family 6 GPU features that correspond to the Apple A13 GPUs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apple6"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLGPUFamilyApple6"
        }
      ],
      "role": "symbol",
      "title": "MTLGPUFamily.apple6",
      "type": "topic",
      "url": "/documentation/metal/mtlgpufamily/apple6"
    },
    "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple7": {
      "abstract": [
        {
          "text": "Represents the Apple family 7 GPU features that correspond to the Apple A14 and M1 GPUs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apple7"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLGPUFamilyApple7"
        }
      ],
      "role": "symbol",
      "title": "MTLGPUFamily.apple7",
      "type": "topic",
      "url": "/documentation/metal/mtlgpufamily/apple7"
    },
    "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple8": {
      "abstract": [
        {
          "text": "Represents the Apple family 8 GPU features that correspond to the Apple A15, A16, and M2 GPUs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apple8"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLGPUFamilyApple8"
        }
      ],
      "role": "symbol",
      "title": "MTLGPUFamily.apple8",
      "type": "topic",
      "url": "/documentation/metal/mtlgpufamily/apple8"
    },
    "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple9": {
      "abstract": [
        {
          "text": "Represents the Apple family 9 GPU features that correspond to the Apple A17, M3, and M4 GPUs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apple9"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLGPUFamilyApple9"
        }
      ],
      "role": "symbol",
      "title": "MTLGPUFamily.apple9",
      "type": "topic",
      "url": "/documentation/metal/mtlgpufamily/apple9"
    },
    "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/common1": {
      "abstract": [
        {
          "text": "Represents the Common family 1 GPU features.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "common1"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/common1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLGPUFamilyCommon1"
        }
      ],
      "role": "symbol",
      "title": "MTLGPUFamily.common1",
      "type": "topic",
      "url": "/documentation/metal/mtlgpufamily/common1"
    },
    "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/common2": {
      "abstract": [
        {
          "text": "Represents the Common family 2 GPU features.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "common2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/common2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLGPUFamilyCommon2"
        }
      ],
      "role": "symbol",
      "title": "MTLGPUFamily.common2",
      "type": "topic",
      "url": "/documentation/metal/mtlgpufamily/common2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/common3": {
      "abstract": [
        {
          "text": "Represents the Common family 3 GPU features.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "common3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/common3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLGPUFamilyCommon3"
        }
      ],
      "role": "symbol",
      "title": "MTLGPUFamily.common3",
      "type": "topic",
      "url": "/documentation/metal/mtlgpufamily/common3"
    },
    "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/metal/mtlgpufamily/init(rawvalue:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/mac1": {
      "abstract": [
        {
          "text": "Represents the Mac family 1 GPU features.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mac1"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/mac1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLGPUFamilyMac1"
        }
      ],
      "role": "symbol",
      "title": "MTLGPUFamily.mac1",
      "type": "topic",
      "url": "/documentation/metal/mtlgpufamily/mac1"
    },
    "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/mac2": {
      "abstract": [
        {
          "text": "Represents the Mac family 2 GPU features.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mac2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/mac2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLGPUFamilyMac2"
        }
      ],
      "role": "symbol",
      "title": "MTLGPUFamily.mac2",
      "type": "topic",
      "url": "/documentation/metal/mtlgpufamily/mac2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/macCatalyst1": {
      "abstract": [
        {
          "text": "Represents a family 1 Mac GPU when running an app you built with Mac Catalyst.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macCatalyst1"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/macCatalyst1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLGPUFamilyMacCatalyst1"
        }
      ],
      "role": "symbol",
      "title": "MTLGPUFamily.macCatalyst1",
      "type": "topic",
      "url": "/documentation/metal/mtlgpufamily/maccatalyst1"
    },
    "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/macCatalyst2": {
      "abstract": [
        {
          "text": "Represents a family 2 Mac GPU when running an app you built with Mac Catalyst.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macCatalyst2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/macCatalyst2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLGPUFamilyMacCatalyst2"
        }
      ],
      "role": "symbol",
      "title": "MTLGPUFamily.macCatalyst2",
      "type": "topic",
      "url": "/documentation/metal/mtlgpufamily/maccatalyst2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/metal3": {
      "abstract": [
        {
          "text": "Represents the Metal 3 features.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metal3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/metal3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLGPUFamilyMetal3"
        }
      ],
      "role": "symbol",
      "title": "MTLGPUFamily.metal3",
      "type": "topic",
      "url": "/documentation/metal/mtlgpufamily/metal3"
    },
    "doc://com.apple.metal/documentation/Metal/detecting-gpu-features-and-metal-software-versions": {
      "abstract": [
        {
          "text": "Use the device object’s properties to determine how you perform tasks in Metal.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/detecting-gpu-features-and-metal-software-versions",
      "kind": "article",
      "role": "article",
      "title": "Detecting GPU Features and Metal Software Versions",
      "type": "topic",
      "url": "/documentation/metal/detecting-gpu-features-and-metal-software-versions"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Checking-a-GPU-Devices-Feature-Support",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFamily(_:)",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFeatureSet(_:)",
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet"
      ],
      "title": "Checking a GPU Device’s Feature Support"
    }
  ],
  "topicSections": [
    {
      "anchor": "Checking-for-Common-GPU-Support",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/metal3",
        "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/common3",
        "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/common2",
        "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/common1"
      ],
      "title": "Checking for Common GPU Support"
    },
    {
      "anchor": "Checking-for-Apple-Family-GPU-Support",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple9",
        "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple8",
        "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple7",
        "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple6",
        "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple5",
        "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple4",
        "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple3",
        "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple2",
        "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple1"
      ],
      "title": "Checking for Apple Family GPU Support"
    },
    {
      "anchor": "Checking-for-macOS-Family-GPU-Support",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/mac2",
        "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/mac1"
      ],
      "title": "Checking for macOS Family GPU Support"
    },
    {
      "anchor": "Checking-for-Mac-Catalyst-Family-GPU-Support",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/macCatalyst2",
        "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/macCatalyst1"
      ],
      "title": "Checking for Mac Catalyst Family GPU Support"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLGPUFamily"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLGPUFamily"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLGPUFamily"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Checking-for-Common-GPU-Support",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/metal3",
                "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/common3",
                "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/common2",
                "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/common1"
              ],
              "title": "Checking for Common GPU Support"
            },
            {
              "anchor": "Checking-for-Apple-Family-GPU-Support",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple9",
                "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple8",
                "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple7",
                "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple6",
                "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple5",
                "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple4",
                "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple3",
                "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple2",
                "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/apple1"
              ],
              "title": "Checking for Apple Family GPU Support"
            },
            {
              "anchor": "Checking-for-macOS-Family-GPU-Support",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/mac2",
                "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/mac1"
              ],
              "title": "Checking for macOS Family GPU Support"
            },
            {
              "anchor": "Checking-for-Mac-Catalyst-Family-GPU-Support",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/macCatalyst2",
                "doc://com.apple.metal/documentation/Metal/MTLGPUFamily/macCatalyst1"
              ],
              "title": "Checking for Mac Catalyst Family GPU Support"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Checking-a-GPU-Devices-Feature-Support",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFamily(_:)",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsFeatureSet(_:)",
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet"
              ],
              "title": "Checking a GPU Device’s Feature Support"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLGPUFamily"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsFamily(_:)/title",
          "value": "supportsFamily:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsFamily(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "supportsFamily:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1apple8/title",
          "value": "MTLGPUFamilyApple8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1apple8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLGPUFamilyApple8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1apple9/title",
          "value": "MTLGPUFamilyApple9"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1apple9/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLGPUFamilyApple9"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1apple7/title",
          "value": "MTLGPUFamilyApple7"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1apple7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLGPUFamilyApple7"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1apple6/title",
          "value": "MTLGPUFamilyApple6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1apple6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLGPUFamilyApple6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsFeatureSet(_:)/title",
          "value": "supportsFeatureSet:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsFeatureSet(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "supportsFeatureSet:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet/title",
          "value": "MTLFeatureSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1mac2/title",
          "value": "MTLGPUFamilyMac2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1mac2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLGPUFamilyMac2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1apple5/title",
          "value": "MTLGPUFamilyApple5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1apple5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLGPUFamilyApple5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/title",
          "value": "MTLDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1apple4/title",
          "value": "MTLGPUFamilyApple4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1apple4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLGPUFamilyApple4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1macCatalyst2/title",
          "value": "MTLGPUFamilyMacCatalyst2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1macCatalyst2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLGPUFamilyMacCatalyst2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1apple2/title",
          "value": "MTLGPUFamilyApple2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1apple2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLGPUFamilyApple2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1common1/title",
          "value": "MTLGPUFamilyCommon1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1common1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLGPUFamilyCommon1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1common2/title",
          "value": "MTLGPUFamilyCommon2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1common2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLGPUFamilyCommon2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1apple1/title",
          "value": "MTLGPUFamilyApple1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1apple1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLGPUFamilyApple1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1macCatalyst1/title",
          "value": "MTLGPUFamilyMacCatalyst1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1macCatalyst1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLGPUFamilyMacCatalyst1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1apple3/title",
          "value": "MTLGPUFamilyApple3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1apple3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLGPUFamilyApple3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1mac1/title",
          "value": "MTLGPUFamilyMac1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1mac1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLGPUFamilyMac1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1metal3/title",
          "value": "MTLGPUFamilyMetal3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1metal3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLGPUFamilyMetal3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1common3/title",
          "value": "MTLGPUFamilyCommon3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily~1common3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLGPUFamilyCommon3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily/title",
          "value": "MTLGPUFamily"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLGPUFamily"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLGPUFamily/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLGPUFamily"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlgpufamily"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlgpufamily"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
