{
  "abstract": [
    {
      "text": "A memory pool from which you can suballocate resources.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLHeap"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MTLHeap",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLHeap"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLHeap"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "MTLHeap"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLHeap"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLAllocation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)MTLAllocation",
              "text": "MTLAllocation"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.metal/documentation/Metal/simplifying-gpu-resource-management-with-residency-sets",
        "doc://com.apple.metal/documentation/Metal/reducing-the-memory-footprint-of-metal-apps",
        "doc://com.apple.metal/documentation/Metal/improving-cpu-performance-by-using-argument-buffers",
        "doc://com.apple.metal/documentation/Metal/creating-sparse-heaps-and-sparse-textures"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Don’t implement this protocol yourself; instead, to create a heap, configure a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLHeapDescriptor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object and call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/makeHeap(descriptor:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method of a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You suballocate resources from a heap and make them ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "aliasable",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "non-aliasable",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ". A sub-allocated resource is non-aliased by default, preventing future resources allocated from the heap from using its memory. Resources are ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "aliased",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " when they share the same memory allocation on a heap.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "All resources sub-allocated from the same heap share the same storage mode and CPU cache mode. You can make heaps purgeable, but not the resources allocated from the heap; they can only reflect the heap’s purgeability state.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAllocation": {
      "abstract": [
        {
          "text": "A memory allocation from a Metal GPU device, such as a memory heap, texture, or data buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAllocation"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAllocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAllocation"
        }
      ],
      "role": "symbol",
      "title": "MTLAllocation",
      "type": "topic",
      "url": "/documentation/metal/mtlallocation"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice": {
      "abstract": [
        {
          "text": "The main Metal interface to a GPU that apps use to draw graphics and run computations in parallel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDevice"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDevice"
        }
      ],
      "role": "symbol",
      "title": "MTLDevice",
      "type": "topic",
      "url": "/documentation/metal/mtldevice"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/makeHeap(descriptor:)": {
      "abstract": [
        {
          "text": "Creates a new GPU heap instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeHeap"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLHeapDescriptor",
          "text": "MTLHeapDescriptor"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLHeap",
          "text": "MTLHeap"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/makeHeap(descriptor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newHeapWithDescriptor:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeHeap(descriptor:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/makeheap(descriptor:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLHeap": {
      "abstract": [
        {
          "text": "A memory pool from which you can suballocate resources.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLHeap"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLHeap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLHeap"
        }
      ],
      "role": "symbol",
      "title": "MTLHeap",
      "type": "topic",
      "url": "/documentation/metal/mtlheap"
    },
    "doc://com.apple.metal/documentation/Metal/MTLHeap/cpuCacheMode": {
      "abstract": [
        {
          "text": "The heap’s CPU cache mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cpuCacheMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLCPUCacheMode",
          "text": "MTLCPUCacheMode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLHeap/cpuCacheMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cpuCacheMode"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "cpuCacheMode",
      "type": "topic",
      "url": "/documentation/metal/mtlheap/cpucachemode"
    },
    "doc://com.apple.metal/documentation/Metal/MTLHeap/currentAllocatedSize": {
      "abstract": [
        {
          "text": "The size, in bytes, of the current heap allocation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentAllocatedSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLHeap/currentAllocatedSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentAllocatedSize"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "currentAllocatedSize",
      "type": "topic",
      "url": "/documentation/metal/mtlheap/currentallocatedsize"
    },
    "doc://com.apple.metal/documentation/Metal/MTLHeap/device": {
      "abstract": [
        {
          "text": "The device object that created the heap.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "device"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDevice",
          "text": "MTLDevice"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLHeap/device",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "device"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "device",
      "type": "topic",
      "url": "/documentation/metal/mtlheap/device"
    },
    "doc://com.apple.metal/documentation/Metal/MTLHeap/hazardTrackingMode": {
      "abstract": [
        {
          "text": "The heap’s hazard tracking mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hazardTrackingMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLHazardTrackingMode",
          "text": "MTLHazardTrackingMode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLHeap/hazardTrackingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hazardTrackingMode"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "hazardTrackingMode",
      "type": "topic",
      "url": "/documentation/metal/mtlheap/hazardtrackingmode"
    },
    "doc://com.apple.metal/documentation/Metal/MTLHeap/label": {
      "abstract": [
        {
          "text": "A string that identifies the heap.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "label"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLHeap/label",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "label"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "label",
      "type": "topic",
      "url": "/documentation/metal/mtlheap/label"
    },
    "doc://com.apple.metal/documentation/Metal/MTLHeap/makeAccelerationStructure(descriptor:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeAccelerationStructure"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLAccelerationStructureDescriptor",
          "text": "MTLAccelerationStructureDescriptor"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLAccelerationStructure",
          "text": "MTLAccelerationStructure"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLHeap/makeAccelerationStructure(descriptor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newAccelerationStructureWithDescriptor:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeAccelerationStructure(descriptor:)",
      "type": "topic",
      "url": "/documentation/metal/mtlheap/makeaccelerationstructure(descriptor:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLHeap/makeAccelerationStructure(descriptor:offset:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeAccelerationStructure"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLAccelerationStructureDescriptor",
          "text": "MTLAccelerationStructureDescriptor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "offset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLAccelerationStructure",
          "text": "MTLAccelerationStructure"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLHeap/makeAccelerationStructure(descriptor:offset:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newAccelerationStructureWithDescriptor:offset:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeAccelerationStructure(descriptor:offset:)",
      "type": "topic",
      "url": "/documentation/metal/mtlheap/makeaccelerationstructure(descriptor:offset:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLHeap/makeAccelerationStructure(size:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeAccelerationStructure"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLAccelerationStructure",
          "text": "MTLAccelerationStructure"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLHeap/makeAccelerationStructure(size:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newAccelerationStructureWithSize:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeAccelerationStructure(size:)",
      "type": "topic",
      "url": "/documentation/metal/mtlheap/makeaccelerationstructure(size:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLHeap/makeAccelerationStructure(size:offset:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeAccelerationStructure"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "offset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLAccelerationStructure",
          "text": "MTLAccelerationStructure"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLHeap/makeAccelerationStructure(size:offset:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newAccelerationStructureWithSize:offset:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeAccelerationStructure(size:offset:)",
      "type": "topic",
      "url": "/documentation/metal/mtlheap/makeaccelerationstructure(size:offset:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLHeap/makeBuffer(length:options:)": {
      "abstract": [
        {
          "text": "Creates a buffer on the heap.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeBuffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "length"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLResourceOptions",
          "text": "MTLResourceOptions"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLBuffer",
          "text": "MTLBuffer"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLHeap/makeBuffer(length:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newBufferWithLength:options:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeBuffer(length:options:)",
      "type": "topic",
      "url": "/documentation/metal/mtlheap/makebuffer(length:options:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLHeap/makeBuffer(length:options:offset:)": {
      "abstract": [
        {
          "text": "Creates a buffer at a specified offset on the heap.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeBuffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "length"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLResourceOptions",
          "text": "MTLResourceOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "offset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLBuffer",
          "text": "MTLBuffer"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLHeap/makeBuffer(length:options:offset:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newBufferWithLength:options:offset:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeBuffer(length:options:offset:)",
      "type": "topic",
      "url": "/documentation/metal/mtlheap/makebuffer(length:options:offset:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLHeap/makeTexture(descriptor:)": {
      "abstract": [
        {
          "text": "Creates a texture on the heap.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeTexture"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLTextureDescriptor",
          "text": "MTLTextureDescriptor"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLHeap/makeTexture(descriptor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newTextureWithDescriptor:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeTexture(descriptor:)",
      "type": "topic",
      "url": "/documentation/metal/mtlheap/maketexture(descriptor:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLHeap/makeTexture(descriptor:offset:)": {
      "abstract": [
        {
          "text": "Creates a texture at a specified offset on the heap.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeTexture"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLTextureDescriptor",
          "text": "MTLTextureDescriptor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "offset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLHeap/makeTexture(descriptor:offset:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newTextureWithDescriptor:offset:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeTexture(descriptor:offset:)",
      "type": "topic",
      "url": "/documentation/metal/mtlheap/maketexture(descriptor:offset:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLHeap/maxAvailableSize(alignment:)": {
      "abstract": [
        {
          "text": "The maximum size of a resource, in bytes, that can be currently allocated from the heap.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxAvailableSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "alignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLHeap/maxAvailableSize(alignment:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxAvailableSizeWithAlignment:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "maxAvailableSize(alignment:)",
      "type": "topic",
      "url": "/documentation/metal/mtlheap/maxavailablesize(alignment:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLHeap/resourceOptions": {
      "abstract": [
        {
          "text": "The options for resources created by the heap.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resourceOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLResourceOptions",
          "text": "MTLResourceOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLHeap/resourceOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resourceOptions"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "resourceOptions",
      "type": "topic",
      "url": "/documentation/metal/mtlheap/resourceoptions"
    },
    "doc://com.apple.metal/documentation/Metal/MTLHeap/setPurgeableState(_:)": {
      "abstract": [
        {
          "text": "Sets the purgeable state of the heap.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setPurgeableState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLPurgeableState",
          "text": "MTLPurgeableState"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLPurgeableState",
          "text": "MTLPurgeableState"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLHeap/setPurgeableState(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPurgeableState:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setPurgeableState(_:)",
      "type": "topic",
      "url": "/documentation/metal/mtlheap/setpurgeablestate(_:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLHeap/size": {
      "abstract": [
        {
          "text": "The total size of the heap, in bytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLHeap/size",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "size"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "size",
      "type": "topic",
      "url": "/documentation/metal/mtlheap/size"
    },
    "doc://com.apple.metal/documentation/Metal/MTLHeap/storageMode": {
      "abstract": [
        {
          "text": "The heap’s storage mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "storageMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLStorageMode",
          "text": "MTLStorageMode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLHeap/storageMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "storageMode"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "storageMode",
      "type": "topic",
      "url": "/documentation/metal/mtlheap/storagemode"
    },
    "doc://com.apple.metal/documentation/Metal/MTLHeap/type": {
      "abstract": [
        {
          "text": "The heap’s type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLHeapType",
          "text": "MTLHeapType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLHeap/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/metal/mtlheap/type"
    },
    "doc://com.apple.metal/documentation/Metal/MTLHeap/usedSize": {
      "abstract": [
        {
          "text": "The size of all resources currently in the heap, in bytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usedSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLHeap/usedSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "usedSize"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "usedSize",
      "type": "topic",
      "url": "/documentation/metal/mtlheap/usedsize"
    },
    "doc://com.apple.metal/documentation/Metal/MTLHeapDescriptor": {
      "abstract": [
        {
          "text": "A configuration that customizes the behavior for a Metal memory heap.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLHeapDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLHeapDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLHeapDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLHeapDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlheapdescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLHeapType": {
      "abstract": [
        {
          "text": "The options you use to choose the heap type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLHeapType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLHeapType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLHeapType"
        }
      ],
      "role": "symbol",
      "title": "MTLHeapType",
      "type": "topic",
      "url": "/documentation/metal/mtlheaptype"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSizeAndAlign": {
      "abstract": [
        {
          "text": "The size and alignment of a resource, in bytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLSizeAndAlign"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSizeAndAlign",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSizeAndAlign"
        }
      ],
      "role": "symbol",
      "title": "MTLSizeAndAlign",
      "type": "topic",
      "url": "/documentation/metal/mtlsizeandalign"
    },
    "doc://com.apple.metal/documentation/Metal/creating-sparse-heaps-and-sparse-textures": {
      "abstract": [
        {
          "text": "Allocate memory for sparse textures by creating a sparse heap.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/creating-sparse-heaps-and-sparse-textures",
      "kind": "article",
      "role": "article",
      "title": "Creating Sparse Heaps and Sparse Textures",
      "type": "topic",
      "url": "/documentation/metal/creating-sparse-heaps-and-sparse-textures"
    },
    "doc://com.apple.metal/documentation/Metal/implementing-a-multistage-image-filter-using-heaps-and-events": {
      "abstract": [
        {
          "text": "Use events to synchronize access to resources allocated on a heap.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/implementing-a-multistage-image-filter-using-heaps-and-events",
      "kind": "article",
      "role": "sampleCode",
      "title": "Implementing a Multistage Image Filter Using Heaps and Events",
      "type": "topic",
      "url": "/documentation/metal/implementing-a-multistage-image-filter-using-heaps-and-events"
    },
    "doc://com.apple.metal/documentation/Metal/implementing-a-multistage-image-filter-using-heaps-and-fences": {
      "abstract": [
        {
          "text": "Use fences to synchronize access to resources allocated on a heap.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/implementing-a-multistage-image-filter-using-heaps-and-fences",
      "kind": "article",
      "role": "sampleCode",
      "title": "Implementing a Multistage Image Filter Using Heaps and Fences",
      "type": "topic",
      "url": "/documentation/metal/implementing-a-multistage-image-filter-using-heaps-and-fences"
    },
    "doc://com.apple.metal/documentation/Metal/improving-cpu-performance-by-using-argument-buffers": {
      "abstract": [
        {
          "text": "Optimize your app’s performance by grouping your resources into argument buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/improving-cpu-performance-by-using-argument-buffers",
      "kind": "article",
      "role": "article",
      "title": "Improving CPU Performance by Using Argument Buffers",
      "type": "topic",
      "url": "/documentation/metal/improving-cpu-performance-by-using-argument-buffers"
    },
    "doc://com.apple.metal/documentation/Metal/reducing-the-memory-footprint-of-metal-apps": {
      "abstract": [
        {
          "text": "Learn best practices for using memory efficiently in iOS and tvOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/reducing-the-memory-footprint-of-metal-apps",
      "kind": "article",
      "role": "article",
      "title": "Reducing the Memory Footprint of Metal Apps",
      "type": "topic",
      "url": "/documentation/metal/reducing-the-memory-footprint-of-metal-apps"
    },
    "doc://com.apple.metal/documentation/Metal/simplifying-gpu-resource-management-with-residency-sets": {
      "abstract": [
        {
          "text": "Organize your resources into groups and influence when they become accessible to the GPU.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/simplifying-gpu-resource-management-with-residency-sets",
      "kind": "article",
      "role": "article",
      "title": "Simplifying GPU Resource Management with Residency Sets",
      "type": "topic",
      "url": "/documentation/metal/simplifying-gpu-resource-management-with-residency-sets"
    },
    "doc://com.apple.metal/documentation/Metal/using-argument-buffers-with-resource-heaps": {
      "abstract": [
        {
          "text": "Reduce CPU overhead by using arrays inside argument buffers and combining them with resource heaps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/using-argument-buffers-with-resource-heaps",
      "kind": "article",
      "role": "sampleCode",
      "title": "Using Argument Buffers with Resource Heaps",
      "type": "topic",
      "url": "/documentation/metal/using-argument-buffers-with-resource-heaps"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLAllocation",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Resource-Memory-Allocation-and-Management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/using-argument-buffers-with-resource-heaps",
        "doc://com.apple.metal/documentation/Metal/implementing-a-multistage-image-filter-using-heaps-and-events",
        "doc://com.apple.metal/documentation/Metal/implementing-a-multistage-image-filter-using-heaps-and-fences",
        "doc://com.apple.metal/documentation/Metal/MTLHeapDescriptor",
        "doc://com.apple.metal/documentation/Metal/MTLHeapType",
        "doc://com.apple.metal/documentation/Metal/MTLSizeAndAlign"
      ],
      "title": "Resource Memory Allocation and Management"
    }
  ],
  "topicSections": [
    {
      "anchor": "Identifying-the-Heap",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLHeap/device",
        "doc://com.apple.metal/documentation/Metal/MTLHeap/label"
      ],
      "title": "Identifying the Heap"
    },
    {
      "anchor": "Querying-Heap-Properties",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLHeap/type",
        "doc://com.apple.metal/documentation/Metal/MTLHeap/storageMode",
        "doc://com.apple.metal/documentation/Metal/MTLHeap/cpuCacheMode",
        "doc://com.apple.metal/documentation/Metal/MTLHeap/hazardTrackingMode",
        "doc://com.apple.metal/documentation/Metal/MTLHeap/resourceOptions",
        "doc://com.apple.metal/documentation/Metal/MTLHeap/size",
        "doc://com.apple.metal/documentation/Metal/MTLHeap/usedSize",
        "doc://com.apple.metal/documentation/Metal/MTLHeap/currentAllocatedSize",
        "doc://com.apple.metal/documentation/Metal/MTLHeap/maxAvailableSize(alignment:)",
        "doc://com.apple.metal/documentation/Metal/MTLHeapType"
      ],
      "title": "Querying Heap Properties"
    },
    {
      "anchor": "Setting-the-Purgeable-State-of-the-Resource",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLHeap/setPurgeableState(_:)"
      ],
      "title": "Setting the Purgeable State of the Resource"
    },
    {
      "anchor": "Creating-Resources-on-the-Heap",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLHeap/makeBuffer(length:options:)",
        "doc://com.apple.metal/documentation/Metal/MTLHeap/makeTexture(descriptor:)",
        "doc://com.apple.metal/documentation/Metal/MTLHeap/makeBuffer(length:options:offset:)",
        "doc://com.apple.metal/documentation/Metal/MTLHeap/makeTexture(descriptor:offset:)"
      ],
      "title": "Creating Resources on the Heap"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLHeap/makeAccelerationStructure(descriptor:)",
        "doc://com.apple.metal/documentation/Metal/MTLHeap/makeAccelerationStructure(descriptor:offset:)",
        "doc://com.apple.metal/documentation/Metal/MTLHeap/makeAccelerationStructure(size:)",
        "doc://com.apple.metal/documentation/Metal/MTLHeap/makeAccelerationStructure(size:offset:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLHeap"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLHeap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLHeap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Identifying-the-Heap",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLHeap/device",
                "doc://com.apple.metal/documentation/Metal/MTLHeap/label"
              ],
              "title": "Identifying the Heap"
            },
            {
              "anchor": "Querying-Heap-Properties",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLHeap/type",
                "doc://com.apple.metal/documentation/Metal/MTLHeap/storageMode",
                "doc://com.apple.metal/documentation/Metal/MTLHeap/cpuCacheMode",
                "doc://com.apple.metal/documentation/Metal/MTLHeap/hazardTrackingMode",
                "doc://com.apple.metal/documentation/Metal/MTLHeap/resourceOptions",
                "doc://com.apple.metal/documentation/Metal/MTLHeap/size",
                "doc://com.apple.metal/documentation/Metal/MTLHeap/usedSize",
                "doc://com.apple.metal/documentation/Metal/MTLHeap/currentAllocatedSize",
                "doc://com.apple.metal/documentation/Metal/MTLHeap/maxAvailableSize(alignment:)",
                "doc://com.apple.metal/documentation/Metal/MTLHeapType"
              ],
              "title": "Querying Heap Properties"
            },
            {
              "anchor": "Setting-the-Purgeable-State-of-the-Resource",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLHeap/setPurgeableState(_:)"
              ],
              "title": "Setting the Purgeable State of the Resource"
            },
            {
              "anchor": "Creating-Resources-on-the-Heap",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLHeap/makeBuffer(length:options:)",
                "doc://com.apple.metal/documentation/Metal/MTLHeap/makeTexture(descriptor:)",
                "doc://com.apple.metal/documentation/Metal/MTLHeap/makeBuffer(length:options:offset:)",
                "doc://com.apple.metal/documentation/Metal/MTLHeap/makeTexture(descriptor:offset:)"
              ],
              "title": "Creating Resources on the Heap"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLHeap/makeAccelerationStructure(descriptor:)",
                "doc://com.apple.metal/documentation/Metal/MTLHeap/makeAccelerationStructure(descriptor:offset:)",
                "doc://com.apple.metal/documentation/Metal/MTLHeap/makeAccelerationStructure(size:)",
                "doc://com.apple.metal/documentation/Metal/MTLHeap/makeAccelerationStructure(size:offset:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLAllocation"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Resource-Memory-Allocation-and-Management",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/using-argument-buffers-with-resource-heaps",
                "doc://com.apple.metal/documentation/Metal/implementing-a-multistage-image-filter-using-heaps-and-events",
                "doc://com.apple.metal/documentation/Metal/implementing-a-multistage-image-filter-using-heaps-and-fences",
                "doc://com.apple.metal/documentation/Metal/MTLHeapDescriptor",
                "doc://com.apple.metal/documentation/Metal/MTLHeapType",
                "doc://com.apple.metal/documentation/Metal/MTLSizeAndAlign"
              ],
              "title": "Resource Memory Allocation and Management"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLHeap"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.apple.metal/documentation/Metal/MTLAllocation",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)MTLAllocation",
                    "text": "MTLAllocation"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1makeAccelerationStructure(size:offset:)/title",
          "value": "newAccelerationStructureWithSize:offset:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1makeAccelerationStructure(size:offset:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newAccelerationStructureWithSize:offset:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAllocation/title",
          "value": "MTLAllocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAllocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAllocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAllocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAllocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1usedSize/title",
          "value": "usedSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1usedSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "usedSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1currentAllocatedSize/title",
          "value": "currentAllocatedSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1currentAllocatedSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentAllocatedSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1setPurgeableState(_:)/title",
          "value": "setPurgeableState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1setPurgeableState(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPurgeableState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1makeAccelerationStructure(descriptor:offset:)/title",
          "value": "newAccelerationStructureWithDescriptor:offset:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1makeAccelerationStructure(descriptor:offset:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newAccelerationStructureWithDescriptor:offset:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/title",
          "value": "MTLDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1size/title",
          "value": "size"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1size/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1makeAccelerationStructure(size:)/title",
          "value": "newAccelerationStructureWithSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1makeAccelerationStructure(size:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newAccelerationStructureWithSize:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1label/title",
          "value": "label"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1label/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "label"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1maxAvailableSize(alignment:)/title",
          "value": "maxAvailableSizeWithAlignment:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1maxAvailableSize(alignment:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "maxAvailableSizeWithAlignment:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1makeAccelerationStructure(descriptor:)/title",
          "value": "newAccelerationStructureWithDescriptor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1makeAccelerationStructure(descriptor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newAccelerationStructureWithDescriptor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1makeBuffer(length:options:)/title",
          "value": "newBufferWithLength:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1makeBuffer(length:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newBufferWithLength:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1makeTexture(descriptor:)/title",
          "value": "newTextureWithDescriptor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1makeTexture(descriptor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newTextureWithDescriptor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1makeTexture(descriptor:offset:)/title",
          "value": "newTextureWithDescriptor:offset:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1makeTexture(descriptor:offset:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newTextureWithDescriptor:offset:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeapType/title",
          "value": "MTLHeapType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeapType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLHeapType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeapType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLHeapType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeHeap(descriptor:)/title",
          "value": "newHeapWithDescriptor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeHeap(descriptor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newHeapWithDescriptor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1storageMode/title",
          "value": "storageMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1storageMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "storageMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap/title",
          "value": "MTLHeap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLHeap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLHeap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1cpuCacheMode/title",
          "value": "cpuCacheMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1cpuCacheMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cpuCacheMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeapDescriptor/title",
          "value": "MTLHeapDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeapDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLHeapDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeapDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLHeapDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSizeAndAlign/title",
          "value": "MTLSizeAndAlign"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSizeAndAlign/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSizeAndAlign"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSizeAndAlign/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSizeAndAlign"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1device/title",
          "value": "device"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1device/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "device"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1makeBuffer(length:options:offset:)/title",
          "value": "newBufferWithLength:options:offset:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1makeBuffer(length:options:offset:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newBufferWithLength:options:offset:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1hazardTrackingMode/title",
          "value": "hazardTrackingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1hazardTrackingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hazardTrackingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1resourceOptions/title",
          "value": "resourceOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap~1resourceOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resourceOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlheap"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlheap"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
