{
  "abstract": [
    {
      "text": "A description of an acceleration structure that derives from instances of primitive acceleration structures.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTLInstanceAccelerationStructureDescriptor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLInstanceAccelerationStructureDescriptor"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLInstanceAccelerationStructureDescriptor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTLInstanceAccelerationStructureDescriptor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLInstanceAccelerationStructureDescriptor"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Metal provides acceleration structures with a two-level hierarchy. The bottom layer consists of primitive acceleration structures, which instance acceleration structures in the top level reference.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructure": {
      "abstract": [
        {
          "text": "A collection of model data for GPU-accelerated intersection of rays with the model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructure"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructure"
        }
      ],
      "role": "symbol",
      "title": "MTLAccelerationStructure",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructure"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureCommandEncoder": {
      "abstract": [
        {
          "text": "An object for encoding commands that build or refit acceleration structures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureCommandEncoder"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureCommandEncoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureCommandEncoder"
        }
      ],
      "role": "symbol",
      "title": "MTLAccelerationStructureCommandEncoder",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructurecommandencoder"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureDescriptor": {
      "abstract": [
        {
          "text": "A base class for classes that define the configuration for a new acceleration structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLAccelerationStructureDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructuredescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceDescriptorType": {
      "abstract": [
        {
          "text": "Options for specifying different kinds of instance types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureInstanceDescriptorType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceDescriptorType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureInstanceDescriptorType"
        }
      ],
      "role": "symbol",
      "title": "MTLAccelerationStructureInstanceDescriptorType",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructureinstancedescriptortype"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureRefitOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureRefitOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureRefitOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureRefitOptions"
        }
      ],
      "role": "symbol",
      "title": "MTLAccelerationStructureRefitOptions",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructurerefitoptions"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureUsage": {
      "abstract": [
        {
          "text": "Options that describe which tasks you can perform on an acceleration structure and how the system performs those tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureUsage"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureUsage"
        }
      ],
      "role": "symbol",
      "title": "MTLAccelerationStructureUsage",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructureusage"
    },
    "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor": {
      "abstract": [
        {
          "text": "A description of an acceleration structure that derives from instances of primitive acceleration structures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLInstanceAccelerationStructureDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLInstanceAccelerationStructureDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLInstanceAccelerationStructureDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlinstanceaccelerationstructuredescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/descriptor": {
      "abstract": [
        {
          "text": "Creates an instance descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "descriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/descriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptor"
        }
      ],
      "role": "symbol",
      "title": "descriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlinstanceaccelerationstructuredescriptor/descriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/instanceCount": {
      "abstract": [
        {
          "text": "The number of instances in the instance descriptor buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instanceCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/instanceCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "instanceCount"
        }
      ],
      "role": "symbol",
      "title": "instanceCount",
      "type": "topic",
      "url": "/documentation/metal/mtlinstanceaccelerationstructuredescriptor/instancecount"
    },
    "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/instanceDescriptorBuffer": {
      "abstract": [
        {
          "text": "A buffer that contains descriptions of each instance in the acceleration structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instanceDescriptorBuffer"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLBuffer",
          "text": "MTLBuffer"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/instanceDescriptorBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "instanceDescriptorBuffer"
        }
      ],
      "role": "symbol",
      "title": "instanceDescriptorBuffer",
      "type": "topic",
      "url": "/documentation/metal/mtlinstanceaccelerationstructuredescriptor/instancedescriptorbuffer"
    },
    "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/instanceDescriptorBufferOffset": {
      "abstract": [
        {
          "text": "The offset, in bytes, to the descripton of the first instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instanceDescriptorBufferOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/instanceDescriptorBufferOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "instanceDescriptorBufferOffset"
        }
      ],
      "role": "symbol",
      "title": "instanceDescriptorBufferOffset",
      "type": "topic",
      "url": "/documentation/metal/mtlinstanceaccelerationstructuredescriptor/instancedescriptorbufferoffset"
    },
    "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/instanceDescriptorStride": {
      "abstract": [
        {
          "text": "The stride, in bytes, between instance descriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instanceDescriptorStride"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/instanceDescriptorStride",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "instanceDescriptorStride"
        }
      ],
      "role": "symbol",
      "title": "instanceDescriptorStride",
      "type": "topic",
      "url": "/documentation/metal/mtlinstanceaccelerationstructuredescriptor/instancedescriptorstride"
    },
    "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/instanceDescriptorType": {
      "abstract": [
        {
          "text": "The format of the instance data in the descriptor buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instanceDescriptorType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLAccelerationStructureInstanceDescriptorType",
          "text": "MTLAccelerationStructureInstanceDescriptorType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/instanceDescriptorType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "instanceDescriptorType"
        }
      ],
      "role": "symbol",
      "title": "instanceDescriptorType",
      "type": "topic",
      "url": "/documentation/metal/mtlinstanceaccelerationstructuredescriptor/instancedescriptortype"
    },
    "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/instanceTransformationMatrixLayout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instanceTransformationMatrixLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLMatrixLayout",
          "text": "MTLMatrixLayout"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/instanceTransformationMatrixLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "instanceTransformationMatrixLayout"
        }
      ],
      "role": "symbol",
      "title": "instanceTransformationMatrixLayout",
      "type": "topic",
      "url": "/documentation/metal/mtlinstanceaccelerationstructuredescriptor/instancetransformationmatrixlayout"
    },
    "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/instancedAccelerationStructures": {
      "abstract": [
        {
          "text": "The bottom-level acceleration structures that instances use in the instance acceleration structure .",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instancedAccelerationStructures"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLAccelerationStructure",
          "text": "MTLAccelerationStructure"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/instancedAccelerationStructures",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "instancedAccelerationStructures"
        }
      ],
      "role": "symbol",
      "title": "instancedAccelerationStructures",
      "type": "topic",
      "url": "/documentation/metal/mtlinstanceaccelerationstructuredescriptor/instancedaccelerationstructures"
    },
    "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/motionTransformBuffer": {
      "abstract": [
        {
          "text": "A buffer that contains descriptions of each motion transform in the acceleration structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "motionTransformBuffer"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLBuffer",
          "text": "MTLBuffer"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/motionTransformBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "motionTransformBuffer"
        }
      ],
      "role": "symbol",
      "title": "motionTransformBuffer",
      "type": "topic",
      "url": "/documentation/metal/mtlinstanceaccelerationstructuredescriptor/motiontransformbuffer"
    },
    "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/motionTransformBufferOffset": {
      "abstract": [
        {
          "text": "The offset, in bytes, to the descripton of the first motion transform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "motionTransformBufferOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/motionTransformBufferOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "motionTransformBufferOffset"
        }
      ],
      "role": "symbol",
      "title": "motionTransformBufferOffset",
      "type": "topic",
      "url": "/documentation/metal/mtlinstanceaccelerationstructuredescriptor/motiontransformbufferoffset"
    },
    "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/motionTransformCount": {
      "abstract": [
        {
          "text": "The number of motion transforms in the motion transform buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "motionTransformCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/motionTransformCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "motionTransformCount"
        }
      ],
      "role": "symbol",
      "title": "motionTransformCount",
      "type": "topic",
      "url": "/documentation/metal/mtlinstanceaccelerationstructuredescriptor/motiontransformcount"
    },
    "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/motionTransformStride": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "motionTransformStride"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/motionTransformStride",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "motionTransformStride"
        }
      ],
      "role": "symbol",
      "title": "motionTransformStride",
      "type": "topic",
      "url": "/documentation/metal/mtlinstanceaccelerationstructuredescriptor/motiontransformstride"
    },
    "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/motionTransformType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "motionTransformType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTransformType",
          "text": "MTLTransformType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/motionTransformType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "motionTransformType"
        }
      ],
      "role": "symbol",
      "title": "motionTransformType",
      "type": "topic",
      "url": "/documentation/metal/mtlinstanceaccelerationstructuredescriptor/motiontransformtype"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPrimitiveAccelerationStructureDescriptor": {
      "abstract": [
        {
          "text": "A description of an acceleration structure that contains geometry primitives.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLPrimitiveAccelerationStructureDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPrimitiveAccelerationStructureDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPrimitiveAccelerationStructureDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLPrimitiveAccelerationStructureDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlprimitiveaccelerationstructuredescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/improving-ray-tracing-data-access-using-per-primitive-data": {
      "abstract": [
        {
          "text": "Simplify data access and improve GPU utilization by storing custom primitive data directly in the acceleration structure.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/improving-ray-tracing-data-access-using-per-primitive-data",
      "kind": "article",
      "role": "article",
      "title": "Improving Ray-Tracing Data Access Using Per-Primitive Data",
      "type": "topic",
      "url": "/documentation/metal/improving-ray-tracing-data-access-using-per-primitive-data"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureDescriptor"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Acceleration-Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/improving-ray-tracing-data-access-using-per-primitive-data",
        "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructure",
        "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureDescriptor",
        "doc://com.apple.metal/documentation/Metal/MTLPrimitiveAccelerationStructureDescriptor",
        "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureCommandEncoder",
        "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureUsage",
        "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureRefitOptions"
      ],
      "title": "Acceleration Structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Specifying-the-Instance-Structures",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/instanceDescriptorType",
        "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/instancedAccelerationStructures",
        "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceDescriptorType"
      ],
      "title": "Specifying the Instance Structures"
    },
    {
      "anchor": "Specifying-the-List-of-Instances",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/instanceCount",
        "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/instanceDescriptorBuffer",
        "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/instanceDescriptorBufferOffset",
        "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/instanceDescriptorStride"
      ],
      "title": "Specifying the List of Instances"
    },
    {
      "anchor": "Specifying-Motion-Data",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/motionTransformCount",
        "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/motionTransformBuffer",
        "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/motionTransformBufferOffset"
      ],
      "title": "Specifying Motion Data"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/instanceTransformationMatrixLayout",
        "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/motionTransformStride",
        "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/motionTransformType"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLInstanceAccelerationStructureDescriptor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLInstanceAccelerationStructureDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLInstanceAccelerationStructureDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Instance-Geometry-Descriptor",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/descriptor"
              ],
              "title": "Creating a Instance Geometry Descriptor"
            },
            {
              "anchor": "Specifying-the-Instance-Structures",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/instanceDescriptorType",
                "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/instancedAccelerationStructures",
                "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceDescriptorType"
              ],
              "title": "Specifying the Instance Structures"
            },
            {
              "anchor": "Specifying-the-List-of-Instances",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/instanceCount",
                "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/instanceDescriptorBuffer",
                "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/instanceDescriptorBufferOffset",
                "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/instanceDescriptorStride"
              ],
              "title": "Specifying the List of Instances"
            },
            {
              "anchor": "Specifying-Motion-Data",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/motionTransformCount",
                "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/motionTransformBuffer",
                "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/motionTransformBufferOffset"
              ],
              "title": "Specifying Motion Data"
            },
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/instanceTransformationMatrixLayout",
                "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/motionTransformStride",
                "doc://com.apple.metal/documentation/Metal/MTLInstanceAccelerationStructureDescriptor/motionTransformType"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureDescriptor"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Acceleration-Structures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/improving-ray-tracing-data-access-using-per-primitive-data",
                "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructure",
                "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureDescriptor",
                "doc://com.apple.metal/documentation/Metal/MTLPrimitiveAccelerationStructureDescriptor",
                "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureCommandEncoder",
                "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureUsage",
                "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureRefitOptions"
              ],
              "title": "Acceleration Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLInstanceAccelerationStructureDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureDescriptor",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MTLAccelerationStructureDescriptor",
                    "text": "MTLAccelerationStructureDescriptor"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor~1instanceTransformationMatrixLayout/title",
          "value": "instanceTransformationMatrixLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor~1instanceTransformationMatrixLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "instanceTransformationMatrixLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor~1motionTransformBuffer/title",
          "value": "motionTransformBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor~1motionTransformBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "motionTransformBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureCommandEncoder/title",
          "value": "MTLAccelerationStructureCommandEncoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureCommandEncoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureCommandEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureCommandEncoder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureCommandEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor/title",
          "value": "MTLInstanceAccelerationStructureDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLInstanceAccelerationStructureDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLInstanceAccelerationStructureDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPrimitiveAccelerationStructureDescriptor/title",
          "value": "MTLPrimitiveAccelerationStructureDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPrimitiveAccelerationStructureDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPrimitiveAccelerationStructureDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPrimitiveAccelerationStructureDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPrimitiveAccelerationStructureDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor~1motionTransformType/title",
          "value": "motionTransformType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor~1motionTransformType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "motionTransformType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureInstanceDescriptorType/title",
          "value": "MTLAccelerationStructureInstanceDescriptorType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureInstanceDescriptorType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureInstanceDescriptorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureInstanceDescriptorType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureInstanceDescriptorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor~1motionTransformBufferOffset/title",
          "value": "motionTransformBufferOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor~1motionTransformBufferOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "motionTransformBufferOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor~1instanceDescriptorBuffer/title",
          "value": "instanceDescriptorBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor~1instanceDescriptorBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "instanceDescriptorBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor~1motionTransformCount/title",
          "value": "motionTransformCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor~1motionTransformCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "motionTransformCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureUsage/title",
          "value": "MTLAccelerationStructureUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureUsage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor~1instanceDescriptorType/title",
          "value": "instanceDescriptorType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor~1instanceDescriptorType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "instanceDescriptorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureRefitOptions/title",
          "value": "MTLAccelerationStructureRefitOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureRefitOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureRefitOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureRefitOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureRefitOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor~1motionTransformStride/title",
          "value": "motionTransformStride"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor~1motionTransformStride/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "motionTransformStride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructure/title",
          "value": "MTLAccelerationStructure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructure/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor~1instanceDescriptorBufferOffset/title",
          "value": "instanceDescriptorBufferOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor~1instanceDescriptorBufferOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "instanceDescriptorBufferOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor~1instancedAccelerationStructures/title",
          "value": "instancedAccelerationStructures"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor~1instancedAccelerationStructures/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "instancedAccelerationStructures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor~1instanceDescriptorStride/title",
          "value": "instanceDescriptorStride"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor~1instanceDescriptorStride/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "instanceDescriptorStride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor~1instanceCount/title",
          "value": "instanceCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLInstanceAccelerationStructureDescriptor~1instanceCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "instanceCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureDescriptor/title",
          "value": "MTLAccelerationStructureDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureDescriptor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlinstanceaccelerationstructuredescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlinstanceaccelerationstructuredescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
