{
  "abstract": [
    {
      "text": "Represents the final state of a compression context.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLIOCompressionStatus"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLIOCompressionStatus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLIOCompressionStatus"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLIOCompressionStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTLIOCompressionStatus"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLIOCompressionStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOFlushAndDestroyCompressionContext(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " returns a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCompressionStatus",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance to reflect the final state of a compression context.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCompressionContext": {
      "abstract": [
        {
          "text": "A pointer that represents the state of a file compression session in progress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIOCompressionContext"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCompressionContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOCompressionContext"
        }
      ],
      "role": "symbol",
      "title": "MTLIOCompressionContext",
      "type": "topic",
      "url": "/documentation/metal/mtliocompressioncontext"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCompressionContextAppendData(_:_:_:)": {
      "abstract": [
        {
          "text": "Adds data to a compression context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIOCompressionContextAppendData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLIOCompressionContext",
          "text": "MTLIOCompressionContext"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCompressionContextAppendData(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOCompressionContextAppendData"
        }
      ],
      "role": "symbol",
      "title": "MTLIOCompressionContextAppendData(_:_:_:)",
      "type": "topic",
      "url": "/documentation/metal/mtliocompressioncontextappenddata(_:_:_:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCompressionContextDefaultChunkSize()": {
      "abstract": [
        {
          "text": "Returns a compression chunk size you can use as a default for creating a compression context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIOCompressionContextDefaultChunkSize"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCompressionContextDefaultChunkSize()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOCompressionContextDefaultChunkSize"
        }
      ],
      "role": "symbol",
      "title": "MTLIOCompressionContextDefaultChunkSize()",
      "type": "topic",
      "url": "/documentation/metal/mtliocompressioncontextdefaultchunksize()"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCompressionMethod": {
      "abstract": [
        {
          "text": "The compression codecs that Metal supports for input/output handles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIOCompressionMethod"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCompressionMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOCompressionMethod"
        }
      ],
      "role": "symbol",
      "title": "MTLIOCompressionMethod",
      "type": "topic",
      "url": "/documentation/metal/mtliocompressionmethod"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCompressionStatus": {
      "abstract": [
        {
          "text": "Represents the final state of a compression context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIOCompressionStatus"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCompressionStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOCompressionStatus"
        }
      ],
      "role": "symbol",
      "title": "MTLIOCompressionStatus",
      "type": "topic",
      "url": "/documentation/metal/mtliocompressionstatus"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCompressionStatus/complete": {
      "abstract": [
        {
          "text": "Indicates the compression API successfully flushed and destroyed a compression context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "complete"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCompressionStatus/complete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOCompressionStatusComplete"
        }
      ],
      "role": "symbol",
      "title": "MTLIOCompressionStatus.complete",
      "type": "topic",
      "url": "/documentation/metal/mtliocompressionstatus/complete"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCompressionStatus/error": {
      "abstract": [
        {
          "text": "Indicates the compression API had an error while flushing and destroying a compression context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "error"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCompressionStatus/error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOCompressionStatusError"
        }
      ],
      "role": "symbol",
      "title": "MTLIOCompressionStatus.error",
      "type": "topic",
      "url": "/documentation/metal/mtliocompressionstatus/error"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCompressionStatus/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCompressionStatus/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/metal/mtliocompressionstatus/init(rawvalue:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCreateCompressionContext": {
      "abstract": [
        {
          "text": "Creates a compression context that you use to compress data into a single file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTLIOCreateCompressionContext"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCreateCompressionContext",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLIOCreateCompressionContext",
      "type": "topic",
      "url": "/documentation/metal/mtliocreatecompressioncontext"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCreateCompressionContext(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a compression context that you use to compress data into a single file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIOCreateCompressionContext"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLIOCompressionMethod",
          "text": "MTLIOCompressionMethod"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLIOCompressionContext",
          "text": "MTLIOCompressionContext"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCreateCompressionContext(_:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLIOCreateCompressionContext(_:_:_:)",
      "type": "topic",
      "url": "/documentation/metal/mtliocreatecompressioncontext(_:_:_:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOFlushAndDestroyCompressionContext(_:)": {
      "abstract": [
        {
          "text": "Finishes compressing and saves the file that a compression context represents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIOFlushAndDestroyCompressionContext"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLIOCompressionContext",
          "text": "MTLIOCompressionContext"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLIOCompressionStatus",
          "text": "MTLIOCompressionStatus"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOFlushAndDestroyCompressionContext(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOFlushAndDestroyCompressionContext"
        }
      ],
      "role": "symbol",
      "title": "MTLIOFlushAndDestroyCompressionContext(_:)",
      "type": "topic",
      "url": "/documentation/metal/mtlioflushanddestroycompressioncontext(_:)"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Asset-Compression",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLIOCreateCompressionContext(_:_:_:)",
        "doc://com.apple.metal/documentation/Metal/MTLIOCompressionMethod",
        "doc://com.apple.metal/documentation/Metal/MTLIOCompressionContextDefaultChunkSize()",
        "doc://com.apple.metal/documentation/Metal/MTLIOCompressionContext",
        "doc://com.apple.metal/documentation/Metal/MTLIOCompressionContextAppendData(_:_:_:)",
        "doc://com.apple.metal/documentation/Metal/MTLIOFlushAndDestroyCompressionContext(_:)"
      ],
      "title": "Asset Compression"
    }
  ],
  "topicSections": [
    {
      "anchor": "Compression-Result-States",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLIOCompressionStatus/complete",
        "doc://com.apple.metal/documentation/Metal/MTLIOCompressionStatus/error"
      ],
      "title": "Compression Result States"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLIOCompressionStatus/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLIOCompressionStatus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCompressionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCompressionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Compression-Result-States",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLIOCompressionStatus/complete",
                "doc://com.apple.metal/documentation/Metal/MTLIOCompressionStatus/error"
              ],
              "title": "Compression Result States"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Asset-Compression",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLIOCreateCompressionContext",
                "doc://com.apple.metal/documentation/Metal/MTLIOCompressionMethod",
                "doc://com.apple.metal/documentation/Metal/MTLIOCompressionContextDefaultChunkSize()",
                "doc://com.apple.metal/documentation/Metal/MTLIOCompressionContext",
                "doc://com.apple.metal/documentation/Metal/MTLIOCompressionContextAppendData(_:_:_:)",
                "doc://com.apple.metal/documentation/Metal/MTLIOFlushAndDestroyCompressionContext(_:)"
              ],
              "title": "Asset Compression"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLIOCompressionStatus"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionStatus~1error/title",
          "value": "MTLIOCompressionStatusError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionStatus~1error/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCompressionStatusError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOFlushAndDestroyCompressionContext(_:)/title",
          "value": "MTLIOFlushAndDestroyCompressionContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOFlushAndDestroyCompressionContext(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOFlushAndDestroyCompressionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionMethod/title",
          "value": "MTLIOCompressionMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCompressionMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionMethod/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCompressionMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionContextAppendData(_:_:_:)/title",
          "value": "MTLIOCompressionContextAppendData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionContextAppendData(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCompressionContextAppendData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionStatus/title",
          "value": "MTLIOCompressionStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCompressionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCompressionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionContext/title",
          "value": "MTLIOCompressionContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCompressionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCompressionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionContextDefaultChunkSize()/title",
          "value": "MTLIOCompressionContextDefaultChunkSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionContextDefaultChunkSize()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCompressionContextDefaultChunkSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionStatus~1complete/title",
          "value": "MTLIOCompressionStatusComplete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionStatus~1complete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCompressionStatusComplete"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtliocompressionstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtliocompressionstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
