{
  "abstract": [
    {
      "text": "A command queue that schedules input/output commands for reading files in the file system, and writing to GPU resources and memory.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueue"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MTLIOCommandQueue",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLIOCommandQueue"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLIOCommandQueue"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "MTLIOCommandQueue"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLIOCommandQueue"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use an input/output command queue to submit commands, in command buffers, that load assets from the file system directly into GPU resources. Your app can then use those resources with other commands it submits to an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandQueue",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that comes from the same ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You make input/output command queues by creating and configuring an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance and calling an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/makeIOCommandQueue(descriptor:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandQueue": {
      "abstract": [
        {
          "text": "An instance you use to create, submit, and schedule command buffers to a specific GPU device to run the commands within those buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCommandQueue"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandQueue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandQueue"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandQueue",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandqueue"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice": {
      "abstract": [
        {
          "text": "The main Metal interface to a GPU that apps use to draw graphics and run computations in parallel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDevice"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDevice"
        }
      ],
      "role": "symbol",
      "title": "MTLDevice",
      "type": "topic",
      "url": "/documentation/metal/mtldevice"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/makeIOCommandQueue(descriptor:)": {
      "abstract": [
        {
          "text": "Creates an input/output command queue you use to submit commands that load assets from the file system into GPU resources or system memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeIOCommandQueue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLIOCommandQueueDescriptor",
          "text": "MTLIOCommandQueueDescriptor"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLIOCommandQueue",
          "text": "MTLIOCommandQueue"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/makeIOCommandQueue(descriptor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newIOCommandQueueWithDescriptor:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeIOCommandQueue(descriptor:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/makeiocommandqueue(descriptor:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueue": {
      "abstract": [
        {
          "text": "A command queue that schedules input/output commands for reading files in the file system, and writing to GPU resources and memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIOCommandQueue"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOCommandQueue"
        }
      ],
      "role": "symbol",
      "title": "MTLIOCommandQueue",
      "type": "topic",
      "url": "/documentation/metal/mtliocommandqueue"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueue/enqueueBarrier()": {
      "abstract": [
        {
          "text": "Appends a barrier that tells the input/output command queue to finish running all in-flight command buffers before running any new command buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enqueueBarrier"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueue/enqueueBarrier()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enqueueBarrier"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "enqueueBarrier()",
      "type": "topic",
      "url": "/documentation/metal/mtliocommandqueue/enqueuebarrier()"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueue/label": {
      "abstract": [
        {
          "text": "An optional name for the input/output command queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "label"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueue/label",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "label"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "label",
      "type": "topic",
      "url": "/documentation/metal/mtliocommandqueue/label"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueue/makeCommandBuffer()": {
      "abstract": [
        {
          "text": "Creates an input/output command buffer for the command queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeCommandBuffer"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLIOCommandBuffer",
          "text": "MTLIOCommandBuffer"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueue/makeCommandBuffer()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "commandBuffer"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeCommandBuffer()",
      "type": "topic",
      "url": "/documentation/metal/mtliocommandqueue/makecommandbuffer()"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueue/makeCommandBufferWithUnretainedReferences()": {
      "abstract": [
        {
          "text": "Creates an input/output command buffer for the command queue that doesn’t retain the instances you pass to its methods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeCommandBufferWithUnretainedReferences"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLIOCommandBuffer",
          "text": "MTLIOCommandBuffer"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueue/makeCommandBufferWithUnretainedReferences()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "commandBufferWithUnretainedReferences"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeCommandBufferWithUnretainedReferences()",
      "type": "topic",
      "url": "/documentation/metal/mtliocommandqueue/makecommandbufferwithunretainedreferences()"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor": {
      "abstract": [
        {
          "text": "A configuration template you use to create a new input/output command queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIOCommandQueueDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOCommandQueueDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLIOCommandQueueDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtliocommandqueuedescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueType": {
      "abstract": [
        {
          "text": "Designates the queue type for a new input/output command queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIOCommandQueueType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOCommandQueueType"
        }
      ],
      "role": "symbol",
      "title": "MTLIOCommandQueueType",
      "type": "topic",
      "url": "/documentation/metal/mtliocommandqueuetype"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOPriority": {
      "abstract": [
        {
          "text": "Designates the priority for a new input/output command queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIOPriority"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOPriority",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOPriority"
        }
      ],
      "role": "symbol",
      "title": "MTLIOPriority",
      "type": "topic",
      "url": "/documentation/metal/mtliopriority"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOScratchBuffer": {
      "abstract": [
        {
          "text": "A protocol your app implements that wraps a Metal buffer instance to serve as scratch memory for an input/output command queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIOScratchBuffer"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOScratchBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOScratchBuffer"
        }
      ],
      "role": "symbol",
      "title": "MTLIOScratchBuffer",
      "type": "topic",
      "url": "/documentation/metal/mtlioscratchbuffer"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOScratchBufferAllocator": {
      "abstract": [
        {
          "text": "A protocol your app implements to provide scratch memory to an input/output command queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIOScratchBufferAllocator"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOScratchBufferAllocator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOScratchBufferAllocator"
        }
      ],
      "role": "symbol",
      "title": "MTLIOScratchBufferAllocator",
      "type": "topic",
      "url": "/documentation/metal/mtlioscratchbufferallocator"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "IO-Command-Queues",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor",
        "doc://com.apple.metal/documentation/Metal/MTLIOPriority",
        "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueType",
        "doc://com.apple.metal/documentation/Metal/MTLIOScratchBufferAllocator",
        "doc://com.apple.metal/documentation/Metal/MTLIOScratchBuffer"
      ],
      "title": "I/O Command Queues"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-InputOutput-Command-Buffer",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueue/makeCommandBuffer()",
        "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueue/makeCommandBufferWithUnretainedReferences()"
      ],
      "title": "Creating a Input/Output Command Buffer"
    },
    {
      "anchor": "Adding-a-Barrier-to-the-Queue",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueue/enqueueBarrier()"
      ],
      "title": "Adding a Barrier to the Queue"
    },
    {
      "anchor": "Naming-the-Queue",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueue/label"
      ],
      "title": "Naming the Queue"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLIOCommandQueue"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCommandQueue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCommandQueue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-InputOutput-Command-Buffer",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueue/makeCommandBuffer()",
                "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueue/makeCommandBufferWithUnretainedReferences()"
              ],
              "title": "Creating a Input/Output Command Buffer"
            },
            {
              "anchor": "Adding-a-Barrier-to-the-Queue",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueue/enqueueBarrier()"
              ],
              "title": "Adding a Barrier to the Queue"
            },
            {
              "anchor": "Naming-the-Queue",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueue/label"
              ],
              "title": "Naming the Queue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "IO-Command-Queues",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor",
                "doc://com.apple.metal/documentation/Metal/MTLIOPriority",
                "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueType",
                "doc://com.apple.metal/documentation/Metal/MTLIOScratchBufferAllocator",
                "doc://com.apple.metal/documentation/Metal/MTLIOScratchBuffer"
              ],
              "title": "I/O Command Queues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLIOCommandQueue"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOScratchBufferAllocator/title",
          "value": "MTLIOScratchBufferAllocator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOScratchBufferAllocator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOScratchBufferAllocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOScratchBufferAllocator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOScratchBufferAllocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandQueue/title",
          "value": "MTLCommandQueue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandQueue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandQueue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandQueue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandQueue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueueDescriptor/title",
          "value": "MTLIOCommandQueueDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueueDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCommandQueueDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueueDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCommandQueueDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOPriority/title",
          "value": "MTLIOPriority"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOPriority/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOPriority/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueue~1label/title",
          "value": "label"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueue~1label/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "label"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeIOCommandQueue(descriptor:)/title",
          "value": "newIOCommandQueueWithDescriptor:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeIOCommandQueue(descriptor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newIOCommandQueueWithDescriptor:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueue~1enqueueBarrier()/title",
          "value": "enqueueBarrier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueue~1enqueueBarrier()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enqueueBarrier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueue~1makeCommandBufferWithUnretainedReferences()/title",
          "value": "commandBufferWithUnretainedReferences"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueue~1makeCommandBufferWithUnretainedReferences()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "commandBufferWithUnretainedReferences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueue/title",
          "value": "MTLIOCommandQueue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCommandQueue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCommandQueue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueueType/title",
          "value": "MTLIOCommandQueueType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueueType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCommandQueueType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueueType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCommandQueueType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOScratchBuffer/title",
          "value": "MTLIOScratchBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOScratchBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOScratchBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOScratchBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOScratchBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/title",
          "value": "MTLDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueue~1makeCommandBuffer()/title",
          "value": "commandBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueue~1makeCommandBuffer()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "commandBuffer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtliocommandqueue"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtliocommandqueue"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
