{
  "abstract": [
    {
      "text": "A configuration template you use to create a new input/output command queue.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTLIOCommandQueueDescriptor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLIOCommandQueueDescriptor"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLIOCommandQueueDescriptor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTLIOCommandQueueDescriptor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLIOCommandQueueDescriptor"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this descriptor type to configure the settings of each input/output command queue that you create using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/makeIOCommandQueue(descriptor:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". To create additional input/output command queues, you can reuse a descriptor instance and optionally reconfigure its properties.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Changing a descriptor’s properties doesn’t affect command queues you’ve already created with the descriptor.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Create each input/output queue to meet your apps needs by setting the descriptor’s properties.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Select a queue’s relative level of importance with the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor/priority",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create a queue that runs multiple input/output command buffers in parallel by setting the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor/type",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueType/concurrent",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Decide how many individual commands a queue can run simultaneously with the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor/maxCommandsInFlight",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Choose how many command buffers a queue can have waiting to run with ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor/maxCommandBufferCount",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Take control of the queue’s scratch memory allocation by implementing ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOScratchBufferAllocator",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and assign an instance of it to the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor/scratchBufferAllocator",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/makeIOCommandQueue(descriptor:)": {
      "abstract": [
        {
          "text": "Creates an input/output command queue you use to submit commands that load assets from the file system into GPU resources or system memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeIOCommandQueue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLIOCommandQueueDescriptor",
          "text": "MTLIOCommandQueueDescriptor"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLIOCommandQueue",
          "text": "MTLIOCommandQueue"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/makeIOCommandQueue(descriptor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newIOCommandQueueWithDescriptor:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeIOCommandQueue(descriptor:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/makeiocommandqueue(descriptor:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueue": {
      "abstract": [
        {
          "text": "A command queue that schedules input/output commands for reading files in the file system, and writing to GPU resources and memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIOCommandQueue"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOCommandQueue"
        }
      ],
      "role": "symbol",
      "title": "MTLIOCommandQueue",
      "type": "topic",
      "url": "/documentation/metal/mtliocommandqueue"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor": {
      "abstract": [
        {
          "text": "A configuration template you use to create a new input/output command queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIOCommandQueueDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOCommandQueueDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLIOCommandQueueDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtliocommandqueuedescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor/maxCommandBufferCount": {
      "abstract": [
        {
          "text": "Sets the largest number of outstanding input/output command buffers a queue can have at any point in time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxCommandBufferCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor/maxCommandBufferCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxCommandBufferCount"
        }
      ],
      "role": "symbol",
      "title": "maxCommandBufferCount",
      "type": "topic",
      "url": "/documentation/metal/mtliocommandqueuedescriptor/maxcommandbuffercount"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor/maxCommandsInFlight": {
      "abstract": [
        {
          "text": "Sets the largest number of individual commands that an input/output command queue can run at a time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxCommandsInFlight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor/maxCommandsInFlight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxCommandsInFlight"
        }
      ],
      "role": "symbol",
      "title": "maxCommandsInFlight",
      "type": "topic",
      "url": "/documentation/metal/mtliocommandqueuedescriptor/maxcommandsinflight"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor/priority": {
      "abstract": [
        {
          "text": "Configures the priority for a new input/output command queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "priority"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLIOPriority",
          "text": "MTLIOPriority"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor/priority",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "priority"
        }
      ],
      "role": "symbol",
      "title": "priority",
      "type": "topic",
      "url": "/documentation/metal/mtliocommandqueuedescriptor/priority"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor/scratchBufferAllocator": {
      "abstract": [
        {
          "text": "An optional memory allocator that you implement to manage the scratch memory that an input/output command queue requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scratchBufferAllocator"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLIOScratchBufferAllocator",
          "text": "MTLIOScratchBufferAllocator"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor/scratchBufferAllocator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scratchBufferAllocator"
        }
      ],
      "role": "symbol",
      "title": "scratchBufferAllocator",
      "type": "topic",
      "url": "/documentation/metal/mtliocommandqueuedescriptor/scratchbufferallocator"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor/type": {
      "abstract": [
        {
          "text": "Configures the queue type for a new input/output command queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLIOCommandQueueType",
          "text": "MTLIOCommandQueueType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/metal/mtliocommandqueuedescriptor/type"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueType": {
      "abstract": [
        {
          "text": "Designates the queue type for a new input/output command queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIOCommandQueueType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOCommandQueueType"
        }
      ],
      "role": "symbol",
      "title": "MTLIOCommandQueueType",
      "type": "topic",
      "url": "/documentation/metal/mtliocommandqueuetype"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueType/concurrent": {
      "abstract": [
        {
          "text": "Sets a new input/output command queue’s type to a queue that runs commands concurrently.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "concurrent"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueType/concurrent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOCommandQueueTypeConcurrent"
        }
      ],
      "role": "symbol",
      "title": "MTLIOCommandQueueType.concurrent",
      "type": "topic",
      "url": "/documentation/metal/mtliocommandqueuetype/concurrent"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOPriority": {
      "abstract": [
        {
          "text": "Designates the priority for a new input/output command queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIOPriority"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOPriority",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOPriority"
        }
      ],
      "role": "symbol",
      "title": "MTLIOPriority",
      "type": "topic",
      "url": "/documentation/metal/mtliopriority"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOScratchBuffer": {
      "abstract": [
        {
          "text": "A protocol your app implements that wraps a Metal buffer instance to serve as scratch memory for an input/output command queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIOScratchBuffer"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOScratchBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOScratchBuffer"
        }
      ],
      "role": "symbol",
      "title": "MTLIOScratchBuffer",
      "type": "topic",
      "url": "/documentation/metal/mtlioscratchbuffer"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOScratchBufferAllocator": {
      "abstract": [
        {
          "text": "A protocol your app implements to provide scratch memory to an input/output command queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIOScratchBufferAllocator"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOScratchBufferAllocator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOScratchBufferAllocator"
        }
      ],
      "role": "symbol",
      "title": "MTLIOScratchBufferAllocator",
      "type": "topic",
      "url": "/documentation/metal/mtlioscratchbufferallocator"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "IO-Command-Queues",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueue",
        "doc://com.apple.metal/documentation/Metal/MTLIOPriority",
        "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueType",
        "doc://com.apple.metal/documentation/Metal/MTLIOScratchBufferAllocator",
        "doc://com.apple.metal/documentation/Metal/MTLIOScratchBuffer"
      ],
      "title": "I/O Command Queues"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuring-the-InputOutput-Command-Queue",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor/priority",
        "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor/type",
        "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor/maxCommandsInFlight",
        "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor/maxCommandBufferCount"
      ],
      "title": "Configuring the Input/Output Command Queue"
    },
    {
      "anchor": "Providing-your-own-a-Scratch-Buffer",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor/scratchBufferAllocator"
      ],
      "title": "Providing your own  a Scratch Buffer"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLIOCommandQueueDescriptor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCommandQueueDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCommandQueueDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuring-the-InputOutput-Command-Queue",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor/priority",
                "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor/type",
                "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor/maxCommandsInFlight",
                "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor/maxCommandBufferCount"
              ],
              "title": "Configuring the Input/Output Command Queue"
            },
            {
              "anchor": "Providing-your-own-a-Scratch-Buffer",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueDescriptor/scratchBufferAllocator"
              ],
              "title": "Providing your own  a Scratch Buffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "IO-Command-Queues",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueue",
                "doc://com.apple.metal/documentation/Metal/MTLIOPriority",
                "doc://com.apple.metal/documentation/Metal/MTLIOCommandQueueType",
                "doc://com.apple.metal/documentation/Metal/MTLIOScratchBufferAllocator",
                "doc://com.apple.metal/documentation/Metal/MTLIOScratchBuffer"
              ],
              "title": "I/O Command Queues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLIOCommandQueueDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeIOCommandQueue(descriptor:)/title",
          "value": "newIOCommandQueueWithDescriptor:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeIOCommandQueue(descriptor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newIOCommandQueueWithDescriptor:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOScratchBufferAllocator/title",
          "value": "MTLIOScratchBufferAllocator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOScratchBufferAllocator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOScratchBufferAllocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOScratchBufferAllocator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOScratchBufferAllocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueueDescriptor~1maxCommandBufferCount/title",
          "value": "maxCommandBufferCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueueDescriptor~1maxCommandBufferCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxCommandBufferCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueueDescriptor~1scratchBufferAllocator/title",
          "value": "scratchBufferAllocator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueueDescriptor~1scratchBufferAllocator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scratchBufferAllocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueueType/title",
          "value": "MTLIOCommandQueueType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueueType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCommandQueueType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueueType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCommandQueueType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueueDescriptor~1maxCommandsInFlight/title",
          "value": "maxCommandsInFlight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueueDescriptor~1maxCommandsInFlight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxCommandsInFlight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueueDescriptor/title",
          "value": "MTLIOCommandQueueDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueueDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCommandQueueDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueueDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCommandQueueDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueue/title",
          "value": "MTLIOCommandQueue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCommandQueue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCommandQueue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOScratchBuffer/title",
          "value": "MTLIOScratchBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOScratchBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOScratchBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOScratchBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOScratchBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueueDescriptor~1priority/title",
          "value": "priority"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueueDescriptor~1priority/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "priority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOPriority/title",
          "value": "MTLIOPriority"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOPriority/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOPriority/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueueDescriptor~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueueDescriptor~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueueType~1concurrent/title",
          "value": "MTLIOCommandQueueTypeConcurrent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCommandQueueType~1concurrent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCommandQueueTypeConcurrent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtliocommandqueuedescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtliocommandqueuedescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
