{
  "abstract": [
    {
      "text": "A compute command in an indirect command buffer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MTLIndirectComputeCommand",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLIndirectComputeCommand"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLIndirectComputeCommand"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "MTLIndirectComputeCommand"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLIndirectComputeCommand"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Don’t implement this protocol; you get objects of this type by asking a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectCommandBuffer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for them.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use this object to reset or encode a command. You must always reset a command before encoding a new command.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDispatchThreadgroupsIndirectArguments": {
      "abstract": [
        {
          "text": "The data layout required for arguments needed to specify the size of threadgroups.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDispatchThreadgroupsIndirectArguments"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDispatchThreadgroupsIndirectArguments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDispatchThreadgroupsIndirectArguments"
        }
      ],
      "role": "symbol",
      "title": "MTLDispatchThreadgroupsIndirectArguments",
      "type": "topic",
      "url": "/documentation/metal/mtldispatchthreadgroupsindirectarguments"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectCommandBuffer": {
      "abstract": [
        {
          "text": "A command buffer containing reusable commands, encoded either on the CPU or GPU.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIndirectCommandBuffer"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectCommandBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIndirectCommandBuffer"
        }
      ],
      "role": "symbol",
      "title": "MTLIndirectCommandBuffer",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectcommandbuffer"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand": {
      "abstract": [
        {
          "text": "A compute command in an indirect command buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIndirectComputeCommand"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIndirectComputeCommand"
        }
      ],
      "role": "symbol",
      "title": "MTLIndirectComputeCommand",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectcomputecommand"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/clearBarrier()": {
      "abstract": [
        {
          "text": "Removes any barrier set on the command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clearBarrier"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/clearBarrier()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clearBarrier"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "clearBarrier()",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectcomputecommand/clearbarrier()"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/concurrentDispatchThreadgroups(_:threadsPerThreadgroup:)": {
      "abstract": [
        {
          "text": "Encodes a compute command using a grid aligned to threadgroup boundaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "concurrentDispatchThreadgroups"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MTLSize",
          "text": "MTLSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "threadsPerThreadgroup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MTLSize",
          "text": "MTLSize"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/concurrentDispatchThreadgroups(_:threadsPerThreadgroup:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "concurrentDispatchThreadgroups:threadsPerThreadgroup:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "concurrentDispatchThreadgroups(_:threadsPerThreadgroup:)",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectcomputecommand/concurrentdispatchthreadgroups(_:threadsperthreadgroup:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/concurrentDispatchThreads(_:threadsPerThreadgroup:)": {
      "abstract": [
        {
          "text": "Encodes a compute command using an arbitrarily sized grid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "concurrentDispatchThreads"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MTLSize",
          "text": "MTLSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "threadsPerThreadgroup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MTLSize",
          "text": "MTLSize"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/concurrentDispatchThreads(_:threadsPerThreadgroup:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "concurrentDispatchThreads:threadsPerThreadgroup:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "concurrentDispatchThreads(_:threadsPerThreadgroup:)",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectcomputecommand/concurrentdispatchthreads(_:threadsperthreadgroup:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/reset()": {
      "abstract": [
        {
          "text": "Resets the command to its default state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reset"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/reset()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reset"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "reset()",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectcomputecommand/reset()"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setBarrier()": {
      "abstract": [
        {
          "text": "Adds a barrier to ensure that commands executed prior to this command are complete before this command executes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setBarrier"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setBarrier()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setBarrier"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setBarrier()",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectcomputecommand/setbarrier()"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setComputePipelineState(_:)": {
      "abstract": [
        {
          "text": "Sets the command’s compute pipeline state object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setComputePipelineState"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLComputePipelineState",
          "text": "MTLComputePipelineState"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setComputePipelineState(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setComputePipelineState:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setComputePipelineState(_:)",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectcomputecommand/setcomputepipelinestate(_:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setImageblockWidth(_:height:)": {
      "abstract": [
        {
          "text": "Sets the size, in pixels, of the imageblock.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setImageblockWidth"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "height"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setImageblockWidth(_:height:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setImageblockWidth:height:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setImageblockWidth(_:height:)",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectcomputecommand/setimageblockwidth(_:height:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setKernelBuffer(_:offset:at:)": {
      "abstract": [
        {
          "text": "Sets a buffer for the compute function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setKernelBuffer"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLBuffer",
          "text": "MTLBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "offset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setKernelBuffer(_:offset:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setKernelBuffer:offset:atIndex:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setKernelBuffer(_:offset:at:)",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectcomputecommand/setkernelbuffer(_:offset:at:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setKernelBuffer(_:offset:attributeStride:at:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setKernelBuffer"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLBuffer",
          "text": "MTLBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "offset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "attributeStride"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setKernelBuffer(_:offset:attributeStride:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setKernelBuffer:offset:attributeStride:atIndex:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setKernelBuffer(_:offset:attributeStride:at:)",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectcomputecommand/setkernelbuffer(_:offset:attributestride:at:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setStageIn(_:)": {
      "abstract": [
        {
          "text": "Sets the region of the stage-in attributes to apply to the compute kernel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setStageIn"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MTLRegion",
          "text": "MTLRegion"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setStageIn(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setStageIn(_:)",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectcomputecommand/setstagein(_:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setStageInRegion(_:)": {
      "abstract": [
        {
          "text": "Sets the region of the stage-in attributes to apply to the compute kernel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setStageInRegion"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MTLRegion",
          "text": "MTLRegion"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setStageInRegion(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setStageInRegion:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setStageInRegion(_:)",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectcomputecommand/setstageinregion(_:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setThreadgroupMemoryLength(_:at:)": {
      "abstract": [
        {
          "text": "Sets the size of a block of threadgroup memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setThreadgroupMemoryLength"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setThreadgroupMemoryLength(_:at:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setThreadgroupMemoryLength(_:at:)",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectcomputecommand/setthreadgroupmemorylength(_:at:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setThreadgroupMemoryLength(_:index:)": {
      "abstract": [
        {
          "text": "Sets the size of a block of threadgroup memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setThreadgroupMemoryLength"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "index"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setThreadgroupMemoryLength(_:index:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setThreadgroupMemoryLength:atIndex:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setThreadgroupMemoryLength(_:index:)",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectcomputecommand/setthreadgroupmemorylength(_:index:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLOrigin": {
      "abstract": [
        {
          "text": "The coordinates for the front upper-left corner of a region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLOrigin"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLOrigin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLOrigin"
        }
      ],
      "role": "symbol",
      "title": "MTLOrigin",
      "type": "topic",
      "url": "/documentation/metal/mtlorigin"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRegion": {
      "abstract": [
        {
          "text": "The bounds for a subset of an object’s elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLRegion"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRegion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLRegion"
        }
      ],
      "role": "symbol",
      "title": "MTLRegion",
      "type": "topic",
      "url": "/documentation/metal/mtlregion"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSize": {
      "abstract": [
        {
          "text": "The dimensions of an object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLSize"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSize"
        }
      ],
      "role": "symbol",
      "title": "MTLSize",
      "type": "topic",
      "url": "/documentation/metal/mtlsize"
    },
    "doc://com.apple.metal/documentation/Metal/MTLStageInRegionIndirectArguments": {
      "abstract": [
        {
          "text": "The data layout required for the arguments needed to specify the stage-in region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLStageInRegionIndirectArguments"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLStageInRegionIndirectArguments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLStageInRegionIndirectArguments"
        }
      ],
      "role": "symbol",
      "title": "MTLStageInRegionIndirectArguments",
      "type": "topic",
      "url": "/documentation/metal/mtlstageinregionindirectarguments"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Indirect-Compute-Commands",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLRegion",
        "doc://com.apple.metal/documentation/Metal/MTLSize",
        "doc://com.apple.metal/documentation/Metal/MTLOrigin",
        "doc://com.apple.metal/documentation/Metal/MTLStageInRegionIndirectArguments",
        "doc://com.apple.metal/documentation/Metal/MTLDispatchThreadgroupsIndirectArguments"
      ],
      "title": "Indirect Compute Commands"
    }
  ],
  "topicSections": [
    {
      "anchor": "Setting-a-Commands-Arguments",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setComputePipelineState(_:)",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setImageblockWidth(_:height:)",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setKernelBuffer(_:offset:at:)",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setThreadgroupMemoryLength(_:index:)",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setThreadgroupMemoryLength(_:at:)",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setStageInRegion(_:)",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setStageIn(_:)"
      ],
      "title": "Setting a Command’s Arguments"
    },
    {
      "anchor": "Synchronizing-Command-Execution",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setBarrier()",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/clearBarrier()"
      ],
      "title": "Synchronizing Command Execution"
    },
    {
      "anchor": "Encoding-a-Compute-Command",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/concurrentDispatchThreadgroups(_:threadsPerThreadgroup:)",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/concurrentDispatchThreads(_:threadsPerThreadgroup:)"
      ],
      "title": "Encoding a Compute Command"
    },
    {
      "anchor": "Resetting-a-Command",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/reset()"
      ],
      "title": "Resetting a Command"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setKernelBuffer(_:offset:attributeStride:at:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLIndirectComputeCommand"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIndirectComputeCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIndirectComputeCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Setting-a-Commands-Arguments",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setComputePipelineState(_:)",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setImageblockWidth(_:height:)",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setKernelBuffer(_:offset:at:)",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setThreadgroupMemoryLength(_:index:)",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setStageInRegion(_:)"
              ],
              "title": "Setting a Command’s Arguments"
            },
            {
              "anchor": "Synchronizing-Command-Execution",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setBarrier()",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/clearBarrier()"
              ],
              "title": "Synchronizing Command Execution"
            },
            {
              "anchor": "Encoding-a-Compute-Command",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/concurrentDispatchThreadgroups(_:threadsPerThreadgroup:)",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/concurrentDispatchThreads(_:threadsPerThreadgroup:)"
              ],
              "title": "Encoding a Compute Command"
            },
            {
              "anchor": "Resetting-a-Command",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/reset()"
              ],
              "title": "Resetting a Command"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLIndirectComputeCommand/setKernelBuffer(_:offset:attributeStride:at:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Indirect-Compute-Commands",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLRegion",
                "doc://com.apple.metal/documentation/Metal/MTLSize",
                "doc://com.apple.metal/documentation/Metal/MTLOrigin",
                "doc://com.apple.metal/documentation/Metal/MTLStageInRegionIndirectArguments",
                "doc://com.apple.metal/documentation/Metal/MTLDispatchThreadgroupsIndirectArguments"
              ],
              "title": "Indirect Compute Commands"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLIndirectComputeCommand"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStageInRegionIndirectArguments/title",
          "value": "MTLStageInRegionIndirectArguments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStageInRegionIndirectArguments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStageInRegionIndirectArguments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStageInRegionIndirectArguments/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStageInRegionIndirectArguments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectComputeCommand~1setKernelBuffer(_:offset:attributeStride:at:)/title",
          "value": "setKernelBuffer:offset:attributeStride:atIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectComputeCommand~1setKernelBuffer(_:offset:attributeStride:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setKernelBuffer:offset:attributeStride:atIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectComputeCommand~1setBarrier()/title",
          "value": "setBarrier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectComputeCommand~1setBarrier()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setBarrier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectComputeCommand~1setImageblockWidth(_:height:)/title",
          "value": "setImageblockWidth:height:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectComputeCommand~1setImageblockWidth(_:height:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setImageblockWidth:height:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectComputeCommand~1clearBarrier()/title",
          "value": "clearBarrier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectComputeCommand~1clearBarrier()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "clearBarrier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDispatchThreadgroupsIndirectArguments/title",
          "value": "MTLDispatchThreadgroupsIndirectArguments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDispatchThreadgroupsIndirectArguments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDispatchThreadgroupsIndirectArguments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDispatchThreadgroupsIndirectArguments/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDispatchThreadgroupsIndirectArguments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectComputeCommand/title",
          "value": "MTLIndirectComputeCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectComputeCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIndirectComputeCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectComputeCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIndirectComputeCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectComputeCommand~1setKernelBuffer(_:offset:at:)/title",
          "value": "setKernelBuffer:offset:atIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectComputeCommand~1setKernelBuffer(_:offset:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setKernelBuffer:offset:atIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectComputeCommand~1setStageInRegion(_:)/title",
          "value": "setStageInRegion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectComputeCommand~1setStageInRegion(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setStageInRegion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectComputeCommand~1concurrentDispatchThreads(_:threadsPerThreadgroup:)/title",
          "value": "concurrentDispatchThreads:threadsPerThreadgroup:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectComputeCommand~1concurrentDispatchThreads(_:threadsPerThreadgroup:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "concurrentDispatchThreads:threadsPerThreadgroup:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSize/title",
          "value": "MTLSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSize/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectComputeCommand~1reset()/title",
          "value": "reset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectComputeCommand~1reset()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "reset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLOrigin/title",
          "value": "MTLOrigin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLOrigin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLOrigin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLOrigin/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLOrigin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectComputeCommand~1concurrentDispatchThreadgroups(_:threadsPerThreadgroup:)/title",
          "value": "concurrentDispatchThreadgroups:threadsPerThreadgroup:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectComputeCommand~1concurrentDispatchThreadgroups(_:threadsPerThreadgroup:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "concurrentDispatchThreadgroups:threadsPerThreadgroup:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRegion/title",
          "value": "MTLRegion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRegion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRegion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectCommandBuffer/title",
          "value": "MTLIndirectCommandBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectCommandBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIndirectCommandBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectCommandBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIndirectCommandBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectComputeCommand~1setThreadgroupMemoryLength(_:index:)/title",
          "value": "setThreadgroupMemoryLength:atIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectComputeCommand~1setThreadgroupMemoryLength(_:index:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setThreadgroupMemoryLength:atIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectComputeCommand~1setComputePipelineState(_:)/title",
          "value": "setComputePipelineState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectComputeCommand~1setComputePipelineState(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setComputePipelineState:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlindirectcomputecommand"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlindirectcomputecommand"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
