{
  "abstract": [
    {
      "text": "A description of an acceleration structure that Metal derives from instances of primitive acceleration structures that the GPU can populate.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTLIndirectInstanceAccelerationStructureDescriptor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLIndirectInstanceAccelerationStructureDescriptor"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLIndirectInstanceAccelerationStructureDescriptor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTLIndirectInstanceAccelerationStructureDescriptor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLIndirectInstanceAccelerationStructureDescriptor"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureDescriptor": {
      "abstract": [
        {
          "text": "A base class for classes that define the configuration for a new acceleration structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLAccelerationStructureDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructuredescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceDescriptor": {
      "abstract": [
        {
          "text": "A description of an instance in an instanced geometry acceleration structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureInstanceDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureInstanceDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLAccelerationStructureInstanceDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructureinstancedescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions": {
      "abstract": [
        {
          "text": "Options for adjusting the behavior of an instanced acceleration structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureInstanceOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureInstanceOptions"
        }
      ],
      "role": "symbol",
      "title": "MTLAccelerationStructureInstanceOptions",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructureinstanceoptions"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureMotionInstanceDescriptor": {
      "abstract": [
        {
          "text": "A description of an instance in an instanced geometry acceleration structure, with the instance including a user identifier and motion data for the instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureMotionInstanceDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureMotionInstanceDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureMotionInstanceDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLAccelerationStructureMotionInstanceDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructuremotioninstancedescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureUserIDInstanceDescriptor": {
      "abstract": [
        {
          "text": "A description of an instance in an instanced geometry acceleration structure, with the instance including a user identifier for the instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureUserIDInstanceDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureUserIDInstanceDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureUserIDInstanceDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLAccelerationStructureUserIDInstanceDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructureuseridinstancedescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor": {
      "abstract": [
        {
          "text": "A description of an instance in an instanced geometry acceleration structure that the GPU can populate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIndirectAccelerationStructureInstanceDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIndirectAccelerationStructureInstanceDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLIndirectAccelerationStructureInstanceDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectaccelerationstructureinstancedescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureMotionInstanceDescriptor": {
      "abstract": [
        {
          "text": "A description of an instance in an acceleration structure that the GPU can populate, with motion data for the instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIndirectAccelerationStructureMotionInstanceDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureMotionInstanceDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIndirectAccelerationStructureMotionInstanceDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLIndirectAccelerationStructureMotionInstanceDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectaccelerationstructuremotioninstancedescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor": {
      "abstract": [
        {
          "text": "A description of an acceleration structure that Metal derives from instances of primitive acceleration structures that the GPU can populate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIndirectInstanceAccelerationStructureDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIndirectInstanceAccelerationStructureDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLIndirectInstanceAccelerationStructureDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectinstanceaccelerationstructuredescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/descriptor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "descriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/descriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptor"
        }
      ],
      "role": "symbol",
      "title": "descriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectinstanceaccelerationstructuredescriptor/descriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/instanceCountBuffer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instanceCountBuffer"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLBuffer",
          "text": "MTLBuffer"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/instanceCountBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "instanceCountBuffer"
        }
      ],
      "role": "symbol",
      "title": "instanceCountBuffer",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectinstanceaccelerationstructuredescriptor/instancecountbuffer"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/instanceCountBufferOffset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instanceCountBufferOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/instanceCountBufferOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "instanceCountBufferOffset"
        }
      ],
      "role": "symbol",
      "title": "instanceCountBufferOffset",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectinstanceaccelerationstructuredescriptor/instancecountbufferoffset"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/instanceDescriptorBuffer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instanceDescriptorBuffer"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLBuffer",
          "text": "MTLBuffer"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/instanceDescriptorBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "instanceDescriptorBuffer"
        }
      ],
      "role": "symbol",
      "title": "instanceDescriptorBuffer",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectinstanceaccelerationstructuredescriptor/instancedescriptorbuffer"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/instanceDescriptorBufferOffset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instanceDescriptorBufferOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/instanceDescriptorBufferOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "instanceDescriptorBufferOffset"
        }
      ],
      "role": "symbol",
      "title": "instanceDescriptorBufferOffset",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectinstanceaccelerationstructuredescriptor/instancedescriptorbufferoffset"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/instanceDescriptorStride": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instanceDescriptorStride"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/instanceDescriptorStride",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "instanceDescriptorStride"
        }
      ],
      "role": "symbol",
      "title": "instanceDescriptorStride",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectinstanceaccelerationstructuredescriptor/instancedescriptorstride"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/instanceDescriptorType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instanceDescriptorType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLAccelerationStructureInstanceDescriptorType",
          "text": "MTLAccelerationStructureInstanceDescriptorType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/instanceDescriptorType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "instanceDescriptorType"
        }
      ],
      "role": "symbol",
      "title": "instanceDescriptorType",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectinstanceaccelerationstructuredescriptor/instancedescriptortype"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/instanceTransformationMatrixLayout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instanceTransformationMatrixLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLMatrixLayout",
          "text": "MTLMatrixLayout"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/instanceTransformationMatrixLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "instanceTransformationMatrixLayout"
        }
      ],
      "role": "symbol",
      "title": "instanceTransformationMatrixLayout",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectinstanceaccelerationstructuredescriptor/instancetransformationmatrixlayout"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/maxInstanceCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxInstanceCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/maxInstanceCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxInstanceCount"
        }
      ],
      "role": "symbol",
      "title": "maxInstanceCount",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectinstanceaccelerationstructuredescriptor/maxinstancecount"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/maxMotionTransformCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxMotionTransformCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/maxMotionTransformCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxMotionTransformCount"
        }
      ],
      "role": "symbol",
      "title": "maxMotionTransformCount",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectinstanceaccelerationstructuredescriptor/maxmotiontransformcount"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/motionTransformBuffer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "motionTransformBuffer"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLBuffer",
          "text": "MTLBuffer"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/motionTransformBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "motionTransformBuffer"
        }
      ],
      "role": "symbol",
      "title": "motionTransformBuffer",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectinstanceaccelerationstructuredescriptor/motiontransformbuffer"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/motionTransformBufferOffset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "motionTransformBufferOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/motionTransformBufferOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "motionTransformBufferOffset"
        }
      ],
      "role": "symbol",
      "title": "motionTransformBufferOffset",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectinstanceaccelerationstructuredescriptor/motiontransformbufferoffset"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/motionTransformCountBuffer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "motionTransformCountBuffer"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLBuffer",
          "text": "MTLBuffer"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/motionTransformCountBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "motionTransformCountBuffer"
        }
      ],
      "role": "symbol",
      "title": "motionTransformCountBuffer",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectinstanceaccelerationstructuredescriptor/motiontransformcountbuffer"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/motionTransformCountBufferOffset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "motionTransformCountBufferOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/motionTransformCountBufferOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "motionTransformCountBufferOffset"
        }
      ],
      "role": "symbol",
      "title": "motionTransformCountBufferOffset",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectinstanceaccelerationstructuredescriptor/motiontransformcountbufferoffset"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/motionTransformStride": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "motionTransformStride"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/motionTransformStride",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "motionTransformStride"
        }
      ],
      "role": "symbol",
      "title": "motionTransformStride",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectinstanceaccelerationstructuredescriptor/motiontransformstride"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/motionTransformType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "motionTransformType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTransformType",
          "text": "MTLTransformType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/motionTransformType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "motionTransformType"
        }
      ],
      "role": "symbol",
      "title": "motionTransformType",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectinstanceaccelerationstructuredescriptor/motiontransformtype"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureDescriptor"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Descriptors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceDescriptor",
        "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureUserIDInstanceDescriptor",
        "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureMotionInstanceDescriptor",
        "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureMotionInstanceDescriptor"
      ],
      "title": "Instance Descriptors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/instanceCountBuffer",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/instanceCountBufferOffset",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/instanceDescriptorBuffer",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/instanceDescriptorBufferOffset",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/instanceDescriptorStride",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/instanceDescriptorType",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/instanceTransformationMatrixLayout",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/maxInstanceCount",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/maxMotionTransformCount",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/motionTransformBuffer",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/motionTransformBufferOffset",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/motionTransformCountBuffer",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/motionTransformCountBufferOffset",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/motionTransformStride",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/motionTransformType"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLIndirectInstanceAccelerationStructureDescriptor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIndirectInstanceAccelerationStructureDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIndirectInstanceAccelerationStructureDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/instanceCountBuffer",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/instanceCountBufferOffset",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/instanceDescriptorBuffer",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/instanceDescriptorBufferOffset",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/instanceDescriptorStride",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/instanceDescriptorType",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/instanceTransformationMatrixLayout",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/maxInstanceCount",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/maxMotionTransformCount",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/motionTransformBuffer",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/motionTransformBufferOffset",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/motionTransformCountBuffer",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/motionTransformCountBufferOffset",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/motionTransformStride",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/motionTransformType"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Type-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor/descriptor"
              ],
              "title": "Type Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureDescriptor"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-Descriptors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceDescriptor",
                "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureUserIDInstanceDescriptor",
                "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureMotionInstanceDescriptor",
                "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureMotionInstanceDescriptor"
              ],
              "title": "Instance Descriptors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLIndirectInstanceAccelerationStructureDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureDescriptor",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MTLAccelerationStructureDescriptor",
                    "text": "MTLAccelerationStructureDescriptor"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1instanceDescriptorBufferOffset/title",
          "value": "instanceDescriptorBufferOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1instanceDescriptorBufferOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "instanceDescriptorBufferOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureMotionInstanceDescriptor/title",
          "value": "MTLAccelerationStructureMotionInstanceDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureMotionInstanceDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureMotionInstanceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureMotionInstanceDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureMotionInstanceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1instanceDescriptorType/title",
          "value": "instanceDescriptorType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1instanceDescriptorType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "instanceDescriptorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1instanceCountBufferOffset/title",
          "value": "instanceCountBufferOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1instanceCountBufferOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "instanceCountBufferOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor/title",
          "value": "MTLIndirectInstanceAccelerationStructureDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIndirectInstanceAccelerationStructureDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIndirectInstanceAccelerationStructureDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectAccelerationStructureInstanceDescriptor/title",
          "value": "MTLIndirectAccelerationStructureInstanceDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectAccelerationStructureInstanceDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIndirectAccelerationStructureInstanceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectAccelerationStructureInstanceDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIndirectAccelerationStructureInstanceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1maxMotionTransformCount/title",
          "value": "maxMotionTransformCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1maxMotionTransformCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxMotionTransformCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1motionTransformBufferOffset/title",
          "value": "motionTransformBufferOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1motionTransformBufferOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "motionTransformBufferOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1instanceDescriptorStride/title",
          "value": "instanceDescriptorStride"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1instanceDescriptorStride/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "instanceDescriptorStride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1instanceDescriptorBuffer/title",
          "value": "instanceDescriptorBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1instanceDescriptorBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "instanceDescriptorBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectAccelerationStructureMotionInstanceDescriptor/title",
          "value": "MTLIndirectAccelerationStructureMotionInstanceDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectAccelerationStructureMotionInstanceDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIndirectAccelerationStructureMotionInstanceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectAccelerationStructureMotionInstanceDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIndirectAccelerationStructureMotionInstanceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1instanceCountBuffer/title",
          "value": "instanceCountBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1instanceCountBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "instanceCountBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1motionTransformStride/title",
          "value": "motionTransformStride"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1motionTransformStride/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "motionTransformStride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureUserIDInstanceDescriptor/title",
          "value": "MTLAccelerationStructureUserIDInstanceDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureUserIDInstanceDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureUserIDInstanceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureUserIDInstanceDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureUserIDInstanceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1motionTransformCountBuffer/title",
          "value": "motionTransformCountBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1motionTransformCountBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "motionTransformCountBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureDescriptor/title",
          "value": "MTLAccelerationStructureDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureInstanceDescriptor/title",
          "value": "MTLAccelerationStructureInstanceDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureInstanceDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureInstanceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureInstanceDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureInstanceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureInstanceOptions/title",
          "value": "MTLAccelerationStructureInstanceOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureInstanceOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureInstanceOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureInstanceOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureInstanceOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1instanceTransformationMatrixLayout/title",
          "value": "instanceTransformationMatrixLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1instanceTransformationMatrixLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "instanceTransformationMatrixLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1maxInstanceCount/title",
          "value": "maxInstanceCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1maxInstanceCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxInstanceCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1motionTransformCountBufferOffset/title",
          "value": "motionTransformCountBufferOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1motionTransformCountBufferOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "motionTransformCountBufferOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1motionTransformType/title",
          "value": "motionTransformType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1motionTransformType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "motionTransformType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1motionTransformBuffer/title",
          "value": "motionTransformBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor~1motionTransformBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "motionTransformBuffer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlindirectinstanceaccelerationstructuredescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlindirectinstanceaccelerationstructuredescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
