{
  "abstract": [
    {
      "text": "A description of an instance in an instanced geometry acceleration structure that the GPU can populate.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@MTLIndirectAccelerationStructureInstanceDescriptor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLIndirectAccelerationStructureInstanceDescriptor"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLIndirectAccelerationStructureInstanceDescriptor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "MTLIndirectAccelerationStructureInstanceDescriptor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLIndirectAccelerationStructureInstanceDescriptor"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceDescriptor": {
      "abstract": [
        {
          "text": "A description of an instance in an instanced geometry acceleration structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureInstanceDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureInstanceDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLAccelerationStructureInstanceDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructureinstancedescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions": {
      "abstract": [
        {
          "text": "Options for adjusting the behavior of an instanced acceleration structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureInstanceOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureInstanceOptions"
        }
      ],
      "role": "symbol",
      "title": "MTLAccelerationStructureInstanceOptions",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructureinstanceoptions"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureMotionInstanceDescriptor": {
      "abstract": [
        {
          "text": "A description of an instance in an instanced geometry acceleration structure, with the instance including a user identifier and motion data for the instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureMotionInstanceDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureMotionInstanceDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureMotionInstanceDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLAccelerationStructureMotionInstanceDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructuremotioninstancedescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureUserIDInstanceDescriptor": {
      "abstract": [
        {
          "text": "A description of an instance in an instanced geometry acceleration structure, with the instance including a user identifier for the instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureUserIDInstanceDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureUserIDInstanceDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureUserIDInstanceDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLAccelerationStructureUserIDInstanceDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructureuseridinstancedescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor": {
      "abstract": [
        {
          "text": "A description of an instance in an instanced geometry acceleration structure that the GPU can populate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIndirectAccelerationStructureInstanceDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIndirectAccelerationStructureInstanceDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLIndirectAccelerationStructureInstanceDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectaccelerationstructureinstancedescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/accelerationStructureID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accelerationStructureID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MTLResourceID",
          "text": "MTLResourceID"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/accelerationStructureID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accelerationStructureID"
        }
      ],
      "role": "symbol",
      "title": "accelerationStructureID",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectaccelerationstructureinstancedescriptor/accelerationstructureid"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectaccelerationstructureinstancedescriptor/init()"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/init(transformationMatrix:options:mask:intersectionFunctionTableOffset:userID:accelerationStructureID:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "transformationMatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "MTLPackedFloat4x3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLAccelerationStructureInstanceOptions",
          "text": "MTLAccelerationStructureInstanceOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "intersectionFunctionTableOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "userID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "accelerationStructureID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MTLResourceID",
          "text": "MTLResourceID"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/init(transformationMatrix:options:mask:intersectionFunctionTableOffset:userID:accelerationStructureID:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(transformationMatrix:options:mask:intersectionFunctionTableOffset:userID:accelerationStructureID:)",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectaccelerationstructureinstancedescriptor/init(transformationmatrix:options:mask:intersectionfunctiontableoffset:userid:accelerationstructureid:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/intersectionFunctionTableOffset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "intersectionFunctionTableOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/intersectionFunctionTableOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "intersectionFunctionTableOffset"
        }
      ],
      "role": "symbol",
      "title": "intersectionFunctionTableOffset",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectaccelerationstructureinstancedescriptor/intersectionfunctiontableoffset"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/mask": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/mask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mask"
        }
      ],
      "role": "symbol",
      "title": "mask",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectaccelerationstructureinstancedescriptor/mask"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/options": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLAccelerationStructureInstanceOptions",
          "text": "MTLAccelerationStructureInstanceOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/options",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "options"
        }
      ],
      "role": "symbol",
      "title": "options",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectaccelerationstructureinstancedescriptor/options"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/transformationMatrix": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transformationMatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "MTLPackedFloat4x3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/transformationMatrix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transformationMatrix"
        }
      ],
      "role": "symbol",
      "title": "transformationMatrix",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectaccelerationstructureinstancedescriptor/transformationmatrix"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/userID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/userID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userID"
        }
      ],
      "role": "symbol",
      "title": "userID",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectaccelerationstructureinstancedescriptor/userid"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureMotionInstanceDescriptor": {
      "abstract": [
        {
          "text": "A description of an instance in an acceleration structure that the GPU can populate, with motion data for the instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIndirectAccelerationStructureMotionInstanceDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureMotionInstanceDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIndirectAccelerationStructureMotionInstanceDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLIndirectAccelerationStructureMotionInstanceDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectaccelerationstructuremotioninstancedescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor": {
      "abstract": [
        {
          "text": "A description of an acceleration structure that Metal derives from instances of primitive acceleration structures that the GPU can populate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIndirectInstanceAccelerationStructureDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIndirectInstanceAccelerationStructureDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLIndirectInstanceAccelerationStructureDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlindirectinstanceaccelerationstructuredescriptor"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Descriptors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceDescriptor",
        "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureUserIDInstanceDescriptor",
        "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureMotionInstanceDescriptor",
        "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureMotionInstanceDescriptor"
      ],
      "title": "Instance Descriptors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/init()",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/init(transformationMatrix:options:mask:intersectionFunctionTableOffset:userID:accelerationStructureID:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/accelerationStructureID",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/intersectionFunctionTableOffset",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/mask",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/options",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/transformationMatrix",
        "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/userID"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLIndirectAccelerationStructureInstanceDescriptor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIndirectAccelerationStructureInstanceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIndirectAccelerationStructureInstanceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/accelerationStructureID",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/intersectionFunctionTableOffset",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/mask",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/options",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/transformationMatrix",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureInstanceDescriptor/userID"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-Descriptors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceDescriptor",
                "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureUserIDInstanceDescriptor",
                "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureMotionInstanceDescriptor",
                "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectInstanceAccelerationStructureDescriptor",
                "doc://com.apple.metal/documentation/Metal/MTLIndirectAccelerationStructureMotionInstanceDescriptor"
              ],
              "title": "Instance Descriptors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLIndirectAccelerationStructureInstanceDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor/title",
          "value": "MTLIndirectInstanceAccelerationStructureDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIndirectInstanceAccelerationStructureDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectInstanceAccelerationStructureDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIndirectInstanceAccelerationStructureDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureUserIDInstanceDescriptor/title",
          "value": "MTLAccelerationStructureUserIDInstanceDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureUserIDInstanceDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureUserIDInstanceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureUserIDInstanceDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureUserIDInstanceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureMotionInstanceDescriptor/title",
          "value": "MTLAccelerationStructureMotionInstanceDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureMotionInstanceDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureMotionInstanceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureMotionInstanceDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureMotionInstanceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureInstanceOptions/title",
          "value": "MTLAccelerationStructureInstanceOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureInstanceOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureInstanceOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureInstanceOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureInstanceOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureInstanceDescriptor/title",
          "value": "MTLAccelerationStructureInstanceDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureInstanceDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureInstanceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureInstanceDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureInstanceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectAccelerationStructureInstanceDescriptor~1options/title",
          "value": "options"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectAccelerationStructureInstanceDescriptor~1options/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectAccelerationStructureInstanceDescriptor/title",
          "value": "MTLIndirectAccelerationStructureInstanceDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectAccelerationStructureInstanceDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIndirectAccelerationStructureInstanceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectAccelerationStructureInstanceDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIndirectAccelerationStructureInstanceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectAccelerationStructureInstanceDescriptor~1accelerationStructureID/title",
          "value": "accelerationStructureID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectAccelerationStructureInstanceDescriptor~1accelerationStructureID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "accelerationStructureID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectAccelerationStructureInstanceDescriptor~1userID/title",
          "value": "userID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectAccelerationStructureInstanceDescriptor~1userID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectAccelerationStructureInstanceDescriptor~1mask/title",
          "value": "mask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectAccelerationStructureInstanceDescriptor~1mask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectAccelerationStructureMotionInstanceDescriptor/title",
          "value": "MTLIndirectAccelerationStructureMotionInstanceDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectAccelerationStructureMotionInstanceDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIndirectAccelerationStructureMotionInstanceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectAccelerationStructureMotionInstanceDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIndirectAccelerationStructureMotionInstanceDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectAccelerationStructureInstanceDescriptor~1transformationMatrix/title",
          "value": "transformationMatrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectAccelerationStructureInstanceDescriptor~1transformationMatrix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "transformationMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectAccelerationStructureInstanceDescriptor~1intersectionFunctionTableOffset/title",
          "value": "intersectionFunctionTableOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectAccelerationStructureInstanceDescriptor~1intersectionFunctionTableOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "intersectionFunctionTableOffset"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlindirectaccelerationstructureinstancedescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlindirectaccelerationstructureinstancedescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
