{
  "abstract": [
    {
      "text": "An indication of whether the compiler can perform optimizations for floating-point arithmetic that may violate the IEEE 754 standard.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLMathMode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLMathMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLMathMode"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLMathMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTLMathMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLMathMode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLArgumentBuffersTier": {
      "abstract": [
        {
          "text": "The values that determine the limits and capabilities of argument buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLArgumentBuffersTier"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLArgumentBuffersTier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLArgumentBuffersTier"
        }
      ],
      "role": "symbol",
      "title": "MTLArgumentBuffersTier",
      "type": "topic",
      "url": "/documentation/metal/mtlargumentbufferstier"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLogStateError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLLogStateError"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLogStateError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLogStateError"
        }
      ],
      "role": "symbol",
      "title": "MTLLogStateError",
      "type": "topic",
      "url": "/documentation/metal/mtllogstateerror"
    },
    "doc://com.apple.metal/documentation/Metal/MTLMathFloatingPointFunctions": {
      "abstract": [
        {
          "text": "Indicates which FP32 math functions Metal uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLMathFloatingPointFunctions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLMathFloatingPointFunctions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLMathFloatingPointFunctions"
        }
      ],
      "role": "symbol",
      "title": "MTLMathFloatingPointFunctions",
      "type": "topic",
      "url": "/documentation/metal/mtlmathfloatingpointfunctions"
    },
    "doc://com.apple.metal/documentation/Metal/MTLMathMode": {
      "abstract": [
        {
          "text": "An indication of whether the compiler can perform optimizations for floating-point arithmetic that may violate the IEEE 754 standard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLMathMode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLMathMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLMathMode"
        }
      ],
      "role": "symbol",
      "title": "MTLMathMode",
      "type": "topic",
      "url": "/documentation/metal/mtlmathmode"
    },
    "doc://com.apple.metal/documentation/Metal/MTLMathMode/fast": {
      "abstract": [
        {
          "text": "An indicator of the mode the compiler uses to make aggressive, potentially lossy assumptions about floating-point math.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fast"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLMathMode/fast",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLMathModeFast"
        }
      ],
      "role": "symbol",
      "title": "MTLMathMode.fast",
      "type": "topic",
      "url": "/documentation/metal/mtlmathmode/fast"
    },
    "doc://com.apple.metal/documentation/Metal/MTLMathMode/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLMathMode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/metal/mtlmathmode/init(rawvalue:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLMathMode/relaxed": {
      "abstract": [
        {
          "text": "An indicator of the mode the compiler uses to make aggressive, potentially lossy assumptions about floating-point math, while honoring Inf/NaN.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "relaxed"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLMathMode/relaxed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLMathModeRelaxed"
        }
      ],
      "role": "symbol",
      "title": "MTLMathMode.relaxed",
      "type": "topic",
      "url": "/documentation/metal/mtlmathmode/relaxed"
    },
    "doc://com.apple.metal/documentation/Metal/MTLMathMode/safe": {
      "abstract": [
        {
          "text": "An indicator of the mode the compiler uses to disable unsafe floating-point optimizations by preventing the compiler from making any transformations that could affect the results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "safe"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLMathMode/safe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLMathModeSafe"
        }
      ],
      "role": "symbol",
      "title": "MTLMathMode.safe",
      "type": "topic",
      "url": "/documentation/metal/mtlmathmode/safe"
    },
    "doc://com.apple.metal/documentation/Metal/MTLMatrixLayout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLMatrixLayout"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLMatrixLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLMatrixLayout"
        }
      ],
      "role": "symbol",
      "title": "MTLMatrixLayout",
      "type": "topic",
      "url": "/documentation/metal/mtlmatrixlayout"
    },
    "doc://com.apple.metal/documentation/Metal/MTLReadWriteTextureTier": {
      "abstract": [
        {
          "text": "The support level for read-write texture formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLReadWriteTextureTier"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLReadWriteTextureTier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLReadWriteTextureTier"
        }
      ],
      "role": "symbol",
      "title": "MTLReadWriteTextureTier",
      "type": "topic",
      "url": "/documentation/metal/mtlreadwritetexturetier"
    },
    "doc://com.apple.metal/documentation/Metal/MTLShaderValidation": {
      "abstract": [
        {
          "text": "Indicates whether shader validation in an enabled or disabled state, or neither state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLShaderValidation"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLShaderValidation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLShaderValidation"
        }
      ],
      "role": "symbol",
      "title": "MTLShaderValidation",
      "type": "topic",
      "url": "/documentation/metal/mtlshadervalidation"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTransformType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLTransformType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTransformType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTransformType"
        }
      ],
      "role": "symbol",
      "title": "MTLTransformType",
      "type": "topic",
      "url": "/documentation/metal/mtltransformtype"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLArgumentBuffersTier",
        "doc://com.apple.metal/documentation/Metal/MTLLogStateError",
        "doc://com.apple.metal/documentation/Metal/MTLMathFloatingPointFunctions",
        "doc://com.apple.metal/documentation/Metal/MTLMatrixLayout",
        "doc://com.apple.metal/documentation/Metal/MTLReadWriteTextureTier",
        "doc://com.apple.metal/documentation/Metal/MTLShaderValidation",
        "doc://com.apple.metal/documentation/Metal/MTLTransformType"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Modes",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLMathMode/fast",
        "doc://com.apple.metal/documentation/Metal/MTLMathMode/relaxed",
        "doc://com.apple.metal/documentation/Metal/MTLMathMode/safe"
      ],
      "title": "Modes"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLMathMode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLMathMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLMathMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLMathMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Modes",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLMathMode/fast",
                "doc://com.apple.metal/documentation/Metal/MTLMathMode/relaxed",
                "doc://com.apple.metal/documentation/Metal/MTLMathMode/safe"
              ],
              "title": "Modes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLArgumentBuffersTier",
                "doc://com.apple.metal/documentation/Metal/MTLLogStateError",
                "doc://com.apple.metal/documentation/Metal/MTLMathFloatingPointFunctions",
                "doc://com.apple.metal/documentation/Metal/MTLMatrixLayout",
                "doc://com.apple.metal/documentation/Metal/MTLReadWriteTextureTier",
                "doc://com.apple.metal/documentation/Metal/MTLShaderValidation",
                "doc://com.apple.metal/documentation/Metal/MTLTransformType"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLMathMode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMatrixLayout/title",
          "value": "MTLMatrixLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMatrixLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLMatrixLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMatrixLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLMatrixLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMathMode/title",
          "value": "MTLMathMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMathMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLMathMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMathMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLMathMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTransformType/title",
          "value": "MTLTransformType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTransformType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTransformType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTransformType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTransformType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentBuffersTier/title",
          "value": "MTLArgumentBuffersTier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentBuffersTier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentBuffersTier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLArgumentBuffersTier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLArgumentBuffersTier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMathMode~1safe/title",
          "value": "MTLMathModeSafe"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMathMode~1safe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLMathModeSafe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLReadWriteTextureTier/title",
          "value": "MTLReadWriteTextureTier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLReadWriteTextureTier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLReadWriteTextureTier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLReadWriteTextureTier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLReadWriteTextureTier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMathFloatingPointFunctions/title",
          "value": "MTLMathFloatingPointFunctions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMathFloatingPointFunctions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLMathFloatingPointFunctions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMathFloatingPointFunctions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLMathFloatingPointFunctions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMathMode~1relaxed/title",
          "value": "MTLMathModeRelaxed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMathMode~1relaxed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLMathModeRelaxed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLShaderValidation/title",
          "value": "MTLShaderValidation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLShaderValidation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLShaderValidation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLShaderValidation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLShaderValidation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogStateError/title",
          "value": "MTLLogStateError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogStateError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLogStateError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLogStateError/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLogStateError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMathMode~1fast/title",
          "value": "MTLMathModeFast"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMathMode~1fast/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLMathModeFast"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlmathmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlmathmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
