{
  "abstract": [
    {
      "text": "Optional arguments used to set the behavior of a resource.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLResourceOptions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLResourceOptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLResourceOptions"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLResourceOptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "MTLResourceOptions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLResourceOptions"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.metal/documentation/Metal/setting-resource-storage-modes"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAllocation": {
      "abstract": [
        {
          "text": "A memory allocation from a Metal GPU device, such as a memory heap, texture, or data buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAllocation"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAllocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAllocation"
        }
      ],
      "role": "symbol",
      "title": "MTLAllocation",
      "type": "topic",
      "url": "/documentation/metal/mtlallocation"
    },
    "doc://com.apple.metal/documentation/Metal/MTLResource": {
      "abstract": [
        {
          "text": "An allocation of memory accessible to a GPU.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLResource"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLResource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLResource"
        }
      ],
      "role": "symbol",
      "title": "MTLResource",
      "type": "topic",
      "url": "/documentation/metal/mtlresource"
    },
    "doc://com.apple.metal/documentation/Metal/MTLResourceID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLResourceID"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLResourceID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLResourceID"
        }
      ],
      "role": "symbol",
      "title": "MTLResourceID",
      "type": "topic",
      "url": "/documentation/metal/mtlresourceid"
    },
    "doc://com.apple.metal/documentation/Metal/MTLResourceOptions": {
      "abstract": [
        {
          "text": "Optional arguments used to set the behavior of a resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLResourceOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLResourceOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLResourceOptions"
        }
      ],
      "role": "symbol",
      "title": "MTLResourceOptions",
      "type": "topic",
      "url": "/documentation/metal/mtlresourceoptions"
    },
    "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/MTLResourceCPUCacheModeDefaultCache": {
      "abstract": [
        {
          "text": "The default CPU cache mode for the resource, which guarantees that read and write operations are executed in the expected order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTLResourceCPUCacheModeDefaultCache"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/MTLResourceCPUCacheModeDefaultCache",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLResourceCPUCacheModeDefaultCache",
      "type": "topic",
      "url": "/documentation/metal/mtlresourceoptions/mtlresourcecpucachemodedefaultcache"
    },
    "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/MTLResourceHazardTrackingModeDefault": {
      "abstract": [
        {
          "text": "An option specifying that the default tracking mode should be used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTLResourceHazardTrackingModeDefault"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/MTLResourceHazardTrackingModeDefault",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLResourceHazardTrackingModeDefault",
      "type": "topic",
      "url": "/documentation/metal/mtlresourceoptions/mtlresourcehazardtrackingmodedefault"
    },
    "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/MTLResourceOptionCPUCacheModeDefault": {
      "abstract": [
        {
          "text": "This constant was deprecated in iOS 9.0 and macOS 10.11.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTLResourceOptionCPUCacheModeDefault"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/MTLResourceOptionCPUCacheModeDefault",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLResourceOptionCPUCacheModeDefault",
      "type": "topic",
      "url": "/documentation/metal/mtlresourceoptions/mtlresourceoptioncpucachemodedefault"
    },
    "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/cpuCacheModeWriteCombined": {
      "abstract": [
        {
          "text": "A write-combined CPU cache mode that is optimized for resources that the CPU writes into, but never reads.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cpuCacheModeWriteCombined"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLResourceOptions",
          "text": "MTLResourceOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/cpuCacheModeWriteCombined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLResourceCPUCacheModeWriteCombined"
        }
      ],
      "role": "symbol",
      "title": "cpuCacheModeWriteCombined",
      "type": "topic",
      "url": "/documentation/metal/mtlresourceoptions/cpucachemodewritecombined"
    },
    "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/hazardTrackingModeTracked": {
      "abstract": [
        {
          "text": "An option specifying that Metal prevents hazards when modifying this object’s contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hazardTrackingModeTracked"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLResourceOptions",
          "text": "MTLResourceOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/hazardTrackingModeTracked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLResourceHazardTrackingModeTracked"
        }
      ],
      "role": "symbol",
      "title": "hazardTrackingModeTracked",
      "type": "topic",
      "url": "/documentation/metal/mtlresourceoptions/hazardtrackingmodetracked"
    },
    "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/hazardTrackingModeUntracked": {
      "abstract": [
        {
          "text": "An option specifying that the app must prevent hazards when modifying this object’s contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hazardTrackingModeUntracked"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLResourceOptions",
          "text": "MTLResourceOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/hazardTrackingModeUntracked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLResourceHazardTrackingModeUntracked"
        }
      ],
      "role": "symbol",
      "title": "hazardTrackingModeUntracked",
      "type": "topic",
      "url": "/documentation/metal/mtlresourceoptions/hazardtrackingmodeuntracked"
    },
    "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/metal/mtlresourceoptions/init(rawvalue:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/optionCPUCacheModeWriteCombined": {
      "abstract": [
        {
          "text": "This constant was deprecated in iOS 9.0 and macOS 10.11.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "optionCPUCacheModeWriteCombined"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLResourceOptions",
          "text": "MTLResourceOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/optionCPUCacheModeWriteCombined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLResourceOptionCPUCacheModeWriteCombined"
        }
      ],
      "role": "symbol",
      "title": "optionCPUCacheModeWriteCombined",
      "type": "topic",
      "url": "/documentation/metal/mtlresourceoptions/optioncpucachemodewritecombined"
    },
    "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/storageModeManaged": {
      "abstract": [
        {
          "text": "The CPU and GPU may maintain separate copies of the resource, and any changes must be explicitly synchronized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "storageModeManaged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLResourceOptions",
          "text": "MTLResourceOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/storageModeManaged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLResourceStorageModeManaged"
        }
      ],
      "role": "symbol",
      "title": "storageModeManaged",
      "type": "topic",
      "url": "/documentation/metal/mtlresourceoptions/storagemodemanaged"
    },
    "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/storageModeMemoryless": {
      "abstract": [
        {
          "text": "The resource’s contents are only available to the GPU, and only exist temporarily during a render pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "storageModeMemoryless"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLResourceOptions",
          "text": "MTLResourceOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/storageModeMemoryless",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLResourceStorageModeMemoryless"
        }
      ],
      "role": "symbol",
      "title": "storageModeMemoryless",
      "type": "topic",
      "url": "/documentation/metal/mtlresourceoptions/storagemodememoryless"
    },
    "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/storageModePrivate": {
      "abstract": [
        {
          "text": "The resource is only available to the GPU.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "storageModePrivate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLResourceOptions",
          "text": "MTLResourceOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/storageModePrivate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLResourceStorageModePrivate"
        }
      ],
      "role": "symbol",
      "title": "storageModePrivate",
      "type": "topic",
      "url": "/documentation/metal/mtlresourceoptions/storagemodeprivate"
    },
    "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/storageModeShared": {
      "abstract": [
        {
          "text": "The CPU and GPU share access to the resource, allocated in system memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "storageModeShared"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLResourceOptions",
          "text": "MTLResourceOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/storageModeShared",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLResourceStorageModeShared"
        }
      ],
      "role": "symbol",
      "title": "storageModeShared",
      "type": "topic",
      "url": "/documentation/metal/mtlresourceoptions/storagemodeshared"
    },
    "doc://com.apple.metal/documentation/Metal/MTLResourceUsage": {
      "abstract": [
        {
          "text": "Options that describe how a graphics or compute function uses an argument buffer’s resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLResourceUsage"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLResourceUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLResourceUsage"
        }
      ],
      "role": "symbol",
      "title": "MTLResourceUsage",
      "type": "topic",
      "url": "/documentation/metal/mtlresourceusage"
    },
    "doc://com.apple.metal/documentation/Metal/setting-resource-storage-modes": {
      "abstract": [
        {
          "text": "Set a storage mode that defines the memory location and access permissions of a resource.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/setting-resource-storage-modes",
      "kind": "article",
      "role": "article",
      "title": "Setting Resource Storage Modes",
      "type": "topic",
      "url": "/documentation/metal/setting-resource-storage-modes"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Common-Resource-Functionality",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLAllocation",
        "doc://com.apple.metal/documentation/Metal/MTLResource",
        "doc://com.apple.metal/documentation/Metal/MTLResourceUsage",
        "doc://com.apple.metal/documentation/Metal/MTLResourceID"
      ],
      "title": "Common Resource Functionality"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializing-Resource-Options",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/init(rawValue:)"
      ],
      "title": "Initializing Resource Options"
    },
    {
      "anchor": "Specifying-CPU-Cache-Modes",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/cpuCacheModeWriteCombined"
      ],
      "title": "Specifying CPU Cache Modes"
    },
    {
      "anchor": "Specifying-Storage-Modes",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/storageModeShared",
        "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/storageModeManaged",
        "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/storageModePrivate",
        "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/storageModeMemoryless"
      ],
      "title": "Specifying Storage Modes"
    },
    {
      "anchor": "Specifying-Hazard-Tracking",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/hazardTrackingModeTracked",
        "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/hazardTrackingModeUntracked"
      ],
      "title": "Specifying Hazard Tracking"
    },
    {
      "anchor": "Deprecated-Options",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/optionCPUCacheModeWriteCombined"
      ],
      "title": "Deprecated Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLResourceOptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResourceOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResourceOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Specifying-CPU-Cache-Modes",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/MTLResourceCPUCacheModeDefaultCache",
                "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/cpuCacheModeWriteCombined"
              ],
              "title": "Specifying CPU Cache Modes"
            },
            {
              "anchor": "Specifying-Storage-Modes",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/storageModeShared",
                "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/storageModeManaged",
                "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/storageModePrivate",
                "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/storageModeMemoryless"
              ],
              "title": "Specifying Storage Modes"
            },
            {
              "anchor": "Specifying-Hazard-Tracking",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/MTLResourceHazardTrackingModeDefault",
                "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/hazardTrackingModeTracked",
                "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/hazardTrackingModeUntracked"
              ],
              "title": "Specifying Hazard Tracking"
            },
            {
              "anchor": "Deprecated-Options",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/MTLResourceOptionCPUCacheModeDefault",
                "doc://com.apple.metal/documentation/Metal/MTLResourceOptions/optionCPUCacheModeWriteCombined"
              ],
              "title": "Deprecated Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Common-Resource-Functionality",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLAllocation",
                "doc://com.apple.metal/documentation/Metal/MTLResource",
                "doc://com.apple.metal/documentation/Metal/MTLResourceUsage",
                "doc://com.apple.metal/documentation/Metal/MTLResourceID"
              ],
              "title": "Common Resource Functionality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLResourceOptions"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResource/title",
          "value": "MTLResource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceOptions~1storageModeManaged/title",
          "value": "MTLResourceStorageModeManaged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceOptions~1storageModeManaged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResourceStorageModeManaged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceOptions~1storageModeShared/title",
          "value": "MTLResourceStorageModeShared"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceOptions~1storageModeShared/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResourceStorageModeShared"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceOptions~1hazardTrackingModeUntracked/title",
          "value": "MTLResourceHazardTrackingModeUntracked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceOptions~1hazardTrackingModeUntracked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResourceHazardTrackingModeUntracked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceOptions~1storageModeMemoryless/title",
          "value": "MTLResourceStorageModeMemoryless"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceOptions~1storageModeMemoryless/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResourceStorageModeMemoryless"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceID/title",
          "value": "MTLResourceID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResourceID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResourceID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceOptions/title",
          "value": "MTLResourceOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResourceOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResourceOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceOptions~1cpuCacheModeWriteCombined/title",
          "value": "MTLResourceCPUCacheModeWriteCombined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceOptions~1cpuCacheModeWriteCombined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResourceCPUCacheModeWriteCombined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceOptions~1hazardTrackingModeTracked/title",
          "value": "MTLResourceHazardTrackingModeTracked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceOptions~1hazardTrackingModeTracked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResourceHazardTrackingModeTracked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceUsage/title",
          "value": "MTLResourceUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResourceUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceUsage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResourceUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceOptions~1optionCPUCacheModeWriteCombined/title",
          "value": "MTLResourceOptionCPUCacheModeWriteCombined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceOptions~1optionCPUCacheModeWriteCombined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResourceOptionCPUCacheModeWriteCombined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceOptions~1storageModePrivate/title",
          "value": "MTLResourceStorageModePrivate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResourceOptions~1storageModePrivate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLResourceStorageModePrivate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAllocation/title",
          "value": "MTLAllocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAllocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAllocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAllocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAllocation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlresourceoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlresourceoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
