{
  "abstract": [
    {
      "text": "A render target that serves as the output destination for pixels generated by a render pass.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTLRenderPassAttachmentDescriptor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLRenderPassAttachmentDescriptor"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLRenderPassAttachmentDescriptor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTLRenderPassAttachmentDescriptor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLRenderPassAttachmentDescriptor"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.metal/documentation/Metal/setting-load-and-store-actions",
        "doc://com.apple.metal/documentation/Metal/choosing-a-resource-storage-mode-for-apple-gpus"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to configure an individual render target of a framebuffer. Each ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object specifies one texture that a graphics rendering pass can write into.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Typically, you don’t directly create ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects. Instead, the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassDescriptor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object creates a default set of attachment objects. For each attachment that you intend to use as a render target, retrieve the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object from the render pass descriptor and configure its properties for use during this rendering pass.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You must set the attachment’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/texture",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/level",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/slice",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/depthPlane",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties specify the mipmap level, slice, and depth plane (for 3D textures) of the texture, respectively.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/loadAction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/storeAction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties specify actions to perform at the start and end of a rendering pass for the attachment, respectively. For example, if you set the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/loadAction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of an attachment to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLLoadAction/clear",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", then the contents of the texture fill with a value for the type of attachment at the start of the rendering pass.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "There are specific ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " subclasses for color, depth, and stencil attachments. Each subclass provides additional properties to configure for that kind of attachment. The table below provides the list of subclasses.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Attachment type",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Descriptor subclass",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Color",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassColorAttachmentDescriptor",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Depth",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassDepthAttachmentDescriptor",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Stencil",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassStencilAttachmentDescriptor",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "anchor": "Multisampling",
          "level": 3,
          "text": "Multisampling",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To perform multisampled antialiased rendering, you use two textures. Attach to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/texture",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureType/type2DMultisample",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " texture, and a 2D or cube texture to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveTexture",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property. When a rendering command executes, it renders to the multisample texture. At the end of the render pass, the GPU resolves the contents of the multisample texture and writes the results into the resolve texture. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveLevel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveSlice",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveDepthPlane",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties specify where the resolved image is written to. The attachment’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/storeAction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property determines what happens to the multisample texture after the GPU resolves its data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLClearColor": {
      "abstract": [
        {
          "text": "An RGBA value used for a color pixel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLClearColor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLClearColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLClearColor"
        }
      ],
      "role": "symbol",
      "title": "MTLClearColor",
      "type": "topic",
      "url": "/documentation/metal/mtlclearcolor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLoadAction/clear": {
      "abstract": [
        {
          "text": "The GPU writes a value to every pixel in the attachment at the start of the render pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clear"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLoadAction/clear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLoadActionClear"
        }
      ],
      "role": "symbol",
      "title": "MTLLoadAction.clear",
      "type": "topic",
      "url": "/documentation/metal/mtlloadaction/clear"
    },
    "doc://com.apple.metal/documentation/Metal/MTLMultisampleDepthResolveFilter": {
      "abstract": [
        {
          "text": "Filtering options for controlling an MSAA depth resolve operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLMultisampleDepthResolveFilter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLMultisampleDepthResolveFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLMultisampleDepthResolveFilter"
        }
      ],
      "role": "symbol",
      "title": "MTLMultisampleDepthResolveFilter",
      "type": "topic",
      "url": "/documentation/metal/mtlmultisampledepthresolvefilter"
    },
    "doc://com.apple.metal/documentation/Metal/MTLMultisampleStencilResolveFilter": {
      "abstract": [
        {
          "text": "Constants used to control the multisample stencil resolve operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLMultisampleStencilResolveFilter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLMultisampleStencilResolveFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLMultisampleStencilResolveFilter"
        }
      ],
      "role": "symbol",
      "title": "MTLMultisampleStencilResolveFilter",
      "type": "topic",
      "url": "/documentation/metal/mtlmultisamplestencilresolvefilter"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor": {
      "abstract": [
        {
          "text": "A render target that serves as the output destination for pixels generated by a render pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLRenderPassAttachmentDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLRenderPassAttachmentDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLRenderPassAttachmentDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassattachmentdescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/depthPlane": {
      "abstract": [
        {
          "text": "The depth plane of the texture used for rendering to the attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "depthPlane"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/depthPlane",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "depthPlane"
        }
      ],
      "role": "symbol",
      "title": "depthPlane",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassattachmentdescriptor/depthplane"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/level": {
      "abstract": [
        {
          "text": "The mipmap level of the texture used for rendering to the attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "level"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/level",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "level"
        }
      ],
      "role": "symbol",
      "title": "level",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassattachmentdescriptor/level"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/loadAction": {
      "abstract": [
        {
          "text": "The action performed by this attachment at the start of a rendering pass for a render command encoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLLoadAction",
          "text": "MTLLoadAction"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/loadAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadAction"
        }
      ],
      "role": "symbol",
      "title": "loadAction",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassattachmentdescriptor/loadaction"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveDepthPlane": {
      "abstract": [
        {
          "text": "The depth plane of the texture used for the multisample resolve action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveDepthPlane"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveDepthPlane",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveDepthPlane"
        }
      ],
      "role": "symbol",
      "title": "resolveDepthPlane",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassattachmentdescriptor/resolvedepthplane"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveLevel": {
      "abstract": [
        {
          "text": "The mipmap level of the texture used for the multisample resolve action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveLevel"
        }
      ],
      "role": "symbol",
      "title": "resolveLevel",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassattachmentdescriptor/resolvelevel"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveSlice": {
      "abstract": [
        {
          "text": "The slice of the texture used for the multisample resolve action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveSlice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveSlice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveSlice"
        }
      ],
      "role": "symbol",
      "title": "resolveSlice",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassattachmentdescriptor/resolveslice"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveTexture": {
      "abstract": [
        {
          "text": "The destination texture used when resolving multisampled texture data into single sample values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveTexture"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveTexture"
        }
      ],
      "role": "symbol",
      "title": "resolveTexture",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassattachmentdescriptor/resolvetexture"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/slice": {
      "abstract": [
        {
          "text": "The slice of the texture used for rendering to the attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "slice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/slice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "slice"
        }
      ],
      "role": "symbol",
      "title": "slice",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassattachmentdescriptor/slice"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/storeAction": {
      "abstract": [
        {
          "text": "The action performed by this attachment at the end of a rendering pass for a render command encoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "storeAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLStoreAction",
          "text": "MTLStoreAction"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/storeAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "storeAction"
        }
      ],
      "role": "symbol",
      "title": "storeAction",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassattachmentdescriptor/storeaction"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/storeActionOptions": {
      "abstract": [
        {
          "text": "The options that modify the store action performed by this attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "storeActionOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLStoreActionOptions",
          "text": "MTLStoreActionOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/storeActionOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "storeActionOptions"
        }
      ],
      "role": "symbol",
      "title": "storeActionOptions",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassattachmentdescriptor/storeactionoptions"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/texture": {
      "abstract": [
        {
          "text": "The texture object associated with this attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "texture"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/texture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "texture"
        }
      ],
      "role": "symbol",
      "title": "texture",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassattachmentdescriptor/texture"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassColorAttachmentDescriptor": {
      "abstract": [
        {
          "text": "A color render target that serves as the output destination for color pixels generated by a render pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLRenderPassColorAttachmentDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassColorAttachmentDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLRenderPassColorAttachmentDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLRenderPassColorAttachmentDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpasscolorattachmentdescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassColorAttachmentDescriptorArray": {
      "abstract": [
        {
          "text": "An array of render pass color attachment descriptor objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLRenderPassColorAttachmentDescriptorArray"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassColorAttachmentDescriptorArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLRenderPassColorAttachmentDescriptorArray"
        }
      ],
      "role": "symbol",
      "title": "MTLRenderPassColorAttachmentDescriptorArray",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpasscolorattachmentdescriptorarray"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassDepthAttachmentDescriptor": {
      "abstract": [
        {
          "text": "A depth render target that serves as the output destination for depth pixels generated by a render pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLRenderPassDepthAttachmentDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassDepthAttachmentDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLRenderPassDepthAttachmentDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLRenderPassDepthAttachmentDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassdepthattachmentdescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassDescriptor": {
      "abstract": [
        {
          "text": "A group of render targets that hold the results of a render pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLRenderPassDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLRenderPassDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLRenderPassDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassdescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassSampleBufferAttachmentDescriptor": {
      "abstract": [
        {
          "text": "A description of where to store GPU counter information at the start and end of a render pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLRenderPassSampleBufferAttachmentDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassSampleBufferAttachmentDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLRenderPassSampleBufferAttachmentDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLRenderPassSampleBufferAttachmentDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpasssamplebufferattachmentdescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassSampleBufferAttachmentDescriptorArray": {
      "abstract": [
        {
          "text": "An array of sample buffer attachments for a render pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLRenderPassSampleBufferAttachmentDescriptorArray"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassSampleBufferAttachmentDescriptorArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLRenderPassSampleBufferAttachmentDescriptorArray"
        }
      ],
      "role": "symbol",
      "title": "MTLRenderPassSampleBufferAttachmentDescriptorArray",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpasssamplebufferattachmentdescriptorarray"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassStencilAttachmentDescriptor": {
      "abstract": [
        {
          "text": "A stencil render target that serves as the output destination for stencil pixels generated by a render pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLRenderPassStencilAttachmentDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassStencilAttachmentDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLRenderPassStencilAttachmentDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLRenderPassStencilAttachmentDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassstencilattachmentdescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureType/type2DMultisample": {
      "abstract": [
        {
          "text": "A two-dimensional texture image that uses more than one sample for each pixel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type2DMultisample"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureType/type2DMultisample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTextureType2DMultisample"
        }
      ],
      "role": "symbol",
      "title": "MTLTextureType.type2DMultisample",
      "type": "topic",
      "url": "/documentation/metal/mtltexturetype/type2dmultisample"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTileRenderPipelineColorAttachmentDescriptorArray": {
      "abstract": [
        {
          "text": "An array of color attachment descriptors for the tile render pipeline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLTileRenderPipelineColorAttachmentDescriptorArray"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTileRenderPipelineColorAttachmentDescriptorArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTileRenderPipelineColorAttachmentDescriptorArray"
        }
      ],
      "role": "symbol",
      "title": "MTLTileRenderPipelineColorAttachmentDescriptorArray",
      "type": "topic",
      "url": "/documentation/metal/mtltilerenderpipelinecolorattachmentdescriptorarray"
    },
    "doc://com.apple.metal/documentation/Metal/choosing-a-resource-storage-mode-for-apple-gpus": {
      "abstract": [
        {
          "text": "Select an appropriate storage mode for your textures and buffers on Apple GPUs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/choosing-a-resource-storage-mode-for-apple-gpus",
      "kind": "article",
      "role": "article",
      "title": "Choosing a Resource Storage Mode for Apple GPUs",
      "type": "topic",
      "url": "/documentation/metal/choosing-a-resource-storage-mode-for-apple-gpus"
    },
    "doc://com.apple.metal/documentation/Metal/setting-load-and-store-actions": {
      "abstract": [
        {
          "text": "Set actions that define how a render pass loads and stores a render target.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/setting-load-and-store-actions",
      "kind": "article",
      "role": "article",
      "title": "Setting Load and Store Actions",
      "type": "topic",
      "url": "/documentation/metal/setting-load-and-store-actions"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLRenderPassColorAttachmentDescriptor",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPassDepthAttachmentDescriptor",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPassStencilAttachmentDescriptor"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-a-Render-Command-Encoder",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLRenderPassDescriptor",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPassColorAttachmentDescriptorArray",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPassColorAttachmentDescriptor",
        "doc://com.apple.metal/documentation/Metal/MTLClearColor",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPassDepthAttachmentDescriptor",
        "doc://com.apple.metal/documentation/Metal/MTLMultisampleDepthResolveFilter",
        "doc://com.apple.metal/documentation/Metal/MTLTileRenderPipelineColorAttachmentDescriptorArray",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPassStencilAttachmentDescriptor",
        "doc://com.apple.metal/documentation/Metal/MTLMultisampleStencilResolveFilter",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPassSampleBufferAttachmentDescriptorArray",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPassSampleBufferAttachmentDescriptor"
      ],
      "title": "Configuring a Render Command Encoder"
    }
  ],
  "topicSections": [
    {
      "anchor": "Specifying-the-Texture-for-the-Attachment",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/texture",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/level",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/slice",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/depthPlane"
      ],
      "title": "Specifying the Texture for the Attachment"
    },
    {
      "anchor": "Specifying-Rendering-Pass-Actions",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/loadAction",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/storeAction",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/storeActionOptions"
      ],
      "title": "Specifying Rendering Pass Actions"
    },
    {
      "anchor": "Specifying-the-Texture-to-Resolve-Multisample-Data",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveTexture",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveLevel",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveSlice",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveDepthPlane"
      ],
      "title": "Specifying the Texture to Resolve Multisample Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLRenderPassAttachmentDescriptor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPassAttachmentDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPassAttachmentDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Specifying-the-Texture-for-the-Attachment",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/texture",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/level",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/slice",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/depthPlane"
              ],
              "title": "Specifying the Texture for the Attachment"
            },
            {
              "anchor": "Specifying-Rendering-Pass-Actions",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/loadAction",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/storeAction",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/storeActionOptions"
              ],
              "title": "Specifying Rendering Pass Actions"
            },
            {
              "anchor": "Specifying-the-Texture-to-Resolve-Multisample-Data",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveTexture",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveLevel",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveSlice",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveDepthPlane"
              ],
              "title": "Specifying the Texture to Resolve Multisample Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLRenderPassColorAttachmentDescriptor",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPassDepthAttachmentDescriptor",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPassStencilAttachmentDescriptor"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-a-Render-Command-Encoder",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLRenderPassDescriptor",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPassColorAttachmentDescriptorArray",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPassColorAttachmentDescriptor",
                "doc://com.apple.metal/documentation/Metal/MTLClearColor",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPassDepthAttachmentDescriptor",
                "doc://com.apple.metal/documentation/Metal/MTLMultisampleDepthResolveFilter",
                "doc://com.apple.metal/documentation/Metal/MTLTileRenderPipelineColorAttachmentDescriptorArray",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPassStencilAttachmentDescriptor",
                "doc://com.apple.metal/documentation/Metal/MTLMultisampleStencilResolveFilter",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPassSampleBufferAttachmentDescriptorArray",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPassSampleBufferAttachmentDescriptor"
              ],
              "title": "Configuring a Render Command Encoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLRenderPassAttachmentDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassStencilAttachmentDescriptor/title",
          "value": "MTLRenderPassStencilAttachmentDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassStencilAttachmentDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPassStencilAttachmentDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassStencilAttachmentDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPassStencilAttachmentDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1storeAction/title",
          "value": "storeAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1storeAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "storeAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassColorAttachmentDescriptor/title",
          "value": "MTLRenderPassColorAttachmentDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassColorAttachmentDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPassColorAttachmentDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassColorAttachmentDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPassColorAttachmentDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1resolveTexture/title",
          "value": "resolveTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1resolveTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resolveTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1depthPlane/title",
          "value": "depthPlane"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1depthPlane/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "depthPlane"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureType~1type2DMultisample/title",
          "value": "MTLTextureType2DMultisample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureType~1type2DMultisample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureType2DMultisample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1level/title",
          "value": "level"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1level/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "level"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1resolveSlice/title",
          "value": "resolveSlice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1resolveSlice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resolveSlice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor/title",
          "value": "MTLRenderPassAttachmentDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPassAttachmentDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPassAttachmentDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTileRenderPipelineColorAttachmentDescriptorArray/title",
          "value": "MTLTileRenderPipelineColorAttachmentDescriptorArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTileRenderPipelineColorAttachmentDescriptorArray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTileRenderPipelineColorAttachmentDescriptorArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTileRenderPipelineColorAttachmentDescriptorArray/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTileRenderPipelineColorAttachmentDescriptorArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1storeActionOptions/title",
          "value": "storeActionOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1storeActionOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "storeActionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassDescriptor/title",
          "value": "MTLRenderPassDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPassDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPassDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassColorAttachmentDescriptorArray/title",
          "value": "MTLRenderPassColorAttachmentDescriptorArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassColorAttachmentDescriptorArray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPassColorAttachmentDescriptorArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassColorAttachmentDescriptorArray/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPassColorAttachmentDescriptorArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassSampleBufferAttachmentDescriptor/title",
          "value": "MTLRenderPassSampleBufferAttachmentDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassSampleBufferAttachmentDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPassSampleBufferAttachmentDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassSampleBufferAttachmentDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPassSampleBufferAttachmentDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMultisampleDepthResolveFilter/title",
          "value": "MTLMultisampleDepthResolveFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMultisampleDepthResolveFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLMultisampleDepthResolveFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMultisampleDepthResolveFilter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLMultisampleDepthResolveFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1resolveLevel/title",
          "value": "resolveLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1resolveLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resolveLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLoadAction~1clear/title",
          "value": "MTLLoadActionClear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLoadAction~1clear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLoadActionClear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassSampleBufferAttachmentDescriptorArray/title",
          "value": "MTLRenderPassSampleBufferAttachmentDescriptorArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassSampleBufferAttachmentDescriptorArray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPassSampleBufferAttachmentDescriptorArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassSampleBufferAttachmentDescriptorArray/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPassSampleBufferAttachmentDescriptorArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1loadAction/title",
          "value": "loadAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1loadAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "loadAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1slice/title",
          "value": "slice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1slice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "slice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1texture/title",
          "value": "texture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1texture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "texture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassDepthAttachmentDescriptor/title",
          "value": "MTLRenderPassDepthAttachmentDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassDepthAttachmentDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPassDepthAttachmentDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassDepthAttachmentDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPassDepthAttachmentDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLClearColor/title",
          "value": "MTLClearColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLClearColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLClearColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLClearColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLClearColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1resolveDepthPlane/title",
          "value": "resolveDepthPlane"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1resolveDepthPlane/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resolveDepthPlane"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMultisampleStencilResolveFilter/title",
          "value": "MTLMultisampleStencilResolveFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMultisampleStencilResolveFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLMultisampleStencilResolveFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLMultisampleStencilResolveFilter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLMultisampleStencilResolveFilter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlrenderpassattachmentdescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlrenderpassattachmentdescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
