{
  "abstract": [
    {
      "text": "Values that determine the border color for clamped texture values when the sampler address mode is ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/clampToBorderColor",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLSamplerBorderColor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLSamplerBorderColor"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLSamplerBorderColor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTLSamplerBorderColor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLSamplerBorderColor"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode": {
      "abstract": [
        {
          "text": "Modes that determine the texture coordinate at each pixel when a fetch falls outside the bounds of a texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLSamplerAddressMode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSamplerAddressMode"
        }
      ],
      "role": "symbol",
      "title": "MTLSamplerAddressMode",
      "type": "topic",
      "url": "/documentation/metal/mtlsampleraddressmode"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/clampToBorderColor": {
      "abstract": [
        {
          "text": "Out-of-range texture coordinates return the value specified by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/borderColor",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clampToBorderColor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/clampToBorderColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSamplerAddressModeClampToBorderColor"
        }
      ],
      "role": "symbol",
      "title": "MTLSamplerAddressMode.clampToBorderColor",
      "type": "topic",
      "url": "/documentation/metal/mtlsampleraddressmode/clamptobordercolor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor": {
      "abstract": [
        {
          "text": "Values that determine the border color for clamped texture values when the sampler address mode is ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/clampToBorderColor",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLSamplerBorderColor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSamplerBorderColor"
        }
      ],
      "role": "symbol",
      "title": "MTLSamplerBorderColor",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerbordercolor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerbordercolor/init(rawvalue:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor/opaqueBlack": {
      "abstract": [
        {
          "text": "An opaque black color ",
          "type": "text"
        },
        {
          "code": "(0,0,0,1)",
          "type": "codeVoice"
        },
        {
          "text": " for texture values outside the border",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "opaqueBlack"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor/opaqueBlack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSamplerBorderColorOpaqueBlack"
        }
      ],
      "role": "symbol",
      "title": "MTLSamplerBorderColor.opaqueBlack",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerbordercolor/opaqueblack"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor/opaqueWhite": {
      "abstract": [
        {
          "text": "An opaque white color ",
          "type": "text"
        },
        {
          "code": "(1,1,1,1)",
          "type": "codeVoice"
        },
        {
          "text": " for texture values outside the border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "opaqueWhite"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor/opaqueWhite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSamplerBorderColorOpaqueWhite"
        }
      ],
      "role": "symbol",
      "title": "MTLSamplerBorderColor.opaqueWhite",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerbordercolor/opaquewhite"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor/transparentBlack": {
      "abstract": [
        {
          "text": "A transparent black color ",
          "type": "text"
        },
        {
          "code": "(0,0,0,0)",
          "type": "codeVoice"
        },
        {
          "text": " for texture values outside the border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transparentBlack"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor/transparentBlack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSamplerBorderColorTransparentBlack"
        }
      ],
      "role": "symbol",
      "title": "MTLSamplerBorderColor.transparentBlack",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerbordercolor/transparentblack"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/borderColor": {
      "abstract": [
        {
          "text": "The border color for clamped texture values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "borderColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLSamplerBorderColor",
          "text": "MTLSamplerBorderColor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/borderColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "borderColor"
        }
      ],
      "role": "symbol",
      "title": "borderColor",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerdescriptor/bordercolor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/rAddressMode": {
      "abstract": [
        {
          "text": "The address mode for the texture depth (r) coordinate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rAddressMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLSamplerAddressMode",
          "text": "MTLSamplerAddressMode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/rAddressMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rAddressMode"
        }
      ],
      "role": "symbol",
      "title": "rAddressMode",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerdescriptor/raddressmode"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/sAddressMode": {
      "abstract": [
        {
          "text": "The address mode for the texture width (s) coordinate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sAddressMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLSamplerAddressMode",
          "text": "MTLSamplerAddressMode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/sAddressMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sAddressMode"
        }
      ],
      "role": "symbol",
      "title": "sAddressMode",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerdescriptor/saddressmode"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/tAddressMode": {
      "abstract": [
        {
          "text": "The address mode for the texture height (t) coordinate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tAddressMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLSamplerAddressMode",
          "text": "MTLSamplerAddressMode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/tAddressMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tAddressMode"
        }
      ],
      "role": "symbol",
      "title": "tAddressMode",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerdescriptor/taddressmode"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Declaring-Addressing-Modes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/rAddressMode",
        "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/sAddressMode",
        "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/tAddressMode",
        "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/borderColor",
        "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode"
      ],
      "title": "Declaring Addressing Modes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Specifying-Border-Color-Options",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor/transparentBlack",
        "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor/opaqueBlack",
        "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor/opaqueWhite"
      ],
      "title": "Specifying Border Color Options"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLSamplerBorderColor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerBorderColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerBorderColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Specifying-Border-Color-Options",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor/transparentBlack",
                "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor/opaqueBlack",
                "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor/opaqueWhite"
              ],
              "title": "Specifying Border Color Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Declaring-Addressing-Modes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/rAddressMode",
                "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/sAddressMode",
                "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/tAddressMode",
                "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/borderColor",
                "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode"
              ],
              "title": "Declaring Addressing Modes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLSamplerBorderColor"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1rAddressMode/title",
          "value": "rAddressMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1rAddressMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rAddressMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerBorderColor~1opaqueBlack/title",
          "value": "MTLSamplerBorderColorOpaqueBlack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerBorderColor~1opaqueBlack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerBorderColorOpaqueBlack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerBorderColor/title",
          "value": "MTLSamplerBorderColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerBorderColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerBorderColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerBorderColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerBorderColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1sAddressMode/title",
          "value": "sAddressMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1sAddressMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sAddressMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerBorderColor~1transparentBlack/title",
          "value": "MTLSamplerBorderColorTransparentBlack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerBorderColor~1transparentBlack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerBorderColorTransparentBlack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1borderColor/title",
          "value": "borderColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1borderColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "borderColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerAddressMode/title",
          "value": "MTLSamplerAddressMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerAddressMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerAddressMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerAddressMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerAddressMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerBorderColor~1opaqueWhite/title",
          "value": "MTLSamplerBorderColorOpaqueWhite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerBorderColor~1opaqueWhite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerBorderColorOpaqueWhite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerAddressMode~1clampToBorderColor/title",
          "value": "MTLSamplerAddressModeClampToBorderColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerAddressMode~1clampToBorderColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerAddressModeClampToBorderColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1tAddressMode/title",
          "value": "tAddressMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1tAddressMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tAddressMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlsamplerbordercolor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlsamplerbordercolor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
