{
  "abstract": [
    {
      "text": "An object that you use to configure a texture sampler.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTLSamplerDescriptor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLSamplerDescriptor"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLSamplerDescriptor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MTLSamplerDescriptor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLSamplerDescriptor"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.metal/documentation/Metal/restricting-access-to-specific-mipmaps",
        "doc://com.apple.metal/documentation/Metal/improving-cpu-performance-by-using-argument-buffers",
        "doc://com.apple.metal/documentation/Metal/adding-mipmap-filtering-to-samplers"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To create a sampler, first create a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object and configure the descriptor’s properties. Then call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/makeSamplerState(descriptor:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method on the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object that will use this sampler. After you create the sampler, you can release the descriptor or reconfigure its properties to create other samplers.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCompareFunction": {
      "abstract": [
        {
          "text": "Options used to specify how a sample compare operation should be performed on a depth texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCompareFunction"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCompareFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCompareFunction"
        }
      ],
      "role": "symbol",
      "title": "MTLCompareFunction",
      "type": "topic",
      "url": "/documentation/metal/mtlcomparefunction"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice": {
      "abstract": [
        {
          "text": "The main Metal interface to a GPU that apps use to draw graphics and run computations in parallel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDevice"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDevice"
        }
      ],
      "role": "symbol",
      "title": "MTLDevice",
      "type": "topic",
      "url": "/documentation/metal/mtldevice"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/makeSamplerState(descriptor:)": {
      "abstract": [
        {
          "text": "Creates a sampler state instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeSamplerState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLSamplerDescriptor",
          "text": "MTLSamplerDescriptor"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLSamplerState",
          "text": "MTLSamplerState"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/makeSamplerState(descriptor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newSamplerStateWithDescriptor:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeSamplerState(descriptor:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/makesamplerstate(descriptor:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplePosition": {
      "abstract": [
        {
          "text": "A subpixel sample position for use in multisample antialiasing (MSAA).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLSamplePosition"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplePosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSamplePosition"
        }
      ],
      "role": "symbol",
      "title": "MTLSamplePosition",
      "type": "topic",
      "url": "/documentation/metal/mtlsampleposition"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode": {
      "abstract": [
        {
          "text": "Modes that determine the texture coordinate at each pixel when a fetch falls outside the bounds of a texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLSamplerAddressMode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSamplerAddressMode"
        }
      ],
      "role": "symbol",
      "title": "MTLSamplerAddressMode",
      "type": "topic",
      "url": "/documentation/metal/mtlsampleraddressmode"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/clampToBorderColor": {
      "abstract": [
        {
          "text": "Out-of-range texture coordinates return the value specified by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/borderColor",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clampToBorderColor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/clampToBorderColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSamplerAddressModeClampToBorderColor"
        }
      ],
      "role": "symbol",
      "title": "MTLSamplerAddressMode.clampToBorderColor",
      "type": "topic",
      "url": "/documentation/metal/mtlsampleraddressmode/clamptobordercolor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor": {
      "abstract": [
        {
          "text": "Values that determine the border color for clamped texture values when the sampler address mode is ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode/clampToBorderColor",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLSamplerBorderColor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSamplerBorderColor"
        }
      ],
      "role": "symbol",
      "title": "MTLSamplerBorderColor",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerbordercolor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor": {
      "abstract": [
        {
          "text": "An object that you use to configure a texture sampler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLSamplerDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSamplerDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLSamplerDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerdescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/borderColor": {
      "abstract": [
        {
          "text": "The border color for clamped texture values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "borderColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLSamplerBorderColor",
          "text": "MTLSamplerBorderColor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/borderColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "borderColor"
        }
      ],
      "role": "symbol",
      "title": "borderColor",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerdescriptor/bordercolor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/compareFunction": {
      "abstract": [
        {
          "text": "The sampler comparison function used when performing a sample compare operation on a depth texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compareFunction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLCompareFunction",
          "text": "MTLCompareFunction"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/compareFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compareFunction"
        }
      ],
      "role": "symbol",
      "title": "compareFunction",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerdescriptor/comparefunction"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/label": {
      "abstract": [
        {
          "text": "A string that identifies the sampler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "label"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/label",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "label"
        }
      ],
      "role": "symbol",
      "title": "label",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerdescriptor/label"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/lodAverage": {
      "abstract": [
        {
          "text": "A Boolean value that specifies whether the GPU can use an average level of detail (LOD) when sampling from a texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lodAverage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/lodAverage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lodAverage"
        }
      ],
      "role": "symbol",
      "title": "lodAverage",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerdescriptor/lodaverage"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/lodMaxClamp": {
      "abstract": [
        {
          "text": "The maximum level of detail (LOD) to use when sampling from a texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lodMaxClamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/lodMaxClamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lodMaxClamp"
        }
      ],
      "role": "symbol",
      "title": "lodMaxClamp",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerdescriptor/lodmaxclamp"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/lodMinClamp": {
      "abstract": [
        {
          "text": "The minimum level of detail (LOD) to use when sampling from a texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lodMinClamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/lodMinClamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lodMinClamp"
        }
      ],
      "role": "symbol",
      "title": "lodMinClamp",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerdescriptor/lodminclamp"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/magFilter": {
      "abstract": [
        {
          "text": "The filtering operation for combining pixels within one mipmap level when the sample footprint is smaller than a pixel (magnification).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "magFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLSamplerMinMagFilter",
          "text": "MTLSamplerMinMagFilter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/magFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "magFilter"
        }
      ],
      "role": "symbol",
      "title": "magFilter",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerdescriptor/magfilter"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/maxAnisotropy": {
      "abstract": [
        {
          "text": "The number of samples that can be taken to improve the quality of sample footprints that are anisotropic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxAnisotropy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/maxAnisotropy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxAnisotropy"
        }
      ],
      "role": "symbol",
      "title": "maxAnisotropy",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerdescriptor/maxanisotropy"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/minFilter": {
      "abstract": [
        {
          "text": "The filtering option for combining pixels within one mipmap level when the sample footprint is larger than a pixel (minification).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLSamplerMinMagFilter",
          "text": "MTLSamplerMinMagFilter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/minFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minFilter"
        }
      ],
      "role": "symbol",
      "title": "minFilter",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerdescriptor/minfilter"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/mipFilter": {
      "abstract": [
        {
          "text": "The filtering option for combining pixels between two mipmap levels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mipFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLSamplerMipFilter",
          "text": "MTLSamplerMipFilter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/mipFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mipFilter"
        }
      ],
      "role": "symbol",
      "title": "mipFilter",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerdescriptor/mipfilter"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/normalizedCoordinates": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether texture coordinates are normalized to the range ",
          "type": "text"
        },
        {
          "code": "[0.0, 1.0]",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "normalizedCoordinates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/normalizedCoordinates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "normalizedCoordinates"
        }
      ],
      "role": "symbol",
      "title": "normalizedCoordinates",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerdescriptor/normalizedcoordinates"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/rAddressMode": {
      "abstract": [
        {
          "text": "The address mode for the texture depth (r) coordinate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rAddressMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLSamplerAddressMode",
          "text": "MTLSamplerAddressMode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/rAddressMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rAddressMode"
        }
      ],
      "role": "symbol",
      "title": "rAddressMode",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerdescriptor/raddressmode"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/sAddressMode": {
      "abstract": [
        {
          "text": "The address mode for the texture width (s) coordinate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sAddressMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLSamplerAddressMode",
          "text": "MTLSamplerAddressMode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/sAddressMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sAddressMode"
        }
      ],
      "role": "symbol",
      "title": "sAddressMode",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerdescriptor/saddressmode"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/supportArgumentBuffers": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether you can reference a sampler, that you make",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "with this descriptor, by its resource ID from an argument buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportArgumentBuffers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/supportArgumentBuffers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportArgumentBuffers"
        }
      ],
      "role": "symbol",
      "title": "supportArgumentBuffers",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerdescriptor/supportargumentbuffers"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/tAddressMode": {
      "abstract": [
        {
          "text": "The address mode for the texture height (t) coordinate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tAddressMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLSamplerAddressMode",
          "text": "MTLSamplerAddressMode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/tAddressMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tAddressMode"
        }
      ],
      "role": "symbol",
      "title": "tAddressMode",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerdescriptor/taddressmode"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerMinMagFilter": {
      "abstract": [
        {
          "text": "Filtering options for determining which pixel value is returned within a mipmap level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLSamplerMinMagFilter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerMinMagFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSamplerMinMagFilter"
        }
      ],
      "role": "symbol",
      "title": "MTLSamplerMinMagFilter",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerminmagfilter"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerMipFilter": {
      "abstract": [
        {
          "text": "Filtering options for determining what pixel value is returned with multiple mipmap levels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLSamplerMipFilter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerMipFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSamplerMipFilter"
        }
      ],
      "role": "symbol",
      "title": "MTLSamplerMipFilter",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplermipfilter"
    },
    "doc://com.apple.metal/documentation/Metal/MTLSamplerState": {
      "abstract": [
        {
          "text": "An object that defines how a texture should be sampled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLSamplerState"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLSamplerState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLSamplerState"
        }
      ],
      "role": "symbol",
      "title": "MTLSamplerState",
      "type": "topic",
      "url": "/documentation/metal/mtlsamplerstate"
    },
    "doc://com.apple.metal/documentation/Metal/adding-mipmap-filtering-to-samplers": {
      "abstract": [
        {
          "text": "Specify how the GPU samples mipmaps in your textures.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/adding-mipmap-filtering-to-samplers",
      "kind": "article",
      "role": "article",
      "title": "Adding Mipmap Filtering to Samplers",
      "type": "topic",
      "url": "/documentation/metal/adding-mipmap-filtering-to-samplers"
    },
    "doc://com.apple.metal/documentation/Metal/creating-and-sampling-textures": {
      "abstract": [
        {
          "text": "Load image data into a texture and apply it to a quadrangle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/creating-and-sampling-textures",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating and Sampling Textures",
      "type": "topic",
      "url": "/documentation/metal/creating-and-sampling-textures"
    },
    "doc://com.apple.metal/documentation/Metal/improving-cpu-performance-by-using-argument-buffers": {
      "abstract": [
        {
          "text": "Optimize your app’s performance by grouping your resources into argument buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/improving-cpu-performance-by-using-argument-buffers",
      "kind": "article",
      "role": "article",
      "title": "Improving CPU Performance by Using Argument Buffers",
      "type": "topic",
      "url": "/documentation/metal/improving-cpu-performance-by-using-argument-buffers"
    },
    "doc://com.apple.metal/documentation/Metal/restricting-access-to-specific-mipmaps": {
      "abstract": [
        {
          "text": "Set the range of mipmap levels that a sampler can access.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/restricting-access-to-specific-mipmaps",
      "kind": "article",
      "role": "article",
      "title": "Restricting Access to Specific Mipmaps",
      "type": "topic",
      "url": "/documentation/metal/restricting-access-to-specific-mipmaps"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Texture-Samplers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/creating-and-sampling-textures",
        "doc://com.apple.metal/documentation/Metal/MTLSamplerState",
        "doc://com.apple.metal/documentation/Metal/MTLSamplePosition"
      ],
      "title": "Texture Samplers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Declaring-the-Coordinate-Space",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/normalizedCoordinates"
      ],
      "title": "Declaring the Coordinate Space"
    },
    {
      "anchor": "Declaring-Addressing-Modes",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/rAddressMode",
        "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/sAddressMode",
        "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/tAddressMode",
        "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/borderColor",
        "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode",
        "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor"
      ],
      "title": "Declaring Addressing Modes"
    },
    {
      "anchor": "Declaring-Filter-Modes",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/minFilter",
        "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/magFilter",
        "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/mipFilter",
        "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/lodMinClamp",
        "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/lodMaxClamp",
        "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/lodAverage",
        "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/maxAnisotropy",
        "doc://com.apple.metal/documentation/Metal/MTLSamplerMinMagFilter",
        "doc://com.apple.metal/documentation/Metal/MTLSamplerMipFilter"
      ],
      "title": "Declaring Filter Modes"
    },
    {
      "anchor": "Declaring-the-Depth-Comparison-Mode",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/compareFunction",
        "doc://com.apple.metal/documentation/Metal/MTLCompareFunction"
      ],
      "title": "Declaring the Depth Comparison Mode"
    },
    {
      "anchor": "Declaring-Whether-the-Sampler-Can-Be-Used-in-Argument-Buffers",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/supportArgumentBuffers"
      ],
      "title": "Declaring Whether the Sampler Can Be Used in Argument Buffers"
    },
    {
      "anchor": "Identifying-the-Sampler",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/label"
      ],
      "title": "Identifying the Sampler"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLSamplerDescriptor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Declaring-the-Coordinate-Space",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/normalizedCoordinates"
              ],
              "title": "Declaring the Coordinate Space"
            },
            {
              "anchor": "Declaring-Addressing-Modes",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/rAddressMode",
                "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/sAddressMode",
                "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/tAddressMode",
                "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/borderColor",
                "doc://com.apple.metal/documentation/Metal/MTLSamplerAddressMode",
                "doc://com.apple.metal/documentation/Metal/MTLSamplerBorderColor"
              ],
              "title": "Declaring Addressing Modes"
            },
            {
              "anchor": "Declaring-Filter-Modes",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/minFilter",
                "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/magFilter",
                "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/mipFilter",
                "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/lodMinClamp",
                "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/lodMaxClamp",
                "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/lodAverage",
                "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/maxAnisotropy",
                "doc://com.apple.metal/documentation/Metal/MTLSamplerMinMagFilter",
                "doc://com.apple.metal/documentation/Metal/MTLSamplerMipFilter"
              ],
              "title": "Declaring Filter Modes"
            },
            {
              "anchor": "Declaring-the-Depth-Comparison-Mode",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/compareFunction",
                "doc://com.apple.metal/documentation/Metal/MTLCompareFunction"
              ],
              "title": "Declaring the Depth Comparison Mode"
            },
            {
              "anchor": "Declaring-Whether-the-Sampler-Can-Be-Used-in-Argument-Buffers",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/supportArgumentBuffers"
              ],
              "title": "Declaring Whether the Sampler Can Be Used in Argument Buffers"
            },
            {
              "anchor": "Identifying-the-Sampler",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLSamplerDescriptor/label"
              ],
              "title": "Identifying the Sampler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Texture-Samplers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/creating-and-sampling-textures",
                "doc://com.apple.metal/documentation/Metal/MTLSamplerState",
                "doc://com.apple.metal/documentation/Metal/MTLSamplePosition"
              ],
              "title": "Texture Samplers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLSamplerDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor/title",
          "value": "MTLSamplerDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1tAddressMode/title",
          "value": "tAddressMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1tAddressMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tAddressMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1lodAverage/title",
          "value": "lodAverage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1lodAverage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lodAverage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1lodMinClamp/title",
          "value": "lodMinClamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1lodMinClamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lodMinClamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerAddressMode~1clampToBorderColor/title",
          "value": "MTLSamplerAddressModeClampToBorderColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerAddressMode~1clampToBorderColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerAddressModeClampToBorderColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1supportArgumentBuffers/title",
          "value": "supportArgumentBuffers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1supportArgumentBuffers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportArgumentBuffers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1compareFunction/title",
          "value": "compareFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1compareFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "compareFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1borderColor/title",
          "value": "borderColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1borderColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "borderColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1rAddressMode/title",
          "value": "rAddressMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1rAddressMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rAddressMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeSamplerState(descriptor:)/title",
          "value": "newSamplerStateWithDescriptor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeSamplerState(descriptor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newSamplerStateWithDescriptor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/title",
          "value": "MTLDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1sAddressMode/title",
          "value": "sAddressMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1sAddressMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sAddressMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompareFunction/title",
          "value": "MTLCompareFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompareFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCompareFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCompareFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCompareFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerBorderColor/title",
          "value": "MTLSamplerBorderColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerBorderColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerBorderColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerBorderColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerBorderColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1normalizedCoordinates/title",
          "value": "normalizedCoordinates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1normalizedCoordinates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "normalizedCoordinates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1magFilter/title",
          "value": "magFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1magFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "magFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerState/title",
          "value": "MTLSamplerState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1mipFilter/title",
          "value": "mipFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1mipFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mipFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerMipFilter/title",
          "value": "MTLSamplerMipFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerMipFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerMipFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerMipFilter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerMipFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerMinMagFilter/title",
          "value": "MTLSamplerMinMagFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerMinMagFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerMinMagFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerMinMagFilter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerMinMagFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1minFilter/title",
          "value": "minFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1minFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1label/title",
          "value": "label"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1label/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "label"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplePosition/title",
          "value": "MTLSamplePosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplePosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplePosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplePosition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplePosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1maxAnisotropy/title",
          "value": "maxAnisotropy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1maxAnisotropy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxAnisotropy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerAddressMode/title",
          "value": "MTLSamplerAddressMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerAddressMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerAddressMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerAddressMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLSamplerAddressMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1lodMaxClamp/title",
          "value": "lodMaxClamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLSamplerDescriptor~1lodMaxClamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lodMaxClamp"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlsamplerdescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlsamplerdescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
