{
  "abstract": [
    {
      "text": "Options for specifying the step function that determines the tessellation factors for a patch from the tessellation factor buffer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLTessellationFactorStepFunction",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLTessellationFactorStepFunction"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLTessellationFactorStepFunction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTLTessellationFactorStepFunction"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLTessellationFactorStepFunction"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/isTessellationFactorScaleEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the pipeline scales the tessellation factor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isTessellationFactorScaleEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/isTessellationFactorScaleEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tessellationFactorScaleEnabled"
        }
      ],
      "role": "symbol",
      "title": "isTessellationFactorScaleEnabled",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpipelinedescriptor/istessellationfactorscaleenabled"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/maxTessellationFactor": {
      "abstract": [
        {
          "text": "The maximum tessellation factor that the tessellator uses when tessellating patches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxTessellationFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/maxTessellationFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxTessellationFactor"
        }
      ],
      "role": "symbol",
      "title": "maxTessellationFactor",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpipelinedescriptor/maxtessellationfactor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationControlPointIndexType": {
      "abstract": [
        {
          "text": "The size of the control point indices in a control point index buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tessellationControlPointIndexType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTessellationControlPointIndexType",
          "text": "MTLTessellationControlPointIndexType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationControlPointIndexType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tessellationControlPointIndexType"
        }
      ],
      "role": "symbol",
      "title": "tessellationControlPointIndexType",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpipelinedescriptor/tessellationcontrolpointindextype"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationFactorFormat": {
      "abstract": [
        {
          "text": "The format of the tessellation factors in the tessellation factor buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tessellationFactorFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTessellationFactorFormat",
          "text": "MTLTessellationFactorFormat"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationFactorFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tessellationFactorFormat"
        }
      ],
      "role": "symbol",
      "title": "tessellationFactorFormat",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpipelinedescriptor/tessellationfactorformat"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationFactorStepFunction": {
      "abstract": [
        {
          "text": "The step function for determining the tessellation factors for a patch from the tessellation factor buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tessellationFactorStepFunction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTessellationFactorStepFunction",
          "text": "MTLTessellationFactorStepFunction"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationFactorStepFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tessellationFactorStepFunction"
        }
      ],
      "role": "symbol",
      "title": "tessellationFactorStepFunction",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpipelinedescriptor/tessellationfactorstepfunction"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationOutputWindingOrder": {
      "abstract": [
        {
          "text": "The winding order of triangles from the tessellator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tessellationOutputWindingOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLWinding",
          "text": "MTLWinding"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationOutputWindingOrder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tessellationOutputWindingOrder"
        }
      ],
      "role": "symbol",
      "title": "tessellationOutputWindingOrder",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpipelinedescriptor/tessellationoutputwindingorder"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationPartitionMode": {
      "abstract": [
        {
          "text": "The partitioning mode that the tessellator uses to derive the number and spacing of segments for subdividing a corresponding edge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tessellationPartitionMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTessellationPartitionMode",
          "text": "MTLTessellationPartitionMode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationPartitionMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tessellationPartitionMode"
        }
      ],
      "role": "symbol",
      "title": "tessellationPartitionMode",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpipelinedescriptor/tessellationpartitionmode"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTessellationControlPointIndexType": {
      "abstract": [
        {
          "text": "Options for specifying the size of the control point indices in a control point index buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLTessellationControlPointIndexType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTessellationControlPointIndexType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTessellationControlPointIndexType"
        }
      ],
      "role": "symbol",
      "title": "MTLTessellationControlPointIndexType",
      "type": "topic",
      "url": "/documentation/metal/mtltessellationcontrolpointindextype"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorFormat": {
      "abstract": [
        {
          "text": "Options for specifying the format of the tessellation factors in a tessellation factor buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLTessellationFactorFormat"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTessellationFactorFormat"
        }
      ],
      "role": "symbol",
      "title": "MTLTessellationFactorFormat",
      "type": "topic",
      "url": "/documentation/metal/mtltessellationfactorformat"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction": {
      "abstract": [
        {
          "text": "Options for specifying the step function that determines the tessellation factors for a patch from the tessellation factor buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLTessellationFactorStepFunction"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTessellationFactorStepFunction"
        }
      ],
      "role": "symbol",
      "title": "MTLTessellationFactorStepFunction",
      "type": "topic",
      "url": "/documentation/metal/mtltessellationfactorstepfunction"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/constant": {
      "abstract": [
        {
          "text": "A constant step function. For all instances, the tessellation factor for all patches in a patch draw call is at the ",
          "type": "text"
        },
        {
          "code": "offset",
          "type": "codeVoice"
        },
        {
          "text": " location in the tessellation factor buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constant"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/constant",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTessellationFactorStepFunctionConstant"
        }
      ],
      "role": "symbol",
      "title": "MTLTessellationFactorStepFunction.constant",
      "type": "topic",
      "url": "/documentation/metal/mtltessellationfactorstepfunction/constant"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/metal/mtltessellationfactorstepfunction/init(rawvalue:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/perInstance": {
      "abstract": [
        {
          "text": "A per-instance step function. For a given instance ID, the tessellation factor for a patch in a patch draw call is at the ",
          "type": "text"
        },
        {
          "code": "offset + (instanceID * instanceStride)",
          "type": "codeVoice"
        },
        {
          "text": " location in the tessellation factor buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perInstance"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/perInstance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTessellationFactorStepFunctionPerInstance"
        }
      ],
      "role": "symbol",
      "title": "MTLTessellationFactorStepFunction.perInstance",
      "type": "topic",
      "url": "/documentation/metal/mtltessellationfactorstepfunction/perinstance"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/perPatch": {
      "abstract": [
        {
          "text": "A per-patch step function. For all instances, the tessellation factor for all patches in a patch draw call is at the ",
          "type": "text"
        },
        {
          "code": "offset + (drawPatchIndex * tessellationFactorStride)",
          "type": "codeVoice"
        },
        {
          "text": " location in the tessellation factor buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perPatch"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/perPatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTessellationFactorStepFunctionPerPatch"
        }
      ],
      "role": "symbol",
      "title": "MTLTessellationFactorStepFunction.perPatch",
      "type": "topic",
      "url": "/documentation/metal/mtltessellationfactorstepfunction/perpatch"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/perPatchAndPerInstance": {
      "abstract": [
        {
          "text": "A per-patch and per-instance step function. For a given instance ID, the tessellation factor for a patch in a patch draw call is at the ",
          "type": "text"
        },
        {
          "code": "offset + (drawPatchIndex * tessellationFactorStride + instanceID * instanceStride)",
          "type": "codeVoice"
        },
        {
          "text": " location in the tessellation factor buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perPatchAndPerInstance"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/perPatchAndPerInstance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTessellationFactorStepFunctionPerPatchAndPerInstance"
        }
      ],
      "role": "symbol",
      "title": "MTLTessellationFactorStepFunction.perPatchAndPerInstance",
      "type": "topic",
      "url": "/documentation/metal/mtltessellationfactorstepfunction/perpatchandperinstance"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTessellationPartitionMode": {
      "abstract": [
        {
          "text": "Options for choosing the partition mode that the tessellator applies when deriving",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "the number and spacing of segments for subdividing a corresponding edge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLTessellationPartitionMode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTessellationPartitionMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTessellationPartitionMode"
        }
      ],
      "role": "symbol",
      "title": "MTLTessellationPartitionMode",
      "type": "topic",
      "url": "/documentation/metal/mtltessellationpartitionmode"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-Tessellation-State",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/maxTessellationFactor",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/isTessellationFactorScaleEnabled",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationFactorFormat",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationControlPointIndexType",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationFactorStepFunction",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationOutputWindingOrder",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationPartitionMode",
        "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorFormat",
        "doc://com.apple.metal/documentation/Metal/MTLTessellationControlPointIndexType",
        "doc://com.apple.metal/documentation/Metal/MTLTessellationPartitionMode"
      ],
      "title": "Specifying Tessellation State"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/constant",
        "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/perPatch",
        "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/perInstance",
        "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/perPatchAndPerInstance"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLTessellationFactorStepFunction"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationFactorStepFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationFactorStepFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/constant",
                "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/perPatch",
                "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/perInstance",
                "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction/perPatchAndPerInstance"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-Tessellation-State",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/maxTessellationFactor",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/isTessellationFactorScaleEnabled",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationFactorFormat",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationControlPointIndexType",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationFactorStepFunction",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationOutputWindingOrder",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationPartitionMode",
                "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorFormat",
                "doc://com.apple.metal/documentation/Metal/MTLTessellationControlPointIndexType",
                "doc://com.apple.metal/documentation/Metal/MTLTessellationPartitionMode"
              ],
              "title": "Specifying Tessellation State"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLTessellationFactorStepFunction"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor~1isTessellationFactorScaleEnabled/title",
          "value": "tessellationFactorScaleEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor~1isTessellationFactorScaleEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tessellationFactorScaleEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor~1tessellationPartitionMode/title",
          "value": "tessellationPartitionMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor~1tessellationPartitionMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tessellationPartitionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor~1tessellationFactorStepFunction/title",
          "value": "tessellationFactorStepFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor~1tessellationFactorStepFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tessellationFactorStepFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorStepFunction/title",
          "value": "MTLTessellationFactorStepFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorStepFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationFactorStepFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorStepFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationFactorStepFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorFormat/title",
          "value": "MTLTessellationFactorFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationFactorFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationFactorFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor~1tessellationOutputWindingOrder/title",
          "value": "tessellationOutputWindingOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor~1tessellationOutputWindingOrder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tessellationOutputWindingOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor~1tessellationControlPointIndexType/title",
          "value": "tessellationControlPointIndexType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor~1tessellationControlPointIndexType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tessellationControlPointIndexType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorStepFunction~1perPatchAndPerInstance/title",
          "value": "MTLTessellationFactorStepFunctionPerPatchAndPerInstance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorStepFunction~1perPatchAndPerInstance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationFactorStepFunctionPerPatchAndPerInstance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationPartitionMode/title",
          "value": "MTLTessellationPartitionMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationPartitionMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationPartitionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationPartitionMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationPartitionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorStepFunction~1perInstance/title",
          "value": "MTLTessellationFactorStepFunctionPerInstance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorStepFunction~1perInstance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationFactorStepFunctionPerInstance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor~1tessellationFactorFormat/title",
          "value": "tessellationFactorFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor~1tessellationFactorFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tessellationFactorFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationControlPointIndexType/title",
          "value": "MTLTessellationControlPointIndexType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationControlPointIndexType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationControlPointIndexType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationControlPointIndexType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationControlPointIndexType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorStepFunction~1constant/title",
          "value": "MTLTessellationFactorStepFunctionConstant"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorStepFunction~1constant/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationFactorStepFunctionConstant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor~1maxTessellationFactor/title",
          "value": "maxTessellationFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor~1maxTessellationFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxTessellationFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorStepFunction~1perPatch/title",
          "value": "MTLTessellationFactorStepFunctionPerPatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorStepFunction~1perPatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationFactorStepFunctionPerPatch"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtltessellationfactorstepfunction"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtltessellationfactorstepfunction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
