{
  "abstract": [
    {
      "text": "A set of options to choose from when creating a texture swizzle pattern.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLTextureSwizzle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLTextureSwizzle"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLTextureSwizzle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTLTextureSwizzle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLTextureSwizzle"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/allowGPUOptimizedContents": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the GPU is allowed to adjust the texture’s contents to improve GPU performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowGPUOptimizedContents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/allowGPUOptimizedContents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowGPUOptimizedContents"
        }
      ],
      "role": "symbol",
      "title": "allowGPUOptimizedContents",
      "type": "topic",
      "url": "/documentation/metal/mtltexturedescriptor/allowgpuoptimizedcontents"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/arrayLength": {
      "abstract": [
        {
          "text": "The number of array elements for this texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arrayLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/arrayLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "arrayLength"
        }
      ],
      "role": "symbol",
      "title": "arrayLength",
      "type": "topic",
      "url": "/documentation/metal/mtltexturedescriptor/arraylength"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/cpuCacheMode": {
      "abstract": [
        {
          "text": "The CPU cache mode used for the CPU mapping of the texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cpuCacheMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLCPUCacheMode",
          "text": "MTLCPUCacheMode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/cpuCacheMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cpuCacheMode"
        }
      ],
      "role": "symbol",
      "title": "cpuCacheMode",
      "type": "topic",
      "url": "/documentation/metal/mtltexturedescriptor/cpucachemode"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/depth": {
      "abstract": [
        {
          "text": "The depth of the texture image for the base level mipmap, in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "depth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/depth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "depth"
        }
      ],
      "role": "symbol",
      "title": "depth",
      "type": "topic",
      "url": "/documentation/metal/mtltexturedescriptor/depth"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/hazardTrackingMode": {
      "abstract": [
        {
          "text": "The texture’s hazard tracking mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hazardTrackingMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLHazardTrackingMode",
          "text": "MTLHazardTrackingMode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/hazardTrackingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hazardTrackingMode"
        }
      ],
      "role": "symbol",
      "title": "hazardTrackingMode",
      "type": "topic",
      "url": "/documentation/metal/mtltexturedescriptor/hazardtrackingmode"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/height": {
      "abstract": [
        {
          "text": "The height of the texture image for the base level mipmap, in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "height"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/height",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "height"
        }
      ],
      "role": "symbol",
      "title": "height",
      "type": "topic",
      "url": "/documentation/metal/mtltexturedescriptor/height"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/mipmapLevelCount": {
      "abstract": [
        {
          "text": "The number of mipmap levels for this texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mipmapLevelCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/mipmapLevelCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mipmapLevelCount"
        }
      ],
      "role": "symbol",
      "title": "mipmapLevelCount",
      "type": "topic",
      "url": "/documentation/metal/mtltexturedescriptor/mipmaplevelcount"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/pixelFormat": {
      "abstract": [
        {
          "text": "The size and bit layout of all pixels in the texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pixelFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLPixelFormat",
          "text": "MTLPixelFormat"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/pixelFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pixelFormat"
        }
      ],
      "role": "symbol",
      "title": "pixelFormat",
      "type": "topic",
      "url": "/documentation/metal/mtltexturedescriptor/pixelformat"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/resourceOptions": {
      "abstract": [
        {
          "text": "The behavior of a new memory allocation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resourceOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLResourceOptions",
          "text": "MTLResourceOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/resourceOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resourceOptions"
        }
      ],
      "role": "symbol",
      "title": "resourceOptions",
      "type": "topic",
      "url": "/documentation/metal/mtltexturedescriptor/resourceoptions"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/sampleCount": {
      "abstract": [
        {
          "text": "The number of samples in each fragment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sampleCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/sampleCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sampleCount"
        }
      ],
      "role": "symbol",
      "title": "sampleCount",
      "type": "topic",
      "url": "/documentation/metal/mtltexturedescriptor/samplecount"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/storageMode": {
      "abstract": [
        {
          "text": "The location and access permissions of the texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "storageMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLStorageMode",
          "text": "MTLStorageMode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/storageMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "storageMode"
        }
      ],
      "role": "symbol",
      "title": "storageMode",
      "type": "topic",
      "url": "/documentation/metal/mtltexturedescriptor/storagemode"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/swizzle": {
      "abstract": [
        {
          "text": "The pattern you want the GPU to apply to pixels when you read or sample pixels from the texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "swizzle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MTLTextureSwizzleChannels",
          "text": "MTLTextureSwizzleChannels"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/swizzle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "swizzle"
        }
      ],
      "role": "symbol",
      "title": "swizzle",
      "type": "topic",
      "url": "/documentation/metal/mtltexturedescriptor/swizzle"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/textureType": {
      "abstract": [
        {
          "text": "The dimension and arrangement of texture image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textureType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTextureType",
          "text": "MTLTextureType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/textureType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textureType"
        }
      ],
      "role": "symbol",
      "title": "textureType",
      "type": "topic",
      "url": "/documentation/metal/mtltexturedescriptor/texturetype"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/usage": {
      "abstract": [
        {
          "text": "Options that determine how you can use the texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTextureUsage",
          "text": "MTLTextureUsage"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/usage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "usage"
        }
      ],
      "role": "symbol",
      "title": "usage",
      "type": "topic",
      "url": "/documentation/metal/mtltexturedescriptor/usage"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/width": {
      "abstract": [
        {
          "text": "The width of the texture image for the base level mipmap, in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "width"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/width",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "width"
        }
      ],
      "role": "symbol",
      "title": "width",
      "type": "topic",
      "url": "/documentation/metal/mtltexturedescriptor/width"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle": {
      "abstract": [
        {
          "text": "A set of options to choose from when creating a texture swizzle pattern.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLTextureSwizzle"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTextureSwizzle"
        }
      ],
      "role": "symbol",
      "title": "MTLTextureSwizzle",
      "type": "topic",
      "url": "/documentation/metal/mtltextureswizzle"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/alpha": {
      "abstract": [
        {
          "text": "The alpha channel of the source pixel is copied to the destination channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alpha"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/alpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTextureSwizzleAlpha"
        }
      ],
      "role": "symbol",
      "title": "MTLTextureSwizzle.alpha",
      "type": "topic",
      "url": "/documentation/metal/mtltextureswizzle/alpha"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/blue": {
      "abstract": [
        {
          "text": "The blue channel of the source pixel is copied to the destination channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "blue"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/blue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTextureSwizzleBlue"
        }
      ],
      "role": "symbol",
      "title": "MTLTextureSwizzle.blue",
      "type": "topic",
      "url": "/documentation/metal/mtltextureswizzle/blue"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/green": {
      "abstract": [
        {
          "text": "The green channel of the source pixel is copied to the destination channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "green"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/green",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTextureSwizzleGreen"
        }
      ],
      "role": "symbol",
      "title": "MTLTextureSwizzle.green",
      "type": "topic",
      "url": "/documentation/metal/mtltextureswizzle/green"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/metal/mtltextureswizzle/init(rawvalue:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/one": {
      "abstract": [
        {
          "text": "A value of ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": " is copied to the destination channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "one"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/one",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTextureSwizzleOne"
        }
      ],
      "role": "symbol",
      "title": "MTLTextureSwizzle.one",
      "type": "topic",
      "url": "/documentation/metal/mtltextureswizzle/one"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/red": {
      "abstract": [
        {
          "text": "The red channel of the source pixel is copied to the destination channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "red"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/red",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTextureSwizzleRed"
        }
      ],
      "role": "symbol",
      "title": "MTLTextureSwizzle.red",
      "type": "topic",
      "url": "/documentation/metal/mtltextureswizzle/red"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/zero": {
      "abstract": [
        {
          "text": "A value of ",
          "type": "text"
        },
        {
          "code": "0.0",
          "type": "codeVoice"
        },
        {
          "text": " is copied to the destination channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zero"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/zero",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTextureSwizzleZero"
        }
      ],
      "role": "symbol",
      "title": "MTLTextureSwizzle.zero",
      "type": "topic",
      "url": "/documentation/metal/mtltextureswizzle/zero"
    },
    "doc://com.externally.resolved.symbol/c:@T@uint8_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@uint8_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "uint8_t",
      "type": "topic",
      "url": "/documentation/kernel/uint8_t"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-Texture-Attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/textureType",
        "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/pixelFormat",
        "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/width",
        "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/height",
        "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/depth",
        "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/mipmapLevelCount",
        "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/sampleCount",
        "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/arrayLength",
        "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/resourceOptions",
        "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/cpuCacheMode",
        "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/storageMode",
        "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/hazardTrackingMode",
        "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/allowGPUOptimizedContents",
        "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/usage",
        "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/swizzle"
      ],
      "title": "Specifying Texture Attributes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Specifying-Swizzle-Channels",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/alpha",
        "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/blue",
        "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/green",
        "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/red",
        "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/one",
        "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/zero"
      ],
      "title": "Specifying Swizzle Channels"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLTextureSwizzle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureSwizzle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureSwizzle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Specifying-Swizzle-Channels",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/alpha",
                "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/blue",
                "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/green",
                "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/red",
                "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/one",
                "doc://com.apple.metal/documentation/Metal/MTLTextureSwizzle/zero"
              ],
              "title": "Specifying Swizzle Channels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-Texture-Attributes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/textureType",
                "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/pixelFormat",
                "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/width",
                "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/height",
                "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/depth",
                "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/mipmapLevelCount",
                "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/sampleCount",
                "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/arrayLength",
                "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/resourceOptions",
                "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/cpuCacheMode",
                "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/storageMode",
                "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/hazardTrackingMode",
                "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/allowGPUOptimizedContents",
                "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/usage",
                "doc://com.apple.metal/documentation/Metal/MTLTextureDescriptor/swizzle"
              ],
              "title": "Specifying Texture Attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLTextureSwizzle"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@uint8_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1width/title",
          "value": "width"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1width/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "width"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle/title",
          "value": "MTLTextureSwizzle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureSwizzle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureSwizzle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle~1one/title",
          "value": "MTLTextureSwizzleOne"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle~1one/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureSwizzleOne"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1height/title",
          "value": "height"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1height/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "height"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle~1alpha/title",
          "value": "MTLTextureSwizzleAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle~1alpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureSwizzleAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1usage/title",
          "value": "usage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1usage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "usage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1swizzle/title",
          "value": "swizzle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1swizzle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "swizzle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle~1zero/title",
          "value": "MTLTextureSwizzleZero"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle~1zero/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureSwizzleZero"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1textureType/title",
          "value": "textureType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1textureType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "textureType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1mipmapLevelCount/title",
          "value": "mipmapLevelCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1mipmapLevelCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mipmapLevelCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1resourceOptions/title",
          "value": "resourceOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1resourceOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resourceOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle~1red/title",
          "value": "MTLTextureSwizzleRed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle~1red/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureSwizzleRed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1arrayLength/title",
          "value": "arrayLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1arrayLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "arrayLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1depth/title",
          "value": "depth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1depth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "depth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle~1blue/title",
          "value": "MTLTextureSwizzleBlue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle~1blue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureSwizzleBlue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1storageMode/title",
          "value": "storageMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1storageMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "storageMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle~1green/title",
          "value": "MTLTextureSwizzleGreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureSwizzle~1green/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureSwizzleGreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1cpuCacheMode/title",
          "value": "cpuCacheMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1cpuCacheMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cpuCacheMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1hazardTrackingMode/title",
          "value": "hazardTrackingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1hazardTrackingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hazardTrackingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1allowGPUOptimizedContents/title",
          "value": "allowGPUOptimizedContents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1allowGPUOptimizedContents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowGPUOptimizedContents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1pixelFormat/title",
          "value": "pixelFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1pixelFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pixelFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1sampleCount/title",
          "value": "sampleCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureDescriptor~1sampleCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sampleCount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtltextureswizzle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtltextureswizzle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
