{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLTextureBinding"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MTLTextureBinding",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLTextureBinding"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLTextureBinding"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "MTLTextureBinding"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLTextureBinding"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLBinding",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)MTLBinding",
              "text": "MTLBinding"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedComputePipelineReflection": {
      "abstract": [
        {
          "text": "A convenience type alias for an autoreleased compute pipeline reflection object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAutoreleasedComputePipelineReflection"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedComputePipelineReflection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAutoreleasedComputePipelineReflection"
        }
      ],
      "role": "symbol",
      "title": "MTLAutoreleasedComputePipelineReflection",
      "type": "topic",
      "url": "/documentation/metal/mtlautoreleasedcomputepipelinereflection"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedRenderPipelineReflection": {
      "abstract": [
        {
          "text": "A convenience type alias for an autoreleased pipeline reflection instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAutoreleasedRenderPipelineReflection"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedRenderPipelineReflection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAutoreleasedRenderPipelineReflection"
        }
      ],
      "role": "symbol",
      "title": "MTLAutoreleasedRenderPipelineReflection",
      "type": "topic",
      "url": "/documentation/metal/mtlautoreleasedrenderpipelinereflection"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBinding": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLBinding"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBinding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBinding"
        }
      ],
      "role": "symbol",
      "title": "MTLBinding",
      "type": "topic",
      "url": "/documentation/metal/mtlbinding"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingAccess": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLBindingAccess"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBindingAccess"
        }
      ],
      "role": "symbol",
      "title": "MTLBindingAccess",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingaccess"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBindingType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLBindingType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBindingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBindingType"
        }
      ],
      "role": "symbol",
      "title": "MTLBindingType",
      "type": "topic",
      "url": "/documentation/metal/mtlbindingtype"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBufferBinding": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLBufferBinding"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBufferBinding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBufferBinding"
        }
      ],
      "role": "symbol",
      "title": "MTLBufferBinding",
      "type": "topic",
      "url": "/documentation/metal/mtlbufferbinding"
    },
    "doc://com.apple.metal/documentation/Metal/MTLComputePipelineReflection": {
      "abstract": [
        {
          "text": "Information about the arguments of a compute function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLComputePipelineReflection"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLComputePipelineReflection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLComputePipelineReflection"
        }
      ],
      "role": "symbol",
      "title": "MTLComputePipelineReflection",
      "type": "topic",
      "url": "/documentation/metal/mtlcomputepipelinereflection"
    },
    "doc://com.apple.metal/documentation/Metal/MTLObjectPayloadBinding": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLObjectPayloadBinding"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLObjectPayloadBinding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLObjectPayloadBinding"
        }
      ],
      "role": "symbol",
      "title": "MTLObjectPayloadBinding",
      "type": "topic",
      "url": "/documentation/metal/mtlobjectpayloadbinding"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineReflection": {
      "abstract": [
        {
          "text": "Information about the arguments of a graphics function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLRenderPipelineReflection"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineReflection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLRenderPipelineReflection"
        }
      ],
      "role": "symbol",
      "title": "MTLRenderPipelineReflection",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpipelinereflection"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureBinding": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLTextureBinding"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureBinding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTextureBinding"
        }
      ],
      "role": "symbol",
      "title": "MTLTextureBinding",
      "type": "topic",
      "url": "/documentation/metal/mtltexturebinding"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureBinding/arrayLength": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arrayLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureBinding/arrayLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "arrayLength"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "arrayLength",
      "type": "topic",
      "url": "/documentation/metal/mtltexturebinding/arraylength"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureBinding/isDepthTexture": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isDepthTexture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureBinding/isDepthTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "depthTexture"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "isDepthTexture",
      "type": "topic",
      "url": "/documentation/metal/mtltexturebinding/isdepthtexture"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureBinding/textureDataType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textureDataType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLDataType",
          "text": "MTLDataType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureBinding/textureDataType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textureDataType"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "textureDataType",
      "type": "topic",
      "url": "/documentation/metal/mtltexturebinding/texturedatatype"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTextureBinding/textureType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textureType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTextureType",
          "text": "MTLTextureType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTextureBinding/textureType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textureType"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "textureType",
      "type": "topic",
      "url": "/documentation/metal/mtltexturebinding/texturetype"
    },
    "doc://com.apple.metal/documentation/Metal/MTLThreadgroupBinding": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLThreadgroupBinding"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLThreadgroupBinding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLThreadgroupBinding"
        }
      ],
      "role": "symbol",
      "title": "MTLThreadgroupBinding",
      "type": "topic",
      "url": "/documentation/metal/mtlthreadgroupbinding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLBinding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Introspection-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLComputePipelineReflection",
        "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedComputePipelineReflection",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineReflection",
        "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedRenderPipelineReflection",
        "doc://com.apple.metal/documentation/Metal/MTLBindingType",
        "doc://com.apple.metal/documentation/Metal/MTLBinding",
        "doc://com.apple.metal/documentation/Metal/MTLBindingAccess",
        "doc://com.apple.metal/documentation/Metal/MTLBufferBinding",
        "doc://com.apple.metal/documentation/Metal/MTLThreadgroupBinding",
        "doc://com.apple.metal/documentation/Metal/MTLObjectPayloadBinding"
      ],
      "title": "Introspection Data"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLTextureBinding/arrayLength",
        "doc://com.apple.metal/documentation/Metal/MTLTextureBinding/isDepthTexture",
        "doc://com.apple.metal/documentation/Metal/MTLTextureBinding/textureDataType",
        "doc://com.apple.metal/documentation/Metal/MTLTextureBinding/textureType"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLTextureBinding"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLTextureBinding/arrayLength",
                "doc://com.apple.metal/documentation/Metal/MTLTextureBinding/isDepthTexture",
                "doc://com.apple.metal/documentation/Metal/MTLTextureBinding/textureDataType",
                "doc://com.apple.metal/documentation/Metal/MTLTextureBinding/textureType"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLBinding"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Introspection-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLComputePipelineReflection",
                "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedComputePipelineReflection",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineReflection",
                "doc://com.apple.metal/documentation/Metal/MTLAutoreleasedRenderPipelineReflection",
                "doc://com.apple.metal/documentation/Metal/MTLBindingType",
                "doc://com.apple.metal/documentation/Metal/MTLBinding",
                "doc://com.apple.metal/documentation/Metal/MTLBindingAccess",
                "doc://com.apple.metal/documentation/Metal/MTLBufferBinding",
                "doc://com.apple.metal/documentation/Metal/MTLThreadgroupBinding",
                "doc://com.apple.metal/documentation/Metal/MTLObjectPayloadBinding"
              ],
              "title": "Introspection Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLTextureBinding"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.apple.metal/documentation/Metal/MTLBinding",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)MTLBinding",
                    "text": "MTLBinding"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLThreadgroupBinding/title",
          "value": "MTLThreadgroupBinding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLThreadgroupBinding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLThreadgroupBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLThreadgroupBinding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLThreadgroupBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineReflection/title",
          "value": "MTLRenderPipelineReflection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineReflection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPipelineReflection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineReflection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPipelineReflection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureBinding~1textureDataType/title",
          "value": "textureDataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureBinding~1textureDataType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "textureDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingAccess/title",
          "value": "MTLBindingAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingAccess/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLObjectPayloadBinding/title",
          "value": "MTLObjectPayloadBinding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLObjectPayloadBinding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLObjectPayloadBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLObjectPayloadBinding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLObjectPayloadBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureBinding~1textureType/title",
          "value": "textureType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureBinding~1textureType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "textureType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComputePipelineReflection/title",
          "value": "MTLComputePipelineReflection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComputePipelineReflection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLComputePipelineReflection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLComputePipelineReflection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLComputePipelineReflection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureBinding~1isDepthTexture/title",
          "value": "depthTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureBinding~1isDepthTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "depthTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureBinding/title",
          "value": "MTLTextureBinding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureBinding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureBinding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBufferBinding/title",
          "value": "MTLBufferBinding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBufferBinding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBufferBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBufferBinding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBufferBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAutoreleasedComputePipelineReflection/title",
          "value": "MTLAutoreleasedComputePipelineReflection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAutoreleasedComputePipelineReflection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAutoreleasedComputePipelineReflection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAutoreleasedComputePipelineReflection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAutoreleasedComputePipelineReflection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinding/title",
          "value": "MTLBinding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureBinding~1arrayLength/title",
          "value": "arrayLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTextureBinding~1arrayLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "arrayLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType/title",
          "value": "MTLBindingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBindingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBindingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAutoreleasedRenderPipelineReflection/title",
          "value": "MTLAutoreleasedRenderPipelineReflection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAutoreleasedRenderPipelineReflection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAutoreleasedRenderPipelineReflection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAutoreleasedRenderPipelineReflection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAutoreleasedRenderPipelineReflection"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtltexturebinding"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtltexturebinding"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
