{
  "abstract": [
    {
      "text": "A 3D rectangular region for the viewport clipping.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLViewport"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@MTLViewport",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MTLViewport"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLViewport"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "MTLViewport"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLViewport"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLQuadTessellationFactorsHalf": {
      "abstract": [
        {
          "text": "The per-patch tessellation factors for a quad patch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLQuadTessellationFactorsHalf"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLQuadTessellationFactorsHalf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLQuadTessellationFactorsHalf"
        }
      ],
      "role": "symbol",
      "title": "MTLQuadTessellationFactorsHalf",
      "type": "topic",
      "url": "/documentation/metal/mtlquadtessellationfactorshalf"
    },
    "doc://com.apple.metal/documentation/Metal/MTLScissorRect": {
      "abstract": [
        {
          "text": "A rectangle for the scissor fragment test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLScissorRect"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLScissorRect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLScissorRect"
        }
      ],
      "role": "symbol",
      "title": "MTLScissorRect",
      "type": "topic",
      "url": "/documentation/metal/mtlscissorrect"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTriangleTessellationFactorsHalf": {
      "abstract": [
        {
          "text": "The per-patch tessellation factors for a triangle patch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLTriangleTessellationFactorsHalf"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTriangleTessellationFactorsHalf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTriangleTessellationFactorsHalf"
        }
      ],
      "role": "symbol",
      "title": "MTLTriangleTessellationFactorsHalf",
      "type": "topic",
      "url": "/documentation/metal/mtltriangletessellationfactorshalf"
    },
    "doc://com.apple.metal/documentation/Metal/MTLVertexAmplificationViewMapping": {
      "abstract": [
        {
          "text": "An offset applied to a render target index and viewport index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLVertexAmplificationViewMapping"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLVertexAmplificationViewMapping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLVertexAmplificationViewMapping"
        }
      ],
      "role": "symbol",
      "title": "MTLVertexAmplificationViewMapping",
      "type": "topic",
      "url": "/documentation/metal/mtlvertexamplificationviewmapping"
    },
    "doc://com.apple.metal/documentation/Metal/MTLViewport": {
      "abstract": [
        {
          "text": "A 3D rectangular region for the viewport clipping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLViewport"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLViewport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLViewport"
        }
      ],
      "role": "symbol",
      "title": "MTLViewport",
      "type": "topic",
      "url": "/documentation/metal/mtlviewport"
    },
    "doc://com.apple.metal/documentation/Metal/MTLViewport/height": {
      "abstract": [
        {
          "text": "The height of the viewport, in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "height"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLViewport/height",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "height"
        }
      ],
      "role": "symbol",
      "title": "height",
      "type": "topic",
      "url": "/documentation/metal/mtlviewport/height"
    },
    "doc://com.apple.metal/documentation/Metal/MTLViewport/init()": {
      "abstract": [
        {
          "text": "Returns a new viewport.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLViewport/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/metal/mtlviewport/init()"
    },
    "doc://com.apple.metal/documentation/Metal/MTLViewport/init(originX:originY:width:height:znear:zfar:)": {
      "abstract": [
        {
          "text": "Returns a new viewport of a specified size at a specified origin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "originX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "originY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "width"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "height"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "znear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "zfar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLViewport/init(originX:originY:width:height:znear:zfar:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(originX:originY:width:height:znear:zfar:)",
      "type": "topic",
      "url": "/documentation/metal/mtlviewport/init(originx:originy:width:height:znear:zfar:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLViewport/originX": {
      "abstract": [
        {
          "text": "The x coordinate of the upper-left corner of the viewport.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "originX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLViewport/originX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "originX"
        }
      ],
      "role": "symbol",
      "title": "originX",
      "type": "topic",
      "url": "/documentation/metal/mtlviewport/originx"
    },
    "doc://com.apple.metal/documentation/Metal/MTLViewport/originY": {
      "abstract": [
        {
          "text": "The y coordinate of the upper-left corner of the viewport.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "originY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLViewport/originY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "originY"
        }
      ],
      "role": "symbol",
      "title": "originY",
      "type": "topic",
      "url": "/documentation/metal/mtlviewport/originy"
    },
    "doc://com.apple.metal/documentation/Metal/MTLViewport/width": {
      "abstract": [
        {
          "text": "The width of the viewport, in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "width"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLViewport/width",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "width"
        }
      ],
      "role": "symbol",
      "title": "width",
      "type": "topic",
      "url": "/documentation/metal/mtlviewport/width"
    },
    "doc://com.apple.metal/documentation/Metal/MTLViewport/zfar": {
      "abstract": [
        {
          "text": "The z coordinate of the far clipping plane of the viewport.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zfar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLViewport/zfar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "zfar"
        }
      ],
      "role": "symbol",
      "title": "zfar",
      "type": "topic",
      "url": "/documentation/metal/mtlviewport/zfar"
    },
    "doc://com.apple.metal/documentation/Metal/MTLViewport/znear": {
      "abstract": [
        {
          "text": "The z coordinate of the near clipping plane of the viewport.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "znear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLViewport/znear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "znear"
        }
      ],
      "role": "symbol",
      "title": "znear",
      "type": "topic",
      "url": "/documentation/metal/mtlviewport/znear"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Dynamic-Render-Pipeline-States",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLScissorRect",
        "doc://com.apple.metal/documentation/Metal/MTLVertexAmplificationViewMapping",
        "doc://com.apple.metal/documentation/Metal/MTLQuadTessellationFactorsHalf",
        "doc://com.apple.metal/documentation/Metal/MTLTriangleTessellationFactorsHalf"
      ],
      "title": "Dynamic Render Pipeline States"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Viewport",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLViewport/init()",
        "doc://com.apple.metal/documentation/Metal/MTLViewport/init(originX:originY:width:height:znear:zfar:)"
      ],
      "title": "Creating a Viewport"
    },
    {
      "anchor": "Specifying-Viewport-Boundaries",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLViewport/originX",
        "doc://com.apple.metal/documentation/Metal/MTLViewport/originY",
        "doc://com.apple.metal/documentation/Metal/MTLViewport/width",
        "doc://com.apple.metal/documentation/Metal/MTLViewport/height",
        "doc://com.apple.metal/documentation/Metal/MTLViewport/znear",
        "doc://com.apple.metal/documentation/Metal/MTLViewport/zfar"
      ],
      "title": "Specifying Viewport Boundaries"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLViewport"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLViewport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLViewport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Specifying-Viewport-Boundaries",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLViewport/originX",
                "doc://com.apple.metal/documentation/Metal/MTLViewport/originY",
                "doc://com.apple.metal/documentation/Metal/MTLViewport/width",
                "doc://com.apple.metal/documentation/Metal/MTLViewport/height",
                "doc://com.apple.metal/documentation/Metal/MTLViewport/znear",
                "doc://com.apple.metal/documentation/Metal/MTLViewport/zfar"
              ],
              "title": "Specifying Viewport Boundaries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Dynamic-Render-Pipeline-States",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLScissorRect",
                "doc://com.apple.metal/documentation/Metal/MTLVertexAmplificationViewMapping",
                "doc://com.apple.metal/documentation/Metal/MTLQuadTessellationFactorsHalf",
                "doc://com.apple.metal/documentation/Metal/MTLTriangleTessellationFactorsHalf"
              ],
              "title": "Dynamic Render Pipeline States"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLViewport"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexAmplificationViewMapping/title",
          "value": "MTLVertexAmplificationViewMapping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexAmplificationViewMapping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexAmplificationViewMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexAmplificationViewMapping/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexAmplificationViewMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLViewport~1originY/title",
          "value": "originY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLViewport~1originY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "originY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLViewport~1originX/title",
          "value": "originX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLViewport~1originX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "originX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTriangleTessellationFactorsHalf/title",
          "value": "MTLTriangleTessellationFactorsHalf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTriangleTessellationFactorsHalf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTriangleTessellationFactorsHalf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTriangleTessellationFactorsHalf/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTriangleTessellationFactorsHalf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLQuadTessellationFactorsHalf/title",
          "value": "MTLQuadTessellationFactorsHalf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLQuadTessellationFactorsHalf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLQuadTessellationFactorsHalf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLQuadTessellationFactorsHalf/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLQuadTessellationFactorsHalf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLViewport~1zfar/title",
          "value": "zfar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLViewport~1zfar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "zfar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLViewport~1height/title",
          "value": "height"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLViewport~1height/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "height"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLScissorRect/title",
          "value": "MTLScissorRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLScissorRect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLScissorRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLScissorRect/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLScissorRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLViewport~1znear/title",
          "value": "znear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLViewport~1znear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "znear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLViewport~1width/title",
          "value": "width"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLViewport~1width/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "width"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLViewport/title",
          "value": "MTLViewport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLViewport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLViewport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLViewport/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLViewport"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlviewport"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlviewport"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
