{
  "abstract": [
    {
      "text": "Locate and work with internal and external GPUs and their displays, video memory, and performance tradeoffs.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/gpu-devices-and-work-submission"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/multi-gpu-systems"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Multi-GPU Systems"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Your app can submit work to any or all of the GPUs of a system that supports multiple GPUs. For example, every Mac notebook, such as a MacBook Pro, has an internal GPU, but some have two.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4005119",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A Mac may have a Thunderbolt connection to an external GPU and its displays.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4085389",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Some systems may have even more complicated arrangements of internal and multiple external GPUs and displays.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4005116",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about Mac configurations with GPUs and displays, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/assessing-multi-gpu-and-multi-display-setups-on-an-intel-based-mac",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Start by locating all GPUs in a system and identifying their types (see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/finding-multiple-gpus-on-an-intel-based-mac",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "). Alternatively, you can locate a specific GPU that’s driving a display (see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/getting-the-gpu-that-drives-a-views-display",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ").",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When selecting a GPU, consider its memory bandwidth and the storage mode options for its memory resources (see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/adjusting-for-gpu-memory-bandwidth-tradeoffs",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ").",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For examples of how to use external GPUs in your graphics rendering or compute processing workflows, see the following:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/selecting-device-objects-for-graphics-rendering",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/selecting-device-objects-for-compute-processing",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about external GPU configurations, see ",
              "type": "text"
            },
            {
              "identifier": "https://support.apple.com/kb/HT208544",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The system may gain or lose an external GPU at any time (see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.metal/documentation/Metal/handling-external-gpu-additions-and-removals",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ").",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/coregraphics/1493900-cgdirectdisplaycopycurrentmetald": {
      "abstract": [
        {
          "text": "Returns the GPU device instance that’s currently driving a display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "CGDirectDisplayCopyCurrentMetalDevice"
        },
        {
          "kind": "text",
          "text": "(CGDirectDisplayID) -> (any MTLDevice)?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coregraphics/1493900-cgdirectdisplaycopycurrentmetald",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGDirectDisplayCopyCurrentMetalDevice(_:)",
      "type": "topic",
      "url": "/documentation/coregraphics/1493900-cgdirectdisplaycopycurrentmetald"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCopyAllDevices()": {
      "abstract": [
        {
          "text": "Returns an array of all the Metal device instances in the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCopyAllDevices"
        },
        {
          "kind": "text",
          "text": "() -> [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDevice",
          "text": "MTLDevice"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCopyAllDevices()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCopyAllDevices"
        }
      ],
      "role": "symbol",
      "title": "MTLCopyAllDevices()",
      "type": "topic",
      "url": "/documentation/metal/mtlcopyalldevices()"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCopyAllDevicesWithObserver": {
      "abstract": [
        {
          "text": "Returns an array of all the Metal GPU devices in the system and registers a notification handler that Metal calls when the device list changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTLCopyAllDevicesWithObserver"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCopyAllDevicesWithObserver",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLCopyAllDevicesWithObserver",
      "type": "topic",
      "url": "/documentation/metal/mtlcopyalldeviceswithobserver"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCopyAllDevicesWithObserver(handler:)": {
      "abstract": [
        {
          "text": "Returns an array of all the Metal GPU devices in the system and registers a notification handler that Metal calls when the device list changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCopyAllDevicesWithObserver"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLDeviceNotificationHandler",
          "text": "MTLDeviceNotificationHandler"
        },
        {
          "kind": "text",
          "text": ") -> (devices"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDevice",
          "text": "MTLDevice"
        },
        {
          "kind": "text",
          "text": "], observer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSObject",
          "text": "NSObject"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCopyAllDevicesWithObserver(handler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLCopyAllDevicesWithObserver(handler:)",
      "type": "topic",
      "url": "/documentation/metal/mtlcopyalldeviceswithobserver(handler:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCreateSystemDefaultDevice()": {
      "abstract": [
        {
          "text": "Returns the device instance Metal selects as the default.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCreateSystemDefaultDevice"
        },
        {
          "kind": "text",
          "text": "() -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDevice",
          "text": "MTLDevice"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCreateSystemDefaultDevice()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCreateSystemDefaultDevice"
        }
      ],
      "role": "symbol",
      "title": "MTLCreateSystemDefaultDevice()",
      "type": "topic",
      "url": "/documentation/metal/mtlcreatesystemdefaultdevice()"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice": {
      "abstract": [
        {
          "text": "The main Metal interface to a GPU that apps use to draw graphics and run computations in parallel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDevice"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDevice"
        }
      ],
      "role": "symbol",
      "title": "MTLDevice",
      "type": "topic",
      "url": "/documentation/metal/mtldevice"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDeviceNotificationHandler": {
      "abstract": [
        {
          "text": "A Swift closure or an Objective-C block that Metal calls",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "when the system adds or removes a GPU device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDeviceNotificationHandler"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDeviceNotificationHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDeviceNotificationHandler"
        }
      ],
      "role": "symbol",
      "title": "MTLDeviceNotificationHandler",
      "type": "topic",
      "url": "/documentation/metal/mtldevicenotificationhandler"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDeviceNotificationName": {
      "abstract": [
        {
          "text": "A notification that represents a change to a GPU device in the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDeviceNotificationName"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDeviceNotificationName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDeviceNotificationName"
        }
      ],
      "role": "symbol",
      "title": "MTLDeviceNotificationName",
      "type": "topic",
      "url": "/documentation/metal/mtldevicenotificationname"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRemoveDeviceObserver(_:)": {
      "abstract": [
        {
          "text": "Removes a registered observer of device notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLRemoveDeviceObserver"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRemoveDeviceObserver(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLRemoveDeviceObserver"
        }
      ],
      "role": "symbol",
      "title": "MTLRemoveDeviceObserver(_:)",
      "type": "topic",
      "url": "/documentation/metal/mtlremovedeviceobserver(_:)"
    },
    "doc://com.apple.metal/documentation/Metal/adjusting-for-gpu-memory-bandwidth-tradeoffs": {
      "abstract": [
        {
          "text": "Choose a suitable GPU and memory storage mode for tasks based on that GPU’s memory bandwidth on a Mac.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/adjusting-for-gpu-memory-bandwidth-tradeoffs",
      "kind": "article",
      "role": "article",
      "title": "Adjusting for GPU Memory Bandwidth Tradeoffs",
      "type": "topic",
      "url": "/documentation/metal/adjusting-for-gpu-memory-bandwidth-tradeoffs"
    },
    "doc://com.apple.metal/documentation/Metal/assessing-multi-gpu-and-multi-display-setups-on-an-intel-based-mac": {
      "abstract": [
        {
          "text": "Learn the possible GPU and display configurations for a Mac and their limitations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/assessing-multi-gpu-and-multi-display-setups-on-an-intel-based-mac",
      "kind": "article",
      "role": "article",
      "title": "Assessing Multi-GPU and Multi-Display Setups on an Intel-Based Mac",
      "type": "topic",
      "url": "/documentation/metal/assessing-multi-gpu-and-multi-display-setups-on-an-intel-based-mac"
    },
    "doc://com.apple.metal/documentation/Metal/detecting-gpu-features-and-metal-software-versions": {
      "abstract": [
        {
          "text": "Use the device object’s properties to determine how you perform tasks in Metal.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/detecting-gpu-features-and-metal-software-versions",
      "kind": "article",
      "role": "article",
      "title": "Detecting GPU Features and Metal Software Versions",
      "type": "topic",
      "url": "/documentation/metal/detecting-gpu-features-and-metal-software-versions"
    },
    "doc://com.apple.metal/documentation/Metal/finding-multiple-gpus-on-an-intel-based-mac": {
      "abstract": [
        {
          "text": "Locate, identify, and choose suitable GPUs for your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/finding-multiple-gpus-on-an-intel-based-mac",
      "kind": "article",
      "role": "article",
      "title": "Finding Multiple GPUs on an Intel-based Mac",
      "type": "topic",
      "url": "/documentation/metal/finding-multiple-gpus-on-an-intel-based-mac"
    },
    "doc://com.apple.metal/documentation/Metal/getting-the-default-gpu": {
      "abstract": [
        {
          "text": "Select the system’s default GPU device on which to run your Metal code.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/getting-the-default-gpu",
      "kind": "article",
      "role": "article",
      "title": "Getting the Default GPU",
      "type": "topic",
      "url": "/documentation/metal/getting-the-default-gpu"
    },
    "doc://com.apple.metal/documentation/Metal/getting-the-gpu-that-drives-a-views-display": {
      "abstract": [
        {
          "text": "Keep up to date with the optimal device for your display.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/getting-the-gpu-that-drives-a-views-display",
      "kind": "article",
      "role": "article",
      "title": "Getting the GPU that Drives a View’s Display",
      "type": "topic",
      "url": "/documentation/metal/getting-the-gpu-that-drives-a-views-display"
    },
    "doc://com.apple.metal/documentation/Metal/gpu-devices-and-work-submission": {
      "abstract": [
        {
          "text": "Find any available GPU, submit work to it with command buffers, suspend work, and coordinate between multiple GPUs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/gpu-devices-and-work-submission",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GPU Devices and Work Submission",
      "type": "topic",
      "url": "/documentation/metal/gpu-devices-and-work-submission"
    },
    "doc://com.apple.metal/documentation/Metal/handling-external-gpu-additions-and-removals": {
      "abstract": [
        {
          "text": "Register and respond to external GPU notifications that a person initiates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/handling-external-gpu-additions-and-removals",
      "kind": "article",
      "role": "article",
      "title": "Handling External GPU Additions and Removals",
      "type": "topic",
      "url": "/documentation/metal/handling-external-gpu-additions-and-removals"
    },
    "doc://com.apple.metal/documentation/Metal/selecting-device-objects-for-compute-processing": {
      "abstract": [
        {
          "text": "Switch dynamically between multiple GPUs to efficiently execute a compute-intensive simulation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/selecting-device-objects-for-compute-processing",
      "kind": "article",
      "role": "sampleCode",
      "title": "Selecting Device Objects for Compute Processing",
      "type": "topic",
      "url": "/documentation/metal/selecting-device-objects-for-compute-processing"
    },
    "doc://com.apple.metal/documentation/Metal/selecting-device-objects-for-graphics-rendering": {
      "abstract": [
        {
          "text": "Switch dynamically between multiple GPUs to efficiently render to a display.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/selecting-device-objects-for-graphics-rendering",
      "kind": "article",
      "role": "sampleCode",
      "title": "Selecting Device Objects for Graphics Rendering",
      "type": "topic",
      "url": "/documentation/metal/selecting-device-objects-for-graphics-rendering"
    },
    "doc://com.apple.metal/documentation/Metal/transferring-data-between-connected-gpus": {
      "abstract": [
        {
          "text": "Use high-speed connections between GPUs to transfer data quickly.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/transferring-data-between-connected-gpus",
      "kind": "article",
      "role": "article",
      "title": "Transferring Data Between Connected GPUs",
      "type": "topic",
      "url": "/documentation/metal/transferring-data-between-connected-gpus"
    },
    "doc://com.apple.metal/documentation/Metal/transferring-data-with-infinity-fabric-link": {
      "abstract": [
        {
          "text": "Efficiently execute and visualize a compute-intensive simulation using multiple GPUs with a peer-to-peer connection.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/transferring-data-with-infinity-fabric-link",
      "kind": "article",
      "role": "sampleCode",
      "title": "Transferring Data with Infinity Fabric Link",
      "type": "topic",
      "url": "/documentation/metal/transferring-data-with-infinity-fabric-link"
    },
    "https://support.apple.com/kb/HT208544": {
      "identifier": "https://support.apple.com/kb/HT208544",
      "title": "Use an external graphics processor with your Mac",
      "titleInlineContent": [
        {
          "text": "Use an external graphics processor with your Mac",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/kb/HT208544"
    },
    "media-4005116": {
      "alt": "A system diagram that shows an iMac Pro connected to an external display, an external GPU, and another external GPU that’s also connected to two additional external displays.",
      "identifier": "media-4005116",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/89d9fcddd529a30fdc2812b475477b59/media-4005116.png"
        },
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/b505af846a78d0167e779ce702fb7d61/media-4005116@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/9b36df5fcaf3f4f301f2fcac78302afb/media-4005116~dark@2x.png"
        }
      ]
    },
    "media-4005119": {
      "alt": "A system diagram that shows two built-in GPUs within a MacBook Pro.",
      "identifier": "media-4005119",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d8e39761ab67f8ac01b859eedcf54ac8/media-4005119.png"
        },
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/b022119842cf3a4a9bc64718e4ac3a20/media-4005119@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ab5912d9f24f9c355c0e7defae21739f/media-4005119~dark@2x.png"
        }
      ]
    },
    "media-4085389": {
      "alt": "A system diagram that shows an external GPU that connects a MacBook Pro to an external display.",
      "identifier": "media-4085389",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/b22a3f95645c4220377c91079b7fb6c5/media-4085389@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c97a373f0a3b0408385682fd809dae80/media-4085389~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Locating-and-Inspecting-a-GPU-Device",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/getting-the-default-gpu",
        "doc://com.apple.metal/documentation/Metal/detecting-gpu-features-and-metal-software-versions",
        "doc://com.apple.metal/documentation/Metal/MTLCreateSystemDefaultDevice()",
        "doc://com.apple.metal/documentation/Metal/MTLDevice"
      ],
      "title": "Locating and Inspecting a GPU Device"
    }
  ],
  "topicSections": [
    {
      "anchor": "Locating-GPUs",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/finding-multiple-gpus-on-an-intel-based-mac",
        "doc://com.apple.metal/documentation/Metal/getting-the-gpu-that-drives-a-views-display",
        "doc://com.apple.metal/documentation/Metal/MTLCopyAllDevices()",
        "doc://com.apple.metal/documentation/Metal/MTLCopyAllDevicesWithObserver(handler:)",
        "doc://com.apple.metal/documentation/Metal/MTLRemoveDeviceObserver(_:)",
        "doc://com.apple.documentation/documentation/coregraphics/1493900-cgdirectdisplaycopycurrentmetald",
        "doc://com.apple.metal/documentation/Metal/MTLDeviceNotificationHandler",
        "doc://com.apple.metal/documentation/Metal/MTLDeviceNotificationName"
      ],
      "title": "Locating GPUs"
    },
    {
      "anchor": "Selecting-GPUs",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/adjusting-for-gpu-memory-bandwidth-tradeoffs",
        "doc://com.apple.metal/documentation/Metal/assessing-multi-gpu-and-multi-display-setups-on-an-intel-based-mac",
        "doc://com.apple.metal/documentation/Metal/selecting-device-objects-for-graphics-rendering",
        "doc://com.apple.metal/documentation/Metal/selecting-device-objects-for-compute-processing"
      ],
      "title": "Selecting GPUs"
    },
    {
      "anchor": "Working-with-External-GPUs",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/handling-external-gpu-additions-and-removals",
        "doc://com.apple.metal/documentation/Metal/transferring-data-between-connected-gpus",
        "doc://com.apple.metal/documentation/Metal/transferring-data-with-infinity-fabric-link"
      ],
      "title": "Working with External GPUs"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Locating-GPUs",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/finding-multiple-gpus-on-an-intel-based-mac",
                "doc://com.apple.metal/documentation/Metal/getting-the-gpu-that-drives-a-views-display",
                "doc://com.apple.metal/documentation/Metal/MTLCopyAllDevices()",
                "doc://com.apple.metal/documentation/Metal/MTLCopyAllDevicesWithObserver",
                "doc://com.apple.metal/documentation/Metal/MTLRemoveDeviceObserver(_:)",
                "doc://com.apple.documentation/documentation/coregraphics/1493900-cgdirectdisplaycopycurrentmetald",
                "doc://com.apple.metal/documentation/Metal/MTLDeviceNotificationHandler",
                "doc://com.apple.metal/documentation/Metal/MTLDeviceNotificationName"
              ],
              "title": "Locating GPUs"
            },
            {
              "anchor": "Selecting-GPUs",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/adjusting-for-gpu-memory-bandwidth-tradeoffs",
                "doc://com.apple.metal/documentation/Metal/assessing-multi-gpu-and-multi-display-setups-on-an-intel-based-mac",
                "doc://com.apple.metal/documentation/Metal/selecting-device-objects-for-graphics-rendering",
                "doc://com.apple.metal/documentation/Metal/selecting-device-objects-for-compute-processing"
              ],
              "title": "Selecting GPUs"
            },
            {
              "anchor": "Working-with-External-GPUs",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/handling-external-gpu-additions-and-removals",
                "doc://com.apple.metal/documentation/Metal/transferring-data-between-connected-gpus",
                "doc://com.apple.metal/documentation/Metal/transferring-data-with-infinity-fabric-link"
              ],
              "title": "Working with External GPUs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Locating-and-Inspecting-a-GPU-Device",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/getting-the-default-gpu",
                "doc://com.apple.metal/documentation/Metal/detecting-gpu-features-and-metal-software-versions",
                "doc://com.apple.metal/documentation/Metal/MTLCreateSystemDefaultDevice()",
                "doc://com.apple.metal/documentation/Metal/MTLDevice"
              ],
              "title": "Locating and Inspecting a GPU Device"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRemoveDeviceObserver(_:)/title",
          "value": "MTLRemoveDeviceObserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRemoveDeviceObserver(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRemoveDeviceObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1coregraphics~11493900-cgdirectdisplaycopycurrentmetald/title",
          "value": "CGDirectDisplayCopyCurrentMetalDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCreateSystemDefaultDevice()/title",
          "value": "MTLCreateSystemDefaultDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCreateSystemDefaultDevice()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCreateSystemDefaultDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceNotificationName/title",
          "value": "MTLDeviceNotificationName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceNotificationName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDeviceNotificationName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceNotificationName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDeviceNotificationName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/title",
          "value": "MTLDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceNotificationHandler/title",
          "value": "MTLDeviceNotificationHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceNotificationHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDeviceNotificationHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceNotificationHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDeviceNotificationHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCopyAllDevices()/title",
          "value": "MTLCopyAllDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCopyAllDevices()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCopyAllDevices"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/multi-gpu-systems"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/multi-gpu-systems"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
