{
  "abstract": [
    {
      "text": "Implement a post-processing pipeline using the latest features on Apple GPUs.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/hdr-content"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/metal-sample-code-library"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/processing-hdr-images-with-metal"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "15.4",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Processing HDR Images with Metal"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This sample code project is associated with WWDC21 session ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc21/10161/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", and WWDC20 session ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc20/10602/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "350115b5a37a/ProcessingHDRImagesWithMetal.zip": {
      "checksum": "350115b5a37a77e2ca2007fdc3c5adf986cc83d6d90830d635b85865706e7072e5a7f23813764227fe9bf6ffd879d133b674b42de9a0df31dac6133223c757ca",
      "identifier": "350115b5a37a/ProcessingHDRImagesWithMetal.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/350115b5a37a/ProcessingHDRImagesWithMetal.zip"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/determining-support-for-edr-values": {
      "abstract": [
        {
          "text": "Check whether a display supports EDR.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/determining-support-for-edr-values",
      "kind": "article",
      "role": "article",
      "title": "Determining Support for EDR Values",
      "type": "topic",
      "url": "/documentation/metal/determining-support-for-edr-values"
    },
    "doc://com.apple.metal/documentation/Metal/displaying-hdr-content-in-a-metal-layer": {
      "abstract": [
        {
          "text": "Bring your high dynamic range (HDR) content to compatible Mac displays.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/displaying-hdr-content-in-a-metal-layer",
      "kind": "article",
      "role": "article",
      "title": "Displaying HDR Content in a Metal Layer",
      "type": "topic",
      "url": "/documentation/metal/displaying-hdr-content-in-a-metal-layer"
    },
    "doc://com.apple.metal/documentation/Metal/hdr-content": {
      "abstract": [
        {
          "text": "Take advantage of high dynamic range to present more vibrant colors in your apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/hdr-content",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HDR Content",
      "type": "topic",
      "url": "/documentation/metal/hdr-content"
    },
    "doc://com.apple.metal/documentation/Metal/implementing-tone-mapping-on-reference-displays": {
      "abstract": [
        {
          "text": "Detect reference displays and keep your content within the capabilities of the display hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/implementing-tone-mapping-on-reference-displays",
      "kind": "article",
      "role": "article",
      "title": "Implementing Tone Mapping on Reference Displays",
      "type": "topic",
      "url": "/documentation/metal/implementing-tone-mapping-on-reference-displays"
    },
    "doc://com.apple.metal/documentation/Metal/metal-sample-code-library": {
      "abstract": [
        {
          "text": "Explore the complete set of Metal samples.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-sample-code-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Sample Code Library",
      "type": "topic",
      "url": "/documentation/metal/metal-sample-code-library"
    },
    "doc://com.apple.metal/documentation/Metal/performing-your-own-tone-mapping": {
      "abstract": [
        {
          "text": "Apply your own tone mapping to get the exact behavior you want.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/performing-your-own-tone-mapping",
      "kind": "article",
      "role": "article",
      "title": "Performing Your Own Tone Mapping",
      "type": "topic",
      "url": "/documentation/metal/performing-your-own-tone-mapping"
    },
    "doc://com.apple.metal/documentation/Metal/using-color-spaces-to-display-hdr-content": {
      "abstract": [
        {
          "text": "Use a color space when you don’t need to edit or process the pixel data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/using-color-spaces-to-display-hdr-content",
      "kind": "article",
      "role": "article",
      "title": "Using Color Spaces to Display HDR Content",
      "type": "topic",
      "url": "/documentation/metal/using-color-spaces-to-display-hdr-content"
    },
    "doc://com.apple.metal/documentation/Metal/using-system-tone-mapping-on-video-content": {
      "abstract": [
        {
          "text": "Use EDR metadata to apply the default system tone mapping to a layer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/using-system-tone-mapping-on-video-content",
      "kind": "article",
      "role": "article",
      "title": "Using System Tone Mapping on Video Content",
      "type": "topic",
      "url": "/documentation/metal/using-system-tone-mapping-on-video-content"
    },
    "https://developer.apple.com/wwdc20/10602/": {
      "identifier": "https://developer.apple.com/wwdc20/10602/",
      "title": "10602: Harness Apple GPUs with Metal",
      "titleInlineContent": [
        {
          "text": "10602: Harness Apple GPUs with Metal",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc20/10602/"
    },
    "https://developer.apple.com/wwdc21/10161/": {
      "identifier": "https://developer.apple.com/wwdc21/10161/",
      "title": "10161: Explore HDR rendering with EDR",
      "titleInlineContent": [
        {
          "text": "10161: Explore HDR rendering with EDR",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc21/10161/"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "350115b5a37a/ProcessingHDRImagesWithMetal.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "High-Dynamic-Range-Content",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/displaying-hdr-content-in-a-metal-layer",
        "doc://com.apple.metal/documentation/Metal/determining-support-for-edr-values",
        "doc://com.apple.metal/documentation/Metal/using-color-spaces-to-display-hdr-content",
        "doc://com.apple.metal/documentation/Metal/using-system-tone-mapping-on-video-content",
        "doc://com.apple.metal/documentation/Metal/performing-your-own-tone-mapping",
        "doc://com.apple.metal/documentation/Metal/implementing-tone-mapping-on-reference-displays"
      ],
      "title": "High Dynamic Range Content"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "High-Dynamic-Range-Content",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/displaying-hdr-content-in-a-metal-layer",
                "doc://com.apple.metal/documentation/Metal/determining-support-for-edr-values",
                "doc://com.apple.metal/documentation/Metal/using-color-spaces-to-display-hdr-content",
                "doc://com.apple.metal/documentation/Metal/using-system-tone-mapping-on-video-content",
                "doc://com.apple.metal/documentation/Metal/performing-your-own-tone-mapping",
                "doc://com.apple.metal/documentation/Metal/implementing-tone-mapping-on-reference-displays"
              ],
              "title": "High Dynamic Range Content"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/processing-hdr-images-with-metal"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/processing-hdr-images-with-metal"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
