{
  "abstract": [
    {
      "text": "Perform parallel calculations on structured data by placing the data in textures.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/compute-passes"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/metal-sample-code-library"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/processing-a-texture-in-a-compute-function"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "10.3",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "10.3",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "10.12",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "10.2",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "12.4",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Processing a Texture in a Compute Function"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This sample processes and displays image data using Metal textures to manage the data. The sample takes advantage of Metal’s unified support for compute and graphics processing, first converting a color image to grayscale using a compute pipeline, and then rendering the resulting texture to the screen using a render pipeline. You’ll learn how to read and write textures in a compute function and how to determine the work each thread performs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For information about compute and render functions, as well as how to create and render textures, see:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/compute-passes",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/render-passes",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/resource-creation",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/resource-fundamentals",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/textures",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Write-a-Compute-Function",
          "level": 3,
          "text": "Write a Compute Function",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This sample uses a compute function, also known as a ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "compute kernel",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", to convert the texture’s pixels from color to grayscale. The compute function in this sample processes the texture’s pixels independently and concurrently. Its signature is shown below:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "kernel void",
            "grayscaleKernel(texture2d<half, access::read>  inTexture  [[texture(AAPLTextureIndexInput)]],",
            "                texture2d<half, access::write> outTexture [[texture(AAPLTextureIndexOutput)]],",
            "                uint2                          gid        [[thread_position_in_grid]])"
          ],
          "syntax": "metal",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The function takes the following resource arguments:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "inTexture",
                      "type": "codeVoice"
                    },
                    {
                      "text": ": A read-only, 2D texture that contains the input color pixels",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "outTexture",
                      "type": "codeVoice"
                    },
                    {
                      "text": ": A write-only, 2D texture that contains the output grayscale pixels",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The sample specifies the ",
              "type": "text"
            },
            {
              "code": "read",
              "type": "codeVoice"
            },
            {
              "text": " access qualifier for ",
              "type": "text"
            },
            {
              "code": "inTexture",
              "type": "codeVoice"
            },
            {
              "text": " because it reads from the texture using the ",
              "type": "text"
            },
            {
              "code": "read()",
              "type": "codeVoice"
            },
            {
              "text": " function, and the ",
              "type": "text"
            },
            {
              "code": "write",
              "type": "codeVoice"
            },
            {
              "text": " access qualifier for ",
              "type": "text"
            },
            {
              "code": "outTexture",
              "type": "codeVoice"
            },
            {
              "text": " because it writes to the texture using the ",
              "type": "text"
            },
            {
              "code": "write()",
              "type": "codeVoice"
            },
            {
              "text": " function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A compute function operates on a 1D, 2D, or 3D grid of threads, and part of designing any compute function is deciding the grid’s dimensions and how threads in the grid correspond to input and output data. The sample operates on 2D texture data, so it uses a 2D grid with each thread processing a different pixel in the source texture.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The function’s ",
              "type": "text"
            },
            {
              "code": "gid",
              "type": "codeVoice"
            },
            {
              "text": " argument provides the grid coordinates for each thread. The argument’s ",
              "type": "text"
            },
            {
              "code": "uint2",
              "type": "codeVoice"
            },
            {
              "text": " type specifies that the grid uses 2D coordinates. The ",
              "type": "text"
            },
            {
              "code": "[[thread_position_in_grid]]",
              "type": "codeVoice"
            },
            {
              "text": " attribute qualifier specifies that the GPU generates and passes each thread’s grid coordinates into the function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A grayscale pixel has the same value for each of its RGB components. The sample calculates this value by applying weights to each component. The sample uses the Rec. 709 luma coefficients for the color-to-grayscale conversion. First, the function reads a pixel from the texture, using the thread’s grid coordinates to identify which pixel each thread receives. After performing the conversion, it uses the same coordinates to write the converted pixel to the output texture.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "half4 inColor  = inTexture.read(gid);",
            "half  gray     = dot(inColor.rgb, kRec709Luma);",
            "outTexture.write(half4(gray, gray, gray, 1.0), gid);"
          ],
          "syntax": "metal",
          "type": "codeListing"
        },
        {
          "anchor": "Execute-a-Compute-Pass",
          "level": 3,
          "text": "Execute a Compute Pass",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To process the image, the sample creates an ",
              "type": "text"
            },
            {
              "code": "MTLComputeCommandEncoder",
              "type": "codeVoice"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "id<MTLComputeCommandEncoder> computeEncoder = [commandBuffer computeCommandEncoder];"
          ],
          "syntax": "objective-c",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "To dispatch the compute command, the sample needs to determine how large a grid to create when it executes the kernel, and the sample calculates this at initialization time. As described earlier, this sample uses a grid where each thread corresponds to a pixel in the texture, so the grid must be at least as large as the 2D image. For simplicity, the sample uses a 16 x 16 threadgroup size, which is small enough to be used by any GPU. In practice, however, selecting an efficient threadgroup size depends on both the size of the data and the capabilities of a specific device object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Set the compute kernel's threadgroup size to 16 x 16.",
            "_threadgroupSize = MTLSizeMake(16, 16, 1);",
            "",
            "// Calculate the number of rows and columns of threadgroups given the size of the",
            "// input image. Ensure that the grid covers the entire image (or more).",
            "_threadgroupCount.width  = (_inputTexture.width  + _threadgroupSize.width -  1) / _threadgroupSize.width;",
            "_threadgroupCount.height = (_inputTexture.height + _threadgroupSize.height - 1) / _threadgroupSize.height;",
            "// The image data is 2D, so set depth to 1.",
            "_threadgroupCount.depth = 1;"
          ],
          "syntax": "objective-c",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The sample encodes a reference to the compute pipeline and the input and output textures, and then encodes the compute command.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "",
            "[computeEncoder setComputePipelineState:_computePipelineState];",
            "",
            "[computeEncoder setTexture:_inputTexture",
            "                   atIndex:AAPLTextureIndexInput];",
            "",
            "[computeEncoder setTexture:_outputTexture",
            "                   atIndex:AAPLTextureIndexOutput];",
            "",
            "[computeEncoder dispatchThreadgroups:_threadgroupCount",
            "               threadsPerThreadgroup:_threadgroupSize];",
            "",
            "[computeEncoder endEncoding];"
          ],
          "syntax": "objective-c",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "After finishing the compute pass, the sample encodes a render pass in the same command buffer, passing the output texture from the compute command as the input to the drawing command.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Metal automatically tracks dependencies between the compute and render passes. When the sample sends the command buffer to be executed, Metal detects that the compute pass writes to the output texture and the render pass reads from it, and makes sure the GPU finishes the compute pass before starting the render pass.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "79b901be5f45/ProcessingATextureInAComputeFunction.zip": {
      "checksum": "79b901be5f45524ea3b5e6573e09e8bc4e1f1feddfc2de28aed02e7f2ee2247075206a6fb05ee95fd9feab8dfec01c48c5961f462b780168619cfa8d66df8d96",
      "identifier": "79b901be5f45/ProcessingATextureInAComputeFunction.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/79b901be5f45/ProcessingATextureInAComputeFunction.zip"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/compute-passes": {
      "abstract": [
        {
          "text": "Encode a compute pass that runs computations in parallel on a thread grid, processing and manipulating Metal resource data on multiple cores of a GPU.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/compute-passes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Compute Passes",
      "type": "topic",
      "url": "/documentation/metal/compute-passes"
    },
    "doc://com.apple.metal/documentation/Metal/metal-sample-code-library": {
      "abstract": [
        {
          "text": "Explore the complete set of Metal samples.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-sample-code-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Sample Code Library",
      "type": "topic",
      "url": "/documentation/metal/metal-sample-code-library"
    },
    "doc://com.apple.metal/documentation/Metal/performing-calculations-on-a-gpu": {
      "abstract": [
        {
          "text": "Use Metal to find GPUs and perform calculations on them.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/performing-calculations-on-a-gpu",
      "kind": "article",
      "role": "sampleCode",
      "title": "Performing Calculations on a GPU",
      "type": "topic",
      "url": "/documentation/metal/performing-calculations-on-a-gpu"
    },
    "doc://com.apple.metal/documentation/Metal/render-passes": {
      "abstract": [
        {
          "text": "Encode a render pass to draw graphics into an image.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/render-passes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Render Passes",
      "type": "topic",
      "url": "/documentation/metal/render-passes"
    },
    "doc://com.apple.metal/documentation/Metal/resource-creation": {
      "abstract": [
        {
          "text": "Load assets with input/output queues and make various resource instances, such as buffers, textures, acceleration structures, and memory heaps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/resource-creation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Resource Creation",
      "type": "topic",
      "url": "/documentation/metal/resource-creation"
    },
    "doc://com.apple.metal/documentation/Metal/resource-fundamentals": {
      "abstract": [
        {
          "text": "Learn the common attributes of all Metal memory resources, including buffers and textures, and how to manage the underlying memory.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/resource-fundamentals",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Resource Fundamentals",
      "type": "topic",
      "url": "/documentation/metal/resource-fundamentals"
    },
    "doc://com.apple.metal/documentation/Metal/textures": {
      "abstract": [
        {
          "text": "Create and manage typed data your app uses to exchange information with its shader functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/textures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Textures",
      "type": "topic",
      "url": "/documentation/metal/textures"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "79b901be5f45/ProcessingATextureInAComputeFunction.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/performing-calculations-on-a-gpu"
      ],
      "title": "Essentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/performing-calculations-on-a-gpu"
              ],
              "title": "Essentials"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/processing-a-texture-in-a-compute-function"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/processing-a-texture-in-a-compute-function"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
