{
  "abstract": [
    {
      "text": "Learn best practices for using memory efficiently in iOS and tvOS.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/resource-fundamentals"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/reducing-the-memory-footprint-of-metal-apps"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Reducing the Memory Footprint of Metal Apps"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Efficient memory usage is a critical consideration for resource-intensive Metal apps in iOS and tvOS. Create apps so they use as little memory as possible, making more memory available for other apps and system services.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "iOS and tvOS monitor your app’s total memory usage at runtime, and if the amount exceeds a predetermined limit, the system terminates your app. This limit varies by device model, so test your app on all supported devices.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Optimize-Memory-Usage-in-Your-Metal-App",
          "level": 3,
          "text": "Optimize Memory Usage in Your Metal App",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Here are some tips to understand how your Metal app is using memory, and best practices to reduce memory usage.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "Use Xcode 11 to measure memory consumption.",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": " Build your app with the iOS or tvOS SDK, then use Xcode Memory Report to observe your app’s total memory footprint during execution. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Xcode/gathering-information-about-memory-use",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more information about Xcode Memory Report.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "Use these tools to gain a deeper understanding of your app’s memory footprint.",
                  "type": "text"
                }
              ],
              "type": "strong"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Take an ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://help.apple.com/instruments/mac/current/#//apple_ref/doc/uid/TP40004652-CH19-SW13",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " trace and look at the Metal Resource Allocations Instrument, which is part of the Metal System Trace template. For more information on working with the Metal Resource Allocations Instrument, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/videos/play/wwdc2019/606/?time=1726",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use ",
                      "type": "text"
                    },
                    {
                      "code": "Debugging Tools",
                      "type": "codeVoice"
                    },
                    {
                      "text": " to capture a GPU trace.  Then use the Memory view to get a visual representation of all of a frame’s GPU resources and a table of properties for each resource. See ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/videos/play/wwdc2019/606/?time=1665",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " for detailed information about the Memory view.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Observe and take action on suggestions highlighted in the Memory insights section of the GPU trace summary. See ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/videos/play/wwdc2020-10605/?time=620",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " for more information on Memory insights.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use the memory graph tool to help identify leaks and abandoned memory. See ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/debugging_with_xcode/chapters/special_debugging_workflows.html#//apple_ref/doc/uid/TP40015022-CH9-DontLinkElementID_1",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " for more information.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Query the amount of memory available to your app at runtime using the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/os/3191911-os_proc_available_memory",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " API to help you identify memory spikes.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "Make your assets as small as possible.",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": " Avoid loading a large resource when a smaller one will do. Use compressed texture formats. Load lower-resolution textures when running on memory-constrained devices. Consider reducing the fidelity of 3D models and compressing per-vertex data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "Simplify memory-intensive special effects.",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": " Some effects, like shadows or motion blur, require large offscreen buffers for temporary image data. Consider lowering the resolution of these image buffers or applying fewer effects when running on memory-constrained devices.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "Avoid loading unused resources.",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": " Xcode can help you identify Metal objects that aren’t in use. Use Metal Debugger to get a GPU trace. Then navigate to the Memory view, and select the Unused filter.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "Designate resources as volatile when possible.",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": " Use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLPurgeableState/volatile",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLResource/setPurgeableState(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for textures and buffers the operating system can safely discard under low-memory conditions, and be subsequently recreated or reloaded by your app as needed. This design means your app keeps a cache of idle resources in memory but doesn’t count them toward the memory limit.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "Use memoryless texture storage for temporary-render targets.",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLStorageMode/memoryless",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " avoids allocating regular system memory, allowing apps to store the contents of temporary render targets directly in tile memory on the GPU.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "Use Metal resource heaps.",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": " Using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLHeap",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", your app can have Multiple Metal resources backed by the same memory allocation. For example, use resource heaps when transient resources are produced and consumed for each frame but aren’t all used together. Those not used together share the same memory, backed by a heap.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Additional-Resources",
          "level": 3,
          "text": "Additional Resources",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The WWDC video ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/videos/play/wwdc2020/10605/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " provides additional information about the latest memory-debugging tools and best practices to help you optimize the memory footprint of your Metal apps and games.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Xcode/gathering-information-about-memory-use": {
      "abstract": [
        {
          "text": "Identify memory-use inefficiencies by measuring and profiling your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/gathering-information-about-memory-use",
      "kind": "article",
      "role": "article",
      "title": "Gathering information about memory use",
      "type": "topic",
      "url": "/documentation/Xcode/gathering-information-about-memory-use"
    },
    "doc://com.apple.documentation/documentation/os/3191911-os_proc_available_memory": {
      "abstract": [
        {
          "text": "Determines the amount of memory available to the current app. ",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/os/3191911-os_proc_available_memory",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_proc_available_memory",
      "type": "topic",
      "url": "/documentation/os/3191911-os_proc_available_memory"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLHeap": {
      "abstract": [
        {
          "text": "A memory pool from which you can suballocate resources.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLHeap"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLHeap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLHeap"
        }
      ],
      "role": "symbol",
      "title": "MTLHeap",
      "type": "topic",
      "url": "/documentation/metal/mtlheap"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPurgeableState/volatile": {
      "abstract": [
        {
          "text": "The system is allowed to discard the resource to free up memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "volatile"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPurgeableState/volatile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPurgeableStateVolatile"
        }
      ],
      "role": "symbol",
      "title": "MTLPurgeableState.volatile",
      "type": "topic",
      "url": "/documentation/metal/mtlpurgeablestate/volatile"
    },
    "doc://com.apple.metal/documentation/Metal/MTLResource/setPurgeableState(_:)": {
      "abstract": [
        {
          "text": "Specifies or queries the resource’s purgeable state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setPurgeableState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLPurgeableState",
          "text": "MTLPurgeableState"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLPurgeableState",
          "text": "MTLPurgeableState"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLResource/setPurgeableState(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPurgeableState:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setPurgeableState(_:)",
      "type": "topic",
      "url": "/documentation/metal/mtlresource/setpurgeablestate(_:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLStorageMode/memoryless": {
      "abstract": [
        {
          "text": "The resource’s contents are only available to the GPU, and only exist temporarily during a render pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "memoryless"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLStorageMode/memoryless",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLStorageModeMemoryless"
        }
      ],
      "role": "symbol",
      "title": "MTLStorageMode.memoryless",
      "type": "topic",
      "url": "/documentation/metal/mtlstoragemode/memoryless"
    },
    "doc://com.apple.metal/documentation/Metal/choosing-a-resource-storage-mode-for-apple-gpus": {
      "abstract": [
        {
          "text": "Select an appropriate storage mode for your textures and buffers on Apple GPUs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/choosing-a-resource-storage-mode-for-apple-gpus",
      "kind": "article",
      "role": "article",
      "title": "Choosing a Resource Storage Mode for Apple GPUs",
      "type": "topic",
      "url": "/documentation/metal/choosing-a-resource-storage-mode-for-apple-gpus"
    },
    "doc://com.apple.metal/documentation/Metal/choosing-a-resource-storage-mode-for-intel-and-amd-gpus": {
      "abstract": [
        {
          "text": "Select an appropriate storage mode for your textures and buffers on AMD and Intel GPUs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/choosing-a-resource-storage-mode-for-intel-and-amd-gpus",
      "kind": "article",
      "role": "article",
      "title": "Choosing a Resource Storage Mode for Intel and AMD GPUs",
      "type": "topic",
      "url": "/documentation/metal/choosing-a-resource-storage-mode-for-intel-and-amd-gpus"
    },
    "doc://com.apple.metal/documentation/Metal/copying-data-to-a-private-resource": {
      "abstract": [
        {
          "text": "Use a blit command encoder to copy buffer or texture data to a private resource.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/copying-data-to-a-private-resource",
      "kind": "article",
      "role": "article",
      "title": "Copying Data to a Private Resource",
      "type": "topic",
      "url": "/documentation/metal/copying-data-to-a-private-resource"
    },
    "doc://com.apple.metal/documentation/Metal/resource-fundamentals": {
      "abstract": [
        {
          "text": "Learn the common attributes of all Metal memory resources, including buffers and textures, and how to manage the underlying memory.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/resource-fundamentals",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Resource Fundamentals",
      "type": "topic",
      "url": "/documentation/metal/resource-fundamentals"
    },
    "doc://com.apple.metal/documentation/Metal/setting-resource-storage-modes": {
      "abstract": [
        {
          "text": "Set a storage mode that defines the memory location and access permissions of a resource.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/setting-resource-storage-modes",
      "kind": "article",
      "role": "article",
      "title": "Setting Resource Storage Modes",
      "type": "topic",
      "url": "/documentation/metal/setting-resource-storage-modes"
    },
    "doc://com.apple.metal/documentation/Metal/synchronizing-a-managed-resource-in-macos": {
      "abstract": [
        {
          "text": "Manually synchronize memory for a Metal resource in apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/synchronizing-a-managed-resource-in-macos",
      "kind": "article",
      "role": "article",
      "title": "Synchronizing a Managed Resource in macOS",
      "type": "topic",
      "url": "/documentation/metal/synchronizing-a-managed-resource-in-macos"
    },
    "doc://com.apple.metal/documentation/Metal/transferring-data-between-connected-gpus": {
      "abstract": [
        {
          "text": "Use high-speed connections between GPUs to transfer data quickly.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/transferring-data-between-connected-gpus",
      "kind": "article",
      "role": "article",
      "title": "Transferring Data Between Connected GPUs",
      "type": "topic",
      "url": "/documentation/metal/transferring-data-between-connected-gpus"
    },
    "https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/debugging_with_xcode/chapters/special_debugging_workflows.html#//apple_ref/doc/uid/TP40015022-CH9-DontLinkElementID_1": {
      "identifier": "https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/debugging_with_xcode/chapters/special_debugging_workflows.html#//apple_ref/doc/uid/TP40015022-CH9-DontLinkElementID_1",
      "title": "Memory Graph Debugging",
      "titleInlineContent": [
        {
          "text": "Memory Graph Debugging",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/debugging_with_xcode/chapters/special_debugging_workflows.html#//apple_ref/doc/uid/TP40015022-CH9-DontLinkElementID_1"
    },
    "https://developer.apple.com/videos/play/wwdc2019/606/?time=1665": {
      "identifier": "https://developer.apple.com/videos/play/wwdc2019/606/?time=1665",
      "title": "Delivering Optimized Metal Apps and Games",
      "titleInlineContent": [
        {
          "text": "Delivering Optimized Metal Apps and Games",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/videos/play/wwdc2019/606/?time=1665"
    },
    "https://developer.apple.com/videos/play/wwdc2019/606/?time=1726": {
      "identifier": "https://developer.apple.com/videos/play/wwdc2019/606/?time=1726",
      "title": "Delivering Optimized Metal Apps and Games",
      "titleInlineContent": [
        {
          "text": "Delivering Optimized Metal Apps and Games",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/videos/play/wwdc2019/606/?time=1726"
    },
    "https://developer.apple.com/videos/play/wwdc2020-10605/?time=620": {
      "identifier": "https://developer.apple.com/videos/play/wwdc2020-10605/?time=620",
      "title": "Gain insights into your Metal app with Xcode 12",
      "titleInlineContent": [
        {
          "text": "Gain insights into your Metal app with Xcode 12",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/videos/play/wwdc2020-10605/?time=620"
    },
    "https://developer.apple.com/videos/play/wwdc2020/10605/": {
      "identifier": "https://developer.apple.com/videos/play/wwdc2020/10605/",
      "title": "Gain insights into your Metal app with Xcode 12",
      "titleInlineContent": [
        {
          "text": "Gain insights into your Metal app with Xcode 12",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/videos/play/wwdc2020/10605/"
    },
    "https://help.apple.com/instruments/mac/current/#//apple_ref/doc/uid/TP40004652-CH19-SW13": {
      "identifier": "https://help.apple.com/instruments/mac/current/#//apple_ref/doc/uid/TP40004652-CH19-SW13",
      "title": "Instruments",
      "titleInlineContent": [
        {
          "text": "Instruments",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://help.apple.com/instruments/mac/current/#//apple_ref/doc/uid/TP40004652-CH19-SW13"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Resource-Management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/setting-resource-storage-modes",
        "doc://com.apple.metal/documentation/Metal/choosing-a-resource-storage-mode-for-apple-gpus",
        "doc://com.apple.metal/documentation/Metal/choosing-a-resource-storage-mode-for-intel-and-amd-gpus",
        "doc://com.apple.metal/documentation/Metal/copying-data-to-a-private-resource",
        "doc://com.apple.metal/documentation/Metal/synchronizing-a-managed-resource-in-macos",
        "doc://com.apple.metal/documentation/Metal/transferring-data-between-connected-gpus"
      ],
      "title": "Resource Management"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Resource-Management",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/setting-resource-storage-modes",
                "doc://com.apple.metal/documentation/Metal/choosing-a-resource-storage-mode-for-apple-gpus",
                "doc://com.apple.metal/documentation/Metal/choosing-a-resource-storage-mode-for-intel-and-amd-gpus",
                "doc://com.apple.metal/documentation/Metal/copying-data-to-a-private-resource",
                "doc://com.apple.metal/documentation/Metal/synchronizing-a-managed-resource-in-macos",
                "doc://com.apple.metal/documentation/Metal/transferring-data-between-connected-gpus"
              ],
              "title": "Resource Management"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap/title",
          "value": "MTLHeap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLHeap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLHeap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLHeap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPurgeableState~1volatile/title",
          "value": "MTLPurgeableStateVolatile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPurgeableState~1volatile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPurgeableStateVolatile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResource~1setPurgeableState(_:)/title",
          "value": "setPurgeableState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLResource~1setPurgeableState(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPurgeableState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStorageMode~1memoryless/title",
          "value": "MTLStorageModeMemoryless"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStorageMode~1memoryless/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStorageModeMemoryless"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/reducing-the-memory-footprint-of-metal-apps"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/reducing-the-memory-footprint-of-metal-apps"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
