{
  "abstract": [
    {
      "text": "Implement realistic real-time lighting by dynamically generating reflection maps",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "by encoding a ray-tracing compute pass.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/metal-sample-code-library"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/ray-tracing-with-acceleration-structures"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/rendering-reflections-in-real-time-using-ray-tracing"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "15.3",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Rendering reflections in real time using ray tracing"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This sample code project relates to multiple WWDC sessions, including:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://developer.apple.com/wwdc24/10089/",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://developer.apple.com/wwdc22/10101/",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://developer.apple.com/wwdc21/10286/",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://developer.apple.com/wwdc21/10150/",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Configure-the-sample-code-project",
          "level": 3,
          "text": "Configure the sample code project",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To run this sample app, you need the following:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A Mac with macOS 13 or later, and Xcode 15.3 or later",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "An iOS device with iOS 16 or later",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This sample doesn’t support running in Simulator.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "a9040dd15c3d/RenderingReflectionsInRealTimeUsingRayTracing.zip": {
      "checksum": "a9040dd15c3d1e30248086af3ffdc4a6e10f35395ce5fb7f84717ae599fbe9cbb887365ae5bb9ac8521a1a05d7445db0b36cf01b6096ac14ae98709b5d9cc048",
      "identifier": "a9040dd15c3d/RenderingReflectionsInRealTimeUsingRayTracing.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/a9040dd15c3d/RenderingReflectionsInRealTimeUsingRayTracing.zip"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/accelerating-ray-tracing-and-motion-blur-using-metal": {
      "abstract": [
        {
          "text": "Generate ray-traced images with motion blur using GPU-based parallel processing.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/accelerating-ray-tracing-and-motion-blur-using-metal",
      "kind": "article",
      "role": "sampleCode",
      "title": "Accelerating ray tracing and motion blur using Metal",
      "type": "topic",
      "url": "/documentation/metal/accelerating-ray-tracing-and-motion-blur-using-metal"
    },
    "doc://com.apple.metal/documentation/Metal/accelerating-ray-tracing-using-metal": {
      "abstract": [
        {
          "text": "Implement ray-traced rendering using GPU-based parallel processing.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/accelerating-ray-tracing-using-metal",
      "kind": "article",
      "role": "sampleCode",
      "title": "Accelerating ray tracing using Metal",
      "type": "topic",
      "url": "/documentation/metal/accelerating-ray-tracing-using-metal"
    },
    "doc://com.apple.metal/documentation/Metal/control-the-ray-tracing-process-using-intersection-queries": {
      "abstract": [
        {
          "text": "Explicitly enumerate a ray’s intersections with acceleration structures by creating an intersection query object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/control-the-ray-tracing-process-using-intersection-queries",
      "kind": "article",
      "role": "sampleCode",
      "title": "Control the Ray Tracing Process Using Intersection Queries",
      "type": "topic",
      "url": "/documentation/metal/control-the-ray-tracing-process-using-intersection-queries"
    },
    "doc://com.apple.metal/documentation/Metal/metal-sample-code-library": {
      "abstract": [
        {
          "text": "Explore the complete set of Metal samples.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-sample-code-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Sample Code Library",
      "type": "topic",
      "url": "/documentation/metal/metal-sample-code-library"
    },
    "doc://com.apple.metal/documentation/Metal/ray-tracing-with-acceleration-structures": {
      "abstract": [
        {
          "text": "Build a representation of your scene’s geometry using triangles and bounding volumes to quickly trace rays through the scene.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/ray-tracing-with-acceleration-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Ray Tracing with Acceleration Structures",
      "type": "topic",
      "url": "/documentation/metal/ray-tracing-with-acceleration-structures"
    },
    "doc://com.apple.metal/documentation/Metal/rendering-a-curve-primitive-in-a-ray-tracing-scene": {
      "abstract": [
        {
          "text": "Implement ray traced rendering using GPU-based parallel processing.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/rendering-a-curve-primitive-in-a-ray-tracing-scene",
      "kind": "article",
      "role": "sampleCode",
      "title": "Rendering a curve primitive in a ray tracing scene",
      "type": "topic",
      "url": "/documentation/metal/rendering-a-curve-primitive-in-a-ray-tracing-scene"
    },
    "https://developer.apple.com/wwdc21/10150/": {
      "identifier": "https://developer.apple.com/wwdc21/10150/",
      "title": "10150: Explore hybrid rendering with Metal ray tracing",
      "titleInlineContent": [
        {
          "text": "10150: Explore hybrid rendering with Metal ray tracing",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc21/10150/"
    },
    "https://developer.apple.com/wwdc21/10286/": {
      "identifier": "https://developer.apple.com/wwdc21/10286/",
      "title": "10286: Explore bindless rendering in Metal",
      "titleInlineContent": [
        {
          "text": "10286: Explore bindless rendering in Metal",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc21/10286/"
    },
    "https://developer.apple.com/wwdc22/10101/": {
      "identifier": "https://developer.apple.com/wwdc22/10101/",
      "title": "10101: Go bindless with Metal 3",
      "titleInlineContent": [
        {
          "text": "10101: Go bindless with Metal 3",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc22/10101/"
    },
    "https://developer.apple.com/wwdc24/10089/": {
      "identifier": "https://developer.apple.com/wwdc24/10089/",
      "title": "10089: Bring your advanced games to Apple platforms",
      "titleInlineContent": [
        {
          "text": "10089: Bring your advanced games to Apple platforms",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc24/10089/"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "a9040dd15c3d/RenderingReflectionsInRealTimeUsingRayTracing.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Ray-Tracing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/accelerating-ray-tracing-using-metal",
        "doc://com.apple.metal/documentation/Metal/control-the-ray-tracing-process-using-intersection-queries",
        "doc://com.apple.metal/documentation/Metal/accelerating-ray-tracing-and-motion-blur-using-metal",
        "doc://com.apple.metal/documentation/Metal/rendering-a-curve-primitive-in-a-ray-tracing-scene"
      ],
      "title": "Ray Tracing"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Ray-Tracing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/accelerating-ray-tracing-using-metal",
                "doc://com.apple.metal/documentation/Metal/control-the-ray-tracing-process-using-intersection-queries",
                "doc://com.apple.metal/documentation/Metal/accelerating-ray-tracing-and-motion-blur-using-metal",
                "doc://com.apple.metal/documentation/Metal/rendering-a-curve-primitive-in-a-ray-tracing-scene"
              ],
              "title": "Ray Tracing"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/rendering-reflections-in-real-time-using-ray-tracing"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/rendering-reflections-in-real-time-using-ray-tracing"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
