{
  "abstract": [
    {
      "text": "Set actions that define how a render pass loads and stores a render target.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/render-passes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/setting-load-and-store-actions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Setting Load and Store Actions"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLLoadAction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " values allow you to define how a render pass loads and stores your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects. By choosing appropriate actions for your render targets, you can avoid costly and unnecessary work at the start (load) or end (store) of a render pass.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Set a render targetʼs texture on its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/texture",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property. Then, set its actions on its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/loadAction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/storeAction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let renderPassDescriptor = MTLRenderPassDescriptor()",
                    "",
                    "// Color render target",
                    "renderPassDescriptor.colorAttachments[0].texture = colorTexture",
                    "renderPassDescriptor.colorAttachments[0].loadAction = .clear",
                    "renderPassDescriptor.colorAttachments[0].storeAction = .store",
                    "",
                    "// Depth render target",
                    "renderPassDescriptor.colorAttachments[0].texture = depthTexture",
                    "renderPassDescriptor.colorAttachments[0].loadAction = .dontCare",
                    "renderPassDescriptor.colorAttachments[0].storeAction = .dontCare",
                    "",
                    "// Stencil render target",
                    "renderPassDescriptor.colorAttachments[0].texture = stencilTexture",
                    "renderPassDescriptor.colorAttachments[0].loadAction = .dontCare",
                    "renderPassDescriptor.colorAttachments[0].storeAction = .dontCare"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "MTLRenderPassDescriptor *renderPassDescriptor = [MTLRenderPassDescriptor renderPassDescriptor];",
                    "",
                    "// Color render target",
                    "renderPassDescriptor.colorAttachments[0].texture = colorTexture;",
                    "renderPassDescriptor.colorAttachments[0].loadAction = MTLLoadActionClear;",
                    "renderPassDescriptor.colorAttachments[0].storeAction = MTLStoreActionStore;",
                    "",
                    "// Depth render target",
                    "renderPassDescriptor.depthAttachment.texture = depthTexture;",
                    "renderPassDescriptor.depthAttachment.loadAction = MTLLoadActionDontCare;",
                    "renderPassDescriptor.depthAttachment.storeAction = MTLStoreActionDontCare;",
                    "",
                    "// Stencil render target",
                    "renderPassDescriptor.stencilAttachment.texture = stencilTexture;",
                    "renderPassDescriptor.stencilAttachment.loadAction = MTLLoadActionDontCare;",
                    "renderPassDescriptor.stencilAttachment.storeAction = MTLStoreActionDontCare;"
                  ],
                  "syntax": "objective-c",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "anchor": "Choose-a-Load-Action",
          "level": 3,
          "text": "Choose a Load Action",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Several options are available, depending on which of the following scenarios describes your render targetʼs loading needs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "You donʼt need the previous contents of the render target and you render to all of its pixels.",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": " Choose ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLLoadAction/dontCare",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". This action incurs no cost, and pixel values are always undefined at the start of the render pass.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3174626",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "You donʼt need the previous contents of the render target and you render to only some of its pixels.",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": " Choose ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLLoadAction/clear",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". This action incurs the cost of writing the render targetʼs clear value to each pixel.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3174625",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "You do need the previous contents of the render target and you render to only some of its pixels.",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": " Choose ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLLoadAction/load",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". This action incurs the cost of loading the previous values of each pixel from memory. This action is significantly slower than ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLLoadAction/dontCare",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLLoadAction/clear",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3174621",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "You canʼt choose ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.metal/documentation/Metal/MTLLoadAction/load",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for a memoryless render target because it isnʼt backed by system memory. For more information about memoryless render targets, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.metal/documentation/Metal/choosing-a-resource-storage-mode-for-apple-gpus",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Choose-a-Store-Action",
          "level": 3,
          "text": "Choose a Store Action",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Several options are available, depending on which of the following scenarios describes your render targetʼs storage needs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "You donʼt need to preserve the contents of the render target.",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": " Choose ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/dontCare",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". This action incurs no cost, and pixel values are always undefined at the end of the render pass. Choose this action for intermediary render targets that you use within the render pass, but you donʼt need afterward. This is typically the correct action for depth and stencil render targets.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3174628",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "You do need to preserve the contents of the render target.",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": " Choose ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/store",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". This action incurs the cost of storing the values of each pixel to memory. This is always the correct action for drawables.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3174627",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "Your render target is a multisample texture.",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": " When you perform multisampling, you decide whether to store the render targetʼs multisampled or resolved data. Multisampled data is stored in the render targetʼs ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/texture",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property. Resolved data is stored in the render targetʼs ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveTexture",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property. Refer to this table to choose a store action when multisampling:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Multisampled data stored",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Resolved data stored",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Resolve texture required",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Required store action",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Yes",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Yes",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Yes",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/storeAndMultisampleResolve",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Yes",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "No",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "No",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/store",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "No",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Yes",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Yes",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/multisampleResolve",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "No",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "No",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "No",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/dontCare",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "To store and resolve a multisample texture in a single render pass, always choose the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/storeAndMultisampleResolve",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " action and use a single render command encoder.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "You need to defer your storage choice.",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": " In some cases, you might not know which store action to use for a particular render target until you gather more render pass information. To defer your store action choice, set the temporary ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/unknown",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value when you create your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. Setting an unknown store action may avoid potential costs incurred by setting another store action prematurely. However, you must specify a valid store action before you finish encoding your render pass; otherwise, an error occurs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "You canʼt choose ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/store",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/storeAndMultisampleResolve",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for a memoryless render target because it isnʼt backed by system memory. For more information about memoryless render targets, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.metal/documentation/Metal/choosing-a-resource-storage-mode-for-apple-gpus",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Evaluate-Actions-Between-Render-Passes",
          "level": 3,
          "text": "Evaluate Actions Between Render Passes",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can use the same render targets across multiple render passes. Several load and store combinations are possible for the same render target between any two render passes, depending on which of the following scenarios describes your render targetʼs needs from one render pass to another.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "You donʼt need the previous contents of a render target in the next render pass.",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": " In the first render pass, choose ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/dontCare",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to avoid storing the contents of the render target. In the second render pass, choose ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLLoadAction/dontCare",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLLoadAction/clear",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to avoid loading the contents of the render target.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3174622",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3174623",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "You do need the previous contents of a render target in the next render pass.",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": " In the first render pass, choose ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/store",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/multisampleResolve",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/storeAndMultisampleResolve",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to store the contents of the render target. In the second render pass, choose ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLLoadAction/load",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to load the contents of the render target.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3174624",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLoadAction": {
      "abstract": [
        {
          "text": "Types of actions performed for an attachment at the start of a rendering pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLLoadAction"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLoadAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLoadAction"
        }
      ],
      "role": "symbol",
      "title": "MTLLoadAction",
      "type": "topic",
      "url": "/documentation/metal/mtlloadaction"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLoadAction/clear": {
      "abstract": [
        {
          "text": "The GPU writes a value to every pixel in the attachment at the start of the render pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clear"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLoadAction/clear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLoadActionClear"
        }
      ],
      "role": "symbol",
      "title": "MTLLoadAction.clear",
      "type": "topic",
      "url": "/documentation/metal/mtlloadaction/clear"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLoadAction/dontCare": {
      "abstract": [
        {
          "text": "The GPU has permission to discard the existing contents of the attachment at the start of the render pass, replacing them with arbitrary data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dontCare"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLoadAction/dontCare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLoadActionDontCare"
        }
      ],
      "role": "symbol",
      "title": "MTLLoadAction.dontCare",
      "type": "topic",
      "url": "/documentation/metal/mtlloadaction/dontcare"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLoadAction/load": {
      "abstract": [
        {
          "text": "The GPU preserves the existing contents of the attachment at the start of the render pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "load"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLoadAction/load",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLoadActionLoad"
        }
      ],
      "role": "symbol",
      "title": "MTLLoadAction.load",
      "type": "topic",
      "url": "/documentation/metal/mtlloadaction/load"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor": {
      "abstract": [
        {
          "text": "A render target that serves as the output destination for pixels generated by a render pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLRenderPassAttachmentDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLRenderPassAttachmentDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLRenderPassAttachmentDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassattachmentdescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/loadAction": {
      "abstract": [
        {
          "text": "The action performed by this attachment at the start of a rendering pass for a render command encoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLLoadAction",
          "text": "MTLLoadAction"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/loadAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadAction"
        }
      ],
      "role": "symbol",
      "title": "loadAction",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassattachmentdescriptor/loadaction"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveTexture": {
      "abstract": [
        {
          "text": "The destination texture used when resolving multisampled texture data into single sample values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveTexture"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/resolveTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveTexture"
        }
      ],
      "role": "symbol",
      "title": "resolveTexture",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassattachmentdescriptor/resolvetexture"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/storeAction": {
      "abstract": [
        {
          "text": "The action performed by this attachment at the end of a rendering pass for a render command encoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "storeAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLStoreAction",
          "text": "MTLStoreAction"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/storeAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "storeAction"
        }
      ],
      "role": "symbol",
      "title": "storeAction",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassattachmentdescriptor/storeaction"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/texture": {
      "abstract": [
        {
          "text": "The texture object associated with this attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "texture"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassAttachmentDescriptor/texture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "texture"
        }
      ],
      "role": "symbol",
      "title": "texture",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassattachmentdescriptor/texture"
    },
    "doc://com.apple.metal/documentation/Metal/MTLStoreAction": {
      "abstract": [
        {
          "text": "Types of actions performed for an attachment at the end of a rendering pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLStoreAction"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLStoreAction"
        }
      ],
      "role": "symbol",
      "title": "MTLStoreAction",
      "type": "topic",
      "url": "/documentation/metal/mtlstoreaction"
    },
    "doc://com.apple.metal/documentation/Metal/MTLStoreAction/dontCare": {
      "abstract": [
        {
          "text": "The GPU has permission to discard the rendered contents of the attachment at the end of the render pass, replacing them with arbitrary data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dontCare"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/dontCare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLStoreActionDontCare"
        }
      ],
      "role": "symbol",
      "title": "MTLStoreAction.dontCare",
      "type": "topic",
      "url": "/documentation/metal/mtlstoreaction/dontcare"
    },
    "doc://com.apple.metal/documentation/Metal/MTLStoreAction/multisampleResolve": {
      "abstract": [
        {
          "text": "The GPU resolves the multisampled data to one sample per pixel and stores the data to the resolve texture, discarding the multisample data afterwards.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multisampleResolve"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/multisampleResolve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLStoreActionMultisampleResolve"
        }
      ],
      "role": "symbol",
      "title": "MTLStoreAction.multisampleResolve",
      "type": "topic",
      "url": "/documentation/metal/mtlstoreaction/multisampleresolve"
    },
    "doc://com.apple.metal/documentation/Metal/MTLStoreAction/store": {
      "abstract": [
        {
          "text": "The GPU stores the rendered contents to the texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "store"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/store",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLStoreActionStore"
        }
      ],
      "role": "symbol",
      "title": "MTLStoreAction.store",
      "type": "topic",
      "url": "/documentation/metal/mtlstoreaction/store"
    },
    "doc://com.apple.metal/documentation/Metal/MTLStoreAction/storeAndMultisampleResolve": {
      "abstract": [
        {
          "text": "The GPU stores the multisample data to the multisample texture, resolves the data to a sample per pixel, and stores the data to the resolve texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "storeAndMultisampleResolve"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/storeAndMultisampleResolve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLStoreActionStoreAndMultisampleResolve"
        }
      ],
      "role": "symbol",
      "title": "MTLStoreAction.storeAndMultisampleResolve",
      "type": "topic",
      "url": "/documentation/metal/mtlstoreaction/storeandmultisampleresolve"
    },
    "doc://com.apple.metal/documentation/Metal/MTLStoreAction/unknown": {
      "abstract": [
        {
          "text": "The app will specify the store action when it encodes the render pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLStoreActionUnknown"
        }
      ],
      "role": "symbol",
      "title": "MTLStoreAction.unknown",
      "type": "topic",
      "url": "/documentation/metal/mtlstoreaction/unknown"
    },
    "doc://com.apple.metal/documentation/Metal/choosing-a-resource-storage-mode-for-apple-gpus": {
      "abstract": [
        {
          "text": "Select an appropriate storage mode for your textures and buffers on Apple GPUs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/choosing-a-resource-storage-mode-for-apple-gpus",
      "kind": "article",
      "role": "article",
      "title": "Choosing a Resource Storage Mode for Apple GPUs",
      "type": "topic",
      "url": "/documentation/metal/choosing-a-resource-storage-mode-for-apple-gpus"
    },
    "doc://com.apple.metal/documentation/Metal/customizing-render-pass-setup": {
      "abstract": [
        {
          "text": "Render into an offscreen texture by creating a custom render pass.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/customizing-render-pass-setup",
      "kind": "article",
      "role": "sampleCode",
      "title": "Customizing Render Pass Setup",
      "type": "topic",
      "url": "/documentation/metal/customizing-render-pass-setup"
    },
    "doc://com.apple.metal/documentation/Metal/improving-rendering-performance-with-vertex-amplification": {
      "abstract": [
        {
          "text": "Run draw commands that render to different outputs using the same vertex data multiple times.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/improving-rendering-performance-with-vertex-amplification",
      "kind": "article",
      "role": "article",
      "title": "Improving Rendering Performance with Vertex Amplification",
      "type": "topic",
      "url": "/documentation/metal/improving-rendering-performance-with-vertex-amplification"
    },
    "doc://com.apple.metal/documentation/Metal/render-passes": {
      "abstract": [
        {
          "text": "Encode a render pass to draw graphics into an image.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/render-passes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Render Passes",
      "type": "topic",
      "url": "/documentation/metal/render-passes"
    },
    "doc://com.apple.metal/documentation/Metal/using-a-render-pipeline-to-render-primitives": {
      "abstract": [
        {
          "text": "Render a simple 2D triangle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/using-a-render-pipeline-to-render-primitives",
      "kind": "article",
      "role": "sampleCode",
      "title": "Using a Render Pipeline to Render Primitives",
      "type": "topic",
      "url": "/documentation/metal/using-a-render-pipeline-to-render-primitives"
    },
    "media-3174621": {
      "alt": "A block diagram that shows the previous contents of a render target and its loaded contents after a Load load action.",
      "identifier": "media-3174621",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d46146edb2f07bd96ccd8cb2a93b51d2/media-3174621@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/a69a9ca41a2c1f4b0dc23a82859fdf6d/media-3174621~dark@2x.png"
        }
      ]
    },
    "media-3174622": {
      "alt": "A block diagram that shows a store and load sequence for a single render target. The render target uses a Don’t Care store action and a Don’t Care load action.",
      "identifier": "media-3174622",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/194bfae826cd6005bd66aa17d5d7a29a/media-3174622@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d0643f38193d4eda26f3b01afc104aaa/media-3174622~dark@2x.png"
        }
      ]
    },
    "media-3174623": {
      "alt": "A block diagram that shows a store and load sequence for a single render target. The render target uses a Don’t Care store action and a Clear load action.",
      "identifier": "media-3174623",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/37cea4d54747a07c9abc09a62b25761c/media-3174623@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/2ea25db62d5f9eedbf53b9c4e8059fe0/media-3174623~dark@2x.png"
        }
      ]
    },
    "media-3174624": {
      "alt": "A block diagram that shows a store and load sequence for a single render target. The render target uses a Store, Multisample Resolve, or Store And Multisample Resolve store action, and then uses a Load load action.",
      "identifier": "media-3174624",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/0909b9c8f011dff122de8ecbb7208c80/media-3174624@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/2bb3740ce8837c4c9aa455e2b5e97129/media-3174624~dark@2x.png"
        }
      ]
    },
    "media-3174625": {
      "alt": "A block diagram that shows the previous contents of a render target and its loaded contents after a Clear load action.",
      "identifier": "media-3174625",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/cc14d2ba5f3ba032a79daa39c2131125/media-3174625@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/b418c45e1dede6c1bcd0f33c20fa984a/media-3174625~dark@2x.png"
        }
      ]
    },
    "media-3174626": {
      "alt": "A block diagram that shows the previous contents of a render target and its loaded contents after a Don’t Care load action.",
      "identifier": "media-3174626",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/7cbe7d6210b0c950a2e64ee927f1cf3b/media-3174626@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e092bf8f3fbc0ccd31009bc5caac6210/media-3174626~dark@2x.png"
        }
      ]
    },
    "media-3174627": {
      "alt": "A block diagram that shows the previous contents of a render target and its stored contents after a Store store action.",
      "identifier": "media-3174627",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/85088cb54304cfe0edef050dd5a1c742/media-3174627@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c532ddc3bb5f799b6dea5b2d80d6816d/media-3174627~dark@2x.png"
        }
      ]
    },
    "media-3174628": {
      "alt": "A block diagram that shows the previous contents of a render target and its stored contents after a Don’t Care store action.",
      "identifier": "media-3174628",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/41f424b40ac240d00812b4718c0f1160/media-3174628@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/045ada16f3b58aa51e3471aa2e186efa/media-3174628~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Applying-Rendering-Techniques",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/using-a-render-pipeline-to-render-primitives",
        "doc://com.apple.metal/documentation/Metal/customizing-render-pass-setup",
        "doc://com.apple.metal/documentation/Metal/improving-rendering-performance-with-vertex-amplification"
      ],
      "title": "Applying Rendering Techniques"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Applying-Rendering-Techniques",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/using-a-render-pipeline-to-render-primitives",
                "doc://com.apple.metal/documentation/Metal/customizing-render-pass-setup",
                "doc://com.apple.metal/documentation/Metal/improving-rendering-performance-with-vertex-amplification"
              ],
              "title": "Applying Rendering Techniques"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1loadAction/title",
          "value": "loadAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1loadAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "loadAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction~1store/title",
          "value": "MTLStoreActionStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction~1store/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStoreActionStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction/title",
          "value": "MTLStoreAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStoreAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStoreAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLoadAction~1dontCare/title",
          "value": "MTLLoadActionDontCare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLoadAction~1dontCare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLoadActionDontCare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1resolveTexture/title",
          "value": "resolveTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1resolveTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resolveTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLoadAction~1clear/title",
          "value": "MTLLoadActionClear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLoadAction~1clear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLoadActionClear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1texture/title",
          "value": "texture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1texture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "texture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLoadAction/title",
          "value": "MTLLoadAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLoadAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLoadAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLoadAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLoadAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction~1dontCare/title",
          "value": "MTLStoreActionDontCare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction~1dontCare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStoreActionDontCare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction~1unknown/title",
          "value": "MTLStoreActionUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStoreActionUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLoadAction~1load/title",
          "value": "MTLLoadActionLoad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLoadAction~1load/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLoadActionLoad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction~1storeAndMultisampleResolve/title",
          "value": "MTLStoreActionStoreAndMultisampleResolve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction~1storeAndMultisampleResolve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStoreActionStoreAndMultisampleResolve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1storeAction/title",
          "value": "storeAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor~1storeAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "storeAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor/title",
          "value": "MTLRenderPassAttachmentDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPassAttachmentDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassAttachmentDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPassAttachmentDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction~1multisampleResolve/title",
          "value": "MTLStoreActionMultisampleResolve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction~1multisampleResolve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStoreActionMultisampleResolve"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/setting-load-and-store-actions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/setting-load-and-store-actions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
