{
  "abstract": [
    {
      "text": "Create static and dynamic shader libraries, and binary shader archives.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/gpu-devices-and-work-submission",
        "doc://com.apple.metal/documentation/Metal/MTLDevice"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/shader-library-and-archive-creation"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Shader Library and Archive Creation"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveDescriptor": {
      "abstract": [
        {
          "text": "A description of a binary shader archive that you want to create.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLBinaryArchiveDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBinaryArchiveDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLBinaryArchiveDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlbinaryarchivedescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveDomain": {
      "abstract": [
        {
          "text": "The domain for Metal binary archive errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLBinaryArchiveDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBinaryArchiveDomain"
        }
      ],
      "role": "symbol",
      "title": "MTLBinaryArchiveDomain",
      "type": "topic",
      "url": "/documentation/metal/mtlbinaryarchivedomain"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes when creating binary archives of compiled shader code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MTLBinaryArchiveError.Code",
      "type": "topic",
      "url": "/documentation/metal/mtlbinaryarchiveerror-swift.struct/code"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice": {
      "abstract": [
        {
          "text": "The main Metal interface to a GPU that apps use to draw graphics and run computations in parallel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDevice"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDevice"
        }
      ],
      "role": "symbol",
      "title": "MTLDevice",
      "type": "topic",
      "url": "/documentation/metal/mtldevice"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/makeBinaryArchive(descriptor:)": {
      "abstract": [
        {
          "text": "Creates a Metal binary archive instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeBinaryArchive"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLBinaryArchiveDescriptor",
          "text": "MTLBinaryArchiveDescriptor"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLBinaryArchive",
          "text": "MTLBinaryArchive"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/makeBinaryArchive(descriptor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newBinaryArchiveWithDescriptor:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeBinaryArchive(descriptor:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/makebinaryarchive(descriptor:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/makeDefaultLibrary()": {
      "abstract": [
        {
          "text": "Creates a Metal library instance that contains the functions from your app’s default Metal library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeDefaultLibrary"
        },
        {
          "kind": "text",
          "text": "() -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLLibrary",
          "text": "MTLLibrary"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/makeDefaultLibrary()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newDefaultLibrary"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeDefaultLibrary()",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/makedefaultlibrary()"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/makeDefaultLibrary(bundle:)": {
      "abstract": [
        {
          "text": "Creates a Metal library instance that contains the functions in a bundle’s default Metal library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeDefaultLibrary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "bundle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBundle",
          "text": "Bundle"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLLibrary",
          "text": "MTLLibrary"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/makeDefaultLibrary(bundle:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newDefaultLibraryWithBundle:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeDefaultLibrary(bundle:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/makedefaultlibrary(bundle:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/makeDynamicLibrary(library:)": {
      "abstract": [
        {
          "text": "Creates a Metal dynamic library instance from a Metal library instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeDynamicLibrary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "library"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLLibrary",
          "text": "MTLLibrary"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDynamicLibrary",
          "text": "MTLDynamicLibrary"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/makeDynamicLibrary(library:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newDynamicLibrary:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeDynamicLibrary(library:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/makedynamiclibrary(library:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/makeDynamicLibrary(url:)": {
      "abstract": [
        {
          "text": "Creates a Metal dynamic library instance that contains the functions in the Metal library file at a URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeDynamicLibrary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDynamicLibrary",
          "text": "MTLDynamicLibrary"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/makeDynamicLibrary(url:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newDynamicLibraryWithURL:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeDynamicLibrary(url:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/makedynamiclibrary(url:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(URL:)": {
      "abstract": [
        {
          "text": "Creates a Metal library instance that contains the functions in the Metal library file at a URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeLibrary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLLibrary",
          "text": "MTLLibrary"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(URL:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newLibraryWithURL:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeLibrary(URL:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/makelibrary(url:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(data:)": {
      "abstract": [
        {
          "text": "Creates a Metal library instance from a dispatch-data instance that contains the functions in a precompiled Metal library.",
          "type": "text"
        }
      ],
      "defaultImplementations": 1,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeLibrary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "dispatch_data_t"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLLibrary",
          "text": "MTLLibrary"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(data:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newLibraryWithData:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeLibrary(data:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/makelibrary(data:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(data:)-7khmh": {
      "abstract": [
        {
          "text": "Creates a Metal library instance that contains the functions in a precompiled Metal library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeLibrary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A4DataV",
          "text": "DispatchData"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLLibrary",
          "text": "MTLLibrary"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(data:)-7khmh",
      "kind": "symbol",
      "role": "symbol",
      "title": "makeLibrary(data:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/makelibrary(data:)-7khmh"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(filepath:)": {
      "abstract": [
        {
          "text": "Creates a Metal library instance that contains the functions in the Metal library file at a file path.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeLibrary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "filepath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLLibrary",
          "text": "MTLLibrary"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(filepath:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newLibraryWithFile:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeLibrary(filepath:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/makelibrary(filepath:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(source:options:)": {
      "abstract": [
        {
          "text": "Synchronously creates a Metal library instance by compiling the functions in a source string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeLibrary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "source"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLCompileOptions",
          "text": "MTLCompileOptions"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLLibrary",
          "text": "MTLLibrary"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(source:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newLibraryWithSource:options:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeLibrary(source:options:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/makelibrary(source:options:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(source:options:completionHandler:)": {
      "abstract": [
        {
          "text": "Asynchronously creates a Metal library instance by compiling the functions in a source string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeLibrary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "source"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLCompileOptions",
          "text": "MTLCompileOptions"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLNewLibraryCompletionHandler",
          "text": "MTLNewLibraryCompletionHandler"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(source:options:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newLibraryWithSource:options:completionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeLibrary(source:options:completionHandler:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/makelibrary(source:options:completionhandler:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(stitchedDescriptor:)": {
      "abstract": [
        {
          "text": "Synchronously creates a Metal library from the function stitching graphs in a descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeLibrary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "stitchedDescriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLStitchedLibraryDescriptor",
          "text": "MTLStitchedLibraryDescriptor"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLLibrary",
          "text": "MTLLibrary"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(stitchedDescriptor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newLibraryWithStitchedDescriptor:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeLibrary(stitchedDescriptor:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/makelibrary(stitcheddescriptor:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(stitchedDescriptor:completionHandler:)": {
      "abstract": [
        {
          "text": "Asynchronously creates a Metal library from the function stitching graphs in a descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeLibrary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "stitchedDescriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLStitchedLibraryDescriptor",
          "text": "MTLStitchedLibraryDescriptor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLNewLibraryCompletionHandler",
          "text": "MTLNewLibraryCompletionHandler"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(stitchedDescriptor:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newLibraryWithStitchedDescriptor:completionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeLibrary(stitchedDescriptor:completionHandler:)",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/makelibrary(stitcheddescriptor:completionhandler:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsDynamicLibraries": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the GPU device can create and use dynamic libraries in compute pipelines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsDynamicLibraries"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsDynamicLibraries",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsDynamicLibraries"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "supportsDynamicLibraries",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/supportsdynamiclibraries"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsRenderDynamicLibraries": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the GPU device can create and use dynamic libraries in render pipelines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsRenderDynamicLibraries"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsRenderDynamicLibraries",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsRenderDynamicLibraries"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "supportsRenderDynamicLibraries",
      "type": "topic",
      "url": "/documentation/metal/mtldevice/supportsrenderdynamiclibraries"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryDomain": {
      "abstract": [
        {
          "text": "The domain for Metal dynamic library errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDynamicLibraryDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDynamicLibraryDomain"
        }
      ],
      "role": "symbol",
      "title": "MTLDynamicLibraryDomain",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibrarydomain"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes that Metal can generate when creating dynamic libraries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MTLDynamicLibraryError.Code",
      "type": "topic",
      "url": "/documentation/metal/mtldynamiclibraryerror-swift.struct/code"
    },
    "doc://com.apple.metal/documentation/Metal/MTLNewLibraryCompletionHandler": {
      "abstract": [
        {
          "text": "A completion handler signature a method calls when it finishes creating a Metal library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLNewLibraryCompletionHandler"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLNewLibraryCompletionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLNewLibraryCompletionHandler"
        }
      ],
      "role": "symbol",
      "title": "MTLNewLibraryCompletionHandler",
      "type": "topic",
      "url": "/documentation/metal/mtlnewlibrarycompletionhandler"
    },
    "doc://com.apple.metal/documentation/Metal/device-inspection": {
      "abstract": [
        {
          "text": "Locate and identify a GPU and the features it supports, and sample its counters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/device-inspection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Device Inspection",
      "type": "topic",
      "url": "/documentation/metal/device-inspection"
    },
    "doc://com.apple.metal/documentation/Metal/gpu-devices-and-work-submission": {
      "abstract": [
        {
          "text": "Find any available GPU, submit work to it with command buffers, suspend work, and coordinate between multiple GPUs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/gpu-devices-and-work-submission",
      "kind": "article",
      "role": "collectionGroup",
      "title": "GPU Devices and Work Submission",
      "type": "topic",
      "url": "/documentation/metal/gpu-devices-and-work-submission"
    },
    "doc://com.apple.metal/documentation/Metal/pipeline-state-creation": {
      "abstract": [
        {
          "text": "Create pipeline states for render and compute passes, samplers, depth and stencil states, and indirect command buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/pipeline-state-creation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Pipeline State Creation",
      "type": "topic",
      "url": "/documentation/metal/pipeline-state-creation"
    },
    "doc://com.apple.metal/documentation/Metal/resource-creation": {
      "abstract": [
        {
          "text": "Load assets with input/output queues and make various resource instances, such as buffers, textures, acceleration structures, and memory heaps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/resource-creation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Resource Creation",
      "type": "topic",
      "url": "/documentation/metal/resource-creation"
    },
    "doc://com.apple.metal/documentation/Metal/work-submission": {
      "abstract": [
        {
          "text": "Create queues that submit work to the GPU or load assets into GPU resources, and indirect command buffers that group your frequent commands together.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/work-submission",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Work Submission",
      "type": "topic",
      "url": "/documentation/metal/work-submission"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-GPU-Devices",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/device-inspection",
        "doc://com.apple.metal/documentation/Metal/work-submission",
        "doc://com.apple.metal/documentation/Metal/pipeline-state-creation",
        "doc://com.apple.metal/documentation/Metal/resource-creation"
      ],
      "title": "Working with GPU Devices"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Shader-Libraries",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLDevice/makeDefaultLibrary()",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/makeDefaultLibrary(bundle:)",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(URL:)",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(source:options:)",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(source:options:completionHandler:)",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(stitchedDescriptor:)",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(stitchedDescriptor:completionHandler:)",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(data:)-7khmh",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(data:)",
        "doc://com.apple.metal/documentation/Metal/MTLNewLibraryCompletionHandler",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(filepath:)"
      ],
      "title": "Creating Shader Libraries"
    },
    {
      "anchor": "Creating-Dynamic-Shader-Libraries",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsDynamicLibraries",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsRenderDynamicLibraries",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/makeDynamicLibrary(library:)",
        "doc://com.apple.metal/documentation/Metal/MTLDevice/makeDynamicLibrary(url:)",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code",
        "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryDomain"
      ],
      "title": "Creating Dynamic Shader Libraries"
    },
    {
      "anchor": "Creating-Binary-Shader-Archives",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLDevice/makeBinaryArchive(descriptor:)",
        "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveDescriptor",
        "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct/Code",
        "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveDomain"
      ],
      "title": "Creating Binary Shader Archives"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Shader-Libraries",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLDevice/makeDefaultLibrary()",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/makeDefaultLibrary(bundle:)",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(URL:)",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(source:options:)",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(source:options:completionHandler:)",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(stitchedDescriptor:)",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(stitchedDescriptor:completionHandler:)",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(data:)",
                "doc://com.apple.metal/documentation/Metal/MTLNewLibraryCompletionHandler",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/makeLibrary(filepath:)"
              ],
              "title": "Creating Shader Libraries"
            },
            {
              "anchor": "Creating-Dynamic-Shader-Libraries",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsDynamicLibraries",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/supportsRenderDynamicLibraries",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/makeDynamicLibrary(library:)",
                "doc://com.apple.metal/documentation/Metal/MTLDevice/makeDynamicLibrary(url:)",
                "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryError-swift.struct/Code",
                "doc://com.apple.metal/documentation/Metal/MTLDynamicLibraryDomain"
              ],
              "title": "Creating Dynamic Shader Libraries"
            },
            {
              "anchor": "Creating-Binary-Shader-Archives",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLDevice/makeBinaryArchive(descriptor:)",
                "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveDescriptor",
                "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveError-swift.struct/Code",
                "doc://com.apple.metal/documentation/Metal/MTLBinaryArchiveDomain"
              ],
              "title": "Creating Binary Shader Archives"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-GPU-Devices",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/device-inspection",
                "doc://com.apple.metal/documentation/Metal/work-submission",
                "doc://com.apple.metal/documentation/Metal/pipeline-state-creation",
                "doc://com.apple.metal/documentation/Metal/resource-creation"
              ],
              "title": "Working with GPU Devices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeLibrary(stitchedDescriptor:completionHandler:)/title",
          "value": "newLibraryWithStitchedDescriptor:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeLibrary(stitchedDescriptor:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newLibraryWithStitchedDescriptor:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinaryArchiveDescriptor/title",
          "value": "MTLBinaryArchiveDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinaryArchiveDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBinaryArchiveDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinaryArchiveDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBinaryArchiveDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeLibrary(stitchedDescriptor:)/title",
          "value": "newLibraryWithStitchedDescriptor:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeLibrary(stitchedDescriptor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newLibraryWithStitchedDescriptor:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeDynamicLibrary(url:)/title",
          "value": "newDynamicLibraryWithURL:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeDynamicLibrary(url:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newDynamicLibraryWithURL:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeLibrary(data:)/title",
          "value": "newLibraryWithData:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeLibrary(data:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newLibraryWithData:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsRenderDynamicLibraries/title",
          "value": "supportsRenderDynamicLibraries"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsRenderDynamicLibraries/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsRenderDynamicLibraries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLNewLibraryCompletionHandler/title",
          "value": "MTLNewLibraryCompletionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLNewLibraryCompletionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLNewLibraryCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLNewLibraryCompletionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLNewLibraryCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeBinaryArchive(descriptor:)/title",
          "value": "newBinaryArchiveWithDescriptor:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeBinaryArchive(descriptor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newBinaryArchiveWithDescriptor:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeDefaultLibrary(bundle:)/title",
          "value": "newDefaultLibraryWithBundle:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeDefaultLibrary(bundle:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newDefaultLibraryWithBundle:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeLibrary(URL:)/title",
          "value": "newLibraryWithURL:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeLibrary(URL:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newLibraryWithURL:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code/title",
          "value": "MTLDynamicLibraryError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDynamicLibraryError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDynamicLibraryError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeLibrary(source:options:)/title",
          "value": "newLibraryWithSource:options:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeLibrary(source:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newLibraryWithSource:options:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryDomain/title",
          "value": "MTLDynamicLibraryDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDynamicLibraryDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDynamicLibraryDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeLibrary(filepath:)/title",
          "value": "newLibraryWithFile:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeLibrary(filepath:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newLibraryWithFile:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeDefaultLibrary()/title",
          "value": "newDefaultLibrary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeDefaultLibrary()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newDefaultLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeDynamicLibrary(library:)/title",
          "value": "newDynamicLibrary:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeDynamicLibrary(library:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newDynamicLibrary:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeLibrary(source:options:completionHandler:)/title",
          "value": "newLibraryWithSource:options:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1makeLibrary(source:options:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newLibraryWithSource:options:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinaryArchiveDomain/title",
          "value": "MTLBinaryArchiveDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinaryArchiveDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBinaryArchiveDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinaryArchiveError-swift.struct~1Code/title",
          "value": "MTLBinaryArchiveError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinaryArchiveError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBinaryArchiveError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBinaryArchiveError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBinaryArchiveError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/title",
          "value": "MTLDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsDynamicLibraries/title",
          "value": "supportsDynamicLibraries"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice~1supportsDynamicLibraries/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsDynamicLibraries"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/shader-library-and-archive-creation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/shader-library-and-archive-creation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
