{
  "abstract": [
    {
      "text": "Assign resources to tile shaders, including buffers, textures, acceleration structures, sampler states, and function tables.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/render-passes",
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/tile-shaders-resource-preparation-commands"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Tile Shaders Resource Preparation Commands"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "All tile shaders share an argument table for each resource type, such as buffers, textures, and sampler states. These argument tables are separate from other shader types, each of which have their own argument tables, one for each resource type.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder": {
      "abstract": [
        {
          "text": "An interface that encodes a render pass into a command buffer, including all its draw calls and configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLRenderCommandEncoder"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLRenderCommandEncoder"
        }
      ],
      "role": "symbol",
      "title": "MTLRenderCommandEncoder",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileAccelerationStructure(_:bufferIndex:)": {
      "abstract": [
        {
          "text": "Assigns an acceleration structure to an entry in the tile shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTileAccelerationStructure"
        },
        {
          "kind": "text",
          "text": "((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLAccelerationStructure",
          "text": "MTLAccelerationStructure"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "bufferIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileAccelerationStructure(_:bufferIndex:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTileAccelerationStructure:atBufferIndex:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setTileAccelerationStructure(_:bufferIndex:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/settileaccelerationstructure(_:bufferindex:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileBuffer(_:offset:index:)": {
      "abstract": [
        {
          "text": "Assigns a buffer to an entry in the tile shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTileBuffer"
        },
        {
          "kind": "text",
          "text": "((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLBuffer",
          "text": "MTLBuffer"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "offset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "index"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileBuffer(_:offset:index:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTileBuffer:offset:atIndex:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setTileBuffer(_:offset:index:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/settilebuffer(_:offset:index:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileBufferOffset(_:index:)": {
      "abstract": [
        {
          "text": "Updates an entry in the tile shader argument table with a new location within the entry’s current buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTileBufferOffset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "index"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileBufferOffset(_:index:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTileBufferOffset:atIndex:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setTileBufferOffset(_:index:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/settilebufferoffset(_:index:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileBuffers(_:offsets:range:)": {
      "abstract": [
        {
          "text": "Assigns multiple buffers to a range of entries in the tile shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTileBuffers"
        },
        {
          "kind": "text",
          "text": "([(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLBuffer",
          "text": "MTLBuffer"
        },
        {
          "kind": "text",
          "text": ")?], "
        },
        {
          "kind": "externalParam",
          "text": "offsets"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "range"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sn",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileBuffers(_:offsets:range:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setTileBuffers(_:offsets:range:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/settilebuffers(_:offsets:range:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileBuffers:offsets:withRange:": {
      "abstract": [
        {
          "text": "Assigns multiple buffers to a range of entries in the tile shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setTileBuffers:offsets:withRange:"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileBuffers:offsets:withRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTileBuffers:offsets:withRange:"
        }
      ],
      "role": "symbol",
      "title": "setTileBuffers:offsets:withRange:",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/settilebuffers:offsets:withrange:"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileBytes(_:length:index:)": {
      "abstract": [
        {
          "text": "Creates a buffer from bytes and assigns it to an entry in the tile shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTileBytes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "length"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "index"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileBytes(_:length:index:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTileBytes:length:atIndex:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setTileBytes(_:length:index:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/settilebytes(_:length:index:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileIntersectionFunctionTable(_:bufferIndex:)": {
      "abstract": [
        {
          "text": "Assigns an intersection function table to an entry in the tile shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTileIntersectionFunctionTable"
        },
        {
          "kind": "text",
          "text": "((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLIntersectionFunctionTable",
          "text": "MTLIntersectionFunctionTable"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "bufferIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileIntersectionFunctionTable(_:bufferIndex:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTileIntersectionFunctionTable:atBufferIndex:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setTileIntersectionFunctionTable(_:bufferIndex:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/settileintersectionfunctiontable(_:bufferindex:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileIntersectionFunctionTables(_:bufferRange:)": {
      "abstract": [
        {
          "text": "Assigns multiple intersection function tables to a range of entries in the tile shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTileIntersectionFunctionTables"
        },
        {
          "kind": "text",
          "text": "([(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLIntersectionFunctionTable",
          "text": "MTLIntersectionFunctionTable"
        },
        {
          "kind": "text",
          "text": ")?], "
        },
        {
          "kind": "externalParam",
          "text": "bufferRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sn",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileIntersectionFunctionTables(_:bufferRange:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setTileIntersectionFunctionTables(_:bufferRange:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/settileintersectionfunctiontables(_:bufferrange:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileIntersectionFunctionTables:withBufferRange:": {
      "abstract": [
        {
          "text": "Assigns multiple intersection function tables to a range of entries in the tile shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setTileIntersectionFunctionTables:withBufferRange:"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileIntersectionFunctionTables:withBufferRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTileIntersectionFunctionTables:withBufferRange:"
        }
      ],
      "role": "symbol",
      "title": "setTileIntersectionFunctionTables:withBufferRange:",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/settileintersectionfunctiontables:withbufferrange:"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileSamplerState(_:index:)": {
      "abstract": [
        {
          "text": "Assigns a sampler state to an entry in the tile shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTileSamplerState"
        },
        {
          "kind": "text",
          "text": "((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLSamplerState",
          "text": "MTLSamplerState"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "index"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileSamplerState(_:index:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTileSamplerState:atIndex:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setTileSamplerState(_:index:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/settilesamplerstate(_:index:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileSamplerState(_:lodMinClamp:lodMaxClamp:index:)": {
      "abstract": [
        {
          "text": "Assigns a sampler state and clamp values to an entry in the tile shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTileSamplerState"
        },
        {
          "kind": "text",
          "text": "((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLSamplerState",
          "text": "MTLSamplerState"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "lodMinClamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "lodMaxClamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "index"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileSamplerState(_:lodMinClamp:lodMaxClamp:index:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTileSamplerState:lodMinClamp:lodMaxClamp:atIndex:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setTileSamplerState(_:lodMinClamp:lodMaxClamp:index:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/settilesamplerstate(_:lodminclamp:lodmaxclamp:index:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileSamplerStates(_:lodMinClamps:lodMaxClamps:range:)": {
      "abstract": [
        {
          "text": "Assigns multiple sampler states and clamp values to a range of entries in the tile shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTileSamplerStates"
        },
        {
          "kind": "text",
          "text": "([(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLSamplerState",
          "text": "MTLSamplerState"
        },
        {
          "kind": "text",
          "text": ")?], "
        },
        {
          "kind": "externalParam",
          "text": "lodMinClamps"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "lodMaxClamps"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "range"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sn",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileSamplerStates(_:lodMinClamps:lodMaxClamps:range:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setTileSamplerStates(_:lodMinClamps:lodMaxClamps:range:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/settilesamplerstates(_:lodminclamps:lodmaxclamps:range:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileSamplerStates(_:range:)": {
      "abstract": [
        {
          "text": "Assigns multiple sampler states to a range of entries in the tile shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTileSamplerStates"
        },
        {
          "kind": "text",
          "text": "([(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLSamplerState",
          "text": "MTLSamplerState"
        },
        {
          "kind": "text",
          "text": ")?], "
        },
        {
          "kind": "externalParam",
          "text": "range"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sn",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileSamplerStates(_:range:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setTileSamplerStates(_:range:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/settilesamplerstates(_:range:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileSamplerStates:lodMinClamps:lodMaxClamps:withRange:": {
      "abstract": [
        {
          "text": "Assigns multiple sampler states and clamp values to a range of entries in the tile shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setTileSamplerStates:lodMinClamps:lodMaxClamps:withRange:"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileSamplerStates:lodMinClamps:lodMaxClamps:withRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTileSamplerStates:lodMinClamps:lodMaxClamps:withRange:"
        }
      ],
      "role": "symbol",
      "title": "setTileSamplerStates:lodMinClamps:lodMaxClamps:withRange:",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/settilesamplerstates:lodminclamps:lodmaxclamps:withrange:"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileSamplerStates:withRange:": {
      "abstract": [
        {
          "text": "Assigns multiple sampler states to a range of entries in the tile shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setTileSamplerStates:withRange:"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileSamplerStates:withRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTileSamplerStates:withRange:"
        }
      ],
      "role": "symbol",
      "title": "setTileSamplerStates:withRange:",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/settilesamplerstates:withrange:"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileTexture(_:index:)": {
      "abstract": [
        {
          "text": "Assigns a texture to an entry in the tile shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTileTexture"
        },
        {
          "kind": "text",
          "text": "((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "index"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileTexture(_:index:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTileTexture:atIndex:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setTileTexture(_:index:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/settiletexture(_:index:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileTextures(_:range:)": {
      "abstract": [
        {
          "text": "Assigns multiple textures to a range of entries in the tile shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTileTextures"
        },
        {
          "kind": "text",
          "text": "([(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": ")?], "
        },
        {
          "kind": "externalParam",
          "text": "range"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sn",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileTextures(_:range:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setTileTextures(_:range:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/settiletextures(_:range:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileTextures:withRange:": {
      "abstract": [
        {
          "text": "Assigns multiple textures to a range of entries in the tile shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setTileTextures:withRange:"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileTextures:withRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTileTextures:withRange:"
        }
      ],
      "role": "symbol",
      "title": "setTileTextures:withRange:",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/settiletextures:withrange:"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileVisibleFunctionTable(_:bufferIndex:)": {
      "abstract": [
        {
          "text": "Assigns a visible function table to an entry in the tile shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTileVisibleFunctionTable"
        },
        {
          "kind": "text",
          "text": "((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLVisibleFunctionTable",
          "text": "MTLVisibleFunctionTable"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "bufferIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileVisibleFunctionTable(_:bufferIndex:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTileVisibleFunctionTable:atBufferIndex:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setTileVisibleFunctionTable(_:bufferIndex:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/settilevisiblefunctiontable(_:bufferindex:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileVisibleFunctionTables(_:bufferRange:)": {
      "abstract": [
        {
          "text": "Assigns multiple visible function tables to a range of entries in the tile shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTileVisibleFunctionTables"
        },
        {
          "kind": "text",
          "text": "([(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLVisibleFunctionTable",
          "text": "MTLVisibleFunctionTable"
        },
        {
          "kind": "text",
          "text": ")?], "
        },
        {
          "kind": "externalParam",
          "text": "bufferRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sn",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileVisibleFunctionTables(_:bufferRange:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setTileVisibleFunctionTables(_:bufferRange:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/settilevisiblefunctiontables(_:bufferrange:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileVisibleFunctionTables:withBufferRange:": {
      "abstract": [
        {
          "text": "Assigns multiple visible function tables to a range of entries in the tile shader argument table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setTileVisibleFunctionTables:withBufferRange:"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileVisibleFunctionTables:withBufferRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTileVisibleFunctionTables:withBufferRange:"
        }
      ],
      "role": "symbol",
      "title": "setTileVisibleFunctionTables:withBufferRange:",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/settilevisiblefunctiontables:withbufferrange:"
    },
    "doc://com.apple.metal/documentation/Metal/argument-buffer-resource-preparation-commands": {
      "abstract": [
        {
          "text": "Load individual resources and multiple resources within a heap into GPU memory so that they’re available to shaders through argument buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/argument-buffer-resource-preparation-commands",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Argument Buffer Resource Preparation Commands",
      "type": "topic",
      "url": "/documentation/metal/argument-buffer-resource-preparation-commands"
    },
    "doc://com.apple.metal/documentation/Metal/fragment-shader-resource-preparation-commands": {
      "abstract": [
        {
          "text": "Assign resources to fragment shaders, including buffers, textures, acceleration structures, sampler states, and function tables.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/fragment-shader-resource-preparation-commands",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Fragment Shader Resource Preparation Commands",
      "type": "topic",
      "url": "/documentation/metal/fragment-shader-resource-preparation-commands"
    },
    "doc://com.apple.metal/documentation/Metal/mesh-and-object-shader-resource-preparation-commands": {
      "abstract": [
        {
          "text": "Assign resources to mesh and object shaders, including buffers, textures, acceleration structures, sampler states, and function tables.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/mesh-and-object-shader-resource-preparation-commands",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mesh and Object Shader Resource Preparation Commands",
      "type": "topic",
      "url": "/documentation/metal/mesh-and-object-shader-resource-preparation-commands"
    },
    "doc://com.apple.metal/documentation/Metal/render-passes": {
      "abstract": [
        {
          "text": "Encode a render pass to draw graphics into an image.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/render-passes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Render Passes",
      "type": "topic",
      "url": "/documentation/metal/render-passes"
    },
    "doc://com.apple.metal/documentation/Metal/vertex-shader-resource-preparation-commands": {
      "abstract": [
        {
          "text": "Assign resources to vertex shaders, including buffers, textures, acceleration structures, sampler states, and function tables.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/vertex-shader-resource-preparation-commands",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Vertex Shader Resource Preparation Commands",
      "type": "topic",
      "url": "/documentation/metal/vertex-shader-resource-preparation-commands"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Encoding-Resource-Preparation-Commands",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/mesh-and-object-shader-resource-preparation-commands",
        "doc://com.apple.metal/documentation/Metal/vertex-shader-resource-preparation-commands",
        "doc://com.apple.metal/documentation/Metal/fragment-shader-resource-preparation-commands",
        "doc://com.apple.metal/documentation/Metal/argument-buffer-resource-preparation-commands"
      ],
      "title": "Encoding Resource Preparation Commands"
    }
  ],
  "topicSections": [
    {
      "anchor": "Assigning-Buffers",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileBuffer(_:offset:index:)",
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileBuffers(_:offsets:range:)",
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileBytes(_:length:index:)",
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileBufferOffset(_:index:)"
      ],
      "title": "Assigning Buffers"
    },
    {
      "anchor": "Assigning-Textures",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileTexture(_:index:)",
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileTextures(_:range:)"
      ],
      "title": "Assigning Textures"
    },
    {
      "anchor": "Assigning-Sampler-States",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileSamplerState(_:index:)",
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileSamplerState(_:lodMinClamp:lodMaxClamp:index:)",
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileSamplerStates(_:range:)",
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileSamplerStates(_:lodMinClamps:lodMaxClamps:range:)"
      ],
      "title": "Assigning Sampler States"
    },
    {
      "anchor": "Assigning-Acceleration-Structures",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileAccelerationStructure(_:bufferIndex:)"
      ],
      "title": "Assigning Acceleration Structures"
    },
    {
      "anchor": "Assigning-Visible-Function-Tables",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileVisibleFunctionTable(_:bufferIndex:)",
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileVisibleFunctionTables(_:bufferRange:)"
      ],
      "title": "Assigning Visible Function Tables"
    },
    {
      "anchor": "Assigning-Intersection-Function-Tables",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileIntersectionFunctionTable(_:bufferIndex:)",
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileIntersectionFunctionTables(_:bufferRange:)"
      ],
      "title": "Assigning Intersection Function Tables"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Assigning-Buffers",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileBuffer(_:offset:index:)",
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileBuffers:offsets:withRange:",
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileBytes(_:length:index:)",
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileBufferOffset(_:index:)"
              ],
              "title": "Assigning Buffers"
            },
            {
              "anchor": "Assigning-Textures",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileTexture(_:index:)",
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileTextures:withRange:"
              ],
              "title": "Assigning Textures"
            },
            {
              "anchor": "Assigning-Sampler-States",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileSamplerState(_:index:)",
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileSamplerState(_:lodMinClamp:lodMaxClamp:index:)",
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileSamplerStates:withRange:",
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileSamplerStates:lodMinClamps:lodMaxClamps:withRange:"
              ],
              "title": "Assigning Sampler States"
            },
            {
              "anchor": "Assigning-Acceleration-Structures",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileAccelerationStructure(_:bufferIndex:)"
              ],
              "title": "Assigning Acceleration Structures"
            },
            {
              "anchor": "Assigning-Visible-Function-Tables",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileVisibleFunctionTable(_:bufferIndex:)",
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileVisibleFunctionTables:withBufferRange:"
              ],
              "title": "Assigning Visible Function Tables"
            },
            {
              "anchor": "Assigning-Intersection-Function-Tables",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileIntersectionFunctionTable(_:bufferIndex:)",
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTileIntersectionFunctionTables:withBufferRange:"
              ],
              "title": "Assigning Intersection Function Tables"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Encoding-Resource-Preparation-Commands",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/mesh-and-object-shader-resource-preparation-commands",
                "doc://com.apple.metal/documentation/Metal/vertex-shader-resource-preparation-commands",
                "doc://com.apple.metal/documentation/Metal/fragment-shader-resource-preparation-commands",
                "doc://com.apple.metal/documentation/Metal/argument-buffer-resource-preparation-commands"
              ],
              "title": "Encoding Resource Preparation Commands"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setTileBuffer(_:offset:index:)/title",
          "value": "setTileBuffer:offset:atIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setTileBuffer(_:offset:index:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setTileBuffer:offset:atIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setTileSamplerState(_:index:)/title",
          "value": "setTileSamplerState:atIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setTileSamplerState(_:index:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setTileSamplerState:atIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setTileAccelerationStructure(_:bufferIndex:)/title",
          "value": "setTileAccelerationStructure:atBufferIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setTileAccelerationStructure(_:bufferIndex:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setTileAccelerationStructure:atBufferIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setTileVisibleFunctionTable(_:bufferIndex:)/title",
          "value": "setTileVisibleFunctionTable:atBufferIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setTileVisibleFunctionTable(_:bufferIndex:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setTileVisibleFunctionTable:atBufferIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setTileBufferOffset(_:index:)/title",
          "value": "setTileBufferOffset:atIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setTileBufferOffset(_:index:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setTileBufferOffset:atIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setTileSamplerState(_:lodMinClamp:lodMaxClamp:index:)/title",
          "value": "setTileSamplerState:lodMinClamp:lodMaxClamp:atIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setTileSamplerState(_:lodMinClamp:lodMaxClamp:index:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setTileSamplerState:lodMinClamp:lodMaxClamp:atIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setTileTexture(_:index:)/title",
          "value": "setTileTexture:atIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setTileTexture(_:index:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setTileTexture:atIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setTileIntersectionFunctionTable(_:bufferIndex:)/title",
          "value": "setTileIntersectionFunctionTable:atBufferIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setTileIntersectionFunctionTable(_:bufferIndex:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setTileIntersectionFunctionTable:atBufferIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder/title",
          "value": "MTLRenderCommandEncoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderCommandEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderCommandEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setTileBytes(_:length:index:)/title",
          "value": "setTileBytes:length:atIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setTileBytes(_:length:index:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setTileBytes:length:atIndex:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/tile-shaders-resource-preparation-commands"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/tile-shaders-resource-preparation-commands"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
