{
  "abstract": [
    {
      "text": "Use a color space when you don’t need to edit or process the pixel data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/hdr-content"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/using-color-spaces-to-display-hdr-content"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Using Color Spaces to Display HDR Content"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you aren’t editing the content in a linear color space, and simply need to display the content with the correct transfer function, use a color space that includes that transfer function. Create a Metal layer and set its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/QuartzCore/CAMetalLayer/wantsExtendedDynamicRangeContent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Set the color space that matches the color primaries and transfer function of your content. The code below creates a Metal layer for content in the BT.2020 color space using the PQ transfer function:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let metalLayer = CAMetalLayer()",
                    "metalLayer.wantsExtendedDynamicRangeContent = true",
                    "metalLayer.pixelFormat = .bgr10a2Unorm",
                    "let name = CGColorSpace.itur_2020_PQ_EOTF",
                    "metalLayer.colorspace = CGColorSpace(name: name)"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "CAMetalLayer *metalLayer = [CAMetalLayer new];",
                    "metalLayer.wantsExtendedDynamicRangeContent = YES;",
                    "metalLayer.pixelFormat = MTLPixelFormatBGR10A2Unorm;",
                    "const CFStringRef name = kCGColorSpaceITUR_2020_PQ_EOTF;",
                    "CGColorSpaceRef colorspace = CGColorSpaceCreateWithName(name);",
                    "metalLayer.colorspace = colorspace;",
                    "CGColorSpaceRelease(colorspace);"
                  ],
                  "syntax": "objective-c",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/QuartzCore/CAMetalLayer/wantsExtendedDynamicRangeContent": {
      "abstract": [
        {
          "text": "Enables extended dynamic range values onscreen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wantsExtendedDynamicRangeContent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/QuartzCore/CAMetalLayer/wantsExtendedDynamicRangeContent",
      "kind": "symbol",
      "role": "symbol",
      "title": "wantsExtendedDynamicRangeContent",
      "type": "topic",
      "url": "/documentation/QuartzCore/CAMetalLayer/wantsExtendedDynamicRangeContent"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/determining-support-for-edr-values": {
      "abstract": [
        {
          "text": "Check whether a display supports EDR.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/determining-support-for-edr-values",
      "kind": "article",
      "role": "article",
      "title": "Determining Support for EDR Values",
      "type": "topic",
      "url": "/documentation/metal/determining-support-for-edr-values"
    },
    "doc://com.apple.metal/documentation/Metal/displaying-hdr-content-in-a-metal-layer": {
      "abstract": [
        {
          "text": "Bring your high dynamic range (HDR) content to compatible Mac displays.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/displaying-hdr-content-in-a-metal-layer",
      "kind": "article",
      "role": "article",
      "title": "Displaying HDR Content in a Metal Layer",
      "type": "topic",
      "url": "/documentation/metal/displaying-hdr-content-in-a-metal-layer"
    },
    "doc://com.apple.metal/documentation/Metal/hdr-content": {
      "abstract": [
        {
          "text": "Take advantage of high dynamic range to present more vibrant colors in your apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/hdr-content",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HDR Content",
      "type": "topic",
      "url": "/documentation/metal/hdr-content"
    },
    "doc://com.apple.metal/documentation/Metal/implementing-tone-mapping-on-reference-displays": {
      "abstract": [
        {
          "text": "Detect reference displays and keep your content within the capabilities of the display hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/implementing-tone-mapping-on-reference-displays",
      "kind": "article",
      "role": "article",
      "title": "Implementing Tone Mapping on Reference Displays",
      "type": "topic",
      "url": "/documentation/metal/implementing-tone-mapping-on-reference-displays"
    },
    "doc://com.apple.metal/documentation/Metal/performing-your-own-tone-mapping": {
      "abstract": [
        {
          "text": "Apply your own tone mapping to get the exact behavior you want.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/performing-your-own-tone-mapping",
      "kind": "article",
      "role": "article",
      "title": "Performing Your Own Tone Mapping",
      "type": "topic",
      "url": "/documentation/metal/performing-your-own-tone-mapping"
    },
    "doc://com.apple.metal/documentation/Metal/processing-hdr-images-with-metal": {
      "abstract": [
        {
          "text": "Implement a post-processing pipeline using the latest features on Apple GPUs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/processing-hdr-images-with-metal",
      "kind": "article",
      "role": "sampleCode",
      "title": "Processing HDR Images with Metal",
      "type": "topic",
      "url": "/documentation/metal/processing-hdr-images-with-metal"
    },
    "doc://com.apple.metal/documentation/Metal/using-system-tone-mapping-on-video-content": {
      "abstract": [
        {
          "text": "Use EDR metadata to apply the default system tone mapping to a layer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/using-system-tone-mapping-on-video-content",
      "kind": "article",
      "role": "article",
      "title": "Using System Tone Mapping on Video Content",
      "type": "topic",
      "url": "/documentation/metal/using-system-tone-mapping-on-video-content"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "High-Dynamic-Range-Content",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/processing-hdr-images-with-metal",
        "doc://com.apple.metal/documentation/Metal/displaying-hdr-content-in-a-metal-layer",
        "doc://com.apple.metal/documentation/Metal/determining-support-for-edr-values",
        "doc://com.apple.metal/documentation/Metal/using-system-tone-mapping-on-video-content",
        "doc://com.apple.metal/documentation/Metal/performing-your-own-tone-mapping",
        "doc://com.apple.metal/documentation/Metal/implementing-tone-mapping-on-reference-displays"
      ],
      "title": "High Dynamic Range Content"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "High-Dynamic-Range-Content",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/processing-hdr-images-with-metal",
                "doc://com.apple.metal/documentation/Metal/displaying-hdr-content-in-a-metal-layer",
                "doc://com.apple.metal/documentation/Metal/determining-support-for-edr-values",
                "doc://com.apple.metal/documentation/Metal/using-system-tone-mapping-on-video-content",
                "doc://com.apple.metal/documentation/Metal/performing-your-own-tone-mapping",
                "doc://com.apple.metal/documentation/Metal/implementing-tone-mapping-on-reference-displays"
              ],
              "title": "High Dynamic Range Content"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1QuartzCore~1CAMetalLayer~1wantsExtendedDynamicRangeContent/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "wantsExtendedDynamicRangeContent"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/using-color-spaces-to-display-hdr-content"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/using-color-spaces-to-display-hdr-content"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
