{
  "abstract": [
    {
      "text": "Create a MetalKit view and a render pass to draw the view’s contents.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/metal-sample-code-library"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/onscreen-presentation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/using-metal-to-draw-a-view's-contents"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "12.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "12.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "10.14",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "12.1",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Using Metal to Draw a View’s Contents"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In this sample, you’ll learn the basics of rendering graphics content with Metal.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "You’ll use the MetalKit framework to create a view that uses Metal to draw the contents of the view.  Then, you’ll encode commands for a render pass that erases the view to a background color.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "MetalKit automates windowing system tasks, loads textures, and handles 3D model data. See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/MetalKit",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for more information.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Prepare-a-MetalKit-View-to-Draw",
          "level": 3,
          "text": "Prepare a MetalKit View to Draw",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "MetalKit provides a class called ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MetalKit/MTKView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", which is a subclass of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppKit/NSView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " (in macOS) or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " (in iOS and tvOS).",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "MTKView",
              "type": "codeVoice"
            },
            {
              "text": " handles many of the details related to getting the content you draw with Metal onto the screen.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "code": "MTKView",
              "type": "codeVoice"
            },
            {
              "text": " needs a reference to a Metal device object in order to create resources internally, so your first step is to set the view’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MetalKit/MTKView/device",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to an existing ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "_view.device = MTLCreateSystemDefaultDevice();"
          ],
          "syntax": "objective-c",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Other properties on ",
              "type": "text"
            },
            {
              "code": "MTKView",
              "type": "codeVoice"
            },
            {
              "text": " allow you to control its behavior. To erase the contents of the view to a solid background color, you set its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MetalKit/MTKView/clearColor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property. You create the color using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLClearColorMake(_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function, specifying the red, green, blue, and alpha values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "_view.clearColor = MTLClearColorMake(0.0, 0.5, 1.0, 1.0);"
          ],
          "syntax": "objective-c",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Because you won’t be drawing animated content in this sample, configure the view so that it only draws when the contents need to be updated, such as when the view changes shape:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "_view.enableSetNeedsDisplay = YES;"
          ],
          "syntax": "objective-c",
          "type": "codeListing"
        },
        {
          "anchor": "Delegate-Drawing-Responsibilities",
          "level": 3,
          "text": "Delegate Drawing Responsibilities",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "code": "MTKView",
              "type": "codeVoice"
            },
            {
              "text": " relies on your app to issue commands to Metal to produce visual content.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "MTKView",
              "type": "codeVoice"
            },
            {
              "text": " uses the delegate pattern to inform your app when it should draw.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "To receive delegate callbacks, set the view’s ",
              "type": "text"
            },
            {
              "code": "delegate",
              "type": "codeVoice"
            },
            {
              "text": " property to an object that conforms to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MetalKit/MTKViewDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "_view.delegate = _renderer;"
          ],
          "syntax": "objective-c",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The delegate implements two methods:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The view calls the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/MetalKit/MTKViewDelegate/mtkView(_:drawableSizeWillChange:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method whenever the size of the contents changes.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "This happens when the window containing the view is resized, or when the device orientation changes (on iOS).",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "This allows your app to adapt the resolution at which it renders to the size of the view.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The view calls the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/MetalKit/MTKViewDelegate/draw(in:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method whenever it’s time to update the view’s contents.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "In this method, you create a command buffer, encode commands that tell the GPU what to draw and when to display it onscreen, and enqueue that command buffer to be executed by the GPU. This is sometimes referred to as drawing a frame. You can think of a frame as all of the work that goes into producing a single image that gets displayed on the screen. In an interactive app, like a game, you might draw many frames per second.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "In this sample, a class called ",
              "type": "text"
            },
            {
              "code": "AAPLRenderer",
              "type": "codeVoice"
            },
            {
              "text": " implements the delegate methods and takes on the responsibility of drawing.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The view controller creates an instance of this class and sets it as the view’s delegate.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-a-Render-Pass-Descriptor",
          "level": 3,
          "text": "Create a Render Pass Descriptor",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you draw, the GPU stores the results into ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "textures",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", which are blocks of memory that contain image data and are accessible to the GPU. In this sample, the ",
              "type": "text"
            },
            {
              "code": "MTKView",
              "type": "codeVoice"
            },
            {
              "text": " creates all of the textures you need to draw into the view. It creates multiple textures so that it can display the contents of one texture while you render into another.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To draw, you create a ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "render pass",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", which is a sequence of rendering commands that draw into a set of textures. When used in a render pass, textures are also called ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "render targets",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ". To create a render pass, you need a render pass descriptor, an instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassDescriptor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". In this sample, rather than configuring your own render pass descriptor, ask the MetalKit view to create one for you.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "MTLRenderPassDescriptor *renderPassDescriptor = view.currentRenderPassDescriptor;",
            "if (renderPassDescriptor == nil)",
            "{",
            "    return;",
            "}"
          ],
          "syntax": "objective-c",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "A render pass descriptor describes the set of render targets, and how they should be processed at the start and end of the render pass. Render passes also define some other aspects of rendering that are not part of this sample. The view returns a render pass descriptor with a single color attachment that points to one of the view’s textures, and otherwise configures the render pass based on the view’s properties. By default, this means that at the start of the render pass, the render target is erased to a solid color that matches the view’s ",
              "type": "text"
            },
            {
              "code": "clearColor",
              "type": "codeVoice"
            },
            {
              "text": " property, and at the end of the render pass, all changes are stored back to the texture.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Because a view’s render pass descriptor might be ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ", you should test to make sure the render pass descriptor object is non-",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " before creating the render pass.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-a-Render-Pass",
          "level": 3,
          "text": "Create a Render Pass",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You create the render pass by encoding it into the command buffer using a  ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. Call the command buffer’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBuffer/makeRenderCommandEncoder(descriptor:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method and pass in the render pass descriptor.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "id<MTLRenderCommandEncoder> commandEncoder = [commandBuffer renderCommandEncoderWithDescriptor:renderPassDescriptor];"
          ],
          "syntax": "objective-c",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "In this sample, you don’t encode any drawing commands, so the only thing the render pass does is erase the texture. Call the encoder’s ",
              "type": "text"
            },
            {
              "code": "endEncoding",
              "type": "codeVoice"
            },
            {
              "text": " method to indicate that the pass is complete.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "[commandEncoder endEncoding];"
          ],
          "syntax": "objective-c",
          "type": "codeListing"
        },
        {
          "anchor": "Present-a-Drawable-to-the-Screen",
          "level": 3,
          "text": "Present a Drawable to the Screen",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Drawing to a texture doesn’t automatically display the new contents onscreen. In fact, only some textures can be presented onscreen. In Metal, textures that can be displayed onscreen are managed by ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "drawable objects",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", and to display the content, you present the drawable.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "code": "MTKView",
              "type": "codeVoice"
            },
            {
              "text": " automatically creates drawable objects to manage its textures. Read the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MetalKit/MTKView/currentDrawable",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to get the drawable that owns the texture that is the render pass’s target. The view returns a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/QuartzCore/CAMetalDrawable",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, an object connected to Core Animation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "id<MTLDrawable> drawable = view.currentDrawable;"
          ],
          "syntax": "objective-c",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBuffer/present(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method on the command buffer, passing in the drawable.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "[commandBuffer presentDrawable:drawable];"
          ],
          "syntax": "objective-c",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "This method tells Metal that when the command buffer is scheduled for execution, Metal should coordinate with Core Animation to display the texture after rendering completes. When Core Animation presents the texture, it becomes the view’s new contents. In this sample, this means that the erased texture becomes the new background for the view. The change happens alongside any other visual updates that Core Animation makes for onscreen user interface elements.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Commit-the-Command-Buffer",
          "level": 3,
          "text": "Commit the Command Buffer",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Now that you’ve issued all the commands for the frame, commit the command buffer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "[commandBuffer commit];"
          ],
          "syntax": "objective-c",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "107fc85eb937/UsingMetalToDrawAViewsContents.zip": {
      "checksum": "107fc85eb9374b9ef5da3478c92ba8e9c574569510c5947d3c55829534d871ab29bb9da00323cd68fcc5fdb3f2bd684cbf1f1babc7ab33014cb4c32f90c92797",
      "identifier": "107fc85eb937/UsingMetalToDrawAViewsContents.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/107fc85eb937/UsingMetalToDrawAViewsContents.zip"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSView",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/AppKit/NSView"
    },
    "doc://com.apple.documentation/documentation/MetalKit": {
      "abstract": [
        {
          "text": "Build Metal apps quicker and easier using a common set of utility classes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MetalKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MetalKit",
      "type": "topic",
      "url": "/documentation/MetalKit"
    },
    "doc://com.apple.documentation/documentation/MetalKit/MTKView": {
      "abstract": [
        {
          "text": "A specialized view that creates, configures, and displays Metal objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKView"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MetalKit/MTKView",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTKView",
      "type": "topic",
      "url": "/documentation/MetalKit/MTKView"
    },
    "doc://com.apple.documentation/documentation/MetalKit/MTKView/clearColor": {
      "abstract": [
        {
          "text": "The color to use to clear the color target when creating a render pass descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clearColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MTLClearColor",
          "text": "MTLClearColor"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MetalKit/MTKView/clearColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "clearColor",
      "type": "topic",
      "url": "/documentation/MetalKit/MTKView/clearColor"
    },
    "doc://com.apple.documentation/documentation/MetalKit/MTKView/currentDrawable": {
      "abstract": [
        {
          "text": "The drawable to use for the current frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentDrawable"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CAMetalDrawable",
          "text": "CAMetalDrawable"
        },
        {
          "kind": "text",
          "text": ")? { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MetalKit/MTKView/currentDrawable",
      "kind": "symbol",
      "role": "symbol",
      "title": "currentDrawable",
      "type": "topic",
      "url": "/documentation/MetalKit/MTKView/currentDrawable"
    },
    "doc://com.apple.documentation/documentation/MetalKit/MTKView/device": {
      "abstract": [
        {
          "text": "The device object the view uses to create its Metal objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "device"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDevice",
          "text": "MTLDevice"
        },
        {
          "kind": "text",
          "text": ")? { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MetalKit/MTKView/device",
      "kind": "symbol",
      "role": "symbol",
      "title": "device",
      "type": "topic",
      "url": "/documentation/MetalKit/MTKView/device"
    },
    "doc://com.apple.documentation/documentation/MetalKit/MTKViewDelegate": {
      "abstract": [
        {
          "text": "Methods for responding to a MetalKit view’s drawing and resizing events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKViewDelegate"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MetalKit/MTKViewDelegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTKViewDelegate",
      "type": "topic",
      "url": "/documentation/MetalKit/MTKViewDelegate"
    },
    "doc://com.apple.documentation/documentation/MetalKit/MTKViewDelegate/draw(in:)": {
      "abstract": [
        {
          "text": "Draws the view’s contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draw"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "view"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTKView",
          "text": "MTKView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MetalKit/MTKViewDelegate/draw(in:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "draw(in:)",
      "type": "topic",
      "url": "/documentation/MetalKit/MTKViewDelegate/draw(in:)"
    },
    "doc://com.apple.documentation/documentation/MetalKit/MTKViewDelegate/mtkView(_:drawableSizeWillChange:)": {
      "abstract": [
        {
          "text": "Updates the view’s contents upon receiving a change in layout, resolution, or size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mtkView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "view"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTKView",
          "text": "MTKView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "drawableSizeWillChange"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MetalKit/MTKViewDelegate/mtkView(_:drawableSizeWillChange:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "mtkView(_:drawableSizeWillChange:)",
      "type": "topic",
      "url": "/documentation/MetalKit/MTKViewDelegate/mtkView(_:drawableSizeWillChange:)"
    },
    "doc://com.apple.documentation/documentation/QuartzCore/CAMetalDrawable": {
      "abstract": [
        {
          "text": "A Metal drawable associated with a Core Animation layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAMetalDrawable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDrawable",
          "text": "MTLDrawable"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/QuartzCore/CAMetalDrawable",
      "kind": "symbol",
      "role": "symbol",
      "title": "CAMetalDrawable",
      "type": "topic",
      "url": "/documentation/QuartzCore/CAMetalDrawable"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIView": {
      "abstract": [
        {
          "text": "An object that manages the content for a rectangular area on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIView",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIView",
      "type": "topic",
      "url": "/documentation/UIKit/UIView"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLClearColorMake(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a color value used to clear a color attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLClearColorMake"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MTLClearColor",
          "text": "MTLClearColor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLClearColorMake(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLClearColorMake"
        }
      ],
      "role": "symbol",
      "title": "MTLClearColorMake(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/metal/mtlclearcolormake(_:_:_:_:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBuffer/makeRenderCommandEncoder(descriptor:)": {
      "abstract": [
        {
          "text": "Creates a render command encoder from a descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeRenderCommandEncoder"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLRenderPassDescriptor",
          "text": "MTLRenderPassDescriptor"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLRenderCommandEncoder",
          "text": "MTLRenderCommandEncoder"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBuffer/makeRenderCommandEncoder(descriptor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "renderCommandEncoderWithDescriptor:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "makeRenderCommandEncoder(descriptor:)",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffer/makerendercommandencoder(descriptor:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBuffer/present(_:)": {
      "abstract": [
        {
          "text": "Presents a drawable as early as possible.",
          "type": "text"
        }
      ],
      "defaultImplementations": 1,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "present"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDrawable",
          "text": "MTLDrawable"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBuffer/present(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentDrawable:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "present(_:)",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffer/present(_:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDevice": {
      "abstract": [
        {
          "text": "The main Metal interface to a GPU that apps use to draw graphics and run computations in parallel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDevice"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDevice"
        }
      ],
      "role": "symbol",
      "title": "MTLDevice",
      "type": "topic",
      "url": "/documentation/metal/mtldevice"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder": {
      "abstract": [
        {
          "text": "An interface that encodes a render pass into a command buffer, including all its draw calls and configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLRenderCommandEncoder"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLRenderCommandEncoder"
        }
      ],
      "role": "symbol",
      "title": "MTLRenderCommandEncoder",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPassDescriptor": {
      "abstract": [
        {
          "text": "A group of render targets that hold the results of a render pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLRenderPassDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPassDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLRenderPassDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLRenderPassDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpassdescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/metal-sample-code-library": {
      "abstract": [
        {
          "text": "Explore the complete set of Metal samples.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/metal-sample-code-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metal Sample Code Library",
      "type": "topic",
      "url": "/documentation/metal/metal-sample-code-library"
    },
    "doc://com.apple.metal/documentation/Metal/onscreen-presentation": {
      "abstract": [
        {
          "text": "Show the output from a GPU’s rendering pass to the user in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/onscreen-presentation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Onscreen Presentation",
      "type": "topic",
      "url": "/documentation/metal/onscreen-presentation"
    },
    "doc://com.apple.metal/documentation/Metal/performing-calculations-on-a-gpu": {
      "abstract": [
        {
          "text": "Use Metal to find GPUs and perform calculations on them.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/performing-calculations-on-a-gpu",
      "kind": "article",
      "role": "sampleCode",
      "title": "Performing Calculations on a GPU",
      "type": "topic",
      "url": "/documentation/metal/performing-calculations-on-a-gpu"
    },
    "doc://com.apple.metal/documentation/Metal/using-a-render-pipeline-to-render-primitives": {
      "abstract": [
        {
          "text": "Render a simple 2D triangle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/using-a-render-pipeline-to-render-primitives",
      "kind": "article",
      "role": "sampleCode",
      "title": "Using a Render Pipeline to Render Primitives",
      "type": "topic",
      "url": "/documentation/metal/using-a-render-pipeline-to-render-primitives"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "107fc85eb937/UsingMetalToDrawAViewsContents.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/performing-calculations-on-a-gpu",
        "doc://com.apple.metal/documentation/Metal/using-a-render-pipeline-to-render-primitives"
      ],
      "title": "Essentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/performing-calculations-on-a-gpu",
                "doc://com.apple.metal/documentation/Metal/using-a-render-pipeline-to-render-primitives"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1MetalKit~1MTKView~1clearColor/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@MTLClearColor",
              "text": "MTLClearColor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "clearColor"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/title",
          "value": "MTLDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1MetalKit~1MTKView~1device/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "retain"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Qoobjc(pl)MTLDevice",
              "text": "id<MTLDevice>"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "device"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1QuartzCore~1CAMetalDrawable/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CAMetalDrawable"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)MTLDrawable",
              "text": "MTLDrawable"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIView/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIView"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIResponder",
              "text": "UIResponder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBuffer~1present(_:)/title",
          "value": "presentDrawable:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBuffer~1present(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "presentDrawable:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder/title",
          "value": "MTLRenderCommandEncoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderCommandEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderCommandEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1MetalKit~1MTKView/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTKView"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIView",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBuffer~1makeRenderCommandEncoder(descriptor:)/title",
          "value": "renderCommandEncoderWithDescriptor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBuffer~1makeRenderCommandEncoder(descriptor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "renderCommandEncoderWithDescriptor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassDescriptor/title",
          "value": "MTLRenderPassDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPassDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPassDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPassDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1MetalKit~1MTKViewDelegate~1draw(in:)/title",
          "value": "drawInMTKView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1MetalKit~1MTKViewDelegate~1draw(in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "drawInMTKView:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MTKView",
              "text": "MTKView"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "view"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLClearColorMake(_:_:_:_:)/title",
          "value": "MTLClearColorMake"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLClearColorMake(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLClearColorMake"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1MetalKit~1MTKViewDelegate/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTKViewDelegate"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSView/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSView"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSResponder",
              "text": "NSResponder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1MetalKit~1MTKView~1currentDrawable/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Qoobjc(pl)CAMetalDrawable",
              "text": "id<CAMetalDrawable>"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "currentDrawable"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1MetalKit~1MTKViewDelegate~1mtkView(_:drawableSizeWillChange:)/title",
          "value": "mtkView:drawableSizeWillChange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1MetalKit~1MTKViewDelegate~1mtkView(_:drawableSizeWillChange:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "mtkView:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MTKView",
              "text": "MTKView"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "view"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "drawableSizeWillChange:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGSize",
              "text": "CGSize"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "size"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/using-metal-to-draw-a-view's-contents"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/using-metal-to-draw-a-view's-contents"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
