{
  "abstract": [
    {
      "text": "Tells the delegate that the most recent snapshot has been updated.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMCameraSnapshotControlDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMCameraSnapshotControlDelegate/cameraSnapshotControlDidUpdateMostRecentSnapshot(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)HMCameraSnapshotControlDelegate(im)cameraSnapshotControlDidUpdateMostRecentSnapshot:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "cameraSnapshotControlDidUpdateMostRecentSnapshot"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)HMCameraSnapshotControl",
        "text": "HMCameraSnapshotControl"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "cameraSnapshotControlDidUpdateMostRecentSnapshot:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "cameraSnapshotControlDidUpdateMostRecentSnapshot(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "cameraSnapshotControlDidUpdateMostRecentSnapshot"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "cameraSnapshotControl"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCameraSnapshotControl",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)HMCameraSnapshotControl",
              "text": "HMCameraSnapshotControl"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The camera snapshot control responsible for the updated snapshot.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "cameraSnapshotControl"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCameraSnapshotControl": {
      "abstract": [
        {
          "text": "An object that can take an image snapshot from a camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCameraSnapshotControl"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCameraSnapshotControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCameraSnapshotControl"
        }
      ],
      "role": "symbol",
      "title": "HMCameraSnapshotControl",
      "type": "topic",
      "url": "/documentation/homekit/hmcamerasnapshotcontrol"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCameraSnapshotControlDelegate": {
      "abstract": [
        {
          "text": "A set of methods used to observe the camera’s snapshot activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCameraSnapshotControlDelegate"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCameraSnapshotControlDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCameraSnapshotControlDelegate"
        }
      ],
      "role": "symbol",
      "title": "HMCameraSnapshotControlDelegate",
      "type": "topic",
      "url": "/documentation/homekit/hmcamerasnapshotcontroldelegate"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCameraSnapshotControlDelegate/cameraSnapshotControl(_:didTake:error:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the camera has taken a new snapshot.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraSnapshotControl"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMCameraSnapshotControl",
          "text": "HMCameraSnapshotControl"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didTake"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMCameraSnapshot",
          "text": "HMCameraSnapshot"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCameraSnapshotControlDelegate/cameraSnapshotControl(_:didTake:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cameraSnapshotControl:didTakeSnapshot:error:"
        }
      ],
      "role": "symbol",
      "title": "cameraSnapshotControl(_:didTake:error:)",
      "type": "topic",
      "url": "/documentation/homekit/hmcamerasnapshotcontroldelegate/camerasnapshotcontrol(_:didtake:error:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCameraSnapshotControlDelegate/cameraSnapshotControlDidUpdateMostRecentSnapshot(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the most recent snapshot has been updated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraSnapshotControlDidUpdateMostRecentSnapshot"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMCameraSnapshotControl",
          "text": "HMCameraSnapshotControl"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCameraSnapshotControlDelegate/cameraSnapshotControlDidUpdateMostRecentSnapshot(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cameraSnapshotControlDidUpdateMostRecentSnapshot:"
        }
      ],
      "role": "symbol",
      "title": "cameraSnapshotControlDidUpdateMostRecentSnapshot(_:)",
      "type": "topic",
      "url": "/documentation/homekit/hmcamerasnapshotcontroldelegate/camerasnapshotcontroldidupdatemostrecentsnapshot(_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Observing-snapshot-activity",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCameraSnapshotControlDelegate/cameraSnapshotControl(_:didTake:error:)"
      ],
      "title": "Observing snapshot activity"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "cameraSnapshotControlDidUpdateMostRecentSnapshot:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cameraSnapshotControlDidUpdateMostRecentSnapshot:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit",
                "doc://com.apple.homekit/documentation/HomeKit/HMCameraSnapshotControlDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Observing-snapshot-activity",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCameraSnapshotControlDelegate/cameraSnapshotControl(_:didTake:error:)"
              ],
              "title": "Observing snapshot activity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "cameraSnapshotControlDidUpdateMostRecentSnapshot:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCameraSnapshotControl",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)HMCameraSnapshotControl",
                    "text": "HMCameraSnapshotControl"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "cameraSnapshotControl"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The camera snapshot control responsible for the updated snapshot.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "cameraSnapshotControl"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraSnapshotControlDelegate/title",
          "value": "HMCameraSnapshotControlDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraSnapshotControlDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCameraSnapshotControlDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraSnapshotControlDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCameraSnapshotControlDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraSnapshotControl/title",
          "value": "HMCameraSnapshotControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraSnapshotControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCameraSnapshotControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraSnapshotControl/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCameraSnapshotControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraSnapshotControlDelegate~1cameraSnapshotControl(_:didTake:error:)/title",
          "value": "cameraSnapshotControl:didTakeSnapshot:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraSnapshotControlDelegate~1cameraSnapshotControl(_:didTake:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cameraSnapshotControl:didTakeSnapshot:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraSnapshotControlDelegate~1cameraSnapshotControlDidUpdateMostRecentSnapshot(_:)/title",
          "value": "cameraSnapshotControlDidUpdateMostRecentSnapshot:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraSnapshotControlDelegate~1cameraSnapshotControlDidUpdateMostRecentSnapshot(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cameraSnapshotControlDidUpdateMostRecentSnapshot:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmcamerasnapshotcontroldelegate/camerasnapshotcontroldidupdatemostrecentsnapshot(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmcamerasnapshotcontroldelegate/camerasnapshotcontroldidupdatemostrecentsnapshot(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
