{
  "abstract": [
    {
      "text": "The types of results from a persistent CloudKit container event fetch request.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerEventResult"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerEventResult/ResultType-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CoreData",
    "externalID": "c:@E@NSPersistentCloudKitContainerEventResultType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ResultType"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ResultType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSPersistentCloudKitContainerEventResult.ResultType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ResultType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerEventResult": {
      "abstract": [
        {
          "text": "The result of a request to fetch persistent CloudKit container events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentCloudKitContainerEventResult"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerEventResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentCloudKitContainerEventResult"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentCloudKitContainerEventResult",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcloudkitcontainereventresult"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerEventResult/ResultType-swift.enum": {
      "abstract": [
        {
          "text": "The types of results from a persistent CloudKit container event fetch request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ResultType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerEventResult/ResultType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ResultType"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentCloudKitContainerEventResult.ResultType",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcloudkitcontainereventresult/resulttype-swift.enum"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerEventResult/ResultType-swift.enum/countEvents": {
      "abstract": [
        {
          "text": "The number of CloudKit container events that match the event request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "countEvents"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerEventResult/ResultType-swift.enum/countEvents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentCloudKitContainerEventResultTypeCountEvents"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentCloudKitContainerEventResult.ResultType.countEvents",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcloudkitcontainereventresult/resulttype-swift.enum/countevents"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerEventResult/ResultType-swift.enum/events": {
      "abstract": [
        {
          "text": "The persistent CloudKit container events that match the event request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "events"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerEventResult/ResultType-swift.enum/events",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentCloudKitContainerEventResultTypeEvents"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentCloudKitContainerEventResult.ResultType.events",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcloudkitcontainereventresult/resulttype-swift.enum/events"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerEventResult/ResultType-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerEventResult/ResultType-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcloudkitcontainereventresult/resulttype-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerEventResult/result": {
      "abstract": [
        {
          "text": "The result of the persistent CloudKit container event request, which the result type determines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "result"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerEventResult/result",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "result"
        }
      ],
      "role": "symbol",
      "title": "result",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcloudkitcontainereventresult/result"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerEventResult/resultType-swift.property": {
      "abstract": [
        {
          "text": "The type of result that the CloudKit container event fetch request returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resultType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPersistentCloudKitContainerEventResult",
          "text": "NSPersistentCloudKitContainerEventResult"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPersistentCloudKitContainerEventResultType",
          "text": "ResultType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerEventResult/resultType-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resultType"
        }
      ],
      "role": "symbol",
      "title": "resultType",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcloudkitcontainereventresult/resulttype-swift.property"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-Event-Results",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerEventResult/result",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerEventResult/resultType-swift.property"
      ],
      "title": "Handling Event Results"
    }
  ],
  "topicSections": [
    {
      "anchor": "Result-Types",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerEventResult/ResultType-swift.enum/events",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerEventResult/ResultType-swift.enum/countEvents"
      ],
      "title": "Result Types"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerEventResult/ResultType-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPersistentCloudKitContainerEventResultType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentCloudKitContainerEventResultType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentCloudKitContainerEventResultType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coredata/documentation/CoreData"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Result-Types",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerEventResult/ResultType-swift.enum/events",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerEventResult/ResultType-swift.enum/countEvents"
              ],
              "title": "Result Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Handling-Event-Results",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerEventResult/result",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerEventResult/resultType-swift.property"
              ],
              "title": "Handling Event Results"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSPersistentCloudKitContainerEventResultType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainerEventResult~1ResultType-swift.enum~1events/title",
          "value": "NSPersistentCloudKitContainerEventResultTypeEvents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainerEventResult~1ResultType-swift.enum~1events/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentCloudKitContainerEventResultTypeEvents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainerEventResult~1resultType-swift.property/title",
          "value": "resultType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainerEventResult~1resultType-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resultType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainerEventResult/title",
          "value": "NSPersistentCloudKitContainerEventResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainerEventResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentCloudKitContainerEventResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainerEventResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentCloudKitContainerEventResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainerEventResult~1ResultType-swift.enum~1countEvents/title",
          "value": "NSPersistentCloudKitContainerEventResultTypeCountEvents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainerEventResult~1ResultType-swift.enum~1countEvents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentCloudKitContainerEventResultTypeCountEvents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainerEventResult~1result/title",
          "value": "result"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainerEventResult~1result/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "result"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainerEventResult~1ResultType-swift.enum/title",
          "value": "NSPersistentCloudKitContainerEventResultType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainerEventResult~1ResultType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentCloudKitContainerEventResultType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainerEventResult~1ResultType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentCloudKitContainerEventResultType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nspersistentcloudkitcontainereventresult/resulttype-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/nspersistentcloudkitcontainereventresult/resulttype-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
