{
  "abstract": [
    {
      "text": "Creates an audio stream basic description with the start offset, and the number of sample frames and bytes in the packet that you specify.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamPacketDescription"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamPacketDescription/init(mStartOffset:mVariableFramesInPacket:mDataByteSize:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So28AudioStreamPacketDescriptionV12mStartOffset017mVariableFramesInC013mDataByteSizeABs5Int64V_s6UInt32VAItcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "mStartOffset"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int64V",
        "text": "Int64"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "mVariableFramesInPacket"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "mDataByteSize"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Core Audio Types"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(mStartOffset:mVariableFramesInPacket:mDataByteSize:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "mStartOffset"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int64V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int64V",
              "text": "Int64"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "mVariableFramesInPacket"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "mDataByteSize"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of bytes from the start of the buffer to the beginning of the packet.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "mStartOffset"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of sample frames of data in the packet. For formats with a constant number of frames per packet, set this to ",
                  "type": "text"
                },
                {
                  "code": "0",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "mVariableFramesInPacket"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of bytes in the packet.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "mDataByteSize"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes": {
      "abstract": [
        {
          "text": "Use specialized data types to interact with audio streams, complex buffers, and audiovisual timestamps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio Types",
      "type": "topic",
      "url": "/documentation/coreaudiotypes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamPacketDescription": {
      "abstract": [
        {
          "text": "A value that describes a packet in a buffer of audio data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioStreamPacketDescription"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamPacketDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioStreamPacketDescription"
        }
      ],
      "role": "symbol",
      "title": "AudioStreamPacketDescription",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiostreampacketdescription"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamPacketDescription/init()": {
      "abstract": [
        {
          "text": "Creates an audio stream basic description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamPacketDescription/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiostreampacketdescription/init()"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamPacketDescription/init(mStartOffset:mVariableFramesInPacket:mDataByteSize:)": {
      "abstract": [
        {
          "text": "Creates an audio stream basic description with the start offset, and the number of sample frames and bytes in the packet that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "mStartOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mVariableFramesInPacket"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mDataByteSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamPacketDescription/init(mStartOffset:mVariableFramesInPacket:mDataByteSize:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(mStartOffset:mVariableFramesInPacket:mDataByteSize:)",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiostreampacketdescription/init(mstartoffset:mvariableframesinpacket:mdatabytesize:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5Int64V": {
      "abstract": [
        {
          "text": "A 64-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int64V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int64",
      "type": "topic",
      "url": "/documentation/Swift/Int64"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-an-audio-stream-packet-descripiton",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioStreamPacketDescription/init()"
      ],
      "title": "Creating an audio stream packet descripiton"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioStreamPacketDescription/title",
          "value": "AudioStreamPacketDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioStreamPacketDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamPacketDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioStreamPacketDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamPacketDescription"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiotypes/audiostreampacketdescription/init(mstartoffset:mvariableframesinpacket:mdatabytesize:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
