{
  "abstract": [
    {
      "text": "The amount of radial color shift around the edges of an image rendered using the camera.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/chromaticAberration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MDLCamera(py)chromaticAberration",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "chromaticAberration"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sf",
        "text": "Float"
      }
    ],
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "chromaticAberration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "chromaticAberration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "chromaticAberration"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sf",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sf",
              "text": "Float"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Chromatic aberration occurs to some degree in all lenses. It results from a lens bringing different wavelengths of light to focus at different places on the image plane. A value of ",
              "type": "text"
            },
            {
              "code": "0.0",
              "type": "codeVoice"
            },
            {
              "text": " (the default) indicates no chromatic aberration, and a value of ",
              "type": "text"
            },
            {
              "code": "1.0",
              "type": "codeVoice"
            },
            {
              "text": " indicates the maximum amount. Chromatic aberration affects all locations in the image according to radial distance. Chromatic aberration also occurs in head-mounted displays, and the value here can be used as an intended amount of chromatic aberration to apply to an image.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera": {
      "abstract": [
        {
          "text": "A point of view for rendering a 3D scene, along with a set of parameters describing an intended appearance for rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLCamera"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLCamera"
        }
      ],
      "role": "symbol",
      "title": "MDLCamera",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/apertureBladeCount": {
      "abstract": [
        {
          "text": "The number of blades in the camera’s simulated aperture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apertureBladeCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/apertureBladeCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "apertureBladeCount"
        }
      ],
      "role": "symbol",
      "title": "apertureBladeCount",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/aperturebladecount"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/barrelDistortion": {
      "abstract": [
        {
          "text": "The first coefficient for determining the radial distortion applied to pixels rendered using the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "barrelDistortion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/barrelDistortion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "barrelDistortion"
        }
      ],
      "role": "symbol",
      "title": "barrelDistortion",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/barreldistortion"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/bokehKernel(withSize:)": {
      "abstract": [
        {
          "text": "Creates and returns a texture, based on the camera’s aperture blade count, to be used in rendering out-of-focus highlights in a scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bokehKernel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vector_int2",
          "text": "vector_int2"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MDLTexture",
          "text": "MDLTexture"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/bokehKernel(withSize:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bokehKernelWithSize:"
        }
      ],
      "role": "symbol",
      "title": "bokehKernel(withSize:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/bokehkernel(withsize:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/chromaticAberration": {
      "abstract": [
        {
          "text": "The amount of radial color shift around the edges of an image rendered using the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "chromaticAberration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/chromaticAberration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "chromaticAberration"
        }
      ],
      "role": "symbol",
      "title": "chromaticAberration",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/chromaticaberration"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/fStop": {
      "abstract": [
        {
          "text": "The relative aperture ratio of the camera’s simulated lens.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fStop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/fStop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fStop"
        }
      ],
      "role": "symbol",
      "title": "fStop",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/fstop"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/fisheyeDistortion": {
      "abstract": [
        {
          "text": "The second coefficient for determining the radial distortion applied to pixels rendered using the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fisheyeDistortion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/fisheyeDistortion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fisheyeDistortion"
        }
      ],
      "role": "symbol",
      "title": "fisheyeDistortion",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/fisheyedistortion"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/focalLength": {
      "abstract": [
        {
          "text": "The focal length, in millimeters, of the camera’s simulated lens.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "focalLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/focalLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "focalLength"
        }
      ],
      "role": "symbol",
      "title": "focalLength",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/focallength"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/focusDistance": {
      "abstract": [
        {
          "text": "The distance, in meters, at which the lens is focused.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "focusDistance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/focusDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "focusDistance"
        }
      ],
      "role": "symbol",
      "title": "focusDistance",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/focusdistance"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/maximumCircleOfConfusion": {
      "abstract": [
        {
          "text": "The maximum diameter, in millimeters on the imaging plane, at which light from a point source should appear in an image rendered using the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumCircleOfConfusion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/maximumCircleOfConfusion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumCircleOfConfusion"
        }
      ],
      "role": "symbol",
      "title": "maximumCircleOfConfusion",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/maximumcircleofconfusion"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/opticalVignetting": {
      "abstract": [
        {
          "text": "The amount of radial light attenuation around the edges of an image rendered using the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "opticalVignetting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/opticalVignetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "opticalVignetting"
        }
      ],
      "role": "symbol",
      "title": "opticalVignetting",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/opticalvignetting"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/shutterOpenInterval": {
      "abstract": [
        {
          "text": "The duration, in seconds, for which the camera’s simulated shutter is open during each frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shutterOpenInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/shutterOpenInterval",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shutterOpenInterval"
        }
      ],
      "role": "symbol",
      "title": "shutterOpenInterval",
      "type": "topic",
      "url": "/documentation/modelio/mdlcamera/shutteropeninterval"
    },
    "doc://com.externally.resolved.symbol/s:Sf": {
      "abstract": [
        {
          "text": "A single-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sf",
      "kind": "symbol",
      "role": "symbol",
      "title": "Float",
      "type": "topic",
      "url": "/documentation/Swift/Float"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Modeling-a-Physical-Lens",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/barrelDistortion",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/fisheyeDistortion",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/opticalVignetting",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/focalLength",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/fStop",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/apertureBladeCount",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/bokehKernel(withSize:)",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/maximumCircleOfConfusion",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/focusDistance",
        "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/shutterOpenInterval"
      ],
      "title": "Modeling a Physical Lens"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "chromaticAberration"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "chromaticAberration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.modelio/documentation/ModelIO",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Modeling-a-Physical-Lens",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/barrelDistortion",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/fisheyeDistortion",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/opticalVignetting",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/focalLength",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/fStop",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/apertureBladeCount",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/bokehKernel(withSize:)",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/maximumCircleOfConfusion",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/focusDistance",
                "doc://com.apple.modelio/documentation/ModelIO/MDLCamera/shutterOpenInterval"
              ],
              "title": "Modeling a Physical Lens"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:f",
                    "text": "float"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "chromaticAberration"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1focusDistance/title",
          "value": "focusDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1focusDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "focusDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1shutterOpenInterval/title",
          "value": "shutterOpenInterval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1shutterOpenInterval/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shutterOpenInterval"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1maximumCircleOfConfusion/title",
          "value": "maximumCircleOfConfusion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1maximumCircleOfConfusion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumCircleOfConfusion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1fStop/title",
          "value": "fStop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1fStop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fStop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1focalLength/title",
          "value": "focalLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1focalLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "focalLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1apertureBladeCount/title",
          "value": "apertureBladeCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1apertureBladeCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "apertureBladeCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera/title",
          "value": "MDLCamera"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1bokehKernel(withSize:)/title",
          "value": "bokehKernelWithSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1bokehKernel(withSize:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "bokehKernelWithSize:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1opticalVignetting/title",
          "value": "opticalVignetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1opticalVignetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "opticalVignetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1barrelDistortion/title",
          "value": "barrelDistortion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1barrelDistortion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "barrelDistortion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1fisheyeDistortion/title",
          "value": "fisheyeDistortion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1fisheyeDistortion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fisheyeDistortion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1chromaticAberration/title",
          "value": "chromaticAberration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLCamera~1chromaticAberration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "chromaticAberration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/mdlcamera/chromaticaberration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/modelio/mdlcamera/chromaticaberration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
