{
  "abstract": [
    {
      "text": "A block that returns the alignment rectangle for the starting and ending views.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/Transition/ZoomOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIZoomTransitionOptions/alignmentRectProvider"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIZoomTransitionOptions(py)alignmentRectProvider",
    "fragments": [
      {
        "kind": "identifier",
        "text": "alignmentRectProvider"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "alignmentRectProvider"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "alignmentRectProvider"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:BF$@S@CGRect(#*$objc(cs)UIZoomTransitionAlignmentRectContext)",
              "text": "struct CGRect (^)(UIZoomTransitionAlignmentRectContext *)"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "alignmentRectProvider"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/Transition/ZoomOptions": {
      "abstract": [
        {
          "text": "Options for a zoom transition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ZoomOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/Transition/ZoomOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ZoomOptions"
        }
      ],
      "role": "symbol",
      "title": "UIViewController.Transition.ZoomOptions",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/transition/zoomoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/Transition/ZoomOptions/AlignmentRectContext": {
      "abstract": [
        {
          "text": "An object that contains a zoom transition’s starting and ending views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AlignmentRectContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/Transition/ZoomOptions/AlignmentRectContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AlignmentRectContext"
        }
      ],
      "role": "symbol",
      "title": "UIViewController.Transition.ZoomOptions.AlignmentRectContext",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/transition/zoomoptions/alignmentrectcontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/Transition/ZoomOptions/dimmingColor": {
      "abstract": [
        {
          "text": "The dimming color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dimmingColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/Transition/ZoomOptions/dimmingColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dimmingColor"
        }
      ],
      "role": "symbol",
      "title": "dimmingColor",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/transition/zoomoptions/dimmingcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/Transition/ZoomOptions/dimmingVisualEffect": {
      "abstract": [
        {
          "text": "The dimming visual effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dimmingVisualEffect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIBlurEffect",
          "text": "UIBlurEffect"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/Transition/ZoomOptions/dimmingVisualEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dimmingVisualEffect"
        }
      ],
      "role": "symbol",
      "title": "dimmingVisualEffect",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/transition/zoomoptions/dimmingvisualeffect"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIZoomTransitionOptions/alignmentRectProvider": {
      "abstract": [
        {
          "text": "A block that returns the alignment rectangle for the starting and ending views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "alignmentRectProvider"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIZoomTransitionOptions/alignmentRectProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "alignmentRectProvider",
      "type": "topic",
      "url": "/documentation/uikit/uizoomtransitionoptions/alignmentrectprovider"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/Transition/ZoomOptions/AlignmentRectContext",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/Transition/ZoomOptions/dimmingColor",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/Transition/ZoomOptions/dimmingVisualEffect"
      ],
      "title": "Setting options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1Transition~1ZoomOptions~1AlignmentRectContext/title",
          "value": "UIZoomTransitionAlignmentRectContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1Transition~1ZoomOptions~1AlignmentRectContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIZoomTransitionAlignmentRectContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1Transition~1ZoomOptions~1AlignmentRectContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIZoomTransitionAlignmentRectContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1Transition~1ZoomOptions~1dimmingColor/title",
          "value": "dimmingColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1Transition~1ZoomOptions~1dimmingColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dimmingColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1Transition~1ZoomOptions~1dimmingVisualEffect/title",
          "value": "dimmingVisualEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1Transition~1ZoomOptions~1dimmingVisualEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dimmingVisualEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1Transition~1ZoomOptions/title",
          "value": "UIZoomTransitionOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1Transition~1ZoomOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIZoomTransitionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1Transition~1ZoomOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIZoomTransitionOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uizoomtransitionoptions/alignmentrectprovider"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
