{
  "abstract": [
    {
      "text": "The supported handle types.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.callkit/documentation/CallKit",
        "doc://com.apple.callkit/documentation/CallKit/CXProviderConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.callkit/documentation/CallKit/CXProviderConfiguration/supportedHandleTypes-kd6i"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CallKit",
    "externalID": "s:So23CXProviderConfigurationC7CallKitE20supportedHandleTypesShySo12CXHandleTypeVGvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "supportedHandleTypes"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sh",
        "text": "Set"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CXHandle",
        "text": "CXHandle"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CXHandleType",
        "text": "HandleType"
      },
      {
        "kind": "text",
        "text": ">"
      }
    ],
    "modules": [
      {
        "name": "CallKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "supportedHandleTypes"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@nonobjc"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "final"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "supportedHandleTypes"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sh",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sh",
              "text": "Set"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.callkit/documentation/CallKit/CXHandle",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CXHandle",
              "text": "CXHandle"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.callkit/documentation/CallKit/CXHandle/HandleType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CXHandleType",
              "text": "HandleType"
            },
            {
              "kind": "text",
              "text": "> { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For possible values, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.callkit/documentation/CallKit/CXHandle/HandleType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.callkit/documentation/CallKit": {
      "abstract": [
        {
          "text": "Display the system-calling UI for your app’s VoIP services, and coordinate your calling services with other apps and the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CallKit",
      "type": "topic",
      "url": "/documentation/callkit"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXHandle": {
      "abstract": [
        {
          "text": "A way to reach a call recipient, such as a phone number or email address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXHandle"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXHandle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXHandle"
        }
      ],
      "role": "symbol",
      "title": "CXHandle",
      "type": "topic",
      "url": "/documentation/callkit/cxhandle"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXHandle/HandleType": {
      "abstract": [
        {
          "text": "The possible types of handles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HandleType"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXHandle/HandleType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HandleType"
        }
      ],
      "role": "symbol",
      "title": "CXHandle.HandleType",
      "type": "topic",
      "url": "/documentation/callkit/cxhandle/handletype"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProviderConfiguration": {
      "abstract": [
        {
          "text": "An encapsulation of the configuration of a provider object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXProviderConfiguration"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProviderConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXProviderConfiguration"
        }
      ],
      "role": "symbol",
      "title": "CXProviderConfiguration",
      "type": "topic",
      "url": "/documentation/callkit/cxproviderconfiguration"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProviderConfiguration/includesCallsInRecents": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the provider includes a call in the system’s Recents list after the call ends.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "includesCallsInRecents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProviderConfiguration/includesCallsInRecents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "includesCallsInRecents"
        }
      ],
      "role": "symbol",
      "title": "includesCallsInRecents",
      "type": "topic",
      "url": "/documentation/callkit/cxproviderconfiguration/includescallsinrecents"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProviderConfiguration/maximumCallGroups": {
      "abstract": [
        {
          "text": "The maximum number of call groups.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumCallGroups"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProviderConfiguration/maximumCallGroups",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumCallGroups"
        }
      ],
      "role": "symbol",
      "title": "maximumCallGroups",
      "type": "topic",
      "url": "/documentation/callkit/cxproviderconfiguration/maximumcallgroups"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProviderConfiguration/maximumCallsPerCallGroup": {
      "abstract": [
        {
          "text": "The maximum number of calls per call group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumCallsPerCallGroup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProviderConfiguration/maximumCallsPerCallGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumCallsPerCallGroup"
        }
      ],
      "role": "symbol",
      "title": "maximumCallsPerCallGroup",
      "type": "topic",
      "url": "/documentation/callkit/cxproviderconfiguration/maximumcallspercallgroup"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProviderConfiguration/supportedHandleTypes-kd6i": {
      "abstract": [
        {
          "text": "The supported handle types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedHandleTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXHandle",
          "text": "CXHandle"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CXHandleType",
          "text": "HandleType"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProviderConfiguration/supportedHandleTypes-kd6i",
      "kind": "symbol",
      "role": "symbol",
      "title": "supportedHandleTypes",
      "type": "topic",
      "url": "/documentation/callkit/cxproviderconfiguration/supportedhandletypes-kd6i"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXProviderConfiguration/supportsVideo": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the provider supports video in addition to audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsVideo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXProviderConfiguration/supportsVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsVideo"
        }
      ],
      "role": "symbol",
      "title": "supportsVideo",
      "type": "topic",
      "url": "/documentation/callkit/cxproviderconfiguration/supportsvideo"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sh": {
      "abstract": [
        {
          "text": "An unordered collection of unique elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SH",
          "text": "Hashable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sh",
      "kind": "symbol",
      "role": "symbol",
      "title": "Set",
      "type": "topic",
      "url": "/documentation/Swift/Set"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Call-Capabilities",
      "generated": true,
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXProviderConfiguration/maximumCallGroups",
        "doc://com.apple.callkit/documentation/CallKit/CXProviderConfiguration/maximumCallsPerCallGroup",
        "doc://com.apple.callkit/documentation/CallKit/CXProviderConfiguration/supportsVideo",
        "doc://com.apple.callkit/documentation/CallKit/CXProviderConfiguration/includesCallsInRecents"
      ],
      "title": "Configuring Call Capabilities"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXHandle/title",
          "value": "CXHandle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXHandle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXHandle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderConfiguration~1includesCallsInRecents/title",
          "value": "includesCallsInRecents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderConfiguration~1includesCallsInRecents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "includesCallsInRecents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderConfiguration~1maximumCallsPerCallGroup/title",
          "value": "maximumCallsPerCallGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderConfiguration~1maximumCallsPerCallGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumCallsPerCallGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXHandle~1HandleType/title",
          "value": "CXHandleType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXHandle~1HandleType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXHandleType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXHandle~1HandleType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXHandleType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderConfiguration~1supportsVideo/title",
          "value": "supportsVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderConfiguration~1supportsVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderConfiguration/title",
          "value": "CXProviderConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXProviderConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXProviderConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderConfiguration~1maximumCallGroups/title",
          "value": "maximumCallGroups"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXProviderConfiguration~1maximumCallGroups/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumCallGroups"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/callkit/cxproviderconfiguration/supportedhandletypes-kd6i"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
