{
  "abstract": [
    {
      "text": "Marks the start of a task that should continue if the app enters the background.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIApplication/beginBackgroundTask(expirationHandler:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIApplication(im)beginBackgroundTaskWithExpirationHandler:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "beginBackgroundTask"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "expirationHandler"
      },
      {
        "kind": "text",
        "text": ": (() -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@UIBackgroundTaskIdentifier",
        "text": "UIBackgroundTaskIdentifier"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "beginBackgroundTaskWithExpirationHandler:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "beginBackgroundTask(expirationHandler:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "nonisolated"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "beginBackgroundTask"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "expirationHandler"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "handler"
            },
            {
              "kind": "text",
              "text": ": (() -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")? = nil) -> "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundTaskIdentifier",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@UIBackgroundTaskIdentifier",
              "text": "UIBackgroundTaskIdentifier"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "nonisolated"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "beginBackgroundTask"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "expirationHandler"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "handler"
            },
            {
              "kind": "text",
              "text": ": (@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " () -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")? = nil) -> "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundTaskIdentifier",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@UIBackgroundTaskIdentifier",
              "text": "UIBackgroundTaskIdentifier"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A handler to be called shortly before the app’s remaining background time reaches 0. Use this handler to clean up and mark the end of the background task. Failure to end the task explicitly will result in the termination of the app. The system calls the handler synchronously on the main thread, blocking the app’s suspension momentarily.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "handler"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A unique identifier for the new background task. You must pass this value to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/endBackgroundTask(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to mark the end of this task. This method returns ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundTaskIdentifier/invalid",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " if running in the background isn’t possible.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method requests additional background execution time for your app. Call this method when leaving a task unfinished might be detrimental to your app’s user experience. For example, call this method before writing data to a file to prevent the system from suspending your app while the operation is in progress. For background tasks requiring more time, use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BackgroundTasks",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Call this method as early as possible before starting your task, preferably before your app actually enters the background. The method requests the task assertion for your app asynchronously. If you call this method shortly before your app is due to be suspended, there’s a chance that the system might suspend your app before that task assertion is granted. For example, don’t call this method at the very end of your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidEnterBackground(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method and expect your app to continue running. If the system is unable to grant the task assertion, it calls your expiration handler.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Each call to this method must be balanced by a matching call to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/endBackgroundTask(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. Apps running background tasks have a finite amount of time in which to run them. (You can find out the maximum background time available using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/backgroundTimeRemaining",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.) If you don’t call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/endBackgroundTask(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for each task before time expires, the system kills the app. If you provide a block object in the ",
              "type": "text"
            },
            {
              "code": "handler",
              "type": "codeVoice"
            },
            {
              "text": " parameter, the system calls your handler before time expires to give you a chance to end the task.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can call this method at any point in your app’s execution. You may also call this method multiple times to mark the beginning of several background tasks that run in parallel. However, each task must be ended separately. You identify a given task using the value returned by this method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To assist with debugging, this method generates a name for the task, based on the name of the calling method or function. If you want to specify a custom name, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/beginBackgroundTask(withName:expirationHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This method can be safely called on a non-main thread. To extend the execution time of an app extension, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/processinfo/1617030-performexpiringactivity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/processinfo",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If you’re having trouble debugging your background task code, you might try using the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/beginBackgroundTask(withName:expirationHandler:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " method instead of this one. That method provides the same behavior but lets you specify a debugger-visible name for your task.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BackgroundTasks": {
      "abstract": [
        {
          "text": "Request the system to launch your app in the background to run tasks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BackgroundTasks",
      "kind": "symbol",
      "role": "collection",
      "title": "Background Tasks",
      "type": "topic",
      "url": "/documentation/BackgroundTasks"
    },
    "doc://com.apple.documentation/documentation/foundation/processinfo": {
      "abstract": [
        {
          "text": "A collection of information about the current process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "ProcessInfo"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/processinfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "ProcessInfo",
      "type": "topic",
      "url": "/documentation/foundation/processinfo"
    },
    "doc://com.apple.documentation/documentation/foundation/processinfo/1617030-performexpiringactivity": {
      "abstract": [
        {
          "text": "Performs the specified block asynchronously and notifies you if the process is about to be suspended.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "performExpiringActivity"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "withReason"
        },
        {
          "kind": "text",
          "text": ": String, "
        },
        {
          "kind": "identifier",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": (Bool) -> Void)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/processinfo/1617030-performexpiringactivity",
      "kind": "symbol",
      "role": "symbol",
      "title": "performExpiringActivity(withReason:using:)",
      "type": "topic",
      "url": "/documentation/foundation/processinfo/1617030-performexpiringactivity"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication": {
      "abstract": [
        {
          "text": "The centralized point of control and coordination for apps running in iOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIApplication"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplication"
        }
      ],
      "role": "symbol",
      "title": "UIApplication",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/backgroundRefreshStatus": {
      "abstract": [
        {
          "text": "Indicates whether the app can refresh content when running in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundRefreshStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIBackgroundRefreshStatus",
          "text": "UIBackgroundRefreshStatus"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/backgroundRefreshStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backgroundRefreshStatus"
        }
      ],
      "role": "symbol",
      "title": "backgroundRefreshStatus",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/backgroundrefreshstatus"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/backgroundRefreshStatusDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that posts when the app’s status for downloading content in the background changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundRefreshStatusDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/backgroundRefreshStatusDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationBackgroundRefreshStatusDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "backgroundRefreshStatusDidChangeNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/backgroundrefreshstatusdidchangenotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/backgroundTimeRemaining": {
      "abstract": [
        {
          "text": "The maximum amount of time remaining for the app to run in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundTimeRemaining"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/backgroundTimeRemaining",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backgroundTimeRemaining"
        }
      ],
      "role": "symbol",
      "title": "backgroundTimeRemaining",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/backgroundtimeremaining"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/beginBackgroundTask(expirationHandler:)": {
      "abstract": [
        {
          "text": "Marks the start of a task that should continue if the app enters the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginBackgroundTask"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "expirationHandler"
        },
        {
          "kind": "text",
          "text": ": (() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIBackgroundTaskIdentifier",
          "text": "UIBackgroundTaskIdentifier"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/beginBackgroundTask(expirationHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginBackgroundTaskWithExpirationHandler:"
        }
      ],
      "role": "symbol",
      "title": "beginBackgroundTask(expirationHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/beginbackgroundtask(expirationhandler:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/beginBackgroundTask(withName:expirationHandler:)": {
      "abstract": [
        {
          "text": "Marks the start of a task with a custom name that should continue if the app enters the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginBackgroundTask"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "expirationHandler"
        },
        {
          "kind": "text",
          "text": ": (() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIBackgroundTaskIdentifier",
          "text": "UIBackgroundTaskIdentifier"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/beginBackgroundTask(withName:expirationHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginBackgroundTaskWithName:expirationHandler:"
        }
      ],
      "role": "symbol",
      "title": "beginBackgroundTask(withName:expirationHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/beginbackgroundtask(withname:expirationhandler:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/endBackgroundTask(_:)": {
      "abstract": [
        {
          "text": "Marks the end of a specific long-running background task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endBackgroundTask"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIBackgroundTaskIdentifier",
          "text": "UIBackgroundTaskIdentifier"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/endBackgroundTask(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endBackgroundTask:"
        }
      ],
      "role": "symbol",
      "title": "endBackgroundTask(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/endbackgroundtask(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidEnterBackground(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the app is now in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationDidEnterBackground"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidEnterBackground(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationDidEnterBackground:"
        }
      ],
      "role": "symbol",
      "title": "applicationDidEnterBackground(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationdelegate/applicationdidenterbackground(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBackgroundRefreshStatus": {
      "abstract": [
        {
          "text": "Constants that indicate whether background execution is enabled for the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIBackgroundRefreshStatus"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundRefreshStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBackgroundRefreshStatus"
        }
      ],
      "role": "symbol",
      "title": "UIBackgroundRefreshStatus",
      "type": "topic",
      "url": "/documentation/uikit/uibackgroundrefreshstatus"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBackgroundTaskIdentifier": {
      "abstract": [
        {
          "text": "A unique token that identifies a request to run in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIBackgroundTaskIdentifier"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundTaskIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBackgroundTaskIdentifier"
        }
      ],
      "role": "symbol",
      "title": "UIBackgroundTaskIdentifier",
      "type": "topic",
      "url": "/documentation/uikit/uibackgroundtaskidentifier"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBackgroundTaskIdentifier/invalid": {
      "abstract": [
        {
          "text": "A token that indicates an invalid task request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIBackgroundTaskIdentifier",
          "text": "UIBackgroundTaskIdentifier"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundTaskIdentifier/invalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBackgroundTaskInvalid"
        }
      ],
      "role": "symbol",
      "title": "invalid",
      "type": "topic",
      "url": "/documentation/uikit/uibackgroundtaskidentifier/invalid"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.documentation/documentation/BackgroundTasks"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Managing-background-tasks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/backgroundRefreshStatus",
        "doc://com.apple.uikit/documentation/UIKit/UIBackgroundRefreshStatus",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/backgroundRefreshStatusDidChangeNotification",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/beginBackgroundTask(withName:expirationHandler:)",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/endBackgroundTask(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIBackgroundTaskIdentifier",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/backgroundTimeRemaining"
      ],
      "title": "Managing background tasks"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "beginBackgroundTaskWithExpirationHandler:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginBackgroundTaskWithExpirationHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.documentation/documentation/BackgroundTasks"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Managing-background-tasks",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/backgroundRefreshStatus",
                "doc://com.apple.uikit/documentation/UIKit/UIBackgroundRefreshStatus",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/backgroundRefreshStatusDidChangeNotification",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/beginBackgroundTask(withName:expirationHandler:)",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/endBackgroundTask(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIBackgroundTaskIdentifier",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/backgroundTimeRemaining"
              ],
              "title": "Managing background tasks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundTaskIdentifier",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@UIBackgroundTaskIdentifier",
                    "text": "UIBackgroundTaskIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "beginBackgroundTaskWithExpirationHandler:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:BFv()",
                    "text": "void (^)(void)"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "handler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A handler to be called shortly before the app’s remaining background time reaches 0. Use this handler to clean up and mark the end of the background task. Failure to end the task explicitly will result in the termination of the app. The system calls the handler synchronously on the main thread, blocking the app’s suspension momentarily.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "handler"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A unique identifier for the new background task. You must pass this value to the ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/endBackgroundTask(_:)",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " method to mark the end of this task. This method returns ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundTaskIdentifier/invalid",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " if running in the background isn’t possible.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1processinfo~11617030-performexpiringactivity/title",
          "value": "performExpiringActivityWithReason:usingBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1backgroundRefreshStatus/title",
          "value": "backgroundRefreshStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1backgroundRefreshStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backgroundRefreshStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationDidEnterBackground(_:)/title",
          "value": "applicationDidEnterBackground:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationDidEnterBackground(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "applicationDidEnterBackground:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBackgroundTaskIdentifier/title",
          "value": "UIBackgroundTaskIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBackgroundTaskIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBackgroundTaskIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBackgroundTaskIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBackgroundTaskIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1processinfo/title",
          "value": "NSProcessInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1backgroundTimeRemaining/title",
          "value": "backgroundTimeRemaining"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1backgroundTimeRemaining/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backgroundTimeRemaining"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/title",
          "value": "UIApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1beginBackgroundTask(withName:expirationHandler:)/title",
          "value": "beginBackgroundTaskWithName:expirationHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1beginBackgroundTask(withName:expirationHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginBackgroundTaskWithName:expirationHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1beginBackgroundTask(expirationHandler:)/title",
          "value": "beginBackgroundTaskWithExpirationHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1beginBackgroundTask(expirationHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginBackgroundTaskWithExpirationHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBackgroundTaskIdentifier~1invalid/title",
          "value": "UIBackgroundTaskInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBackgroundTaskIdentifier~1invalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBackgroundTaskInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1backgroundRefreshStatusDidChangeNotification/title",
          "value": "UIApplicationBackgroundRefreshStatusDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1backgroundRefreshStatusDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationBackgroundRefreshStatusDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBackgroundRefreshStatus/title",
          "value": "UIBackgroundRefreshStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBackgroundRefreshStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBackgroundRefreshStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBackgroundRefreshStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBackgroundRefreshStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1endBackgroundTask(_:)/title",
          "value": "endBackgroundTask:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1endBackgroundTask(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "endBackgroundTask:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiapplication/beginbackgroundtask(expirationhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiapplication/beginbackgroundtask(expirationhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
