{
  "abstract": [
    {
      "text": "Returns the user notification settings for the app.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/UserNotifications/UNUserNotificationCenter",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIApplication/currentUserNotificationSettings"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:objc(cs)UIApplication(py)currentUserNotificationSettings",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "currentUserNotificationSettings"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIUserNotificationSettings",
        "text": "UIUserNotificationSettings"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "currentUserNotificationSettings"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "8.0",
        "message": "Use UserNotifications Framework's -[UNUserNotificationCenter getNotificationSettingsWithCompletionHandler:] and -[UNUserNotificationCenter getNotificationCategoriesWithCompletionHandler:]",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "8.0",
        "message": "Use UserNotifications Framework's -[UNUserNotificationCenter getNotificationSettingsWithCompletionHandler:] and -[UNUserNotificationCenter getNotificationCategoriesWithCompletionHandler:]",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Use UserNotifications Framework's -[UNUserNotificationCenter getNotificationSettingsWithCompletionHandler:] and -[UNUserNotificationCenter getNotificationCategoriesWithCompletionHandler:]",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "currentUserNotificationSettings"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "currentUserNotificationSettings"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationSettings",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIUserNotificationSettings",
              "text": "UIUserNotificationSettings"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A user notification settings object indicating the types of notifications that your app may use.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you configure local or remote notifications with unavailable notification types, the system does not display the corresponding alerts to the user. The system does still deliver the local and remote notifications to your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/UserNotifications/UNUserNotificationCenter": {
      "abstract": [
        {
          "text": "The central object for managing notification-related activities for your app or app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UNUserNotificationCenter"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UserNotifications/UNUserNotificationCenter",
      "kind": "symbol",
      "role": "symbol",
      "title": "UNUserNotificationCenter",
      "type": "topic",
      "url": "/documentation/UserNotifications/UNUserNotificationCenter"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication": {
      "abstract": [
        {
          "text": "The centralized point of control and coordination for apps running in iOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIApplication"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplication"
        }
      ],
      "role": "symbol",
      "title": "UIApplication",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/applicationIconBadgeNumber": {
      "abstract": [
        {
          "text": "The number currently set as the badge of the app icon on the Home screen.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationIconBadgeNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/applicationIconBadgeNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationIconBadgeNumber"
        }
      ],
      "role": "symbol",
      "title": "applicationIconBadgeNumber",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/applicationiconbadgenumber"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/currentUserNotificationSettings": {
      "abstract": [
        {
          "text": "Returns the user notification settings for the app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentUserNotificationSettings"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUserNotificationSettings",
          "text": "UIUserNotificationSettings"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/currentUserNotificationSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentUserNotificationSettings"
        }
      ],
      "role": "symbol",
      "title": "currentUserNotificationSettings",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/currentusernotificationsettings"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/isIgnoringInteractionEvents": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the receiver is ignoring events initiated by touches on the screen.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isIgnoringInteractionEvents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/isIgnoringInteractionEvents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ignoringInteractionEvents"
        }
      ],
      "role": "symbol",
      "title": "isIgnoringInteractionEvents",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/isignoringinteractionevents"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/isNetworkActivityIndicatorVisible": {
      "abstract": [
        {
          "text": "A Boolean value that turns an indicator of network activity on or off.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isNetworkActivityIndicatorVisible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/isNetworkActivityIndicatorVisible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "networkActivityIndicatorVisible"
        }
      ],
      "role": "symbol",
      "title": "isNetworkActivityIndicatorVisible",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/isnetworkactivityindicatorvisible"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/isStatusBarHidden": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the status bar is hidden.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isStatusBarHidden"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/isStatusBarHidden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "statusBarHidden"
        }
      ],
      "role": "symbol",
      "title": "isStatusBarHidden",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/isstatusbarhidden"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/keyWindow": {
      "abstract": [
        {
          "text": "The app’s key window.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyWindow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindow",
          "text": "UIWindow"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/keyWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keyWindow"
        }
      ],
      "role": "symbol",
      "title": "keyWindow",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/keywindow"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/proximitySensingEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether proximity sensing is enabled.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "proximitySensingEnabled"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/proximitySensingEnabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "proximitySensingEnabled",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/proximitysensingenabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/registerUserNotificationSettings(_:)": {
      "abstract": [
        {
          "text": "Registers your preferred options for notifying the user.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registerUserNotificationSettings"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUserNotificationSettings",
          "text": "UIUserNotificationSettings"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/registerUserNotificationSettings(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "registerUserNotificationSettings:"
        }
      ],
      "role": "symbol",
      "title": "registerUserNotificationSettings(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/registerusernotificationsettings(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/scheduledLocalNotifications": {
      "abstract": [
        {
          "text": "All currently scheduled local notifications.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scheduledLocalNotifications"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UILocalNotification",
          "text": "UILocalNotification"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/scheduledLocalNotifications",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scheduledLocalNotifications"
        }
      ],
      "role": "symbol",
      "title": "scheduledLocalNotifications",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/scheduledlocalnotifications"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarFrame": {
      "abstract": [
        {
          "text": "The frame rectangle defining the area of the status bar.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusBarFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "statusBarFrame"
        }
      ],
      "role": "symbol",
      "title": "statusBarFrame",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/statusbarframe"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarFrameUserInfoKey": {
      "abstract": [
        {
          "text": "A key whose value indicates the new status bar frame.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusBarFrameUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarFrameUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationStatusBarFrameUserInfoKey"
        }
      ],
      "role": "symbol",
      "title": "statusBarFrameUserInfoKey",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/statusbarframeuserinfokey"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarOrientation": {
      "abstract": [
        {
          "text": "The current orientation of the app’s status bar.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusBarOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIInterfaceOrientation",
          "text": "UIInterfaceOrientation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "statusBarOrientation"
        }
      ],
      "role": "symbol",
      "title": "statusBarOrientation",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/statusbarorientation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarOrientationAnimationDuration": {
      "abstract": [
        {
          "text": "The animation duration in seconds for the status bar during a 90 degree orientation change.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusBarOrientationAnimationDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarOrientationAnimationDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "statusBarOrientationAnimationDuration"
        }
      ],
      "role": "symbol",
      "title": "statusBarOrientationAnimationDuration",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/statusbarorientationanimationduration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarOrientationUserInfoKey": {
      "abstract": [
        {
          "text": "A key whose value indicates the current interface orientation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusBarOrientationUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarOrientationUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationStatusBarOrientationUserInfoKey"
        }
      ],
      "role": "symbol",
      "title": "statusBarOrientationUserInfoKey",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/statusbarorientationuserinfokey"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarStyle": {
      "abstract": [
        {
          "text": "The current style of the status bar.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusBarStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIStatusBarStyle",
          "text": "UIStatusBarStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "statusBarStyle"
        }
      ],
      "role": "symbol",
      "title": "statusBarStyle",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/statusbarstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/windows": {
      "abstract": [
        {
          "text": "The app’s visible and hidden windows.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "windows"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindow",
          "text": "UIWindow"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/windows",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "windows"
        }
      ],
      "role": "symbol",
      "title": "windows",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/windows"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationSettings": {
      "abstract": [
        {
          "text": "The types of notifications that can be displayed to the user by your app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUserNotificationSettings"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserNotificationSettings"
        }
      ],
      "role": "symbol",
      "title": "UIUserNotificationSettings",
      "type": "topic",
      "url": "/documentation/uikit/uiusernotificationsettings"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/registerUserNotificationSettings(_:)"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Deprecated-properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/applicationIconBadgeNumber",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarFrameUserInfoKey",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarOrientationUserInfoKey",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/isIgnoringInteractionEvents",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/isNetworkActivityIndicatorVisible",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/isStatusBarHidden",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/keyWindow",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/scheduledLocalNotifications",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarFrame",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarOrientation",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarOrientationAnimationDuration",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarStyle",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/windows"
      ],
      "title": "Deprecated properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.0",
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.0",
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "currentUserNotificationSettings"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentUserNotificationSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/registerUserNotificationSettings(_:)"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Deprecated-properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/applicationIconBadgeNumber",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarFrameUserInfoKey",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarOrientationUserInfoKey",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/isIgnoringInteractionEvents",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/isNetworkActivityIndicatorVisible",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/proximitySensingEnabled",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/isStatusBarHidden",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/keyWindow",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/scheduledLocalNotifications",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarFrame",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarOrientation",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarOrientationAnimationDuration",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarStyle",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/windows"
              ],
              "title": "Deprecated properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationSettings",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIUserNotificationSettings",
                    "text": "UIUserNotificationSettings"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "currentUserNotificationSettings"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/UserNotifications/UNUserNotificationCenter",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1isStatusBarHidden/title",
          "value": "statusBarHidden"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1isStatusBarHidden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "statusBarHidden"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1isNetworkActivityIndicatorVisible/title",
          "value": "networkActivityIndicatorVisible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1isNetworkActivityIndicatorVisible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "networkActivityIndicatorVisible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1windows/title",
          "value": "windows"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1windows/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "windows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1statusBarFrameUserInfoKey/title",
          "value": "UIApplicationStatusBarFrameUserInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1statusBarFrameUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationStatusBarFrameUserInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1applicationIconBadgeNumber/title",
          "value": "applicationIconBadgeNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1applicationIconBadgeNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "applicationIconBadgeNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationSettings/title",
          "value": "UIUserNotificationSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserNotificationSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationSettings/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserNotificationSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/title",
          "value": "UIApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UserNotifications~1UNUserNotificationCenter/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UNUserNotificationCenter"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1isIgnoringInteractionEvents/title",
          "value": "ignoringInteractionEvents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1isIgnoringInteractionEvents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ignoringInteractionEvents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1registerUserNotificationSettings(_:)/title",
          "value": "registerUserNotificationSettings:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1registerUserNotificationSettings(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "registerUserNotificationSettings:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1statusBarFrame/title",
          "value": "statusBarFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1statusBarFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "statusBarFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1keyWindow/title",
          "value": "keyWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1keyWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "keyWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1statusBarOrientationAnimationDuration/title",
          "value": "statusBarOrientationAnimationDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1statusBarOrientationAnimationDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "statusBarOrientationAnimationDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1statusBarStyle/title",
          "value": "statusBarStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1statusBarStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "statusBarStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1statusBarOrientationUserInfoKey/title",
          "value": "UIApplicationStatusBarOrientationUserInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1statusBarOrientationUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationStatusBarOrientationUserInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1statusBarOrientation/title",
          "value": "statusBarOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1statusBarOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "statusBarOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1currentUserNotificationSettings/title",
          "value": "currentUserNotificationSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1currentUserNotificationSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentUserNotificationSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1scheduledLocalNotifications/title",
          "value": "scheduledLocalNotifications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1scheduledLocalNotifications/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scheduledLocalNotifications"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiapplication/currentusernotificationsettings"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiapplication/currentusernotificationsettings"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
