{
  "abstract": [
    {
      "text": "Reports whether this app is the person’s default app in the given category.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIApplication/defaultStatusForCategory:error:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIApplication(im)defaultStatusForCategory:error:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "defaultStatusForCategory:error:"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "defaultStatusForCategory:error:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "defaultStatusForCategory:error:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultStatus",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UIApplicationCategoryDefaultStatus",
              "text": "UIApplicationCategoryDefaultStatus"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "defaultStatusForCategory:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/Category",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UIApplicationCategory",
              "text": "UIApplicationCategory"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "category"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "error:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSError",
              "text": "NSError"
            },
            {
              "kind": "text",
              "text": " * *) "
            },
            {
              "kind": "internalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The type of app for which you test whether your app is the default.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "category"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "If an error occurs, upon return contains an ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " object that describes the problem. If you are not interested in possible errors, pass in ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "error"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the system could determine the status of the app, this method returns ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultStatus/UIApplicationCategoryDefaultStatusIsDefault",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " if the app is the default app in the category, and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultStatus/UIApplicationCategoryDefaultStatusNotDefault",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " otherwise. If the system couldn’t determine the status, or the app has exceeded the threshold rate for calling this method, it returns ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultStatus/UIApplicationCategoryDefaultStatusUnavailable",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and supplies more information about the problem in ",
              "type": "text"
            },
            {
              "code": "error",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To reduce the likelihood that users will face continuous requests to set a browser as their default, this API will only tell the browser app if it is the default once per year. If you call the method too frequently, it throws an error with the domain ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultErrorDomain",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and the code ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/CategoryDefaultError/rateLimited",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The error’s info dictionary contains these keys:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The date at which the app most recently received a ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultStatus/UIApplicationCategoryDefaultStatusIsDefault",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " or ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultStatus/UIApplicationCategoryDefaultStatusNotDefault",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " response from this method.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultStatusLastProvidedDateErrorKey",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The date at which the app can next request an updated response.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultRetryAvailabilityDateErrorKey",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nserror": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication": {
      "abstract": [
        {
          "text": "The centralized point of control and coordination for apps running in iOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIApplication"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplication"
        }
      ],
      "role": "symbol",
      "title": "UIApplication",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/Category": {
      "abstract": [
        {
          "text": "Constants that describe the types of apps in the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Category"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/Category",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Category"
        }
      ],
      "role": "symbol",
      "title": "UIApplication.Category",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/category"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/CategoryDefaultError/rateLimited": {
      "abstract": [
        {
          "text": "An error code that indicates your app requested its status too frequently.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rateLimited"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC37UIApplicationCategoryDefaultErrorCodeLeV",
          "text": "CategoryDefaultError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIApplicationCategoryDefaultErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/CategoryDefaultError/rateLimited",
      "kind": "symbol",
      "role": "symbol",
      "title": "rateLimited",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/categorydefaulterror/ratelimited"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/defaultStatusForCategory:error:": {
      "abstract": [
        {
          "text": "Reports whether this app is the person’s default app in the given category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "defaultStatusForCategory:error:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/defaultStatusForCategory:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultStatusForCategory:error:"
        }
      ],
      "role": "symbol",
      "title": "defaultStatusForCategory:error:",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/defaultstatusforcategory:error:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultErrorDomain": {
      "abstract": [
        {
          "text": "A string that identifies errors the system encounters when it determines if your app is the default in a category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIApplicationCategoryDefaultErrorDomain"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultErrorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIApplicationCategoryDefaultErrorDomain",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationcategorydefaulterrordomain"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultRetryAvailabilityDateErrorKey": {
      "abstract": [
        {
          "text": "A dictionary key, with a value that’s a date when a result is next available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIApplicationCategoryDefaultRetryAvailabilityDateErrorKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultRetryAvailabilityDateErrorKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIApplicationCategoryDefaultRetryAvailabilityDateErrorKey",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationcategorydefaultretryavailabilitydateerrorkey"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultStatus": {
      "abstract": [
        {
          "text": "The default status of an application for some category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIApplicationCategoryDefaultStatus"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultStatus",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIApplicationCategoryDefaultStatus",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationcategorydefaultstatus"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultStatus/UIApplicationCategoryDefaultStatusIsDefault": {
      "abstract": [
        {
          "text": "The application is the default for the category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIApplicationCategoryDefaultStatusIsDefault"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultStatus/UIApplicationCategoryDefaultStatusIsDefault",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIApplicationCategoryDefaultStatusIsDefault",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationcategorydefaultstatus/uiapplicationcategorydefaultstatusisdefault"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultStatus/UIApplicationCategoryDefaultStatusNotDefault": {
      "abstract": [
        {
          "text": "The application is not the default for the category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIApplicationCategoryDefaultStatusNotDefault"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultStatus/UIApplicationCategoryDefaultStatusNotDefault",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIApplicationCategoryDefaultStatusNotDefault",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationcategorydefaultstatus/uiapplicationcategorydefaultstatusnotdefault"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultStatus/UIApplicationCategoryDefaultStatusUnavailable": {
      "abstract": [
        {
          "text": "The status was not available. This is an error condition and the returned error object has more information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIApplicationCategoryDefaultStatusUnavailable"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultStatus/UIApplicationCategoryDefaultStatusUnavailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIApplicationCategoryDefaultStatusUnavailable",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationcategorydefaultstatus/uiapplicationcategorydefaultstatusunavailable"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultStatusLastProvidedDateErrorKey": {
      "abstract": [
        {
          "text": "A dictionary key, with a value that’s the date your app last received a successful result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIApplicationCategoryDefaultStatusLastProvidedDateErrorKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultStatusLastProvidedDateErrorKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIApplicationCategoryDefaultStatusLastProvidedDateErrorKey",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationcategorydefaultstatuslastprovideddateerrorkey"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSError": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Discovering-if-your-app-is-the-default-app-in-a-category",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultStatus",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/Category",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultErrorDomain",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultRetryAvailabilityDateErrorKey",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultStatusLastProvidedDateErrorKey"
      ],
      "title": "Discovering if your app is the default app in a category"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/title",
          "value": "UIApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1Category/title",
          "value": "UIApplicationCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1Category/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1Category/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationCategory"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiapplication/defaultstatusforcategory:error:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
