{"kind":"symbol","identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIApplication/protectedDataDidBecomeAvailableNotification","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"nonisolated","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"protectedDataDidBecomeAvailableNotification","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSNotification","text":"NSNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":".","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSNotificationName","text":"Name","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}]},{"content":[{"text":"Discussion","type":"heading","anchor":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"This notification does not contain a ","type":"text"},{"type":"codeVoice","code":"userInfo"},{"text":" dictionary.","type":"text"}]}],"kind":"content"}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIApplication"]]},"seeAlsoSections":[{"anchor":"Accessing-protected-content","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIApplication/isProtectedDataAvailable","doc://com.apple.uikit/documentation/UIKit/UIApplication/protectedDataWillBecomeUnavailableNotification"],"generated":true,"title":"Accessing protected content"}],"variants":[{"paths":["/documentation/uikit/uiapplication/protecteddatadidbecomeavailablenotification"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uiapplication/protecteddatadidbecomeavailablenotification"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"A notification that posts when the protected files become available for your code to access.","type":"text"}],"metadata":{"title":"protectedDataDidBecomeAvailableNotification","externalID":"c:@UIApplicationProtectedDataDidBecomeAvailable","navigatorTitle":[{"text":"UIApplicationProtectedDataDidBecomeAvailable","kind":"identifier"}],"roleHeading":"Type Property","platforms":[{"deprecated":false,"name":"iOS","unavailable":false,"introducedAt":"4.0","beta":false},{"deprecated":false,"name":"iPadOS","unavailable":false,"introducedAt":"4.0","beta":false},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.1","beta":false},{"deprecated":false,"name":"tvOS","unavailable":false,"beta":false},{"introducedAt":"1.0","name":"visionOS","unavailable":false,"deprecated":false,"beta":false}],"extendedModule":"UIKit","role":"symbol","symbolKind":"property","modules":[{"name":"UIKit"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"protectedDataDidBecomeAvailableNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Name","preciseIdentifier":"c:@T@NSNotificationName","kind":"typeIdentifier"}]},"references":{"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIApplication":{"kind":"symbol","role":"symbol","title":"UIApplication","navigatorTitle":[{"text":"UIApplication","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIApplication","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication","url":"/documentation/uikit/uiapplication","abstract":[{"type":"text","text":"The centralized point of control and coordination for apps running in iOS."}],"type":"topic"},"doc://com.externally.resolved.symbol/c:objc(cs)NSNotification":{"kind":"symbol","title":"NSNotification","abstract":[{"text":"An object containing information broadcast to registered observers that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"url":"/documentation/foundation/nsnotification","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSNotification","type":"topic","role":"symbol","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSNotification"}]},"doc://com.apple.uikit/documentation/UIKit/UIApplication/protectedDataDidBecomeAvailableNotification":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIApplicationProtectedDataDidBecomeAvailable"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"protectedDataDidBecomeAvailableNotification"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNotification","kind":"typeIdentifier","text":"NSNotification"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@NSNotificationName","kind":"typeIdentifier","text":"Name"}],"title":"protectedDataDidBecomeAvailableNotification","abstract":[{"type":"text","text":"A notification that posts when the protected files become available for your code to access."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/protectedDataDidBecomeAvailableNotification","url":"/documentation/uikit/uiapplication/protecteddatadidbecomeavailablenotification"},"doc://com.apple.uikit/documentation/UIKit/UIApplication/protectedDataWillBecomeUnavailableNotification":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIApplicationProtectedDataWillBecomeUnavailable"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"protectedDataWillBecomeUnavailableNotification"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNotification","kind":"typeIdentifier","text":"NSNotification"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@NSNotificationName","kind":"typeIdentifier","text":"Name"}],"title":"protectedDataWillBecomeUnavailableNotification","abstract":[{"type":"text","text":"A notification that posts shortly before protected files are locked down and become inaccessible."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/protectedDataWillBecomeUnavailableNotification","url":"/documentation/uikit/uiapplication/protecteddatawillbecomeunavailablenotification"},"doc://com.externally.resolved.symbol/c:@T@NSNotificationName":{"role":"symbol","fragments":[{"text":"struct ","kind":"text"},{"text":"NSNotification.Name","kind":"identifier"}],"url":"/documentation/foundation/nsnotification/name","title":"NSNotification.Name","identifier":"doc://com.externally.resolved.symbol/c:@T@NSNotificationName","abstract":[{"text":"A structure that defines the name of a notification.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIApplication/isProtectedDataAvailable":{"url":"/documentation/uikit/uiapplication/isprotecteddataavailable","navigatorTitle":[{"kind":"identifier","text":"protectedDataAvailable"}],"type":"topic","title":"isProtectedDataAvailable","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/isProtectedDataAvailable","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isProtectedDataAvailable"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","abstract":[{"text":"A Boolean value that indicates whether content protection is active.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"introducedAt":"4.0","name":"iOS","deprecated":false,"beta":false,"unavailable":false},{"introducedAt":"4.0","name":"iPadOS","deprecated":false,"beta":false,"unavailable":false},{"introducedAt":"13.1","name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false},{"name":"tvOS","deprecated":false,"beta":false,"unavailable":false},{"introducedAt":"1.0","name":"visionOS","deprecated":false,"beta":false,"unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Global Variable","op":"replace"},{"path":"/metadata/title","value":"UIApplicationProtectedDataDidBecomeAvailable","op":"replace"},{"op":"replace","value":"var","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"UIApplicationProtectedDataDidBecomeAvailable","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"anchor":"Accessing-protected-content","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIApplication/isProtectedDataAvailable","doc://com.apple.uikit/documentation/UIKit/UIApplication/protectedDataWillBecomeUnavailableNotification"],"title":"Accessing protected content"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSNotificationName","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSNotificationName","preciseIdentifier":"c:@T@NSNotificationName"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIApplicationProtectedDataDidBecomeAvailable","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/title","value":"UIApplication","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/fragments","value":[{"kind":"identifier","text":"UIApplication"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/navigatorTitle","value":[{"text":"UIApplication","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSNotification/abstract","value":[{"type":"text","text":"A container for information broadcast through a notification center to all registered observers."}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1protectedDataDidBecomeAvailableNotification/title","value":"UIApplicationProtectedDataDidBecomeAvailable","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1protectedDataDidBecomeAvailableNotification/fragments","value":[{"kind":"identifier","text":"UIApplicationProtectedDataDidBecomeAvailable"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1protectedDataWillBecomeUnavailableNotification/title","value":"UIApplicationProtectedDataWillBecomeUnavailable","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1protectedDataWillBecomeUnavailableNotification/fragments","value":[{"text":"UIApplicationProtectedDataWillBecomeUnavailable","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSNotificationName/title","value":"NSNotificationName","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1isProtectedDataAvailable/title","value":"protectedDataAvailable","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1isProtectedDataAvailable/fragments","value":[{"text":"protectedDataAvailable","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}