{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIApplication"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"stateRestorationTimestampKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS","identifier":"doc://com.externally.resolved.symbol/s:SS"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","anchor":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"The value of this key is an "},{"identifier":"doc://com.apple.documentation/documentation/foundation/nsdate","type":"reference","isActive":true},{"type":"text","text":" object containing the date when the restoration archive was saved. The date is specified using coordinated universal time (UTC)."}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uiapplication/staterestorationtimestampkey"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uiapplication/staterestorationtimestampkey"]}],"kind":"symbol","abstract":[{"type":"text","text":"The time your app created the restoration archive."}],"metadata":{"extendedModule":"UIKit","navigatorTitle":[{"kind":"identifier","text":"UIApplicationStateRestorationTimestampKey"}],"roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"stateRestorationTimestampKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"modules":[{"name":"UIKit"}],"symbolKind":"property","title":"stateRestorationTimestampKey","role":"symbol","platforms":[{"introducedAt":"7.0","deprecated":false,"name":"iOS","beta":false,"unavailable":false},{"deprecated":false,"introducedAt":"7.0","unavailable":false,"name":"iPadOS","beta":false},{"deprecated":false,"introducedAt":"13.1","unavailable":false,"name":"Mac Catalyst","beta":false},{"deprecated":false,"unavailable":false,"name":"tvOS","beta":false},{"deprecated":false,"introducedAt":"1.0","unavailable":false,"name":"visionOS","beta":false}],"externalID":"c:@UIApplicationStateRestorationTimestampKey"},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIApplication/stateRestorationTimestampKey","interfaceLanguage":"swift"},"seeAlsoSections":[{"generated":true,"title":"Managing app state restoration","anchor":"Managing-app-state-restoration","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:shouldSaveSecureApplicationState:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:shouldRestoreSecureApplicationState:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:viewControllerWithRestorationIdentifierPath:coder:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:willEncodeRestorableStateWith:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didDecodeRestorableStateWith:)","doc://com.apple.uikit/documentation/UIKit/UIApplication/stateRestorationBundleVersionKey","doc://com.apple.uikit/documentation/UIKit/UIApplication/stateRestorationSystemVersionKey","doc://com.apple.uikit/documentation/UIKit/UIApplication/stateRestorationUserInterfaceIdiomKey","doc://com.apple.uikit/documentation/UIKit/UIApplication/stateRestorationViewControllerStoryboardKey"]}],"references":{"doc://com.apple.documentation/documentation/foundation/nsdate":{"abstract":[{"text":"A representation of a specific point in time, for use when you need reference semantics or other Foundation-specific behavior.","type":"text"}],"kind":"symbol","role":"symbol","title":"NSDate","fragments":[{"text":"class ","kind":"text"},{"kind":"identifier","text":"NSDate"}],"type":"topic","identifier":"doc://com.apple.documentation/documentation/foundation/nsdate","url":"/documentation/foundation/nsdate"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:willEncodeRestorableStateWith:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"willEncodeRestorableStateWith","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","role":"symbol","url":"/documentation/uikit/uiapplicationdelegate/application(_:willencoderestorablestatewith:)","title":"application(_:willEncodeRestorableStateWith:)","abstract":[{"text":"Tells your delegate to save any high-level state information at the beginning of the state preservation process.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:willEncodeRestorableStateWith:)","navigatorTitle":[{"text":"application:willEncodeRestorableStateWithCoder:","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:viewControllerWithRestorationIdentifierPath:coder:)":{"navigatorTitle":[{"text":"application:viewControllerWithRestorationIdentifierPath:coder:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"viewControllerWithRestorationIdentifierPath","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","url":"/documentation/uikit/uiapplicationdelegate/application(_:viewcontrollerwithrestorationidentifierpath:coder:)","title":"application(_:viewControllerWithRestorationIdentifierPath:coder:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:viewControllerWithRestorationIdentifierPath:coder:)","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Asks the delegate to provide the specified view controller."}]},"doc://com.apple.uikit/documentation/UIKit/UIApplication/stateRestorationViewControllerStoryboardKey":{"abstract":[{"text":"A reference to the storyboard that contains the view controller.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/stateRestorationViewControllerStoryboardKey","url":"/documentation/uikit/uiapplication/staterestorationviewcontrollerstoryboardkey","navigatorTitle":[{"text":"UIStateRestorationViewControllerStoryboardKey","kind":"identifier"}],"title":"stateRestorationViewControllerStoryboardKey","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stateRestorationViewControllerStoryboardKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIApplication/stateRestorationUserInterfaceIdiomKey":{"abstract":[{"text":"The user interface idiom that was in effect when your app created the restoration archive.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/stateRestorationUserInterfaceIdiomKey","url":"/documentation/uikit/uiapplication/staterestorationuserinterfaceidiomkey","navigatorTitle":[{"text":"UIApplicationStateRestorationUserInterfaceIdiomKey","kind":"identifier"}],"title":"stateRestorationUserInterfaceIdiomKey","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stateRestorationUserInterfaceIdiomKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didDecodeRestorableStateWith:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"text":"(","kind":"text"},{"text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didDecodeRestorableStateWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","role":"symbol","url":"/documentation/uikit/uiapplicationdelegate/application(_:diddecoderestorablestatewith:)","title":"application(_:didDecodeRestorableStateWith:)","abstract":[{"text":"Tells your delegate to restore any high-level state information as part of the state restoration process.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didDecodeRestorableStateWith:)","navigatorTitle":[{"text":"application:didDecodeRestorableStateWithCoder:","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIApplication":{"kind":"symbol","role":"symbol","title":"UIApplication","navigatorTitle":[{"text":"UIApplication","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIApplication","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication","url":"/documentation/uikit/uiapplication","abstract":[{"type":"text","text":"The centralized point of control and coordination for apps running in iOS."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:shouldSaveSecureApplicationState:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldSaveSecureApplicationState","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"/documentation/uikit/uiapplicationdelegate/application(_:shouldsavesecureapplicationstate:)","title":"application(_:shouldSaveSecureApplicationState:)","abstract":[{"text":"Asks the delegate whether to securely preserve the app’s state.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:shouldSaveSecureApplicationState:)","navigatorTitle":[{"text":"application:shouldSaveSecureApplicationState:","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:shouldRestoreSecureApplicationState:)":{"abstract":[{"text":"Asks the delegate whether to restore the app’s saved state.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:shouldRestoreSecureApplicationState:)","url":"/documentation/uikit/uiapplicationdelegate/application(_:shouldrestoresecureapplicationstate:)","navigatorTitle":[{"text":"application:shouldRestoreSecureApplicationState:","kind":"identifier"}],"title":"application(_:shouldRestoreSecureApplicationState:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldRestoreSecureApplicationState","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIApplication/stateRestorationBundleVersionKey":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"stateRestorationBundleVersionKey","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"/documentation/uikit/uiapplication/staterestorationbundleversionkey","title":"stateRestorationBundleVersionKey","abstract":[{"text":"The version of your app responsible for creating the restoration archive.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/stateRestorationBundleVersionKey","navigatorTitle":[{"text":"UIApplicationStateRestorationBundleVersionKey","kind":"identifier"}]},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"abstract":[{"type":"text","text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. "}],"title":"NSString","url":"/documentation/foundation/nsstring","kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","fragments":[{"kind":"text","text":"class "},{"text":"NSString","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIApplication/stateRestorationTimestampKey":{"abstract":[{"text":"The time your app created the restoration archive.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/stateRestorationTimestampKey","url":"/documentation/uikit/uiapplication/staterestorationtimestampkey","navigatorTitle":[{"text":"UIApplicationStateRestorationTimestampKey","kind":"identifier"}],"title":"stateRestorationTimestampKey","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stateRestorationTimestampKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIApplication/stateRestorationSystemVersionKey":{"abstract":[{"text":"The version of the system on which your app created the restoration archive.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/stateRestorationSystemVersionKey","url":"/documentation/uikit/uiapplication/staterestorationsystemversionkey","navigatorTitle":[{"text":"UIApplicationStateRestorationSystemVersionKey","kind":"identifier"}],"title":"stateRestorationSystemVersionKey","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stateRestorationSystemVersionKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://com.externally.resolved.symbol/s:SS":{"identifier":"doc://com.externally.resolved.symbol/s:SS","title":"String","url":"/documentation/Swift/String","abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}],"fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"String"}],"type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"introducedAt":"7.0","deprecated":false,"beta":false,"name":"iOS"},{"unavailable":false,"introducedAt":"7.0","deprecated":false,"beta":false,"name":"iPadOS"},{"unavailable":false,"introducedAt":"13.1","deprecated":false,"beta":false,"name":"Mac Catalyst"},{"beta":false,"deprecated":false,"name":"tvOS","unavailable":false},{"beta":false,"introducedAt":"1.0","deprecated":false,"name":"visionOS","unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Global Variable","op":"replace"},{"path":"/metadata/title","value":"UIApplicationStateRestorationTimestampKey","op":"replace"},{"path":"/metadata/symbolKind","value":"var","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"UIApplicationStateRestorationTimestampKey","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"anchor":"Managing-app-state-restoration","title":"Managing app state restoration","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:shouldSaveSecureApplicationState:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:shouldRestoreSecureApplicationState:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:viewControllerWithRestorationIdentifierPath:coder:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:willEncodeRestorableStateWith:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didDecodeRestorableStateWith:)","doc://com.apple.uikit/documentation/UIKit/UIApplication/stateRestorationBundleVersionKey","doc://com.apple.uikit/documentation/UIKit/UIApplication/stateRestorationSystemVersionKey","doc://com.apple.uikit/documentation/UIKit/UIApplication/stateRestorationUserInterfaceIdiomKey","doc://com.apple.uikit/documentation/UIKit/UIApplication/stateRestorationViewControllerStoryboardKey"],"generated":true}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIApplicationStateRestorationTimestampKey"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsdate/abstract","value":[{"text":"A representation of a specific point in time, independent of any calendar or time zone.","type":"text"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:willEncodeRestorableStateWith:)/title","value":"application:willEncodeRestorableStateWithCoder:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:willEncodeRestorableStateWith:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"application:willEncodeRestorableStateWithCoder:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:viewControllerWithRestorationIdentifierPath:coder:)/title","value":"application:viewControllerWithRestorationIdentifierPath:coder:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:viewControllerWithRestorationIdentifierPath:coder:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"application:viewControllerWithRestorationIdentifierPath:coder:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1stateRestorationViewControllerStoryboardKey/title","value":"UIStateRestorationViewControllerStoryboardKey"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1stateRestorationViewControllerStoryboardKey/fragments","value":[{"kind":"identifier","text":"UIStateRestorationViewControllerStoryboardKey"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1stateRestorationUserInterfaceIdiomKey/title","value":"UIApplicationStateRestorationUserInterfaceIdiomKey"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1stateRestorationUserInterfaceIdiomKey/fragments","value":[{"text":"UIApplicationStateRestorationUserInterfaceIdiomKey","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didDecodeRestorableStateWith:)/title","value":"application:didDecodeRestorableStateWithCoder:"},{"value":[{"text":"- ","kind":"text"},{"text":"application:didDecodeRestorableStateWithCoder:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didDecodeRestorableStateWith:)/fragments"},{"value":"UIApplication","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/title"},{"value":[{"text":"UIApplication","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/fragments"},{"value":[{"text":"UIApplication","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/navigatorTitle"},{"value":"application:shouldSaveSecureApplicationState:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:shouldSaveSecureApplicationState:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:shouldSaveSecureApplicationState:"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:shouldSaveSecureApplicationState:)/fragments"},{"value":"application:shouldRestoreSecureApplicationState:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:shouldRestoreSecureApplicationState:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:shouldRestoreSecureApplicationState:"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:shouldRestoreSecureApplicationState:)/fragments"},{"value":"UIApplicationStateRestorationBundleVersionKey","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1stateRestorationBundleVersionKey/title"},{"value":[{"kind":"identifier","text":"UIApplicationStateRestorationBundleVersionKey"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1stateRestorationBundleVersionKey/fragments"},{"value":[{"text":"A static, plain-text Unicode string object.","type":"text"}],"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract"},{"value":"UIApplicationStateRestorationTimestampKey","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1stateRestorationTimestampKey/title"},{"value":[{"kind":"identifier","text":"UIApplicationStateRestorationTimestampKey"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1stateRestorationTimestampKey/fragments"},{"value":"UIApplicationStateRestorationSystemVersionKey","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1stateRestorationSystemVersionKey/title"},{"value":[{"text":"UIApplicationStateRestorationSystemVersionKey","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1stateRestorationSystemVersionKey/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}