{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIApplication"]]},"kind":"symbol","identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIApplication/willTerminateNotification","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A notification that posts when the app is about to terminate."}],"seeAlsoSections":[{"generated":true,"anchor":"Responding-to-app-life-cycle-events","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidBecomeActive(_:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationWillResignActive(_:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidEnterBackground(_:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationWillEnterForeground(_:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationWillTerminate(_:)","doc://com.apple.uikit/documentation/UIKit/UIApplication/didBecomeActiveNotification","doc://com.apple.uikit/documentation/UIKit/UIApplication/didEnterBackgroundNotification","doc://com.apple.uikit/documentation/UIKit/UIApplication/willEnterForegroundNotification","doc://com.apple.uikit/documentation/UIKit/UIApplication/willResignActiveNotification"],"title":"Responding to app life-cycle events"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"nonisolated","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willTerminateNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSNotification"},{"text":".","kind":"text"},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName","identifier":"doc://com.externally.resolved.symbol/c:@T@NSNotificationName"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"Discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"text":"This notification is associated with the delegate ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationWillTerminate(_:)","type":"reference","isActive":true},{"text":" method. This notification does not contain a ","type":"text"},{"type":"codeVoice","code":"userInfo"},{"text":" dictionary.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"sections":[],"variants":[{"paths":["/documentation/uikit/uiapplication/willterminatenotification"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uiapplication/willterminatenotification"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"willTerminateNotification","extendedModule":"UIKit","roleHeading":"Type Property","platforms":[{"name":"iOS","deprecated":false,"beta":false,"unavailable":false},{"name":"iPadOS","deprecated":false,"beta":false,"unavailable":false},{"name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false},{"name":"tvOS","deprecated":false,"beta":false,"unavailable":false},{"name":"visionOS","deprecated":false,"beta":false,"unavailable":false}],"externalID":"c:@UIApplicationWillTerminateNotification","modules":[{"name":"UIKit"}],"symbolKind":"property","navigatorTitle":[{"text":"UIApplicationWillTerminateNotification","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willTerminateNotification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":".","kind":"text"},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName"}],"role":"symbol"},"references":{"doc://com.externally.resolved.symbol/c:objc(cs)NSNotification":{"kind":"symbol","title":"NSNotification","abstract":[{"text":"An object containing information broadcast to registered observers that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"url":"/documentation/foundation/nsnotification","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSNotification","type":"topic","role":"symbol","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSNotification"}]},"doc://com.apple.uikit/documentation/UIKit/UIApplication":{"kind":"symbol","role":"symbol","title":"UIApplication","navigatorTitle":[{"text":"UIApplication","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIApplication","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication","url":"/documentation/uikit/uiapplication","abstract":[{"type":"text","text":"The centralized point of control and coordination for apps running in iOS."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationWillEnterForeground(_:)":{"abstract":[{"type":"text","text":"Tells the delegate that the app is about to enter the foreground."}],"navigatorTitle":[{"kind":"identifier","text":"applicationWillEnterForeground:"}],"type":"topic","url":"/documentation/uikit/uiapplicationdelegate/applicationwillenterforeground(_:)","title":"applicationWillEnterForeground(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationWillEnterForeground"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationWillEnterForeground(_:)","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIApplication/willEnterForegroundNotification":{"abstract":[{"type":"text","text":"A notification that posts shortly before an app leaves the background state on its way to becoming the active app."}],"url":"/documentation/uikit/uiapplication/willenterforegroundnotification","navigatorTitle":[{"text":"UIApplicationWillEnterForegroundNotification","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"willEnterForegroundNotification"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSNotificationName","text":"Name","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/willEnterForegroundNotification","title":"willEnterForegroundNotification"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationWillTerminate(_:)":{"abstract":[{"type":"text","text":"Tells the delegate when the app is about to terminate."}],"url":"/documentation/uikit/uiapplicationdelegate/applicationwillterminate(_:)","navigatorTitle":[{"kind":"identifier","text":"applicationWillTerminate:"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"applicationWillTerminate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationWillTerminate(_:)","title":"applicationWillTerminate(_:)"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationWillResignActive(_:)":{"abstract":[{"type":"text","text":"Tells the delegate that the app is about to become inactive."}],"url":"/documentation/uikit/uiapplicationdelegate/applicationwillresignactive(_:)","navigatorTitle":[{"kind":"identifier","text":"applicationWillResignActive:"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationWillResignActive","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationWillResignActive(_:)","title":"applicationWillResignActive(_:)"},"doc://com.apple.uikit/documentation/UIKit/UIApplication/willTerminateNotification":{"abstract":[{"type":"text","text":"A notification that posts when the app is about to terminate."}],"url":"/documentation/uikit/uiapplication/willterminatenotification","navigatorTitle":[{"kind":"identifier","text":"UIApplicationWillTerminateNotification"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"willTerminateNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName","text":"Name"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/willTerminateNotification","title":"willTerminateNotification"},"doc://com.apple.uikit/documentation/UIKit/UIApplication/willResignActiveNotification":{"abstract":[{"type":"text","text":"A notification that posts when the app is no longer active and loses focus."}],"url":"/documentation/uikit/uiapplication/willresignactivenotification","navigatorTitle":[{"text":"UIApplicationWillResignActiveNotification","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"willResignActiveNotification"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSNotificationName","text":"Name","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/willResignActiveNotification","title":"willResignActiveNotification"},"doc://com.apple.uikit/documentation/UIKit/UIApplication/didEnterBackgroundNotification":{"abstract":[{"type":"text","text":"A notification that posts when the app enters the background."}],"url":"/documentation/uikit/uiapplication/didenterbackgroundnotification","navigatorTitle":[{"text":"UIApplicationDidEnterBackgroundNotification","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"didEnterBackgroundNotification"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSNotificationName","text":"Name","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/didEnterBackgroundNotification","title":"didEnterBackgroundNotification"},"doc://com.apple.uikit/documentation/UIKit/UIApplication/didBecomeActiveNotification":{"abstract":[{"type":"text","text":"A notification that posts when the app becomes active."}],"url":"/documentation/uikit/uiapplication/didbecomeactivenotification","navigatorTitle":[{"kind":"identifier","text":"UIApplicationDidBecomeActiveNotification"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"didBecomeActiveNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName","text":"Name"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/didBecomeActiveNotification","title":"didBecomeActiveNotification"},"doc://com.externally.resolved.symbol/c:@T@NSNotificationName":{"role":"symbol","fragments":[{"text":"struct ","kind":"text"},{"text":"NSNotification.Name","kind":"identifier"}],"url":"/documentation/foundation/nsnotification/name","title":"NSNotification.Name","identifier":"doc://com.externally.resolved.symbol/c:@T@NSNotificationName","abstract":[{"text":"A structure that defines the name of a notification.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidBecomeActive(_:)":{"abstract":[{"type":"text","text":"Tells the delegate that the app has become active."}],"url":"/documentation/uikit/uiapplicationdelegate/applicationdidbecomeactive(_:)","navigatorTitle":[{"text":"applicationDidBecomeActive:","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"applicationDidBecomeActive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidBecomeActive(_:)","title":"applicationDidBecomeActive(_:)"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidEnterBackground(_:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"applicationDidEnterBackground:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationDidEnterBackground","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication"},{"kind":"text","text":")"}],"url":"/documentation/uikit/uiapplicationdelegate/applicationdidenterbackground(_:)","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidEnterBackground(_:)","title":"applicationDidEnterBackground(_:)","abstract":[{"text":"Tells the delegate that the app is now in the background.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"beta":false,"name":"iOS","deprecated":false},{"unavailable":false,"beta":false,"name":"iPadOS","deprecated":false},{"unavailable":false,"beta":false,"name":"Mac Catalyst","deprecated":false},{"unavailable":false,"beta":false,"name":"tvOS","deprecated":false},{"unavailable":false,"beta":false,"name":"visionOS","deprecated":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Global Variable","op":"replace"},{"path":"/metadata/title","value":"UIApplicationWillTerminateNotification","op":"replace"},{"path":"/metadata/symbolKind","value":"var","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"UIApplicationWillTerminateNotification","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidBecomeActive(_:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationWillResignActive(_:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidEnterBackground(_:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationWillEnterForeground(_:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationWillTerminate(_:)","doc://com.apple.uikit/documentation/UIKit/UIApplication/didBecomeActiveNotification","doc://com.apple.uikit/documentation/UIKit/UIApplication/didEnterBackgroundNotification","doc://com.apple.uikit/documentation/UIKit/UIApplication/willEnterForegroundNotification","doc://com.apple.uikit/documentation/UIKit/UIApplication/willResignActiveNotification"],"title":"Responding to app life-cycle events","anchor":"Responding-to-app-life-cycle-events"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSNotificationName","kind":"typeIdentifier","text":"NSNotificationName","preciseIdentifier":"c:@T@NSNotificationName"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIApplicationWillTerminateNotification"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSNotification/abstract","value":[{"type":"text","text":"A container for information broadcast through a notification center to all registered observers."}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/title","value":"UIApplication","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/fragments","value":[{"kind":"identifier","text":"UIApplication"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/navigatorTitle","value":[{"text":"UIApplication","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationWillEnterForeground(_:)/title","value":"applicationWillEnterForeground:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationWillEnterForeground(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"applicationWillEnterForeground:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1willEnterForegroundNotification/title","value":"UIApplicationWillEnterForegroundNotification","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1willEnterForegroundNotification/fragments","value":[{"text":"UIApplicationWillEnterForegroundNotification","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationWillTerminate(_:)/title","value":"applicationWillTerminate:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationWillTerminate(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"applicationWillTerminate:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationWillResignActive(_:)/title","value":"applicationWillResignActive:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationWillResignActive(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applicationWillResignActive:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1willTerminateNotification/title","value":"UIApplicationWillTerminateNotification","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1willTerminateNotification/fragments","value":[{"kind":"identifier","text":"UIApplicationWillTerminateNotification"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1willResignActiveNotification/title","value":"UIApplicationWillResignActiveNotification","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1willResignActiveNotification/fragments","value":[{"text":"UIApplicationWillResignActiveNotification","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1didEnterBackgroundNotification/title","value":"UIApplicationDidEnterBackgroundNotification","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1didEnterBackgroundNotification/fragments","value":[{"kind":"identifier","text":"UIApplicationDidEnterBackgroundNotification"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1didBecomeActiveNotification/title","value":"UIApplicationDidBecomeActiveNotification","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1didBecomeActiveNotification/fragments","value":[{"kind":"identifier","text":"UIApplicationDidBecomeActiveNotification"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSNotificationName/title","value":"NSNotificationName","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationDidBecomeActive(_:)/title","value":"applicationDidBecomeActive:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationDidBecomeActive(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applicationDidBecomeActive:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationDidEnterBackground(_:)/title","value":"applicationDidEnterBackground:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationDidEnterBackground(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applicationDidEnterBackground:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}