{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/coreaudio/1494595-anonymous"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/coreaudio/1494595-anonymous"]}],"seeAlsoSections":[{"title":"Enumerations","identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous"],"anchor":"Enumerations","generated":true}],"metadata":{"title":"Anonymous","role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"Core Audio"}]},"identifier":{"url":"doc://com.apple.coreaudio/documentation/CoreAudio/1494595-anonymous","interfaceLanguage":"swift"},"kind":"article","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coreaudio/documentation/CoreAudio","doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations"]]},"topicSections":[{"title":"Constants","identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInClassID"],"anchor":"Constants"}],"sections":[],"references":{"doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous":{"kind":"article","title":"Anonymous","type":"topic","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous","url":"/documentation/coreaudio/1580736-anonymous","role":"collectionGroup"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580748-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous":{"kind":"article","title":"Anonymous","type":"topic","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous","url":"/documentation/coreaudio/1580731-anonymous","role":"collectionGroup"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInClassID":{"navigatorTitle":[{"text":"kAudioPlugInClassID","kind":"identifier"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInClassID","title":"kAudioPlugInClassID","url":"/documentation/coreaudio/kaudiopluginclassid","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kAudioPlugInClassID"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@AudioClassID","kind":"typeIdentifier","text":"AudioClassID"}],"role":"symbol","kind":"symbol","abstract":[],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","role":"overview","kind":"technologies"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580719-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580741-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580749-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580746-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580737-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous":{"abstract":[],"url":"/documentation/coreaudio/1580715-anonymous","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous","type":"topic","role":"collectionGroup","kind":"article","title":"Anonymous"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580740-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous":{"kind":"article","title":"Anonymous","type":"topic","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous","url":"/documentation/coreaudio/1580726-anonymous","role":"collectionGroup"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580720-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous":{"kind":"article","title":"Anonymous","type":"topic","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous","url":"/documentation/coreaudio/1580722-anonymous","role":"collectionGroup"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous":{"abstract":[],"url":"/documentation/coreaudio/1580747-anonymous","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous","type":"topic","role":"collectionGroup","kind":"article","title":"Anonymous"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous":{"type":"topic","title":"Anonymous","kind":"article","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous","role":"collectionGroup","abstract":[],"url":"/documentation/coreaudio/1580723-anonymous"},"doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations":{"kind":"article","title":"Core Audio Enumerations","type":"topic","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations","url":"/documentation/coreaudio/core-audio-enumerations","role":"collectionGroup"},"doc://com.apple.coreaudio/documentation/CoreAudio":{"kind":"symbol","title":"Core Audio","type":"topic","abstract":[{"type":"text","text":"Use the Core Audio framework to interact with device’s audio hardware."}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio","url":"/documentation/coreaudio","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"title":"Constants","anchor":"Constants","identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInClassID"]}],"op":"replace","path":"/topicSections"},{"value":[{"generated":true,"title":"Enumerations","identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous"],"anchor":"Enumerations"}],"op":"replace","path":"/seeAlsoSections"},{"value":"kAudioPlugInClassID","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioPlugInClassID/title"},{"value":[{"kind":"identifier","text":"kAudioPlugInClassID"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioPlugInClassID/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}