{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio",
        "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/1494541-anonymous"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Anonymous"
  },
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580715-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580719-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580720-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580722-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580723-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580726-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580731-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580736-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580737-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580740-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580741-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580746-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580747-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580748-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580749-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio Enumerations",
      "type": "topic",
      "url": "/documentation/coreaudio/core-audio-enumerations"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyAvailablePhysicalFormats": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyAvailablePhysicalFormats"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyAvailablePhysicalFormats",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyAvailablePhysicalFormats"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamPropertyAvailablePhysicalFormats",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreampropertyavailablephysicalformats"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyAvailableVirtualFormats": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyAvailableVirtualFormats"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyAvailableVirtualFormats",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyAvailableVirtualFormats"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamPropertyAvailableVirtualFormats",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreampropertyavailablevirtualformats"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyDirection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyDirection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyDirection"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamPropertyDirection",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreampropertydirection"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyIsActive": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyIsActive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyIsActive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyIsActive"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamPropertyIsActive",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreampropertyisactive"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyLatency": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyLatency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyLatency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyLatency"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamPropertyLatency",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreampropertylatency"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyPhysicalFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyPhysicalFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyPhysicalFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyPhysicalFormat"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamPropertyPhysicalFormat",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreampropertyphysicalformat"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyStartingChannel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyStartingChannel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyStartingChannel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyStartingChannel"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamPropertyStartingChannel",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreampropertystartingchannel"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyTerminalType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyTerminalType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyTerminalType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyTerminalType"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamPropertyTerminalType",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreampropertyterminaltype"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyVirtualFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyVirtualFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyVirtualFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyVirtualFormat"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamPropertyVirtualFormat",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreampropertyvirtualformat"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyAvailablePhysicalFormats",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyAvailableVirtualFormats",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyDirection",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyIsActive",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyLatency",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyPhysicalFormat",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyStartingChannel",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyTerminalType",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyVirtualFormat"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyAvailablePhysicalFormats",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyAvailableVirtualFormats",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyDirection",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyIsActive",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyLatency",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyPhysicalFormat",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyStartingChannel",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyTerminalType",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyVirtualFormat"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyAvailableVirtualFormats/title",
          "value": "kAudioStreamPropertyAvailableVirtualFormats"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyAvailableVirtualFormats/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamPropertyAvailableVirtualFormats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyVirtualFormat/title",
          "value": "kAudioStreamPropertyVirtualFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyVirtualFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamPropertyVirtualFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyLatency/title",
          "value": "kAudioStreamPropertyLatency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyLatency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamPropertyLatency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyDirection/title",
          "value": "kAudioStreamPropertyDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamPropertyDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyTerminalType/title",
          "value": "kAudioStreamPropertyTerminalType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyTerminalType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamPropertyTerminalType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyPhysicalFormat/title",
          "value": "kAudioStreamPropertyPhysicalFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyPhysicalFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamPropertyPhysicalFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyAvailablePhysicalFormats/title",
          "value": "kAudioStreamPropertyAvailablePhysicalFormats"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyAvailablePhysicalFormats/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamPropertyAvailablePhysicalFormats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyIsActive/title",
          "value": "kAudioStreamPropertyIsActive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyIsActive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamPropertyIsActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyStartingChannel/title",
          "value": "kAudioStreamPropertyStartingChannel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyStartingChannel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamPropertyStartingChannel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/1494541-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/1494541-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
