{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio",
        "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/1494580-anonymous"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Anonymous"
  },
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580715-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580719-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580720-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580722-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580723-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580726-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580731-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580736-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580737-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580740-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580741-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580746-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580747-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580748-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580749-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio Enumerations",
      "type": "topic",
      "url": "/documentation/coreaudio/core-audio-enumerations"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeAVB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeAVB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeAVB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeAVB"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceTransportTypeAVB",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicetransporttypeavb"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeAggregate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeAggregate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeAggregate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeAggregate"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceTransportTypeAggregate",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicetransporttypeaggregate"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeAirPlay": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeAirPlay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeAirPlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeAirPlay"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceTransportTypeAirPlay",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicetransporttypeairplay"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeBluetooth": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeBluetooth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeBluetooth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeBluetooth"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceTransportTypeBluetooth",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicetransporttypebluetooth"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeBluetoothLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeBluetoothLE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeBluetoothLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeBluetoothLE"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceTransportTypeBluetoothLE",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicetransporttypebluetoothle"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeBuiltIn": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeBuiltIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeBuiltIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeBuiltIn"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceTransportTypeBuiltIn",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicetransporttypebuiltin"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeDisplayPort": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeDisplayPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeDisplayPort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeDisplayPort"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceTransportTypeDisplayPort",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicetransporttypedisplayport"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeFireWire": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeFireWire"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeFireWire",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeFireWire"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceTransportTypeFireWire",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicetransporttypefirewire"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeHDMI": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeHDMI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeHDMI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeHDMI"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceTransportTypeHDMI",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicetransporttypehdmi"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypePCI": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypePCI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypePCI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypePCI"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceTransportTypePCI",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicetransporttypepci"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeThunderbolt": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeThunderbolt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeThunderbolt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeThunderbolt"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceTransportTypeThunderbolt",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicetransporttypethunderbolt"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeUSB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeUSB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeUSB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeUSB"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceTransportTypeUSB",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicetransporttypeusb"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeUnknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeUnknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceTransportTypeUnknown",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicetransporttypeunknown"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeVirtual": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeVirtual"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeVirtual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeVirtual"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceTransportTypeVirtual",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicetransporttypevirtual"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeAVB",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeAggregate",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeAirPlay",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeBluetooth",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeBluetoothLE",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeBuiltIn",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeDisplayPort",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeFireWire",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeHDMI",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypePCI",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeThunderbolt",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeUSB",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeUnknown",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeVirtual"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeAVB",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeAggregate",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeAirPlay",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeBluetooth",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeBluetoothLE",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeBuiltIn",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeDisplayPort",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeFireWire",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeHDMI",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypePCI",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeThunderbolt",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeUSB",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeUnknown",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeVirtual"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeUSB/title",
          "value": "kAudioDeviceTransportTypeUSB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeUSB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypeUSB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeAirPlay/title",
          "value": "kAudioDeviceTransportTypeAirPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeAirPlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypeAirPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypePCI/title",
          "value": "kAudioDeviceTransportTypePCI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypePCI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypePCI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeBuiltIn/title",
          "value": "kAudioDeviceTransportTypeBuiltIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeBuiltIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypeBuiltIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeDisplayPort/title",
          "value": "kAudioDeviceTransportTypeDisplayPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeDisplayPort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypeDisplayPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeThunderbolt/title",
          "value": "kAudioDeviceTransportTypeThunderbolt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeThunderbolt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypeThunderbolt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeAggregate/title",
          "value": "kAudioDeviceTransportTypeAggregate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeAggregate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypeAggregate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeBluetoothLE/title",
          "value": "kAudioDeviceTransportTypeBluetoothLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeBluetoothLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypeBluetoothLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeUnknown/title",
          "value": "kAudioDeviceTransportTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeVirtual/title",
          "value": "kAudioDeviceTransportTypeVirtual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeVirtual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypeVirtual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeFireWire/title",
          "value": "kAudioDeviceTransportTypeFireWire"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeFireWire/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypeFireWire"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeHDMI/title",
          "value": "kAudioDeviceTransportTypeHDMI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeHDMI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypeHDMI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeAVB/title",
          "value": "kAudioDeviceTransportTypeAVB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeAVB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypeAVB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeBluetooth/title",
          "value": "kAudioDeviceTransportTypeBluetooth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeBluetooth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypeBluetooth"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/1494580-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/1494580-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
