{"metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"Anonymous","modules":[{"name":"Core Audio"}]},"topicSections":[{"identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyBaseClass","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyClass","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementCategoryName","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementName","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementNumberName","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyFirmwareVersion","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyIdentify","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyManufacturer","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyModelName","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyName","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyOwnedObjects","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyOwner","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertySerialNumber"],"title":"Constants","anchor":"Constants"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.coreaudio/documentation/CoreAudio/1494449-anonymous"},"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous"],"title":"Enumerations","anchor":"Enumerations"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/coreaudio/1494449-anonymous"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/coreaudio/1494449-anonymous"]}],"kind":"article","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coreaudio/documentation/CoreAudio","doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations"]]},"references":{"doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580720-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous":{"kind":"article","title":"Anonymous","type":"topic","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous","url":"/documentation/coreaudio/1580736-anonymous","role":"collectionGroup"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","role":"overview","kind":"technologies"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580746-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyFirmwareVersion":{"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"kAudioObjectPropertyFirmwareVersion","kind":"identifier"}],"url":"/documentation/coreaudio/kaudioobjectpropertyfirmwareversion","title":"kAudioObjectPropertyFirmwareVersion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"kAudioObjectPropertyFirmwareVersion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyFirmwareVersion","role":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous":{"kind":"article","title":"Anonymous","type":"topic","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous","url":"/documentation/coreaudio/1580731-anonymous","role":"collectionGroup"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyClass":{"kind":"symbol","type":"topic","url":"/documentation/coreaudio/kaudioobjectpropertyclass","title":"kAudioObjectPropertyClass","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"kAudioObjectPropertyClass","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyClass","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kAudioObjectPropertyClass"}],"abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyOwner":{"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"kAudioObjectPropertyOwner"}],"url":"/documentation/coreaudio/kaudioobjectpropertyowner","title":"kAudioObjectPropertyOwner","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kAudioObjectPropertyOwner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyOwner","role":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementNumberName":{"abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioObjectPropertyElementNumberName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"url":"/documentation/coreaudio/kaudioobjectpropertyelementnumbername","type":"topic","kind":"symbol","title":"kAudioObjectPropertyElementNumberName","navigatorTitle":[{"text":"kAudioObjectPropertyElementNumberName","kind":"identifier"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementNumberName"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580719-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementName":{"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"kAudioObjectPropertyElementName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"url":"/documentation/coreaudio/kaudioobjectpropertyelementname","type":"topic","kind":"symbol","title":"kAudioObjectPropertyElementName","navigatorTitle":[{"text":"kAudioObjectPropertyElementName","kind":"identifier"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementName"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyBaseClass":{"kind":"symbol","type":"topic","url":"/documentation/coreaudio/kaudioobjectpropertybaseclass","title":"kAudioObjectPropertyBaseClass","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioObjectPropertyBaseClass"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyBaseClass","role":"symbol","navigatorTitle":[{"text":"kAudioObjectPropertyBaseClass","kind":"identifier"}],"abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580741-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertySerialNumber":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioObjectPropertySerialNumber","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AudioObjectPropertySelector","text":"AudioObjectPropertySelector","kind":"typeIdentifier"}],"type":"topic","url":"/documentation/coreaudio/kaudioobjectpropertyserialnumber","kind":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertySerialNumber","abstract":[],"role":"symbol","navigatorTitle":[{"text":"kAudioObjectPropertySerialNumber","kind":"identifier"}],"title":"kAudioObjectPropertySerialNumber"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyModelName":{"role":"symbol","abstract":[],"url":"/documentation/coreaudio/kaudioobjectpropertymodelname","type":"topic","title":"kAudioObjectPropertyModelName","navigatorTitle":[{"text":"kAudioObjectPropertyModelName","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioObjectPropertyModelName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AudioObjectPropertySelector","text":"AudioObjectPropertySelector","kind":"typeIdentifier"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyModelName"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyName":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioObjectPropertyName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AudioObjectPropertySelector","text":"AudioObjectPropertySelector","kind":"typeIdentifier"}],"type":"topic","url":"/documentation/coreaudio/kaudioobjectpropertyname","kind":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyName","abstract":[],"role":"symbol","navigatorTitle":[{"text":"kAudioObjectPropertyName","kind":"identifier"}],"title":"kAudioObjectPropertyName"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous":{"kind":"article","title":"Anonymous","type":"topic","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous","url":"/documentation/coreaudio/1580722-anonymous","role":"collectionGroup"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyOwnedObjects":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"kAudioObjectPropertyOwnedObjects"}],"role":"symbol","url":"/documentation/coreaudio/kaudioobjectpropertyownedobjects","title":"kAudioObjectPropertyOwnedObjects","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyOwnedObjects","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioObjectPropertyOwnedObjects"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"kind":"symbol","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio":{"kind":"symbol","title":"Core Audio","type":"topic","abstract":[{"type":"text","text":"Use the Core Audio framework to interact with device’s audio hardware."}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio","url":"/documentation/coreaudio","role":"collection"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580737-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyIdentify":{"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioObjectPropertyIdentify","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyIdentify","navigatorTitle":[{"text":"kAudioObjectPropertyIdentify","kind":"identifier"}],"abstract":[],"url":"/documentation/coreaudio/kaudioobjectpropertyidentify","title":"kAudioObjectPropertyIdentify","kind":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580740-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations":{"kind":"article","title":"Core Audio Enumerations","type":"topic","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations","url":"/documentation/coreaudio/core-audio-enumerations","role":"collectionGroup"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580749-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyManufacturer":{"type":"topic","navigatorTitle":[{"text":"kAudioObjectPropertyManufacturer","kind":"identifier"}],"role":"symbol","url":"/documentation/coreaudio/kaudioobjectpropertymanufacturer","title":"kAudioObjectPropertyManufacturer","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyManufacturer","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioObjectPropertyManufacturer","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector","kind":"typeIdentifier"}],"kind":"symbol","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementCategoryName":{"type":"topic","navigatorTitle":[{"text":"kAudioObjectPropertyElementCategoryName","kind":"identifier"}],"role":"symbol","url":"/documentation/coreaudio/kaudioobjectpropertyelementcategoryname","title":"kAudioObjectPropertyElementCategoryName","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementCategoryName","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioObjectPropertyElementCategoryName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"kind":"symbol","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous":{"abstract":[],"url":"/documentation/coreaudio/1580747-anonymous","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous","type":"topic","role":"collectionGroup","kind":"article","title":"Anonymous"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous":{"kind":"article","title":"Anonymous","type":"topic","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous","url":"/documentation/coreaudio/1580726-anonymous","role":"collectionGroup"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous":{"abstract":[],"url":"/documentation/coreaudio/1580715-anonymous","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous","type":"topic","role":"collectionGroup","kind":"article","title":"Anonymous"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous":{"type":"topic","title":"Anonymous","kind":"article","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous","role":"collectionGroup","abstract":[],"url":"/documentation/coreaudio/1580723-anonymous"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580748-anonymous","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyBaseClass","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyClass","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementCategoryName","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementName","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementNumberName","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyFirmwareVersion","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyIdentify","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyManufacturer","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyModelName","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyName","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyOwnedObjects","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyOwner","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertySerialNumber"],"title":"Constants","anchor":"Constants"}],"op":"replace","path":"/topicSections"},{"value":[{"title":"Enumerations","generated":true,"identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous"],"anchor":"Enumerations"}],"op":"replace","path":"/seeAlsoSections"},{"value":"kAudioObjectPropertyFirmwareVersion","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyFirmwareVersion/title"},{"value":[{"text":"kAudioObjectPropertyFirmwareVersion","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyFirmwareVersion/fragments"},{"value":"kAudioObjectPropertyClass","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyClass/title"},{"value":[{"kind":"identifier","text":"kAudioObjectPropertyClass"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyClass/fragments"},{"value":"kAudioObjectPropertyOwner","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyOwner/title"},{"value":[{"text":"kAudioObjectPropertyOwner","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyOwner/fragments"},{"value":"kAudioObjectPropertyElementNumberName","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyElementNumberName/title"},{"value":[{"kind":"identifier","text":"kAudioObjectPropertyElementNumberName"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyElementNumberName/fragments"},{"value":"kAudioObjectPropertyElementName","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyElementName/title"},{"value":[{"text":"kAudioObjectPropertyElementName","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyElementName/fragments"},{"value":"kAudioObjectPropertyBaseClass","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyBaseClass/title"},{"value":[{"text":"kAudioObjectPropertyBaseClass","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyBaseClass/fragments"},{"value":"kAudioObjectPropertySerialNumber","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertySerialNumber/title"},{"value":[{"kind":"identifier","text":"kAudioObjectPropertySerialNumber"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertySerialNumber/fragments"},{"value":"kAudioObjectPropertyModelName","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyModelName/title"},{"value":[{"kind":"identifier","text":"kAudioObjectPropertyModelName"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyModelName/fragments"},{"value":"kAudioObjectPropertyName","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyName/title"},{"value":[{"text":"kAudioObjectPropertyName","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyName/fragments"},{"value":"kAudioObjectPropertyOwnedObjects","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyOwnedObjects/title"},{"value":[{"text":"kAudioObjectPropertyOwnedObjects","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyOwnedObjects/fragments"},{"value":"kAudioObjectPropertyIdentify","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyIdentify/title"},{"value":[{"kind":"identifier","text":"kAudioObjectPropertyIdentify"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyIdentify/fragments"},{"value":"kAudioObjectPropertyManufacturer","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyManufacturer/title"},{"value":[{"text":"kAudioObjectPropertyManufacturer","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyManufacturer/fragments"},{"value":"kAudioObjectPropertyElementCategoryName","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyElementCategoryName/title"},{"value":[{"text":"kAudioObjectPropertyElementCategoryName","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyElementCategoryName/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}