{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio",
        "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/1494512-anonymous"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Anonymous"
  },
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580715-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580719-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580720-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580722-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580723-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580726-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580731-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580736-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580737-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580740-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580741-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580746-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580747-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580748-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580749-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio Enumerations",
      "type": "topic",
      "url": "/documentation/coreaudio/core-audio-enumerations"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBooleanControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioBooleanControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioClassID",
          "text": "AudioClassID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBooleanControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioBooleanControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kAudioBooleanControlClassID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiobooleancontrolclassid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClipLightControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioClipLightControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioClassID",
          "text": "AudioClassID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClipLightControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioClipLightControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kAudioClipLightControlClassID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiocliplightcontrolclassid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioJackControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioJackControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioClassID",
          "text": "AudioClassID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioJackControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioJackControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kAudioJackControlClassID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiojackcontrolclassid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioLFEMuteControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioLFEMuteControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioClassID",
          "text": "AudioClassID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioLFEMuteControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLFEMuteControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kAudioLFEMuteControlClassID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiolfemutecontrolclassid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioListenbackControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioListenbackControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioClassID",
          "text": "AudioClassID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioListenbackControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioListenbackControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kAudioListenbackControlClassID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiolistenbackcontrolclassid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioMuteControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioMuteControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioClassID",
          "text": "AudioClassID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioMuteControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioMuteControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kAudioMuteControlClassID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiomutecontrolclassid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPhantomPowerControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioPhantomPowerControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioClassID",
          "text": "AudioClassID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPhantomPowerControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioPhantomPowerControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kAudioPhantomPowerControlClassID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiophantompowercontrolclassid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPhaseInvertControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioPhaseInvertControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioClassID",
          "text": "AudioClassID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPhaseInvertControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioPhaseInvertControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kAudioPhaseInvertControlClassID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiophaseinvertcontrolclassid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioSoloControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSoloControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioClassID",
          "text": "AudioClassID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioSoloControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSoloControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kAudioSoloControlClassID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiosolocontrolclassid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioTalkbackControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioTalkbackControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioClassID",
          "text": "AudioClassID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioTalkbackControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioTalkbackControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kAudioTalkbackControlClassID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiotalkbackcontrolclassid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBooleanControlClassID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClipLightControlClassID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioJackControlClassID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioLFEMuteControlClassID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioListenbackControlClassID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioMuteControlClassID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPhantomPowerControlClassID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPhaseInvertControlClassID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioSoloControlClassID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioTalkbackControlClassID"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBooleanControlClassID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClipLightControlClassID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioJackControlClassID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioLFEMuteControlClassID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioListenbackControlClassID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioMuteControlClassID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPhantomPowerControlClassID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPhaseInvertControlClassID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioSoloControlClassID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioTalkbackControlClassID"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioListenbackControlClassID/title",
          "value": "kAudioListenbackControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioListenbackControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioListenbackControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioPhantomPowerControlClassID/title",
          "value": "kAudioPhantomPowerControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioPhantomPowerControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioPhantomPowerControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioBooleanControlClassID/title",
          "value": "kAudioBooleanControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioBooleanControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioBooleanControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioMuteControlClassID/title",
          "value": "kAudioMuteControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioMuteControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioMuteControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioPhaseInvertControlClassID/title",
          "value": "kAudioPhaseInvertControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioPhaseInvertControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioPhaseInvertControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioClipLightControlClassID/title",
          "value": "kAudioClipLightControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioClipLightControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioClipLightControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioTalkbackControlClassID/title",
          "value": "kAudioTalkbackControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioTalkbackControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioTalkbackControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioLFEMuteControlClassID/title",
          "value": "kAudioLFEMuteControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioLFEMuteControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLFEMuteControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioSoloControlClassID/title",
          "value": "kAudioSoloControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioSoloControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSoloControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioJackControlClassID/title",
          "value": "kAudioJackControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioJackControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioJackControlClassID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/1494512-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/1494512-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
