{"identifier":{"url":"doc://com.apple.coreaudio/documentation/CoreAudio/1494531-anonymous","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coreaudio/documentation/CoreAudio","doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/coreaudio/1494531-anonymous"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/coreaudio/1494531-anonymous"]}],"topicSections":[{"anchor":"Constants","title":"Constants","identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePermissionsError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceUnsupportedFormatError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadDeviceError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadObjectError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadPropertySizeError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadStreamError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareIllegalOperationError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareNoError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareNotRunningError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnknownPropertyError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnspecifiedError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnsupportedOperationError"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"Core Audio"}],"roleHeading":"API Collection","role":"collectionGroup","title":"Anonymous"},"kind":"article","seeAlsoSections":[{"anchor":"Enumerations","title":"Enumerations","generated":true,"identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous"]}],"references":{"doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous":{"kind":"article","title":"Anonymous","type":"topic","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous","url":"/documentation/coreaudio/1580731-anonymous","role":"collectionGroup"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580746-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnknownPropertyError":{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnknownPropertyError","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwareUnknownPropertyError","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@OSStatus","text":"OSStatus","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"kAudioHardwareUnknownPropertyError","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"/documentation/coreaudio/kaudiohardwareunknownpropertyerror","title":"kAudioHardwareUnknownPropertyError"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580737-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareNotRunningError":{"abstract":[],"title":"kAudioHardwareNotRunningError","navigatorTitle":[{"text":"kAudioHardwareNotRunningError","kind":"identifier"}],"url":"/documentation/coreaudio/kaudiohardwarenotrunningerror","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwareNotRunningError","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@OSStatus","text":"OSStatus","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareNotRunningError"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous":{"abstract":[],"url":"/documentation/coreaudio/1580715-anonymous","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous","type":"topic","role":"collectionGroup","kind":"article","title":"Anonymous"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous":{"abstract":[],"url":"/documentation/coreaudio/1580747-anonymous","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous","type":"topic","role":"collectionGroup","kind":"article","title":"Anonymous"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadDeviceError":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwareBadDeviceError","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@OSStatus","text":"OSStatus","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"kAudioHardwareBadDeviceError","kind":"identifier"}],"kind":"symbol","url":"/documentation/coreaudio/kaudiohardwarebaddeviceerror","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadDeviceError","title":"kAudioHardwareBadDeviceError","abstract":[],"role":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadStreamError":{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadStreamError","abstract":[],"kind":"symbol","title":"kAudioHardwareBadStreamError","url":"/documentation/coreaudio/kaudiohardwarebadstreamerror","navigatorTitle":[{"text":"kAudioHardwareBadStreamError","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwareBadStreamError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"OSStatus","kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus"}],"type":"topic","role":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadObjectError":{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadObjectError","abstract":[],"kind":"symbol","title":"kAudioHardwareBadObjectError","url":"/documentation/coreaudio/kaudiohardwarebadobjecterror","navigatorTitle":[{"kind":"identifier","text":"kAudioHardwareBadObjectError"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioHardwareBadObjectError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OSStatus","preciseIdentifier":"c:@T@OSStatus"}],"type":"topic","role":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations":{"kind":"article","title":"Core Audio Enumerations","type":"topic","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations","url":"/documentation/coreaudio/core-audio-enumerations","role":"collectionGroup"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580740-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580748-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous":{"type":"topic","title":"Anonymous","kind":"article","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous","role":"collectionGroup","abstract":[],"url":"/documentation/coreaudio/1580723-anonymous"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePermissionsError":{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePermissionsError","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioDevicePermissionsError","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@OSStatus","text":"OSStatus","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"kAudioDevicePermissionsError","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"/documentation/coreaudio/kaudiodevicepermissionserror","title":"kAudioDevicePermissionsError"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580749-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceUnsupportedFormatError":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioDeviceUnsupportedFormatError"},{"text":": ","kind":"text"},{"text":"OSStatus","kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus"}],"type":"topic","navigatorTitle":[{"text":"kAudioDeviceUnsupportedFormatError","kind":"identifier"}],"kind":"symbol","url":"/documentation/coreaudio/kaudiodeviceunsupportedformaterror","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceUnsupportedFormatError","title":"kAudioDeviceUnsupportedFormatError","abstract":[],"role":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadPropertySizeError":{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadPropertySizeError","abstract":[],"kind":"symbol","title":"kAudioHardwareBadPropertySizeError","url":"/documentation/coreaudio/kaudiohardwarebadpropertysizeerror","navigatorTitle":[{"text":"kAudioHardwareBadPropertySizeError","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwareBadPropertySizeError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"OSStatus","kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus"}],"type":"topic","role":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous":{"kind":"article","title":"Anonymous","type":"topic","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous","url":"/documentation/coreaudio/1580726-anonymous","role":"collectionGroup"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","role":"overview","kind":"technologies"},"doc://com.apple.coreaudio/documentation/CoreAudio":{"kind":"symbol","title":"Core Audio","type":"topic","abstract":[{"type":"text","text":"Use the Core Audio framework to interact with device’s audio hardware."}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio","url":"/documentation/coreaudio","role":"collection"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnspecifiedError":{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnspecifiedError","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwareUnspecifiedError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"OSStatus","kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus"}],"navigatorTitle":[{"text":"kAudioHardwareUnspecifiedError","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"/documentation/coreaudio/kaudiohardwareunspecifiederror","title":"kAudioHardwareUnspecifiedError"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnsupportedOperationError":{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnsupportedOperationError","role":"symbol","url":"/documentation/coreaudio/kaudiohardwareunsupportedoperationerror","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioHardwareUnsupportedOperationError"},{"text":": ","kind":"text"},{"text":"OSStatus","preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier"}],"abstract":[],"title":"kAudioHardwareUnsupportedOperationError","kind":"symbol","navigatorTitle":[{"text":"kAudioHardwareUnsupportedOperationError","kind":"identifier"}]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580719-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareIllegalOperationError":{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareIllegalOperationError","role":"symbol","url":"/documentation/coreaudio/kaudiohardwareillegaloperationerror","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwareIllegalOperationError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"OSStatus","kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus"}],"abstract":[],"title":"kAudioHardwareIllegalOperationError","kind":"symbol","navigatorTitle":[{"text":"kAudioHardwareIllegalOperationError","kind":"identifier"}]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous":{"kind":"article","title":"Anonymous","type":"topic","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous","url":"/documentation/coreaudio/1580722-anonymous","role":"collectionGroup"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580720-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareNoError":{"abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwareNoError","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@OSStatus","text":"OSStatus","kind":"typeIdentifier"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareNoError","kind":"symbol","title":"kAudioHardwareNoError","url":"/documentation/coreaudio/kaudiohardwarenoerror","type":"topic","navigatorTitle":[{"text":"kAudioHardwareNoError","kind":"identifier"}]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous":{"kind":"article","title":"Anonymous","type":"topic","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous","url":"/documentation/coreaudio/1580736-anonymous","role":"collectionGroup"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580741-anonymous","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/topicSections","value":[{"anchor":"Constants","title":"Constants","identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePermissionsError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceUnsupportedFormatError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadDeviceError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadObjectError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadPropertySizeError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadStreamError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareIllegalOperationError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareNoError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareNotRunningError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnknownPropertyError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnspecifiedError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnsupportedOperationError"]}]},{"op":"replace","path":"/seeAlsoSections","value":[{"anchor":"Enumerations","identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous"],"generated":true,"title":"Enumerations"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareUnknownPropertyError/title","value":"kAudioHardwareUnknownPropertyError"},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareUnknownPropertyError/fragments","value":[{"text":"kAudioHardwareUnknownPropertyError","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareNotRunningError/title","value":"kAudioHardwareNotRunningError"},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareNotRunningError/fragments","value":[{"kind":"identifier","text":"kAudioHardwareNotRunningError"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareBadDeviceError/title","value":"kAudioHardwareBadDeviceError"},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareBadDeviceError/fragments","value":[{"text":"kAudioHardwareBadDeviceError","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareBadStreamError/title","value":"kAudioHardwareBadStreamError"},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareBadStreamError/fragments","value":[{"text":"kAudioHardwareBadStreamError","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareBadObjectError/title","value":"kAudioHardwareBadObjectError"},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareBadObjectError/fragments","value":[{"kind":"identifier","text":"kAudioHardwareBadObjectError"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePermissionsError/title","value":"kAudioDevicePermissionsError"},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePermissionsError/fragments","value":[{"text":"kAudioDevicePermissionsError","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceUnsupportedFormatError/title","value":"kAudioDeviceUnsupportedFormatError"},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceUnsupportedFormatError/fragments","value":[{"text":"kAudioDeviceUnsupportedFormatError","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareBadPropertySizeError/title","value":"kAudioHardwareBadPropertySizeError"},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareBadPropertySizeError/fragments","value":[{"kind":"identifier","text":"kAudioHardwareBadPropertySizeError"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareUnspecifiedError/title","value":"kAudioHardwareUnspecifiedError"},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareUnspecifiedError/fragments","value":[{"kind":"identifier","text":"kAudioHardwareUnspecifiedError"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareUnsupportedOperationError/title","value":"kAudioHardwareUnsupportedOperationError"},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareUnsupportedOperationError/fragments","value":[{"text":"kAudioHardwareUnsupportedOperationError","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareIllegalOperationError/title","value":"kAudioHardwareIllegalOperationError"},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareIllegalOperationError/fragments","value":[{"text":"kAudioHardwareIllegalOperationError","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareNoError/title","value":"kAudioHardwareNoError"},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareNoError/fragments","value":[{"text":"kAudioHardwareNoError","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}