{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coreaudio/documentation/CoreAudio","doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.coreaudio/documentation/CoreAudio/1545886-anonymous","interfaceLanguage":"swift"},"sections":[],"metadata":{"roleHeading":"API Collection","modules":[{"name":"Core Audio"}],"title":"Anonymous","role":"collectionGroup"},"topicSections":[{"title":"Constants","identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyBoxList","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultInputDevice","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultOutputDevice","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultSystemOutputDevice","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDevices","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyHogModeIsAllowed","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyIsInitingOrExiting","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyMixStereoToMono","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPlugInList","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPowerHint","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsAudible","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsMaster","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyServiceRestarted","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertySleepingIsAllowed","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateBundleIDToPlugIn","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateBundleIDToTransportManager","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateUIDToBox","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateUIDToDevice","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTransportManagerList","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyUnloadingIsAllowed","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyUserIDChanged","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyUserSessionIsActiveOrHeadless","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyClockDeviceList","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateUIDToClockDevice"],"anchor":"Constants"}],"variants":[{"paths":["/documentation/coreaudio/1545886-anonymous"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/coreaudio/1545886-anonymous"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"title":"Enumerations","identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous"],"anchor":"Enumerations","generated":true}],"kind":"article","references":{"doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous":{"type":"topic","title":"Anonymous","kind":"article","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous","role":"collectionGroup","abstract":[],"url":"/documentation/coreaudio/1580723-anonymous"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateBundleIDToPlugIn":{"navigatorTitle":[{"text":"kAudioHardwarePropertyTranslateBundleIDToPlugIn","kind":"identifier"}],"title":"kAudioHardwarePropertyTranslateBundleIDToPlugIn","kind":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateBundleIDToPlugIn","url":"/documentation/coreaudio/kaudiohardwarepropertytranslatebundleidtoplugin","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyTranslateBundleIDToPlugIn","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"type":"topic","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyServiceRestarted":{"kind":"symbol","role":"symbol","abstract":[],"title":"kAudioHardwarePropertyServiceRestarted","url":"/documentation/coreaudio/kaudiohardwarepropertyservicerestarted","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyServiceRestarted","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyServiceRestarted","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyServiceRestarted"}]},"doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations":{"kind":"article","title":"Core Audio Enumerations","type":"topic","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations","url":"/documentation/coreaudio/core-audio-enumerations","role":"collectionGroup"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultOutputDevice":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyDefaultOutputDevice","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector","kind":"typeIdentifier"}],"abstract":[],"title":"kAudioHardwarePropertyDefaultOutputDevice","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyDefaultOutputDevice"}],"url":"/documentation/coreaudio/kaudiohardwarepropertydefaultoutputdevice","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultOutputDevice","role":"symbol","type":"topic"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsMaster":{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsMaster","url":"/documentation/coreaudio/kaudiohardwarepropertyprocessismaster","deprecated":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyProcessIsMaster","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@AudioObjectPropertySelector","kind":"typeIdentifier","text":"AudioObjectPropertySelector"}],"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyProcessIsMaster"}],"kind":"symbol","type":"topic","title":"kAudioHardwarePropertyProcessIsMaster"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580746-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio":{"kind":"symbol","title":"Core Audio","type":"topic","abstract":[{"type":"text","text":"Use the Core Audio framework to interact with device’s audio hardware."}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio","url":"/documentation/coreaudio","role":"collection"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultSystemOutputDevice":{"title":"kAudioHardwarePropertyDefaultSystemOutputDevice","url":"/documentation/coreaudio/kaudiohardwarepropertydefaultsystemoutputdevice","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyDefaultSystemOutputDevice","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyDefaultSystemOutputDevice"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultSystemOutputDevice","type":"topic"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateUIDToDevice":{"kind":"symbol","title":"kAudioHardwarePropertyTranslateUIDToDevice","url":"/documentation/coreaudio/kaudiohardwarepropertytranslateuidtodevice","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateUIDToDevice","navigatorTitle":[{"text":"kAudioHardwarePropertyTranslateUIDToDevice","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioHardwarePropertyTranslateUIDToDevice"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector","text":"AudioObjectPropertySelector"}]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyUserIDChanged":{"navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyUserIDChanged"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyUserIDChanged","abstract":[],"title":"kAudioHardwarePropertyUserIDChanged","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioHardwarePropertyUserIDChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector","text":"AudioObjectPropertySelector"}],"url":"/documentation/coreaudio/kaudiohardwarepropertyuseridchanged","kind":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsAudible":{"type":"topic","navigatorTitle":[{"text":"kAudioHardwarePropertyProcessIsAudible","kind":"identifier"}],"abstract":[],"title":"kAudioHardwarePropertyProcessIsAudible","url":"/documentation/coreaudio/kaudiohardwarepropertyprocessisaudible","role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsAudible","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyProcessIsAudible","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyUnloadingIsAllowed":{"kind":"symbol","title":"kAudioHardwarePropertyUnloadingIsAllowed","url":"/documentation/coreaudio/kaudiohardwarepropertyunloadingisallowed","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyUnloadingIsAllowed","navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyUnloadingIsAllowed"}],"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioHardwarePropertyUnloadingIsAllowed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector","text":"AudioObjectPropertySelector"}]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580719-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous":{"abstract":[],"url":"/documentation/coreaudio/1580715-anonymous","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous","type":"topic","role":"collectionGroup","kind":"article","title":"Anonymous"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyBoxList":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyBoxList","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector","kind":"typeIdentifier"}],"abstract":[],"title":"kAudioHardwarePropertyBoxList","kind":"symbol","navigatorTitle":[{"text":"kAudioHardwarePropertyBoxList","kind":"identifier"}],"url":"/documentation/coreaudio/kaudiohardwarepropertyboxlist","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyBoxList","role":"symbol","type":"topic"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyHogModeIsAllowed":{"navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyHogModeIsAllowed"}],"title":"kAudioHardwarePropertyHogModeIsAllowed","kind":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyHogModeIsAllowed","url":"/documentation/coreaudio/kaudiohardwarepropertyhogmodeisallowed","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyHogModeIsAllowed","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"type":"topic","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateUIDToClockDevice":{"navigatorTitle":[{"text":"kAudioHardwarePropertyTranslateUIDToClockDevice","kind":"identifier"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateUIDToClockDevice","abstract":[],"title":"kAudioHardwarePropertyTranslateUIDToClockDevice","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioHardwarePropertyTranslateUIDToClockDevice"},{"kind":"text","text":": "},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"url":"/documentation/coreaudio/kaudiohardwarepropertytranslateuidtoclockdevice","kind":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertySleepingIsAllowed":{"title":"kAudioHardwarePropertySleepingIsAllowed","url":"/documentation/coreaudio/kaudiohardwarepropertysleepingisallowed","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertySleepingIsAllowed","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AudioObjectPropertySelector","text":"AudioObjectPropertySelector","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"kAudioHardwarePropertySleepingIsAllowed","kind":"identifier"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertySleepingIsAllowed","type":"topic"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyUserSessionIsActiveOrHeadless":{"title":"kAudioHardwarePropertyUserSessionIsActiveOrHeadless","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyUserSessionIsActiveOrHeadless"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kAudioHardwarePropertyUserSessionIsActiveOrHeadless"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector","text":"AudioObjectPropertySelector"}],"abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyUserSessionIsActiveOrHeadless","kind":"symbol","url":"/documentation/coreaudio/kaudiohardwarepropertyusersessionisactiveorheadless"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580741-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous":{"kind":"article","title":"Anonymous","type":"topic","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous","url":"/documentation/coreaudio/1580726-anonymous","role":"collectionGroup"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous":{"kind":"article","title":"Anonymous","type":"topic","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous","url":"/documentation/coreaudio/1580736-anonymous","role":"collectionGroup"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyIsInitingOrExiting":{"navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyIsInitingOrExiting"}],"title":"kAudioHardwarePropertyIsInitingOrExiting","kind":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyIsInitingOrExiting","url":"/documentation/coreaudio/kaudiohardwarepropertyisinitingorexiting","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyIsInitingOrExiting","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"type":"topic","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous":{"abstract":[],"url":"/documentation/coreaudio/1580747-anonymous","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous","type":"topic","role":"collectionGroup","kind":"article","title":"Anonymous"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580720-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateUIDToBox":{"kind":"symbol","title":"kAudioHardwarePropertyTranslateUIDToBox","url":"/documentation/coreaudio/kaudiohardwarepropertytranslateuidtobox","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateUIDToBox","navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyTranslateUIDToBox"}],"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kAudioHardwarePropertyTranslateUIDToBox"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector","text":"AudioObjectPropertySelector"}]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580737-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyMixStereoToMono":{"navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyMixStereoToMono"}],"title":"kAudioHardwarePropertyMixStereoToMono","kind":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyMixStereoToMono","url":"/documentation/coreaudio/kaudiohardwarepropertymixstereotomono","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyMixStereoToMono","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"type":"topic","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous":{"kind":"article","title":"Anonymous","type":"topic","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous","url":"/documentation/coreaudio/1580731-anonymous","role":"collectionGroup"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultInputDevice":{"type":"topic","url":"/documentation/coreaudio/kaudiohardwarepropertydefaultinputdevice","role":"symbol","title":"kAudioHardwarePropertyDefaultInputDevice","kind":"symbol","navigatorTitle":[{"text":"kAudioHardwarePropertyDefaultInputDevice","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyDefaultInputDevice","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultInputDevice","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580748-anonymous","abstract":[]},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","role":"overview","kind":"technologies"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous":{"kind":"article","title":"Anonymous","type":"topic","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous","url":"/documentation/coreaudio/1580722-anonymous","role":"collectionGroup"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580740-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTransportManagerList":{"navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyTransportManagerList"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTransportManagerList","abstract":[],"title":"kAudioHardwarePropertyTransportManagerList","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kAudioHardwarePropertyTransportManagerList"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector","text":"AudioObjectPropertySelector"}],"url":"/documentation/coreaudio/kaudiohardwarepropertytransportmanagerlist","kind":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyClockDeviceList":{"kind":"symbol","title":"kAudioHardwarePropertyClockDeviceList","url":"/documentation/coreaudio/kaudiohardwarepropertyclockdevicelist","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyClockDeviceList","navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyClockDeviceList"}],"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioHardwarePropertyClockDeviceList"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector","text":"AudioObjectPropertySelector"}]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPowerHint":{"kind":"symbol","type":"topic","url":"/documentation/coreaudio/kaudiohardwarepropertypowerhint","navigatorTitle":[{"text":"kAudioHardwarePropertyPowerHint","kind":"identifier"}],"title":"kAudioHardwarePropertyPowerHint","abstract":[],"role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPowerHint","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyPowerHint","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AudioObjectPropertySelector","text":"AudioObjectPropertySelector","kind":"typeIdentifier"}]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPlugInList":{"kind":"symbol","type":"topic","url":"/documentation/coreaudio/kaudiohardwarepropertypluginlist","navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyPlugInList"}],"title":"kAudioHardwarePropertyPlugInList","abstract":[],"role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPlugInList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioHardwarePropertyPlugInList"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDevices":{"type":"topic","url":"/documentation/coreaudio/kaudiohardwarepropertydevices","role":"symbol","title":"kAudioHardwarePropertyDevices","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyDevices"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioHardwarePropertyDevices"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDevices","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateBundleIDToTransportManager":{"kind":"symbol","role":"symbol","abstract":[],"title":"kAudioHardwarePropertyTranslateBundleIDToTransportManager","url":"/documentation/coreaudio/kaudiohardwarepropertytranslatebundleidtotransportmanager","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyTranslateBundleIDToTransportManager","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AudioObjectPropertySelector","text":"AudioObjectPropertySelector","kind":"typeIdentifier"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateBundleIDToTransportManager","type":"topic","navigatorTitle":[{"text":"kAudioHardwarePropertyTranslateBundleIDToTransportManager","kind":"identifier"}]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580749-anonymous","abstract":[]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/topicSections","value":[{"identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyBoxList","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultInputDevice","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultOutputDevice","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultSystemOutputDevice","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDevices","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyHogModeIsAllowed","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyIsInitingOrExiting","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyMixStereoToMono","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPlugInList","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPowerHint","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsAudible","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsMaster","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyServiceRestarted","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertySleepingIsAllowed","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateBundleIDToPlugIn","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateBundleIDToTransportManager","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateUIDToBox","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateUIDToDevice","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTransportManagerList","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyUnloadingIsAllowed","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyUserIDChanged","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyUserSessionIsActiveOrHeadless","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyClockDeviceList","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateUIDToClockDevice"],"title":"Constants","anchor":"Constants"}],"op":"replace"},{"path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous"],"generated":true,"anchor":"Enumerations","title":"Enumerations"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyTranslateBundleIDToPlugIn/title","value":"kAudioHardwarePropertyTranslateBundleIDToPlugIn","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyTranslateBundleIDToPlugIn/fragments","value":[{"kind":"identifier","text":"kAudioHardwarePropertyTranslateBundleIDToPlugIn"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyServiceRestarted/title","value":"kAudioHardwarePropertyServiceRestarted","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyServiceRestarted/fragments","value":[{"text":"kAudioHardwarePropertyServiceRestarted","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDefaultOutputDevice/title","value":"kAudioHardwarePropertyDefaultOutputDevice","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDefaultOutputDevice/fragments","value":[{"text":"kAudioHardwarePropertyDefaultOutputDevice","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyProcessIsMaster/title","value":"kAudioHardwarePropertyProcessIsMaster","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyProcessIsMaster/fragments","value":[{"kind":"identifier","text":"kAudioHardwarePropertyProcessIsMaster"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDefaultSystemOutputDevice/title","value":"kAudioHardwarePropertyDefaultSystemOutputDevice","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDefaultSystemOutputDevice/fragments","value":[{"kind":"identifier","text":"kAudioHardwarePropertyDefaultSystemOutputDevice"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyTranslateUIDToDevice/title","value":"kAudioHardwarePropertyTranslateUIDToDevice","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyTranslateUIDToDevice/fragments","value":[{"text":"kAudioHardwarePropertyTranslateUIDToDevice","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyUserIDChanged/title","value":"kAudioHardwarePropertyUserIDChanged","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyUserIDChanged/fragments","value":[{"kind":"identifier","text":"kAudioHardwarePropertyUserIDChanged"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyProcessIsAudible/title","value":"kAudioHardwarePropertyProcessIsAudible","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyProcessIsAudible/fragments","value":[{"text":"kAudioHardwarePropertyProcessIsAudible","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyUnloadingIsAllowed/title","value":"kAudioHardwarePropertyUnloadingIsAllowed","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyUnloadingIsAllowed/fragments","value":[{"text":"kAudioHardwarePropertyUnloadingIsAllowed","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyBoxList/title","value":"kAudioHardwarePropertyBoxList","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyBoxList/fragments","value":[{"kind":"identifier","text":"kAudioHardwarePropertyBoxList"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyHogModeIsAllowed/title","value":"kAudioHardwarePropertyHogModeIsAllowed","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyHogModeIsAllowed/fragments","value":[{"kind":"identifier","text":"kAudioHardwarePropertyHogModeIsAllowed"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyTranslateUIDToClockDevice/title","value":"kAudioHardwarePropertyTranslateUIDToClockDevice","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyTranslateUIDToClockDevice/fragments","value":[{"text":"kAudioHardwarePropertyTranslateUIDToClockDevice","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertySleepingIsAllowed/title","value":"kAudioHardwarePropertySleepingIsAllowed","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertySleepingIsAllowed/fragments","value":[{"text":"kAudioHardwarePropertySleepingIsAllowed","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyUserSessionIsActiveOrHeadless/title","value":"kAudioHardwarePropertyUserSessionIsActiveOrHeadless","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyUserSessionIsActiveOrHeadless/fragments","value":[{"text":"kAudioHardwarePropertyUserSessionIsActiveOrHeadless","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyIsInitingOrExiting/title","value":"kAudioHardwarePropertyIsInitingOrExiting","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyIsInitingOrExiting/fragments","value":[{"kind":"identifier","text":"kAudioHardwarePropertyIsInitingOrExiting"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyTranslateUIDToBox/title","value":"kAudioHardwarePropertyTranslateUIDToBox","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyTranslateUIDToBox/fragments","value":[{"kind":"identifier","text":"kAudioHardwarePropertyTranslateUIDToBox"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyMixStereoToMono/title","value":"kAudioHardwarePropertyMixStereoToMono","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyMixStereoToMono/fragments","value":[{"text":"kAudioHardwarePropertyMixStereoToMono","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDefaultInputDevice/title","value":"kAudioHardwarePropertyDefaultInputDevice","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDefaultInputDevice/fragments","value":[{"text":"kAudioHardwarePropertyDefaultInputDevice","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyTransportManagerList/title","value":"kAudioHardwarePropertyTransportManagerList","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyTransportManagerList/fragments","value":[{"kind":"identifier","text":"kAudioHardwarePropertyTransportManagerList"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyClockDeviceList/title","value":"kAudioHardwarePropertyClockDeviceList","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyClockDeviceList/fragments","value":[{"text":"kAudioHardwarePropertyClockDeviceList","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyPowerHint/title","value":"kAudioHardwarePropertyPowerHint","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyPowerHint/fragments","value":[{"kind":"identifier","text":"kAudioHardwarePropertyPowerHint"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyPlugInList/title","value":"kAudioHardwarePropertyPlugInList","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyPlugInList/fragments","value":[{"text":"kAudioHardwarePropertyPlugInList","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDevices/title","value":"kAudioHardwarePropertyDevices","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDevices/fragments","value":[{"kind":"identifier","text":"kAudioHardwarePropertyDevices"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyTranslateBundleIDToTransportManager/title","value":"kAudioHardwarePropertyTranslateBundleIDToTransportManager","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyTranslateBundleIDToTransportManager/fragments","value":[{"kind":"identifier","text":"kAudioHardwarePropertyTranslateBundleIDToTransportManager"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}