{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio",
        "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Anonymous"
  },
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580715-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580719-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580720-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580722-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580723-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580726-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580736-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580737-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580738-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580738-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580738-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580740-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580741-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580746-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580747-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580748-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580749-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio Enumerations",
      "type": "topic",
      "url": "/documentation/coreaudio/core-audio-enumerations"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyBufferSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyBufferSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyBufferSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyBufferSize"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyBufferSize",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertybuffersize"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyBufferSizeRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyBufferSizeRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyBufferSizeRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyBufferSizeRange"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyBufferSizeRange",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertybuffersizerange"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelCategoryName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelCategoryName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelCategoryName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelCategoryName"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyChannelCategoryName",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertychannelcategoryname"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelCategoryNameCFString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelCategoryNameCFString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelCategoryNameCFString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelCategoryNameCFString"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyChannelCategoryNameCFString",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertychannelcategorynamecfstring"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelName"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyChannelName",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertychannelname"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNameCFString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelNameCFString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNameCFString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelNameCFString"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyChannelNameCFString",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertychannelnamecfstring"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNominalLineLevelNameForID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelNominalLineLevelNameForID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNominalLineLevelNameForID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelNominalLineLevelNameForID"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyChannelNominalLineLevelNameForID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertychannelnominallinelevelnameforid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNumberName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelNumberName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNumberName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelNumberName"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyChannelNumberName",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertychannelnumbername"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNumberNameCFString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelNumberNameCFString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNumberNameCFString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelNumberNameCFString"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyChannelNumberNameCFString",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertychannelnumbernamecfstring"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockSourceNameForID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyClockSourceNameForID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockSourceNameForID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyClockSourceNameForID"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyClockSourceNameForID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyclocksourcenameforid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDataSourceNameForID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDataSourceNameForID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDataSourceNameForID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDataSourceNameForID"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyDataSourceNameForID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertydatasourcenameforid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceManufacturer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceManufacturer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceManufacturer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceManufacturer"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyDeviceManufacturer",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertydevicemanufacturer"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceManufacturerCFString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceManufacturerCFString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceManufacturerCFString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceManufacturerCFString"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyDeviceManufacturerCFString",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertydevicemanufacturercfstring"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceName"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyDeviceName",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertydevicename"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceNameCFString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceNameCFString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceNameCFString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceNameCFString"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyDeviceNameCFString",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertydevicenamecfstring"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyHighPassFilterSettingNameForID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyHighPassFilterSettingNameForID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyHighPassFilterSettingNameForID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyHighPassFilterSettingNameForID"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyHighPassFilterSettingNameForID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyhighpassfiltersettingnameforid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyPlayThruDestinationNameForID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyPlayThruDestinationNameForID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyPlayThruDestinationNameForID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyPlayThruDestinationNameForID"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyPlayThruDestinationNameForID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyplaythrudestinationnameforid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyRegisterBufferList": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyRegisterBufferList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyRegisterBufferList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyRegisterBufferList"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyRegisterBufferList",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyregisterbufferlist"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyStreamFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyStreamFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyStreamFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyStreamFormat"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyStreamFormat",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertystreamformat"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyStreamFormatMatch": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyStreamFormatMatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyStreamFormatMatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyStreamFormatMatch"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyStreamFormatMatch",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertystreamformatmatch"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyStreamFormatSupported": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyStreamFormatSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyStreamFormatSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyStreamFormatSupported"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyStreamFormatSupported",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertystreamformatsupported"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyStreamFormats": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyStreamFormats"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyStreamFormats",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyStreamFormats"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyStreamFormats",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertystreamformats"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertySupportsMixing": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertySupportsMixing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertySupportsMixing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertySupportsMixing"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertySupportsMixing",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertysupportsmixing"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580738-anonymous"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyBufferSize",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyBufferSizeRange",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelCategoryName",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelCategoryNameCFString",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelName",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNameCFString",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNominalLineLevelNameForID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNumberName",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNumberNameCFString",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockSourceNameForID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDataSourceNameForID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceManufacturer",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceManufacturerCFString",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceName",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceNameCFString",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyHighPassFilterSettingNameForID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyPlayThruDestinationNameForID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyRegisterBufferList",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyStreamFormat",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyStreamFormatMatch",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyStreamFormatSupported",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyStreamFormats",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertySupportsMixing"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyBufferSize",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyBufferSizeRange",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelCategoryName",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelCategoryNameCFString",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelName",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNameCFString",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNominalLineLevelNameForID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNumberName",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNumberNameCFString",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockSourceNameForID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDataSourceNameForID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceManufacturer",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceManufacturerCFString",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceName",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceNameCFString",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyHighPassFilterSettingNameForID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyPlayThruDestinationNameForID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyRegisterBufferList",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyStreamFormat",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyStreamFormatMatch",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyStreamFormatSupported",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyStreamFormats",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertySupportsMixing"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580738-anonymous"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyPlayThruDestinationNameForID/title",
          "value": "kAudioDevicePropertyPlayThruDestinationNameForID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyPlayThruDestinationNameForID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyPlayThruDestinationNameForID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyStreamFormats/title",
          "value": "kAudioDevicePropertyStreamFormats"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyStreamFormats/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyStreamFormats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyStreamFormatSupported/title",
          "value": "kAudioDevicePropertyStreamFormatSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyStreamFormatSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyStreamFormatSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyClockSourceNameForID/title",
          "value": "kAudioDevicePropertyClockSourceNameForID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyClockSourceNameForID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyClockSourceNameForID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertySupportsMixing/title",
          "value": "kAudioDevicePropertySupportsMixing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertySupportsMixing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertySupportsMixing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceName/title",
          "value": "kAudioDevicePropertyDeviceName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyDeviceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceManufacturerCFString/title",
          "value": "kAudioDevicePropertyDeviceManufacturerCFString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceManufacturerCFString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyDeviceManufacturerCFString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyStreamFormatMatch/title",
          "value": "kAudioDevicePropertyStreamFormatMatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyStreamFormatMatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyStreamFormatMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelNumberName/title",
          "value": "kAudioDevicePropertyChannelNumberName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelNumberName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyChannelNumberName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyStreamFormat/title",
          "value": "kAudioDevicePropertyStreamFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyStreamFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyStreamFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelNominalLineLevelNameForID/title",
          "value": "kAudioDevicePropertyChannelNominalLineLevelNameForID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelNominalLineLevelNameForID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyChannelNominalLineLevelNameForID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelCategoryName/title",
          "value": "kAudioDevicePropertyChannelCategoryName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelCategoryName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyChannelCategoryName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceNameCFString/title",
          "value": "kAudioDevicePropertyDeviceNameCFString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceNameCFString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyDeviceNameCFString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelNumberNameCFString/title",
          "value": "kAudioDevicePropertyChannelNumberNameCFString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelNumberNameCFString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyChannelNumberNameCFString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyBufferSizeRange/title",
          "value": "kAudioDevicePropertyBufferSizeRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyBufferSizeRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyBufferSizeRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelNameCFString/title",
          "value": "kAudioDevicePropertyChannelNameCFString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelNameCFString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyChannelNameCFString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyRegisterBufferList/title",
          "value": "kAudioDevicePropertyRegisterBufferList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyRegisterBufferList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyRegisterBufferList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyHighPassFilterSettingNameForID/title",
          "value": "kAudioDevicePropertyHighPassFilterSettingNameForID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyHighPassFilterSettingNameForID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyHighPassFilterSettingNameForID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDataSourceNameForID/title",
          "value": "kAudioDevicePropertyDataSourceNameForID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDataSourceNameForID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyDataSourceNameForID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelCategoryNameCFString/title",
          "value": "kAudioDevicePropertyChannelCategoryNameCFString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelCategoryNameCFString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyChannelCategoryNameCFString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelName/title",
          "value": "kAudioDevicePropertyChannelName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyChannelName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceManufacturer/title",
          "value": "kAudioDevicePropertyDeviceManufacturer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceManufacturer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyDeviceManufacturer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyBufferSize/title",
          "value": "kAudioDevicePropertyBufferSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyBufferSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyBufferSize"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/1580731-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/1580731-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
