{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coreaudio/documentation/CoreAudio","doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous"},"metadata":{"role":"collectionGroup","title":"Anonymous","modules":[{"name":"Core Audio"}],"roleHeading":"API Collection"},"kind":"article","schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"anchor":"Constants","title":"Constants","identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDriverShouldOwniSub","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyPlayThruVolumeDecibelsToScalarTransferFunction","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertySubVolumeDecibelsToScalarTransferFunction","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyVolumeDecibelsToScalarTransferFunction"]}],"seeAlsoSections":[{"anchor":"Enumerations","title":"Enumerations","generated":true,"identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580738-anonymous"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/coreaudio/1580715-anonymous"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/coreaudio/1580715-anonymous"]}],"references":{"doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous":{"abstract":[],"url":"/documentation/coreaudio/1580747-anonymous","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous","type":"topic","role":"collectionGroup","kind":"article","title":"Anonymous"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580746-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580737-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580738-anonymous":{"url":"/documentation/coreaudio/1580738-anonymous","kind":"article","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580738-anonymous","title":"Anonymous","role":"collectionGroup","type":"topic"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580740-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580720-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580741-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous":{"kind":"article","title":"Anonymous","type":"topic","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous","url":"/documentation/coreaudio/1580722-anonymous","role":"collectionGroup"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyVolumeDecibelsToScalarTransferFunction":{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyVolumeDecibelsToScalarTransferFunction","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioDevicePropertyVolumeDecibelsToScalarTransferFunction"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@AudioObjectPropertySelector","kind":"typeIdentifier","text":"AudioObjectPropertySelector"}],"url":"/documentation/coreaudio/kaudiodevicepropertyvolumedecibelstoscalartransferfunction","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"kAudioDevicePropertyVolumeDecibelsToScalarTransferFunction"}],"title":"kAudioDevicePropertyVolumeDecibelsToScalarTransferFunction","role":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous":{"kind":"article","title":"Anonymous","type":"topic","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous","url":"/documentation/coreaudio/1580731-anonymous","role":"collectionGroup"},"doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations":{"kind":"article","title":"Core Audio Enumerations","type":"topic","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations","url":"/documentation/coreaudio/core-audio-enumerations","role":"collectionGroup"},"doc://com.apple.coreaudio/documentation/CoreAudio":{"kind":"symbol","title":"Core Audio","type":"topic","abstract":[{"type":"text","text":"Use the Core Audio framework to interact with device’s audio hardware."}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio","url":"/documentation/coreaudio","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","role":"overview","kind":"technologies"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580719-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDriverShouldOwniSub":{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDriverShouldOwniSub","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioDevicePropertyDriverShouldOwniSub"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@AudioObjectPropertySelector","kind":"typeIdentifier","text":"AudioObjectPropertySelector"}],"url":"/documentation/coreaudio/kaudiodevicepropertydrivershouldownisub","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"kAudioDevicePropertyDriverShouldOwniSub"}],"title":"kAudioDevicePropertyDriverShouldOwniSub","role":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580748-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous":{"kind":"article","title":"Anonymous","type":"topic","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous","url":"/documentation/coreaudio/1580726-anonymous","role":"collectionGroup"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyPlayThruVolumeDecibelsToScalarTransferFunction":{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyPlayThruVolumeDecibelsToScalarTransferFunction","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioDevicePropertyPlayThruVolumeDecibelsToScalarTransferFunction"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@AudioObjectPropertySelector","kind":"typeIdentifier","text":"AudioObjectPropertySelector"}],"url":"/documentation/coreaudio/kaudiodevicepropertyplaythruvolumedecibelstoscalartransferfunction","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"kAudioDevicePropertyPlayThruVolumeDecibelsToScalarTransferFunction"}],"title":"kAudioDevicePropertyPlayThruVolumeDecibelsToScalarTransferFunction","role":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous":{"type":"topic","title":"Anonymous","kind":"article","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous","role":"collectionGroup","abstract":[],"url":"/documentation/coreaudio/1580723-anonymous"},"doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous":{"title":"Anonymous","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous","kind":"article","role":"collectionGroup","url":"/documentation/coreaudio/1580749-anonymous","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous":{"kind":"article","title":"Anonymous","type":"topic","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous","url":"/documentation/coreaudio/1580736-anonymous","role":"collectionGroup"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertySubVolumeDecibelsToScalarTransferFunction":{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertySubVolumeDecibelsToScalarTransferFunction","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioDevicePropertySubVolumeDecibelsToScalarTransferFunction"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@AudioObjectPropertySelector","kind":"typeIdentifier","text":"AudioObjectPropertySelector"}],"url":"/documentation/coreaudio/kaudiodevicepropertysubvolumedecibelstoscalartransferfunction","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"kAudioDevicePropertySubVolumeDecibelsToScalarTransferFunction"}],"title":"kAudioDevicePropertySubVolumeDecibelsToScalarTransferFunction","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/topicSections","value":[{"anchor":"Constants","title":"Constants","identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDriverShouldOwniSub","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyPlayThruVolumeDecibelsToScalarTransferFunction","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertySubVolumeDecibelsToScalarTransferFunction","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyVolumeDecibelsToScalarTransferFunction"]}]},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous","doc://com.apple.coreaudio/documentation/CoreAudio/1580738-anonymous"],"anchor":"Enumerations","generated":true,"title":"Enumerations"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyVolumeDecibelsToScalarTransferFunction/title","value":"kAudioDevicePropertyVolumeDecibelsToScalarTransferFunction"},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyVolumeDecibelsToScalarTransferFunction/fragments","value":[{"kind":"identifier","text":"kAudioDevicePropertyVolumeDecibelsToScalarTransferFunction"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDriverShouldOwniSub/title","value":"kAudioDevicePropertyDriverShouldOwniSub"},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDriverShouldOwniSub/fragments","value":[{"text":"kAudioDevicePropertyDriverShouldOwniSub","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyPlayThruVolumeDecibelsToScalarTransferFunction/title","value":"kAudioDevicePropertyPlayThruVolumeDecibelsToScalarTransferFunction"},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyPlayThruVolumeDecibelsToScalarTransferFunction/fragments","value":[{"text":"kAudioDevicePropertyPlayThruVolumeDecibelsToScalarTransferFunction","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertySubVolumeDecibelsToScalarTransferFunction/title","value":"kAudioDevicePropertySubVolumeDecibelsToScalarTransferFunction"},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertySubVolumeDecibelsToScalarTransferFunction/fragments","value":[{"kind":"identifier","text":"kAudioDevicePropertySubVolumeDecibelsToScalarTransferFunction"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}