{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamSetProperty"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@AudioStreamSetProperty",
    "fragments": [
      {
        "kind": "identifier",
        "text": "AudioStreamSetProperty"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AudioStreamSetProperty"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.6",
        "introducedAt": "10.1",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "AudioStreamSetProperty"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioStreamSetProperty"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioStreamID",
              "text": "AudioStreamID"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inStream"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@AudioTimeStamp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@AudioTimeStamp",
              "text": "AudioTimeStamp"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "inWhen"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@UInt32",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inChannel"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDevicePropertyID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioDevicePropertyID",
              "text": "AudioDevicePropertyID"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inPropertyID"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@UInt32",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inPropertyDataSize"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "inPropertyData"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceAddIOProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDeviceAddIOProc"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceAddIOProc",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDeviceAddIOProc",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodeviceaddioproc"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceAddPropertyListener": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDeviceAddPropertyListener"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceAddPropertyListener",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDeviceAddPropertyListener",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodeviceaddpropertylistener"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetProperty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDeviceGetProperty"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDeviceGetProperty",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicegetproperty"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetPropertyInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDeviceGetPropertyInfo"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetPropertyInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDeviceGetPropertyInfo",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicegetpropertyinfo"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDevicePropertyID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDevicePropertyID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDevicePropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDevicePropertyID"
        }
      ],
      "role": "symbol",
      "title": "AudioDevicePropertyID",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicepropertyid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRead": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDeviceRead"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRead",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDeviceRead",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodeviceread"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRemoveIOProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDeviceRemoveIOProc"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRemoveIOProc",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDeviceRemoveIOProc",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodeviceremoveioproc"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRemovePropertyListener": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDeviceRemovePropertyListener"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRemovePropertyListener",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDeviceRemovePropertyListener",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodeviceremovepropertylistener"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceSetProperty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDeviceSetProperty"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceSetProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDeviceSetProperty",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicesetproperty"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareAddPropertyListener": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioHardwareAddPropertyListener"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareAddPropertyListener",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioHardwareAddPropertyListener",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwareaddpropertylistener"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareAddRunLoopSource": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioHardwareAddRunLoopSource"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareAddRunLoopSource",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioHardwareAddRunLoopSource",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwareaddrunloopsource"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareGetProperty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioHardwareGetProperty"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareGetProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioHardwareGetProperty",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwaregetproperty"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareGetPropertyInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioHardwareGetPropertyInfo"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareGetPropertyInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioHardwareGetPropertyInfo",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwaregetpropertyinfo"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareRemovePropertyListener": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioHardwareRemovePropertyListener"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareRemovePropertyListener",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioHardwareRemovePropertyListener",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwareremovepropertylistener"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareRemoveRunLoopSource": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioHardwareRemoveRunLoopSource"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareRemoveRunLoopSource",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioHardwareRemoveRunLoopSource",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwareremoverunloopsource"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareSetProperty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioHardwareSetProperty"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareSetProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioHardwareSetProperty",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwaresetproperty"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioStreamID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioStreamID"
        }
      ],
      "role": "symbol",
      "title": "AudioStreamID",
      "type": "topic",
      "url": "/documentation/coreaudio/audiostreamid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamSetProperty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioStreamSetProperty"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamSetProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioStreamSetProperty",
      "type": "topic",
      "url": "/documentation/coreaudio/audiostreamsetproperty"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@S@AudioTimeStamp": {
      "abstract": [
        {
          "text": "A structure that represents a timestamp value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioTimeStamp"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@AudioTimeStamp",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioTimeStamp",
      "type": "topic",
      "url": "/documentation/CoreAudioTypes/AudioTimeStamp"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceAddIOProc",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceAddPropertyListener",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetProperty",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetPropertyInfo",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRead",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRemoveIOProc",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRemovePropertyListener",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceSetProperty",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareAddPropertyListener",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareAddRunLoopSource",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareGetProperty",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareGetPropertyInfo",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareRemovePropertyListener",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareRemoveRunLoopSource",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareSetProperty"
      ],
      "title": "Deprecated Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@S@AudioTimeStamp/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioTimeStamp"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamID/title",
          "value": "AudioStreamID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDevicePropertyID/title",
          "value": "AudioDevicePropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDevicePropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDevicePropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDevicePropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDevicePropertyID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/audiostreamsetproperty"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
