{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@AudioServerPlugInDriverInterface",
    "fragments": [
      {
        "kind": "identifier",
        "text": "AudioServerPlugInDriverInterface"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AudioServerPlugInDriverInterface"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AudioServerPlugInDriverInterface"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioServerPlugInDriverInterface"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDriverPlugInHostInfo"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDriverPlugInHostInfo",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodriverpluginhostinfo"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareIOProcStreamUsage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareIOProcStreamUsage"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareIOProcStreamUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareIOProcStreamUsage"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareIOProcStreamUsage",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwareioprocstreamusage"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyAddress"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyAddress"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertyAddress",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertyaddress"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInClientInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioServerPlugInClientInfo"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInClientInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioServerPlugInClientInfo",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverpluginclientinfo"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInCustomPropertyInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioServerPlugInCustomPropertyInfo"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInCustomPropertyInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioServerPlugInCustomPropertyInfo",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugincustompropertyinfo"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioServerPlugInDriverInterface"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioServerPlugInDriverInterface",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugindriverinterface"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/AbortDeviceConfigurationChange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AbortDeviceConfigurationChange"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/AbortDeviceConfigurationChange",
      "kind": "symbol",
      "role": "symbol",
      "title": "AbortDeviceConfigurationChange",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugindriverinterface/abortdeviceconfigurationchange"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/AddDeviceClient": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AddDeviceClient"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/AddDeviceClient",
      "kind": "symbol",
      "role": "symbol",
      "title": "AddDeviceClient",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugindriverinterface/adddeviceclient"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/AddRef": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AddRef"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/AddRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "AddRef",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugindriverinterface/addref"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/BeginIOOperation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BeginIOOperation"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/BeginIOOperation",
      "kind": "symbol",
      "role": "symbol",
      "title": "BeginIOOperation",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugindriverinterface/beginiooperation"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/CreateDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CreateDevice"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/CreateDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "CreateDevice",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugindriverinterface/createdevice"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/DestroyDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DestroyDevice"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/DestroyDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "DestroyDevice",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugindriverinterface/destroydevice"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/DoIOOperation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "DoIOOperation"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/DoIOOperation",
      "kind": "symbol",
      "role": "symbol",
      "title": "DoIOOperation",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugindriverinterface/doiooperation"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/EndIOOperation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "EndIOOperation"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/EndIOOperation",
      "kind": "symbol",
      "role": "symbol",
      "title": "EndIOOperation",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugindriverinterface/endiooperation"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/GetPropertyData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GetPropertyData"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/GetPropertyData",
      "kind": "symbol",
      "role": "symbol",
      "title": "GetPropertyData",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugindriverinterface/getpropertydata"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/GetPropertyDataSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GetPropertyDataSize"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/GetPropertyDataSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "GetPropertyDataSize",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugindriverinterface/getpropertydatasize"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/GetZeroTimeStamp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GetZeroTimeStamp"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/GetZeroTimeStamp",
      "kind": "symbol",
      "role": "symbol",
      "title": "GetZeroTimeStamp",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugindriverinterface/getzerotimestamp"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/HasProperty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "HasProperty"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/HasProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "HasProperty",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugindriverinterface/hasproperty"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/Initialize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "Initialize"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/Initialize",
      "kind": "symbol",
      "role": "symbol",
      "title": "Initialize",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugindriverinterface/initialize"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/IsPropertySettable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IsPropertySettable"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/IsPropertySettable",
      "kind": "symbol",
      "role": "symbol",
      "title": "IsPropertySettable",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugindriverinterface/ispropertysettable"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/PerformDeviceConfigurationChange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PerformDeviceConfigurationChange"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/PerformDeviceConfigurationChange",
      "kind": "symbol",
      "role": "symbol",
      "title": "PerformDeviceConfigurationChange",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugindriverinterface/performdeviceconfigurationchange"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/QueryInterface": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "QueryInterface"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/QueryInterface",
      "kind": "symbol",
      "role": "symbol",
      "title": "QueryInterface",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugindriverinterface/queryinterface"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/Release": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "Release"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/Release",
      "kind": "symbol",
      "role": "symbol",
      "title": "Release",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugindriverinterface/release"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/RemoveDeviceClient": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "RemoveDeviceClient"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/RemoveDeviceClient",
      "kind": "symbol",
      "role": "symbol",
      "title": "RemoveDeviceClient",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugindriverinterface/removedeviceclient"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/SetPropertyData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SetPropertyData"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/SetPropertyData",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetPropertyData",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugindriverinterface/setpropertydata"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/StartIO": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "StartIO"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/StartIO",
      "kind": "symbol",
      "role": "symbol",
      "title": "StartIO",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugindriverinterface/startio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/StopIO": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "StopIO"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/StopIO",
      "kind": "symbol",
      "role": "symbol",
      "title": "StopIO",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugindriverinterface/stopio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/WillDoIOOperation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "WillDoIOOperation"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/WillDoIOOperation",
      "kind": "symbol",
      "role": "symbol",
      "title": "WillDoIOOperation",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugindriverinterface/willdoiooperation"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInHostInterface": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioServerPlugInHostInterface"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInHostInterface",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioServerPlugInHostInterface",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverpluginhostinterface"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioServerPlugInIOCycleInfo"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioServerPlugInIOCycleInfo",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverpluginiocycleinfo"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRangedDescription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioStreamRangedDescription"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRangedDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioStreamRangedDescription"
        }
      ],
      "role": "symbol",
      "title": "AudioStreamRangedDescription",
      "type": "topic",
      "url": "/documentation/coreaudio/audiostreamrangeddescription"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareIOProcStreamUsage",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyAddress",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInClientInfo",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInCustomPropertyInfo",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInHostInterface",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRangedDescription"
      ],
      "title": "Structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/AbortDeviceConfigurationChange",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/AddDeviceClient",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/AddRef",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/BeginIOOperation",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/CreateDevice",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/DestroyDevice",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/DoIOOperation",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/EndIOOperation",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/GetPropertyData",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/GetPropertyDataSize",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/GetZeroTimeStamp",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/HasProperty",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/Initialize",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/IsPropertySettable",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/PerformDeviceConfigurationChange",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/QueryInterface",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/Release",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/RemoveDeviceClient",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/SetPropertyData",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/StartIO",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/StopIO",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface/WillDoIOOperation"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareIOProcStreamUsage/title",
          "value": "AudioHardwareIOProcStreamUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareIOProcStreamUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwareIOProcStreamUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareIOProcStreamUsage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwareIOProcStreamUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyAddress/title",
          "value": "AudioObjectPropertyAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyAddress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamRangedDescription/title",
          "value": "AudioStreamRangedDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamRangedDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamRangedDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamRangedDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamRangedDescription"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/audioserverplugindriverinterface"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
