{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyListenerBlock"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@AudioObjectPropertyListenerBlock",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AudioObjectPropertyListenerBlock"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AudioObjectPropertyListenerBlock"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "AudioObjectPropertyListenerBlock"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyListenerBlock"
            },
            {
              "kind": "text",
              "text": " = ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyAddress",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@AudioObjectPropertyAddress",
              "text": "AudioObjectPropertyAddress"
            },
            {
              "kind": "text",
              "text": ">) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioClassID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioClassID"
        }
      ],
      "role": "symbol",
      "title": "AudioClassID",
      "type": "topic",
      "url": "/documentation/coreaudio/audioclassid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDeviceID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDeviceID"
        }
      ],
      "role": "symbol",
      "title": "AudioDeviceID",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodeviceid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceIOBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDeviceIOBlock"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceIOBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDeviceIOBlock"
        }
      ],
      "role": "symbol",
      "title": "AudioDeviceIOBlock",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodeviceioblock"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceIOProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDeviceIOProc"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceIOProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDeviceIOProc"
        }
      ],
      "role": "symbol",
      "title": "AudioDeviceIOProc",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodeviceioproc"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceIOProcID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDeviceIOProcID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceIOProcID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDeviceIOProcID"
        }
      ],
      "role": "symbol",
      "title": "AudioDeviceIOProcID",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodeviceioprocid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDevicePropertyID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDevicePropertyID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDevicePropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDevicePropertyID"
        }
      ],
      "role": "symbol",
      "title": "AudioDevicePropertyID",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicepropertyid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDevicePropertyListenerProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDevicePropertyListenerProc"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDevicePropertyListenerProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDevicePropertyListenerProc"
        }
      ],
      "role": "symbol",
      "title": "AudioDevicePropertyListenerProc",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicepropertylistenerproc"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDevicePropertyChangedProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDriverPlugInDevicePropertyChangedProc"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDevicePropertyChangedProc",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDriverPlugInDevicePropertyChangedProc",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodriverplugindevicepropertychangedproc"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInStreamPropertyChangedProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDriverPlugInStreamPropertyChangedProc"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInStreamPropertyChangedProc",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDriverPlugInStreamPropertyChangedProc",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodriverpluginstreampropertychangedproc"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePropertyID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwarePropertyID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwarePropertyID"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwarePropertyID",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwarepropertyid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePropertyListenerProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwarePropertyListenerProc"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePropertyListenerProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwarePropertyListenerProc"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwarePropertyListenerProc",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwarepropertylistenerproc"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectID"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectID",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyAddress"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyAddress"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertyAddress",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertyaddress"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyElement": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyElement"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyElement"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertyElement",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertyelement"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyListenerBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyListenerBlock"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyListenerBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyListenerBlock"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertyListenerBlock",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertylistenerblock"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyListenerProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyListenerProc"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyListenerProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyListenerProc"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertyListenerProc",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertylistenerproc"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyScope": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyScope"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyScope",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyScope"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertyScope",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertyscope"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertySelector",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertyselector"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioStreamID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioStreamID"
        }
      ],
      "role": "symbol",
      "title": "AudioStreamID",
      "type": "topic",
      "url": "/documentation/coreaudio/audiostreamid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SP": {
      "abstract": [
        {
          "text": "A pointer for accessing data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafePointer"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioClassID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceIOBlock",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceIOProc",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceIOProcID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDevicePropertyID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDevicePropertyListenerProc",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePropertyID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePropertyListenerProc",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyElement",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyListenerProc",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyScope",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamID"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AudioObjectPropertyListenerBlock"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyListenerBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyListenerBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudio/documentation/CoreAudio"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioClassID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceIOBlock",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceIOProc",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceIOProcID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDevicePropertyID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDevicePropertyListenerProc",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDevicePropertyChangedProc",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInStreamPropertyChangedProc",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePropertyID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePropertyListenerProc",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyElement",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyListenerProc",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyScope"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:BFv(#i#*1$@S@AudioObjectPropertyAddress)",
                    "text": "void (^)(unsigned int, const struct AudioObjectPropertyAddress *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AudioObjectPropertyListenerBlock"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyAddress/title",
          "value": "AudioObjectPropertyAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyAddress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyListenerProc/title",
          "value": "AudioObjectPropertyListenerProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyListenerProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyListenerProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyListenerProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyListenerProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyScope/title",
          "value": "AudioObjectPropertyScope"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyScope/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyScope/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceIOProcID/title",
          "value": "AudioDeviceIOProcID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceIOProcID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceIOProcID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceIOProcID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceIOProcID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamID/title",
          "value": "AudioStreamID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyListenerBlock/title",
          "value": "AudioObjectPropertyListenerBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyListenerBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyListenerBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyListenerBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyListenerBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDevicePropertyListenerProc/title",
          "value": "AudioDevicePropertyListenerProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDevicePropertyListenerProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDevicePropertyListenerProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDevicePropertyListenerProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDevicePropertyListenerProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceIOProc/title",
          "value": "AudioDeviceIOProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceIOProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceIOProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceIOProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceIOProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyElement/title",
          "value": "AudioObjectPropertyElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceID/title",
          "value": "AudioDeviceID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceIOBlock/title",
          "value": "AudioDeviceIOBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceIOBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceIOBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceIOBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceIOBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/title",
          "value": "AudioObjectPropertySelector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDevicePropertyID/title",
          "value": "AudioDevicePropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDevicePropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDevicePropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDevicePropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDevicePropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioClassID/title",
          "value": "AudioClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioClassID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwarePropertyListenerProc/title",
          "value": "AudioHardwarePropertyListenerProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwarePropertyListenerProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwarePropertyListenerProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwarePropertyListenerProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwarePropertyListenerProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwarePropertyID/title",
          "value": "AudioHardwarePropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwarePropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwarePropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwarePropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwarePropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectID/title",
          "value": "AudioObjectID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/audioobjectpropertylistenerblock"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/audioobjectpropertylistenerblock"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
