{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coreaudio/documentation/CoreAudio"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@T@OSStatus","text":"OSStatus","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"AudioStreamGetPropertyInfo","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamID","preciseIdentifier":"c:@T@AudioStreamID","text":"AudioStreamID","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inStream"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"c:@T@UInt32"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inChannel"},{"kind":"text","text":", "},{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDevicePropertyID","kind":"typeIdentifier","text":"AudioDevicePropertyID","preciseIdentifier":"c:@T@AudioDevicePropertyID"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inPropertyID"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"c:@T@UInt32"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"outSize"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@T@Boolean","kind":"typeIdentifier","text":"Boolean"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"outWritable"},{"kind":"text","text":");"}]}]}],"kind":"symbol","seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceAddIOProc","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceAddPropertyListener","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetProperty","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetPropertyInfo","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRead","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRemoveIOProc","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRemovePropertyListener","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceSetProperty","doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareAddPropertyListener","doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareAddRunLoopSource","doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareGetProperty","doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareGetPropertyInfo","doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareRemovePropertyListener","doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareRemoveRunLoopSource","doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareSetProperty"],"anchor":"Deprecated-Functions","title":"Deprecated Functions"}],"identifier":{"url":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamGetPropertyInfo","interfaceLanguage":"occ"},"metadata":{"fragments":[{"kind":"identifier","text":"AudioStreamGetPropertyInfo"}],"modules":[{"name":"Core Audio"}],"roleHeading":"Function","role":"symbol","symbolKind":"func","externalID":"c:@F@AudioStreamGetPropertyInfo","platforms":[{"deprecated":false,"deprecatedAt":"13.1","unavailable":false,"beta":false,"introducedAt":"13.1","name":"Mac Catalyst"},{"deprecated":false,"deprecatedAt":"10.6","unavailable":false,"beta":false,"introducedAt":"10.1","name":"macOS"}],"title":"AudioStreamGetPropertyInfo","navigatorTitle":[{"kind":"identifier","text":"AudioStreamGetPropertyInfo"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/coreaudio/audiostreamgetpropertyinfo"]}],"references":{"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareRemoveRunLoopSource":{"abstract":[],"role":"symbol","url":"/documentation/coreaudio/audiohardwareremoverunloopsource","kind":"symbol","fragments":[{"text":"AudioHardwareRemoveRunLoopSource","kind":"identifier"}],"title":"AudioHardwareRemoveRunLoopSource","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareRemoveRunLoopSource","type":"topic"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamID":{"type":"topic","url":"/documentation/coreaudio/audiostreamid","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamID","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AudioStreamID"}],"title":"AudioStreamID","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AudioStreamID"}],"role":"symbol","kind":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRead":{"abstract":[],"role":"symbol","url":"/documentation/coreaudio/audiodeviceread","kind":"symbol","fragments":[{"text":"AudioDeviceRead","kind":"identifier"}],"title":"AudioDeviceRead","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRead","type":"topic"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamGetPropertyInfo":{"role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamGetPropertyInfo","type":"topic","title":"AudioStreamGetPropertyInfo","abstract":[],"kind":"symbol","fragments":[{"kind":"identifier","text":"AudioStreamGetPropertyInfo"}],"url":"/documentation/coreaudio/audiostreamgetpropertyinfo"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareAddPropertyListener":{"fragments":[{"kind":"identifier","text":"AudioHardwareAddPropertyListener"}],"kind":"symbol","url":"/documentation/coreaudio/audiohardwareaddpropertylistener","abstract":[],"title":"AudioHardwareAddPropertyListener","type":"topic","role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareAddPropertyListener"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDevicePropertyID":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AudioDevicePropertyID"}],"kind":"symbol","title":"AudioDevicePropertyID","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDevicePropertyID","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AudioDevicePropertyID"}],"url":"/documentation/coreaudio/audiodevicepropertyid","type":"topic","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRemovePropertyListener":{"fragments":[{"kind":"identifier","text":"AudioDeviceRemovePropertyListener"}],"kind":"symbol","url":"/documentation/coreaudio/audiodeviceremovepropertylistener","abstract":[],"title":"AudioDeviceRemovePropertyListener","type":"topic","role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRemovePropertyListener"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareGetPropertyInfo":{"fragments":[{"kind":"identifier","text":"AudioHardwareGetPropertyInfo"}],"kind":"symbol","url":"/documentation/coreaudio/audiohardwaregetpropertyinfo","abstract":[],"title":"AudioHardwareGetPropertyInfo","type":"topic","role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareGetPropertyInfo"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareGetProperty":{"fragments":[{"kind":"identifier","text":"AudioHardwareGetProperty"}],"kind":"symbol","url":"/documentation/coreaudio/audiohardwaregetproperty","abstract":[],"title":"AudioHardwareGetProperty","type":"topic","role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareGetProperty"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceAddIOProc":{"fragments":[{"kind":"identifier","text":"AudioDeviceAddIOProc"}],"kind":"symbol","url":"/documentation/coreaudio/audiodeviceaddioproc","abstract":[],"title":"AudioDeviceAddIOProc","type":"topic","role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceAddIOProc"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceSetProperty":{"abstract":[],"role":"symbol","url":"/documentation/coreaudio/audiodevicesetproperty","kind":"symbol","fragments":[{"text":"AudioDeviceSetProperty","kind":"identifier"}],"title":"AudioDeviceSetProperty","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceSetProperty","type":"topic"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareAddRunLoopSource":{"fragments":[{"kind":"identifier","text":"AudioHardwareAddRunLoopSource"}],"kind":"symbol","url":"/documentation/coreaudio/audiohardwareaddrunloopsource","abstract":[],"title":"AudioHardwareAddRunLoopSource","type":"topic","role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareAddRunLoopSource"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceAddPropertyListener":{"fragments":[{"kind":"identifier","text":"AudioDeviceAddPropertyListener"}],"kind":"symbol","url":"/documentation/coreaudio/audiodeviceaddpropertylistener","abstract":[],"title":"AudioDeviceAddPropertyListener","type":"topic","role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceAddPropertyListener"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetPropertyInfo":{"abstract":[],"role":"symbol","url":"/documentation/coreaudio/audiodevicegetpropertyinfo","kind":"symbol","fragments":[{"text":"AudioDeviceGetPropertyInfo","kind":"identifier"}],"title":"AudioDeviceGetPropertyInfo","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetPropertyInfo","type":"topic"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareSetProperty":{"fragments":[{"kind":"identifier","text":"AudioHardwareSetProperty"}],"kind":"symbol","url":"/documentation/coreaudio/audiohardwaresetproperty","abstract":[],"title":"AudioHardwareSetProperty","type":"topic","role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareSetProperty"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRemoveIOProc":{"fragments":[{"kind":"identifier","text":"AudioDeviceRemoveIOProc"}],"kind":"symbol","url":"/documentation/coreaudio/audiodeviceremoveioproc","abstract":[],"title":"AudioDeviceRemoveIOProc","type":"topic","role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRemoveIOProc"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","role":"overview","kind":"technologies"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareRemovePropertyListener":{"type":"topic","role":"symbol","fragments":[{"text":"AudioHardwareRemovePropertyListener","kind":"identifier"}],"kind":"symbol","title":"AudioHardwareRemovePropertyListener","url":"/documentation/coreaudio/audiohardwareremovepropertylistener","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareRemovePropertyListener"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetProperty":{"fragments":[{"kind":"identifier","text":"AudioDeviceGetProperty"}],"kind":"symbol","url":"/documentation/coreaudio/audiodevicegetproperty","abstract":[],"title":"AudioDeviceGetProperty","type":"topic","role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetProperty"},"doc://com.apple.coreaudio/documentation/CoreAudio":{"kind":"symbol","title":"Core Audio","type":"topic","abstract":[{"type":"text","text":"Use the Core Audio framework to interact with device’s audio hardware."}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio","url":"/documentation/coreaudio","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"AudioStreamID","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamID/title","op":"replace"},{"value":[{"text":"AudioStreamID","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamID/fragments","op":"replace"},{"op":"replace","value":[{"text":"AudioStreamID","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamID/navigatorTitle"},{"op":"replace","value":"AudioDevicePropertyID","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDevicePropertyID/title"},{"op":"replace","value":[{"kind":"identifier","text":"AudioDevicePropertyID"}],"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDevicePropertyID/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AudioDevicePropertyID"}],"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDevicePropertyID/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}