{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetHostClockMinimumTimeDelta()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@AudioGetHostClockMinimumTimeDelta",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AudioGetHostClockMinimumTimeDelta"
      },
      {
        "kind": "text",
        "text": "() -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AudioGetHostClockMinimumTimeDelta"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "AudioGetHostClockMinimumTimeDelta()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioGetHostClockMinimumTimeDelta"
            },
            {
              "kind": "text",
              "text": "() -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertHostTimeToNanos(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioConvertHostTimeToNanos"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertHostTimeToNanos(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioConvertHostTimeToNanos"
        }
      ],
      "role": "symbol",
      "title": "AudioConvertHostTimeToNanos(_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audioconverthosttimetonanos(_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertNanosToHostTime(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioConvertNanosToHostTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertNanosToHostTime(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioConvertNanosToHostTime"
        }
      ],
      "role": "symbol",
      "title": "AudioConvertNanosToHostTime(_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audioconvertnanostohosttime(_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcID(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDeviceCreateIOProcID"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioDeviceIOProc",
          "text": "AudioDeviceIOProc"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioDeviceIOProcID",
          "text": "AudioDeviceIOProcID"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcID(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDeviceCreateIOProcID"
        }
      ],
      "role": "symbol",
      "title": "AudioDeviceCreateIOProcID(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicecreateioprocid(_:_:_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcIDWithBlock(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDeviceCreateIOProcIDWithBlock"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioDeviceIOProcID",
          "text": "AudioDeviceIOProcID"
        },
        {
          "kind": "text",
          "text": "?>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioDeviceIOBlock",
          "text": "AudioDeviceIOBlock"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcIDWithBlock(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDeviceCreateIOProcIDWithBlock"
        }
      ],
      "role": "symbol",
      "title": "AudioDeviceCreateIOProcIDWithBlock(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicecreateioprocidwithblock(_:_:_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceDestroyIOProcID(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDeviceDestroyIOProcID"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioDeviceIOProcID",
          "text": "AudioDeviceIOProcID"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceDestroyIOProcID(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDeviceDestroyIOProcID"
        }
      ],
      "role": "symbol",
      "title": "AudioDeviceDestroyIOProcID(_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicedestroyioprocid(_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetCurrentTime(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDeviceGetCurrentTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioTimeStamp",
          "text": "AudioTimeStamp"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetCurrentTime(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDeviceGetCurrentTime"
        }
      ],
      "role": "symbol",
      "title": "AudioDeviceGetCurrentTime(_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicegetcurrenttime(_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetNearestStartTime(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDeviceGetNearestStartTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioTimeStamp",
          "text": "AudioTimeStamp"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetNearestStartTime(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDeviceGetNearestStartTime"
        }
      ],
      "role": "symbol",
      "title": "AudioDeviceGetNearestStartTime(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicegetneareststarttime(_:_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStart(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDeviceStart"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioDeviceIOProcID",
          "text": "AudioDeviceIOProcID"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStart(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDeviceStart"
        }
      ],
      "role": "symbol",
      "title": "AudioDeviceStart(_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicestart(_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStartAtTime(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDeviceStartAtTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioDeviceIOProcID",
          "text": "AudioDeviceIOProcID"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioTimeStamp",
          "text": "AudioTimeStamp"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStartAtTime(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDeviceStartAtTime"
        }
      ],
      "role": "symbol",
      "title": "AudioDeviceStartAtTime(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicestartattime(_:_:_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStop(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDeviceStop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioDeviceIOProcID",
          "text": "AudioDeviceIOProcID"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStop(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDeviceStop"
        }
      ],
      "role": "symbol",
      "title": "AudioDeviceStop(_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicestop(_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceTranslateTime(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDeviceTranslateTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioTimeStamp",
          "text": "AudioTimeStamp"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioTimeStamp",
          "text": "AudioTimeStamp"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceTranslateTime(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDeviceTranslateTime"
        }
      ],
      "role": "symbol",
      "title": "AudioDeviceTranslateTime(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicetranslatetime(_:_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInClose": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDriverPlugInClose"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInClose",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDriverPlugInClose",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodriverpluginclose"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceGetProperty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDriverPlugInDeviceGetProperty"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceGetProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDriverPlugInDeviceGetProperty",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodriverplugindevicegetproperty"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceGetPropertyInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDriverPlugInDeviceGetPropertyInfo"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceGetPropertyInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDriverPlugInDeviceGetPropertyInfo",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodriverplugindevicegetpropertyinfo"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceSetProperty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDriverPlugInDeviceSetProperty"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceSetProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDriverPlugInDeviceSetProperty",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodriverplugindevicesetproperty"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetCurrentHostTime()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioGetCurrentHostTime"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetCurrentHostTime()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioGetCurrentHostTime"
        }
      ],
      "role": "symbol",
      "title": "AudioGetCurrentHostTime()",
      "type": "topic",
      "url": "/documentation/coreaudio/audiogetcurrenthosttime()"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetHostClockFrequency()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioGetHostClockFrequency"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float64a",
          "text": "Float64"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetHostClockFrequency()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioGetHostClockFrequency"
        }
      ],
      "role": "symbol",
      "title": "AudioGetHostClockFrequency()",
      "type": "topic",
      "url": "/documentation/coreaudio/audiogethostclockfrequency()"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetHostClockMinimumTimeDelta()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioGetHostClockMinimumTimeDelta"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetHostClockMinimumTimeDelta()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioGetHostClockMinimumTimeDelta"
        }
      ],
      "role": "symbol",
      "title": "AudioGetHostClockMinimumTimeDelta()",
      "type": "topic",
      "url": "/documentation/coreaudio/audiogethostclockminimumtimedelta()"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareCreateAggregateDevice(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareCreateAggregateDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareCreateAggregateDevice(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareCreateAggregateDevice"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareCreateAggregateDevice(_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwarecreateaggregatedevice(_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareDestroyAggregateDevice(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareDestroyAggregateDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareDestroyAggregateDevice(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareDestroyAggregateDevice"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareDestroyAggregateDevice(_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwaredestroyaggregatedevice(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertHostTimeToNanos(_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertNanosToHostTime(_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcID(_:_:_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcIDWithBlock(_:_:_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceDestroyIOProcID(_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetCurrentTime(_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetNearestStartTime(_:_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStart(_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStartAtTime(_:_:_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStop(_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceTranslateTime(_:_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetCurrentHostTime()",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetHostClockFrequency()",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareCreateAggregateDevice(_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareDestroyAggregateDevice(_:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AudioGetHostClockMinimumTimeDelta"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioGetHostClockMinimumTimeDelta"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudio/documentation/CoreAudio"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertHostTimeToNanos(_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertNanosToHostTime(_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcID(_:_:_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcIDWithBlock(_:_:_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceDestroyIOProcID(_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetCurrentTime(_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetNearestStartTime(_:_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStart(_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStartAtTime(_:_:_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStop(_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceTranslateTime(_:_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInClose",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceGetProperty",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceGetPropertyInfo",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceSetProperty"
              ],
              "title": "Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@UInt32",
                    "text": "UInt32"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AudioGetHostClockMinimumTimeDelta"
                  },
                  {
                    "kind": "text",
                    "text": "();"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioConvertHostTimeToNanos(_:)/title",
          "value": "AudioConvertHostTimeToNanos"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioConvertHostTimeToNanos(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioConvertHostTimeToNanos"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioGetHostClockMinimumTimeDelta()/title",
          "value": "AudioGetHostClockMinimumTimeDelta"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioGetHostClockMinimumTimeDelta()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioGetHostClockMinimumTimeDelta"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareDestroyAggregateDevice(_:)/title",
          "value": "AudioHardwareDestroyAggregateDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareDestroyAggregateDevice(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwareDestroyAggregateDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceStop(_:_:)/title",
          "value": "AudioDeviceStop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceStop(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceStop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceCreateIOProcIDWithBlock(_:_:_:_:)/title",
          "value": "AudioDeviceCreateIOProcIDWithBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceCreateIOProcIDWithBlock(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceCreateIOProcIDWithBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareCreateAggregateDevice(_:_:)/title",
          "value": "AudioHardwareCreateAggregateDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareCreateAggregateDevice(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwareCreateAggregateDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioGetHostClockFrequency()/title",
          "value": "AudioGetHostClockFrequency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioGetHostClockFrequency()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioGetHostClockFrequency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioGetCurrentHostTime()/title",
          "value": "AudioGetCurrentHostTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioGetCurrentHostTime()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioGetCurrentHostTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceGetNearestStartTime(_:_:_:)/title",
          "value": "AudioDeviceGetNearestStartTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceGetNearestStartTime(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceGetNearestStartTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceTranslateTime(_:_:_:)/title",
          "value": "AudioDeviceTranslateTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceTranslateTime(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceTranslateTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceStart(_:_:)/title",
          "value": "AudioDeviceStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceStart(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceStartAtTime(_:_:_:_:)/title",
          "value": "AudioDeviceStartAtTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceStartAtTime(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceStartAtTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceDestroyIOProcID(_:_:)/title",
          "value": "AudioDeviceDestroyIOProcID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceDestroyIOProcID(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceDestroyIOProcID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioConvertNanosToHostTime(_:)/title",
          "value": "AudioConvertNanosToHostTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioConvertNanosToHostTime(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioConvertNanosToHostTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceGetCurrentTime(_:_:)/title",
          "value": "AudioDeviceGetCurrentTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceGetCurrentTime(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceGetCurrentTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceCreateIOProcID(_:_:_:_:)/title",
          "value": "AudioDeviceCreateIOProcID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceCreateIOProcID(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceCreateIOProcID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/audiogethostclockminimumtimedelta()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/audiogethostclockminimumtimedelta()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
