{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@AudioServerPlugInIOCycleInfo",
    "fragments": [
      {
        "kind": "identifier",
        "text": "AudioServerPlugInIOCycleInfo"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AudioServerPlugInIOCycleInfo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AudioServerPlugInIOCycleInfo"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioServerPlugInIOCycleInfo"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDriverPlugInHostInfo"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDriverPlugInHostInfo",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodriverpluginhostinfo"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareIOProcStreamUsage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareIOProcStreamUsage"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareIOProcStreamUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareIOProcStreamUsage"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareIOProcStreamUsage",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwareioprocstreamusage"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyAddress"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyAddress"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertyAddress",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertyaddress"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInClientInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioServerPlugInClientInfo"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInClientInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioServerPlugInClientInfo",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverpluginclientinfo"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInCustomPropertyInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioServerPlugInCustomPropertyInfo"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInCustomPropertyInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioServerPlugInCustomPropertyInfo",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugincustompropertyinfo"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioServerPlugInDriverInterface"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioServerPlugInDriverInterface",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugindriverinterface"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInHostInterface": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioServerPlugInHostInterface"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInHostInterface",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioServerPlugInHostInterface",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverpluginhostinterface"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioServerPlugInIOCycleInfo"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioServerPlugInIOCycleInfo",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverpluginiocycleinfo"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo/mCurrentTime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mCurrentTime"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo/mCurrentTime",
      "kind": "symbol",
      "role": "symbol",
      "title": "mCurrentTime",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverpluginiocycleinfo/mcurrenttime"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo/mDeviceHostTicksPerFrame": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mDeviceHostTicksPerFrame"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo/mDeviceHostTicksPerFrame",
      "kind": "symbol",
      "role": "symbol",
      "title": "mDeviceHostTicksPerFrame",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverpluginiocycleinfo/mdevicehostticksperframe"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo/mIOCycleCounter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mIOCycleCounter"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo/mIOCycleCounter",
      "kind": "symbol",
      "role": "symbol",
      "title": "mIOCycleCounter",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverpluginiocycleinfo/miocyclecounter"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo/mInputTime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mInputTime"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo/mInputTime",
      "kind": "symbol",
      "role": "symbol",
      "title": "mInputTime",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverpluginiocycleinfo/minputtime"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo/mMainHostTicksPerFrame": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mMainHostTicksPerFrame"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo/mMainHostTicksPerFrame",
      "kind": "symbol",
      "role": "symbol",
      "title": "mMainHostTicksPerFrame",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverpluginiocycleinfo/mmainhostticksperframe"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo/mMasterHostTicksPerFrame": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mMasterHostTicksPerFrame"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo/mMasterHostTicksPerFrame",
      "kind": "symbol",
      "role": "symbol",
      "title": "mMasterHostTicksPerFrame",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverpluginiocycleinfo/mmasterhostticksperframe"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo/mNominalIOBufferFrameSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mNominalIOBufferFrameSize"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo/mNominalIOBufferFrameSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "mNominalIOBufferFrameSize",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverpluginiocycleinfo/mnominaliobufferframesize"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo/mOutputTime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mOutputTime"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo/mOutputTime",
      "kind": "symbol",
      "role": "symbol",
      "title": "mOutputTime",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverpluginiocycleinfo/moutputtime"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRangedDescription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioStreamRangedDescription"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRangedDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioStreamRangedDescription"
        }
      ],
      "role": "symbol",
      "title": "AudioStreamRangedDescription",
      "type": "topic",
      "url": "/documentation/coreaudio/audiostreamrangeddescription"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareIOProcStreamUsage",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyAddress",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInClientInfo",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInCustomPropertyInfo",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInHostInterface",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRangedDescription"
      ],
      "title": "Structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo/mCurrentTime",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo/mDeviceHostTicksPerFrame",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo/mIOCycleCounter",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo/mInputTime",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo/mMainHostTicksPerFrame",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo/mMasterHostTicksPerFrame",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo/mNominalIOBufferFrameSize",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo/mOutputTime"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamRangedDescription/title",
          "value": "AudioStreamRangedDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamRangedDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamRangedDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamRangedDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamRangedDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareIOProcStreamUsage/title",
          "value": "AudioHardwareIOProcStreamUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareIOProcStreamUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwareIOProcStreamUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareIOProcStreamUsage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwareIOProcStreamUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyAddress/title",
          "value": "AudioObjectPropertyAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyAddress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyAddress"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/audioserverpluginiocycleinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
