{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"AudioStreamAddPropertyListener"}],"role":"symbol","roleHeading":"Function","externalID":"c:@F@AudioStreamAddPropertyListener","symbolKind":"func","platforms":[{"deprecated":false,"beta":false,"name":"Mac Catalyst","introducedAt":"13.1","unavailable":false,"deprecatedAt":"13.1"},{"deprecated":false,"beta":false,"name":"macOS","introducedAt":"10.1","unavailable":false,"deprecatedAt":"10.6"}],"fragments":[{"kind":"identifier","text":"AudioStreamAddPropertyListener"}],"modules":[{"name":"Core Audio"}],"title":"AudioStreamAddPropertyListener"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coreaudio/documentation/CoreAudio"]]},"identifier":{"interfaceLanguage":"occ","url":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamAddPropertyListener"},"seeAlsoSections":[{"title":"Deprecated Functions","identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceAddIOProc","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceAddPropertyListener","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetProperty","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetPropertyInfo","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRead","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRemoveIOProc","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRemovePropertyListener","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceSetProperty","doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareAddPropertyListener","doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareAddRunLoopSource","doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareGetProperty","doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareGetPropertyInfo","doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareRemovePropertyListener","doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareRemoveRunLoopSource","doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareSetProperty"],"generated":true,"anchor":"Deprecated-Functions"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/coreaudio/audiostreamaddpropertylistener"]}],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OSStatus","kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus"},{"text":" ","kind":"text"},{"text":"AudioStreamAddPropertyListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AudioStreamID","kind":"typeIdentifier","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamID","preciseIdentifier":"c:@T@AudioStreamID"},{"text":" ","kind":"text"},{"text":"inStream","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"UInt32","kind":"typeIdentifier","preciseIdentifier":"c:@T@UInt32"},{"text":" ","kind":"text"},{"text":"inChannel","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"AudioDevicePropertyID","kind":"typeIdentifier","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDevicePropertyID","preciseIdentifier":"c:@T@AudioDevicePropertyID"},{"text":" ","kind":"text"},{"text":"inPropertyID","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"AudioStreamPropertyListenerProc","kind":"typeIdentifier","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamPropertyListenerProc","preciseIdentifier":"c:@T@AudioStreamPropertyListenerProc"},{"text":" ","kind":"text"},{"text":"inProc","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" * ","kind":"text"},{"text":"inClientData","kind":"internalParam"},{"text":");","kind":"text"}],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.apple.coreaudio/documentation/CoreAudio":{"kind":"symbol","title":"Core Audio","type":"topic","abstract":[{"type":"text","text":"Use the Core Audio framework to interact with device’s audio hardware."}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio","url":"/documentation/coreaudio","role":"collection"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamID":{"type":"topic","url":"/documentation/coreaudio/audiostreamid","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamID","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AudioStreamID"}],"title":"AudioStreamID","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AudioStreamID"}],"role":"symbol","kind":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareRemovePropertyListener":{"type":"topic","role":"symbol","fragments":[{"text":"AudioHardwareRemovePropertyListener","kind":"identifier"}],"kind":"symbol","title":"AudioHardwareRemovePropertyListener","url":"/documentation/coreaudio/audiohardwareremovepropertylistener","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareRemovePropertyListener"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRemovePropertyListener":{"fragments":[{"kind":"identifier","text":"AudioDeviceRemovePropertyListener"}],"kind":"symbol","url":"/documentation/coreaudio/audiodeviceremovepropertylistener","abstract":[],"title":"AudioDeviceRemovePropertyListener","type":"topic","role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRemovePropertyListener"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetPropertyInfo":{"abstract":[],"role":"symbol","url":"/documentation/coreaudio/audiodevicegetpropertyinfo","kind":"symbol","fragments":[{"text":"AudioDeviceGetPropertyInfo","kind":"identifier"}],"title":"AudioDeviceGetPropertyInfo","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetPropertyInfo","type":"topic"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareSetProperty":{"fragments":[{"kind":"identifier","text":"AudioHardwareSetProperty"}],"kind":"symbol","url":"/documentation/coreaudio/audiohardwaresetproperty","abstract":[],"title":"AudioHardwareSetProperty","type":"topic","role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareSetProperty"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceAddPropertyListener":{"fragments":[{"kind":"identifier","text":"AudioDeviceAddPropertyListener"}],"kind":"symbol","url":"/documentation/coreaudio/audiodeviceaddpropertylistener","abstract":[],"title":"AudioDeviceAddPropertyListener","type":"topic","role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceAddPropertyListener"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamPropertyListenerProc":{"navigatorTitle":[{"text":"AudioStreamPropertyListenerProc","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[],"type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamPropertyListenerProc","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioStreamPropertyListenerProc","kind":"identifier"}],"url":"/documentation/coreaudio/audiostreampropertylistenerproc","title":"AudioStreamPropertyListenerProc"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamAddPropertyListener":{"abstract":[],"role":"symbol","url":"/documentation/coreaudio/audiostreamaddpropertylistener","kind":"symbol","fragments":[{"text":"AudioStreamAddPropertyListener","kind":"identifier"}],"title":"AudioStreamAddPropertyListener","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamAddPropertyListener","type":"topic"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceSetProperty":{"abstract":[],"role":"symbol","url":"/documentation/coreaudio/audiodevicesetproperty","kind":"symbol","fragments":[{"text":"AudioDeviceSetProperty","kind":"identifier"}],"title":"AudioDeviceSetProperty","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceSetProperty","type":"topic"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRead":{"abstract":[],"role":"symbol","url":"/documentation/coreaudio/audiodeviceread","kind":"symbol","fragments":[{"text":"AudioDeviceRead","kind":"identifier"}],"title":"AudioDeviceRead","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRead","type":"topic"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRemoveIOProc":{"fragments":[{"kind":"identifier","text":"AudioDeviceRemoveIOProc"}],"kind":"symbol","url":"/documentation/coreaudio/audiodeviceremoveioproc","abstract":[],"title":"AudioDeviceRemoveIOProc","type":"topic","role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRemoveIOProc"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareAddRunLoopSource":{"fragments":[{"kind":"identifier","text":"AudioHardwareAddRunLoopSource"}],"kind":"symbol","url":"/documentation/coreaudio/audiohardwareaddrunloopsource","abstract":[],"title":"AudioHardwareAddRunLoopSource","type":"topic","role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareAddRunLoopSource"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetProperty":{"fragments":[{"kind":"identifier","text":"AudioDeviceGetProperty"}],"kind":"symbol","url":"/documentation/coreaudio/audiodevicegetproperty","abstract":[],"title":"AudioDeviceGetProperty","type":"topic","role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetProperty"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareGetPropertyInfo":{"fragments":[{"kind":"identifier","text":"AudioHardwareGetPropertyInfo"}],"kind":"symbol","url":"/documentation/coreaudio/audiohardwaregetpropertyinfo","abstract":[],"title":"AudioHardwareGetPropertyInfo","type":"topic","role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareGetPropertyInfo"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDevicePropertyID":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AudioDevicePropertyID"}],"kind":"symbol","title":"AudioDevicePropertyID","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDevicePropertyID","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AudioDevicePropertyID"}],"url":"/documentation/coreaudio/audiodevicepropertyid","type":"topic","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareRemoveRunLoopSource":{"abstract":[],"role":"symbol","url":"/documentation/coreaudio/audiohardwareremoverunloopsource","kind":"symbol","fragments":[{"text":"AudioHardwareRemoveRunLoopSource","kind":"identifier"}],"title":"AudioHardwareRemoveRunLoopSource","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareRemoveRunLoopSource","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","role":"overview","kind":"technologies"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceAddIOProc":{"fragments":[{"kind":"identifier","text":"AudioDeviceAddIOProc"}],"kind":"symbol","url":"/documentation/coreaudio/audiodeviceaddioproc","abstract":[],"title":"AudioDeviceAddIOProc","type":"topic","role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceAddIOProc"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareGetProperty":{"fragments":[{"kind":"identifier","text":"AudioHardwareGetProperty"}],"kind":"symbol","url":"/documentation/coreaudio/audiohardwaregetproperty","abstract":[],"title":"AudioHardwareGetProperty","type":"topic","role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareGetProperty"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareAddPropertyListener":{"fragments":[{"kind":"identifier","text":"AudioHardwareAddPropertyListener"}],"kind":"symbol","url":"/documentation/coreaudio/audiohardwareaddpropertylistener","abstract":[],"title":"AudioHardwareAddPropertyListener","type":"topic","role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareAddPropertyListener"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamID/title","value":"AudioStreamID"},{"value":[{"text":"AudioStreamID","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamID/fragments"},{"value":[{"text":"AudioStreamID","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamID/navigatorTitle"},{"value":"AudioStreamPropertyListenerProc","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamPropertyListenerProc/title"},{"value":[{"kind":"identifier","text":"AudioStreamPropertyListenerProc"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamPropertyListenerProc/fragments"},{"value":[{"kind":"identifier","text":"AudioStreamPropertyListenerProc"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamPropertyListenerProc/navigatorTitle"},{"value":"AudioDevicePropertyID","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDevicePropertyID/title"},{"value":[{"text":"AudioDevicePropertyID","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDevicePropertyID/fragments"},{"value":[{"text":"AudioDevicePropertyID","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDevicePropertyID/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}