{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/coreaudio/audiohardwaredestroyprocesstap(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/coreaudio/audiohardwaredestroyprocesstap(_:)"]}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coreaudio/documentation/CoreAudio"]]},"seeAlsoSections":[{"generated":true,"anchor":"Functions","identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertHostTimeToNanos(_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertNanosToHostTime(_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcID(_:_:_:_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcIDWithBlock(_:_:_:_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceDestroyIOProcID(_:_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetCurrentTime(_:_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetNearestStartTime(_:_:_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStart(_:_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStartAtTime(_:_:_:_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStop(_:_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceTranslateTime(_:_:_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetCurrentHostTime()","doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetHostClockFrequency()","doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetHostClockMinimumTimeDelta()","doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareCreateAggregateDevice(_:_:)"],"title":"Functions"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioHardwareDestroyProcessTap","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inTapID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectID","text":"AudioObjectID","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectID"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus","text":"OSStatus"}]}],"kind":"declarations"}],"identifier":{"url":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareDestroyProcessTap(_:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"func","title":"AudioHardwareDestroyProcessTap(_:)","roleHeading":"Function","role":"symbol","platforms":[{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS","introducedAt":"14.2"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioHardwareDestroyProcessTap"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AudioObjectID","preciseIdentifier":"c:@T@AudioObjectID"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"OSStatus","preciseIdentifier":"c:@T@OSStatus"}],"modules":[{"name":"Core Audio"}],"navigatorTitle":[{"kind":"identifier","text":"AudioHardwareDestroyProcessTap"}],"externalID":"c:@F@AudioHardwareDestroyProcessTap"},"references":{"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInClose":{"url":"/documentation/coreaudio/audiodriverpluginclose","type":"topic","kind":"symbol","title":"AudioDriverPlugInClose","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"AudioDriverPlugInClose"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInClose"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcID(_:_:_:_:)":{"type":"topic","navigatorTitle":[{"text":"AudioDeviceCreateIOProcID","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioDeviceCreateIOProcID","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AudioObjectID","preciseIdentifier":"c:@T@AudioObjectID","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"AudioDeviceIOProc","preciseIdentifier":"c:@T@AudioDeviceIOProc","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"AudioDeviceIOProcID","preciseIdentifier":"c:@T@AudioDeviceIOProcID","kind":"typeIdentifier"},{"text":"?>) -> ","kind":"text"},{"text":"OSStatus","preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier"}],"url":"/documentation/coreaudio/audiodevicecreateioprocid(_:_:_:_:)","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcID(_:_:_:_:)","abstract":[],"kind":"symbol","role":"symbol","title":"AudioDeviceCreateIOProcID(_:_:_:_:)"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectID":{"navigatorTitle":[{"kind":"identifier","text":"AudioObjectID"}],"url":"/documentation/coreaudio/audioobjectid","title":"AudioObjectID","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AudioObjectID"}],"abstract":[],"kind":"symbol","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectID"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceTranslateTime(_:_:_:)":{"abstract":[],"title":"AudioDeviceTranslateTime(_:_:_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioDeviceTranslateTime"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@AudioObjectID","kind":"typeIdentifier","text":"AudioObjectID"},{"kind":"text","text":", "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@S@AudioTimeStamp","kind":"typeIdentifier","text":"AudioTimeStamp"},{"kind":"text","text":">, "},{"preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@S@AudioTimeStamp","kind":"typeIdentifier","text":"AudioTimeStamp"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier","text":"OSStatus"}],"kind":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceTranslateTime(_:_:_:)","type":"topic","url":"/documentation/coreaudio/audiodevicetranslatetime(_:_:_:)","navigatorTitle":[{"kind":"identifier","text":"AudioDeviceTranslateTime"}]},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareCreateAggregateDevice(_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"AudioHardwareCreateAggregateDevice"}],"url":"/documentation/coreaudio/audiohardwarecreateaggregatedevice(_:_:)","title":"AudioHardwareCreateAggregateDevice(_:_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AudioHardwareCreateAggregateDevice"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@CFDictionaryRef","kind":"typeIdentifier","text":"CFDictionary"},{"kind":"text","text":", "},{"preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectID","text":"AudioObjectID"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus","text":"OSStatus"}],"abstract":[],"kind":"symbol","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareCreateAggregateDevice(_:_:)"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertNanosToHostTime(_:)":{"navigatorTitle":[{"kind":"identifier","text":"AudioConvertNanosToHostTime"}],"url":"/documentation/coreaudio/audioconvertnanostohosttime(_:)","title":"AudioConvertNanosToHostTime(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioConvertNanosToHostTime"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"}],"abstract":[],"kind":"symbol","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertNanosToHostTime(_:)"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetHostClockMinimumTimeDelta()":{"role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetHostClockMinimumTimeDelta()","url":"/documentation/coreaudio/audiogethostclockminimumtimedelta()","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioGetHostClockMinimumTimeDelta"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"}],"navigatorTitle":[{"kind":"identifier","text":"AudioGetHostClockMinimumTimeDelta"}],"title":"AudioGetHostClockMinimumTimeDelta()","type":"topic"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcIDWithBlock(_:_:_:_:)":{"abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioDeviceCreateIOProcIDWithBlock","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@T@AudioDeviceIOProcID","kind":"typeIdentifier","text":"AudioDeviceIOProcID"},{"kind":"text","text":"?>, "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectID","text":"AudioObjectID"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@dispatch_queue_t","text":"dispatch_queue_t"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioDeviceIOBlock","text":"AudioDeviceIOBlock"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus","text":"OSStatus"}],"navigatorTitle":[{"kind":"identifier","text":"AudioDeviceCreateIOProcIDWithBlock"}],"type":"topic","url":"/documentation/coreaudio/audiodevicecreateioprocidwithblock(_:_:_:_:)","title":"AudioDeviceCreateIOProcIDWithBlock(_:_:_:_:)","kind":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcIDWithBlock(_:_:_:_:)"},"doc://com.apple.coreaudio/documentation/CoreAudio":{"kind":"symbol","title":"Core Audio","type":"topic","abstract":[{"type":"text","text":"Use the Core Audio framework to interact with device’s audio hardware."}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio","url":"/documentation/coreaudio","role":"collection"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceSetProperty":{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceSetProperty","url":"/documentation/coreaudio/audiodriverplugindevicesetproperty","title":"AudioDriverPlugInDeviceSetProperty","abstract":[],"fragments":[{"kind":"identifier","text":"AudioDriverPlugInDeviceSetProperty"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceDestroyIOProcID(_:_:)":{"url":"/documentation/coreaudio/audiodevicedestroyioprocid(_:_:)","navigatorTitle":[{"text":"AudioDeviceDestroyIOProcID","kind":"identifier"}],"type":"topic","kind":"symbol","title":"AudioDeviceDestroyIOProcID(_:_:)","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioDeviceDestroyIOProcID"},{"kind":"text","text":"("},{"text":"AudioObjectID","preciseIdentifier":"c:@T@AudioObjectID","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"AudioDeviceIOProcID","preciseIdentifier":"c:@T@AudioDeviceIOProcID","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"OSStatus","preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceDestroyIOProcID(_:_:)"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetHostClockFrequency()":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"AudioGetHostClockFrequency","kind":"identifier"}],"title":"AudioGetHostClockFrequency()","role":"symbol","url":"/documentation/coreaudio/audiogethostclockfrequency()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioGetHostClockFrequency","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Float64","preciseIdentifier":"s:s7Float64a","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetHostClockFrequency()"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","role":"overview","kind":"technologies"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetCurrentTime(_:_:)":{"type":"topic","navigatorTitle":[{"text":"AudioDeviceGetCurrentTime","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioDeviceGetCurrentTime","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AudioObjectID","preciseIdentifier":"c:@T@AudioObjectID","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"AudioTimeStamp","preciseIdentifier":"c:@S@AudioTimeStamp","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"text":"OSStatus","preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier"}],"url":"/documentation/coreaudio/audiodevicegetcurrenttime(_:_:)","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetCurrentTime(_:_:)","abstract":[],"kind":"symbol","role":"symbol","title":"AudioDeviceGetCurrentTime(_:_:)"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceGetProperty":{"abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceGetProperty","url":"/documentation/coreaudio/audiodriverplugindevicegetproperty","title":"AudioDriverPlugInDeviceGetProperty","fragments":[{"text":"AudioDriverPlugInDeviceGetProperty","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetCurrentHostTime()":{"title":"AudioGetCurrentHostTime()","kind":"symbol","role":"symbol","url":"/documentation/coreaudio/audiogetcurrenthosttime()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioGetCurrentHostTime"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AudioGetCurrentHostTime"}],"type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetCurrentHostTime()"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStartAtTime(_:_:_:_:)":{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStartAtTime(_:_:_:_:)","url":"/documentation/coreaudio/audiodevicestartattime(_:_:_:_:)","navigatorTitle":[{"text":"AudioDeviceStartAtTime","kind":"identifier"}],"title":"AudioDeviceStartAtTime(_:_:_:_:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioDeviceStartAtTime"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@AudioObjectID","kind":"typeIdentifier","text":"AudioObjectID"},{"text":", ","kind":"text"},{"text":"AudioDeviceIOProcID","preciseIdentifier":"c:@T@AudioDeviceIOProcID","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"AudioTimeStamp","preciseIdentifier":"c:@S@AudioTimeStamp","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"OSStatus","preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetNearestStartTime(_:_:_:)":{"abstract":[],"title":"AudioDeviceGetNearestStartTime(_:_:_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioDeviceGetNearestStartTime"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@AudioObjectID","kind":"typeIdentifier","text":"AudioObjectID"},{"kind":"text","text":", "},{"preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@S@AudioTimeStamp","kind":"typeIdentifier","text":"AudioTimeStamp"},{"text":">, ","kind":"text"},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"OSStatus","preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetNearestStartTime(_:_:_:)","type":"topic","url":"/documentation/coreaudio/audiodevicegetneareststarttime(_:_:_:)","navigatorTitle":[{"text":"AudioDeviceGetNearestStartTime","kind":"identifier"}]},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStop(_:_:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"AudioDeviceStop","kind":"identifier"}],"title":"AudioDeviceStop(_:_:)","role":"symbol","url":"/documentation/coreaudio/audiodevicestop(_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioDeviceStop","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AudioObjectID","preciseIdentifier":"c:@T@AudioObjectID","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"AudioDeviceIOProcID","preciseIdentifier":"c:@T@AudioDeviceIOProcID","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"OSStatus","preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStop(_:_:)"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceGetPropertyInfo":{"abstract":[],"role":"symbol","fragments":[{"text":"AudioDriverPlugInDeviceGetPropertyInfo","kind":"identifier"}],"type":"topic","url":"/documentation/coreaudio/audiodriverplugindevicegetpropertyinfo","title":"AudioDriverPlugInDeviceGetPropertyInfo","kind":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceGetPropertyInfo"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertHostTimeToNanos(_:)":{"navigatorTitle":[{"kind":"identifier","text":"AudioConvertHostTimeToNanos"}],"abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertHostTimeToNanos(_:)","url":"/documentation/coreaudio/audioconverthosttimetonanos(_:)","title":"AudioConvertHostTimeToNanos(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AudioConvertHostTimeToNanos"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier","text":"UInt64"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier","text":"UInt64"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareDestroyProcessTap(_:)":{"type":"topic","title":"AudioHardwareDestroyProcessTap(_:)","url":"/documentation/coreaudio/audiohardwaredestroyprocesstap(_:)","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareDestroyProcessTap(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioHardwareDestroyProcessTap"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@AudioObjectID","text":"AudioObjectID","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"OSStatus","preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"AudioHardwareDestroyProcessTap","kind":"identifier"}],"role":"symbol","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStart(_:_:)":{"role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStart(_:_:)","url":"/documentation/coreaudio/audiodevicestart(_:_:)","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioDeviceStart"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectID","text":"AudioObjectID"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioDeviceIOProcID","text":"AudioDeviceIOProcID"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus","text":"OSStatus"}],"navigatorTitle":[{"kind":"identifier","text":"AudioDeviceStart"}],"title":"AudioDeviceStart(_:_:)","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"unavailable":false,"name":"macOS","introducedAt":"14.2","beta":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Function","path":"/metadata/roleHeading","op":"replace"},{"value":"AudioHardwareDestroyProcessTap","path":"/metadata/title","op":"replace"},{"value":"func","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"AudioHardwareDestroyProcessTap","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coreaudio/documentation/CoreAudio"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"generated":true,"title":"Functions","anchor":"Functions","identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertHostTimeToNanos(_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertNanosToHostTime(_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcID(_:_:_:_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcIDWithBlock(_:_:_:_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceDestroyIOProcID(_:_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetCurrentTime(_:_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetNearestStartTime(_:_:_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStart(_:_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStartAtTime(_:_:_:_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStop(_:_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceTranslateTime(_:_:_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInClose","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceGetProperty","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceGetPropertyInfo","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceSetProperty"]}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus","text":"OSStatus"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioHardwareDestroyProcessTap"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectID","text":"AudioObjectID","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectID"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inTapID"},{"kind":"text","text":");"}],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceCreateIOProcID(_:_:_:_:)/title","value":"AudioDeviceCreateIOProcID"},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceCreateIOProcID(_:_:_:_:)/fragments","value":[{"text":"AudioDeviceCreateIOProcID","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectID/title","value":"AudioObjectID"},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectID/fragments","value":[{"text":"AudioObjectID","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectID/navigatorTitle","value":[{"kind":"identifier","text":"AudioObjectID"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceTranslateTime(_:_:_:)/title","value":"AudioDeviceTranslateTime"},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceTranslateTime(_:_:_:)/fragments","value":[{"kind":"identifier","text":"AudioDeviceTranslateTime"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareCreateAggregateDevice(_:_:)/title","value":"AudioHardwareCreateAggregateDevice"},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareCreateAggregateDevice(_:_:)/fragments","value":[{"text":"AudioHardwareCreateAggregateDevice","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioConvertNanosToHostTime(_:)/title","value":"AudioConvertNanosToHostTime"},{"value":[{"text":"AudioConvertNanosToHostTime","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioConvertNanosToHostTime(_:)/fragments"},{"value":"AudioGetHostClockMinimumTimeDelta","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioGetHostClockMinimumTimeDelta()/title"},{"value":[{"text":"AudioGetHostClockMinimumTimeDelta","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioGetHostClockMinimumTimeDelta()/fragments"},{"value":"AudioDeviceCreateIOProcIDWithBlock","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceCreateIOProcIDWithBlock(_:_:_:_:)/title"},{"value":[{"text":"AudioDeviceCreateIOProcIDWithBlock","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceCreateIOProcIDWithBlock(_:_:_:_:)/fragments"},{"value":"AudioDeviceDestroyIOProcID","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceDestroyIOProcID(_:_:)/title"},{"value":[{"kind":"identifier","text":"AudioDeviceDestroyIOProcID"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceDestroyIOProcID(_:_:)/fragments"},{"value":"AudioGetHostClockFrequency","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioGetHostClockFrequency()/title"},{"value":[{"kind":"identifier","text":"AudioGetHostClockFrequency"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioGetHostClockFrequency()/fragments"},{"value":"AudioDeviceGetCurrentTime","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceGetCurrentTime(_:_:)/title"},{"value":[{"text":"AudioDeviceGetCurrentTime","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceGetCurrentTime(_:_:)/fragments"},{"value":"AudioGetCurrentHostTime","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioGetCurrentHostTime()/title"},{"value":[{"kind":"identifier","text":"AudioGetCurrentHostTime"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioGetCurrentHostTime()/fragments"},{"value":"AudioDeviceStartAtTime","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceStartAtTime(_:_:_:_:)/title"},{"value":[{"kind":"identifier","text":"AudioDeviceStartAtTime"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceStartAtTime(_:_:_:_:)/fragments"},{"value":"AudioDeviceGetNearestStartTime","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceGetNearestStartTime(_:_:_:)/title"},{"value":[{"text":"AudioDeviceGetNearestStartTime","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceGetNearestStartTime(_:_:_:)/fragments"},{"value":"AudioDeviceStop","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceStop(_:_:)/title"},{"value":[{"text":"AudioDeviceStop","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceStop(_:_:)/fragments"},{"value":"AudioConvertHostTimeToNanos","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioConvertHostTimeToNanos(_:)/title"},{"value":[{"text":"AudioConvertHostTimeToNanos","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioConvertHostTimeToNanos(_:)/fragments"},{"value":"AudioHardwareDestroyProcessTap","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareDestroyProcessTap(_:)/title"},{"value":[{"kind":"identifier","text":"AudioHardwareDestroyProcessTap"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareDestroyProcessTap(_:)/fragments"},{"value":"AudioDeviceStart","op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceStart(_:_:)/title"},{"value":[{"kind":"identifier","text":"AudioDeviceStart"}],"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceStart(_:_:)/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}