{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePowerHint"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AudioHardwarePowerHint",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AudioHardwarePowerHint"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AudioHardwarePowerHint"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "AudioHardwarePowerHint"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioHardwarePowerHint"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580715-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580719-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580720-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580722-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580723-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580726-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580731-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580736-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580737-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580740-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580741-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580746-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580747-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580748-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580749-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePowerHint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwarePowerHint"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePowerHint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwarePowerHint"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwarePowerHint",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwarepowerhint"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePowerHint/favorSavingPower": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "favorSavingPower"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePowerHint/favorSavingPower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwarePowerHintFavorSavingPower"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwarePowerHint.favorSavingPower",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwarepowerhint/favorsavingpower"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePowerHint/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePowerHint/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwarepowerhint/init(rawvalue:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePowerHint/none": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePowerHint/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwarePowerHintNone"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwarePowerHint.none",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwarepowerhint/none"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePowerHint/favorSavingPower",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePowerHint/none"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePowerHint/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AudioHardwarePowerHint"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwarePowerHint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwarePowerHint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudio/documentation/CoreAudio"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePowerHint/favorSavingPower",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePowerHint/none"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AudioHardwarePowerHint"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@UInt32",
                    "text": "UInt32"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwarePowerHint~1favorSavingPower/title",
          "value": "kAudioHardwarePowerHintFavorSavingPower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwarePowerHint~1favorSavingPower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwarePowerHintFavorSavingPower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwarePowerHint~1none/title",
          "value": "kAudioHardwarePowerHintNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwarePowerHint~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwarePowerHintNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwarePowerHint/title",
          "value": "AudioHardwarePowerHint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwarePowerHint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwarePowerHint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwarePowerHint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwarePowerHint"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/audiohardwarepowerhint"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/audiohardwarepowerhint"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
