{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coreaudio/documentation/CoreAudio"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInStreamGetProperty"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/coreaudio/audiodriverpluginstreamgetproperty"]}],"kind":"symbol","seeAlsoSections":[{"anchor":"Functions","title":"Functions","identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertHostTimeToNanos(_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertNanosToHostTime(_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcID(_:_:_:_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcIDWithBlock(_:_:_:_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceDestroyIOProcID(_:_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetCurrentTime(_:_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetNearestStartTime(_:_:_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStart(_:_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStartAtTime(_:_:_:_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStop(_:_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceTranslateTime(_:_:_:)","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInClose","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceGetProperty","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceGetPropertyInfo","doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceSetProperty"],"generated":true}],"metadata":{"platforms":[{"unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst"},{"unavailable":false,"beta":false,"deprecated":false,"name":"macOS"}],"roleHeading":"Function","role":"symbol","symbolKind":"func","fragments":[{"kind":"identifier","text":"AudioDriverPlugInStreamGetProperty"}],"externalID":"c:@F@AudioDriverPlugInStreamGetProperty","modules":[{"name":"Core Audio"}],"navigatorTitle":[{"kind":"identifier","text":"AudioDriverPlugInStreamGetProperty"}],"title":"AudioDriverPlugInStreamGetProperty"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@T@OSStatus","text":"OSStatus","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"AudioDriverPlugInStreamGetProperty","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@AudioDeviceID","kind":"typeIdentifier","text":"AudioDeviceID","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceID"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inDevice"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@T@io_object_t","kind":"typeIdentifier","text":"io_object_t","identifier":"doc://com.externally.resolved.symbol/c:@T@io_object_t"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inIOAudioStream"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@UInt32","text":"UInt32"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inChannel"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioDevicePropertyID","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDevicePropertyID","text":"AudioDevicePropertyID"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inPropertyID"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@T@UInt32","text":"UInt32","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"ioPropertyDataSize","kind":"internalParam"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"outPropertyData"},{"kind":"text","text":");"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"}],"references":{"doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertHostTimeToNanos(_:)":{"navigatorTitle":[{"kind":"identifier","text":"AudioConvertHostTimeToNanos"}],"abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertHostTimeToNanos(_:)","url":"/documentation/coreaudio/audioconverthosttimetonanos(_:)","title":"AudioConvertHostTimeToNanos(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AudioConvertHostTimeToNanos"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier","text":"UInt64"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier","text":"UInt64"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceTranslateTime(_:_:_:)":{"abstract":[],"title":"AudioDeviceTranslateTime(_:_:_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioDeviceTranslateTime"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@AudioObjectID","kind":"typeIdentifier","text":"AudioObjectID"},{"kind":"text","text":", "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@S@AudioTimeStamp","kind":"typeIdentifier","text":"AudioTimeStamp"},{"kind":"text","text":">, "},{"preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@S@AudioTimeStamp","kind":"typeIdentifier","text":"AudioTimeStamp"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier","text":"OSStatus"}],"kind":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceTranslateTime(_:_:_:)","type":"topic","url":"/documentation/coreaudio/audiodevicetranslatetime(_:_:_:)","navigatorTitle":[{"kind":"identifier","text":"AudioDeviceTranslateTime"}]},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStartAtTime(_:_:_:_:)":{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStartAtTime(_:_:_:_:)","url":"/documentation/coreaudio/audiodevicestartattime(_:_:_:_:)","navigatorTitle":[{"text":"AudioDeviceStartAtTime","kind":"identifier"}],"title":"AudioDeviceStartAtTime(_:_:_:_:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioDeviceStartAtTime"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@AudioObjectID","kind":"typeIdentifier","text":"AudioObjectID"},{"text":", ","kind":"text"},{"text":"AudioDeviceIOProcID","preciseIdentifier":"c:@T@AudioDeviceIOProcID","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"AudioTimeStamp","preciseIdentifier":"c:@S@AudioTimeStamp","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"OSStatus","preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcIDWithBlock(_:_:_:_:)":{"abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioDeviceCreateIOProcIDWithBlock","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@T@AudioDeviceIOProcID","kind":"typeIdentifier","text":"AudioDeviceIOProcID"},{"kind":"text","text":"?>, "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectID","text":"AudioObjectID"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@dispatch_queue_t","text":"dispatch_queue_t"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioDeviceIOBlock","text":"AudioDeviceIOBlock"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus","text":"OSStatus"}],"navigatorTitle":[{"kind":"identifier","text":"AudioDeviceCreateIOProcIDWithBlock"}],"type":"topic","url":"/documentation/coreaudio/audiodevicecreateioprocidwithblock(_:_:_:_:)","title":"AudioDeviceCreateIOProcIDWithBlock(_:_:_:_:)","kind":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcIDWithBlock(_:_:_:_:)"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertNanosToHostTime(_:)":{"navigatorTitle":[{"kind":"identifier","text":"AudioConvertNanosToHostTime"}],"url":"/documentation/coreaudio/audioconvertnanostohosttime(_:)","title":"AudioConvertNanosToHostTime(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioConvertNanosToHostTime"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"}],"abstract":[],"kind":"symbol","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertNanosToHostTime(_:)"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetNearestStartTime(_:_:_:)":{"abstract":[],"title":"AudioDeviceGetNearestStartTime(_:_:_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioDeviceGetNearestStartTime"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@AudioObjectID","kind":"typeIdentifier","text":"AudioObjectID"},{"kind":"text","text":", "},{"preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@S@AudioTimeStamp","kind":"typeIdentifier","text":"AudioTimeStamp"},{"text":">, ","kind":"text"},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"OSStatus","preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetNearestStartTime(_:_:_:)","type":"topic","url":"/documentation/coreaudio/audiodevicegetneareststarttime(_:_:_:)","navigatorTitle":[{"text":"AudioDeviceGetNearestStartTime","kind":"identifier"}]},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDevicePropertyID":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AudioDevicePropertyID"}],"kind":"symbol","title":"AudioDevicePropertyID","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDevicePropertyID","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AudioDevicePropertyID"}],"url":"/documentation/coreaudio/audiodevicepropertyid","type":"topic","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio":{"kind":"symbol","title":"Core Audio","type":"topic","abstract":[{"type":"text","text":"Use the Core Audio framework to interact with device’s audio hardware."}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio","url":"/documentation/coreaudio","role":"collection"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInStreamGetProperty":{"type":"topic","url":"/documentation/coreaudio/audiodriverpluginstreamgetproperty","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInStreamGetProperty","title":"AudioDriverPlugInStreamGetProperty","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"AudioDriverPlugInStreamGetProperty","kind":"identifier"}]},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceGetProperty":{"abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceGetProperty","url":"/documentation/coreaudio/audiodriverplugindevicegetproperty","title":"AudioDriverPlugInDeviceGetProperty","fragments":[{"text":"AudioDriverPlugInDeviceGetProperty","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","role":"overview","kind":"technologies"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcID(_:_:_:_:)":{"type":"topic","navigatorTitle":[{"text":"AudioDeviceCreateIOProcID","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioDeviceCreateIOProcID","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AudioObjectID","preciseIdentifier":"c:@T@AudioObjectID","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"AudioDeviceIOProc","preciseIdentifier":"c:@T@AudioDeviceIOProc","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"AudioDeviceIOProcID","preciseIdentifier":"c:@T@AudioDeviceIOProcID","kind":"typeIdentifier"},{"text":"?>) -> ","kind":"text"},{"text":"OSStatus","preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier"}],"url":"/documentation/coreaudio/audiodevicecreateioprocid(_:_:_:_:)","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcID(_:_:_:_:)","abstract":[],"kind":"symbol","role":"symbol","title":"AudioDeviceCreateIOProcID(_:_:_:_:)"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceSetProperty":{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceSetProperty","url":"/documentation/coreaudio/audiodriverplugindevicesetproperty","title":"AudioDriverPlugInDeviceSetProperty","abstract":[],"fragments":[{"kind":"identifier","text":"AudioDriverPlugInDeviceSetProperty"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceDestroyIOProcID(_:_:)":{"url":"/documentation/coreaudio/audiodevicedestroyioprocid(_:_:)","navigatorTitle":[{"text":"AudioDeviceDestroyIOProcID","kind":"identifier"}],"type":"topic","kind":"symbol","title":"AudioDeviceDestroyIOProcID(_:_:)","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioDeviceDestroyIOProcID"},{"kind":"text","text":"("},{"text":"AudioObjectID","preciseIdentifier":"c:@T@AudioObjectID","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"AudioDeviceIOProcID","preciseIdentifier":"c:@T@AudioDeviceIOProcID","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"OSStatus","preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceDestroyIOProcID(_:_:)"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStart(_:_:)":{"role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStart(_:_:)","url":"/documentation/coreaudio/audiodevicestart(_:_:)","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioDeviceStart"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectID","text":"AudioObjectID"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioDeviceIOProcID","text":"AudioDeviceIOProcID"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus","text":"OSStatus"}],"navigatorTitle":[{"kind":"identifier","text":"AudioDeviceStart"}],"title":"AudioDeviceStart(_:_:)","type":"topic"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInClose":{"url":"/documentation/coreaudio/audiodriverpluginclose","type":"topic","kind":"symbol","title":"AudioDriverPlugInClose","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"AudioDriverPlugInClose"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInClose"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceGetPropertyInfo":{"abstract":[],"role":"symbol","fragments":[{"text":"AudioDriverPlugInDeviceGetPropertyInfo","kind":"identifier"}],"type":"topic","url":"/documentation/coreaudio/audiodriverplugindevicegetpropertyinfo","title":"AudioDriverPlugInDeviceGetPropertyInfo","kind":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceGetPropertyInfo"},"doc://com.externally.resolved.symbol/c:@T@io_object_t":{"type":"topic","identifier":"doc://com.externally.resolved.symbol/c:@T@io_object_t","kind":"symbol","url":"/documentation/iokit/io_object_t","role":"symbol","title":"io_object_t","abstract":[{"type":"text","text":""}],"fragments":[{"text":"typealias ","kind":"text"},{"text":"io_object_t","kind":"identifier"}]},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStop(_:_:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"AudioDeviceStop","kind":"identifier"}],"title":"AudioDeviceStop(_:_:)","role":"symbol","url":"/documentation/coreaudio/audiodevicestop(_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioDeviceStop","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AudioObjectID","preciseIdentifier":"c:@T@AudioObjectID","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"AudioDeviceIOProcID","preciseIdentifier":"c:@T@AudioDeviceIOProcID","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"OSStatus","preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStop(_:_:)"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetCurrentTime(_:_:)":{"type":"topic","navigatorTitle":[{"text":"AudioDeviceGetCurrentTime","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioDeviceGetCurrentTime","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AudioObjectID","preciseIdentifier":"c:@T@AudioObjectID","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"AudioTimeStamp","preciseIdentifier":"c:@S@AudioTimeStamp","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"text":"OSStatus","preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier"}],"url":"/documentation/coreaudio/audiodevicegetcurrenttime(_:_:)","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetCurrentTime(_:_:)","abstract":[],"kind":"symbol","role":"symbol","title":"AudioDeviceGetCurrentTime(_:_:)"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceID":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AudioDeviceID"}],"kind":"symbol","title":"AudioDeviceID","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceID","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AudioDeviceID"}],"url":"/documentation/coreaudio/audiodeviceid","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioConvertHostTimeToNanos(_:)/title","value":"AudioConvertHostTimeToNanos"},{"op":"replace","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioConvertHostTimeToNanos(_:)/fragments","value":[{"text":"AudioConvertHostTimeToNanos","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceTranslateTime(_:_:_:)/title","op":"replace","value":"AudioDeviceTranslateTime"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceTranslateTime(_:_:_:)/fragments","op":"replace","value":[{"text":"AudioDeviceTranslateTime","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceStartAtTime(_:_:_:_:)/title","op":"replace","value":"AudioDeviceStartAtTime"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceStartAtTime(_:_:_:_:)/fragments","op":"replace","value":[{"kind":"identifier","text":"AudioDeviceStartAtTime"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceCreateIOProcIDWithBlock(_:_:_:_:)/title","op":"replace","value":"AudioDeviceCreateIOProcIDWithBlock"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceCreateIOProcIDWithBlock(_:_:_:_:)/fragments","op":"replace","value":[{"text":"AudioDeviceCreateIOProcIDWithBlock","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioConvertNanosToHostTime(_:)/title","op":"replace","value":"AudioConvertNanosToHostTime"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioConvertNanosToHostTime(_:)/fragments","op":"replace","value":[{"text":"AudioConvertNanosToHostTime","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceGetNearestStartTime(_:_:_:)/title","op":"replace","value":"AudioDeviceGetNearestStartTime"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceGetNearestStartTime(_:_:_:)/fragments","op":"replace","value":[{"kind":"identifier","text":"AudioDeviceGetNearestStartTime"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDevicePropertyID/title","op":"replace","value":"AudioDevicePropertyID"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDevicePropertyID/fragments","op":"replace","value":[{"text":"AudioDevicePropertyID","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDevicePropertyID/navigatorTitle","op":"replace","value":[{"text":"AudioDevicePropertyID","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceCreateIOProcID(_:_:_:_:)/title","op":"replace","value":"AudioDeviceCreateIOProcID"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceCreateIOProcID(_:_:_:_:)/fragments","op":"replace","value":[{"text":"AudioDeviceCreateIOProcID","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceDestroyIOProcID(_:_:)/title","op":"replace","value":"AudioDeviceDestroyIOProcID"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceDestroyIOProcID(_:_:)/fragments","op":"replace","value":[{"text":"AudioDeviceDestroyIOProcID","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceStart(_:_:)/title","op":"replace","value":"AudioDeviceStart"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceStart(_:_:)/fragments","op":"replace","value":[{"text":"AudioDeviceStart","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceStop(_:_:)/title","op":"replace","value":"AudioDeviceStop"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceStop(_:_:)/fragments","op":"replace","value":[{"kind":"identifier","text":"AudioDeviceStop"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceGetCurrentTime(_:_:)/title","op":"replace","value":"AudioDeviceGetCurrentTime"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceGetCurrentTime(_:_:)/fragments","op":"replace","value":[{"kind":"identifier","text":"AudioDeviceGetCurrentTime"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceID/title","op":"replace","value":"AudioDeviceID"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceID/fragments","op":"replace","value":[{"kind":"identifier","text":"AudioDeviceID"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceID/navigatorTitle","op":"replace","value":[{"text":"AudioDeviceID","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}