{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareIOProcStreamUsage"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@AudioHardwareIOProcStreamUsage",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AudioHardwareIOProcStreamUsage"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AudioHardwareIOProcStreamUsage"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AudioHardwareIOProcStreamUsage"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioHardwareIOProcStreamUsage"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDriverPlugInHostInfo"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDriverPlugInHostInfo",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodriverpluginhostinfo"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareIOProcStreamUsage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareIOProcStreamUsage"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareIOProcStreamUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareIOProcStreamUsage"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareIOProcStreamUsage",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwareioprocstreamusage"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareIOProcStreamUsage/init(mIOProc:mNumberStreams:mStreamIsOn:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "mIOProc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mNumberStreams"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mStreamIsOn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareIOProcStreamUsage/init(mIOProc:mNumberStreams:mStreamIsOn:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(mIOProc:mNumberStreams:mStreamIsOn:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwareioprocstreamusage/init(mioproc:mnumberstreams:mstreamison:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareIOProcStreamUsage/mIOProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mIOProc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareIOProcStreamUsage/mIOProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mIOProc"
        }
      ],
      "role": "symbol",
      "title": "mIOProc",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwareioprocstreamusage/mioproc"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareIOProcStreamUsage/mNumberStreams": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mNumberStreams"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareIOProcStreamUsage/mNumberStreams",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mNumberStreams"
        }
      ],
      "role": "symbol",
      "title": "mNumberStreams",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwareioprocstreamusage/mnumberstreams"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareIOProcStreamUsage/mStreamIsOn": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mStreamIsOn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareIOProcStreamUsage/mStreamIsOn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mStreamIsOn"
        }
      ],
      "role": "symbol",
      "title": "mStreamIsOn",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwareioprocstreamusage/mstreamison"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyAddress"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyAddress"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertyAddress",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertyaddress"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInClientInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioServerPlugInClientInfo"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInClientInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioServerPlugInClientInfo",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverpluginclientinfo"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInCustomPropertyInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioServerPlugInCustomPropertyInfo"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInCustomPropertyInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioServerPlugInCustomPropertyInfo",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugincustompropertyinfo"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioServerPlugInDriverInterface"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioServerPlugInDriverInterface",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugindriverinterface"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInHostInterface": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioServerPlugInHostInterface"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInHostInterface",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioServerPlugInHostInterface",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverpluginhostinterface"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioServerPlugInIOCycleInfo"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioServerPlugInIOCycleInfo",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverpluginiocycleinfo"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRangedDescription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioStreamRangedDescription"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRangedDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioStreamRangedDescription"
        }
      ],
      "role": "symbol",
      "title": "AudioStreamRangedDescription",
      "type": "topic",
      "url": "/documentation/coreaudio/audiostreamrangeddescription"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/UnsafeMutableAudioBufferListPointer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutableAudioBufferListPointer"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/UnsafeMutableAudioBufferListPointer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UnsafeMutableAudioBufferListPointer"
        }
      ],
      "role": "symbol",
      "title": "UnsafeMutableAudioBufferListPointer",
      "type": "topic",
      "url": "/documentation/coreaudio/unsafemutableaudiobufferlistpointer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyAddress",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRangedDescription",
        "doc://com.apple.coreaudio/documentation/CoreAudio/UnsafeMutableAudioBufferListPointer"
      ],
      "title": "Structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareIOProcStreamUsage/init(mIOProc:mNumberStreams:mStreamIsOn:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareIOProcStreamUsage/mIOProc",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareIOProcStreamUsage/mNumberStreams",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareIOProcStreamUsage/mStreamIsOn"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AudioHardwareIOProcStreamUsage"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwareIOProcStreamUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwareIOProcStreamUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudio/documentation/CoreAudio"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareIOProcStreamUsage/mIOProc",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareIOProcStreamUsage/mNumberStreams",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareIOProcStreamUsage/mStreamIsOn"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Structures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyAddress",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInClientInfo",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInCustomPropertyInfo",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInHostInterface",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRangedDescription"
              ],
              "title": "Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AudioHardwareIOProcStreamUsage"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareIOProcStreamUsage~1mNumberStreams/title",
          "value": "mNumberStreams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareIOProcStreamUsage~1mNumberStreams/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mNumberStreams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareIOProcStreamUsage~1mStreamIsOn/title",
          "value": "mStreamIsOn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareIOProcStreamUsage~1mStreamIsOn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mStreamIsOn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareIOProcStreamUsage~1mIOProc/title",
          "value": "mIOProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareIOProcStreamUsage~1mIOProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mIOProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamRangedDescription/title",
          "value": "AudioStreamRangedDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamRangedDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamRangedDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamRangedDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamRangedDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareIOProcStreamUsage/title",
          "value": "AudioHardwareIOProcStreamUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareIOProcStreamUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwareIOProcStreamUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareIOProcStreamUsage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwareIOProcStreamUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyAddress/title",
          "value": "AudioObjectPropertyAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyAddress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyAddress"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/audiohardwareioprocstreamusage"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/audiohardwareioprocstreamusage"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
