{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AudioLevelControlTransferFunction",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AudioLevelControlTransferFunction"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AudioLevelControlTransferFunction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "AudioLevelControlTransferFunction"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioLevelControlTransferFunction"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580715-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580719-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580720-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580722-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580723-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580726-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580731-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580736-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580737-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580740-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580741-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580746-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580747-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580748-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580749-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioLevelControlTransferFunction"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioLevelControlTransferFunction"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/init(rawvalue:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction10Over1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction10Over1"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction10Over1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction10Over1"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction10Over1",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction10over1"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction11Over1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction11Over1"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction11Over1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction11Over1"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction11Over1",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction11over1"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction12Over1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction12Over1"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction12Over1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction12Over1"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction12Over1",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction12over1"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction1Over2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction1Over2"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction1Over2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction1Over2"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction1Over2",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction1over2"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction1Over3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction1Over3"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction1Over3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction1Over3"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction1Over3",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction1over3"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction2Over1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction2Over1"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction2Over1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction2Over1"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction2Over1",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction2over1"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction3Over1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction3Over1"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction3Over1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction3Over1"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction3Over1",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction3over1"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction3Over2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction3Over2"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction3Over2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction3Over2"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction3Over2",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction3over2"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction3Over4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction3Over4"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction3Over4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction3Over4"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction3Over4",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction3over4"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction4Over1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction4Over1"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction4Over1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction4Over1"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction4Over1",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction4over1"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction5Over1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction5Over1"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction5Over1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction5Over1"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction5Over1",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction5over1"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction6Over1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction6Over1"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction6Over1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction6Over1"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction6Over1",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction6over1"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction7Over1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction7Over1"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction7Over1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction7Over1"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction7Over1",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction7over1"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction8Over1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction8Over1"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction8Over1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction8Over1"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction8Over1",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction8over1"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction9Over1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction9Over1"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction9Over1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction9Over1"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction9Over1",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction9over1"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunctionLinear": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunctionLinear"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunctionLinear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunctionLinear"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunctionLinear",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunctionlinear"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction10Over1",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction11Over1",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction12Over1",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction1Over2",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction1Over3",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction2Over1",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction3Over1",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction3Over2",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction3Over4",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction4Over1",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction5Over1",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction6Over1",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction7Over1",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction8Over1",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction9Over1",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunctionLinear"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AudioLevelControlTransferFunction"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioLevelControlTransferFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioLevelControlTransferFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudio/documentation/CoreAudio"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction10Over1",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction11Over1",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction12Over1",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction1Over2",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction1Over3",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction2Over1",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction3Over1",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction3Over2",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction3Over4",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction4Over1",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction5Over1",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction6Over1",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction7Over1",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction8Over1",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction9Over1",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunctionLinear"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AudioLevelControlTransferFunction"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@UInt32",
                    "text": "UInt32"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction10Over1/title",
          "value": "kAudioLevelControlTranferFunction10Over1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction10Over1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction10Over1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction12Over1/title",
          "value": "kAudioLevelControlTranferFunction12Over1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction12Over1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction12Over1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunctionLinear/title",
          "value": "kAudioLevelControlTranferFunctionLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunctionLinear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunctionLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction1Over2/title",
          "value": "kAudioLevelControlTranferFunction1Over2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction1Over2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction1Over2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction/title",
          "value": "AudioLevelControlTransferFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioLevelControlTransferFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioLevelControlTransferFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction7Over1/title",
          "value": "kAudioLevelControlTranferFunction7Over1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction7Over1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction7Over1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction9Over1/title",
          "value": "kAudioLevelControlTranferFunction9Over1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction9Over1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction9Over1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction6Over1/title",
          "value": "kAudioLevelControlTranferFunction6Over1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction6Over1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction6Over1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction1Over3/title",
          "value": "kAudioLevelControlTranferFunction1Over3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction1Over3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction1Over3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction5Over1/title",
          "value": "kAudioLevelControlTranferFunction5Over1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction5Over1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction5Over1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction3Over4/title",
          "value": "kAudioLevelControlTranferFunction3Over4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction3Over4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction3Over4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction4Over1/title",
          "value": "kAudioLevelControlTranferFunction4Over1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction4Over1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction4Over1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction3Over2/title",
          "value": "kAudioLevelControlTranferFunction3Over2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction3Over2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction3Over2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction2Over1/title",
          "value": "kAudioLevelControlTranferFunction2Over1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction2Over1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction2Over1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction3Over1/title",
          "value": "kAudioLevelControlTranferFunction3Over1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction3Over1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction3Over1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction8Over1/title",
          "value": "kAudioLevelControlTranferFunction8Over1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction8Over1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction8Over1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction11Over1/title",
          "value": "kAudioLevelControlTranferFunction11Over1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction11Over1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction11Over1"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/audiolevelcontroltransferfunction"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/audiolevelcontroltransferfunction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
