{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-data-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Core Audio Data Types"
  },
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioClassID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioClassID"
        }
      ],
      "role": "symbol",
      "title": "AudioClassID",
      "type": "topic",
      "url": "/documentation/coreaudio/audioclassid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDeviceID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDeviceID"
        }
      ],
      "role": "symbol",
      "title": "AudioDeviceID",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodeviceid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceIOBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDeviceIOBlock"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceIOBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDeviceIOBlock"
        }
      ],
      "role": "symbol",
      "title": "AudioDeviceIOBlock",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodeviceioblock"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceIOProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDeviceIOProc"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceIOProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDeviceIOProc"
        }
      ],
      "role": "symbol",
      "title": "AudioDeviceIOProc",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodeviceioproc"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceIOProcID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDeviceIOProcID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceIOProcID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDeviceIOProcID"
        }
      ],
      "role": "symbol",
      "title": "AudioDeviceIOProcID",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodeviceioprocid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDevicePropertyID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDevicePropertyID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDevicePropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDevicePropertyID"
        }
      ],
      "role": "symbol",
      "title": "AudioDevicePropertyID",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicepropertyid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDevicePropertyListenerProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDevicePropertyListenerProc"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDevicePropertyListenerProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDevicePropertyListenerProc"
        }
      ],
      "role": "symbol",
      "title": "AudioDevicePropertyListenerProc",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicepropertylistenerproc"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDevicePropertyChangedProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDriverPlugInDevicePropertyChangedProc"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDevicePropertyChangedProc",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDriverPlugInDevicePropertyChangedProc",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodriverplugindevicepropertychangedproc"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInStreamPropertyChangedProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDriverPlugInStreamPropertyChangedProc"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInStreamPropertyChangedProc",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDriverPlugInStreamPropertyChangedProc",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodriverpluginstreampropertychangedproc"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePropertyID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwarePropertyID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePropertyID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwarePropertyID"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwarePropertyID",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwarepropertyid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePropertyListenerProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwarePropertyListenerProc"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePropertyListenerProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwarePropertyListenerProc"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwarePropertyListenerProc",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwarepropertylistenerproc"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectID"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectID",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyElement": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyElement"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyElement"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertyElement",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertyelement"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyListenerBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyListenerBlock"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyListenerBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyListenerBlock"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertyListenerBlock",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertylistenerblock"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyListenerProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyListenerProc"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyListenerProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyListenerProc"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertyListenerProc",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertylistenerproc"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyScope": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyScope"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyScope",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyScope"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertyScope",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertyscope"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertySelector",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertyselector"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInCustomPropertyDataType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioServerPlugInCustomPropertyDataType"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInCustomPropertyDataType",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioServerPlugInCustomPropertyDataType",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugincustompropertydatatype"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverRef": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioServerPlugInDriverRef"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioServerPlugInDriverRef",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugindriverref"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInHostRef": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioServerPlugInHostRef"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInHostRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioServerPlugInHostRef",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverpluginhostref"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioStreamID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioStreamID"
        }
      ],
      "role": "symbol",
      "title": "AudioStreamID",
      "type": "topic",
      "url": "/documentation/coreaudio/audiostreamid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamPropertyListenerProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioStreamPropertyListenerProc"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamPropertyListenerProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioStreamPropertyListenerProc"
        }
      ],
      "role": "symbol",
      "title": "AudioStreamPropertyListenerProc",
      "type": "topic",
      "url": "/documentation/coreaudio/audiostreampropertylistenerproc"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio Constants",
      "type": "topic",
      "url": "/documentation/coreaudio/core-audio-constants"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio Enumerations",
      "type": "topic",
      "url": "/documentation/coreaudio/core-audio-enumerations"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio Functions",
      "type": "topic",
      "url": "/documentation/coreaudio/core-audio-functions"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio Structures",
      "type": "topic",
      "url": "/documentation/coreaudio/core-audio-structures"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-structures",
        "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-functions",
        "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-constants",
        "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioClassID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceIOBlock",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceIOProc",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceIOProcID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDevicePropertyID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDevicePropertyListenerProc",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePropertyID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePropertyListenerProc",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyElement",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyListenerBlock",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyListenerProc",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyScope",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamPropertyListenerProc"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioClassID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceIOBlock",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceIOProc",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceIOProcID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDevicePropertyID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDevicePropertyListenerProc",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDevicePropertyChangedProc",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInStreamPropertyChangedProc",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePropertyID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePropertyListenerProc",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyElement",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyListenerBlock",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyListenerProc",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyScope",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInCustomPropertyDataType",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverRef",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInHostRef",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamPropertyListenerProc"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-structures",
                "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-functions",
                "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-constants",
                "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDevicePropertyID/title",
          "value": "AudioDevicePropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDevicePropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDevicePropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDevicePropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDevicePropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyListenerProc/title",
          "value": "AudioObjectPropertyListenerProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyListenerProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyListenerProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyListenerProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyListenerProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyElement/title",
          "value": "AudioObjectPropertyElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyScope/title",
          "value": "AudioObjectPropertyScope"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyScope/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyScope/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamID/title",
          "value": "AudioStreamID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyListenerBlock/title",
          "value": "AudioObjectPropertyListenerBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyListenerBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyListenerBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyListenerBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyListenerBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDevicePropertyListenerProc/title",
          "value": "AudioDevicePropertyListenerProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDevicePropertyListenerProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDevicePropertyListenerProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDevicePropertyListenerProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDevicePropertyListenerProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceIOProc/title",
          "value": "AudioDeviceIOProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceIOProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceIOProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceIOProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceIOProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceIOProcID/title",
          "value": "AudioDeviceIOProcID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceIOProcID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceIOProcID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceIOProcID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceIOProcID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwarePropertyListenerProc/title",
          "value": "AudioHardwarePropertyListenerProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwarePropertyListenerProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwarePropertyListenerProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwarePropertyListenerProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwarePropertyListenerProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceIOBlock/title",
          "value": "AudioDeviceIOBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceIOBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceIOBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceIOBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceIOBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwarePropertyID/title",
          "value": "AudioHardwarePropertyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwarePropertyID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwarePropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwarePropertyID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwarePropertyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioClassID/title",
          "value": "AudioClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioClassID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectID/title",
          "value": "AudioObjectID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamPropertyListenerProc/title",
          "value": "AudioStreamPropertyListenerProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamPropertyListenerProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamPropertyListenerProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamPropertyListenerProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamPropertyListenerProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/title",
          "value": "AudioObjectPropertySelector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceID/title",
          "value": "AudioDeviceID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/core-audio-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/core-audio-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
