{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-structures"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Core Audio Structures"
  },
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDriverPlugInHostInfo"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDriverPlugInHostInfo",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodriverpluginhostinfo"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareIOProcStreamUsage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareIOProcStreamUsage"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareIOProcStreamUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareIOProcStreamUsage"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareIOProcStreamUsage",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwareioprocstreamusage"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyAddress"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertyAddress"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertyAddress",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertyaddress"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInClientInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioServerPlugInClientInfo"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInClientInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioServerPlugInClientInfo",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverpluginclientinfo"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInCustomPropertyInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioServerPlugInCustomPropertyInfo"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInCustomPropertyInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioServerPlugInCustomPropertyInfo",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugincustompropertyinfo"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioServerPlugInDriverInterface"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioServerPlugInDriverInterface",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverplugindriverinterface"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInHostInterface": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioServerPlugInHostInterface"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInHostInterface",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioServerPlugInHostInterface",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverpluginhostinterface"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioServerPlugInIOCycleInfo"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioServerPlugInIOCycleInfo",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverpluginiocycleinfo"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRangedDescription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioStreamRangedDescription"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRangedDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioStreamRangedDescription"
        }
      ],
      "role": "symbol",
      "title": "AudioStreamRangedDescription",
      "type": "topic",
      "url": "/documentation/coreaudio/audiostreamrangeddescription"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/UnsafeMutableAudioBufferListPointer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutableAudioBufferListPointer"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/UnsafeMutableAudioBufferListPointer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UnsafeMutableAudioBufferListPointer"
        }
      ],
      "role": "symbol",
      "title": "UnsafeMutableAudioBufferListPointer",
      "type": "topic",
      "url": "/documentation/coreaudio/unsafemutableaudiobufferlistpointer"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio Constants",
      "type": "topic",
      "url": "/documentation/coreaudio/core-audio-constants"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio Data Types",
      "type": "topic",
      "url": "/documentation/coreaudio/core-audio-data-types"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio Enumerations",
      "type": "topic",
      "url": "/documentation/coreaudio/core-audio-enumerations"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio Functions",
      "type": "topic",
      "url": "/documentation/coreaudio/core-audio-functions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-data-types",
        "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-functions",
        "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-constants",
        "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Structures",
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareIOProcStreamUsage",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyAddress",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRangedDescription",
        "doc://com.apple.coreaudio/documentation/CoreAudio/UnsafeMutableAudioBufferListPointer"
      ],
      "title": "Structures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Structures",
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInHostInfo",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareIOProcStreamUsage",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertyAddress",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInClientInfo",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInCustomPropertyInfo",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInDriverInterface",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInHostInterface",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOCycleInfo",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRangedDescription"
              ],
              "title": "Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-data-types",
                "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-functions",
                "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-constants",
                "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareIOProcStreamUsage/title",
          "value": "AudioHardwareIOProcStreamUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareIOProcStreamUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwareIOProcStreamUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareIOProcStreamUsage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwareIOProcStreamUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamRangedDescription/title",
          "value": "AudioStreamRangedDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamRangedDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamRangedDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioStreamRangedDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioStreamRangedDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyAddress/title",
          "value": "AudioObjectPropertyAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertyAddress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertyAddress"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/core-audio-structures"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/core-audio-structures"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
