{
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Core Audio Enumerations"
  },
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494430-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494430-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494430-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494437-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494437-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494437-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494439-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494439-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494439-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494441-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494441-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494441-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494445-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494445-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494445-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494449-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494449-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494449-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494454-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494454-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494454-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494461-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494461-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494461-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494464-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494464-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494464-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494466-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494466-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494466-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494470-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494470-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494470-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494472-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494472-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494472-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494474-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494474-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494474-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494483-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494483-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494483-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494489-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494489-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494489-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494503-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494503-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494503-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494510-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494510-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494510-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494512-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494512-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494512-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494522-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494522-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494522-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494526-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494526-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494526-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494528-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494528-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494528-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494531-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494531-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494531-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494533-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494533-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494533-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494536-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494536-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494536-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494541-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494541-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494541-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494543-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494543-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494543-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494551-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494551-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494551-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494554-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494554-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494554-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494557-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494557-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494557-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494569-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494569-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494569-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494571-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494571-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494571-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494573-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494573-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494573-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494576-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494576-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494576-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494580-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494580-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494580-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494587-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494587-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494587-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494591-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494591-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494591-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494594-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494594-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494594-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1494595-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1494595-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1494595-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1545849-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1545849-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1545849-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1545857-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1545857-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1545857-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1545861-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1545861-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1545861-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1545865-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1545865-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1545865-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1545866-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1545866-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1545866-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1545867-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1545867-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1545867-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1545873-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1545873-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1545873-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1545874-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1545874-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1545874-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1545875-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1545875-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1545875-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1545878-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1545878-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1545878-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1545880-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1545880-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1545880-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1545881-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1545881-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1545881-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1545884-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1545884-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1545884-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1545886-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1545886-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1545886-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580715-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580719-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580720-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580722-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580723-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580726-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580728-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580728-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580728-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580731-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580736-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580737-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580738-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580738-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580738-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580740-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580741-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580746-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580747-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580748-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1580749-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1646514-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1646514-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1646514-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/1646515-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/1646515-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/1646515-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/3782865-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/3782865-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/3782865-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/4160684-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/4160684-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/4160684-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/4160685-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/4160685-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/4160685-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/4160686-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/4160686-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/4160686-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/4160687-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/4160687-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/4160687-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/4160688-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/4160688-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/4160688-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/4160689-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/4160689-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/4160689-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/4160690-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/4160690-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/coreaudio/4160690-anonymous"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceClockAlgorithmSelector": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDeviceClockAlgorithmSelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceClockAlgorithmSelector",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDeviceClockAlgorithmSelector",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodeviceclockalgorithmselector"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareDirection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareDirection"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareDirection"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareDirection",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwaredirection"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePowerHint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwarePowerHint"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePowerHint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwarePowerHint"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwarePowerHint",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwarepowerhint"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioLevelControlTransferFunction"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioLevelControlTransferFunction"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOOperation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioServerPlugInIOOperation"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOOperation",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioServerPlugInIOOperation",
      "type": "topic",
      "url": "/documentation/coreaudio/audioserverpluginiooperation"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/CATapMuteBehavior": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATapMuteBehavior"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/CATapMuteBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATapMuteBehavior"
        }
      ],
      "role": "symbol",
      "title": "CATapMuteBehavior",
      "type": "topic",
      "url": "/documentation/coreaudio/catapmutebehavior"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio Constants",
      "type": "topic",
      "url": "/documentation/coreaudio/core-audio-constants"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio Data Types",
      "type": "topic",
      "url": "/documentation/coreaudio/core-audio-data-types"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio Functions",
      "type": "topic",
      "url": "/documentation/coreaudio/core-audio-functions"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio Structures",
      "type": "topic",
      "url": "/documentation/coreaudio/core-audio-structures"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-structures",
        "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-data-types",
        "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-functions",
        "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-constants"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580738-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1580728-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1545857-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1545849-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1545881-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1545873-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1545880-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1545886-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1545884-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1545866-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1545867-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1545874-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1545875-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1545861-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1545865-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1545878-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494510-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494551-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494557-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494489-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494580-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494466-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494573-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494441-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494474-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494430-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494576-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494528-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494522-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494472-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494571-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494439-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494512-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1646514-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494595-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494454-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494554-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494445-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494533-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494591-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494569-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494461-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494526-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494437-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494531-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494587-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494541-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494594-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1646515-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494536-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494449-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494483-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494464-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494503-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494543-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/1494470-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePowerHint",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction",
        "doc://com.apple.coreaudio/documentation/CoreAudio/3782865-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/4160684-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/4160685-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/4160686-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/4160687-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/4160688-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/4160689-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/4160690-anonymous",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareDirection",
        "doc://com.apple.coreaudio/documentation/CoreAudio/CATapMuteBehavior"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580748-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580731-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580722-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580720-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580736-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580737-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580746-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580723-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580747-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580749-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580719-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580715-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580740-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580741-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580726-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580738-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1580728-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1545857-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1545849-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1545881-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1545873-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1545880-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1545886-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1545884-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1545866-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1545867-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1545874-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1545875-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1545861-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1545865-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1545878-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494510-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494551-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494557-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494489-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494580-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494466-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494573-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494441-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494474-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494430-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494576-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494528-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494522-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494472-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494571-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494439-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494512-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1646514-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494595-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494454-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494554-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494445-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494533-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494591-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494569-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494461-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494526-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494437-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494531-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494587-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494541-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494594-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1646515-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494536-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494449-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494483-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494464-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494503-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494543-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/1494470-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceClockAlgorithmSelector",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwarePowerHint",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction",
                "doc://com.apple.coreaudio/documentation/CoreAudio/3782865-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/4160684-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/4160685-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/4160686-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/4160687-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/4160688-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/4160689-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/4160690-anonymous",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioServerPlugInIOOperation",
                "doc://com.apple.coreaudio/documentation/CoreAudio/CATapMuteBehavior"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-structures",
                "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-data-types",
                "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-functions",
                "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-constants"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwarePowerHint/title",
          "value": "AudioHardwarePowerHint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwarePowerHint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwarePowerHint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwarePowerHint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwarePowerHint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1CATapMuteBehavior/title",
          "value": "CATapMuteBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1CATapMuteBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATapMuteBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1CATapMuteBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CATapMuteBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction/title",
          "value": "AudioLevelControlTransferFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioLevelControlTransferFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioLevelControlTransferFunction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/core-audio-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/core-audio-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
