{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-functions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Core Audio Functions"
  },
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertHostTimeToNanos(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioConvertHostTimeToNanos"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertHostTimeToNanos(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioConvertHostTimeToNanos"
        }
      ],
      "role": "symbol",
      "title": "AudioConvertHostTimeToNanos(_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audioconverthosttimetonanos(_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertNanosToHostTime(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioConvertNanosToHostTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertNanosToHostTime(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioConvertNanosToHostTime"
        }
      ],
      "role": "symbol",
      "title": "AudioConvertNanosToHostTime(_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audioconvertnanostohosttime(_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceAddIOProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDeviceAddIOProc"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceAddIOProc",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDeviceAddIOProc",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodeviceaddioproc"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceAddPropertyListener": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDeviceAddPropertyListener"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceAddPropertyListener",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDeviceAddPropertyListener",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodeviceaddpropertylistener"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcID(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDeviceCreateIOProcID"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioDeviceIOProc",
          "text": "AudioDeviceIOProc"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioDeviceIOProcID",
          "text": "AudioDeviceIOProcID"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcID(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDeviceCreateIOProcID"
        }
      ],
      "role": "symbol",
      "title": "AudioDeviceCreateIOProcID(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicecreateioprocid(_:_:_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcIDWithBlock(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDeviceCreateIOProcIDWithBlock"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioDeviceIOProcID",
          "text": "AudioDeviceIOProcID"
        },
        {
          "kind": "text",
          "text": "?>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioDeviceIOBlock",
          "text": "AudioDeviceIOBlock"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcIDWithBlock(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDeviceCreateIOProcIDWithBlock"
        }
      ],
      "role": "symbol",
      "title": "AudioDeviceCreateIOProcIDWithBlock(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicecreateioprocidwithblock(_:_:_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceDestroyIOProcID(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDeviceDestroyIOProcID"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioDeviceIOProcID",
          "text": "AudioDeviceIOProcID"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceDestroyIOProcID(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDeviceDestroyIOProcID"
        }
      ],
      "role": "symbol",
      "title": "AudioDeviceDestroyIOProcID(_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicedestroyioprocid(_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetCurrentTime(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDeviceGetCurrentTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioTimeStamp",
          "text": "AudioTimeStamp"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetCurrentTime(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDeviceGetCurrentTime"
        }
      ],
      "role": "symbol",
      "title": "AudioDeviceGetCurrentTime(_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicegetcurrenttime(_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetNearestStartTime(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDeviceGetNearestStartTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioTimeStamp",
          "text": "AudioTimeStamp"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetNearestStartTime(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDeviceGetNearestStartTime"
        }
      ],
      "role": "symbol",
      "title": "AudioDeviceGetNearestStartTime(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicegetneareststarttime(_:_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetProperty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDeviceGetProperty"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDeviceGetProperty",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicegetproperty"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetPropertyInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDeviceGetPropertyInfo"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetPropertyInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDeviceGetPropertyInfo",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicegetpropertyinfo"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRead": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDeviceRead"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRead",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDeviceRead",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodeviceread"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRemoveIOProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDeviceRemoveIOProc"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRemoveIOProc",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDeviceRemoveIOProc",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodeviceremoveioproc"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRemovePropertyListener": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDeviceRemovePropertyListener"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRemovePropertyListener",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDeviceRemovePropertyListener",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodeviceremovepropertylistener"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceSetProperty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDeviceSetProperty"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceSetProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDeviceSetProperty",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicesetproperty"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStart(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDeviceStart"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioDeviceIOProcID",
          "text": "AudioDeviceIOProcID"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStart(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDeviceStart"
        }
      ],
      "role": "symbol",
      "title": "AudioDeviceStart(_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicestart(_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStartAtTime(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDeviceStartAtTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioDeviceIOProcID",
          "text": "AudioDeviceIOProcID"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioTimeStamp",
          "text": "AudioTimeStamp"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStartAtTime(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDeviceStartAtTime"
        }
      ],
      "role": "symbol",
      "title": "AudioDeviceStartAtTime(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicestartattime(_:_:_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStop(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDeviceStop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioDeviceIOProcID",
          "text": "AudioDeviceIOProcID"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStop(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDeviceStop"
        }
      ],
      "role": "symbol",
      "title": "AudioDeviceStop(_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicestop(_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceTranslateTime(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioDeviceTranslateTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioTimeStamp",
          "text": "AudioTimeStamp"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioTimeStamp",
          "text": "AudioTimeStamp"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceTranslateTime(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioDeviceTranslateTime"
        }
      ],
      "role": "symbol",
      "title": "AudioDeviceTranslateTime(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodevicetranslatetime(_:_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInClose": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDriverPlugInClose"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInClose",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDriverPlugInClose",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodriverpluginclose"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceGetProperty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDriverPlugInDeviceGetProperty"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceGetProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDriverPlugInDeviceGetProperty",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodriverplugindevicegetproperty"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceGetPropertyInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDriverPlugInDeviceGetPropertyInfo"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceGetPropertyInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDriverPlugInDeviceGetPropertyInfo",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodriverplugindevicegetpropertyinfo"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceSetProperty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDriverPlugInDeviceSetProperty"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceSetProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDriverPlugInDeviceSetProperty",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodriverplugindevicesetproperty"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInOpen": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDriverPlugInOpen"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInOpen",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDriverPlugInOpen",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodriverpluginopen"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInStreamGetProperty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDriverPlugInStreamGetProperty"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInStreamGetProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDriverPlugInStreamGetProperty",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodriverpluginstreamgetproperty"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInStreamGetPropertyInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDriverPlugInStreamGetPropertyInfo"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInStreamGetPropertyInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDriverPlugInStreamGetPropertyInfo",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodriverpluginstreamgetpropertyinfo"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInStreamSetProperty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioDriverPlugInStreamSetProperty"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInStreamSetProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioDriverPlugInStreamSetProperty",
      "type": "topic",
      "url": "/documentation/coreaudio/audiodriverpluginstreamsetproperty"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetCurrentHostTime()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioGetCurrentHostTime"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetCurrentHostTime()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioGetCurrentHostTime"
        }
      ],
      "role": "symbol",
      "title": "AudioGetCurrentHostTime()",
      "type": "topic",
      "url": "/documentation/coreaudio/audiogetcurrenthosttime()"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetHostClockFrequency()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioGetHostClockFrequency"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float64a",
          "text": "Float64"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetHostClockFrequency()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioGetHostClockFrequency"
        }
      ],
      "role": "symbol",
      "title": "AudioGetHostClockFrequency()",
      "type": "topic",
      "url": "/documentation/coreaudio/audiogethostclockfrequency()"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetHostClockMinimumTimeDelta()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioGetHostClockMinimumTimeDelta"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetHostClockMinimumTimeDelta()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioGetHostClockMinimumTimeDelta"
        }
      ],
      "role": "symbol",
      "title": "AudioGetHostClockMinimumTimeDelta()",
      "type": "topic",
      "url": "/documentation/coreaudio/audiogethostclockminimumtimedelta()"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareAddPropertyListener": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioHardwareAddPropertyListener"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareAddPropertyListener",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioHardwareAddPropertyListener",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwareaddpropertylistener"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareAddRunLoopSource": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioHardwareAddRunLoopSource"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareAddRunLoopSource",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioHardwareAddRunLoopSource",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwareaddrunloopsource"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareCreateAggregateDevice(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareCreateAggregateDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareCreateAggregateDevice(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareCreateAggregateDevice"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareCreateAggregateDevice(_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwarecreateaggregatedevice(_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareCreateProcessTap(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareCreateProcessTap"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CATapDescription",
          "text": "CATapDescription"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareCreateProcessTap(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareCreateProcessTap"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareCreateProcessTap(_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwarecreateprocesstap(_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareDestroyAggregateDevice(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareDestroyAggregateDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareDestroyAggregateDevice(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareDestroyAggregateDevice"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareDestroyAggregateDevice(_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwaredestroyaggregatedevice(_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareDestroyProcessTap(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareDestroyProcessTap"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareDestroyProcessTap(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareDestroyProcessTap"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareDestroyProcessTap(_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwaredestroyprocesstap(_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareGetProperty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioHardwareGetProperty"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareGetProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioHardwareGetProperty",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwaregetproperty"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareGetPropertyInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioHardwareGetPropertyInfo"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareGetPropertyInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioHardwareGetPropertyInfo",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwaregetpropertyinfo"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareRemovePropertyListener": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioHardwareRemovePropertyListener"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareRemovePropertyListener",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioHardwareRemovePropertyListener",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwareremovepropertylistener"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareRemoveRunLoopSource": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioHardwareRemoveRunLoopSource"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareRemoveRunLoopSource",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioHardwareRemoveRunLoopSource",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwareremoverunloopsource"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareSetProperty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioHardwareSetProperty"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareSetProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioHardwareSetProperty",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwaresetproperty"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareUnload()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioHardwareUnload"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareUnload()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioHardwareUnload"
        }
      ],
      "role": "symbol",
      "title": "AudioHardwareUnload()",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwareunload()"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectAddPropertyListener(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectAddPropertyListener"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioObjectPropertyAddress",
          "text": "AudioObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertyListenerProc",
          "text": "AudioObjectPropertyListenerProc"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectAddPropertyListener(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectAddPropertyListener"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectAddPropertyListener(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectaddpropertylistener(_:_:_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectAddPropertyListenerBlock(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectAddPropertyListenerBlock"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioObjectPropertyAddress",
          "text": "AudioObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertyListenerBlock",
          "text": "AudioObjectPropertyListenerBlock"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectAddPropertyListenerBlock(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectAddPropertyListenerBlock"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectAddPropertyListenerBlock(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectaddpropertylistenerblock(_:_:_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectGetPropertyData(_:_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectGetPropertyData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioObjectPropertyAddress",
          "text": "AudioObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectGetPropertyData(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectGetPropertyData"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectGetPropertyData(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectgetpropertydata(_:_:_:_:_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectGetPropertyDataSize(_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectGetPropertyDataSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioObjectPropertyAddress",
          "text": "AudioObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectGetPropertyDataSize(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectGetPropertyDataSize"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectGetPropertyDataSize(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectgetpropertydatasize(_:_:_:_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectHasProperty(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectHasProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioObjectPropertyAddress",
          "text": "AudioObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectHasProperty(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectHasProperty"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectHasProperty(_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjecthasproperty(_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectIsPropertySettable(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectIsPropertySettable"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioObjectPropertyAddress",
          "text": "AudioObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Darwin0A7BooleanV",
          "text": "DarwinBoolean"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectIsPropertySettable(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectIsPropertySettable"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectIsPropertySettable(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectispropertysettable(_:_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectRemovePropertyListener(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectRemovePropertyListener"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioObjectPropertyAddress",
          "text": "AudioObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertyListenerProc",
          "text": "AudioObjectPropertyListenerProc"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectRemovePropertyListener(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectRemovePropertyListener"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectRemovePropertyListener(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectremovepropertylistener(_:_:_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectRemovePropertyListenerBlock(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectRemovePropertyListenerBlock"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioObjectPropertyAddress",
          "text": "AudioObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertyListenerBlock",
          "text": "AudioObjectPropertyListenerBlock"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectRemovePropertyListenerBlock(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectRemovePropertyListenerBlock"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectRemovePropertyListenerBlock(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectremovepropertylistenerblock(_:_:_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectSetPropertyData(_:_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectSetPropertyData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioObjectPropertyAddress",
          "text": "AudioObjectPropertyAddress"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectSetPropertyData(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectSetPropertyData"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectSetPropertyData(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectsetpropertydata(_:_:_:_:_:_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectShow(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectShow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectID",
          "text": "AudioObjectID"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectShow(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectShow"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectShow(_:)",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectshow(_:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamAddPropertyListener": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioStreamAddPropertyListener"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamAddPropertyListener",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioStreamAddPropertyListener",
      "type": "topic",
      "url": "/documentation/coreaudio/audiostreamaddpropertylistener"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamGetProperty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioStreamGetProperty"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamGetProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioStreamGetProperty",
      "type": "topic",
      "url": "/documentation/coreaudio/audiostreamgetproperty"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamGetPropertyInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioStreamGetPropertyInfo"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamGetPropertyInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioStreamGetPropertyInfo",
      "type": "topic",
      "url": "/documentation/coreaudio/audiostreamgetpropertyinfo"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRemovePropertyListener": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioStreamRemovePropertyListener"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRemovePropertyListener",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioStreamRemovePropertyListener",
      "type": "topic",
      "url": "/documentation/coreaudio/audiostreamremovepropertylistener"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamSetProperty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioStreamSetProperty"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamSetProperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioStreamSetProperty",
      "type": "topic",
      "url": "/documentation/coreaudio/audiostreamsetproperty"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/PropertyAddress(_:scope:element:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PropertyAddress"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "scope"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertyScope",
          "text": "AudioObjectPropertyScope"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "element"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertyElement",
          "text": "AudioObjectPropertyElement"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioObjectPropertyAddress",
          "text": "AudioObjectPropertyAddress"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/PropertyAddress(_:scope:element:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "PropertyAddress(_:scope:element:)",
      "type": "topic",
      "url": "/documentation/coreaudio/propertyaddress(_:scope:element:)"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio Constants",
      "type": "topic",
      "url": "/documentation/coreaudio/core-audio-constants"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio Data Types",
      "type": "topic",
      "url": "/documentation/coreaudio/core-audio-data-types"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio Enumerations",
      "type": "topic",
      "url": "/documentation/coreaudio/core-audio-enumerations"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Audio Structures",
      "type": "topic",
      "url": "/documentation/coreaudio/core-audio-structures"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-structures",
        "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-data-types",
        "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-constants",
        "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions",
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertHostTimeToNanos(_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertNanosToHostTime(_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcID(_:_:_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcIDWithBlock(_:_:_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceDestroyIOProcID(_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetCurrentTime(_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetNearestStartTime(_:_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStart(_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStartAtTime(_:_:_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStop(_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceTranslateTime(_:_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetCurrentHostTime()",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetHostClockFrequency()",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetHostClockMinimumTimeDelta()",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareCreateAggregateDevice(_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareDestroyAggregateDevice(_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareUnload()",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectAddPropertyListener(_:_:_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectAddPropertyListenerBlock(_:_:_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectGetPropertyData(_:_:_:_:_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectGetPropertyDataSize(_:_:_:_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectHasProperty(_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectIsPropertySettable(_:_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectRemovePropertyListener(_:_:_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectRemovePropertyListenerBlock(_:_:_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectSetPropertyData(_:_:_:_:_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectShow(_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareCreateProcessTap(_:_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareDestroyProcessTap(_:)",
        "doc://com.apple.coreaudio/documentation/CoreAudio/PropertyAddress(_:scope:element:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions",
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertHostTimeToNanos(_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioConvertNanosToHostTime(_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcID(_:_:_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceCreateIOProcIDWithBlock(_:_:_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceDestroyIOProcID(_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetCurrentTime(_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetNearestStartTime(_:_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStart(_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStartAtTime(_:_:_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceStop(_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceTranslateTime(_:_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInClose",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceGetProperty",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceGetPropertyInfo",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInDeviceSetProperty",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInOpen",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInStreamGetProperty",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInStreamGetPropertyInfo",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDriverPlugInStreamSetProperty",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetCurrentHostTime()",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetHostClockFrequency()",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioGetHostClockMinimumTimeDelta()",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareCreateAggregateDevice(_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareDestroyAggregateDevice(_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareUnload()",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectAddPropertyListener(_:_:_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectAddPropertyListenerBlock(_:_:_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectGetPropertyData(_:_:_:_:_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectGetPropertyDataSize(_:_:_:_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectHasProperty(_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectIsPropertySettable(_:_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectRemovePropertyListener(_:_:_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectRemovePropertyListenerBlock(_:_:_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectSetPropertyData(_:_:_:_:_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectShow(_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareCreateProcessTap(_:_:)",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareDestroyProcessTap(_:)"
              ],
              "title": "Functions"
            },
            {
              "anchor": "Deprecated-Functions",
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceAddIOProc",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceAddPropertyListener",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetProperty",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceGetPropertyInfo",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRead",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRemoveIOProc",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceRemovePropertyListener",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioDeviceSetProperty",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareAddPropertyListener",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareAddRunLoopSource",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareGetProperty",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareGetPropertyInfo",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareRemovePropertyListener",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareRemoveRunLoopSource",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareSetProperty",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamAddPropertyListener",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamGetProperty",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamGetPropertyInfo",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamRemovePropertyListener",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioStreamSetProperty"
              ],
              "title": "Deprecated Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-structures",
                "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-data-types",
                "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-constants",
                "doc://com.apple.coreaudio/documentation/CoreAudio/core-audio-enumerations"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareCreateAggregateDevice(_:_:)/title",
          "value": "AudioHardwareCreateAggregateDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareCreateAggregateDevice(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwareCreateAggregateDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceGetCurrentTime(_:_:)/title",
          "value": "AudioDeviceGetCurrentTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceGetCurrentTime(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceGetCurrentTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceDestroyIOProcID(_:_:)/title",
          "value": "AudioDeviceDestroyIOProcID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceDestroyIOProcID(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceDestroyIOProcID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceCreateIOProcID(_:_:_:_:)/title",
          "value": "AudioDeviceCreateIOProcID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceCreateIOProcID(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceCreateIOProcID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceCreateIOProcIDWithBlock(_:_:_:_:)/title",
          "value": "AudioDeviceCreateIOProcIDWithBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceCreateIOProcIDWithBlock(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceCreateIOProcIDWithBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectRemovePropertyListenerBlock(_:_:_:_:)/title",
          "value": "AudioObjectRemovePropertyListenerBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectRemovePropertyListenerBlock(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectRemovePropertyListenerBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectRemovePropertyListener(_:_:_:_:)/title",
          "value": "AudioObjectRemovePropertyListener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectRemovePropertyListener(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectRemovePropertyListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioConvertHostTimeToNanos(_:)/title",
          "value": "AudioConvertHostTimeToNanos"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioConvertHostTimeToNanos(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioConvertHostTimeToNanos"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareDestroyProcessTap(_:)/title",
          "value": "AudioHardwareDestroyProcessTap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareDestroyProcessTap(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwareDestroyProcessTap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectSetPropertyData(_:_:_:_:_:_:)/title",
          "value": "AudioObjectSetPropertyData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectSetPropertyData(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectSetPropertyData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectIsPropertySettable(_:_:_:)/title",
          "value": "AudioObjectIsPropertySettable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectIsPropertySettable(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectIsPropertySettable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareUnload()/title",
          "value": "AudioHardwareUnload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareUnload()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwareUnload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceStartAtTime(_:_:_:_:)/title",
          "value": "AudioDeviceStartAtTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceStartAtTime(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceStartAtTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioGetCurrentHostTime()/title",
          "value": "AudioGetCurrentHostTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioGetCurrentHostTime()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioGetCurrentHostTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioGetHostClockFrequency()/title",
          "value": "AudioGetHostClockFrequency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioGetHostClockFrequency()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioGetHostClockFrequency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioGetHostClockMinimumTimeDelta()/title",
          "value": "AudioGetHostClockMinimumTimeDelta"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioGetHostClockMinimumTimeDelta()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioGetHostClockMinimumTimeDelta"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceGetNearestStartTime(_:_:_:)/title",
          "value": "AudioDeviceGetNearestStartTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceGetNearestStartTime(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceGetNearestStartTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectAddPropertyListenerBlock(_:_:_:_:)/title",
          "value": "AudioObjectAddPropertyListenerBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectAddPropertyListenerBlock(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectAddPropertyListenerBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioConvertNanosToHostTime(_:)/title",
          "value": "AudioConvertNanosToHostTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioConvertNanosToHostTime(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioConvertNanosToHostTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectShow(_:)/title",
          "value": "AudioObjectShow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectShow(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectShow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectHasProperty(_:_:)/title",
          "value": "AudioObjectHasProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectHasProperty(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectHasProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectAddPropertyListener(_:_:_:_:)/title",
          "value": "AudioObjectAddPropertyListener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectAddPropertyListener(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectAddPropertyListener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectGetPropertyData(_:_:_:_:_:_:)/title",
          "value": "AudioObjectGetPropertyData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectGetPropertyData(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectGetPropertyData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareDestroyAggregateDevice(_:)/title",
          "value": "AudioHardwareDestroyAggregateDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareDestroyAggregateDevice(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwareDestroyAggregateDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceTranslateTime(_:_:_:)/title",
          "value": "AudioDeviceTranslateTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceTranslateTime(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceTranslateTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectGetPropertyDataSize(_:_:_:_:_:)/title",
          "value": "AudioObjectGetPropertyDataSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectGetPropertyDataSize(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectGetPropertyDataSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareCreateProcessTap(_:_:)/title",
          "value": "AudioHardwareCreateProcessTap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioHardwareCreateProcessTap(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioHardwareCreateProcessTap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceStart(_:_:)/title",
          "value": "AudioDeviceStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceStart(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceStop(_:_:)/title",
          "value": "AudioDeviceStop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioDeviceStop(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioDeviceStop"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/core-audio-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/core-audio-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
