{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyPlayThruVolumeRangeDecibels"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioDevicePropertyJackIsConnected@kAudioDevicePropertyPlayThruVolumeRangeDecibels",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioDevicePropertyPlayThruVolumeRangeDecibels"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
        "text": "AudioObjectPropertySelector"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioDevicePropertyPlayThruVolumeRangeDecibels"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioDevicePropertyPlayThruVolumeRangeDecibels"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyPlayThruVolumeRangeDecibels"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
              "text": "AudioObjectPropertySelector"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertySelector",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertyselector"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNominalLineLevel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelNominalLineLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNominalLineLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelNominalLineLevel"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyChannelNominalLineLevel",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertychannelnominallinelevel"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNominalLineLevelNameForIDCFString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelNominalLineLevelNameForIDCFString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNominalLineLevelNameForIDCFString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelNominalLineLevelNameForIDCFString"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyChannelNominalLineLevelNameForIDCFString",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertychannelnominallinelevelnameforidcfstring"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNominalLineLevels": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelNominalLineLevels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNominalLineLevels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelNominalLineLevels"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyChannelNominalLineLevels",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertychannelnominallinelevels"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClipLight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyClipLight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClipLight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyClipLight"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyClipLight",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertycliplight"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockSource": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyClockSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyClockSource"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyClockSource",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyclocksource"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockSourceKindForID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyClockSourceKindForID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockSourceKindForID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyClockSourceKindForID"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyClockSourceKindForID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyclocksourcekindforid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockSourceNameForIDCFString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyClockSourceNameForIDCFString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockSourceNameForIDCFString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyClockSourceNameForIDCFString"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyClockSourceNameForIDCFString",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyclocksourcenameforidcfstring"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockSources": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyClockSources"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockSources",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyClockSources"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyClockSources",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyclocksources"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDataSource": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDataSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDataSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDataSource"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyDataSource",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertydatasource"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDataSourceKindForID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDataSourceKindForID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDataSourceKindForID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDataSourceKindForID"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyDataSourceKindForID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertydatasourcekindforid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDataSourceNameForIDCFString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDataSourceNameForIDCFString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDataSourceNameForIDCFString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDataSourceNameForIDCFString"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyDataSourceNameForIDCFString",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertydatasourcenameforidcfstring"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDataSources": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDataSources"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDataSources",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDataSources"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyDataSources",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertydatasources"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyHighPassFilterSetting": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyHighPassFilterSetting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyHighPassFilterSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyHighPassFilterSetting"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyHighPassFilterSetting",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyhighpassfiltersetting"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyHighPassFilterSettingNameForIDCFString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyHighPassFilterSettingNameForIDCFString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyHighPassFilterSettingNameForIDCFString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyHighPassFilterSettingNameForIDCFString"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyHighPassFilterSettingNameForIDCFString",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyhighpassfiltersettingnameforidcfstring"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyHighPassFilterSettings": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyHighPassFilterSettings"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyHighPassFilterSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyHighPassFilterSettings"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyHighPassFilterSettings",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyhighpassfiltersettings"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyPlayThruVolumeRangeDecibels": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyPlayThruVolumeRangeDecibels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyPlayThruVolumeRangeDecibels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyPlayThruVolumeRangeDecibels"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyPlayThruVolumeRangeDecibels",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyplaythruvolumerangedecibels"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNominalLineLevel",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNominalLineLevelNameForIDCFString",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNominalLineLevels",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClipLight",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockSource",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockSourceKindForID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockSourceNameForIDCFString",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockSources",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDataSource",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDataSourceKindForID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDataSourceNameForIDCFString",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDataSources",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyHighPassFilterSetting",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyHighPassFilterSettingNameForIDCFString",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyHighPassFilterSettings"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioDevicePropertyPlayThruVolumeRangeDecibels"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyPlayThruVolumeRangeDecibels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudio/documentation/CoreAudio"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNominalLineLevel",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNominalLineLevelNameForIDCFString",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNominalLineLevels",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClipLight",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockSource",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockSourceKindForID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockSourceNameForIDCFString",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockSources",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDataSource",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDataSourceKindForID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDataSourceNameForIDCFString",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDataSources",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyHighPassFilterSetting",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyHighPassFilterSettingNameForIDCFString",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyHighPassFilterSettings"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioDevicePropertyPlayThruVolumeRangeDecibels"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelNominalLineLevelNameForIDCFString/title",
          "value": "kAudioDevicePropertyChannelNominalLineLevelNameForIDCFString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelNominalLineLevelNameForIDCFString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyChannelNominalLineLevelNameForIDCFString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyClockSources/title",
          "value": "kAudioDevicePropertyClockSources"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyClockSources/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyClockSources"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyClockSourceKindForID/title",
          "value": "kAudioDevicePropertyClockSourceKindForID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyClockSourceKindForID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyClockSourceKindForID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/title",
          "value": "AudioObjectPropertySelector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyHighPassFilterSetting/title",
          "value": "kAudioDevicePropertyHighPassFilterSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyHighPassFilterSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyHighPassFilterSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDataSourceNameForIDCFString/title",
          "value": "kAudioDevicePropertyDataSourceNameForIDCFString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDataSourceNameForIDCFString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyDataSourceNameForIDCFString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelNominalLineLevels/title",
          "value": "kAudioDevicePropertyChannelNominalLineLevels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelNominalLineLevels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyChannelNominalLineLevels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDataSourceKindForID/title",
          "value": "kAudioDevicePropertyDataSourceKindForID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDataSourceKindForID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyDataSourceKindForID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDataSource/title",
          "value": "kAudioDevicePropertyDataSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDataSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyClockSourceNameForIDCFString/title",
          "value": "kAudioDevicePropertyClockSourceNameForIDCFString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyClockSourceNameForIDCFString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyClockSourceNameForIDCFString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyHighPassFilterSettings/title",
          "value": "kAudioDevicePropertyHighPassFilterSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyHighPassFilterSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyHighPassFilterSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyPlayThruVolumeRangeDecibels/title",
          "value": "kAudioDevicePropertyPlayThruVolumeRangeDecibels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyPlayThruVolumeRangeDecibels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyPlayThruVolumeRangeDecibels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyClockSource/title",
          "value": "kAudioDevicePropertyClockSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyClockSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyClockSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyHighPassFilterSettingNameForIDCFString/title",
          "value": "kAudioDevicePropertyHighPassFilterSettingNameForIDCFString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyHighPassFilterSettingNameForIDCFString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyHighPassFilterSettingNameForIDCFString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDataSources/title",
          "value": "kAudioDevicePropertyDataSources"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDataSources/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyDataSources"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelNominalLineLevel/title",
          "value": "kAudioDevicePropertyChannelNominalLineLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelNominalLineLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyChannelNominalLineLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyClipLight/title",
          "value": "kAudioDevicePropertyClipLight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyClipLight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyClipLight"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/kaudiodevicepropertyplaythruvolumerangedecibels"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/kaudiodevicepropertyplaythruvolumerangedecibels"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
