{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyLatency"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioDevicePropertyConfigurationApplication@kAudioDevicePropertyLatency",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioDevicePropertyLatency"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
        "text": "AudioObjectPropertySelector"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioDevicePropertyLatency"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioDevicePropertyLatency"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyLatency"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
              "text": "AudioObjectPropertySelector"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertySelector",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertyselector"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyAvailableNominalSampleRates": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyAvailableNominalSampleRates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyAvailableNominalSampleRates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyAvailableNominalSampleRates"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyAvailableNominalSampleRates",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyavailablenominalsamplerates"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyClockDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyClockDomain"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyClockDomain",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyclockdomain"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyConfigurationApplication": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyConfigurationApplication"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyConfigurationApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyConfigurationApplication"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyConfigurationApplication",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyconfigurationapplication"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceCanBeDefaultDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceCanBeDefaultDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceCanBeDefaultDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceCanBeDefaultDevice"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyDeviceCanBeDefaultDevice",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertydevicecanbedefaultdevice"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceCanBeDefaultSystemDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceCanBeDefaultSystemDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceCanBeDefaultSystemDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceCanBeDefaultSystemDevice"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyDeviceCanBeDefaultSystemDevice",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertydevicecanbedefaultsystemdevice"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceIsAlive": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceIsAlive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceIsAlive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceIsAlive"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyDeviceIsAlive",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertydeviceisalive"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceIsRunning": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceIsRunning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceIsRunning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceIsRunning"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyDeviceIsRunning",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertydeviceisrunning"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceUID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceUID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceUID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceUID"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyDeviceUID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertydeviceuid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyIcon": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyIcon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyIcon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyIcon"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyIcon",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyicon"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyIsHidden": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyIsHidden"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyIsHidden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyIsHidden"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyIsHidden",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyishidden"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyLatency": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyLatency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyLatency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyLatency"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyLatency",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertylatency"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyModelUID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyModelUID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyModelUID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyModelUID"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyModelUID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertymodeluid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyNominalSampleRate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyNominalSampleRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyNominalSampleRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyNominalSampleRate"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyNominalSampleRate",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertynominalsamplerate"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyPreferredChannelLayout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyPreferredChannelLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyPreferredChannelLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyPreferredChannelLayout"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyPreferredChannelLayout",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertypreferredchannellayout"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyPreferredChannelsForStereo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyPreferredChannelsForStereo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyPreferredChannelsForStereo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyPreferredChannelsForStereo"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyPreferredChannelsForStereo",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertypreferredchannelsforstereo"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyRelatedDevices": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyRelatedDevices"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyRelatedDevices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyRelatedDevices"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyRelatedDevices",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyrelateddevices"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyAvailableNominalSampleRates",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockDomain",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyConfigurationApplication",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceCanBeDefaultDevice",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceCanBeDefaultSystemDevice",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceIsAlive",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceIsRunning",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceUID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyIcon",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyIsHidden",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyModelUID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyNominalSampleRate",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyPreferredChannelLayout",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyPreferredChannelsForStereo",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyRelatedDevices"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioDevicePropertyLatency"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyLatency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudio/documentation/CoreAudio"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyAvailableNominalSampleRates",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockDomain",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyConfigurationApplication",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceCanBeDefaultDevice",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceCanBeDefaultSystemDevice",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceIsAlive",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceIsRunning",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceUID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyIcon",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyIsHidden",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyModelUID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyNominalSampleRate",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyPreferredChannelLayout",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyPreferredChannelsForStereo",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyRelatedDevices"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioDevicePropertyLatency"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyNominalSampleRate/title",
          "value": "kAudioDevicePropertyNominalSampleRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyNominalSampleRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyNominalSampleRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceCanBeDefaultSystemDevice/title",
          "value": "kAudioDevicePropertyDeviceCanBeDefaultSystemDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceCanBeDefaultSystemDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyDeviceCanBeDefaultSystemDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceCanBeDefaultDevice/title",
          "value": "kAudioDevicePropertyDeviceCanBeDefaultDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceCanBeDefaultDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyDeviceCanBeDefaultDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceIsAlive/title",
          "value": "kAudioDevicePropertyDeviceIsAlive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceIsAlive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyDeviceIsAlive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyIsHidden/title",
          "value": "kAudioDevicePropertyIsHidden"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyIsHidden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyIsHidden"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/title",
          "value": "AudioObjectPropertySelector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyLatency/title",
          "value": "kAudioDevicePropertyLatency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyLatency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyLatency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyPreferredChannelLayout/title",
          "value": "kAudioDevicePropertyPreferredChannelLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyPreferredChannelLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyPreferredChannelLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyModelUID/title",
          "value": "kAudioDevicePropertyModelUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyModelUID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyModelUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyAvailableNominalSampleRates/title",
          "value": "kAudioDevicePropertyAvailableNominalSampleRates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyAvailableNominalSampleRates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyAvailableNominalSampleRates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyClockDomain/title",
          "value": "kAudioDevicePropertyClockDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyClockDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyClockDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyConfigurationApplication/title",
          "value": "kAudioDevicePropertyConfigurationApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyConfigurationApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyConfigurationApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceIsRunning/title",
          "value": "kAudioDevicePropertyDeviceIsRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceIsRunning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyDeviceIsRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyIcon/title",
          "value": "kAudioDevicePropertyIcon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyIcon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyIcon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceUID/title",
          "value": "kAudioDevicePropertyDeviceUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceUID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyDeviceUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyPreferredChannelsForStereo/title",
          "value": "kAudioDevicePropertyPreferredChannelsForStereo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyPreferredChannelsForStereo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyPreferredChannelsForStereo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyRelatedDevices/title",
          "value": "kAudioDevicePropertyRelatedDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyRelatedDevices/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyRelatedDevices"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/kaudiodevicepropertylatency"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/kaudiodevicepropertylatency"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
