{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPhantomPowerControlClassID"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioBooleanControlClassID@kAudioPhantomPowerControlClassID",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioPhantomPowerControlClassID"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioClassID",
        "text": "AudioClassID"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioPhantomPowerControlClassID"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioPhantomPowerControlClassID"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioPhantomPowerControlClassID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioClassID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioClassID",
              "text": "AudioClassID"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioClassID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioClassID"
        }
      ],
      "role": "symbol",
      "title": "AudioClassID",
      "type": "topic",
      "url": "/documentation/coreaudio/audioclassid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBooleanControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioBooleanControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioClassID",
          "text": "AudioClassID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBooleanControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioBooleanControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kAudioBooleanControlClassID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiobooleancontrolclassid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClipLightControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioClipLightControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioClassID",
          "text": "AudioClassID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClipLightControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioClipLightControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kAudioClipLightControlClassID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiocliplightcontrolclassid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioJackControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioJackControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioClassID",
          "text": "AudioClassID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioJackControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioJackControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kAudioJackControlClassID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiojackcontrolclassid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioLFEMuteControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioLFEMuteControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioClassID",
          "text": "AudioClassID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioLFEMuteControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLFEMuteControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kAudioLFEMuteControlClassID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiolfemutecontrolclassid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioListenbackControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioListenbackControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioClassID",
          "text": "AudioClassID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioListenbackControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioListenbackControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kAudioListenbackControlClassID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiolistenbackcontrolclassid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioMuteControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioMuteControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioClassID",
          "text": "AudioClassID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioMuteControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioMuteControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kAudioMuteControlClassID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiomutecontrolclassid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPhantomPowerControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioPhantomPowerControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioClassID",
          "text": "AudioClassID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPhantomPowerControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioPhantomPowerControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kAudioPhantomPowerControlClassID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiophantompowercontrolclassid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPhaseInvertControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioPhaseInvertControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioClassID",
          "text": "AudioClassID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPhaseInvertControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioPhaseInvertControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kAudioPhaseInvertControlClassID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiophaseinvertcontrolclassid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioSoloControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSoloControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioClassID",
          "text": "AudioClassID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioSoloControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSoloControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kAudioSoloControlClassID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiosolocontrolclassid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioTalkbackControlClassID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioTalkbackControlClassID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioClassID",
          "text": "AudioClassID"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioTalkbackControlClassID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioTalkbackControlClassID"
        }
      ],
      "role": "symbol",
      "title": "kAudioTalkbackControlClassID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiotalkbackcontrolclassid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBooleanControlClassID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClipLightControlClassID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioJackControlClassID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioLFEMuteControlClassID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioListenbackControlClassID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioMuteControlClassID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPhaseInvertControlClassID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioSoloControlClassID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioTalkbackControlClassID"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioPhantomPowerControlClassID"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioPhantomPowerControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudio/documentation/CoreAudio"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBooleanControlClassID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClipLightControlClassID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioJackControlClassID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioLFEMuteControlClassID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioListenbackControlClassID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioMuteControlClassID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPhaseInvertControlClassID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioSoloControlClassID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioTalkbackControlClassID"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioPhantomPowerControlClassID"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioClassID/title",
          "value": "AudioClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioClassID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioBooleanControlClassID/title",
          "value": "kAudioBooleanControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioBooleanControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioBooleanControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioJackControlClassID/title",
          "value": "kAudioJackControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioJackControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioJackControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioMuteControlClassID/title",
          "value": "kAudioMuteControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioMuteControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioMuteControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioLFEMuteControlClassID/title",
          "value": "kAudioLFEMuteControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioLFEMuteControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLFEMuteControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioTalkbackControlClassID/title",
          "value": "kAudioTalkbackControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioTalkbackControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioTalkbackControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioPhantomPowerControlClassID/title",
          "value": "kAudioPhantomPowerControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioPhantomPowerControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioPhantomPowerControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioSoloControlClassID/title",
          "value": "kAudioSoloControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioSoloControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSoloControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioPhaseInvertControlClassID/title",
          "value": "kAudioPhaseInvertControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioPhaseInvertControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioPhaseInvertControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioClipLightControlClassID/title",
          "value": "kAudioClipLightControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioClipLightControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioClipLightControlClassID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioListenbackControlClassID/title",
          "value": "kAudioListenbackControlClassID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioListenbackControlClassID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioListenbackControlClassID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/kaudiophantompowercontrolclassid"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/kaudiophantompowercontrolclassid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
