{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceHasChanged"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioDevicePropertyPlugIn@kAudioDevicePropertyDeviceHasChanged",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioDevicePropertyDeviceHasChanged"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
        "text": "AudioObjectPropertySelector"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioDevicePropertyDeviceHasChanged"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioDevicePropertyDeviceHasChanged"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyDeviceHasChanged"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
              "text": "AudioObjectPropertySelector"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertySelector",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertyselector"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceProcessorOverload": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceProcessorOverload"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceProcessorOverload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceProcessorOverload"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceProcessorOverload",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodeviceprocessoroverload"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyActualSampleRate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyActualSampleRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyActualSampleRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyActualSampleRate"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyActualSampleRate",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyactualsamplerate"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyBufferFrameSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyBufferFrameSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyBufferFrameSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyBufferFrameSize"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyBufferFrameSize",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertybufferframesize"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyBufferFrameSizeRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyBufferFrameSizeRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyBufferFrameSizeRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyBufferFrameSizeRange"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyBufferFrameSizeRange",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertybufferframesizerange"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyClockDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyClockDevice"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyClockDevice",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyclockdevice"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceHasChanged": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceHasChanged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceHasChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceHasChanged"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyDeviceHasChanged",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertydevicehaschanged"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceIsRunningSomewhere": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceIsRunningSomewhere"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceIsRunningSomewhere",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceIsRunningSomewhere"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyDeviceIsRunningSomewhere",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertydeviceisrunningsomewhere"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyHogMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyHogMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyHogMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyHogMode"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyHogMode",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyhogmode"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyIOCycleUsage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyIOCycleUsage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyIOCycleUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyIOCycleUsage"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyIOCycleUsage",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyiocycleusage"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyIOProcStreamUsage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyIOProcStreamUsage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyIOProcStreamUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyIOProcStreamUsage"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyIOProcStreamUsage",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyioprocstreamusage"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyIOStoppedAbnormally": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyIOStoppedAbnormally"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyIOStoppedAbnormally",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyIOStoppedAbnormally"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyIOStoppedAbnormally",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyiostoppedabnormally"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyPlugIn": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyPlugIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyPlugIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyPlugIn"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyPlugIn",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyplugin"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyStreamConfiguration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyStreamConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyStreamConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyStreamConfiguration"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyStreamConfiguration",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertystreamconfiguration"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyUsesVariableBufferFrameSizes": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyUsesVariableBufferFrameSizes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyUsesVariableBufferFrameSizes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyUsesVariableBufferFrameSizes"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyUsesVariableBufferFrameSizes",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyusesvariablebufferframesizes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceProcessorOverload",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyActualSampleRate",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyBufferFrameSize",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyBufferFrameSizeRange",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceIsRunningSomewhere",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyHogMode",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyIOCycleUsage",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyIOProcStreamUsage",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyIOStoppedAbnormally",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyPlugIn",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyStreamConfiguration",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyUsesVariableBufferFrameSizes",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockDevice"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioDevicePropertyDeviceHasChanged"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyDeviceHasChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudio/documentation/CoreAudio"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceProcessorOverload",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyActualSampleRate",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyBufferFrameSize",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyBufferFrameSizeRange",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceIsRunningSomewhere",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyHogMode",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyIOCycleUsage",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyIOProcStreamUsage",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyIOStoppedAbnormally",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyPlugIn",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyStreamConfiguration",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyUsesVariableBufferFrameSizes",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockDevice"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioDevicePropertyDeviceHasChanged"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceIsRunningSomewhere/title",
          "value": "kAudioDevicePropertyDeviceIsRunningSomewhere"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceIsRunningSomewhere/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyDeviceIsRunningSomewhere"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyStreamConfiguration/title",
          "value": "kAudioDevicePropertyStreamConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyStreamConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyStreamConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyActualSampleRate/title",
          "value": "kAudioDevicePropertyActualSampleRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyActualSampleRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyActualSampleRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceProcessorOverload/title",
          "value": "kAudioDeviceProcessorOverload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceProcessorOverload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceProcessorOverload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyIOCycleUsage/title",
          "value": "kAudioDevicePropertyIOCycleUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyIOCycleUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyIOCycleUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/title",
          "value": "AudioObjectPropertySelector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyUsesVariableBufferFrameSizes/title",
          "value": "kAudioDevicePropertyUsesVariableBufferFrameSizes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyUsesVariableBufferFrameSizes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyUsesVariableBufferFrameSizes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyClockDevice/title",
          "value": "kAudioDevicePropertyClockDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyClockDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyClockDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyHogMode/title",
          "value": "kAudioDevicePropertyHogMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyHogMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyHogMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyPlugIn/title",
          "value": "kAudioDevicePropertyPlugIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyPlugIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyPlugIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyBufferFrameSize/title",
          "value": "kAudioDevicePropertyBufferFrameSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyBufferFrameSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyBufferFrameSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyBufferFrameSizeRange/title",
          "value": "kAudioDevicePropertyBufferFrameSizeRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyBufferFrameSizeRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyBufferFrameSizeRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceHasChanged/title",
          "value": "kAudioDevicePropertyDeviceHasChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceHasChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyDeviceHasChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyIOProcStreamUsage/title",
          "value": "kAudioDevicePropertyIOProcStreamUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyIOProcStreamUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyIOProcStreamUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyIOStoppedAbnormally/title",
          "value": "kAudioDevicePropertyIOStoppedAbnormally"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyIOStoppedAbnormally/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyIOStoppedAbnormally"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/kaudiodevicepropertydevicehaschanged"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/kaudiodevicepropertydevicehaschanged"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
