{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeAirPlay"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioDeviceTransportTypeUnknown@kAudioDeviceTransportTypeAirPlay",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioDeviceTransportTypeAirPlay"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioDeviceTransportTypeAirPlay"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioDeviceTransportTypeAirPlay"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypeAirPlay"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeAVB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeAVB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeAVB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeAVB"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceTransportTypeAVB",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicetransporttypeavb"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeAggregate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeAggregate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeAggregate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeAggregate"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceTransportTypeAggregate",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicetransporttypeaggregate"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeAirPlay": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeAirPlay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeAirPlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeAirPlay"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceTransportTypeAirPlay",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicetransporttypeairplay"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeBluetooth": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeBluetooth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeBluetooth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeBluetooth"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceTransportTypeBluetooth",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicetransporttypebluetooth"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeBluetoothLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeBluetoothLE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeBluetoothLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeBluetoothLE"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceTransportTypeBluetoothLE",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicetransporttypebluetoothle"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeBuiltIn": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeBuiltIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeBuiltIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeBuiltIn"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceTransportTypeBuiltIn",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicetransporttypebuiltin"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeDisplayPort": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeDisplayPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeDisplayPort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeDisplayPort"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceTransportTypeDisplayPort",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicetransporttypedisplayport"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeFireWire": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeFireWire"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeFireWire",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeFireWire"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceTransportTypeFireWire",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicetransporttypefirewire"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeHDMI": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeHDMI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeHDMI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeHDMI"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceTransportTypeHDMI",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicetransporttypehdmi"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypePCI": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypePCI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypePCI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypePCI"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceTransportTypePCI",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicetransporttypepci"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeThunderbolt": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeThunderbolt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeThunderbolt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeThunderbolt"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceTransportTypeThunderbolt",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicetransporttypethunderbolt"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeUSB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeUSB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeUSB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeUSB"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceTransportTypeUSB",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicetransporttypeusb"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeUnknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeUnknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceTransportTypeUnknown",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicetransporttypeunknown"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeVirtual": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeVirtual"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeVirtual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceTransportTypeVirtual"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceTransportTypeVirtual",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicetransporttypevirtual"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeAVB",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeAggregate",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeBluetooth",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeBluetoothLE",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeBuiltIn",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeDisplayPort",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeFireWire",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeHDMI",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypePCI",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeThunderbolt",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeUSB",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeUnknown",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeVirtual"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioDeviceTransportTypeAirPlay"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypeAirPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudio/documentation/CoreAudio"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeAVB",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeAggregate",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeBluetooth",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeBluetoothLE",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeBuiltIn",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeDisplayPort",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeFireWire",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeHDMI",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypePCI",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeThunderbolt",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeUSB",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeUnknown",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceTransportTypeVirtual"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioDeviceTransportTypeAirPlay"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeUSB/title",
          "value": "kAudioDeviceTransportTypeUSB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeUSB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypeUSB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeAggregate/title",
          "value": "kAudioDeviceTransportTypeAggregate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeAggregate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypeAggregate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeBluetoothLE/title",
          "value": "kAudioDeviceTransportTypeBluetoothLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeBluetoothLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypeBluetoothLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeVirtual/title",
          "value": "kAudioDeviceTransportTypeVirtual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeVirtual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypeVirtual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeHDMI/title",
          "value": "kAudioDeviceTransportTypeHDMI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeHDMI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypeHDMI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeDisplayPort/title",
          "value": "kAudioDeviceTransportTypeDisplayPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeDisplayPort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypeDisplayPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeThunderbolt/title",
          "value": "kAudioDeviceTransportTypeThunderbolt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeThunderbolt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypeThunderbolt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeFireWire/title",
          "value": "kAudioDeviceTransportTypeFireWire"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeFireWire/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypeFireWire"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeUnknown/title",
          "value": "kAudioDeviceTransportTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypePCI/title",
          "value": "kAudioDeviceTransportTypePCI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypePCI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypePCI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeBuiltIn/title",
          "value": "kAudioDeviceTransportTypeBuiltIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeBuiltIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypeBuiltIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeBluetooth/title",
          "value": "kAudioDeviceTransportTypeBluetooth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeBluetooth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypeBluetooth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeAVB/title",
          "value": "kAudioDeviceTransportTypeAVB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeAVB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypeAVB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeAirPlay/title",
          "value": "kAudioDeviceTransportTypeAirPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceTransportTypeAirPlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceTransportTypeAirPlay"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/kaudiodevicetransporttypeairplay"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/kaudiodevicetransporttypeairplay"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
