{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInPropertyDeviceList"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioPlugInPropertyBundleID@kAudioPlugInPropertyDeviceList",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioPlugInPropertyDeviceList"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
        "text": "AudioObjectPropertySelector"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioPlugInPropertyDeviceList"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioPlugInPropertyDeviceList"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioPlugInPropertyDeviceList"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
              "text": "AudioObjectPropertySelector"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertySelector",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertyselector"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInPropertyBoxList": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioPlugInPropertyBoxList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInPropertyBoxList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioPlugInPropertyBoxList"
        }
      ],
      "role": "symbol",
      "title": "kAudioPlugInPropertyBoxList",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiopluginpropertyboxlist"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInPropertyBundleID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioPlugInPropertyBundleID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInPropertyBundleID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioPlugInPropertyBundleID"
        }
      ],
      "role": "symbol",
      "title": "kAudioPlugInPropertyBundleID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiopluginpropertybundleid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInPropertyClockDeviceList": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioPlugInPropertyClockDeviceList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInPropertyClockDeviceList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioPlugInPropertyClockDeviceList"
        }
      ],
      "role": "symbol",
      "title": "kAudioPlugInPropertyClockDeviceList",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiopluginpropertyclockdevicelist"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInPropertyDeviceList": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioPlugInPropertyDeviceList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInPropertyDeviceList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioPlugInPropertyDeviceList"
        }
      ],
      "role": "symbol",
      "title": "kAudioPlugInPropertyDeviceList",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiopluginpropertydevicelist"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInPropertyTranslateUIDToBox": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioPlugInPropertyTranslateUIDToBox"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInPropertyTranslateUIDToBox",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioPlugInPropertyTranslateUIDToBox"
        }
      ],
      "role": "symbol",
      "title": "kAudioPlugInPropertyTranslateUIDToBox",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiopluginpropertytranslateuidtobox"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInPropertyTranslateUIDToClockDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioPlugInPropertyTranslateUIDToClockDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInPropertyTranslateUIDToClockDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioPlugInPropertyTranslateUIDToClockDevice"
        }
      ],
      "role": "symbol",
      "title": "kAudioPlugInPropertyTranslateUIDToClockDevice",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiopluginpropertytranslateuidtoclockdevice"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInPropertyTranslateUIDToDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioPlugInPropertyTranslateUIDToDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInPropertyTranslateUIDToDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioPlugInPropertyTranslateUIDToDevice"
        }
      ],
      "role": "symbol",
      "title": "kAudioPlugInPropertyTranslateUIDToDevice",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiopluginpropertytranslateuidtodevice"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInPropertyBoxList",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInPropertyBundleID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInPropertyTranslateUIDToBox",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInPropertyTranslateUIDToDevice",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInPropertyClockDeviceList",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInPropertyTranslateUIDToClockDevice"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioPlugInPropertyDeviceList"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioPlugInPropertyDeviceList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudio/documentation/CoreAudio"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInPropertyBoxList",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInPropertyBundleID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInPropertyTranslateUIDToBox",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInPropertyTranslateUIDToDevice",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInPropertyClockDeviceList",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioPlugInPropertyTranslateUIDToClockDevice"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioPlugInPropertyDeviceList"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/title",
          "value": "AudioObjectPropertySelector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioPlugInPropertyClockDeviceList/title",
          "value": "kAudioPlugInPropertyClockDeviceList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioPlugInPropertyClockDeviceList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioPlugInPropertyClockDeviceList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioPlugInPropertyBoxList/title",
          "value": "kAudioPlugInPropertyBoxList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioPlugInPropertyBoxList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioPlugInPropertyBoxList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioPlugInPropertyDeviceList/title",
          "value": "kAudioPlugInPropertyDeviceList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioPlugInPropertyDeviceList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioPlugInPropertyDeviceList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioPlugInPropertyTranslateUIDToBox/title",
          "value": "kAudioPlugInPropertyTranslateUIDToBox"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioPlugInPropertyTranslateUIDToBox/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioPlugInPropertyTranslateUIDToBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioPlugInPropertyTranslateUIDToClockDevice/title",
          "value": "kAudioPlugInPropertyTranslateUIDToClockDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioPlugInPropertyTranslateUIDToClockDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioPlugInPropertyTranslateUIDToClockDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioPlugInPropertyTranslateUIDToDevice/title",
          "value": "kAudioPlugInPropertyTranslateUIDToDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioPlugInPropertyTranslateUIDToDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioPlugInPropertyTranslateUIDToDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioPlugInPropertyBundleID/title",
          "value": "kAudioPlugInPropertyBundleID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioPlugInPropertyBundleID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioPlugInPropertyBundleID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/kaudiopluginpropertydevicelist"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/kaudiopluginpropertydevicelist"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
