{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeDigitalAudioInterface"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioStreamTerminalTypeUnknown@kAudioStreamTerminalTypeDigitalAudioInterface",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioStreamTerminalTypeDigitalAudioInterface"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioStreamTerminalTypeDigitalAudioInterface"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioStreamTerminalTypeDigitalAudioInterface"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioStreamTerminalTypeDigitalAudioInterface"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeDigitalAudioInterface": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamTerminalTypeDigitalAudioInterface"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeDigitalAudioInterface",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamTerminalTypeDigitalAudioInterface"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamTerminalTypeDigitalAudioInterface",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreamterminaltypedigitalaudiointerface"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeDisplayPort": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamTerminalTypeDisplayPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeDisplayPort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamTerminalTypeDisplayPort"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamTerminalTypeDisplayPort",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreamterminaltypedisplayport"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeHDMI": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamTerminalTypeHDMI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeHDMI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamTerminalTypeHDMI"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamTerminalTypeHDMI",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreamterminaltypehdmi"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeHeadphones": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamTerminalTypeHeadphones"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeHeadphones",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamTerminalTypeHeadphones"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamTerminalTypeHeadphones",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreamterminaltypeheadphones"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeHeadsetMicrophone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamTerminalTypeHeadsetMicrophone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeHeadsetMicrophone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamTerminalTypeHeadsetMicrophone"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamTerminalTypeHeadsetMicrophone",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreamterminaltypeheadsetmicrophone"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeLFESpeaker": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamTerminalTypeLFESpeaker"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeLFESpeaker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamTerminalTypeLFESpeaker"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamTerminalTypeLFESpeaker",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreamterminaltypelfespeaker"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeLine": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamTerminalTypeLine"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeLine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamTerminalTypeLine"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamTerminalTypeLine",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreamterminaltypeline"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeMicrophone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamTerminalTypeMicrophone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeMicrophone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamTerminalTypeMicrophone"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamTerminalTypeMicrophone",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreamterminaltypemicrophone"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeReceiverMicrophone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamTerminalTypeReceiverMicrophone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeReceiverMicrophone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamTerminalTypeReceiverMicrophone"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamTerminalTypeReceiverMicrophone",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreamterminaltypereceivermicrophone"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeReceiverSpeaker": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamTerminalTypeReceiverSpeaker"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeReceiverSpeaker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamTerminalTypeReceiverSpeaker"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamTerminalTypeReceiverSpeaker",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreamterminaltypereceiverspeaker"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeSpeaker": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamTerminalTypeSpeaker"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeSpeaker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamTerminalTypeSpeaker"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamTerminalTypeSpeaker",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreamterminaltypespeaker"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeTTY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamTerminalTypeTTY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeTTY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamTerminalTypeTTY"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamTerminalTypeTTY",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreamterminaltypetty"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeUnknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamTerminalTypeUnknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamTerminalTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamTerminalTypeUnknown",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreamterminaltypeunknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeDisplayPort",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeHDMI",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeHeadphones",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeHeadsetMicrophone",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeLFESpeaker",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeLine",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeMicrophone",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeReceiverMicrophone",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeReceiverSpeaker",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeSpeaker",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeTTY",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeUnknown"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioStreamTerminalTypeDigitalAudioInterface"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamTerminalTypeDigitalAudioInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudio/documentation/CoreAudio"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeDisplayPort",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeHDMI",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeHeadphones",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeHeadsetMicrophone",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeLFESpeaker",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeLine",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeMicrophone",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeReceiverMicrophone",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeReceiverSpeaker",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeSpeaker",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeTTY",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamTerminalTypeUnknown"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioStreamTerminalTypeDigitalAudioInterface"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamTerminalTypeHDMI/title",
          "value": "kAudioStreamTerminalTypeHDMI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamTerminalTypeHDMI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamTerminalTypeHDMI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamTerminalTypeLFESpeaker/title",
          "value": "kAudioStreamTerminalTypeLFESpeaker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamTerminalTypeLFESpeaker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamTerminalTypeLFESpeaker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamTerminalTypeMicrophone/title",
          "value": "kAudioStreamTerminalTypeMicrophone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamTerminalTypeMicrophone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamTerminalTypeMicrophone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamTerminalTypeReceiverSpeaker/title",
          "value": "kAudioStreamTerminalTypeReceiverSpeaker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamTerminalTypeReceiverSpeaker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamTerminalTypeReceiverSpeaker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamTerminalTypeSpeaker/title",
          "value": "kAudioStreamTerminalTypeSpeaker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamTerminalTypeSpeaker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamTerminalTypeSpeaker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamTerminalTypeTTY/title",
          "value": "kAudioStreamTerminalTypeTTY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamTerminalTypeTTY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamTerminalTypeTTY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamTerminalTypeUnknown/title",
          "value": "kAudioStreamTerminalTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamTerminalTypeUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamTerminalTypeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamTerminalTypeDisplayPort/title",
          "value": "kAudioStreamTerminalTypeDisplayPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamTerminalTypeDisplayPort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamTerminalTypeDisplayPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamTerminalTypeHeadphones/title",
          "value": "kAudioStreamTerminalTypeHeadphones"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamTerminalTypeHeadphones/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamTerminalTypeHeadphones"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamTerminalTypeHeadsetMicrophone/title",
          "value": "kAudioStreamTerminalTypeHeadsetMicrophone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamTerminalTypeHeadsetMicrophone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamTerminalTypeHeadsetMicrophone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamTerminalTypeReceiverMicrophone/title",
          "value": "kAudioStreamTerminalTypeReceiverMicrophone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamTerminalTypeReceiverMicrophone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamTerminalTypeReceiverMicrophone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamTerminalTypeLine/title",
          "value": "kAudioStreamTerminalTypeLine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamTerminalTypeLine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamTerminalTypeLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamTerminalTypeDigitalAudioInterface/title",
          "value": "kAudioStreamTerminalTypeDigitalAudioInterface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamTerminalTypeDigitalAudioInterface/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamTerminalTypeDigitalAudioInterface"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/kaudiostreamterminaltypedigitalaudiointerface"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/kaudiostreamterminaltypedigitalaudiointerface"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
