{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coreaudio/documentation/CoreAudio"]]},"seeAlsoSections":[{"generated":true,"title":"Constants","identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyBaseClass","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyClass","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementCategoryName","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementName","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementNumberName","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyIdentify","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyManufacturer","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyModelName","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyName","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyOwnedObjects","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyOwner","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertySerialNumber"],"anchor":"Constants"}],"identifier":{"url":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyFirmwareVersion","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"kAudioObjectPropertyFirmwareVersion","kind":"identifier"}],"externalID":"c:@Ea@kAudioObjectPropertyBaseClass@kAudioObjectPropertyFirmwareVersion","platforms":[{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false},{"name":"macOS","beta":false,"deprecated":false,"unavailable":false}],"title":"kAudioObjectPropertyFirmwareVersion","symbolKind":"var","modules":[{"name":"Core Audio"}],"roleHeading":"Global Variable","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioObjectPropertyFirmwareVersion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioObjectPropertyFirmwareVersion"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@AudioObjectPropertySelector","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector","kind":"typeIdentifier","text":"AudioObjectPropertySelector"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["Mac Catalyst","macOS"]}]}],"variants":[{"paths":["/documentation/coreaudio/kaudioobjectpropertyfirmwareversion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/coreaudio/kaudioobjectpropertyfirmwareversion"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyModelName":{"role":"symbol","abstract":[],"url":"/documentation/coreaudio/kaudioobjectpropertymodelname","type":"topic","title":"kAudioObjectPropertyModelName","navigatorTitle":[{"text":"kAudioObjectPropertyModelName","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioObjectPropertyModelName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AudioObjectPropertySelector","text":"AudioObjectPropertySelector","kind":"typeIdentifier"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyModelName"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyManufacturer":{"type":"topic","navigatorTitle":[{"text":"kAudioObjectPropertyManufacturer","kind":"identifier"}],"role":"symbol","url":"/documentation/coreaudio/kaudioobjectpropertymanufacturer","title":"kAudioObjectPropertyManufacturer","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyManufacturer","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioObjectPropertyManufacturer","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector","kind":"typeIdentifier"}],"kind":"symbol","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementNumberName":{"abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioObjectPropertyElementNumberName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"url":"/documentation/coreaudio/kaudioobjectpropertyelementnumbername","type":"topic","kind":"symbol","title":"kAudioObjectPropertyElementNumberName","navigatorTitle":[{"text":"kAudioObjectPropertyElementNumberName","kind":"identifier"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementNumberName"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyBaseClass":{"kind":"symbol","type":"topic","url":"/documentation/coreaudio/kaudioobjectpropertybaseclass","title":"kAudioObjectPropertyBaseClass","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioObjectPropertyBaseClass"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyBaseClass","role":"symbol","navigatorTitle":[{"text":"kAudioObjectPropertyBaseClass","kind":"identifier"}],"abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyClass":{"kind":"symbol","type":"topic","url":"/documentation/coreaudio/kaudioobjectpropertyclass","title":"kAudioObjectPropertyClass","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"kAudioObjectPropertyClass","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyClass","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kAudioObjectPropertyClass"}],"abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyOwnedObjects":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"kAudioObjectPropertyOwnedObjects"}],"role":"symbol","url":"/documentation/coreaudio/kaudioobjectpropertyownedobjects","title":"kAudioObjectPropertyOwnedObjects","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyOwnedObjects","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioObjectPropertyOwnedObjects"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"kind":"symbol","abstract":[]},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","role":"overview","kind":"technologies"},"doc://com.apple.coreaudio/documentation/CoreAudio":{"kind":"symbol","title":"Core Audio","type":"topic","abstract":[{"type":"text","text":"Use the Core Audio framework to interact with device’s audio hardware."}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio","url":"/documentation/coreaudio","role":"collection"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyIdentify":{"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioObjectPropertyIdentify","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyIdentify","navigatorTitle":[{"text":"kAudioObjectPropertyIdentify","kind":"identifier"}],"abstract":[],"url":"/documentation/coreaudio/kaudioobjectpropertyidentify","title":"kAudioObjectPropertyIdentify","kind":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementCategoryName":{"type":"topic","navigatorTitle":[{"text":"kAudioObjectPropertyElementCategoryName","kind":"identifier"}],"role":"symbol","url":"/documentation/coreaudio/kaudioobjectpropertyelementcategoryname","title":"kAudioObjectPropertyElementCategoryName","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementCategoryName","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioObjectPropertyElementCategoryName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"kind":"symbol","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementName":{"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"kAudioObjectPropertyElementName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"url":"/documentation/coreaudio/kaudioobjectpropertyelementname","type":"topic","kind":"symbol","title":"kAudioObjectPropertyElementName","navigatorTitle":[{"text":"kAudioObjectPropertyElementName","kind":"identifier"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementName"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyName":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioObjectPropertyName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AudioObjectPropertySelector","text":"AudioObjectPropertySelector","kind":"typeIdentifier"}],"type":"topic","url":"/documentation/coreaudio/kaudioobjectpropertyname","kind":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyName","abstract":[],"role":"symbol","navigatorTitle":[{"text":"kAudioObjectPropertyName","kind":"identifier"}],"title":"kAudioObjectPropertyName"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyFirmwareVersion":{"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"kAudioObjectPropertyFirmwareVersion","kind":"identifier"}],"url":"/documentation/coreaudio/kaudioobjectpropertyfirmwareversion","title":"kAudioObjectPropertyFirmwareVersion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"kAudioObjectPropertyFirmwareVersion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyFirmwareVersion","role":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertySerialNumber":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioObjectPropertySerialNumber","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AudioObjectPropertySelector","text":"AudioObjectPropertySelector","kind":"typeIdentifier"}],"type":"topic","url":"/documentation/coreaudio/kaudioobjectpropertyserialnumber","kind":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertySerialNumber","abstract":[],"role":"symbol","navigatorTitle":[{"text":"kAudioObjectPropertySerialNumber","kind":"identifier"}],"title":"kAudioObjectPropertySerialNumber"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyOwner":{"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"kAudioObjectPropertyOwner"}],"url":"/documentation/coreaudio/kaudioobjectpropertyowner","title":"kAudioObjectPropertyOwner","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kAudioObjectPropertyOwner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyOwner","role":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector":{"type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector","navigatorTitle":[{"text":"AudioObjectPropertySelector","kind":"identifier"}],"url":"/documentation/coreaudio/audioobjectpropertyselector","abstract":[],"title":"AudioObjectPropertySelector","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"identifier"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"unavailable":false,"deprecated":false,"name":"Mac Catalyst","beta":false},{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"/metadata/title","value":"kAudioObjectPropertyFirmwareVersion"},{"op":"replace","path":"/metadata/symbolKind","value":"case"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"kAudioObjectPropertyFirmwareVersion","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coreaudio/documentation/CoreAudio"]]}},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"anchor":"Constants","title":"Constants","generated":true,"identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyBaseClass","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyClass","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementCategoryName","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementName","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementNumberName","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyIdentify","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyManufacturer","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyModelName","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyName","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyOwnedObjects","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyOwner","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertySerialNumber"]}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"kAudioObjectPropertyFirmwareVersion","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyModelName/title","op":"replace","value":"kAudioObjectPropertyModelName"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyModelName/fragments","op":"replace","value":[{"kind":"identifier","text":"kAudioObjectPropertyModelName"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyManufacturer/title","op":"replace","value":"kAudioObjectPropertyManufacturer"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyManufacturer/fragments","op":"replace","value":[{"text":"kAudioObjectPropertyManufacturer","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyElementNumberName/title","op":"replace","value":"kAudioObjectPropertyElementNumberName"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyElementNumberName/fragments","op":"replace","value":[{"text":"kAudioObjectPropertyElementNumberName","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyBaseClass/title","op":"replace","value":"kAudioObjectPropertyBaseClass"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyBaseClass/fragments","op":"replace","value":[{"kind":"identifier","text":"kAudioObjectPropertyBaseClass"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyClass/title","op":"replace","value":"kAudioObjectPropertyClass"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyClass/fragments","op":"replace","value":[{"text":"kAudioObjectPropertyClass","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyOwnedObjects/title","op":"replace","value":"kAudioObjectPropertyOwnedObjects"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyOwnedObjects/fragments","op":"replace","value":[{"text":"kAudioObjectPropertyOwnedObjects","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyIdentify/title","op":"replace","value":"kAudioObjectPropertyIdentify"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyIdentify/fragments","op":"replace","value":[{"kind":"identifier","text":"kAudioObjectPropertyIdentify"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyElementCategoryName/title","op":"replace","value":"kAudioObjectPropertyElementCategoryName"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyElementCategoryName/fragments","op":"replace","value":[{"text":"kAudioObjectPropertyElementCategoryName","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyElementName/title","op":"replace","value":"kAudioObjectPropertyElementName"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyElementName/fragments","op":"replace","value":[{"text":"kAudioObjectPropertyElementName","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyName/title","op":"replace","value":"kAudioObjectPropertyName"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyName/fragments","op":"replace","value":[{"kind":"identifier","text":"kAudioObjectPropertyName"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyFirmwareVersion/title","op":"replace","value":"kAudioObjectPropertyFirmwareVersion"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyFirmwareVersion/fragments","op":"replace","value":[{"kind":"identifier","text":"kAudioObjectPropertyFirmwareVersion"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertySerialNumber/title","op":"replace","value":"kAudioObjectPropertySerialNumber"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertySerialNumber/fragments","op":"replace","value":[{"kind":"identifier","text":"kAudioObjectPropertySerialNumber"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyOwner/title","op":"replace","value":"kAudioObjectPropertyOwner"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyOwner/fragments","op":"replace","value":[{"text":"kAudioObjectPropertyOwner","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/title","op":"replace","value":"AudioObjectPropertySelector"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/fragments","op":"replace","value":[{"kind":"identifier","text":"AudioObjectPropertySelector"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AudioObjectPropertySelector"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}