{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyStartingChannel"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioStreamPropertyIsActive@kAudioStreamPropertyStartingChannel",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioStreamPropertyStartingChannel"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
        "text": "AudioObjectPropertySelector"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioStreamPropertyStartingChannel"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioStreamPropertyStartingChannel"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioStreamPropertyStartingChannel"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
              "text": "AudioObjectPropertySelector"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertySelector",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertyselector"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyAvailablePhysicalFormats": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyAvailablePhysicalFormats"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyAvailablePhysicalFormats",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyAvailablePhysicalFormats"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamPropertyAvailablePhysicalFormats",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreampropertyavailablephysicalformats"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyAvailableVirtualFormats": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyAvailableVirtualFormats"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyAvailableVirtualFormats",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyAvailableVirtualFormats"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamPropertyAvailableVirtualFormats",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreampropertyavailablevirtualformats"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyDirection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyDirection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyDirection"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamPropertyDirection",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreampropertydirection"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyIsActive": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyIsActive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyIsActive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyIsActive"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamPropertyIsActive",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreampropertyisactive"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyLatency": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyLatency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyLatency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyLatency"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamPropertyLatency",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreampropertylatency"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyPhysicalFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyPhysicalFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyPhysicalFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyPhysicalFormat"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamPropertyPhysicalFormat",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreampropertyphysicalformat"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyStartingChannel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyStartingChannel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyStartingChannel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyStartingChannel"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamPropertyStartingChannel",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreampropertystartingchannel"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyTerminalType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyTerminalType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyTerminalType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyTerminalType"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamPropertyTerminalType",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreampropertyterminaltype"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyVirtualFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyVirtualFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyVirtualFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioStreamPropertyVirtualFormat"
        }
      ],
      "role": "symbol",
      "title": "kAudioStreamPropertyVirtualFormat",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiostreampropertyvirtualformat"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyAvailablePhysicalFormats",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyAvailableVirtualFormats",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyDirection",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyIsActive",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyLatency",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyPhysicalFormat",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyTerminalType",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyVirtualFormat"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioStreamPropertyStartingChannel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamPropertyStartingChannel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudio/documentation/CoreAudio"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyAvailablePhysicalFormats",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyAvailableVirtualFormats",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyDirection",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyIsActive",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyLatency",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyPhysicalFormat",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyTerminalType",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioStreamPropertyVirtualFormat"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioStreamPropertyStartingChannel"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyTerminalType/title",
          "value": "kAudioStreamPropertyTerminalType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyTerminalType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamPropertyTerminalType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyLatency/title",
          "value": "kAudioStreamPropertyLatency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyLatency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamPropertyLatency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyDirection/title",
          "value": "kAudioStreamPropertyDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamPropertyDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyAvailablePhysicalFormats/title",
          "value": "kAudioStreamPropertyAvailablePhysicalFormats"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyAvailablePhysicalFormats/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamPropertyAvailablePhysicalFormats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyAvailableVirtualFormats/title",
          "value": "kAudioStreamPropertyAvailableVirtualFormats"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyAvailableVirtualFormats/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamPropertyAvailableVirtualFormats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyIsActive/title",
          "value": "kAudioStreamPropertyIsActive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyIsActive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamPropertyIsActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyVirtualFormat/title",
          "value": "kAudioStreamPropertyVirtualFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyVirtualFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamPropertyVirtualFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyStartingChannel/title",
          "value": "kAudioStreamPropertyStartingChannel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyStartingChannel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamPropertyStartingChannel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/title",
          "value": "AudioObjectPropertySelector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyPhysicalFormat/title",
          "value": "kAudioStreamPropertyPhysicalFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioStreamPropertyPhysicalFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioStreamPropertyPhysicalFormat"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/kaudiostreampropertystartingchannel"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/kaudiostreampropertystartingchannel"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
