{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePermissionsError"},"metadata":{"modules":[{"name":"Core Audio"}],"roleHeading":"Global Variable","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioDevicePermissionsError"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier","text":"OSStatus"}],"symbolKind":"var","navigatorTitle":[{"kind":"identifier","text":"kAudioDevicePermissionsError"}],"role":"symbol","title":"kAudioDevicePermissionsError","platforms":[{"beta":false,"deprecated":false,"unavailable":false,"name":"Mac Catalyst"},{"unavailable":false,"beta":false,"name":"macOS","deprecated":false}],"externalID":"c:@Ea@kAudioHardwareNoError@kAudioDevicePermissionsError"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioDevicePermissionsError","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@OSStatus","text":"OSStatus","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/coreaudio/kaudiodevicepermissionserror"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/coreaudio/kaudiodevicepermissionserror"]}],"seeAlsoSections":[{"generated":true,"title":"Constants","identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceUnsupportedFormatError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadDeviceError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadObjectError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadPropertySizeError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadStreamError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareIllegalOperationError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareNoError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareNotRunningError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnknownPropertyError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnspecifiedError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnsupportedOperationError"],"anchor":"Constants"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coreaudio/documentation/CoreAudio"]]},"references":{"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnsupportedOperationError":{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnsupportedOperationError","role":"symbol","url":"/documentation/coreaudio/kaudiohardwareunsupportedoperationerror","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioHardwareUnsupportedOperationError"},{"text":": ","kind":"text"},{"text":"OSStatus","preciseIdentifier":"c:@T@OSStatus","kind":"typeIdentifier"}],"abstract":[],"title":"kAudioHardwareUnsupportedOperationError","kind":"symbol","navigatorTitle":[{"text":"kAudioHardwareUnsupportedOperationError","kind":"identifier"}]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePermissionsError":{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePermissionsError","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioDevicePermissionsError","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@OSStatus","text":"OSStatus","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"kAudioDevicePermissionsError","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"/documentation/coreaudio/kaudiodevicepermissionserror","title":"kAudioDevicePermissionsError"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceUnsupportedFormatError":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioDeviceUnsupportedFormatError"},{"text":": ","kind":"text"},{"text":"OSStatus","kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus"}],"type":"topic","navigatorTitle":[{"text":"kAudioDeviceUnsupportedFormatError","kind":"identifier"}],"kind":"symbol","url":"/documentation/coreaudio/kaudiodeviceunsupportedformaterror","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceUnsupportedFormatError","title":"kAudioDeviceUnsupportedFormatError","abstract":[],"role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","role":"overview","kind":"technologies"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareNotRunningError":{"abstract":[],"title":"kAudioHardwareNotRunningError","navigatorTitle":[{"text":"kAudioHardwareNotRunningError","kind":"identifier"}],"url":"/documentation/coreaudio/kaudiohardwarenotrunningerror","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwareNotRunningError","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@OSStatus","text":"OSStatus","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareNotRunningError"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareNoError":{"abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwareNoError","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@OSStatus","text":"OSStatus","kind":"typeIdentifier"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareNoError","kind":"symbol","title":"kAudioHardwareNoError","url":"/documentation/coreaudio/kaudiohardwarenoerror","type":"topic","navigatorTitle":[{"text":"kAudioHardwareNoError","kind":"identifier"}]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnspecifiedError":{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnspecifiedError","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwareUnspecifiedError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"OSStatus","kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus"}],"navigatorTitle":[{"text":"kAudioHardwareUnspecifiedError","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"/documentation/coreaudio/kaudiohardwareunspecifiederror","title":"kAudioHardwareUnspecifiedError"},"doc://com.apple.coreaudio/documentation/CoreAudio":{"kind":"symbol","title":"Core Audio","type":"topic","abstract":[{"type":"text","text":"Use the Core Audio framework to interact with device’s audio hardware."}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio","url":"/documentation/coreaudio","role":"collection"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareIllegalOperationError":{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareIllegalOperationError","role":"symbol","url":"/documentation/coreaudio/kaudiohardwareillegaloperationerror","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwareIllegalOperationError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"OSStatus","kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus"}],"abstract":[],"title":"kAudioHardwareIllegalOperationError","kind":"symbol","navigatorTitle":[{"text":"kAudioHardwareIllegalOperationError","kind":"identifier"}]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadObjectError":{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadObjectError","abstract":[],"kind":"symbol","title":"kAudioHardwareBadObjectError","url":"/documentation/coreaudio/kaudiohardwarebadobjecterror","navigatorTitle":[{"kind":"identifier","text":"kAudioHardwareBadObjectError"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioHardwareBadObjectError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OSStatus","preciseIdentifier":"c:@T@OSStatus"}],"type":"topic","role":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnknownPropertyError":{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnknownPropertyError","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwareUnknownPropertyError","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@OSStatus","text":"OSStatus","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"kAudioHardwareUnknownPropertyError","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"/documentation/coreaudio/kaudiohardwareunknownpropertyerror","title":"kAudioHardwareUnknownPropertyError"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadDeviceError":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwareBadDeviceError","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@OSStatus","text":"OSStatus","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"kAudioHardwareBadDeviceError","kind":"identifier"}],"kind":"symbol","url":"/documentation/coreaudio/kaudiohardwarebaddeviceerror","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadDeviceError","title":"kAudioHardwareBadDeviceError","abstract":[],"role":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadPropertySizeError":{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadPropertySizeError","abstract":[],"kind":"symbol","title":"kAudioHardwareBadPropertySizeError","url":"/documentation/coreaudio/kaudiohardwarebadpropertysizeerror","navigatorTitle":[{"text":"kAudioHardwareBadPropertySizeError","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwareBadPropertySizeError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"OSStatus","kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus"}],"type":"topic","role":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadStreamError":{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadStreamError","abstract":[],"kind":"symbol","title":"kAudioHardwareBadStreamError","url":"/documentation/coreaudio/kaudiohardwarebadstreamerror","navigatorTitle":[{"text":"kAudioHardwareBadStreamError","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwareBadStreamError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"OSStatus","kind":"typeIdentifier","preciseIdentifier":"c:@T@OSStatus"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"beta":false,"name":"Mac Catalyst","deprecated":false},{"unavailable":false,"beta":false,"name":"macOS","deprecated":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"/metadata/title","value":"kAudioDevicePermissionsError","op":"replace"},{"path":"/metadata/symbolKind","value":"case","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"kAudioDevicePermissionsError"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coreaudio/documentation/CoreAudio"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"generated":true,"identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceUnsupportedFormatError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadDeviceError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadObjectError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadPropertySizeError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadStreamError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareIllegalOperationError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareNoError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareNotRunningError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnknownPropertyError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnspecifiedError","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnsupportedOperationError"],"title":"Constants","anchor":"Constants"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"text":"kAudioDevicePermissionsError","kind":"identifier"}]}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareUnsupportedOperationError/title","op":"replace","value":"kAudioHardwareUnsupportedOperationError"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareUnsupportedOperationError/fragments","op":"replace","value":[{"kind":"identifier","text":"kAudioHardwareUnsupportedOperationError"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePermissionsError/title","op":"replace","value":"kAudioDevicePermissionsError"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePermissionsError/fragments","op":"replace","value":[{"text":"kAudioDevicePermissionsError","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceUnsupportedFormatError/title","op":"replace","value":"kAudioDeviceUnsupportedFormatError"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceUnsupportedFormatError/fragments","op":"replace","value":[{"text":"kAudioDeviceUnsupportedFormatError","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareNotRunningError/title","op":"replace","value":"kAudioHardwareNotRunningError"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareNotRunningError/fragments","op":"replace","value":[{"kind":"identifier","text":"kAudioHardwareNotRunningError"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareNoError/title","op":"replace","value":"kAudioHardwareNoError"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareNoError/fragments","op":"replace","value":[{"kind":"identifier","text":"kAudioHardwareNoError"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareUnspecifiedError/title","op":"replace","value":"kAudioHardwareUnspecifiedError"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareUnspecifiedError/fragments","op":"replace","value":[{"text":"kAudioHardwareUnspecifiedError","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareIllegalOperationError/title","op":"replace","value":"kAudioHardwareIllegalOperationError"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareIllegalOperationError/fragments","op":"replace","value":[{"text":"kAudioHardwareIllegalOperationError","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareBadObjectError/title","op":"replace","value":"kAudioHardwareBadObjectError"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareBadObjectError/fragments","op":"replace","value":[{"kind":"identifier","text":"kAudioHardwareBadObjectError"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareUnknownPropertyError/title","op":"replace","value":"kAudioHardwareUnknownPropertyError"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareUnknownPropertyError/fragments","op":"replace","value":[{"kind":"identifier","text":"kAudioHardwareUnknownPropertyError"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareBadDeviceError/title","op":"replace","value":"kAudioHardwareBadDeviceError"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareBadDeviceError/fragments","op":"replace","value":[{"text":"kAudioHardwareBadDeviceError","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareBadPropertySizeError/title","op":"replace","value":"kAudioHardwareBadPropertySizeError"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareBadPropertySizeError/fragments","op":"replace","value":[{"text":"kAudioHardwareBadPropertySizeError","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareBadStreamError/title","op":"replace","value":"kAudioHardwareBadStreamError"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareBadStreamError/fragments","op":"replace","value":[{"text":"kAudioHardwareBadStreamError","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}