{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnspecifiedError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioHardwareNoError@kAudioHardwareUnspecifiedError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioHardwareUnspecifiedError"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioHardwareUnspecifiedError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioHardwareUnspecifiedError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioHardwareUnspecifiedError"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePermissionsError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePermissionsError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePermissionsError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePermissionsError"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePermissionsError",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepermissionserror"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceUnsupportedFormatError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDeviceUnsupportedFormatError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceUnsupportedFormatError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDeviceUnsupportedFormatError"
        }
      ],
      "role": "symbol",
      "title": "kAudioDeviceUnsupportedFormatError",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodeviceunsupportedformaterror"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadDeviceError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwareBadDeviceError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadDeviceError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwareBadDeviceError"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwareBadDeviceError",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiohardwarebaddeviceerror"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadObjectError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwareBadObjectError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadObjectError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwareBadObjectError"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwareBadObjectError",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiohardwarebadobjecterror"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadPropertySizeError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwareBadPropertySizeError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadPropertySizeError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwareBadPropertySizeError"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwareBadPropertySizeError",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiohardwarebadpropertysizeerror"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadStreamError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwareBadStreamError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadStreamError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwareBadStreamError"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwareBadStreamError",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiohardwarebadstreamerror"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareIllegalOperationError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwareIllegalOperationError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareIllegalOperationError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwareIllegalOperationError"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwareIllegalOperationError",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiohardwareillegaloperationerror"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareNoError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwareNoError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareNoError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwareNoError"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwareNoError",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiohardwarenoerror"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareNotRunningError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwareNotRunningError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareNotRunningError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwareNotRunningError"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwareNotRunningError",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiohardwarenotrunningerror"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnknownPropertyError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwareUnknownPropertyError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnknownPropertyError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwareUnknownPropertyError"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwareUnknownPropertyError",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiohardwareunknownpropertyerror"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnspecifiedError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwareUnspecifiedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnspecifiedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwareUnspecifiedError"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwareUnspecifiedError",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiohardwareunspecifiederror"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnsupportedOperationError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwareUnsupportedOperationError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnsupportedOperationError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwareUnsupportedOperationError"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwareUnsupportedOperationError",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiohardwareunsupportedoperationerror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePermissionsError",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceUnsupportedFormatError",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadDeviceError",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadObjectError",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadPropertySizeError",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadStreamError",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareIllegalOperationError",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareNoError",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareNotRunningError",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnknownPropertyError",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnsupportedOperationError"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioHardwareUnspecifiedError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwareUnspecifiedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudio/documentation/CoreAudio"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePermissionsError",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDeviceUnsupportedFormatError",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadDeviceError",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadObjectError",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadPropertySizeError",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareBadStreamError",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareIllegalOperationError",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareNoError",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareNotRunningError",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnknownPropertyError",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwareUnsupportedOperationError"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioHardwareUnspecifiedError"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareNotRunningError/title",
          "value": "kAudioHardwareNotRunningError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareNotRunningError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwareNotRunningError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareBadDeviceError/title",
          "value": "kAudioHardwareBadDeviceError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareBadDeviceError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwareBadDeviceError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareUnsupportedOperationError/title",
          "value": "kAudioHardwareUnsupportedOperationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareUnsupportedOperationError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwareUnsupportedOperationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareIllegalOperationError/title",
          "value": "kAudioHardwareIllegalOperationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareIllegalOperationError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwareIllegalOperationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareUnknownPropertyError/title",
          "value": "kAudioHardwareUnknownPropertyError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareUnknownPropertyError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwareUnknownPropertyError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceUnsupportedFormatError/title",
          "value": "kAudioDeviceUnsupportedFormatError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDeviceUnsupportedFormatError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDeviceUnsupportedFormatError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareBadObjectError/title",
          "value": "kAudioHardwareBadObjectError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareBadObjectError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwareBadObjectError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareBadPropertySizeError/title",
          "value": "kAudioHardwareBadPropertySizeError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareBadPropertySizeError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwareBadPropertySizeError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareBadStreamError/title",
          "value": "kAudioHardwareBadStreamError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareBadStreamError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwareBadStreamError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareNoError/title",
          "value": "kAudioHardwareNoError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareNoError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwareNoError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareUnspecifiedError/title",
          "value": "kAudioHardwareUnspecifiedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwareUnspecifiedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwareUnspecifiedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePermissionsError/title",
          "value": "kAudioDevicePermissionsError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePermissionsError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePermissionsError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/kaudiohardwareunspecifiederror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/kaudiohardwareunspecifiederror"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
