{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyBoxUID"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioBoxPropertyBoxUID@kAudioBoxPropertyBoxUID",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioBoxPropertyBoxUID"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
        "text": "AudioObjectPropertySelector"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioBoxPropertyBoxUID"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioBoxPropertyBoxUID"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioBoxPropertyBoxUID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
              "text": "AudioObjectPropertySelector"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertySelector",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertyselector"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyAcquired": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioBoxPropertyAcquired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyAcquired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioBoxPropertyAcquired"
        }
      ],
      "role": "symbol",
      "title": "kAudioBoxPropertyAcquired",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioboxpropertyacquired"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyAcquisitionFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioBoxPropertyAcquisitionFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyAcquisitionFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioBoxPropertyAcquisitionFailed"
        }
      ],
      "role": "symbol",
      "title": "kAudioBoxPropertyAcquisitionFailed",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioboxpropertyacquisitionfailed"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyBoxUID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioBoxPropertyBoxUID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyBoxUID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioBoxPropertyBoxUID"
        }
      ],
      "role": "symbol",
      "title": "kAudioBoxPropertyBoxUID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioboxpropertyboxuid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyClockDeviceList": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioBoxPropertyClockDeviceList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyClockDeviceList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioBoxPropertyClockDeviceList"
        }
      ],
      "role": "symbol",
      "title": "kAudioBoxPropertyClockDeviceList",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioboxpropertyclockdevicelist"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyDeviceList": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioBoxPropertyDeviceList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyDeviceList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioBoxPropertyDeviceList"
        }
      ],
      "role": "symbol",
      "title": "kAudioBoxPropertyDeviceList",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioboxpropertydevicelist"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyHasAudio": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioBoxPropertyHasAudio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyHasAudio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioBoxPropertyHasAudio"
        }
      ],
      "role": "symbol",
      "title": "kAudioBoxPropertyHasAudio",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioboxpropertyhasaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyHasMIDI": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioBoxPropertyHasMIDI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyHasMIDI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioBoxPropertyHasMIDI"
        }
      ],
      "role": "symbol",
      "title": "kAudioBoxPropertyHasMIDI",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioboxpropertyhasmidi"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyHasVideo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioBoxPropertyHasVideo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyHasVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioBoxPropertyHasVideo"
        }
      ],
      "role": "symbol",
      "title": "kAudioBoxPropertyHasVideo",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioboxpropertyhasvideo"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyIsProtected": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioBoxPropertyIsProtected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyIsProtected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioBoxPropertyIsProtected"
        }
      ],
      "role": "symbol",
      "title": "kAudioBoxPropertyIsProtected",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioboxpropertyisprotected"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyTransportType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioBoxPropertyTransportType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyTransportType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioBoxPropertyTransportType"
        }
      ],
      "role": "symbol",
      "title": "kAudioBoxPropertyTransportType",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioboxpropertytransporttype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyAcquired",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyAcquisitionFailed",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyDeviceList",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyHasAudio",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyHasMIDI",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyHasVideo",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyIsProtected",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyTransportType",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyClockDeviceList"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioBoxPropertyBoxUID"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioBoxPropertyBoxUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudio/documentation/CoreAudio"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyAcquired",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyAcquisitionFailed",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyDeviceList",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyHasAudio",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyHasMIDI",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyHasVideo",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyIsProtected",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyTransportType",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioBoxPropertyClockDeviceList"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioBoxPropertyBoxUID"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioBoxPropertyAcquired/title",
          "value": "kAudioBoxPropertyAcquired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioBoxPropertyAcquired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioBoxPropertyAcquired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioBoxPropertyBoxUID/title",
          "value": "kAudioBoxPropertyBoxUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioBoxPropertyBoxUID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioBoxPropertyBoxUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioBoxPropertyHasVideo/title",
          "value": "kAudioBoxPropertyHasVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioBoxPropertyHasVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioBoxPropertyHasVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/title",
          "value": "AudioObjectPropertySelector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioBoxPropertyHasAudio/title",
          "value": "kAudioBoxPropertyHasAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioBoxPropertyHasAudio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioBoxPropertyHasAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioBoxPropertyTransportType/title",
          "value": "kAudioBoxPropertyTransportType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioBoxPropertyTransportType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioBoxPropertyTransportType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioBoxPropertyClockDeviceList/title",
          "value": "kAudioBoxPropertyClockDeviceList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioBoxPropertyClockDeviceList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioBoxPropertyClockDeviceList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioBoxPropertyAcquisitionFailed/title",
          "value": "kAudioBoxPropertyAcquisitionFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioBoxPropertyAcquisitionFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioBoxPropertyAcquisitionFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioBoxPropertyHasMIDI/title",
          "value": "kAudioBoxPropertyHasMIDI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioBoxPropertyHasMIDI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioBoxPropertyHasMIDI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioBoxPropertyIsProtected/title",
          "value": "kAudioBoxPropertyIsProtected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioBoxPropertyIsProtected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioBoxPropertyIsProtected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioBoxPropertyDeviceList/title",
          "value": "kAudioBoxPropertyDeviceList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioBoxPropertyDeviceList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioBoxPropertyDeviceList"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/kaudioboxpropertyboxuid"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/kaudioboxpropertyboxuid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
