{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyStreamFormatSupported"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioDevicePropertyDeviceName@kAudioDevicePropertyStreamFormatSupported",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioDevicePropertyStreamFormatSupported"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
        "text": "AudioObjectPropertySelector"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioDevicePropertyStreamFormatSupported"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioDevicePropertyStreamFormatSupported"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyStreamFormatSupported"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
              "text": "AudioObjectPropertySelector"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertySelector",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertyselector"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyBufferSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyBufferSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyBufferSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyBufferSize"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyBufferSize",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertybuffersize"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyBufferSizeRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyBufferSizeRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyBufferSizeRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyBufferSizeRange"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyBufferSizeRange",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertybuffersizerange"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelCategoryName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelCategoryName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelCategoryName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelCategoryName"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyChannelCategoryName",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertychannelcategoryname"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelCategoryNameCFString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelCategoryNameCFString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelCategoryNameCFString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelCategoryNameCFString"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyChannelCategoryNameCFString",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertychannelcategorynamecfstring"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelName"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyChannelName",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertychannelname"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNameCFString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelNameCFString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNameCFString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelNameCFString"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyChannelNameCFString",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertychannelnamecfstring"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNominalLineLevelNameForID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelNominalLineLevelNameForID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNominalLineLevelNameForID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelNominalLineLevelNameForID"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyChannelNominalLineLevelNameForID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertychannelnominallinelevelnameforid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNumberName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelNumberName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNumberName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelNumberName"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyChannelNumberName",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertychannelnumbername"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNumberNameCFString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelNumberNameCFString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNumberNameCFString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyChannelNumberNameCFString"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyChannelNumberNameCFString",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertychannelnumbernamecfstring"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockSourceNameForID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyClockSourceNameForID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockSourceNameForID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyClockSourceNameForID"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyClockSourceNameForID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyclocksourcenameforid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDataSourceNameForID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDataSourceNameForID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDataSourceNameForID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDataSourceNameForID"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyDataSourceNameForID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertydatasourcenameforid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceManufacturer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceManufacturer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceManufacturer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceManufacturer"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyDeviceManufacturer",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertydevicemanufacturer"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceManufacturerCFString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceManufacturerCFString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceManufacturerCFString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceManufacturerCFString"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyDeviceManufacturerCFString",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertydevicemanufacturercfstring"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceName"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyDeviceName",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertydevicename"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceNameCFString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceNameCFString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceNameCFString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyDeviceNameCFString"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyDeviceNameCFString",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertydevicenamecfstring"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyStreamFormatSupported": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyStreamFormatSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyStreamFormatSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyStreamFormatSupported"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyStreamFormatSupported",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertystreamformatsupported"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyBufferSize",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyBufferSizeRange",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelCategoryName",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelCategoryNameCFString",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelName",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNameCFString",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNominalLineLevelNameForID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNumberName",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNumberNameCFString",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockSourceNameForID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDataSourceNameForID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceManufacturer",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceManufacturerCFString",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceName",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceNameCFString"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioDevicePropertyStreamFormatSupported"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyStreamFormatSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudio/documentation/CoreAudio"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyBufferSize",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyBufferSizeRange",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelCategoryName",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelCategoryNameCFString",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelName",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNameCFString",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNominalLineLevelNameForID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNumberName",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyChannelNumberNameCFString",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyClockSourceNameForID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDataSourceNameForID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceManufacturer",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceManufacturerCFString",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceName",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyDeviceNameCFString"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioDevicePropertyStreamFormatSupported"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyClockSourceNameForID/title",
          "value": "kAudioDevicePropertyClockSourceNameForID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyClockSourceNameForID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyClockSourceNameForID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceManufacturerCFString/title",
          "value": "kAudioDevicePropertyDeviceManufacturerCFString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceManufacturerCFString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyDeviceManufacturerCFString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelNominalLineLevelNameForID/title",
          "value": "kAudioDevicePropertyChannelNominalLineLevelNameForID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelNominalLineLevelNameForID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyChannelNominalLineLevelNameForID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDataSourceNameForID/title",
          "value": "kAudioDevicePropertyDataSourceNameForID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDataSourceNameForID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyDataSourceNameForID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelCategoryName/title",
          "value": "kAudioDevicePropertyChannelCategoryName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelCategoryName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyChannelCategoryName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyBufferSize/title",
          "value": "kAudioDevicePropertyBufferSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyBufferSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyBufferSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyBufferSizeRange/title",
          "value": "kAudioDevicePropertyBufferSizeRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyBufferSizeRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyBufferSizeRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelNameCFString/title",
          "value": "kAudioDevicePropertyChannelNameCFString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelNameCFString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyChannelNameCFString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelNumberNameCFString/title",
          "value": "kAudioDevicePropertyChannelNumberNameCFString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelNumberNameCFString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyChannelNumberNameCFString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceName/title",
          "value": "kAudioDevicePropertyDeviceName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyDeviceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelNumberName/title",
          "value": "kAudioDevicePropertyChannelNumberName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelNumberName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyChannelNumberName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelName/title",
          "value": "kAudioDevicePropertyChannelName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyChannelName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceNameCFString/title",
          "value": "kAudioDevicePropertyDeviceNameCFString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceNameCFString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyDeviceNameCFString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceManufacturer/title",
          "value": "kAudioDevicePropertyDeviceManufacturer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyDeviceManufacturer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyDeviceManufacturer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelCategoryNameCFString/title",
          "value": "kAudioDevicePropertyChannelCategoryNameCFString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyChannelCategoryNameCFString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyChannelCategoryNameCFString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyStreamFormatSupported/title",
          "value": "kAudioDevicePropertyStreamFormatSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyStreamFormatSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyStreamFormatSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/title",
          "value": "AudioObjectPropertySelector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/kaudiodevicepropertystreamformatsupported"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/kaudiodevicepropertystreamformatsupported"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
