{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertySleepingIsAllowed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioHardwarePropertyDevices@kAudioHardwarePropertySleepingIsAllowed",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioHardwarePropertySleepingIsAllowed"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
        "text": "AudioObjectPropertySelector"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioHardwarePropertySleepingIsAllowed"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioHardwarePropertySleepingIsAllowed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioHardwarePropertySleepingIsAllowed"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
              "text": "AudioObjectPropertySelector"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertySelector",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertyselector"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyBoxList": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyBoxList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyBoxList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyBoxList"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwarePropertyBoxList",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiohardwarepropertyboxlist"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultInputDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyDefaultInputDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultInputDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyDefaultInputDevice"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwarePropertyDefaultInputDevice",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiohardwarepropertydefaultinputdevice"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultOutputDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyDefaultOutputDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultOutputDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyDefaultOutputDevice"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwarePropertyDefaultOutputDevice",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiohardwarepropertydefaultoutputdevice"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultSystemOutputDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyDefaultSystemOutputDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultSystemOutputDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyDefaultSystemOutputDevice"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwarePropertyDefaultSystemOutputDevice",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiohardwarepropertydefaultsystemoutputdevice"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDevices": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyDevices"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDevices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyDevices"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwarePropertyDevices",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiohardwarepropertydevices"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyHogModeIsAllowed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyHogModeIsAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyHogModeIsAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyHogModeIsAllowed"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwarePropertyHogModeIsAllowed",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiohardwarepropertyhogmodeisallowed"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyIsInitingOrExiting": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyIsInitingOrExiting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyIsInitingOrExiting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyIsInitingOrExiting"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwarePropertyIsInitingOrExiting",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiohardwarepropertyisinitingorexiting"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyMixStereoToMono": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyMixStereoToMono"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyMixStereoToMono",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyMixStereoToMono"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwarePropertyMixStereoToMono",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiohardwarepropertymixstereotomono"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPlugInList": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyPlugInList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPlugInList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyPlugInList"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwarePropertyPlugInList",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiohardwarepropertypluginlist"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPowerHint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyPowerHint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPowerHint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyPowerHint"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwarePropertyPowerHint",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiohardwarepropertypowerhint"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsAudible": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyProcessIsAudible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsAudible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyProcessIsAudible"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwarePropertyProcessIsAudible",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiohardwarepropertyprocessisaudible"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsMaster": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyProcessIsMaster"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsMaster",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyProcessIsMaster"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwarePropertyProcessIsMaster",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiohardwarepropertyprocessismaster"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyServiceRestarted": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyServiceRestarted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyServiceRestarted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyServiceRestarted"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwarePropertyServiceRestarted",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiohardwarepropertyservicerestarted"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertySleepingIsAllowed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertySleepingIsAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertySleepingIsAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertySleepingIsAllowed"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwarePropertySleepingIsAllowed",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiohardwarepropertysleepingisallowed"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateBundleIDToPlugIn": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyTranslateBundleIDToPlugIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateBundleIDToPlugIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyTranslateBundleIDToPlugIn"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwarePropertyTranslateBundleIDToPlugIn",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiohardwarepropertytranslatebundleidtoplugin"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateBundleIDToTransportManager": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyTranslateBundleIDToTransportManager"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateBundleIDToTransportManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyTranslateBundleIDToTransportManager"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwarePropertyTranslateBundleIDToTransportManager",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiohardwarepropertytranslatebundleidtotransportmanager"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyBoxList",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultInputDevice",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultOutputDevice",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultSystemOutputDevice",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDevices",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyHogModeIsAllowed",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyIsInitingOrExiting",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyMixStereoToMono",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPlugInList",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPowerHint",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsAudible",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsMaster",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyServiceRestarted",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateBundleIDToPlugIn",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateBundleIDToTransportManager"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioHardwarePropertySleepingIsAllowed"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwarePropertySleepingIsAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudio/documentation/CoreAudio"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyBoxList",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultInputDevice",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultOutputDevice",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultSystemOutputDevice",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDevices",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyHogModeIsAllowed",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyIsInitingOrExiting",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyMixStereoToMono",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPlugInList",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPowerHint",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsAudible",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsMaster",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyServiceRestarted",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateBundleIDToPlugIn",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateBundleIDToTransportManager"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioHardwarePropertySleepingIsAllowed"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyIsInitingOrExiting/title",
          "value": "kAudioHardwarePropertyIsInitingOrExiting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyIsInitingOrExiting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwarePropertyIsInitingOrExiting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertySleepingIsAllowed/title",
          "value": "kAudioHardwarePropertySleepingIsAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertySleepingIsAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwarePropertySleepingIsAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyBoxList/title",
          "value": "kAudioHardwarePropertyBoxList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyBoxList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwarePropertyBoxList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyPowerHint/title",
          "value": "kAudioHardwarePropertyPowerHint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyPowerHint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwarePropertyPowerHint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDevices/title",
          "value": "kAudioHardwarePropertyDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDevices/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwarePropertyDevices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyTranslateBundleIDToPlugIn/title",
          "value": "kAudioHardwarePropertyTranslateBundleIDToPlugIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyTranslateBundleIDToPlugIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwarePropertyTranslateBundleIDToPlugIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyProcessIsAudible/title",
          "value": "kAudioHardwarePropertyProcessIsAudible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyProcessIsAudible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwarePropertyProcessIsAudible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyTranslateBundleIDToTransportManager/title",
          "value": "kAudioHardwarePropertyTranslateBundleIDToTransportManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyTranslateBundleIDToTransportManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwarePropertyTranslateBundleIDToTransportManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyMixStereoToMono/title",
          "value": "kAudioHardwarePropertyMixStereoToMono"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyMixStereoToMono/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwarePropertyMixStereoToMono"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyProcessIsMaster/title",
          "value": "kAudioHardwarePropertyProcessIsMaster"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyProcessIsMaster/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwarePropertyProcessIsMaster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDefaultInputDevice/title",
          "value": "kAudioHardwarePropertyDefaultInputDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDefaultInputDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwarePropertyDefaultInputDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDefaultSystemOutputDevice/title",
          "value": "kAudioHardwarePropertyDefaultSystemOutputDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDefaultSystemOutputDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwarePropertyDefaultSystemOutputDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyPlugInList/title",
          "value": "kAudioHardwarePropertyPlugInList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyPlugInList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwarePropertyPlugInList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDefaultOutputDevice/title",
          "value": "kAudioHardwarePropertyDefaultOutputDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDefaultOutputDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwarePropertyDefaultOutputDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyHogModeIsAllowed/title",
          "value": "kAudioHardwarePropertyHogModeIsAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyHogModeIsAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwarePropertyHogModeIsAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyServiceRestarted/title",
          "value": "kAudioHardwarePropertyServiceRestarted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyServiceRestarted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwarePropertyServiceRestarted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/title",
          "value": "AudioObjectPropertySelector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/kaudiohardwarepropertysleepingisallowed"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/kaudiohardwarepropertysleepingisallowed"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
