{"metadata":{"symbolKind":"var","modules":[{"name":"Core Audio"}],"navigatorTitle":[{"text":"kAudioHardwarePropertyPlugInList","kind":"identifier"}],"title":"kAudioHardwarePropertyPlugInList","roleHeading":"Global Variable","externalID":"c:@Ea@kAudioHardwarePropertyDevices@kAudioHardwarePropertyPlugInList","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyPlugInList","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"role":"symbol","platforms":[{"deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false},{"deprecated":false,"beta":false,"name":"macOS","unavailable":false}]},"primaryContentSections":[{"declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioHardwarePropertyPlugInList"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector","text":"AudioObjectPropertySelector"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/coreaudio/kaudiohardwarepropertypluginlist"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/coreaudio/kaudiohardwarepropertypluginlist"]}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coreaudio/documentation/CoreAudio"]]},"seeAlsoSections":[{"generated":true,"title":"Constants","anchor":"Constants","identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyBoxList","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultInputDevice","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultOutputDevice","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultSystemOutputDevice","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDevices","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyHogModeIsAllowed","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyIsInitingOrExiting","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyMixStereoToMono","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPowerHint","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsAudible","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsMaster","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyServiceRestarted","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertySleepingIsAllowed","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateBundleIDToPlugIn","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateBundleIDToTransportManager"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPlugInList"},"references":{"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyIsInitingOrExiting":{"navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyIsInitingOrExiting"}],"title":"kAudioHardwarePropertyIsInitingOrExiting","kind":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyIsInitingOrExiting","url":"/documentation/coreaudio/kaudiohardwarepropertyisinitingorexiting","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyIsInitingOrExiting","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"type":"topic","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyBoxList":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyBoxList","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector","kind":"typeIdentifier"}],"abstract":[],"title":"kAudioHardwarePropertyBoxList","kind":"symbol","navigatorTitle":[{"text":"kAudioHardwarePropertyBoxList","kind":"identifier"}],"url":"/documentation/coreaudio/kaudiohardwarepropertyboxlist","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyBoxList","role":"symbol","type":"topic"},"doc://com.apple.coreaudio/documentation/CoreAudio":{"kind":"symbol","title":"Core Audio","type":"topic","abstract":[{"type":"text","text":"Use the Core Audio framework to interact with device’s audio hardware."}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio","url":"/documentation/coreaudio","role":"collection"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsMaster":{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsMaster","url":"/documentation/coreaudio/kaudiohardwarepropertyprocessismaster","deprecated":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyProcessIsMaster","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@AudioObjectPropertySelector","kind":"typeIdentifier","text":"AudioObjectPropertySelector"}],"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyProcessIsMaster"}],"kind":"symbol","type":"topic","title":"kAudioHardwarePropertyProcessIsMaster"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyMixStereoToMono":{"navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyMixStereoToMono"}],"title":"kAudioHardwarePropertyMixStereoToMono","kind":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyMixStereoToMono","url":"/documentation/coreaudio/kaudiohardwarepropertymixstereotomono","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyMixStereoToMono","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"type":"topic","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateBundleIDToPlugIn":{"navigatorTitle":[{"text":"kAudioHardwarePropertyTranslateBundleIDToPlugIn","kind":"identifier"}],"title":"kAudioHardwarePropertyTranslateBundleIDToPlugIn","kind":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateBundleIDToPlugIn","url":"/documentation/coreaudio/kaudiohardwarepropertytranslatebundleidtoplugin","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyTranslateBundleIDToPlugIn","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"type":"topic","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsAudible":{"type":"topic","navigatorTitle":[{"text":"kAudioHardwarePropertyProcessIsAudible","kind":"identifier"}],"abstract":[],"title":"kAudioHardwarePropertyProcessIsAudible","url":"/documentation/coreaudio/kaudiohardwarepropertyprocessisaudible","role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsAudible","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyProcessIsAudible","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyHogModeIsAllowed":{"navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyHogModeIsAllowed"}],"title":"kAudioHardwarePropertyHogModeIsAllowed","kind":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyHogModeIsAllowed","url":"/documentation/coreaudio/kaudiohardwarepropertyhogmodeisallowed","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyHogModeIsAllowed","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"type":"topic","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDevices":{"type":"topic","url":"/documentation/coreaudio/kaudiohardwarepropertydevices","role":"symbol","title":"kAudioHardwarePropertyDevices","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyDevices"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioHardwarePropertyDevices"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDevices","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertySleepingIsAllowed":{"title":"kAudioHardwarePropertySleepingIsAllowed","url":"/documentation/coreaudio/kaudiohardwarepropertysleepingisallowed","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertySleepingIsAllowed","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AudioObjectPropertySelector","text":"AudioObjectPropertySelector","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"kAudioHardwarePropertySleepingIsAllowed","kind":"identifier"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertySleepingIsAllowed","type":"topic"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPlugInList":{"kind":"symbol","type":"topic","url":"/documentation/coreaudio/kaudiohardwarepropertypluginlist","navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyPlugInList"}],"title":"kAudioHardwarePropertyPlugInList","abstract":[],"role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPlugInList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioHardwarePropertyPlugInList"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateBundleIDToTransportManager":{"kind":"symbol","role":"symbol","abstract":[],"title":"kAudioHardwarePropertyTranslateBundleIDToTransportManager","url":"/documentation/coreaudio/kaudiohardwarepropertytranslatebundleidtotransportmanager","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyTranslateBundleIDToTransportManager","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AudioObjectPropertySelector","text":"AudioObjectPropertySelector","kind":"typeIdentifier"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateBundleIDToTransportManager","type":"topic","navigatorTitle":[{"text":"kAudioHardwarePropertyTranslateBundleIDToTransportManager","kind":"identifier"}]},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector":{"type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector","navigatorTitle":[{"text":"AudioObjectPropertySelector","kind":"identifier"}],"url":"/documentation/coreaudio/audioobjectpropertyselector","abstract":[],"title":"AudioObjectPropertySelector","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","role":"overview","kind":"technologies"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyServiceRestarted":{"kind":"symbol","role":"symbol","abstract":[],"title":"kAudioHardwarePropertyServiceRestarted","url":"/documentation/coreaudio/kaudiohardwarepropertyservicerestarted","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyServiceRestarted","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyServiceRestarted","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyServiceRestarted"}]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultSystemOutputDevice":{"title":"kAudioHardwarePropertyDefaultSystemOutputDevice","url":"/documentation/coreaudio/kaudiohardwarepropertydefaultsystemoutputdevice","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyDefaultSystemOutputDevice","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyDefaultSystemOutputDevice"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultSystemOutputDevice","type":"topic"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultInputDevice":{"type":"topic","url":"/documentation/coreaudio/kaudiohardwarepropertydefaultinputdevice","role":"symbol","title":"kAudioHardwarePropertyDefaultInputDevice","kind":"symbol","navigatorTitle":[{"text":"kAudioHardwarePropertyDefaultInputDevice","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyDefaultInputDevice","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultInputDevice","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultOutputDevice":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyDefaultOutputDevice","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector","kind":"typeIdentifier"}],"abstract":[],"title":"kAudioHardwarePropertyDefaultOutputDevice","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyDefaultOutputDevice"}],"url":"/documentation/coreaudio/kaudiohardwarepropertydefaultoutputdevice","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultOutputDevice","role":"symbol","type":"topic"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPowerHint":{"kind":"symbol","type":"topic","url":"/documentation/coreaudio/kaudiohardwarepropertypowerhint","navigatorTitle":[{"text":"kAudioHardwarePropertyPowerHint","kind":"identifier"}],"title":"kAudioHardwarePropertyPowerHint","abstract":[],"role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPowerHint","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyPowerHint","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AudioObjectPropertySelector","text":"AudioObjectPropertySelector","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false},{"unavailable":false,"name":"macOS","deprecated":false,"beta":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"/metadata/title","value":"kAudioHardwarePropertyPlugInList","op":"replace"},{"path":"/metadata/symbolKind","value":"case","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"kAudioHardwarePropertyPlugInList"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coreaudio/documentation/CoreAudio"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"anchor":"Constants","identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyBoxList","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultInputDevice","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultOutputDevice","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultSystemOutputDevice","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDevices","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyHogModeIsAllowed","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyIsInitingOrExiting","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyMixStereoToMono","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPowerHint","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsAudible","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsMaster","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyServiceRestarted","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertySleepingIsAllowed","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateBundleIDToPlugIn","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateBundleIDToTransportManager"],"generated":true,"title":"Constants"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"kAudioHardwarePropertyPlugInList"}]}]}},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyIsInitingOrExiting/title","value":"kAudioHardwarePropertyIsInitingOrExiting","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyIsInitingOrExiting/fragments","value":[{"text":"kAudioHardwarePropertyIsInitingOrExiting","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyBoxList/title","value":"kAudioHardwarePropertyBoxList","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyBoxList/fragments","value":[{"kind":"identifier","text":"kAudioHardwarePropertyBoxList"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyProcessIsMaster/title","value":"kAudioHardwarePropertyProcessIsMaster","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyProcessIsMaster/fragments","value":[{"kind":"identifier","text":"kAudioHardwarePropertyProcessIsMaster"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyMixStereoToMono/title","value":"kAudioHardwarePropertyMixStereoToMono","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyMixStereoToMono/fragments","value":[{"text":"kAudioHardwarePropertyMixStereoToMono","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyTranslateBundleIDToPlugIn/title","value":"kAudioHardwarePropertyTranslateBundleIDToPlugIn","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyTranslateBundleIDToPlugIn/fragments","value":[{"text":"kAudioHardwarePropertyTranslateBundleIDToPlugIn","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"kAudioHardwarePropertyProcessIsAudible","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyProcessIsAudible/title"},{"op":"replace","value":[{"text":"kAudioHardwarePropertyProcessIsAudible","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyProcessIsAudible/fragments"},{"op":"replace","value":"kAudioHardwarePropertyHogModeIsAllowed","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyHogModeIsAllowed/title"},{"op":"replace","value":[{"kind":"identifier","text":"kAudioHardwarePropertyHogModeIsAllowed"}],"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyHogModeIsAllowed/fragments"},{"op":"replace","value":"kAudioHardwarePropertyDevices","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDevices/title"},{"op":"replace","value":[{"text":"kAudioHardwarePropertyDevices","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDevices/fragments"},{"op":"replace","value":"kAudioHardwarePropertySleepingIsAllowed","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertySleepingIsAllowed/title"},{"op":"replace","value":[{"text":"kAudioHardwarePropertySleepingIsAllowed","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertySleepingIsAllowed/fragments"},{"op":"replace","value":"kAudioHardwarePropertyPlugInList","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyPlugInList/title"},{"op":"replace","value":[{"kind":"identifier","text":"kAudioHardwarePropertyPlugInList"}],"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyPlugInList/fragments"},{"op":"replace","value":"kAudioHardwarePropertyTranslateBundleIDToTransportManager","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyTranslateBundleIDToTransportManager/title"},{"op":"replace","value":[{"text":"kAudioHardwarePropertyTranslateBundleIDToTransportManager","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyTranslateBundleIDToTransportManager/fragments"},{"op":"replace","value":"AudioObjectPropertySelector","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/title"},{"op":"replace","value":[{"text":"AudioObjectPropertySelector","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AudioObjectPropertySelector"}],"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/navigatorTitle"},{"op":"replace","value":"kAudioHardwarePropertyServiceRestarted","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyServiceRestarted/title"},{"op":"replace","value":[{"text":"kAudioHardwarePropertyServiceRestarted","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyServiceRestarted/fragments"},{"op":"replace","value":"kAudioHardwarePropertyDefaultSystemOutputDevice","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDefaultSystemOutputDevice/title"},{"op":"replace","value":[{"kind":"identifier","text":"kAudioHardwarePropertyDefaultSystemOutputDevice"}],"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDefaultSystemOutputDevice/fragments"},{"op":"replace","value":"kAudioHardwarePropertyDefaultInputDevice","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDefaultInputDevice/title"},{"op":"replace","value":[{"kind":"identifier","text":"kAudioHardwarePropertyDefaultInputDevice"}],"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDefaultInputDevice/fragments"},{"op":"replace","value":"kAudioHardwarePropertyDefaultOutputDevice","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDefaultOutputDevice/title"},{"op":"replace","value":[{"text":"kAudioHardwarePropertyDefaultOutputDevice","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDefaultOutputDevice/fragments"},{"op":"replace","value":"kAudioHardwarePropertyPowerHint","path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyPowerHint/title"},{"op":"replace","value":[{"text":"kAudioHardwarePropertyPowerHint","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyPowerHint/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}