{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessObjectList"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioHardwarePropertyDevices@kAudioHardwarePropertyProcessObjectList",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioHardwarePropertyProcessObjectList"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
        "text": "AudioObjectPropertySelector"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioHardwarePropertyProcessObjectList"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioHardwarePropertyProcessObjectList"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioHardwarePropertyProcessObjectList"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
              "text": "AudioObjectPropertySelector"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareTapping_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioHardwareTapping_h"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareTapping_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioHardwareTapping_h",
      "type": "topic",
      "url": "/documentation/coreaudio/audiohardwaretapping_h"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertySelector",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertyselector"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription_h": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CATapDescription_h"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription_h",
      "kind": "symbol",
      "role": "symbol",
      "title": "CATapDescription_h",
      "type": "topic",
      "url": "/documentation/coreaudio/catapdescription_h"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceClockDeviceKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioAggregateDeviceClockDeviceKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceClockDeviceKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioAggregateDeviceClockDeviceKey"
        }
      ],
      "role": "symbol",
      "title": "kAudioAggregateDeviceClockDeviceKey",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioaggregatedeviceclockdevicekey"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceIsPrivateKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioAggregateDeviceIsPrivateKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceIsPrivateKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioAggregateDeviceIsPrivateKey"
        }
      ],
      "role": "symbol",
      "title": "kAudioAggregateDeviceIsPrivateKey",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioaggregatedeviceisprivatekey"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceIsStackedKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioAggregateDeviceIsStackedKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceIsStackedKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioAggregateDeviceIsStackedKey"
        }
      ],
      "role": "symbol",
      "title": "kAudioAggregateDeviceIsStackedKey",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioaggregatedeviceisstackedkey"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceMainSubDeviceKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioAggregateDeviceMainSubDeviceKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceMainSubDeviceKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioAggregateDeviceMainSubDeviceKey"
        }
      ],
      "role": "symbol",
      "title": "kAudioAggregateDeviceMainSubDeviceKey",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioaggregatedevicemainsubdevicekey"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceMasterSubDeviceKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioAggregateDeviceMasterSubDeviceKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceMasterSubDeviceKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioAggregateDeviceMasterSubDeviceKey"
        }
      ],
      "role": "symbol",
      "title": "kAudioAggregateDeviceMasterSubDeviceKey",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioaggregatedevicemastersubdevicekey"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioAggregateDeviceNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioAggregateDeviceNameKey"
        }
      ],
      "role": "symbol",
      "title": "kAudioAggregateDeviceNameKey",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioaggregatedevicenamekey"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDevicePropertyMainSubDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioAggregateDevicePropertyMainSubDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDevicePropertyMainSubDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioAggregateDevicePropertyMainSubDevice"
        }
      ],
      "role": "symbol",
      "title": "kAudioAggregateDevicePropertyMainSubDevice",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioaggregatedevicepropertymainsubdevice"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDevicePropertySubTapList": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioAggregateDevicePropertySubTapList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDevicePropertySubTapList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioAggregateDevicePropertySubTapList"
        }
      ],
      "role": "symbol",
      "title": "kAudioAggregateDevicePropertySubTapList",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioaggregatedevicepropertysubtaplist"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDevicePropertyTapList": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioAggregateDevicePropertyTapList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDevicePropertyTapList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioAggregateDevicePropertyTapList"
        }
      ],
      "role": "symbol",
      "title": "kAudioAggregateDevicePropertyTapList",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioaggregatedevicepropertytaplist"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceSubDeviceListKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioAggregateDeviceSubDeviceListKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceSubDeviceListKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioAggregateDeviceSubDeviceListKey"
        }
      ],
      "role": "symbol",
      "title": "kAudioAggregateDeviceSubDeviceListKey",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioaggregatedevicesubdevicelistkey"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceTapAutoStartKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioAggregateDeviceTapAutoStartKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceTapAutoStartKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioAggregateDeviceTapAutoStartKey"
        }
      ],
      "role": "symbol",
      "title": "kAudioAggregateDeviceTapAutoStartKey",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioaggregatedevicetapautostartkey"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceTapListKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioAggregateDeviceTapListKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceTapListKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioAggregateDeviceTapListKey"
        }
      ],
      "role": "symbol",
      "title": "kAudioAggregateDeviceTapListKey",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioaggregatedevicetaplistkey"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceUIDKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioAggregateDeviceUIDKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceUIDKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioAggregateDeviceUIDKey"
        }
      ],
      "role": "symbol",
      "title": "kAudioAggregateDeviceUIDKey",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioaggregatedeviceuidkey"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyIOThreadOSWorkgroup": {
      "abstract": [
        {
          "text": "The device’s workgroup object, which you use to coordinate your threads with the threads of the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyIOThreadOSWorkgroup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyIOThreadOSWorkgroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyIOThreadOSWorkgroup"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyIOThreadOSWorkgroup",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyiothreadosworkgroup"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyProcessMute": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyProcessMute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyProcessMute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioDevicePropertyProcessMute"
        }
      ],
      "role": "symbol",
      "title": "kAudioDevicePropertyProcessMute",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiodevicepropertyprocessmute"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessObjectList": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyProcessObjectList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessObjectList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioHardwarePropertyProcessObjectList"
        }
      ],
      "role": "symbol",
      "title": "kAudioHardwarePropertyProcessObjectList",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiohardwarepropertyprocessobjectlist"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceClockDeviceKey",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceIsPrivateKey",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceIsStackedKey",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceMainSubDeviceKey",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceMasterSubDeviceKey",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceNameKey",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDevicePropertyMainSubDevice",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDevicePropertySubTapList",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDevicePropertyTapList",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceSubDeviceListKey",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceTapAutoStartKey",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceTapListKey",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceUIDKey",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyIOThreadOSWorkgroup",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioDevicePropertyProcessMute"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioHardwarePropertyProcessObjectList"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwarePropertyProcessObjectList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudio/documentation/CoreAudio"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioHardwareTapping_h",
                "doc://com.apple.coreaudio/documentation/CoreAudio/CATapDescription_h",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceClockDeviceKey",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceIsPrivateKey",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceIsStackedKey",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceMainSubDeviceKey",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceMasterSubDeviceKey",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceNameKey",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDevicePropertyMainSubDevice",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDevicePropertySubTapList",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDevicePropertyTapList",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceSubDeviceListKey",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceTapAutoStartKey",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceTapListKey",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioAggregateDeviceUIDKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioHardwarePropertyProcessObjectList"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioAggregateDeviceTapAutoStartKey/title",
          "value": "kAudioAggregateDeviceTapAutoStartKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioAggregateDeviceTapAutoStartKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioAggregateDeviceTapAutoStartKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioAggregateDevicePropertySubTapList/title",
          "value": "kAudioAggregateDevicePropertySubTapList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioAggregateDevicePropertySubTapList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioAggregateDevicePropertySubTapList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioAggregateDeviceNameKey/title",
          "value": "kAudioAggregateDeviceNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioAggregateDeviceNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioAggregateDeviceNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyProcessMute/title",
          "value": "kAudioDevicePropertyProcessMute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyProcessMute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyProcessMute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioAggregateDeviceClockDeviceKey/title",
          "value": "kAudioAggregateDeviceClockDeviceKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioAggregateDeviceClockDeviceKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioAggregateDeviceClockDeviceKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioAggregateDeviceMasterSubDeviceKey/title",
          "value": "kAudioAggregateDeviceMasterSubDeviceKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioAggregateDeviceMasterSubDeviceKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioAggregateDeviceMasterSubDeviceKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioAggregateDevicePropertyTapList/title",
          "value": "kAudioAggregateDevicePropertyTapList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioAggregateDevicePropertyTapList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioAggregateDevicePropertyTapList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyProcessObjectList/title",
          "value": "kAudioHardwarePropertyProcessObjectList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyProcessObjectList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioHardwarePropertyProcessObjectList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioAggregateDeviceIsStackedKey/title",
          "value": "kAudioAggregateDeviceIsStackedKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioAggregateDeviceIsStackedKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioAggregateDeviceIsStackedKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyIOThreadOSWorkgroup/title",
          "value": "kAudioDevicePropertyIOThreadOSWorkgroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioDevicePropertyIOThreadOSWorkgroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioDevicePropertyIOThreadOSWorkgroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioAggregateDeviceUIDKey/title",
          "value": "kAudioAggregateDeviceUIDKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioAggregateDeviceUIDKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioAggregateDeviceUIDKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioAggregateDeviceMainSubDeviceKey/title",
          "value": "kAudioAggregateDeviceMainSubDeviceKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioAggregateDeviceMainSubDeviceKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioAggregateDeviceMainSubDeviceKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioAggregateDeviceIsPrivateKey/title",
          "value": "kAudioAggregateDeviceIsPrivateKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioAggregateDeviceIsPrivateKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioAggregateDeviceIsPrivateKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioAggregateDeviceSubDeviceListKey/title",
          "value": "kAudioAggregateDeviceSubDeviceListKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioAggregateDeviceSubDeviceListKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioAggregateDeviceSubDeviceListKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/title",
          "value": "AudioObjectPropertySelector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioAggregateDevicePropertyMainSubDevice/title",
          "value": "kAudioAggregateDevicePropertyMainSubDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioAggregateDevicePropertyMainSubDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioAggregateDevicePropertyMainSubDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioAggregateDeviceTapListKey/title",
          "value": "kAudioAggregateDeviceTapListKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioAggregateDeviceTapListKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioAggregateDeviceTapListKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/kaudiohardwarepropertyprocessobjectlist"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/kaudiohardwarepropertyprocessobjectlist"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
