{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyLatency"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioClockDevicePropertyDeviceUID@kAudioClockDevicePropertyLatency",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioClockDevicePropertyLatency"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
        "text": "AudioObjectPropertySelector"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioClockDevicePropertyLatency"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioClockDevicePropertyLatency"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioClockDevicePropertyLatency"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
              "text": "AudioObjectPropertySelector"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertySelector",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertyselector"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyAvailableNominalSampleRates": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioClockDevicePropertyAvailableNominalSampleRates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyAvailableNominalSampleRates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioClockDevicePropertyAvailableNominalSampleRates"
        }
      ],
      "role": "symbol",
      "title": "kAudioClockDevicePropertyAvailableNominalSampleRates",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioclockdevicepropertyavailablenominalsamplerates"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyClockDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioClockDevicePropertyClockDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyClockDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioClockDevicePropertyClockDomain"
        }
      ],
      "role": "symbol",
      "title": "kAudioClockDevicePropertyClockDomain",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioclockdevicepropertyclockdomain"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyControlList": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioClockDevicePropertyControlList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyControlList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioClockDevicePropertyControlList"
        }
      ],
      "role": "symbol",
      "title": "kAudioClockDevicePropertyControlList",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioclockdevicepropertycontrollist"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyDeviceIsAlive": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioClockDevicePropertyDeviceIsAlive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyDeviceIsAlive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioClockDevicePropertyDeviceIsAlive"
        }
      ],
      "role": "symbol",
      "title": "kAudioClockDevicePropertyDeviceIsAlive",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioclockdevicepropertydeviceisalive"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyDeviceIsRunning": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioClockDevicePropertyDeviceIsRunning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyDeviceIsRunning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioClockDevicePropertyDeviceIsRunning"
        }
      ],
      "role": "symbol",
      "title": "kAudioClockDevicePropertyDeviceIsRunning",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioclockdevicepropertydeviceisrunning"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyDeviceUID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioClockDevicePropertyDeviceUID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyDeviceUID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioClockDevicePropertyDeviceUID"
        }
      ],
      "role": "symbol",
      "title": "kAudioClockDevicePropertyDeviceUID",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioclockdevicepropertydeviceuid"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyLatency": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioClockDevicePropertyLatency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyLatency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioClockDevicePropertyLatency"
        }
      ],
      "role": "symbol",
      "title": "kAudioClockDevicePropertyLatency",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioclockdevicepropertylatency"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyNominalSampleRate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioClockDevicePropertyNominalSampleRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyNominalSampleRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioClockDevicePropertyNominalSampleRate"
        }
      ],
      "role": "symbol",
      "title": "kAudioClockDevicePropertyNominalSampleRate",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioclockdevicepropertynominalsamplerate"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyTransportType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioClockDevicePropertyTransportType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyTransportType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioClockDevicePropertyTransportType"
        }
      ],
      "role": "symbol",
      "title": "kAudioClockDevicePropertyTransportType",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioclockdevicepropertytransporttype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyAvailableNominalSampleRates",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyClockDomain",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyControlList",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyDeviceIsAlive",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyDeviceIsRunning",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyDeviceUID",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyNominalSampleRate",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyTransportType"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioClockDevicePropertyLatency"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioClockDevicePropertyLatency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudio/documentation/CoreAudio"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyAvailableNominalSampleRates",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyClockDomain",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyControlList",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyDeviceIsAlive",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyDeviceIsRunning",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyDeviceUID",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyNominalSampleRate",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioClockDevicePropertyTransportType"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioClockDevicePropertyLatency"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioClockDevicePropertyLatency/title",
          "value": "kAudioClockDevicePropertyLatency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioClockDevicePropertyLatency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioClockDevicePropertyLatency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioClockDevicePropertyAvailableNominalSampleRates/title",
          "value": "kAudioClockDevicePropertyAvailableNominalSampleRates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioClockDevicePropertyAvailableNominalSampleRates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioClockDevicePropertyAvailableNominalSampleRates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/title",
          "value": "AudioObjectPropertySelector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioClockDevicePropertyDeviceIsAlive/title",
          "value": "kAudioClockDevicePropertyDeviceIsAlive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioClockDevicePropertyDeviceIsAlive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioClockDevicePropertyDeviceIsAlive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioClockDevicePropertyNominalSampleRate/title",
          "value": "kAudioClockDevicePropertyNominalSampleRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioClockDevicePropertyNominalSampleRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioClockDevicePropertyNominalSampleRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioClockDevicePropertyDeviceIsRunning/title",
          "value": "kAudioClockDevicePropertyDeviceIsRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioClockDevicePropertyDeviceIsRunning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioClockDevicePropertyDeviceIsRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioClockDevicePropertyClockDomain/title",
          "value": "kAudioClockDevicePropertyClockDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioClockDevicePropertyClockDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioClockDevicePropertyClockDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioClockDevicePropertyControlList/title",
          "value": "kAudioClockDevicePropertyControlList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioClockDevicePropertyControlList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioClockDevicePropertyControlList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioClockDevicePropertyTransportType/title",
          "value": "kAudioClockDevicePropertyTransportType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioClockDevicePropertyTransportType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioClockDevicePropertyTransportType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioClockDevicePropertyDeviceUID/title",
          "value": "kAudioClockDevicePropertyDeviceUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioClockDevicePropertyDeviceUID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioClockDevicePropertyDeviceUID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/kaudioclockdevicepropertylatency"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/kaudioclockdevicepropertylatency"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
