{
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioSubDeviceDriftCompensationMediumQuality"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioSubDeviceDriftCompensationMinQuality@kAudioSubDeviceDriftCompensationMediumQuality",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioSubDeviceDriftCompensationMediumQuality"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioSubDeviceDriftCompensationMediumQuality"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.4",
        "introducedAt": "16.0",
        "name": "iOS",
        "renamed": "kAudioAggregateDriftCompensationMediumQuality",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.4",
        "introducedAt": "16.0",
        "name": "iPadOS",
        "renamed": "kAudioAggregateDriftCompensationMediumQuality",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "renamed": "kAudioAggregateDriftCompensationMediumQuality",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.4",
        "introducedAt": "13.0",
        "name": "macOS",
        "renamed": "kAudioAggregateDriftCompensationMediumQuality",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioSubDeviceDriftCompensationMediumQuality"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioSubDeviceDriftCompensationMediumQuality"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioSubDeviceDriftCompensationHighQuality": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSubDeviceDriftCompensationHighQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioSubDeviceDriftCompensationHighQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSubDeviceDriftCompensationHighQuality"
        }
      ],
      "role": "symbol",
      "title": "kAudioSubDeviceDriftCompensationHighQuality",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiosubdevicedriftcompensationhighquality"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioSubDeviceDriftCompensationLowQuality": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSubDeviceDriftCompensationLowQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioSubDeviceDriftCompensationLowQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSubDeviceDriftCompensationLowQuality"
        }
      ],
      "role": "symbol",
      "title": "kAudioSubDeviceDriftCompensationLowQuality",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiosubdevicedriftcompensationlowquality"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioSubDeviceDriftCompensationMaxQuality": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSubDeviceDriftCompensationMaxQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioSubDeviceDriftCompensationMaxQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSubDeviceDriftCompensationMaxQuality"
        }
      ],
      "role": "symbol",
      "title": "kAudioSubDeviceDriftCompensationMaxQuality",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiosubdevicedriftcompensationmaxquality"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioSubDeviceDriftCompensationMediumQuality": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSubDeviceDriftCompensationMediumQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioSubDeviceDriftCompensationMediumQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSubDeviceDriftCompensationMediumQuality"
        }
      ],
      "role": "symbol",
      "title": "kAudioSubDeviceDriftCompensationMediumQuality",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiosubdevicedriftcompensationmediumquality"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioSubDeviceDriftCompensationMinQuality": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioSubDeviceDriftCompensationMinQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioSubDeviceDriftCompensationMinQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioSubDeviceDriftCompensationMinQuality"
        }
      ],
      "role": "symbol",
      "title": "kAudioSubDeviceDriftCompensationMinQuality",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudiosubdevicedriftcompensationminquality"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioSubDeviceDriftCompensationHighQuality",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioSubDeviceDriftCompensationLowQuality",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioSubDeviceDriftCompensationMaxQuality",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioSubDeviceDriftCompensationMinQuality"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.4",
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioSubDeviceDriftCompensationMediumQuality"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSubDeviceDriftCompensationMediumQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudio/documentation/CoreAudio"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioSubDeviceDriftCompensationHighQuality",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioSubDeviceDriftCompensationLowQuality",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioSubDeviceDriftCompensationMaxQuality",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioSubDeviceDriftCompensationMinQuality"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioSubDeviceDriftCompensationMediumQuality"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioSubDeviceDriftCompensationMaxQuality/title",
          "value": "kAudioSubDeviceDriftCompensationMaxQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioSubDeviceDriftCompensationMaxQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSubDeviceDriftCompensationMaxQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioSubDeviceDriftCompensationMediumQuality/title",
          "value": "kAudioSubDeviceDriftCompensationMediumQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioSubDeviceDriftCompensationMediumQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSubDeviceDriftCompensationMediumQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioSubDeviceDriftCompensationLowQuality/title",
          "value": "kAudioSubDeviceDriftCompensationLowQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioSubDeviceDriftCompensationLowQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSubDeviceDriftCompensationLowQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioSubDeviceDriftCompensationMinQuality/title",
          "value": "kAudioSubDeviceDriftCompensationMinQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioSubDeviceDriftCompensationMinQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSubDeviceDriftCompensationMinQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioSubDeviceDriftCompensationHighQuality/title",
          "value": "kAudioSubDeviceDriftCompensationHighQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioSubDeviceDriftCompensationHighQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioSubDeviceDriftCompensationHighQuality"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/kaudiosubdevicedriftcompensationmediumquality"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/kaudiosubdevicedriftcompensationmediumquality"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
