{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementNumberName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kAudioObjectPropertyBaseClass@kAudioObjectPropertyElementNumberName",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kAudioObjectPropertyElementNumberName"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
        "text": "AudioObjectPropertySelector"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioObjectPropertyElementNumberName"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kAudioObjectPropertyElementNumberName"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kAudioObjectPropertyElementNumberName"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
              "text": "AudioObjectPropertySelector"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "role": "symbol",
      "title": "AudioObjectPropertySelector",
      "type": "topic",
      "url": "/documentation/coreaudio/audioobjectpropertyselector"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyBaseClass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioObjectPropertyBaseClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyBaseClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioObjectPropertyBaseClass"
        }
      ],
      "role": "symbol",
      "title": "kAudioObjectPropertyBaseClass",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioobjectpropertybaseclass"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyClass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioObjectPropertyClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioObjectPropertyClass"
        }
      ],
      "role": "symbol",
      "title": "kAudioObjectPropertyClass",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioobjectpropertyclass"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementCategoryName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioObjectPropertyElementCategoryName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementCategoryName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioObjectPropertyElementCategoryName"
        }
      ],
      "role": "symbol",
      "title": "kAudioObjectPropertyElementCategoryName",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioobjectpropertyelementcategoryname"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioObjectPropertyElementName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioObjectPropertyElementName"
        }
      ],
      "role": "symbol",
      "title": "kAudioObjectPropertyElementName",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioobjectpropertyelementname"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementNumberName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioObjectPropertyElementNumberName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementNumberName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioObjectPropertyElementNumberName"
        }
      ],
      "role": "symbol",
      "title": "kAudioObjectPropertyElementNumberName",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioobjectpropertyelementnumbername"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyFirmwareVersion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioObjectPropertyFirmwareVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyFirmwareVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioObjectPropertyFirmwareVersion"
        }
      ],
      "role": "symbol",
      "title": "kAudioObjectPropertyFirmwareVersion",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioobjectpropertyfirmwareversion"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyIdentify": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioObjectPropertyIdentify"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyIdentify",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioObjectPropertyIdentify"
        }
      ],
      "role": "symbol",
      "title": "kAudioObjectPropertyIdentify",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioobjectpropertyidentify"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyManufacturer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioObjectPropertyManufacturer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyManufacturer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioObjectPropertyManufacturer"
        }
      ],
      "role": "symbol",
      "title": "kAudioObjectPropertyManufacturer",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioobjectpropertymanufacturer"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyModelName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioObjectPropertyModelName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyModelName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioObjectPropertyModelName"
        }
      ],
      "role": "symbol",
      "title": "kAudioObjectPropertyModelName",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioobjectpropertymodelname"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioObjectPropertyName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioObjectPropertyName"
        }
      ],
      "role": "symbol",
      "title": "kAudioObjectPropertyName",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioobjectpropertyname"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyOwnedObjects": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioObjectPropertyOwnedObjects"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyOwnedObjects",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioObjectPropertyOwnedObjects"
        }
      ],
      "role": "symbol",
      "title": "kAudioObjectPropertyOwnedObjects",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioobjectpropertyownedobjects"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyOwner": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioObjectPropertyOwner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyOwner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioObjectPropertyOwner"
        }
      ],
      "role": "symbol",
      "title": "kAudioObjectPropertyOwner",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioobjectpropertyowner"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertySerialNumber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAudioObjectPropertySerialNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AudioObjectPropertySelector",
          "text": "AudioObjectPropertySelector"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertySerialNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioObjectPropertySerialNumber"
        }
      ],
      "role": "symbol",
      "title": "kAudioObjectPropertySerialNumber",
      "type": "topic",
      "url": "/documentation/coreaudio/kaudioobjectpropertyserialnumber"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyBaseClass",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyClass",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementCategoryName",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementName",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyFirmwareVersion",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyIdentify",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyManufacturer",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyModelName",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyName",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyOwnedObjects",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyOwner",
        "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertySerialNumber"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioObjectPropertyElementNumberName"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioObjectPropertyElementNumberName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudio/documentation/CoreAudio"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyBaseClass",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyClass",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementCategoryName",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyElementName",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyFirmwareVersion",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyIdentify",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyManufacturer",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyModelName",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyName",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyOwnedObjects",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertyOwner",
                "doc://com.apple.coreaudio/documentation/CoreAudio/kAudioObjectPropertySerialNumber"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioObjectPropertyElementNumberName"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyElementNumberName/title",
          "value": "kAudioObjectPropertyElementNumberName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyElementNumberName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioObjectPropertyElementNumberName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyElementName/title",
          "value": "kAudioObjectPropertyElementName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyElementName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioObjectPropertyElementName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/title",
          "value": "AudioObjectPropertySelector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioObjectPropertySelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyManufacturer/title",
          "value": "kAudioObjectPropertyManufacturer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyManufacturer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioObjectPropertyManufacturer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyOwner/title",
          "value": "kAudioObjectPropertyOwner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyOwner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioObjectPropertyOwner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyClass/title",
          "value": "kAudioObjectPropertyClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioObjectPropertyClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyElementCategoryName/title",
          "value": "kAudioObjectPropertyElementCategoryName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyElementCategoryName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioObjectPropertyElementCategoryName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyName/title",
          "value": "kAudioObjectPropertyName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioObjectPropertyName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyFirmwareVersion/title",
          "value": "kAudioObjectPropertyFirmwareVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyFirmwareVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioObjectPropertyFirmwareVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyModelName/title",
          "value": "kAudioObjectPropertyModelName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyModelName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioObjectPropertyModelName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyIdentify/title",
          "value": "kAudioObjectPropertyIdentify"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyIdentify/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioObjectPropertyIdentify"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyBaseClass/title",
          "value": "kAudioObjectPropertyBaseClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyBaseClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioObjectPropertyBaseClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertySerialNumber/title",
          "value": "kAudioObjectPropertySerialNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertySerialNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioObjectPropertySerialNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyOwnedObjects/title",
          "value": "kAudioObjectPropertyOwnedObjects"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioObjectPropertyOwnedObjects/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioObjectPropertyOwnedObjects"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/kaudioobjectpropertyelementnumbername"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/kaudioobjectpropertyelementnumbername"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
