{"variants":[{"paths":["/documentation/coreaudio/kaudiohardwarepropertyclockdevicelist"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/coreaudio/kaudiohardwarepropertyclockdevicelist"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"generated":true,"anchor":"Constants","identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyBoxList","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultInputDevice","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultOutputDevice","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultSystemOutputDevice","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDevices","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyHogModeIsAllowed","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyIsInitingOrExiting","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyMixStereoToMono","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPlugInList","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPowerHint","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsAudible","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsMaster","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyServiceRestarted","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertySleepingIsAllowed","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateBundleIDToPlugIn"],"title":"Constants"}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coreaudio/documentation/CoreAudio"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"symbolKind":"var","navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyClockDeviceList"}],"roleHeading":"Global Variable","modules":[{"name":"Core Audio"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioHardwarePropertyClockDeviceList"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@AudioObjectPropertySelector","kind":"typeIdentifier","text":"AudioObjectPropertySelector"}],"title":"kAudioHardwarePropertyClockDeviceList","platforms":[{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false},{"unavailable":false,"name":"macOS","deprecated":false,"beta":false}],"externalID":"c:@Ea@kAudioHardwarePropertyDevices@kAudioHardwarePropertyClockDeviceList","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyClockDeviceList"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyClockDeviceList","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"}],"references":{"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsAudible":{"type":"topic","navigatorTitle":[{"text":"kAudioHardwarePropertyProcessIsAudible","kind":"identifier"}],"abstract":[],"title":"kAudioHardwarePropertyProcessIsAudible","url":"/documentation/coreaudio/kaudiohardwarepropertyprocessisaudible","role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsAudible","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyProcessIsAudible","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio":{"kind":"symbol","title":"Core Audio","type":"topic","abstract":[{"type":"text","text":"Use the Core Audio framework to interact with device’s audio hardware."}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio","url":"/documentation/coreaudio","role":"collection"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultSystemOutputDevice":{"title":"kAudioHardwarePropertyDefaultSystemOutputDevice","url":"/documentation/coreaudio/kaudiohardwarepropertydefaultsystemoutputdevice","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyDefaultSystemOutputDevice","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyDefaultSystemOutputDevice"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultSystemOutputDevice","type":"topic"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyHogModeIsAllowed":{"navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyHogModeIsAllowed"}],"title":"kAudioHardwarePropertyHogModeIsAllowed","kind":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyHogModeIsAllowed","url":"/documentation/coreaudio/kaudiohardwarepropertyhogmodeisallowed","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyHogModeIsAllowed","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"type":"topic","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultInputDevice":{"type":"topic","url":"/documentation/coreaudio/kaudiohardwarepropertydefaultinputdevice","role":"symbol","title":"kAudioHardwarePropertyDefaultInputDevice","kind":"symbol","navigatorTitle":[{"text":"kAudioHardwarePropertyDefaultInputDevice","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyDefaultInputDevice","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultInputDevice","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector":{"type":"topic","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/AudioObjectPropertySelector","navigatorTitle":[{"text":"AudioObjectPropertySelector","kind":"identifier"}],"url":"/documentation/coreaudio/audioobjectpropertyselector","abstract":[],"title":"AudioObjectPropertySelector","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertySleepingIsAllowed":{"title":"kAudioHardwarePropertySleepingIsAllowed","url":"/documentation/coreaudio/kaudiohardwarepropertysleepingisallowed","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertySleepingIsAllowed","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AudioObjectPropertySelector","text":"AudioObjectPropertySelector","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"kAudioHardwarePropertySleepingIsAllowed","kind":"identifier"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertySleepingIsAllowed","type":"topic"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyBoxList":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyBoxList","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector","kind":"typeIdentifier"}],"abstract":[],"title":"kAudioHardwarePropertyBoxList","kind":"symbol","navigatorTitle":[{"text":"kAudioHardwarePropertyBoxList","kind":"identifier"}],"url":"/documentation/coreaudio/kaudiohardwarepropertyboxlist","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyBoxList","role":"symbol","type":"topic"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyMixStereoToMono":{"navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyMixStereoToMono"}],"title":"kAudioHardwarePropertyMixStereoToMono","kind":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyMixStereoToMono","url":"/documentation/coreaudio/kaudiohardwarepropertymixstereotomono","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyMixStereoToMono","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"type":"topic","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateBundleIDToPlugIn":{"navigatorTitle":[{"text":"kAudioHardwarePropertyTranslateBundleIDToPlugIn","kind":"identifier"}],"title":"kAudioHardwarePropertyTranslateBundleIDToPlugIn","kind":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateBundleIDToPlugIn","url":"/documentation/coreaudio/kaudiohardwarepropertytranslatebundleidtoplugin","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyTranslateBundleIDToPlugIn","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"type":"topic","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPlugInList":{"kind":"symbol","type":"topic","url":"/documentation/coreaudio/kaudiohardwarepropertypluginlist","navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyPlugInList"}],"title":"kAudioHardwarePropertyPlugInList","abstract":[],"role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPlugInList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioHardwarePropertyPlugInList"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyIsInitingOrExiting":{"navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyIsInitingOrExiting"}],"title":"kAudioHardwarePropertyIsInitingOrExiting","kind":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyIsInitingOrExiting","url":"/documentation/coreaudio/kaudiohardwarepropertyisinitingorexiting","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyIsInitingOrExiting","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"type":"topic","abstract":[]},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","role":"overview","kind":"technologies"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDevices":{"type":"topic","url":"/documentation/coreaudio/kaudiohardwarepropertydevices","role":"symbol","title":"kAudioHardwarePropertyDevices","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyDevices"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioHardwarePropertyDevices"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDevices","abstract":[]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPowerHint":{"kind":"symbol","type":"topic","url":"/documentation/coreaudio/kaudiohardwarepropertypowerhint","navigatorTitle":[{"text":"kAudioHardwarePropertyPowerHint","kind":"identifier"}],"title":"kAudioHardwarePropertyPowerHint","abstract":[],"role":"symbol","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPowerHint","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyPowerHint","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AudioObjectPropertySelector","text":"AudioObjectPropertySelector","kind":"typeIdentifier"}]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyClockDeviceList":{"kind":"symbol","title":"kAudioHardwarePropertyClockDeviceList","url":"/documentation/coreaudio/kaudiohardwarepropertyclockdevicelist","abstract":[],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyClockDeviceList","navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyClockDeviceList"}],"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kAudioHardwarePropertyClockDeviceList"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AudioObjectPropertySelector","text":"AudioObjectPropertySelector"}]},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsMaster":{"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsMaster","url":"/documentation/coreaudio/kaudiohardwarepropertyprocessismaster","deprecated":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyProcessIsMaster","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@AudioObjectPropertySelector","kind":"typeIdentifier","text":"AudioObjectPropertySelector"}],"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyProcessIsMaster"}],"kind":"symbol","type":"topic","title":"kAudioHardwarePropertyProcessIsMaster"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultOutputDevice":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyDefaultOutputDevice","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector","kind":"typeIdentifier"}],"abstract":[],"title":"kAudioHardwarePropertyDefaultOutputDevice","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyDefaultOutputDevice"}],"url":"/documentation/coreaudio/kaudiohardwarepropertydefaultoutputdevice","identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultOutputDevice","role":"symbol","type":"topic"},"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyServiceRestarted":{"kind":"symbol","role":"symbol","abstract":[],"title":"kAudioHardwarePropertyServiceRestarted","url":"/documentation/coreaudio/kaudiohardwarepropertyservicerestarted","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"kAudioHardwarePropertyServiceRestarted","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AudioObjectPropertySelector","preciseIdentifier":"c:@T@AudioObjectPropertySelector"}],"identifier":"doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyServiceRestarted","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kAudioHardwarePropertyServiceRestarted"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst"},{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"/metadata/title","op":"replace","value":"kAudioHardwarePropertyClockDeviceList"},{"path":"/metadata/symbolKind","op":"replace","value":"case"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"kAudioHardwarePropertyClockDeviceList","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coreaudio/documentation/CoreAudio"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"title":"Constants","identifiers":["doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyBoxList","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultInputDevice","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultOutputDevice","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDefaultSystemOutputDevice","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyDevices","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyHogModeIsAllowed","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyIsInitingOrExiting","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyMixStereoToMono","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPlugInList","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyPowerHint","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsAudible","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyProcessIsMaster","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyServiceRestarted","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertySleepingIsAllowed","doc://com.apple.coreaudio/documentation/CoreAudio/kAudioHardwarePropertyTranslateBundleIDToPlugIn"],"anchor":"Constants"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"kAudioHardwarePropertyClockDeviceList","kind":"identifier"}]}]}},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyProcessIsAudible/title","value":"kAudioHardwarePropertyProcessIsAudible","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyProcessIsAudible/fragments","value":[{"kind":"identifier","text":"kAudioHardwarePropertyProcessIsAudible"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDefaultSystemOutputDevice/title","value":"kAudioHardwarePropertyDefaultSystemOutputDevice","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDefaultSystemOutputDevice/fragments","value":[{"kind":"identifier","text":"kAudioHardwarePropertyDefaultSystemOutputDevice"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyHogModeIsAllowed/title","value":"kAudioHardwarePropertyHogModeIsAllowed","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyHogModeIsAllowed/fragments","value":[{"kind":"identifier","text":"kAudioHardwarePropertyHogModeIsAllowed"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDefaultInputDevice/title","value":"kAudioHardwarePropertyDefaultInputDevice","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDefaultInputDevice/fragments","value":[{"kind":"identifier","text":"kAudioHardwarePropertyDefaultInputDevice"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/title","value":"AudioObjectPropertySelector","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/fragments","value":[{"kind":"identifier","text":"AudioObjectPropertySelector"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioObjectPropertySelector/navigatorTitle","value":[{"text":"AudioObjectPropertySelector","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertySleepingIsAllowed/title","value":"kAudioHardwarePropertySleepingIsAllowed","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertySleepingIsAllowed/fragments","value":[{"kind":"identifier","text":"kAudioHardwarePropertySleepingIsAllowed"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyBoxList/title","value":"kAudioHardwarePropertyBoxList","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyBoxList/fragments","value":[{"text":"kAudioHardwarePropertyBoxList","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyMixStereoToMono/title","value":"kAudioHardwarePropertyMixStereoToMono","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyMixStereoToMono/fragments","value":[{"text":"kAudioHardwarePropertyMixStereoToMono","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyTranslateBundleIDToPlugIn/title","value":"kAudioHardwarePropertyTranslateBundleIDToPlugIn","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyTranslateBundleIDToPlugIn/fragments","value":[{"text":"kAudioHardwarePropertyTranslateBundleIDToPlugIn","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyPlugInList/title","value":"kAudioHardwarePropertyPlugInList","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyPlugInList/fragments","value":[{"text":"kAudioHardwarePropertyPlugInList","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyIsInitingOrExiting/title","value":"kAudioHardwarePropertyIsInitingOrExiting","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyIsInitingOrExiting/fragments","value":[{"text":"kAudioHardwarePropertyIsInitingOrExiting","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDevices/title","value":"kAudioHardwarePropertyDevices","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDevices/fragments","value":[{"text":"kAudioHardwarePropertyDevices","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyPowerHint/title","value":"kAudioHardwarePropertyPowerHint","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyPowerHint/fragments","value":[{"text":"kAudioHardwarePropertyPowerHint","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyClockDeviceList/title","value":"kAudioHardwarePropertyClockDeviceList","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyClockDeviceList/fragments","value":[{"kind":"identifier","text":"kAudioHardwarePropertyClockDeviceList"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyProcessIsMaster/title","value":"kAudioHardwarePropertyProcessIsMaster","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyProcessIsMaster/fragments","value":[{"text":"kAudioHardwarePropertyProcessIsMaster","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDefaultOutputDevice/title","value":"kAudioHardwarePropertyDefaultOutputDevice","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyDefaultOutputDevice/fragments","value":[{"text":"kAudioHardwarePropertyDefaultOutputDevice","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyServiceRestarted/title","value":"kAudioHardwarePropertyServiceRestarted","op":"replace"},{"path":"/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1kAudioHardwarePropertyServiceRestarted/fragments","value":[{"text":"kAudioHardwarePropertyServiceRestarted","kind":"identifier"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}