{
  "abstract": [
    {
      "text": "Returns detailed change information for the specified asset or collection.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/Photos",
        "doc://com.apple.photokit/documentation/Photos/PHChange"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.photokit/documentation/Photos/PHChange/changeDetailsForObject:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHChange(im)changeDetailsForObject:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "changeDetailsForObject:"
      }
    ],
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "changeDetailsForObject:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "changeDetailsForObject:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHObjectChangeDetails",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PHObjectChangeDetails",
              "text": "PHObjectChangeDetails"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "identifier",
              "text": "changeDetailsForObject:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PHObject",
              "text": "PHObject"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "object"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollection",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionList",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " object.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "object"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A change details object, or ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if there have been no changes to the specified asset or collection.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When Photos calls your change observer’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibraryChangeObserver/photoLibraryDidChange(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, get detailed change information about an asset or collection you’ve previously fetched by calling the ",
              "type": "text"
            },
            {
              "code": "changeDetailsForObject",
              "type": "codeVoice"
            },
            {
              "text": " methods:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.photokit/documentation/Photos/PHChange/changeDetailsForObject:",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.photokit/documentation/Photos/PHChange/changeDetails(for:)-536rd",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.photokit/documentation/Photos/PHChange/changeDetails(for:)-2fne7",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "If the asset or collection has changed since you last fetched it, the resulting ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHObjectChangeDetails",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object describes the changes. If there are no changes between the fetched object and the current state of the asset or collection it represents in the Photos library, this method returns ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For an asset collection or collection list, this method and the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHObjectChangeDetails",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object it returns describe changes only to the collection’s properties. If you are instead interested in changes to the collection’s membership, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHChange/changeDetails(for:)-33a6n",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset": {
      "abstract": [
        {
          "text": "A representation of an image, video, or Live Photo in the Photos library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAsset"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAsset"
        }
      ],
      "role": "symbol",
      "title": "PHAsset",
      "type": "topic",
      "url": "/documentation/photos/phasset"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollection": {
      "abstract": [
        {
          "text": "A representation of a Photos asset grouping, such as a moment, user-created album, or smart album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetCollection"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollection"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollection",
      "type": "topic",
      "url": "/documentation/photos/phassetcollection"
    },
    "doc://com.apple.photokit/documentation/Photos/PHChange": {
      "abstract": [
        {
          "text": "A description of a change that occurred in the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHChange"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHChange"
        }
      ],
      "role": "symbol",
      "title": "PHChange",
      "type": "topic",
      "url": "/documentation/photos/phchange"
    },
    "doc://com.apple.photokit/documentation/Photos/PHChange/changeDetails(for:)-2fne7": {
      "abstract": [
        {
          "text": "Returns detailed change information for a fetch result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeDetails"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHFetchResult",
          "text": "PHFetchResult"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHFetchResultChangeDetails",
          "text": "PHFetchResultChangeDetails"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHChange/changeDetails(for:)-2fne7",
      "kind": "symbol",
      "role": "symbol",
      "title": "changeDetails(for:)",
      "type": "topic",
      "url": "/documentation/photos/phchange/changedetails(for:)-2fne7"
    },
    "doc://com.apple.photokit/documentation/Photos/PHChange/changeDetails(for:)-33a6n": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeDetails"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHFetchResult",
          "text": "PHFetchResult"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9AnyObjecta",
          "text": "AnyObject"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHFetchResultChangeDetails",
          "text": "PHFetchResultChangeDetails"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHObject",
          "text": "PHObject"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHChange/changeDetails(for:)-33a6n",
      "kind": "symbol",
      "role": "symbol",
      "title": "changeDetails(for:)",
      "type": "topic",
      "url": "/documentation/photos/phchange/changedetails(for:)-33a6n"
    },
    "doc://com.apple.photokit/documentation/Photos/PHChange/changeDetails(for:)-536rd": {
      "abstract": [
        {
          "text": "Returns detailed change information for the specified asset or collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeDetails"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHObjectChangeDetails",
          "text": "PHObjectChangeDetails"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHChange/changeDetails(for:)-536rd",
      "kind": "symbol",
      "role": "symbol",
      "title": "changeDetails(for:)",
      "type": "topic",
      "url": "/documentation/photos/phchange/changedetails(for:)-536rd"
    },
    "doc://com.apple.photokit/documentation/Photos/PHChange/changeDetailsForFetchResult:": {
      "abstract": [
        {
          "text": "Returns detailed change information for a fetch result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "changeDetailsForFetchResult:"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHChange/changeDetailsForFetchResult:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "changeDetailsForFetchResult:"
        }
      ],
      "role": "symbol",
      "title": "changeDetailsForFetchResult:",
      "type": "topic",
      "url": "/documentation/photos/phchange/changedetailsforfetchresult:"
    },
    "doc://com.apple.photokit/documentation/Photos/PHChange/changeDetailsForObject:": {
      "abstract": [
        {
          "text": "Returns detailed change information for the specified asset or collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "changeDetailsForObject:"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHChange/changeDetailsForObject:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "changeDetailsForObject:"
        }
      ],
      "role": "symbol",
      "title": "changeDetailsForObject:",
      "type": "topic",
      "url": "/documentation/photos/phchange/changedetailsforobject:"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCollectionList": {
      "abstract": [
        {
          "text": "A group containing Photos asset collections, such as Moments, Years, or folders of user-created albums.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHCollectionList"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCollectionList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHCollectionList"
        }
      ],
      "role": "symbol",
      "title": "PHCollectionList",
      "type": "topic",
      "url": "/documentation/photos/phcollectionlist"
    },
    "doc://com.apple.photokit/documentation/Photos/PHObject": {
      "abstract": [
        {
          "text": "The abstract superclass for Photos model objects (assets and collections).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHObject"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHObject"
        }
      ],
      "role": "symbol",
      "title": "PHObject",
      "type": "topic",
      "url": "/documentation/photos/phobject"
    },
    "doc://com.apple.photokit/documentation/Photos/PHObjectChangeDetails": {
      "abstract": [
        {
          "text": "A description of changes that occurred in an asset or collection object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHObjectChangeDetails"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHObjectChangeDetails",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHObjectChangeDetails"
        }
      ],
      "role": "symbol",
      "title": "PHObjectChangeDetails",
      "type": "topic",
      "url": "/documentation/photos/phobjectchangedetails"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibraryChangeObserver/photoLibraryDidChange(_:)": {
      "abstract": [
        {
          "text": "Tells your observer that a set of changes has occurred in the Photos library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photoLibraryDidChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHChange",
          "text": "PHChange"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibraryChangeObserver/photoLibraryDidChange(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "photoLibraryDidChange:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "photoLibraryDidChange(_:)",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrarychangeobserver/photolibrarydidchange(_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Change-Details",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHChange/changeDetailsForFetchResult:"
      ],
      "title": "Getting Change Details"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHObject/title",
          "value": "PHObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHObjectChangeDetails/title",
          "value": "PHObjectChangeDetails"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHObjectChangeDetails/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHObjectChangeDetails"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHObjectChangeDetails/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHObjectChangeDetails"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibraryChangeObserver~1photoLibraryDidChange(_:)/title",
          "value": "photoLibraryDidChange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibraryChangeObserver~1photoLibraryDidChange(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "photoLibraryDidChange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/title",
          "value": "PHAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionList/title",
          "value": "PHCollectionList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCollectionList/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCollectionList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection/title",
          "value": "PHAssetCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHChange/title",
          "value": "PHChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHChange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHChange"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photos/phchange/changedetailsforobject:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
