{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsArbitraryLoadsForMedia"},"kind":"symbol","primaryContentSections":[{"kind":"details","details":{"ideTitle":"Allows Arbitrary Loads for Media","name":"NSAllowsArbitraryLoadsForMedia","titleStyle":"symbol","value":[{"baseType":"boolean","arrayMode":false}],"platforms":[]},"title":"Details"},{"kind":"attributes","title":"Attributes","attributes":[{"kind":"default","value":"NO"}]},{"kind":"content","content":[{"type":"heading","anchor":"Discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Set this key’s value to ","type":"text"},{"type":"codeVoice","code":"YES"},{"text":" to disable App Transport Security restrictions for media loaded using the ","type":"text"},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/AVFoundation","isActive":true},{"text":" framework, without affecting your ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/foundation/urlsession"},{"type":"text","text":" connections. Domains you specify in the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSExceptionDomains"},{"type":"text","text":" dictionary aren’t affected by this key’s value."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Employ this key only for loading encrypted media—like files protected by FairPlay or by secure "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/HTTP-Live-Streaming"},{"type":"text","text":"—that don’t contain personalized information."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In iOS 10 and later and in macOS 10.12 and later, if you include this key with any value, then App Transport Security ignores the value of the "},{"identifier":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsArbitraryLoads","isActive":true,"type":"reference"},{"type":"text","text":" key, instead using that key’s default value of "},{"type":"codeVoice","code":"NO"},{"type":"text","text":". For more information about how the OS version affects ATS behavior, see the "},{"identifier":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity","isActive":true,"type":"reference"},{"type":"text","text":" key’s Versioning section."}]},{"type":"aside","name":"Important","content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"You must supply a justification during App Store review if you set the key’s value to YES, as described in "},{"code":"Provide Justification for Exceptions","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}],"style":"important"}]}],"metadata":{"platforms":[{"unavailable":false,"beta":false,"introducedAt":"10.0","name":"iOS","deprecated":false},{"unavailable":false,"beta":false,"introducedAt":"10.0","name":"iPadOS","deprecated":false},{"unavailable":false,"beta":false,"introducedAt":"10.12","name":"macOS","deprecated":false},{"unavailable":false,"beta":false,"introducedAt":"1.0","name":"visionOS","deprecated":false}],"title":"NSAllowsArbitraryLoadsForMedia","symbolKind":"typealias","navigatorTitle":[{"text":"NSAllowsArbitraryLoadsForMedia","kind":"identifier"}],"modules":[{"name":"Bundle Resources"}],"roleHeading":"Property List Key","role":"symbol","externalID":"plist:Information_Property_List.NSAppTransportSecurity.NSAllowsArbitraryLoadsForMedia"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"A Boolean value indicating whether all App Transport Security restrictions are disabled for requests made using the AV Foundation framework."}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.bundleresources/documentation/BundleResources","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/bundleresources/information-property-list/nsapptransportsecurity/nsallowsarbitraryloadsformedia"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/bundleresources/information-property-list/nsapptransportsecurity/nsallowsarbitraryloadsformedia"]}],"seeAlsoSections":[{"anchor":"Global-Exceptions","identifiers":["doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsArbitraryLoads","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsArbitraryLoadsInWebContent","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsLocalNetworking"],"generated":true,"title":"Global Exceptions"}],"references":{"doc://com.apple.bundleresources/documentation/BundleResources":{"identifier":"doc://com.apple.bundleresources/documentation/BundleResources","title":"Bundle Resources","abstract":[{"type":"text","text":"Resources located in an app, framework, or plugin bundle."}],"kind":"symbol","role":"collection","url":"/documentation/bundleresources","type":"topic"},"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List":{"identifier":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List","title":"Information Property List","abstract":[{"type":"text","text":"A resource containing key-value pairs that identify and configure a bundle."}],"kind":"symbol","role":"symbol","url":"/documentation/bundleresources/information-property-list","name":"Information Property List","navigatorTitle":[{"text":"Information Property List","kind":"identifier"}],"type":"topic","titleStyle":"symbol"},"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSExceptionDomains":{"ideTitle":"Exception Domains","title":"NSExceptionDomains","abstract":[{"type":"text","text":"Custom App Transport Security (ATS) configurations for named domains."}],"role":"symbol","url":"/documentation/bundleresources/information-property-list/nsapptransportsecurity/nsexceptiondomains","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSExceptionDomains"}],"identifier":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSExceptionDomains","type":"topic","name":"NSExceptionDomains","titleStyle":"symbol"},"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity":{"identifier":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity","title":"NSAppTransportSecurity","abstract":[{"text":"A description of changes made to the default security for HTTP connections.","type":"text"}],"kind":"symbol","role":"symbol","ideTitle":"App Transport Security Settings","url":"/documentation/bundleresources/information-property-list/nsapptransportsecurity","name":"NSAppTransportSecurity","navigatorTitle":[{"kind":"identifier","text":"NSAppTransportSecurity"}],"type":"topic","titleStyle":"symbol"},"doc://com.apple.documentation/documentation/foundation/urlsession":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/foundation/urlsession","kind":"symbol","fragments":[{"text":"class ","kind":"text"},{"kind":"identifier","text":"URLSession"}],"url":"/documentation/foundation/urlsession","title":"URLSession","abstract":[{"type":"text","text":"An object that coordinates a group of related, network data transfer tasks."}],"role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","kind":"technologies","role":"overview","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsLocalNetworking":{"kind":"symbol","name":"NSAllowsLocalNetworking","role":"symbol","title":"NSAllowsLocalNetworking","abstract":[{"text":"A Boolean value that indicates whether to allow local resources to load.","type":"text"}],"url":"/documentation/bundleresources/information-property-list/nsapptransportsecurity/nsallowslocalnetworking","titleStyle":"symbol","type":"topic","ideTitle":"Allows Local Networking","identifier":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsLocalNetworking","navigatorTitle":[{"kind":"identifier","text":"NSAllowsLocalNetworking"}]},"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsArbitraryLoadsInWebContent":{"type":"topic","ideTitle":"Allow Arbitrary Loads in Web Content","identifier":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsArbitraryLoadsInWebContent","kind":"symbol","url":"/documentation/bundleresources/information-property-list/nsapptransportsecurity/nsallowsarbitraryloadsinwebcontent","title":"NSAllowsArbitraryLoadsInWebContent","abstract":[{"type":"text","text":"A Boolean value indicating whether all App Transport Security restrictions are disabled for requests made from web views."}],"name":"NSAllowsArbitraryLoadsInWebContent","role":"symbol","titleStyle":"symbol","navigatorTitle":[{"text":"NSAllowsArbitraryLoadsInWebContent","kind":"identifier"}]},"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsArbitraryLoadsForMedia":{"type":"topic","ideTitle":"Allows Arbitrary Loads for Media","identifier":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsArbitraryLoadsForMedia","kind":"symbol","url":"/documentation/bundleresources/information-property-list/nsapptransportsecurity/nsallowsarbitraryloadsformedia","title":"NSAllowsArbitraryLoadsForMedia","abstract":[{"type":"text","text":"A Boolean value indicating whether all App Transport Security restrictions are disabled for requests made using the AV Foundation framework."}],"name":"NSAllowsArbitraryLoadsForMedia","role":"symbol","titleStyle":"symbol","navigatorTitle":[{"text":"NSAllowsArbitraryLoadsForMedia","kind":"identifier"}]},"doc://com.apple.documentation/documentation/AVFoundation":{"abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"title":"AVFoundation","url":"/documentation/AVFoundation","kind":"symbol","role":"collection","type":"topic","identifier":"doc://com.apple.documentation/documentation/AVFoundation"},"doc://com.apple.documentation/documentation/HTTP-Live-Streaming":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/HTTP-Live-Streaming","role":"collection","title":"HTTP Live Streaming","url":"/documentation/HTTP-Live-Streaming","kind":"article","abstract":[{"text":"Send audio and video to iOS, tvOS, and macOS devices.","type":"text"}]},"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsArbitraryLoads":{"url":"/documentation/bundleresources/information-property-list/nsapptransportsecurity/nsallowsarbitraryloads","navigatorTitle":[{"text":"NSAllowsArbitraryLoads","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsArbitraryLoads","titleStyle":"symbol","ideTitle":"Allow Arbitrary Loads","name":"NSAllowsArbitraryLoads","abstract":[{"text":"A Boolean value indicating whether App Transport Security restrictions are disabled for all network connections.","type":"text"}],"title":"NSAllowsArbitraryLoads"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"beta":false,"name":"iOS","unavailable":false,"deprecated":false,"introducedAt":"10.0"},{"beta":false,"name":"iPadOS","unavailable":false,"deprecated":false,"introducedAt":"10.0"},{"beta":false,"name":"macOS","unavailable":false,"deprecated":false,"introducedAt":"10.12"},{"beta":false,"name":"visionOS","unavailable":false,"deprecated":false,"introducedAt":"1.0"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Property List Key","op":"replace"},{"path":"/metadata/title","value":"NSAllowsArbitraryLoadsForMedia","op":"replace"},{"path":"/metadata/symbolKind","value":"typealias","op":"replace"},{"op":"replace","path":"/metadata/navigatorTitle","value":[{"text":"NSAllowsArbitraryLoadsForMedia","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.bundleresources/documentation/BundleResources","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsArbitraryLoads","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsArbitraryLoadsInWebContent","doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/NSAppTransportSecurity/NSAllowsLocalNetworking"],"anchor":"Global-Exceptions","title":"Global Exceptions","generated":true}]},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title","value":"Information Property List"},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle","value":[{"text":"Information Property List","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAppTransportSecurity~1NSExceptionDomains/title","value":"NSExceptionDomains"},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAppTransportSecurity~1NSExceptionDomains/navigatorTitle","value":[{"text":"NSExceptionDomains","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAppTransportSecurity/title","value":"NSAppTransportSecurity"},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAppTransportSecurity/navigatorTitle","value":[{"kind":"identifier","text":"NSAppTransportSecurity"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1urlsession/title","value":"NSURLSession"},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAppTransportSecurity~1NSAllowsLocalNetworking/title","value":"NSAllowsLocalNetworking"},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAppTransportSecurity~1NSAllowsLocalNetworking/navigatorTitle","value":[{"kind":"identifier","text":"NSAllowsLocalNetworking"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAppTransportSecurity~1NSAllowsArbitraryLoadsInWebContent/title","value":"NSAllowsArbitraryLoadsInWebContent"},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAppTransportSecurity~1NSAllowsArbitraryLoadsInWebContent/navigatorTitle","value":[{"text":"NSAllowsArbitraryLoadsInWebContent","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAppTransportSecurity~1NSAllowsArbitraryLoadsForMedia/title","value":"NSAllowsArbitraryLoadsForMedia"},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAppTransportSecurity~1NSAllowsArbitraryLoadsForMedia/navigatorTitle","value":[{"kind":"identifier","text":"NSAllowsArbitraryLoadsForMedia"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAppTransportSecurity~1NSAllowsArbitraryLoads/title","value":"NSAllowsArbitraryLoads"},{"op":"replace","path":"/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1NSAppTransportSecurity~1NSAllowsArbitraryLoads/navigatorTitle","value":[{"kind":"identifier","text":"NSAllowsArbitraryLoads"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}