{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits"]]},"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/none","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/button","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/link","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/image","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/searchField","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/toggleButton","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/keyboardKey","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/staticText","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/header","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/tabBar","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/summaryElement","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/selected","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/notEnabled","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/adjustable","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/allowsDirectInteraction"],"title":"Constants","anchor":"Constants"}],"metadata":{"roleHeading":"Type Property","modules":[{"name":"UIKit"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIAccessibilityTraitUpdatesFrequently"}],"platforms":[{"unavailable":false,"deprecated":false,"name":"iOS","beta":false},{"unavailable":false,"deprecated":false,"name":"iPadOS","beta":false},{"unavailable":false,"deprecated":false,"name":"Mac Catalyst","beta":false},{"unavailable":false,"deprecated":false,"name":"tvOS","beta":false},{"unavailable":false,"deprecated":false,"name":"visionOS","beta":false},{"unavailable":false,"introducedAt":"2.0","deprecated":false,"name":"watchOS","beta":false}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatesFrequently"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@UIAccessibilityTraits","kind":"typeIdentifier","text":"UIAccessibilityTraits"}],"symbolKind":"property","extendedModule":"UIKit","externalID":"c:@UIAccessibilityTraitUpdatesFrequently","title":"updatesFrequently"},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/updatesFrequently"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uiaccessibilitytraits/updatesfrequently"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uiaccessibilitytraits/updatesfrequently"]}],"abstract":[{"text":"The accessibility element frequently updates its label or value.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"nonisolated"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatesFrequently"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@UIAccessibilityTraits","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits","text":"UIAccessibilityTraits"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Use this trait to characterize an accessibility element that updates its label or value too frequently to send update notifications. Include this trait when you want an assistive app to avoid handling continual notifications and, instead, poll for changes when it needs updated information. For example, you might use this trait to characterize the readout of a stopwatch."}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/header":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"header","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIAccessibilityTraits","kind":"typeIdentifier","preciseIdentifier":"c:@T@UIAccessibilityTraits"}],"navigatorTitle":[{"text":"UIAccessibilityTraitHeader","kind":"identifier"}],"abstract":[{"text":"The accessibility element is a header that divides content into sections, such as the title of a navigation bar.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/header","url":"/documentation/uikit/uiaccessibilitytraits/header","type":"topic","title":"header","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/searchField":{"navigatorTitle":[{"text":"UIAccessibilityTraitSearchField","kind":"identifier"}],"title":"searchField","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/searchField","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"searchField","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIAccessibilityTraits","kind":"typeIdentifier","preciseIdentifier":"c:@T@UIAccessibilityTraits"}],"abstract":[{"text":"The accessibility element behaves like a search field.","type":"text"}],"url":"/documentation/uikit/uiaccessibilitytraits/searchfield","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/allowsDirectInteraction":{"role":"symbol","abstract":[{"type":"text","text":"The accessibility element allows direct touch interaction for VoiceOver users."}],"url":"/documentation/uikit/uiaccessibilitytraits/allowsdirectinteraction","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allowsDirectInteraction"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@UIAccessibilityTraits","kind":"typeIdentifier","text":"UIAccessibilityTraits"}],"title":"allowsDirectInteraction","navigatorTitle":[{"kind":"identifier","text":"UIAccessibilityTraitAllowsDirectInteraction"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/allowsDirectInteraction","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/notEnabled":{"abstract":[{"text":"The accessibility element isn’t in an enabled state and doesn’t respond to user interaction.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIAccessibilityTraits","kind":"typeIdentifier","preciseIdentifier":"c:@T@UIAccessibilityTraits"}],"role":"symbol","url":"/documentation/uikit/uiaccessibilitytraits/notenabled","navigatorTitle":[{"text":"UIAccessibilityTraitNotEnabled","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/notEnabled","type":"topic","title":"notEnabled","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/selected":{"navigatorTitle":[{"kind":"identifier","text":"UIAccessibilityTraitSelected"}],"title":"selected","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/selected","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"selected"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@UIAccessibilityTraits","kind":"typeIdentifier","text":"UIAccessibilityTraits"}],"abstract":[{"type":"text","text":"The accessibility element is currently in a selected state."}],"url":"/documentation/uikit/uiaccessibilitytraits/selected","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/keyboardKey":{"role":"symbol","abstract":[{"text":"The accessibility element behaves like a keyboard key.","type":"text"}],"url":"/documentation/uikit/uiaccessibilitytraits/keyboardkey","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIAccessibilityTraits","kind":"typeIdentifier","preciseIdentifier":"c:@T@UIAccessibilityTraits"}],"title":"keyboardKey","navigatorTitle":[{"text":"UIAccessibilityTraitKeyboardKey","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/keyboardKey","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/image":{"abstract":[{"type":"text","text":"The accessibility element behaves like an image."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@UIAccessibilityTraits","kind":"typeIdentifier","text":"UIAccessibilityTraits"}],"url":"/documentation/uikit/uiaccessibilitytraits/image","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/image","kind":"symbol","type":"topic","role":"symbol","title":"image","navigatorTitle":[{"kind":"identifier","text":"UIAccessibilityTraitImage"}]},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/summaryElement":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"summaryElement","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@UIAccessibilityTraits","text":"UIAccessibilityTraits","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"UIAccessibilityTraitSummaryElement","kind":"identifier"}],"abstract":[{"type":"text","text":"The accessibility element provides summary information when the app starts."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/summaryElement","url":"/documentation/uikit/uiaccessibilitytraits/summaryelement","type":"topic","title":"summaryElement","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/tabBar":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tabBar","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIAccessibilityTraits","preciseIdentifier":"c:@T@UIAccessibilityTraits","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"UIAccessibilityTraitTabBar","kind":"identifier"}],"abstract":[{"text":"The accessibility element behaves like a tab bar.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/tabBar","url":"/documentation/uikit/uiaccessibilitytraits/tabbar","type":"topic","title":"tabBar","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/updatesFrequently":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updatesFrequently","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIAccessibilityTraits","kind":"typeIdentifier","preciseIdentifier":"c:@T@UIAccessibilityTraits"}],"navigatorTitle":[{"text":"UIAccessibilityTraitUpdatesFrequently","kind":"identifier"}],"abstract":[{"text":"The accessibility element frequently updates its label or value.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/updatesFrequently","url":"/documentation/uikit/uiaccessibilitytraits/updatesfrequently","type":"topic","title":"updatesFrequently","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/button":{"role":"symbol","abstract":[{"text":"The accessibility element behaves like a button.","type":"text"}],"url":"/documentation/uikit/uiaccessibilitytraits/button","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"button","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIAccessibilityTraits","kind":"typeIdentifier","preciseIdentifier":"c:@T@UIAccessibilityTraits"}],"title":"button","navigatorTitle":[{"text":"UIAccessibilityTraitButton","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/button","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/staticText":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"staticText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@UIAccessibilityTraits","text":"UIAccessibilityTraits"}],"navigatorTitle":[{"kind":"identifier","text":"UIAccessibilityTraitStaticText"}],"abstract":[{"type":"text","text":"The accessibility element behaves like static text that can’t change."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/staticText","url":"/documentation/uikit/uiaccessibilitytraits/statictext","type":"topic","title":"staticText","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/toggleButton":{"role":"symbol","abstract":[{"type":"text","text":"The accessibility element behaves like a toggle button."}],"navigatorTitle":[{"kind":"identifier","text":"UIAccessibilityTraitToggleButton"}],"type":"topic","url":"/documentation/uikit/uiaccessibilitytraits/togglebutton","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/toggleButton","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"toggleButton"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@UIAccessibilityTraits","kind":"typeIdentifier","text":"UIAccessibilityTraits"}],"title":"toggleButton"},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/link":{"abstract":[{"type":"text","text":"The accessibility element behaves like a link."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"link"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@UIAccessibilityTraits","text":"UIAccessibilityTraits"}],"url":"/documentation/uikit/uiaccessibilitytraits/link","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/link","kind":"symbol","type":"topic","role":"symbol","title":"link","navigatorTitle":[{"kind":"identifier","text":"UIAccessibilityTraitLink"}]},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits":{"role":"symbol","abstract":[{"type":"text","text":"Constants that describe how an accessibility element behaves."}],"navigatorTitle":[{"kind":"identifier","text":"UIAccessibilityTraits"}],"type":"topic","url":"/documentation/uikit/uiaccessibilitytraits","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIAccessibilityTraits"}],"title":"UIAccessibilityTraits"},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/none":{"role":"symbol","abstract":[{"type":"text","text":"The accessibility element has no traits."}],"navigatorTitle":[{"kind":"identifier","text":"UIAccessibilityTraitNone"}],"type":"topic","url":"/documentation/uikit/uiaccessibilitytraits/none","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/none","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@UIAccessibilityTraits","kind":"typeIdentifier","text":"UIAccessibilityTraits"}],"title":"none"},"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/adjustable":{"navigatorTitle":[{"text":"UIAccessibilityTraitAdjustable","kind":"identifier"}],"title":"adjustable","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/adjustable","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adjustable","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@UIAccessibilityTraits","text":"UIAccessibilityTraits","kind":"typeIdentifier"}],"abstract":[{"text":"The accessibility element allows continuous adjustment through a range of values.","type":"text"}],"url":"/documentation/uikit/uiaccessibilitytraits/adjustable","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"unavailable":false,"name":"iOS","beta":false},{"deprecated":false,"unavailable":false,"name":"iPadOS","beta":false},{"unavailable":false,"deprecated":false,"name":"Mac Catalyst","beta":false},{"unavailable":false,"deprecated":false,"name":"tvOS","beta":false},{"unavailable":false,"deprecated":false,"name":"visionOS","beta":false},{"unavailable":false,"introducedAt":"2.0","deprecated":false,"name":"watchOS","beta":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Global Variable","path":"/metadata/roleHeading","op":"replace"},{"value":"UIAccessibilityTraitUpdatesFrequently","path":"/metadata/title","op":"replace"},{"path":"/metadata/symbolKind","value":"var","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"UIAccessibilityTraitUpdatesFrequently","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"anchor":"Constants","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/none","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/button","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/link","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/image","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/searchField","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/toggleButton","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/keyboardKey","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/staticText","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/header","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/tabBar","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/summaryElement","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/selected","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/notEnabled","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/adjustable","doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/allowsDirectInteraction"],"generated":true,"title":"Constants"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits","text":"UIAccessibilityTraits","preciseIdentifier":"c:@T@UIAccessibilityTraits"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIAccessibilityTraitUpdatesFrequently"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1header/title","op":"replace","value":"UIAccessibilityTraitHeader"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1header/fragments","value":[{"kind":"identifier","text":"UIAccessibilityTraitHeader"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1searchField/title","value":"UIAccessibilityTraitSearchField"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1searchField/fragments","value":[{"text":"UIAccessibilityTraitSearchField","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1allowsDirectInteraction/title","value":"UIAccessibilityTraitAllowsDirectInteraction"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1allowsDirectInteraction/fragments","value":[{"text":"UIAccessibilityTraitAllowsDirectInteraction","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1notEnabled/title","value":"UIAccessibilityTraitNotEnabled"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1notEnabled/fragments","value":[{"kind":"identifier","text":"UIAccessibilityTraitNotEnabled"}]},{"value":"UIAccessibilityTraitSelected","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1selected/title"},{"value":[{"text":"UIAccessibilityTraitSelected","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1selected/fragments"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1keyboardKey/title","op":"replace","value":"UIAccessibilityTraitKeyboardKey"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1keyboardKey/fragments","op":"replace","value":[{"text":"UIAccessibilityTraitKeyboardKey","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1image/title","op":"replace","value":"UIAccessibilityTraitImage"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1image/fragments","op":"replace","value":[{"kind":"identifier","text":"UIAccessibilityTraitImage"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1summaryElement/title","op":"replace","value":"UIAccessibilityTraitSummaryElement"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1summaryElement/fragments","op":"replace","value":[{"text":"UIAccessibilityTraitSummaryElement","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1tabBar/title","op":"replace","value":"UIAccessibilityTraitTabBar"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1tabBar/fragments","op":"replace","value":[{"text":"UIAccessibilityTraitTabBar","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1updatesFrequently/title","op":"replace","value":"UIAccessibilityTraitUpdatesFrequently"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1updatesFrequently/fragments","op":"replace","value":[{"text":"UIAccessibilityTraitUpdatesFrequently","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1button/title","op":"replace","value":"UIAccessibilityTraitButton"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1button/fragments","op":"replace","value":[{"kind":"identifier","text":"UIAccessibilityTraitButton"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1staticText/title","op":"replace","value":"UIAccessibilityTraitStaticText"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1staticText/fragments","op":"replace","value":[{"text":"UIAccessibilityTraitStaticText","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1toggleButton/title","op":"replace","value":"UIAccessibilityTraitToggleButton"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1toggleButton/fragments","op":"replace","value":[{"kind":"identifier","text":"UIAccessibilityTraitToggleButton"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1link/title","op":"replace","value":"UIAccessibilityTraitLink"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1link/fragments","op":"replace","value":[{"text":"UIAccessibilityTraitLink","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits/title","op":"replace","value":"UIAccessibilityTraits"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits/fragments","op":"replace","value":[{"text":"UIAccessibilityTraits","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits/navigatorTitle","op":"replace","value":[{"text":"UIAccessibilityTraits","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1none/title","op":"replace","value":"UIAccessibilityTraitNone"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1none/fragments","op":"replace","value":[{"kind":"identifier","text":"UIAccessibilityTraitNone"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1adjustable/title","op":"replace","value":"UIAccessibilityTraitAdjustable"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1adjustable/fragments","op":"replace","value":[{"kind":"identifier","text":"UIAccessibilityTraitAdjustable"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}