{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentGroup"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentGroup/group(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "s:So44UITextFormattingViewControllerComponentGroupC5UIKitE5groupyABSaySo0abcdE0CGFZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "group"
      },
      {
        "kind": "text",
        "text": "(["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
        "text": "UITextFormattingViewController"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UITextFormattingViewControllerComponent",
        "text": "Component"
      },
      {
        "kind": "text",
        "text": "]) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
        "text": "UITextFormattingViewController"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UITextFormattingViewControllerComponentGroup",
        "text": "ComponentGroup"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "group(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "group"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "components"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
              "text": "UITextFormattingViewController"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Component",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UITextFormattingViewControllerComponent",
              "text": "Component"
            },
            {
              "kind": "text",
              "text": "]) -> "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
              "text": "UITextFormattingViewController"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentGroup",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UITextFormattingViewControllerComponentGroup",
              "text": "ComponentGroup"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextFormattingViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewController"
        }
      ],
      "role": "symbol",
      "title": "UITextFormattingViewController",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Component": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Component"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Component",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Component"
        }
      ],
      "role": "symbol",
      "title": "UITextFormattingViewController.Component",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/component"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentGroup": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ComponentGroup"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ComponentGroup"
        }
      ],
      "role": "symbol",
      "title": "UITextFormattingViewController.ComponentGroup",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/componentgroup"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentGroup/group(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "group"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
          "text": "UITextFormattingViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextFormattingViewControllerComponent",
          "text": "Component"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
          "text": "UITextFormattingViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextFormattingViewControllerComponentGroup",
          "text": "ComponentGroup"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentGroup/group(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "group(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/componentgroup/group(_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController/title",
          "value": "UITextFormattingViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentGroup/title",
          "value": "UITextFormattingViewControllerComponentGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerComponentGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerComponentGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1Component/title",
          "value": "UITextFormattingViewControllerComponent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1Component/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1Component/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerComponent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitextformattingviewcontroller/componentgroup/group(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
