{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/pdfkit/pdfselection/extend(atstart:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/pdfkit/pdfselection/extend(atstart:)"]}],"identifier":{"url":"doc://com.apple.pdfkit/documentation/PDFKit/PDFSelection/extend(atStart:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.pdfkit/documentation/PDFKit","doc://com.apple.pdfkit/documentation/PDFKit/PDFSelection"]]},"seeAlsoSections":[{"generated":true,"title":"Modifying a Selection","anchor":"Modifying-a-Selection","identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/PDFSelection/add(_:)-8c2r","doc://com.apple.pdfkit/documentation/PDFKit/PDFSelection/add(_:)-3fyld","doc://com.apple.pdfkit/documentation/PDFKit/PDFSelection/extend(atEnd:)"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"extend"},{"kind":"text","text":"("},{"kind":"externalParam","text":"atStart"},{"kind":"text","text":" "},{"kind":"internalParam","text":"precede"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The selection may be extended by any amount, up to and including the beginning of the document."}]}]}],"abstract":[{"type":"text","text":"Extends the selection from its start toward the beginning of the document."}],"metadata":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extend","kind":"identifier"},{"text":"(","kind":"text"},{"text":"atStart","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"externalID":"c:objc(cs)PDFSelection(im)extendSelectionAtStart:","title":"extend(atStart:)","symbolKind":"method","navigatorTitle":[{"text":"extendSelectionAtStart:","kind":"identifier"}],"modules":[{"name":"PDFKit"}],"roleHeading":"Instance Method","platforms":[{"deprecated":false,"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0"},{"deprecated":false,"beta":false,"unavailable":false,"name":"iPadOS","introducedAt":"11.0"},{"unavailable":false,"introducedAt":"13.1","deprecated":false,"beta":false,"name":"Mac Catalyst"},{"unavailable":false,"introducedAt":"10.4","deprecated":false,"beta":false,"name":"macOS"},{"unavailable":false,"introducedAt":"11.0","deprecated":false,"beta":false,"name":"tvOS"},{"unavailable":false,"introducedAt":"1.0","deprecated":false,"beta":false,"name":"visionOS"}]},"references":{"doc://com.externally.resolved.symbol/s:Si":{"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Si","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}],"title":"Int","url":"/documentation/Swift/Int","abstract":[{"type":"text","text":"A signed integer value type."}],"type":"topic","role":"symbol"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFSelection/extend(atStart:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"extend"},{"kind":"text","text":"("},{"kind":"externalParam","text":"atStart"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"extend(atStart:)","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFSelection/extend(atStart:)","type":"topic","url":"/documentation/pdfkit/pdfselection/extend(atstart:)","kind":"symbol","navigatorTitle":[{"text":"extendSelectionAtStart:","kind":"identifier"}],"abstract":[{"type":"text","text":"Extends the selection from its start toward the beginning of the document."}],"role":"symbol"},"doc://com.apple.pdfkit/documentation/PDFKit":{"role":"collection","identifier":"doc://com.apple.pdfkit/documentation/PDFKit","type":"topic","abstract":[{"type":"text","text":"Display and manipulate PDF documents in your apps."}],"kind":"symbol","title":"PDFKit","url":"/documentation/pdfkit"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFSelection":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PDFSelection"}],"title":"PDFSelection","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFSelection","type":"topic","url":"/documentation/pdfkit/pdfselection","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PDFSelection"}],"abstract":[{"type":"text","text":"A "},{"code":"PDFSelection","type":"codeVoice"},{"type":"text","text":" object identifies a contiguous or noncontiguous selection of text in a PDF document."}],"role":"symbol"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFSelection/add(_:)-8c2r":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PDFSelection","text":"PDFSelection"},{"text":")","kind":"text"}],"title":"add(_:)","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFSelection/add(_:)-8c2r","type":"topic","url":"/documentation/pdfkit/pdfselection/add(_:)-8c2r","kind":"symbol","navigatorTitle":[{"text":"addSelection:","kind":"identifier"}],"abstract":[{"type":"text","text":"Adds the specified selection to the receiving selection."}],"role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","url":"/documentation/technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"title":"Technologies","type":"topic"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFSelection/add(_:)-3fyld":{"url":"/documentation/pdfkit/pdfselection/add(_:)-3fyld","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"add"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PDFSelection","text":"PDFSelection"},{"kind":"text","text":"])"}],"navigatorTitle":[{"kind":"identifier","text":"addSelections:"}],"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFSelection/add(_:)-3fyld","abstract":[{"text":"Adds the specified array of selections to the receiving selection.","type":"text"}],"kind":"symbol","type":"topic","title":"add(_:)"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFSelection/extend(atEnd:)":{"url":"/documentation/pdfkit/pdfselection/extend(atend:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"extend"},{"kind":"text","text":"("},{"kind":"externalParam","text":"atEnd"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"extendSelectionAtEnd:"}],"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFSelection/extend(atEnd:)","abstract":[{"text":"Extends the selection from its end toward the end of the document.","type":"text"}],"kind":"symbol","type":"topic","title":"extend(atEnd:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"deprecated":false,"name":"iOS","introducedAt":"11.0","beta":false},{"unavailable":false,"deprecated":false,"name":"iPadOS","introducedAt":"11.0","beta":false},{"unavailable":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.1","beta":false},{"unavailable":false,"deprecated":false,"name":"macOS","introducedAt":"10.4","beta":false},{"unavailable":false,"deprecated":false,"name":"tvOS","introducedAt":"11.0","beta":false},{"unavailable":false,"introducedAt":"1.0","deprecated":false,"beta":false,"name":"visionOS"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"extendSelectionAtStart:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"extendSelectionAtStart:","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.pdfkit/documentation/PDFKit","doc://com.apple.pdfkit/documentation/PDFKit/PDFSelection"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/PDFSelection/add(_:)-8c2r","doc://com.apple.pdfkit/documentation/PDFKit/PDFSelection/add(_:)-3fyld","doc://com.apple.pdfkit/documentation/PDFKit/PDFSelection/extend(atEnd:)"],"title":"Modifying a Selection","anchor":"Modifying-a-Selection","generated":true}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"extendSelectionAtStart:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"precede","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"op":"replace","value":"extendSelectionAtStart:","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFSelection~1extend(atStart:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"extendSelectionAtStart:"}],"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFSelection~1extend(atStart:)/fragments"},{"op":"replace","value":"PDFSelection","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFSelection/title"},{"op":"replace","value":[{"kind":"identifier","text":"PDFSelection"}],"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFSelection/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"PDFSelection"}],"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFSelection/navigatorTitle"},{"op":"replace","value":"addSelection:","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFSelection~1add(_:)-8c2r/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addSelection:"}],"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFSelection~1add(_:)-8c2r/fragments"},{"op":"replace","value":"addSelections:","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFSelection~1add(_:)-3fyld/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addSelections:"}],"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFSelection~1add(_:)-3fyld/fragments"},{"op":"replace","value":"extendSelectionAtEnd:","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFSelection~1extend(atEnd:)/title"},{"path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFSelection~1extend(atEnd:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"extendSelectionAtEnd:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"diffAvailability":{"major":{"change":"modified","platform":"Xcode","versions":["16.0","16.3 beta 2"]}},"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}