{
  "abstract": [
    {
      "text": "Creates a text provider that shows the difference in time between the provided dates.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.clockkit/documentation/ClockKit",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateTextProvider"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateTextProvider/initWithDate:relativeToDate:style:units:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CLKRelativeDateTextProvider(im)initWithDate:relativeToDate:style:units:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "initWithDate:relativeToDate:style:units:"
      }
    ],
    "modules": [
      {
        "name": "ClockKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithDate:relativeToDate:style:units:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "initWithDate:relativeToDate:style:units:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "initWithDate:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSDate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSDate",
              "text": "NSDate"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "date"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "relativeToDate:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSDate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSDate",
              "text": "NSDate"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "relativeDate"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "style:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CLKRelativeDateStyle",
              "text": "CLKRelativeDateStyle"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "style"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "units:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@E@NSCalendarUnit",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSCalendarUnit",
              "text": "NSCalendarUnit"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "calendarUnits"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The starting date, used to calculate the relative date string.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "date"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The end date, used to calculate the relative date string.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "relativeDate"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The style to use when formatting the relative date value. For a list of possible values, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "style"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The units to include in the resulting date string. For a list of supported calendar units, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateTextProvider#Date-Format-Options",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "calendarUnits"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This initializer creates a text provider that produces a fixed, relative date. If you want a text provider that automatically updates as time passes, use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateTextProvider/init(date:style:units:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.clockkit/documentation/ClockKit": {
      "abstract": [
        {
          "text": "Display app-specific data on the clock face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClockKit",
      "type": "topic",
      "url": "/documentation/clockkit"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle": {
      "abstract": [
        {
          "text": "Constants indicating the formatting style for the relative date values.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKRelativeDateStyle"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKRelativeDateStyle"
        }
      ],
      "role": "symbol",
      "title": "CLKRelativeDateStyle",
      "type": "topic",
      "url": "/documentation/clockkit/clkrelativedatestyle"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateTextProvider": {
      "abstract": [
        {
          "text": "A formatted string that conveys the difference in time between the current date and a date that you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKRelativeDateTextProvider"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateTextProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKRelativeDateTextProvider"
        }
      ],
      "role": "symbol",
      "title": "CLKRelativeDateTextProvider",
      "type": "topic",
      "url": "/documentation/clockkit/clkrelativedatetextprovider"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateTextProvider#Date-Format-Options": {
      "abstract": [],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateTextProvider#Date-Format-Options",
      "kind": "section",
      "title": "Date Format Options",
      "type": "topic",
      "url": "/documentation/clockkit/clkrelativedatetextprovider#Date-Format-Options"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateTextProvider/init(date:relativeTo:style:units:)": {
      "abstract": [
        {
          "text": "Creates a text provider that shows the difference in time between the provided dates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "date"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "relativeTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "style"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLKRelativeDateStyle",
          "text": "CLKRelativeDateStyle"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "units"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCalendar",
          "text": "NSCalendar"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCalendarUnit",
          "text": "Unit"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateTextProvider/init(date:relativeTo:style:units:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textProviderWithDate:relativeToDate:style:units:"
        }
      ],
      "role": "symbol",
      "title": "init(date:relativeTo:style:units:)",
      "type": "topic",
      "url": "/documentation/clockkit/clkrelativedatetextprovider/init(date:relativeto:style:units:)"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateTextProvider/init(date:style:units:)": {
      "abstract": [
        {
          "text": "Creates a text provider that shows the difference between the current time and the specified date.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "date"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "style"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLKRelativeDateStyle",
          "text": "CLKRelativeDateStyle"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "units"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCalendar",
          "text": "NSCalendar"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCalendarUnit",
          "text": "Unit"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateTextProvider/init(date:style:units:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textProviderWithDate:style:units:"
        }
      ],
      "role": "symbol",
      "title": "init(date:style:units:)",
      "type": "topic",
      "url": "/documentation/clockkit/clkrelativedatetextprovider/init(date:style:units:)"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateTextProvider/initWithDate:relativeToDate:style:units:": {
      "abstract": [
        {
          "text": "Creates a text provider that shows the difference in time between the provided dates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithDate:relativeToDate:style:units:"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateTextProvider/initWithDate:relativeToDate:style:units:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDate:relativeToDate:style:units:"
        }
      ],
      "role": "symbol",
      "title": "initWithDate:relativeToDate:style:units:",
      "type": "topic",
      "url": "/documentation/clockkit/clkrelativedatetextprovider/initwithdate:relativetodate:style:units:"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateTextProvider/initWithDate:style:units:": {
      "abstract": [
        {
          "text": "Creates a text provider that shows the difference between the current time and the specified date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithDate:style:units:"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateTextProvider/initWithDate:style:units:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDate:style:units:"
        }
      ],
      "role": "symbol",
      "title": "initWithDate:style:units:",
      "type": "topic",
      "url": "/documentation/clockkit/clkrelativedatetextprovider/initwithdate:style:units:"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@E@NSCalendarUnit": {
      "abstract": [
        {
          "text": "Calendrical units such as year, month, day and hour. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "NSCalendar.Unit"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@E@NSCalendarUnit",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCalendar.Unit",
      "type": "topic",
      "url": "/documentation/foundation/nscalendar/unit"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSDate": {
      "abstract": [
        {
          "text": "A representation of a specific point in time, for use when you need reference semantics or other Foundation-specific behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSDate"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSDate",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDate",
      "type": "topic",
      "url": "/documentation/foundation/nsdate"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Text-Provider",
      "generated": true,
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateTextProvider/init(date:style:units:)",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateTextProvider/initWithDate:style:units:",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKRelativeDateTextProvider/init(date:relativeTo:style:units:)"
      ],
      "title": "Creating a Text Provider"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKRelativeDateTextProvider~1init(date:relativeTo:style:units:)/title",
          "value": "textProviderWithDate:relativeToDate:style:units:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKRelativeDateTextProvider~1init(date:relativeTo:style:units:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "textProviderWithDate:relativeToDate:style:units:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKRelativeDateTextProvider~1init(date:style:units:)/title",
          "value": "textProviderWithDate:style:units:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKRelativeDateTextProvider~1init(date:style:units:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "textProviderWithDate:style:units:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKRelativeDateTextProvider/title",
          "value": "CLKRelativeDateTextProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKRelativeDateTextProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKRelativeDateTextProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKRelativeDateTextProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKRelativeDateTextProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSDate/abstract",
          "value": [
            {
              "text": "A representation of a specific point in time, independent of any calendar or time zone.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKRelativeDateStyle/title",
          "value": "CLKRelativeDateStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKRelativeDateStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKRelativeDateStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKRelativeDateStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKRelativeDateStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/clockkit/clkrelativedatetextprovider/initwithdate:relativetodate:style:units:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
